### ISSUE TITLE
In small viewport the hamburgermenu button active state forces button below search field

### ISSUE THREAD

**Issue by VolleMelk** [dso-toolkit/dso-toolkit#10]
De menu balk is geïntegreerd in het ontwikkelaarsportaal maar werkt niet [netjes] op mobile devices.
* Op een laptop wordt de standaard menu layout netjes getoond en werkt naar behoren.
* Op een mobile device wordt de hamburger getoond, maar op de hamburger tikken/klikken laat de hamburger icon een stuk zakken.

/Original reporter: Marcel Dullaart

**Comment by legolas** [comment]
Behalve dat de hamburger naar beneden zakt klapt deze ook niet open.
Daat laatste is wel het belangrijkste.

**Comment by VolleMelk** [comment]
@legolas: Zoals aangegeven in mijn mail van 9 feb (om 16:41), kan ik dat niet voor je fixen. Het open/dichtklappen van het menu wordt door collapse.js gedaan.

Helaas is er een dependency genomen op collapse.js in de stijlgids. Vanaf versie 1.2.0 is de stijlgids 100% framework agnostisch en schrijft de stijlgids enkel en alleen de markup voor.

Jouw applicatie is geschreven in Angular. Je zou naar de originele Bootstrap collapse.js kunnen kijken. [ng-bootstrap](https://ng-bootstrap.github.io/#/home) heeft een [collapse](https://ng-bootstrap.github.io/#/components/collapse/examples) component. Of je kan zelf een Angular component maken.

De scope van deze issue blijft beperkt tot styling.
