### ISSUE TITLE
Kan de toolkit worden vrijgegeven onder de EUPL licentie?

### ISSUE THREAD

**Issue by EdoPlantinga** [dso-toolkit/dso-toolkit#1000]
Hoi DSO-toolkit team, 

We kijken vanuit [Common Ground](https://commonground.nl/) met interesse naar jullie webcomponents ontwikkelingen, die goed in lijn lijken te zijn met de richting die [NL Design System](nldesignsystem.nl/) opgaat. We hebben zelf ons eigen [Common Ground design system](https://github.com/VNG-Realisatie/common-ground-design-system), dat onder de EUPL licentie beschikbaar is. We zouden graag kijken of (delen van) jullie code voor ons herbruikbaar zijn. Zou het mogelijk zijn om ook de toolkit vrij te geven onder de EUPL licentie? 
Mocht ik kunnen helpen bij deze beslissing, dan doe ik dat graag. Ik heb overleg gehad met de landsadvocaat over de licentiekeuze van CoronaMelder en ik deel graag onze ervaringen op dat gebied. Zie ook dit document op Github over de [motivatie van de licentiekeuze voor CoronaMelder](https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE-considerations.md).

**Comment by sgort** [comment]
GPLv3 mag ook ;-)

**Comment by tfrijsewijk** [comment]
Hi @EdoPlantinga en @sgort!

Dit onderwerp staat al een tijdje op onze agenda.. We zullen het morgen weer bij de betreffende stakeholders onder de aandacht brengen.

We houden jullie op de hoogte.

Trouwens, dit issue is nummertje 1000... Wat een mijlpaal. Zou leuk zijn als we nummer 1000 kunnen afronden met een echte licentie :-)

**Comment by EdoPlantinga** [comment]
Ik kwam net dit [artikel over open source](https://opensource.pleio.nl/news/view/a323e3fe-eb40-44fa-b19f-6c2cf4791cb1/ctociso-sandor-de-coninck-van-rijkswaterstaat-ik-geloof-in-open-platforms) van de CTO / CISO van Rijkswaterstaat. Wellicht helpt dat?

**Comment by tfrijsewijk** [comment]
Het is zeker een argument.. We nemen 'm mee

**Comment by gofix** [comment]
Na uitgebreid onderzoek naar mogelijke licenties, oa. door te kijken naar https://opensource.pleio.nl/file/download/6f4791bd-e12c-4556-aa94-ab544d639f2c/1.Handleiding%20BZK%20delen%20en%20gebruik%20van%20overheidssoftware.pdf (Delen en hergebruik van overheidssoftware, een stuk dat in opdracht van Ministerie van Binnenlandse Zaken en Koninkrijksrelaties is geschreven), ligt nu de uiteindelijke beslissing over welke vorm van licentie gevoerd gaat worden, en met welke aanvullende voorwaarden, bij de eigenaar van het programma DSO. Als hier tzt. uitspraak over komt zal dit worden doorgevoerd in deze repository.

Tot die tijd sluiten we nu dit issue.
