### ISSUE TITLE
Anchor styling aanpassingen voor componenten met gekleurde achtergrond

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#1009]
Voor alle componenten met een gekleurde achtegrond moet de volgende styling aangehouden worden. 

- Links zijn altijd in het zwart (ook bij hover en visited)
- Underline verdwijnt op hover, active en focus

Component specifiek: 

**Alert:**
- Visited states zwart maken
- Underline op hover,active en focus verwijderen
- Webcomponent variant wijkt af van CSS variant (Op hover verandert de kleur naar blauw->zwart maken)

**Banner**
- Underline op hover,active en focus verwijderen

**Highlightbox + Info** 
- Underline op hover, active en focus verwijderen

**Comment by gofix** [comment]
Ik denk dat dit goed is zo, jij ook @MichielDHVD, zie voor test-urls de PR https://github.com/dso-toolkit/dso-toolkit/pull/1013

**Comment by MichielDHVD** [comment]
Prima, doorzetten die handel.
