### ISSUE TITLE
Favicon updaten en meer formaten toevoegen

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#1010]
Het huidige favicon is sterk verouderd en wordt in beperkt formaat geleverd. Favicon is aangepast aan het logo (grootte van cirkels aangepast). Met behulp van https://realfavicongenerator.net/ is de volledige set iconen gegenereerd voor implementatie.

Bestanden:
[favicon_package_v0.16.zip](https://github.com/dso-toolkit/dso-toolkit/files/5972757/favicon_package_v0.16.zip)

![Schermafbeelding 2021-02-12 om 16 34 13](https://user-images.githubusercontent.com/598735/107788330-946e4d00-6d50-11eb-9437-beec83b2e120.png)

**Comment by daverhelst** [comment]
Zoals besproken met @bramhoosemans gaan we de huidige opzet loslaten. Een tabel met alle formaten wordt te gortig en biedt niks toe voor de implementatoren die de favicon moeten inzetten.

Er is besloten om de .zip file aan te bieden op deze favicon pagina in de toolkit en de daarbij bijbehorende installatie instructie  te tonen.

**Comment by daverhelst** [comment]
@bramhoosemans zou jij kunnen kijken of dit klopt qua woordgebruik, of het compleet is, en of er iets anders zou moeten?
https://dso-toolkit.nl/_1010.Favicon-updaten/docs/fundament/favicon.html

**Comment by gofix** [comment]
@bramhoosemans zie https://dso-toolkit.nl/_1010.Favicon-updaten/docs/fundament/favicon.html

@daverhelst Hoezo is dit [BREAKING]?

**Comment by daverhelst** [comment]
@gofix Volgens mij schrijven we voor het eerst een manier aan om de favicon in te stellen. Daarnaast zal een implementator het favicon bestand moeten aanpassen, aangezien deze opnieuw is ontworpen.

**Comment by bramhoosemans** [comment]
Ziet er goed uit 👍
