### ISSUE TITLE
Structuur voorbeeldpagina's aanbrengen. 

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#1016]
Op dit moment voelen de verschillende pagina's nog een mengelmoes. De onderline pagina's willen qua functie ook nog eens flink verschillen. 

Afgelopen Donderdag is er nog gesproken over indelingen betreffende voorbeeldpagina's. 

Een mogelijke optie is: 

Praktijk voorbeelden (Andere naam mogelijk wenselijk) 
Patronen
Extreme situaties

Voorstellen voor een andere indeling mogen gedaan worden.

**Comment by bramhoosemans** [comment]
Volgens mij hebben we dezelfde gedachte wat betreft indeling, alleen iets andere naamgeving:

**Voorbeelden**
- Patronen
    - Formulieren
    - Meldingenstrategie
        - Inline validatie
    - Zoeksuggesties
    - Header
    - Footer
- Toepassingen
    - Vergunningcheck
    - Maatregelen op maat
    - Aanvragen
    - Mijn Omgevingsloket
    - Regels op de kaart
    - Stelselcatalogus
    - Samenwerken
    - Beheerportaal
- Componenten
    - Buttons
    - …

**Comment by MichielDHVD** [comment]
**Voorbeelden**
- Patronen
    - Accordion table (Verwijderen?)
    - Beheer basis
    - Footer
    - Formulieren
    - Header
    - Info button + Info (of is dit in het formulier al genoeg?)
    - Meldingenstrategie
        - Pagina met banner
        - Alerts
        - Inline validatie
        - Modals
    - Zoeken in lijst met cards
    - Zoeksuggesties
- Toepassingen
    - Vergunningcheck
       - Wizard stap 1 
       - Wizard stap 2
       - Wizard stap 3 
       - Wizard stap 4
    - Maatregelen op maat (wizard verdubbelen denk het niet toch?) 
    - Aanvragen
       - Aanvragen (betere titel is nodig)
       - Aanvragen file upload (dito)
       - Stap 7 (komt eraan. Willen we van stap 6 de verschillende pagina's gaan toevoegen?) 
    - Mijn Omgevingsloket
    - Regels op de kaart
    - Stelselcatalogus
    - Samenwerken
       - Actieverzoeken
       - Overzicht samenwerkingen
    - Beheerportaal
    - Homepage
    - Landingspagina
    - 404 pagina
- Componenten
    - Buttons
    - Link
    - Full width
    - Layout
    - Row equal height
    - Dso rich content (is een vraag?) 
    
    
Het staat nog niet allemaal netjes op alfabetische volgorde. Maar dit is mijn eerste inzicht. 
Deze indeling creëert bij mij wel de behoefte om in de toekomst pagina's toe te voegen zodat we meer visuele controle krijgen over het gehele loket.

**Comment by PieterVerheij** [comment]
Voor Wizard stap 2 (Locatie) is een horizontale plaatsing van form-groups en dso-form-buttons gemaakt:

Zien jullie dit ook als een patroon? 
![image](https://user-images.githubusercontent.com/25430835/109820711-8ae05280-7c35-11eb-866b-9fe3b5e96ca5.png)

**Comment by bramhoosemans** [comment]
> Zien jullie dit ook als een patroon?

Dat denk ik wel; horizontale en verticale formulieren.

**Comment by tfrijsewijk** [comment]
Ik begrijp de indeling niet.

> **Voorbeelden**
> 
> * Patronen **_Betekent dit dat "Patronen" onder "Voorbeelden komt"?_**
>   
>   * Accordion table (Verwijderen? > ja, als het enkel een voorbeeld is. Anders depecaten in apart issue) **_Dit is alleen een voorbeeld, er is geen CSS voor_**
>   * Beheer basis
>   * Footer
>   * Formulieren **_Is dit het component "Form" wat nu in onder "Componenten" staat? https://dso-toolkit.nl/21.1.0/components/detail/form.html_**
>     
>     * Horizontaal formulier
>     * Verticaal formulier
>   * Header
>   * Layout
>   * Meldingenstrategie **_Dit is een documentatie file (.md)_**
>     
>     * Pagina met banner **_Zijn dit 4 componenten die onder "Componenten" staan?_**
>     * Alerts
>     * Inline validatie
>     * Modals
>   * Zoeken in lijst met cards (@MichielDHVD is dit een ‘echt’ voorbeeld?) **_Vraagteken?_**
>   * Zoeksuggesties **_Dit is een documentatie file (.md)_**
> * Toepassingen **_Betekent dit dat "Toepassingen" onder "Voorbeelden komt"?_**
>   
>   * Aanvragen
>     
>     * Landingspagina
>     * Wizard stap 1 > Project **_Wat betekent `>` ?_**
>     * Wizard stap 2 > Locatie
>     * Wizard stap 3 > Activiteiten
>     * Aanvragen > Vragen
>     * Aanvragen file upload > Documenten
>     * Verzoeken (verwijderen) **_Wat betekent `(verwijderen)` en waarom staat ie dan onder "Aanvragen" ?_**
>     * Verzoeken Wijzigen (verwijderen)
>     * Verzoeken Wijzigen Bevoegd Gezag > Verzoeken
>     * Omgevingsoverleg
>     * Verzoeken Indienen
>   * Samenwerken
>     
>     * Actieverzoeken
>     * Samenwerken > Overzicht samenwerkingen
>   * Vergunningcheck
>     
>     * Wizard stap 4 > Resultaat
>   * Homepage
>   * 404 pagina
> * Componenten **_Het kan niet de bedoeling zijn dat "Componenten" onder "Voorbeelden" komt, maar toch staan "Componenten", "Toepassingen" en "Patronen" naast elkaar_**
>   
>   * Buttons
>   * Links
>   * Full width (?) **_Vraagteken?_**
>   * Layout (?)
>   * Row equal height (?)
> 

Zie bovenstaande **_opmerkingen_**. Daarnaast:
* In Fractal zijn Component (.njk) en Documentatie (.md) concepten die niet te mixen zijn: Ze kunnen niet door elkaar in de boom gebruikt worden.
* Graag een uitgebreidere en specifiekere indeling aanleveren

**Comment by bramhoosemans** [comment]
> Betekent dit dat "Patronen" onder "Voorbeelden komt"?

Ja, onder "Voorbeelden" komen de volgende onderdelen: Patronen, Toepassingen en Componenten. "Componenten" bevat voorbeeldpagina's met extreme varianten van een component, zoals buttons met hele lange labels.

> Accordion table (Verwijderen? > ja, als het enkel een voorbeeld is. Anders depecaten in apart issue) Dit is alleen een voorbeeld, er is geen CSS voor

Mooi, dan mag die worden verwijderd.

> Formulieren Is dit het component "Form" wat nu in onder "Componenten" staat? https://dso-toolkit.nl/21.1.0/components/detail/form.html

Zo zag ik dat eerst wel. Al ben ik nu tot het inzicht gekomen dat het mogelijk twee verschillende dingen zijn. Het patroon laat de verschillende situaties / gebruik van het component "formulier" zien. Denk aan simpele formulieren, formulieren met meerdere stappen of in een modal.

> Meldingenstrategie Dit is een documentatie file (.md)

En dus niet te combineren met voorbeelden (.njk) en (.md). Helder; dan zullen we die onder documentatie moeten houden.

> Pagina met banner Zijn dit 4 componenten die onder "Componenten" staan?

Nee, het idee was om voor alle type meldingen een voorbeeld op te nemen. Zoals de huidige https://dso-toolkit.nl/21.1.0/components/detail/pagina-met-banner.html

> Zoeken in lijst met cards (@MichielDHVD is dit een ‘echt’ voorbeeld?) Vraagteken?

Bevestiging van Michiel; het is geen echt voorbeeld. Deze opzet is een voorbode van de layout vanuit de Viewer.

> Zoeksuggesties Dit is een documentatie file (.md)

Oké, wordt net als de meldingenstrategie ondergebracht in documentatie.

>  Toepassingen Betekent dit dat "Toepassingen" onder "Voorbeelden komt"?

Ja.

>  Wizard stap 1 > Project Wat betekent > ?

Naam “Wizard stap 1” veranderen in “Project”.

>  Verzoeken (verwijderen) Wat betekent (verwijderen) en waarom staat ie dan onder "Aanvragen" ?

Naar mijn mening kunnen we deze voorbeeldpagina’s verwijderen, omdat ze dubbel zijn met de huidige “Verzoeken Wijzigen Bevoegd Gezag”.

>  Componenten Het kan niet de bedoeling zijn dat "Componenten" onder "Voorbeelden" komt, maar toch staan "Componenten", "Toepassingen" en "Patronen" naast elkaar

Wat @gofix zegt. Onder voorbeelden willen we de extreme varianten van componenten opnemen zodat de component pagina’s zelf een stuk eenvoudiger worden.

>  Full width (?) Vraagteken?

Ik vraag me af of ‘Full width, Layout en Row equal height’ wel een aparte voorbeeldpagina moeten zijn. En waar deze onder te brengen. Dit is toch onderdeel van de desbetreffende voorbeelden, zoals homepage en landingspagina’s.

**Comment by bramhoosemans** [comment]
Hierbij een aangepast voorstel mbt indeling in de DSO Toolkit. Beperkt tot de huidige set voorbeeldpagina's.

**Voorbeelden**

* Patronen
    * Beheer basis
    * Footer
    * Full width
    * Header
    * Layout
    * Pagina met banner
    * Row equal height
    * Zoeken in lijst met cards
* Toepassingen
    * Aanvragen
        * Landingspagina
        * Wizard stap 1 > Project
        * Wizard stap 2 > Locatie
        * Wizard stap 3 > Activiteiten
        * Aanvragen > Vragen
        * Aanvragen file upload > Documenten
        * Verzoeken Wijzigen Bevoegd Gezag > Verzoeken
        * Omgevingsoverleg
        * Verzoeken Indienen
    * Samenwerken
        * Actieverzoeken
        * Samenwerken > Overzicht samenwerkingen
    * Vergunningcheck
        * Wizard stap 4 > Resultaat
    * Homepage
    * 404 pagina
* Componenten
    * Link


Te verwijderen voorbeelden:

- Accordion table
- Verzoeken
- Verzoeken Wijzigen

**Comment by gofix** [comment]
NB. over Voorbeelden / Patronen / Layout:
We hebben ook Fundament / Layout, en op dit moment is dat dan ook volstrekt dubbele/indentieke informatie:
- packages\dso-toolkit\docs\20-Fundament\04-layout.md
- packages\dso-toolkit\components\Voorbeelden\layout\layout.njk

In https://github.com/dso-toolkit/dso-toolkit/issues/977 passen we deze beschrijving aan, en volgens mij hadden we afgesproken dat alleen in "Fundament" te doen, en vooralsnog "Voorbeelden" te ontdoen van deze pagina. Voorbeelden van lay-out zijn immers al veelvuldig aanwezig in de ... jawel ... voorbeelden!

**Comment by bramhoosemans** [comment]
> In #977 passen we deze beschrijving aan, en volgens mij hadden we afgesproken dat alleen in "Fundament" te doen, en vooralsnog "Voorbeelden" te ontdoen van deze pagina.

Klopt helemaal. Ik stel voor het huidige voorbeeld van de layout te verwijderen; het overzicht is bijgewerkt.

**Comment by gofix** [comment]
Bij nader inzien en in overleg met @MichielDHVD heb ik deze toch laten bestaan, en daar alleen het markup voorbeeld in laten staan, en een verwijzing naar de fundament-documentatie.
