### ISSUE TITLE
Maps - Buttons

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#1021]
Acties op de kaart.

Deze zijn onder te verdelen in twee typen; zoom controls en buttons. Beide hebben een vergelijkbare visuele styling. Nog verder uit te werken:
- Worden buttons automatisch gestyled als ze in de context van de kaart worden geplaatst?
- Gaan we een modifier toevoegen om de buttons te stylen?

Het idee is dat naast het (gewijzigde) component er óók een voorbeeld implementatie van Leaflet is opgenomen in de toolkit. 

Specificaties: [map-buttons.zip](https://github.com/dso-toolkit/dso-toolkit/files/6048821/map-buttons.zip)

![map-buttons](https://user-images.githubusercontent.com/598735/109285543-8248e000-7821-11eb-9711-648415e2e327.png)

**Comment by tfrijsewijk** [comment]
In overleg met Bram mag deze 'n release opschuiven. Ik heb een aanname gedaan hoe een button op de kaart gezet gaat worden (Custom Control, zie https://github.com/dso-toolkit/dso-toolkit/blob/3fbe24356ef9bd69ce38f1ad1d75c9dc15d25f2b/packages/leaflet/public/index.ts#L9) maar de styling voor een button leeft nog in `dso-toolkit`. In het Web Component "Map Controls" is al gesmokkeld met het stijlen van de knoppen. Dat is hier niet mogelijk, omdat er geen Shadow DOM is.

In #856 zal de smokkelstyling uit het Map Controls component worden aangepakt, de knop in de leaflet kaart worden gestijld (en natuurlijk alle bijbehorende button stijling worden overgezet).
