### ISSUE TITLE
Maps - MapControls

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#1022]
Kaartlagen 'side-panel'.

- Gaan we hier een specifiek 'kaart component' voor maken of een algemeen 'side-panel' dan op de kaart gebruikt wordt?

Het idee is dat naast het (gewijzigde) component er óók een voorbeeld implementatie van Leaflet is opgenomen in de toolkit.

Specificaties: [side-panel.zip](https://github.com/dso-toolkit/dso-toolkit/files/6048861/side-panel.zip)

![side-panel](https://user-images.githubusercontent.com/598735/109286660-d56f6280-7822-11eb-94e7-70e3d2e862eb.png)

**Comment by tfrijsewijk** [comment]
@bramhoosemans Met pijn in mijn hart moet ik deze nog 'n release opschuiven.. Ik heb er te weinig tijd voor vrijgemaakt :-(

**Comment by tfrijsewijk** [comment]
Gepubliceerd naar NPM: `@dso-toolkit/leaflet` en `@dso-toolkit/react-leaflet` 🚀
