### ISSUE TITLE
Scheidingslijnen styling consistent

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#1024]
### Aanleiding
Er zijn op dit moment veel verschillende scheidingslijnen met allemaal verschillende kleuren. Deze story maakt dat consistent.

### Werkzaamheden
Voor de volgende onderdelen moet de styling omgezet worden naar 1px #CCC

hr
Cards
Footnotes
Form Steps
Modal
Panel (Valt deze wel hieronder?)
definitionlist + definition list (wordt getriggered wanneer er opvolgende definition lists zijn) 
Rich Content hr
Table
Lijst met componenten waar scheidingslijn reeds 1px #CCC is:
Form Fieldset
Navigations
Shoppingcart

### Ontwerp
![image](https://user-images.githubusercontent.com/36912722/113303912-d3a52d00-9301-11eb-8124-8c846adc1b54.png)

### Testen
Welke test stappen moeten uitgevoerd worden om te controleren of het component correct is gebouwd

Visuele controle
Voorbeeldpagina's nalopen kijken of er onwenselijke veranderingen zijn

**Comment by gofix** [comment]
@bramhoosemans kun jij testen? Aan https://percy.io/dso-toolkit/dso-toolkit/builds/9711309/changed/547543331?browser=chrome&browser_ids=16&subcategories=approved&viewLayout=side-by-side&viewMode=new&width=1280&widths=380%2C780%2C1024%2C1280 is duidelijk te zien wat er is 'geraakt'.

**Comment by bramhoosemans** [comment]
Ziet er goed uit! (wel veel onnodige hr's tussen component previews, maar dat pakken we nu niet op.)
