### ISSUE TITLE
Margin onder tabs

### ISSUE THREAD

**Issue by PieterVerheij** [dso-toolkit/dso-toolkit#1027]
De margin onder het tabs-component moet 32px worden.
0px
![image](https://user-images.githubusercontent.com/25430835/109520776-e03d2800-7aac-11eb-9516-9a05c3449c7d.png)
32px
![image](https://user-images.githubusercontent.com/25430835/109520857-f4812500-7aac-11eb-8f6f-702954d873b0.png)

**Comment by PieterVerheij** [comment]
@bramhoosemans of 16px?
![image](https://user-images.githubusercontent.com/25430835/109520974-14b0e400-7aad-11eb-92cd-f4ce94a6a0b1.png)

**Comment by bramhoosemans** [comment]
@PieterVerheij Ik heb het even met Michiel besproken. Laten we voor nu 24px magin-bottom toevoegen.

Met als side-note: we hebben momenteel geen duidelijk 'systeem' wat marges betreft. Dit zullen we in de toekomst moeten vaststellen, zodat ook het schalen van resonsive layouts makkelijker wordt.

**Comment by PieterVerheij** [comment]
Ik was eigenlijk als van een opzetje met 8px-16px-24px uitgegaan ;)

**Comment by PieterVerheij** [comment]
https://www.dso-toolkit.nl/_1027.Margin-onder-tabs/components/detail/tabs.html

**Comment by PieterVerheij** [comment]
variabele nog omnoemen naar $dso-vertical-spacing-bla

**Comment by gofix** [comment]
Gedaan -> `$dso-vertical-spacing-large` (= `$u3`, = `$dso-unit * 3` = `24px` dus :))

**Comment by gofix** [comment]
Resultaat ziet er goed uit, zoals verwacht:
![image](https://user-images.githubusercontent.com/2689559/110201492-a6c93b80-7e63-11eb-8642-5854aa5c1b17.png)
