### ISSUE TITLE
Label component

### ISSUE THREAD

**Issue by DjangoBlok** [dso-toolkit/dso-toolkit#103]
I would like to have a component showing a selected filter (like "verbouwen" in the sample screenshot).
This component has the option to delete the filter (by clicking on the cross)
Is this a variant of the label component, or something new?
I am open to discussion about the colors. 
![ovrek-345 geselecteerd filter](https://user-images.githubusercontent.com/34900082/38550669-6ff3ab68-3cb7-11e8-8b13-5023f4389cfc.png)

**Comment by VolleMelk** [comment]
Lijkt mij inderdaad een variant/uitbreiding op het label component.

Maar de labels die er nu zijn lijken niet op het label wat jij in je screenshot hebt.. Misschien moeten we eerst de labels wat strakker trekken.

Inhoudelijk over de label met een delete:
* Er zit aanzienlijke ruimte tussen de tekst en het kruis, waarom? Is het label een fixed width of zit deze ruimte altijd tussen de tekst en het kruis?
* Wat zijn de hover/active/focus states?
* Wat gebeurt er met langere termen in een label met kruis?

**Comment by MichielDHVD** [comment]
Dit wordt denk ik een algemene aanpassing voor de labels. En we zullen even goed moeten zoeken naar een vorm die werkt voor het DSO. 

Want momenteel komt het default label(Grijs) niet door de wcag check heen. 

Heb jij hier al states voor gemaakt  @DjangoBlok ? 

Plus ik zal morgen even wat afbeeldingen maken zodat je kan zien wat er gebeurt als deze labels zo worden doorgevoerd en waar dit allemaal implicatie op heeft. 

Ik voeg even deze link toe dan kan het realtime bekeken worden. 
https://pre.omgevingswet.overheid.nl/content/orienteren

**Comment by DjangoBlok** [comment]
- De ruimte tussen tekst en kruis hoort inderdaad niet zo groot te zijn.
- Ik heb nog geen states gemaakt, maar kan dat wel even doen.
- Wellicht een maximum labellengte die wordt afgebroken met puntjes. (optioneel)
- Dit kan nog niet realtime bekeken worden, want zit er nog niet in (alleen in mijn ontwerp)

**Comment by DjangoBlok** [comment]
Hier een uitgewerkt voorstel (WCAG proof):
![ovrek-345_geselecteerd_filter](https://user-images.githubusercontent.com/34900082/38558508-ab4ecf12-3cd0-11e8-899a-c7466be32454.png)

**Comment by DjangoBlok** [comment]
Klopt wat dat betreft is dit echt wel een ander component dan een label.
Ik ben van mening dat een klik naast het kruisje verder niks moet doen in dit geval. (niet verwijderen en geen nieuwe zoekactie)

**Comment by VolleMelk** [comment]
Dan begrijp ik de hover state nog niet helemaal uit je vorige ontwerp. Wanneer wordt het label lichtgroen en wanneer wordt het kruisje rood?

Wat is de maatvoering van het blokje? Ruimte tussen tekst en knop, rand label tot inhoud?

**Comment by MichielDHVD** [comment]
Hier is mijn voorstel voor een kleuren samenstelling van de filters. 
Als basis gebruik ik de lime kleur 20% #E4F1D4 . Deze wordt namelijk ook gebruikt voor de succes-alert. Zorgt weer voor extra consistentie. 

Ik heb een versie waar de text de standaard is en text in bosgroen beide halen de wcag check. 
Verder heb ik even margins toegevoegd die voldoen aan het 8px grid en overeenkomen met het ontwerp van Django. 

![filter labels](https://user-images.githubusercontent.com/36912722/38617979-a5fb8618-3d98-11e8-9ba6-e665e0f8549a.png)

![filter labels in context](https://user-images.githubusercontent.com/36912722/38617978-a5e0b75c-3d98-11e8-8116-47c7d973319e.png)

Verder is het nu kijken welke kleuren combinatie we gaan gebruiken uiteindelijk.

**Comment by DjangoBlok** [comment]
Die lime 20% zag ik niet in de stijlgids, zou je die dan ook als kleur kunnen toevoegen?
Zijn die bovenste de up states en die onderste de over states?
Een paar kleine opmerkingen:
- In de basis ben ik wel voor de derde versie (background: lime 20%, font: )
- Wat mij betreft hoeven die over states niet (zo heel erg) te verschillen van de up states. Dat zou suggereren dat het om klikbare elementen gaat terwijl het element eigenlijk helemaal niet klikbaar is. Van mij mag vooral het kruisje op een of andere manier oplichten bij een mouse over. (zie mijn voorstel)
- De horizontale marges van 16 pixels vind ik wat veel, zou je daar niet beter 8 van kunnen maken?
- Ook de verticale marges zouden wat mij betreft van 8 naar 4 mogen
- Er kunnen meerder van deze elementen naast elkaar komen. We moeten definiëren wat de marge is tussen twee opeenvolgende items. (16 px?) 
![ovrek-345_geselecteerd_filter_v2](https://user-images.githubusercontent.com/34900082/38666010-342a4e92-3e3e-11e8-8e0b-408ddd728504.png)

**Comment by VolleMelk** [comment]
Ik vind de iets compactere variant met 4px ook net wat strakker

**Comment by Poofy83** [comment]
Als ruimte tussen 2 elementen stel ik 8px voor horizontaal en 4px verticaal (mochten elementen onder elkaar komen te vallen)

**Comment by MichielDHVD** [comment]
Ik heb even wat extra's toegevoegd aan dit component. Namelijk een normal-state en dit even contextueel binnen een ontwerp gezet. @DjangoBlok @VolleMelk @Poofy83 

Want de extra normal state kan er voor zorgen dat het label voor meer elementen gebruikt kan worden. Ook hebben ik een large state gemaakt. Deze is groter dan wat Django voorstelde, om te kijken hoe het dan in de context valt. 

Grootte labels. 
![filter labels plus xl](https://user-images.githubusercontent.com/36912722/39180168-76d78abc-47b6-11e8-895c-2aa8fed9abe4.png)

![filters binnen api-register](https://user-images.githubusercontent.com/36912722/39180182-7e93394a-47b6-11e8-9970-7b6352092a6d.png)

![filters-binnen api register groot](https://user-images.githubusercontent.com/36912722/39180183-7eb337e0-47b6-11e8-9741-df9f49bee467.png)


Ik maak ook even een opsomming van wat er tot nu toe is beslist en wat al vast gezet kan worden. Om het overzichtelijk te houden. 

**Vastgezet**

Dit onderdeel is niet hetzelfde als het Label onderdeel in de toolkit, het krijgt dus zijn eigen kopje.

De normale versie heeft: 
font-size: 16px
margins-top-bottom: 4px 
margins-right-left: 8px 
active-state: 20% lime.

**Comment by DjangoBlok** [comment]
@MichielDHVD ik ben de draad even kwijt in je voorstel. Lijkt een heel ander component. 
- Vanwaar die schuifjes?
Jij hebt er een soort labels van gemaakt die je aan en uit kan zetten. Klopt dat?
Voor mij ging het om weergeven van een elders geselecteerd filter.
- Je beschrijft normale versie, maar in je uitwerking is het de Large versie. 
- De 'normale' lijkt niet te zijn gespecificeerd.
- Welke is nou de default? (Ik kan zelf niet zo veel met die grote)

**Comment by MichielDHVD** [comment]
Ik snap je verwarring. Iets meer toelichting was handig geweest. 

Al deze aanpassingen zijn een exploratie om te kijken of dit component in andere contexten ook werkt. Om te voorkomen dat dit onderdeel single use wordt en geen overeenkomsten met mogelijk andere toekomstige filters in de toolkit. 

Daarom had ik wat toevoegingen gedaan. 

- De schuifjes; Dit zijn Font-awesome schuifjes en waren bedoeld om aan te geven dat waar het kruisje staat ook andere symbolen kunnen komen. Dus soms schuifjes, soms kruisjes misschien nog wat anders. 

- de Normal/Default volgens mij hetzelfde. Is wat jij als Large omschreef in je eerdere post. 
Font-size: 16px
Margins-top-bottom: 4px;
Margins-left-right: 8px; 

Maar als deze structuur verwarrend is / of het component onnodig complex . 
Dan stel ik voor om het gewoon zo simpel mogelijk te houden. En dit component alleen te gebruiken binnen de definitie van Django. 

Als dat besloten is kunnen we het ontwerp definitief maken.

**Comment by Poofy83** [comment]
De schuifjes maken het een en ander wel complexer, ik zie namelijk 2 schuifjes:

- actief
- inactief

Dit betekent dat er een "state" bijgehouden moet worden. In het geval van een sluitkruis is dat niet het geval.

**Comment by MichielDHVD** [comment]
Om even een opsomming te maken en een visual erbij. 

De waardes van het component als @DjangoBlok het er mee eens is. 

![filters-final](https://user-images.githubusercontent.com/36912722/39418385-6fe60e6a-4c5a-11e8-8bf0-517b4cc21a32.png)

**Comment by MichielDHVD** [comment]
@DjangoBlok  heb gister even overleg gehad bij een sprint review en toen over deze werkvorm besloten. 

![filters- sidebutton](https://user-images.githubusercontent.com/36912722/39508317-55160a3e-4de2-11e8-8968-9d2b004ae13c.png)

Margins zijn nog steeds top bottom 4px ; links rechts 8px;

**Comment by Poofy83** [comment]
@MichielDHVD Bedankt voor het ontwerp, maar ik zie hier een kleine inconsistentie. In de normal state staat er een halve border links van het kruis, dit is lastig te fabriceren aangezien de knop (met kruis) helemaal van boven tot onder loopt. Ik stel voor om deze lijn door te trekken, of eventueel zelfs weg te halen zodat alleen de hover op knop een verschil laat zien.

**Comment by MichielDHVD** [comment]
Dan stel ik voor het helemaal door te trekken.

**Comment by Poofy83** [comment]
@MichielDHVD Nog een kleine vraag, wordt dit een aanpassing op het label component of een geheel eigen filter label component? Ik heb even terug gelezen, maar hier is nog geen duidelijk antwoord op gegeven.

**Comment by MichielDHVD** [comment]
Dit wordt een geheel eigen filter label component. 
In de toolkit zou het fijn zijn als deze onder het een subkopje viewer zou komen. 

ps. Het huidige label component zullen vrij snel aanpassingen komen.

**Comment by VolleMelk** [comment]
Dat dit een eigen component wordt zou ik nog ter discussie willen stellen.

Een label is een label. Een verwijderbaar label is een variant op het oorspronkelijke label component. Dat een (verwijderbaar) label component in de context van de viewer wordt gebruikt, daar heeft de DSO Toolkit niet zoveel mee te maken.

Ik stel het volgende voor:
* Het huidige labelcomponent (https://www.dso-toolkit.nl/2.0.0-alpha.0/components/detail/label.html) dient als basis
* Dit label wordt visueel gelijk getrokken met bovenstaand ontwerp
* Er wordt een button variant aangeboden

Ik zie het al aankomen dat wij nu een 'filter-label' gaan maken en dat over een paar maanden het verzoek komt om het label-component visueel gelijk te trekken met filter-label, maar dan zonder de knop.

Vervolgens hebben we visueel identieke werkvormen die in de code op twee plekken wordt onderhouden.

Door het 'filter-label' component in een Viewer categorie te plaatsen lijkt het alsof de label alleen in de context van een viewer gebruikt kan/mag worden. Maar ook bij een (facet)zoeker die niets met de viewer te maken heeft kan het/een label component gebruiken.

Strekking van mijn epistel: Zolang het "gewoon" een label is, laat het dan een label zijn. Zodra een applicatie een complexere werkvorm vereist kan er altijd nog een "viewer-label" gemaakt worden. Dan pas is het gerechtvaardigd deze werkvorm onder een "Viewer" kopje te plaatsen.

**Comment by MichielDHVD** [comment]
@DjangoBlok @VolleMelk @Poofy83 

Als label compleet aangepast worden moeten de volgende aanpassingen ook worden meegenomen. 

Want de huidige labels hebben een wcag-error de contrast ratio op het default label is namelijk te laag.

Ook worden kleuren aangepast om overeen te komen met de notificaties. Zodat info warning danger constant de zelfde kleuren stelling hebben. 

![labels- plus kleuren](https://user-images.githubusercontent.com/36912722/39980920-7f6930a2-574e-11e8-81e8-67bb58e639ac.png)

Verder zijn de margins en fontsize hetzelfde als het label/selected-filter-component dat in dit issue wordt besproken.

**Comment by Poofy83** [comment]
Prima, ik was even in de war bij het badges issue. Natuurlijk ga ik hier een variant met sluitkruis aan toevoegen, en niet bij de badges.

**Comment by VolleMelk** [comment]
@MichielDHVD: Wat dacht je ervan om de default Lime 20% maken? Dat is een mooie en neutrale kleur in het DSO palet.

Dat grijs staat zo raar zwaar in contrast. En dan moeten we 'n status voor Lime 20% als label bedenken. Gaat de grijze vorm ergens gebruikt worden?

**Comment by MichielDHVD** [comment]
Ik heb geen variant gezien waar grijs wordt gebruikt dus die aanpassing is mogelijk. Ben het er mee eens dat de lime iets neutraler is en mooier. Hier even een aangepaste versie. 

![labels- plus kleuren](https://user-images.githubusercontent.com/36912722/39986039-c619a042-5760-11e8-8508-23a588a06c72.png)

Zij notitie. Op dit moment zijn de teksten in labels bold. Maar in het component zoals voorgesteld door @DjangoBlok is dit gewoon een normale font-weight. 

Is hier een elegante oplossing voor?

**Comment by VolleMelk** [comment]
Eleganter dan niet meer bold maken kan niet bedenken :)

**Comment by tfrijsewijk** [comment]
https://www.dso-toolkit.nl/3.0.0-alpha.0/components/detail/label.html

**Comment by MichielDHVD** [comment]
Deze zijn nog niet helemaal klaar. De kleur geel bij de hover moet nog aangepast worden. En bij rood zie ik geen scheidings lijn en geen kleur hover. 

Is het handig als ik hier nog de kleuren voor aanlever? Bij blauw en donker groen heb je zelf een interpretatie aan de kleur gegeven en die zien er uitstekend uit!

**Comment by MichielDHVD** [comment]
![labels- plus kleuren en hovers](https://user-images.githubusercontent.com/36912722/45138238-04557200-b1ac-11e8-80a9-82b544988911.png)


Iets meer aanpassingen dan oorspronkelijk gedacht. Omdat de kleuren niet goed uitkwamen. Als er meer gespecificeerd moet worden laat maar weten
