### ISSUE TITLE
Toelichting onder formelementen moet ook "static" kunnen zijn.

### ISSUE THREAD

**Issue by PieterVerheij** [dso-toolkit/dso-toolkit#1030]
De toelichting bij formulierlementen luistert niet naar de instelling `static: true` . Daardoor toont altijd het (i)-tje en het [x]-je:

![image](https://user-images.githubusercontent.com/25430835/109654750-d70e9280-7b62-11eb-8bf8-040c4e4db114.png)

**Comment by gofix** [comment]
Hij miste nog bij de reguliere 'group-input' @PieterVerheij (wel in de `yml`, maar de ondersteuning ervoor is nu ondergebracht in de `njk`)
