### ISSUE TITLE
Headings in legend moeten geen margins hebben.

### ISSUE THREAD

**Issue by PieterVerheij** [dso-toolkit/dso-toolkit#1032]
In sommige gevallen is het gebruik van headings in een legend gewenst (en ook toegestaan want phrasing content). Alleen zijn in deze gevallen de standaard verticale margins van de headings niet gewenst.

**Comment by gofix** [comment]
Hiervan is momenteel (nog) geen voorbeeld te vinden in de toolkit, maar dat komt verderop nog wel. Voor nu is dit dus helemaal goed.
