### ISSUE TITLE
Definition lists in geneste accordion

### ISSUE THREAD

**Issue by PieterVerheij** [dso-toolkit/dso-toolkit#1034]
Voor o.a. de voorbeeldpagina 'Verzoeken indienen' is het wenselijk dat er een definition list in een geneste accordion geplaatst moet kunnen worden, dus niet alleen op het hoogste nivo.

**Comment by gofix** [comment]
Deze change bevat slechts een uitbreiding op `accordion.njk` en levert geen visuele verschillen op. Prima dus, we gaan er verderop in #826 plezier van hebben.
