### ISSUE TITLE
Aanpassen edit mogelijkheid bij group static

### ISSUE THREAD

**Issue by PieterVerheij** [dso-toolkit/dso-toolkit#1036]
Bij de styling van de edit mogelijkheid werd geen rekening gehouden met de langere teksten. Styling aanpassen en langere tekst plaatsen.

**Comment by gofix** [comment]
![image](https://user-images.githubusercontent.com/2689559/110203493-dd588380-7e6e-11eb-88ce-11830bf9eb4e.png)

OK!
