### ISSUE TITLE
Instelbare buttontekst mogelijk maken bij search-bar

### ISSUE THREAD

**Issue by PieterVerheij** [dso-toolkit/dso-toolkit#1037]
In de njk markup is de buttontekst hard-coded: instelbaar maken

**Comment by gofix** [comment]
Deze change levert zoals verwacht geen visuele verschillen op, het zorgt er alleen maar voor dat de button in `search-bar.njk` een parametriseerbare buttontekst krijgt, iets dat we verderop zullen gaan gebruiken.
