### ISSUE TITLE
Refactoring voorbeeldtemplates: correctie markup link-list homepage

### ISSUE THREAD

**Issue by PieterVerheij** [dso-toolkit/dso-toolkit#1041]
De linklist onderaan de homepage heeft geen correcte markup: er wordt gebruik gemaakt van <br>'s in plaats van een unordered list:
![image](https://user-images.githubusercontent.com/25430835/109798131-a8ec8980-7c1a-11eb-8df8-90def44a28e4.png)

@bramhoosemans ik denk dat er ook nog een nieuw issue moet komen voor aparte styling van link-lists met chevrons?

![image](https://user-images.githubusercontent.com/25430835/109798071-91150580-7c1a-11eb-8564-73711a104f30.png)

**Comment by bramhoosemans** [comment]
> @bramhoosemans ik denk dat er ook nog een nieuw issue moet komen voor aparte styling van link-lists met chevrons?

Of een list variant zonder bullets..

![Schermafbeelding 2021-03-04 om 12 40 20](https://user-images.githubusercontent.com/598735/109958735-d7379b00-7ce6-11eb-8158-e602c2e9b38d.png)

**Comment by DjangoBlok** [comment]
Ja, heb ik ook behoefte aan. 
Hoewel... Ik vraag me nu af of chevrons voor de links niet verwarrend zijn. Lijken net uitklappers. 
Lijkt mij logischer de chevrons na de link te kunnen plaatsen. 
En eventueel een ander bullet item te kiezen.

**Comment by gofix** [comment]
In ieder geval is het huidige voorbeeld niet goed, dus dat normaliseren we naar een reguliere lijst.
