### ISSUE TITLE
Horizontale plaatsing form-groups en dso-form-buttons

### ISSUE THREAD

**Issue by PieterVerheij** [dso-toolkit/dso-toolkit#1046]
Voor Wizard stap 2 (Locatie) is een horizontale plaatsing van form-groups en dso-form-buttons gewenst:

![image](https://user-images.githubusercontent.com/25430835/109817986-cfb6ba00-7c32-11eb-86ec-43f2822c963e.png)

**Comment by PieterVerheij** [comment]
Responisve gedrag is buiten beschouwing gelaten.

**Comment by gofix** [comment]
Deze class is nu nog slechts een voorziening die straks (#845) in de gewijzigde wizard stap 2 in beeld gaat komen.
