### ISSUE TITLE
Op highlight box pagina hebben alle voorbeelden titel "Default"

### ISSUE THREAD

**Issue by gofix** [dso-toolkit/dso-toolkit#1048]
![image](https://user-images.githubusercontent.com/2689559/109924725-06d3ac80-7cc1-11eb-9382-6eeb5cd2768a.png)

https://dso-toolkit.nl/20.0.0/components/detail/highlight-box.html

**Comment by gofix** [comment]
Vraag: noemen we de 'default' werkvorm 'default' of 'standaard'? Ik kom nu in de Toolkit beide formuleringen tegen:
`__title: default` -> 23x
`__title: Standaard` -> 1x (in `definition-list\definition-list.config.yml`)

Ikzelf neig toch naar 'Standaard', maar ik heb dan ook een bijzondere voorliefde voor de Nederlandse taal. Wat zullen we doen @bramhoosemans , @MichielDHVD ?

**Comment by MichielDHVD** [comment]
Vraag is is dit een technische term of documentatie term? 

Technische terminologie engels documentatie taal nederlands? 

Volgens mij is dit documentatie uitleg van componenten dus standaard kan prima. Maar zo kijk ik er tegen aan.

**Comment by bramhoosemans** [comment]
> Ikzelf neig toch naar 'Standaard', maar ik heb dan ook een bijzondere voorliefde voor de Nederlandse taal. Wat zullen we doen @bramhoosemans , @MichielDHVD ?

Ik neig ook naar 'Standaard'. Alleen lijkt me het doorvoeren van Nederlandse titels in de overige voorbeelden een apart issue waardig.

**Comment by gofix** [comment]
OK, "Standaard" wordt het dan (daar had ik dus ook al zelf voor gekozen). Zie https://dso-toolkit.nl/_1048-highlight-box-all-default/components/detail/highlight-box.html

> Alleen lijkt me het doorvoeren van Nederlandse titels in de overige voorbeelden een apart issue waardig.
Helemaal mee eens, daar valt wel meer op een te merken zo links en rechts.
