### ISSUE TITLE
H1 Anchor bovenaan toolkit herontwerp. 

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#1049]
### Aanleiding
Bovenaan component pagina's staat de `h1` van die pagina gelinked om een 'standalone' weergave van die betreffende pagina op te kunnen vragen: zonder de header en navigatie van de DSO Toolkit. Dit is handig om bv. het responsive gedrag goed te kunnen bestuderen.

Het is niet voor alle gebruikers duidelijk dat de paginatitel deze functie heeft, en bovendien ziet het er niet bijzonder fraai uit:
<img width="334" alt="Screenshot 2021-03-04 at 11 25 23" src="https://user-images.githubusercontent.com/36912722/109949991-54a9de00-7cdc-11eb-8325-888c8dd5e7e8.png">

### Werkzaamheden
Dit onderdeel van componentpagina's is herontworpen en moet gewijzigd worden:
- de `<h1>` zelf moet niet linken,
- ernaast staat een link "Component preview" (met visueel verborgen de tekst " (opent in nieuw tabblad)"), die dus in een nieuw venster opent (`target="_blank" rel="noopener noreferrer"`);
- met een nieuw icoon ([new-window.svg.zip](https://github.com/dso-toolkit/dso-toolkit/files/6220049/new-window.svg.zip));

### Ontwerp
![image](https://user-images.githubusercontent.com/2689559/112803500-a2afc880-9073-11eb-870b-1a727794716e.png)

### Waar is het te testen
Voorbeeld URLs, bv. https://dso-toolkit.nl/master/components/detail/tabs.html -> opent https://dso-toolkit.nl/master/components/preview/tabs.html

**Comment by MichielDHVD** [comment]
![Open in nieuw 1](https://user-images.githubusercontent.com/36912722/110768067-2afe3300-8257-11eb-9fdc-41a398c13aeb.png)
![Open in nieuw 2](https://user-images.githubusercontent.com/36912722/110768070-2b96c980-8257-11eb-9110-2d18b6d5121f.png)


Twijfel nog over icoon. Maar een keuze uit deze drie vormen lijkt me het beste. Heb ook met primaire button getest maar die was te dominant. 

Tweede icoon hebben we niet in de toolkit. Mogelijk moeten we een nog een uniek icoon hiervoor laten maken, ik wil eigenlijk external link niet mengen met openen in nieuw tabblad.

Icoon in tweede afbeelding is eigenlijk voor de taak copying.

**Comment by bramhoosemans** [comment]
- Open in nieuw tabblad
- Open component (in een nieuw tabblad)
- Component preview (opent in een nieuw tabblad)
- Open buiten frame (opent in een nieuw tabblad)
- Component voorvertoning (opent in een nieuw tabblad)
-

**Comment by gofix** [comment]
@PieterVerheij je hebt de linktekst "component preview" niet opgenomen, maar deze als `title` behouden. Waarom? Heb ik iets gemist of is dit ergens bilateraal nog nabesproken (of is dit creatieve vrijheid die je jezelf gegund hebt ;)) ?

**Comment by PieterVerheij** [comment]
Dat laatste, gemixt met wat misinterpretatie.

**Comment by gofix** [comment]
Zit er goed uit. Ook wat jou betreft, @MichielDHVD ?

**Comment by gofix** [comment]
@timveld zekerheidshalve heb ik het ook nog even met een screenreader geprobeerd, klinkt goed :)
