### ISSUE TITLE
Highlightbox variaties / modifiers ? 

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#1050]
Willen we de huidige highlightboxes variaties behouden. 

Of moet elk element zijn eigen modifier worden die gemixed and matched kunnen worden naar wens. 

modifies:

- Wit
- Grijs
- Geel
- Dropshadow
- Lijntje om highlight box

**Comment by gofix** [comment]
Zie ook #1048, waar ik nu de voorbeelden een title heb gegeven (zodat ze niet allemaal `Default` heten) -> https://github.com/dso-toolkit/dso-toolkit/commit/281847fe0fb89b2971d1703f033621de1a14ae94

**Comment by svrijsewijk** [comment]
@MichielDHVD is dit nog relevant?

**Comment by MichielDHVD** [comment]
Ik close dit issue. Als iemand er om gaat roepen, moet het maar eerst gespecced worden. En dan kom het op github.
