### ISSUE TITLE
Tabs niet over de volledige breedte

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#1059]
Tabs niet over de volledige breedte van de container weergeven, zodat er minder visuele afstand tussen de verschillende tabs zit.

![Schermafbeelding 2021-02-26 om 10 22 37](https://user-images.githubusercontent.com/598735/110321576-298ff900-8012-11eb-8d65-77edd20f6703.png)

**Comment by MichielDHVD** [comment]
Aangezien dit zo duidelijk is zou dit niet meteen naar ready mogen?

**Comment by bramhoosemans** [comment]
> Aangezien dit zo duidelijk is zou dit niet meteen naar ready mogen?

Dat bepalen de ontwikkelaars.

**Comment by gofix** [comment]
Fraai zo. Mee eens @bramhoosemans https://dso-toolkit.nl/_1059.Tabs-niet-over-de-volledige-breedte/components/detail/tabs.html

**Comment by bramhoosemans** [comment]
@gofix Goed zo.
