### ISSUE TITLE
Voorbeeld titels in het Nederlands

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#1063]
Vervolg op https://github.com/dso-toolkit/dso-toolkit/issues/1048.

Voorbeeld titels op component pagina's zien we als documentatie en zouden daarom in het Nederlands moeten worden geschreven. In dit issue alle componenten nalopen en titels omzetten naar het Nederlands. 

Voorbeeld:
![Schermafbeelding 2021-03-11 om 12 57 42](https://user-images.githubusercontent.com/598735/110783992-699ce900-8269-11eb-9085-ce3b45dd5548.png)

**Comment by tfrijsewijk** [comment]
Dit gaan we niet meer doen, dit zijn wijzigingen in de Fractal codebase terwijl Fractal eruit gaat.
