### ISSUE TITLE
Alert responsive styling op smalle viewport

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#1064]
Bij Alert stel ik de volgende wijzigingen voor:

Wijzigingen bij Vormfactor: $screen-xs-min: 480px

- Icoon moet boven de tekst komen te staan

- Padding van 20px boven en onder -> 16px van maken. Bespaart verticale ruimte. Anders wordt de verdeling 16px boven en 20px onder (vanwege herindeling icoon).

Visueel ontwerp Alert op 320px width: 
![image](https://user-images.githubusercontent.com/36912722/111139538-898e1e80-8581-11eb-8635-8b9b4c016d25.png)

Alle varianten van alert ( 343px moet genegeerd worden in deze afbeelding): 
![image](https://user-images.githubusercontent.com/36912722/111139620-a1fe3900-8581-11eb-995f-385249a33380.png)

**Comment by gofix** [comment]
NB. @MichielDHVD je specificeert hier <320px, maar dat moet natuurlijk zijn <=320px, anders heb je er op devices van 320px breed nog niks aan :)

**Comment by MichielDHVD** [comment]
Behoefte is eerst om 480px te doen. En te kijken is dit afdoende, is het niet vervelend voor gebruikers. 

Als dat zo is hoeven we namelijk geen extra breakpoint te introduceren. 

Is 480 too much switchen we het. Maar daar kunnen we geen oordeel geven totdat we een live voorbeeld hebben.

**Comment by gofix** [comment]
Ok, goed dat ik het nog even vroeg dus. Helder! (En inderdaad, 320 < 480 dus dat gaat hoe dan ook goedkomen)

**Comment by gofix** [comment]
- Reviewed, en nu net dan de verduidelijking van @MichielDHVD verwerkt (dus: dat we toch niet bij 320, maar bij 480 gaan switchen).
- Testbaar op: https://dso-toolkit.nl/_1064.Alert-Responsive/components/preview/alert.html, @MichielDHVD

**Comment by MichielDHVD** [comment]
Werkt uitstekend naar mijn mening @bramhoosemans  wat denk jij?

Van mij mag het doorgezet worden.

**Comment by bramhoosemans** [comment]
Prima!
