### ISSUE TITLE
Group Files component uitbreiding

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#1070]
### Aanleiding
Er is een wens om de group-files in een form-horizontal onder te kunnen brengen. Daardoor is besloten om ook eens goed te kijken naar het Group-Files component.

### Werkzaamheden

- Group-Files component aanpassen; compleet maken met alle mogelijke elementen (zie lijst Opbouw component).
- Group-Files component geschikt maken voor gebruik in form-horizontal.
- Varianten doorvoeren op de component pagina; Compleet component, compleet component met alert, compleet component met toelichting, etc.
- Bepalen of er een voorbeeldpagina komt, patroon/component. Deze invulling geven met de gewenste voorbeelden.

NB. Punt 3 en 4 kunnen pas gestalte krijgen tijdens het uitvoeren van dit issue

**Opbouw component**

- Label (optioneel)
- Toelichting (optioneel)
- Lijst van ge-uploade bestanden
- Alert (optioneel)
- Upload knop
- Invalid melding (optioneel)

### Testen
https://dso-toolkit.nl/master/components/detail/group-files.html.

**Comment by daverhelst** [comment]
Voor nu is de component pagina van Group-Files aangepakt en alvast hier te bewonderen: https://dso-toolkit.nl/_1070.Group-Files-component-uitbreiding/components/detail/group-files.html

Mocht ik een variant hebben gemist, of juist teveel varianten te hebben opgenomen, dan hoor ik het graag.

Als dit akkoord is kan er nagedacht worden over de volgende stap; de patroon/voorbeeld pagina en hoe deze opgebouwt moet worden.

**Comment by bramhoosemans** [comment]
Ziet er goed uit! Precies de varianten die ik ook in het ontwerp had gezet, dus volgens mij compleet. Twee opmerkingen:

- De huidige vorm dient behouden te blijven. Dus variant zonder label... is dat iets voor de patroon/voorbeeld pagina?
- Op de backlog staat een issue om voorbeeldtitels in het Nederlands te zetten (https://github.com/dso-toolkit/dso-toolkit/issues/1063). Voor 'Group Files' gelijk verwerken?

**Comment by daverhelst** [comment]
@bramhoosemans we zien ook nog een description, komt dat te vervallen? Moeten we dat expliciet deprecated maken (rode kleur)?? Of blijven we deze wel ondersteunen, dan moet er een variant in het component bij komen.

![image](https://user-images.githubusercontent.com/5871330/115025929-31b93f00-9ec2-11eb-8bb7-ff7ff33c09c9.png)

Nu we er naar kijken denken we dat de werkvorm idealiter als `fieldset` opgemaakt moet worden. Er komt dan wel een `sr-only` legend bij met daarin dezelfde tekst als in het label staat. De legend wordt dan simpelweg niet getoond, en het label niet gelezen (aria-hidden="true") -> zie group-checkboxes

Vraag die nog ligt is hoe om te gaan met de label loze groupfiles. We staan dan nog steeds achter de fieldset vorm, maar het zichtbare label doet er dan niet meer toe. Maar een fieldset heeft _wel_ een legend nodig, er zal dus een verschil ontstaan tussen ziende gebruikers (die wel legend "zien") en niet-ziende gebruikers (die niet legend "zien"). Waarom zouden er dan dus label-loze group-files moeten bestaan?

Over punt 2, laten we dat nu nog niet doen. Liever in 1 keer, anders krijgen we nu zaken die door elkaar gaan lopen.

**Comment by daverhelst** [comment]
Over de voorbeelden, zullen we een voorbeeld patroon "Beschrijving installatie en activiteiten" aanmaken waarin het Group-File component zoals hier staat: https://dso-toolkit.nl/22.1.1/components/detail/documenten.html in onderbrengen (alleen inhoud van accordion)?

En tevens een voorbeeld component pagina aanmaken waarin we extremen, zoals erg lange tekst bij bestandsnaam, kunnen borgen?

**Comment by daverhelst** [comment]
Naar aanleiding van het telefonisch overleg met @bramhoosemans is het volgende besproken en afgesproken:
- De huidige opzet die nu in de applicatie gebruikt wordt wijkt qua markup al af van wat er in de toolkit staan. De dringende wens vanuit het implementatie team is dat er visueel _niks_ veranderd mag worden. De wijzigingen die nu in de toolkit zijn gedaan zijn voornamelijk markup wijzigingen. Zolang zij deze wijzigingen niet overnemen, blijft hun huidige opzet zoals het is.
- Omdat de markup van de huidige opzet in de applicatie niet klopt, ontstaat er een WCAG issue (fieldset zonder legend). Dit zal in een toekomstige issue moeten worden opgepakt.
- Het werk dat gedaan is in de toolkit sluit precies aan op de andere wens van @bramhoosemans, namelijk dat de Group File ingezet kan worden in een form-horizontal
- De voorbeeld pagina "Documenten" bevat nu een form-horizontal class, deze nog verwijderen
- De voorbeeld pagina "Verzoeken indienen" moet aangevuld worden met een aantal Group Files

**Comment by daverhelst** [comment]
Ook afgesproken is om het "description" element zoals hij nu is in het Group File component te deprecaten

**Comment by bramhoosemans** [comment]
> Ook afgesproken is om het "description" element zoals hij nu is in het Group File component te deprecaten

In de huidige situatie is het de toelichting bij de vraag die als "description" is toegevoegd. De toelichting hebben we in de nieuwe variant al een plek gegeven, dus wordt er geen extra description element toegevoegd.

**Comment by daverhelst** [comment]
@bramhoosemans Ik heb alle wijzigingen doorgevoerd, kun jij nog een blik werpen op de aanpassingen en zien of het (nog) klopt:

https://dso-toolkit.nl/_1070.Group-Files-component-uitbreiding/components/detail/group-files.html
https://dso-toolkit.nl/_1070.Group-Files-component-uitbreiding/components/detail/documenten.html
https://dso-toolkit.nl/_1070.Group-Files-component-uitbreiding/components/detail/verzoeken-indienen.html

**Comment by bramhoosemans** [comment]
@daverhelst Ziet er goed uit. Één opmerking over het component:
- De margin-top van de waarschuwing ook 16px maken (ipv 24px). Dan is de afstand tot de bestanden gelijk als dat er alleen een button staat.

**Comment by daverhelst** [comment]
@bramhoosemans Ik weet niet of we dat zomaar kunnen doen, die alert is namelijk een op zichzelf staand los component. Dan krijgt hij overal 16px ipv 24px. Is daar over nagedacht?

**Comment by bramhoosemans** [comment]
> @bramhoosemans Ik weet niet of we dat zomaar kunnen doen, die alert is namelijk een op zichzelf staand los component. Dan krijgt hij overal 16px ipv 24px. Is daar over nagedacht?

Mijn vermoeden was dat deze afstand specifiek in het component 'Group Files' gezet werd. Aangezien het algemene styling op het component 'Alert' is laten we het zo staan.

**Comment by daverhelst** [comment]
@bramhoosemans wijzigingen die zijn besproken op slack zijn nu ook doorgevoerd, voornamelijk de aanpassing van de voorbeeld pagina. Kun jij weer een check doen?

https://dso-toolkit.nl/_1070.Group-Files-component-uitbreiding/components/detail/group-files.html
https://dso-toolkit.nl/_1070.Group-Files-component-uitbreiding/components/detail/documenten.html
https://dso-toolkit.nl/_1070.Group-Files-component-uitbreiding/components/detail/verzoeken-indienen.html

**Comment by bramhoosemans** [comment]
Ziet er goed uit!
