### ISSUE TITLE
Visited state in Tabs verwijderen

### ISSUE THREAD

**Issue by Anto1nette** [dso-toolkit/dso-toolkit#1073]
Het is niet wenselijk dat de links in de tabs component een herkenbare 'visited state' styling krijgen (dit is niet wenselijk, omdat het "navigatie menu links" betreft). De links in de tab moeten  donkergrijs `#666666` blijven.

URL in DSO Toolkit : https://dso-toolkit.nl/master/components/detail/tabs.html

![image](https://user-images.githubusercontent.com/2689559/112382380-0fca0380-8cec-11eb-8676-1e77dd159b05.png)

NB: het huidige 'paars' lijkt default-browser styling te zijn.

Hoe te testen:
Klik eenmaal op een van de links in de tabs. Foutsituatie (huidig) is dat de link verkleurt. Goedsituatie na change is dat de link donkergrijs blijft.

**Comment by gofix** [comment]
@MichielDHVD, @bramhoosemans nu testbaar: https://dso-toolkit.nl/_1073.Visited-state-in-Tabs-verwijderen/components/detail/tabs.html

**Comment by bramhoosemans** [comment]
Het lijkt erop dat de 'disabled' tab nu ook een visited state meekrijgt.

**Comment by gofix** [comment]
Eigenlijk is het best bijzonder dat de disabled tab een `<a>` bevat!

**Comment by PieterVerheij** [comment]
Aangepast: "Het lijkt erop dat de 'disabled' tab nu ook een visited state meekrijgt."

Over de opmerking van @gofix : pakken we dat op in een nieuw issue of eerst bespreken?

**Comment by gofix** [comment]
Please check again @bramhoosemans 
Verder, @PieterVerheij inderdaad de vraag of de `<a>` in een disabled tab wel zou moeten bestaan is een ander issue. Daar heeft overigens @timveld ook vast wel een mening over.

**Comment by bramhoosemans** [comment]
> Please check again @bramhoosemans

Prima zo 👍
