### ISSUE TITLE
Storybook voor Web Components

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#1075]
Zoals in #827 is aangegeven, is Fractal EOL. Daarnaast is de developers experience van maintainers voor het ontwikkelen Web Components suboptimaal. Er wordt nog gebruik gemaakt van de standaard index.html van Stencil.

Het onderhouden van Web Components wordt niet meer in Fractal/Stencil's {{index.html}} gedaan maar in Storybook

**Comment by tfrijsewijk** [comment]
Notes to self:

Ik heb de Cypress omgevint getracht uit te breiden met code coverage zoals hier beschreven: https://docs.cypress.io/guides/tooling/code-coverage

Ik krijg de volgende foutmelding

```
cy.task('coverageReport') failed with the following error: NOENT
```

Het lijkt erop alsof Istanbul niet overweg kan met lazy loading, hij elk HTML rapport ziet er zo uit:

![image](https://user-images.githubusercontent.com/9696261/115150768-2274f580-a06a-11eb-9490-d246234216fd.png)

Behalve links zijn alle links 404, de link verwijst naar een file in het rapport die niet bestaat. Root werkt wel, maar geeft weinig nuttigs.

Punten voor de volgende poging:
* Stencil upgraden naar latest greatest (2.3.0 naar 2.5.2)
* Volgens de Stencil documentatie zou `./dist/dso-toolkit/dso-toolkit.js` moeten bestaan, maar bij mij niet. Wellicht dat het met de upgrade is gefixt.
* Istanbul wordt via `rollup-plugin-istanbul` geinjecteerd:

```
// stencil.config.ts
const istanbul = require('rollup-plugin-istanbul');

export const config: Config = {
  plugins: [
    // [..]
     process.env.DSO_ENV === 'cypress'
       ? istanbul({
         exclude: ['**.spec.ts']
       })
       : null
  ]
};
```

**Comment by PieterVerheij** [comment]
> Punten voor de volgende poging:
>
> Stencil upgraden naar latest greatest (2.3.0 naar 2.5.2)

Kan je dan gelijk de toolkit upgraden naar een hogere node.js versie zodat we niet de hele tijd hoeven te switchen tussen (in mijn geval) 12.16. 1 en 14.15.1? #prettyplease

**Comment by tfrijsewijk** [comment]
Goed punt, ik heb meteen #1095 aangemaakt
