### ISSUE TITLE
Variant toevoegen voor Progress Indicator

### ISSUE THREAD

**Issue by Anto1nette** [dso-toolkit/dso-toolkit#1083]
**Aanleiding**
In sommige toepassingen is het wenselijk een progress indicator te kunnen opnemen die duidelijker aanwezig is (en een vastgestelde hoogte heeft).

**Werkzaamheden**
We introduceren 2 modifier classes op de .dso-progress-indicator:

.dso-block (resulteert in vastgestelde hoogte, en centrering van de tekst en de spinner);
.dso-lightgray die resulteert in #e5e5e5;
De change moet non-breaking/optioneel zijn.

De hoogte varieert met .dso-small, .dso-medium en .dso-large -> resp. 48px, 64px, 96px
Breedte component is 100%

NB: de naamgeving van deze modifiers kiezen we bewust vrij algemeen, maar werken alleen in combinatie met duidelijk gedefinieerde werkvormen, in dit geval dus voor .dso-progress-indicator. Vergelijkbaar met .dso-small, .dso-medium en .dso-large die ook algemeen klinken, maar alleen hun werk doen in combinatie met de werkvorm die de modifier ondersteunt.

**Ontwerp**
![image-2021-04-01-10-25-07-915](https://user-images.githubusercontent.com/1033595/113296594-f6334800-92f9-11eb-82c4-db111377853b.png)

**Testen**
https://dso-toolkit.nl/master/components/detail/progress-indicator.html
Op deze componentpagina nemen we extra voorbeelden op van de .dso-block modifier op de .dso-small, .dso-medium en .dso-large varianten, en van 1 daarvan (.dso-medium?) ook in combinatie met .dso-lightgray.

**Comment by gofix** [comment]
@bramhoosemans zie 
- https://dso-toolkit.nl/_1083.Variant-toevoegen-voor-Progress-Indicator/components/preview/progress-indicator.html
- https://dso-toolkit.nl/_1083.Variant-toevoegen-voor-Progress-Indicator/components/detail/progress-indicator.html

Wat ik me nog wel afvraag: zou hetgeen @PieterVerheij in de pull request als informatie heeft gezet, niet eigenlijk ook in het documentatietabblad moeten staan?

**Comment by bramhoosemans** [comment]
Ziet er wat mij betreft goed uit. Ik heb @DHvD-Michael ook gevraagd het even na te lopen, aangezien hij erom gevraagd heeft.

Ik zou deze varianten idd even beschrijven in 'Technische opmerkingen' op het documentatietabblad.

**Comment by DHvD-Michael** [comment]
Top, ziet er goed uit.
