### ISSUE TITLE
Shopping Cart subitems hebben niet voldoende padding aan de rechterkant

### ISSUE THREAD

**Issue by Anto1nette** [dso-toolkit/dso-toolkit#1084]
**Aanleiding**
Bij enorm lange activiteitsnamen loopt de tekst door het icoon, zie afbeelding:
![image001](https://user-images.githubusercontent.com/1033595/113301469-57114f00-92ff-11eb-959e-e8bf1a2dce19.png)

**Werkzaamheden**
Padding-right ook in sub-balken vergroten tot 40 ipv 16px.
Voorbeeld opnemen lange regel om de fix te demonstreren en ook naar de toekomst toe in de visuele regressietests mee te nemen.

**Ontwerp**
nvt

**Testen**
https://dso-toolkit.nl/21.3.0/components/detail/shopping-cart.html

**Comment by gofix** [comment]
Ziet er goed uit (https://dso-toolkit.nl/_1084.Shopping-Cart-subitems-hebben-niet-voldoende-padding-aan-de-rechterkant/components/detail/shopping-cart.html, zie subitems voorbeelden). Mee eens @MichielDHVD ?

**Comment by bramhoosemans** [comment]
Helemaal top! Zie dat de padding-right 48px is geworden, zodat er nog 8px ruimte tussen tekst en button staat. Die had ik gemist.

**Comment by MichielDHVD** [comment]
Prima inderdaad. Zet jij deze naar accepted @bramhoosemans ?
