### ISSUE TITLE
Verticale (onder)marge van form-groups

### ISSUE THREAD

**Issue by gofix** [dso-toolkit/dso-toolkit#1091]
### Aanleiding
Bij implementatie van de inzichten zoals gedocumenteerd in https://dso-toolkit.nl/21.2.0/docs/fundament/layout.html doemen een aantal vraagstukken op.

Heeft .form-group de margin-bottom: 0 nog wel nodig?

### Werkzaamheden
Aanpassen ondermarge van .form-group en middels de beschikbare tooling beoordelen of dit tot het gewenste resultaat leidt.

### Testen
https://dso-toolkit.nl/master/components/detail/form.html, https://dso-toolkit.nl/master/components/detail/group-checkboxes.html etc.

**Comment by daverhelst** [comment]
@MichielDHVD Ik heb een vlugge remove gedaan van de margin-bottom, en ziehier het visuele resultaat: https://percy.io/dso-toolkit/dso-toolkit/builds/10049177?utm_campaign=dso-toolkit&utm_content=dso-toolkit&utm_source=github_status_public

**Comment by MichielDHVD** [comment]
Gekeken naar het resultaat. Leid vooral tot meer ademruimte voor buttons onderaan Pagina's. Extra 16px zo te zien. 

Verder valt wel de volgende voorbeeld pagina omver. 

https://dso-toolkit.nl/_1091.Verticale-ondermarge-van-form-groups/components/detail/locatie.html

**Comment by daverhelst** [comment]
@MichielDHVD @bramhoosemans Ik heb nog een kleine change toegevoegd die ervoor zorgt dat een `.form-group` in een `.dso-justify-form-groups` _geen_ margin-bottom heeft. Zodat de bevinding van Michiel is opgelost. 

Deze oorspronkelijke change heeft wel impact op de component pagina's, elk form element krijgt natuurlijk nu wel margin aan de onderkant. Zie bijvoorbeeld: https://dso-toolkit.nl/_1091.Verticale-ondermarge-van-form-groups/components/detail/group-input.html

Maar bij een goed ingericht form valt deze over de margin-top van een opvolgende `.form-group`, zie bijvoorbeeld: https://dso-toolkit.nl/_1091.Verticale-ondermarge-van-form-groups/components/detail/form.html

Graag jullie goedkeuring en/of op- en aanmerkingen.

**Comment by gofix** [comment]
We denken dat margin-bottom van fieldset verkleind moet worden van 32px naar 16px. Want, dit form-groups zelf hebben niet meer 0 margin hebben (maar 16).
