### ISSUE TITLE
Verticale (onder)marge van dso-search-bar

### ISSUE THREAD

**Issue by gofix** [dso-toolkit/dso-toolkit#1092]
### Aanleiding
Bij implementatie van de inzichten zoals gedocumenteerd in https://dso-toolkit.nl/21.2.0/docs/fundament/layout.html doemen een aantal vraagstukken op.

Heeft .dso-search-bar misschien verticale (onder)marge nodig?

### Werkzaamheden
Aanpassen ondermarge van .dso-search-bar en middels de beschikbare tooling - en in overleg met de applicatiebouwers -  beoordelen of dit tot het gewenste resultaat leidt.

### Testen
https://dso-toolkit.nl/master/components/detail/search-bar.html en https://dso-toolkit.nl/master/components/detail/group-search-bar.html

**Comment by daverhelst** [comment]
@MichielDHVD @bramhoosemans Ik heb de wijziging toegepast zodat een `.dso-search-bar` een margin-bottom van 16px krijgt, tenzij deze in een `.form-group` staat. Het resultaat is te zien hier: https://dso-toolkit.nl/_1092.Verticale-ondermarge-van-dso-search-bar/components/detail/group-search-bar.html en hier: https://dso-toolkit.nl/_1092.Verticale-ondermarge-van-dso-search-bar/components/detail/search-bar.html en in de percy scan. Daar vallen wel een aantal dingen op. 

Kunnen jullie het resultaat bekijken en melden of dit akkoord is, of dat er nog uitzonderingen aangepast moeten worden?

@gofix kijk jij ook even mee?

**Comment by MichielDHVD** [comment]
Ik vind het er prima uitzien
