### ISSUE TITLE
Storybook CSS component - Alert

### ISSUE THREAD

**Issue by daverhelst** [dso-toolkit/dso-toolkit#1103]
Voor storybook gaan we verschillende varianten van stories opnemen. In dit issue zorgen we er voor dat er naast het Alert webcomponent ook de HTML variant staat. Deze wordt later verhuisd naar zijn eigen storybook.

**Werkzaamheden:**
- Maak een kopie van het huidige webcomponent en hernoem deze naar "alert-html" en in de storiesOf naar "Alert (HTML)"
- De webcomponent variant hernoemen naar "alert-wc" en in de storiesOf naar "Alert (WC)"
- In alert-html; neem de markup vanuit de .tsx file over en herschrijf deze naar lit-html

**Comment by tfrijsewijk** [comment]
Wordt binnenkort opgeleverd
