### ISSUE TITLE
Storybook CSS Component - Attachments counter

### ISSUE THREAD

**Issue by daverhelst** [dso-toolkit/dso-toolkit#1104]
Voor storybook gaan we verschillende varianten van stories opnemen. In dit issue zorgen we er voor dat er naast het Attachments counter webcomponent ook de HTML variant staat. Deze wordt later verhuisd naar zijn eigen storybook.

**Werkzaamheden:**
- Maak een kopie van het huidige webcomponent en hernoem deze naar "attachments-counter-html" en in de storiesOf naar "Attachments Counter (HTML)"
- Het webcomponent in de storiesOf naar "Attachments Counter (WC)"
- In attachments-counter-html; neem de markup vanuit de .tsx file over en herschrijf deze naar lit-html

**Comment by tfrijsewijk** [comment]
Wordt binnenkort opgeleverd
