### ISSUE TITLE
Storybook CSS Component - Banner

### ISSUE THREAD

**Issue by daverhelst** [dso-toolkit/dso-toolkit#1106]
Voor storybook gaan we verschillende varianten van stories opnemen. In dit issue zorgen we er voor dat er naast het Banner webcomponent ook de HTML variant staat. Deze wordt later verhuisd naar zijn eigen storybook.

**Werkzaamheden:**
- Maak een kopie van het huidige webcomponent en hernoem deze naar "banner-html" en in de storiesOf naar "Banner (HTML)"
- Voor de webcomponent variant de storiesOf hernoemen naar "Banner (WC)"
- In banner-html; neem de markup vanuit de .tsx file over en herschrijf deze naar lit-html

**Comment by tfrijsewijk** [comment]
Wordt binnenkort opgeleverd
