### ISSUE TITLE
Primary Button  WCAG Contrast Error

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#111]
De Primary button fontsize is 18. Maar alleen 18.66 is geeft een hoog genoeg contrast. 

Omdat een 8px grid gebruikt moet de primary button opgeschaald worden naar 20px. 

![image](https://user-images.githubusercontent.com/36912722/39182095-0e481740-47bc-11e8-9a9f-373205945d5f.png)

**Comment by Poofy83** [comment]
@MichielDHVD Deze change heeft wel invloed op alle soorten buttons, wij vergroten de generieke button font-size. Het is namelijk een beetje vreemd om alleen de primary buttons een groter font te laten hebben.
