### ISSUE TITLE
Storybook CSS Component - Highlight box

### ISSUE THREAD

**Issue by daverhelst** [dso-toolkit/dso-toolkit#1111]
Voor storybook gaan we verschillende varianten van stories opnemen. In dit issue zorgen we er voor dat er naast het Highlight box webcomponent ook de HTML variant staat. Deze wordt later verhuisd naar zijn eigen storybook.

**Werkzaamheden:**
- Maak een kopie van het huidige webcomponent en hernoem deze naar "highlight-box-html" en in de storiesOf naar "Highlight box (HTML)"
- Het webcomponent in de storiesOf naar "Highlight box (WC)"
- In highlight-box-html; neem de markup vanuit de .tsx file over en herschrijf deze naar lit-html

**Comment by tfrijsewijk** [comment]
Wordt binnenkort opgeleverd
