### ISSUE TITLE
Component "Applicatie heading"

### ISSUE THREAD

**Issue by gofix** [dso-toolkit/dso-toolkit#1113]
**Aanleiding**
In diverse toepassingen wordt een paginatitel (H1) toegepast met daaronder een scheidingslijn. 
Dit component wordt aangepast/uitgebreid, zodat het breder inzetbaar is.

**Werkzaamheden**
Form Steps hernoemen naar 'Application Heading'
3 varianten beschikbaar stellen: alleen paginatitel, paginatitel met subtitel, paginatitel met subtitel én stappen.

**Ontwerp**
Zie bijgevoegde schermen.

**Comment by bramhoosemans** [comment]
![form-steps-afstanden](https://user-images.githubusercontent.com/598735/116887160-4586d400-ac2a-11eb-984b-ad3ca3cba36a.png)
![form-steps](https://user-images.githubusercontent.com/598735/116887166-47509780-ac2a-11eb-80f0-4f0a8a2d96e8.png)

**Comment by daverhelst** [comment]
@bramhoosemans Bij het aanpassen van dit component waren er ook een paar wijzigingen nodig op de voorbeeld pagina's, aangezien de H1 nu bij het component hoort. Maar hierdoor zag ik ook een aantal pagina's die _geen_ H1 boven de subtitel hebben staan. Dit zijn:

- Project
- Locatie
- Activiteiten

Ook zag ik dat er pagina's bestaan die geen subtitel (of stappen) hebben, dit zijn:
- Vragen
- Actieverzoeken
- Overzicht samenwerkingen

Klopt dit? Of moet iemand dit nog gaan aanvullen?

**Comment by daverhelst** [comment]
@bramhoosemans Inmiddels is er al iets testbaars gekomen:
https://dso-toolkit.nl/_1113.Component-Applicatie-heading/components/detail/application-heading.html

Kijk ook nog even naar bovenstaande comment over eventueel missende headings op de voorbeeldpagina's

**Comment by daverhelst** [comment]
@MichielDHVD Zoals besproken in de refinement, kun jij voor de voorbeeldpagina's aangeven of de heading een `application-heading` is, en wat dan de vulling moet zijn (voornamelijk missende H1's)

Een lijstje is wenselijk:
- Voorbeeldpagina, application-heading (check of kruis), en vulling

**Comment by gofix** [comment]
Tijdens de refinement gisteren bleek dat de steps indicator soms toch echt nog wel los van de `<h1>` inzetbaar moest kunnen zijn... Daarover moet uitsluitsel komtn @bramhoosemans , @MichielDHVD

**Comment by MichielDHVD** [comment]
Mee eens. Form steps / application header moet zonder H1 inzetbaar zijn. Bram Hoosemans is daar mee akkoord

**Comment by MichielDHVD** [comment]
Patronen:
Beheer basis - Yes - Invulling: Titel van beheer-applicatie, Subtitel voor de meta-data
Footer - No
Fullwidth - No 
Header - No
Lay-out - No
Pagina met banner - No
Zoeken in lijst cards (heeft twee h1's Dit mag niet volgens mij) Yes - H2 only (de tweede) - Invulling: Wetgeving gemeente den haag
Toepassingen:
Landingspagina:- No
Project: Yes - Invulling: H1: Aanvragen H2: Project stap 1/7
Locatie: Yes - Invulling: H1: Aanvraag Laan van Eik en Duinen 125, Den Haag stap H2 Locatie 2/7 (is nu 1/7)
Activiteiten: Yes - Invulling: H1: Aanvraag Laan van Eik en Duinen 125, Den Haag H2 Activiteiten  stap 3/7 
Vragen: Yes - Invulling: h1 Aanvraag Laan van Eik en Duinen 125, Den Haag H2 Vragen - stap 4/7
D
