### ISSUE TITLE
Group componenten hoeven niet zo genoemd te worden

### ISSUE THREAD

**Issue by daverhelst** [dso-toolkit/dso-toolkit#1128]
**Aanleiding**
Steeds kritischer kijken we naar hoe we op dso-toolkit.nl de componenten demonstreren/presenteren. We kijken naar taalgebruik (Engels vs. Nederlands) en hoe we dingen noemen. Zodoende doemden wat vraagtekens op bij de naamgeving in de navigatie van de Toolkit mbt. de Group ... werkvormen (onder "Form Elements"). Die heten "Group" omdat de 'formulierregel' met de uit bootstrap afkomstige class .form-group wordt gemarkeerd. Voor de lezer van de Toolkit site echter slaat die aanduiding "Group" nergens op.

**Werkzaamheden**
Verwijderen woordje "Group" uit de navigatie van de "Form Elements", alsmede uit de namen/labels bij de diverse varianten.

**Ontwerp**
![image](https://user-images.githubusercontent.com/5871330/117808630-68823b00-b25d-11eb-9f14-ed9cd1958a33.png)

**Comment by gofix** [comment]
Ik snap je dilemma. Nog steeds vind ik group- een rare term die ik in dit form elements rijtje weg zou willen. Zouden we misschien de losse input-number en search-bar component pagina's dan input-number-standalone en search-bar-standalone moeten noemen? Ik begin bijna te neigen naar atomic design analogieen, input-number-molecule en zo.

**Comment by daverhelst** [comment]
Het "vervelende" is dat ik het wel eens ben met je gedachtegang, maar de huidige `input-number` en `search-bar` zijn precies deze componenten, de group- varianten zetten daar alleen een `form-group` omheen. Oftewel, de "form" variant van `input-number` en `search-bar`. 

Alle mogelijke varianten die bij mij de revue passeren zijn ook niet passend voor gebruiksvriendelijke naamgeving in de toolkit, want hoe krijg je de naam beschrijvend genoeg:
- form-input-number
- input-number-standalone
- input-number-atom
- input-number-solo

**Comment by MichielDHVD** [comment]
Ik zou voor de form-input-number gaan. 

het is een input-number in een form. Dus het komt het dichts bij wat het daadwerkelijk is. 

Atom en Molecule gebruiken we verder nergens in ons systeem dus ook niet een optie voor mij persoonlijk.

**Comment by gofix** [comment]
We hebben besloten aan de naamgeving van files niks te wijzigen. Daarin zit 'group' helemaal niet in de weg. Het gaat hier puur om de beleving van de bezoeker, en die is nu veel beter. 

Enige dat toch nog resteert is of dit nu wel duidelijk is:
![image](https://user-images.githubusercontent.com/2689559/117960930-d2621980-b31d-11eb-94af-11d3b4bfbb4f.png)

Ik zou als labels voor de input-number en search-bar die NIET form-elements zijn de voorkeur geven aan:
- Search Bar Standalone
- Input Number Standalone
... maar we kunnen het ook gewoon hierbij laten.

Wat denk jij @MichielDHVD

**Comment by daverhelst** [comment]
Ik leg zelf de twijfel bij de naamgeving van `Form Elements`, dit proeft een beetje naar pure HTML formulier elementen, en daar zit nu meer in dan die vormen. `Form Group Elements` zou wat mij betreft beter volstaan.

Ook heeft het wel mijn voorkeur om nu niks te wijzigen aan de component namen. Het verschil is toch wel te zien aan de locatie; `Search Bar` - bevat het single search-bar component. `Form (Group) Elements` - bevat het single search-bar component _binnen_ een `form-group`

**Comment by MichielDHVD** [comment]
Ik ben het eens met Ad. We hoeven het niet groter te maken. De hierarchie is duidelijk.
