### ISSUE TITLE
Remove legacy components

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#113]
Edit @tfrijsewijk:

De volgende componenten zijn verwijderd:
* Streamer
* Inline forms
* Button group
* DSO Select
* Input group
* Split button dropdown
* Wizard
* Nieuwsartikel

De docmentatiepagina "positioning affix" is ook verwijderd.

### Originele issue:

Er was een voorstel om verschillende componenten te verwijderen / op hidden te zetten. 

Hieronder staan enkele componenten die zeker verwijderd moeten worden en sommige die op hidden gezet moeten worden. 

**Verwijderen**

In documentation: _Positioning Affix_

Dropdown button. De onderste drie mogen verwijderd worden.  De bovenste blijft. Wat is het slimste? Compleet verwijderen of de onderste 3 op hidden zetten op een bepaalde manier?  

![image](https://user-images.githubusercontent.com/36912722/39184514-ec5dc758-47c3-11e8-8aaa-af6f781db731.png)

**To be deprecated**

_Wizard_
_DSO Select_

**To be hidden**

_Panel_

Mogelijk moet _ButtonGroup_ ook hidden worden gezet. 
In de huidige staat staat deze buttongroup sowieso niet werken. Dus zou een aanpassing zou nodig zijn, maar omdat dit onderdeel niet nodig is. Kan het ook op hidden gezet worden. 

Is dat genoeg? Of moet er alsnog een herontwerp en aanpassingen overheen?

**Comment by Poofy83** [comment]
@MichielDHVD Hieronder mijn voorstellen op bovenstaande en eerder gemaakt (en besproken) document.

Ten eerste stel ik voor om componenten niet te verbergen maar simpelweg te verwijderen. Dit zodat er geen "rommel" in de code achterblijft en dankzij versie beheer kunnen we altijd eenvoudig teruggrijpen naar de betreffende code als deze in de toekomst toch wenselijk blijkt.

**Position Affix**
Dit was ooit opgezet als stuk documentatie voor een Showcase; mag van mij verwijderd worden

**Dropdown button**
Ik stel voor om de onderste 3 varianten simpelweg te verwijderen

**Wizard**
Mag verwijderd worden

**DSO Select**
Een stukje legacy; mag van mij verwijderd worden

**Panel**
Ik kan me voorstellen dat dit in de toekomst waarschijnlijk een wenselijk component kan zijn. Voor nu (indien nergens gebruikt) stel ik voor om deze te verwijderen.

**Streamer**
Ik kan me voorstellen dat dit in de toekomst waarschijnlijk een wenselijk component kan zijn. Voor nu (indien nergens gebruikt) stel ik voor om deze te verwijderen.

**Input group**
Ik kan me voorstellen dat dit in de toekomst waarschijnlijk een wenselijk component kan zijn. Voor nu (indien nergens gebruikt) stel ik voor om deze te verwijderen.

Kun jij confirmeren dat je het hiermee eens bent? Zo ja, dan kan ik ze (voor nu) verwijderen.

**Comment by MichielDHVD** [comment]
Ik loop het nog even na met @DHvD-Michael

**Comment by Poofy83** [comment]
@MichielDHVD Is hier al enige vordering in the vinden?

**Comment by MichielDHVD** [comment]
Behalve Streamer en Panel mogen deze onderdelen inderdaad weggehaald worden. 

Voor Streamer en Panel zou het wel handig zijn om het kopje deprecated mee te geven. Wij kunnen bij die onderdelen op dit moment niet goed overzien of het in gebruik is.  @Poofy83

**Comment by tfrijsewijk** [comment]
Bij mijn bezoek in Rotterdam is besloten bovenstaande componenten (en meer) te verwijderen. Aan de hand van mijn aantekeningen heb ik de openingspost aangepast zodat snel inzichtelijk is wat er is gesneuveld.
