### ISSUE TITLE
Recente dso.css is niet te bundlen met Angular v12

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#1140]
Gemeld door @kad-tammie

```
✖ Index html generation failed.
undefined:21:70579: missing '}'
```

```
angular.json dso-viewer: architect/build/builder/options/styles

    {
      "input": "src/styles.scss",
      "inject": true
    },
    {
      "input": "node_modules/dso-toolkit/dist/toolkit/styles/dso.css",
      "inject": true
    },
    {
      "input": "node_modules/@fortawesome/fontawesome-free/css/all.min.css",
      "inject": true
    },
    {
      "input": "src/assets/ol/ol.css",
      "inject": true
    }
```

Als de verwijzing naar `dso.css` wordt weggehaald slaagt de build.

De CSS gaat nou niet echt lekker door de CSS3 validator van W3C, maar Angular 11 heeft er geen moeite mee. 

De volgende CSS geeft dezelfde foutmelding op csslint.net:

```
@media screen and (min-width: 768px) {
    .dso-modal {
        bottom: 0;
        height: 100%;
        left: 0;
        position: fixed;
        right: 0;
        top: 0;
        z-index: 20;
    }
    @keyframes slideInFromTop {
        0% {
            opacity: 0;
        }
        100% {
            opacity: 1;
        }
    }
    .dso-modal .dso-dialog {
        animation: 1s ease-out 0s 1 slideInFromTop;
        margin: auto;
        margin-top: 15vh;
        max-width: 640px;
        opacity: 1;
    }
    .dso-modal .dso-footer .btn+.btn-default {
        margin-left: 16px;
    }
    .dso-modal .dso-footer .btn+.btn-link {
        margin-left: 0;
    }
}
```

Maar het is wel geldige CSS.

Afgesproken met Eric dat wij een dezer dagen een 24.0.1 uitbrengen waarin we deze lintfout hebben verholpen. Ik denk dat het makkelijker is dat wij meebuigen met Angular 12 dan andersom - Ervanuitgaande dat dit het probleem is, en dan negeren we maar dat het wel degelijk geldige CSS is.

**Comment by tfrijsewijk** [comment]
@kad-tammie: fyi, de release van vandaag heeft deze fix. Laat maar weten of dit het probleem was!

**Comment by kad-tammie** [comment]
@tfrijsewijk Probleem doet zich nog steeds voor.

**Comment by tfrijsewijk** [comment]
@kad-tammie Ohneeee!

We gaan 't oppakken in een nieuw issue, onder dit issue is een wijziging in de codebase gedaan en opgeleverd in een milestone. Ik ga 'm nu aanmaken
