### ISSUE TITLE
Interactieve zoeksuggesties aanbieden als webcomponent

### ISSUE THREAD

**Issue by Anto1nette** [dso-toolkit/dso-toolkit#1158]
### Aanleiding
In de zelfevaluatie van de Viewer zijn verbeterpunten op het gebied van toegankelijkheid ontdekt. Daarnaast zijn er wensen om zoeksuggesties ook toe te passen bij zoeken naar werkzaamheden en activiteiten.

Nu we Web Components aanbieden zouden we het component functioneel kunnen aanbieden. Op deze manier bouwen (en onderhouden) we dit component op één plek (DSO Toolkit) en hoeven de teams niet afzonderlijk een oplossing te bedenken.

### Werkzaamheden
Zoeksuggesties aanbieden als Web Component in de DSO Toolkit. 

**Aandachtspunten**
-  Zoeksuggesties worden altijd in combinatie weergegeven met een Search Bar.
-  Het tonen van typen/categorieën is optioneel. Dit wordt alleen toegepast in de Viewer.

—
Documentatie op https://dso-toolkit.nl/24.1.0/docs/fundament/zoek-suggestie.html:
Zoeksuggesties zijn aanbevolen resultaten die verschijnen in een dropdown als gebruikers in een zoekveld typen.

### Gedrag en toegankelijkheid
- Geef maximaal 10 suggesties. Zo houden we de lijst compact en zijn er geen scrollbars te zien.
- Breek een zoeksuggestie nooit af. Past een zin niet binnen de breedte van de lijst? Laat de zin dan verdergaan op de volgende regel.
- Maak het mogelijk dat gebruikers met de pijltoetsen door het menu kunnen navigeren en met enter een resultaat kunnen kiezen.
- Geef de zoeksuggestie een duidelijke hover state met een ‘hand’-cursor.
- Toon eerdere zoekopdrachten als de gebruiker in het veld focust. Deze stap is optioneel. 

**Tekst highlighten**
- Een zoeksuggestie bestaat uit twee delen: het gedeelte dat de gebruiker typt en het gedeelte dat het systeem aanvult.
- Dit verschil moet duidelijk zichtbaar zijn. Zo kan de gebruiker makkelijk zien welk deel het systeem aanvult.
- Zorg ervoor dat wat de gebruiker typt, in bold zichtbaar is. Zo kan de gebruiker op meerdere elementen uit de zoeksuggestie zoeken. Dingen die niet in bold staan, zijn aanvullingen vanuit het systeem.

Bijvoorbeeld:
    **Rijnstraat 51**, 1234 gt, Amsterdam
    Rijnstraat, **1234 gt**, Amsterdam
    Rijnstraat, 1234 gt, **Amsterdam**

Of zelfs een combinatie van meerdere elementen.
    **Rijnstraat**, 1234gt, **Amsterdam**

Dit zorgt ervoor dat een gebruiker altijd snel resultaten kan scannen op zijn ingevulde zoekopdracht.

**Screenreader**
Zoeksuggesties moeten ook waar te nemen zijn door mensen die een bijvoorbeeld screenreader gebruiken. Zorg ervoor dat de screenreader in ieder geval de volgende informatie aangeeft:

- Geef het label en de placeholder een duidelijke en begrijpelijke tekst, omdat die worden opgelezen. Geef een inputveld een role=combobox mee. Dit helpt de gebruiker bij het herkennen van het inputveld.
- Geef een melding met hoeveel beschikbare resultaten er zijn als een gebruiker stopt met typen. Dat geldt voor als de gebruiker klaar is met typen of als hij halverwege stopt. Geef maximaal 10 beschikbare resultaten. Geef ook een indicatie dat de lijst navigeerbaar is met de pijltoetsen en de enterknop.
- Laat de screenreader een resultaat voorlezen als een gebruiker erboven hovert.
- Sluit af met een bevestiging als een gebruiker een selectie bevestigt. Bijvoorbeeld ‘Geselecteerd: …’

Zie de de Vergunningcheck op het Omgevingsloket voor een live voorbeeld.

**Comment by tfrijsewijk** [comment]
Regels op de kaart:
![image](https://user-images.githubusercontent.com/9696261/126187249-dcff02be-63c2-4f02-8c98-82e5e8a92024.png)

Vergunningscheck:
![image](https://user-images.githubusercontent.com/9696261/126187343-921e6b54-dd86-401f-aabf-192966cfab32.png)

**Comment by tfrijsewijk** [comment]
# Autosuggest

De Autosuggest is een component die suggesties voor een `input[type="text"]` levert. Bij het selecteren van een suggestie wordt de `input[type="text"]` gevuld met de gekozen waarde. Het selecteren van zoekresultaten is mogelijk met de pijltjestoetsen en ENTER. Elke 200ms wordt er om nieuwe suggesties gevraagd.

## API

De API bestaat uit een prop en een `input[type="text"]`

### Prop `fetchSuggestions`

Type: `(value: string) => Promise<Array<{ value: string; type?: string }>>`.

Zodra er suggesties nodig zijn wordt deze methode aangeroepen. Bij resolven van de promise worden de resultaten als suggesties getoond.

Het (maximaal) aantal resultaten is een implementatiedetail. Deze functie wordt ook aangeroepen bij een lege zoekopdracht `""`.

Als de promise wordt rejected komt er een foutmelding te staan.

### Slot

Onder de slotted children worden de suggesties getoond.

## Voorbeelden

```html
<dso-autosuggest .fetchSuggestions=${fetchSuggestions}>
  <input type="text">
</dso-autosuggest>
```

```html
<div class="dso-context-wrapper">
  <label for="my-autosuggest" class="dso-context-label">
    Locatie
  </label>
  <div class="dso-context-container">
    <dso-dropdown-menu />
  </div>
  <div class="dso-search-bar">
    <div class="dso-search-bar-input">
      <span class="dso-search-icon" aria-hidden="true"></span>
      <dso-autosuggest .fetchSuggestions=${fetchSuggestions}>
        <input type="text" id="my-autosuggest">
      </dso-autosuggest>
    </div>
    <button type="button" class="btn btn-default">
      Button
    </button>
  </div>
</div>
```

```html
<div class="dso-context-wrapper">
  <label for="my-autosuggest" class="dso-context-label">
    Locatie
  </label>
  <div class="dso-context-container">
    <dso-dropdown-menu />
  </div>
  <dso-search-bar>
    <dso-autosuggest .fetchSuggestions=${fetchSuggestions}>
      <input type="text" id="my-autosuggest">
    </dso-autosuggest>
  </dso-search-bar>
</div>
```

## Impact van wijzigingen

Het HTML/CSS component `.dso-search-bar` zal aangepast moeten worden dat het mogelijk is om iets om de `input[type="text"]` heen te hebben staan.

## Functionaliteit

Gedrag kan afgekeken worden bij de huidige implementatie (https://pre.omgevingswet.overheid.nl/checken/stap/1)

Daarnaast speciale aandacht voor de toegankelijkheid. De huidige implementatie heeft de volgende JSX:

```jsx
<span aria-live="assertive" aria-atomic className="screen-reader-text">
  {amountOfSuggestions > 0 && !selectedItem
  && (
    <>
      {!hasResults && 'Geen resultaten gevonden voor uw invoer.'}
      {hasResults && amountOfSuggestions === 1 && 'Er is 1 resultaat beschikbaar.'}
      {hasResults && amountOfSuggestions > 1 && `Er zijn ${amountOfSuggestions} resultaten beschikbaar.`}
      {hasResults && 'Gebruik de pijltoetsen omhoog en omlaag om door de resultaten te bladeren.'}
    </>
  )}
</span>
```

* Breek een zoeksuggestie nooit af. Past een zin niet binnen de breedte van de lijst? Laat de zin dan verdergaan op de volgende regel.
* Maak het mogelijk dat gebruikers met de pijltoetsen door het menu kunnen navigeren en met enter een resultaat kunnen kiezen.
* Geef de zoeksuggestie een duidelijke hover state met een pointer cursor.

### Markeren van de term in de suggestie
Een zoeksuggestie bestaat uit twee delen: het gedeelte dat de gebruiker typt en het gedeelte dat het systeem aanvult. Dit verschil moet duidelijk zichtbaar zijn. Zo kan de gebruiker makkelijk zien welk deel het systeem aanvult.

Zorg ervoor dat wat de gebruiker invoert vetgedrukt zichtbaar is. Zo kan de gebruiker op meerdere elementen uit de zoeksuggestie zoeken. Tekst van de suggestie die niet vetgedrukt staan is een aanvulling vanuit het systeem.

Markeren gaat met `<mark>`.

Bijvoorbeeld:
    **Rijnstraat 51**, 1234 gt, Amsterdam
    Rijnstraat, **1234 gt**, Amsterdam
    Rijnstraat, 1234 gt, **Amsterdam**

Of zelfs een combinatie van meerdere elementen.
    **Rijnstraat**, 1234gt, **Amsterdam**

## Implementatie documentatie

Geef maximaal 10 suggesties. Zo houden we de lijst compact en zijn er geen scrollbars te zien.

Het tonen van typen/categorieën is optioneel. Dit wordt alleen toegepast in de Viewer.

Zoeksuggesties moeten ook waar te nemen zijn door mensen die een bijvoorbeeld screenreader gebruiken. Zorg ervoor dat de screenreader in ieder geval de volgende informatie aangeeft:

## Openstaande punten:

* "Geef het inputveld een `role=combobox` mee. Dit helpt de gebruiker bij het herkennen van het inputveld." -> Gaat `<dso-autosuggest>` dit doen of is dat een implementatiedetail?
* "Laat de screenreader een resultaat voorlezen als een gebruiker erboven hovert." -> Hoveren met de muis en dan voorlezen?
* "Sluit af met een bevestiging als een gebruiker een selectie bevestigt. Bijvoorbeeld ‘Geselecteerd: …’" -> Doet de huidige implementatie dit ook?

@MichielDHVD @bramhoosemans Kunnen jullie naar de openstaande punten kijken en meedenken? Dank!

**Comment by bramhoosemans** [comment]
> * Geef de zoeksuggestie een duidelijke hover state met een pointer cursor.

Gebruik hier een ‘hand’ cursor.

> * "Geef het inputveld een role=combobox mee. Dit helpt de gebruiker bij het herkennen van het inputveld." -> Gaat <dso-autosuggest> dit doen of is dat een implementatiedetail?

Geen idee. Iets om met developers uit de team te overleggen?

> * "Laat de screenreader een resultaat voorlezen als een gebruiker erboven hovert." -> Hoveren met de muis en dan voorlezen?

Ik weet niet meer precies waar deze wens vandaan kwam, maar de huidige implementatie leest inderdaad items op hover: “Boompjes 200, 3011XD Rotterdam, klikbaar”. Misschien kan @timveld hier meer achtergrond over geven.

> * "Sluit af met een bevestiging als een gebruiker een selectie bevestigt. Bijvoorbeeld ‘Geselecteerd: …’" -> Doet de huidige implementatie dit ook?

Jazeker: “U heeft de volgende locatie geselecteerd: Boompjes 200, 3011XD Rotterdam”

**Comment by tfrijsewijk** [comment]
> > * Geef de zoeksuggestie een duidelijke hover state met een pointer cursor.
> 
> Gebruik hier een ‘hand’ cursor.

De pointer cursor is de "hand" cursor :)

![image](https://user-images.githubusercontent.com/9696261/126755086-ef86c2dd-e7be-4cd6-8111-ce11188ca296.png)

```
cursor: pointer;
```

https://developer.mozilla.org/en-US/docs/Web/CSS/cursor

> > * "Geef het inputveld een role=combobox mee. Dit helpt de gebruiker bij het herkennen van het inputveld." -> Gaat  dit doen of is dat een implementatiedetail?
> 
> Geen idee. Iets om met developers uit de team te overleggen?

Bij nader onderzoek staat er nu ook helemaal geen `role=combobox` op de input, maar op een div hoger: Die zal de `role=listbox` wel koppelen aan de input. We gaan dit opnemen in de Autosuggest.

![image](https://user-images.githubusercontent.com/9696261/126756858-9bfed945-9c52-4534-a680-d5f8118a6793.png)

> > * "Laat de screenreader een resultaat voorlezen als een gebruiker erboven hovert." -> Hoveren met de muis en dan voorlezen?
> 
> Ik weet niet meer precies waar deze wens vandaan kwam, maar de huidige implementatie leest inderdaad items op hover: “Boompjes 200, 3011XD Rotterdam, klikbaar”. Misschien kan @timveld hier meer achtergrond over geven.

Ik vind niets op de term "klikbaar" maar ik vermoed dat dit de NVDA screenreader is:

![image](https://user-images.githubusercontent.com/9696261/126758443-07fb3ce3-71d6-49b9-a09c-dc44d2ca48e8.png)

Die `role=option` zal het wel regelen.

> > * "Sluit af met een bevestiging als een gebruiker een selectie bevestigt. Bijvoorbeeld ‘Geselecteerd: …’" -> Doet de huidige implementatie dit ook?
> 
> Jazeker: “U heeft de volgende locatie geselecteerd: Boompjes 200, 3011XD Rotterdam”

Ik heb het gevonden in de codebase: Maar als wij dit gaan maken zal dit de implementatie in de weg zitten. De Verginningscheck heeft 4 verschillende manieren om een locatie te selecteren: Op een hoger (omvattend) niveau is deze routine geschreven, waardoor dit ook voor de andere 3 locatiekeuzes werkt.

Ofwel: Het is Autosuggest overstijgend. Ik stel voor dat we dit voor nu buiten scope laten en kijken hoever we komen. We kunnen deze functionaliteit altijd nog onder een boolean attribute onderbrengen (`<dso-autosuggest confirm-selection>` oid) realiseren

**Comment by timveld** [comment]
Wat betreft voorlezen on mouse hover: dat is een NVDA functie. Zeker niet iets wat jullie moeten gaan implementeren. Niet te verwarren met het voorlezen als met pijltjestoetsen wordt genavigeerd door de suggesties.

**Comment by timveld** [comment]
Als toegezegd heb ik dit component uitgebreider onderzocht en [deze uitgebreide blogpost over comboboxes|https://www.evinced.com/blog/creating-accessible-combo-boxes/] gevonden. Het daar ontwikkelde voorbeeld kunnen we grotendeels volgen, maar er zijn een paar dingetjes die niet kloppen of volgens onze conventies anders moeten.  

==Voorgestelde wijzigingen aan het component 
* De role=combobox niet op de div maar op de input zetten. 
* aria-haspopup=listbox op de input zetten.
* aria-controls verwijderen. In eerdere gevallen kan onze conclusie worden samengevat met de titel van het aangehaalde artikel "aria-controls is poop", geen reden om daar nu anders over te denken. JAWS schijnt de enige screen reader te zijn die hier wat mee doet, ik zal na het verwijderen daarmee testen. 
* aria-expanded op de input zetten, deze moet true zijn als de combobox is uitgeklapt (let op terugzetten naar false bij inklappen). Dat maakt een aankondiging "x resultaten gevonden" zoals die nu in de vergunningcheck overbodig, doordat de screen reader "uitgeklapt" zegt weet de gebruiker al dat er resultaten zijn en het aantal ligt besloten in de lijst. 

== Uitkomst testen 
Met NVDA en JAWS in Firefox, Edge en Chrome werkt het goed. Op de iPhone zonder VoiceOver wel, maar met VoiceOver is er wat vreemd gedrag. Ik denk dat dit met de voorgestelde aanpassingen verbetert. Belangrijk is in ieder geval dat bij gebruik van de pijltjestoetsen de cursor overal netjes wordt gevolgd, dus dat hebben we onder controle.

**Comment by benheldoorn** [comment]
Interessant. Dus eigenlijk  wat de w3 org over listbox combo adviseert kan met een flink pak zout genomen worden. https://www.w3.org/TR/wai-aria-practices-1.1/examples/combobox/aria1.1pattern/listbox-combo.html

**Comment by timveld** [comment]
@benheldoorn inderdaad, er zijn grote verschillen in hoe user agents met aria omgaan en er is in complexere situaties soms meer dan een waarheid. Dus je moet de impact op een screen reader goed kennen, van daaruit ontwerpbeslissingen nemen en dan kan het zijn dat experts verschillende adviezen geven. Ik kan niet de motivatie van iedere keuze volledig uitwerken maar de blogpost waar ik naar verwees geeft een aardig idee van het soort afwegingen wat we moeten maken. Ik ben nu bezig met de treeview, dat is ook zo'n leuk stukje aria voor gevorderden...

**Comment by benheldoorn** [comment]
@timveld jou voorgestelde wijzigingen aan het component zijn doorgevoerd. Zou je nog een keer kunnen testen?
Link naar het component: https://core.dso-toolkit.nl/_1158-Interactieve-zoeksuggesties/?path=/story/autosuggest--autosuggest
