### ISSUE TITLE
Link lists (met soms button styling)

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#1159]
**Aanleiding**
Bij het verbeteren van de footer is er behoefte gekomen om een link list vorm te introduceren. 

**Werkzaamheden**

Icoon toevoegen
Marges updaten
Voor gekleurde achtergronden is er een variatie gemaakt. 

**Ontwerp**

![image](https://user-images.githubusercontent.com/36912722/120639364-8bc19400-c471-11eb-8e4d-98ed44bea792.png)
![image](https://user-images.githubusercontent.com/36912722/120639385-92500b80-c471-11eb-9521-962d2b7e6f81.png)

 

    
**Testen**
 

Screenreader test 
Visuele controle , contrast waardes kloppen
Voorbeeldpagina's nalopen kijken of er onwenselijke veranderingen zijn
Acceptatiecriteria
Controle/ Approval door Reporter/schrijver van Story
WCAG Approved (in afstemming met Tim in't Veld
Technische keuze consistentie Toolkit bewaakt door Info Projects .
Options

**Comment by PieterVerheij** [comment]
@MichielDHVD https://www.dso-toolkit.nl/_1159.v2-Link-lists/

**Comment by MichielDHVD** [comment]
@PieterVerheij  Bij de footer zie ik nog groene links op hover worden ze pas zwart. Gekleurde achtergrond is altijd zwart. 

https://www.dso-toolkit.nl/_1159.v2-Link-lists/components/detail/link-list.html

**Comment by PieterVerheij** [comment]
Ah ja, ik ga mijn leesbril afpoetsen. Maar we zijn nu ook even aan het kijken naar een andere oplossingsrichting voor de styling.

**Comment by tfrijsewijk** [comment]
Deze heeft de release van 23-6 niet gehaald. Als het morgen nodig is kan ik er nog een release achteraan rollen, en anders komt ie volgende release mee.

**Comment by tfrijsewijk** [comment]
Michiel heeft aangegeven dat er geen gelegenheidsrelease nodig is. Aankomende release is prima.

Omdat er toch geen haast is breiden we de scope een klein beetje uit door het component ook meteen in Storybook onder te brengen. Openstaande punten zijn:

- [ ] Review items behandelen
- [ ] Story definitie in `/packages/sources/src/components/link-list` aanmaken (afkijken van defintion-list)
- [ ] `/packages/sources/src/components/link-list/link-list.scss` met mixins aanmaken (afkijken van description)
- [ ] Implementatie van mixins uit `packages/sources` in `@dso-toolkit/css` (`/packages/css/src/components/link-list/link-list.scss`, afkijken van description)
- [ ] Storybook definitie voorzien van templates in `@dso-toolkit/css`, afkijken bij description of definition-list
- [ ] Testen in CSS Storybook met `yarn start:css`
- [ ] Testen in Fractal met `yarn fractal`
