### ISSUE TITLE
Storybook plugin "@whitespace/storybook-addon-html" neemt whitespace aan het einde in een element niet over

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#1163]
De volgende code...

![image](https://user-images.githubusercontent.com/9696261/121321518-7683b400-c90e-11eb-833d-9c7afa8adbe9.png)

...toont als volgt in Storybook...

![image](https://user-images.githubusercontent.com/9696261/121321605-89968400-c90e-11eb-9947-6dd1a0874bea.png)

...maar wordt als volgt in het DOM geplaatst...

![image](https://user-images.githubusercontent.com/9696261/121321671-9ca95400-c90e-11eb-80c1-aafbb260c98a.png)

De plugin `@whitespace/storybook-addon-html` statificeert het DOM element tijdens de runtime van Storybook. Tijdens dit proces raakt de whitespace verloren. Ik vermoed dat het iets te maken heeft met de configuratie:

```
// .storybook/parameters.js
export const parameters = {
  html: {
    root: '#root-inner', // default: #root
    removeEmptyComments: true // default: false
  }
};
```

PS: Ironisch genoeg noemt de developer van deze plugin zichzelf _whitespace_..

**Comment by tfrijsewijk** [comment]
Dit is een van de oudste nog openstaande issues, en vooralsnog hebben we één melding gekregen. Ik sluit dit issue, als er iemand weer over begint heropenen we 'm.

**Comment by iterox** [comment]
Is de patch `@whitespace+storybook-addon-html+5.1.6.patch` hier aan gerelateerd?

En meer algemeen: waar leggen wij vast wat een patch fixt?
