### ISSUE TITLE
Date Picker met shadowRoot is met extern label element niet toegankelijk

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#1164]
![image](https://user-images.githubusercontent.com/9696261/121325652-11ca5880-c912-11eb-89ff-8bff95bf90e3.png)

Het `input` element in `<dso-date-picker>` krijgt ook geen focus als je op het `<label>` element klikt.

Zie https://github.com/whatwg/html/issues/3219 voor meer informatie.

Het originele component (de Duet Date Picker) heeft hier geen last van omdat die geen shadowRoot gebruikt. Mogelijke oplossingen:
* `shadow: true` naar `scoped: true`
* `id` op `<dso-date-picker>` en scriptend het focus gedrag doorzetten

**Comment by gofix** [comment]
Ineens begrijp ik waarom het accessiblity paneel in Storybook geen foutmelding geeft over het ontbreken van een label. Namelijk: de input in datapicker heeft wel een placeholder. En, als een input geen label is maar wel een placeholder, wordt die placeholder geinterpreteerd als de 'accessible name'. Dat is inhoudelijk natuurlijk helemaal niet correct, maar verklaart wel waarom we daar niet al veel eerder op gealerteerd raakten.

![image](https://user-images.githubusercontent.com/2689559/142874650-dc7098f5-7b09-4e4f-8f97-b4f915238847.png)

**Comment by tfrijsewijk** [comment]
Met `shadow: false, scoped: true` wordt styling niet meer in een Shadow Root met een Constructed Stylesheet geplaatst, maar in Document met een `<style>` element: alle styling is extra gescoped met een door Stencil gegenereerde selector `.sc-dso-date-picker`.

De tests zijn aangepast (geen `.shadow()` meer) en het component zelf maakt ook geen gebruik meer van `HTMLElement.shadowRoot`.

**Comment by tfrijsewijk** [comment]
De Percy test faalt:

![image](https://user-images.githubusercontent.com/9696261/153164514-e263dc09-2461-4af6-adc2-d3d79d08c6f6.png)

Dit is géén timing issue maar een Percy configuratie + Shadow DOM issue.

Een Percy snapshot bestaat uit twee fasen: Lokaal wordt een DOM snapshot met alle assets gemaakt. De servers van Percy renderen deze snapshot en maken een image snapshot: https://docs.percy.io/docs/debugging-sdks

Het DOM wordt geserialiseerd, maar Percy serialiseert geen Shadow DOM. Daarom hebben wij `enableJavascript: true` gezet waardoor Percy het Web Component kan starten.

Doordat we het Shadow DOM hebben uitgezet maar wel `enableJavascript: true` hebben wordt het component dubbel gestart: één keer lokaal en één keer remote (simpele weergave):

```html
<!-- Zo staat het in de reference .html files -->
<dso-date-picker></dso-date-picker>

<!-- dit maakt de lokale browser ervan, en het wordt ongeveer op deze manier geserializeerd -->
<dso-date-picker><input type="text"></dso-date-picker>

<!---- dit maakt de REMOTE browser ervan, het web component wordt NOG 'n keer gestart en Stencil schiet gewoon nog 'n keer een input element. Het is Web Component eigen om elementen in "onbekende" of niet-bestaande slots "gewoon" te tonen, vandaar de extra input -->
<dso-date-picker><input type="text"><input type="text"></dso-date-picker>
```

Het is Web Component eigen om elementen zonder slot of onbekend slot "gewoon" te blijven renderen, waardoor het input element dubbel wordt getoond: het is er immers twee keer.

We kunnen `enableJavascript: true` niet uitzetten, want dan worden alle Web Components met een Shadow DOM niet meer geshot:

![image](https://user-images.githubusercontent.com/9696261/153166234-6c14b28e-4854-4294-8135-2804fd00ce76.png)

Met de huidige opzet is het niet mogelijk om `enableJavascript` per reference file te configureren. In een Storybook/Cypress opzet kunnen we `enableJavascript` per snapshot configureren. Ik denk dat het zelfs mogelijk is om het het Shadow DOM zelf te serialiseren met `cy.get('dso-date-picker').shadow().percySnapshot()`, maar daar moet ik meer onderzoek naar doen.

Ik stel voor dat we de pijn pakken en het referentieshot accepteren. Het belangrijkste is dat we gewezen worden op wijzigingen. Met de dubbele input in het referentieshot is onhandig maar niet onmogelijk om dat te zien.

cc @benheldoorn @gofix
