### ISSUE TITLE
SCSS van 24.3.0 kan niet gecompileerd worden

### ISSUE THREAD

**Issue by WiebeCnossen** [dso-toolkit/dso-toolkit#1167]
Er zijn diverse verwijzingen naar bestanden onder het pad `@dso-toolkit/css` maar die directory zit niet in de release.

Output van `ripgrep`
![image](https://user-images.githubusercontent.com/6065375/121421203-32c09700-c96e-11eb-91c3-215f0366afc1.png)

**Comment by tfrijsewijk** [comment]
Gefixed in 24.3.1, thanks voor melden
