### ISSUE TITLE
Versie selectie in de toolkit voldoet niet aan voorschrift dropdown button

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#1172]
Aanleiding
Versie selectie is niet met pijltjes te navigeren of met 'spatie' te activeren zoals wordt voorgeschreven sinds release 21.3.0 22.0.0.

Werkzaamheden
Versie selectie implementatie in DSO Toolkit zoals voorgeschreven.
event.code ArrowUp : omhoog, vorige ‘option’, zelfde als tab
event.code ArrowDown : omlaag, volgende ‘option’, zelfde als shift-tab
event.code Space : maak keuze
In de documentatie staat geen 'enter' event omschreven; zouden we die niet moeten toevoegen?
Testen
Toetsenbord interactie testen op https://dso-toolkit.nl/

Acceptatiecriteria

**Comment by gofix** [comment]
@MichielDHVD met de ontwikkeling van het dropdown button web component (#1173) en het implementeren daarvan in de documentatiesite is dit issue volgens mij 100% opgelost.

Je kunt testen op de topic-deploy-branch: https://dso-toolkit.nl/_1173-Webcomponent-Dropdown-button/

**Comment by bramhoosemans** [comment]
Net even getest; werkt nu inderdaad (ook) goed met een toetsenbord.

**Comment by MichielDHVD** [comment]
Werkt zoals het hoort. Doorzetten.
