### ISSUE TITLE
Webcomponent: Dropdown button 

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#1173]
Webcomponenten hebben geen Jira context @gofix  of @tfrijsewijk  kunnen jullie deze aanvullen naar eigen behoefte. 

Gekoppeld aan dit issue op Jira was : https://github.com/dso-toolkit/dso-toolkit/issues/1172  Het accessible maken van de version selector

**Comment by tfrijsewijk** [comment]
Originele tekst uit JIRA:
> # Werkzaamheden
> Versie selectie implementatie in DSO Toolkit zoals voorgeschreven.
> event.code ArrowUp : omhoog, vorige ‘option’, zelfde als tab
> event.code ArrowDown : omlaag, volgende ‘option’, zelfde als shift-tab
> event.code Space : maak keuze

Het visuele ontwerp staat vast, zoals deze nu is geimplementeerd op dso-toolkit.nl. In #373 staan design specificaties.

In dit issue gaan we een Web Component opleveren. Maar we moeten wel nog bepalen wat de scope van dit web component is:
* Component "Dropdown": inclusief button? (Dropdown button??)
* Component: "Dropdown menu": Alleen het menu? Dat kunnen we misschien met Popper.js (zoals bij Tooltip) op de juiste plek positioneren. Het openen/sluiten moet op 'n andere manier geregeld worden
* De API van het component

Voorzet:

```html
<dso-dropdown>
  <button type="button" slot="toggle-button">
    Opties
  </button>
  <ul slot="options"> <!-- options goede naam? -->
    <li>Optie 1</li>
    <li>Optie 1</li>
    <li>Optie 1</li>
    <li>Optie 1</li>
  </ul>
</dso-dropdown>
```

Checked variant uitwerken en hoe de checked markeren?
