### ISSUE TITLE
Datepicker: aria-current=date toevoegen

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#1174]
We hebben in de kalender van de datepicker toch een klein probleempje gemist: er staat altijd een cirkeltje rond de datum van vandaag, maar daarvoor is geen tekstalternatief. Op deze dag moet aria-current="date" staan.

**Comment by MichielDHVD** [comment]
Comment van Tim in't Veld plaats ik  er toch bij is mogelijk handig ter herinnering. 

NAV discussie vorige week: het is inderdaad een ingewikkelde situatie en ook in het voorbeeld van aria zelf is het niet goed gedaan, zowel de huidige datum als de geselecteerde datum zijn visueel gemarkeerd maar wordt niet uitgesproken! Denk dat ik ze feedback moet gaan geven, we zijn inmiddels zo goed dat we Aria gaan corrigeren!

Maar aria-current voor vandaag en selected voor geselecteerd lijkt me de beste oplossing.
De specificatie van aria-current zegt dat aria-current=date "Represents the current date within a collection of dates." Dat is dus de huidige datum, niet de geselecteerde datum. Zie ook het artikel aria-selected – when (not) to use it over hoe current en selected zich verhouden.

Als zou blijken dat gebruikers van deze oplossing in de war raken dan zou je met sr-only expliciet kunnen zeggen dat het om vandaag gaat. Maar het beste is om zo veel mogelijk standaarden te volgen zodat screen readers zelf kunnen bepalen hoe ze eer mee omgaan, aria-current voor de huidige datum en aria-selected voor de geselecteerde datum lijkt me duidelijk en gaat met NVDA ook goed werken.

**Comment by tfrijsewijk** [comment]
# `aria-selected`
Het lijkt erop dat er dit het opnemen van de Duet Datepicker stuk is gegaan, er staat namelijk een routine voor: https://github.com/dso-toolkit/dso-toolkit/blob/master/packages/core/src/components/date-picker/date-picker-month.tsx#L81

Ik vermoed dat dit te maken heeft met het andere date format.

# `aria-current`
Ik stel voor dat we dit implementeren naast `aria-selected` met dezelfde logica zoals hier: https://github.com/dso-toolkit/dso-toolkit/blob/master/packages/core/src/components/date-picker/date-picker-day.tsx#L23

# Tests en updaten
We hebben tests die met Cypress worden gedraaid, maar de tests van Duet zijn niet overgezet. Ik zou de tests van Duet graag ook opnemen in onze test routine. De Date Picker is in issue #877 aangevraagd en in PR #965 gerealiseerd. [De eerste commit "Date Picker - initiele commit, copy van Duet date picker"](https://github.com/dso-toolkit/dso-toolkit/pull/965/commits/bfda7f31c4462aa76abcdca8795b13cbcefa807f) was op 6 januari 2021 om 14:03. Ik ben er vrij zeker van dat ik toen de stavaza uit duet-datepicker master branch heb overgenomen.
* Ik ben benieuwd welke versie het toen was en welke verbeteringen er sindsdien zijn uitgebracht
* Haalbare zaak om deze verbeteringen door te voeren?
* Wat moeten we doen om de tests van Duet te draaien. Kunnen we deze door Cypress laten uitvoeren of moeten we daarvoor de Stencil e2e test suite gebruiken?

**Comment by benheldoorn** [comment]
Op zich is het verzoek "aria-current=date toevoegen" uitgevoerd, maar waarschijnlijk zal het niet het gewenste effect hebben.
In de duetds/date-picker is, nadat deze overgenomen is in de toolkit, het gedeelte waar het hier om gaat op de schop gegaan [https://github.com/duetds/date-picker/pull/51]
Als blijkt dat de hier toegevoegde aria-current=date niet het gewenste effect heeft en de laatste versie van duetds wel [https://duetds.github.io/date-picker/],  dan zal de toolkit implementatie van de datepicker ook bijgewerkt moeten worden. Aangezien het geen fork is maar een bewerkte en aangepaste kopie is dat best wel een uitdaging op zich.

**Comment by gofix** [comment]
@timveld kun jij het resultaat bestuderen van de kleine ingreep die @benheldoorn nu heeft gedaan?

https://dso-toolkit.nl/_1174-date-picker-aria-current/components/preview/date-picker.html, als je nu bv. de "Default" opent, die op de huidige maand opent, heeft de huidige dag aan `aria-current="date"` gekregen. 

![image](https://user-images.githubusercontent.com/2689559/124562885-d56e1780-de3f-11eb-8540-9db57a1e5d75.png)

Dit is dus precies wat in dit ticket gewenst wordt, maar zoals je voorgaand kunt lezen zijn er nadat we destijds de Duet datepicker code hebben opgenomen in DSO Toolkit, nog wel flink wat wijzigingen geweest in de oorspronkelijke Duet code. De vraag is nu vooral: is wat we nu gedaan hebben _genoeg_, of zouden we alle andere verbeteringen in de oorspronkelijke code ook weer moeten nemen.

**Comment by timveld** [comment]
Ik zie dat hij inmidels gereleased is en hij doet wat ik verwacht
