### ISSUE TITLE
breadcrumb: testcondities / test story

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#1175]
In de breadcrumb documentatie staan bij gedrag en toegankelijkheid 2 condities.

Werkzaamheden

- Een nuttige automatische test is controleren of aria-current="page" op het laatste element in de lijst staat.

 

Andere condities gaan over het correct overnemen van de markup dus lijkt me geen automatische test waard. Zouden we nog iets moeten doen om te controleren of de links en hierarchie tussen de pagina's overal kloppen? Waarschijnlijk gaat dat te ver maar is een idee wat bij mij opkwam.

**Comment by bramhoosemans** [comment]
Ik ben ook voorstander van 'terug naar de backlog' en blocken door een test suite in de HTML/CSS storybook.

**Comment by svrijsewijk** [comment]
Ik sluit dit ticket. Mocht er een HTML/CSS cypress test-suite komen worden vanzelf alle componenten geevalueerd op benodigde tests.
