### ISSUE TITLE
Modal responsive button uitlijning

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#1178]
Aanleiding
Tijdens testen kwam deze bug toevallig naar boven.  Onder de 768px viewport krijgt de modal een volledige breedte en de knoppen staan dan niet strak uitgelijnd. De tweede knop wordt ingesprongen met een margin van 16px links. 

Werkzaamheden
Zorgen dat knoppen netjes onder elkaar uitlijnen op responsive viewport onder 768px. 
16px margin aan de linker kant verwijderen. 

Ontwerp
![image](https://user-images.githubusercontent.com/36912722/122079629-e22dbb80-cdfd-11eb-834b-f6a1d98a3282.png)

Testen
Visuele controle -> Responsive, Zoom 400%
Interactie gedrag testen meerdere browsers
Voorbeeldpagina's nalopen kijken of er onwenselijke veranderingen zijn

**Comment by PieterVerheij** [comment]
https://www.dso-toolkit.nl/_1178.Modal-responsive-button-uitlijning/components/detail/modal.html
