### ISSUE TITLE
Selectable type checkbox voorzien van indeterminate state

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#1185]
# Checkbox Indeterminate state

Een klassieke `input[type="checkbox"]` kan een *indeterminate* state krijgen. De `checked` blijft ongewijzigd. De indeterminate state is alleen een visueel aspect.

Het markeren van een indeterminate checkbox kan alleen met scripting: De property `indeterminate` op `true` zetten:

```js
document.querySelector('input[type="checkbox"]').indeterminate = true;
```

De Selectable type checkbox breiden we uit met een boolean attribuut `indeterminate`. Als dit attribuut is gezet wordt op de `input[type="checkbox"]` de indeterminate state gezet.

## API

```html
<dso-selectable type="checkbox" indeterminate>
  Label
</dso-selectable>
```

Dit attribuut mag alleen reageren als het een `type="checkbox"` betreft.

## Ontwerp

![image](https://user-images.githubusercontent.com/2689559/127976063-84b300e4-56ac-44ab-862f-18c633ead0f7.png)

## Werkzaamheden

De Selectable bieden we als HTML/CSS component en Web Component aan. De styling bevindt zich in `@dso-toolkit/sources` en moet gestijld worden op de `:indeterminate` pseudo class selector: https://developer.mozilla.org/en-US/docs/Web/CSS/:indeterminate

Voor beide implementaties moeten de Storybook controls worden uitgebreid.

## Openstaande punten

Het voorbeeld van Bram laat een nested constructie zien. Ik stel voor dat we dit alleen als HTML/CSS component opleveren. Met bovenstaande wijzigingen kan vanuit een markup voorschrift makkelijk de indeterminate state worden gezet. Door het state management niet bij de DSO Toolkit te beleggen (dmv. een Web Component) maar alleen het visuele aspect te waarborgen (dmv. een HTMl/CSS component) moet de implementator de state van de diverse checkboxen op zich nemen.

Hiermee wordt de implementator ook meteen gedwongen een beslissing over de kwestie `:checked:indeterminate` en `:not(:checked):indeterminate` te nemen.

Een alternatief is de selectable nestable maken:

```html
<dso-selectable type="checkbox" indeterminate>
  Auto
  <div slot="nested">
    <dso-selectable type="checkbox" checked>
      Alfa
    </dso-nestable>
    <dso-selectable type="checkbox">
      Ferrari
    </dso-nestable>
    <dso-selectable type="checkbox" checked>
      Maserati
    </dso-nestable>
    <dso-selectable type="checkbox" indeterminate>
      Overig
      <div slot="nested">
        <dso-selectable type="checkbox" checked>
          BMW
        </dso-nestable>
        <dso-selectable type="checkbox">
          Mercedes
        </dso-nestable>
      </div>
    </dso-nestable>
  </div>
```

Doordat de selectables nestable zijn is het visuele inspringen makkelijk te realiseren.

Wat nog uitgewerkt moet worden: Hoe gaat de implementator ermee aan de slag?

**Comment by gofix** [comment]
Met @bramhoosemans en @daverhelst besproken:
- het ziet ernaar uit dat het team nog gebruik gaat maken van het CSS component (niet het Web Component);
- daarom zijn we nu het meest geholpen met dat in iedere geval de CSS beschikbaar komt die de juiste inspringing programmeert, en een markup voorschrift voor hoe dit dan gemaakt moet worden.

Daartoe:
Gaan we nu op fractal pagina https://dso-toolkit.nl/_1185-checkbox-indeterminate-state/components/detail/selectable.html 
- ook de checkbox laten zien
- de zinloze voorbeelden die er nu staan halen we weg
- (en waar het om gaat) -> we laten de een geneste vorm van selectable checkboxes zien

Markup zal ongeveer worden:
```
<div class="dso-selectable">
  <input
    type="checkbox"
    id="papa"
    value="the-value"
  />

  <label for="papa">Label</label>

  <div class="dso-selectable">
    <input
      type="checkbox"
      id="kind"
      value="the-value"
    />

    <label for="kind">Label</label>
  </div>
</div>
```

Buiten scope valt:
- verwerking in het storybook
- web component
... daarvoor wordt een los issue op de backlog geplaatst.

**Comment by gofix** [comment]
@bramhoosemans https://dso-toolkit.nl/_1185-checkbox-indeterminate-state/components/detail/selectable.html

**Comment by bramhoosemans** [comment]
Styling is goedgekeurd 👍

**Comment by gofix** [comment]
Ja ziet er fraai uit, en hoe dan ook is nu deze documentatie pagina een stuk zinvoller. Maar... semantisch is het volgens mij nog niet helemaal ok.

**Comment by gofix** [comment]
Gesproken is over oplossingen met geneste lijsten, of met een fieldset. @timveld heeft ernstige twijfels bij geneste lijsten, dus - als we treeview (ook een suggestie) nog maar even buiten beschouweing laten (want die moet nog geboren worden) - blijft `<fieldset />` over.

**Comment by gofix** [comment]
En dan... wat zetten we in de `<legend />` ofwel, wat adviseren we developers dan in de `<legend />` te zetten?
Iets als 'onderdelen van X', waarbij X dan het parent checkbox is ?

**Comment by gofix** [comment]
Na nader overleg: we ontkomen er niet aan om toch geneste lijsten te gaan maken. Dit betekent dat we een component 'nestable selectables' gaan introduceren. Deze moet zelfstandig getoond worden, maar kan ook deel uitmaken van een form. En zal in fractal dan dus onder form elements komen, bij checkboxes of als los 'hoofdstukje' dat valt nog te bezien.

**Comment by timveld** [comment]
Ik was aanvankelijk te pessimistisch over die nested lists, gaat wel werken. Als we de lijsten een label geven met aria-label / labeledby kan het onderscheid extra duidelijk worden gemaakt, bijvoorbeeld "hoofdactiviteit" op eerste lijst en "subactiviteiten" op tweede lijst. Graag een werkend voorbeeld liefst met realistische inhoud.

**Comment by gofix** [comment]
@timveld kun jij een blik werpen op https://dso-toolkit.nl/_1185-checkbox-indeterminate-state/components/preview/selectable.html, en dan het voorbeeld "CHECKBOX - NESTED". Na veel wederzijds overleg hebben we daar de semantiek van lijsten en nestings dus met `ul` en `li` gemaakt, en dat lijkt heel logisch. Aan jou de vraag of deze opzet nu qua toegankelijkheid ook in de haak is. We hebben het onszelf niet al te gemakkelijk gemaakt en er ook een info-button met toelichting bij gezet. Inhoudelijk is de terminologie natuurlijk "bogus", dus daar moet je misschien even doorheen kijken.
