### ISSUE TITLE
CSS Component Image naar storybook - varianten `img-rounded` en `img-thumbnail` deprecated

### ISSUE THREAD

**Issue by daverhelst** [dso-toolkit/dso-toolkit#1188]
**Aanleiding**
De vraag was of uberhaupt de IMG tag een webcomponent moet worden. Antwoord is Ja in de toekomst zal onder andere in de landingspagina voor de viewer de class rounded gebruikt worden in de img tag. 

**Werkzaamheden**
Wat moet er concreet aan development stappen gezet worden omdat het issue te realiseren. Dit kunnen bijv. zijn

- img component verhuizen
- Volgende classes deprecaten: rounded and thumbnail

**Ontwerp**
NVT

**Testen**
Welke test stappen moeten uitgevoerd worden om te controleren of het component correct is gebouwd

Visuele controle -> Responsive, Zoom 400%
Voorbeeldpagina's nalopen kijken of er onwenselijke veranderingen zijn

**Acceptatiecriteria**
Controle/ Approval door Reporter/schrijver van Story
WCAG Approved (in afstemming met Tim in't Veld
Technische keuze consistentie Toolkit bewaakt door Info Projects .

**Comment by gofix** [comment]
@daverhelst wat moet hier nu eigenlijk nog gebeuren?
