### ISSUE TITLE
Add Datepicker functionality

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#119]
Onder het kopje group input. 

https://dso-toolkit.nl/2.0.0-alpha.0/components/detail/group-input.html

Staat ook een form met een datepicker icoontje maar de functionaliteit zit er niet in. Ik neem aan dat bootstrap dit standaard meelevert. 

Misschien wel handig om die functionaliteit te laten zien en even er bij te zetten hoe het moet worden aangeroepen.

**Comment by VolleMelk** [comment]
Het icoon is nogal slecht gekozen. De pagina waar naar verwezen wordt heeft geen component uitgewerkt met button. Het component met icoon (het slecht gekozen calendar icoon) was bedoeld om de `has-feedback` te demonstreren: https://getbootstrap.com/docs/3.3/css/#callout-has-feedback-icon-positioning

Bootstrap levert geen datepicker.

De DSO Toolkit is framework agnostisch. Het is geen probleem dat wij een datepicker template uitwerken, maar ik kan mij voorstellen dat een implementator dit vreselijk zal vinden: Niemand maakt z'n eigen datepicker component, iedereen neemt een bestaande module. Het zal lastig zijn om de template die vanuit de DSO Toolkit wordt opgelegd te verwerken in de datepicker module en aan te sluiten.

**Comment by MichielDHVD** [comment]
Dan lijkt het me slimmer om even een ander icoontje te kiezen. Of is die er een twee niet. Deze issue is dan meer een nitpick geworden en hoeft opgepakt te worden.

**Comment by Poofy83** [comment]
Een ander icoon is eenvoudig te kiezen, ik zal een meer neutraal icoon inzetten.

**Comment by MichielDHVD** [comment]
Het icoontje in het formulier is op dit moment niet klikbaar. De wens is dat het icoon klikbaar is zodat de developers er zelf een datepricker achter kunnen hangen.

**Comment by tfrijsewijk** [comment]
Het is geen button, we kunnen het niet oplossen. De datepicker werkvorm die jij zoekt moeten we overleggen
