### ISSUE TITLE
Buttons in form .group-static documentatie uitwerken

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#1190]
## Aanleiding
Bij het bespreken van het voorbeeld 'Verzoeken indienen' ontdekten we een implementatie die niet ondersteund wordt door de DSO Toolkit. In de huidige implementatie wordt namelijk een 'form-group' gebruikt met enkel een button erin. Op deze manier wordt afstand tot andere form-group elementen afgedwongen, zie screenshot.

## Werkzaamheden
Zouden we deze implementatie willen opnemen in de DSO Toolkit als 'Group button'? Om zo het gebruik van losse buttons ook binnen een formulier vast te leggen?

**Comment by tfrijsewijk** [comment]
@bramhoosemans 

Dit is een issue wat ook maar terugkomt en elke keer als ik er naar kijk wordt ik gewoon niet blij.

* Het is een een werkvorm waar jullie ook niet precies weten wat jullie ermee willen
* De aangedragen oplossing is een hack, maar door 'm te documenteren lijkt het alsof we erachter staan

Inhoudelijk heb ik moeite met de voorgeschreven markup:

```
<div class="form-group dso-static">
  <div class="dso-label-container">
    <span class="control-label"></span>
  </div>
  <div class="dso-field-container">
    <button type="button" class="btn btn-link">
      <dso-icon icon="download" class="hydrated"></dso-icon><span>Download verzoeken</span>
    </button>
  </div>
</div>
```

Een lege `span.control-label` puur om de verticale marges te realiseren: Dit is iets wat ik niet wil waarborgen.

Het resultaat van dit issue leeft al een tijdje, maarals ik het mij goed herinner was je niet op zoek naar een permanente oplossing: Deze constructie staat op de tocht.

Zoals de oplossing nu wordt voorgesteld kan ik 't niet opnemen. Mocht dit een werkvorm zijn die je wilt aanbieden, dan gaan we _the whole nine yards_. Mocht mijn geheugen mij niet in de steek hebben gelaten en dit inderdaad een tijdelijke situatie is stel ik voor dat je de developers op bovenstaande markup _suggestie_ wijst en ze die laten implementeren. Je bevindt je dan wel in "no man's land, maar je hebt "iets".

Het PR sluit ik. Wil jij aangeven wat je met dit issue wilt doen?

**Comment by bramhoosemans** [comment]
@tfrijsewijk Het is inderdaad zo dat we momenteel geen andere use-case hebben waarbij men een enkele button in een formulier toepast. Het doel was om te beoordelen of we er überhaupt iets mee moeten in de toolkit; zoals in de aanleiding te lezen is wordt de button in een 'form-group' geplaatst om marges af te dwingen.

Ik kan er prima mee leven als we deze constructie niet opnemen in de toolkit. We borgen het alternatief namelijk al wel. In dit geval zou de download knop links naast de indien knop moeten staan.

Nog één laatste vraag voordat we dit issue sluiten met "won't do":
- Waarom zouden we de markup wijzigen met de toevoeging 'dso-static' als alleen 'form-group' al het gewenste resultaat geeft?

**Comment by tfrijsewijk** [comment]
>Waarom zouden we de markup wijzigen met de toevoeging 'dso-static' als alleen 'form-group' al het gewenste resultaat geeft?
Functioneel zit het verschil voornamelijk in responsive gedrag: Een `.form-group` in `.form-horizontal` gedraagt zich als een `.row`: Het trekt 16px (de helft van de gutter) naar buiten toe. De `.dso-label-container` en `.dso-field-container` gedragen zich als kolommen en hebben een links en rechts een padding van 16px waarmee er tussen de kolommen de gutter van 32px ontstaat.

Daarnaast heeft een `.form-group` in `.form-horizontal` nog verticale padding van 7px

Netto is er ook een verschil tussen een kale `.form-group` en `.form-group.dso-static` met 'n lege `.dso-field-container`:
* `.form-group` heeft een verticale ruimte boven van **24px**
* `.form-group` met lege `.dso-field-label` heeft verticale ruimte boven van 24px + 16px = **40px**
* `.form-group` zonder `.dso-field-label` heeft verticale ruimte boven van **16px**

Dus eigenlijk zou ik dan voor de laatste pleiten:

```
<div class="form-group dso-static">
  <div class="dso-field-container">
    <button type="button" class="btn btn-link">
      <dso-icon icon="download" class="hydrated"></dso-icon><span>Download verzoeken</span>
    </button>
  </div>
</div>
```

![image](https://user-images.githubusercontent.com/9696261/125254787-17450500-e2fb-11eb-8549-44d219878eeb.png)

**Comment by bramhoosemans** [comment]
Dank, ik zal het doorgeven. Wat mij betreft mag dit issue gesloten worden.
