### ISSUE TITLE
Fieldset modifier zodat naast de legend "iets" geplaatst kan worden

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#1191]
![101_activiteiten](https://user-images.githubusercontent.com/9696261/122761759-df6b1480-d29c-11eb-8b29-f74ed61c9bed.png)

**Comment by tfrijsewijk** [comment]
https://dso-toolkit.nl/25.0.0/components/detail/activiteiten.html

**Comment by tfrijsewijk** [comment]
# Context

Context is een HTML/CSS component en bestaat uit drie classes:

* `dso-context-wrapper`
* `dso-context-label`
* `dso-context-container`

En kan op de volgende manier ingezet worden:

```html
<div class="dso-context-wrapper">
  <label class="dso-context-label">
    Resultaten
  </label>
  <div class="dso-context-container">
    <dso-dropdown-menu />
  </div>
  <div class="row">[..]</div>
</div>
```

```html
<fieldset class="dso-context-wrapper">
  <legend class="dso-context-label">
    Resultaten
  </legend>
  <div class="dso-context-container">
    <dso-dropdown-menu />
  </div>
  <div class="row">[..]</div>
</fieldset>
```

## Openstaande punten

Ik ben nog niet zo weg van de term Context: Dat is namelijk een concept binnen React. Suggesties?

**Comment by daverhelst** [comment]
We gaan dit waarschijnlijk oplossen met een `display: flex` constructie, lijkt de term `dso-flex-wrapper` iets? Of `dso-flex-context-wrapper` -> dat ligt lekkerder bij de kindjes: dso-flex-context-label en dso-flex-context-container

**Comment by tfrijsewijk** [comment]
Dus we stappen over van een React concept naar een CSS3 concept. Van de drup naar de regen ;-)

**Comment by gofix** [comment]
`dso-suffix-wrapper` ? waarbij `suffix` een term is die we natuurlijk uit de bootstrap wereld kennen, en die daar bedoeld was om een icoon aan/naast een knop te plakken, als ik het me goed herinner.
Of... `dso-superrow` ...
