### ISSUE TITLE
 Zwart 5% toevoegen en Zwart 10% veranderen

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#120]
Zwart 5% hex: #f2f2f2 toevoegen 
De 100% mag worden verwijderd want die wordt vrijwel niet meer gebruikt. Deze is immers te intens.

De kleur zwart 10% veranderen naar Hex: #e5e5e5. 

De kleur zwart 10% klopte ook niet. Dit was zwart 10% gebaseerd op 10% van #191919. Ze zijn vrijwel identiek in uiterlijk maar voor consistentie is dit beter. 

Het rijtje betreffende zwart wordt dan: 

Zwart 90% #191919  /   RGB(25,25,25)
Zwart 60% #666666  /   RGB(102,102,102)
Zwart 10% #e5e5e5   /  RGB(229,229,229)
Zwart 5% f2f2f2  /  RGB(242,242,242)

@DjangoBlok

**Comment by DjangoBlok** [comment]
Mooi!

**Comment by MichielDHVD** [comment]
RGB waardes even voor alle onderdelen toegevoegd @Poofy83

**Comment by VolleMelk** [comment]
De kleuren zijn doorgevoerd in de documentatie, alleen wordt de kleur `$zwart` nog wel gebruikt:

![image](https://user-images.githubusercontent.com/9696261/40922666-0de3d06a-6813-11e8-9686-79196040bd7f.png)

Ontmantelen we de kleur `$zwart` en gaan we voor `$grijs-90` ? Overigens is `$grijs-90` ook 'n rare naam, lijkt mij eerder `$zwart-90`
