### ISSUE TITLE
Storybook CSS Component - Jumbotron

### ISSUE THREAD

**Issue by daverhelst** [dso-toolkit/dso-toolkit#1206]
Voor storybook gaan we verschillende varianten van stories opnemen. In dit issue zorgen we er voor dat de Jumbotron als CSS component beschikbaar wordt.

**Werkzaamheden:**
- Maak een nieuw storybook CSS component
- Neem de markup over van het fractal component en herschrijf deze naar lit-html

**Comment by tfrijsewijk** [comment]
Dit component gaan we verwijderen in #1458 .
