### ISSUE TITLE
Bordered definition list (voor in Stelselcatalogus)

### ISSUE THREAD

**Issue by Anto1nette** [dso-toolkit/dso-toolkit#1209]
### Aanleiding
In de Stelselcatalogus worden op veel plekken definities gegeven. Behalve een term en een definitie (zoals in een definition list) bevat deze ook een link naar de (Linked Data) standaard van de term. Daarnaast is er een wens om de termen ook in begrijpelijke taal toe te lichten.
 
### Ontwerp
Zie bijlage voor schetsen

- Header hoort er niet bij
- Naam variant bordered
- Variant van definition list met borders
- Dubbele punt in voorbeeld pagina met sr-only opnemen (visueel verbergen)

![2 1 Begrip - details open](https://user-images.githubusercontent.com/1033595/124327970-096be300-db89-11eb-89da-fdb0ca979b07.png)

**Comment by gofix** [comment]
@PieterVerheij als ik expliciet naar het responsive gedrag kijk van definition list, valt me op dat de situatie met dt + dd + dd (dus: meerdere definition data elementen voorafgegaan door 1 definition term) best lelijk is qua regelafstanden:
![image](https://user-images.githubusercontent.com/2689559/124749064-14759900-df24-11eb-95c6-8ab5216af580.png)
Dat was eerder echter ook al zo, alleen dan nog erger:
![image](https://user-images.githubusercontent.com/2689559/124749170-2e16e080-df24-11eb-9dbc-7106b69a0859.png)
Ik weet niet of we hier nu binnen de scope van dit issue naar zouden moeten kijken...?

**Comment by bramhoosemans** [comment]
@gofix @PieterVerheij Het is eigenlijk een losstaand probleem, maar ik ben wel benieuwd waarom er in deze situatie 8px padding onder de dt wordt geplaatst? Ik kan überhaupt geen responsive ontwerp vinden..

![Schermafbeelding 2021-07-07 om 13 38 00](https://user-images.githubusercontent.com/598735/124753075-da5ac600-df28-11eb-8c86-7037e396a08d.png)

De marge tussen twee of meer dd's zouden we inderdaad weg kunnen halen. Op dit moment is tie best globaal voor alle dd's behalve de laatste:

![Schermafbeelding 2021-07-07 om 13 42 04](https://user-images.githubusercontent.com/598735/124753554-666ced80-df29-11eb-948c-27d4e00d52f5.png)

**Comment by PieterVerheij** [comment]
Het was een opzetje van mij. 
Maar bedoel je op de smalle viewport voor `dt + dd` en `dd+dd` altijd 16px tussenruimte?

**Comment by bramhoosemans** [comment]
@PieterVerheij Ik zou zeggen voor de verticale weergave (ook smalle viewport) geen tussenruimte tussen dd + dd. Ik hoop dat het plaatje helder is ;-)

![Schermafbeelding 2021-07-07 om 13 58 35](https://user-images.githubusercontent.com/598735/124755613-ded4ae00-df2b-11eb-8e33-43afdea75a1e.png)
