### ISSUE TITLE
Icon only buttons moeten sr-only hebben

### ISSUE THREAD

**Issue by Anto1nette** [dso-toolkit/dso-toolkit#1210]
### Aanleiding
Bij het realiseren van de web components, waarbij de markup van componenenten nog eens extra onder de loupe wordt gelegd, komen soms vraagtekens naar boven, zoals nu deze: In component "Label" kan een 'verwijder'-knop zijn opgenomen. Deze krijgt momenteel een attribuut "title" om een 'accessible name' te hebben. Elders doen we dat met een '.sr-only' tekstfragment in de knop (bv. bij de sluitknop van "Banner"), en in de "modal" gebeurt dit met een aria-label.

Label: https://dso-toolkit.nl/24.3.1/components/detail/label-css.html
Banner: https://dso-toolkit.nl/24.3.1/components/detail/banner.html
Modal: https://dso-toolkit.nl/24.3.1/components/detail/modal.html

Welke van deze technieken is nu eigenlijk het beste? 
Persoonlijk neig ik soms naar 'title' omdat de 'ziende'/muizende mensch daar ook nog iets aan heeft, maar title wordt volgens mij als een inferieure oplossing voor 'accessible name' gezien.

### Werkzaamheden
Uitzoeken en beschrijven wat voor dit soort icon-only knoppen de best practice is.
Alles langs lopen in storybook en css nalopen en sr-only toepassen.

**Comment by timveld** [comment]
Er is indertijd een duidelijke keuze gemaakt voor sr-only ipv title, misschien ook omdat sr-only bij uitgeschakelde CSS wel zichtbaar is en title niet? (weet niet of dat zo is) Wat mij betreft geen aanleiding om daar nu op terug te komen dus waar nog titles worden gebruikt kunnen we beter de sr-only nemen.
