### ISSUE TITLE
Card Grid

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#1216]
### Aanleiding
Op de homepage is behoefte om de verschillende ingangen van de catalogus kort toe te lichten en te ontsluiten.

### Werkzaamheden

- [ ] Een card grid bouwen die de spacing verzorgt tussen cards, horizontale variant.
- [ ] Cards moet visueel representeren wat door teams is/wordt geimplementeerd. 
- [x] Huidige cards implementatie naam verandert (card-list bijv.) om verschillen duidelijk te duiden. 
- [ ] Documentatie bij card.config.yml bijwerken

### Ontwerp
![image](https://user-images.githubusercontent.com/36912722/124720831-d5861a00-df08-11eb-8c2f-b5ebc5616c3c.png)
 
![image](https://user-images.githubusercontent.com/36912722/124720850-dcad2800-df08-11eb-92e8-58d8be8ef668.png)

### Testen
Acceptatiecriteria
zie bijgevoegde specs voor afmetingen
shadow: 0 4px 8px 0 rgb(0 0 0 / 20%)
gehele card is clickable
geschikt voor Row equal heights 
content in de card: tekst

**Comment by gofix** [comment]
Beeld op https://css.dso-toolkit.nl/_1216-Card-Grid/?path=/story/card-grid--card-grid
