### ISSUE TITLE
Lege elementen zoals sr-only, id's, legends en labels in de toolkit

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#1220]
Ontbrekende sr-only span, label en id's toevoegen in de voorbeelden op dso-toolkit.nl.

- https://dso-toolkit.nl/25.0.0/components/detail/list-button.html
- https://dso-toolkit.nl/25.0.0/components/detail/activiteiten.html

Ook gespot bij:

- https://dso-toolkit.nl/25.1.0/components/detail/documenten.html

![Schermafbeelding 2021-07-07 om 16 19 51](https://user-images.githubusercontent.com/598735/124776578-d8503180-df3f-11eb-8750-b9eb35f76b26.png)
![Schermafbeelding 2021-07-08 om 09 23 02](https://user-images.githubusercontent.com/598735/124893819-5f9eb300-dfdb-11eb-93d2-e28a3e9f18e6.png)

**Comment by daverhelst** [comment]
@bramhoosemans de aanpassingen zijn hier te zien:
https://dso-toolkit.nl/_1220.lege-spans-en-ids-in-toolkit/components/detail/list-button.html
https://dso-toolkit.nl/_1220.lege-spans-en-ids-in-toolkit/components/detail/documenten.html
https://dso-toolkit.nl/_1220.lege-spans-en-ids-in-toolkit/components/detail/activiteiten.html

Zoals telefonisch besproken zal op de documenten voorbeeld pagina een label zichtbaar zijn, we hebben gekozen voor "Documenten"

**Comment by bramhoosemans** [comment]
Thanks @daverhelst!

Twee vragen/opmerkingen:
- Bij list-button en activiteiten zie ik (nog) geen label element. Is dat niet nodig?
- Bij files en documenten is de inhoud van de `for` statements in het label verschillend met de `id` van de input. Zouden die niet gelijk moeten zijn?

**Comment by daverhelst** [comment]
- Zeker, goed gezien! Ik had deze ook al genoteerd, de input bij een `input-number` _in_ een `list-button` moet ook een bijbehorende label hebben (lijkt mij). Maar dat leek me los te staan van dit issue?
- Klopt enigszins. Ik had dit ook al kort aangekaart in ons gesprekje aan de telefoon. Dit is een uitzonderlijk geval aangezien de `dso-files` geen input element in de `dso-field-container` heeft staan. De `input type="file"` heeft namelijk een bijbehorend label. Het label wat in de `dso-label-container` staat relateert aan niks. @gofix Of zouden we deze ook naar de `input type="file"` moeten laten verwijzen?

**Comment by bramhoosemans** [comment]
2 losse issues aanmaken @bramhoosemans
