### ISSUE TITLE
Group Files button toetsenbord focus styling kapot sinds 25.0.0

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#1221]
Als de 'upload button' focus ontvangt met het toetsenbord is de styling kapot. Als je er vervolgens met de cursor op gaat staan is het label niet meer zichtbaar.

![Schermafbeelding 2021-07-08 om 08 56 52](https://user-images.githubusercontent.com/598735/124894058-97a5f600-dfdb-11eb-98ef-811cf1e6657d.png)
![Schermafbeelding 2021-07-08 om 08 56 59](https://user-images.githubusercontent.com/598735/124894068-9a085000-dfdb-11eb-9bdc-6ddab5896747.png)

**Comment by tfrijsewijk** [comment]
Nou, je verwacht het niet maar dit is toch lastiger op te lossen.

Er zijn twee problemen:
* Focus styling: Het icoon wordt groen
* Focus met hover: De achtergrond van de knop wordt groen

Het tweede is prima op te lossen.

Maar de eerste is lastig. Want de focus state van een secondary button in Chrome en Firefox zien er zo uit:

![image](https://user-images.githubusercontent.com/9696261/124924168-70f7b780-dffb-11eb-9b9c-571d67e87000.png)
![image](https://user-images.githubusercontent.com/9696261/124924213-80770080-dffb-11eb-8b83-863bf51a432b.png)

Default, vanilla styling baby.

En nou komt het: Het element wat eruit ziet als een knop is helemaal geen knop, maar een `<label>`. Dit hebben we gedaan omdat het dan mogelijk is om zonder scripting de `input[type="file"]` te activeren.

Een label is niet focusable, maar een `input[type="radio"]` wel, en daarom hebben we de label _na_ de `input[type="radio"]` gezet en kunnen we de selector `input[type="radio"]:focus + label` gebruiken om de "knop" te stijlen.

Maar! We hebben geen custom focus styling meer. Dus wat stijlen we dan?

Ik heb al geprobeerd om de browser te tricken:
* `<label role="button">` (negeer semantiek): Krijgt geen focus styling
* `<label tabindex="0">` Krijgt wel focus styling, maar pas als het label element is gefocussed. Het activeren het label element met Enter of Space doet niets, dus je krijgt 'n loze focus state.

We hebben een korte en lange termijn oplossing nodig.

Korte termijn:
Ik fix focus en hover combinatie styling en voor focus:
* Ik maak de hele knop groen met wit icoon en witte tekst. Dat betekent dat deze knop custom focus styling krijgt EN er nog eens anders uitziet dan een normale secondary button
* We maken zelf een outline-achtige stijling
* We veranderen niets, het groene icoon is de enige indicator dat er focus stijling is

Lange termijn:
* Afstappen van de `input[type="file"] + label` constructie en een echte `button` en scripting gebruiken. (Waar staat `label` dan nog? Hoe betrouwbaar is deze oplossing?)
* File button herstijlen tot een component wat er niet uitziet als een button waardoor custom focus styling te rechtvaardigen is. 
* Op alle buttons custom focus styling toevoegen 🤡 (serieus)
* We accepteren de custom outline-achtige focus stijling van de korte termijn oplossing.

@bramhoosemans Tell me!

**Comment by bramhoosemans** [comment]
@tfrijsewijk Voor de korte (en mogelijk lange) termijn stel ik voor om specifiek de "button" in Group Files custom focus styling te geven. We geven overigens al meerdere formulier-elementen custom focus styling mee, zie input, radios, checkboxes en select.

Op de lange termijn zouden we wellicht opnieuw kunnen afwegen welke strategie we moeten voeren mbt custom focus styling. Maar helemaal zwart/wit is het niet zou ik zeggen.

Schets:
![Schermafbeelding 2021-07-08 om 15 50 00](https://user-images.githubusercontent.com/598735/124941044-c7202700-e00a-11eb-9d65-a5a0805408be.png)

**Comment by tfrijsewijk** [comment]
Dank! Ik heb 'm uitgebracht in de 25.1.1
