### ISSUE TITLE
Packages missen artifacts

### ISSUE THREAD

**Issue by WiebeCnossen** [dso-toolkit/dso-toolkit#1223]
Onder andere `loader` mist in @dso-toolkit/core. Misschien dat dat de bedoeling is, maar dan zou het als breaking change gedocumenteerd moeten zijn.

Nu gebeurt in de implementatie

```
import { applyPolyfills, defineCustomElements } from "@dso-toolkit/core/loader";
```

en dat werkt in 25.1.1 niet meer.

Daarnaast missen de volgende artifacts in andere packages:
* `@dso-toolkit/core` - `/dist`
* `@dso-toolkit/css` - `/dist`
* `@dso-toolkit/react` - `/dist`
* `dso-toolkit` - `/hydrate`

**Comment by tfrijsewijk** [comment]
Eigenlijk was de build en deploystraat voor alle package stuk sinds 25.0.0 maar omdat juist die release met de hand is gedaan is die bug later aan het licht gekomen.

Ik heb alle packages icm. CI/CD langsgelopen en een nieuwe release uitgebracht: 25.1.2.
