### ISSUE TITLE
Vaste toelichtingen hebben geen duidelijke relatie met de vraag of antwoord waar ze bijhoren

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#1229]
Markup bij vaste toelichtingen in de toolkit hebben geen duidelijke relatie met de bijbehorende vraag of antwoordoptie.

**Werkzaamheden**
- Toelichting op de vraag dmv aria-describedby koppelen aan de fieldset.
- Als het antwoord een toelichting heeft die dmv aria-describedby koppelen aan radio of checkbox.

**Component:**
- https://dso-toolkit.nl/master/components/detail/info.html

**Form elementen:**
- https://dso-toolkit.nl/master/components/detail/group-checkboxes.html
- https://dso-toolkit.nl/master/components/detail/group-input.html
- https://dso-toolkit.nl/master/components/detail/group-input.html
- https://dso-toolkit.nl/master/components/detail/group-radios.html
- https://dso-toolkit.nl/master/components/detail/group-select.html
- https://dso-toolkit.nl/master/components/detail/group-static.html
- https://dso-toolkit.nl/master/components/detail/group-textarea.html

**Storybook**
- https://css.dso-toolkit.nl/26.0.0/?path=/story/selectable--with-info&args=infoFixed:true
- https://core.dso-toolkit.nl/26.0.0/?path=/story/selectable--with-info&args=infoFixed:true

**Comment by gofix** [comment]
Voor de volledigheid: het gaat dus alleen om VASTE TOELICHTINGEN. Niet de toelichtingen die uitklappen uit een infobutton.

![image](https://user-images.githubusercontent.com/2689559/128134602-6e2d4d5c-5aee-4460-8144-66735f3a32b8.png)

**Comment by bramhoosemans** [comment]
Klopt.
