### ISSUE TITLE
Toegankelijke helpteksten, toelichtingen en validatiefoutmeldingen

### ISSUE THREAD

**Issue by Anto1nette** [dso-toolkit/dso-toolkit#1238]
### Waar
Alle formulier invoerelementen.

### Aanleiding
Onder het veld staat een help tekst, bijvoorbeeld "Minimaal 6 tekens waarvan 1 leesteken". Maar deze instructie is niet gekoppeld aan het veld.

### Werkzaamheden
- ARIA toepassen zoals gewenst is:
Instructie én validatie fout met aria-describedby koppelen.
aria-invalid="true" toevoegen bij een validatie fout
https://dso-toolkit.nl/26.0.0/components/detail/group-input.html (bij input-date ontbreekt deze)
- Technische documentatie bijwerken.

Voorbeeld/inspiratie
https://medium.com/pulsar/creating-accessible-input-errors-and-help-text-74c7e00e757a

```
 <div class="form__group has-error">
    <label for="name" class="control__label">Name</label>
    <div class="controls">
        <input id="name" name="name" type="text" aria-describedby="guid-836139621 guid-677110833" aria-invalid="true" class="form__control">
        <span class="help-block is-error" role="alert" id="guid-836139621"><i aria-hidden="true" class="icon-warning-sign"></i> Please enter your full name</span>
        <span class="help-block" id="guid-677110833">Your full name, including any middle names</span>
    </div>
</div>
```

**Comment by daverhelst** [comment]
Het `aria-describedby` die je zou verwachten op de input die door de `dso-date-picker` wordt gemaakt, zou dus moeten gaan verwijzen naar een element dat in het Light DOM leeft.

Andersom liepen we al tegen een uitdaging aan omtrent het label bij de `dso-date-picker`: https://github.com/dso-toolkit/dso-toolkit/issues/1164

@gofix @tfrijsewijk

**Comment by daverhelst** [comment]
Misschien moeten we dit voor de `dso-date-picker` nu nog maar niet doen, maar meenemen in bovenstaand gelinkt issue.

**Comment by gofix** [comment]
In de groepsvormen (radios, checkboxen) (die dus een `<fieldset>`  krijgen, worden zowel `dso-info` als `dso-help-block` gerefereerd vanuit de fieldset, met een `aria-describedby`. Ik denk dat `dso-message` dezelfde behandeling moet krijgen.

**Comment by gofix** [comment]
Ik vind 'm fraai zo, ben reuze benieuwd of @timveld dat ook zo ervaart.

Even wat extra toelichting: formulierwerkvormen kunnen voorzien worden van een:
- foutmelding (een `dso-message`)
- helptekst (een `dso-help-block`)
- statische infotekst (een `dso-info`)

Al deze onderdelen krijgen nu een uniek ID, en daarnaar wordt verwezen vanuit:
- als het een 'simpele' inputvorm is: de input zelf
- als het een complexe groepsvorm is: de fieldset

Dit verwijzen gaat met het `aria-describedby` attribuut, dat in het extreemste geval dus zelfs naar 3 (!) andere elementen kan verwijzen. Zie voor deze extreemste vormen bijvoorbeeld:
- bv. voor de 'select': https://dso-toolkit.nl/_1238.Toegankelijke-helptekst-en-validatie-fouten-dmv-ARIA/components/preview/group-select--input-select-allmessages.html (in de `aria-describedby` staan maar liefst 3 ids `errorTextId_input-select-allmessages helpTextId_input-select-allmessages infoTextId_input-select-allmessages`)
- bv. voor radios: https://dso-toolkit.nl/_1238.Toegankelijke-helptekst-en-validatie-fouten-dmv-ARIA/components/detail/group-radios--input-radio-allmessages.html (zelfde, maar dan op de fieldset)

**Comment by bramhoosemans** [comment]
@gofix Alles werkt zoals verwacht; alle gekoppelde elementen worden na elkaar voorgelezen. Ook bij de extreemste vormen met bijvoorbeeld radios. Wel had ik moeite de focus op de groep te zetten met toetsenbord, maar dat zal wel een skill zijn die @timveld wel bezit ;-)

![Schermafbeelding 2021-11-10 om 09 40 31](https://user-images.githubusercontent.com/598735/141079287-0d66f72b-2a41-4af6-95a3-2d5a1e827eb8.png)

Getest op OS Monterey met VoiceOver in laatste build Chrome en Firefox. Helaas krijg ik VirtualBox met NVDA nog niet draaiende op m'n laptop...
