### ISSUE TITLE
Search bar: verwijderen varianten zonder label

### ISSUE THREAD

**Issue by Anto1nette** [dso-toolkit/dso-toolkit#1239]
### Waar
Search bar component (https://dso-toolkit.nl/26.0.0/components/detail/search-bar.html)

### Aanleiding
Er zijn varianten van search bar zonder label / accessible name. Dat is een WCAG afwijking.
Refinement: zijn deze varianten nodig / wenselijk en wanneer / waarom?
Zo ja, dan zou je de placeholder als label kunnen gebruiken waarbij dubbel voorlezen moet worden voorkomen.

### Werkzaamheden
Search Bar zonder label voorbeelden verwijderen (GEEN LABEL, WEL ICON en GEEN LABEL, GEEN ICON).

**Comment by tfrijsewijk** [comment]
@Anto1nette: Is dit nog van toepassing?

**Comment by bramhoosemans** [comment]
@tfrijsewijk @Anto1nette  Ja, deze is nog relevant.

Het gaat hier om het verwijderen van de voorbeelden; de documentatie over de gewenste @for naar het @id van de search bar input als er geen label wordt gebruikt wordt later verwerkt.

**Comment by gofix** [comment]
Ik zie inderdaad dat deze varianten niet meer getoond worden:
![image](https://user-images.githubusercontent.com/2689559/152516713-31189491-a999-4064-99c8-0c60aa7f4cbc.png)

https://dso-toolkit.nl/_1239.Search-bar--verwijderen-varianten-zonder-label/components/detail/search-bar.html

Lijkt me helemaal de bedoeling, jou ook @MichielDHVD ?

**Comment by gofix** [comment]
Zoals zojuist besproken @MichielDHVD, staat ook nog een wens open in documentatie te verwerken dat de label-loze variant natuurlijk wel zou kunnen worden ingezet als in een omliggende werkvorm al een label met een `for` wordt verstrekt, zoals dat bv. het geval is in een form (bv. https://dso-toolkit.nl/33.2.0/components/detail/group-search-bar.html). De vraag is even of we dat in dit ticket nog mee zouden moeten opnemen (in dat geval: graag een suggestie/voorstel) of dat we dat in een ander ticket doen.

**Comment by bramhoosemans** [comment]
@gofix maakt een voorzet voor documentatie, zodat we het direct kunnen afronden.

**Comment by gofix** [comment]
@MichielDHVD, @bramhoosemans zie documentatie tabblad bij https://dso-toolkit.nl/_1239.Search-bar--verwijderen-varianten-zonder-label/components/detail/search-bar.html -> zoiets dan maar?
