### ISSUE TITLE
Deprecated toelichting verwijderen 

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#1241]
De ondersteuning voor de 'oude' werkwijze (toelichting vraag onder antwoorden) ook écht verwijderen. Gerelateerd aan https://github.com/dso-toolkit/dso-toolkit/issues/920

**Comment by gofix** [comment]
In het kader van de deprecated rode dingen, kwam ik ook deze nog tegen:
![image](https://user-images.githubusercontent.com/2689559/127894299-8a8653e9-ea3b-42ab-8da9-a650c022a6f1.png)

Valt buiten scope van _dit_ issue, maar... moet dit ook nog een keer weg? `.dso-description`, that is...

**Comment by bramhoosemans** [comment]
@gofix Dank, ik heb een nieuwe taak aangemaakt in de volgende milestone. Heeft geen haast, maar goed om zaken ook echt op te ruimen ;-)
