### ISSUE TITLE
Badges component redesign

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#125]
Omdat de labels worden aangepast lijkt het me ook slim om de badges ook aan te passen. 

De badges hebben op dit moment nog geen eigenkopje in de toolkit maar worden wel gebruikt. Zie bijvoorbeeld https://www.dso-toolkit.nl/2.0.0-alpha.0/components/detail/header.html 

Achter _over ons_ staat een badge met 12. Het grijs in combinatie met de text haalt de juiste contrast ratio niet. 

De aanpassing zullen op veel plekken overeenkomen met het label component alleen de corners zijn afgerond. Zoals ze nu dat al zijn. 

![badges](https://user-images.githubusercontent.com/36912722/39981950-fb810742-5752-11e8-86ae-f45d78dc4f68.png)

**Comment by Poofy83** [comment]
Prima, duidelijk zo, Dit gaan we oppakken en het sluitkruis als variant hierop toevoegen

**Comment by tfrijsewijk** [comment]
Merged

**Comment by tfrijsewijk** [comment]
https://www.dso-toolkit.nl/3.0.0-alpha.0/components/detail/badge.html

**Comment by MichielDHVD** [comment]
Ziet er goed uit wordt verplaatst naar Done

**Comment by DjangoBlok** [comment]
Het valt me nu op dat je een groenige kleur hebt gekozen voor een warning.
Dat lijkt me verwarrend. Kunnen we daar ook oranje voor gebruiken?

**Comment by MichielDHVD** [comment]
Ik verplaats deze om te beginnen even terug naar To verify.

De gele kleur voor waarschuwing wordt ook gebruikt voor de Alert. 

https://www.dso-toolkit.nl/3.0.0-alpha.0/components/detail/alert.html

Dat is de eerste reden dat ik het bij geel wil houden. Ik snap dat Oranje wat feller en meer opvallend overkomt. Maar dit is meer in de lijn met de vormgeving over de gehele toolkit. En voor de echt belangrijke gevallen hebben we de rode. 

Verder, wil je oranje gebruiken dan moet de tekst zwart blijven. Omdat het kleine tekst is en anders wordt de contrast waarde voor de WCAG niet gehaald. Dus krijg je oranje (#e1700) plus zwarte tekst. Probleem is dan wel dat als er een primaire button op de pagina plus een waarschuwingslabel dan krijg je oranje met wit en oranje met zwart. Daar ben ik geen fan van twee verschillende kleur combinaties op zon manier. 

Dat zijn mijn argumenten om het op geel te houden.

**Comment by MichielDHVD** [comment]
![badges](https://user-images.githubusercontent.com/36912722/45156831-9aef5680-b1df-11e8-91a3-1834c2b747a2.png)

**Comment by tfrijsewijk** [comment]
In het #103 label issue is besproken de tekst niet dikgedrukt te maken. Dat is ook in dit component gedaan
