### ISSUE TITLE
Storybook CSS Component - Navbar

### ISSUE THREAD

**Issue by daverhelst** [dso-toolkit/dso-toolkit#1252]
Aanleiding

Met ontwikkeling nieuwe header moet het Navigations component omgezet worden naar een CSS/HTML component. Een losse story voor de complete header wordt ook opgezet. 

Werkzaamheden
Maak een nieuw storybook CSS component
Neem de markup over van het fractal component en herschrijf deze naar lit-html
Ontwerp

Nvt

Testen
Functionaliteit en looks hetzelfde als Html/css component

Acceptatiecriteria
Functionaliteit en looks hetzelfde als Html/css component

**Comment by gofix** [comment]
Wat is eigenlijk de 'dso navbar'? Is dat deze https://dso-toolkit.nl/31.0.0/components/detail/navigations.html @daverhelst ?

**Comment by gofix** [comment]
Wordt dit niet misschien helemaal anders omdat we met de header aan de slag gaan? Of moet deze navbar ook nog los inzetbaar zijn? @MichielDHVD ?

**Comment by MichielDHVD** [comment]
Navbar wordt los inzetbaar

**Comment by gofix** [comment]
Mooi dat deze nu zijn weg heeft gevonden naar het HTML/CSS storybook:
https://css.dso-toolkit.nl/_1252.Storybook-CSS-Component---Navbar/?path=/story/navbar--primary
https://css.dso-toolkit.nl/_1252.Storybook-CSS-Component---Navbar/?path=/story/navbar--secondary

Wat nog te doen met https://dso-toolkit.nl/_1252.Storybook-CSS-Component---Navbar/components/detail/navigations.html ?

Overigens, ondanks het antwoord van @MichielDHVD 
> Navbar wordt los inzetbaar
... vind ik dat toch heel raar, voor de primaire. Die is toch overduidelijk alleen maar (en exclusief) een onderdeel van de (nieuwe) header?

**Comment by MichielDHVD** [comment]
Heb je inderdaad een punt. 

Enigste scenario dat ik zie is dat bijvoorbeeld stelselcatalogus navbar los wil gebruiken van header constructie. Dat is een compleet eigen website. 

Zie afbeelding. Maar dat is ook volgens mij op te lossen in de header variant. 
<img width="1133" alt="Screenshot 2022-01-26 at 12 43 49" src="https://user-images.githubusercontent.com/36912722/151157652-189f5f35-ede6-48c5-a9e9-666bb1e3631e.png">


Voordeel van de primaire dumpen of te wel niet beschikbaar stellen buiten de header. Is dat het component een stuk simpeler qua inzet wordt. 

Het is dan gewoon het sub-navigatie component, niet meer navigations primaire en sub. Hoe zou jij het component positioneren als we primaire header only maken. 

Misschien is dat hetgene dat we kunnen bespreken.

**Comment by gofix** [comment]
We moeten **_nu_** de primaire variant niet dumpen, als ie blijkbaar nog gebruikt wordt. Maar ik denk dat we 'm moeten deprecaten zodra we de header gaan uitbrengen. Dan behouden we alleen de secundaire variant (die we dan inderdaad zouden kunnen omdopen naar subnavigatie).

**Comment by MichielDHVD** [comment]
Akkoord! Pakken we het zo aan.
