### ISSUE TITLE
Visited state in navigatiewerkvormen mag visueel niet zichtbaar zijn

### ISSUE THREAD

**Issue by gofix** [dso-toolkit/dso-toolkit#1263]
In https://github.com/dso-toolkit/dso-toolkit/issues/1256 heeft een flinke refactoring plaatgevonden van buttons en daarmee samenhanged ook link-styling. Daarmee is blijkbaar een foutje geintroduceerd, namelijk dat in dropdown-menus met anchors de visited links paars worden. **edit:** Dit geldt ook voor navigations en pagination.

Speelt zowel het CSS Component als het Web Component "Dropdown menu":
https://www.dso-toolkit.nl/27.1.0/components/detail/dropdown-menu-css.html

**Comment by gofix** [comment]
We zien in nog enkele andere 'navigatie' werkvormen dat visited nu paars is:
- in Navigations
- in Pagination

Het lijkt me dat we dit ook gelijk maar even mee moeten pakken @bramhoosemans @MichielDHVD

**Comment by gofix** [comment]
@tfrijsewijk gaf me al aan dat we eigenlijk in de tests / shots hier toch ook iets voor zouden moeten faciliteren. Al deze states worden nu door Percy niet geshot en dus gaan foutjes daarin niet opvallen. Gaan we nu niet zomaar 1-2-3 iets aan kunnen doen, maar zou wel een krachtige verbetering kunnen zijn.

**Comment by MichielDHVD** [comment]
Eens. Gister al beslist volgens mij dat we dit ook in de extra release wilden mee nemen Bug met High priority.

**Comment by gofix** [comment]
In branch deploy https://dso-toolkit.nl/_1263-v2-visited-states/ is het resultaat van de werkzaamheden te zien. We hebben zelf alle componenten langsgelopen, en deze vergeleken met de situatie van VOOR 25.0.0 (waarin we begonnen met de buttons/anchors refactoring). Daar lijkt het nu weer goed gelijk mee te lopen (maar nu dan dus op de dso-* classes naast de btn-* classes). Het concrete issue (het scampi in dropdown menu, navigations, etc.) is ook opgelost.

Waarom we 'zelf' moesten controleren en Percy dat niet voor ons kon doen? Percy heeft zeker geholpen, maar die maakt alleen shots van de regulare staat van anchors, niet van `:focus`, `:hover`, `:visited`, etc. Dat is ook waarom deze bug ueberhaupt heeft kunnen ontstaan. Eigenlijk zouden we Percy wellicht dus anders moeten gaan inrichten, en laten voeden vanuit Cypress, zodat ook deze states geshot kunnen gaan worden. Maar dat is voor een andere keer (en misschien zelfs een ander jaar).

Bij onze uitgebreide controleronde vielen ons nog wel een aantal zaken op:
Op de 'anchors' pagina bv. werkt de externe link niet. Waarom niet, wel, de console vertelt het:
> Blocked opening 'http://www.google.nl/' in a new window because the request was made in a sandboxed frame whose 'allow-popups' permission is not set.
En inderdaad, op het iframe van fractal staat: `sandbox="allow-same-origin allow-scripts allow-forms allow-modals"`
Het resultaat is dat de `:visited` state ook niet persisteert. Aandachtspuntje dus bij externe links.

Het was ons al een keer opgevallen, maar ook nu weer:
![image](https://user-images.githubusercontent.com/2689559/132459376-5425ae42-299a-432f-b3fb-1e4403232cf2.png)
De `.extern` en `.download` varianten van links laten het icoon (dat op `::after` is geprogrammeerd met een background-image) niet kleuren. Dat kan niet, want dat voorkomen browsers om privacy-redenen.

**Comment by gofix** [comment]
@MichielDHVD zou jij ook nog een laatste (?) blik willen werpen? Dan kunnen we rollen!

**Comment by tfrijsewijk** [comment]
> De `.extern` en `.download` varianten van links laten het icoon (dat op `::after` is geprogrammeerd met een background-image) niet kleuren. Dat kan niet, want dat voorkomen browsers om privacy-redenen.

Zie ook https://github.com/dso-toolkit/dso-toolkit/issues/501

**Comment by MichielDHVD** [comment]
Wanneer je hovert over een link in dropdown hoort deze wit te zijn. Als je nog geen link geclicked hebt klopt dit ook. 
Maar wanneer visited states actief worden dan wordt de tekst on hover zwart en niet meer wit. 

<img width="414" alt="Screenshot 2021-09-08 at 09 41 38" src="https://user-images.githubusercontent.com/36912722/132467541-33fdf7a7-fc71-4a37-ad47-3bfcacbce049.png">
<img width="320" alt="Screenshot 2021-09-08 at 09 41 08" src="https://user-images.githubusercontent.com/36912722/132467537-5a97068c-bd38-48fe-85f2-25501df71fe9.png">
