### ISSUE TITLE
Update Kitty Giraudel's name

### ISSUE THREAD

**Issue by angeliquejw** [dso-toolkit/dso-toolkit#1268]
Hello! The [table example](https://www.dso-toolkit.nl/27.3.0/components/detail/table.html) in the Toolkit uses Kitty Giraudel as a bit of example data, but uses a past name. 

Would you be open to a PR correcting this? There appear to be [12 instances](https://github.com/dso-toolkit/dso-toolkit/search?q=hugo+giraudel) that need to be updated.

Thank you for considering this request!

**Comment by Anto1nette** [comment]
Hi @angeliquejw we will take your request into consideration.

**Comment by gofix** [comment]
@MichielDHVD zie https://dso-toolkit.nl/_1268-namechange/components/detail/table.html

**Comment by MichielDHVD** [comment]
Prima, dankjewel voor het aanpassen en het mag doorgezet worden.
