### ISSUE TITLE
Gedrag Context Component bij lange labels en/of grotere interactieve onderdelen

### ISSUE THREAD

**Issue by gofix** [dso-toolkit/dso-toolkit#1274]
**Aanleiding**
In https://github.com/dso-toolkit/dso-toolkit/issues/1191 is gerealiseerd dat een interactief onderdeel naast het 'label' geplaatst kan worden. Dit vindt zijn toepassing in "Activiteiten", waarin een sorteer-pulldown moet kunnen worden geplaatst.

Deze oplossingsrichting had als uitgangspunt dat het moest werken binnen de fieldset. Vandaar de keuze om 'floats' te gebruiken. Helaas werkt dit niet goed met flexibele content in de labels en sorteeroptie.

Zie:
https://dso-toolkit.nl/master/components/detail/activiteiten.html
https://dso-toolkit.nl/master/components/detail/group-select.html

**Werkzaamheden**
`.dso-context-wrapper`
`.dso-context-label`
`.dso-context-container`
gaan niet meer OP de `<fieldset>` en het `<legend>` ondersteund worden, maar mogen alleen nog maar op `<div>`s. Dit heeft consequenties voor hoe met het label en de legend wordt omgegaan:
- het zichtbare label wordt `aria-hidden`
- de `legend` wordt visueel verborgen (met `sr-only`)
Deze opzet maakt het beoogde ontwerp, het gedrag bij lange labels of grote onderdelen in de `.dso-context-container`, mogelijk. De CSS wordt daarop aangepast.

**Ontwerp**
![page-1-1-132_responsive-gedrag](https://user-images.githubusercontent.com/2689559/135036099-9ee963a8-968b-4db6-adf9-7c64cd5c1492.png)
Als de de sorteeroptie (de inhoud van `.dso-context-container`) niet meer past, gaat deze onder het label vallen,uitlijning rechts blijft behouden.
Uitgebreid: 
[context-ontwerp.zip](https://github.com/dso-toolkit/dso-toolkit/files/7241690/context-ontwerp.zip)

**Testen**
Het resultaat van de werkzaamheden wordt beschikbaar:
- in het HTML/CSS storybook: https://css.dso-toolkit.nl/master/?path=/story/context--label
- in de voorbeeldpagina voor activiteiten: https://dso-toolkit.nl/master/components/detail/activiteiten.html

**Comment by daverhelst** [comment]
In telefonisch overleg besproken met @bramhoosemans :
- "children" gaan uit de `dso-context-wrapper`, en komen direct daar onder.
- `dso-context-wrapper` krijgt standaard een marge van 8px aan de onderkant.

Zie ook de afweging in dit issue van het filterblok, waarin al wordt gesproken over 8px ruimte tussen titel en content daaronder: https://github.com/dso-toolkit/dso-toolkit/issues/1323

**Comment by gofix** [comment]
Getest,:
- in het HTML/CSS storybook: https://css.dso-toolkit.nl/_1274.Gedrag-Context-Component-bij-lange-labels/iframe.html?id=context--legend&args=&viewMode=story#
- op Fractal pagina https://dso-toolkit.nl/_1274.Gedrag-Context-Component-bij-lange-labels/components/preview/filterblok.html
- op Fractal pagina https://dso-toolkit.nl/_1274.Gedrag-Context-Component-bij-lange-labels/components/detail/activiteiten.html

Wat in storybook opvalt is een gekke underlined spatie:
![image](https://user-images.githubusercontent.com/2689559/141175360-ddcfa30a-10dc-4b5b-becc-51278141d1f0.png)
... maar dat is niet nieuws zo te zien en buiten scope van dit issue.

Verder alles conform specs en nader overleg:
- `.dso-context-label` en `.dso-context-container` blijven naast elkaar zolang het past, past het niet schuiven ze onder elkaar met de beoogde 'gap' van 16px;
- onder de werkvorm een ruimte van 8px;
