### ISSUE TITLE
Uitbreiding Accordion component tot 3 visuele thema's

### ISSUE THREAD

**Issue by Anto1nette** [dso-toolkit/dso-toolkit#1280]
### Aanleiding
Aan de hand van inzichten uit eerdere gebruikerstesten is een herontwerp gemaakt van de conclusie Vergunningcheck. In het kort zijn de volgende punten in de huidige conclusie verbeterd:
- Wordt niet gezien resultaat.
- Waarschuwingsiconen zorgen voor stress.
- Overgang van werkzaamheden naar activiteiten.
- Verschillende toestemmingstypen onvoldoende bekend.
- Verwarrende conclusies bij een werkzaamheid (subactiviteiten)

Het nieuwe ontwerp is tijdens twee kwalitatieve gebruikerstesten (06-07-2021 en 20-07-2021) gevalideerd.

In refinement van 16-09-2021 is besproken dat het de voorkeur heeft om het Accordion component uit te breiden ipv een losstaand component te ontwikkelen. Wat specificaties betreft komt de nieuwe 'conclusion' overeen met de 'accordion'.

Naast het ontwerp van conclusie is er door Django ook de wens geuit de accordion uitlijning om te kunnen draaien, zodat het label geheel links staat en de 'pijl' rechts. Deze variatie is gewenst in de Viewer.

### Werkzaamheden
BREAKING CHANGES.
Uitbreiding van het Accordion component.
- Één accordion component met 3 visuele thema’s (default, compact en conclusion). --> betere naamgeving wenselijk.
- Iconen (status iconen) marge 16px ten opzichte van 'dso-status' en rand van de accordion (nu is dat 12px).
- Responsive weergave 'dso-status' is gewijzigd.
- Multiselectable state toevoegen. Meerdere secties van de accordion moeten tegelijk open kunnen zijn; als voorbeeld markup toevoegen.
- Nieuwe ‘add-on’ met icoon toevoegen. Iconen met currentColor (één kleur) kunnen met CSS worden gestyled in de verschillende states.
- Alignment kunnen omdraaien. We leggen de locatie van het label/pijltje en icoon (optioneel) in beide gevallen vast.
- Dso-status en attachment-counter hebben een hele specifieke usecase. We maken ze wel beschikbaar in de verschillende thema’s, maar ondersteunen geen omgedraaide uitlijning.
- De ‘compact’ geneste accordion wijkt wat margins af, omdat er geen ruimte boven en onder de ‘kinderen’ wordt getoond.

### Ontwerp
Zie afbeeldingen in bijlage. De ontwerpen zijn gemaakt op 1440px (breakpoint XL ≥1200px) en 375px (breakpoint XS ≤480px).
[accordion-specifications.zip](https://github.com/dso-toolkit/dso-toolkit/files/7285234/accordion-specifications.zip)

**Comment by gofix** [comment]
Zoals zojuist in tijdens planningsoverleg nog voorbesproken, en daarna nog door @tfrijsewijk en mijzelf nabesproken: in dit issue beperken we ons tot het verhuizen en centraliseren van de styling van dit component naar de css package. In de nabije toekomst zal ook het Web Component worden gerealiseerd, maar dat behoort nu nog niet tot de scope en we hoeven de organisatie van de styling daar nu nog niet structureel op voor te sorteren, dat komt _dan_ wel.

NB @daverhelst we realiseren nu dus al _wel_ het HTML/CSS component in het HTML/CSS storybook.

**Comment by daverhelst** [comment]
Vraag aan @bramhoosemans; We willen graag echte content hebben voor in het Accordion component. Zou je deze kunnen aanleveren, zodat ik die vervolgens kan verwerken?

Het component staat hier: https://css.dso-toolkit.nl/_1280.Uitbreiding-Accordion-component/

Nog een vraag, er is gesproken over het verwijderen van de Fractal vorm, maar deze wordt op een aantal plekken in voorbeeldpagina's gebruikt. Die zullen dan ook weg moeten. Is iedereen hiervan op de hoogte (@bramhoosemans, @tfrijsewijk , @gofix)?

**Comment by tfrijsewijk** [comment]
Goed punt dat het Fractal component op meerdere plekken gebruikt wordt.

Dit component is vanwege z'n complexiteit eigenlijk niet op twee plekken te onderhouden, laat staan dat het dan ook nog eens in Nunjucks is.

Ik realiseer mij dat we hiermee de nodige demo content kwijtraken. Maar toch zou ik ervoor kiezen om alle uitvoeringen van accordion in Fractal te ontmantelen en in te zetten op prioriteitpagina's in de HTML/CSS component Storybook.

Verder ziet het er goed uit, wat realistische content erin en we kunnen mergen.

**Comment by bramhoosemans** [comment]
> Vraag aan @bramhoosemans; We willen graag echte content hebben voor in het Accordion component. Zou je deze kunnen aanleveren, zodat ik die vervolgens kan verwerken?

Ik zou even niet weten welke échte content we in het Accordion component in Storybook moeten zetten:
- Default bevat in de Gebruikerstoepassingen vaak formulieren (https://dso-toolkit.nl/32.1.0/components/detail/accordion-formulieren.html), maar ook tekstuele content of lijsten (https://dso-toolkit.nl/32.1.0/components/detail/verzoeken-indienen.html).
- Compact wordt o.a. gebruikt voor veelgestelde vragen op de landingspagina's (https://pre.omgevingswet.overheid.nl/checken)
- Conclusion is de nieuwe werkvorm met lijsten en info componenten, zie specificaties nieuwe conclusie Vergunningcheck.

Wellicht kunnen we in het component in tekst aangeven welke content er ondersteund wordt? Iets als:
"Een Accordion kan zowel Rich Content als formulieren bevatten."

> Nog een vraag, er is gesproken over het verwijderen van de Fractal vorm, maar deze wordt op een aantal plekken in voorbeeldpagina's gebruikt. Die zullen dan ook weg moeten. Is iedereen hiervan op de hoogte?

@daverhelst Nee, goed dat je het aangeeft! Dat is natuurlijk wel heel jammer, maar ik kan me geen alternatief scenario bedenken als die @tfrijsewijk voorstelt. We raken nu voorbeelden en documentatie in Fractal deels kwijt; kun je aangeven welke precies? Dan maak ik er taken voor aan om in de toekomst deze in Storybook o.i.d. te realiseren.

**Comment by daverhelst** [comment]
@bramhoosemans `Accordion` wordt nu in de volgende voorbeeld pagina's gerenderd:
- Accordion Formulieren (https://dso-toolkit.nl/32.1.0/components/detail/accordion-formulieren.html)
- Documenten (https://dso-toolkit.nl/32.1.0/components/detail/documenten.html)
- Verzoeken indienen (https://dso-toolkit.nl/32.1.0/components/detail/verzoeken-indienen.html)
- Vragen (https://dso-toolkit.nl/32.1.0/components/detail/vragen.html)

**Comment by bramhoosemans** [comment]
> Daarnaast stel ik voor om de vulling in Storybook die van de `Veelgestelde Vragen` (https://pre.omgevingswet.overheid.nl/checken) te laten zijn. Die lijkt me compact (ha!) genoeg om als voorbeeld te dienen zonder lorem ipsum teksten. @tfrijsewijk @bramhoosemans , mee eens?

Wat mij betreft prima.

**Comment by daverhelst** [comment]
@bramhoosemans is mijn lijst hierboven van de plekken waar de `Accordion` wordt ingezet voldoende? Kan ik deze nunjucks gaan verwijderen uit de Fractal omgeving?

**Comment by bramhoosemans** [comment]
> @bramhoosemans is mijn lijst hierboven van de plekken waar de `Accordion` wordt ingezet voldoende? Kan ik deze nunjucks gaan verwijderen uit de Fractal omgeving?

Yes, ga je gang. Ik heb screenshots gemaakt voor het geval dat.. en zal ik toevoegen aan de nieuwe taak.

**Comment by tfrijsewijk** [comment]
FYI: Het bestaande conclusion component is (nog?) niet verwijderd

**Comment by bramhoosemans** [comment]
> FYI: Het bestaande conclusion component is (nog?) niet verwijderd

Dat is maar goed ook; die wordt nog gebruikt. Er is een aparte taak op de backlog om deze te verwijderen in de toekomst.

**Comment by tfrijsewijk** [comment]
Zo'n vermoeden had ik al ;-) Thanks!
