### ISSUE TITLE
Anchor link styling op gekleurde achtergrond niet gelijk

### ISSUE THREAD

**Issue by Anto1nette** [dso-toolkit/dso-toolkit#1281]
### Aanleiding
De underline van tekstlinks in een Alert verdwijnt als erop geklikt is (focus state). Dit is zeer verwarrend in een toon/verberg scenario.

### Bevinding
De anchor styling zou gelijk moeten zijn voor alle componenten met gekleurde achtergrond; zoals gespecificeerd in https://github.com/dso-toolkit/dso-toolkit/issues/1009. In release 20.0.0 uitgebracht. Dit is in de huidige versie niet meer zo.

Underline verdwijnt op hover, active en focus:
https://dso-toolkit.nl/27.3.0/components/detail/alert.html
https://dso-toolkit.nl/27.3.0/components/detail/banner.html - hover/focus krijgt weer paarse kleur, omgevallen in 21.3.0
https://dso-toolkit.nl/27.3.0/components/detail/info.html

Underline blijft staan op hover en focus bij:
https://dso-toolkit.nl/27.3.0/components/detail/highlight-box.html - underline blijft staan op hover/focus, omgevallen in 27.0.0
https://dso-toolkit.nl/27.3.0/components/detail/footer.html - underline blijft staan op hover/focus, uitgebracht in 27.0.0

### Werkzaamheden
Anchor styling op gekleurde achtergrond overal gelijk trekken en underline op focus styling terugbrengen.
- Links blijven altijd zwart (#191919).
- Underline blijft op hover / focus / visited en verdwijnt op active. 

Dit geldt voor de volgende componenten:
- Alert
- Banner
- Highlight-box (standaard, geel)
- Info
- Footer

**Comment by gofix** [comment]
Changes zien er begrijpelijk uit, @bramhoosemans zou jij even willen testen, in de PR heeft @daverhelst URLs geplakt.

**Comment by bramhoosemans** [comment]
Getest en akkoord. Ziet eruit zoals verwacht.
