### ISSUE TITLE
Ozon Content: "Noot -> Description" vervangen met "Toggle Noot" compositie + Description variant "Note" verwijderen.

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#1288]
De XML van Ozon kent een element `Noot` (https://koop.gitlab.io/STOP/standaard/1.3.0/tekst_xsd_Element_tekst_Noot.html). Dit wordt gemapt naar een Description (https://dso-toolkit.nl/35.0.0/components/detail/description--note-expanded.html).

Het blijkt dat Noten ook in tabellen voorkomen. Een Description in een `<td>` is suboptimaal:

* ![image](https://user-images.githubusercontent.com/9696261/164291654-4828a696-d8cd-407e-8fb0-a16174706ea6.png)
* ![image](https://user-images.githubusercontent.com/9696261/164291710-051296f7-9987-4131-bfb6-39aa38994c4d.png)

We gaan `Noot` niet meer naar Description mappen, maar naar een compositie waardoor er een Tooltip wordt getoond:

* ![image](https://user-images.githubusercontent.com/9696261/164291920-6beebf59-c9f5-4a18-841e-138f87d75586.png)
* ![image](https://user-images.githubusercontent.com/9696261/164291949-4758239d-789b-47dd-8359-b7cfffd69552.png)
* ![image](https://user-images.githubusercontent.com/9696261/164291979-00db75d8-4b4c-4e9b-92d4-961fcb5ed33d.png)

In `packages\core\src\components\ozon-content\nodes\noot.node.tsx` wordt een `a` (met `sub`) en `span` gemaakt. Dit wordt een `button` en `dso-tooltip`.

De routine gaat een beetje lijken op hoe het nu met Toggletip (packages\core\src\components\toggletip\toggletip.tsx) is geregeld:
* Tooltip` wordt `stateless`
* De button in `noot.node.tsx` opent/sluit de tooltip
* State bevindt zich in `noot.node.tsx` (dmv. de state helpers op `render()`).

De compositie heeft een eigenwijzere opzet: Geen `@Prop() position`, geen `@Prop() secondary`, geen `@Prop() small` en geen eigen stijling.

In dit issue:
* Maken we de "Toggle Noot" met gebruik van bestaande componenten. Eventuele stijling kan in `ozon-content.scss`, maar het liefst zoveel mogelijk native functionaliteit.
* Van het component "Description" verwijderen we de variant "Note".

**Comment by tfrijsewijk** [comment]
Hier moeten we ook nog wat mee: De XML is geleverd en het component gemaakt 🎉

**Comment by gofix** [comment]
@tfrijsewijk elders besproken: 
> story komt te vervallen we gaan togglenote implementeren
Dit ticket van description wijzigen, of... ander ticket opstellen?

**Comment by tfrijsewijk** [comment]
Ik heb het issue bijgewerkt. @DjangoBlok kan jij reviewen?

**Comment by DjangoBlok** [comment]
@tfrijsewijk ziet er prima uit. 
In je laatste punt zeg je dat het component "description" wordt verwijdert? 
Dat gaat me iets te ver. Dat zou pas kunnen als we besluiten ook begrippen niet meer via de description willen laten tonen.

**Comment by tfrijsewijk** [comment]
Goed punt, ik heb de scope bijgewerkt dat we van het component "Description" de variant "Note" verwijderen. Dat is wat er bij de laatste refinement is besproken.
