### ISSUE TITLE
External link in banner of alert krijgt groen icoontje

### ISSUE THREAD

**Issue by Anto1nette** [dso-toolkit/dso-toolkit#1295]
![Schermafbeelding 2021-10-15 om 13 43 50](https://user-images.githubusercontent.com/1033595/137762843-5e95d514-ceb4-4941-abf2-319328259830.png)
<img width="1139" alt="Schermafbeelding 2021-10-15 om 13 41 24" src="https://user-images.githubusercontent.com/1033595/137762865-09fa4984-7387-4cf3-98bd-b71f84fe7b7b.png">

**Comment by gofix** [comment]
Getest in:
**Alert**

Alert in Fractal
https://dso-toolkit.nl/_1295.External-link-in-banner-of-alert-krijgt-groen-icoontje/components/preview/alert--info.html

Alert in React Storybook
https://react.dso-toolkit.nl/_1295.External-link-in-banner-of-alert-krijgt-groen-icoontje/?path=/story/alert--info

Alert in Web Component Storybook
https://core.dso-toolkit.nl/_1295.External-link-in-banner-of-alert-krijgt-groen-icoontje/?path=/story/alert--info

Alert in HTML/CSS Storybook
https://css.dso-toolkit.nl/_1295.External-link-in-banner-of-alert-krijgt-groen-icoontje/?path=/story/alert--info

**Banner**

Banner in Fractal
https://dso-toolkit.nl/_1295.External-link-in-banner-of-alert-krijgt-groen-icoontje/components/preview/banner--banner-with-headings.html

Banner in React Storybook
https://react.dso-toolkit.nl/_1295.External-link-in-banner-of-alert-krijgt-groen-icoontje/?path=/story/banner--danger-with-headings

Banner in Web Component Storybook
https://core.dso-toolkit.nl/_1295.External-link-in-banner-of-alert-krijgt-groen-icoontje/?path=/story/banner--danger-with-headings

Banner in HTML/CSS Storybook
https://css.dso-toolkit.nl/_1295.External-link-in-banner-of-alert-krijgt-groen-icoontje/?path=/story/banner--danger-with-headings
