### ISSUE TITLE
Logo toekomstbestendig (alternatieve plaatsing beta label)

### ISSUE THREAD

**Issue by Anto1nette** [dso-toolkit/dso-toolkit#1296]
### Aanleiding
De plaatsing van het huidige beta-label vergroot de afstand tussen het logo en de extra tekstregel. Bij livegang zouden alle logo's vervangen moeten worden (zonder beta label), wat leidt tot een ander formaat. We willen hierop voorbereid zijn en zorgen voor een solide logo implementatie.

### Werkzaamheden
- Documentatie pagina aanpassen https://dso-toolkit.nl/master/docs/fundament/logo.html
- Logo als component verwijderen, maar geen deprecation proces (geen rood blok) 
- Logo Webcomponent is een won't do

### Ontwerp
Zie bijgevoegde ontwerpen.
[logo-svg.zip](https://github.com/dso-toolkit/dso-toolkit/files/7366614/logo-svg.zip)

**Comment by daverhelst** [comment]
@bramhoosemans @MichielDHVD Ik heb de logo's aangepast, en dus ook de aanroep in verschillende voorbeeldpagina's. Aangezien er in het eerdere .png logo marges zaten, zit er visueel wezenlijk een verschil op deze plek met het nieuwe .svg logo. Zie bijvoorbeeld hier:

https://dso-toolkit.nl/_1296.Logo-toekomstbestendig/components/detail/header.html

**Comment by gofix** [comment]
We zien ze natuurlijk wel graag op https://dso-toolkit.nl/_1296.Logo-toekomstbestendig/docs/fundament/logo.html

**Comment by daverhelst** [comment]
Na overleg: in het header patroon graag weer de oude .png terug (en dus ook het stukje stijling wat hem op 300px zet)

**Comment by gofix** [comment]
@bramhoosemans zie
**Logo**
https://dso-toolkit.nl/_1296.Logo-toekomstbestendig/docs/fundament/logo.html
**Header**
https://dso-toolkit.nl/_1296.Logo-toekomstbestendig/components/detail/header.html
**Homepage**
https://dso-toolkit.nl/_1296.Logo-toekomstbestendig/components/detail/homepage.html
Niet meer bestaat: https://dso-toolkit.nl/master/components/detail/logo.html

**Comment by bramhoosemans** [comment]
@daverhelst zou je onderstaande afbeelding nog kunnen toevoegen aan de documentatie? Boven 'Hoe te gebruiken'.

![logo-afmetingen](https://user-images.githubusercontent.com/598735/151383409-a42769ff-1c3c-494f-b277-491664b802d0.png)

**Comment by gofix** [comment]
@bramhoosemans check again. 
https://dso-toolkit.nl/_1296.Logo-toekomstbestendig/docs/fundament/logo.html

Accepted?

**Comment by bramhoosemans** [comment]
Top!
