### ISSUE TITLE
DatePicker in modal gaat niet goed

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#1304]
![image](https://user-images.githubusercontent.com/9696261/138587667-f73a5364-a5a2-4dab-9cfc-ac6bc89ebfe5.png)

cc: @jeroenpeeters (DSO Developer), @Anto1nette (DSO Toolkit PO) en @bramhoosemans (Team UX-er)

**Comment by gofix** [comment]
Dit is toch hetzelfde als #1331 ?

**Comment by bramhoosemans** [comment]
> Dit is toch hetzelfde als #1331 ?

Volgens mij wel ja.

**Comment by tfrijsewijk** [comment]
Is duplicate, en het andere issue is ook gesloten. Ik sluit deze ook.
