### ISSUE TITLE
Voorbeeldpagina's Mijn Omgevingsloket

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#1307]
### Aanleiding
In aankomend(e) PI(s) gaan we aan de slag met de implementatie van het nieuwe Mijn Omgevingsloket. Hiervoor zijn o.a. de Cards aangepast en de toggletips geïntroduceerd. We willen de markup van de key-layouts uit Mijn Omgevingsloket borgen in de toolkit.

### Werkzaamheden
- Onder 'Toepassingen' komt een nieuwe sectie 'Mijn Omgevingsloket':
- Opzetten en valideren van voorbeeldpagina voor:
  - Mijn projecten
  - Project overzicht
  - Verzoek detail

### Ontwerp
![206_mijn-projecten-meerdere-projecten](https://user-images.githubusercontent.com/598735/138704220-77895938-38e5-4931-9cfe-b34afdb75b84.png)
![504_project--meerdere-verzoeken-tooltip](https://user-images.githubusercontent.com/598735/138704210-6dae1899-f134-4e36-b383-fd7cedc5ff72.png)
![601_project-verzoek](https://user-images.githubusercontent.com/598735/138704225-f286d221-6436-403f-913b-b4be8a4dc120.png)

**Comment by MichielDHVD** [comment]
De eerste opzet voor de voorbeeld pagina's @bramhoosemans @gofix :

- https://dso-toolkit.nl/_1307-Voorbeeld-MijnOmgevingsloket/components/detail/mijn-projecten.html
- https://dso-toolkit.nl/_1307-Voorbeeld-MijnOmgevingsloket/components/detail/project-overzicht.html
- https://dso-toolkit.nl/_1307-Voorbeeld-MijnOmgevingsloket/components/detail/verzoek-detail.html

Opvallende issues/ongewenste resultaten: 
Als ik dingen in de toolkit gemist heb die  een van de issues oplost. Graag laten weten dan pas ik het aan.

- Header heeft geen bottom margin, Button heeft geen top-margin waardoor deze op elkaar knallen
<img width="1175" alt="Screenshot 2021-11-30 at 15 20 41" src="https://user-images.githubusercontent.com/36912722/144064581-22cab9ac-6518-42b8-b550-ff71deb089af.png">

- In de ontwerpen heeft Bram onder buttons vaak 16px margins toegepast voor ademruimte. Buttons hebben dit niet in de de voorbeeldpagina's waardoor onderdelen op elkaar knallen
<img width="507" alt="Screenshot 2021-11-30 at 15 20 50" src="https://user-images.githubusercontent.com/36912722/144064612-cbea318f-c2e9-493f-9a52-b7a66c787db4.png">

- Button row responsive, wanneer buttons in een rij staan en je verkleint de viewport dan hebben de buttons eronder nog steeds een margin left 16px. Waardoor het raar uitlijnt zie afb. (viewport 320px)
<img width="300" alt="Screenshot 2021-11-30 at 15 21 36" src="https://user-images.githubusercontent.com/36912722/144064652-300ed3b8-990c-4849-9561-117d951692e5.png">

- Grijze tekst achter toggletip is niet beschikbaar in de toolkit, heb ik voor nu een caption van gemaakt (Niet helemaal zeker, miss heb ik iets gemist) 
- In ontwerpen van Bram hebben de eerste cellen van een tablerow geen dik gedrukte tekst. Omdat de eerste cel van een row altijd een th moet zijn (accessibility) wordt deze wel dik gedrukt getoond. 
- Het rode label wordt ook dik gedrukt getoond omdat deze in dezelfde th staat. 
<img width="511" alt="Screenshot 2021-11-30 at 15 23 04" src="https://user-images.githubusercontent.com/36912722/144064752-029b3781-f542-45ae-9598-4485d172c6bf.png">

- Anchor links hebben een underline tenzij Bram hier tertiare non icon button van wil maken ( In mijn projecten is het nu een anchor) 
- De cardlist in project overzicht heeft in het ontwerp een lijn aan de bovenkant. Deze is er niet in de toolkit
- *Bug* (Zie Verzoek detail) Een link met icoon ervoor toont een streepje 
<img width="331" alt="Screenshot 2021-11-30 at 15 20 57" src="https://user-images.githubusercontent.com/36912722/144064792-8b6885e8-55ed-4fdc-ad66-4e77903065ea.png">

- *Bug* (Zie Mijn projecten) Wanneer een Tooltip op een icon only button wordt geplaatst verspringt deze on hover en komt er een streepje bij. 
<img width="221" alt="Screenshot 2021-11-30 at 15 20 34" src="https://user-images.githubusercontent.com/36912722/144064844-f593070f-4786-4db9-adfa-c830c3cfa1cb.png">

**Comment by bramhoosemans** [comment]
> * Header heeft geen bottom margin, Button heeft geen top-margin waardoor deze op elkaar knallen

Goed punt; hier zullen we een oplossing voor moeten verzinnen.

> * In de ontwerpen heeft Bram onder buttons vaak 16px margins toegepast voor ademruimte. Buttons hebben dit niet in de de voorbeeldpagina's waardoor onderdelen op elkaar knallen

We hebben het al vaker gehad over een “button bar/row” waar deze styling op toegepast kan worden. Kan me niet herinneren of deze gerealiseerd is.

> * Button row responsive, wanneer buttons in een rij staan en je verkleint de viewport dan hebben de buttons eronder nog steeds een margin left 16px. Waardoor het raar uitlijnt zie afb. (viewport 320px)

Zelfde comment als hierboven.

> * Grijze tekst achter toggletip is niet beschikbaar in de toolkit, heb ik voor nu een caption van gemaakt (Niet helemaal zeker, miss heb ik iets gemist)

Deze hebben we wel > class="text-muted”. Er staat nog een taak voor op de backlog om deze zichtbaar te maken in Typografie.

> * In ontwerpen van Bram hebben de eerste cellen van een tablerow geen dik gedrukte tekst. Omdat de eerste cel van een row altijd een th moet zijn (accessibility) wordt deze wel dik gedrukt getoond.

In het ontwerp is deze ook semi-bold…

> * Het rode label wordt ook dik gedrukt getoond omdat deze in dezelfde th staat.

Dat is vreemd, maar goed af te vangen in context. Ik kan op productie niet zo snel dit label te voorschijn halen maar kan me niet herinneren dat deze bold werd.

> * Anchor links hebben een underline tenzij Bram hier tertiare non icon button van wil maken ( In mijn projecten is het nu een anchor)

Prima.

> * De cardlist in project overzicht heeft in het ontwerp een lijn aan de bovenkant. Deze is er niet in de toolkit

Staat als taak op de backlog.

> * Bug (Zie Verzoek detail) Een link met icoon ervoor toont een streepje
> * Bug (Zie Mijn projecten) Wanneer een Tooltip op een icon only button wordt geplaatst verspringt deze on hover en komt er een streepje bij.

Idd niet gewenst.

**Comment by MichielDHVD** [comment]
Dan ga ik het volgende nog aanpassen

- Text-muted toepassen (ik dacht al dat ik iets over het hoofd had gezien)
-  Tertiare non icon button maken van de anchors in mijn projecten

Vraag voor @gofix 
Hebben we nu een button row? Of moet die nog steeds een keer gebouwd worden, in forms en modals hebben we aanpassingen gedaan.

**Comment by gofix** [comment]
Als ik naar de huidige stand van zaken in de 3 gerealiseerde markup voorbeelden kijk, vallen me nog een paar zaken op:

**Mijn projecten**
https://dso-toolkit.nl/_1307-Voorbeeld-MijnOmgevingsloket/components/detail/mijn-projecten.html
![image](https://user-images.githubusercontent.com/2689559/151164071-c18f2f3e-75fa-4677-9cab-183ba9e2a41e.png)

Moeten die buttons [nieuw project] en [actiecode invoeren] niet `.dso-secondary` zijn?

**Comment by gofix** [comment]
Over het vraagstuk "hebben we een button row": nee, die hebben we niet. We hebben:
`.dso-form-buttons` (voor buttons onder/in een form)
`.dso-context-wrapper` (voor als je iets rechts wil van iets label-achtigs)
Maar wellicht hebben we dus inderdaad een groepering nodig voor buttons in dit soort schermen.

**Comment by gofix** [comment]
We zijn volgens mij zo ver als we kunnen komen met de huidige DSO Toolkit voorzieningen, @bramhoosemans, @MichielDHVD 

Openstaande punten, die in een nieuw issue zullen moeten worden aangepakt, zijn volgens mij nu nog (ik herhaal bij verschillende schermen niet bevindingen die al op eerdere schermen ook gelden):

https://dso-toolkit.nl/_1307-Voorbeeld-MijnOmgevingsloket/components/detail/mijn-projecten.html
- de balk met 2 knoppen en een search bar, is nu een .dso-context-wrapper maar zou misschien iets specifieks moeten zijn, of juist iets (anders) generieks.
- de boldness van de links in de tabel, en die van het rode label
- tooltip issues (https://github.com/dso-toolkit/dso-toolkit/issues/1362)

https://dso-toolkit.nl/_1307-Voorbeeld-MijnOmgevingsloket/components/detail/project-overzicht.html
- de 'teruglink' [Bekijk andere projecten], en dan met name de ruimte die gewenst is tussen header en deze link
- uitlijning caret op card
- is text-muted voor de tekst "Ingediend" de meest wenselijke oplossing?

https://dso-toolkit.nl/_1307-Voorbeeld-MijnOmgevingsloket/components/detail/verzoek-detail.html
- button bar, en marges die deze moet hebben

**Comment by bramhoosemans** [comment]
> We zijn volgens mij zo ver als we kunnen komen met de huidige DSO Toolkit voorzieningen, @bramhoosemans, @MichielDHVD
> 
> Openstaande punten, die in een nieuw issue zullen moeten worden aangepakt, zijn volgens mij nu nog (ik herhaal bij verschillende schermen niet bevindingen die al op eerdere schermen ook gelden):
> 
> https://dso-toolkit.nl/_1307-Voorbeeld-MijnOmgevingsloket/components/detail/mijn-projecten.html
> 
> * de balk met 2 knoppen en een search bar, is nu een .dso-context-wrapper maar zou misschien iets specifieks moeten zijn, of juist iets (anders) generieks.

Meenemen in discussie ‘button row’. Voor nu zo laten.

> * de boldness van de links in de tabel, en die van het rode label

Is het een link of een button? In de huidige toepassing zie ik vaak een link met role button erop staan… Daarom had ik in het ontwerp de styling van de tertiaire button gebruikt. Bekijk ook bijlagen op de verzoek detail pagina.

Als het wél een link moet zijn, dan ook link styling toepassen.

Label dient niet bold te zijn > nieuwe taak.

> * tooltip issues ([Verbeteringen Tooltip en Toggletip #1362](https://github.com/dso-toolkit/dso-toolkit/issues/1362))

Naast reeds bekende issue; graag tooltip ‘position top’ geven in het voorbeeld.

> https://dso-toolkit.nl/_1307-Voorbeeld-MijnOmgevingsloket/components/detail/project-overzicht.html
> 
> * de 'teruglink' [Bekijk andere projecten], en dan met name de ruimte die gewenst is tussen header en deze link

Ik zal hier een nieuwe taak voor aanmaken.

> * uitlijning caret op card

Naast de uitlijning van het pijltje ontbreken ook de borders boven en onderaan de Cards List. Deze zal ik samenvoegen in een taak.

> * is text-muted voor de tekst "Ingediend" de meest wenselijke oplossing?

Tja, ik kan niet beoordelen of dat gewenst is. De styling wordt geleverd en ook toegepast. Er staat al enige tijd een taak op de backlog om deze styling ook zichtbaar te maken bij de Typografie.

- ‘Nieuwe verzoeken’ en ‘Deelnemers’ mogen responsive gezien onder de ‘Verzoeken’ komen te staan.
![Schermafbeelding 2022-01-27 om 14 55 33](https://user-images.githubusercontent.com/598735/151372739-7009b4d5-999b-40a7-8a8a-31fd9e8bca1b.png)
 
> https://dso-toolkit.nl/_1307-Voorbeeld-MijnOmgevingsloket/components/detail/verzoek-detail.html
> 
> * button bar, en marges die deze moet hebben

Ik zal een nieuwe story aanmaken om de specificaties te bespreken rond 'Button rows'.

- Responsive tabel ook inzetten voor bijlagen. “Beweeg de tabel van links naar rechts”

**Comment by gofix** [comment]
Nog even met @bramhoosemans op een rijtje gezet wat er in kader van _dit_ issue nu nog moet gebeuren:
- tooltip ‘position top’
- push pull van zone en zijbalk wijzigen, zodat in smalle viewport de blokken onderaan komen
- Responsive tabel ook inzetten voor bijlagen. “Beweeg de tabel van links naar rechts”

**Comment by gofix** [comment]
@MichielDHVD kun jij een knoop doorhakken over wat nu te doen op https://dso-toolkit.nl/_1307-Voorbeeld-MijnOmgevingsloket/components/detail/mijn-projecten.html met de tooltip positie, ik zie 2 opties:
- nu die `position="top"` behouden en accepteren dat dat een suboptimale ervaring levert, die we wellicht dan oplossen in https://github.com/dso-toolkit/dso-toolkit/issues/1362
- nu die position eraf, zodat weliswaar het ontwerp nog niet behaald wordt, maar de gebruikservaring acceptabel is. Eventueel kunnen we dan alsnog als 'bijvangst' in https://github.com/dso-toolkit/dso-toolkit/issues/1362 de position alsnog op top zetten.

**Comment by MichielDHVD** [comment]
@bramhoosemans  en @gofix  

Ik zeg behouden en acccepteren in dit issue. Dit issue was om voorbeeld pagina's te bouwen conform Toolkit markup. 

Als er problemen zijn die volgen of zichtbaar worden in de voorbeeldpagina's deze los oppakken in andere issues. 

Optie 1 uitvoeren.

**Comment by gofix** [comment]
✔️
