### ISSUE TITLE
document-header en document-list-item in dso-viewer-grid main panel

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#1308]

**Comment by tfrijsewijk** [comment]
@LiesbethVorst en @kad-leeffs: In het ontwerp, derde plaat: Daar staat `{opschrift}`: Is dit hetzelfde Opschrift waar ook noten in kunnen voorkomen?

**Comment by kad-leeffs** [comment]
> @LiesbethVorst en @kad-leeffs: In het ontwerp, derde plaat: Daar staat `[opschrift]`: Is dit hetzelfde Opschrift waar ook noten in kunnen voorkomen?

Nee, dat is niet hetzelfde opschrift. Dit is de titel van een document en is een 'plain' string, zonder HTML opmaak.

**Comment by tfrijsewijk** [comment]
Dank!

**Comment by tfrijsewijk** [comment]
@LiesbethVorst 
* Hoe _heet_ de tweede variant, die in het ontwerp rechts onder "Documentheader variant: regels op maat met statusbadge". Waarom heeft deze een link naar "gehele document bekijken" en geen knop om details uit te klappen?

![image](https://user-images.githubusercontent.com/9696261/142413942-57d56e4c-fcf1-4516-9d10-838e02634fae.png)
* Is `[status]` altijd een badge type "warning" met de tekst "Ontwerp"? Kan daar ooit een ander type badge en/of andere tekst staan?
* `[datum]` is niet helemaal toereikend. Wie zet de tekst "Bekendgemaakt op ...." en "In werking vanaf ....." neer?

Ik heb nu de volgende API bedacht:

```html
<!-- type en owner zijn attributen -->
<dso-viewer-document-header
  type="Omgevingsplan"
  owner="Gemeente Gouda"
>
  <!-- Opschrift gaat met een slot. De juiste header kan door de afnemer worden meegegeven -->
  <h1 slot="opschrift">Omgevingsplan gemeente Gouda</h1>

  <!-- Een slot "action" waar een button kan worden geplaatst. Het is hiermee de verantwoordelijkheid van de afnemer om de juiste knop te maken -->
  <button slot="action" type="button"></button>

  <!-- Een slot "status" waar de status en de datum in wordt geplaatst. Let op dat ook de tekst "Bekendgemaakt" de verantwoordelijkheid van de afnemer is -->
  <span slot="status">
    <dso-badge status="warning">Ontwerp</dso-badge> Bekendgemaakt 01-03-2021
  </span>

  <!-- Alle kenmerken -->
  <dl slot="kenmerken">
    <dt>Opschrift</dt>
    <dd>Besluit van 3 juli 2018, houdende regels over activiteiten in de fysieke leefomgeving</dd>
    <dt>Identificatie</dt>
    <dd>/akn/nl/act/mnre1034/2021/BWBR0041330</dd>
    <dt>Besluit</dt>
    <dd><a href="#" target="_blank" class="extern">Bekijk besluit</a></dd>
  </dl>
</dso-viewer-document-header>
```

Doordat ik het verschil tussen de twee varianten nog niet weet heb ik nog geen oplossing voor wanneer de knop "Meer kenmerken" of de link "Hele document bekijken" wordt getoond.

Wordt die tweede variant in een lijst gebruikt, zodat je kan doorstappen naar het hele document?

**Comment by LiesbethVorst** [comment]
- Die 2e variant wordt inderdaad in een lijst gebruikt (vandaar de H2). De link "Hele document bekijken" opent een nieuwe pagina met alleen dat document, daar wordt de 1e variant gebruikt (met de H1). Omdat dit het hele document is staan er ook meer details in de header, te openen met de knop "Meer kenmerken".
- er zijn meerdere statussen mogelijk: zowel het type als de tekst moet variabel zijn
- klopt dat [datum] niet altijd alleen een datum is maar ook een tekst moet kunnen bevatten zoals "Bekendgemaakt 01-03-2021". Dit wordt door de viewer daar neergezet.

**Comment by tfrijsewijk** [comment]
Na overleg met Liesbeth moeten we beide tot de conclusie komen dat het eigenlijk twee componenten zijn:

```html
<dso-viewer-document-header
  type="Omgevingsplan"
  owner="Gemeente Gouda"
>
  <h1 slot="opschrift">Omgevingsplan gemeente Gouda</h1>

  <button slot="action" type="button"></button>

  <span slot="status">
    <dso-badge status="warning">Ontwerp</dso-badge> Bekendgemaakt 01-03-2021
  </span>

  <dl slot="kenmerken">
    <dt>Opschrift</dt>
    <dd>Besluit van 3 juli 2018, houdende regels over activiteiten in de fysieke leefomgeving</dd>
    <dt>Identificatie</dt>
    <dd>/akn/nl/act/mnre1034/2021/BWBR0041330</dd>
    <dt>Besluit</dt>
    <dd><a href="#" target="_blank" class="extern">Bekijk besluit</a></dd>
  </dl>
</dso-viewer-document-header>



<dso-viewer-document-list-item
  type="Omgevingsplan"
  owner="Gemeente Gouda"
>
  <h2 slot="opschrift">Omgevingsplan gemeente Gouda</h2>

  <span slot="status">
    <dso-badge status="warning">Ontwerp</dso-badge> Bekendgemaakt 01-03-2021
  </span>

  <div slot="body">
    
  </div>
</dso-viewer-document-list-item>
```

**Comment by tfrijsewijk** [comment]
@LiesbethVorst Hebben we het al over responsive gedrag vs. paneelbreedte gehad? Want daar was iets mee.. wat hier ook is ;)

**Comment by LiesbethVorst** [comment]
Kan ik me voorstellen, maar dit hebben we niet eerder besproken @tfrijsewijk

**Comment by tfrijsewijk** [comment]
Hoe zullen we dit dan aanpakken? Zal ik de styling scopen naar de breedte van het paneel en niet naar viewport width?

**Comment by LiesbethVorst** [comment]
Aha, dat bedoel je. Het lijkt me inderdaad logisch om de styling aan te passen aan de breedte van het paneel.

**Comment by tfrijsewijk** [comment]
@LiesbethVorst @DjangoBlok https://css.dso-toolkit.nl/_1308-Documentheader-juridische-regels/?path=/story/viewer-grid--viewer-grid

Kunnen jullie hier naar kijken? Ik ben nog niet enthousiast, maar laten we dat maandag of donderdag verder bespreken
