### ISSUE TITLE
Labels: Symbolen tonen

### ISSUE THREAD

**Issue by Anto1nette** [dso-toolkit/dso-toolkit#1313]
### Aanleiding
Bij het zoeken naar juridische regels kunnen gebruikers gebieden selecteren waarvoor specifieke regels gelden. De geselecteerde gebieden worden vervolgens getoond op de kaart en in het filterblok. In het filterblok moet naast de naam van de gebieden ook worden getoond met welke kleur/patroon het gebied op de kaart is ingetekend. 

### Werkzaamheden
Component Label uitbreiden zodat ook een blokje met kleur/patroon kan worden getoond.

Op andere plekken binnen de viewer wordt voor zo'n blokje een div gebruikt met een bepaalde afmeting. In de CSS worden er 2 manieren gebruikt voor het vullen van de blokjes: met CSS of met een PNG. De border kan verschillende kleuren hebben, die hoort niet bij het toolkit component.

```
div.symboolcode[data-symboolcode='vszt030'] {
  background-color: rgba(235, 225, 235, 0.5);
  border-width: 1px;
  border-color: #000001;
  border-style: solid;
}

div.symboolcode[data-symboolcode='vag000'] {
  background-image: url('./symbols/va000.png');
  border-width: 1px;
  border-color: #000001;
  border-style: solid;
}
```

![va000](https://user-images.githubusercontent.com/1033595/139685694-9d9a443b-ad6f-4954-898b-d53f3ce21d19.png)

Een voorbeeld: https://pre.omgevingswet.overheid.nl/orienteren/viewer/document/NL.IMRO.0344.BPOOGINALLUNETTEN-VA01/locatiedetails?locatie-id=adr-cb755943912aa65bfe131cbefe316094. Dit is een bestemmingsplan waarvan je details kan bekijken, hiervoor prik je dan ergens op de kaart binnen het gebied van het bestemmingsplan.

Een legenda blokje is een decoratieve toevoeging aan een label die verwijst naar de verbeelding op de kaart. Daarom hoeven de blokjes alleen visueel zichtbaar te zijn en niet op een andere manier toegankelijk te worden gemaakt.

### Ontwerp
![Filterblok - specs legenda blokjes](https://user-images.githubusercontent.com/1033595/139685803-273a3e37-6771-4ad3-914e-14ff09ea5e93.png)

**Comment by tfrijsewijk** [comment]
@LiesbethVorst: Zoals ik in Slack al had laten vallen, die 23px kloppen volgens mij niet. Je gaf aan dat het komt bij het schalen van een plaat van 30x25 naar 20px hoog, dat er dan een breedte van 23px uitkomt. Maar volgens de formule `30 / 25 * 20` is het `24px`.

Bij 23px zal het volgende gebeuren:

![image](https://user-images.githubusercontent.com/9696261/142373440-774d45af-de57-40c5-83ec-72c0b6f5c99e.png)

Ik ben zo vrij geweest om voor 24px te gaan.

De change heb ik ter review aangeboden bij Ad. Hier kan jij testen:

* https://dso-toolkit.nl/_1313-Labels--Uitbreiden-met-symbolen/components/detail/label.html
* https://dso-toolkit.nl/_1313-Labels--Uitbreiden-met-symbolen/components/detail/label-css.html
* https://core.dso-toolkit.nl/_1313-Labels--Uitbreiden-met-symbolen/?path=/story/label--with-symbol-image en https://core.dso-toolkit.nl/_1313-Labels--Uitbreiden-met-symbolen/?path=/story/label--with-symbol-color
* https://css.dso-toolkit.nl/_1313-Labels--Uitbreiden-met-symbolen/?path=/story/label--with-symbol-image en https://css.dso-toolkit.nl/_1313-Labels--Uitbreiden-met-symbolen/?path=/story/label--with-symbol-color
* https://react.dso-toolkit.nl/_1313-Labels--Uitbreiden-met-symbolen/?path=/story/label--with-symbol-image en https://react.dso-toolkit.nl/_1313-Labels--Uitbreiden-met-symbolen/?path=/story/label--with-symbol-color
