### ISSUE TITLE
Afbreken van lange labels

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#1314]
In #1278 is een patroon aangeboden voor het implementeren voor het filterblok. Tijdens de refinement kwam naar voren dat labels wel erg lang kunnen worden:

![image](https://user-images.githubusercontent.com/9696261/140037927-146bebf2-cbe8-46d3-9d3e-b668ad560c5e.png)

In een maatwerk implementatie is het als volgt opgelost:

![image](https://user-images.githubusercontent.com/9696261/140038021-210735b6-a9b2-44da-8aed-0adb68d69420.png)

De wens is dat er ellipsis worden getoond. Dit zou bv. met CSS kunnen, maar gebruikers die een standaard browser gebruiken kunnen de volledige tekst niet meer lezen. Screenreaders overigens wel.

Bij een aantal refinements is het afbreken van labels besproken maar wij (toolkit maintainers) hebben onze bedenkingen bij het afbreken van teksten zonder alternatief om de volledige tekst te kunnen tonen.

* https://github.com/w3c/wcag/issues/728
* https://www.w3.org/TR/WCAG20-TECHS/G179.html

Zoals wij de regels interpreteren zijn er situaties waarin het wel is toegestaan om teksten af te breken maar valt het Label component daar niet onder.

Situaties waar het wel mag:
* Links met een afgebroken linktekst die bij het openen van de pagina wel volledig toont;
* Afbreken maar een scrollbar aanbieden waarmee de volledige tekst alsnog leesbaar is;
* Interactiviteit (hover/focus/button) waarmee de volledige tekst (ergens) alsnog zichtbaar is;

In dit issue wil ik van @timveld weten of de toolkit maintainers 'n punt hebben en/of wat een toegankelijk alternatief is.

Laatste reactie over dit onderwerp was van Tim:

>_Ik (redactie)_ zag je vraag van 1 oktober over afbreken in relatie tot sc 1.4.12: ik ken de situatie niet precies maar bij een bepaalde zoom afkappen met ellipsis is in principe geen acceptabele oplossing inderdaad. Ik begrijp dat tekstafbreking een nieuw issue wordt, tzt samen nadenken over betere oplossing.

cc: @LiesbethVorst, @timveld, @Anto1nette, @kad-tammie

**Comment by timveld** [comment]
De maintainers hebben zeker een punt, bij inzoomen mag in beginsel geen content verloren gaan. 
De genoemde uitzonderingen zien op situaties waar het eenvoudig is om de content alsnog te zien (hoveren / doorklikken). Maar als content boven een bepaalde zoom visueel verdwijnt dan is er een afwijking. Zelfs als je dat met scrollen en hoveren oplost is het de vraag of het op mobiele apparaten goed gaat. 
Morgen ben ik bij refinement, daar verder bespreken? Mij is nog niet duidelijk in welke situaties afbreken echt nodig is (en waarom je dan niet over meerdere regels kunt verdelen) Misschien kunnen we een oplossing bedenken.

**Comment by tfrijsewijk** [comment]
Zoomen heeft er niet (meteen) mee te maken, bovenstaande screenshots is de normale weergave. Er worden lange teksten in labels gezet.

**Comment by kad-tammie** [comment]
Bij hoveren met de musaanwijzer over het label zoals het nu is in de Regels op de Kaart, tonen we dit:
<img width="375" alt="Screenshot 2021-11-03 at 12 04 18" src="https://user-images.githubusercontent.com/77613213/140049545-4f79845f-bcb9-46f0-b57a-40d546ca4daa.png">

**Comment by tfrijsewijk** [comment]
Kijk, dat is interessant. Werkt het ook bij focus, voor bijvoorbeeld toetsenbordgebruikers?

**Comment by kad-tammie** [comment]
Als ik ga tabben, dan
<img width="302" alt="Screenshot 2021-11-03 at 14 46 07" src="https://user-images.githubusercontent.com/77613213/140071678-238c623c-0a77-4bae-a109-09c476cd8bf5.png">
:

**Comment by hansgrimm** [comment]
Ik heb een vingeroefing in Codepen staan, Waar @timveld redelijk happy mee is (met mate ;))
Url: https://codepen.io/picturit/pen/eYMpjKv
Geen aanwijzing hoe het zou moeten, maar meer een eventuele inspiratiebron.

**Comment by svrijsewijk** [comment]
@hansgrimm ik heb het width gedrag even gelaten op 180px. Ik stel voor dat we hier een apart issue voor maken. Voor de breedte zou het component ook naar zijn parent kunnen kijken. zodat gaten efficiënt worden gevuld. Bv bij de rode pijl:

![image](https://user-images.githubusercontent.com/21218284/184526578-82940b51-3eff-4453-9126-4caa4438d2bb.png)

To be continued.
