### ISSUE TITLE
Search Bar in CSS Storybook opnemen

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#1317]
In #1316 is de styling van de Search Bar van `dso-toolkit` naar `@dso-toolkit/css` verplaatst. In dit issue moet de bijbehorende Storybook inrichting worden gerealiseerd.

- [ ] Restant van `packages/dso-toolkit/src/styles/components/_search-bar.scss` refactoren
- [ ] Storybook stories in `@dso-toolkit/sources` en `@dso-toolkit/css`
- [ ] In core/autosuggest/stories is de Search Bar opgenomen. Markup vervangen met `searchBarTemplate()`.
- [ ] Documentatie

cc: @Anto1nette

**Comment by gofix** [comment]
Volgens mij is dit al gedaan, toch, @PieterVerheij, @tfrijsewijk, in #1466 
Zie: https://css.dso-toolkit.nl/38.1.0/?path=/story/search-bar--visual-label-with-icon

**Comment by tfrijsewijk** [comment]
Nope, lijkt erop alsof dit al is gedaan 🤷
