### ISSUE TITLE
Image replacement in documentatie

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#132]
In layout moet layout_1.png aangepast worden naar deze versie 
![layout_1](https://user-images.githubusercontent.com/36912722/40161396-f4121ef0-59b0-11e8-8f1c-da15171f4ce9.png)

Ik wilde het zelf doen via source tree en zelf een pull request proberen. Maar hij laat het niet meer toe geen acces. Dus moet het via deze route proberen.

**Comment by VolleMelk** [comment]
@MichielDHVD Ik vermoed dat je eerst de repository moet forken. Daarna kun je uit je vanuit je eigen namespace een pull request openen naar deze repository
