### ISSUE TITLE
Filterblok component

### ISSUE THREAD

**Issue by Anto1nette** [dso-toolkit/dso-toolkit#1323]
### Aanleiding
Het filterblok is op dit moment een compositie van componenten. Het nadeel is dat de verticale margins niet helemaal volgens het ontwerp kunnen worden gerealiseerd. 

### Werkzaamheden
- Een component maken van het filterblok (class toevoegen)
- Margins fixen tussen h3 - locatie - labels
- Suggestie voor namen:
   - filters (hele blok)
   - selected-location (adres/locatie)
   - selected-filters (verzameling gekozen filters)

### Wens
Het filterblok over de volle breedte tonen van het paneel van de viewer.

Ontwerp
![Filterblok - specs](https://user-images.githubusercontent.com/1033595/140318761-4f4b7352-2498-428b-86b0-7ead5f73255b.png)

**Comment by gofix** [comment]
Let op: het responsive gedrag in de smalste viewport is anders dan standaard in context-wrapper.
Zie ook https://github.com/dso-toolkit/dso-toolkit/issues/1341#issuecomment-970386245

**Comment by gofix** [comment]
Zouden we deze nu nog weg moeten halen? https://dso-toolkit.nl/31.1.1/components/detail/filterblok.html

**Comment by tfrijsewijk** [comment]
Dat lijkt mij wel:

![image](https://user-images.githubusercontent.com/9696261/144883724-0823794d-f863-4ddd-ad6c-ab6f55b16998.png)

en daarom zijn we weg ;)

**Comment by gofix** [comment]
Aha de build liep nog
![image](https://user-images.githubusercontent.com/2689559/144883851-236b1c61-0176-450d-bbb3-9feff8e99d9c.png)
