### ISSUE TITLE
Date Picker hanteert verkeerde dateformat

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#1325]
De Date Picker maakt geen gebruik van voorloopnullen bij dag en maand lager dan 10 terwijl dat expliciet staat vermeldt in de documentatie dat dit wel de bedoeling.

**Comment by bramhoosemans** [comment]
**Originele bug melding:**
Open modal

**Verwacht gedrag:**
Datum heeft direct de focus

**Actueel gedrag:**
Datum heeft niet de default focus. De button "Datum wijzigen" heeft de focus.

**Comment by bramhoosemans** [comment]
<img width="810" alt="Screenshot 2021-10-29 at 09 31 46" src="https://user-images.githubusercontent.com/598735/140328567-1041c3df-c73e-4dd3-9b50-eb4c95db2f49.png">
