### ISSUE TITLE
Date Picker geeft geen event bij foutieve invoer

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#1326]

**Comment by bramhoosemans** [comment]
**Originele bug melding:**
Testdatum 11-6-2021 is geselecteerd
Open de modal
Plak er "15-6-" in
Druk op wijzigen

**Verwacht resultaat:**
Een validatie fout

**Actueel resultaat:**
Geen validatie fout. Modal wordt gesloten, oude datum blijft zichtbaar.

P.S. Als je datum handmatig aanpast naar "15-6-" dan wordt wel "15-6-2021" getoond. Al is dat ook eigenaardig, immers, "15-6-" blijft geen valide datum invoer. In ieder geval verschil in knippen en plakken.

**Comment by gofix** [comment]
Eigenlijk begrijp ik niet veel van deze bugmelding. En... validatiemelding? Die geeft de datepicker toch ueberhaupt niet?

> Open de modal -> _welke modal_, bedoel je de datepicker?
Plak er "15-6-" in > _waarin_? In het datumveld waar de datepicker een hulpmiddel bij is?
Druk op wijzigen > _wijzigen?_

@bramhoosemans help!

**Comment by bramhoosemans** [comment]
@gofix Als het goed is weet @tfrijsewijk hier alles van. Er zijn tijdens implementatie een aantal bug en improvements naar boven gekomen en besproken. Thomas heeft hier de issues voor aangemaakt en ik heb de 'originele tekst' erin geplakt. De flow met Modal die wordt beschreven gaat idd verder dan alleen de Date Picker.

Voor deze bug gaat het erom dat er op dit moment geen validatie plaatsvindt op foutieve invoer. Het invoerveld is onderdeel van het webcomponent en nu kun je er alles inzetten.

Iets wat over het hoofd gezien is bij het originele issue https://github.com/dso-toolkit/dso-toolkit/issues/877.

**Comment by tfrijsewijk** [comment]
De Date Picker geeft nu twee events:

* Bij elke geldige datum invoer (handmatig of selectie)
  ![image](https://user-images.githubusercontent.com/9696261/142838169-70ffbdde-43dd-41c0-aa76-44cb8319d43b.png)
* Bij het legen van het datum veld
  ![image](https://user-images.githubusercontent.com/9696261/142838052-47370c7b-8d0e-4957-b695-6fa6442b2b47.png)

De wens is dat er ook een event wordt afgevuurd als er een ongeldige datum wordt ingevoerd:
* Invoer wat lijkt op een datum maar geen datum is, bijvoorbeeld `40-11-2000` of `1-20-2000`.
* Invoer wat geen geldige datum is maar de gebruiker gaat met iets anders verder (onBlur)

Ik twijfel nog hoe we het moeten implementeren, we kunnen het `DsoDatePickerChangeEvent` uitbreiden:

```
export type DsoDatePickerChangeEvent = {
  component: "dso-date-picker"
  valueAsDate: Date | undefined
  value: string
  error?: {
    type: 'invalid' | 'required',
    message: string
  }
}
```

Met `event.error !== 'undefined' kan de afnemer bepalen of er een error is.

Of een nieuw object emitten en het type argument aanpassen:

```
@Event() dateChange!: EventEmitter<DsoDatePickerChangeEvent | DsoDatePickerError>
```

Met `event instanceof DsoDatePickerError` kan de afnemer bepalen of er een error is.

@benheldoorn Verduidelijkt dit de boel? En hoe denk jij over de afhandeling? Andere ideeen mag natuurlijk ook.
