### ISSUE TITLE
Date Picker voorzien van autofocus attribuut

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#1327]

**Comment by bramhoosemans** [comment]
Originele bug melding:
Open modal

Verwacht gedrag:
Datum heeft direct de focus

Actueel gedrag:
Datum heeft niet de default focus. De button "Datum wijzigen" heeft de focus.

**Comment by gofix** [comment]
Gaat dit issue, net als https://github.com/dso-toolkit/dso-toolkit/issues/1326 en https://github.com/dso-toolkit/dso-toolkit/issues/1328, eigenlijk wel over de datepicker, of over de werkvorm waarbij een datepicker IN een modal wordt geplaatst?

@tfrijsewijk @bramhoosemans

**Comment by bramhoosemans** [comment]
De wens is om focus op het invoerveld van de Date Picker te kunnen zetten. Dit was niet mogelijk (begreep ik) omdat het invoerveld onderdeel is van het Web Component.

**Comment by gofix** [comment]
Daarover gaat https://github.com/dso-toolkit/dso-toolkit/issues/1164, maar misschien is dit gerelateerd.

**Comment by bramhoosemans** [comment]
> Daarover gaat #1164, maar misschien is dit gerelateerd.

#1164 gaat over het label toch? Mogelijk is het onderliggende probleem én daarmee de oplossing aan elkaar gerelateerd.

**Comment by tfrijsewijk** [comment]
#1164 heeft er niets mee te maken.

In dit issue gaan we het [attribuut `autofocus`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autofocus) emuleren.

Omdat Date Picker een Shadow DOM heeft is het voor afnemers geen triviale zaak om het input element te selecteren en `.focus()` te doen. En daarnaast, het DOM in het Shadow DOM is geen onderdeel van de Public API.

Het `dso-date-picker` element moet uitgebreid worden met een attribuut waarmee het `autofocus` gedrag wordt nagedaan. Meerdere elementen kunnen het attribuut `autofocus` hebben, het attribuut heeft alleen effect tijdens het activeren van een element.

Als `<dso-date-picker>` het autofocus attribuut heeft moet bij de eerste render de focus worden gezet. Het is dus mogelijk dat een ander mechanisme de focus weer weghaalt, maar dat kunnen we niet voorkomen en is buiten scope van dit ticket. Het is dus geen "focus trap".

Ik twijfel alleen of we het attribuut `autofocus` moeten noemen. `autofocus` is een global attribute, maar mag je 'm dan zelf implementeren of is het juist verstandig om er vandaan te blijven? In dat geval stel ik `<dso-date-picker dso-autofocus>` voor.

@benheldoorn Kan jij hier nog wat over zeggen?
