### ISSUE TITLE
Date Picker emit Enter keydown event van nested input

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#1328]

**Comment by bramhoosemans** [comment]
**Originele bug melding:**
Modal voor testdatum open
Invoer van een nieuwe datum geven
Enter

**Verwacht gedrag:**
Modal sluit en de nieuwe datum is verwerkt

**Actueel gedrag:**
Modal blijft open staan.

**Comment by bramhoosemans** [comment]
Mogelijke oplossingsrichting: alle keydown events doorgeven vanuit web component?

**Comment by gofix** [comment]
Ook hier weer: we (althans, @benheldoorn  en ik) begrijpen de melding niet: welke modal -> de datepicker?
Als ik op https://core.dso-toolkit.nl/31.0.0/?path=/story/date-picker--default een datum invoer als de datepicker open is, en ik voer iets anders in, sluit de datepicker keurig, en als ik m daarna weer open is dat te zien.
Of begrijpen we deze weer helemaal verkeerd, net als https://github.com/dso-toolkit/dso-toolkit/issues/1326
@bramhoosemans @tfrijsewijk 

(NB: ooit hebben we geroepen dat een ticket altijd een "Waar" moet bevatten zodat iedere developer snapt hoe en wat -> de description van dit ticket is leeg, dus bevat ook niet echt een "waar")

**Comment by bramhoosemans** [comment]
Wat ik heb begrepen is dat er geen 'enter' event wordt doorgegeven als de focus in het invoerveld staat; dus niet in de kalender zelf.

**Comment by tfrijsewijk** [comment]
De afnemers willen weten wanneer de gebruiker op ENTER drukt. Omdat de input van het Date Picker component is moeten we iets. We kunnen inderdaad alle `keyup` en `keydown` events proxyen, of we kunnen een `onEnter` event maken. @benheldoorn Suggesties?
