### ISSUE TITLE
Date Picker in Modal werkt niet

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#1331]
## Situatie

![image](https://user-images.githubusercontent.com/9696261/140327994-7a5166f8-9a55-48d6-9c00-6e975487d30b.png)

## Oorzaak

De Modal bestaat uit 3 elementen: header, body en footer. Body heeft `max-height` en `overflow: auto`. Hierdoor is een deel van de kalendar niet zichtbaar en is dit geen triviale oplossing (z-index truuk gaat hier niet op).

### Alternatieve positionerings strategie

De kalendar wordt nu absoluut gepositioneerd. We kunnen daarnaast een nieuwe strategie "fixed" introduceren. Dit betekent dat de afnemer een extra argument meegeeft waarmee de date picker begrijpt dat
* het kalendar element ergens anders in het DOM moet worden geplaatst;
* dmv. scripting het kalendar element visueel op dezelfde plek wordt gepositioneerd dmv. `position: fixed;`
* DOM observers en scroll eventlisteners moeten komen die de visuele positionering bijstellen indien nodig;

Eventueel kunnen we de API uitbreiden met 'n verwijzing naar een container element of een functie waarmee de afnemer nog meer invloed heeft op het positioneren van het kalendar element.

With great power comes great responsibility..

* Een element wat op een andere plek in het DOM staat wordt ook door user agents op een andere plek behandeld: bijvoorbeeld: Screenreaders gaan anders voorlezen
* Styling gaat nog wel eens 'n dingetje worden, nu leeft de styling van de kalendar in het shadow dom
* Uberhaupt styling: hoe gaat de global styling van de toolkit samen met 'n willekeurig geplaatst kalendar element?

Ofwel, hier zit best wel 'n afnemer detail/risico aan.

**Dure oplossing.**

### Modifier op Modal

We kunnen een modifier op de Modal introduceren die de problematische styling uitschakelt. Het is dan de verantwoordelijkheid van de afnemer om modals te maken die niet te buiten beeld scrollen.

**Dit een goedkope oplossing**, maar ook hier weer geen echte waterdichte oplossing. En daarnaast een API die ook misbruikt kan worden.

### Deze werkvorm niet toestaan

Ik heb sowiezo mijn bedenkingen bij deze implementatie, onder andere vanuit een responsive perspectief. Op smalle viewports wordt de modal schermvullend....

![image](https://user-images.githubusercontent.com/9696261/140374933-2fd0996c-c84f-4764-b570-0ec0a4064e64.png)

...wat bij het activeren van de date picker een schermvullende kalendar geeft....

![image](https://user-images.githubusercontent.com/9696261/140375158-6751ed95-2bf9-4ae7-b1a4-8fd3e332cd7a.png)

Op een kleine viewport heb je dus 3 lagen interacties (applicatie, modal, datepicker calendar).

Overigens is dit ook de **goedkoopste oplossing** voor de toolkit ;-) (geintje natuurlijk)

cc: @Anto1nette en @bramhoosemans

**Comment by bramhoosemans** [comment]
@tfrijsewijk Wat bedoel je precies met "geen echte waterdichte oplossing. En daarnaast een API die ook misbruikt kan worden." bij oplossingsrichting Modifier op Modal?

_Dat het aan de afnemer is om de modifier er in de juiste situatie op te zetten / of te misbruiken?_

**Comment by bramhoosemans** [comment]
Helder. Ik ga peilen hoe vaak dit scenario voorkomt en wat de gewenste oplossingsrichting is.

**Comment by tfrijsewijk** [comment]
We kunnen ook een compactere versie van de Date Picker aanbieden? Dan snijden we de hele modal uit de userflow weg

**Comment by bramhoosemans** [comment]
Wat mij betreft gaat het inderdaad om de volgende opties:
1. Huidige implementatie met modal behouden en (het liefst specifieke `dso-modal-date-picker`) modifier toevoegen.
2. Deze werkvorm niet toestaan. Alternatief ontwerp maken zonder modal.

**Comment by bramhoosemans** [comment]
We accepteren voorlopig dat de Date Picker in Modal niet optimaal werkt. Dit issue wordt gesloten.
