### ISSUE TITLE
Date picker: label sluitknopje

### ISSUE THREAD

**Issue by Anto1nette** [dso-toolkit/dso-toolkit#1334]
### Waar
Date picker, modal waarin datum wordt gekozen

### Aanleiding
Het sluitknopje heeft label "sluit window", window is geen Nederlands

### Werkzaamheden
Knopje krijgt (net als andere sluitknopjes die we kennen) het label "sluiten".

### Gebruikersimpact
Beperkt: meeste screen reader gebruikers weten wel wat Window betekent.

**Comment by gofix** [comment]
Hij is moeilijk te vinden, die sluiten-knop, maar nu heet ie dan ook echt 'sluiten':
![image](https://user-images.githubusercontent.com/2689559/142250513-93e63ee1-90c9-4d16-999d-69108a5999f9.png)

(hoe je'm vindt? open de datepicker en doe shift-tab)

@timveld kun jij testen, op bv.:
https://dso-toolkit.nl/_1334-sluit-window-tekst/components/detail/date-picker.html
https://core.dso-toolkit.nl/_1334-sluit-window-tekst/iframe.html?id=date-picker--default&args=&viewMode=story

**Comment by gofix** [comment]
Ook zonder @timveld's test durf ik deze eigenlijk wel door te zetten.
