### ISSUE TITLE
Build: Release automatisering

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#1337]
# Aanleiding

Aan het einde van elke sprint wordt er een release opgeleverd. Sinds anderhalve maand is de onderlinge samenwerking tussen de maintainers, UX-ers en afnemers intensiever geworden: bugs worden gemeld, nieuwe functionaliteit aangevraagd of de scope van een feature (al dan niet in ontwikkeling) gewijzigd. Dit betekent dat er vaker dan de normale releasecycles wordt geleverd, de zogenaamde _gelegenheidsreleases_. Dit is een volwaardige release. Als er aan het einde van de sprint sinds de laatste gelegenheidsrelease geen werk is om uit te brengen, wordt er geen release uitgebracht.

Het uitrollen van een release naar NPM gaat automatisch, maar bij elke release zit er nog wat voorbereidingswerk (CHANGELOG controleren, versie bepalen & zetten, en tag schieten).

Op dit moment rollen we officiele releases uit naar NPM en dso-toolkit.nl. Voor topic releases ("branch releases") doen we dit alleen naar dso-toolkit.nl.

# Wens

We willen de branch releases ook naar NPM gaan deployen. Dan kunnen afnemers meegenomen worden in het ontwikkelproces en onze deliverables in hun applicaties testen zonder dat wij ze moeten uitbrengen in een release. Dit gaan wij in #2565 realiseren.

# Scope

Voordat #2565 kan worden gerealiseerd moet de package.json voorzien worden van een actuele versie. Dat wil zeggen: Het versienummer in package.json wordt onderdeel van de git historie.

Dat is nu niet het geval. Een release wordt gestart door een tag te schieten. Tijdens de build wordt het versienummer in de package.json gezet.

Het is nu niet mogelijk om te bepalen wat de versie voor een topic release wordt.

## Huidige opzet

In dit issue gaan wij het release proces aanpassen. Het proces is nu:

Developer (lokaal):
* CHANGELOG.md uitbreiden met versienummer (`## 1.2.3 - datum-van-vandaag`)
* Tag schieten (`v1.2.3`) en pushen

Buildstraat (CI/CD):
* Tag in package.json plaatsen
* Packages naar NPM publiceren

## Gewenste opzet

In het nieuwe proces wordt de versie tijdens de Developer (lokale) fase in de package.json geplaatst:

Developer (lokaal):
* CHANGELOG.md uitbreiden met versienummer (`## 1.2.3 - datum-van-vandaag`)
* Tag schieten (`v1.2.3`) en pushen
* Tag in package.json plaatsen

Buildstraat (CI/CD):
* Packages naar NPM publiceren

Dit gaan we uiteraard niet handmatig doen. We gaan naar tools als Lerna en release-it kijken.

# Acceptatiecriteria

* Een release wordt lokaal gemaakt.
* Een release wordt gemaakt met een "release commando". De input van dit commando is de absolute (of relatieve) versie.
* Alle relevante package.json's worden lokaal voorzien van de juiste versie

**Comment by gofix** [comment]
@tfrijsewijk klinkt goed, vooral benieuwd ben ik naar de "commitmessage conventie" en ook naar hoe we om gaan met de `changelog.md` en de release-headings daarbinnen.

**Comment by hansgrimm** [comment]
@tfrijsewijk is dit nog courant?

**Comment by tfrijsewijk** [comment]
Ja 👍

**Comment by tfrijsewijk** [comment]
Nog steeds courant, maar het einde is in zicht!

**Comment by tfrijsewijk** [comment]
> In de aanleiding lees ik iets over woensdag. Waarom woensdag 😔 ?

Woeps, dat was nog outdated. Bijgewerkt!
