### ISSUE TITLE
Icon als placeholder in kunnen zetten

### ISSUE THREAD

**Issue by smvandermeulen** [dso-toolkit/dso-toolkit#1338]
In de Tree View component maken we gebruik van de `dso-icon` component voor de open- en dichtklapper met 'chevron-down' en 'chevron-right'. Voor Tree View items die geen child items hebben willen we een leeg `dso-icon` kunnen inzetten.

**Comment by gofix** [comment]
Dit kan nu: ook een `<dso-icon />` kan geplaatst worden.
