### ISSUE TITLE
Select in context-container

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#1341]
## Werkzaamheden
Select component:
- Variant met flexibele breedte
- Label links uitgelijnd op 8px van de selectbox
- Verwerken in voorbeeldpagina activiteiten in Fractal https://dso-toolkit.nl/31.0.0/components/detail/activiteiten.html
-- Sorteer op:
-- Meest gekozen
-- Alfabetisch

![133_voorbeeld-1440](https://user-images.githubusercontent.com/598735/141312986-2b17abb9-693c-44ad-b018-84528b067aa0.png)

**Comment by gofix** [comment]
Testbaar!
https://dso-toolkit.nl/_1341.Select-in-context-container/
https://css.dso-toolkit.nl/_1341.Select-in-context-container/?path=/story/context--label

**Comment by bramhoosemans** [comment]
Mooi! Nog twee vragen:

- In de HTML/CSS Storybook is nog geen form select styling aanwezig; of zie ik dat verkeerd?
- Op de activiteiten voorbeeld pagina zou het mooi zijn om ook het responsive breakpunt (<480px) mee te nemen. Is dat mogelijk?

![132_responsive-gedrag](https://user-images.githubusercontent.com/598735/141991704-2d3c8416-9559-4da0-9247-815b4280d2a8.png)

**Comment by daverhelst** [comment]
@bramhoosemans 
- Klopt, er bestaat (nog) geen HTML/CSS Storybook component van formulier items. @gofix laten we het hier even over hebben
- Ik heb al wel het responsive breakpunt (<480px) kunnen regelen voor je

**Comment by gofix** [comment]
Tja, de vraag is wat nu te doen met het HTML/CSS storybook. Er is daar nog best een beetje werk te verrichten om daar ook de form-elementen en hun styling in onder te brengen. Dat is uiteraard niet de scope van de change hier.
We kunnen:
- het hier nu bij laten (dan is overduidelijk dat die select nog een keer moet);
- de change in storybook terugdraaien (maar wat er stond - een dropdown button - sloeg eigenlijk ook nergens op);
- zowel in label als container iets abstracters plaatsen;

Wat denk jij @bramhoosemans

**Comment by bramhoosemans** [comment]
@gofix wat mij betreft laten we het voor nu zo staan. Is niet in scope en is overduidelijk dat we er nog wat mee moeten.

**Comment by gofix** [comment]
Gevolg van dat @daverhelst nu het responsive gedrag heeft getuned is nog wel dit, is dat wel wenselijk @bramhoosemans 
![image](https://user-images.githubusercontent.com/2689559/142014621-1359215f-8353-454a-b3a4-79bceb792f09.png)

**Comment by bramhoosemans** [comment]
@gofix we hebben nog een issue waarin het filterblok een 'component' wordt, zie https://github.com/dso-toolkit/dso-toolkit/issues/1323. Daarin zou eventueel alternatief gedrag kunnen worden gerealiseerd toch?

@LiesbethVorst wat is het gewenste responsive gedrag van het filterblok?

**Comment by LiesbethVorst** [comment]
In het filterblok zou de knop Alle opties rechtsboven moeten blijven staan.

**Comment by gofix** [comment]
Laten we dan dit specifieke gedrag - dat dus eigenlijk wezenlijk, maar bedoeld, anders is dan het standaard gedrag van context, maar in #1323 meenemen. Ik noem het daar even expliciet.
