### ISSUE TITLE
Toetsenbordinteractie Tree View werkt niet met NVDA

### ISSUE THREAD

**Issue by smvandermeulen** [dso-toolkit/dso-toolkit#1342]
De recente (last-minute) aanpassingen aan de structuur van de aria attributen van de Tree View om te voldoen aan voorwaarden voor parent - child relaties, hebben de toetsenbordinteractie bij gebruik van NVDA stuk gemaakt. Bij deze wijzigingen zijn we er van uitgegaan dat de Cypress tests voldoende borging geven om deze wijzigingen door te voeren. Helaas blijkt het testen met NVDA _aan_ ook niet meteen tot het gewenste (falende) resultaat te leiden.

Bij de laatste aanpassingen zijn de `treeitem` attributen van de `<p>` in de `<li>` verhuisd naar de `<li>` zelf, het focus gedrag met de roving tabindex is echter op de `<p>` blijven staan. De keuze om het focus gedrag op deze inhoud in de `<li>` zetten i.p.v. op de `<li>` zelf is vooral ingegeven door de focus border, die nu gewoon door de browser zelf getekend kan worden. Zouden we de `<li>` gebruiken voor focus dan zou het hele `<li>` blok inclusief de childnodes de focus border krijgen. Om dit weer visueel netjes te krijgen zou de focus border via css op de inhoud (`<p>`) geplaatst kunnen worden.

De vraag is nu: gaan we terug naar het originele concept en plaatsen we bij de `<li>` een `role="none"` om de hiërarchische structuur valide te maken, of maken we de `<li>` elementen focusable en gaan we focus borders handmatig aan/uit zetten.

**Comment by timveld** [comment]
De eerste optie (terug naar oude opzet en hiërarchische structuur repareren met role none) lijkt me prima. NVDA negeert daarmee de <li> tags (en dat is wat we willen, voor NVDA moet het overkomen als een treeview met treeitems en die li is daarbij niet relevant of zelfs storend). 
Tweede optie (li elementen focusable maken als ik het goed begrijp?) klinkt minder goed en ingewikkelder, weet niet zeker of ik hem goed begrijp maar voor NVDA heeft die oplossing geen voordelen.

**Comment by tfrijsewijk** [comment]
Als we op de `li` een `role="none"` moeten zetten zodat de user agent (niet alleen NVDA!) de `li` negeert.. waarom maken we er dan niet gewoon 'n `div` van?

Anders gesteld: Is een `ul` met alleen maar `li role="none"` niet hetzelfde als 'n lege `ul`? Het is 'n lijst zonder (geldige?) items

**Comment by timveld** [comment]
Aria heeft alleen impact op hulptechnologie zoals NVDA. En dit geheel los van de elementen die er werkelijk staan. 
Als je de li's role none geeft dan moet je de ul waarschijnlijk ook role none geven. 
Maar als je het met divs simpeler kunt oplossen, uitstekend... de lijst heeft hier geen meerwaarde (het is semantisch ook geen lijst maar onderdeel van een treeview). Hoe simpeler (en hoe minder aria) hoe beter. 

Achtergrond: 
"the first rule of aria is not to use it". En daaraan zou ik toevoegen: "als je het toch gebruikt, zo codeer dan simpel en minimaal als mogelijk". 
 
Als we in een betere wereld leefden zou html standaard een <treeview> <treeitem> ... constructie kennen die een toegankelijke treeview zou opleveren. Helaas bestaat die niet en ben je gedwongen zelf een custom treeview te bouwen, waar je dan met aria de juiste roles op de elementen zet. Maar in de kern wil je eigenlijk <div role=treeview> <div role=treeitem> ... hebben. 
Als jij kiest voor bijvoorbeeld een <ul role=none> <li role=treeitem> <a role=none> ... constructie is het effect op NVDA precies hetzelfde. De extra complexiteit van lijst en link voeg je toe om de boel mooi op te maken of voor niet-aria gebruikers beter te laten werken, voor NVDA is het resultaat van deze 2 constructies constructies precies hetzelfde.

**Comment by smvandermeulen** [comment]
Ik zou dan toch nog wel even bij `<ul>`'s met `<li>`'s willen blijven. 
De Tree View is nu vrijwel weer in de staat die @timveld heeft getest. Wel is er nadien nog de mogelijkheid van een href toegevoegd bij Tree Items waarmee direct een `<a>` wordt gerendered (zie: Bebouwde omgeving > bouwelementen > afvoerbuizen).
Als extra heb ik nog toegevoegd dat het attribuut `aria-busy` bij het dynamisch inladen (zie: Bebouwde omgeving > complexen) op de `<p>` wordt gezet, in combinatie met het zetten van `aria-expanded=true` _nadat_ de items zijn geladen. 

Kun je nog een keer testen @timveld via https://core.dso-toolkit.nl/_1342-Toetsenbordinteractie-Tree-View-werkt-niet-met-NVDA/?path=/story/tree-view--tree-view

**Comment by timveld** [comment]
Doet het weer, en je hebt ook het probleem met aria-busy opgelost; dit doet nu precies wat ik had bedacht!
Dus kan de volgende release in en issues kunnen gesloten worden.
