### ISSUE TITLE
Klikken in de Tree View op een item dient de roving tabindex naar dat item te verplaatsen

### ISSUE THREAD

**Issue by smvandermeulen** [dso-toolkit/dso-toolkit#1348]
De Tree View maakt gebruik van een roving tabindex, waarmee er altijd maar één element binnen de Tree View focusable is (`tabindex = 0`). Bij gebruik van toetsenbord wordt de `tabindex = 0` telkens op het te focussen element gezet en `tabindex = -1` op het element dat focus had. Tabbed de gebruiker uit de Tree View en weer terug, dan zal altijd de focus hersteld worden op het juiste element.
Wanneer de gebruiker een Tree View item klikt dient de roving tabindex ook naar het geklikte item verplaatst te worden.

**Comment by smvandermeulen** [comment]
@DHvD-Michael

**Comment by smvandermeulen** [comment]
@timveld Er is een functionaliteit aan de Tree View toegevoegd waarbij we de tabindex verplaatsen bij klikken. Mogelijk heeft dit ook weer invloed heeft op andere zaken, zou je daarom nog een keer willen testen of alles nog in orde is: https://core.dso-toolkit.nl/_1342-Toetsenbordinteractie-Tree-View-werkt-niet-met-NVDA/?path=/story/tree-view--tree-view

**Comment by timveld** [comment]
@smvandermeulen  heb extra getest met in / uit tabben en klikken, lijkt goed te werken.
