### ISSUE TITLE
Tree View items dienen een "selected" en een "active" state te ondersteunen

### ISSUE THREAD

**Issue by smvandermeulen** [dso-toolkit/dso-toolkit#1349]
Om aan te geven welke items in een Tree View 'gevonden' zijn dienen Tree View items een selected state te ondersteunen. Daarnaast kan een item ook de active state hebben, bijvoorbeeld om aan te geven dat het item geopend is.

**Comment by smvandermeulen** [comment]
@DHvD-Michael

**Comment by DHvD-Michael** [comment]
@smvandermeulen Het idee is om "selected" Bold en Underline te geven en bij "active" alleen Bold. "default" is met alleen underline in tree view voor RTR.

**Comment by DHvD-Michael** [comment]
![RTR - tree view - meerdere resultaten](https://user-images.githubusercontent.com/4227175/142393284-014b12ed-ab1e-4859-bd5c-25d04aaf5a91.png)
Bijgaand ook een plaat als voorbeeld.

**Comment by DHvD-Michael** [comment]
![RTR - link states in Tree View](https://user-images.githubusercontent.com/4227175/143270128-70fe908e-f443-49ef-baf1-7eec63bcc64a.png)

Op basis van onze sparsessie van net wordt het volgende meegenomen in dit Github issue:
- Hover state waarbij underline verdwijnt wordt meegenomen.
- Selected state => voor alle gevonden resultaten.
- Active state => item waarop geklikt is.
- Als op een gevonden resultaat geklikt wordt, dan krijgt het naast de selected state ook een active state.
- Bij selected state wordt ook screenreader behoefte meegenomen:
-- Bij een gevonden resultaat wordt een screen reader only prepend "Resultaat: " toegevoegd aan het betreffende resultaat. 
-- Een resultaat als "Indieningsvereisten Aanvraag vergunning" wordt dan als volgt opgelezen: "Resultaat: Indieningsvereisten Aanvraag vergunning" door screen reader. 
-- Gevonden resultaten zijn tevens sneller in de tree-view met een toetsenbord te vinden met de letter "R" op het toetsenbord van "resultaat"
-- N.B. Mocht blijken dat teveel situaties zijn waarbij niet-resultaten naar boven komen met de letter "R" op het toetsenbord, dan kan in een latere iteratie (met een nieuw ticket) dit verder worden verfijnd.

**Comment by smvandermeulen** [comment]
@timveld Er staat een volgende versie van de Tree View klaar om getest te worden: https://core.dso-toolkit.nl/_1349-Tree-View-items-selected-en-active-state/?path=/story/tree-view--tree-view
Wanneer je een item klikt (of Enter gebruikt) wordt deze "active", dit is vooral een visuele state.
Met behulp van een nieuwe zoekbox kun je items zoeken die vervolgens "selected" worden. Je kunt door de selected items stappen met de "R" toets.

**Comment by timveld** [comment]
Morgen bespreken 
* active state wordt vet maar verder niet aangekondigd. Als de betekenis "huidige item" is dan aria-current?
* Bij het zoekveld zullen we iets moeten verzinnen waardoor het aantal gevonden resultaten wordt aangekondigd.  
* Het met r navigeren tussen resultaten vind ik toch echt te "quick and dirty". Probleem is onder meer dat een goedziende toetsenbordgebruiker (die het woord resultaat niet ziet) verwacht dat een druk op de eerste zichtbare letter naar het item springt. De conventie voor vorige / volgende resultaat is ctrl + page up/down, maar dat conflicteert met Firefox. Page up / down kan wel, die toetsen gebruiken we bewust niet voor scrollen maar voor deze functie lijken ze me heel geschikt. 
* Er moet een hint zijn dat page up / down deze functie heeft, zowel leesbaar als uitgesproken. Hoe / waar geven we die hint weer? Vast of pas als de treeview toetsenbordfocus krijgt? Uitspreken door met aria-describedby aan de treeview te koppelen.

**Comment by smvandermeulen** [comment]
@timveld Ik heb de `aria-current` toegevoegd wat vind je daarvan?
En verder: 
- Het zoekveld is geen onderdeel van de Tree View zelf, het is hier alleen geïntroduceerd om een selectie te kunnen maken in de Tree View. In het 'echt' zal de afnemer zelf een zoekformulier maken en zelf de boom met gevonden resultaten aanbieden aan de Tree View. 
- Het gedrag van de "R" staat expliciet in het issue, maar ik voel wel met je mee dat het veel side-effects heeft. Page up / down lijkt me wel gewoon voor scrollen gereserveerd zodra en een scrollbar verschijnt, dus ik verwacht niet dat we niet kunnen inzetten. Zijn er geen andere oplossingen voor het doorlopen van zoekresultaten?

**Comment by DHvD-Michael** [comment]
@timveld : 

- Met de "r" naar een resultaat springen hebben we eerder bij onze voorbereidingen uitgebreid over gehad. Dit was de oplossingsrichting waar we destijds op voorsorteerden. Het schuurde toen ook, maar we wilden dit agile aanvliegen. Naar een resultaat springen beschouwden we als essentieel voor bruikbaarheid voor gebruikers met beperkingen op zicht en gebruikers die afhankelijk zijn van navigeren via een toetsenbord. Iemand door tientallen of honderden items in de tree view laten navigeren om bij een resultaat te kunnen, is onbruikbaar. We hadden daarbij als uitgangspunt genomen dat ziende gebruikers de resultaten visueel terugvinden door het uiterlijk, nu bold van de resultaten. Maar dit creëert inderdaad een beperking als ziende gebruikers ook met het toetsenbord willen navigeren.
- Voorstel: "Resultaat" is nu sr-only. Dit aanpassen naar een zichtbare vorm. Dan is behoud van informatie geborgd. Oftewel als in het Storybook voorbeeld gezocht wordt naar bijvoorbeeld "complex". Dan verschijnt in de treeview het als "Resultaat: complexen". Dit lijkt dan ook de kleinste impact te hebben. We blijven dan nog dicht op het WAI-ARIA voorbeeld qua patroon. Andere interactievormen moeten we later over doorsparren. Dit kan in een volgende iteratie qua oplevering. 
- Kun je aangeven waar de conventie voor CTRL + Page Up / Page Down voor Volgende en Vorige Resultaten op gebaseerd is? Ik heb bij NVDA en JAWS de sneltoets-lijsten even doorgenomen. Ik zie deze interactievorm daar niet terugkomen. Page Up en Page Down zijn ook vaker niet meer zichtbaar aanwezig als toetsen op toetsenborden. De bijbehorende sneltoets is voor velen onbekend. 

@timveld en @smvandermeulen : 
- Over het zoekveld: in de RTR wordt het aantal resultaten opgelezen. Het zoekveld valt inderdaad sec buiten het Web Component van de Tree View. Ik ben wel van mening dat de voorbeelden die we aanbieden in Storybook wel dienen te voldoen aan WCAG en onze best practices. Voorstel: Naderhand een separaat voorbeeld aanmaken in Storybook "Treeview met zoekresultaten", waarin de beoogde implementatie van een zoekveld met het oplezen van resultaten is opgenomen.

**Comment by timveld** [comment]
* aria-current werkt. Als het klopt dat dit het huidige item representeert, opgelost. 
* Er is bewust voor gekozen page up en down in de treeview niet te gebruiken, omdat het aantal te scrollen items niet vast te stellen is. Dus kan wel geruikt worden voor volgende / vorige resultaat. Maar we kunnen dit wel even laten rusten en er bij de implementatie (als we de context beter kennen) op terug komen, huidige implementatie werkt wel
* Als het voorbeeld in deze vorm (met zoekveld) in de toolkit komt dan moeten we (met een alert of live region) minstens aangeven of er al dan niet resultaten zijn, anders hebben we een voorbeeld met duidelijke WCAG afwijking in de toolkit.

**Comment by DHvD-Michael** [comment]
@smvandermeulen 

Net even met Tim afgestemd over dit issue. Dit issue mag worden afgerond: 

- Hierbij hanteren we de "r" naar resultaten springen zoals gespecificeerd. "Resultaat: " blijft ook sr-only. 
- Aria-current graag meenemen in dit ticket.
- Page Up / Page Down is buiten scope van dit ticket.
- Zoekveld in combinatie met Tree View is buiten scope van dit ticket. 

In latere tickets worden andere aspecten verder opgepakt. 
N.B. Het is handig voor Tim om eerst een implementatie van dit component te ervaren. In aanstaand increment is implementatie van dit Tree View Web Component beoogd bij een ontwikkelteam.
