### ISSUE TITLE
Hamburger menu small view example

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#135]
In #87 is het navigatie component los gemaakt van het menu/header component. Het responsive gedrag moet nog uitgewerkt worden dmv. de Fractal Switches (zoals ook in #106) is gedaan.

Uitwerking met extra variant. Met de demo checkboxes kan het open en dicht gesimuleerd en getoond worden

**Comment by tfrijsewijk** [comment]
https://www.dso-toolkit.nl/3.0.0-alpha.0/components/detail/menu.html

**Comment by MichielDHVD** [comment]
Gezien en wordt verplaatst naar Done
