### ISSUE TITLE
Treeview deprecaten

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#1351]
**Aanleiding**
Er is een nieuwe treeview beschikbaar, waardoor de "oude" niet meer essentieel is. Dus deprecation. De reden dat de nieuwe RTR-Treeview niet wordt verwerkt in Fractal is vanwege end of life van Fractal.  

**Werkzaamheden**
Deprecation Treeview

**Ontwerp**
NVT

**Testen**
NVT

**Acceptatiecriteria**
Oude werkvorm van Treeview niet beschikbaar.

**Comment by gofix** [comment]
Zie https://dso-toolkit.nl/_1351-treeview-deprecation/components/detail/tree-view.html (niet meer te benaderen vanuit het menu, maar nog wel opvraagbaar, zodat we mooi kunnen zien dat ie deprecated is)
