### ISSUE TITLE
Node 16

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#1359]
Node 14 wordt niet meer ondersteund, op naar de volgende LTS

**Comment by tfrijsewijk** [comment]
cc @Anto1nette

**Comment by gofix** [comment]
Lokaal geen echte problemen, zo lijkt:
- gewoontegetrouw (bij dit soort updates) `rimraf` ik even alle `node_modules`
- `yarn install` -> Done with warnings in 6m 11s
- `yarn build` -> "No name was provided for external module '@storybook/addon-actions' in output.globals – guessing 'addonActions'"
- `yarn start:all` -> all good
- `yarn fractal` -> all good
- `yarn workspace @dso-toolkit/core cypress` -> all good

Onderweg wordt er wel van alles geroepen over nieuwe storybook versie, nieuwe cypress versie. Maar alles werkt, dus fine voor deze scope.

**Comment by gofix** [comment]
Getest, nu ook op Apple silicon:
<img width="2048" alt="2021-12-01_20-44-20" src="https://user-images.githubusercontent.com/2689559/144305840-db90b394-884d-4156-b6c1-ee6022ddd05e.png">
