### ISSUE TITLE
Verbeteringen Tooltip en Toggletip

### ISSUE THREAD

**Issue by gofix** [dso-toolkit/dso-toolkit#1362]
### Waar
https://dso-toolkit.nl/31.0.0/components/detail/tooltip-css.html
https://dso-toolkit.nl/31.0.0/components/detail/tooltip.html
https://dso-toolkit.nl/31.0.0/components/detail/toggletip.html

### Aanleiding
Met het testen van de Toggletip zijn een aantal (stylings) issues naar boven gekomen die we willen aanpakken. Onder de werkzaamheden een opsomming van de aandachtspunten.

### Werkzaamheden
- Styling bijwerken (geen transparante achtergrond en consistente dropshadow)
`background: #FFFFFF;`
`box-shadow: 0 2px 8px 0 rgba(0,0,0,0.40);`

- Pijltje tooltip wijst naar gekoppeld element (niet vast in het midden).
Zie overflow prevention op smalle viewport op https://popper.js.org

- Breedte tooltip op smalle viewport
In ontwerp spreken we van een maximale breedte van 640px (default) of 320px. Als de beschikbare ruimte kleiner is zou de tooltip zich daaraan moeten aanpassen.

- Safari rendering bug?
De huidige implementatie met dropshadow rendert niet goed in Safari (getest in Versie 15.1 (17612.2.9.1.20)). 
![image](https://user-images.githubusercontent.com/2689559/143771281-ea276c92-4756-46d0-b5ef-4fac6b2fe1c5.png)

- Cursor bij de Toggletip blijft een 'pijltje'. Dit moet, net als bij de losse Info Button, een 'handje' worden.

### Ontwerp
Zie bijgevoegde schermen.
[tooltip-specificaties.zip](https://github.com/dso-toolkit/dso-toolkit/files/7613675/tooltip-specificaties.zip)

### Testen
Test de weergave en werking in verschillende browsers
Extra aandachtspunt: als een Toggletip is geopend en er verschijnt een modal wordt de focus verplaatst én sluit daarmee de Toggletip.

**Comment by gofix** [comment]
Nog een bevinding, zie https://github.com/dso-toolkit/dso-toolkit/pull/1366#issuecomment-995207495, de tooltip die daarin een tabel zit, laat _heel kort_ een scrollbalkje verschijnen bij hover.

**Comment by gofix** [comment]
@bramhoosemans die Safari rendering bug, ervaar jij die nog steeds? 
Ikzelf check zojuist op mijn Mac en kan het niet (meer?) reproduceren:
![image](https://user-images.githubusercontent.com/2689559/152685287-75560854-2486-4bfb-b2ed-9fed64e2d38a.png)

Safari : Versie 15.2 (17612.3.6.1.6)

**Comment by gofix** [comment]
Wat mij juist weer wel opvalt, is dit, op https://dso-toolkit.nl/33.2.0/components/detail/mijn-projecten.html
![image](https://user-images.githubusercontent.com/2689559/152685419-d7175c0f-f7d9-40d8-bfa4-b5b9d53a2391.png)

Dit komt omdat de tooltip hier in een `.dso-table-responsive` staat waarvan de overflow-x auto is. Als ik deze tabel 'gewoon' plaats (dus niet responsive) wordt de tooltip niet afgebroken, en wordt ook het gevraagde `position="top"` gehonoreerd:

![image](https://user-images.githubusercontent.com/2689559/152685535-0470cd08-6756-4b66-b7a1-d5a09b744e09.png)

**Comment by gofix** [comment]
Over dit afbreekgedrag van de responsive table, daarover wordt ook op https://getbootstrap.com/docs/4.0/content/tables/#responsive-tables (waar de oorspronkelijke responsive tabel vandaan komt) al genoemd:
> Vertical clipping/truncation
Responsive tables make use of overflow-y: hidden, which clips off any content that goes beyond the bottom or top edges of the table. In particular, this can clip off dropdown menus and other third-party widgets.

**Comment by bramhoosemans** [comment]
> @bramhoosemans die Safari rendering bug, ervaar jij die nog steeds?

Ja, ik krijg nog steeds vreemde rendering van de tooltips in release 33.2.0. Zowel in Fractal als Storybook..

**Comment by bramhoosemans** [comment]
Hertest in Safari Versie 15.3 (17612.4.9.1.5) en de rendering bugs zijn verdwenen.

**Comment by PieterVerheij** [comment]
@bramhoosemans Die grotere linker marge bij de toggletip, is dat gewenst?
![image](https://user-images.githubusercontent.com/25430835/153369833-c27a14f5-fd8e-4e8f-bed5-57d67822d09d.png)

**Comment by bramhoosemans** [comment]
> @bramhoosemans Die grotere linker marge bij de toggletip, is dat gewenst?
> ![image](https://user-images.githubusercontent.com/25430835/153369833-c27a14f5-fd8e-4e8f-bed5-57d67822d09d.png)

De marge is onderdeel van de Info Button. Deze komt vaak voor aan het einde van een zin, waardoor de marge waarschijnlijk is toegevoegd. Dit zou ik nu niet wijzigingen. Zeker niet in de scope van dit issue.

**Comment by PieterVerheij** [comment]
Ok, duidelijk!

**Comment by gofix** [comment]
Er kan getest worden @bramhoosemans 
Tooltip - in HTML/CSS Storybook
https://css.dso-toolkit.nl/_1362-Verbeteringen-Tooltip-en-Toggletip/?path=/story/tooltip--tooltip
-> eigenlijk kan deze op termijn wel een keer weg denk ik. Wie gaat er nu ooit nog zelf een tooltip tekenen nu er een Web Component is...?

Tooltip - in Web Component Storybook
https://core.dso-toolkit.nl/_1362-Verbeteringen-Tooltip-en-Toggletip/?path=/story/tooltip--as-child

Toggletip - in Web Component Storybook
https://core.dso-toolkit.nl/_1362-Verbeteringen-Tooltip-en-Toggletip/?path=/story/toggletip--toggletip

Toggletip (Web Component) | DSO Toolkit | Component Library
https://dso-toolkit.nl/_1362-Verbeteringen-Tooltip-en-Toggletip/components/detail/toggletip.html

Tooltip (Web Component) | DSO Toolkit | Component Library
https://dso-toolkit.nl/_1362-Verbeteringen-Tooltip-en-Toggletip/components/detail/tooltip.html

Tooltip (CSS Component) | DSO Toolkit | Component Library
https://dso-toolkit.nl/_1362-Verbeteringen-Tooltip-en-Toggletip/components/detail/tooltip-css.html

**Comment by bramhoosemans** [comment]
Ziet er goed uit.

> -> eigenlijk kan deze op termijn wel een keer weg denk ik. Wie gaat er nu ooit nog zelf een tooltip tekenen nu er een Web Component is...?

Dat klopt, maar dan moeten we er zeker van zijn dat geen team meer gebruik maakt van de HTML/CSS.

**Comment by gofix** [comment]
Ok, dat zien we dan later nog wel eens. We pakken door!
