### ISSUE TITLE
Standaard $grijs-5 als grijze achtergrond

### ISSUE THREAD

**Issue by gofix** [dso-toolkit/dso-toolkit#1363]
#### Componenten met 10% zwarte achtergrond
Shopping Cart
Table (10% hover/active rijen)
Highlightbox
Info (toelichtingen bij formulier elementen/conclusie)
Footer

#### Componenten met 5% zwarte achtergrond
Accordion conclusie (5% default, 10% hover)
Cards list (5% hover)
Tabs (5% hover)
Label
Files
Filterblok
Document header

### Aanleiding
Lichtere tint achtergrond gebruiken, $grijs-5 ipv $grijs-10. Aanvullend hebben we een inventarisatie gemaakt van het huidige gebruik en gezien dat deze niet overal consistent is. Vandaar de wens om deze overal gelijk te trekken. 

### Werkzaamheden
Gebruik standaard $grijs-5 (#F2F2F2) als grijze achtergrond.
Shopping Cart
wijzig achtergrond naar #F2F2F2.
Table 
wijzig hover en active state naar #F2F2F2.
Highlightbox
wijzig achtergrond naar #F2F2F2.
Info
Wijzig achtergrond naar #F2F2F2
Zet het icoon (kruisje) 8px van de rand
Wijzig de icoon (kruisje) kleur naar #191919
Footer
wijzig achtergrond naar #F2F2F2.

**Comment by daverhelst** [comment]
@bramhoosemans De aanpassingen staan klaar om bekeken te worden, kun jij een blik werpen om te zien of het zo naar wens is?

URL's:
https://dso-toolkit.nl/_1363.Standaard-grijs-5-als-grijze-achtergrond/components/detail/shopping-cart.html
https://dso-toolkit.nl/_1363.Standaard-grijs-5-als-grijze-achtergrond/components/detail/table.html
https://dso-toolkit.nl/_1363.Standaard-grijs-5-als-grijze-achtergrond/components/detail/highlight-box.html
https://dso-toolkit.nl/_1363.Standaard-grijs-5-als-grijze-achtergrond/components/detail/info.html
https://dso-toolkit.nl/_1363.Standaard-grijs-5-als-grijze-achtergrond/components/detail/footer.html

**Comment by bramhoosemans** [comment]
Netjes. Volgens mij precies zoals beschreven 👍
