### ISSUE TITLE
Search Bar placeholder tekst loopt buiten input in Safari

### ISSUE THREAD

**Issue by gofix** [dso-toolkit/dso-toolkit#1364]
De placeholder tekst loopt buiten het invoerveld in Safari.
### Omgeving/browser
Safari Versie 15.1 (17612.2.9.1.20)

###  Componenten:
https://dso-toolkit.nl/31.0.0/components/detail/group-search-bar.html
https://dso-toolkit.nl/31.0.0/components/detail/search-bar.html

### Werkzaamheden:
Naast de Search Bar lijkt me dat de oplossing ook toepassen op de Input.

**Comment by gofix** [comment]
@bramhoosemans is dit probleem er nog, want... ik wilde het net gaan oplossen, maar zie het op mijn Mac niet meer...
<img width="1461" alt="2021-12-01_21-00-10" src="https://user-images.githubusercontent.com/2689559/144305116-d39d84cf-4075-4720-9392-fdfe1aa3b3f6.png">

**Comment by gofix** [comment]
Herstel. Toch wel. Het is natuurlijk geen Mac issue, maar een Safari issue. Reproduceerbaar:
<img width="1141" alt="2021-12-01_21-01-20" src="https://user-images.githubusercontent.com/2689559/144305303-8803b1f3-30b4-47f7-9825-84e4507d8f80.png">

**Comment by gofix** [comment]
Het is gefixed. Het was overigens geen Safari gekkigheid, maar gewoon DSO Toolkit styling. Toevallig was alleen Safari de browser die het ondersteunde!

Waar de styling vandaan kwam?
https://github.com/dso-toolkit/dso-toolkit/commit/831f7f743ab3d61599a4da39a27fec2018f80b2a
https://github.com/dso-toolkit/dso-toolkit/issues/625

Maar, dat fenomeen treedt gelukkig ueberhaupt niet meer op:
![image](https://user-images.githubusercontent.com/2689559/144489354-fb9cf6e2-a91c-47a4-a57e-fc6940b08f9d.png)

@bramhoosemans @MichielDHVD 
https://dso-toolkit.nl/master/components/preview/search-bar--huge-placeholder.html
https://dso-toolkit.nl/master/components/preview/group-input--input-text-huge-placeholder.html

**Comment by bramhoosemans** [comment]
Mooi zo. Test in Safari laat nu ook het gewenste gedrag zien.
