### ISSUE TITLE
Tooltip

### ISSUE THREAD

**Issue by DjangoBlok** [dso-toolkit/dso-toolkit#137]
Seems that tooltip styling hasn't been taken care of yet.
My proposal is showing the tooltip without delay and something like this. 
Font: 14 points Asap White
Back: #39870C
Corner radius: 4
Light blur shadow

![owrek-499_tooltip](https://user-images.githubusercontent.com/34900082/40360937-fd11c378-5dc7-11e8-8513-0de72878fcac.png)

But as always I am open for better suggestions...

**Comment by DjangoBlok** [comment]
Wat mij betreft wordt hij dan te groot @MichielDHVD. 
Maar als het verboden is 14px te gebruiken dan kan het niet natuurlijk...

**Comment by Anto1nette** [comment]
Graag tooltip in deze vorm, zie bijlage. @MichielDHVD 
![screen shot 2018-05-29 at 16 11 28](https://user-images.githubusercontent.com/1033595/40664450-4087b9c6-635b-11e8-9a9a-59a5f4f2bd26.png)

**Comment by MichielDHVD** [comment]
Ik heb even geinterpreteerd wat de afmetingen zijn van dit ontwerp. Zodat het makkelijk na te bouwen is. Dat ziet er als volgt uit. 

![tooltip](https://user-images.githubusercontent.com/36912722/40718518-9b38b25c-6410-11e8-8f74-6b06dfdb6f7b.png)

Klopt dit @Anto1nette @DjangoBlok ?

**Comment by Anto1nette** [comment]
Bij mij is de rechthoek120x32 en het driehoekje 16x8 @MichielDHVD Morgen anders even doornemen?

**Comment by VolleMelk** [comment]
Zit er een max-width op? Wat te doen met lange teksten? Of laten gaan en de implementator op te lange teksten aanspreken?

**Comment by DjangoBlok** [comment]
Ik zou wel met een max width werken en de tekst wrappen. De rest is inderdaad aan de implementator.

**Comment by MichielDHVD** [comment]
Max width gaan we instellen op 240px.  

Is dan bij deze alles compleet ? Voeg ook even een vernieuwde afbeelding toe waar alles op 1 plek staat. @VolleMelk 

Een laatste opmerking is dat er mogelijk een small text bij gaat komen in het kopje typography. Dit zou 14px worden. Dit is nog in overleg. Jij bent hier voorstander van toch @DjangoBlok ? 

![tooltip](https://user-images.githubusercontent.com/36912722/41083842-8b5ecb00-6a32-11e8-93cd-fbe7c4ae22a0.png)

**Comment by DjangoBlok** [comment]
OK, ziet er prima uit! Ik kijk er naar uit!
Ik ben op zich wel een voorstander van kleinere tekst in specifieke gevallen.

**Comment by VolleMelk** [comment]
Ik til deze naar de volgende release: Wij hebben nu een tooltip gemaakt maar dit is een typisch component wat samen met de implementator gemaakt moet worden. Wat verwacht de developer (React/Angular)?

Dit hoeft niet meteen weer 3 maanden op de plank te liggen, we kunnen (en dat moedig ik ook aan) veel sneller releasen (major, minor of patch maakt dan niet uit).

**Comment by tfrijsewijk** [comment]
https://www.dso-toolkit.nl/3.0.0-alpha.0/components/detail/tooltip.html

**Comment by MichielDHVD** [comment]
Gezien en wordt verplaatst naar Done. Als ik het goed begrijp is de rest hoe het gebruikt wordt developer implementatie?
