### ISSUE TITLE
Nieuwe 'conclusie' iconen toevoegen

### ISSUE THREAD

**Issue by gofix** [dso-toolkit/dso-toolkit#1375]
**Werkzaamheden**
Iconen toevoegen.

Contact > `call`
Aanvraag > `document`
Plichtenvrij > `check-circle`
Verbod > `forbidden`

Het huidige `forbidden` icoon wijzigen in `status-forbidden`.

Let op: de gewijzigde naamgeving ook toepassen in https://dso-toolkit.nl/master/components/detail/conclusion.html

**Comment by gofix** [comment]
[DSOT-226.zip](https://github.com/dso-toolkit/dso-toolkit/files/7663283/DSOT-226.zip)

**Comment by gofix** [comment]
@bramhoosemans kun jij een blik werpen op:

Icon (CSS Component) in Fractal
https://dso-toolkit.nl/_1375-Nieuwe-conclusie-iconen-toevoegen/components/preview/icon-css.html

Conclusion in Fractal
https://dso-toolkit.nl/_1375-Nieuwe-conclusie-iconen-toevoegen/components/preview/conclusion.html

Conclusion in Storybook
https://css.dso-toolkit.nl/_1375-Nieuwe-conclusie-iconen-toevoegen/?path=/story/conclusion--forbidden

**Comment by bramhoosemans** [comment]
> @bramhoosemans kun jij een blik werpen

Ziet er naar mijn idee goed uit 👍
