### ISSUE TITLE
Toggletip in Safari sluit niet en zijn interactieve elementen niet met toetsenbord te benaderen

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#1379]
**Aanleiding**
Bij het testen van de alternatieve styling op de Info button (en geïntegreerd in de Toggletip) liepen we tegen een aantal bugs aan in Safari. Het gedrag is in Fractal en Storybook gelijk.

https://dso-toolkit.nl/32.0.0/components/detail/toggletip.html

**Bevindingen**
- Getest op macOS Monterey Versie 12.0.1 / Safari Versie 15.1 (17612.2.9.1.20)
- Als je een toggletip opent dmv een muisklik wordt deze niet gesloten en kunnen we meerdere toggletips tegelijk geopend worden.
- Als met toetsenbord genavigeerd worden naar een Toggletip met interactieve content wordt met 'tab' de Toggletip gesloten. En is de interactieve content niet te bereiken.

**Testen**
Testen in verschillende browsers (DoD)

![Schermafbeelding 2021-12-13 om 16 03 07](https://user-images.githubusercontent.com/598735/145836131-e1c447f3-89fd-4db9-9800-8a3fdbc4822d.png)

**Comment by gofix** [comment]
De bevinding dat je in safari inderdaad meerdere toggletips openhoudt als je met muis bedient klopt. De bevinding dat toetsenbordnavigatie niet goed werkt matcht niet met mijn beleving. Als ik met TAB navigeer door de pagina, en dan bij een toggletip met enter open, kan ik prima de interactieve content bereiken. Overigens heb ik wel in Safari het toetsenbordgedrag zodanig ingesteld dat ik ueberhaupt iets kan:

> To turn on full keyboard navigation in Safari, go to:
> Preferences ( ⌘ + , )
> Advanced (the last tab)
> Accessibility.
> “Press tab to highlight each item on a webpage” checkbox.

<img width="619" alt="2021-12-31_08-52-17" src="https://user-images.githubusercontent.com/2689559/147810709-ce1b0507-d25c-4536-a1fc-b41f58f0b9a8.png">

Doe ik dat niet, snap ik niet eens hoe ik moet navigeren door de pagina.

https://user-images.githubusercontent.com/2689559/147810733-7916c99d-910c-4df1-b86b-80eb82f80420.mp4

**Comment by gofix** [comment]
Over het niet-sluiten van de toggle-tip na openen ervan met muis: ook [ESC] sluit 'm niet.

**Comment by gofix** [comment]
Noot: die eventListeners zijn er dus wel, maar ze doen niks :(
<img width="567" alt="2021-12-31_09-33-06" src="https://user-images.githubusercontent.com/2689559/147812546-3cc9dd12-0d54-4caf-83bb-c627bea18c61.png">

**Comment by gofix** [comment]
Oplossingsrichting in zicht: als het element dat naar de events moet luisteren een `tabindex` krijgt, werkt het wel.

**Comment by gofix** [comment]
Visueel heeft de change wel impact:

<img width="433" alt="2021-12-31_10-33-42" src="https://user-images.githubusercontent.com/2689559/147815521-36a86380-b9e4-4118-872c-69ed77db82d6.png">

<img width="438" alt="2021-12-31_10-34-50" src="https://user-images.githubusercontent.com/2689559/147815546-c6219c1b-f457-40c2-b385-cbff22b615a1.png">

... de vraag is of we deze ongewenste focus styling (in Safari) verwijderd krijgen.

**Comment by gofix** [comment]
Note to self: Wellicht kan ik hier iets mee: https://github.com/microsoft/fast/issues/2812
```
    /* Provide basic, default focus styles. */
    :host(:focus) { }
```
Want, technisch moet het web component dan wel focusable zijn, we hoeven het echt niet te zien, de werkvorm zelf maakt al duidelijk genoeg dat ermee geinteracteerd wordt.
