### ISSUE TITLE
Input-type number heeft geen label in een List-Button

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#1386]
Waar
https://dso-toolkit.nl/master/components/detail/list-button.html

Aanleiding
Ontbrekend label overgebleven uit https://github.com/dso-toolkit/dso-toolkit/issues/1220

Werkzaamheden

- De input bij een input-number in een list-button zou ook een bijbehorende label moeten hebben.

**Comment by gofix** [comment]
Bespreken: een optie zou zijn de input in deze vorm `aria-labelledby` te laten verwijzen naar de button (die dan een `id` krijgt), maar... is dat correct? Is wat in de button staat 'labelend' voor waar die input number voor wordt ingezet? Wat willen we eigenlijk vertellen in dat label... (misschien is een `aria-label` dan beter, met "Aantal", of "Aantal ... wat?")

**Comment by gofix** [comment]
NB: ook in het CSS component in storybook willen we deze change zien natuurlijk: https://css.dso-toolkit.nl/master/?path=/story/input-number--input-number

**Comment by gofix** [comment]
Testen kan op:
https://dso-toolkit.nl/_1386-input-number-label-in-list-button/components/detail/group-input-number.html
https://dso-toolkit.nl/_1386-input-number-label-in-list-button/components/detail/input-number.html
https://dso-toolkit.nl/_1386-input-number-label-in-list-button/components/detail/list-button.html
https://css.dso-toolkit.nl/_1386-input-number-label-in-list-button/?path=/story/input-number--input-number&args=label:
