### ISSUE TITLE
Flex-spacer

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#139]
Vanuit developers is er een verzoek om een flex-spacer standaard in te toolkit te hebben als class om te helpen bij het uitlijnen van componenten. Om het gebruik van div's te beperken

Het voorstel is om dit als volgt aan te pakken. 

.flex-spacer {
flex: 1 1 auto;
}

Een voorbeeld. 

 <md-toolbar color="primary">
  <span><img src="/assets/images/logo.png" height=30 width=41></span>
  <a md-button routerLink="/home" routerLinkActive="active"><span class="fa fa-home fa-lg"></span> Home</a>
  <a md-button routerLink="/about" routerLinkActive="active"><span class="fa fa-info fa-lg"></span> About</a>
  <a md-button routerLink="/menu" routerLinkActive="active"><span class="fa fa-list fa-lg"></span> Menu</a>
  <a md-button routerLink="/contactus" routerLinkActive="active"><span class="fa fa-address-card fa-lg"></span> Contact</a>
  **<span class="flex-spacer"></span>**
  <a md-button (click)="openLoginForm()"><span class="fa fa-sign-in fa-lg"></span> Login</a>
</md-toolbar>

In dit voorbeeld zou de login altijd aan de rechterkant bevinden, door de span + class .

**Comment by VolleMelk** [comment]
Dit zal niet mogelijk zijn. De Toolkit moet IE9 compatible zijn, die de caniuse.com tabel voor `flex`:

![image](https://user-images.githubusercontent.com/9696261/40625374-54104dd6-62b2-11e8-924a-5c9a5c2a7eae.png)

Verder ontmoedig ik het gebruik van dit soort 'wildcard' elementen: Dit is een symptoon dat de toolkit niet gehandhaafd wordt en door truuks en hacks alsnog het visueel gewenste effect geeft. De bijlage werkt niet, maar het lijkt erop dat dit het menu is waar Login altijd rechts moet uitlijnen? Dit moet de implementator niet oplossen, maar als change inschieten bij de toolkit. Zodra deze change merged is en er een release is uitgekomen, zal _overal_ Login rechts uitlijnen.

Als we op deze manier gaan werken is er geen eenheid meer. Ik begrijp dat de ontwikkelaars verder willen, wij ook: Maar verzoeken plaatsen voor dit soort modifier classes brengt ons alleen maar verder van het doel.
