### ISSUE TITLE
Realiseren opzet voorbeeldpagina’s in Storybook

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#1394]
**Aanleiding**
Fractal wordt uitgefaseerd. Nieuwe componenten worden aangemaakt in Storybook en steeds meer bestaande componenten worden overgezet. Hierdoor verdwijnen ze uit Fractal, en de daarin gemaakte patronen en voorbeeldpagina's. Deze voorbeelden zijn erg waardevol, omdat ze componenten in context plaatsen en we daardoor ongewenst gedrag eerder kunnen spotten. Ook levert het gevalideerde markup voorschrift veel tijdswinst op voor de implementatie teams.

**Werkzaamheden**
De componenten leven in twee verschillende Storybooks; CSS en Core (Web Componenten). Om voorbeeldpagina's te kunnen realiseren zullen deze samengebracht moeten worden.
...

**Testen**
ntb

**Acceptatiecriteria**
ntb

**Comment by MichielDHVD** [comment]
Er wordt door @bramhoosemans  een side ticket aangemaakt om het te overzetten van CSS packages. 

Dit Ticket wordt opgepakt wanneer de visie rondom documentatie website afgerond is.
