### ISSUE TITLE
Datepicker bugs: Backspace leegt veld, en min max story in storybook is incorrect

### ISSUE THREAD

**Issue by WidoBurg** [dso-toolkit/dso-toolkit#1395]
1. https://www.dso-toolkit.nl/33.0.0/components/preview/date-picker.html
2. Ga naar het 'Default' veld
2. Vul een datum in, bijv 11-12-2021
3. Het jaartal wil je wijzigen dus backspace

**Verwacht gedrag:**
Invoer wordt 11-12-202

**Actueel gedrag:**
Invoer wordt volledig geschoond. Je moet opnieuw beginnen. 

Aanvullende opmerkingen:
- Bij stap 3 invoer via DatePicker treed het gedrag ook op
- In 31.0.0 werkt dit nog wel. https://www.dso-toolkit.nl/31.0.0/components/preview/date-picker.html

**Comment by gofix** [comment]
Ziet er goed uit @benheldoorn, fijn ook die automatische test.
https://dso-toolkit.nl/_1395-Datepicker-backspace-bugfix/components/detail/date-picker.html
https://core.dso-toolkit.nl/_1395-Datepicker-backspace-bugfix/?path=/story/date-picker--default

Zelfs als de value vanuit de initiatie niet compleet zou zijn, wordt deze nu gewoon doorgezet. Het leeghalen van het veld bij onaf ingevulde values treedt niet meer op.
![image](https://user-images.githubusercontent.com/2689559/151124782-f7d0a1dc-1084-4386-bbeb-80c8541678af.png)

Validatie maakt op geen enkele manier deel uit van het component? Ik kan 30-02-2000 invoeren, en dan:
![image](https://user-images.githubusercontent.com/2689559/151124891-0c9a7bcc-5a88-44c6-8678-a4d070da6ea0.png)

**Comment by gofix** [comment]
Wat ook nog opvalt (maar, net als volgens mij mijn andere bevinding over geen validatie, ook buiten scope van dit issue), is dat het scenario met een min en een max een wat verwonderlijke ervaring oplevert:
![image](https://user-images.githubusercontent.com/2689559/151126519-005ad7e4-00e9-455a-ab02-0693696aa073.png)

**Comment by benheldoorn** [comment]
Klopt, validatie is geen onderdeel van het component, in zo verre, on change worden er event ge-emit over het wel/niet geldig zijn van de waarde.

**Comment by benheldoorn** [comment]
Dat min en max, dat is een typo in de storubook templating:
![image](https://user-images.githubusercontent.com/41840996/151129048-6a2ac55c-7569-4195-ac82-37d28df5d206.png)
Dat zullen we meteen even meepakken.

**Comment by gofix** [comment]
(helaas, build faalt vanwege een test: `1) should padStart days and months with 0`)

**Comment by benheldoorn** [comment]
What? Alleen maar op de min max fix? Ongeloofelijk.

**Comment by gofix** [comment]
Geinig, percy laat ook zien wat het effect van onze changes zijn:
![image](https://user-images.githubusercontent.com/2689559/151163104-c7c0c870-59f0-4246-b989-5184b7145bee.png)
