### ISSUE TITLE
Voorbeeldpagina: Vergunningcheck Conclusie

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#1396]
**Aanleiding**
Voor de conclusie van de Vergunningcheck is een nieuw ontwerp gemaakt dat gebruik maakt van het Accordion component.

**Werkzaamheden**
In deze story gaan we de gewenste content opnemen binnen de Accordion 'conclusion'. Deze verwerken in een voorbeeldpagina met conclusie Vergunningcheck.

Content:
- Unordered list (ook genest) met activiteiten.
- Info component met voorbehouden en toelichting bij activiteiten.
- Paragraaf met class "text-muted" met uitleg waarom er contact opgenomen dient te worden. 

Aandachtspunten:
- Marges aanpassen aan context > bijvoorbeeld bij opeenvolgende info-componenten binnen conclusion accordion.

**Ontwerp**
![voorbeeldpagina-conclusie](https://user-images.githubusercontent.com/598735/149473325-456d4e04-7bc9-482b-9c20-f89eeac465e3.png)
![114_specificaties-content](https://user-images.githubusercontent.com/598735/149473345-5c3d8b39-ead7-4936-b8c0-467f3bf36993.png)

**Comment by gofix** [comment]
@MichielDHVD 
![image](https://user-images.githubusercontent.com/2689559/151832214-a697a49c-d07a-4d1c-9759-a068781f0a58.png)
Punt or geen punt (aan het eind van zo'n statement), that's the question.

**Comment by gofix** [comment]
Verder, als ik de HTML door de W3 validator haal, heeft die nog best veel bevindingen.
![image](https://user-images.githubusercontent.com/2689559/151834925-1d1842e0-363c-45a2-8da7-900696f37935.png)
Ik ben toch de markup een beetje aan het nalopen, dus zal deze bevindingen wel even fixen.

**Comment by gofix** [comment]
Dit scherm kan vast bekeken worden. @bramhoosemans en @MichielDHVD pakken jullie dat samen op:
https://dso-toolkit.nl/_1405-Voorbeeld-paginas-bouwen/components/preview/resultaat.html

**Comment by bramhoosemans** [comment]
> Punt or geen punt (aan het eind van zo'n statement), that's the question.

Overal een punt aan het einde van de zin.

**Comment by bramhoosemans** [comment]
@gofix ik had mijn comments al in https://github.com/dso-toolkit/dso-toolkit/issues/1405 gezet:

Vragen:
- Moet het resultaat wel in een <form> gezet worden?
- Waarom staat er een div 'rich content' om de accordions? Die haalt ook nog eens margin van de bovenste h3 af.
- In de huidige toepassing staat de hr en disclaimer tekst buiten het <form> en niet in rich content. Hierdoor krijgen de form buttons wél 32px margin-bottom ipv 16px.

Gewenste CSS wijzigingen toolkit:
- Binnen de accordion lijsten <ul> padding-inline-start op 24px.
- Binnen de accordion Info component 8px margin boven- en onder.
- Padding bottom op de dso-section-body mag 16px worden ipv 24px.

**Comment by gofix** [comment]
Wat zullen we doen @bramhoosemans @MichielDHVD

**Comment by bramhoosemans** [comment]
- Laat de `<form>` maar staan. Zeker als het layout technisch geen verschil maakt én is consistent met de stappen voor de conclusie.
- Als je de `dso-rich-content` div met hr en disclaimer buiten het formulier plaatst krijg je 32px marge onder de buttons (`.dso-form-buttons:last-child`). Zie ook de schermafbeelding.
- Mijn vraag is of we de gewenste CSS wijzigingen nog in dit issue oppakken (ging ik eerder wel vanuit) of een vervolg aanmaken in de volgende release?

CSS wijzigingen:
- Binnen de accordion lijsten `<ul>` padding-inline-start op 24px.
- Binnen de accordion Info component 8px margin boven- en onder.
- Padding bottom op de dso-section-body mag 16px worden ipv 24px.


![Schermafbeelding 2022-02-02 om 08 48 33](https://user-images.githubusercontent.com/598735/152114319-a04d4502-7319-4f0f-ad4d-6d0aad3b0f89.png)

**Comment by gofix** [comment]
Zoals ook besproken met @MichielDHVD: we verplaatsen die hr en de disclaimer naar buiten het form. Verdere (styling) improvements worden losse issues.
