### ISSUE TITLE
Typography

### ISSUE THREAD

**Issue by VolleMelk** [dso-toolkit/dso-toolkit#14]
<img width="538" alt="screen shot 2018-02-01 at 10 09 08" src="https://user-images.githubusercontent.com/9696261/36110782-2f4ae820-1024-11e8-9fb3-5a017ee94259.png">

**Comment by Poofy83** [comment]
Dit wordt lastig:

De CSS voor een element wordt gegenereerd. Als de bron andere CSS genereert, moet dat (handmatig) bijgewerkt worden in het overzicht. Deze wijziging kan uit een Bootstrap update komen, of uit een user story.
Daarbij komt nog dat styling voor elementen uit verschillende selectors komt, en dan nog eens in verschillende contexten: een h1 in een header heeft andere styling dan een "gewone" h1.
In je voorbeeld staan een aantal properties en 'etc..'. De enige die 'etc...' weet, is de browser. Los van bovenstaand probleem, is het niet makkelijk om voor een vooraf gedefinieerde lijst properties de waarden op te halen.
De styling van de component library (de tool, Fractal) is niet gelijk aan die van de DSO Toolkit. Ik heb wel wat dingen gelijkgetrokken (voornamelijk de fonts), maar bij lange na niet alles: Het is niet mogelijk om 1 op 1 de styling van de toolkit in te hangen, de bootstrap CSS conflicteert met de Fractal markup. Alle documentatiepagina's zijn 'fractal' pagina's, maar de componenten pagina's zijn iFrames waar alleen de DSO styling actief is.
Wat dacht je van het volgende: Ik maak een componenten pagina (dus in een iFrame, alleen DSO styling) waar de h1, h2, h3, p, ol, ul, a en table in getoond worden. Hier staat geen styling naast, maar de gebruiker kan wel makkelijk en overzichtelijk de verschillende elementen inspecteren met de browser inspector. Dit lost niet het "context"-probleem op, maar wel de andere 3 problemen.

/Original commenter: Thomas


Thomas RijsewijkIk snap nu beter wat de moeilijkheid hiervan is.

Helemaal prima om een componentenpagina voor : h1, h2, h3, p, a te maken, zodat het met een inspector bekeken kan worden. 
ol, ul en table hebben al hun eigen pagina's.

Wat dacht je van het volgende:
De css, die nodig is voor het component in de iframe, wordt tevens ook onder het kopje Notes gegenereerd als tekst voor h1, h2, h3, p en a.
Voorzie je hier complicaties bij?

/Original commenter: Michael


Het maken van een extra tab is geen probleem, het ophalen van de gegenereerde CSS is een probleem. Een element wordt door meerdere CSS selectors gestyled. We hebben hier twee opties in:

- De gegenereerde CSS scannen en alle selectors tonen. We kunnen hier nog verder in gaan door ook de specifity van een selector mee te nemen en de styling die niet zwaar genoeg is achterwege laten
- Elk component in een headless browser inladen, en vervolgens de computedCss van opvragen. Dit is een complex proces. Tevens moet er dan ergens gespecificeerd worden welke elementen in het CSS tabje moeten komen.

Een alternatief zou een scriptende variant zijn. Niet tijdens buildtime maar tijdens run-time, in de browser. Nadeel hier weer van is dat je met computedCss werkt, en dat gebruikers op verschillende platforms en/of verschillende browsers andere informatie kunnen krijgen. Dit is met een inspector ook, maar het uitlezen van de gegenereerde CSS geeft tenminste dezelfde resultaten.

Al met al hebben we het hier over serieus werk, complex proces met schimmige routines. Ik kan je niet garanderen dat dit blijft werken. Nog belangrijker: Ik kan je niet garanderen dat het tabje ook daadwerkelijk "gelijk" heeft: Alleen de browser heeft gelijk.

De veiligste (en toevallig snelste) is de inspector van je browser gebruiken.

/Original commenter: Thomas
