### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by VolleMelk** [dso-toolkit/dso-toolkit#140]
Tijdens het ontwikkelen van componenten mis ik soms de mogelijkheid om te sparren met UI/UX designers, product owner of de developers die de componenten gaan gebruiken.

Wat vinden jullie ervan om een tool als Slack te gaan gebruiken? Openbaar, iedereen mag meelezen/meepraten

@MichielDHVD @DjangoBlok @Anto1nette (en anderen)

**Comment by DjangoBlok** [comment]
Ik begrijp de behoefte. Kan die communicatie niet in deze Github? Lijkt me juist praktisch om het op een plek te hebben.
Of gaat het dan meer over het voortraject?

**Comment by MichielDHVD** [comment]
Wat is het doel? Het gaat om sparren, gaat het om snelheid of vooral contact met partijen die nu niet op github zitten. 

Of is het de mogelijkheid om een iets uitgebreidere dialoog te houden over bepaalde onderdelen?

**Comment by VolleMelk** [comment]
GitHub moet nog steeds de waarheid blijven. Maar soms lopen we tegen problemen of vraagstukken aan waar je met een gesprek verder komt. Uit een gesprek of chat komt een conclusie, deze conclusie moet dan verwerkt worden in de betreffende GH issues. Vaak is het voortraject van een conclusie alleen maar ruis. Overwegingen en argumenten kunnen/moeten nog steeds in het GH issue verwerkt worden.

Misschien zit er ook wel een informelere kant aan: GitHub wil je formeel, helder en zakelijk houden. Een gesprek/chat is informeler en vrijer

**Comment by MichielDHVD** [comment]
Ik snap het idee. Ik vind het zelf prima. Maar ik ben niet de enigste op de github natuurlijk. Ik weet niet hoe andere hier tegen aan kijken. Plus of ze er gebruik van zouden maken.

**Comment by DjangoBlok** [comment]
Wat mij betreft geen probleem, ik ben benieuwd of het lukt die mensen die niet op Github zitten wel aan te haken op een andere tool. Maar dat zien we wel...
Wellicht in ieder geval ook goed als communicatiekanaal voor UX?

**Comment by VolleMelk** [comment]
Ik heb 'n Slack channel gemaakt http://dso-toolkit.slack.com. Je kan via https://join.slack.com/t/dso-toolkit/shared_invite/enQtMzc3ODE2Njk5MjM2LTZmMmY4MTYyMTMzMTg5NTE5NGUxNTUxOWVlNDQ4ODk1NTAwZmY3NDQ1NjQ1MTMwM2IyZDIzNTVmZDk4N2IyNzQ een uitnodiging krijgen.

Tot chat's ;-)
