### ISSUE TITLE
Web Component Header

### ISSUE THREAD

**Issue by gofix** [dso-toolkit/dso-toolkit#1404]

**Comment by daverhelst** [comment]
@MichielDHVD is er al zicht op de subtitel .svg's ?

**Comment by MichielDHVD** [comment]
Morgen op zijn vroegst. Maak het even een prio @daverhelst

**Comment by daverhelst** [comment]
De locatie van de uitklapper is volgens de ontwerpen altijd onder de lijn van de header, maar de uitklapper zelf zit in het dropdown component. Vanwege verschillende onderdelen die aan en uit gezet kunnen worden, wil de hoogte van de header nog wel eens verschillen.

Het lijkt me dat we deze hoogte met een stukje scripting moeten gaan uitlezen, zodat de uitklapper altijd op de gewenste plek komt te staan.

**Comment by MichielDHVD** [comment]
[Svg-logos.zip](https://github.com/dso-toolkit/dso-toolkit/files/8002861/Svg-logos.zip)

Svg logo's voor de kleine header variant. 

Toekomstige varianten zijn meegenomen ook al zullen die niet in eerste instantie geimplementeerd worden.

**Comment by gofix** [comment]
Opmerkingen van @MichielDHVD in https://github.com/dso-toolkit/dso-toolkit/issues/1422 zijn verwerkt. The work is done. Wellicht komen er bij implementatie van de werkvorm nog vragen naar boven, of optimalisaties, maar die pakken we dan in eigen nieuwe issues op.

NB: zo hadden we misschien best wat aan de Description van de diverse eigenschappen kunnen doen, in https://core.dso-toolkit.nl/_1404-Web-Component-Header/?path=/docs/header--header, maar we denken dat eigenlijk de controls in de story een en ander al goed duidelijk maken. En bij vragen weet men ons toch wel te vinden!
