### ISSUE TITLE
Voorbeeldpagina's bouwen binnen fractal verzamel issue

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#1405]
@MichielDHVD Gaat de volgende voorbeeldpagina's bouwen

- Voorbeeldpagina conclusie vergunningcheck https://github.com/dso-toolkit/dso-toolkit/issues/1396
- ~~Voorbeeldpagina RTR Pagina~~
- Voorbeeldpagina stelselcatalogus https://github.com/dso-toolkit/dso-toolkit/issues/1407

**Comment by MichielDHVD** [comment]
Openstaande issues omtrent voorbeeldpagina's 

Vergunningcheck:
- Icons renderen niet online, local wel. 

RTR pagina:
- Check opbouw pagina
-  DSO-treeview, basis van component wordt ingeladen maar er wordt geen inhoud meegeleverd. 

Wanneer render functie fractal te gebruiken. Als er een combinatie van componenten is dan kan render al niet meer gebruikt worden.

**Comment by MichielDHVD** [comment]
Story scope wordt aangepast. Het is niet mogelijk de DSO-treeview op een simpele manier in fractal te verwerken. 
Een voorbeeld pagina in storybook is hiervoor echt essentieel. 

Dus:

Vergunningcheck resultaat (nieuw) 
Stelselcatalogus - begrip 

Wordeno opgeleverd.

**Comment by bramhoosemans** [comment]
Vragen:
- Moet het resultaat wel in een <form> gezet worden?
- Waarom staat er een div 'rich content' om de accordions? Die haalt ook nog eens margin van de bovenste h3 af.
- In de huidige toepassing staat de hr en disclaimer tekst buiten het <form> en niet in rich content. Hierdoor krijgen de form buttons wél 32px margin-bottom ipv 16px.

Gewenste CSS wijzigingen toolkit:
- Binnen de accordion lijsten <ul> padding-inline-start op 24px.
- Binnen de accordion Info component 8px margin boven- en onder.
- Padding bottom op de dso-section-body mag 16px worden ipv 24px.

**Comment by gofix** [comment]
Zoals ook besproken met @MichielDHVD: we verplaatsen die hr en de disclaimer naar buiten het form. Verdere (styling) improvements worden losse issues.
