### ISSUE TITLE
Map Controls weet niet dat een kaartlaag niet beschikbaar is (disabled checkbox)

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#1406]
**Aanleiding**
Review van de module @dso-toolkit/react-leaflet ter voorbereiding op de implementatie bracht aan het licht dat we een specificatie over het hoofd hebben gezien. De gewenste kaartlagen zijn niet op ieder zoom niveau beschikbaar en moeten dan ook niet geselecteerd kunnen worden (disabled state). 

**Achtergrond:**
uit de module @dso-toolkit/react-leaflet bieden we twee React componenten "MapControls" en "Overlay" aan
in de module @dso-toolkit/leaflet sluiten we deze functionaliteit aan op de Leaflet kaart en het Web Component
uit de module @dso-toolkit/core bieden we 'n presentatie component <map-controls /> aan die leunt op <dso-map-overlay />
<dso-map-overlay /> zet het HTML CSS component "checkbox" uit formulier aan

**Werkzaamheden**
De "Overlay" dient de "MapControls" te laten weten of de kaartlaag beschikbaar is, zodat deze enabled of disabled kan worden.

**Ontwerp**
![116_locatie-adres--kaartlaag-niet-beschikbaar](https://user-images.githubusercontent.com/598735/150507635-0fcfac49-5732-4a45-9769-179dc1dab211.png)

**Comment by bramhoosemans** [comment]
Tooltip bij een disabled state wordt een aparte taak

**Comment by tfrijsewijk** [comment]
In dit issue zijn de changes gerealiseerd in het `<dso-map-controls>` Web Component.
