### ISSUE TITLE
Voorbeeldpagina: Stelselcatalogus Begrip

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#1407]
Aanleiding
Er is een nieuw ontwerp voor de pagina Begrip op basis van componenten uit de DSO toolkit.

Werkzaamheden
Voorbeeldpagina maken

Ontwerp
![image](https://user-images.githubusercontent.com/36912722/150746601-5bad1c2f-50e2-4013-a545-aeec8404a316.png)

Testen
Acceptatiecriteria

**Comment by LiesbethVorst** [comment]
@MichielDHVD De pagina ziet er netjes uit. In het design zit wel meer marge onder de <dl>, namelijk 32px (ipv 16). Ik denk dat de extra marges nodig zijn om de pagina goed scanbaar te houden.

**Comment by gofix** [comment]
Inmiddels is ook https://dso-toolkit.nl/_1405-Voorbeeld-paginas-bouwen/components/detail/begrippen.html testklaar. @MichielDHVD en @LiesbethVorst kijken jullie ernaar?
Voornaamste openstaande vragen zijn:
- welke tekstjes moeten waarnaartoe linken
- welke links zijn 'extern'
- welke links moeten een vriendelijk label hebben

... en, zo mogelijk zou het plezierig zijn echte links ook echte links te laten zijn, hoewel dat voor de demonstratiewaarde van de pagina natuurlijk niet strikt noodzakelijk is

**Comment by MichielDHVD** [comment]
Het linken naar echte pagina's lijk mij eerlijk gezegd niet wenselijk. Dead links mogelijkheden etc. 

Welke links extern en vriendelijk label moeten hebben kan ik geen duidelijkheid over geven. 

Voor de definition list bottom margin ga ik wel een losse issue opvoeren.

**Comment by gofix** [comment]
Zoals besproken @MichielDHVD maken we nu alle hrefs even naar '#' en pakken we eventuele andere changes - zowel inhoudelijk als improvements in styling - later in losse issues wel op.
