### ISSUE TITLE
Map Control - buttons in op de Leaflet Map

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#1412]
**Aanleiding**
Tijdens implementatie van de Leaflet map controls liepen we tegen een aantal issues aan. Met name de styling van de knop 'Teken een gebied op de kaart' bleek lastig te realiseren.

Door toepassing van de class '.dso-leaflet-button' lijkt de styling inmiddels goed te gaan. Alleen lopen we nu tegen de volgende afwijkingen aan:

- De nieuwe knop krijgt via .leaflet-top etc. een margin van 10px, maar de Kaartlagen-knop staat op 16px van de rand.
- Toetsenbord bediening werkt niet goed. Als je met tab langs de controls gaat, wordt visueel heel even aangegeven dat de knop focus krijgt, maar dat verdwijnt bijna direct. Kaartlagen en de zoom-buttons kan je op die manier wel bedienen.

Originele GitHub issue https://github.com/dso-toolkit/dso-toolkit/issues/1021

**Werkzaamheden**

- Button 'Teken een gebied op de kaart' dient dezelfde marges (16px) ten opzichte van de rand te krijgen als 'Kaartlagen' en zoom controls.
- De button moet ook met het toetsenbord te bedienen zijn. Inclusief focus styling.
- Draggen en zoomen (dubbelklik) werkt niet in de bounding box om "Kaarlagen" en de zoomknoppen. Zie bijgevoegde video

**Ontwerp**
![119_map-buttons](https://user-images.githubusercontent.com/598735/153563830-42fa030a-7ac2-4038-aa3c-276cfc12117a.png)

**Comment by tfrijsewijk** [comment]
De positionering van de Leaflet Controls is een simpele wijziging. In `dso-leaflet.css` (de enige juiste Leaflet CSS stylesheet voor gebruik van Leaflet applicatie binnen het programma) staan deze idd op `10px`. Als ik dit aanpas naar `$u2` ziet het er meteen goed uit.

Maar voor toetsenbord gebruik speelt er meer. De focusstyling wordt door Leaflet verborgen. Het lijkt erop alsof dit ook niet configureerbaar is. De gedachte erachter is dat je bij drag 'n drop geen focusstyling ziet. Er is een routine die de focus styling ook weer toont als er een knop is ingedrukt: bv SHIFT, ALT, of zelfs DELETE: zolang het maar 'n modifier key is.

Dit gedrag is ook van toepassing op de demo leaflet op https://leafletjs.com/. Druk maar eens 'n paar keer op TAB totdat je focus hebt op een element in de Leaflet en houd dan SHIFT ingedrukt.

De elementen van de DSO Map Controls hebben hier geen last van, vanwege Shadow DOM: De Leaflet styling/routines zijn niet actief op deze elementen omdat Leaflet deze elementen niet kan vinden.

Dan is er nog een ander probleem: de focus. De DSO Leaflet adapter heb ik de eigenschappen van 'n Leaflet Control laten erven (oa. positionering en event bubbling), maar staat in z'n geheel na de Leaflet controls:

![image](https://user-images.githubusercontent.com/9696261/152820242-4c3fd259-8ce3-409b-8c01-bf23a06ee165.png)

Ik dacht even een oplossing met 

```
.dso-leaflet-button:focus-visible {
    outline: auto !important;
}
```

Maar zo makkelijk is dat dus niet:

![image](https://user-images.githubusercontent.com/9696261/152821345-60dff780-ec54-4b96-9ccc-cfc677952c4c.png)

Hoe verder? Ik kan in ieder geval de positionerings fix doorvoeren, dat is geen werk.

* Gaan we tegen Leaflet inwerken door de focus styling weer naar voren te halen?
* Gaan we iets aan de focus volgorde doen?

**Comment by tfrijsewijk** [comment]
cc: @gofix, @bramhoosemans

**Comment by gofix** [comment]
> Dan is er nog een ander probleem: de focus.

Daar zul je 'volgorde' bedoelen. Ik zou 'voor nu' willen voorstellen daar niks aan te doen. 

Mbt. de focus styling: ik denk dat we misschien in de hele Leaflet werkvorm dan maar 'zelf' focus styling moeten toepassen. 
Maar omdat we 'm dan dus zelf maken, en niet aan de browser default styling overlaten, zullen er verschillen zijn tussen onderdelen die we zelf stijlen, en onderdelen die de browser nog wel stijlt. Om dat zo min mogelijk storend te laten zijn, zou ik er wel naar willen streven focus styling op alle onderdelen binnen de kaart dan maar zelf te doen (zowel in light als shadow DOM).

**Comment by bramhoosemans** [comment]
Custom focus styling toevoegen (gelijk aan hover state). Focus volgorde gaat in de toepassing goed. Wordt nu niet meegenomen.

**Comment by tfrijsewijk** [comment]
Custom focus styling toegevoegd aan `.dso-leaflet-button` en de buttons die in `<dso-map-controls />` zitten.

@PieterVerheij kan jij de knoppen in `div#controls` opnieuw positioneren ZONDER de `div#controls` ?

![image](https://user-images.githubusercontent.com/9696261/153654348-3dd9256b-42e7-4b65-9608-c3a446d24016.png)

Dit element zorgt ervoor dat je op die plek geen drag of zoom actie kan starten. Dit element wordt in `/packages/core/src/components/map-controls/map-controls.tsx` gemaakt, styling staat in `/packages/core/src/components/map-controls/map-controls.scss`.
