### ISSUE TITLE
Autosuggest: onSelect met enter toets

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#1415]
**Probleembeschrijving**
Er word nu twee keer gezocht als de gebruiker met het toetsenbord een suggestie kiest. 1x goed, exacte zoekopdracht, en daarna 1x normale zoekopdracht (fout). Dit komt omdat we op 2 events moeten luisteren. 1 voor het afvangen van als de gebruiker een optie selecteert (auto-suggest) en 1 als de gebruiker enter toets gebruikt om te zoeken.

In dit geval gebeurd het dus beide, want de gebruiker kiest een optie met enter toets. We willen dan gedrag wat hoort bij onSelect, dus exacte zoekopdracht. Maar omdat we ook moeten luisteren op onKeyDown(enter) op het input veld gaan we ook normaal zoeken.

Als je een optie met de muisklik selecteerd gaat het wel goed, want dat krijgen we dat laatste onKeyDown(enter) event niet.
Met andere woorden, we willen onderscheid in het enter event wanneer met een optie selecteert en het enter event in het zoekveld om gewoon te zoeken, niet beide tegelijk.

**Oplossingsrichting**
het autosuggest component ook een onSearch event emitter geven zodat het onderscheid duidelijk word. Zo hoeft het afnemende component ook niet meer zelf te luisteren naar een key event. Het autosuggest component laat dus weten via de onSelect wanneer de gebruiker een suggestie heeft gekozen (click of enter key) of wanneer deze gewoon wilt zoeken met de huidige input value (enter key).

**Comment by gofix** [comment]
Kan getest worden, op https://core.dso-toolkit.nl/_1415-Autosuggest-onSearch/?path=/story/autosuggest--example

**Comment by benheldoorn** [comment]
Het is ook niet de bedoeling om beide te gebruiken. Afhankelijk van wat je wil kies je de een of de ander. Dus in een zoeken op enter implementatie gebruik je dsoSearch, wil je alleen iets doen als er echt iets gekozen wordt, dan gebruik je dsoSelect.

**Comment by rblanconeira** [comment]
Dan is dit component niet bruikbaar voor ons. Wij moeten kunnen afvangen en gedrag koppelen aan die twee verschillende gebruikersacties. Zo is het ontwerp van de week wel besproken met Ad en Thomas.

**Comment by gofix** [comment]
We kunnen nog alle kanten uit. Ik dacht dat @benheldoorn hier letterlijk geïmplementeerd heeft wat gewenst is. Maar misschien is er behoefte aan een wat uitgebreidere `details` eigenschap die je meekrijgt. Nu bevat die alleen de waarde, maar als we er een object van maken met daarbij ook de 'afzender' (de input resp. de suggesties) kom je er misschien wel mee uit de voeten, @rblanconeira ? Daarmee bereiken we hetgeen in de specs al letterlijk genoemd is:
>  onderscheid in het enter event wanneer met een optie selecteert en het enter event in het zoekveld om gewoon te zoeken

**Comment by rblanconeira** [comment]
Misschien snap ik dan niet helemaal wat er gebouwd is. Maar mijn verwachting is dat ik als afnemer van het component een onSelect event krijg als de gebruiker een suggestie heeft gekozen uit de lijst (met muis of enter key) en een onSearch krijg als de gebruiker gewoon de enter key gebruikt in het input field zonder een suggestie te kiezen.
Nu lijkt het alsof we in situatie 1 beide events krijgen. Dat was eerst ook al zo en dat willen we dus niet omdat we deze scenarios anders moeten behandelen

**Comment by gofix** [comment]
Dus: eigenlijk wil je simpelweg geen dsoSearch als je een selectie uit de suggesties maakt (ongeacht of je dat met muis of enter doet). Dan geeft uiteindelijk dus alleen een enter in de zoekbox een dsoSearch, en een enter in de suggesties gaat _alleen_ een dsoSelect emitten.

**Comment by rblanconeira** [comment]
@gofix correct
