### ISSUE TITLE
Accordion bevindingen en verbeteringen

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#1419]
**Aanleiding**
Uitbreiding Accordion component tbv conclusie Vergunningcheck #1280

**Werkzaamheden**

Gevonden issues:
- Uitlijning van pijltjes, iconen en addons altijd bovenaan.
- Nested compact en conclusie styling komt niet door.
- Bij een icon addon heeft het icoon geen marge met de tekst en komt er tegenaan te staan.
- Als de alignment wordt omgedraaid heeft het pijltje (before) niet voldoende marge en loopt door de tekst heen.
- In de #1280 hebben we het Accordion component uitgebreid met de wens om ALLE iconen toe te kunnen passen. Hiervoor zal ook een toegankelijk alternatief (oftewel beschrijving) aan gekoppeld moeten worden.

Optimalisaties:
- Binnen de accordion lijsten `<ul>` padding-inline-start op 24px.
- Binnen de accordion Info component 8px margin boven- en onder.
- Padding bottom op de dso-section-body mag 16px worden ipv 24px.

**Ontwerp**
![Schermafbeelding 2021-12-23 om 08 54 57](https://user-images.githubusercontent.com/598735/152490905-7078eba1-4b85-43ce-bacc-c46e1fb7432c.png)
![Schermafbeelding 2021-12-23 om 08 56 34](https://user-images.githubusercontent.com/598735/152490907-0bd99662-e08f-4f30-933a-ee9cc00aaf88.png)
![Schermafbeelding 2021-12-23 om 08 58 01](https://user-images.githubusercontent.com/598735/152490911-c5606fc4-5ee6-4891-927e-e6e76bf96e76.png)
![Schermafbeelding 2021-12-23 om 09 03 52](https://user-images.githubusercontent.com/598735/152490914-bb744803-9762-4aa5-9a45-ce5ac7c584b9.png)
![Schermafbeelding 2021-12-23 om 09 06 50](https://user-images.githubusercontent.com/598735/152490916-1394f872-b78a-4fff-ac3f-34cf0caea051.png)
![114_specificaties-content](https://user-images.githubusercontent.com/598735/152490926-23658204-5c11-42cf-91eb-dec8c91edab6.png)

**Comment by daverhelst** [comment]
Voor het punt omtrent de info components in de accordion. Besproken met @gofix:

Dit wordt opgelost dmv deze contextuele stijling onder te brengen in `lists.scss`, op een later moment zal deze stijling verhuizen naar een HTML/CSS Component constructie (#1397)

**Comment by gofix** [comment]
@bramhoosemans please check:

Accordion - default
https://css.dso-toolkit.nl/_1419.Accordion-bevindingen-en-verbeteringen/?path=/story/accordion--default

Accordion - nested
https://css.dso-toolkit.nl/_1419.Accordion-bevindingen-en-verbeteringen/?path=/story/accordion--nested

Accordion - multiselectable
https://css.dso-toolkit.nl/_1419.Accordion-bevindingen-en-verbeteringen/?path=/story/accordion--multiselectable

Accordion - addons
https://css.dso-toolkit.nl/_1419.Accordion-bevindingen-en-verbeteringen/?path=/story/accordion--addons

Accordion - alignment
https://css.dso-toolkit.nl/_1419.Accordion-bevindingen-en-verbeteringen/?path=/story/accordion--alignment

**Comment by tfrijsewijk** [comment]
@bramhoosemans:

>Binnen de accordion lijsten `<ul>` padding-inline-start op 24px.

https://dso-toolkit.nl/34.1.0/components/detail/rich-content.html Hier staan ook lijsten, maar die springen nog diep in. Ik stel voor:
* Binnen Accordion lijsten padding-inline-start: 24px verplaatsen naar Rich Content
* Binnen Accordion gebruik te maken van Rich Content.

De huidige demo laat een mengelmoes zien:

![image](https://user-images.githubusercontent.com/9696261/158990274-6c618a60-d559-4bbb-b207-c765569fd3ed.png)

En laten we wel wezen, voor dit soort typografische specificaties is het Rich Content component gemaakt. Wat denk jij?

**Comment by bramhoosemans** [comment]
@tfrijsewijk Lijkt mij helemaal goed.

Toen wij de conclusie in accordion realiseerden heb ik deze vraag ook met @daverhelst besproken. Waarom er wél een Rich Content om een lijst met paragraaf staat en niet om een lijst alleen. Toen heb ik aan het team doorgegeven om alles binnen de 'dso-section-body' in een div 'dso-rich-content' te zetten.
