### ISSUE TITLE
Styling Webcomponent Header. 

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#1422]
Issue waar alle styling omtrent header issue wordt uitgevoerd 

Aanleiding
Header is nog niet responsive en ziet er op verschillende viewports nog slordig uit. Ook is er een variant nodig voor de viewer, waar een kleinere versie van de header moet komen. Zodat de kaart applicatie beter tot zijn recht komt. 

Werkzaamheden
Wat moet er concreet aan development stappen gezet worden omdat het issue te realiseren. 

Herindeling menu items opzet (Mijn Omgevingsloket rechts uitlijnen) 
Dropdown menu mogelijkheid in menu introduceren
Kleine variant header voor viewer realiseren, met optie om huidige item naast/onder logo te tonen (gebaseerd op mobile menu) 
Ontwerp
Afbeelding ontwerp (Alle ontwerpen staan in de bijlagen kan ze niet hier toevoegen krijg heel de tijd foutmeldingen? ) 

 
[Header afbeeldingen.zip](https://github.com/dso-toolkit/dso-toolkit/files/8003045/Header.afbeeldingen.zip)

 

 

Testen
Welke test stappen moeten uitgevoerd worden om te controleren of het component correct is gebouwd

Acceptatiecriteria
Controle/ Approval door Reporter/schrijver van Story
WCAG Approved (in afstemming met Tim in't Veld
Technische keuze consistentie Toolkit bewaakt door Info Projects .

**Comment by daverhelst** [comment]
@MichielDHVD Zoals zojuist besproken;
- de sublogo svg's zijn niet helemaal lekker uit de verf gekomen, ze zijn dunner dan de bedoeling is

Afgesproken is dat jij deze dezelfde hoogte in totaal meegeeft, viewbox sizing, als die van de main logo. Dan is de uitlijning hopelijk tot op de pixel goed. Daarnaast ging je nog de tekst omzetten naar outlines, zodat het een grafisch element wordt ipv een SVG met daadwerkelijke tekst (zoals ze nu zijn)

**Comment by MichielDHVD** [comment]
[Logo's Outline.zip](https://github.com/dso-toolkit/dso-toolkit/files/8038918/Logo.s.Outline.zip)

Logo's update

**Comment by gofix** [comment]
Styling is nu conform specs en/of nadere afspraken. Alles is verwerkt in https://github.com/dso-toolkit/dso-toolkit/issues/1404

Eventuele verdere verbeteringen, op welk vlak dan ook, pakken we op in vervolgtickets.
