### ISSUE TITLE
Map Controls bevat een form zonder submit

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#1426]
**Aanleiding**
Melding in HTML Codesniffer dat 'dso-map-controls' een form bevat zonder submit.

**Werkzaamheden**
Submit toevoegen zonder visuele of functionele wijzigingen (auto submit bij selectie?)

**Comment by tfrijsewijk** [comment]
Er spelen een aantal dingen:

* Dit issue verwijst naar een Storybook pagina. Hier wordt de functionaliteit van `<dso-map-controls>`, `<dso-map-base-layers>` en `<dso-map-overlays>` getoond. Dit is geen productie markup, maar demo markup.
* Er is nu één implementatie (`@dso-toolkit/leaflet`) die deze 3 componenten heeft aangesloten. Hier wordt (ongeveer) dezelfde (verkeerde) markup gegereerd.

Stel nou dat we het `<form />` element van een submit button voorzien, wat submitten we dan en wie gaat naar dat event luisteren? Het zijn de losse elementen die telkens een verschillende actie hebben.

Dan hebben we nog het Shadow DOM:

![image](https://user-images.githubusercontent.com/9696261/154733431-61d286da-bc3c-4905-bb84-702aa5864afe.png)

Als we al echt iets gaan submitten, gaat het om de `value`s van elementen die wel 2 shadow roots diep zitten.

Ik stel voor om het `<form>` element te verwijderen. @timveld Hoe denk jij hierover?

Simpel gezegd gesproken zitten er geen herkenbare input elementen in dit `<form>`: voor zover scripting en screenreaders weten is het een leeg formulier. De elementen zijn natuurlijk wel te vinden en benaderen, maar niet in de context van een `form`ulier. Daarnaast heeft dit formulier geen "verzend"-gedrag, daar het direct de kaart bestuurt.

Ik denk dat het `<form>` element hier niet terecht is. We kunnen het misschien vervangen door een `<fieldset>`, maar daar twijfel ik aan.

**Comment by tfrijsewijk** [comment]
ping: @timveld

**Comment by tfrijsewijk** [comment]
@Anto1nette @bramhoosemans: Wat ga ik met dit issue doen? Sluiten? Indien hier nog werk verricht moet worden: dat gaat voor woensdag niet meer lukken.

**Comment by timveld** [comment]
Als het niets submit, is het sowieso geen form. Dus inderdaad weghalen. 
Ik zie binnen het form een fieldset met legend kaartlagen. Als ik het goed begrijp, komen daarin een soort checkboxes waarmee je kaartlagen zichtbaar of onzichtbaar kunt maken. 
In dat geval is de fieldset terecht: deze groepeert bij elkaar horende checkboxes.

**Comment by tfrijsewijk** [comment]
`<form>` is weg.
