### ISSUE TITLE
Voorbeeldpagina conclusie Vergunningcheck aanpassen 'Opslaan in Mijn Omgevingswet'

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#1430]
**Werkzaamheden**
In de voorbeeldpagina conclusie Vergunningcheck twee keer 'dso-form-buttons' opnemen.
https://www.dso-toolkit.nl/master/components/detail/resultaat.html

![Schermafbeelding 2022-02-16 om 14 35 56](https://user-images.githubusercontent.com/598735/154492608-cf055639-296f-4fd2-890c-3bf4fae9d892.png)

**Comment by MichielDHVD** [comment]
Testable op: https://dso-toolkit.nl/_1430-Voorbeeld-Conclusie-Opslaan-in-Mijn-Omgevingsloket/components/detail/resultaat.html

**Comment by gofix** [comment]
Ziet er goed uit, precies zoals gevraagd.
