### ISSUE TITLE
Thema tile variant in viewer panel

### ISSUE THREAD

**Issue by Anto1nette** [dso-toolkit/dso-toolkit#1443]
### Werkzaamheden
- Thema iconen aparte componenten in een grid
- Iconen flow is van links naar rechts
- Aantal iconen op een regel afhankelijk van de maat van het panel waar ze in zitten
- Hoogte van alle tegels afhankelijk van de hoogste die voorkomt in de set.

Gewenst gedrag en ontwerp in attachments uitgewerkt voor verschillende paneelbreedtes.

![layout-1440 Viewer Panel L Max](https://user-images.githubusercontent.com/1033595/156022234-7a9ce3c1-3095-405d-9411-f9aaaa75defa.png)

![layout-1440 Viewer Panel L](https://user-images.githubusercontent.com/1033595/156022243-0210378d-5205-4ecc-8fc9-8a61f5115f82.png)

![layout-1440 Viewer Panel M](https://user-images.githubusercontent.com/1033595/156022246-f1c50d85-a24c-440a-91fa-cb3352759bbd.png)

![layout-1440 Viewer Panel S](https://user-images.githubusercontent.com/1033595/156022248-a1fd47e0-585a-4591-b883-49ec891b49fe.png)

**Comment by DjangoBlok** [comment]
@PieterVerheij 
https://www.sketch.com/s/bbe6bee4-eb50-401c-b482-897f44878507/p/B72D7020-0C51-4086-B45E-062245842F1C/canvas
Kun je hier zo bij?

**Comment by PieterVerheij** [comment]
@DjangoBlok 
Hi! Ik kan er bij, maar ik mis de specs van de afmetingen van de cirkels, het icon en de achtergrondkleuren en borderkleuren?

**Comment by MichielDHVD** [comment]
https://www.sketch.com/s/bbe6bee4-eb50-401c-b482-897f44878507/a/ZOoxAwx#Inspector 

Met deze moet het wel lukken.

**Comment by PieterVerheij** [comment]
![image](https://user-images.githubusercontent.com/25430835/158147060-1dc64b37-c9f3-4cff-a1f0-1fe23b513a93.png)
 Murphy's law ;-)

**Comment by PieterVerheij** [comment]
@DjangoBlok @MichielDHVD Ik krijg nog steeds een foutmelding op die pagina, ook als ik opnieuw vanaf het overzichtsscherm er naartoe navigeer. Kunnen jullie niet een zipje met de Measure export maken, dat is toch wat handiger in dit geval. 

https://utom.design/measure.html

**Comment by PieterVerheij** [comment]
@DjangoBlok zijn de thema's links of buttons? Als in: gebeurt er iets op de kaart als je erop klikt?

**Comment by DjangoBlok** [comment]
Is dit wat je bedoelt?
[DSOT-320 Thema Tiles.zip](https://github.com/dso-toolkit/dso-toolkit/files/8245826/DSOT-320.Thema.Tiles.zip)

**Comment by gofix** [comment]
Om deze variant te etaleren denken we dat we de story "Viewer Grid" moeten splitsen naar 2 stories:
- default (dat wat er nu al in zit, zie https://core.dso-toolkit.nl/34.1.0/?path=/story/viewer-grid--viewer-grid)
- themes (deze nieuwe vulling)

En, straks met #1445 komt daar dan wellicht de derde story bij "filters".

@DjangoBlok ?

**Comment by gofix** [comment]
Een alternatieve aanvliegroute zou nog zijn deze theme-tiles niet per se als story van het viewer grid te etaleren, maar losstaand zoals https://core.dso-toolkit.nl/_1444-Afbeelding-groot-kunnen-weergeven/iframe.html?id=image-overlay--image-overlay&viewMode=story

**Comment by gofix** [comment]
We hebben het hier in de refinement van zojuist uitgebreid over gehad. Zowel voor deze "Theme Tiles" als voor de "Image Overlay" geldt dat we deze als op zich staande hoofdonderdeel in storybook gaan opnemen, en dus niet als 'sub' onder "Viewer Grid". 
Vooralsnog _tonen_ we de werkvormen nog wel in het viewer grid paneel, omdat zodoende goed het samenspel met die omgeving in beeld komt. 
In afwachting van het `<dso-responsive-element />` (of zo) moeten we dat ook wel doen, omdat we moeten reageren op de breedte van een container, niet op die van het scherm.

**Comment by tfrijsewijk** [comment]
>Zowel voor deze "Theme Tiles" als voor de "Image Overlay" geldt dat we deze als op zich staande hoofdonderdeel in storybook gaan opnemen, en dus niet als 'sub' onder "Viewer Grid".

De visie en techniek die nodig is om dit te realiseren is afhankelijk van Storybook documentatie. Maar verder vind ik dit niet zo'n goed idee: Je kiest een _component_ en je ziet vervolgens veel meer, namelijk het Viewer Grid. Ik denk dat dit verwarrend is en niet in lijn met een lijst van componenten.

Je wilt hier een patroon tonen, terwijl ik een component verwacht. Ik ben het ermee eens dat Viewer Grid in 'n grijs gebied zit.

Ik stel voor dat we het component voorlopig alleen onder Viewer Grid als variant tonen: Het component werkt eigenlijk ook alleen binnen het Viewer Grid.

**Comment by tfrijsewijk** [comment]
En dan nog 'n inhoudelijke kanttekening:
* Hebben we nagedacht over deze tile's ten opzichte van de huidige [Tile](https://dso-toolkit.nl/34.1.0/components/detail/tile.html) ?

Technisch zag ik namelijk de volgende opzet voor mij:
* Er komt een nieuw component "Tile Grid";
* In "Tile Grid" wordt er gebruik gemaakt van "Tile"
  1. Tile wordt omgestijld naar het nieuwe ontwerp en ziet er overal zo uit;
  2. Tile krijgt het gevraagde ontwerp alleen in "Tile Grid";
  3. Tile wordt uitgebreid met een modifier;

**Comment by tfrijsewijk** [comment]
@MichielDHVD & @bramhoosemans hebben jullie mijn bovenstaande kanttekening gezien?

**Comment by MichielDHVD** [comment]
Goed dat je even pingt @tfrijsewijk 

Er moet een keuze gemaakt worden uit die 3 opties. 

Hier moeten Django en ik samen even snel op reageren. Wij gebruiken beiden tiles. 
Optie 1 valt af ik wil voorlopig niet overal dezelfde Tile met grijze achtergrond. 

Dan blijven alleen:
- Alleen ontwerp in Tilegrid 
- Of een modifier 


@DjangoBlok Heb jij een voorkeur?

**Comment by bramhoosemans** [comment]
Besproken planning 28-03:

- Nieuw component 'Tile Grid'.

- Tile wordt uitgebreid met een modifier voor de grijze achtergrond.

**Comment by gofix** [comment]
Hier is iets goed mis gegaan: de plaatjes doen het niet.
https://core.dso-toolkit.nl/master/?path=/story/viewer-grid--with-tiles
https://css.dso-toolkit.nl/master/?path=/story/tile--theme

**Comment by tfrijsewijk** [comment]
Had niets met dit issue te maken, is in #1520 opgelost.
