### ISSUE TITLE
Afbeelding groot kunnen weergeven

### ISSUE THREAD

**Issue by Anto1nette** [dso-toolkit/dso-toolkit#1444]
### Werkzaamheden
- Van toepassingen op afbeeldingen die op 100% breedte worden weergegeven in het tekstpaneel van de viewer.
- Deze afbeeldingen voorzien van een knop om de afbeelding groot weer te geven.
- In de grote weergave van de afbeelding wordt de rest van het viewer scherm afgedekt.
- De grote weergave kan weer worden verlaten door een sluiten knop.

### Ontwerp component
https://overflow.io/s/P1KPB5BR

### Interactie
- Bij mouseover of via tab wordt knop getoond om te vergroten
- Zie https://github.com/deoostfrees/Parvus voor toegankelijk voorbeeld
- Na klik wordt afbeelding als modal weergegeven
- Afbeelding wordt gecentreerd in breedte en in hoogte (met marge van 16 pixels). 
- De afbeelding wordt niet groter weergegeven dan 100%
- Rechtsboven in de afbeelding wordt permanent ene knop weergegeven om de dialoog weer te sluiten
- Escape toets sluit de modal
- Naast geopende afbeelding klikken sluit de afbeelding

**Comment by gofix** [comment]
@DjangoBlok we zijn lekker onderweg met deze component, maar er zijn nog wel wat detailvragen. Bijvoorbeeld: we hebben eigenlijk niks gezegd over de `<img src />` die we gaan vergroten. We zijn er nu voor het gemak even vanuit gegaan dat in de `<img />` maar 1 `src` staat, met een eigenlijk dus 'te grote afbeelding', die middels een `width` attribuut op maat wordt geperst. Bij vergroting nemen we dan die plaat en laten we 'm wel, rekening houdend met de randvoorwaarden, in z'n volle glorie zien.

Jammer is natuurlijk dat de bezoeker dan toch ook initieel al die vette plaat zal downloaden. Is nagedacht over het inzetten van `srcset`, zodat de browser voor de kleine weergave een passende resource downloadt? Als `srcset` gebruikt gaat worden, zal in het Web Component vervolgens ook de juiste maat daaruit gepickt moeten worden. Misschien moeten we dat nu buiten scope plaatsen, maar eigenlijk hoor je in een moderne webtoepassing dit wel als zodanig te implementeren.

**Comment by gofix** [comment]
Work so far: https://core.dso-toolkit.nl/_1444-Afbeelding-groot-kunnen-weergeven/?path=/story/image-overlay--image-overlay

**Comment by DjangoBlok** [comment]
@gofix Dat is een logische gedachte. Wij hebben momenteel helaas die afbeelding maar in één grootte. Ik kan niet goed overzien wat er in de keten nodig is om daar een set van te maken.
Vooralsnog zou ik die inderdaad buiten scope plaatsen.

**Comment by gofix** [comment]
Ok helder, geen srcset dus, voorlopig.

We hebben het in de refinement van zojuist nog gehad over hoe en waar we dit component etaleren. Zoals @benheldoorn het nu heeft gedaan is prima, als losstaand onderdeel in Storybook, maar wel gepresenteerd in context van het Viewer Grid paneel (om zodoende goed te laten zien hoe dat in samenspel werkt). Overigens moet het component theoretisch ook wel in andere contexten kunnen functioneren (bv. in het helpcenter (!)), maar dat hoeven we nu nog niet te laten zien.

**Comment by gofix** [comment]
Wat mij betreft werkt dit fantastisch:
https://core.dso-toolkit.nl/_1444-Afbeelding-groot-kunnen-weergeven/iframe.html?id=image-overlay--image-overlay&viewMode=story
Zowel met muis als toetsenbord helder te bedienen (en zoals je zou verwachten, met [ESC] te sluiten waarna je rustig verder kunt tabben door de pagina.

Grafische afwerking volgt spoedig, maar misschien heb jij op voorhand nog wat opmerkingen @DjangoBlok ?

**Comment by DjangoBlok** [comment]
Ja, lijkt inderdaad goed te werken @gofix 
Zou die afbeelding functioneel geen modal moeten zijn?
Ik zie nu nog dat de achtergrond kan door scrollen.

**Comment by benheldoorn** [comment]
Dat scrollen ligt meer aan de Storybook weergave. Als je de `padding: 1rem;` weghaalt van de `body` dan zie je dat de content niet meer scrollt.

**Comment by benheldoorn** [comment]
https://storybook.js.org/docs/react/configure/story-layout
