### ISSUE TITLE
Viewer - filterpaneel

### ISSUE THREAD

**Issue by Anto1nette** [dso-toolkit/dso-toolkit#1445]
### Aanleiding
Vanuit veel schermen in de viewer kan een paneel worden geopend waar gebruikers alle filters/keuzes kunnen inzien en aanpassen. Dit paneel wordt geopend links over het scherm heen waarbij nog een deel van het scherm zichtbaar blijft maar wel uitgegrijsd is.

### Werkzaamheden
n.t.b.

### Ontwerp
- paneel hoogte is gelijk aan hoogte van scherm
- paneel breedte is max: 896px
- paneel breedte is schermbreedte - 40px
- onder 768px is het paneel net zo breed als het scherm
- rechts naast het paneel is de achtergrond uitgegrijsd en disabled
- het paneel kan worden gesloten met knoppen in het paneel, naast het paneel klikken heeft geen effect

![Uw keuzes](https://user-images.githubusercontent.com/1033595/156025067-e0c0157a-0cb0-477f-b8c9-87471c0b860b.png)

**Comment by gofix** [comment]
@tfrijsewijk als we hier mee aan de slag gaan, moet wsl. even gewacht worden op het werk uit https://github.com/dso-toolkit/dso-toolkit/issues/1443, omdat we daar voor het eerst ANDERE vulling van het linkerpaneel in het viewer grid introduceren. Het lijkt het meest voor de hand liggend om dit te etaleren middels verschillende stories van het Viewer Grid, en dat aspect zijn we dus in dat andere issue aan het uitwerken.

**Comment by gofix** [comment]
Voor "Theme Tiles" en "Image Overlay" geldt dat we die als zelfstandige componenten gaan opnemen in Storybook (maar wel tonen in context van een viewer grid paneel).

@DjangoBlok voor dit filterpaneel wel logischer deze als (optioneel) onderdeel voor het viewer grid beschikbaar te stellen, en dus in Storybook daaronder bv. met een 'with Filter Panel' story te etaleren. Of zouden we deze toch ook 'los' opnemen (maar  dan ook net als "Theme Tiles" en "Image Overlay" in context van het viewer grid laten zien).
