### ISSUE TITLE
Disabled buttons with hover styles wrong

### ISSUE THREAD

**Issue by TonD83** [dso-toolkit/dso-toolkit#145]
Ik weet niet of dit al dan niet zo bedoeld is, maar ik vind het vreemd ogen:

een button met classes 'btn btn-primary' en disabled property heeft een hover effect (raar, voor een disabled knop) en vrijwel zwarte (#191919) tekst wat er niet bepaald fraai uitziet.

Is dit allemaal opzet?

btn btn-primary disabled
<img width="273" alt="screen shot 2018-06-28 at 13 39 52" src="https://user-images.githubusercontent.com/18580063/42032123-dc859d5e-7ad8-11e8-83c3-699bce13f8d8.png">

btn btn-primary disabled :hover
<img width="261" alt="screen shot 2018-06-28 at 13 40 04" src="https://user-images.githubusercontent.com/18580063/42032129-de7bef14-7ad8-11e8-8f0d-c7d3ae2907d8.png">

**Comment by MichielDHVD** [comment]
Nee dit is zeker niet de opzet. Hij hoort niet te reageren op een hover en geen zwarte tekst te hebben 

Hoe het eruit hoort te zien
<img width="245" alt="screen shot 2018-07-02 at 09 25 20" src="https://user-images.githubusercontent.com/36912722/42150352-e0d3e8a8-7dd9-11e8-9bab-72a2547f1bc9.png">

Je kan de disabled state hier terug vinden. 
https://dso-toolkit.nl/2.0.0/components/detail/buttons.html

**Comment by TonD83** [comment]
@MichielDHVD Geef de bovenste knop op die pagina maar eens een disabled property en dan zal je hetzelfde zien als wat ik toonde in mijn bug report.

**Comment by VolleMelk** [comment]
@TonD83 We pakken 'm op!

**Comment by tfrijsewijk** [comment]
Deze fix zal in `3.0.0-alpha.1` het licht zien. Tevens de hover states over disabled default en link buttons aangepakt, die hadden een soortgelijke bug

**Comment by MichielDHVD** [comment]
Ik beschouw dit als opgelost en zet hem daar naar Done. Mochten developers er nog last van hebben horen we het vanzelf.
