### ISSUE TITLE
Afmetingen van viewer grid panelen en animaties daartussen

### ISSUE THREAD

**Issue by gofix** [dso-toolkit/dso-toolkit#1451]
In https://github.com/dso-toolkit/dso-toolkit/issues/1403 is het Viewer Grid Web Component gerealiseerd, waarbij de bedoeling was dat de afmetingen van de panelen gelijk zouden blijven aan die van het tot nu toe gangbare CSS component. De 'small' weergave van het linkerpaneel heeft niet de juiste breedte. Ook lopen de animaties tussen de afmetingen niet vloeiend.

**Comment by PieterVerheij** [comment]
Note: de foutieve afmetingen van "small" werd veroorzaakt door het niet wrappen van de definition list. Opgelost in ander issue.

**Comment by gofix** [comment]
It's good.
