### ISSUE TITLE
Card List heeft boven en onder geen border + `chevron-right` lijnt niet met linktekst

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#1452]
Aanleiding
Bij het opzetten van de voorbeeld pagina's Mijn Omgevingsloket #1307 vielen een aantal dingen op. Zo heeft de eerste card geen lijn boven, en de laatste card geen lijn onder. Ook is het pijltje niet in het midden van de link (titel) uitgelijnd.

Werkzaamheden

- De Cards List dient ook helemaal boven en onder een 1px border #ccc te krijgen.
- Cardlist heeft altijd margin-top: -1px (Om te voorkomen dat er een dubbele lijn tegen de navbar staat.) 
- (bugje) Op de voorbeeldpagina is het eerste pijltje een stuk kleiner
- Het pijltje dient in het midden van de link uit te lijnen. Het probleem zit waarschijnlijk in de line height van de heading, zie screenshot.

Ontwerp
![image](https://user-images.githubusercontent.com/36912722/156557629-68c1323d-002f-4cf3-8e10-860701a3ea77.png)

Bugs:
![image](https://user-images.githubusercontent.com/36912722/156557757-9adbb8f0-2131-446c-aa46-31ee74619abd.png)
<img width="239" alt="Screenshot 2022-03-03 at 12 40 31" src="https://user-images.githubusercontent.com/36912722/156557873-c14e9158-5d9b-489f-9ae7-ac9a2a23400a.png">

Testen
ntb

Acceptatiecriteria
ntb

**Comment by gofix** [comment]
@MichielDHVD 
https://dso-toolkit.nl/_1452-Cards-list-heeft-geen-border-helemaal-boven--en-onder-en-pijltje-lijnt-niet-met-de-link/components/detail/card-list.html
https://css.dso-toolkit.nl/_1452-Cards-list-heeft-geen-border-helemaal-boven--en-onder-en-pijltje-lijnt-niet-met-de-link/?path=/story/card-list--card-list

**Comment by MichielDHVD** [comment]
Story is wat mij betreft ok. Ziet er al beter uit. 

Vooral op deze voorbeeldpagina is verschil goed te zien. Plus daar was ook een van de bugs gemeld. 

https://dso-toolkit.nl/_1452-Cards-list-heeft-geen-border-helemaal-boven--en-onder-en-pijltje-lijnt-niet-met-de-link/components/detail/project-overzicht.html
