### ISSUE TITLE
Navigation block - Link list in Highlightbox 

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#1454]
### Aanleiding
Binnen een project in Mijn Omgevingsloket kun je ingediende verzoeken terugvinden, verder werken aan je aanvraag of deelnemers beheren. In de toekomst wordt het ook mogelijk een Vergunningcheck of Maatregelen op maat toe te voegen aan een project. Met zoveel verschillende elementen is het wel handig als er een ‘projectnavigatie’ komt.

De projectnavigatie komt bovenaan in de rechter zijbalk te staan. Zo houden we focus op de content en staat de navigatie op een vaste positie op de pagina’s binnen het project.

### Werkzaamheden
- Link List in highlightbox variant maken. 
- Current state nodig.
- Geen visited state wenselijk.
- Voorbeeldpagina 'Project Overzicht' aanpassen.
- Combinatie Highlightbox, H3 en Navigation block/Link List (zie bijgevoegd screenshot).

### Ontwerp
![image](https://user-images.githubusercontent.com/36912722/156560240-2edee539-7c00-44d3-b4bc-fb8c076a7405.png)
![image](https://user-images.githubusercontent.com/36912722/156560255-4dac2bd0-5b4e-497f-b2ab-03782741ce71.png)
![image](https://user-images.githubusercontent.com/36912722/156560270-e7742cc6-41ad-472f-bad8-5e67e03d2a17.png)
![image](https://user-images.githubusercontent.com/36912722/156560292-75fce8fd-f336-4f54-9739-20482f86f4fe.png)

**Comment by daverhelst** [comment]
Zoals met @gofix doorgesproken:
- in CSS storybook; variant voor Linklist toevoegen, LinkList in Nav
- Stijling voor visited en aria-current="page" (ook) onderbrengen voor deze variant, nav .link-list
- Er bestaat de mogelijkheid om een LinkList in een nav onder te brengen in een HighlightBox

**Comment by gofix** [comment]
@MichielDHVD @bramhoosemans zie:
- https://dso-toolkit.nl/_1454-Navigation-block-linklist-in-nav/components/detail/project-overzicht.html
- https://css.dso-toolkit.nl/_1454-Navigation-block-linklist-in-nav/?path=/story/link-list--in-nav

**Comment by bramhoosemans** [comment]
Ziet er wat mij betreft goed uit!

Enige wat me opviel was de beperkte breedte bij smalle viewports bij https://dso-toolkit.nl/_1454-Navigation-block-linklist-in-nav/components/detail/project-overzicht.html Mogelijk iets met block elementen?

<img width="755" alt="Schermafbeelding 2022-03-17 om 10 08 58" src="https://user-images.githubusercontent.com/598735/158775879-44cf004f-2b8b-4818-8c8a-6b214dd93ce7.png">

**Comment by MichielDHVD** [comment]
Als ik col-xs-12 toevoeg aan navigation blok dan is er niks meer aan de hand. 

Deelnemers is wel volle breedte omdat die een paragraaf heeft die de maxbreedte invult. Navigation blok heeft dat niet. Dus of je moet Col-xs-12 toevoegen aan beiden om op beide viewports volle breedte af te dwingen. 

Weet niet precies wat je voorkeur is qua responsive @bramhoosemans

**Comment by bramhoosemans** [comment]
Responsive ging ik er vanuit dat als componenten boven elkaar worden gestapeld ze de volledige breedte innemen, tenzij anders gedefinieerd. Blijkbaar reageert de Highlightbox anders met een paragraaf dan met een lijst... dat is vreemd toch?

**Comment by daverhelst** [comment]
Ik heb even gekeken en zie dat dit komt door de bootstrap col-verdeling om de `<nav>` heen:
![image](https://user-images.githubusercontent.com/5871330/159289163-0131bceb-3ae6-475d-942b-05234f15c577.png)

Als ik deze waarde bijvoorbeeld zou veranderen in `col-xs-12` dan vult het blok goed uit:
![image](https://user-images.githubusercontent.com/5871330/159289278-48d4ffe8-53d5-4dfe-b9b1-4536a6feb84c.png)

En de gewenste situatie zou volgens mij `col-md-12 col-sm-6 col-xs-12` moeten zijn. Volledig uitgevuld in kolom op grote maten, dan halve vulling op tablet view, en volledige uitvulling op smalle view.

**Comment by bramhoosemans** [comment]
Duss gewenste columns toepassen voor responsive voorspelbaar gedrag op zowel Mijn project als Deelnemers: `col-md-12 col-sm-6 col-xs-12`.
