### ISSUE TITLE
Nieuw component `<dso-responsive-element>`

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#1456]
Aanleiding
Het linkerpaneel van de viewer kan in verschillende breedtes getoond worden. Voor juist responsive gedrag moeten de elementen in het paneel weten hoe breed ze moeten zijn. 

Werkzaamheden
Hiervoor is een extra component (een wrapper) nodig.

Ontwerp
nvt

Testen
ntb

Acceptatiecriteria
ntb

**Comment by tfrijsewijk** [comment]
Merged met 05d12993b3f982cc3d22ea3887a3a078c671d80b
