### ISSUE TITLE
Form Fields Optioneel - Verplicht omdraaien

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#146]
pr12 heeft iets raars gevonden tijdens het implementeren van de toolkit. 

Bij elk niet verplicht veld wordt optioneel neergezet. Waardoor er een raar beeld onstaat. 

![image](https://user-images.githubusercontent.com/36912722/42034801-7492c90c-7ae1-11e8-8bb0-d5d8a8375ca4.png)

De vorm die ontbreek is een required field plus indicator. De WCAG geeft ook aan dat als een field required is dat hier altijd een asterisk of een woord verplicht/required achter moet staan. Deze staat nog niet in de toolkit. 

We willen eigenlijk de vorm omgedraaid zien. Bij elk verplicht veld staat er een indicator achter en bij optioneel niets. 

Hiervoor ga ik een herontwerp aanleveren, de verplichte velden. Ook gaat het woord achter de formfield nog een andere kleur krijgen deze is namelijk te licht. (Hier waren we al bewust van)

**Comment by VolleMelk** [comment]
Alles wat je omschrijft is _by design_ en volgens de wens van een paar maanden geleden. Uiteraard geen probleem als anders moet worden.

Zoals ik de impact van de nieuwe wens nu inschat, hoeven de implementatoren niets te doen (mits de voorgeschreven markup is gehanteerd).

Wij wachten het ontwerp af

**Comment by MichielDHVD** [comment]
![verpicht veld uitgetyped](https://user-images.githubusercontent.com/36912722/43307703-4eb52112-917f-11e8-9ea9-3bbdd48e0ca8.png)

Verplichte velden moeten volgens de WCAG succescriteria 3.2.2 altijd een indicatie hebben. Dit hanteert de digitale toegankelijkheid ook.  

Dus optioneel en verplicht moeten worden omgedraaid. 

De kleur van optioneel wordt #666 dit haalt de contrast waarde volgens de WCAG. 

Ik heb ook contact opgenomen met Logius, deze overzien de digitale toegankelijkheid binnen de overheid, over dit onderwerp. Voor de zekerheid.

**Comment by tfrijsewijk** [comment]
Het 4e veld van het ontwerp ("Voor hoeveel personen is het bouwwerk bestemd?") heeft een lichtere kleur border-color. Aangezien deze change en kleur nergens gespecificeerd staat heb ik het alleen de verplicht/optioneel omgedraaid.

Voorheen was "optioneel" bewust met kleine letters. Het ontwerp geeft "Verplicht" met een hoofdletter. Is dit bewust?

**Comment by tfrijsewijk** [comment]
Komt uit in `3.0.0-alpha.1`

**Comment by MichielDHVD** [comment]
Nu ik Verplicht met hoofdletter zie is dat net wat te intens. Een kleine letter v is beter. Als dat is aangepast kan deze naar Done gezet worden.

**Comment by tfrijsewijk** [comment]
Testable, oa: https://www.dso-toolkit.nl/3.0.0-alpha.2/components/detail/form--form-horizontal.html

**Comment by MichielDHVD** [comment]
Verplaatst naar done en kan gesloten worden.
