### ISSUE TITLE
`.input-group` verwijderen

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#1462]
Tijdens de weekly refinement gaf ik aan dat de volgende werkvorm een `group-input` zou zijn:

![image](https://user-images.githubusercontent.com/9696261/156649842-f8468482-172e-4094-8df0-05630292162a.png)

Maar dat is helemaal niet waar. Dit is een input-group:

![image](https://user-images.githubusercontent.com/9696261/156650039-147be46d-83d0-43b8-939d-2d6ec362afbc.png)

Dit is een native Bootstrap component, wat wij nergens documenteren.

**Comment by gofix** [comment]
@tfrijsewijk hoe zat dit nu? Het ticket luidt "verwijderen of verhuizen" -> wat wordt het nu?

**Comment by tfrijsewijk** [comment]
Verwijderen als de teams het niet meer gebruiken, anders verhuizen. Ik dacht dat de UXers dit zouden navragen in hun teams.

**Comment by bramhoosemans** [comment]
Binnen PR12G hebben we geen gebruik van `.input-group` gevonden.
