### ISSUE TITLE
Modal verhuizen naar `@dso-toolkit/css`.

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#1463]
Het Modal component verhuizen naar `@dso-toolkit/css` en documenteren.

**Comment by daverhelst** [comment]
Er staan een aantal varianten van het `Dialog` component in de code, maar deze worden nergens in Fractal getoond. De vraag is, welke willen we wel gaan tonen in de CSS storybook omgeving?

- Aparte varianten voor de verschillende button modi? (Deze zijn nu ingesteld als stuurbaar via de controls, maar hebben geen eigen 'losse' story
- Een `max-height` variant, waarbij de inhoud van de modal erg lang is, en er een scrollbar moet verschijnen op de `dso-body` in de modal

@bramhoosemans @MichielDHVD kunnen jullie bepalen welke varianten we zichtbaar willen hebben in de CSS Storybook?

Daarnaast zijn we nog aan het kijken hoe Storybook in te richten is omtrent de dimmer en aanpassingen voor de `dso-modal` dmv van classes op `<body>`

**Comment by MichielDHVD** [comment]
Dat kunnen we @bramhoosemans heeft recentelijk een voorstel gedaan voor 3 soorten modals die we willen vastleggen. 

![image](https://user-images.githubusercontent.com/36912722/166677626-d5f140f5-e3be-4052-92a8-492ebc37dc2e.png)

Bevestigingsdialogen 
Passieve dialogen
En Actieve dialogen 

In de afbeelding zelf zit de specifieke toelichting van elke vorm.
