### ISSUE TITLE
Modal - Animatie

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#147]
Vraagje 

Pr12 heeft voor het component modal een eigen Animatie gemaakt. Maar die valt nu weg door de toolkit. 

De vraag is, heeft de Modal een animatie als deze verschijnt? Misschien is er een kleine fade. Als deze er is, was deze te subtiel om te waarnemen voor ons.

**Comment by tfrijsewijk** [comment]
Er is geen animatie, maar kan zeker gemaakt worden. Ik denk dat we het beste een plan van aanpak kunnen bespreken in slack

**Comment by PieterVerheij** [comment]
Voorstel: we kunnen van de modal verticaal animeren (dus een beweging over de Y-as)

`transition: margin-top .4s ease-in-out;`

**Comment by PieterVerheij** [comment]
@MichielDHVD Kan jij iets met bovenstaande suggesties?

**Comment by MichielDHVD** [comment]
Het is waarschijnlijk niet mogelijk om dit visueel te zien ergens. Mijn voorkeur heeft sowieso de fade in, het inschuiven kan nogal onrustig overkomen. Fades zijn in het algemeen een stuk rustiger.

**Comment by PieterVerheij** [comment]
@MichielDHVD @tfrijsewijk We zullen de modal fade als WIP uitbrengen in de volgende release, dan krijgen jullie een beeld.

**Comment by tfrijsewijk** [comment]
Note to self: Vergeet CHANGELOG niet als dit wordt geaccepteerd

**Comment by tfrijsewijk** [comment]
Uitgekomen ni `3.1.0-alpha.1`: https://www.dso-toolkit.nl/3.1.0-alpha.1/components/detail/modal--modal.html

Alle modals hebben nu een fade-in die je ziet als de pagina wordt geopend. Zodra deze modal scriptend wordt gemaakt zal je 'm ook zien

**Comment by MichielDHVD** [comment]
Prima, ik zet deze naar done!
