### ISSUE TITLE
Vertical margin lijsten en Definition List optimalisatie

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#1472]
**Aanleiding**
Optimalisatie uit https://github.com/dso-toolkit/dso-toolkit/issues/1419 heeft ongewenst effect.

**Werkzaamheden**

- Voorbeeld van `dl` met `dt` en meerdere `dd`'s toevoegen aan Definition List component
- De marge tussen opvolgende `dd`'s gelijktrekken aan `dd > ul`
- Lijsten binnen een Definition List géén `padding-inline-start` geven maar verplaatsen naar `.dso-rich-content`

![Schermafbeelding 2022-03-07 om 10 13 16](https://user-images.githubusercontent.com/598735/157200410-4e226e5f-c62f-4cab-9879-468345b4ef08.png)

**Comment by PieterVerheij** [comment]
@bramhoosemans @gofix 
Ik zie hier eigenlijk twee zaken door elkaar heen lopen en vraag mij af of dit wel binnen de scope van de toolkit moet worden opgelost. Er zit namelijk "eigen" styling (`.permit-application`) op die `<ul>` (in oranje). Die haalt de bullet weg en poogt de padding op 0 te zetten.
De toolkit styling gaat er echter vanuit dat er wel een bullet is (!) en zet de padding links (op een andere manier) op 24px:

![image](https://user-images.githubusercontent.com/25430835/158558662-1991666d-acd4-476c-a4bb-5e2c50e0b7d2.png)

Alhoewel wij eigen styling natuurlijk nooit moeten propageren, heb ik van een man in een regenjas gehoord dat als in de eigen styling de `padding-left: 0;` wordt aangepast in `padding-inline-start: 0;`, het zou moeten werken.

**Comment by bramhoosemans** [comment]
@PieterVerheij Aha! Excuses, ik wist niet dat er custom styling werd toegepast.

Is het dan opgelost als `class="dso-columns-list"` op de `ul` wordt toegepast? Of zal de wijziging naar `padding-inline-start: 0;` tóch in de toolkit moeten worden gemaakt?

<img width="1443" alt="Schermafbeelding 2022-03-16 om 10 41 52" src="https://user-images.githubusercontent.com/598735/158562189-dacf43c4-4106-4784-aa13-1dc1ce296afd.png">

**Comment by PieterVerheij** [comment]
@bramhoosemans `class="dso-columns-list" ` zet de lijst ook gelijk op 3 kolommen, is dat hier wel de bedoeling?
De padding op 0 zetten heeft alleen zin als de bullets ook verdwijnen: dat lijkt mij niet de bedoeling.

Wat ik mij afvraag: waarom wordt er hier ueberhaupt een list ingezet als er maar 1 item is en de bullet weggestijld wordt?

**Comment by bramhoosemans** [comment]
> @bramhoosemans `class="dso-columns-list" ` zet de lijst ook gelijk op 3 kolommen, is dat hier wel de bedoeling? De padding op 0 zetten heeft alleen zin als de bullets ook verdwijnen: dat lijkt mij niet de bedoeling.

Nee, we willen geen kolommen. De bullets moeten wel verdwijnen, en de padding mag naar 0.

> Wat ik mij afvraag: waarom wordt er hier ueberhaupt een list ingezet als er maar 1 item is en de bullet weggestijld wordt?

In het voorbeeld van dit issue kunnen er één of meerdere activiteiten in het verzoek zitten. Waarschijnlijk wordt de dynamische content altijd in een lijst gerenderd.

**Comment by bramhoosemans** [comment]
Ik vraag me even af waarom we bij lijsten in de 'definition list' alléén de bullets en marge weghalen als ze in meerdere kolommen staan.

Zouden we dat niet breder moeten trekken. En vervolgens kan de custom styling in de eigen applicatie weg.

**Comment by PieterVerheij** [comment]
`class="dso-columns-list"` zet de lijst ook gelijk op 3 kolommen en verwijderd de bullets en padding, ongeacht of deze in een accordion of een definition list zit. Waarom? Dat was ooit de wens.

De vraag is hier: willen we wel dat ALTIJD de bullets van een list in een definition list verdwijnen? Of moeten we hiervoor een aparte class introduceren? Mij lijkt het het meest logische om dat laatste te doen, anders leg je iets was wat je in een ander geval misschien helemaal niet wilt?

**Comment by bramhoosemans** [comment]
Goed punt. Een aparte class lijkt mij ook het meest logisch én dan kan de custom styling weg.

Ik schuif de bevinding een release op, zodat we dit morgen in refinement kunnen bespreken met alle teams.

**Comment by PieterVerheij** [comment]
@bramhoosemans @tfrijsewijk 
We hebben er nog een keer naar gekeken en eigenlijk komen we op twee oplossingsrichtingen:
- toch het gebruik van de class `dso-columns-list`: bij een enkele term toont het dan zoals gewenst, alleen is de vraag de verdeling in meerdere column wel gewenst is bij meerdere termen
- geen gebruik van een `ul`: als er maar een enkele term is, is dit niet nodig. Bij meerdere termen kan je je afvragen of het wel correct is om de bullets weg te stijlen: het zijn niettemin indicatoren voor het feit dat er meerdere termen zijn.

En dan eigenlijk een heel wezenlijke vraag: is het gebruik van een defenition list hier wel correct? Het lijkt eigenlijk veel eerder tabulaire data te zijn?

**Comment by bramhoosemans** [comment]
- Nee, verdeling in meerdere columns is **in dit geval niet wenselijk** bij meerdere items.
- We hebben eerder in https://github.com/dso-toolkit/dso-toolkit/issues/1378 bepaald meerdere items in een `ul` te plaatsen. En bullets ook wegstijlen.

Ik zie dit niet als tabular data, want één kolom/rij maakt nog geen tabel. In een definition list kan een 'term' meerdere 'definities' hebben. En dan is de vraag of we deze in een `ul` zetten of gewoon als meerdere opvolgende `dd`?

**Comment by tfrijsewijk** [comment]
>Ik zie dit niet als tabular data, want één kolom/rij maakt nog geen tabel.

Ik zie twee kolommen met meerdere rijen.

>We hebben eerder in https://github.com/dso-toolkit/dso-toolkit/issues/1378 bepaald meerdere items in een ul te plaatsen. En bullets ook wegstijlen. 

Ik begrijp niet wat je hier stelt: kan je dit verder toelichten?

>In een definition list kan een 'term' meerdere 'definities' hebben. En dan is de vraag of we deze in een ul zetten of gewoon als meerdere opvolgende dd?

Ik vroeg mij af in hoeverre het redelijk is te stellen dat bijvoorbeeld "Indienen bij" of "Doel" een term is waar een definitie bij hoort. Maar aan de andere kant , MDN geeft aan dat een Definition List handig is voor het tonen van meta data: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl#metadata

>En dan is de vraag of we deze in een `ul` zetten of gewoon als meerdere opvolgende `dd`?

Tsja.. Dat is aan jou. We hebben een aantal componenten die je kun kan gebruiken. Waarom zou je geen meerder `dd`'s gebruiken?

**Comment by tfrijsewijk** [comment]
> > > Ik zie dit niet als tabular data, want één kolom/rij maakt nog geen tabel.
> > 
> > 
> > Ik zie twee kolommen met meerdere rijen.
> 
> En wat zouden de headers van de kolommen moeten zijn?

Niet: Kolommen krijgen geen header, maar de rijen krijgen headers. Met `<th scope="row">` kun je tabellen met 'n "verticale header" maken: https://www.w3.org/TR/WCAG20-TECHS/H63

De cellen in de linkerkolom worden de headers voor rest van de rij:

```html
<table>
  <tbody>
    <tr>
      <th scope="row">A</th>
      <td>b</td>
    </tr>
    <tr>
      <th scope="row">C</th>
      <td>d</td>
    </tr>
  </tbody>
</table>
```

> Zijn er naast een haakje voor meerdere kolommen andere redenen te bedenken dat we een `ul` zouden moeten gebruiken?

Niet voor zover ik weet. Als je wegkomt met 'n `dl` met `dt` en meerdere `dd`'s, zou ik daarvoor gaan. Nu ziet dat er visueel anders uit dan een `dd` met `ul`, maar wat mij betreft is het te rechtvaardigen om die ruimte tussen opvolgende `dd`'s gelijk te trekken aan `dd ul`.

**Comment by bramhoosemans** [comment]
> Niet: Kolommen krijgen geen header, maar de rijen krijgen headers. Met `<th scope="row">` kun je tabellen met 'n "verticale header" maken: https://www.w3.org/TR/WCAG20-TECHS/H63

Dat kan natuurlijk ook inderdaad, maar dan nóg zie ik niet in dat dit tabulaire data is en geen definition list.
<img width="428" alt="Schermafbeelding 2022-03-28 om 09 37 02" src="https://user-images.githubusercontent.com/598735/160349638-b9f421a9-f868-49bc-b49d-f0a60b0f5978.png">

>  > Zijn er naast een haakje voor meerdere kolommen andere redenen te bedenken dat we een `ul` zouden moeten gebruiken?
> 
> Niet voor zover ik weet. Als je wegkomt met 'n `dl` met `dt` en meerdere `dd`'s, zou ik daarvoor gaan. Nu ziet dat er visueel anders uit dan een `dd` met `ul`, maar wat mij betreft is het te rechtvaardigen om die ruimte tussen opvolgende `dd`'s gelijk te trekken aan `dd ul`.

Dit lijkt me de gewenste oplossing.

Het enige wat we wellicht nog moeten afwegen is het verschil tussen een lijst items in `dd` in één kolom (opvolgende `dd`'s) vs meerdere kolommen (`ul` binnen één `dd`). Dat komt mij niet heel consistent over..

**Comment by tfrijsewijk** [comment]
> > Niet: Kolommen krijgen geen header, maar de rijen krijgen headers. Met `<th scope="row">` kun je tabellen met 'n "verticale header" maken: https://www.w3.org/TR/WCAG20-TECHS/H63
> 
> Dat kan natuurlijk ook inderdaad, maar dan nóg zie ik niet in dat dit tabulaire data is en geen definition list. <img alt="Schermafbeelding 2022-03-28 om 09 37 02" width="428" src="https://user-images.githubusercontent.com/598735/160349638-b9f421a9-f868-49bc-b49d-f0a60b0f5978.png">

Ik zou de tabel bij twee kolommen houden met in de `td` een `ul`. En dan vind ik het er best wel als tabulaire data uitzien.. Sites als MDN gebruiken het voor soortgelijke situaties: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table

> > Niet voor zover ik weet. Als je wegkomt met 'n `dl` met `dt` en meerdere `dd`'s, zou ik daarvoor gaan. Nu ziet dat er visueel anders uit dan een `dd` met `ul`, maar wat mij betreft is het te rechtvaardigen om die ruimte tussen opvolgende `dd`'s gelijk te trekken aan `dd ul`.
> 
> Dit lijkt me de gewenste oplossing.

Dus wat wordt de scope van dit issue dan? Volgens mij moeten we mijn opmerking in https://github.com/dso-toolkit/dso-toolkit/issues/1419#issuecomment-1072299705 hier namelijk ook bij betrekken.

> Het enige wat we wellicht nog moeten afwegen is het verschil tussen een lijst items in `dd` in één kolom (opvolgende `dd`'s) vs meerdere kolommen (`ul` binnen één `dd`). Dat komt mij niet heel consistent over..

Heb je het vanuit een UX- of code oogpunt? De `ul` in `dd` is nodig om de definities over meerdere kolommen te tonen. Tim heeft zijn fiat hierop afgegeven dat het sematisch geen verschil zou uitmaken.

**Comment by bramhoosemans** [comment]
Een tabel met twee kolommen en in de `td` een `ul` is mogelijk. Of het wenselijk is om alle Definition Lists om te zetten naar Tables, omdat één `dt` meerdere `dd`'s kan bevatten, weet ik niet. Semantisch gezien zou ik ervoor kiezen een Definition List te blijven gebruiken (met meerdere `dd`'s) voor presentatie van metadata/een lijst met termen en definities.

> Volgens mij moeten we mijn opmerking in #1419 (comment) hier namelijk ook bij betrekken.

Wat bedoel je precies? "Binnen Accordion lijsten padding-inline-start: 24px verplaatsen naar Rich Content"

> De ul in dd is nodig om de definities over meerdere kolommen te tonen.

Prima, lekker laten staan 👍 

Samenvattend; in de scope van dit issue:

- Voorbeeld van `dl` met `dt` en meerdere `dd`'s toevoegen aan Definition List component

- De marge tussen opvolgende `dd`'s gelijktrekken aan `dd > ul`

**Comment by PieterVerheij** [comment]
Voor:
![image](https://user-images.githubusercontent.com/25430835/160429648-164db6be-3a54-44c0-889f-c7a61b67a556.png)

Na:
![image](https://user-images.githubusercontent.com/25430835/160429733-a4dece32-156c-422f-9eb2-5af88888f7bf.png)

**Comment by DjangoBlok** [comment]
Ik vind het zelfs een verbetering @PieterVerheij

**Comment by bramhoosemans** [comment]
> Maar dit is een ook neveneffect. Zie bij kopje "Euismod" Je kunt je afvragen of dat hier een probleem is:

Dit lijkt me geen neveneffect; als we de marge tussen `dd`'s weghalen gebeurd dat overal natuurlijk. Als opmaak binnen een `dd` gewenst is kan er nog steeds gebruik worden gemaakt van paragrafen of lijsten :-)
