### ISSUE TITLE
Panel verhuizen naar `@dso-toolkit/css`

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#1476]
**Waar**
https://dso-toolkit.nl/master/components/detail/panel.html

**Aanleiding**
PR12 maakt gebruik van een panel implementatie voor accordions ivm oude bootstrap https://react-bootstrap-v3.netlify.app/components/panel/#panels-accordion. Daarom wél CSS verhuizen naar @dso-toolkit/css.

**Werkzaamheden**
Het Panel component verhuizen naar @dso-toolkit/css en documenteren.

**Comment by daverhelst** [comment]
Zojuist besproken; in de `css` package komt een folder `legacy/components` met daarin `panel.scss`. In deze file worden alle zoals nu bestaande panel gerelateerde stijling gezet.
