### ISSUE TITLE
Kaartlagen in MapControls is niet scrollbaar

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#1478]
**Aanleiding**
Toolkit release 34.0.0 > https://github.com/dso-toolkit/dso-toolkit/issues/1432
Kaartlagen is niet scrollbaar. Waardoor andere kaartlagen of toelichtingen buiten beeld vallen en niet kunnen worden genaderd.

**Werkzaamheden**
Kaartlagen (panel) in MapControls scrollbaar maken, zodat er inhoud altijd benaderbaar is.

**Comment by gofix** [comment]
Ziet er goed uit. @bramhoosemans kijk op https://core.dso-toolkit.nl/_1478-Kaartlagen-in-MapControls-is-niet-scrollbaar/?path=/story/map-controls--map-controls

![image](https://user-images.githubusercontent.com/2689559/158546696-4cde096b-1eb1-48f3-a151-24dd4783f290.png)

**Comment by gofix** [comment]
Het sluit icoon van de info lijkt te zijn gekrompen? Die mag altijd 24px blijven.
