### ISSUE TITLE
Font-awesome classnames fix FA v5

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#148]
Bij font awesome lijken niet alle icoontje te werken. 

Als je bijvoorbeeld het apple icoontje probeert te plaatsen krijg je een vierkantje te zien. Zie het midden.

<img width="137" alt="screen shot 2018-07-05 at 14 49 51" src="https://user-images.githubusercontent.com/36912722/42324187-b32cfe68-8062-11e8-900e-ba1aea21c79c.png">

 Maar als ik bijvoorbeeld een iets meer standaard icoontje pak zoals een pijltje naar beneden. Dan wordt deze wel gewoon weergeven 

<img width="60" alt="screen shot 2018-07-05 at 14 51 07" src="https://user-images.githubusercontent.com/36912722/42324232-e1e6b4f6-8062-11e8-886f-de2673d6af8b.png">
  
We kunnen niet achterhalen waar het hier aan ligt. Is het een versioning problem. Op dit moment is het teveel trial en error voor developers om te kunnen kijken welk icoontje wel en niet kan. 
Waar wel al opgelet is dat er alleen icoontjes worden gebruikt die onder het kopje _free_ vallen. 

Ik zag dat in de upgrade naar font awesome dit font awesome 5.06 was. Maar ik voor die specifieke versie geen cheatsheet vinden met beschikbare icoontjes. 

De vraag is of dit een bug is of dat er simpelweg de verkeerde icoontjes gebruikt worden. Als de verkeerde icoontjes gebruikt worden moeten we wel een soort handleiding of overzichtje leveren waar de geschikte icoontjes staan.

**Comment by MichielDHVD** [comment]
Na snel wat dieper te zoeken heb ik het mogelijk antwoord al zelf gevonden. 

Ten eerste is hier de pagina om de icoontjes te selecteren voor Fontawesome versie. 5.0.6 

https://fontawesome.com/v5.0.6/icons?d=gallery&m=free

Ten tweede zijn er twee manieren hoe je een icoontje kan aanroepen. 

nu staat in de toolkit de volgende html markup  : 

<span class="fa fa-road" aria-hidden="true"></span>

Alleen er is een verandering met v5 van font awesome meegekomen namelijk

**Comment by tfrijsewijk** [comment]
Fix beschikbaar vanaf `3.0.0-alpha.1`. Ik heb de classnames omgeschreven naar FA5 voorschriften

**Comment by MichielDHVD** [comment]
Deze verplaatst ik naar Done. Wat nog voor mij op de rol zit is extra documentatie wat meer uitleg biedt over implementatie. Maar dat zal in een los issue verwerkt worden.
