### ISSUE TITLE
Date Picker invoer via input geeft geen fout bij datum buiten opgegeven range

### ISSUE THREAD

**Issue by smvandermeulen** [dso-toolkit/dso-toolkit#1482]
Als een min en/of een max is opgegeven aan de Date Picker, dan zou deze bij invoer via de input een fout moeten geven als de datum niet binnen de opgegeven range valt. 
Daarnaast zou ook bij vreemde input, bijvoorbeeld "zzzzz" een fout status moeten worden aangeven.

**Comment by smvandermeulen** [comment]
Voorstel:
- wanneer een op zich valide input van een datum buiten een eventueel opgegeven min of max valt, dan wordt een error ge-emit "min-range" of "max-range"
- wanneer een karakter wordt getypt dat niet in de range "-0123456789" valt, dan wordt dit karakter genegeerd
- wanneer door bijvoorbeeld plakken niet toegestane karakters worden ingevuld, dan een error ge-emit "invalid"

**Comment by gofix** [comment]
Testbaar op https://core.dso-toolkit.nl/_1482-Date-Picker-invoer-via-input-verbeterde-foutafhandeling/?path=/story/date-picker--default
