### ISSUE TITLE
dso-icon in button size moet 24px zijn

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#1486]
**Aanleiding**
Bij het testen van https://github.com/dso-toolkit/dso-toolkit/issues/1478 (scrollen in kaartlagen) viel op dat de sluitknop kleiner is dan normaal. De afmetingen van het icoon zijn in em uitgedrukt, zie screenshot.

**Werkzaamheden**
De sluitknop moet overal 24px groot zijn.

![image](https://user-images.githubusercontent.com/598735/158551289-4a774e92-6340-4795-9b34-1027a9f1a75a.png)

**Comment by gofix** [comment]
@bramhoosemans stelt:
> De sluitknop moet overal 24px groot zijn.

Volgens mij hadden we gesteld: we maken ALLE icons in buttons 24px.

**Comment by bramhoosemans** [comment]
Scherp! Dat hebben we inderdaad genoemd in refinement, maar niet opgeschreven.

**Comment by daverhelst** [comment]
@tfrijsewijk Ik ben op onderzoek gegaan waarom de 1.5em anders lijkt te reageren in een shadowDOM, maar kan geen duidelijk antwoord vinden online. Ik stel voor om de omvorming van `$dso-icon-size` van `em` naar `rem` door te zetten, hierdoor komt de maatvoering wel altijd uit op `24px`.

**Comment by tfrijsewijk** [comment]
Als ik op de `button` in `dso-info` shadow root `font-size: inherit;` zet gaat het goed, heb je dat gezien?

![image](https://user-images.githubusercontent.com/9696261/159688046-59390406-2d50-40c0-8e67-a27631b8d8e3.png)

Moeten we in een Shadow Root soms expliciet inheriten? 🤔

**Comment by daverhelst** [comment]
Ah, ik had hem op `:host` niveau gezet op `font-size: 16px` en dat gaf geen gewenst resultaat. Wel bijzonder dat het wel werkt met een `font-size: inherit` op `:host > button`, Heeft dit voorkeur boven de `1.5rem` invulling op de variabele? Als de wens is dat de iconen in buttons altijd `24px` moeten zijn, dan zal dit met de `1.5rem` zeker het geval zijn, uitgaande van de base-font-size van 16px.

Welke keuze gaan we maken?

**Comment by tfrijsewijk** [comment]
Wil jij uitzoeken waarom het zo werkt? Kunnen we daarna samen de afweging maken tussen `1.5rem` vs. `24px`.

**Comment by daverhelst** [comment]
Ok, we zijn er uit. Aangezien de ShadowDOM in een "eigen wereld" leeft, komt de default useragent styling ineens om de hoek kijken, dat is de reden waarom `font-size: inherit` wel werkt zodra het op `:host > button` gezet wordt, want dan wordt de default useragent styling overschreven.

We kiezen er voor om dit op te lossen met een stukje "normalize" stijling, die te vinden is in:
```
@import "~@dso-toolkit/sources/src/styling/global/button";
```

Dit doen we echter ook al in `map-controls.scss`, maar dit zou op meerdere plekken aangepast moeten worden. Dit probleem wordt in sommige webcomponents nu op een andere manier opgelost, zie bijvoorbeeld bij `info-button`:

```
$dso-info-button-size: $u3;

@mixin info-button_root() {
  @include di("info", $dso-info-button-size);
```

**Comment by tfrijsewijk** [comment]
Voor formulier elementen (`button`, `input`, etc) is de default user agent styling voor `font-size: 13.333px`. Dat betekent dat `1.5em` dus `19.9995px` wordt, afgerond `20px`.
