### ISSUE TITLE
Checkbox display in IE 11 

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#149]
In IE 11 zien de checkboxes er uit als een soort stembiljet. Bug ? Implementatie? 

![image](https://user-images.githubusercontent.com/36912722/42556379-b274f70e-84eb-11e8-8b00-22ec1754d740.png)

**Comment by tfrijsewijk** [comment]
Merged, komt uit in `3.0.0-alpha.2`

**Comment by tfrijsewijk** [comment]
Testable: https://www.dso-toolkit.nl/3.0.0-alpha.2/components/detail/group-checkboxes.html

**Comment by MichielDHVD** [comment]
Verplaatst naar Done en kan gesloten worden. (Ik kan dit zelf niet zo snel op IE11 testen maar ga er in dit geval vanuit dat het opgelost ist)
