### ISSUE TITLE
Button Row component voor afdwingen marges en responsive gedrag

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#1492]
Aanleiding
Bij het opzetten van de voorbeeld pagina's Mijn Omgevingsloket #1307 vielen een aantal dingen op. De terug link zit tegen de header aan geplakt én rijen met meerdere acties hebben onvoldoende marge / verkeerd responsive gedrag.

Werkzaamheden
Button Row component toevoegen voor gewenste marges en responsive gedrag:

Marge boven en onder de button-row 32px
Marge tussen buttons altijd 16px

Ontwerp
![image](https://user-images.githubusercontent.com/36912722/159916997-18d4fa76-91c2-4cd4-a5ed-e743f9fbf980.png)
![image](https://user-images.githubusercontent.com/36912722/159917019-f463bf20-8d1e-48c1-addf-0ead7758e8ef.png)
![image](https://user-images.githubusercontent.com/36912722/159917035-df32010e-3fb5-4715-92f7-faecca8b4385.png)

Testen
ntb

Acceptatiecriteria
ntb

**Comment by PieterVerheij** [comment]
Er bestaat al de class `dso-form-buttons` met de modifier `dso-aside`. Is het de bedoeling dat deze twee (button-row en form-buttons) naast elkaar komen te leven?

Als ik `dso-form-buttons` toepas op de Projectoverzicht-pagina, krijg ik onderstaand resultaat:
![image](https://user-images.githubusercontent.com/25430835/163200121-15bcc2ce-cf03-46f2-9e6a-da4e57955a02.png)

![image](https://user-images.githubusercontent.com/25430835/163199985-62d935dd-f905-4bfe-9134-41bb7d3089d5.png)

Het nadeel van `dso-form-buttons` is dat er (complexe) logica in zit qua horizontale uitlijning van de buttons (zie ), maar die zou met een class-modifier te manipuleren kunnen zijn. Zie Button combinaties op https://www.dso-toolkit.nl/master/components/detail/buttons.html

**Comment by MichielDHVD** [comment]
@PieterVerheij vandaag tijdens refinement bespreken?

**Comment by bramhoosemans** [comment]
> Er bestaat al de class `dso-form-buttons` met de modifier `dso-aside`. Is het de bedoeling dat deze twee (button-row en form-buttons) naast elkaar komen te leven?

Wat mij betreft wel. De `dso-form-buttons` zijn volledig gericht op button uitlijning in (wizard) formulieren, terwijl een 'button-row' geen specifieke relatie heeft met een formulier.

Het is juist de bedoeling om meerdere knoppen goed uit te lijnen _buiten_ formulieren.

**Comment by tfrijsewijk** [comment]
Deze is nog niet goed: https://github.com/dso-toolkit/dso-toolkit/commit/13c3d10925c7ac57bb78c7c38e15df320ff36e57#r71735551

Dit is gelukkig de laatste die gemerged is. @gofix en @PieterVerheij kunnen jullie een fix realiseren en de commit op master amenden?

**Comment by tfrijsewijk** [comment]
Bovenstaande opmerking hebben Pieter en ik verwerkt, kan weer gesloten worden.
