### ISSUE TITLE
Component button row toevoegen aan Voorbeeldpagina's

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#1493]
**Aanleiding**
Bij het opzetten van de voorbeeld pagina's Mijn Omgevingsloket #1307 vielen een aantal dingen op. De terug link zit tegen de header aan geplakt.

**Werkzaamheden**
Buttonrow toepassen op voorbeeldpagina's
Mijn Omgevingsloket (3 pagina's)
Samenwerken

Testen
ntb

Acceptatiecriteria
ntb

**Comment by PieterVerheij** [comment]
@MichielDHVD 
Volgens mij moet de button-row maar op 2 pagina's bij _Mijn Omgevingsloket_ worden toegepast en ik zie niet waar die bij _Beheer basis_ geplaatst moet worden?

**Comment by MichielDHVD** [comment]
@PieterVerheij  Ik heb inderdaad verkeerd gekeken. Bij beheer basis is het niet nodig. Heb deze uit de story gehaald.

**Comment by PieterVerheij** [comment]
@bramhoosemans 

![image](https://user-images.githubusercontent.com/25430835/164219310-6d42af91-eb0b-46c4-81b5-c4b7a8192e5e.png)

Deze marges zijn ook de beoelding? Dit is de huidige situatie:
![image](https://user-images.githubusercontent.com/25430835/164219410-69752e48-e156-4ee2-aedd-40e636418064.png)

**Comment by PieterVerheij** [comment]
Omdat bij Mijn Projecten de `app-heading` een margin-bottom heeft en de `button-row` IN de `dso-context-wrapper` staat, worden de margin-bottom (16px) van de `app-heading` en de margin-top van de `button-row` bij elkaar opgeteld: 48px: 32px + 16px.

Ik heb een uitzondering in de css gemaakt, maar er kunnen nog meer scenario's zijn waar dit bij kan voorkomen, heel solide is het niet:
```.dso-button-row {
  display: flex;
  flex-wrap: wrap;
  gap: $u2;
  margin: $u4 0;

  .dso-context-wrapper & {
    margin: $u2 0 $u4;
  }
}```

**Comment by PieterVerheij** [comment]
@bramhoosemans we hebben naar bovenstaand probleem gekeken en hebben geconcludeerde dat het niet mogelijk is om een eenduidige oplossing te vinden. Je weet namelijk nooit of het element ervoor een margin-bottom heeft en of deze wel of niet genest is (ivm met collapsing margins).

Er zijn drie mogelijkheden:
we accepteren de ontstane (grote) margins as is
we passen de margins aan voor alleen dit scenario

Maar onze voorleur gaat uit naar deze oplossing: de margin-top van buttin-row zetten we op 16px, de margin-bottom op 32px.  In ALLE voorbeeldpagina's leidt dit naar onze mening tot een acceptabel resultaat:
Overzicht samenwerkingen
![image](https://user-images.githubusercontent.com/25430835/164465078-8243cef1-5fc6-4594-9d72-fd80f7a40a93.png)

Mijn projecten
![image](https://user-images.githubusercontent.com/25430835/164465180-813ac7f9-0b34-45a9-80b4-167d28354590.png)

Project overzicht
![image](https://user-images.githubusercontent.com/25430835/164465273-b3fa4770-919a-4be2-b71b-c9469dde2e7d.png)

Verzoek detail
![image](https://user-images.githubusercontent.com/25430835/164465360-2a86d231-d0af-4ccc-8481-3a3e322af966.png)

**Comment by bramhoosemans** [comment]
Tja, collapsing margins zijn/blijven vervelend.

Ik kan me wel vinden in een subtiele aanpassing van de margin-top, omdat de button row zich vaak onder een `app-heading` bevindt. Van 32 naar 16px is wel een flinke stap... ik zou ook 24px willen overwegen.

Is er ergens een branche release te vinden waar ik dit in kan beoordelen?

**Comment by bramhoosemans** [comment]
Hmm ik zie inderdaad op meerdere plekken meer marges ontstaan dan verwacht. Vergelijk ze met de ontwerpen in https://github.com/dso-toolkit/dso-toolkit/issues/1492. Ik vermoed ook dat een margin-top 16px het "probleem" is opgelost. Wat mij betreft gaan we het zo doorvoeren.

Zou je wel overal de `dso-button-row` kunnen toepassen in de voorbeeldpagina's? Bijvoorbeeld op de 'Verzoek detail' alle buttons in aparte row's en op 'Project overzicht' de button "Bekijk andere projecten" in eigen row over de volledige breedte.
