### ISSUE TITLE
100% zoom in firefox Radiobuttons en Form display issue in Modal

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#150]
De radiobuttons en form wordt niet perfect weergeven. Ze lijken aan de bovenkant afgekapt te worden. Ben benieuwd wat er voor zorgt dat sommige browsers deze elementen zo weergeven. 

![image](https://user-images.githubusercontent.com/36912722/42556571-5342aff0-84ec-11e8-9ef3-0194810d1c47.png)

**Comment by tfrijsewijk** [comment]
Ik kan het niet reproduceren. Welke versie Firefox is dit? Kun je het reproduceren op dso-toolkit.nl ?

**Comment by MichielDHVD** [comment]
Even aan de developer gevraagd die meldt het volgende. 

Het eerste, afgekapte radiobuttons treedt bij mij nog steeds op.
Met Firefox 61.0.1 op Ubuntu 18.04 en met Firefox 61.0.2 op Windows 7.

 Op dso-toolkit.nl is er geen pagina waarmee het te reproduceren is: je hebt er radiobuttons in een modal voor nodig.

**Comment by tfrijsewijk** [comment]
We gaan het onderzoeken

**Comment by Poofy83** [comment]
Ik heb dit pogen te reproduceren, maar krijg dit resultaat niet naar voren. Ik heb mijn best gedaan om het zo goed mogelijk na te bouwen in de toolkit om te testen, een modal met radiobuttons en de searchbar, maar zie daarin geen afwijkende zaken.

@MichielDHVD Is het mogelijk dat wij het stuk markup van jullie krijgen waar zich dit in voordoet?

**Comment by MichielDHVD** [comment]
Ik zal het morgen bij de developers even navragen.

**Comment by maartenvs** [comment]
De pagina is te bekijken op de INT-omgeving. Ik zal de URL privé doorgeven aan @tfrijsewijk .
Instructies:
* Klik in stap 1 op "Volgende stap".
* Kies in stap 2 een willekeurige locatie en ga naar de volgende stap.
* Klik in stap 3 op "Toevoegen".
* De modal verschijnt.

**Comment by Poofy83** [comment]
Mijn eerste onderzoek geeft het volgende resultaat:
Het heeft te maken met `subpixel calculation`, oftewel ergens wordt een .xx waarde uitgerekent en sommige browsers ronden dit af naar boven, anderen weer naar beneden.

Zo kan het dus zijn dat 1.65px in de ene browser als 2px wordt gezien (wat de bedoeling is) en in de andere browser als 1px.

Een oplossing is om het element waar dit zich voordoet meer ruimte te geven zodat hij volle pixels kan benutten (padding, oid), maar ik ga eerst onderzoeken _waarom_ er ergens een niet volledige pixel wordt gegeven. U hoort nog.

**Comment by maartenvs** [comment]
We gebruiken nu versie 3.0.0 van de DSO Toolkit, en daarbij treedt dit effect niet meer op. De input en checkboxes (ondertussen geen radiobuttons meer) zien er nu goed uit.

Gezien in [Alexia build: 2018-09-20T15:07:12-a4206ddd].

**Comment by tfrijsewijk** [comment]
We sluiten 'm, dank voor terugkoppelen!
