### ISSUE TITLE
Regression in 34.2: list group within rich content has extra left padding

### ISSUE THREAD

**Issue by WiebeCnossen** [dso-toolkit/dso-toolkit#1503]
Since release 34.2.0 a `ul.list-group` has a `padding-left` of `24px` when nested in a `div.dso-rich-content`.  
In 34.1 and before, the `padding-left` was `0`.

Reproduction:
```html
<div class="dso-rich-content">
  <ul class="list-group"
    <li class="list-group-item">
      Cras justo odio
    </li>
  <li class="list-group-item">
      Dapibus ac facilisis in
    </li>
  <li class="list-group-item">
      Morbi leo risus
    </li>
  <li class="list-group-item">
      Porta ac consectetur ac
    </li>
  <li class="list-group-item">
      Vestibulum at eros
    </li>
  </ul>
</div>
```

**Comment by WiebeCnossen** [comment]
Visueel is dit ook duidelijk op de Patronen > Full Width pagina, vergelijk:

* https://dso-toolkit.nl/34.1.0/components/detail/full-width.html
* https://dso-toolkit.nl/34.2.0/components/detail/full-width.html

**Comment by gofix** [comment]
Het is op veel meer plekken mis, ook bv. in link lists -> https://dso-toolkit.nl/34.2.0/components/detail/project-overzicht.html
