### ISSUE TITLE
Modal repositions when content changes

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#151]
Er is een modal gebruikt bij activiteit selecteren.  Daar staan eerste mogelijke bouw activiteiten, zodra je gaat zoeken verkleint de modal en past zich aan naar de overgebleven resultaten. 

<img width="1427" alt="screen shot 2018-07-11 at 09 37 15" src="https://user-images.githubusercontent.com/36912722/42557872-ede098e4-84ef-11e8-98bc-df771a353f48.png">
<img width="1432" alt="screen shot 2018-07-11 at 09 37 30" src="https://user-images.githubusercontent.com/36912722/42557873-edfb7bdc-84ef-11e8-964a-07ee9fc7a304.png">

Maar de modal staat altijd gecentreerd waardoor zowel boven als onder ruimte wegvalt. Deze verspringen is best intens.

 Fijner zou zijn als de bovenkant van het modal blijft staan en dat de ruimte die wegvalt onder wordt wegvalt. (Hopelijk verwoord ik het zo goed en helpen de afbeeldingen. )

Ook even een linkje om het even te bekijken met wat uitleg. 

https://alexia-develop.docker2.team-dso.nl/alexia-frontend/toepassingen/checken/stap/2

Als je naar deze link gaat en je klikt op het icoontje voor Activiteit toevoegen. Dan zie je 4 resultaten staan. Als je dan bouwen intypte dan zul je de modal zien verkleinen.

**Comment by tfrijsewijk** [comment]
CSS gestuurde oplossing zijn beperkt. Ik heb de volgende aanpassingen gedaan:
* Het hart van de modal wordt niet meer in het midden van het scherm gepositioneerd
* De modal heeft een `top: 15vh` gekregen. Hierdoor staat een modal "hoger" in het scherm
* De maximale hoogte _van de inhoud_ is ongeveer `70vh` geworden

Doordat niet meer het hart van de modal maar de bovenkant van de modal wordt gepositioneerd zal de modal niet meer verschuiven als de inhoud van de modal verandert.

De modal is pas in het hart van het scherm uitgelijnd als de modal zijn maximale hoogte heeft bereikt:

![image](https://user-images.githubusercontent.com/9696261/43760978-f1bdea04-9a23-11e8-96a6-bb0ee8ab51c7.png)

Een kleinere modal zal "hoger" staan:

![image](https://user-images.githubusercontent.com/9696261/43761009-0e272304-9a24-11e8-9e08-ccbc12b3df14.png)

Vanuit de CSS kan ik geen andere oplossing leveren. Alternatief is de modal scriptend positioneren. Ik kan dan een modifier class maken waarmee het positioneren vanuit de CSS wordt uitgezet. Er is dan geen conflict met een positie die scriptend is bepaald

**Comment by tfrijsewijk** [comment]
Bovenstaande fix komt uit in `3.0.0-alpha.1`

**Comment by MichielDHVD** [comment]
Ik vind dit een prima oplossing die wij vanuit CSS kunnen aanbieden. Ik geef het door aan de developers hoe dit is opgelost. 

Ik verplaats deze naar Done
