### ISSUE TITLE
Uitbreiding Shopping Cart met functie 'alles verwijderen'

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#1510]
**Aanleiding**
Uit ervaring is gebleken dat het lastig is om een nieuwe (lege) Vergunningcheck of Maatregelen op maat te starten. De verwachting is dat een deel van de frustratie weggenomen kan worden door de optie aan te bieden waarmee alle gekozen werkzaamheden in één keer kunnen worden verwijderd.

**Werkzaamheden**
'Alles verwijderen' actie toevoegen aan de Shopping Cart.

- 'Alles verwijderen' is een optionele actie
- Toevoegen aan 'Summary' en rechts uitgelijnd. Op smalle viewports rechter uitlijning aanhouden
- 'Summary' toevoegen aan niet inklapbare variant (incl. alles verwijderen actie)
- Screenreader "Verwijder alle werkzaamheden/activiteiten."
- Voorbeeldpagina 'activiteiten' wijzigen

**Ontwerp**
![image](https://user-images.githubusercontent.com/36912722/162186829-173b3cda-e8b2-48a4-a1a4-94547524dd18.png)
![image](https://user-images.githubusercontent.com/36912722/162186852-4f36478b-a8a9-4eb2-9d15-a08eecf07f5e.png)

Twee bugs zijn een subtaak van dit issue:

**Comment by PieterVerheij** [comment]
'Alles verwijderen' is een optionele actie' 
Maar de button verschijnt toch wel altijd als er een maatregel gekozen is?

**Comment by bramhoosemans** [comment]
@PieterVerheij 
- De gedachte achter "alles verwijderen is een optionele actie" is dat het geen verplicht element is binnen het component Shopping Cart. In Storybook zou ik bijvoorbeeld een toggle verwachten om de "feature" uit of aan te zetten.
- Met 'summary' wordt de samenvatting boven de lijst items bedoeld. Hierbij heb ik de terminologie proberen aan te houden die nu wordt gebruikt.
<img width="530" alt="Schermafbeelding 2022-05-17 om 11 41 52" src="https://user-images.githubusercontent.com/598735/168782340-72df7e83-cba5-43dc-aa84-82b3a6baf164.png">

**Comment by PieterVerheij** [comment]
@bramhoosemans https://www.dso-toolkit.nl/_1510-Uitbreiding-Shopping-Cart-met-functie-alles-verwijderen/components/detail/shopping-cart.html

**Comment by bramhoosemans** [comment]
@PieterVerheij nog een paar opmerkingen:

Op smalle weergave, bijvoorbeeld 320px, schuift de actie ‘alles verwijderen’ over de tekst heen.

Het sr-only label van de button zou ik veranderen in de juiste context. Het is nu “Verwijder alle werkzaamheden/activiteiten” > in het voorbeeld gaat het altijd om ‘activiteiten’, dus “Verwijder alle activiteiten”.

Tooltips werken niet voor alle icon-only acties, naast ‘Alles verwijderen’ en ‘Verwijder’ bij enkele activiteiten ook:
- ‘Verwijder’ toevoegen aan subitems prullenbak.
- ‘Naam veranderen’ toevoegen aan potlood icoon.

**Comment by PieterVerheij** [comment]
> Tooltips werken niet voor alle icon-only acties, naast ‘Alles verwijderen’ en ‘Verwijder’ bij enkele activiteiten ook:

> ‘Verwijder’ toevoegen aan subitems prullenbak.
> ‘Naam veranderen’ toevoegen aan potlood icoon.

Dat valt volgens mij onder https://github.com/dso-toolkit/dso-toolkit/issues/1512

**Comment by bramhoosemans** [comment]
Ah die had ik over het hoofd gezien! Ik zal de inhoud (nog snel even) nalopen, want ik zie er woorden in staan die niet onder B1 taalgebruik vallen.

**Comment by PieterVerheij** [comment]
> Op smalle weergave, bijvoorbeeld 320px, schuift de actie ‘alles verwijderen’ over de tekst heen.
Oeps, net teveel scss opgeschoond. Gefixt.

> Het sr-only label van de button zou ik veranderen in de juiste context. Het is nu “Verwijder alle werkzaamheden/activiteiten” > in het voorbeeld gaat het altijd om ‘activiteiten’, dus “Verwijder alle activiteiten”.
Aangepast

**Comment by bramhoosemans** [comment]
Wat mij betreft goed zo 👍

**Comment by bramhoosemans** [comment]
@PieterVerheij volgens mij hebben we een variant gemist...

<img width="1293" alt="Schermafbeelding 2022-05-27 om 09 04 54" src="https://user-images.githubusercontent.com/598735/170648865-c40f1f59-f1b0-4206-bcc8-3a398fd32275.png">

**Comment by gofix** [comment]
Dus, @bramhoosemans welke variant willen we nu precies nog toevoegen en waar (Storybook/Fractal)...?
Trouwens, dit aantal klopt niet toch?
![image](https://user-images.githubusercontent.com/2689559/170989494-48a4e71f-d943-4b94-a7cf-3a6a62544577.png)
Of zijn die 'subjes' wat de 'activiteiten' zijn (dan klopt die 3 wel).

**Comment by bramhoosemans** [comment]
@gofix Zojuist besproken met @PieterVerheij en nieuwe taak aangemaakt, zie [ #1581](https://github.com/dso-toolkit/dso-toolkit/issues/1581)
