### ISSUE TITLE
Shopping cart: ontbrekend aria-expanded attribuut op button

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#1511]
Aanleiding
Aria-expanded ontbreekt op knoppen "U heeft 2 activiteiten gekozen "

Gebruikersimpact
Hinderlijk: screen reader gebruikers moeten handmatig uit de opvolgende content afleiden of de knop wel of niet uitgeklapt is, kan verwarrend zijn.

Werkzaamheden
Aria-expanded aan deze knoppen toevoegen

**Comment by gofix** [comment]
Met knopnaam zal de accessible name van een element bedoeld worden. dat is dus ofwel hetgeen in een `button` of `a` staat, ofwel wat in `aria-label` staat, maar, in dit geval IS de knopnaam dus gewoon "U heeft 2 activiteiten gekozen".

**Comment by PieterVerheij** [comment]
@timveld hier zijn `aria-expanded` toegevoegd: https://www.dso-toolkit.nl/_1511.Shopping-cart--ontbrekende-aria-expanded-en-knopnaam/components/detail/shopping-cart.html
