### ISSUE TITLE
Shopping cart: labels knoppen

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#1512]
Aanleiding
De labels voor naam wijzigen en verwijderen bevatten niet de naam van wat we wijzigen / verwijderen, dat doen we verder overal wel.

Gebruikersimpact
Beperkt: functie knopje kan ook uit de context worden afgeleid, aanvulling label is extra hint

Werkzaamheden
Voorgestelde labels

Naam wijzigen wordt "wijzig naam [naam]"
Verwijderen wordt "verwijder [naam]"

**Comment by PieterVerheij** [comment]
@bramhoosemans @MichielDHVD 
Welke tekst komt er in de tooltip?

In de afbeelding wordt `Naam veranderen` gebruikt, in dit issue `wijzig naam`?

Kunnen jullie uitsluitsel geven over de teksten in de `tooltip` en in de `sr-only`?

**Comment by bramhoosemans** [comment]
@PieterVerheij aangezien 'wijzigen' en 'bewerken' geen B1 taalniveau zijn stel ik voor de volgende teksten te gebruiken.

Verwijderen:
- tooltip "Verwijder"
- sr-only "Verwijder [activiteit]"

Naam veranderen:
- tooltip "Naam veranderen"
- sr-only "Naam veranderen van [activiteitsnaam]"

**Comment by gofix** [comment]
Klaar. @bramhoosemans voor de duidelijkheid, de tooltips zijn alleen in fractal te zien, niet in het html/css storybook. Want: tooltips zijn Web Components, die laten zich vooralsnog niet zomaar in het html/css storybook tonen.

**Comment by bramhoosemans** [comment]
Top!
