### ISSUE TITLE
Paragraaf in Card heading zorgt voor overbodige marge

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#1513]
Aanleiding
Wens om marge onder Card heading te verkleinen leidde tot de ontdekking dat de paragraaf bij de Toggletip extra witruimte meegeeft. Met andere woorden de `<p class="text-muted">` in de voorbeeldpagina Projectoverzicht zorgt voor 16px 'extra' marge.

Werkzaamheden
Margin-bottom van `<p>` in Card heading op 0 zetten.

**Comment by daverhelst** [comment]
Testlink: https://dso-toolkit.nl/_1513.Paragraaf-in-Card-heading-zorgt-voor-overbodige-marge/components/detail/project-overzicht.html
