### ISSUE TITLE
Cards marge heading verkleinen

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#1514]
Aanleiding
Als een Card alleen een heading en term (korte inhoud) bevat is de ruimte tussen titel en content té groot. Vandaar de wens om de marge onder de Card heading te verkleinen naar 8px (was 16px).

Werkzaamheden
dso-card-heading line-height hanteren van 24px (dat is nu 27px?)
dso-card-heading margin-bottom verkleinen naar 8px

**Comment by daverhelst** [comment]
De 27px maat komt door de `dso-icon` die er in staat. Deze heeft een verkeerde maatvoering. Dit probleem wordt opgelost in [1542](https://github.com/dso-toolkit/dso-toolkit/issues/1542)
