### ISSUE TITLE
`<dso-ozon-content deleted>` voor het markeren van verwijderde content

### ISSUE THREAD

**Issue by kad-leeffs** [dso-toolkit/dso-toolkit#1518]
Als **Viewer Regels op de Kaart** wil ik graag titels tonen, waarvan de tekst is doorgehaald.

- Idee: Als `strikethrough` meegeven dat als `control` input.
- Output is gewrapped in `<del>`

**Comment by kad-leeffs** [comment]
@tfrijsewijk Het is inderdaad een property op hoger niveau. En het gebruik van het `del` element volgt eigenlijk op het advies van jullie specs. Het is zeker niet verplicht om dit element te gebruiken, sterker nog het ziet er heel lelijk uit in een geneste HTML structuur. Wel zou ik hem als input aan het webcomponent willen geven. zodat jullie eventueel via styling wat kunnen zetten.

**Comment by tfrijsewijk** [comment]
![image](https://user-images.githubusercontent.com/9696261/169071082-83c7b132-abd2-4907-a572-f103ed00d04d.png)

![image](https://user-images.githubusercontent.com/9696261/169071168-e57165fa-b1ea-4231-bc82-50cd77eb548d.png)
