### ISSUE TITLE
Accordeon border-top schakelbaar maken

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#152]
De lijntjes in de accordeon hebben wat extra werk nodig. Op dit moment wordt deze alleen boven weergegeven. Er zijn twee dingen die moeten gebeuren

1) De lijntjes moeten zowel boven als onder aan gezet kunnen worden. Soms komt het voor dat aan de bovenkant geen lijn nodig is. De optie om beide zowel boven als onder aan te zetten is verzocht. 

2) " Extra lijntje"  Als de accordeon uitklopt moet er nog steeds onder de titel een lijntje staan. Zie de afbeelding. 

<img width="571" alt="screen shot 2018-07-12 at 14 16 29" src="https://user-images.githubusercontent.com/36912722/42632732-7b5d4052-85de-11e8-9c86-22cf1a7885c7.png">

Als je dus kijkt naar het uitgeklapte " Boom 23 kappen " staat er zowel boven als onder een streepje.  Elk accordeon zou deze moeten hebben. 

Als het geanimeerd zou zijn zou de content onder deze lijn vandaag verschijnen. 

Als er meer uitleg of vormgeving nodig is hoor ik het graag.

**Comment by tfrijsewijk** [comment]
1. De accordeon uit de toolkit heeft een top border, jouw screenshot niet
2. De accordeon uit de toolkit heeft geen border bottom, jouw screenshot wel
3. De inhoud van een accordeon krijgt onder de nodige ruimte om verticale spacing te maken: jouw screenshot niet.
4. In het voorbeeld uit de toolkit wordt de inhoud van een accordeon gevuld met `<p>`. Een `<p>` krijgt een margin-bottom, samen de padding uit punt 3 maakt dit veel verticale spacing. Echter, is dit onvoorspelbaar. Als er een `<table>` in zit is de totale verticale spacing anders. Ik stel voor om bij lopende teksten de container wrapper `.dso-rich-content` te gebruiken. De markup wordt dan `.dso-accordion > .dso-accordion-section > .dso-accordion-body > .dso-rich-content`. Het `.dso-rich-content` component zorgt ervoor dat de verticale spacing te sturen is, zie #85.
5. De verticale spacing uit punt 4 zie ik niet terug in jouw screenshot. Ik zie dat de tekst van de `.btn-link` is uitgelijnd met het woord "Bijlagen" links (met een badge die niet in de toolkit zit), ik geloof niet dat de toolkit dit zo levert: Ik vermoed dat de button "hoger" zal staan. In ieder geval, de ruimte onder de inhoud van een blok is niet terug te vinden in jouw screenshot. Wil je dat ik 'm ook uit het component weghaal?

Heeft niet met de scope van deze issue te maken, maar het lijkt erop dat je een Definition List (https://www.dso-toolkit.nl/2.0.0/components/detail/definition-list.html) gebruikt. De labels hebben een andere kleur, wil je hier iets mee doen?

**Comment by MichielDHVD** [comment]
Ik ga deze nog even herbeoordelen. Even kijken of ik een consistente logica kan vinden. 

Plus ik ga ook een kleine verzameling maken van afbeeldingen waar de verschillende vormen duidelijk geillustreerd zijn. 

(Ik ga ook een nieuwe balk in het project toevoegen. To be Respecified. Daar kunnen issues heen waar ik nog meer input moet leveren. Dan is er een duidelijk overzicht tussen wat ik moet doen en tussen issues die jullie kunnen oppakken.)

**Comment by MichielDHVD** [comment]
Deze gaan we iets langer de tijd voor nemen om goed door te nemen. Omdat we ook volgend PI de whitespaces en de toolkit willen verbeteren en doornemen. Daar gaan we ruimte en tijd voor maken. dit past daar mooi in.

**Comment by MichielDHVD** [comment]
We zijn er uit.  De enigste variatie die wenselijk is betreffende de accordeon is dat de top border uitgezet kan worden. 

![accordeon einde open](https://user-images.githubusercontent.com/36912722/48194879-8568eb00-e34e-11e8-8b83-8d99381c089f.png)
![accordeon midden open](https://user-images.githubusercontent.com/36912722/48194880-8568eb00-e34e-11e8-9d1d-e31a1beaa19f.png)
![accordeon top geen border](https://user-images.githubusercontent.com/36912722/48194881-8568eb00-e34e-11e8-9938-f76f67e1fa1d.png)


Even afbeeldingen ter verduidelijking toegevoegd.

**Comment by tfrijsewijk** [comment]
@MichielDHVD: Er is een PR (#230) waar de border voor elke eerste sectie in elke accordion wordt uitgezet.

Maar ik interpreteer deze issue als een wens voor een modifier class, dat de ontwikkelaar kan kiezen voor een border.

Los van dit alles wil ik nogmaals benadrukken dat dit niet een wenselijke situatie is. Beter is om de werkvormen te bestuderen en aan de hand van volgordes van componenten, inzetbaarheid of context deze border sturing te geven

**Comment by MichielDHVD** [comment]
De border moet uitstaan als er boven de accordeon ook nog een andere border of line staat. Het beeld wordt erg onrustig als er twee lijnen onder elkaar staan. En dat willen we voorkomen in de ontwerpen. 

Jij wil dit proces automatiseren dat developers dit niet zelf moeten doen maar de toolkit bepaalt het gedrag compleet. 

Is dat genoeg informatie om je vraag te beantwoorden. Dus als er boven de accordeon een lijn staat dan willen we de bovenste border uit hebben.

**Comment by PieterVerheij** [comment]
@MichielDHVD @tfrijsewijk Dan zouden we een lijst van eventuele combinaties (bv. table + accordion) moeten maken waarbij we de eerste border uitzetten? Enige andere oplossing is mijns inziens dat de implementator een extra class op de accordion plaatst die de eerste border uitzet.

**Comment by tfrijsewijk** [comment]
@PieterVerheij Dat klopt, dat zou mijn voorkeur hebben. Maar ik begrijp ook dat we de toolkit dan minder 'bouwstenerig' maken, dus laten we maar voor een modifier class gaan: `dso-no-border` of `dso-no-top-border` ?

**Comment by MichielDHVD** [comment]
Gezien en verplaatst naar done
