### ISSUE TITLE
Als ik een custom contrast instel in Firefox worden checkboxes onzichtbaar.

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#1521]
Aanleiding
Tijdens een gebruikerstest met mensen met een beperking kwam dit naar voren. De gebruiker maakte gebruik van de custom instelling van firefox om contrast te verhogen. Maar dit zorgde ervoor dat de radiobuttons en checkboxes in de toolkit onzichtbaar worden. 

Werkzaamheden
Checkboxes en radiobuttons moeten zichtbaar zijn wanneer de contrast instellingen aangepast worden. 

Testen
Welke test stappen moeten uitgevoerd worden om te controleren of het component correct is gebouwd

Bijv:

Screenreader test in geval van WCAG aanpassingen
Visuele controle -> Responsive, Zoom 400%
Interactie gedrag testen meerdere browsers
Voorbeeldpagina's nalopen kijken of er onwenselijke veranderingen zijn
Acceptatiecriteria
Controle/ Approval door Reporter/schrijver van Story
WCAG Approved (in afstemming met Tim in't Veld
Technische keuze consistentie Toolkit bewaakt door Info Projects .

**Comment by PieterVerheij** [comment]
De truc om `prefers-contrast` in Firefox aan te zwengelen:
```To get prefers-contrast, set layout.css.prefers-contrast.enabled to true in about:config. Now, go forth and build a more accessible web! 🎉```

**Comment by PieterVerheij** [comment]
Zie: https://www.dso-toolkit.nl/_1521-contrast-mode-styling-radiobuttons-en-checkboxes/components/detail/group-radios.html
Bij status `invalid` is de afwijkende border-kleur niet zichtbaar, maar wel de melding. Ik weet niet of dit ueberhaupt een probleem is (op zich is de melding er) en of dit dan binnen dit issue valt.
![image](https://user-images.githubusercontent.com/25430835/163188054-8292f87f-0e7a-485d-a54e-5ef926110185.png)

**Comment by gofix** [comment]
> Bij status invalid is de afwijkende border-kleur niet zichtbaar
Da's niet erg, je mag informatie toch al niet alleen met kleur overbrengen. En we brengen het op allerlei manieren over.
`aria-invalid` EN een melding
