### ISSUE TITLE
Accordion: overflow: hidden van section-handle af

### ISSUE THREAD

**Issue by daverhelst** [dso-toolkit/dso-toolkit#1522]
Tijdens implementatie van een `dso-toggletip` in de `section-handle` van een `dso-accordion` is naar voren gekomen dat de uitklap wordt afgesneden omdat er een `overflow: hidden` op de `section-handle` zit.

Er is een klein onderzoek nodig waarom deze `overflow: hidden` hier op staat. Als blijkt dat er geen duidelijke reden is, dan mag dit verwijderd worden. Anders moet er een uitbreiding gedaan worden dmv. een extra class (bijv. `.enable-toggletip`) die deze setting overruled.

**Comment by daverhelst** [comment]
Gerelateerd: https://github.com/dso-toolkit/dso-toolkit/issues/1480 -> @gofix gaat uitzoeken waar toggle- en tooltip allemaal problematisch zijn en wat daar de beste oplossing voor zou zijn. Dan wil je eigenljk deze casus toch wel meepakken. Dat zou dan betekenen dat we in het CSS storybook ook in een van de handles een toggletip moeten laten zien...

Of... houden we zoals @gofix voorstelt, de change zo klein als ie nu is... @bramhoosemans

**Comment by bramhoosemans** [comment]
@daverhelst @gofix @MichielDHVD Ik zou deze change zo klein mogelijk houden.

We hebben het er al eens eerder over gehad; met de nieuwe documentatiesite en Storybooks bekijken waar (en of) we combinaties van componenten willen borgen voor automatische testen e.d. Maar dat hoort naar mijn idee niet thuis in deze 'bug'.
