### ISSUE TITLE
Probleem met het implementeren van dso-header component in de Stelselcatalogus

### ISSUE THREAD

**Issue by kad-orhung** [dso-toolkit/dso-toolkit#1524]
Op dit moment ben ik bezig met het implementeren van <dso-header>(https://core.dso-toolkit.nl/35.0.0/?path=/story/header--header) component in de StelselCatalogus, en ik krijg hierbij de volgende javascript fout:
```
TypeError: Cannot read properties of undefined (reading 'filter')
    at s.render (p-06de0fa1.entry.js:1:2844)
    at te (p-dad72605.js:1:7658)
    at ee (p-dad72605.js:1:7501)
    at p-dad72605.js:1:7287
    at ie (p-dad72605.js:1:9024)
    at Z (p-dad72605.js:1:7277)
    at Array.<anonymous> (p-dad72605.js:1:7093)
    at Ce (p-dad72605.js:1:14546)
    at Re (p-dad72605.js:1:14608)
    at timer (zone.js:2561:1) 
```

De stelselcatalogus is een Angular applicatie met versie 13.3.1 en we maken gebruik van dso-toolkit 34.1.0.

Stappen die ik heb gedaan om dit component te implementeren:
index.html:
```
<script type="module" src="https://cdn.dso-toolkit.nl/34.1.0/core/dso-toolkit.esm.js"></script>
```

app.module.ts
```
schemas: [CUSTOM_ELEMENTS_SCHEMA],
```

header.component.html

```
<dso-header
  use-drop-down-menu="auto"
  is-logged-in="false"
  login-url="#login"
  logout-url="#logout"
  user-profile-url="#profiel"
  user-profile-name="J.A. Jansen"
  user-home-url="#myhome"
>
  <div slot="logo">
    <img
      height="40"
      alt="Omgevingsloket"
      src="
        <truncated>
        "
    />
  </div>
  <div slot="sub-logo">
    <img
      alt="Regels op de kaart"
      src="
<truncated>      "
    />
  </div>
</dso-header>

```

Kan iemand mij vertellen hoe ik dit kan oplossen?

**Comment by tfrijsewijk** [comment]
Hi @kad-orhung! 👋 

Ik vermoed dat het komt omdat je geen property `mainMenu` zet.

Probeer eens:

```
<dso-header
  main-menu="[]"
  use-drop-down-menu="auto"
  is-logged-in="false"
  login-url="#login"
  logout-url="#logout"
  user-profile-url="#profiel"
  user-profile-name="J.A. Jansen"
  user-home-url="#myhome"
>
```

Kijkende naar jouw foutmelding: In het Header component wordt alleen over `this.mainMenu` de property `filter` opgevraagd (https://github.com/dso-toolkit/dso-toolkit/blob/master/packages/core/src/components/header/header.tsx#L237, https://github.com/dso-toolkit/dso-toolkit/blob/master/packages/core/src/components/header/header.tsx#L252).

`this.mainMenu` is een `@Prop()` (https://github.com/dso-toolkit/dso-toolkit/blob/master/packages/core/src/components/header/header.tsx#L35) die een [non-null assertion operator](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#non-null-assertion-operator) heeft.. wat ik voor Web Components nogal twijfelachtig vind.

@gofix, @MichielDHVD: Zijn `mainMenu` items verplicht? Ik denk in ieder geval dat we die non-null assertion operator (`!`) moeten weghalen en de foutmelding moeten afvangen met bijvoorbeeld een default value lege array (`mainMenu = [];`) of een duidelijkere foutmelding tonen zodat de afnemer beter geholpen is.

**Comment by MichielDHVD** [comment]
Er is een specifieke story om een header neer te zetten zonder Menu items.  https://github.com/dso-toolkit/dso-toolkit/issues/1491 @tfrijsewijk 

Vraag is wel of dit logisch is voor de stelselcatalogus. De stelselcatalogus heeft altijd menu items gehad als ik de stelselcatalogus heb gezien. https://stelselcatalogus.omgevingswet.overheid.nl/home

Hoe moet de header er uit gaan zien voor Stelselcatalogus  @kad-orhung @LiesbethVorst ? Dan kunnen we het beste advies geven.

**Comment by kad-orhung** [comment]
@tfrijsewijk Heb het even geprobeerd en wanneer ik een valide mainMenu waarde opgeef dan dit element netjes getoond.

Ik heb aan onze kant een nieuwe story aangemaakt zodat we ook even kunnen kijken naar de menuitems. Dat zat namelijk niet in de scope.

Ik vraag me ook af of dit uberhaupt gaat werken aangezien wij in Angular Routerlink gebruiken. Een href zorgt voor een harde pageload. Zonder een menu heeft deze component geen toegevoegde waarde lijkt mij want er wordt niets getoond als mainMenu leeg is.

**Comment by tfrijsewijk** [comment]
@kad-orhung: Dat scheelt weer.

Mbt. framework routers: Hier hebben wij een strategie voor. Ik ben meteen voor je in de code gegaan, maar zag dat die niet is geimplementeerd voor de header 😅 Zal wel komen omdat we agile zijn 👼.

Het komt erop neer dat het Web Component voor elke `click` op `a` een event geeft. Vanuit je Angular codebase subscribe je op deze events en sluit je daar de router aan.

Pseudo code:

```typescript
import { DsoHeaderItemClickEvent } from '@dso-toolkit/core';

@Component({
  template: '<dso-header (itemClick)="navigate($event)"></dso-header>'
})
class MyComponent {
  constructor(private router: Router) {}

  navigate(event: CustomEvent<DsoHeaderItemClickEvent>) {
    event.detail.originalEvent.preventDefault(); // Voorkom standaard anchor gedrag

    this.router.navigate(['/item'], { id: event.detail.item.id }); // doe alles wat je anders met `[RouterLink]` doet.
  }
}
```

Maar volgens mij ben je in ieder geval geblokkeerd door het issue wat Michiel aandraagt #1491. Want er moeten wel menuItems komen, toch?

**Comment by kad-orhung** [comment]
Mij is niet bekend dat we een header nodig hebben zonder menu items. Dit is ook pas mijn derde week bij het kadaster 😄 

Dus nu is het enige blokkerende factor de itemClick support?

**Comment by LiesbethVorst** [comment]
> Er is een specifieke story om een header neer te zetten zonder Menu items. #1491 @tfrijsewijk

@MichielDHVD De header zonder menu items is niet bedoeld voor de Stelselcatalogus maar voor VDK.

**Comment by tfrijsewijk** [comment]
OK! Dus dan moeten we die itemClick support gaan implementeren. Wanneer heb je het nodig?

cc: @MichielDHVD @gofix

**Comment by kad-orhung** [comment]
Ik ga zo over 10 miuten even een kop koffie halen. Is het dan klaar? 😛 

Ik heb het nu in een aparte story staan. Onze nieuwe sprint start vanmiddag en als je het in de komende twee weken klaar is dan kunnen we deze story ook meteen meenemen in de planning.

**Comment by MichielDHVD** [comment]
Ik neem deze ticket mee en we nemen het donderdag door.

**Comment by tfrijsewijk** [comment]
@MichielDHVD Ik heb #1525 gemaakt en ben zo vrij geweest 'm in aankomende milestone te plaatsen. Wil jij de planning/administratie vanaf hier overnemen?

**Comment by MichielDHVD** [comment]
@tfrijsewijk Ik neem het over.

**Comment by MichielDHVD** [comment]
Dit issue is opgelost in https://github.com/dso-toolkit/dso-toolkit/issues/1525 daarmee is dit issue gesloten
