### ISSUE TITLE
Stappenteller in Koppen

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#153]
<img width="619" alt="screen shot 2018-07-12 at 14 42 39" src="https://user-images.githubusercontent.com/36912722/42633830-e965b108-85e1-11e8-8288-a25a78a85006.png">

Het verzoek is dit element. Wat dus eigenlijk op vele pagina's standaard zal terugkomen.

**Comment by PieterVerheij** [comment]
@MichielDHVD de lijnkleur #7d9886 kom ik verder niet tegen. Klopt het dat dat een nieuwe kleur is?

**Comment by MichielDHVD** [comment]
Dat klopt het is een kleur die niet eerder is gebruikt. 

Maar net als de lijn bij de accordeon die de kleur #D3DDD6 heeft (Staat ook niet in de toolkit). Hoeft deze geen prominente plek te krijgen in het keuren palet.  

#7d9886 is een percentage van #275937

Er zijn een aantal vaste kleuren die we developers aan willen bieden. Verder is vanuit communicatie aangegeven  dat tinten in percentages van #39870c en #275937 zijn toegestaan.

**Comment by tfrijsewijk** [comment]
Uitgekomen in `3.1.0-alpha.1`: https://www.dso-toolkit.nl/3.1.0-alpha.1/components/detail/steps.html

**Comment by MichielDHVD** [comment]
De lijn onder de h2 en stappen teller komt niet overeen met het ontwerp. Heeft nu de kleur #39870c deze is #7d9886 in het ontwerp .  

Deze zit ik nog even terug naar in progress

**Comment by MichielDHVD** [comment]
Ik zie nog een fout. De h2 die erin zit hoort standaard de kleur #275937 hebben. Deze is nu #39870c 

Ik zie nu ook waar de verwarring is ontstaan. De kleur voor stap 6/6 is anders dan de h2. 

De h2 is #275937 en de stappen teller is #39870c 

Bij typography https://dso-toolkit.nl/3.1.0-alpha.4/docs/typography.html kun je ook terug vinden welke kleuren bij welke grootte header zijn gegeven. Deze zijn altijd leidend.

**Comment by tfrijsewijk** [comment]
@PieterVerheij Fix jij die kleurtjes?

**Comment by tfrijsewijk** [comment]
Laatste fix zit in `3.1.0-beta.0`: https://www.dso-toolkit.nl/3.1.0-beta.0/components/detail/steps.html

PS: zou dit component niet beter staan onder "Indicatoren" ipv "Navigatie" ?

**Comment by MichielDHVD** [comment]
Gezien en verplaatst naar done
