### ISSUE TITLE
Correctie alt attributen in img tags voor whitebox en tile

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#1540]
Waar
Whitebox component

Aanleiding
De icoontjes in whitebox zijn img tags zonder alt tags.

Gebruikersimpact
Beperkt: op het referentie platform lijkt het geen problemen te geven maar in andere omstandigheden zijn problemen wel mogelijk.

Werkzaamheden
Dit zijn decoratieve plaatjes, dus alt="" meegeven.

**Comment by MichielDHVD** [comment]
@timveld Je kunt deze testen. Ik heb een lijstje met links in deze comment gezet. Waar de whitebox en tiles(voormalig whitebox-small) voorkomen. 

Te testen links: 
https://dso-toolkit.nl/_1540-Whitebox-invalid-html-door-imgtag-zonder-alt/components/detail/tile.html
https://dso-toolkit.nl/_1540-Whitebox-invalid-html-door-imgtag-zonder-alt/components/detail/whitebox.html
https://dso-toolkit.nl/_1540-Whitebox-invalid-html-door-imgtag-zonder-alt/components/detail/row-equal-heights.html
https://dso-toolkit.nl/_1540-Whitebox-invalid-html-door-imgtag-zonder-alt/components/detail/homepage.html

**Comment by timveld** [comment]
Zie dat de img een lege alt heeft, dus lijkt me prima. Is verder weinig aan te testen omdat het een validatiefout is (die in dit geval geen invloed heeft op wat NVDA voorleest). Kan wat mij betreft release in zo.
