### ISSUE TITLE
Toegankelijkheidsissues met tooltip en toggletip

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#1548]
In https://github.com/dso-toolkit/dso-toolkit/issues/1480 is naar voren gekomen dat:

- De tekst van een tooltip IN een button nu door een screenreaders wordt voorgelezen, hetgeen een zinloze dubbeling oplevert met de sr-only of leesbare buttontekst
- Toggletips soms niet met met het toetsenbord focusable zijn

Wijzigingen:
- `aria-hidden` kunnen instellen voor dso-tooltip (NB niet voor dso-toggletip)
- verwerken in voorbeelden en documentatie
- `role="tooltip"` eraf (dan hoeft `aria-describedby` ook niet meer)
- `aria-expanded` van de button laten wijzigen bij in/uitklappen van tooltip in toggletip
- focus-doorzet introduceren om focus op toggletip door te zetten naar de button (zodat `tabindex="-1"` weg kan)

~~Verder, verwijderen we het CSS component voor tooltip, die gaat nooit ingezet worden.~~

**Comment by gofix** [comment]
`aria-expanded` van de button laten wijzigen bij in/uitklappen van tooltip in toggletip -> dat lijkt toch wel gewoon al goed te werken

**Comment by gofix** [comment]
Inmiddels opgelost/aangepast:
- `role="tooltip"` verwijderd;
- `<dso-tooltip>` kan attribuut `descriptive` krijgen, alleen dan wordt op de tekstballon _niet_ `aria-hidden="true"` gezet;
- de `<dso-toolitp>` die gemaakt wordt door de `<dso-toggletip>` is hoe dan ook `descriptive`;
- `tabindex="-1"` verwijderd van de `<dso-toggletip>`, zodat deze met het toetsenbord gefocust kan worden;

**Comment by gofix** [comment]
Er kan getest worden @MichielDHVD 
https://css.dso-toolkit.nl/_1548-toegankelijkheidsissues-met-tooltip-en-toggletip/?path=/story/tooltip--tooltip
-> in het css component zetten we standaard nu `aria-hidden="true"`
Web component, tooltip:
https://core.dso-toolkit.nl/_1548-toegankelijkheidsissues-met-tooltip-en-toggletip/?path=/story/tooltip--as-child
- > eventueel zet je 'm op descriptive, dan gaat de  `aria-hidden="true"` eraf.
https://core.dso-toolkit.nl/_1548-toegankelijkheidsissues-met-tooltip-en-toggletip/?path=/story/toggletip--toggletip
-> daarin is de tooltip hoe dan ook 'descriptive'

**Comment by MichielDHVD** [comment]
Prima, ik ga er vandaag nog proberen naar te kijken. Anders geef ik er morgen een ok op.

**Comment by MichielDHVD** [comment]
Getest en ok. Doorzetten. 

Verschillende versies van toggletip en tooltip zijn goed te bedienen met het toetsenbord. aria-labels en teksten zijn nu ook consistent.
