### ISSUE TITLE
Modal wordt verkeerd gecentreerd bij een lange pagina. 

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#155]
Als er een lange pagina is wordt het model in het het verticale midden van de lengte van de gehele pagina gezet. En niet in het midden van het browser scherm.

Dit zorgt ervoor dat bij een extreem lange pagina de Modal soms niet zichtbaar is tenzij je naar beneden scrolled. 

Beste zou zijn dat modal centreerd word verticaal en horizontaal in de viewport. 

Misschien is het handig deze te combineren met https://github.com/dso-toolkit/dso-toolkit/issues/151

**Comment by tfrijsewijk** [comment]
Dit krijg ik niet gereproduceerd: https://www.dso-toolkit.nl/2.0.0/components/preview/modal--modal.html

Is de implementatie correct? Zelfs als ik van class `dso-modal-open` van de `body` verwijder (en dus kan scrollen) staat de modal netjes in het midden.

Bij een correct geimplementeerde modal zou je niet eens _kunnen_ scrollen

**Comment by tfrijsewijk** [comment]
Overigens heb ik wel een fout in IE11 gevonden: De modal lijnt altijd links uit. Ik heb dit opgelost

**Comment by MichielDHVD** [comment]
Ook met developer besproken. Deze kon het niet meer vinden en reproduceren. 

Hoe moet deze naar done of hoe moet dit in het systeem worden verwerkt?
