### ISSUE TITLE
Styling <dso-viewer-grid>

### ISSUE THREAD

**Issue by krechj** [dso-toolkit/dso-toolkit#1555]
Bij de implementatie van Viewer-grid lopen we tegen een paar styling issues aan. Standaard wordt er een gelockte scrollbalk getoond ook al is er niets te scrollen (op class main, zie afbeelding).

Bij het verbergen van die scrollbalk wordt ook een padding zichtbaar die we eerst niet hadden (op class dso-map-panel, zie afbeelding2).

![afbeelding](https://user-images.githubusercontent.com/37870677/168073365-0c3270e3-a96f-41a5-bf0c-07e88a63d644.jpg)
![afbeelding2](https://user-images.githubusercontent.com/37870677/168073382-90a7179c-483b-4c15-896a-65729c858c72.jpg)

**Comment by tfrijsewijk** [comment]
cc @LiesbethVorst

**Comment by LiesbethVorst** [comment]
@krechj  die scrollbar is inderdaad niet zo mooi, maar dat was de beste optie.

**Comment by MichielDHVD** [comment]
Dit issue wordt gesloten. De padding is een bewust keuze van ux/toolkit omdat we niet kunnen ontsnappen aan scrollbalken. De padding is nodig om de paneel kleiner/groter knoppen wat adem ruimte te geven.
