### ISSUE TITLE
Viewer Grid: Initiële breedte van het linkerpaneel "main" instelbaar

### ISSUE THREAD

**Issue by krechj** [dso-toolkit/dso-toolkit#1556]
Als **Viewer Regels op de Kaart** wil ik de default breedte (small | medium | large) van het linkerpaneel kunnen setten in de code. 
**Idee:**
Property binding waarbij we de mainSize property kunnen setten.  
`<dso-viewer-grid [mainSize]="defaultSize()" (mainSizeChange)="updateMap($event)">`

**Comment by tfrijsewijk** [comment]
We kunnen het ook stateless maken, dan is de applicatie verantwoordelijk voor zetten van de size. Wat denk je daarvan?

Jouw idee is ook prima: dan hernoem ik de property naar `[initMainSize]`, zodat duidelijk is dat deze property niets meer doet zodra het component is geinitializeerd. Het Viewer Grid Main Size is immers stateful.
