### ISSUE TITLE
Wijziging ondermarges dso-rich-content en highlightbox

### ISSUE THREAD

**Issue by gofix** [dso-toolkit/dso-toolkit#1558]
In de voorbeeldpagina die is gemaakt voor het cardpanel is naar voren gekomen dat aandacht besteed zou moeten worden aan de ondermarge van bepaalde bouwstenen. Betreft dso-rich-content (waarbij nog bepaald moet worden of dat ALTIJD wenselijk is, of alleen op specifieke plekken), en highlightbox (zelfde vraagstuk).

Aanleiding: https://dso-toolkit.nl/master/components/preview/card-panel.html (toegevoegd aan DSO Toolkit met #1544 )

**Comment by gofix** [comment]
Allereerst hebben we de ondermarges van de highlightbox vergroot. Over het algemeen ziet dat er helemaal niet gek uit, sterker nog, persoonlijk vind ik het verticale ritme op veel plekken logischer voelen (zoals besproken @MichielDHVD, @DjangoBlok, @LiesbethVorst)

Zie https://percy.io/dso-toolkit/dso-toolkit/builds/18144467/changed/1017505265

Enige twijfel die ik heb betreft https://dso-toolkit.nl/_1558-ondermarges/components/detail/activiteiten.html waar de search bar in een higlight box staat. Ik kan me voorstellen dat @bramhoosemans dat niet helemaal fraai vindt.

**Comment by bramhoosemans** [comment]
@gofix de ondermarge van de Highlightbox is van 16px verhoogd naar 24px, klopt? Ik heb geen problemen met de voorgestelde wijzingen.

**Comment by MichielDHVD** [comment]
Highlightbox ondermarges ziet er bijna overal inderdaad beter uit. 

Wacht met spanning af hoe we de rich-content gaan omzetten.

**Comment by MichielDHVD** [comment]
Hoe ver dit moet dit ook mee met de release van woensdag? Staat niet in de milestone ?

**Comment by gofix** [comment]
Well, als we kijken naar de meest recente percy screenshots (https://percy.io/dso-toolkit/dso-toolkit/builds/18178141/changed/1019325938) zien we:
- Dat de ruimtes onder alle highlight boxes wat ruimter is (16px -> 24px). Zoals @bramhoosemans al aangeeft is dat alleszins acceptabel
- We zien dat het verwijderen van de vrij specifieke regel `margin-bottom: 0` IN highlightboxes op `> .dso-rich-content > *:last-child` de bevinding in het card panel grootdeels oplost, en weinig bij-effect heeft op andere plekken
- De buttons onderin de highlightbox hebben we in een button row geplaatst (dat is wat deze change breaking maakt)

Als we dit issue veel structureler zouden willen aanpakken, zouden we wellicht toe moeten naar een soort 'verticaal-ritme-register', waarin we alle verticale afstanden tussen alle componenten vastleggen (liefst natuurlijk in groepjes), en die afstanden dan weghalen uit de styling van de componenten zelf. Maar... dat klinkt wel als nogal een stevige exercitie.

Dus: als dit nu acceptabel is, kan het natuurlijk prima mee!

Dus: als jullie de huidige changes

**Comment by bramhoosemans** [comment]
> * We zien dat het verwijderen van de vrij specifieke regel `margin-bottom: 0` IN highlightboxes op `> .dso-rich-content > *:last-child` de bevinding in het card panel grootdeels oplost, en weinig bij-effect heeft op andere plekken

Wat was de originele bevinding hiervoor? Ik zie dat er nu dat paragrafen en buttons 8px extra margin onderin de Highlightbox krijgen wat in veel gevallen leidt tot een onevenwichtig beeld.

> * De buttons onderin de highlightbox hebben we in een button row geplaatst (dat is wat deze change breaking maakt)

Waarom? Dan heb je het over de voorbeelden met meerdere buttons neem ik aan; een enkele button zou toch niet in een `dso-button-row` hoeven te staan? Of wel?

**Comment by gofix** [comment]
Ik ruik het al aankomen: we willen toch vrij specifiek met verticale ruimtes omgaan. Dan is de vraag: gaan we 'all-in' of maken we nu alleen een begin met zo'n verticaal-ruimte-register voor de nu voorkomende gevallen...

**Comment by bramhoosemans** [comment]
> > Wat was de originele bevinding hiervoor
> 
> #1278 Filterblok

Ah gaat het om deze afstanden? Ik vraag me wel af waarom er niet gewoon één `dso-rich-content` div gebruikt wordt.. dan krijg je mooi 16px marge van de paragraaf mee.
<img width="1253" alt="Schermafbeelding 2022-05-24 om 10 54 34" src="https://user-images.githubusercontent.com/598735/169992177-4e176f68-198a-481c-b2c9-622100b5f489.png">

**Comment by gofix** [comment]
> één dso-rich-content div gebruikt wordt.. dan krijg je mooi 16px marge van de paragraaf mee.
Klopt. Dat is ook precies hetgeen @MichielDHVD aanvankelijk had, alleen vind ik dat zelf heel gek. Ik beschouw altijd `.dso-rich-content` als een 'blad' aan een boom, waarin niet nog nieuwe (interactieve) werkvormen komen, zoals in dit geval de search bar. 

En... als het het hier inderdaad voor search bar oplost (en we dat acceptabel vinden), heb je nog steeds de andere highlightboxes met het tile grid, en de dso-context-wrapper.  Als je alles in een dso-rich-content wilt gaan kunnen stoppen, is het hele doel daarvan een beetje weg.

**Comment by LiesbethVorst** [comment]
Ik ben blij met de 8px die ik nu zie in https://dso-toolkit.nl/_1558-ondermarges/components/preview/card-panel.html. 

Daarnaast lijkt een spacing system me een goed plan.

**Comment by DjangoBlok** [comment]
Ja, ik ook!
