### ISSUE TITLE
Tabbladen

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#156]
Voor de project mappen komen er nieuwe onderdelen die moeten ook ontwikkeld gaan worden. 

Hier een afbeelding van de specificaties en een tabblad in context.
 
![tabbladen](https://user-images.githubusercontent.com/36912722/42760172-e4d18542-8909-11e8-8fcd-7bfc5bd047b6.png)

![mijnloket](https://user-images.githubusercontent.com/36912722/42760196-f490e5ae-8909-11e8-8a39-32d08dd03351.jpg)

**Comment by MichielDHVD** [comment]
@tfrijsewijk Op dit moment moeten de developers dit al gaan ontwikkelen. Maar Bootstrap heeft standaard tabbladen dus daar gaan ze mee vooruit. 

Worden op dit moment op alle onderdelen in bootstrap er speciale unieke classes voor gegeven. Of kan bijvoorbeeld bij tabbladen gewoon de standaard klasse definitie gebruikt worden? Verzoek vanuit developers.

**Comment by PieterVerheij** [comment]
We kunnen de tabs stijlen, maar in het voorbeeld staan een 50%/50% verdeling in breedte. Ik neem aan dat bij drie tabs de breedteverdeling 33%-33%-33% wordt, etc. Dat betekent dat we verschillende classes zullen moeten introduceren. Tot hoe ver zullen we gaan? Meer dan tien tabs lijkt mij niet reeel (en gebruiksonvriendelijk).

**Comment by MichielDHVD** [comment]
Nee zeker niet. Laten we voor nu maximaal 10 nemen. Uiteindelijke zullen we in de toekomst het liefst naar scenarios toe willen werken waar geen 10 tabbladen nodig zijn. 

Maar voor nu is dat een prima grens.

**Comment by gofix** [comment]
In hoeverre mogen we `display: flex` gebruiken? Zie https://stackoverflow.com/questions/10551369/how-to-evenly-distribute-menu-items-with-css-when-width-and-quantity-is-not-know, met flex is het gevraagde mogelijk zonder allerlei helperclasses `third`, `sixth` of `has-seven-tabs` oid.

**Comment by gofix** [comment]
https://caniuse.com/#feat=flexbox

**Comment by MichielDHVD** [comment]
Dit heeft veel te maken met implementatie neem ik aan? 

Hier loop ik tegen een muurtje aan qua technische kennis. Is input van developers hiervoor nodig of wie kan je helpen deze vraag te beantwoorden?

**Comment by tfrijsewijk** [comment]
Het laatste bekende is dat de toolkit IE9 moet ondersteunen. Dit is een aantal keer ter sprake geweest, maar uiteindelijk heeft Michael besloten dat het IE9 is.

Flexbox valt dan dus af

**Comment by PieterVerheij** [comment]
@MichielDHVD wat zijn jullie gedachten over hoe het er op mobiel en tablet uit zou moeten zien? Ter illustratie:
![image](https://user-images.githubusercontent.com/25430835/47204316-58469f80-d383-11e8-825d-435837de153f.png)

**Comment by MichielDHVD** [comment]
In de afb staan de tabs niet onder elkaar, ik zie dat de cijfertjes onder het tabje komen. Ik heb moeite om hier een beeld bij te vormen.

**Comment by PieterVerheij** [comment]
Een optie is om de tabbladen een minimale breedte te geven, maar dan zweven de niet actieve tabs een beetje:
![image](https://user-images.githubusercontent.com/25430835/47369770-b1486780-d6e4-11e8-8791-47766cfda198.png)
Een andere optie om ze de volledige breedte te geven:
![image](https://user-images.githubusercontent.com/25430835/47369900-ea80d780-d6e4-11e8-8679-c118a296f9b7.png)
Maar mijn voorkeur gaat uit naar een pill-achtige vormgeving?

**Comment by MichielDHVD** [comment]
![tabbladen 1 select](https://user-images.githubusercontent.com/36912722/48194693-ffe53b00-e34d-11e8-81f4-3b4853fb2b74.png)
![tabbladen 2 select](https://user-images.githubusercontent.com/36912722/48194695-ffe53b00-e34d-11e8-8ffc-8939518a650c.png)

Enigste wat voor mobiel dus moet gebeuren is dus. Een border bottom toevoegen en de afronding op de hoeken wordt. 8px ipv 4px. 

Border: solid 1px 39870C Radius: 8px

**Comment by tfrijsewijk** [comment]
Uitgekomen in `3.1.0-alpha.5`: https://www.dso-toolkit.nl/3.1.0-alpha.5/components/detail/tabs.html

**Comment by MichielDHVD** [comment]
Gezien en verplaats naar done. Ziet er goed uit!
