### ISSUE TITLE
Definition list marge tussen dd + dt's verkleinen naar 8px

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#1565]
Voor Wie*
Alle toepassingen

Waar*
https://www.dso-toolkit.nl/36.1.0/components/detail/definition-list.html
https://css.dso-toolkit.nl/36.1.0/?path=/story/definition-list–default
Voorbeeld implementaties

https://www.dso-toolkit.nl/36.1.0/components/detail/omgevingsoverleg.html
https://www.dso-toolkit.nl/36.1.0/components/detail/project-overzicht.html
https://www.dso-toolkit.nl/36.1.0/components/detail/verzoek-detail.html
Precondities*
 

Aanleiding
Voortkomend uit https://github.com/dso-toolkit/dso-toolkit/pull/1547 de bevinding dat de ruimte tussen de items (16px) te groot is en gehalveerd mag worden (8px) voor een rustiger beeld.

Werkzaamheden
Marges verkleinen van 16px naar 8px.
Dit geldt voor alle type definition lists (default, dso-vertical, dso-columns, dso-bordered)
Ontwerp
Zie bijgevoegde schermen.

Testen
 

Acceptatiecriteria

**Comment by PieterVerheij** [comment]
@MichielDHVD moet de margin-bottom van de `<dl>` ook 8px worden (is nu 16px).

In onderstaand voorbeeld is dat al gedaan, anders staat de lijn verticaal gezein niet in het midden:
![image](https://user-images.githubusercontent.com/25430835/173364376-8d32c300-0102-4781-80cd-7406bc241fad.png)

**Comment by bramhoosemans** [comment]
> @bramhoosemans @LiesbethVorst Even een stap terug tov van mijn opmerking van 13 juni.
> 
> Door de aanpassing van de ruimte IN de definition list, staat de lijn TUSSEN twee definition lists niet meer in het midden. Wat doen we?
> 
> * laten as is?
> * of de ruimte boven de lijn kleiner maken
> * of de ruimte onder de lijn groter maken

Het mooiste is wat mij betreft de ruimte onder de lijn groter te maken, zodat de de scheiding tussen twee definition lists (nog) duidelijker wordt. Een `hr` in Rich Content heeft ook 16px boven en onder.
 
> Persoonlijk vind ik het nu op de pagina 'Begrippen' in een definition list met borders wel wat krap geworden?

Daar heb ik @LiesbethVorst eerder al op gewezen, maar is toen geaccepteerd. Zo houden dus.

**Comment by LiesbethVorst** [comment]
Klopt dat de aanpassing best veel effect zal hebben op de pagina Begrippen. Ik verwacht dat het even wennen is maar ook het voordeel heeft dat de pagina's minder lang worden.
