### ISSUE TITLE
Projectmap Row + Kralenketting

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#157]
Hier moeten we nog even overleggen wat het handigste is. Zijn dit twee losse componenten of een gezamenlijke component. Anders kan het moeilijk worden met de uitlijning van de twee verschillende elementen. 

De specificaties. 

![kralenketting plus project map row](https://user-images.githubusercontent.com/36912722/42761205-221535d6-890d-11e8-975b-dce4c88d4e25.png)

En het geheel in context

![mijnloket](https://user-images.githubusercontent.com/36912722/42761215-2a8bafe2-890d-11e8-867e-32a55fffe3fe.jpg)

Ik heb wat maten aan moeten passen omdat het anders niet in het 8px grid past. Dit wordt nog overlegd met Antoinette. Die is momenteel op vakantie.

**Comment by PieterVerheij** [comment]
Hi @MichielDHVD , wat gebeurt er als je op Openen klikt? Ga je dan naar een volgende pagina, of klapt hij uit? Moeten we daar in het laatste geval rekening mee houden?

**Comment by MichielDHVD** [comment]
@PieterVerheij Bij openen ga je naar een andere locatie.  

Ik voeg nog even een afbeelding toe over wat er onder Verzonden staat. Dat helpt bij de beeldvorming. Want bij de kralenketting onder het kopje Voorbereiden staat dus geen accordeon. 

Bij verzonden is dit wel het geval. 

![06_mijn-loket project pagina - meer activiteiten](https://user-images.githubusercontent.com/36912722/46596038-4f301580-cadb-11e8-9d7e-1b845fe78262.jpg)

**Comment by tfrijsewijk** [comment]
Ik heb 'm voor nu van de 3.1.0 milestone afgehaald
