### ISSUE TITLE
Pagina's op https://dso-toolkit.nl/2.0.0/ scrollen niet ver genoeg

### ISSUE THREAD

**Issue by milovanderlinden** [dso-toolkit/dso-toolkit#158]
Even gechecked, de onderdelen _body_ en _frame_ krijgen vanuit `default.css` een 100% height. Wanneer je die weghaalt werkt de site wel goed.

**Comment by tfrijsewijk** [comment]
Ik krijg het niet gereproduceerd. Met welke browser ervaar je dit?

Overigens, heb je gezien dat een componenten pagina uit 3 onderdelen bestaat: het menu, het component en een rij tabbladen met informatie?

![image](https://user-images.githubusercontent.com/9696261/43510827-1c61270a-9577-11e8-86ec-636f0f4416ec.png)

Ik kan tussen alle drie de onderdelen goed scrollen en zie alle informatie. Deze 3 onderdelen zijn resizable, misschien dat het tabblad onderdeel helemaal naar beneden staat?

**Comment by tfrijsewijk** [comment]
Vanwege geen reactie sluit ik het ticket. Voel je vrij om het ticket weer te openen indien nodig
