### ISSUE TITLE
Shopping Cart 'non-collapsable' variant toevoegen

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#1581]
**Aanleiding**
In https://github.com/dso-toolkit/dso-toolkit/issues/1510 hebben we een variant gemist. De Shopping Cart moet ook de optie 'alles verwijderen' kunnen tonen bij de niet-inklapbare variant. Oftewel "U heeft x activiteiten gekozen" met actie 'alles verwijderen', maar zonder pijltje open/dichtklappen.

**Werkzaamheden**
- In Storybook een story 'non-collapsable' (en daaruit voortkomend een control 'collapsable'), zonder chevron maar met prullenbakje.
- In Fractal een 'non-collabsable', zonder chevron maar met prullenbakje.
- Aantal activiteiten voor variant 'SUBITEMS WITH WARNING' veranderen in '2' (alleen de ouders tellen).

**Ontwerp**
![162186852-4f36478b-a8a9-4eb2-9d15-a08eecf07f5e (1)](https://user-images.githubusercontent.com/598735/170995923-e58b6243-1bd8-4c07-92c0-10ee400bd10a.png)
![170989494-48a4e71f-d943-4b94-a7cf-3a6a62544577](https://user-images.githubusercontent.com/598735/170995951-c6a1fd1e-da42-45b4-9c73-1f6d3dfb285e.png)

**Comment by PieterVerheij** [comment]
@bramhoosemans 

> Aantal activiteiten voor variant 'SUBITEMS WITH WARNING' veranderen in '2' (alleen de ouders tellen).

Er is speciaal een functie `countSubitems` om de subitems te tellen, ervan uitgaande dat als er subitems zijn, het nivo erboven de categorie is die dan niet geteld wordt. Zeker weten dat dit aangepast moet worden, het is namelijk een ingrijpende aanpassing?

**Comment by bramhoosemans** [comment]
@PieterVerheij Ik zou nu ook zeker geen functies van het component wijzigen; er zijn geen signalen dat het nu verkeerd geïmplementeerd is. In mijn beleving ging het puur over een label-tekst aanpassing in Fractal...

Voor de beeldvorming, het component Shopping Cart wordt op twee plekken ingezet:

1. Werkzaamheden 
Werkzaamheden kunnen ook relaties hebben met bedrijfstakken, dan ontstaan er subitems en deze tellen allemaal mee. Bijvoorbeeld: 2 bedrijfstakken met daaronder allebei 1 werkzaamheid = "U heeft 4 werkzaamheden gekozen".

2. Activiteiten
Bij activiteiten kan er sprake zijn van hoofdactiviteiten en subactiviteiten. Hierbij tellen we alleen de hoofdactiviteiten. Bijvoorbeeld: 1 hoofdactiviteit met 2 subactiviteiten = "U heeft 1 activiteit gekozen".

In het ontwerp hierboven is dat ook zo toegepast.

**Comment by PieterVerheij** [comment]
Ok, dus we laten het zo in Fractal?

**Comment by tfrijsewijk** [comment]
Alles is markup voorschrift, we bieden geen functionaliteit _aan_ maar we willen benadrukken dat wij bij het ontwikkelen van het component een speciale Fractal Templating function hebben geschreven die uit de data uitrekent hoeveel werkzaamheden er zijn. Die telt de subjes (dat ding heeft ook `countSubItems`. Voor de markup voorschriften maakt het niet uit, maar we willen dubbelchecken of jij echt wilt dat die functie eruit gesloopt wordt.

**Comment by bramhoosemans** [comment]
@tfrijsewijk @PieterVerheij Tja, ik kan niet terugvinden waarom die erin is gekomen. Als ik in de Vergunningcheck en Aanvragen (gebruikerstoepassingen) kijk wordt het Shopping Cart component ingezet zoals hierboven beschreven.

In het Fractal voorbeeld staat 'Activiteiten' erboven en zouden we dus de hoofdactiviteiten juist moeten tellen.

Dan kom ik tot de conclusie dat de functie `countSubItems` eruit kan.

**Comment by tfrijsewijk** [comment]
Prima! Dank voor bevestigen.

**Comment by gofix** [comment]
Ik mis in de fractal voorbeelden nog dit:
![image](https://user-images.githubusercontent.com/2689559/172705473-2a7d4f4c-4417-4ff4-a06e-dc630c701293.png)

Maar goed, dat stond ook niet in de werkzaamheden. In Storybook zit'ie wel.
