### ISSUE TITLE
Autosuggest loading state toevoegen

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#1582]
**Werkzaamheden**
- Loading state toevoegen aan Autosuggest component.
- Default tekst "Een moment geduld alstublieft.", deze moet overschreven kunnen worden door implementatoren.
- Oplossingsrichting afstemmen met ontwikkelaars PR12 ivm bevinding.

**Ontwerp**
![zoeksuggesties-loading-state](https://user-images.githubusercontent.com/598735/171019231-0b60cf3d-cf73-421d-8f74-fc9f362e35a8.png)

**Comment by bramhoosemans** [comment]
Hmm.. nu ik er in detail naar kijk zie ik dat de afstanden van de 'normale' suggesties ook afwijken met ontwerp.

Wat ik in ontwerp van de had toegepast is dezelfde uitlijning als het icoon + tekst in de Search Bar. Deze loading state van de suggesties verschijnen er direct onder, dus mooi om het daarmee uit te lijnen.

![zoeksuggesties-loading-state-measurements](https://user-images.githubusercontent.com/598735/171569295-e7207084-3384-4eb2-a4fe-028c9cd56d53.png)

**Comment by gofix** [comment]
Ok, pakken we dat als zodanig op.
