### ISSUE TITLE
Woordafbreking alleen als deze niet op een eigen regel past

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#1585]
Zet 'overflow-wrap: break-word;' op de body.
https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap

**Comment by PieterVerheij** [comment]
![image](https://user-images.githubusercontent.com/25430835/174774004-ead8df56-ab37-4c3a-aa3a-43ed69827192.png)
Zie https://www.dso-toolkit.nl/_1585-Woordafbreking-alleen-als-deze-niet-op-een-eigen-regel-past/components/detail/rich-content.html op smalle viewport.
