### ISSUE TITLE
Date picker inputveld: aanpassen datum, en plakken/selecteren in Safari MacOS

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#1597]
1. Het aanpassen van een reeds ingevulde datum in het inputveld (dus zonder de datepicker te gebruiken) is lastig voor 'gewone' gebruikers, en vrijwel onmogelijk met alleen screenreader.
> Reproduceren: zet cursor in het veld, en ga met pijltoetsen naar de datum, bijvoorbeeld 15-06-2022. zet de cursor achter de 5, en wis de 5 met de backspace. 15 is nu 01, en de cursor staat achter 2022. ga opnieuw terug naar de dag (nu 01), en wis de 01 met de backspace. dit werkt nu wel. type een nieuwe datum (bijv. 16); nu is de datum weer 01, en de 6 staat achter 2022: 01-06-20226.  Let op: dit probleem speelt ook bij de maand (maar dan net even anders qua backspace-gedrag).
2. Plakken van een elders gecopieerde datum in het inputveld werkt niet in Safari op MacOS.
> Reproduceren: Copieer een datum (bijv. 16-06-2022); in Safari/MacOS, plaats cursor in het veld (of focus het veld), en plak de datum erin. Er gebeurt niets. Rechtsklik + 'plak' werkt wel, cmd + v niet.
3. selecteren van datum werkt niet correct in Safari/MacOS.
> Reproduceren: plaats de cursor in het ingevulde inputveld, en selecteer de inhoud met cmd+a. er vindt geen selectie plaats. Selecteren dmv focus werkt wel.

Omdat deze 'quirks' mogelijk gerelateerd zijn, heb ik ze in één issue ondergebracht. Liever gesplitst? let me know!

NB: nr 3 is wat mij betreft minder urgent; als het kan worden gefixt samen met de rest, dan helemaal prima. als er een krachtsinspanning nodig is, dan wat mij betreft apart zetten en opschuiven.

**Comment by LVMartin** [comment]
Bevinding vanuit PR12 na test van release 4.1.0:

Reproduceren: zet cursor in het veld, en ga met pijltoetsen naar de datum, bijvoorbeeld 15-06-2022. zet de cursor achter de 5, en wis de 5 met de backspace. 15 is nu 01, en de cursor staat achter 2022. ga opnieuw terug naar de dag (nu 01), en wis de 01 met de backspace. dit werkt nu wel. type een nieuwe datum (bijv. 16); nu is de datum weer 01, en de 6 staat achter 2022: 01-06-20226. Let op: dit probleem speelt ook bij de maand (maar dan net even anders qua backspace-gedrag).

**Comment by tfrijsewijk** [comment]
Kunnen jullie dit ook op https://core.dso-toolkit.nl/40.1.0/?path=/story/date-picker--default reproduceren? In mijn omgeving (Win10/Chrome103) kan ik jouw bevinding niet reproduceren.

@svrijsewijk Heb je gezien dat bij het React component in de React Storybook de Actions niet worden geregistreerd? https://react.dso-toolkit.nl/40.1.0/?path=/story/date-picker--default Ik begrijp alleen nog niet waarom, ik maak er een issue van
