### ISSUE TITLE
Content-security-policy issue met SVG spritesheet voor iconen

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#1600]
**Aanleiding**
Melding:
Wij hebben een ContentSecurityPolicy in onze portalen waar wij voor resources (images, styles, scripts, iframes ea) definieren waar die vandaan mogen komen. Wij hebben dat redelijk strict opgesteld voor de meeste zaken, maar voor style lopen tegen een probleem aan. Wij gebruiken het bestand ‘dso-icons.svg’ uit de toolkit, wat eigenlijk een xml bestand is, daar staat <style> gedefinieerd per icon. Chrome ziet dit als inline style en blokkeert dit tenzij wij unsafe-inline toelaten in onze CSP (wat wij dus eigenlijk niet meer willen).

In /packages/css maken we dso-icons.svg met een routine in gulpfile.js. Deze routine leest alle icons en varianten in /packages/sources/src/icons in en maakt daar een spritesheet van. Per icon bijbehorende varianten wordt onderstaande gemaakt:

```

<style type="text/css">
  #img-chevron-right + g {
    color: #39870c;
  }  #img-chevron-right-scampi + g {
    color: #676cb0;
  }  #img-chevron-right-grijs50 + g {
    color: #7f7f7f;
  }  #img-chevron-right-grijs90 + g {
    color: #191919;
  }
</style>
<view id="img-chevron-right" viewBox="1181 0 32 32"/>
<g transform="translate(1181)">
  <use href="#chevron-right"/>
</g>
<view id="img-chevron-right-scampi" viewBox="1223 0 32 32"/>
<g transform="translate(1223)">
  <use href="#chevron-right"/>
</g>
<view id="img-chevron-right-grijs50" viewBox="1265 0 32 32"/>
<g transform="translate(1265)">
  <use href="#chevron-right"/>
</g>
<view id="img-chevron-right-grijs90" viewBox="1307 0 32 32"/>
<g transform="translate(1307)">
  <use href="#chevron-right"/>
</g>
<symbol id="chevron-right" viewBox="0 0 24 24">
  <path fill="currentColor" d="M9 19a.93.93 0 0 1-.67-.29 1 1 0 0 1 0-1.42l5-5.29-5-5.29a1 1 0 0 1 0-1.42.93.93 0 0 1 1.35 0L16 12l-6.38 6.71A.93.93 0 0 1 9 19Z"/>
</symbol> 
```

Oplossing: 
De color-styling die in <style> zit gaan we direct in een fill van het bijbehorende element plaatsen:

```
<view id="img-chevron-right" viewBox="1181 0 32 32"/>
<g transform="translate(1181)">
  <svg viewBox="0 0 24 24">
    <path fill="#39870c" d="M9 19a.93.93 0 0 1-.67-.29 1 1 0 0 1 0-1.42l5-5.29-5-5.29a1 1 0 0 1 0-1.42.93.93 0 0 1 1.35 0L16 12l-6.38 6.71A.93.93 0 0 1 9 19Z"/>
  </svg>
</g>
<view id="img-chevron-right-scampi" viewBox="1223 0 32 32"/>
<g transform="translate(1223)">
  <svg viewBox="0 0 24 24">
    <path fill="#676cb0" d="M9 19a.93.93 0 0 1-.67-.29 1 1 0 0 1 0-1.42l5-5.29-5-5.29a1 1 0 0 1 0-1.42.93.93 0 0 1 1.35 0L16 12l-6.38 6.71A.93.93 0 0 1 9 19Z"/>
  </svg>
</g>
<view id="img-chevron-right-grijs50" viewBox="1265 0 32 32"/>
<g transform="translate(1265)">
  <svg viewBox="0 0 24 24">
    <path fill="#7f7f7f" d="M9 19a.93.93 0 0 1-.67-.29 1 1 0 0 1 0-1.42l5-5.29-5-5.29a1 1 0 0 1 0-1.42.93.93 0 0 1 1.35 0L16 12l-6.38 6.71A.93.93 0 0 1 9 19Z"/>
  </svg>
</g>
<view id="img-chevron-right-grijs90" viewBox="1307 0 32 32"/>
<g transform="translate(1307)">
  <svg viewBox="0 0 24 24">
    <path fill="#191919" d="M9 19a.93.93 0 0 1-.67-.29 1 1 0 0 1 0-1.42l5-5.29-5-5.29a1 1 0 0 1 0-1.42.93.93 0 0 1 1.35 0L16 12l-6.38 6.71A.93.93 0 0 1 9 19Z"/>
  </svg>
</g> 
```

**Werkzaamheden**
aanpassen /packages/css/gulpfile.js.

- Automatisch testen gaat met Percy.
- Styling wordt alleen overgezet voor elementen met fill="currentColor" waarbij het in de styling alleen een om de color property gaat. Bij andere properties faalt het compileren met een buildfout.

**Comment by tfrijsewijk** [comment]
@MichielDHVD Dit is gemerged en komt met de release van woensdag mee. De CSP beheerders zullen met de diverse applicaties tot een datum moeten komen wanneer ze geupdatet MOETEN zijn naar (tenminste) aanstaande release.
