### ISSUE TITLE
initialMainSize prop-binding wordt bij 2de rendering niet opgepakt

### ISSUE THREAD

**Issue by krechj** [dso-toolkit/dso-toolkit#1601]
De size van het linkerpaneel wordt vergeten de **tweede** keer dat ie wordt gerendered; ondanks het setten van de initialMainSize property. Zie gif voor een voorbeeld.

We implementeren viewer-grid maar op één plek in onze code:
```
<dso-viewer-grid
  [initialMainSize]="'medium'"
  (onMainSizeChange)="updateMap()"
```
![viewerGrid2](https://user-images.githubusercontent.com/37870677/174078844-2b55793a-5e43-4569-b19f-bc6578ebed11.gif)

**Comment by tfrijsewijk** [comment]
Hi @krechj 👋 

Ik kan het reproduceren met een simpele toggle button en een `*ngIf`.

Maar waarom het zo werkt? Geen idee. Ik heb een debugbuild gedraad waarin het VieweGrid bomvol debugs staat. Zodra het element voor een tweede keer wordt gerendered, is alles weg. Het component kan op geen enkele manier meer herstellen.

Ik vermoed dat dit komt hoe Angular HTML elementen opnieuw inzet.

Maar gelukkig heb ik wel een oplossing gevonden. Kan je het eens proberen met _attribute binding_ ipv _property binding_ ?

```html
<!-- Property binding -->
<dso-viewer-grid [initialMainSize]="'medium'">

<!-- Attribute binding -->
<dso-viewer-grid initial-main-size="medium">
```

Bij mij werkte dit. Overigens vind ik dit wel een zorgwekkende situatie: Nu komen we ermee weg omdat het een `string` is, die ook met een attribuut gezet kan worden. Stencil werkt met een concept `Prop` wat zowel via een attribuut als via een property gezet kan worden.

Het lijkt erop dat Angular het element dat bij het component hoort opnieuw inzet (recycled) maar er dan vanuit gaat dat de properties nog zijn gezet. Maar Stencil (ons Web Component framework) ruimt het component netjes op.

Voor React genereren we React bindings, voor Angular kan dat ook. Ik ga hier nog wat onderzoek naar doen en kijken of het probleem is opgelost als er met Angular gegenereerde componenten wordt gewerkt. Hier is al een issue van: #915.

Laat je weten of de oplossing toereikend is? Dan sluiten we dit issue.

**Comment by tfrijsewijk** [comment]
cc @benheldoorn: Bizar verhaal hierboven..

**Comment by krechj** [comment]
Hoi @tfrijsewijk,
Je oplossing werkt! Issue mag gesloten worden. Bedankt!
