### ISSUE TITLE
Angular support

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#1604]
Nav. #1601 heb ik het gevoel dat we geen grip op de Angular support hebben.

De fix in bovenstaand issue is geen fix maar een pleister. We komen er nu mee weg omdat de gewenste value een `string` is. Als het iets anders is, dan hangen we. Omdat dit mij zorgen maakt heb ik mij verdiept in de Angular bindings van Stencil.

* https://stenciljs.com/docs/framework-bindings
* https://stenciljs.com/docs/angular

Mijn aandacht ging uit naar "Web Component behoudt property niet na eerste render". De originele melding ging over een situatie met de router, maar ik heb het kunnen reproduceren met een simpele `*ngIf`:

```html
<button type="button" (click)="showGrid = !showGrid">Toggle ({{ showGrid }})</button>
<dso-viewer-grid [initialMainSize]="'medium'" *ngIf="showGrid"></dso-viewer-grid>
```

De lifecycle is als volgt:
* `showGrid = true`
* Component rendered keurig op `medium`
* Sizing buttons werken
* Toggle button (`showGrid = false`)
* Viewer grid is weg
* Toggle button (`showGrid = true`)
* Viewer grid toont met `size === large`, dat is de default als er geen initial is gegeven.

Daarnaast geven de Angular bindings nog iets bijzonders. Angular v14 support is onbekend? En als er met Angular bindings wordt gewerkt lijkt het erop alsof er niet met lokale symlinks gewerkt mag worden. Vanuit een monorepo (waar het dus bol van de symlinks staat) angular bindings onderhouden klinkt als een uitdaging. Overigens kan dit zomaar een Windows issue zijn..

**Comment by tfrijsewijk** [comment]
OK, ik ben een heel eind en ik kan gelukkig zeggen dat het allemaal meevalt: Er kwam in één keer heel veel samen waardoor het vreselijk _leek_.

* De bug in #1601 is een bug in onze code die vanwege de inner working van Angular laat zien. Ik kan 'm met VanillaJS ook reproduceren;
* Zodra bovenstaande bug is opgelost werken de Angular bindings ook (v13 en v14);
* Angular bindings werken NIET in een Yarn Workspace, het linken laat "iets" in Angular klappen. In versie 14 is zijn er meer (en heftigere) foutmeldingen. Zodra de Angular bindings als volwaardige package worden ingevlogen is er niets aan de hand;
* De Angular bindings generator heeft nog een bug waarmee Interfaces onder de verkeerde noemer worden geimporteerd waarmee de TypeScript compiler faalt. Handmatige correcties in de typings lossen het probleem op. Hier moet ik nog naar kijken en eventueel een bug voor aanmaken in de Stencil repository;
* Los van alles: De typings worden by default niet geexporteerd, maar dit kan aangezet worden met een ["tussen type definitie"](https://stenciljs.com/docs/angular#why-aren-t-my-custom-interfaces-exported-from-within-the-index-d-ts-file);

Ik vul dit comment zo nog verder aan, maar het brandje lijkt bijna geblust.

**Comment by gofix** [comment]
Phew (whipes some sweat off).
