### ISSUE TITLE
dso-header logout link verrijken met `logoutClick` event

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#1605]
`<dso-header />` heeft een property `logout-url` waarmee de logout link in de header wordt gevuld. Maar die pagina bestaat helemaal niet. In plaats daarvan moet er een popup worden getoond waarmee om bevestiging wordt gevraagd.

In plaats van dat het component een `logout-url` meekrijgt moet het een event `logoutClick` emitten. De afnemer neemt de rest van de flow voor zijn rekening.

**Comment by tfrijsewijk** [comment]
cc: @yktoo, @MichielDHVD en @hansgrimm.

**Comment by yktoo** [comment]
Ik vind het persoonlijk prima om de `logout-url` te behouden (en een extra event bij te voegen), misschien is het voor iemand een geldige usecase.

**Comment by yktoo** [comment]
Hoi @tfrijsewijk, momenteel wordt het `Uitloggen` item alleen getoond als er ook een `logoutUrl` is gezet. Deze URL is echter nutteloos als je van de click-event gebruikmaakt (we hebben er namelijk geen), dus je moet een dummy-URL daarin plakken. Kan het niet anders?

**Comment by tfrijsewijk** [comment]
@yktoo Lijkt mij prima! Ik heb #1662 voor je aangemaakt, laten we daar verder gaan.
