### ISSUE TITLE
In Ozon Content krijgt eerste `p` margin-top: 8px;

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#1620]
Originele melding van Linda Vels (https://dso-toolkit.slack.com/archives/CB417GQBC/p1655715796443089):

> Met de update naar een hogere toolkit versie (34.2.1) hebben we het volgende probleem met de uitlijning binnen dso-ozon-content. Er wordt aan de p tag een margin-top en -bottom meegegeven van 8px, zie onderstaande voorbeelden.
> 
> ![image](https://user-images.githubusercontent.com/9696261/175327441-06f3bcbd-25c4-4a2e-b13d-61ee4d0d4ba3.png)
> 
> ![image](https://user-images.githubusercontent.com/9696261/175327461-57f8211d-24a0-47cd-b3d0-7d92362ff478.png)

Dit komt omdat er sinds `@dso-toolkit/core@>=34` in het Ozon Content component het `<Al>` element wordt gemapt naar `<p>`, waar het voorheen een betekenisloze `<div class="od-Al">` was.

Deze `<p>` staat in het Rich Content component:

```html
<div class="dso-rich-content">
  <p>paragraaf</p>
</div>
```

en krijgt dus keurig een `margin-top: 8px;`.

Tijdens refinement zei ik vrolijk dat we hier wel een fix op kunnen bedenken, iets wat lijkt op `dso-ozon-content .dso-rich-content :first-child { margin-top: 0px; }`, maar ik denk dat dit niet opgaat.. Het Ozon Content component kan natuurlijk ook gewoon worden ingezet om pagina's te vullen. En rijke tekst staat nou eenmaal in een Rich Content component.

Ik denk dat we op een hoger niveau die verticale ruimte moeten besturen. Maar als ik naar de structuur kijk, wordt dit component in een component gebruikt wat niet door de toolkit wordt geleverd (namelijk een Angular component).

Ik ben dus zoekende naar een oplossing die past in de filosofie van de toolkit.. Iemand ideeen? @gofix @hansgrimm

**Comment by DjangoBlok** [comment]
In de viewer wordt die 8 pixel op een hoger niveau gezet op de container waar het cijfertje bij in zit.
Dat Ozon Content component zal naar mijn idee ook altijd gebruikt worden in deze context samen met zijn kop.
Ik vraag me dus af of we er nu rekening mee moeten houden dat hij op een andere manier wordt ingezet (om pagina's te vullen)

**Comment by hansgrimm** [comment]
een <p> moet een marge hebben om hem 'los' te zetten van de elementen eromheen.

Vaak wordt een <p> in de top van de css-cascade voorzien van een standaard margin-top of -bottom om die spacing te regelen.

echter, als een <p> het enige element is binnen een container (bijv. een alert of een tegel), dan is een standaard margin onhandig.

Wat in de praktijk veel beter werkt is een margin-top op de volgende <p>:
p + p  { margin-top: 1 rem; }

Voor de echte daredevils hebben we ook altijd nog de oplossing van mijn vriend en collega Heydon Pickering, de "Lobotomized Owl Selector":

*+ * { margin-top: 1rem; }

Spoiler: doe maar niet

**Comment by hansgrimm** [comment]
@DjangoBlok @LiesbethVorst Gaan we hier nog iets mee doen?

**Comment by DjangoBlok** [comment]
Ik zou de voorkeur hebben om hier wel wat mee te doen. Al mappen we dit specifiek op het Ozon Content component.
@tfrijsewijk Heb jij hier overwegende bezwaren tegen?

**Comment by tfrijsewijk** [comment]
Waar het om gaat is dat het Ozon Content component gebruik maakt van het Rich Content component, maar dat de selector `dso-ozon-content .dso-rich-content` eigenlijk niet klopt: Ozon Content is in wezen ook maar gewoon rich content, waarom zou het daar ineens andere stijling moeten krijgen?

De selector waar in die styling boven en (en onder) weg moet zijn gaat over context die op dit moment buiten de scope van de toolkit ligt. De context bestaat uit componenten die niet door de toolkit wordt geleverd maar maatwerk is.

En misschien is dat het antwoord ook wel: Als afnemers zelf die componenten maken, moeten ze zelf die uitzondering realiseren.

Wat mij betreft sluiten we dit issue.

**Comment by hansgrimm** [comment]
> Waar het om gaat is dat het Ozon Content component gebruik maakt van het Rich Content component, maar dat de selector `dso-ozon-content .dso-rich-content` eigenlijk niet klopt: Ozon Content is in wezen ook maar gewoon rich content, waarom zou het daar ineens andere stijling moeten krijgen?
> 
> De selector waar in die styling boven en (en onder) weg moet zijn gaat over context die op dit moment buiten de scope van de toolkit ligt. De context bestaat uit componenten die niet door de toolkit wordt geleverd maar maatwerk is.
> 
> En misschien is dat het antwoord ook wel: Als afnemers zelf die componenten maken, moeten ze zelf die uitzondering realiseren.
> 
> Wat mij betreft sluiten we dit issue.

Eens. De toolkit is een bron van generieke oplossingen; uitzonderingen worden gemaakt bij implementatie.
