### ISSUE TITLE
Info button staat niet op dezelfde regel als het label over twee regels loopt 

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#1623]
**Waar**
Input https://dso-toolkit.nl/39.0.0/components/detail/group-input.html
Textarea https://dso-toolkit.nl/39.0.0/components/detail/group-textarea.html
Select https://dso-toolkit.nl/39.0.0/components/detail/group-select.html
Static https://dso-toolkit.nl/39.0.0/components/detail/group-static.html
Search bar https://dso-toolkit.nl/39.0.0/components/detail/group-search-bar.html
Files, radio's en checkboxen lijken wel goed te gaan.

**Aanleiding**
Opgevallen op pre-productie omgeving dat de info button in het formulier niet op dezelfde regel staat als het label langer is dat 1 tekstregel. 

**Werkzaamheden**
Zorg dat de info button bij alle formulier componenten, indien het past, op de laatste regel staat van het label.

![image](https://user-images.githubusercontent.com/36912722/175478286-005118d4-b5ba-4547-9b82-5a5eeaaab0eb.png)
![image](https://user-images.githubusercontent.com/36912722/175478314-5cd89bd6-2b9c-49a5-9fba-44325005c713.png)

**Comment by hansgrimm** [comment]
Dit komt doordat het label de css-properties 'display: inline-block' + 'max-width: 100%' heeft. als je het label volplempt met tekst, dan pakt hij de hele breedte van de container, en drukt het volgende element, de 'i'-button naar de volgende regel. Dit kan je "oplossen" door de 'i'-button in het label te plaatsen (= suboptimaal), maar dan wisselt-ie weer stuivertje met het tekstje "verplicht", dat in een ::after staat (dus achter alles, ook de button).
Nog even geen kant-en-klare oplossing, maar wel de oorzaak ;)

**Comment by hansgrimm** [comment]
UPDATE

een smerige CSS-fix: op het label `max-width: calc(100% - 36px);`

**Comment by hansgrimm** [comment]
UPDATE 2

het label `display: inline` geven werkt ook, maar dan moeten we het margin/padding verhaal fixen.

**Comment by daverhelst** [comment]
Met de huidige markup zie ik geen oplossing om het icoon achter de tekst te houden. Zoals @hansgrimm hier boven ook omschrijft zijn er verschillende wegen te bewandelen, die allemaal een flink punt van aandacht hebben, en wat mij betreft geen sluitende oplossingen zijn.

Ik zie wel 2 andere mogelijkheden, maar daar moet iemand een akkoord op geven:

1. We plaatsen een extra `<div class="dso-label-wrapper">` om het label en de button heen. Deze geven we dan de verticale margin en padding die nu op het `<label>` zit, waardoor we het `<label>` wel een `display: inline-block` kunnen geven zodat het icoon achter de tekst blijft staan en de ruimtes tussen de elementen visueel blijven bestaan. Dit vergt dus wel een aanpassing van de markup, en maakt deze change `BREAKING`
2. We besluiten om het icoon niet vlak achter de tekst te plaatsen, en gaan denken over een soort `display: flex` oplossing, waardoor het icoon aan de rechterkant (eventueel met uitlijning aan de bovenkant) zal staan. Dit zal visueel dus wel anders gaan tonen, maar levert geen `BREAKING` change op

@MichielDHVD @hansgrimm @tfrijsewijk Wat is jullie mening?

**Comment by tfrijsewijk** [comment]
Ik denk dat we `label` en `info-button` moeten `display: inline`n. De wens is immers dat de info button als karakter/symbol in het label meedoet. Dat gedrag bestaat alleen bij `inline`.

Alle andere oplossingen zullen het icoon bij meerdere regels rechts laten staan.

Kunnen we de margin/paddings verplaatsen naar het container element `.dso-label-container` en daarmee bij horizontale formulieren de verticale uitlijning en bij verticale formulieren de horizontale uitlijning fixen?

**Comment by daverhelst** [comment]
> Kunnen we de margin/paddings verplaatsen naar het container element `.dso-label-container` en daarmee bij horizontale formulieren de verticale uitlijning en bij verticale formulieren de horizontale uitlijning fixen?

Helaas niet, het `.dso-info` blok leeft ook binnen `.dso-label-container`, de verticale ruimte tussen dat blok en de label/button combinatie wordt aangetast door het `display: inline` maken van het label.

**Comment by hansgrimm** [comment]
haha waren tegelijk aan het kloppen @daverhelst :)

**Comment by hansgrimm** [comment]
Zo, en nu weer van mijn vrije vrijdag genieten. ik kijk zo nu en dan wel waar de discussie heen gaat ;)

**Comment by tfrijsewijk** [comment]
Ik heb twee oplossingen bedacht:

![image](https://user-images.githubusercontent.com/9696261/179360335-1b615ece-eaa6-40bc-a113-5032c24cd96e.png)

![image](https://user-images.githubusercontent.com/9696261/179360560-5b70b01b-f728-4461-9d44-23be79c4fc54.png)

Ik zeg niet dat het de perfecte oplossing is, maar jullie obstakels heb ik hier mee getackeld. Wat denken jullie?

**Comment by hansgrimm** [comment]
Hoi Thomas,

Ik bewonder je work-ethic! rond de tijd dat jij dat schreef zat ik op een Haarlems terras achter een Jopen Tripel.. :)

Ik moet zeggen dat ik je oplossing best wel creatief vind, maar niet zo heel erg houdbaar; met name die truc met de line-height en de vertical-align zou nog wel eens onverwachte gevolgen kunnen hebben. Maar je oplossing prikkelt me, dus ook hier wat weekend-werk:

Ik heb dus zelf ook wat zitten hacken in de inspector, en daar kwam dit uit:
![Schermafbeelding 2022-07-16 om 21 27 25](https://user-images.githubusercontent.com/506527/179369509-20e78c88-281f-46f1-86cb-6ab6ac0feabd.png)
![Schermafbeelding 2022-07-16 om 21 27 35](https://user-images.githubusercontent.com/506527/179369511-2ce1b59d-52f5-4c9d-a1ed-b3b3fce91c94.png)

Het label kan nu toe met alleen `display: inline`, en de button met een `margin-top: 0` (of nog beter `margin-block-start: 0`). De spacing naar het info-block kan je bereiken met `.dso-label-container > control-label ~ .dso-info { margin-top: 1rem; }`; zo werkt het met en zonder button.

**Comment by tfrijsewijk** [comment]
Bij jouw oplossing lijnt het label niet uit met het veld:

![image](https://user-images.githubusercontent.com/9696261/179389320-0c41ae96-5e2f-4d6c-b1a7-c7cf11057633.png)

vs.

![image](https://user-images.githubusercontent.com/9696261/179389048-cf265108-f80e-4275-9e4f-ca30635df7fc.png)

Vandaar mijn truuk met vertical-align/lineheight. Ik vond 'm ook een beetje aan de creatieve kant, maar in de basis blijven het gewoon rekensommetjes en kan daarom ook niet inzien waarom het niet zou passen.

Maar mijn tweede suggestie maakt gebruik van padding-top op het label container. Volgens mij werkt dat net zo goed, ook als het een verticaal formulier is. Maar daar kunnen we @daverhelst morgen wel wat onderzoek naar laten doen:

* padding-top op de `.dso-label-container`
* verticale spacing op `.dso-info`

> De spacing naar het info-block kan je bereiken met `.dso-label-container > control-label ~ .dso-info { margin-top: 1rem; }`; zo werkt het met en zonder button.

Ik neem aan dat je `.control-label` bedoeld, maar waarom ga je voor zo'n complexe selector ipv `.dso-label-container .dso-info`?

**Comment by hansgrimm** [comment]
O ja, had ik even geen rekening mee gehouden (my bad). Nu wel:
![Schermafbeelding 2022-07-17 om 10 21 42](https://user-images.githubusercontent.com/506527/179390397-c558e393-8d31-495c-9c6d-9b650986e8c1.png)
Ik heb het label nu een `::before` gegeven met `display: block` en `margin-top: 8px` (eigenlijk moet dat .5rem zijn, zelfde resultaat. was te lui voor een nieuwe screenshot ;)). voor de rest idem.

**Comment by hansgrimm** [comment]
en inderdaad, die selector was wat aan de gecompliceerde kant; de mijne zou alleen werken als-ie na een `.control-label` komt, maar dat gebeurt waarschijnlijk altijd; dan kan-ie idd simpeler.

Ik ken een back-end programmeur die zijn beste werk doet na middernacht met een fles wijn en kaarsjes om de monitor :)

**Comment by tfrijsewijk** [comment]
@daverhelst Nou, do your best!
