### ISSUE TITLE
Autosuggest vertraging op loading state

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#1625]
### Aanleiding
Nav https://github.com/dso-toolkit/dso-toolkit/issues/1582. Wat vinden jullie van de suggestie van een configureerbaar delay (in ms) om aan te geven wanneer de spinner getoond wordt? Om het beeld te schetsen, in opstellen hebben voor de grote spinner een delay van 1 sec alvorens de spinner echt getoond wordt. Bij elke toepassing in DSO is het aan te nemen dat de spinner niet direct getoond dient te worden. Daarom mijn gedachte dat het een property zou kunnen zijn.

### Werkzaamheden
Extra property toevoegen aan het Autosuggest component. Naast de 'loading' property ook 'loading-delayed' toevoegen.

Loading-delayed wacht 1 sec voordat de loading state wordt getoond. Hiermee kan voorkomen worden dat de loading state bij suggesties "flikkerend" gedrag vertoond door calls tijdens het typen.

**Comment by LukeVerlaan** [comment]
PR: https://github.com/dso-toolkit/dso-toolkit/pull/1703
