### ISSUE TITLE
Nieuw component: `<dso-table>`

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#1627]
### Aanleiding 
In toggletip in table moet niet afgesneden worden https://github.com/dso-toolkit/dso-toolkit/issues/1480 . Is de conclusie getrokken om een dso-table component te maken. 1480 wordt een onderzoeksstory deze story is voor het uitwerken van het table component in combinatie met de toggletip. 

### Werkzaamheden
- dso-table component bouwen
- dso-table component tonen in toolkit in combinatie met toggletip implementatie.

**Comment by tfrijsewijk** [comment]
![image](https://user-images.githubusercontent.com/9696261/178315195-e100bf8d-8804-4d65-9aff-e8d127181394.png)

Als ik de strategie aanpas van `absolute` naar `fixed` wordt het:

![image](https://user-images.githubusercontent.com/9696261/178315259-33aa9746-ca1a-45a5-884f-606989ad1927.png)

De rand waar de tooltip nu op afbreekt (de shadow verdwijnt) is de rand van `body`. De witte ruimte daarnaast is van Storybook.

Als dit het probleem oplost, zou ik eigenlijk iets anders willen voorstellen..

```
<dso-tooltip strategy="auto|absolute|fixed"></dso-tooltip>
```

* **auto** (default): De tooltip heeft een routine waarmee hij bepaalt welke strategie nodig is. Als een element overflow heeft, dan zet ie 'm op fixed. Anders op absolute. Absolute positioneren is goedkoper dan fixed.
* **absolute**: De default strategie van Popper
* **fixed**: De tooltip positioneren met `position: fixed`.

@gofix Of mis ik iets? Als dit het probleem en een prima oplossing is, doe ik dat liever dan nu `<dso-table>` maken..

**Comment by gofix** [comment]
De analyse hier betreft eigenlijk #1480. Maar inderdaad, als we met een eenvoudige wijziging het oorspronkelijke probleem goed kunnen oplossen, zijn we snel thuis. 

Dan kan alsnog bepaald worden of er een slimmere `<dso-table/>` moet komen (om slimmer met het 'beweeg van links naar rechts' om te gaan dan nu), maar de noodzaak daarvan is dan een stuk minder.

**Comment by gofix** [comment]
Dus, wat mij betreft: kan _dit_ ticket op de backlog, en kan voor https://github.com/dso-toolkit/dso-toolkit/issues/1480 de door jou voorgestelde oplossing worden gerealiseerd.

**Comment by tfrijsewijk** [comment]
OK. Dus @hansgrimm, @LiesbethVorst en @DjangoBlok: we gaan het een beetje anders doen..

**Comment by hansgrimm** [comment]
dus deze gaat de backlog op, en #1480 wordt gereanimeerd, of wil je een nieuwe?

**Comment by tfrijsewijk** [comment]
Ik heb een nieuwe gemaakt: #1641

**Comment by hansgrimm** [comment]
Top, ik maak een jira-ticket aan.

Met vriendelijke groet,
Hans Grimm | Grimm.nl<http://grimm.nl/> BV

[Afbeelding met tekst, klok    Automatisch gegenereerde beschrijving]
T +31 6 22275783<tel:+31%206%2022275783>
E ***@***.******@***.***> :: W www.grimm.nl<http://www.grimm.nl/>
Grimm.nl<http://grimm.nl/> BV, Valeriuslaan 55, 1422 HS Uithoorn<x-apple-data-detectors://4/0> – NL
KvK: 70294674<tel:70294674> – BTW: NL858241997B01
LinkedIn: http://www.linkedin.com/in/hansgrimm


Op 13 jul. 2022 om 13:57 heeft Thomas Rijsewijk ***@***.***> het volgende geschreven:

﻿

Ik heb een nieuwe gemaakt: #1641<https://github.com/dso-toolkit/dso-toolkit/issues/1641>
