### ISSUE TITLE
dso-ozon-content met prefix en suffix

### ISSUE THREAD

**Issue by kad-tammie** [dso-toolkit/dso-toolkit#1628]
Via https://github.com/dso-toolkit/dso-toolkit/issues/1569 is de interactieve visualisatie van dso-ozon-content binnen een kop gerealiseerd. 

In de VRK wordt het dso-ozon-content web-component gevoed met een xml-string die de VRK van OZON ontvangt. Daarnaast kan er in de VRK een prefix en/of een suffix in een kop worden geplaatst. Bijvoorbeeld:
<img width="1262" alt="dso-ozon-content interactive met prefix en suffix in VRK" src="https://user-images.githubusercontent.com/77613213/175507640-288624e0-c5e2-4ef3-9fd2-eabc3cd14e8f.png">
Hier is zichtbaar dat de xml-content binnen dso-ozon-content netjes is voorzien van een interactieve visualisatie, terwijl de prefix en de suffix niet-interactief zijn. Dit is voor de VRK onwenselijk. 

**Het verzoek is (suggestie van Django Blok) om voor ozon-content in titels/koppen een speciaal web-component te realiseren, waarop 2 extra optionele inputs, prefix en suffix, aanwezig zijn die binnen web-component gecombineerd kunnen worden tot een samengestelde titel of kop:**

Voorbeeld van zo'n output:
<img width="1934" alt="dso-ozon-content interactive VOORSTEL visualisatie met prefix en suffix in VRK" src="https://user-images.githubusercontent.com/77613213/175509668-de3075b3-2ef0-4293-afd5-ea434f7679bb.png">

**Comment by tfrijsewijk** [comment]
Wat dacht je van:

```html
<dso-ozon-content>
  <span slot="prefix">AFDELING 4.1</span>
  <span slot="suffix">[gereserveerd]</span>
</dso-ozon-content>
```

Met slots kan er markup worden doorgegeven. Het kan ook met attributen, maar dan kan het alleen maar platte tekst zijn:

```html
<dso-ozon-content prefix="AFDELING 4.1" suffix="[gereserveerd]"></dso-ozon-content>
```

Met markup kunnen we er later misschien meer mee, en heeft een afnemer meer invloed op de semantiek.

**Comment by kad-tammie** [comment]
Mooi. Markup in VRK wordt er weer een stukje mooier van.
