### ISSUE TITLE
IE11 modal is positioned left

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#163]

**Comment by tfrijsewijk** [comment]
Komt uit in `3.0.0-alpha.1`

**Comment by tfrijsewijk** [comment]
@MichielDHVD https://www.dso-toolkit.nl/3.0.0-alpha.1/components/detail/modal--modal.html

**Comment by MichielDHVD** [comment]
Verplaatst naar done en kan gesloten worden
