### ISSUE TITLE
dso-document-list-item-type in Viewer Grid "Document item" mist margin-right: 8px

### ISSUE THREAD

**Issue by kad-tammie** [dso-toolkit/dso-toolkit#1637]
[Voorbeeldpagina "Document header"](https://core.dso-toolkit.nl/39.0.0/?path=/story/viewer-grid--voorbeeldpagina-document-header): de paragraph met class="dso-document-header-type" heeft een margin-right: 8px.
[Voorbeeldpagina "Document item"](https://core.dso-toolkit.nl/39.0.0/?path=/story/viewer-grid--voorbeeldpagina-document-item): de paragraph met class="dso-document-list-item-type" ontbreekt een margin-right: 8px.

Dit is niet zichtbaar in de voorbeeldpagina van het webcomponent Viewer Grid, maar komt wel naar voren bij de implementatie in de VRK. Zie de afbeeldingen. Gaarne deze margin: 8px toevoegen
<img width="1229" alt="dso-document-list-item-type_MISSING_margin_right_8px" src="https://user-images.githubusercontent.com/77613213/177113891-3272a41e-3733-474e-bc1e-c020632f12d7.png">
<img width="1231" alt="dso-document-header-type_margin_right_8px" src="https://user-images.githubusercontent.com/77613213/177113901-a3d5e672-683c-41ef-b1a3-45a5148efc2f.png">
.

**Comment by hansgrimm** [comment]
@kad-tammie dit is volgens mij een duplicaat van #1649 (die staat al op de rol). Kan ik deze sluiten?

**Comment by kad-tammie** [comment]
Ja, doet dat maar @hansgrimm
