### ISSUE TITLE
Paginering Web Component

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#1638]
De functionaliteit is als volgt: 

Alle beschikbare pagina's staan in een rij aangegeven met hun nummer

- Alle beschikbare pagina's staan in een rij aangegeven met hun nummer
- De huidige pagina is gehighlight
- Alle paginanummers zijn klikbaar, behalve de huidige pagina
- Als de huidige pagina niet de eerste is dan staat er links van de rij een < knop (functie: ga naar vorige pagina tov. de huidige)
- Als de huidige pagina niet de laatste is dan staat er recht van de rij een > knop (functie: ga naar volgende pagina tov. de huidige)

### Non-functionals:

- De hele rij staat gecentreerd in zijn container
- Als de rij te breed is voor de container, dan gaan de getallen en knoppen door op de volgende regel
- Let op met hiden/showen van de < en > knoppen dat de rij niet hinderlijk verspringt (dus dat de < en > knoppen op dezelfde positie beschikbaar blijven -> gebruik een placeholder als < en/of > niet getoond worden)
- Houd qua opzet rekening met eventuele uitgebreidere gewenste functionaliteit op een later moment: bijvoorbeeld het afbreken/onderbreken van reeksen bij een groot aantal pagina's, eventueel extra knoppen << en >> waarmee met meerdere pagina's tegelijk kan worden gesprongen, het klikbaar maken van de huidige pagina, etc. (dit is dus mogelijk toekomstige functionaliteit, hoeft nu niet te worden meegenomen)

**Comment by hansgrimm** [comment]
Let op: beschrijving aangepast.

**Comment by gofix** [comment]
Wat ik nog mis in dit verhaal is hoe om te gaan met het aantal te tonen pager links na de eerste, voor en na de huidige, en voor de laatste.

![image](https://user-images.githubusercontent.com/2689559/178716971-0a783d39-1323-48b7-9f01-188e21c417f9.png)

**Comment by gofix** [comment]
Daarover: In het implementatieplatform dat InfoProjects normaliter hanteert kent de pager de volgende parameters:

`pager_page`  → huidige pagenumber, startend bij 0
`pager_rows` → aantal items/resultaten per 'page'
`pager_count` → totaal aantal items/resultaten (NB: we kennen geen ‘infinite’)
`pager_pages_from_start` → je ziet altijd [1], en dit aantal bepaalt hoeveel pages je daarna nog als link aangeboden krijgt (dus: of je bv. ook [2], [3] ziet);
`pager_pages_before_current` → stel je zit op page [8], dit aantal bepaalt hoeveel pages je daarvoor nog als link aangeboden krijgt (dus: of je bv. ook [6], [7] ziet);
`pager_pages_after_current` → stel je zit op page [8], dit aantal bepaalt hoeveel pages je daarna nog als link aangeboden krijgt (dus: of je bv. ook [9], [10] zet);
`pager_pages_from_end` → je ziet altijd de laatste, bv. [19], en dit aantal bepaalt hoeveel pages je daarvoor nog als link aangeboden krijgt (dus: of je bv. ook [17], [18] ziet);
`pager_label_type` → of de links gelabeld worden als [1], [2], [3], of als [1-10], [11-20], [21-30]

Dat gezegd hebbende, lijkt me dat van al deze ‘customizing parameters’ we niets moeten aanbieden in een DSO component. Immers, de ‘smaak' (dus: label type, en het aantal links dat je voor/na first, current en last aanbiedt) zou al in het design system moeten zijn vastgelegd. Enige input lijkt me te zijn:

- page
- rows (hoewel ook daar een gezonde default/standaard ook echt wel raadzaam is)
- count

Over de overige zaken moet in het ontwerp wel een knoop worden doorgehakt.

**Comment by hansgrimm** [comment]
Overleg 18/7:
we willen voor nu als MVP een simpele versie die alle beschikbare pagina's laat zien, desnoods met wrapping. naar verwachting gaat het aantal pagina's beperkt zijn. Mocht het anders moeten, doen we dat in een volgende versie.
