### ISSUE TITLE
`<dso-tooltip>` voorzien van positioning strategy parameter

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#1641]
In #1480 gemeld dat een tooltip wordt afgesneden. In eerste instantie is bedacht dit op te lossen door `<dso-table>` te maken, die samenwerkt met `<dso-tooltip>`.

Tijdens het ontwikkelen van #1627 heb ik een andere oplossing voor dit probleem gevonden. Dit betekent dat `<dso-table>` naar de backlog kan en dat `<dso-tooltip-container>` en afgeleiden geen bestaansrecht meer hebben.

Popper ondersteund verschillende _positioning strategies_: `absolute` (default) en `fixed`. Met de `fixed` strategie wordt de tooltip niet meer afgesneden omdat de toolipt met `position: fixed` wordt gepositioneerd.

Deze functionaliteit moet aangeboden worden aan de afnemer:

```html
<dso-tooltip strategy="auto|absolute|fixed"></dso-tooltip>
```

Fixed is een dure routine. Zodra het element waar de tooltip op staat verplaatst ten opzichte van de viewport, moet Popper de tooltip verplaatsen. Bij absolute beweegt de tooltip automatisch mee.

`absolute` en `fixed` spreken voor zich: Die values worden direct doorgegeven aan de popper instance.

Auto heeft wat toelichting nodig: Bij auto gaat de tooltip zelf kijken welke strategie het beste past. In eerste instantie doet hij dit door de parents omhoog te lopen:
* Voor elk element in de parent tree wordt er gekeken of dat element een overflow heeft. Het traversen stopt dan.
* Voor elk [ShadowRoot](https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot) zet de traversal door in het DOM van het host element (het zgn "light dom").
* Bij `Document` eindigt de parent traversal.

Het detecteren van overflow kan oa. met:
* [computedStyling](https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle)
* Het meten van de inhoud en de hoogte van het element (volgens mij `scrollHeight` en `clientHeight`).

Ik denk dat de CSS oplossing het mooiste is, maar ik weet niet hoe goed toepasbaar die is.

Aandachtspunten: Hoe gaan we met DOM modificaties om? Moeten we met DOMObserver gaan werken?

**Comment by benheldoorn** [comment]
Hier https://dso-toolkit.nl/40.0.0/components/detail/mijn-projecten.html zie je hoe het fout gaat dus. (En straks hoe het goed is)
