### ISSUE TITLE
Conclusion definitief verwijderen

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#1643]
zie #1624 

Deprecated component definitief verwijderen.

**Comment by hansgrimm** [comment]
https://jira.team-dso.nl/jira/browse/DSOT-462

**Comment by daverhelst** [comment]
@MichielDHVD in #1624 wordt gesteld: `Het icoon 'status-forbidden' kan hierbij ook worden verwijderd, omdat deze nergens meer wordt toegepast.`

Maar nu zie ik deze wel terug komen op "Vergunningscheck -> Resultaat". Wordt hij toch nog wel ergens toegepast, of moet hier ook iets aangepast worden?

**Comment by MichielDHVD** [comment]
Nee hoor je hebt forbidden (gewoon zwart icoon) en status-forbidden (rood met witte lijn) status-forbidden wordt dus gezegd dat deze weg mag. 

In resultaat staat forbidden.
