### ISSUE TITLE
`.dso-justify-form-groups` onderbrengen in `@dso-toolkit/css`

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#1646]
Dit component wordt niet direct gedemo-ed, maar het gaat om: 

![image](https://user-images.githubusercontent.com/9696261/179196715-c0a55c42-1c9c-438a-b8ab-e78f65af2ce3.png)

https://dso-toolkit.nl/40.0.0/components/detail/locatie.html

Ik denk dat we deze als volwaardig component moeten positioneren. Qua modelering denk ik aan:

```ts
// /packages/sources/src/components/justify-form-groups/justify-form-groups.model

export interface JustifyFormGroups {
  formGroups: FormGroup[];
}
```

Iets anders mag er toch niet in.

- [x] CHANGELOG entry
- [ ] Stories en modelering in `/packages/sources`
- [ ] Templates en styling in `/packages/css` (geen mixins/imports)
- [ ] `/packages/dso-toolkit` opruimen

**Comment by PieterVerheij** [comment]
@tfrijsewijk Welke controls zie jij hier voor je? Volgens mij is er hier geen enkele van toepassing?
