### ISSUE TITLE
Toolkit 40.0.0: Chevron en kaarticoon verdwenen

### ISSUE THREAD

**Issue by krechj** [dso-toolkit/dso-toolkit#1648]
Hallo,
In de toolkit v40.0.0 zien wij dat de chevron achter 'Meer kenmerken' is verdwenen en dat de 'Toon gebied op de kaart' button weg is. 
![image](https://user-images.githubusercontent.com/37870677/179466255-918c7b7a-3ed9-46c2-96bc-b4a7749ad1f4.png)

**Comment by hansgrimm** [comment]
tweede deel van deze issue ondergebracht in issue #1652

**Comment by tfrijsewijk** [comment]
Dit is opgelost doordat de Storybooks zijn gefuseerd #1438

**Comment by hansgrimm** [comment]
👍👍
