### ISSUE TITLE
Viewer Grid: `.document-list-item` mist margin right voor `.dso-document-list-item-type`

### ISSUE THREAD

**Issue by kad-tammie** [dso-toolkit/dso-toolkit#1649]
In de Voorbeeldpagina "Document-header" binnen Viewer-grid zorgt onderstaande regel (dso-toolkit.css) dat er tussen het document-type en document-owner een witruimte wordt getoond:

`dso-viewer-grid:not([small]) .dso-document-header-type {
    margin-right: 8px;
}`

In de Voorbeeldpagina "Document-item" binnen Viewer-grid wordt ook een witruimte getoond tussen het document-type en document-owner. Deze is echter niet het gevolgd van een css-regel, maar een gevolg van wituimt in de html tussen de verschillende p-elementen.

Dit manifesteert zich in de Viewer Regels op de kaart, doordat de angular compiler options "preserveWhitespaces" de default-waarde van "false" heeft, waardoor alle whitespace in de html tijdens het AOT-compilatie proces wordt verwijderd.

Het verzoek is om onderstaande regel toe te voegen aan dso-toolkit.css:

`dso-viewer-grid:not([small]) .dso-document-list-item-type {
    margin-right: 8px;
}`

Tevens de zelfde "small" styling voor document-list als voor document-header toepassen: document-type en document-owner op separate regels.

**Comment by tfrijsewijk** [comment]
@kad-tammie We pakken 'm op!

**Comment by tfrijsewijk** [comment]
@kad-tammie Welke toolkit versie zitten jullie? Sinds enige releases is deze selector vervangen door iets met `dso-responsive-element`.

We kunnen de wens nog steeds bouwen, maar de implementatie zal anders zijn. Ik vermoed dat jullie nog niet over zijn naar v40.0.0: https://github.com/dso-toolkit/dso-toolkit/blob/master/CHANGELOG.md#4000

**Comment by kad-tammie** [comment]
We zijn in het proces om 40.0.0 te gaan gebruiken en heb in mijn PR review aan andere developer aangegeven dat dso-responsive-element moet worden geïmplementeerd. Kijken we even in hoeverre dat deze melding beïnvloedt.

**Comment by PieterVerheij** [comment]
Margin-right toegevoegd met lit-html/storybook whitespace:
![image](https://user-images.githubusercontent.com/25430835/186450478-dc949940-a868-43be-8785-c3463c7cc1da.png)

Margin-right toegevoegd en whitespace handmatig verwijderd in de dev toolbar:
![image](https://user-images.githubusercontent.com/25430835/186450080-fdecda3f-46a9-48e5-917b-7745ba075652.png)
