### ISSUE TITLE
Toolkit 40.0.0: Als de tekst te lang is dan loopt ie over de 'Hele document bekijken'-knop heen

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#1652]
Verschil met 39.0.0: Als de tekst te lang is dan loopt ie over de 'Hele document bekijken'-knop heen.
![image](https://user-images.githubusercontent.com/37870677/179467452-88fa44e3-fc65-48e0-bf81-f680f4f5742a.png)

**Comment by PieterVerheij** [comment]
Het is nooit goed geweest, ook niet in 39.0.0.
![image](https://user-images.githubusercontent.com/25430835/185650568-e40abd57-e5e2-4d6b-b200-38a35f7b440c.png)
