### ISSUE TITLE
Document Item uitbreiden met container voor regels

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#1657]
In het document item zoals geetaleerd in https://core.dso-toolkit.nl/_1515.Update-Documentheader/?path=/story/viewer-grid--voorbeeldpagina-document-item is nu geen rekening gehouden met regeltekst die eronder moet worden weergegeven.
In deze story wordt het document item aangepast zodat er regeltekst onder kan worden weergegeven.

**Comment by tfrijsewijk** [comment]
@DjangoBlok Dit issue behoeft nog een ontwerp

**Comment by daverhelst** [comment]
Ontwerpen zoals gevonden in Jira ticket:

![image](https://user-images.githubusercontent.com/5871330/183348530-512b53e9-5607-4d17-a2e2-123e1e920cc5.png)

![image](https://user-images.githubusercontent.com/5871330/183348556-0f96987c-ba08-4fac-8f26-131ba5a2465f.png)

**Comment by daverhelst** [comment]
@DjangoBlok @LiesbethVorst de toevoeging is al hier te bekijken. Zijn jullie het er mee eens?
https://core.dso-toolkit.nl/_1657.Document-Item-uitbreiden-met-container-voor-regels/?path=/story/viewer-grid--voorbeeldpagina-document-list

**Comment by LiesbethVorst** [comment]
De container voor eigen content is prima zo! Wat er precies in de container staat maakt eigenlijk niet uit, maar deze typische viewer content valt zo wel op (wordt nog aan gesleuteld en die link list is niet wat hier bedoeld wordt...). Persoonlijk zou ik er wat eenvoudigere content inzetten. 
Django is op vakantie, wanneer wil je dit afronden @daverhelst?

**Comment by daverhelst** [comment]
Klopt, de content heb ik overgenomen van de ontwerpen, maar die is natuurlijk vrij te vullen door jullie. Qua afronding, als jullie (jij) het eens zijn (bent) met hoe het er nu bij staat, dan kan dit het review traject in en heel snel afgerond worden.
