### ISSUE TITLE
Ozon Content: In Storybook markeren als "verwijderd" verschuift de elementen

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#1658]
![image](https://user-images.githubusercontent.com/9696261/180981687-bbc02695-c559-4f5b-a98d-7c3709ef06ac.png)

![image](https://user-images.githubusercontent.com/9696261/180981743-2d6fcf1c-c77d-46bc-bf0c-957add034d2b.png)

Als een Ozon Content component als `deleted` wordt gemarkeerd, wordt deze inhoud in een section getoond. Dit is een blok element waardoor de prefix/suffix niet uitlijnen.

Daarnaast denk ik dat het problematisch is dat dit component geen Shadow DOM heeft, maar dat moet nog blijken. Stencil emuleert het gedrag van slots als het geen Shadow DOM heeft.

Uitkomst van dit issue is dat `<dso-ozon-content deleted>` netjes uitlijnt.

**Comment by LiesbethVorst** [comment]
@svrijsewijk, heb even een check gedaan. De prefix en suffix moeten ook doorgehaald worden doorgegeven.
