### ISSUE TITLE
Header: Ook uitloggen zonder logoutUrl

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#1662]
> Hoi @tfrijsewijk, momenteel wordt het Uitloggen item alleen getoond als er ook een logoutUrl is gezet. Deze URL is echter nutteloos als je van de click-event gebruikmaakt (we hebben namelijk geen logout-URL), dus je moet een dummy-URL daarin plakken. Kan het niet anders?
> 
> Ik denk dat als isLoggedIn true is is dat voldoende om dat item te laten zien, nietwaar?

Zoals @yktoo aangeeft, lijkt mij dat geen slecht idee. Ik vraag mij alleen af wat we dan in de href van  `<a href="....">Uitloggen</>` moeten zetten, of dat het dan een `<button>` moet worden.. Ik neig naar een button.

cc: @hansgrimm @MichielDHVD

**Comment by hansgrimm** [comment]
Yep, button. Geen linkbestemming, wel een actie.

Met vriendelijke groet,
Hans Grimm | Grimm.nl BV

[Afbeelding met tekst, klok  Automatisch gegenereerde beschrijving]
T +31 6 22275783
E ***@***.******@***.***> :: W www.grimm.nl<http://www.grimm.nl/>
Grimm.nl BV, Valeriuslaan 55, 1422 HS Uithoorn – NL
KvK: 70294674 – BTW: NL858241997B01
LinkedIn: http://www.linkedin.com/in/hansgrimm


Van: Thomas Rijsewijk ***@***.***>
Datum: dinsdag, 26 juli 2022 om 13:58
Aan: dso-toolkit/dso-toolkit ***@***.***>
CC: Hans Grimm | Grimm.nl ***@***.***>, Mention ***@***.***>
Onderwerp: [dso-toolkit/dso-toolkit] Header: Ook uitloggen zonder logoutUrl (Issue #1662)

Hoi @tfrijsewijk<https://github.com/tfrijsewijk>, momenteel wordt het Uitloggen item alleen getoond als er ook een logoutUrl is gezet. Deze URL is echter nutteloos als je van de click-event gebruikmaakt (we hebben namelijk geen logout-URL), dus je moet een dummy-URL daarin plakken. Kan het niet anders?

Ik denk dat als isLoggedIn true is is dat voldoende om dat item te laten zien, nietwaar?

Zoals @yktoo<https://github.com/yktoo> aangeeft, lijkt mij dat geen slecht idee. Ik vraag mij alleen af wat we dan in de href van <a href="....">Uitloggen</> moeten zetten, of dat het dan een <button> moet worden.. Ik neig naar een button.

cc: @hansgrimm<https://github.com/hansgrimm> @MichielDHVD<https://github.com/MichielDHVD>

**Comment by tfrijsewijk** [comment]
Moeten we het dan voorwaardelijk maken? Als logoutUrl is gegeven, dan `a` anders `button` ?

@yktoo wat denk jij?

**Comment by yktoo** [comment]
Mij maakt het niet uit, misschien heeft @MichielDHVD wat te zeggen?

**Comment by MichielDHVD** [comment]
Ik heb geen specifieke voorkeur. Kan niet in de toekomst kijken welke varianten mogelijk gewenst zijn.
