### ISSUE TITLE
Button selectors van Bootstrap (default en link) deprecaten

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#1663]
# Aanleiding
In de releasenotes van 25.0.0 wordt gevraagd gebruik te maken van nieuwe button selectors die beter afgestemd zijn op het uitgangspunt van UX.

Dit is echter niet noodzakelijk, want de bestaande selectors blijven werken. Ook de voorbeelden op dso-toolkit.nl maken nog gebruik van de eerdere opzet. Vandaar dat team PR12 ervoor heeft gekozen dit nog niet te verwerken.

Uit de CHANGELOG entry van versie 25:
> Daarnaast hebben we de terminologie van het UX team doorgevoerd: Primary, secondary en tertiary buttons. Primary, default en link is een erfenis van Bootstrap. Voorlopig zullen de bestaande selectors blijven werken maar hieronder een mapping tabel:
> 
> ```
> .btn.btn-primary -> a.dso-primary, button.dso-primary
> .btn.btn-default -> a.dso-secondary, button.dso-secondary
> .btn.btn-link -> a.dso-tertiary, button.dso-tertiary
> ```

## Werkzaamheden
* Voorbeeld implementaties in de DSO Toolkit bijwerken met de gewenste selectors.
* Bestaande classes deprecaten (primary, default en link).

_Deprecation notice sturen naar alle teams die gebruik maken van de DSO-Toolkit, Reminder bij Sprint-Review geven._

**Comment by daverhelst** [comment]
Ik zag tijdens het ontwikkelen dat de buttons in de `highlight-box` component in een `dso-button-row` staan, maar de buttons in de `info` component niet. Nu heb ik dat gelijk getrokken, zodat in beide gevallen de buttons in een `dso-button-row` staan, zodat ze verticaal ook netjes uitgelijnd zijn (heb je geen `btn-align` meer nodig), maar nu staan deze ook in een `dso-rich-content` en die kan qua link stijling nog wat roet in het eten gooien (dat gebeurde al).

Vraag, willen we de `dso-button-row` niet uit de `dso-rich-content` plaatsen? Dat zal dan in een nieuw issue opgepakt moeten worden.

@tfrijsewijk @svrijsewijk @hansgrimm

**Comment by hansgrimm** [comment]
Een rich-content container lijkt me geen logische plek voor een button-row, dus wat mij betreft is dat OK.
