### ISSUE TITLE
Ozon content - Opschrift prefix verschuift bij verwijderd

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#1665]
## Waar
Ozon content - opschrift element

## Aanleiding
Het opschrift kent nu een aantal varianten die met properties worden aangestuurd.
Bij omschakelen naar verwijderd verspringt de prefix naar achteren. 

## Werkzaamheden
Ook bij de status verwijderd de prefix vooraan weergeven.

## Gebruikersimpact
Groot. Verwijderde elementen worden zo niet correct weergegeven.

**Comment by tfrijsewijk** [comment]
Deze bestond al: #1658

**Comment by hansgrimm** [comment]
Ik zag het bij een refresh van Jira….

Hij is alweer weg 😊


Met vriendelijke groet,
Hans Grimm | Grimm.nl BV

[Afbeelding met tekst, klok  Automatisch gegenereerde beschrijving]
T +31 6 22275783
E ***@***.******@***.***> :: W www.grimm.nl<http://www.grimm.nl/>
Grimm.nl BV, Valeriuslaan 55, 1422 HS Uithoorn – NL
KvK: 70294674 – BTW: NL858241997B01
LinkedIn: http://www.linkedin.com/in/hansgrimm


Van: Thomas Rijsewijk ***@***.***>
Datum: woensdag, 27 juli 2022 om 09:31
Aan: dso-toolkit/dso-toolkit ***@***.***>
CC: Hans Grimm | Grimm.nl ***@***.***>, State change ***@***.***>
Onderwerp: Re: [dso-toolkit/dso-toolkit] Ozon content - Opschrift prefix verschuift bij verwijderd (Issue #1665)

Deze bestond al: #1658<https://github.com/dso-toolkit/dso-toolkit/issues/1658>
