### ISSUE TITLE
Links in navs hebben geen visited state meer.

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#1666]
Aanleiding
Met het bouwen is er 1 punt uitgekomen waar het ontwerp nog sub-optimaal is. We willen een link list zonder visited state. Na overleg in Toolkit refinement kwam naar voren dat wanneer links voor nav doeleinden gebruikt worden we geen visited states willen hebben. 

Werkzaamheden
Links in nav elementen hebben geen visited state meer

Ontwerp
Afbeelding ontwerp waar je de visited states wel ziet.
![image](https://user-images.githubusercontent.com/36912722/181208166-d36679af-e676-4626-a53e-d924b5d9429a.png)

Afbeeldingen zonder visited state
![image](https://user-images.githubusercontent.com/36912722/181208190-cc1bd439-ec92-42a6-891b-bb3eee2dd203.png)

**Comment by tfrijsewijk** [comment]
Misschien is het goed om ook een overzicht van situaties waar een visuele visited-state wel gewenst is te hebben.

**Comment by MichielDHVD** [comment]
Ik ga dit issue sluiten. 

Wanneer een nav om een link list gezet wordt dan zijn de visited states al verwijderd. 

Dit was gedaan in issue https://github.com/dso-toolkit/dso-toolkit/issues/1454 Navigation block link list in highlight-box. 
Maar de selector was toegepast op nav.
