### ISSUE TITLE
Logo updaten

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#167]
Het huidige logo is al een tijdje gedateerd. 

Deze moet geupdate worden naar de meegeleverde afbeelding. 
![omgevingsloket](https://user-images.githubusercontent.com/36912722/44771399-25461380-ab6b-11e8-97ca-daa0dbbb33ad.png)

**Comment by tfrijsewijk** [comment]
Merged, komt uit in `3.0.0-alpha.2`

**Comment by tfrijsewijk** [comment]
Testable: https://www.dso-toolkit.nl/3.0.0-alpha.2/components/detail/header.html

**Comment by MichielDHVD** [comment]
Verplaatst naar Done. Kan gesloten worden
