### ISSUE TITLE
Form Group Input Number: label lijnt niet met nummer

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#1672]
![image](https://user-images.githubusercontent.com/9696261/181729779-1f6173a8-4ea8-4703-8244-6eeba18b1203.png)

**Comment by PieterVerheij** [comment]
DIt is wellicht iets teveel van het goede:
![image](https://user-images.githubusercontent.com/25430835/186444522-676ab8ef-f4af-41b6-80c1-2a02854abcc2.png)
