### ISSUE TITLE
Content-security-policy issue met SVG spritesheet voor iconen met style="fill: #hex;"

### ISSUE THREAD

**Issue by svrijsewijk** [dso-toolkit/dso-toolkit#1676]
**Aanleiding**
In #1600 <style> tag met css voor iconen met kleurvarianten weggehaald. Op andere iconen zitten nog style attributen.

![image](https://user-images.githubusercontent.com/21218284/182333870-c26dba3d-1629-40a3-8563-8aa817578d48.png)

**Oplossing**
We passen de iconen aan zodat de fill direct als attribuut wordt gezet ipv via een `style` attribuut.

**Comment by PieterVerheij** [comment]
https://www.dso-toolkit.nl/_1676.Content-security-policy-issue-met-SVG-spritesheet/
