### ISSUE TITLE
Helpcenter Panel: iframe content laden alleen als de panel open is

### ISSUE THREAD

**Issue by yktoo** [dso-toolkit/dso-toolkit#1678]
De Helpcenter-panel fetcht de content zodra die een nieuwe URL krijgt. Dat moet echter alleen gebeuren als de panel geopend is. De huidige implementatie zorgt voor onnodige traffic elke keer dat de gebruiker naar een andere route navigeert.

Aanvulling: dit gebeurt pas als je de panel een keer hebt uitgeklapt.

**Comment by hansgrimm** [comment]
hallo @yktoo 
Sorry voor de late reactie; is deze issue nog actueel?

**Comment by yktoo** [comment]
@hansgrimm Ja zeker, het speelt nog steeds
