### ISSUE TITLE
Icons.scss generated wrongly on unix-based OS

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#168]
`icons.scss` wordt tijdens het builden gegenereerd. De svg bestanden worden inline gebracht. De variablename wordt afgeleid van een relative pad naar de betreffende SVG.

Tijdens dit proces worden `_` en `\` omgezet naar `-`, dit moet verrijkt worden met `/`.

**Comment by MichielDHVD** [comment]
Mooi dat dit is opgelost. Was al benieuwd hoe dit kon gebeuren. 

Ik zet deze op done en kan gesloten worden.
