### ISSUE TITLE
Aanpassing document header

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#1681]
In de documentheaders zoals gemaakt in https://jira.team-dso.nl/jira/browse/DSOT-376 zijn nog een aantal bevindingen en ontwerpwijzigingen gewenst.

Werkzaamheden
Toevoegen icon only button om te zoomen naar plancontour. (kaarticoontje rechts naast de naam van het plan)
Toevoegen mogelijkheid om 1 of 2 badge elementen toe te voegen achter weergegeven versie (uitroepteken-icoontjes)
Aanpassen flow van de elementen zodat bij lange inhoud deze niet over elkaar heen vallen (zie onderaan/laatste afbeeldingen)
Ontwerp

Voorbeeld van het component in de viewercontext
![image](https://user-images.githubusercontent.com/506527/182827116-cf42b2b6-f9eb-4422-ba1f-80baea48aada.png)

Voorbeeld van het component met extra status label
![image](https://user-images.githubusercontent.com/506527/182827206-48232a69-cc64-449f-b5c6-87bbbd3d512d.png)

Voorbeeld alle versies paneel uitgevouwen
![image](https://user-images.githubusercontent.com/506527/182827271-2d0c2004-c513-4f0d-897c-73bcdce05178.png)

Specificaties
![image](https://user-images.githubusercontent.com/506527/182827356-af1fa00c-d440-4b3f-a329-0d71f95e8ba5.png)

**Comment by LiesbethVorst** [comment]
Aanvulling voor de badges met uitroeptekens:
- min width: 22px
- SR-only tekst voor de gele badge: “Let op: ontwerpversie beschikbaar” en voor de witte badge:  “Let op: toekomstige versie beschikbaar”

**Comment by daverhelst** [comment]
@LiesbethVorst @svrijsewijk Nou weet ik dat de badges 22px hoog zijn (en dat ze dus ook minimaal zo breed moeten zijn), maar dat is weer net een getal wat niet in het 8-punts grid valt. Zullen we er 24px van maken? Dat hebben we toen ook besloten voor de iconen

**Comment by hansgrimm** [comment]
@daverhelst eens. 24px (1.5rem) is logischer en sluit aan bij de rest.

**Comment by daverhelst** [comment]
Net ook besproken met @svrijsewijk ; het is zeker een goed idee om dit naar 24px (1.5rem) te trekken, maar dat valt buiten de scope van dit ticket. Deze wijziging zal dus in een eigen ticket moeten worden opgenomen, maar laten we wel even wat meer koppen bij elkaar steken omtrent de aanpak hiervan.

**Comment by LiesbethVorst** [comment]
Ik ben het helemaal met je eens @daverhelst dat deze afmeting aangepast moet worden. Ik zal hier een issue voor maken en dan nemen we meteen mee dat de versie met een border hiervoor niet outline gebruikt, zodat alle versies even groot zijn.

**Comment by hansgrimm** [comment]
@LiesbethVorst precies. Alles moet binnen `box-sizing: border-box` vallen, anders kan je nooit ‘bulletin-proof’ afmetingen zetten. Omdat de badges tekst kunnen bevatten, zullen die afmetingen in relatieve units moeten (em/rem), want ze moeten kunnen meeschalen met de tekst. 
Al met al een ingreep die naar een aparte ticket moet, of naar #1647
