### ISSUE TITLE
Leaflet upgraden naar versie 1.9.x

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#1683]
Mail van Rien Berkhout (plvv PO van PR12):
"Wij hebben een prio bug die veroorzaakt wordt door de gebruikte leaflet versie: (zie PR12-15850: we kunnen pop-up bij 'locatie kiezen' niet meer sluiten..)
Het probleem is opgelost in leaflet 1.9.0.
Wanneer kunnen jullie deze versie in de Toolkit toepassen?"

**Comment by hansgrimm** [comment]
@svrijsewijk checkt impact en hoeveelheid werk

**Comment by svrijsewijk** [comment]
https://www.npmjs.com/package/leaflet heeft geen versie 1.9.0

**Comment by hansgrimm** [comment]
Volgens https://github.com/Leaflet/Leaflet/milestone/38 is de operatie compleet, en volgens https://www.npmjs.com/package/leaflet zijn ze inmiddels bij versie 1.9.2
