### ISSUE TITLE
Tooltip: dismiss met escape toets

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#1689]
## Waar
Tooltip web componenten

## Aanleiding
Als een tooltip verschijnt door mouse hover of toetsenbordfocus moet deze dismissable zijn zonder de muispijl / toetsenbordfocus te verplaatsen, in principe met escape toets. Zijn ze dat niet, dan wordt afgeweken van succescriterium 1.4.13 indien de tooltip iets anders overlapt (en dat komt in de praktijk voor, bijvoorbeeld in projectentabel mijn omgevingsloket).

## Werkzaamheden
Zorgen dat bij indrukken escape toets een eventueel zichtbare tooltip verdwijnt. Voor toggletip lijkt dit al te zijn gedaan dus waarschijnlijk ongeveer dezelfde code toepassen.

## Gebruikersimpact
Beperkt: bij de voorbeelden die ik tot nu toe tegen kom overlapt de kleine tooltip (bijna) niets, dus verwacht niet dat gebruikers hierdoor in de problemen zullen komen.

**Comment by hansgrimm** [comment]
In review, maar ik zie geen PR; kloptat? :)

**Comment by LukeVerlaan** [comment]
PR: https://github.com/dso-toolkit/dso-toolkit/pull/1700
