### ISSUE TITLE
.dso-rich-content in highlight-box component

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#170]
Als er rich content in een highlight box wordt getoond moet deze wrapped zijn met ee `.dso-rich-content`. De gewenste markup wordt dan

```html
<div class="highlight-box">
  <div class="dso-rich-content">
    <h3>[..]</h3>
    [..]
  </div>
</div>
```

Graag het component bijwerken met begeleidende documentatie

**Comment by tfrijsewijk** [comment]
Testable: https://www.dso-toolkit.nl/3.0.0-alpha.2/components/detail/highlight-box.html

**Comment by WiebeCnossen** [comment]
Zijn er ook situaties waarin je _geen_ rich content in zo'n box wilt plaatsen? Ik kan me dat nauwelijks voorstellen. En dan nog zou `.dso-rich-content` geen effect hebben.

Dus de vraag blijft waarom dat gedrag er niet standaard op staat.

**Comment by MichielDHVD** [comment]
Ik kan die vraag niet goed beantwoorden. Wie zou die vraag kunnen beantwoorden?

**Comment by tfrijsewijk** [comment]
Ik denk dat jij dat moet doen, @MichielDHVD. Of in ieder geval een Product Owner-achtig-persoon.

Sta jij toe dat er in een highlight box bijvoorbeeld een formulier wordt gemaakt?
