### ISSUE TITLE
Op voorbeeldpagina 'Verzoek Detail' is een verkeerde caption opgenomen

### ISSUE THREAD

**Issue by Mennowm** [dso-toolkit/dso-toolkit#1701]
Zie https://dso-toolkit.nl/42.0.0/components/detail/verzoek-detail.html#browser-47cd7714e787c9d2073db86cd2b4649d-panel-html.
In de 'table' van bijlagen is een caption opgenomen:
```<caption class="sr-only">Overzicht van gebruikersnamen</caption>```

**Comment by hansgrimm** [comment]
@Mennowm Je bedoelt qua inhoud verkeerd neem ik aan; daar kan ik het alleen maar mee eens zijn :)

**Comment by Mennowm** [comment]
@hansgrimm ja dat klopt ging op de inhoud ;).

**Comment by hansgrimm** [comment]
Het gaat om een verborgen element op een voorbeeldpagina. je constatering is terecht, maar deze gaan we voor nu niet fixen. Er komt t.z.t. een nieuwe versie uit van de toolkit, daarbij wordt ook gekeken naar alle zaken die we daarheen migreren. op dat moment komt-ie vast wel bovendrijven ;)
Daar voor je arendsoog!
