### ISSUE TITLE
Niet alle event-emitters hebben React bindings

### ISSUE THREAD

**Issue by svrijsewijk** [dso-toolkit/dso-toolkit#1706]
Event emitters waarvan de propertyName al bezet is op `document` krijgen geen React bindings. Dit betekent dat React implementaties deze events niet kunnen gebruiken.

Uitleg hier door @LukeVerlaan 
https://github.com/dso-toolkit/dso-toolkit/pull/1789#issuecomment-1258177242

Tabel met naamswijzigingen is hier te vinden:
https://github.com/dso-toolkit/dso-toolkit/pull/1789#issue-1386242869

**Comment by LukeVerlaan** [comment]
Vervolg op https://github.com/dso-toolkit/dso-toolkit/issues/1664
