### ISSUE TITLE
Viewer grid: toegankelijkheid bediening breedte kaartpaneel

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#1708]
## Waar

Viewer grid

## Aanleiding

Het tekstpaneel kan 3 breedtes hebben (hierna: smal, middel of breed)
De breedte wordt aangepast met 2 knopjes.

Ook als deze knopjes gelabeled zijn (zie issue 415) is dit mechanisme niet toegankelijk, omdat een blinde gebruiker de huidige breedte hooguit indirect kan afleiden uit de op dit moment zichtbare knopjes en de actie bij het indrukken van een knopje alleen visueel wordt overgebracht.

Na overleg hebben we geconcludeerd dat het huidige ontwerp (voor nu) behouden blijft. De eenvoudigste oplossing is dan om een sr-only tekst "breedte tekstpaneel: [smal / middel / breed]" toe te voegen. Om te zorgen dat een screen reader wijziging van deze tekst voorleest bij indrukken van een verbreed / versmal knopje kan attribuut aria-live=polite worden meegegeven.

## Werkzaamheden
(in DOM) voor de knopjes een sr-only tekst toevoegen "breedte tekstpaneel: middel" (als middel de standaard is).
Deze tekst aria-live=polite meegeven.
Bij indrukken van de verbreed / versmal knopjes de sr-only tekst aanpassen.

##Gebruikersimpact
Beperkt: we moeten dit aanpakken om aan WCAG te voldoen, maar iemand die zo weinig ziet dat hij het paneel niet breder / smaller ziet worden zal deze knoppen hooguit gebruiken als hij met een goedziende samen werkt.

**Comment by hansgrimm** [comment]
Deze is nu getest en goed bevonden, toch?

**Comment by tfrijsewijk** [comment]
Allang gemerged joh!

![image](https://user-images.githubusercontent.com/9696261/189342517-28c8a51d-8ff1-40fb-8dfd-83ae254b9c6c.png)

;-)

**Comment by hansgrimm** [comment]
Note to self #1: even 1 minuut wachten voortaan.
Note to self #2: je op je vrije dag niet overal tegenaan bemoeien.
