### ISSUE TITLE
Map controls: sluiten bij escape

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#1710]
## Waar
Map controls web component

## Aanleiding
Als ik met de kaartlagen knop het dialoog open, kan ik dit alleen sluiten met het sluitknopje. Omdat het hier gaat om een soort modal (die ook dingen verbergt) verwacht ik dat dit met escape gesloten kan worden.

## Werkzaamheden
Sluiten met escape knop implementeren

## Gebruikersimpact
Hinderlijk: is voor toetsenbordgebruikers wel een afwijking van de conventie maar sluitknopje is met het toetsenbord bereikbaar.

**Comment by svrijsewijk** [comment]
Hiervan is besloten dat het toch niet wenselijk is om de controls te sluiten met Escape dacht ik @hansgrimm

**Comment by hansgrimm** [comment]
Klopt. Die laten we gaan.

**Comment by hansgrimm** [comment]
Tim: "Besproken in refinement 18 augustus. Omdat het "dialoog" niet als modal bedoeld is, willen we het niet met escape sluiten. In plaats daarvan moet (in tekstalternatieven en ontwerp) duidelijker gemaakt worden dat het een paneel is wat weer verborgen kan worden."
