### ISSUE TITLE
Label-group en Label component; WCAG verbeteringen

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#1712]
## Waar
Viewer grid component

## Aanleiding
Bevinding in zelfevaluatie viewer:
Onder de h3 "uw keuzes" staan witte blokjes met toegepaste filters. Dit moet gezien worden als een "lijst van toegepaste filters" en zo ziet het er ook uit.
Om WCAG succescriterium 1.3.1 info en relaties te behalen, moet deze unordered list als zodanig gecodeerd worden.
Daarbij mogen de sr-only ':' tekens weg en voldoen de verwijder knopjes niet aan onze conventie dat in het label sr-only staat wat verwijderd wordt.

## Werkzaamheden
* Witte blokjes met geselecteerde filters in `<ul>` zetten
* Labels in filterblok removable maken

## Gebruikersimpact
Beperkt: is een WCAG afwijking maar de kans dat problemen ontstaan is klein.

**Comment by daverhelst** [comment]
De `:` was onterecht, er werd een `bright`-status gebruikt en deze komt niet voor in de betreffende `statusMap`. Nu zag ik ook na wat dieper duiken, dat deze mapping van de statussen voor Label niet helemaal synchroon meer loopt.

@tfrijsewijk hier moet iemand even goed naar kijken om misschien met een andere oplossing te komen die wat stabieler voor alle geldende smaken zal zijn
