### ISSUE TITLE
Autosuggest: automatische testen

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#1713]
## Voorgestelde automatische testen autosuggest web component
Wordt aria-expanded correct aangepast bij zowel uitklappen als inklappen?
### Bij open suggestielijst
Als een item is geselecteerd, is dat dan altijd ook de aria-activedescendant en het item dat bij een druk op enter wordt geselecteerd?

Er zijn enkele toetsenbord gedragingen die (in de context van de applicatie) gecontroleerd moeten worden, in het voorbeeld gaan ze allemaal goed:

- Escape: sluit lijst en plaatst focus in tekstvak (tekstcursor na laatste teken)
- pijl omhoog / omlaag, afhankelijk van huidige focus:
- Focus in tekstveld, pijl omlaag / omhoog: zet focus op eerste / laatste item
- Focus op laatste item, pijl omlaag / eerste item, pijl omhoog: zet focus op eerste / laatste item
- andere gevallen pijl omlaag / omhoog: focus op volgende / vorige item
- Focus op een item, backspace of letter: klap lijst in, verplaats focus naar het invoerveld en verwerk toets.

**Comment by svrijsewijk** [comment]
Dit is al gedaan
https://github.com/dso-toolkit/dso-toolkit/blob/master/cypress/integration/core/autosuggest.spec.ts
