### ISSUE TITLE
Progress bar / indicator: WCAG verbeteringen

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#1714]
## Waar
Progress bar en progress indicator web componenten

## Aanleiding
Omdat de progress indicator niet als zodanig wordt voorgelezen hier nogmaals in gedoken.

De <div class=progress bar/indicator> hebben aria-labeledby.
Dit is volgens [wai-aria 1.2 (ProgressBar) ](https://www.w3.org/TR/wai-aria-1.2/#progressbar)"prohibited"! Dus weghalen, een progressbar mag volgens de specificatie geen name hebben. Idee is dat de tekst binnen het element staat en wordt voorgelezen, zoals dat bij onze progress bar al het geval is (en die wordt goed voorgelezen).

Bij de progress indicator is ook dit fout gegaan: de `<span id=progress-indicator-label>` staat na de `<div>`. Gevolg is dat de `<div role=progressbar>` wordt genegeerd en alleen de span wordt voorgelezen. De `<div>` moet dus pas na de `<span>` komen.

## Werkzaamheden
- aria-labeledby verwijderen (is onnodig)
- progress indicator: span binnen de div plaatsen

## Gebruikersimpact
Hinderlijk: gebruiker weet niet dat het een progress indicator is maar begrijpt OBV de tekst wel wat er aan de hand is.

**Comment by daverhelst** [comment]
@timveld Dit issue staat nu klaar ter test:

**Progress Bar - HTML/CSS**
https://storybook.dso-toolkit.nl/_1714.Progress-bar-indicator-WCAG-verbeteringen/?path=/story/html-css-progress-bar--default

**Progress Indicator - HTML/CSS**
https://storybook.dso-toolkit.nl/_1714.Progress-bar-indicator-WCAG-verbeteringen/?path=/story/html-css-progress-indicator--small

**Progress Bar - Webcomponent**
https://storybook.dso-toolkit.nl/_1714.Progress-bar-indicator-WCAG-verbeteringen/?path=/story/core-progress-bar--default

**Progress Indicator - Webcomponent**
https://storybook.dso-toolkit.nl/_1714.Progress-bar-indicator-WCAG-verbeteringen/?path=/story/core-progress-indicator--small

**Comment by hansgrimm** [comment]
**Hij doet heel moeilijk (leest de voorbeelden nogal inconsistent voor) en ik krijg het in codepen niet goed. Maar waarom gebruiken we eigenlijk geen <progress>? Veel simpeler en het gaat meteen goed: https://codepen.io/timveld/pen/poVbBGV
CodePenCodePen
[progressbar met html5 progress](https://codepen.io/timveld/pen/poVbBGV)
... (4 kB)
https://codepen.io/timveld/pen/poVbBGV**

**Comment by hansgrimm** [comment]
https://css-tricks.com/html5-progress-element/

**Comment by hansgrimm** [comment]
Parallels Windows 11, Chrome/NVDA leest voor: 
- Progress Bar - HTML/CSS: "progress bar sixty".
- Progress Indicator - HTML/CSS: "progress bar half checked zero".
- Progress Bar - Webcomponent: "progress bar sixty".
- Progress Indicator - Webcomponent: "progress bar half checked zero".

**Comment by hansgrimm** [comment]
de aria role 'progressbar' gaat anders om met descendants dan je zou verwachten, waardoor de NL-tekst (die in een span staat binnen de progressbar (dus een descendant). Als je de tekst in een aria-label attribuut van de progressbar stopt, wordt deze keurig voorgelezen.
![Schermafbeelding 2022-09-13 om 09 38 25](https://user-images.githubusercontent.com/506527/189840189-2644534e-5f6d-473b-bdbc-3aaf581a35b0.png)

**Comment by timveld** [comment]
Na veel gepruts tot de conclusie gekomen dat een goede oplossing zonder html5 <progress> niet mogelijk is. De <label for> constructie werkt wel op progress maar niet op een div/span. Resterende labelopties zijn ook niet goed:
* aria-labeledby wordt overal genegeerd, in de firefox accessibility tree blijft de name null en zo wordt het ook voorgelezen.
* aria-label lost dit wel op en dan wordt het met NVDA goed voorgelezen (mits je het zichtbare label hidden maakt), maar aria-label wordt door JAWS genegeerd.

Dus het is kiezen tussen totaal ontoegankelijk voor JAWS gebruikers (kan niet) of dubbel voorgelezen label voor NVDA (ook niet handig).

Ik ga dan voor de minst slechte optie aria-labeledby in combinatie met een paar wijzigingen. Het wordt dan zowel door JAWS als NVDA in de praktijk acceptabel voorgelezen. Dat firefox aria-labeledby negeert is een kennelijke bug (=niet onze verantwoordelijkheid).

Voorgestelde wijzigingen:
* Haal de span met het label buiten de span met de progressbar role, en plaats die in DOM boven
* Verwijs hiernaar met aria-labeledby (dat doet in de praktijk niets maar dan volgen we in ieder geval de standaard)
* gebruik span ipv div rond de progress, dit voorkomt dat een regel wordt overgeslagen (die regelafbreuk kan verwarrend zijn als de progressbar geen label heeft)
Het 'skelet' (zie eerder genoemde codepen voor volledige code):
<span id="zichtbaarlabel">Zichtbaar label</span/>
<span role="progressbar" aria-labeledby="zichtbaarlabel" .../>
Dit skelet geldt zowel voor progressbar als progress indicator.

Beste oplossing blijft html5 progress, met <label for> constructie waarbij label in DOM ook boven de progressbar moet staan. Zie mijn codepen, dit wordt nog beter voorgelezen. Maar als overstappen op <progress> nu niet mogelijk / wenselijk is kan ik daar mee leven, met mijn voorgestelde wijzigingen werkt het voor gebruikers goed genoeg.

**Comment by tfrijsewijk** [comment]
Hoi @timveld,

![image](https://user-images.githubusercontent.com/9696261/189879011-840979e5-e975-4bb6-985e-f67b7d5256aa.png)

`aria-labelledby` spel je met dubbel L.

**Comment by timveld** [comment]
Correctie op vorige comment (spellllling...) 
Na wat gepruts de oplossing gevonden. 
Voorgestelde wijzigingen: 
* Haal de span met het label buiten de span met de progressbar role, en plaats die in DOM boven
* Verwijs hiernaar met aria-labelledby  
* gebruik span ipv div rond de progress, dit voorkomt dat een regel wordt overgeslagen (die regelafbreuk kan verwarrend zijn als de progressbar geen label heeft)
Het 'skelet' (zie eerder genoemde codepen voor volledige code):
<span id="zichtbaarlabel">Zichtbaar label</span/>
<span role="progressbar" aria-labelledby="zichtbaarlabel" .../>
Dit skelet geldt zowel voor progressbar als progress indicator. 

Beste oplossing blijft html5 progress, met <label for> constructie waarbij label in DOM ook boven de progressbar moet staan. Zie mijn codepen, dit wordt nog beter voorgelezen. Maar als overstappen op <progress> nu niet mogelijk / wenselijk is kan ik daar mee leven, met mijn voorgestelde wijzigingen werkt het voor gebruikers goed genoeg.

**Comment by hansgrimm** [comment]
Hoi @timveld 
Kunnen wij concluderen dat dit de voorgestelde markup zou zijn:
`<div class="progress">
     <span id="progress-label">Genereren export: nog ongeveer 4 minuten.</span>
      <span class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" aria-labelledby="progress-label">
     </span>
    </div>`
    Laat even weten!

**Comment by timveld** [comment]
Klopt, in theorie zou het met deze markup als basis goed moeten gaan.

**Comment by hansgrimm** [comment]
@tfrijsewijk witte rook :)

**Comment by timveld** [comment]
Progress indicator is goed. Maar op de progress bar lijkt aria-labelledby te ontbreken of inspecteer ik niet goed?

**Comment by daverhelst** [comment]
@timveld goed gezien, deze ontbrak in het Progress Bar CSS component. Bij het webcomponent was hij overigens wel aanwezig. Kun je nog eens kijken?

cc: @hansgrimm @svrijsewijk

**Comment by hansgrimm** [comment]
@daverhelst ^^ hij kan door! :)
