### ISSUE TITLE
Afstand tussen chevron en tekst verkleinen

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#1725]
### Aanleiding
Tussen tekst en icons zit overal een marge van 8px. Omdat chevrons binnen het icon (24x24) al witruimte om zich heen hebben komen ze ver af te staan van tekst. Daardoor zweven ze in sommige componenten en lijken niet bij de tekst te horen. 

Het speelt niet bij componenten waar de chevron en de tekst duidelijk bij elkaar horen door een border of achtergrondkleur, zoals op buttons.

Componenten waar het mis gaat:

- Link list
- Tertiaire button
- Dropdown menu - met tertiaire button

### Voortraject
- Zijn dit alle componenten?
- Er zijn meer smalle icons, moeten die ook meegenomen worden of worden die niet gebruikt in situaties/componenten waar de afstand te groot kan zijn?

**Conclusie**: We beperken de scope op de genoemde componenten, en het `chevron` icoon.

### Werkzaamheden
- Link list & dropdown menu
Bij Link list en Dropdown menu wordt altijd het chevron gebruikt door middel van een `::after`. Voor deze specifieke componenten passen we de margin aan zodat het icoon niet meer zweeft
- Tertiaire button
We stijlen op `.btn-tertiair > dso-icon[icon="chevron-right"` zodat we voor specifiek voor de tertiaire button in combinatie met chevron iconen een passendere margin gezet kan worden.

Voorbeeld is chevron bij openklappende tekst in documenten

### Acceptatiecriteria

**Comment by daverhelst** [comment]
Ik vraag mij af of dit issue nog relevant is, als ik het commentaar in het Jira ticket lees. @hansgrimm @MichielDHVD ?

**Comment by daverhelst** [comment]
Wat ik wel even ter discussie wil stellen @hansgrimm @LiesbethVorst @MichielDHVD is dat de voorbeelden die genoemd worden 
(op de link-list na) ook andere iconen kunnen bevatten en _daar_ wil je juist wel die 8px margin tussen het icoon en de tekst hebben. 

Of moeten we het gaan vinden in een modifier op deze componenten die zorgt dat er _geen_ margin tussen icoon en tekst staat?

Het voorstel om de afstand te verkleinen met 8px is dus niet zo eenvoudig.

**Comment by hansgrimm** [comment]
aangezien alle iconen op hetzelfde artboard staan, en het verschil zit in de afstand tot de rand *binnen* dat artboard, vrees ik met jou dat het enige alternatief een modifier zal zijn. niet ideaal, ik weet het..

**Comment by LiesbethVorst** [comment]
Klopt @daverhelst, een mooie oplossing bestaat waarschijnlijk niet. Helaas...

**Comment by DjangoBlok** [comment]
Dus eigenlijk zijn er twee oplossingsrichtingen:
1. Een modifier (die door implementator gezet kan worden)
2. Voor sommige iconen toestaan dat ze een ander artboard breedte hebben
Misschien voors en tegens van beide oplossingen even naast elkaar zetten?

**Comment by daverhelst** [comment]
@DjangoBlok Optie 2 is wat mij betreft geen optie. Alle iconen dienen nou eenmaal gebruik te maken van hetzelfde artboard, en die is bepaald op 24x24 pixels.

**Comment by daverhelst** [comment]
@LiesbethVorst de wijzigingen zijn o.a. hier te bekijken:

https://dso-toolkit.nl/_1725.Afstand-tussen-chevron-en-tekst-verkleinen/components/detail/dropdown-menu-css.html
https://dso-toolkit.nl/_1725.Afstand-tussen-chevron-en-tekst-verkleinen/components/detail/link-list.html
https://dso-toolkit.nl/_1725.Afstand-tussen-chevron-en-tekst-verkleinen/components/detail/buttons.html

en in verschillende voorbeeldpagina's

Zijn er nog op- of aanmerkingen?

**Comment by LiesbethVorst** [comment]
Hi, nog een vraag over de afstand tussen de chevron en de tekst. Het lijkt alsof deze nu constant is en dus aangepast aan of het een smalle chevron is (left/right) of een brede (up/down). Ziet er mooi uit, maar werkt dat ook als je in een tertiaire button een brede chevron plaats? Op de voorbeeldpagina staat die niet maar die gebruiken we wel.

**Comment by daverhelst** [comment]
@LiesbethVorst We kunnen per soort icoon sturen naar de ruimte tussen de tekst en het icoon. Als jij nu al aangeeft dat er ook tertiare buttons zijn (niet dropdown-menu) met een chevron-up en chevron-down icoon, dan kan ik daar alvast de bijbehorende stijling toevoegen (wel zoals bij dropdown-menu)

**Comment by LiesbethVorst** [comment]
Mooi! We gebruiken zeker buttons (die geen dropdown zijn) met een up/down chevron. Er zitten er nu bijv. al 2 in de document header:
![image](https://user-images.githubusercontent.com/91903058/192532369-b1c5f558-683a-49f1-9954-d601d857a3e3.png)
