### ISSUE TITLE
Externe links: href ontbreekt

### ISSUE THREAD

**Issue by iterox** [dso-toolkit/dso-toolkit#1728]
Het ozon-content web-component ontvangt de volgende xml voor een externe referentie (voorbeeld is een de inhoud voor een begripplijst, die ik heb ingekort):

`<Inhoud xmlns='https://standaarden.overheid.nl/stop/imop/tekst/' xmlns:DSO-PI12='https://standaarden.overheid.nl/lvbb/DSO-PI12' xmlns:data='https://standaarden.overheid.nl/stop/imop/data/' xmlns:ns10='http://www.w3.org/2001/SMIL20/Language' xmlns:ns2='https://standaarden.overheid.nl/stop/imop/consolidatie/' xmlns:ns4='https://standaarden.overheid.nl/lvbb/stop/uitlevering/' xmlns:ns5='http://www.opengis.net/se' xmlns:ns6='http://www.w3.org/1999/xlink' xmlns:ns7='http://www.opengis.net/ogc' xmlns:ns8='http://www.opengis.net/gml' xmlns:ns9='http://www.w3.org/2001/SMIL20/'>
    <Begrippenlijst eId='cmp_2__content_o_1__list_o_1' wId='pv31_1__cmp_2__content_o_1__list_o_1'>
        <Begrip eId='cmp_I__content_o_1__list_o_1__item_o_1' wId='pv25_1__cmp_I__content_o_1__list_o_1__item_o_1'>
            <Term>Overstromingskans bebouwd gebied 1</Term>
            <Definitie>
                <Al>
                    <ExtIoRef xmlns='' href='https://identifier-eto.overheid.nl//join/id/regdata/pv25/2021/OKBebouwdEenOpHonderdWRIJ/nld@2021-11-14;1'>/join/id/regdata/pv25/2021/OKBebouwdEenOpHonderdWRIJ/nld@2021-11-14;1</ExtIoRef>
                </Al>
            </Definitie>
        </Begrip>
    </Begrippenlijst>
</Inhoud>`

Het element 'ExtIoRef' vertegenwoordigt de externe referentie.

De html binnen het ozon-content webcomponent is als volgt:

`<span class="fallback od-Begrip sc-dso-ozon-content"><span class="fallback od-Term sc-dso-ozon-content">Overstromingskans bebouwd gebied 1</span>
  <span class="fallback od-Definitie sc-dso-ozon-content">
    <p class="sc-dso-ozon-content">
      <a target="_blank" rel="noopener noreferrer" class="sc-dso-ozon-content">
        <span class="sr-only sc-dso-ozon-content">opent in nieuw venster</span>
        /join/id/regdata/pv25/2021/OKBebouwdEenOpHonderdWRIJ/nld@2021-11-14;1
      </a>
    </p>
  </span>
</span>`

Op het anchor element ontbreekt het href-attribuut met de juiste value.

Geconstateerd in v42.0.0.

**Comment by tfrijsewijk** [comment]
He @kad-tammie! Goed dat je er nog een reminder stuurt. Dit issue is ongeveer bij ons op de radar. Als dit de hoogste prio heeft dan pakken we het natuurlijk direct voor je op. Heb je het NU nodig, of kan het de release van aanstaande woensdag mee?

cc: @hansgrimm @LiesbethVorst @DjangoBlok

**Comment by kad-tammie** [comment]
Aanstaande woensdag is prima. Dank!

**Comment by hansgrimm** [comment]
hallo @kad-tammie Sorry, deze is geheel aan mijn aandacht ontsnapt... iets met een filter dat ik op de issues zet, kennelijk toch niet helemaal goed.
We bespreken deze issue straks in onze refinement!
