### ISSUE TITLE
Label: Bij truncaten gaten opvullen

### ISSUE THREAD

**Issue by svrijsewijk** [dso-toolkit/dso-toolkit#1734]
vervolg op #1724

* Component zelf laten berekenen hoe labels de breedte van de omliggende container goed kunnen vullen (om te voorkomen dat er grote gaten ontstaan).

**Comment by tfrijsewijk** [comment]
We gaan deze proberen op te pakken ipv. #1724, het werk in dit issue maakt het werk in dat issue overbodig

**Comment by tfrijsewijk** [comment]
@LiesbethVorst Luke en ik hebben wat voorzetjes gegeven. Kan jij kijken wat je ervan vindt?

* Hier staan een aantal varianten onder elkaar: https://storybook.dso-toolkit.nl/_1734-Label-Bij-truncaten-gaten-opvullen/?path=/story/core-viewer-grid--voorbeeldpagina-filterblok
* Hier staat een losse variant: https://storybook.dso-toolkit.nl/_1734-thomas/?path=/story/core-viewer-grid--voorbeeldpagina-filterblok

Ter verslaglegging:
* https://css-tricks.com/piecing-together-approaches-for-a-css-masonry-layout/

**Comment by DjangoBlok** [comment]
Eens. Niet alle varianten breken goed af zie ik. Wat is er gedaan in de losse variant?

**Comment by LiesbethVorst** [comment]
Jammer dat het niet mogelijk is alles te combineren. Wat mij betreft zijn er situaties waarin de labels zo lang zijn dat je ze echt wil afbreken. In de losse variant kan onderstaande situatie ontstaan en dat is echt zonde van de schermruimte want het filterblok is bedoeld als samenvatting.

<img width="1232" alt="image" src="https://user-images.githubusercontent.com/91903058/189932256-fe3cc199-47f8-44cd-a331-c717355ce8aa.png">

**Comment by tfrijsewijk** [comment]
Laat mij benadrukken dat afhangt van de inhoud en sortering. Als jouw laatste voorbeeld gesorteerd was op lengte, dan hadden de laatste 2 labels naast "Tuin" gestaan en daarmee keurig het loze gat opvullend. Dan is het juist zonde om een max-width te zetten, want dan is dat hele lange label afgebroken, terwijl er niets meer staat.

De volgende stap zou een intelligente routine zijn die ook de labels gaat sorteren. Voor nu denk ik dat de korte variant de beste optie is.

**Comment by tfrijsewijk** [comment]
@LiesbethVorst @DjangoBlok zullen we de losse variant mergen en daarna verder kijken?
