### ISSUE TITLE
dso-ozon-content in interactieve modus hanteert ongewenste styling

### ISSUE THREAD

**Issue by iterox** [dso-toolkit/dso-toolkit#1737]
In https://github.com/dso-toolkit/dso-toolkit/issues/1569 is het dso-ozon-content in interactieve modus voorzien van de volgende styling:

`
[interactive].sc-dso-ozon-content-h {
    background-color: #0000;
    color: #39870c;
    text-decoration: underline;
    cursor: pointer;
}
`

Dit leidt to een erg druk beeld in de VRK:

<img width="529" alt="Screenshot 2022-08-30 at 13 53 29" src="https://user-images.githubusercontent.com/4646174/187433638-9e16c252-84fd-4e68-b19d-4b54adad9c4d.png">

Het verzoek vanuit de VRK is om aan te kunnen geven dat deze interactieve styling niet moet worden gehanteerd.

Als tijdelijke oplossing in de VRK worden de volgende text-decoration: none en color: inherit geforceerd.

**Comment by LiesbethVorst** [comment]
![image](https://user-images.githubusercontent.com/91903058/187916395-635e5f1a-3d7c-4aff-8908-9ef874a1301c.png)

- Het inspringen wordt niet door het toolkit component gefaciliteerd.
- De basisstijl is: font-size 16px, font-weight: bold; line-height: 24px
- De enige variant in stijl is de kleur:
- - Titels van hoofdstukken, afdelingen, (sub)paragrafen etc.:  bosgroen
- - Titels van artikelen: zwart

Voorbeeld van content in VRK: https://preprod.viewer.dso.kadaster.nl/viewer/document/%2Fakn%2Fnl%2Fact%2Fmnre1034%2F2019%2Freg0001/regels?regelsbeleid=regels,geldend&locatie-x=140577&locatie-y=461753&locatie-stelsel=RD&no-zoom=false&documenten=%5B%7B%22documentId%22:%22%2Fakn%2Fnl%2Fact%2Fmnre1034%2F2019%2Freg0001%22,%22title%22:%22Omgevingsregeling%22,%22documentType%22:%22Ministeriële%20Regeling%22,%22apiSource%22:%22OZON%22,%22isOmgevingsvergunning%22:false%7D%5D

**Comment by DjangoBlok** [comment]
Een toevoeging is dat deze lay-out hetzelfde blijft als de elementen een HTML H2-H6 meekrijgen.

**Comment by tfrijsewijk** [comment]
Ik heb het Ozon Content component attribuut `interactive` uitgebreid met een modifier `"sub"`. Hiermee wordt er geschakeld tussen bosgroen en zwart.

>Een toevoeging is dat deze lay-out hetzelfde blijft als de elementen een HTML H2-H6 meekrijgen.

Ik heb nog eens goed gekeken hoe dit nou zit, maar dat is toch niet zo'n goed idee om vanuit de toolkit te regelen. Dit component staat namelijk in een heading element (`h2-h5`). Als ik een kleinere font-size forceer gaat dat gegarandeerd uitlijning issues opleveren met bv. de chevron die daarnaast staat.

Die font-size op headings moeten we op 'n andere manier realiseren.

Daarnaast is de markup die nu wordt gemaakt ongeldig: Er staat een `div` in het heading element.

![image](https://user-images.githubusercontent.com/9696261/190179540-df1c9872-b47c-435c-b1b8-8beb2b797c29.png)
