### ISSUE TITLE
Icoon van searchbar komt in beeld vliegen

### ISSUE THREAD

**Issue by WiebeCnossen** [dso-toolkit/dso-toolkit#175]
Het icoon van searchbar komt met een animatie in beeld vliegen. Volgens mij is de betrokken CSS alleen bedoeld voor de overgang van inactive naar active, niet om de initiële display te beïnvloeden.

**Comment by tfrijsewijk** [comment]
Dit is ook door Michiel aangegeven in #71. Kun jij je vinden in de voorgestelde oplossing dmv. een modifier class `.dso-animate` ?

**Comment by WiebeCnossen** [comment]
Ja, dat zag ik later ook. Lijkt me goede oplossing.
