### ISSUE TITLE
Viewer grid: Focus trap negeert focusable elements in shadow-dom

### ISSUE THREAD

**Issue by MichielKadaster** [dso-toolkit/dso-toolkit#1756]
De `dso-toggletip` werkt niet goed wanneer deze in het `filterpanel` slot van de `dso-viewer-grid` wordt geplaatst.
Er zijn verschillende problemen met de tooltip binnen het filterpanel.
Ik verwacht dat deze gerelateerd zijn aangezien ik ze op andere plekken niet kan reproduceren.

**Icoontje blijft actief**
Sluit de tooltip.
Merk op dat het icoontje actief blijft.
![image](https://user-images.githubusercontent.com/111350940/191189455-658be568-28ad-4e8a-98cf-049bc157a350.png)

**Tooltip opent niet altijd**
Probeer nog een keer de tooltip te openen.
Merk op dat de tooltip soms kort verschijnt maar meteen ook weer verdwijnt.

**Voorbeeld**
Onderstaand voorbeeld komt uit uit het storybook: https://storybook.dso-toolkit.nl/44.0.0/?path=/story/core-viewer-grid--viewer-grid&args=filterpanelOpen:true
Deze heb ik aangevuld met een toggletip.

```html
<dso-viewer-grid filterpanel-open="">
  <!--?lit$55756462$-->
  <div slot="filterpanel">
    <!--?lit$55756462$-->
    <dso-toggletip>Toggletip content</dso-toggletip>
    <div class="alert alert-info">
      Dit is
      <code>slot="filterpanel"</code>
      .
    </div>
  </div>
  <div slot="main">
    <!--?lit$55756462$-->
    <dso-alert status="info">
      <div class="dso-rich-content">
        <!--?lit$55756462$-->
        <p>
          Dit is
          <code>slot="main"</code>
          .
        </p>
        <!--?lit$55756462$-->
      </div>
    </dso-alert>
  </div>
  <div slot="map">
    <!--?lit$55756462$-->
    <div class="alert alert-info">
      Dit is
      <code>slot="map"</code>
      .
    </div>
  </div>
  <!--?lit$55756462$-->
  <div slot="overlay">
    <!--?lit$55756462$-->
    <div class="alert alert-info">
      Dit is
      <code>slot="overlay"</code>
    </div>
    <div></div>
  </div>
</dso-viewer-grid>
```

**Comment by tfrijsewijk** [comment]
Ook dank voor deze melding!

Zou je wat markup kunnen copy/pasten? Dan kunnen wij het beter reproduceren in onze ontwikkelomgeving.

**Comment by MichielKadaster** [comment]
Ik heb de originele beschrijving aangepast.
Het punt mbt het scrollen ligt bij onze implementatie dus zullen we zelf moeten oplossen.
De overige punten heb ik laten staan en een voorbeeld toegevoegd.

**Comment by svrijsewijk** [comment]
Dit lijkt een issue met focus trap, zodra in de filterpanel een focusable element komt krijg je een focus trap op alleen de bovenste twee filter panel buttons.

**Comment by svrijsewijk** [comment]
opgelost in https://github.com/dso-toolkit/dso-toolkit/pull/1815
