### ISSUE TITLE
Iconen van zoeken en inloggen lijnen vreemd uit

### ISSUE THREAD

**Issue by WiebeCnossen** [dso-toolkit/dso-toolkit#176]
Als je in de header de searchbar niet geopend hebt, dan lijnen de twee iconen een beetje raar uit:

![image](https://user-images.githubusercontent.com/6065375/45427035-25cbc780-b69e-11e8-92c7-62e79f880379.png)

Zowel de onderkant als de bovenkant van het zoeken icoon staat hoger dan de onderkant resp. bovenkant van het inloggen icoon.

**Comment by tfrijsewijk** [comment]
Fixed in `3.0.0-beta.0`
