### ISSUE TITLE
Styling issues Document header

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#1760]
## Issues
- Als de 1e property van de status leeg is schuift het label op naar links maar niet voldoende
- In de smalste weergave van het linkerpaneel treden volgende visuele issues op:
- - Op de DL ontbreekt de margin-top 
- - Op DD staat een margin-top die er niet hoort

Zie ook afbeelding
![image](https://user-images.githubusercontent.com/506527/190352765-b32e84d7-7d51-423a-945e-b8f193ba3b2b.png)

**Comment by LiesbethVorst** [comment]
In overleg met @daverhelst besloten om nog een ander foutje mee te nemen in deze story: er worden verkeerde iconen gebruikt. Graag de gebruikte angles vervangen door chevrons (in de designs staan chevrons).
