### ISSUE TITLE
Elementen verdwijnen achter `dso-document-list-item`

### ISSUE THREAD

**Issue by MichielKadaster** [dso-toolkit/dso-toolkit#1764]
Voor de fix https://github.com/dso-toolkit/dso-toolkit/issues/1652 is een `float: left` toegevoegd aan `.dso-document-list-item-heading`.
Hierdoor heeft de parent div `.dso-document-list-item` geen hoogte meer en verdwijnt content achter de header.
De float zou opgeheven moeten worden met een `clear` zodat het andere elementen eromheen niet beinvloedt.

Ik zie dat jullie een `@include clearfix()` gebruiken op andere plekken, dat zou denk ik hier ook de oplossing zijn.

![image](https://user-images.githubusercontent.com/111350940/190391113-19d8bb93-ec8d-46f6-b98b-b1cacf29f3f5.png)

**Comment by tfrijsewijk** [comment]
Hi @MichielKadaster 👋 

Bedankt voor je melding, we gaan er naar kijken!

cc: @hansgrimm @svrijsewijk

**Comment by MichielKadaster** [comment]
Bedankt, nog nettere oplossing om helemaal geen float te gebruiken :)
