### ISSUE TITLE
Button selectors van Bootstrap (default en link) verwijderen

### ISSUE THREAD

**Issue by daverhelst** [dso-toolkit/dso-toolkit#1776]
In issue [1663](https://github.com/dso-toolkit/dso-toolkit/issues/1663) zijn de button selectors van Bootstrap deprecated. In dit issue zorgen we er voor dat deze stijling ook uit de toolkit wordt verwijderd.

**Comment by tfrijsewijk** [comment]
Ik zet 'm terug naar Refinement zodat ie morgen langskomt. Dit issue is immers zo oud, even opnieuw de aandacht kan geen kwaad.

**Comment by tfrijsewijk** [comment]
@MYpenburg gaat uitzoeken of zijn team nog gebruik maakt van de legacy selectors.

**Comment by MYpenburg** [comment]
PR12 zegt go
