### ISSUE TITLE
Header elementen kunnen over elkaar heen vallen

### ISSUE THREAD

**Issue by WiebeCnossen** [dso-toolkit/dso-toolkit#178]
![image](https://user-images.githubusercontent.com/6065375/45427274-ba362a00-b69e-11e8-9fa0-99a274c1835b.png)

**Comment by tfrijsewijk** [comment]
https://www.dso-toolkit.nl/3.0.0-alpha.2/components/detail/header.html

**Comment by tfrijsewijk** [comment]
@MichielDHVD Wat zou je willen op smalle viewports?

**Comment by PieterVerheij** [comment]
Ik zou op de smalle viewport de absolute postionering van inloggen en zoekbox opheffen, zodat deze naast elkaar komen te staan. Logo erboven met css-truukje oid.

**Comment by MichielDHVD** [comment]
Ik vind dit een goede oplossing @PieterVerheij zet maar door!

**Comment by MichielDHVD** [comment]
Er zijn soms verschillende hoogtes bij de afbeeldingen soms komt er bijvoorbeeld een woord bij. 

Omgevingsloket
Beheerportaal 

of 

Omgevingsloket
Catalogus

Dus ik weet niet of ik de vaste hoogte kan meegeven. Maar de catalogus maakt mogelijk zijn eigen header dus die valt waarschijnlijk al af. Maar het beheerportaal is compleet gebaseerd op de toolkit. Dus weet niet de consequenties. 

Maar als dit de oplossing is moet er dus een Logo strategie komen waarin wordt vastgesteld worden aan welke parameters het logo moet voldoen. 

Dan heb ik vervolgens nog een vraag. Mag het logo bijv 600px breed zijn maar wordt door de header naar 300px gezet worden. Voor een iets scherper logo bijv.

**Comment by PieterVerheij** [comment]
> Mag het logo bijv 600px breed zijn maar wordt door de header naar 300px gezet worden. Voor een iets scherper logo bijv.
Ja. Er zijn verschillende wegen naar Rome (zie ook http://www.enforme.com/blog-detail/2-ways-to-optimize-logos-retina-screens):
- We zouden jouw voorstel kunnen volgen: vastleggen dat een afbeelding altijd op 300px gezet wordt. Vul je dan een afbeelding van 600px dan toont hij scherper.
- Twee afbeeldingen aanbieden, die dan via een stukje css worden getoond

Maar het mooiste is natuurlijk de logo's als SVG plaatsen! :D

**Comment by PieterVerheij** [comment]
Maar een aanpassing van de volgorde in de html is uit den boze?

**Comment by PieterVerheij** [comment]
We ontkomen niet aan een aanpassing van de html en css. De voorgestelde wijziging is te bewonderen in https://github.com/dso-toolkit/dso-toolkit/pull/254

**Comment by PieterVerheij** [comment]
ping @MichielDHVD

**Comment by MichielDHVD** [comment]
Wat wordt er precies gevraagd ? 

Ik kan deze niet na lopen, ik kan de wijziging niet zien in #254. Moet ik controleren of deze naar Done kan? Thomas geeft meestal een link waar ik dit element kan nalopen en controleren. 

In de project lijn zetten we dan componenten op to verify.

**Comment by tfrijsewijk** [comment]
Het gaat om een voorstel, de code is niet nog gemerged in het eindproduct. Zoals aangegeven gaat dit om een breaking change en we willen graag input of dit markup is waar men (jij/developers) mee kan leven. Er zijn twee mogelijkheden en Pieter heeft er een uitgewerkt. We staan open voor aanpassingen/suggesties

**Comment by MichielDHVD** [comment]
Ik ga een developer vandaag even vragen om hier naar te kijken.

**Comment by MichielDHVD** [comment]
Gezien en getest. Werkt goed, compliment! 

Verplaatst naar done
