### ISSUE TITLE
Modal: Web Component

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#1793]
Modal is een goede kandidaat voor een web component. De huidige markup klopt wel (afgezien van een paar validatiefouten maar die hoeven waarschijnlijk niet te worden aangepakt). Maar in een web component kan veel vereiste functionaliteit al worden ingebouwd. Zie ter inspiratie onder meer het (wai-aria modal example|https://www.w3.org/TR/wai-aria-practices-1.1/examples/dialog-modal/dialog.html).

Bestaande html/css component:
https://dso-toolkit.nl/44.0.0/components/detail/modal--dialog.html

**Aandachtspunten:**
Er zijn meerdere modal vormen in de toolkit beschikbaar al. Het is slim om te kijken of de interactie patronen over al deze verschillende componenten consistent zijn. 

_Vergelijkbare componenten:_
In het viewer grid de varianten filter open en overlay open
Helpcenterpanel
Image Overlay

**Werkzaamheden**
Focus trap
Reageren op escape toets en eventueel enter (default button)
Focus gedrag binnen het dialoog en bij sluiten, moet de implementator van het web component het element kunnen aangeven dat bij sluiten focus krijgt?

**Testen**
Accessibility test door Tim in't Veld.

**Comment by hansgrimm** [comment]
Deze loopt door naar 24.5
