### ISSUE TITLE
Documentation: Layout

### ISSUE THREAD

**Issue by VolleMelk** [dso-toolkit/dso-toolkit#18]
Beschrijving van de layout en het 8px grid, ondersteund door images

**Comment by Poofy83** [comment]
Testable op de unstable branch: https://www.dso-toolkit.nl/unstable/docs/layout.html

/Original commenter: Thomas - 13-02-18 13:37

-----

Enigste wat nog hoeft worden aangepast is de laatste afbeeldingen veranderen naar degene die ik net heb toegevoegd en dan is deze klaar voor acceptatie.

/Original commenter: Michael - 22-02-18 10:21

-----

Is het prima als ik snel regel dat de afbeelding wordt vervangen door de juiste in de git repository?

/Original commenter: Michael - 28-02-18

-----

Prima. Je mag de repo zelf clonen of de juiste afbeeldingen als bijlage toevoegen

/Original commenter: Thomas - 28-02-18

-----

Ik heb jouw PR gemerged (super cool, eerste externe bijdrage!)

De plaat is hier te bewonderen: https://www.dso-toolkit.nl/unstable/docs/layout.html

/Original commenter: Thomas - 28-02-18
