### ISSUE TITLE
Document header: state toevoegen tbv sticky maken

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#1809]
### Aanleiding
De document header is steeds uitgebreider geworden en neemt inmiddels best wat ruimte in. Dat is bezwaarlijk omdat in beide viewers het de bedoeling is om de document header sticky in beeld te houden.
Daarom is het idee om als er in het document naar beneden wordt gescrolld dat de header dan alleen nog maar de titel toont (extra state van het component). Door klikken op de titel scrollt het document weer omhoog en wordt de header getoond in de state die deze had voor het scrollen (kan dus ook een opengeklapte state zijn).

### Werkzaamheden
- Extra state toevoegen
- Wordt opgelost in html/css
- Op basis van class klein maken en sticky maken. 
- Titel klein maken en content weghalen. 
- (Animatie buiten scope)
- Titel wordt button met chevron , scrolled omhoog (visueel een heading) 
- Afbreken op wat past (ellipsis)

### Ontwerp
<img width="743" alt="image" src="https://user-images.githubusercontent.com/91903058/194302013-0f28afa9-8b88-44dd-8474-eb617b8b7a6b.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/91903058/194302051-5ae42373-b445-4410-b0ae-b1bc6e6e87fa.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/91903058/194302074-19c3b8e5-8061-4e55-a7e5-5e8c5040b5d0.png">

**Comment by PieterVerheij** [comment]
https://storybook.dso-toolkit.nl/_1809-Document-header-state-toevoegen-tbv-sticky-maken/?path=/story/html-css-document-header--sticky

**Comment by LiesbethVorst** [comment]
Ik zie 2 kleuren grijs in bg van de sticky header: #EFEFEF en #F2F2F2. Volgens mij moet het #F2F2F2 zijn.

**Comment by LiesbethVorst** [comment]
Is het mogelijk om de hele balk klikbaar te maken? Nu zit er best wat padding om het klikbare gebied heen:
![image](https://user-images.githubusercontent.com/91903058/200550039-b767dd42-d4b2-4518-991f-478519a071c0.png)

**Comment by PieterVerheij** [comment]
@LiesbethVorst  

> Ik zie 2 kleuren grijs in bg van de sticky header: #EFEFEF en #F2F2F2. Volgens mij moet het #F2F2F2 zijn.

Ik zie dat niet. Kan je daar een screenshot van maken?

>Is het mogelijk om de hele balk klikbaar te maken? 

Aangepast

**Comment by LiesbethVorst** [comment]
@PieterVerheij  
Het binnenste deel (wat ik in screenshot hierboven donkerder grijs had gemaakt) is #EFEFEF:
<img width="499" alt="image" src="https://user-images.githubusercontent.com/91903058/200574279-9cebf1d3-8eeb-45c1-9d93-8c7382c2b8e4.png">

**Comment by PieterVerheij** [comment]
Ah ja, met het pipetje zie ik het. Tijd voor een nieuwe monitor! 
Opgelost.
