### ISSUE TITLE
Aanpassing iconenset en alert notificaties

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#1812]
## Iconen
- Deprecaten van status-danger
- Nieuw icoon status-error (rood)
- Nieuw icoon status-warning-inline (rood)
- Nieuw icoon status-warning-inline-negative (rood)
- Aanpassing icoon status-warning (geel)
- Aanpassing icoon status-success (grasgroen)
- Aanpassing icoon status-info (donkerblauw)
## Alerts
- alert-danger hernoemen naar alert-error
- alert-error gebruikt icoon status-error

![image](https://user-images.githubusercontent.com/506527/201081849-a83bf290-c6b9-4614-b542-0d05a5ac6ede.png)
![image](https://user-images.githubusercontent.com/506527/201081887-6c60ff76-bb33-4713-a50a-de58b6d81314.png)

**Comment by hansgrimm** [comment]
[iconen-svg.zip](https://github.com/dso-toolkit/dso-toolkit/files/9980351/iconen-svg.zip)
