### ISSUE TITLE
Highlightbox banner-image

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#1813]
**Aanleiding:**
Voor de homepage is een ontwerp gemaakt die niet compleet te realiseren is in de toolkit. Deze is wel live gezet met custom css door PR02. Deze CSS moet of de toolkit doen of PR02 moet een aanpassing gaan doen. 

**Ontwerp:** 

Visueel gewenste situatie live: https://dso-toolkit.nl/_POC-Nieuwe-Homepage-verbeteringen/components/preview/homepage.html
Voor de highlightbox wordt het mogelijk om een image te plaatsen en deze word dan als banner over de complete breedte van een highlightbox geplaatst.  

**Werkzaamheden:**

- Custom class maken voor img in highlightbox voorstel: dso-highlight-box-banner 
- Stijlen op first child selector
- Code PR02: 

`img.dso-highlight-box-banner {      width: calc(100% + 32px);      max-width: 100vw;      max-height: 150px;       object-fit: cover;      margin-left: -16px;      margin-right: -16px;      margin-top: -16px;    } `
 
**Test:**

Responsive testing

**Comment by PieterVerheij** [comment]
@hansgrimm @MichielDHVD Is dit echt een harde waarde die we gaan vastleggen?
`max-height: 150px;`

**Comment by hansgrimm** [comment]
@PieterVerheij als je de aspect ratio op die manier gaat afdwingen, moeten de <img>'s ook intrinsiek die verhoudingen hebben, anders krijg je visueel heel nare verschijnselen. In de 1-koloms layout gaat de <img> in de hoogte best wel veel ruimte pakken.

**Comment by PieterVerheij** [comment]
@hansgrimm Dat begrijp ik, maar met `max-height:150px` wordt het ook geen feestje als de highlightbox breder is:

![image](https://user-images.githubusercontent.com/25430835/199716838-88437cd6-90a3-46f9-a9d7-eb559cec7a5f.png)

Een andere optie is om geen formaat/beeldverhouding af te dwingen en het helemaal een redactionele verantwoordelijkheid te maken. Maar dat is een gewetensvraag ;-)

**Comment by MichielDHVD** [comment]
@PieterVerheij  Het maakt mij niet uit hoe de implementatie precies werkt. Ik heb een voorzet gedaan. 

Maar de wens is:
- Geen vervormde afbeeldingen 
- dat afbeeldingen dezelfde hoogte en breedtes hebben. 
- En dit komt aan de bovenkant van een highlightbox te staan. 

Dus de CSS die ik heb neergezet is niet heilig. Maar visueel moet het wel lijken wat tot nu toe is gerealiseerd.

**Comment by PieterVerheij** [comment]
@MichielDHVD is de beeldverhouding (2.38 / 1) op deze pagina wel definitief (zodat ik hem als vaste waarde in de css kan gebruiken)? https://dso-toolkit.nl/_POC-Nieuwe-Homepage-verbeteringen/components/preview/homepage.html

**Comment by MichielDHVD** [comment]
@PieterVerheij Ja die is definitief.
