### ISSUE TITLE
Webcomponent Accordion: Algemene verbeteringen

### ISSUE THREAD

**Issue by svrijsewijk** [dso-toolkit/dso-toolkit#1826]
* Als de attachmentcount van 1 naar 0 gaat dan verschijnt een 0 achter de heading.
* Styling: de onderste corners van het uitklap-gedeelte moeten radius 0 krijgen in uitgeklapte toestand
* De heading control lijkt geen effect te hebben, mogelijk de property ook niet.
* Wanneer de titel multi-line is centreert de tekst ongewenst.
* ~~documentatie voor `<dso-accordion-section>` tonen in storybook.~~ - Niet mogelijk

**Comment by MYpenburg** [comment]
Wens: als de chevrons links staan (reverseAlign false), gebruik dan een chevron-right als ingeklapt, en een chevron-down als uitgeklapt. Rechts-uitgelijnde chevrons blijven hetzelfde (ingeklapt -down, uitgeklapt -up)

> ingeklapte accordion 

V uitgeklapte accordion

ingeklapte accordion      V

uitgeklapte accordion     ^

**Comment by MYpenburg** [comment]
Animatie in accordion:
- Rotatie van chevrons bij open- en dichtklappen
- Uit- en inschuiven van content panel bij open- en dichtklappen
Beide met een lekkere maar onopvallende ease in en uit, niet te langzaam en niet te snel.

**Comment by LiesbethVorst** [comment]
Om de compacte variant ook compacter te maken zijn er een aantal visuele aanpassingen gewenst. Belangrijk verschil is dat er geen border meer zit onder de titel van een opengeklapte item.

**Compact**
![Accordion - compact](https://user-images.githubusercontent.com/91903058/199242505-4f83e875-d24f-4b1e-8675-3b53c7860ce4.png)

**Compact - reverse align**
![Accordion - compact - reverse align](https://user-images.githubusercontent.com/91903058/199242527-c45c827a-1c74-4a9d-9c91-06575cf36db5.png)

**Specs**
![Accordion compact - specs](https://user-images.githubusercontent.com/91903058/199242545-ae356036-526b-41df-bf09-263427273695.png)
