### ISSUE TITLE
Helpcenter panel: role=dialog op modal zetten

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#1835]
## Waar
core / Helpcenter Panel

## Aanleiding
Zelfevaluatie PR02.
De knop 'hulp nodig' opent een modal.
De aria op deze knop is conform de specificatie, maar op de modal zelf ontbreekt de vereiste role=dialog. Daardoor kondigt een screen reader niet aan dat een modal opent, en is er voor de virtuele cursor geen focus trap (voor de systeemcursos is die er overigens wel).

## Werkzaamheden
role = dialog op modal zetten
aria-label="helpcentrum" toevoegen
## Gebruikersimpact
Kritiek: een volledig blinde gebruiker begrijpt niet dat er een modal verschijnt. Als de virtuele focus de modal verlaat kan de gebruiker de weg kwijtraken en in het ergste geval vastlopen.

**Comment by svrijsewijk** [comment]
Ik heb @timveld gevraagd over `aria-labelledby`. 

Zijn reactie:
> Een dialog moet inderdaad een label hebben. Ik denk liefst volgens hetzelfde patroon als de paginatitel (dus iets als hulp bij vergunningcheck - helpcentrum") maar ik kan me voorstellen dat dit lastig is, omdat de implementator dan altijd de juiste titel moet meegeven. Mijn voorstel zou zijn om voor dit kritieke issue te volstaan met aria-label="helpcentrum", de discussie of en hoe we dat label moeten verduidelijken kunnen we dan voeren in een door mij nieuw aan te maken (veel minder prioritair) issue.

Ik heb 'aria-label="helpcentrum" toevoegen' toegevoegd aan de werkzaamheden.
