### ISSUE TITLE
Margins buttons vergroten - Whitespace bepalen (PI12)

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#184]
Sommige buttons hebben geen margins. Vanuit developers is de wens om met zo min mogelijk custom css te gaan werken. Daarom gaan we de white spaces in verschillende elementen zo goed mogelijk te verwerken dat alles bij elkaar aan sluit 

Specs volgen

**Comment by tfrijsewijk** [comment]
In welke situaties is dit een probleem?

**Comment by MichielDHVD** [comment]
Dit sluit ook een beetje aan op https://github.com/dso-toolkit/dso-toolkit/issues/233 . De optimale situatie zou zijn dat veel onderdelen hun marges al bepaald hebben. Dus dat bij implementatie alleen maar gedropped hoeft worden als het ware. 

Maar dit vereist natuurlijk veel afstemming tussen onderdelen onderling. 

Hier een voorbeeld waar het bijvoorbeeld nog niet lekker gaat. 

![image](https://user-images.githubusercontent.com/36912722/49582035-0a4a2300-f954-11e8-8707-1be7bcc19189.png)

De afstand tussen de accordeon en de tertiare knop en vervolgens de secundaire knop is heel erg krap

**Comment by tfrijsewijk** [comment]
@MichielDHVD: In hoeverre is dit nog een probleem met de nieuwe knoppen styling?

**Comment by MichielDHVD** [comment]
Weet ik niet precies. Maar Bram en ik zijn van plan om het spelen met margins zelf op te pakken. 

Ik ga templates bouwen van de belangrijkste pagina's die er zijn. Deze zullen veel van de huidige voorbeeld paginas vervangen. 

In de toekomst gaan wij proberen de kleinere css wijzigingen door te voeren. Dus deze mag mooi op mij assigned blijven en hoeven jullie niet naar om te kijken. 

Ik heb deze wel voor mij staan om dit increment een stap op te maken, anders wordt deze gesloten.

**Comment by MichielDHVD** [comment]
Dit issue wordt bij deze gesloten. Margins worden in zijn geheel toolkit breed in de toekomst onderzocht
