### ISSUE TITLE
Overlay toont geen shadow in Safari

### ISSUE THREAD

**Issue by kad-leeffs** [dso-toolkit/dso-toolkit#1840]
- Open Safari (op de Mac)
- Ga naar https://storybook.dso-toolkit.nl/45.2.0/?path=/story/core-viewer-grid--viewer-grid&args=overlayOpen:true
- Constateer dat er geen (donker) grijze overlay wordt getoond

![Schermafbeelding 2022-10-27 om 14 21 03](https://user-images.githubusercontent.com/66617030/198283250-05e27970-9fea-4fbb-a8e4-62aef59f0f26.png)

Verwacht: Wel een grijze overlay, zoals in bijv. Chrome

**Comment by hansgrimm** [comment]
![Schermafbeelding 2022-10-31 om 09 28 29](https://user-images.githubusercontent.com/506527/198964715-d0415e93-fb3a-4a7c-834d-316d1faec6a0.png)
Dit is het resultaat in Safari bij mij (Safari 16.0 op MacOS Monterey 12.6)

**Comment by hansgrimm** [comment]
Op een oude Safari TP (15.5) gaat het wel fout (geen overlay zichtbaar). Onderzoekstaakje.

**Comment by PieterVerheij** [comment]
Fixed in Safari 15.4: https://storybook.dso-toolkit.nl/_1840-Overlay-toont-geen-shadow-in-Safari/?path=/story/core-viewer-grid--viewer-grid&args=overlayOpen:true

Alleen is even een impact analyse nodig omdat `overflow: visible` is toegevoegd aan de `.overlay` div.

**Comment by hansgrimm** [comment]
Werkt bij mij in Safari 16.0
