### ISSUE TITLE
Keyboard focus state van <dso-selectable> niet duidelijk genoeg

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#1845]
De keyboard focus state van zowel de radiobutton als de checkbox zijn niet duidelijk genoeg. (alleen de rand wordt 1 px dikker, zie eerste screenshot)

Gewenst is om een duidelijker kader om de checkbox/radio inclusief het bijbehorende label te plaatsen.
![](https://jira.team-dso.nl/jira/secure/attachment/34264/screenshot-1.png)

![](https://jira.team-dso.nl/jira/secure/attachment/34265/screenshot-2.png)

**Comment by hansgrimm** [comment]
<img width="1185" alt="screenshot-1" src="https://user-images.githubusercontent.com/506527/199040160-1cef796f-14a7-4d88-b9a9-0eab97e5ec85.png">

**Comment by MYpenburg** [comment]
<img width="1333" alt="image" src="https://user-images.githubusercontent.com/7289928/202434881-0686bf5a-6ee9-4769-9a3e-d5f0fca30288.png">

**Comment by MYpenburg** [comment]
<img width="1333" alt="image" src="https://user-images.githubusercontent.com/7289928/202435330-7a7a90d7-e57b-416b-8a15-f1da5255f602.png">

Bijgevoegd voorbeeld ziet er in het ontwerpbestand iig goed uit en lijkt voldoende contrast te hebben met de palet-kleuren. De kleur van de border is 008CCC, 3 px dik, 3 px rounded en staat op een afstand van 2,5 pixel van het element. Kijk maar wat haalbaar is in deze richting. Niets is heilig, kleur is een probeersel, 2,5 pixel is natuurlijk niet te doen en wellicht mot er ook nog verplicht een randje wit bij... laten we iets proberen!

**Comment by MYpenburg** [comment]
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/7289928/202436092-2fb4e2b5-aa1c-4d44-b02e-0a2f0b5c40d1.png">

**Comment by tfrijsewijk** [comment]
Allereerst: Tenzij ik iets heb gemist is op dit moment de filosofie mbt. de focusstyling dat we die **niet** toepassen en het overlaten aan de user agent. Ik ben er helemaal mee akkoord als we dit loslaten.

Waarom breekt de focus styling bij de datepicker zo af? Is dit voortschrijdend inzicht en is specifiek voor het `input` element gekozen? Nu ik er nog een keer naar kijk, de focus styling klopt niet in combinatie met de zichbare kalender. De kalender toont zodra je op de date picker button klikt, en dan krijgt de huidige dag focus. Kan je hier meer over vertellen?

Wat betreft de focus styling over het selectable component, deze bieden we in twee implementaties aan (WC en HTML/CSS). Voor de HTML/CSS implementatie moet de afnemer zelf een modifier class zetten, het is niet mogelijk om het gewenste effect met styling op `:focus` te realiseren (edit: @svrijsewijk misschien een `::before` met `display: block;` die dan het volledige oppervlak van de `.dso-selectable` inneemt?)

Het Web Component is uiteraard geen probleem, dat kunnen we maken.

En willen we al nadenken over focus styling voor de accordion? Ik begrijp dat Hans een screenshot plaatst vanwege de selectable _in_ de accordion, maar de headers van een accordion kan ook focus krijgen.

**Comment by hansgrimm** [comment]
Met WCAG 2.2 heeft het W3C een opmerkelijke stap gezet door te impliceren dat de standaard user agent focus-state niet meer automatisch goed genoeg is: https://www.w3.org/TR/WCAG22/#focus-appearance (NB: status 'at risk').
cc @timveld

**Comment by hansgrimm** [comment]
Om de boel een beetje binnen de perken te houden, hebben we het hier alleen over de radio en checkbox. In de stretch goals staat nog een kaartje om de focus states over de hele linie recht te trekken. Naar verwachting een ambitie voor 2023 ;)

**Comment by tfrijsewijk** [comment]
OK! Helder.

**Comment by svrijsewijk** [comment]
Dit is best lastig. Ik heb even gekeken en het is denk ik voor het HTML/CSS component niet te implementeren zonder breaking markup changes te introduceren. de `div.dso-selectable` heeft `display: block;` waardoor de focus-rand veel breder wordt dan alleen de input+label.

Kwa modifier class: eventueel kan met :focus-within een en ander nog worden bereikt, alleen als in het label dan een tooltip oid. gaat het mis.

Zoals @tfrijsewijk heeft aangegeven is het prima toepasbaar in het WC.

**Comment by hansgrimm** [comment]
Je zou nog kunnen spelen met de `:has` pseudoclass, als je Firefox links laat liggen (https://caniuse.com/?search=%3Ahas)

**Comment by hansgrimm** [comment]
Het fixen van deze issue zou een breaking change opleveren in de html/css versie, dus deze ronde pakken we alleen het webcomponent aan. Overleg hans/Simon dd 07dec22.

**Comment by hansgrimm** [comment]
@svrijsewijk burning da midnight oil? 😎
