### ISSUE TITLE
Webcomponent Accordion: Animaties

### ISSUE THREAD

**Issue by svrijsewijk** [dso-toolkit/dso-toolkit#1846]
Animatie in accordion:

Rotatie van chevrons bij open- en dichtklappen
Uit- en inschuiven van content panel bij open- en dichtklappen
Beide met een lekkere maar onopvallende ease in en uit, niet te langzaam en niet te snel.

**Comment by MYpenburg** [comment]
Ik heb evt. voorbeeld css van ok animatie
