### ISSUE TITLE
ViewerGrid: dsoMainSizeChange 'end' fires too early

### ISSUE THREAD

**Issue by MichielKadaster** [dso-toolkit/dso-toolkit#1847]
De ViewerGrid component vuurt twee events af (start en end) wanneer de panelen van grootte wisselen.
Wij gebruiken het 'end' event om de grootte van onze kaart opnieuw in te stellen.
Maar het lijkt erop alsof het 'end' event te vroeg wordt afgevuurd terwijl de animatie nog bezig is waardoor onze kaart niet overeenkomt met de grootte van de uiteindelijke container waar die in zit.

Ik zie in de code van de component wel een timeout met `TRANSITION_TIME` staan die ervoor zou moeten zorgen dat het event pas fired nadat de animatie is afgerond.
Maar het lijkt er dus op dat het paneel dan nog bezig is met resizen en zijn uiteindelijke grootte nog niet heeft bereikt.

Zouden jullie kunnen checken of dit klopt?

**Comment by tfrijsewijk** [comment]
We gaan er naar kijken. Die dubbele transition time (in CSS en scripting) is natuurlijk 'n beetje onhandig.. Ik denk dat we iets met https://developer.mozilla.org/en-US/docs/Web/API/Element/transitionend_event moeten doen.

@LukeVerlaan iets voor jou?

cc: @svrijsewijk

**Comment by LukeVerlaan** [comment]
Ik wil hier wel naar kijken.
