### ISSUE TITLE
Accordeon font-size naar 20px

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#185]
Ergens dacht ik dat deze al was uitgevoerd. 

Maar alle teksten met de kleur oranje moeten naar 20px. Alleen bij Accordeon is dat nog niet gebeurd. Dit betekent dat alle titels in een accordeon naar 20px moeten. 

Omdat oranje in 18px niet de wcag haalt. Ik was alles persoonlijk nog eens aan het nalopen en toen kwam ik deze tegen.

**Comment by PieterVerheij** [comment]
@MichielDHVD We nemen aan dat je bedoelt dat EN de oranje (uitgelklapt) EN de groene (ingeklapt) teksten naar 20px moeten?

**Comment by MichielDHVD** [comment]
Ja allebei moeten naar 20 px om consistentie te houden. De oranje kleur is alleen de oorzaak waarom dit gebeurt.

**Comment by tfrijsewijk** [comment]
Uitgekomen in `3.1.0-alpha.0`.

Testable: https://www.dso-toolkit.nl/3.1.0-alpha.0/components/detail/accordion.html

**Comment by MichielDHVD** [comment]
Gezien en deze verplaats ik naar Done.
