### ISSUE TITLE
Dropdown Menu `.dropdown-menu-options` bevat elementen die niet zijn toegestaan

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#1853]
Tijdens het bijwerken van packages (#1852) is de accessibility definitie bijgewerkt en faalt de accessibility test van Axe:

![image](https://user-images.githubusercontent.com/9696261/199675769-590652ca-e810-4ebf-ac6b-712379080a61.png)

Dat komt vanwege de volgende markup:

```html
<div class="dso-dropdown-options" role="menu" aria-labelledby="_id_">
  <h2 class="dso-group-label">Tekst</h2>
  <ul role="none">[...]</ul>
</div>
```

http://localhost:45000/?path=/story/html-css-dropdown-menu--anchors

Volgende de foutmelding van Axe mag een `[role="menu"]` geen `h2` elementen bevatten.

Ik heb de accessibility test voor nu uitgezet, in dit issue moet de markup gefixed worden en de test weer worden aangezet. Zie de `Todo: ` in `cypress\integration\dropdown-menu-anchors.spec.ts`.

cc: @hansgrimm @timveld

**Comment by hansgrimm** [comment]
Ik vind het wel apart dat aXe niet struikelt over die lege <ul>, maar dat zal wel komen door die role=”none”; nooit getest zelf, maar dat lijkt logisch.

Die <h2> moet idd boven de role=”menu”, niet erin.

Even door de aXe documentatie zitten ploegen, zie geen optie om alleen een snippet niet te testen.

Met vriendelijke groet,
Hans Grimm | Grimm.nl BV

[Afbeelding met tekst, klok  Automatisch gegenereerde beschrijving]
T +31 6 22275783
E ***@***.******@***.***> :: W www.grimm.nl<http://www.grimm.nl/>
Grimm.nl BV, Valeriuslaan 55, 1422 HS Uithoorn – NL
KvK: 70294674 – BTW: NL858241997B01
LinkedIn: http://www.linkedin.com/in/hansgrimm


Van: Thomas Rijsewijk ***@***.***>
Datum: donderdag, 3 november 2022 om 09:45
Aan: dso-toolkit/dso-toolkit ***@***.***>
CC: Hans Grimm | Grimm.nl ***@***.***>, Mention ***@***.***>
Onderwerp: [dso-toolkit/dso-toolkit] Dropdown Menu `.dropdown-menu-options` bevat elementen die niet zijn toegestaan (Issue #1853)

Tijdens het bijwerken van packages (#1852<https://github.com/dso-toolkit/dso-toolkit/issues/1852>) is de accessibility definitie bijgewerkt en faalt de accessibility test van Axe:

[image]<https://user-images.githubusercontent.com/9696261/199675769-590652ca-e810-4ebf-ac6b-712379080a61.png>

Dat komt vanwege de volgende markup:

<div class="dso-dropdown-options" role="menu" aria-labelledby="_id_">

  <h2 class="dso-group-label">Tekst</h2>

  <ul role="none"></ul>

</div>

http://localhost:45000/?path=/story/html-css-dropdown-menu--anchors

Volgende de foutmelding van Axe mag een [role="menu"] geen h2 elementen bevatten.

Ik heb de accessibility test voor nu uitgezet, in dit issue moet de markup gefixed worden en de test weer worden aangezet. Zie de Todo: in cypress\integration\dropdown-menu-anchors.spec.ts.

cc: @hansgrimm<https://github.com/hansgrimm> @timveld<https://github.com/timveld>

**Comment by hansgrimm** [comment]
@timveld kan je hier even naar kijken?

**Comment by timveld** [comment]
@hansgrimm Volgens mij gaat dit issue over hetzelfde als #1918, of moet ik hier nog een andere vraag beantwoorden dan ik daar al heb gedaan?

**Comment by hansgrimm** [comment]
@timveld klopt. deze horen bij elkaar.

**Comment by daverhelst** [comment]
Is opgelost in #1918
