### ISSUE TITLE
Icoon toevoegen - meerdere kaartlagen

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#1859]
Voor de viewers is een icoon nodig voor "meerdere kaartlagen"
Het ontwerp voor het icoon is bijgevoegd.

![Meerdere kaartlagen 18dp](https://user-images.githubusercontent.com/36912722/200239573-b98ddf4e-a50f-4760-9364-fad9a2907514.svg)

**Comment by PieterVerheij** [comment]
Toegevoegd als icon `map-layers`.
