### ISSUE TITLE
Tertiare button 16px

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#186]
Toen de font sizes van de buttons waren verhoogd omdat de contrast waardes van de Oranje knop niet door de WCAG heen kwamen zijn alle knoppen meteen verhoogd. 

Nu is dat logisch voor de Primaire en Secundaire knop omdat die precies dezelfde vormgeving hebben alleen een iets andere kleuren stelling. 

Maar de tertiare knop heeft een andere functie. Kan deze terug gezet worden naar zijn oorspronkelijke grootte namelijk 16px.

**Comment by WiebeCnossen** [comment]
Wat bedoel je precies met 'andere functie' @MichielDHVD ? Vanuit het CMS gaan wij er nu van uit dat je buttons niet inline (dwz: binnen een lopende tekst) inzet, maar altijd als element in een eigen blok element.
Bedoel je met 'andere functie' dat je voorziet dat je dit element _wel_ als inline element kunt inzetten?

**Comment by MichielDHVD** [comment]
Nee andere functie is puur vanuit ux. 

De tertiare knop wordt vaak gebruikt als link naar andere pagina's. Meer een go to functionaliteit. Of als er een kruisje staat op de plek waar het pijltje staat bijvoorbeeld als annuleren knop. 

De primaire en secundaire knop staan vaak op dezelfde plekken op de pagina's dus die moeten consistent aan elkaar zijn. 

De tertiare knop vervult een iets andere rol binnen ons ontwerp dus hoeft qua tekst grootte niet gelijk zijn aan de primaire en secundaire knop.

**Comment by PieterVerheij** [comment]
@MichielDHVD ik ga ervan uit dat het icoon ongewijzigd blijft en alleen het font verkleind wordt.

**Comment by MichielDHVD** [comment]
@PieterVerheij Klopt helemaal. Icon size blijft het zelfde alleen Fontsize wordt verkleind.

**Comment by MichielDHVD** [comment]
Gezien, en verplaatst naar done.

**Comment by tfrijsewijk** [comment]
Fixed in `3.1.0-alpha.1`: https://www.dso-toolkit.nl/3.1.0-alpha.1/components/detail/buttons.html

**Comment by MichielDHVD** [comment]
Goedkeurd wordt verplaatst naar done
