### ISSUE TITLE
Menu knop mobile in header + Vormgeving mobile header

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#187]
Nieuwe vorming menu knop voor de header. Plus locatie van de elementen bij mobiele weergave

Specificaties volgen

**Comment by PieterVerheij** [comment]
Is het geen optie om de elementen gewoon te laten wrappen?

![image](https://user-images.githubusercontent.com/25430835/46535402-96d05a80-c8ab-11e8-9777-f5be1b935c74.png)

**Comment by MichielDHVD** [comment]
In issue https://github.com/dso-toolkit/dso-toolkit/issues/178 is er een oplossing door @PieterVerheij aangedragen:

_" Ik zou op de smalle viewport de absolute postionering van inloggen en zoekbox opheffen, zodat deze naast elkaar komen te staan. Logo erboven met css-truukje oid. "_ 

Lijkt me slim om deze door te voeren.

**Comment by tfrijsewijk** [comment]
@MichielDHVD: Volgens mij hebben we dit issue niet meer nodig en kan deze gesloten worden. Wat jij?

**Comment by MichielDHVD** [comment]
Ik denk dat ik dit issue moet omvormen of een ander issue voor maken. Het hamburger menu heeft namelijk een stijl die niet past bij de huidige huisstijl. Die moet nog aangepast worden. Maar deze issue gaat inderdaad ook over issues die in een ander issue zijn opgelost. 

Daarom sluit ik deze en maak ik een los issue aan voor het oplossen van de menu balk vormgeving.
