### ISSUE TITLE
Incomplete templates in voorbeeldpagina's nalopen

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#1872]
In #1844 is het model van ApplicationHeading aangepast waarmee de title optioneel is geworden. Dit moest omdat dit in voorbeeldpagina's met handmatige markup was gerealiseerd.

Ook naar https://github.com/dso-toolkit/dso-toolkit/pull/1848/files#r1014388609 kijken. Want het lijkt erop alsof een component misbruikt wordt.

cc: @michieldhvd

**Comment by MichielDHVD** [comment]
Met Dion het volgende besproken. 

Verkeerd gebruik Context wrapper
 1. Inventarisatie maken van waar de context wrapper wordt gebruikt. 
 2. Wat voor oplossing gaan we maken voor het rechts uitlijnen van componenten (Refinement bespreken)
 
 Incomplete templates:
 - Bepaalde templates zijn niet overgezet omdat deze niet up to date waren. Samenwerken en helpcentrum 
 - Pagina's updaten door Michiel (miss eerste keer pagina's bouwen in storybook leren) 
 
 @tfrijsewijk Is dat wat er bedoeld werd met incomplete templates Thomas in de titel van het issue? De ontbrekende voorbeeldpagina's

**Comment by MichielDHVD** [comment]
@gofix 
Deze story zit wel in de sprint, maar zijn eigenlijk twee issues geworden. 

De incomplete templates = voorbeeldpagina's.  https://github.com/dso-toolkit/dso-toolkit/issues/2024 
Context component dat misbruikt is is dit issue geworden = https://github.com/dso-toolkit/dso-toolkit/issues/1933
