### ISSUE TITLE
Accordion webcomponent uitbreiden met scrollIntoView functionaliteit

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#1875]
Het zou handig zijn om een functionaliteit toe te voegen waardoor de inhoud van een bepaald accordion panel binnen de viewport kan worden gescrolled, rekening houdend met:

## animatie (niet abrupt)
- de wenselijkheid om een flink deel (vanaf de bovenkant) van de content in beeld te krijgen (in plaats van de bovenste pixel)
- deze functie moet apart aan te roepen zijn
- deze functie kan ook worden meegegeven als parameter aan de toggle functie
- de functie moet ook werken als meerdere accordions tegelijk open mogen zijn
- Standaard wordt bij het togglen via de muis/toetsenbord ook scrollIntoView uitgevoerd.

**Comment by MYpenburg** [comment]
Belangrijk vanuit PR12: animatie moet compatible zijn met iframe resizer!!!

**Comment by svrijsewijk** [comment]
@MYpenburg nu ik wat meer van de iframe resizer begrijp denk ik dat het geen issue is. De div die bij jullie de hoogte bepaald wordt bij het uitklappen netjes naar beneden geduwt omdat de accordion ruimte inneemt. Ik verwacht hier geen issues.

**Comment by svrijsewijk** [comment]
> @MYpenburg nu ik wat meer van de iframe resizer begrijp denk ik dat het geen issue is. De div die bij jullie de hoogte bepaald wordt bij het uitklappen netjes naar beneden geduwt omdat de accordion ruimte inneemt. Ik verwacht hier geen issues.

Inmiddels denk ik dat dit juist helemaal niet gaat werken. het is heel lastig om buiten je iframe te scroll. de 'window' is namelijk het iframe.

**Comment by hansgrimm** [comment]
Als ik het goed begrepen heb, wil men voor livegang alle iframes opruimen. 
met dat in gedachten, is het zinvol om hier nog heel veel moeite in te steken?

**Comment by hansgrimm** [comment]
Kennelijk wel :)
