### ISSUE TITLE
Web component dso-table modal volledige hoogte kunnen benutten

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#1879]
Een paar bugjes in de tabelcomponent en het uitspringen ervan:

 ̶1̶.̶ ̶I̶n̶ ̶d̶e̶ ̶s̶t̶a̶n̶d̶a̶a̶r̶d̶ ̶i̶n̶l̶i̶n̶e̶ ̶w̶e̶e̶r̶g̶a̶v̶e̶ ̶i̶s̶ ̶d̶e̶ ̶k̶n̶o̶p̶ ̶o̶m̶ ̶u̶i̶t̶ ̶t̶e̶ ̶s̶p̶r̶i̶n̶g̶e̶n̶ ̶u̶i̶t̶ ̶b̶e̶e̶l̶d̶ ̶g̶e̶s̶c̶r̶o̶l̶d̶.̶ ̶H̶i̶j̶ ̶i̶s̶ ̶p̶a̶s̶ ̶t̶e̶ ̶v̶i̶n̶d̶e̶n̶ ̶b̶i̶j̶ ̶n̶a̶a̶r̶ ̶r̶e̶c̶h̶t̶s̶ ̶s̶c̶r̶o̶l̶l̶e̶n̶.̶
moet in implemantatie opgelost worden.

2. Na klikken op vergroten verschijnt de tabel achter een witte laag.

![image](https://user-images.githubusercontent.com/506527/202441367-b15263cb-efa4-4c38-85af-021a80ad21d0.png)

## Reproductiepad
Nog niet op acceptatie uitgerold:

https://snapshot.viewer.dso.kadaster.nl/viewer/document/_akn_nl_act_pv26_2022_1_1_akn_nl_bill_pv26_2022_1_12/beleid?locatie=Perceel%20De%20Bilt%20(BIL01)%20D%209008&documenten=%5B%7B%22documentId%22:%22_akn_nl_act_pv26_2022_1_1_akn_nl_bill_pv26_2022_1_12%22,%22documentType%22:%22Omgevingsvisie%22%7D%5D&isOntwerp=true

3. De weergave van de grote tabel. pakt niet de beschikbare hoogte van het scherm.

**Comment by svrijsewijk** [comment]
Ik twijfel of dit nu een bug is, we hebben in het viewer-grid lokaal een `<dso-table>` component geplaatst. Deze gedraagde zich zoals verwacht:
![image](https://user-images.githubusercontent.com/21218284/203595373-d579dbc5-28e3-4858-bff3-a319423862f8.png)

Het lijkt erop dat er in bovenstaand screenshots de `<dso-table>` in `view-grid` breeder is dan het paneel. Ik vermoed zodra dat opgelost wordt in de implementatie dat de tabel gaat tonen zoals het hoort.

**Comment by hansgrimm** [comment]
dus dit is een "won't do"?

**Comment by DjangoBlok** [comment]
@hansgrimm alleen het eerste punt niet.
Er staan twee andere punten in dit ticket die wel moeten worden opgelost.

**Comment by hansgrimm** [comment]
klopt, is een aparte issue voor aangemaakt.

**Comment by svrijsewijk** [comment]
Voor punt 2 is een oplossing gemaakt in https://github.com/dso-toolkit/dso-toolkit/issues/1902

Ik hernoem de titel van dit ticket om het resterende punt beter te omvatten.
