### ISSUE TITLE
Hamburger menu documentatie bijwerken met instructies voor scripting

### ISSUE THREAD

**Issue by Arcturus5404** [dso-toolkit/dso-toolkit#188]
Als het scherm te klein wordt, dan wil het menu niet meer uitklappen waardoor het onbruikbaar wordt

**Comment by PieterVerheij** [comment]
Hi @Arcturus5404 Heb je hier een url van? 
Voor het openen van het menu is het noodzakelijk dat de class ".dso-open" op de ".dso-navbar" komt te staan.

**Comment by Arcturus5404** [comment]
https://www.dso-toolkit.nl/3.0.0/components/preview/header.html

verklein je browser.. klik op de hamburger

**Comment by Arcturus5404** [comment]
ik kan deze natuurlijk zelf toggelen
