### ISSUE TITLE
Jumbotron deprecaten

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#1880]
Deprecation notice + eruit vlgs afspraak

**Comment by tfrijsewijk** [comment]
@hansgrimm Waar is dit ding? Ik kan in de codebase niets vinden over 'n jumbotron. We hadden 'm vroeger wel, maar dat was echt heel lang geleden..

![image](https://user-images.githubusercontent.com/9696261/205602928-14a1445f-b7b7-40b5-8ca5-3e3557c75102.png)

Ergens in versie 2.0.0 zeggen we er wat over, maar ik denk dat deze al eens 'n keer is verwijderd maar dat we dat niet goed hebben gedocumenteerd..

**Comment by hansgrimm** [comment]
Mij werd verteld dat dit component niet meer in de documentatie, maar nog wel in de codebase voorkwam.

Als dat laatste inderdaad ook niet meer het geval is, dan kan deze naar "won't do". Eens, @MichielDHVD ?

**Comment by MichielDHVD** [comment]
Als er niks te verwijderen valt is het klaar. Won't do prima.
