### ISSUE TITLE
ozon-content kan lege titels/bijschrift div renderen bij image-overlay

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#1881]
##vEen aantal bugjes in de image overlay:

- De marge tussen de afbeelding en het bijschrift is te groot.![image](https://user-images.githubusercontent.com/506527/202442189-76053b63-5b85-4f2d-8475-c1e00654a979.png)

- In de overlay verschijnt in de linkerbovenhoek een wit blokje (waarschijnlijk in het geval er geen titel is)

- Er zit een transparant gat onder de foto binnen het witte kader. Hier zou het bijschrift in getoond moeten worden (op een witte achtergrond).![image](https://user-images.githubusercontent.com/506527/202442264-2d30b9e2-afd7-46a5-92a4-d24bcfdfbc13.png)

**Comment by svrijsewijk** [comment]
Dit is een bug in ozon-content. Niet de image overlay. De ozon-content rendered onterecht een lege `<div slot="bijschrift"`> in `<dso-image-overlay>` als er geen bijschrift is. (hetzelfde gaat mis voor de `title`)

Wat betreft de marge: Ik denk dat de applicatie stijling hier per onbedoeld ook de `<span class="figuur-bijschrift">` stijlt met marge. Binnen de dso-toolkit zetten we deze niet. het ozon-component maakt geen gebruik van shadow-dom waardoor het mogelijk is voor applicatie-stijling om de HTML van dit component te raken.

Ik pas de titel aan
