### ISSUE TITLE
SCSS variabelen beschikbaar maken

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#1882]
## Aanleiding: 
Bij de toolkit retro kwam het naar voren dat het niet makkelijk is om variabelen makkelijk te gebruiken als men iets wil bouwen. 

Onderzoek? Is het nog nodig om eerst een inventarisatie te maken?  

## Werkzaamheden:
- Variabelen beschikbaar stellen via een centrale ontsluiting
- Details?

**Comment by tfrijsewijk** [comment]
Dit pak ik wel op in het kader van het omschrijven van het koppelvlak van de toolkit: https://dso-toolkit.nl/master/voor-developers/api
