### ISSUE TITLE
Modal Webcomponent: Mogelijk maken sluitkruis te verbergen - Grijze overlay toont soms voor het modal

### ISSUE THREAD

**Issue by svrijsewijk** [dso-toolkit/dso-toolkit#1884]
> Op 2 plaatsen ligt de via selector body.dso-modal-open::before gerealiseerde “grijze” achtergrond overlay niet achter de modal, maar ook over de modal heen. Help!
VRK heeft een html/css versie zonder sluitkruisje (zie de afbeelding); dit kunnen we uiteraard realiseren met de html/css versie, maar niet met de webcomponent-versie. In ieder geval kan ik geen setting vinden die dit evt mogelijk zou kunnen maken. (even afgezien van de mogelijk ongelukkig gebruikers interactie, want er is geen keuze)

Django en Liesbeth:
>Hmm, ik denk wel dat het sluiten kruis een optie zou moeten zijn van dit component.
In dit specifieke geval (een disclaimer) willen we dat iemand niet gewoon de modal sluit maar op “akkoord” klikt om verder te kunnen gaan. En is het dus juist goed dat er geen sluitenkruis is.

De achtergrond overlay gaan we oplossen

**Comment by hansgrimm** [comment]
ivm de combi verbetering/bug deze issue maar 2 types toegekend :)

**Comment by svrijsewijk** [comment]
https://github.com/dso-toolkit/dso-toolkit/issues/1902 aangemaakt voor vervolg grijze overlay

**Comment by hansgrimm** [comment]
Bikkel :)
