### ISSUE TITLE
dso-ozon-content: html wordt weergegeven als tekst

### ISSUE THREAD

**Issue by MichielKadaster** [dso-toolkit/dso-toolkit#1888]
de `dso-ozon-content` component wordt de XML omgezet om de content te renderen.
Wij krijgen de melding dat dat sommige html-entities niet worden omgezet:
![image](https://user-images.githubusercontent.com/111350940/202998142-6c6f0970-a55b-4389-9858-22aae337fae8.png)

![image](https://user-images.githubusercontent.com/111350940/202997982-8d48be0d-a8ed-492f-98a3-f3507d5739b5.png)

Zouden jullie willen kijken waar dit mis gaat?

**Comment by hansgrimm** [comment]
Hallo @MichielKadaster, we pakken 'm op.

**Comment by hansgrimm** [comment]
URL zou handig zijn.

**Comment by DjangoBlok** [comment]
https://acceptatie.viewer.dso.kadaster.nl/viewer/document/%2Fakn%2Fnl%2Fact%2Fgm0855%2F2022%2Fomgevingsplan-staalkaart/regels?beschikbaarOp=2022-10-20T11:28:53.247542Z&inWerkingOp=2022-07-23&geldigOp=2022-07-23

wachtwoord is bekend toch?

**Comment by hansgrimm** [comment]
@DjangoBlok: 
https://acceptatie.viewer.dso.kadaster.nl/viewer/document/%2Fakn%2Fnl%2Fact%2Fgm0855%2F2022%2Fomgevingsplan-staalkaart/regels?beschikbaarOp=2022-10-20T11:28:53.247542Z&inWerkingOp=2022-07-23&geldigOp=2022-07-23

wachtwoord is bekend toch?

**Comment by tfrijsewijk** [comment]
Ik denk dat dit een fout in de content is. Het lijkt erop alsof de content tweemaal is geescaped.

De originele waarde is `Het &amp;lt;&amp;lt;naam programma&amp;gt;&amp;gt; van`, wat zou je verwachten dat er toont?

Als ik eenmaal en daarna nogmaals unescape ziet dat er zo uit:

```
// origineel
Het &amp;lt;&amp;lt;naam programma&amp;gt;&amp;gt; van

// eenmaal unescape
Het &lt;&lt;naam programma&gt;&gt; van

// nogmaals unescape
Het <<naam programma>> van
```

Ik kan mij niet voorstellen dat het de bedoeling is dat wij de waarde moeten unescapen om vervolgens onveilig in het DOM te plaatsen.

Edit: **En trouwens, dit is helemaal geen XML.** Aan de Ozon API kan je een vlaggetje meegeven (header? query param?) waarmee de properties `inhoud` geen HTML maar XML bevatten. Het Ozon Content component kan niet met HTML overweg.

**Comment by hansgrimm** [comment]
Zoiets had ik ook al uitgeknobbeld inderdaad, dus +1.

**Comment by MichielKadaster** [comment]
Oke, bedankt voor het uitzoeken.
Ik had inderdaad niet gezien dat er wel degelijk een transformatie plaatsvindt.
De content lijkt inderdaad onlogisch.

**Comment by tfrijsewijk** [comment]
Graag gedaan.

Los van het transformeren, kijk nog even naar HTML vs. XML, want het Ozon Content component is niet bedoeld om HTML te verwerken.

**Comment by MichielKadaster** [comment]
Yes dank je, dit gaan we aanpassen
