### ISSUE TITLE
Header: smalle viewport: Menu toont niet bij dropdownmenu never, en sub-logo valt buiten de header

### ISSUE THREAD

**Issue by svrijsewijk** [dso-toolkit/dso-toolkit#1889]

**Comment by LukeVerlaan** [comment]
"Menu toont niet bij dropdownmenu never" heb ik volgens mij al bij https://github.com/dso-toolkit/dso-toolkit/pull/1886/files opgelost, maar dat mag zeker nog wel gecontroleerd worden.

**Comment by svrijsewijk** [comment]
opgelost in https://github.com/dso-toolkit/dso-toolkit/pull/1897
