### ISSUE TITLE
percy.cy.ts faalt incidenteel

### ISSUE THREAD

**Issue by svrijsewijk** [dso-toolkit/dso-toolkit#1899]
Bijvoorbeeld hier:
https://app.travis-ci.com/github/dso-toolkit/dso-toolkit/jobs/589307029

**Comment by tfrijsewijk** [comment]
@LukeVerlaan Wil jij deze doen? Ik kan dit lokaal met enige regelmaat reproduceren.

Ergens gaat er iets mis (duh). Ik verdenk de automatische URL redirect van Storybook: Als een url een `?id=story` _zonder_ variant (dus `?id=story--variant`) heeft lijkt het erop dat Storybook een redirect naar de enige/default variant doet. Dit geldt ook voor het openen van Storybook _zonder_ story: De eerste story wordt dan opgehaald. Ik denk dat op dat moment Cypress de weg kwijt raakt. Maar dit is speculeren.

Mogelijke oplossingen maar niet beperkt tot:
* Betere assertions waardoor de test langer robuster wordt.
* `cy.visit()` uitbreiden met de eerste story (accordion geloof ik) en variant.

Succes! Laat @svrijsewijk maar reviewen, hoe eerder dit gemerged is hoe beter..

**Comment by LukeVerlaan** [comment]
Mijn vermoeden is dat het inladen van de iframe de boosdoener is. Dat wanneer de iframe net voor de `.click()` wordt ingeladen, de test faalt.
