### ISSUE TITLE
Small button met icon voor toelichtingen. 

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#190]
Op dit moment worden er toelichtingen ontwikkeld. 

En moet er een toevoeging worden gedaan aan de formfields. Namelijk het knopje achter het form field in onderstaande afbeelding
![toelichtingen](https://user-images.githubusercontent.com/36912722/46070587-78b57c80-c17e-11e8-8add-bd159215e687.png)

![image](https://user-images.githubusercontent.com/36912722/46070605-83701180-c17e-11e8-9ba1-6794fcc0f46b.png)

![image](https://user-images.githubusercontent.com/36912722/46070621-908d0080-c17e-11e8-9646-863f63e9e8e1.png)

![image](https://user-images.githubusercontent.com/36912722/46070648-9d115900-c17e-11e8-98cb-de85429f771b.png)

Het knopje met de i (genomen uit font awesome ) staat achter het form field en is onderdeel van de 50% van het invoerveld. 

De knop zelf is eigenlijk een verkleining van de tertiare knop de hover en focus states zijn hetzelfde alleen staat er geen tekst achter en is de knop 16 px bij 16px. 

De developers willen al aan de slag met bouwen, wat voor place holder zouden ze hiervoor kunnen gebruiken?  @tfrijsewijk 

Is het misschien een idee om een small version van de tertiare knop te maken of is dat dan weer too much?

**Comment by PieterVerheij** [comment]
@MichielDHVD 
Wat als een veld verplicht is EN je hebt een i-knopje? Staat de i dan rechts van de tekst 'verplicht'?
In het ontwerp is er ruimte rechts van de invoervelden gereserveerd, staat het i-knopje daar bewust niet?
Valt de uitklaptekst (op grijze achtergrond) buiten het kader van dit ticket en is daar een ander ticket voor (heeft wel de voorkeur).

**Comment by tfrijsewijk** [comment]
Zoals bij het ontwerp in issue #32: https://github.com/dso-toolkit/dso-toolkit/issues/32#issue-297830587

**Comment by MichielDHVD** [comment]
Het ontwerp dat @tfrijsewijk aanhaalt is een verouderd ontwerp. In de laatst beslissing betreffende toelichtingen is bepaald dat het icoontje achter de vraag komt. 

Ik voeg even voor de beeldvorming en de discussie een ontwerp toe waar beiden versies te zien zijn. Zowel bij een korte vraagstelling en een langere vraag stelling. 

![verplicht met informatie - lang en kort](https://user-images.githubusercontent.com/36912722/46786981-c0b7d000-cd36-11e8-921c-3dd46b281f0c.png)

Deze wordt ook nog even voorgelegd aan de rest van het UX team.

**Comment by tfrijsewijk** [comment]
@MichielDHVD Kun je de iconen ook aanleveren? Ik zie tussen de ontwerpen verschillende iconen.

Kun je ook een definitie van de hover/focus/active states geven?

**Comment by MichielDHVD** [comment]
Zal ik doen. 

En de verschillende versies komt omdat ik de iconen te groot had staan uit een oudere versie.  Excuses voor de onduidelijkheid. Ik voeg vandaag nog even de states en het ontwerp toe. 

In praktijk is het een font-awesome info icon. Dus qua gedrag en look komt het veel overeen met de tertiare knop maar dan kleiner.

**Comment by tfrijsewijk** [comment]
Is het mogelijk dat er een ander icoon komt te staan? Ofwel: Krijgt de implementator de vrijheid om zelf een icoon te kiezen?

**Comment by MichielDHVD** [comment]
In dit geval zal dat niet nodig. Het blijft beperkt tot alleen het I'tje

**Comment by MichielDHVD** [comment]
Met Ux-team is besloten om het I'tje achter verplicht te zetten.  

![verplicht -info - achter](https://user-images.githubusercontent.com/36912722/46797680-1c428780-cd50-11e8-931f-071064f432bf.png)

**Comment by tfrijsewijk** [comment]
Ok. Dan nog het icoon: Je zegt dat het een Font-Awesome icoon is. De toolkit heeft FA5. Als ik zoek op "info" kom ik de volgende iconen tegen:

![image](https://user-images.githubusercontent.com/9696261/46799694-bbb64900-cd55-11e8-8ba1-909df1a7584d.png)
https://fontawesome.com/icons?d=gallery&q=info

De laatste twee iconen hebben een PRO license nodig, die we (nu?) niet hebben. Gaan we een PRO license aanschaffen of nemen we een ander icoon?

**Comment by MichielDHVD** [comment]
Het loopt hier helemaal door elkaar heen. Ik krijg letterlijk net een lading specs binnen betreffende toelichtingen. 

A) Voor een nieuw component dat ik later ga aanmaken 

B) Er zitten ook afbeeldingen bij voor de icoontjes. 

![tooltip_actief](https://user-images.githubusercontent.com/36912722/46803367-32f0da80-cd60-11e8-979c-b0a461b82d9c.png)
![tooltip_info](https://user-images.githubusercontent.com/36912722/46803368-32f0da80-cd60-11e8-86e0-29398251f33c.png)

Ze heten nu tooltip wat verwarrend klinkt ivm met andere component deze zullen dus een andere naam moeten krijgen. 

Verder kwam ik dit icoon in font-awesome tegen. 
https://fontawesome.com/v5.0.6/icons/info?style=solid Maar deze is dus overbodig geworden. 

Excuses voor het ongemak.

**Comment by tfrijsewijk** [comment]
In #203 zie ik dat het icoontje ook achter het veld kan komen te staan als het een checkbox/radio is. Zijn dit de enige uitzonderingen? Kun je dit beschrijving in dit ticket, dan nemen we ze mee

**Comment by MichielDHVD** [comment]
Ik ga het even navragen. Anders moet het gemaakt worden.

**Comment by MichielDHVD** [comment]
@PieterVerheij Allebei opgeleverd in .svg . Als je meer nodig hebt laat maar weten. 
[Icoon_Rond.zip](https://github.com/dso-toolkit/dso-toolkit/files/2505043/Icoon_Rond.zip)

Heb je gehoord van de Slack pieter? Of vind je dat geen fijne werk vorm. Het is makkelijk om snel vragen te stellen.

**Comment by tfrijsewijk** [comment]
>Heb je gehoord van de Slack pieter? Of vind je dat geen fijne werk vorm. Het is makkelijk om snel vragen te stellen.
Pieter zit op slack, username "Pieter Verheij"

**Comment by tfrijsewijk** [comment]
Wat zijn de hover/focus states van de iconen? De open-state (groen gevuld) zou als hover/focus state gebruikt kunnen worden voor closed-state (wit gevuld), maar als een actief icoon een hover/focus krijgt wat dan?

**Comment by tfrijsewijk** [comment]
Uitgekomen in `3.1.0-alpha.5`.

Zie alle formulier componenten op https://www.dso-toolkit.nl/3.1.0-alpha.5/

**Comment by MichielDHVD** [comment]
Gezien en verplaatst naar done
