### ISSUE TITLE
Webcomponent header - verbeteringen

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#1904]
Het is mogelijk om de header de optie never mee te geven als het gaat om een dropdown menu. 

Als je dit doet dan komt er nooit een dropdown menu. Voor deze vorm is nooit een ontwerp gemaakt, en is ook niet gewenst.  

## Werkzaamheden: 
- Optie never niet beschikbaar maken in webcomponent
- chevron van de meer knop is grasgroen - deze moet bosgroen zijn gelijk aan de tekst
- Term Dropdown-menu aanpassen naar Compacte header (opties always en auto blijven hetzelfde)

**Comment by MichielDHVD** [comment]
Toevoeging:

In storybook staat de header + sublogo zoals we dit willen zien. 
![image](https://user-images.githubusercontent.com/36912722/208636052-b7482e2d-ac42-4011-9c80-9dafa73c4a59.png)


Dit wit ruimte klopt precies. Maar dit is niet wat je krijgt als je de header implementeert. Want hier staat het webcomponent nog niet in een header tag zoals het hoort. En wanneer je het webcomponent in een header tag stopt gebeurt het volgende. 
![image](https://user-images.githubusercontent.com/36912722/208636214-c116a039-f81e-466a-a432-0cdfe4bbdfae.png)


Dit gebeurt wanneer de class .logo op een element in de header staat. Dan wordt het logo 300 px breed. 
![image](https://user-images.githubusercontent.com/36912722/208636262-9b2b9d7b-3f86-40d1-9338-30a7ec8b961e.png)

**Comment by PieterVerheij** [comment]
@hansgrimm de text van de meer-knop is ook grasgroen, ik neem aan dat deze ook basgroen moet worden?
![image](https://user-images.githubusercontent.com/25430835/210768774-5070f72d-636f-4e2f-9f1a-022acd077f33.png)

**Comment by hansgrimm** [comment]
Volgens mij wel, maar check dat ook even met UX.

**Comment by PieterVerheij** [comment]
@MichielDHVD kan jij daar (tekstkleur meer-knop) uitsluitsel over geven?

**Comment by hansgrimm** [comment]
> @MichielDHVD kan jij daar (tekstkleur meer-knop) uitsluitsel over geven?
> 
> Wat betreft de ruimte tussen het logo, die komt door legacy css:
> 
> ```
> header .logo {
>     width: 300px;
> }
> ```
> 
> Wanneer wij dit aanpassen naar
> 
> ```
> header > :not(.dso-header) .logo {
>     width: 300px;
> }
> ```
> 
> is dat opgelost, maar dat impliceert wel dat er NOOIT een div tussen `header` en `.dso-header` mag staan. Een andere oplossing is om te wachten totdast `legacy-header.scss` naar de eeuwige jachtvelen gaat, want dan zijn we dat stuk css ueberhaupt kwijt.
> 
> Waar gaat jullie voorkeur naar uit?

Ik ben als css-architectuur-nerd geen liefhebber van de `:not` selector; als je de cascade goed voor mekaar hebt, zou het niet nodig moeten zijn om tegen de stroom op te zwemmen. Kan je daar nog eens naar kijken?

**Comment by tfrijsewijk** [comment]
>[...] als je de cascade goed voor mekaar hebt, zou het niet nodig moeten zijn om tegen de stroom op te zwemmen. Kan je daar nog eens naar kijken?

We hebben het hier over een legacy component wat een modern component in de weg zit. We gaan het moderne component geen rekening laten houden met 'n legacy component, en we gaan het legacy component niet aanpassen.

Er is hier dan ook geen sprake van een CSS cascade die wel/niet goed zou zijn. Er zijn twee componenten die elkaar in de weg zitten. Uitstekend idee om hier een `:not()` selector voor in te zetten.

Dus we kunnen twee dingen doen: Het legacy component patchen of wachten tot het legacy component wordt verwijderd.

**Comment by hansgrimm** [comment]
> > [...] als je de cascade goed voor mekaar hebt, zou het niet nodig moeten zijn om tegen de stroom op te zwemmen. Kan je daar nog eens naar kijken?
> 
> We hebben het hier over een legacy component wat een modern component in de weg zit. We gaan het moderne component geen rekening laten houden met 'n legacy component, en we gaan het legacy component niet aanpassen.
> 
> Er is hier dan ook geen sprake van een CSS cascade die wel/niet goed zou zijn. Er zijn twee componenten die elkaar in de weg zitten. Uitstekend idee om hier een `:not()` selector voor in te zetten.
> 
> Dus we kunnen twee dingen doen: Het legacy component patchen of wachten tot het legacy component wordt verwijderd.

Heel goed, er is dus een sluitende verklaring voor het linksaf slaan. Daar was ik naar op zoek. Prima 👍

**Comment by MichielDHVD** [comment]
> @PieterVerheij de text van de meer-knop is ook grasgroen, ik neem aan dat deze ook basgroen moet worden? ![image](https://user-images.githubusercontent.com/25430835/210768774-5070f72d-636f-4e2f-9f1a-022acd077f33.png)

De menuknop is altijd voorzien om grasgroen te zijn. (Net als inloggen)  de menu knop volgt het tertiaire knop patroon van grasgroen met grasgroen als chevron. 

De hoofd menu items zijn bosgroen en het menu item meer heeft daardoor een bosgroene chevron.

**Comment by PieterVerheij** [comment]
Ok, dus geen kleuraanpassiung? Dan zet ik hem door.

**Comment by MichielDHVD** [comment]
Misschien toch niet duidelijk genoeg gecommuniceerd. Had nog even naar de header verbetering gekeken @PieterVerheij 

Chevrons hebben altijd de kleur van het bijhorende link tekst. 

Dus voor meer knop is het allemaal bosgroen. Dit is dus goed
<img width="102" alt="Screenshot 2023-01-12 at 07 54 08" src="https://user-images.githubusercontent.com/36912722/211998205-f887714e-28df-476c-991c-bb911770039e.png">

Voor de menu knop is de chevron en de tekst allebei grasgroen, dus deze moet grasgroen zijn. Zoals de tertiaire button. 
<img width="108" alt="Screenshot 2023-01-12 at 07 53 54" src="https://user-images.githubusercontent.com/36912722/211998290-f199a9bf-8bd3-4a09-84c4-21e4853ae370.png">

**Comment by PieterVerheij** [comment]
OK, allebei grasgroen: aangepast.

**Comment by PieterVerheij** [comment]
![image](https://user-images.githubusercontent.com/25430835/212078237-2208a881-26bb-4cbe-b7a6-e50d9468df7b.png)
spraakverwarring opgelost :)

**Comment by hansgrimm** [comment]
Dat wat is top 😂

**Comment by svrijsewijk** [comment]
Voor de volledigheid, we gaan het legacy component dus niet patchen, in de milestone van week 5 wordt deze immers verwijderd.
https://github.com/dso-toolkit/dso-toolkit/issues/1460
