### ISSUE TITLE
sticky variant voor Document List Item Heading

### ISSUE THREAD

**Issue by kad-tammie** [dso-toolkit/dso-toolkit#1905]
Document Header kent een sticky variant. 
Document List Item ontbeert een sticky variant.

Verzoeke een sticky variant a la document header.

Ihkv het sticky maken van document List Item Heading binnen Geselecteerde Regels binnen gebruikerstoepassing Regels op de Kaart

Gaat om dit stuk styling:

`&.dso-document-header-sticky {
    left: 0;
    padding: 0;
    position: sticky;
    top: 0;

    #{typography.$headings} {
      font-size: 1.25rem;
      margin-bottom: 0;

      button {
        align-items: center;
        background-color: transparent;
        display: flex;
        padding: units.$u1 - 1 units.$u2 units.$u1;
        text-align: left;
        width: 100%;

        &::after {
          @include di.base("chevron-up-bosgroen");

          content: "";
          display: inline-block;
        }

        span {
          display: inline-block;
          margin-right: units.$u1;
          max-width: calc(100% - #{units.$u2 * 2});
          overflow: hidden;
          text-overflow: ellipsis; // stylelint-disable-line declaration-property-value-disallowed-list -- We don't want wrapping in sticky document-header: full text in initial (scroll=0) position
          white-space: nowrap; // stylelint-disable-line declaration-property-value-disallowed-list -- We don't want wrapping in sticky document-header: full text in initial (scroll=0) position
        }
      }
    }`

**Comment by tfrijsewijk** [comment]
Hi @kad-tammie,

Ik heb begrepen dat er in 'n JIRA ticket aan dit issue wordt gewerkt.

cc: @hansgrimm @DjangoBlok @svrijsewijk

**Comment by hansgrimm** [comment]
Jira ticket is aangemaakt, staat gepland voor refinement.

**Comment by svrijsewijk** [comment]
@kad-tammie dit zal in de release van week 3 verschijnen

**Comment by daverhelst** [comment]
@DjangoBlok @LiesbethVorst (@hansgrimm) Ik heb een compacte variant van de document-list-item-heading kunnen maken. Kunnen jullie aangeven of hij zo naar wens is?

https://storybook.dso-toolkit.nl/_1905.sticky-variant-voor-Document-List-Item-Heading/?path=/story/html-css-document-list--sticky

**Comment by LiesbethVorst** [comment]
@daverhelst de design specs waren helaas niet meegekomen (vanuit Jira) in dit issue. De hoogte moet 40px zijn

**Comment by daverhelst** [comment]
@liesbeth is een hoogte van 42.59 ook akkoord? Daar kom ik namelijk op uit als ik alleen de padding-top en padding-bottom verklein van 16px naar 8px

![image](https://user-images.githubusercontent.com/5871330/212919963-15a4b89f-1e11-4d69-80ec-d8a2630d7f70.png)

**Comment by LiesbethVorst** [comment]
Dat is wel een aparte hoogte @daverhelst. De sticky variant van de document header is wel gewoon 40...
<img width="912" alt="image" src="https://user-images.githubusercontent.com/91903058/212929631-29a6836a-cbea-4efa-9865-f272bf974502.png">

**Comment by hansgrimm** [comment]
42.59 is wel een klassiek voorbeeld van een ‘magic number’. Something to avoid.
Ben je daarop uitgekomen door te kijken naar de computed values? Dan speelt vermoedelijk de `line-height` van de content een rol hier.

**Comment by hansgrimm** [comment]
en inderdaad. als je de `line-height` van de `<h2>` naar 1.2 zet, kom je keurig op 40px computed height uit.

**Comment by hansgrimm** [comment]
@LiesbethVorst ik vermoed dat die designs er in Jira bij gekomen zijn toen de github issue al was aangemaakt. dat is het grote nadeel van de dubbele boekhouding die wij erop nahouden... 
Misschien moeten we eens kijken naar een sync tool: https://exalate.com/ppc-jira-github-integration/ of https://unito.io/integrations/github-jira/

**Comment by daverhelst** [comment]
@hansgrimm nou een duurzame oplossing zit er wat dat betreft niet in, maar ik zal tevens de `line-height: 1.2` toevoegen op de h2. Dan wordt hij inderdaad netjes 40px hoog.

**Comment by hansgrimm** [comment]
@daverhelst het zij zo, als maar duidelijk is waar het vandaan komt. Kijk wel even of de verticale tekstafstand nog een beetje redelijk is met die `line-height`, heb ik daarstraks nagelaten 😉
