### ISSUE TITLE
Maximale hoogte van dso-body in modal te klein / niet handig.

### ISSUE THREAD

**Issue by TonD83** [dso-toolkit/dso-toolkit#191]
Doordat er een maximale hoogte wordt gezet krijgt de body een scrollbar wat niet wenselijk is. Zeker in combinatie met de iframe-resizer (in het loket) geeft dit ongewenst gedrag. Namelijk, de modal probeert zich in de huidige (kleine) afmetingen van het iframe te voegen waardoor de melding niet meer leesbaar is. In plaats van gewoon groter te worden, waarop het iframe meegroeit. 

De boosdoener: `.dso-modal .dso-body {
      max-height: calc(70vh - 114px - 1.5em);
      overflow-x: auto; }`

Verwacht:
<img width="740" alt="screen shot 2018-09-27 at 10 07 26" src="https://user-images.githubusercontent.com/18580063/46132080-79f9ae80-c23d-11e8-99c0-eef612ff35c1.png">
Resultaat:
<img width="812" alt="screen shot 2018-09-27 at 10 07 19" src="https://user-images.githubusercontent.com/18580063/46132081-79f9ae80-c23d-11e8-94d6-96c4fde627a5.png">

**Comment by PieterVerheij** [comment]
Dit is inderdaad vervelend, maar kunnen we er altijd vanuit gaan dat het iframe meegroeit? 
@TonD83 Ik ga er vanuit dat we het hier hebben over een iframe van jullie applicatie? Is deze altijd hoog genoeg? Er is naar mijn weten iig geen rekening gehouden met het openen van een modal vanuit een iframe in zijn parent.

**Comment by PieterVerheij** [comment]
Als we de hoogtebeperking eraf halen, lopen we weer het risico dat een modal (in met name een iframe) uit het beeld zal lopen. 
Wat een optie is, is om de hoogtebeperking (of ontbreken daarvan) aan een class te binden. De implemenator heeft dan de keuze (en verantwoordelijkheid) om de voor hem juiste optie te kiezen.
Daarnaast heeft de implementator natuurlijk ook de keuze om een script (die wij niet gaan aanbieden) te gebruiken om een modal vanuit een iframe in de parent te openen. Dan zel de hoogtebeperking ook minder een rol spelen.

**Comment by tfrijsewijk** [comment]
@MichielDHVD ?

**Comment by MichielDHVD** [comment]
Ik ga overleggen met het team. Wat een wenselijke situatie is in dit geval. We moeten wel zien te voorkomen dat er rare situaties ontstaan met het modal. Ik loop ook nog even langs bij @TonD83 om te kijken vanuit het team wat een wenselijke situatie is. Neem ik ook even de default rows group mee.

**Comment by TonD83** [comment]
Deze heeft wat ons betreft erg hoge prioriteit, te meer omdat wij een loading indicator ('spinner') hebben geimplementeerd dia ook als modal wordt gepresenteerd. Deze kan nu volledig buiten beeld vallen, waarder de gebruiker aardige de weg kwijt kan raken.

**Comment by PieterVerheij** [comment]
Ok, willen we dan wat op 5 november is voorgesteld? Een extra class die de hoogtebeperking er afhaalt en dat jullie dan scriptend de modal op de juiste hoogte zetten (let erop of dat wel/niet binnen een iframe gebeurt...).

**Comment by TonD83** [comment]
> Ik ga overleggen met het team. Wat een wenselijke situatie is in dit geval. We moeten wel zien te voorkomen dat er rare situaties ontstaan met het modal. Ik loop ook nog even langs bij @TonD83 om te kijken vanuit het team wat een wenselijke situatie is. Neem ik ook even de default rows group mee.

Dit overleg heeft m.i. nooit plaatsgevonden, we zijn er ook pas recent achter dat het hoge prio heeft :)

**Comment by TonD83** [comment]
@PieterVerheij Excuus, door de opmerking in #192 dat deze erg lijkt op #191 was ik even in de war. De urgentie ligt wat ons betreft bij #191 en niet bij dit issue.

**Comment by PieterVerheij** [comment]
@TonD83 Dus met (bv.) een class `scripted-height` wordt de max-height overruled en kan de implementator de juiste hoogte er scriptend op zetten?

**Comment by TonD83** [comment]
@PieterVerheij Ja, dat lijkt me prima.

**Comment by MichielDHVD** [comment]
Gezien en verplaats naar Done.
