### ISSUE TITLE
html/css - dropdown menu / anchors: aria correcties in markup

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#1918]
## Waar
html/css - dropdown menu / anchors (en afgeleide web component)

## Aanleiding
Axe valt in het voorbeeld over de h2 'versies', omdat binnen een aria menu geen h2 mag voorkomen.
De [aria specificatie voor menu](https://www.w3.org/TR/wai-aria-1.2/#menu) vermeldt inderdaad dat child elementen van menu uitsluitend de role menuitem, menuitemradio of menuitemcheckbox of group mogen hebben.

Bovendien valideert het voorbeeld niet, omdat volgens de W3C markup validation service ieder menuitem aria-checked moet hebben. Dus op de niet aangevinkte opties moet aria-checked=false komen.

Tenslotte viel me op dat in het storybook voorbeeld de aria-labelledby van het menu verwijst naar de knop (dat zou de titel moeten zijn).

In ieder geval zal "versies" boven de menu div moeten komen, en moet aria-labelledby van de menu div daarnaar verwijzen. De volgende vraag is of versies een h2 of een div moet zijn.
Ik stel voor er een div (of span) van te maken:

Omdat de titel met aria-labelledby aan het menu is gekoppeld, wordt succescriterium 1.3.1 "info en relaties" al behaald; daarvoor hoeft het geen heading te zijn
De heading heeft geen meerwaarde omdat een screen reader hem nooit zal voorlezen, want de focus is trapped in het menu
Volgens onze best practice zou de implementator het heading niveau moeten kunnen wijzigen (want anders kun je bijvoorbeeld een h2 onder een h4 krijgen). Een grote complicatie die gezien het vorige punt volstrekt onnodig is, nog los van de vraag of het semantisch eigenlijk wel een heading moet zijn.

## Werkzaamheden
- De titel boven de menu div zetten en er een div of span (ipv h2) van maken
- Aria-labelledby van de menu div laten verwijzen naar deze titel (ipv de knop)
- zorgen dat alle menuitemradio's aria-checked = false hebben (en de geselecteerde true)
- Betreffende Axe test opnieuw inschakelen en checken of het nu wel een pass is.
- Checken of W3C validator nieuwe markup inderdaad accepteert

Dat resulteert als het goed is in de volgende markup:
```
<h2 id="title" >Tekst</h2>
<div role="menu" aria-labelledby="title">
<ul role="none">
<li role="none" >
<a role="menuitemradio" aria-checked="true" href="">Geselecteerd item</a>
</li>
<li role="none" >
<a role="menuitemradio" aria-checked="false"href="">Niet geselecteerd item</a>
</li>
</ul>
</div>
```

## Gebruikersimpact
Beperkt: de huidige markup is inderdaad niet conform standaard maar werkt in de praktijk wel.

**Comment by daverhelst** [comment]
Ik heb een oplossing kunnen vinden die gebruik maakt van `role="menu"` , `role="group"` en eventueel `role="menuitemradio"` of `role="menuitem"`

@timveld zou jij kunnen checken of deze oplossing valide is?

HTML/CSS
- https://storybook.dso-toolkit.nl/_1918.html-css-dropdown-menu-anchors-aria-correcties-in-markup/iframe.html?id=html-css-dropdown-menu--anchors&viewMode=story
- https://storybook.dso-toolkit.nl/_1918.html-css-dropdown-menu-anchors-aria-correcties-in-markup/iframe.html?args=&id=html-css-dropdown-menu--buttons&viewMode=story

CORE
- https://storybook.dso-toolkit.nl/_1918.html-css-dropdown-menu-anchors-aria-correcties-in-markup/iframe.html?args=&id=core-dropdown-menu--anchors&viewMode=story
- https://storybook.dso-toolkit.nl/_1918.html-css-dropdown-menu-anchors-aria-correcties-in-markup/iframe.html?args=&id=core-dropdown-menu--buttons&viewMode=story

**Comment by timveld** [comment]
@daverhelst excuses voor de late reactie, dit issue is van mijn radar gevallen.

Het klopt dat ik in mijn specificatie niet ben uit gegaan van meerdere 'groepen' items. 

Ik heb alternatieve oplossingsrichtingen (zonder de wat gekunstelde ul's of met gebruik van fieldsets) bestudeerd. Maar die zijn om verschillende redenen niet mogelijk. Ik vind je oplossing daarom de best mogelijke.

Er zijn echter wel twee belangrijke correcties nodig: 
* De li's met class dso-group-label bevatten de 'groeptitels'. Je hebt ze role=menuitem gegeven, maar dat is (uiteraard) niet correct. Ze moeten role=none hebben, waarmee je tegen een screen reader zegt dat het 'gewone' tekst is.
* Daarnaast moet de ul met group rolle aria-labelledby=[ID van groeptitel] hebben. Dit zorgt dat wordt voorgelezen 'versies groepering ...' en hiermee voldoen we aan WCAG sc 1.3.1.

Graag deze aanpassingen doorvoeren en mij laten weten als ik kan testen, bij mijn eigen experimenten leek het goed te werken maar ik weet niet hoe dit in het webcomponent uit gaat pakken.

**Comment by daverhelst** [comment]
@timveld ik heb de aanpassingen die je hebt aangedragen doorgevoerd. Zou je nog eens kunnen kijken?

**Comment by daverhelst** [comment]
@hansgrimm @timveld nog even een tikkie naar bovenstaande vraag die nog open staat

**Comment by hansgrimm** [comment]
Yoo @timveld effe checken!

**Comment by timveld** [comment]
@daverhelst oeps, ik heb je commentaar weer gemist... even kijken hoe ik mijn proces op dit punt ga verbeteren. 
Je aanpassingen doen precies wat ik had verwacht dus kan de release in!
