### ISSUE TITLE
Modal opent deels buiten beeld

### ISSUE THREAD

**Issue by maartenvs** [dso-toolkit/dso-toolkit#192]
De modal van DSO Toolkit 3 wordt niet altijd volledig in beeld geplaatst. Dit gebeurt als:
* de webpagina zo lang is dat de browser verticaal laat scrollen
* je helemaal naar beneden scrollt
* de modal verschijnt
De bovenkant van de modal is nu te hoog op de pagina, en staat "buiten beeld".

**Comment by PieterVerheij** [comment]
We kunnen dit niet reproduceren (in de toolkit). Is het mogelijk dat wij de broncode krijgen van de pagina waarop het fout gaat?

**Comment by maartenvs** [comment]
De pagina is te bekijken op de INT-omgeving. Ik zal de URL privé doorgeven aan @PieterVerheij  .
Instructies:

- Klik in stap 1 op "Volgende stap".
- Kies in stap 2 een willekeurige locatie en ga naar de volgende stap.
- Klik in stap 3 op "Toevoegen".
- Selecteer zoveel mogelijk activiteiten en klik op "Toevoegen".
- Wacht tot de browser alle gegevens heeft geladen.
- Om de fout te kunnen reproduceren, moeten er genoeg gegevens zichtbaar zijn op de pagina. Klap daarom in de accordion een sectie en subsectie uit die veel regels heeft. Bv. sectie "Gebruik en het in stand houden van bouwwerken - Melding" en subsectie "Tijdelijk gebruik".
- Scroll helemaal naar beneden.
- Klik op de prullenbak bij de onderste sectie. Dat zorgt ervoor dat de modal verschijnt.
- De modal staat nu bovenin, "buiten beeld".

Versie die op dit moment op INT staat: [Alexia build: 2018-10-01T15:08:52-2cad2366]

**Comment by PieterVerheij** [comment]
De modal kan zelfs helemaal buiten beeld vallen! Als het iframe hoger is dan de hoogte van de modal en van je window, staat hij te hoog. Nu staat hij met een margin-top gepositioneerd, maar zelfs wanneer je hem (met een transform) centreert, kan hij nog steeds buiten beeld komen te staan.

**Comment by tfrijsewijk** [comment]
Lijkt op #191

**Comment by PieterVerheij** [comment]
> Hier gaan we verder induiken.

Ik hoorde een plons en daarna niks meer? ;)

**Comment by tfrijsewijk** [comment]
Ik ga vandaag of morgen `v3.1.0` uitbrengen. Deze issue is niet opgelost. Dit betekent niet dat we weer een PI moeten wachten tot er 'n release is, ik kan ook releases op bestelling uitbrengen als men wacht op een specifiek probleem

**Comment by TonD83** [comment]
@PieterVerheij Ik ben een paar weken met verlof geweest, vandaar geen verdere (re)actie meer van deze kant. Ik probeer @MichielDHVD en andere betrokkenen bij DSO hier binnenkort weer over te spreken. Weet niet precies wanneer dat zal zijn, aangezien het nog een beetje vakantieperiode is.

@tfrijsewijk Fijn dat er ook releases 'on demand' gemaakt kunnen worden!

**Comment by MichielDHVD** [comment]
Samen met Ton besproken en de conclusie is dat dit issue niet opgelost kan worden in de Toolkit. 

PR02 en PR12 moeten samen kijken hoe er functioneel een modal geopend kan worden. Nu wordt deze in de iframe geopend en veroorzaakt dit probleem.
