### ISSUE TITLE
Grid - Landingspagina styling verbeteringen

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#1923]
## Aanleiding:
Voor de homepage is een ontwerp gemaakt die is nu niet te realiseren met de toolkit. De homepage neemt onderdelen over van de viewer landingspagina. En deze grid aanpassingen zijn bedoeld om alle landingspagina's te verbeteren. 

## Werkzaamheden:

- Nieuw patroon Thema-pagina-intro, met 2 opties:
- - Een thema pagina intro heeft altijd, DSO-Banner-Image, Highlight-box, H1 in de highlight box en een paragraaf
- - 1e optie is de versie zoals boven beschreven. De thema-pagina-intro is dan 296px
- - 2e optie is een thema-pagina-intro met een knop in de highlightbox (zoals in de afbeelding) dan heeft het een total hoogte van 352px
- Wanneer we op kleinste breakpoint zitten boven padding van 24px daar 8px omzetten. 
- Wanneer een dso-featured (brede groene balk) onder een Hero-image-banner staat geen witruimte. Sluit direct aan
- Wanneer een normale row onder een hero-image-banner staat is er 24px witruimte. (was 32)
- DSO-featured margins en paddings aangepast (nam teveel ruimte in)
- - Padding-top: 40px wordt 24px
- - Padding-bottom: 48px wordt 40px
- - Margin-bottom:40px wordt 32px
- Extra voorbeeldpagina's toegevoegd onder aparte map, loket. 
- 
##Testen
Veranderingen zijn reeds gemaakt en zichtbaar te zien op deze pagina's. 

https://dso-toolkit.nl/_POC-Grid-aanpassingen/components/preview/aanvragen-landingspagina.html
https://dso-toolkit.nl/_POC-Grid-aanpassingen/components/preview/maatregelen-op-maat-landingspagina.html
https://dso-toolkit.nl/_POC-Grid-aanpassingen/components/preview/regels-op-de-kaart-landingspagina.html
https://dso-toolkit.nl/_POC-Grid-aanpassingen/components/preview/vergunningcheck-landingspagina.html

**Comment by MichielDHVD** [comment]
Ik zie dat de afbeeldingen niet overgezet zijn toen je begonnen was aan de story. Die voeg ik nog even toe. 
![image](https://user-images.githubusercontent.com/36912722/212832879-250466af-64f7-403b-8e6d-206798a6a7ec.png)
![image](https://user-images.githubusercontent.com/36912722/212832955-95d5a4c5-56b6-4632-9bca-0e13092b38f7.png)


@daverhelst 

Wat ik nog mis is dat dso-featured standaard 32px margin boven heeft. De margin wordt alleen 0px wanneer dso featured onder een hero image banner komt. 

Want dit is bijvoorbeeld geen gewenste situatie. 
![Screenshot 2023-01-17 at 08 11 08](https://user-images.githubusercontent.com/36912722/212833139-fbd33cbd-62c7-4eb2-bec5-f1ba387e4f9a.png)

Gevonden op voorbeeld pagina. 
https://storybook.dso-toolkit.nl/_1923.Grid-Landingspagina-styling-verbeteringen/?path=/story/voorbeeldpagina-s-toepassingen-aanvragen-landingspagina--landingspagina

Een ander punt dat niet klopt is de twee varianten van de hero-banner image. 
Op dit moment is er geen verschil tussen de twee. 
Wanneer er geen button staat in de highlight box. moet de maximale hoogte van de hero banner image zijn 296px. 
Nu is het voor beide 352px. 
De landingspagina regels op de kaart zou een 296px versie moeten krijgen. 
https://storybook.dso-toolkit.nl/_1923.Grid-Landingspagina-styling-verbeteringen/?path=/story/voorbeeldpagina-s-toepassingen-regels-op-de-kaart-landingspagina--landingspagina

**Comment by daverhelst** [comment]
@MichielDHVD Ik heb deze twee dingen aangepast. Zijn we dan nu compleet?

**Comment by MichielDHVD** [comment]
Gezien en gecontroleerd. Mag doorgezet worden.
