### ISSUE TITLE
Lijnen van secundaire button niet altijd even dik

### ISSUE THREAD

**Issue by maartenvs** [dso-toolkit/dso-toolkit#193]
Met DSO Toolkit 3 is door afronding de onderste lijn van de secundaire button soms dunner dan de andere lijnen. Dit is te zien bij zoomlevel 100% in Firefox 62.0.2 op Windows 7 en Firefox 62 op Ubuntu.

![afronding](https://user-images.githubusercontent.com/15095200/46153096-c6abac80-c272-11e8-9db5-acc71825c8ba.png)

Dit lijkt op het effect dat gemeld is in issue #150, maar niet meer optreedt met DSO Toolkit 3.

**Comment by PieterVerheij** [comment]
In applicatie ook reproduceerbaar in Win10 - FF62.0.2 (64-bit)

**Comment by tfrijsewijk** [comment]
@MichielDHVD Zou jij deze nog kunnen bekijken?
