### ISSUE TITLE
Component voor rechts uitlijnen van elementen / Context-wrapper rework?

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#1933]
## Aanleiding
In github story https://github.com/dso-toolkit/dso-toolkit/issues/1872  is aangegeven dat de context wrapper onjuist wordt gebruikt. Specifiek de card-panel. Context wrapper mag alleen gebruikt worden wanneer er iets links staat en het andere element rechts uitgelijnd moet worden. Niet wanneer alleen iets simpel rechts moet uitgelijnd moet worden. 

Inventarisatie Context Wrapper:

- DSO-Toolkit code base
- - Viewergrid - Filterblok (correct gebruik)
- -  Card-Panel (fout gebruik)
- - Mijn Projecten (correct gebruik)
- - Mijn activiteiten (correct gebruik)
- Samenwerken? 
- Andere gebruikerstoepassingen? 
 
##Werkzaamheden
- Een component realiseren dat het mogelijk maakt om een element rechts uit te lijnen.
- Dit toepassen op Cardpanel

![image](https://user-images.githubusercontent.com/506527/207844991-4237c6e2-72ba-4d2c-8da1-49058cd6ee9b.png)

![image](https://user-images.githubusercontent.com/506527/207845082-da45a4cf-d0e6-4b49-af47-5a7b42fea3a3.png)

**Comment by daverhelst** [comment]
@hansgrimm Ik heb een aantal vragen omtrent dit issue. Je stelt hier boven `Context wrapper mag alleen gebruikt worden wanneer er iets links staat en het andere element rechts uitgelijnd moet worden`, maar dat klopt niet helemaal. Het `context` component bestaan namelijk uit de `dso-context-wrapper` waarin `dso-context-label` _en_ `dso-context-container` zitten, maar ook de `row` die de uiteindelijke context bevat.

Daarnaast speelt een stuk filosofie van de toolkit mee, waarbij eerst de vraag "Wie wil deze manier van uitlijning eigenlijk? Komt deze wens vanuit UX vandaan?" gesteld moet worden. We neigen telkens naar een utility class oplossing, maar dat lijkt mij niet de bedoeling. Zomaar willekeurig een element rechts uitlijnen zou niet mogen. Dit zou wel kunnen als het onderdeel zou worden van de componenten waar dit in gebeurd, in dit geval dus het `Card` component.

Laten we hier anders even met een aantal mensen (@tfrijsewijk @svrijsewijk ?) over babbelen in een meeting.

**Comment by hansgrimm** [comment]
@daverhelst ik denk idd ook dat je hierover ven met UX moet bomen, met @MichielDHVD in het bijzonder 😉

**Comment by MichielDHVD** [comment]
Besproken met @daverhelst deze gaat terug naar spec. 

Er zijn te veel variaties en er kan geen duidelijke vuistregel gehanteerd worden. 

Voordal de vuistregel om geen onnodige utlity classes toe te passen. 

Vervolg:

- met UX duidelijke vuistregels voor uitlijning opzetten. 
- Inventarisatie uitlijning rechts over alle componenten heen. 
- Herevaluatie gebruik context wrapper huidige opzet. 

@svrijsewijk  Deze mag uit de release voor over twee weken.

**Comment by tfrijsewijk** [comment]
Volgens mij is dit een non-issue: Als er iets rechts staat moet dat onderdeel van de werkvorm zijn. Een utility class "align right" conflicteert met de filosofie van de toolkit.

@MichielDHVD Jij hebt hier nog wat actiepunten openstaan. Hoe staat het daarmee? Is dit ticket inmiddels sluit-waardig?

**Comment by MichielDHVD** [comment]
Probeer deze week een antwoord af te ronden. 

Als een utility class niet wenselijk is zullen er een aantal stories komen waar we dit wel moeten gaan toepassen voor bestaande component combinaties.

**Comment by MichielDHVD** [comment]
@tfrijsewijk Deze behoefte slaat eigenlijk op de mogelijkheid om buttons rechts te kunnen uitlijnen. Maar eigenlijk hebben we deze class al namelijk met dso form buttons. Als je namelijk een div met dso-form-buttons om een enkele button zet lijnt deze rechts uit. 

Eigenlijk is dat component niet alleen bruikbaar voor forms maar op veel plekken waar je buttons op een generieke wijze wil uitlijnen. De verschillende variaties houden naar mijn mening stand. 

Hoe kijk jij hier tegen aan? 

Als dit niet wenselijk is, wordt de enigste story een highlightbox aanpassing. Waar je kan aangeven waar je een button onderaan een highlightbox wil laten staan. 

Pullrequest om dit te demonstreren is aangemaakt. Met een succesvolle build voeg ik de link toe.

**Comment by tfrijsewijk** [comment]
Het component Form Buttons mag alleen in combinatie met een Form gebruikt worden.

Ook hier geldt dat de toolkit een componenten bibliotheek is en geen utility classes bibliotheek: Wij leveren werkvormen.

De vraag die we ons moeten stellen is _waarom die knoppen naar rechts toe moeten_. Is het vanwege de werkvorm? Dan moet het in de werkvorm.

Uitlijnen, onderlinge afstanden (margin, paddings), kleuren, font sizes, etc zijn niet te vertalen tot losse componenten maar moet een eigenschap van een component worden.

**Comment by MichielDHVD** [comment]
Ik ga dit issue sluiten. 

Enigste plek waar dit voorkomt is op een viewer pagina. Daar wordt een highlightbox gebruikt met een button. Maar het is niet mogelijk om die button een plaatsing te geven. 

HIer is het issue om een generieke oplossing voor button placements te maken, die uiteindelijk ook toekomstbestendig is.
