### ISSUE TITLE
Label spacing padding too small

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#194]
Er is te weinig ruimte tussen de tekst en het | (scheidingslijntje) 

De gewenste afstand is 8px tussen het scheidingslijntje en de tekst 

![image](https://user-images.githubusercontent.com/36912722/46282716-8dc14f80-c572-11e8-87a2-e860f6d7a4f2.png)

**Comment by PieterVerheij** [comment]
In de toolkit zien we die spacing -abusievelijk- wel. Deze wordt gecreeerd door gerenderde white-spacing. De enige manier om hier aan te ontkomen is door de tekst ook in een element te zetten. Dit behoeft dan ook wel een aanpassing in de html.

**Comment by MichielDHVD** [comment]
Gezien en op done gezet.
