### ISSUE TITLE
Laatste componenten opnemen in z-index register

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#1945]
## Aanleiding

Er is een z-index register aangemaakt. Niet alle componenten met een z-index zijn daar in opgenomen.

## Werkzaamheden

Er zijn nog twee stylesheets waar een z-index staat:

* `packages\core\src\components\table\table.scss`
* `packages\dso-toolkit\src\components\shopping-cart\shopping-cart.scss`

**Comment by tfrijsewijk** [comment]
@MichielDHVD Bij nadere inspectie blijkt dat de door jou genoemde componenten helemaal geen z-index (meer) hebben. Er zijn nog twee stylesheets waar een z-index staat:

* `packages\core\src\components\table\table.scss`
* `packages\dso-toolkit\src\components\shopping-cart\shopping-cart.scss`

@hansgrimm gaat deze twee waardes verplaatsen naar het z-index register (`packages\dso-toolkit\src\variables\zindex.scss`). Daarna gaat hij uitzoeken of dat hele z-index (register) nog wel bestaansrecht heeft, en of het wellicht op een mooiere manier opgelost kan worden.
