### ISSUE TITLE
404 op webfonts uit cdn toolkit

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#1952]
Wij hebben wat problemen met de WebFonts vanaf de CDN.

Hier kun je het probleem zien: https://plan-plan-validatie.pre.omgevingswet.overheid.nl/  (webfonts leveren 404).

**Comment by tfrijsewijk** [comment]
Hi @MarcoDuiker 👋 

Heeft Hans toevallig https://dso-toolkit.nl/50.0.0/blog/2023/01/18/dso-toolkit-50-0-0 doorgegeven? 48.0.0 is natuurlijk 'n hele mooie release, maar het is niet genoeg om `master` met `50.0.0` te vervangen. De layout van de CDN is gewijzigd en de assets (inclusief `dso.css`) staat op 'n andere plek.

Neemt niet weg dat zomaar updaten een goed idee is, dus waarschijnlijk is 48.0.0 een goede keuze.

**Comment by MarcoDuiker** [comment]
Hans heeft helemaal niks doorgegeven. Ik kreeg dit issue in mijn mailbox (via cc @MarcoDuiker ).

Ik heb master geprobeerd, en uiteraard het  juiste pad naar de dso.css ingesteld. De webfonts werden dan niet gevonden.

**Comment by hansgrimm** [comment]
> Hans heeft helemaal niks doorgegeven. Ik kreeg dit issue in mijn mailbox (via cc @MarcoDuiker ).
> 
> Ik heb master geprobeerd, en uiteraard het juiste pad naar de dso.css ingesteld. De webfonts werden dan niet gevonden.

Hoi @MarcoDuiker, ik heb inderdaad niet apart gecommuniceerd omdat ik wist dat je automatisch vanuit deze ticket geïnformeerd zou worden. Echter had ik me niet gerealiseerd dat je in verhouding tot de andere toolkit-afnemers nog niet zo lang in de release-routines meeloopt. excuus daarvoor.
Even voor de duidelijkheid: Als je nu volgens de aanwijzingen versie 50.0.0 inlaadt, zijn je problemen dan opgelost?

**Comment by tfrijsewijk** [comment]
Vooruitlopend op het antwoord van Marco heb ik een testje gedaan en bij ons werkt het voor `master` en `50.0.0`: https://stackblitz.com/edit/typescript-pslh9g?file=index.html

Het volledige pad is `https://cdn.dso-toolkit.nl/dso-toolkit/master/dist/dso.css` hoewel ik je adviseer om **niet** op `master` te hangen.
