### ISSUE TITLE
Custom Element tags configureerbaar/prefixable/suffixable maken

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#1953]
Ter behoeve van de vervanging van het iframe.

**Comment by tfrijsewijk** [comment]
* https://github.com/ionic-team/stencil/issues/3138
* https://dev.to/sanderand/running-multiple-versions-of-a-stencil-design-system-without-conflicts-2f46
* https://github.com/WICG/webcomponents/issues/716

> > hey Fabio
> >  you can find the solution [here](https://github.com/johnjenkins/Stenciljs-micro-frontend) - the main secret sauce is [this file](https://github.com/johnjenkins/Stenciljs-micro-frontend/blob/main/component-lib/src/index.ts)  - it's just exporting a helper (`setTransformHandler`) - which is used by importing libs to [write their own](https://github.com/johnjenkins/Stenciljs-micro-frontend/blob/main/micro-app/src/global/app.ts) `transformHandler` function which is in turn [used](https://github.com/johnjenkins/Stenciljs-micro-frontend/blob/main/component-lib/src/utils/query.util.ts) < as you were doing before.
> > It's not all sunshines and rainbows though unfortunately. There's a bundling error / bug from rollup / stencil. I'll try to outline it:
> > 1. build component lib. All is well. `my-component` contains `my-input` < they rely on each other, so stencil sensibly turns them into a single module. This module contains the reference to your custom `h` and by extension, our new `componentLibTagTransformer` function
> > 2. build the micro-lib. All is not well. `my-input` and `my-component` are split into separate modules. `my-input` is re-written to import `h` and `componentLibTagTransformer` from a new module, but `my-component` is not re-written so is left with a zombie import that doesn't exist :disappointed:
> > My solution for now, was to [force stencil to split ](https://github.com/johnjenkins/Stenciljs-micro-frontend/blob/main/component-lib/stencil.config.ts#L5) `my-component` and `my-input` into separate modules which forces our util functions into their own module so when built in the micro-lib continue to work as expected.
> > If you can iron out that one issue, I believe this is the cleanest name spacing solution in stencil I've seen so far. That custom `h` of yours is :female-cook::kiss: (edited)
> 
> the idea is consumers can then load your components like so:
> ```
> import { setTransformHandler } from "component-lib";
> import { defineCustomElements } from "component-lib/loader";
> 
> export default async () => {
>    const tagTransformer = (tag) => 'v3-' + tag;
>    setTransformHandler(tagTransformer)
> 
>   defineCustomElements(window, {
>     transformTagName: tagTransformer,
>   } as any);
> };
> ```
> and it handles all the internal renaming of components on the fly.

https://github.com/ionic-team/stencil-ds-output-targets/issues/311

**Comment by tfrijsewijk** [comment]
Er is maar één `CustomElementsRegistry`. Alle Web Componenten worden in dit register aangemeld. Met het huidige portaal is er geen probleem: Applicaties worden in een iframe ingeladen. Het portaal en de applicaties in het iframe hebben allemaal een eigen `CustomElementsRegistry`.

Het portaal en de applicaties activeren een toolkit versie. Zonder iframe zitten alle applicaties en portaal in hetzelfde DOM. Dit levert problemen voor styling en de Web Components.

Voor styling kan een deel worden afgevangen door het gebruik van een Shadow Root. Voor Web Components moeten we iets doen met namespacing in de `tagName`.

## Factoren

* We genereren de Web Components met Stencil.
* Voor elk Web Component genereren we ook een React en Angular component
* De Web Components en framework bindings hebben allemaal een eigen package (`@dso-toolkit/core`, `@dso-toolkit/react` en `@dso-toolkit/angular`)
* Zonder framework bindings moet de afnemer de Web Components registreren
* Een Framework component registreert een Web Component pas als deze wordt gebruikt.
* Framework bindings zijn dunne componenten die voor een native Developer Experience zorgen, het echte werk wordt nog steeds door het Web Component gedaan.
* De Framework bindings worden door Stencil gegenereerd.
* Web Componenten uit de toolkit maken ook gebruik van de toolkit.

## Voorstel

De toolkit gaat Web Componenten versioneren:

```html
<dso-alert>
<!-- wordt -->
<dso-alert-v1>
```

Bij een breaking change komt er eerst `<dso-alert-v2>`. Een aantal releases bestaan er twee alerts: `<dso-alert-v1>` en `<dso-alert-v2>`. `v1` wordt bij de release van `v2` meteen deprecated. Een paar releases later wordt `v1` verwijderd.

Overwegingen:
* Het is niet zo dat we alle Web Componenten NU moeten renamen naar `-v1`.
* Dit is een organisatorische oplossing.
* Framework bindings gaan ook mee.
* Het nadeel is mogelijk dubbel onderhoud. Als er meerdere versies van Web Componenten in omloop zijn met dezelfde bug, moet deze in twee codebases worden opgelost.
* Automatisch testen met Cypress en Percy levert 'n extra uitdaging op.
* Het voordeel is dat we hier geen wijzigingen in het framework (Stencil en/of de toolkit) hoeven doen.

## Aandachtspunten

Het portaal activeert zijn benodigde versie van de toolkit. Dit is styling en scripting. Het portaal gaat de applicaties in een Web Component met Shadow Root inladen. Deze applicatie heeft ook een dependency op de toolkit styling en scripting. Een Shadow Root biedt bescherming tegen styling van buitenaf, dat betekent dat de styling van het portaal in principe niet beschikbaar is. De applicatie moet nog steeds styling inladen. Ik denk dat dit een aangepaste `dso.css` moet worden, zonder bv. `html` en `body` styling.

Sommige componenten (zoals het HTML/CSS component Modal) leunen op globale styling, bijvoorbeeld op `body`.

cc: @hansgrimm @svrijsewijk @MichielDHVD

**Comment by MichielDHVD** [comment]
Dit is doorgenomen met het PR02 team en de oplossing is ok bevonden. Dit proces moet goed gedocumenteerd worden. 

@svrijsewijk als ik het goed heb begrepen heeft Thomas dit aan jouw overgedragen.

**Comment by hansgrimm** [comment]
Ik heb wat twijfel of dat versioneren (-v1) wel zo’n goed idee is.

**Comment by tfrijsewijk** [comment]
Dit issue wordt uitgewerkt in een stuk documentatie. Ondanks dat het mijn voorstel uit mijn koker komt ben ik niet echt meer enthousiast.. Dus ik wil hier nog wel met de nodige belanghebbers over praten.

Voor nu: het doel van het issue is behaald.
