### ISSUE TITLE
Docusaurus lokaal kunnen draaien met localhost storybook widgets

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#1957]
Tijdens het bouwen van stories kwam naar voren dat Docusaurus verwijst naar de Master branch. Dus het is niet te testen of de stories die je ontwikkelt goed terecht komen als je ze in Docusaurus wilt bekijken. 

Dan zou deze eerst naar de Master gereleased moeten worden.

**Comment by tfrijsewijk** [comment]
Klopt, ik heb het nu opgezet als losse systemen. Als we dit willen betekent het dat we lokaal ook Storybook gaan starten bij het ontwikkelen van de website. Of misschien achter een CLI flag?

Want dat betekent dat er 3 Storybooks moeten draaien (core, react, angular) naast het Docusaurus proces.

**Comment by MichielDHVD** [comment]
Vraag is wel hoe essentieel dit is. 

Reden dat dit gebeurde is. Ik heb een typografie pagina gemaakt. https://storybook.dso-toolkit.nl/_Documentatie-Widget-toevoegingen/?path=/story/voorbeeldpagina-s-toepassingen-componenten-typografie--typografie 

En deze wilde ik meteen bekijken in docusaurus documentatie. Dat kon dus niet. 

Maar de belangrijke vraag is hoe vaak gaat het voorkomen dat er een story gebouwd wordt en dat we deze meteen in docusaurus willen zien, local? 

Denk eerlijk gezegd dat het niet heel vaak gaat voorkomen. 

Dus als dit issue veel tijd kost (daarmee ook geld) Zou ik zeggen dit niet op te pakken. Ik zou het beschouwen als een luxe.

**Comment by hansgrimm** [comment]
OK, sluiten dan maar, @MichielDHVD?

**Comment by MichielDHVD** [comment]
Voor mij prima

**Comment by tfrijsewijk** [comment]
Ik heb "iets" gedaan waarmee lokaal enigszins Docusaurus en Storybook elkaar kunnen vinden, maar echt fantastisch is het nog niet. Ik zet dit issue op de backlog, want we willen dit wel 'n keer goed hebben.

**Comment by tfrijsewijk** [comment]
Het lijkt best wel prima te werken, dus we sluiten deze.
