### ISSUE TITLE
Wens: Accordion.dsoTogglEnd event

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#1966]
~Wens: Niet alleen de header, maar ook een element uit de content van een accordion binnen de viewport te kunnen brengen.~ 

~Hoe het element meegegeven wordt (DOM, tag, attribuut, ...): voorstel door IP, afstemmen met PR12?~

Simon: 
Event aanbieden om aan het einde van de animatie de afnemer in staat te stellen iets te doen. `dsoToggleSectionEnd`

Gewenste oplevering medio sprint 2/3 van aankomend increment.

**Comment by MYpenburg** [comment]
Na afstemming met PR12: vanwege het iframe is het niet mogelijk om dit vanuit het component te doen. Om dit vanuit de pagina code te kunnen doen wordt een (nieuw te maken) event gevuurd op het moment dat de animatie klaar is.
