### ISSUE TITLE
Schuifje/toggle component

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#1967]
## Aanleiding
Binnen de viewers gebruiken we schuifjes voor het aan/uitzetten van gebieden op de kaart. Deze zijn nu in material stijl en die is recentelijk aangepast naar een nogal opvallend schuifje. Maar als je in de viewers een schuifje aanzet staat deze naast een legendablokje en daar moet de aandacht naar uitgaan. 

Eerst moet er een ontwerp komen van een schuifje dat past in de huisstijl maar niet te opvallend is.

## Ontwerp
In overleg met UX team bepalen

## Testen
n.t.b.

## Acceptatiecriteria
n.t.b.

**Comment by LiesbethVorst** [comment]
Hierbij de SVG's. Ook voor de disabled state zou ik graag SVG's gebruiken.

![DSO switch on disabled](https://user-images.githubusercontent.com/91903058/214096098-97c9b6ff-3f9e-4526-8278-6da66b906bfc.svg)
![DSO switch off disabled](https://user-images.githubusercontent.com/91903058/214096102-661956e5-fa94-4be1-a692-d774e94aee9f.svg)
![DSO switch on](https://user-images.githubusercontent.com/91903058/214096107-b44f0c61-796d-41e4-9c29-807f797d349c.svg)
![DSO switch off](https://user-images.githubusercontent.com/91903058/214096109-105ae210-f01b-4ae5-8964-07b027fe47d5.svg)

**Comment by hansgrimm** [comment]
Je zou deze vormen ook in CSS kunnen bouwen. Scheelt inladen van assets.

**Comment by tfrijsewijk** [comment]
@LiesbethVorst Wil je nog iets met animaties?

**Comment by LiesbethVorst** [comment]
@tfrijsewijk goed idee, daar ga ik naar kijken!

**Comment by hansgrimm** [comment]
@LiesbethVorst ben jij vandaag in 030?

**Comment by LiesbethVorst** [comment]
@hansgrimm ik kom vanmiddag

**Comment by LiesbethVorst** [comment]
Prima punt @hansgrimm om dit met css op te lossen. Het is wel zo dat er op hover niets moet gebeuren, voor aan/uitzetten moet je klikken. De animatie kan misschien nog een klein beetje subtieler, dat het bolletje aan het eind vertraagd.

**Comment by hansgrimm** [comment]
@LiesbethVorst hover is puur gebruikt om de animatie te tonen op een simpele manier, er komen andere events op neem ik aan. Er zit al een ease-in-out op de animatie, maar omdat de animatie zelf vrij kort is, is die vertraging nauwelijks waarneembaar.

**Comment by LiesbethVorst** [comment]
Misschien kan de ease-in-out wat langzamer, of de hele animatie een beetje langzamer.

**Comment by hansgrimm** [comment]
Volgens mij willen we de animatieduur enigszins standaardiseren, dus ik weet niet of we teveel van die 0.2 sec willen afwijken. Ik kan wel even kijken of ik wat kan rommelen met de cubic-bezier van de ease-in-out.

**Comment by hansgrimm** [comment]
Ik heb de ease een beetje aangepast, en de animatieduur opgehoogd naar 0,25sec. Op die korte duur valt het nauwelijks op, maar als je de animatie langer maakt, zie je de extra vertraging aan het eind wel. Duur moet kort blijven, gebruiker wil een ‘snappy’ interface.

**Comment by LiesbethVorst** [comment]
Precies, het moet snappy zijn maar je moet ook wel kunnen volgen wat er gebeurt. Wat mij betreft is dit zo okay.

**Comment by daverhelst** [comment]
Het webcomponent staat klaar, maar om een soort van toegankelijkheids test te kunnen voeren, heb ik een voorbeeldpagina gemaakt met verschillende patronen. @timveld (@hansgrimm) zou jij kunnen kijken welke van deze patronen goed gekeurd zijn. Dan kunnen we namelijk vastleggen wat de spelregels voor dit component zijn:

- Slide toggle en label met alleen een koppeling naar `aria-labelledby`: https://storybook.dso-toolkit.nl/_1967-Schuifje-toggle-component/iframe.html?args=&id=voorbeeldpagina-s-patronen-slide-toggle-slide-toggle-met-aria-labelledby--slide-toggle-met-aria-labelledby&viewMode=story
- Slide toggle en label met een koppeling tussen `for` en `id` en een koppeling naar `aria-labelledby`: https://storybook.dso-toolkit.nl/_1967-Schuifje-toggle-component/iframe.html?args=&id=voorbeeldpagina-s-patronen-slide-toggle-slide-toggle-met-aria-labelledby-en-for--slide-toggle-met-aria-labelledby-en-for&viewMode=story
- Slide toggle en label met een koppeling tussen `for` en `id`: https://storybook.dso-toolkit.nl/_1967-Schuifje-toggle-component/iframe.html?args=&id=voorbeeldpagina-s-patronen-slide-toggle-slide-toggle-met-for--slide-toggle-met-for&viewMode=story
- Slide toggle en paragraph met een koppeling tussen `for` en `id` en een koppeling naar `aria-labelledby`: https://storybook.dso-toolkit.nl/_1967-Schuifje-toggle-component/iframe.html?args=&id=voorbeeldpagina-s-patronen-slide-toggle-slide-toggle-met-paragraph--slide-toggle-met-paragraph&viewMode=story

**Comment by timveld** [comment]
Alle varianten valideren.
De eerste drie varianten worden door NVDA hetzelfde voorgelezen. 
Ik denk dat de derde variant met alleen label for het beste is. Aria-labelledby is in dit geval overbodig en dan kun je het beter weglaten, ook geldt 'liever een native oplossing dan aria' en die native oplossing is er. 

In de vierde variant staat het label in een p. Omdat het dan op een eigen regel komt, leest NVDA het twee keer voor ('selectievakje uitgeschakeld label [nieuwe regel] label'). Ik weet niet of er redenen zijn om een p te willen gebruiken maar het is qua toegankelijkheid geen verbetering.

**Comment by hansgrimm** [comment]
@daverhelst @svrijsewijk ^^
