### ISSUE TITLE
Modal web component met progress indicator geeft een foutmelding in de browser console

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#1972]
De modal web component met progress indicator geeft een foutmelding in de browser console:
Error: Your focus-trap must have at least one container with at least one tabbable node in it at all times
Zie https://storybook.dso-toolkit.nl/!react/49.1.0/?path=/story/modal--loading

**Comment by maartenwest** [comment]
Extra info: de link verwijst naar React, maar het probleem lijkt ook op te treden wanneer de web component direct wordt gebruikt.

**Comment by svrijsewijk** [comment]
opgelost in https://github.com/dso-toolkit/dso-toolkit/issues/1989
