### ISSUE TITLE
Accordion: status danger eruit (deprecate), status error erin

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#1976]
Toevoegen status error: toont rechts het error icoon.

Deprecaten status danger: toont rechts de solid rode driehoek

Mag ook meteen breaking eruit, is voor team PR12 geen probleem.

**Comment by daverhelst** [comment]
@mypenburg Kun je kijken of dit zo naar wens is?

https://storybook.dso-toolkit.nl/_1976.Accordion-status-danger-eruit-deprecate-status-error-erin/iframe.html?args=state:error&id=html-css-accordion--default&viewMode=story

**Comment by MYpenburg** [comment]
@daverhelst: Status danger is er nu helemaal uit, dat was (denk ik) nog niet de bedoeling? Msch moeten we "ons" een afkoelingsperiode gunnen. En klopt het dat de iconen verticaal niet helemaal in het midden staan? (is observatie/vraag, weet niet of dat destijds de bedoeling was)

**Comment by daverhelst** [comment]
@mypenburg de status danger is weer terug (voorlopig). Over de verticale uitlijning; ik begrijp niet helemaal wat je bedoeld? Naar mijn idee staat het juist wel in het midden?

![image](https://user-images.githubusercontent.com/5871330/214269662-f6391559-96b8-401d-8bbe-2099113ce8d1.png)

**Comment by MYpenburg** [comment]
Thanks voor de status danger. Afgaande op het screenshot is de verticale uitlijning ok. De eerdere leek niet helemaal in het midden te staan dus ging ik twijfelen over de uitlijning, maar de centrering is helder. Dan ben ik akkoord met opleveren van dit issue. Op 24 jan. 2023 om 11:34 heeft Dion Verhelst ***@***.***> het volgende geschreven:﻿
@MYpenburg de status danger is weer terug (voorlopig). Over de verticale uitlijning; ik begrijp niet helemaal wat je bedoeld? Naar mijn idee staat het juist wel in het midden?
