### ISSUE TITLE
Code voorbeelden in DSO Toolkit kunnen kopiëren

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#1986]
## Aanleiding
Voor ontwikkelaars is het beoogd om makkelijk code voorbeelden te kopiëren en plakken. Momenteel dient men hiervoor vanuit DSO-toolkit naar Storybook te gaan, daar te wisselen naar het tabblad HTML om vervolgens de code te kopiëren.

In het oorspronkelijke ontwerp voor het "DSO-design system" is beoogd om direct in DSO-toolkit al een code kopieer-functionaliteit beschikbaar te maken. 

![image](https://user-images.githubusercontent.com/506527/214837864-7b62d8da-acd6-4540-8ac1-d3934eb7c809.png)

Zie bijvoorbeeld: https://storybook.dso-toolkit.nl/master/?path=/story/html-css-alert--success

## Werkzaamheden
- Code kopieer functionaliteit beschikbaar maken in DSO-toolkit
- Elke Storybook variant hiernaar laten verwijzen en "eigen" code voorbeeld tonen voor kopiëren. 

## Ontwerp
Screenshot van DSO-toolkit presentatie Toekomstbeeld op Miro:

![image](https://user-images.githubusercontent.com/506527/214838110-e5b4790a-83c8-416d-ab70-dbcf79d664d7.png)

## Testen
n.t.b.

## Acceptatiecriteria
n.t.b.

**Comment by LukeVerlaan** [comment]
Waar halen we de code vandaan die getoond gaat worden?

In de afbeelding is het in de form van import en de html. 

Een bedachte eventuele richting is om de html te pakken en door prettier te laten formatten.

**Comment by LukeVerlaan** [comment]
Ik zie geen mogelijkheid om ergens code vandaan te pakken

**Comment by tfrijsewijk** [comment]
> Ik zie geen mogelijkheid om ergens code vandaan te pakken

En nu pas begrijp ik waar je tegenaan loopt: De code uit Storybook naar Docusaurus halen. En niet de code uit Docusaurus op je klembord krijgen: Daar heb je iets slims op bedacht..

Sorry man, ik zat helemaal op een ander spoor. Ik ga ff met je meedenken..

**Comment by tfrijsewijk** [comment]
We zetten deze even in de backlog, ik moet hier een plan voor verzinnen.

**Comment by tfrijsewijk** [comment]
Ik weet het nog niet. Verder heb ik deze wens nog nergens "uit het veld" vernomen en hebben we aangenomen dat deze functionaliteit gewenst is. Ik sluit dit issue, we kunnen 'm altijd weer openen.
