### ISSUE TITLE
html/css ListButton - Selected styling heeft dubbele rand

### ISSUE THREAD

**Issue by svrijsewijk** [dso-toolkit/dso-toolkit#1997]
![image](https://user-images.githubusercontent.com/21218284/215713112-9b74681b-7098-407e-b4ba-4c13639bbe31.png)

**Comment by hansgrimm** [comment]
hier speelt het ook, maar alleen in FF: https://dso-toolkit.nl/50.0.1/components/modal/

**Comment by hansgrimm** [comment]
Dit is iets dat alleen voorkomt in Firefox (mac/win).
