### ISSUE TITLE
Build: Latest version toevoegen aan toolkit

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#2003]
## Aanleiding
Het kan handig zijn om een url te hebben die altijd de latest version van de toolkit opent. Bijvoorbeeld om te delen bij een design dat een team pas over enige tijd gaat bouwen. Via zo'n link wordt dan altijd de laatste versie van een component geopend.

## Acceptatiecriteria
- url: dso-toolkit/nl/latest
- in het lijstje met versies is de volgorde:
  - latest
  - master
  - 50.0..
  - 49....
- bij openen van de toolkit wordt de latest url gebruikt (dus geen re-direct naar een url met laatste versienummer)

**Comment by gofix** [comment]
De redirect vindt plaats doordat in de `index.html` van dso-toolkit.nl staat 
```
<meta http-equiv="refresh" content="0; url=/51.3.0" />
```
Die versie wordt door het webhook script `prune-topic-branches.js` bijgewerkt, in hetzelfde proces als waarin `versions.json` (de bron voor de versieselector) wordt gevuld.

Het eenvoudigste zou wellicht zijn van de 'latest' (dus bv. 51.3.0) een kopie of virtuele directory zouden kunnen maken, waardoor `/latest/` daarmee altijd naar de 'latest' set bestanden wijst.

**Comment by gofix** [comment]
Dus, ik denk er eigenlijk aan in git iets te organiseren dat `latest` een branch wordt, die bij iedere officiele release gevuld wordt met exact de versie die in de 'latest' staat.

**Comment by gofix** [comment]
ff nog wat vastlegging over hoe de build & deployment werken, ...

In https://github.com/dso-toolkit/dso-toolkit/blob/master/.travis.yml zien we:
```
stages:
  - name: deploy
    if: (branch =~ /^#/ || branch = master) && type = push
```
en in die deploy stage zien we:
```
ssh -p ${DEPLOY_PORT} ${DEPLOY_USER}@${DEPLOY_HOST} "cd ${DEPLOY_ROOT}/webhooks.dso-toolkit.nl && npm run update-versions"
```
die update-versions vinden we aldaar:
```
"scripts": {
  "update-versions": "node ./prune-topic-branches.js"
}
```
en daarin wordt in `updateVersions()` de reeks van versies bepaald (en worden folders van niet meer bestaande branches geschoond, etc.

**Comment by hansgrimm** [comment]
Ik ben geen expert, maar het klinkt plausibel :)

**Comment by hansgrimm** [comment]
volgorde:
latest
nummers
onder kop branch realeases: master

**Comment by gofix** [comment]
En als zodanig nu te zien op: https://dso-toolkit.nl/latest/


![Image](https://user-images.githubusercontent.com/2689559/224284742-28f3447e-fa88-4409-b1a0-d305392c2ebe.png)

Als jullie hier blij van worden

**Comment by hansgrimm** [comment]
Looking good!

**Comment by LiesbethVorst** [comment]
Hoi @gofix, ziet er goed uit! Ik zou alleen het plaatje weglaten bij latest. Begrijp de logica (finish vlag?) niet en door het plaatje valt de caret van de dropdown wel een beetje weg. 
<img width="158" alt="image" src="https://user-images.githubusercontent.com/91903058/224939024-2a4159d5-dbd7-4b4c-af28-f73c745e2807.png">

**Comment by hansgrimm** [comment]
@gofix zie opmerking @LiesbethVorst

**Comment by tfrijsewijk** [comment]
@gofix Bedankt voor de opzet! Inhoudelijk neem ik alles van je over, technisch werk ik het 'n beetje anders uit.

Ik heb het volgende bedacht: Bij elke release
* een kopie van de Storybooks naar `/latest` (of mogelijk zelfs symlinken, hier heb ik contact over met EvD)
* De Docusaurus opnieuw builden met `config.baseUrl = 'latest'` (https://docusaurus.io/docs/api/docusaurus-config#baseUrl) en deployen naar `/latest`.

Ik zet deze in de volgende milestone, ik ga hier nu niet meer aan toekomen.

**Comment by tfrijsewijk** [comment]
Ik weet eigenlijk niet of ik dit nog wel wil. Mijn grootste bezwaar is dat URLs niet permalinkable zijn en zomaar stuk kunnen gaan. We leveren met `latest` eigenlijk gebroken functionaliteit. Niemand zit op gebroken URLs te wachten.

Een alternatief is om geen `latest` aan te bieden en dat we bij oudere versies een melding plaatsen dat de gebruiker naar verouderde documentatie kijkt, een beetje zoals Angular dat doet: https://v12.angular.io/docs. Hiermee voorkomen we dat er gebroken links gaan circuleren.

Maar Node Docs werken ook met `latest`: https://nodejs.org/docs/latest/api/

**Comment by tfrijsewijk** [comment]
Ik heb hier al tijden niemand meer over gehoord, voor nu sluiten we 'm.
