### ISSUE TITLE
Tekstkleur tekst en interactieve element op gekleurde achtergrond naar #000

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#2005]
## Aanleiding
De tekst op het blauwe/info label leest niet zo lekker qua contrast. Het voldoet wel aan WCAG AA maar toch lijkt het contrast niet voldoende. Daarom willen we graag de tekstkleur aanpassen naar echt zwart #000000.

Buitenscope:
Hover states van buttons op een gekleurde achtergrond. Daar wordt een los issue voor gemaakt. 

## Werkzaamheden
- Zwart tint voor tekst en interactieve elementen op gekleurde achtergrond wordt omgezet naar #000000 
- Lijst met componenten waar aanpassingen nodig zijn 
- Voor Badge en Label bij de kleur geel en blauw
- Shopping cart 
- Footer
- Highlightbox (Vergeet de Tertiare knop niet mee te nemen) 
- Alerts 
- Banners 
- Document Header
- Document List 
- Info - fixed 

## Inventarisatie:
1. Bij sommige componenten is #000 al doorgevoerd. Voor document header en document list hebben de interactieve elementen de kleur #000. De statische tekst daar in tegen is nog steeds #191919. Dit is al inconsistent.
2. Document list en header zijn zwarte interactieve elementen op een grijze achtergrond. Als we dit consistent zouden willen doorvoeren zouden de volgende onderdelen ook aangepast moeten worden. 
Shoppingcart
Footer
Tertiare buttons en links in grijze Highlightboxes 
Form files - deze heeft nog een grasgroen kruis op een grijze achtergrond dit moeten we sowieso niet willen denk ik.
3. Alerts en Banners 

Deze buttons hebben een grijze achtergrond met een opacity. Waardoor het de kleur van de achtergrond deels overneemt. Deze splitsing met de achtergrond is niet sterk zichtbaar (het is niet perse een wcag probleem maar heeft geen sterke uitstraling). Misschien een los issue maar wel iets om op te lossen) 
Links op gekleurde achtergrond, hoewel deze achtergronden een zwakkere kleur intensiteit hebben dan het blauw van badge)  kunnen mogelijk ook naar #000
Hetzelfde geldt voor banners ophoging naar #000 mogelijk
Vragen waar een beslissing over genomen moet worden: 
Gaan we #000 gebruiken voor alle zwarte interactieve elementen op een gekleurde achtergrond ?
Als we 000# gebruiken voor interactieve elementen wordt de statische zwarte tekst dan ook altijd #000 ipv #191919?

Op dit moment zijn we in ieder geval niet consistent met de kleur zwart op een gekleurde achtergrond.

**Comment by gofix** [comment]
Bij het uitvoeren van de fix en het controleren van het resultaat ervan, zagen we dat er blijkbaar al enige tijd een foutje zat bij de presentatie van:

- banner -> danger-with-headings -> was geel, maar moet natuurlijk rood zijn
- banner -> rich-warning -> was rood, maar moet natuurlijk geel zijn

Dat is nu ook gelijk gefixed.

**Comment by gofix** [comment]
Gecontroleerd (steekproefsgewijs zelf, en natuurlijk door Percy):
- typografie (koppen, tekst, links) (en bijbehorende chevrons) in de footer en highlightbox
- badge en label, met status info (blauw) en warning (geel)

**Comment by gofix** [comment]
@hansgrimm kan het nu je goedkeuring wegdragen?

**Comment by hansgrimm** [comment]
@gofix Stond vanavond te rocken in een oefenruimte in IJmuiden. Kijk morgen (of eigenlijk vandaag) even :)

**Comment by hansgrimm** [comment]
en hij zag dat het goed was :)
