### ISSUE TITLE
card - selectable: titel in labels selectievakje en informatie knopje

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#2006]
## Waar
Html/css en core | card - selectable

## Aanleiding
Bij controleren van het component vond ik een selectievakje met accessible name "selecteer" en een knopje met accessible name "toon informatie".
De titel van de card "omgevingsplan Nieuwegein" moet sr-only worden toegevoegd aan de accessible name.

## Werkzaamheden
- Het selectievakje aria-labelledby = [id van card titel] geven, het label "selecteer" kan vervallen (zie kopje toelichting)
- Het knopje label "toon informatie (sr-only: over [titel van card]) geven
## Gebruikersimpact
Hinderlijk: omdat deze cards in een lijst of grid staan kan een screen reader gebruiker niet eenvoudig bepalen welke checkbox en welk knopje bij welke card hoort.

## Toelichting
Ik heb me afgevraagd of het woord "selecteer" in het selectievakje moest verdwijnen. Dit ligt voor de hand omdat een selectievakje (what's in a name) per definitie dient om iets te selecteren.
Probleem is echter dat er dan twee elementen (de link en het selectievakje) hetzelfde label "omgevingsplan Nieuwegein" hebben. Voor spraakherkenningssoftware lastig: waarop moet je klikken als wordt gezegd "klik omgevingsplan Nieuwegein"?
Dragon zou bij dit commando als het goed is zowel de link als het selectievakje markeren, dan kan de gebruiker kiezen.
Bovendien leid ik uit de [Dragon command cheat sheet](https://www.nuance.com/content/dam/nuance/en_us/collateral/dragon/command-cheat-sheet/ct-dragon-naturally-speaking-en-us.pdf) en [deze forum discussie](https://www.knowbrainer.com/forums/forum/messageview.cfm?catid=4&threadid=24013) af dat Dragon het verschil tussen "klik link omgevingsplan Nieuwegein" en "klik selectievakje omgevingsplan Nieuwegein" zal begrijpen.

En ook als dit niet zo is, maken we de situatie niet beter door sr-only "selecteer" er in te houden. De Dragon gebruiker krijgt dit woordje niet te zien en moet zelf maar bedenken dat wij het hebben toegevoegd. Dat bedenkt hij hoogstwaarschijnlijk niet. Dus in het beste geval helpt het hem niet, in het slechtste geval van de regen in de drup (als Dragon door het woordje selecteer voor de titel de opdrackt klik oselectievakje omgevingsloket Nieuwegein niet meer herkent). Ik noteer dit component wel voor een toekomstige gebruikerstest met spraakherkenning.

**Comment by gofix** [comment]
Op zich is het nu gemaakt zoals gespect, maar... zowel @LukeVerlaan als ikzelf hebben zo onze twijfels over hoe nu om te gaan met het `<label>` (dat nu leeg mag zijn omdat via `aria-labelledby` de checkbox van een accesible name wordt voorzien. Je zou denken laat weg dat `<label>` maar dat is het element dat nu zorgdraagt voor de custom styling van de input, en voor dat je de 'echte' input tenminste kunt aan- en uitzetten. Dus weglaten is geen optie. Maar, een `<label>` moet dan wel een `for` hebben. Eventueel zouden we het verder zinloze label dan nog wel `aria-hidden` kunnen maken.

Wat denk jij @hansgrimm, zie https://storybook.dso-toolkit.nl/_2006.card-selectable-titel-in-labels-selectievakje-en-informatie-knopje/?path=/story/html-css-card--selectable voor de huidige stavaza

**Comment by hansgrimm** [comment]
@gofix ik duik daar straks even in.

**Comment by hansgrimm** [comment]
door de styling op te hangen aan de aanwezigheid van een `label`-element, ipv een class die je in dit geval ook op een `span` had kunnen zetten, hebben we onszelf een beetje een hoek in geschilderd. dat label hebben we in andere gevallen wel nodig, maar hier dus net even niet. Omdat het hier vwb dit component gaat om een uitzonderingsgeval, lijkt 'aria-hidden` mij hier de beste oplossing. niet heel elegant, maar te verdedigen.

**Comment by hansgrimm** [comment]
@timveld kan jij hier nog even naar kijken morgenochtend?

**Comment by timveld** [comment]
@hansgrimm ik weet niet wat me heeft bezield om hier aria-labelledby voor te stellen, want er is geen enkele reden om geen label for... constructie te gebruiken. Dus lijkt me dat we de aria-labelledby weg moeten halen en in plaats daarvan een label tag om de card titel heen moeten zetten, daarbij maakt het niet uit dat dit een anchor is.

**Comment by hansgrimm** [comment]
@timveld Dat zou een breaking change betekenen, want de `card-title` staat nu op een heel andere plek, en de styling vereist een `label` als 'adjacent sibling'. we moeten een beetje schipperen hier.

**Comment by hansgrimm** [comment]
Conclusie tijdens refinement: niets meer aan doen. een leeg label zonder `for`-attribuut is in dit geval acceptabel; lelijk, maar acceptabel.

**Comment by timveld** [comment]
toolkit-accessibility-approved (nog niet afgesproken hoe we dit in github gaan doen)
