### ISSUE TITLE
Tooltip: Verwijderen HTML/CSS implementatie

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#2017]
# Inleiding

De HTML/CSS implementatie (code, styling, uniformiteit met het Web Component, documentatie voor toegankelijkheid) van Tooltip is niet meer te onderhouden.

In dit issue verwijderen we de HTML/CSS implementatie.

## Werkzaamheden

* Story uit Storybook verwijderen.
* Omdat er dan maar één implementatie is hoeft de styling niet meer met mixins te worden gecentraliseerd. Alles wat met de styling te maken heeft mag naar `/packages/core/src/components/tooltip` worden verhuisd.
* Documentatie (de verschillende README.md) bijwerken.
* Aandachtspunt zijn de tooltip variables: Als deze alleen binnen het Tooltip component worden gebruikt mag deze file ook naar de Web Component implementatie worden verplaatst. Als er nog andere componenten zijn die van deze variables gebruik maken, dan in `dso-toolkit` laten staan.

**Comment by hansgrimm** [comment]
html/css component deprecaten?

**Comment by tfrijsewijk** [comment]
Ik ben voor wat Hans voorstelt.. Weg met de HTML/CSS implementatie van Tooltip.

**Comment by timveld** [comment]
Prima om html/css te deprecaten. Zo te zien is het in core wel goed, alleen ontbreekt de role=tooltip.

**Comment by hansgrimm** [comment]
HTML/CSS component deprecaten, role=tooltip toevoegen aan het core component.

**Comment by tfrijsewijk** [comment]
> HTML/CSS component deprecaten, role=tooltip toevoegen aan het core component.

Volgens mij is dit dus al zo: 
* https://github.com/dso-toolkit/dso-toolkit/blob/master/packages/core/src/components/tooltip/tooltip.tsx#L225
* https://storybook.dso-toolkit.nl/54.0.1/?path=/story/core-tooltip--as-child
  ![image](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/203aff1e-31b6-4db5-bce0-d96a09f21ac5)

En kunnen we dit issue gebruiken om de HTML/CSS implementatie van het Tooltip component te deprecaten.

**Comment by tfrijsewijk** [comment]
In principe deprecaten, ik ga nog even de codebase van de viewers inspecteren of de HTML/CSS implementatie wordt gebruikt.

**Comment by tfrijsewijk** [comment]
In #2289 deprecaten we de HTML/CSS implementatie van Tooltip. In dit issue verwijderen we de codebase.

Aangezien er dan maar één implementatie zal zijn gaan we ook de SCSS reorganiseren. Alle styling zal naar de `core` package gaan.
