### ISSUE TITLE
Security-melding GitHub

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#2018]
![image](https://user-images.githubusercontent.com/506527/219343482-33ce1ea1-56db-466c-b77c-e047b3f16548.png)

**Comment by tfrijsewijk** [comment]
Ik sluit dit issue, de melding is achterhaald vanwege #2118. Daarnaast gaan we met `npm audit` in CI aan de slag, daar zal ook een proces ontstaan voor het afhandelen van security bevindingen.
