### ISSUE TITLE
Voorbeeld opnemen in Storybook: Datepicker in de body van een Modal

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#2019]
Zodat je kunt zien dat de modal meeschaalt als de day-selector van de datepicker wordt getoond. Geen haast, liefst wel dit increment.

**Comment by LukeVerlaan** [comment]
https://storybook.dso-toolkit.nl/_2019.modal-story-datepicker/?path=/story/core-modal--with-datepicker
@hansgrimm Hier een voorbeeld van een modal met datepicker, maar er valt te zien dat dit niet meeschaalt. Wordt daar een nieuw issue voor gemaakt of pakken we dat hier op?

**Comment by hansgrimm** [comment]
@LukeVerlaan met de inspector zie ik een simplistico oplossing door op `dso-body` de `overflow: auto;` uit te zetten. dat zou je tijdelijk kunnen doen zolang de datepicker open staat.

**Comment by LukeVerlaan** [comment]
@hansgrimm De oplossing met alleen de `overflow-x` eraf halen lijkt niet voldoende. Wanneer er meer tekst in de modal staat gaat dit er ook buiten vallen. Nu hebben @gofix en ik het voorstel om naast het afhalen van de `overflow-x`, ook de `max-height` eraf te halen. En daarbij de `position` van de modal van `fixed` naar `absolute` te veranderen. Hierdoor zal je niet in de body van het modal meer scrollen, maar de body van de pagina.

Daarnaast kan met een `overflow-y: hidden` op de body en een `overflow-x: hidden` op `.dso-modal` ervoor gezorgd worden dat de content achter de modal blijft staan tijdens het scrollen.

Zie voorbeeld: https://storybook.dso-toolkit.nl/_2019.modal-story-datepicker/iframe.html?args=&id=voorbeeldpagina-s-toepassingen-componenten-modal--modal&viewMode=story

**Comment by hansgrimm** [comment]
@LukeVerlaan lijkt een goede oplossing, doet alleen een beetje raar als je de bovenste datepicker openklapt, naar beneden scrollt en ook de onderste openklapt. Edgecase der edgecases, I know :)
