### ISSUE TITLE
Alle varianten van de button etaleren

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#2020]
Momenteel worden niet alle varianten van de button getoond in zowel de documentatiepagina als in storybook.

In deze story worden alle varianten weergeven op de documentatiepagina van de button en zijn de verschillende varianten in storybook zichtbaar.

# Werkzaamheden

## Button varianten (compact) toevoegen aan storybook

Compact wordt gedaan met de modifier class `btn-sm`. Het Button model (in `button.models.ts`) is hier nog niet bekend mee. De functionaliteit bestaat maar moet nog in alle routines worden verwerkt. Ook toevoegen als Control in Storybook.

## Button varianten weergeven op documentatiepagina 

Op de documentatiepagina in Docusaurus wordt wel geschreven over de diverse varianten maar er is geen Widget met 'n verwijzing naar de Storybook variant. Dit graag maken.

**Comment by tfrijsewijk** [comment]
Het lastige aan dit issue is dat we lokaal nog geen Docusaurus en Storybook kunnen draaien waarmee het plaatsen van Widgets 'n beetje in het donker tasten is.

**Comment by HalloJo** [comment]
Etaleren `compact` button en de mogelijkheid toegevoegd om `args` mee te geven aan een `StorybookComponent` om een uitgebreider component weer te geven in de widget in de Docusaurus 🦖 .  In dit specifieke geval: `<StorybookComponent implementations={["html-css"]} variant="primary" args={{ compact: true }} />` om de primary button te etaleren met de `compact` styling. Werkt nog niet, omdat de `compact` boolean nog niet in de `master` zit, maar al wel getest met de `disabled` voor de button. En dat werkte! ✅

**Comment by tfrijsewijk** [comment]
Mooi werk!
