### ISSUE TITLE
dso-label geeft strike-through wanneer je erop klikt

### ISSUE THREAD

**Issue by MichielKadaster** [dso-toolkit/dso-toolkit#2022]
Een `dso-label` kan removable zijn. Maar ook wanneer deze niet removable is dan kan je erop klikken en wordt de tekst doorgestreept.
![image](https://user-images.githubusercontent.com/111350940/220391112-b8b25a17-0a1e-4534-9771-02406f06af9d.png)

Is dit een kleine bug in de component?
Een voorbeeld kun je al zien in de storybook zelf: https://storybook.dso-toolkit.nl/51.2.1/?path=/story/angular_label--default&args=removable:false
![image](https://user-images.githubusercontent.com/111350940/220390888-f6430c96-c46f-433a-bbfd-d405d87b501d.png)

**Comment by svrijsewijk** [comment]
Ik sluit dit issue, het is dubbel met #2010
