### ISSUE TITLE
Storybook: Alle varianten accordeon etaleren

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#2025]
Momenteel zijn de verschillende varianten van de accordeon niet makkelijk te vinden in storybook. Alleen de default variant is direct te openen vanuit de treeview links. 

 

## Werkzaamheden

De volgende varianten toevoegen aan storybook, zodat deze een link krijgen in de treeview links:

- compact
- conclusion

**Comment by MichielDHVD** [comment]
@gofix Changes zijn zoals het hoort. Maar de build faalt, en heb geen idee waarom. 

https://github.com/dso-toolkit/dso-toolkit/tree/%232025-Accordion-etaleren 

React:build wil niet succesvol draaien, maar daar heb ik niks aangepast als het goed is.

**Comment by MichielDHVD** [comment]
Ik zie nu onder andere waarom de build faalt. Ik ga even door klussen.

**Comment by MichielDHVD** [comment]
Build draait nu, ik ga het aan de rest van de UX'rs tonen kijken of die het goed vinden. En dan mag ie door als het ook aan de standaard van IP voldoet.

**Comment by gofix** [comment]
Ik was hier even op het verkeerde been gezet door de verwoording in de description van dit issue:
> de treeview links
Want, 'treeview' is natuurlijk ook zelf al een component:
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/2689559/224293476-260ca129-e8de-4bb8-94a5-cef82dc3f556.png">

Maar met 'treeview links' wordt hier bedoeldt: 'de storybook navigatie', en dat is helemaal gelukt. Zowel voor:
- html/css
- core
- angular
- react
... zien we keurig de nieuwe varianten geetaleerd onder accordion:

![image](https://user-images.githubusercontent.com/2689559/224293805-193ee3bb-97e5-416f-8e10-df1831f41058.png)

**Comment by LiesbethVorst** [comment]
Mooi dat de varianten nu in de navigatie van Storybook zitten! 
De tekst op de pagina kan misschien wat duidelijker, maar dat maakt voor de release niet uit.
