### ISSUE TITLE
Toelichtingen box

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#203]
Er is een tekst box nodig die verschijnt wanneer iemand op het informatie I'tje klinkt.  

In de afbeeldingen hieronder staan verschillende vormen die mogelijk zijn, specs zijn hier ook terug te vinden 

@DHvD-Michael @TonD83

![16px antw tekst - 32px kruis - zonder lijnen](https://user-images.githubusercontent.com/36912722/46804221-59b01080-cd62-11e8-8958-61eff7087f8b.png)
![16px antw tekst - 32px kruis](https://user-images.githubusercontent.com/36912722/46804222-59b01080-cd62-11e8-8d2a-e1e358e0f9b4.png)
![16px vraag afb tekst - 32px kruis - zonder lijnen](https://user-images.githubusercontent.com/36912722/46804223-59b01080-cd62-11e8-8c90-4097e5756379.png)
![16px vraag afb tekst - 32px kruis](https://user-images.githubusercontent.com/36912722/46804225-59b01080-cd62-11e8-8311-46be3e362715.png)
![16px vraag afb tekst lees meer - 32px kruis - zonder lijnen](https://user-images.githubusercontent.com/36912722/46804226-5a48a700-cd62-11e8-90fc-acae1e48057b.png)
![16px vraag afb tekst lees meer - 32px kruis](https://user-images.githubusercontent.com/36912722/46804227-5a48a700-cd62-11e8-84a6-39b3dbf81fd9.png)
![16px vraag tekst - 32px kruis - zonder lijnen](https://user-images.githubusercontent.com/36912722/46804228-5a48a700-cd62-11e8-9833-f09085d53f4f.png)
![16px vraag tekst - 32px kruis](https://user-images.githubusercontent.com/36912722/46804229-5a48a700-cd62-11e8-8f61-20564a86ad25.png)

**Comment by jeroenpeeters** [comment]
Ook goed om rekening te houden met de styling van de content. We renderen HTML via Markdown, dus er zullen plain html elementen (zonder specifieke css classes) in de toelichtingen box worden opgenomen. Het is van belang dat deze de juiste DSO styling meekrijgen. Het gaat bijvoorbeeld om: h1,h2,h3,h4,p,table,ol,ul,hr,blockquote,a. Het is handig als plain elementen, zonder classes ook DSO styling krijgen.

Bijgesloten is een screenshot. Opzich ziet alles er goed uit. Alleen de table krijgt geen DSO styling mee. De velden van de table staan te dicht op elkaar.
![localhost_8088_opstellen_stap_1 1](https://user-images.githubusercontent.com/2640634/46871249-212b3800-ce31-11e8-99cb-7fbc73187b39.png)

**Comment by PieterVerheij** [comment]
@MichielDHVD Wat is de hover-stijl van het sluitkruisje?

**Comment by MichielDHVD** [comment]
@PieterVerheij 

De hover stijl van het kruisje is een een cirkel erom heen met een lijn width van 2px. No fill gewoon de background zoals deze is. 

In de modal close https://dso-toolkit.nl/3.0.0/components/detail/modal--modal-close.html Kun je dit kruisje werkend zien.

**Comment by PieterVerheij** [comment]
@MichielDHVD in dit geval staat de gefocusde variant van het kruisje wel dicht op de rand van de uitklapper. Bezwaarlijk?
![image](https://user-images.githubusercontent.com/25430835/47367261-a3441800-d6df-11e8-97e3-322be9fe7e65.png)

**Comment by MichielDHVD** [comment]
Ik ga dit met mijn collega bespreken. Ik geef vandaag nog antwoord.

**Comment by tfrijsewijk** [comment]
@MichielDHVD: Nog nieuws over de hover state van het sluiten-kruis?

@jeroenpeeters: Goed punt! We pakken dit op in #220

**Comment by MichielDHVD** [comment]
@tfrijsewijk @PieterVerheij Over het kruisje zojuist contact gehad en het gaat een compleet andere kant op. 

De hover state van het kruis gaat helemaal weg. Enigste wat moet gebeuren is dat er een handje over het kruisje komt. 

We gaan ook kijken of het interactie patroon van het kruisje op andere plekken moet worden veranderd. 

Dus het kruis blijft staan, maar het kruisje heeft geen expliciete hover state. Alleen een handje dat aangeeft dat het een clickable element is.

**Comment by tfrijsewijk** [comment]
Kleurtje? Hover naar oranje bv? Wel met handje, maar zonder cirkeltje

**Comment by MichielDHVD** [comment]
Oranje als hover wordt nergens gebruikt op dit moment in de toolkit. Vraag is ook of dat door de wcag komt. Kruisje is geen tekst maar er zijn toch wel wat contrast regels.

**Comment by jeroenpeeters** [comment]
Ik heb 3.1.0-alpha4 bekeken, en daarin mis ik nog het volgende. Een image mag maximaal 100% van de breedte innemen, nu kan het voorkomen dat van een breed plaatje een deel wegvalt. Verder is het zo dat plaatjes die kleiner zijn dan 100% gecentreerd weergegeven dienen te worden.

Kortom, een image in de toelichtingen box zou de volgonde css mee moeten krijgen:

```
    display: block;
    margin-left: auto;
    margin-right: auto;
    max-width: 100%;
```

**Comment by tfrijsewijk** [comment]
/cc @MichielDHVD kun jij hier een uitspraak over doen? Ergens voel ik wel wat voor het voorstel van @jeroenpeeters maar is het niet te algemeen?

@jeroenpeeters: Kan een plaat in een `p` staan? In de beschrijving van het DsoRichContent component (wat IN DsoFieldInfo wordt geplaatst) ben ik daar wel van uitgegaan. Dan is ook de tussenruimte geregeld.

Dus:

```html
<div class="dso-rich-content">
  <p>Paragraaf</p>
  <p><img /></p>
  <p>Volgende paragraaf</p>
</div>
```

Hoewel er ook wat voor te zeggen valt dat `img { display:block; }` NIET in een `p` hoeft.. Waar ik mij het meeste zorgen over maak is: wat nou als je het NIET wilt? Komt dat voor?

**Comment by MichielDHVD** [comment]
Het gaat hier alleen om afbeeldingen in de toelichtingen box. 

Punt is dat Bevoegde gezagen (Mensen van gemeentes,waterschappen, provincies etc. ) afbeeldingen gaan toevoegen aan de toelichtingen box. Dus de content wordt gevuld door mensen van buitenaf. In zulke situaties vind ik het des te belangrijker om juist wat meer vast te zetten. 

Want anders onstaan er veel inconsistenties in hoe de toelichtingen eruit gaan zien. Dus ik ben het eens met voorstel van @jeroenpeeters om het meer vast te leggen. Want de gewone gebruiker kan niet de verantwoordelijkheid dragen om de afbeeldingen goed te plaatsten in het systeem en met <p> aan de slag te gaan etc.

**Comment by jeroenpeeters** [comment]
@tfrijsewijk Een plaat kan in een `p` staan inderdaad. Vooralsnog lijkt dit ook altijd zo door de markdown renderer gedaan te worden, maar ik zou hier niet vanuit gaan. Zoals @MichielDHVD al hierboven zegt; het is volgens mij het beste om platen in div.dso-rich-content altijd de door mij voorgestelde css attributen mee te geven.

**Comment by tfrijsewijk** [comment]
De stand van zaken is vandaag uitgekomen in `3.1.0-alpha.5`. Hier zit de suggestie van Jeroen (nog) niet in, dit zullen we in een ander issue meepakken

(Sorry, administratief geneuzel maar technisch gezien heeft het wel met een ander component te maken)

**Comment by MichielDHVD** [comment]
Ik heb zojuist net even alles nog even gecontroleerd en de wcag check gedaan en kwam erachter dat het kruisje niet door de wcag contrast waarde heen komt. 

Alleen de codesniffer geeft dit niet duidelijk weer omdat het kruisje een svg is. Maar de kleur van het kruisje moet veranderd worden van #39870c naar #275937 dan komt het wel door de contrast checker heen. Deze is nu 3.9 maar moet 4.5 zijn. De nieuwe kleur heeft 6.49

Ik tag @DHvD-Michael even om hem te updaten over de situatie van het kruisje.

**Comment by tfrijsewijk** [comment]
Uitgekomen in `3.1.0-beta.0`: https://www.dso-toolkit.nl/3.1.0-beta.0/components/detail/form-field-info.html

**Comment by MichielDHVD** [comment]
Gezien en verplaatst naar done.
