### ISSUE TITLE
Build: Percy visueel regressie-testen stabiel maken

### ISSUE THREAD

**Issue by svrijsewijk** [dso-toolkit/dso-toolkit#2030]
We maken dankbaar gebruik van Percy, maar we moeten aandacht besteden aan false positives: Animaties en async.
. Momenteel heeft percy altijd visual changes, dit komt omdat de spinner en de header gescreenshot wordt. De animatie van de spinner zal alleen in percy uitgezet moeten worden.

De header zal een wait moeten hebben voordat een screenshot genomen wordt, zodat deze in een stable render is.
## Animaties

We kennen ze inmiddels wel: 

* html-css-progress-indicator
* html-css-progress-indicator
* html-css-progress-indicator
* core-progress-indicator

Dit is geen complete lijst.

![image](https://user-images.githubusercontent.com/9696261/208871483-6ab089ca-dc6f-4388-8f24-1214492bd469.png)

Percy heeft hier de volgende oplossingen voor
* https://docs.percy.io/docs/percy-specific-css
* https://docs.percy.io/docs/ignored-regions
* https://docs.percy.io/docs/animations

Ik vind vooral "Percy Specific CSS" icm. de SDK een mooie optie.

## Async

Soms worden screenshots te vroeg genomen waardoor Web Components nog niet klaar zijn, lijkt het wel:

![image](https://user-images.githubusercontent.com/9696261/208871611-d625fb65-ab3a-49a3-91c5-f05ab480be9e.png)

Ik ben nog niet helemaal achter een oplossing gekomen, maar dat het een timing issue is staat als een paal boven water. De test die vaak faalt is Header, en dat is geen Shadow dus `@percy/dom` zou de gegenereerde markup gewoon moeten serializeren. Maar omdat `enable_javascript` aanstaat zal het Web Component de markup wel opnieuw renderen?

We zullen dus moeten wachten, maar op 'n dusdanige manier dat stories die gebruik maken van Header daar ook plezier van hebben.

* https://docs.percy.io/docs/debugging-sdks#how-percy-works
* https://docs.percy.io/docs/percy-snapshot#advanced

**Comment by LukeVerlaan** [comment]
De Percy specific css voor html-css spinner werkt. Maar voor core krijg ik het niet werkend. Header heb ik nog geen oplossing voor kunnen vinden.

**Comment by MichielDHVD** [comment]
@tfrijsewijk dit issue is een duplicate van #1937. Voorstel deze sluiten (andere heeft meer specificatie). 1937 is wel RFD?

**Comment by tfrijsewijk** [comment]
Laten we het andere issue sluiten en de specs naar dit issue verhuizen. Onder dit issue heeft Luke al best wel wat werk verzet.

**Comment by tfrijsewijk** [comment]
@LukeVerlaan Kan jij naar de branch kijken, rebasen en een (draft?) PR aanmaken? Dan staat ie op de radar en gaan we dit belangrijke PR eens ff mergen..

**Comment by tfrijsewijk** [comment]
Ivm. de vakantie van Luke neem ik dit issue over.

**Comment by tfrijsewijk** [comment]
- [ ] Iconen blijven een dingetje, ze tonen soms wel/niet

**Comment by tfrijsewijk** [comment]
😌✨
