### ISSUE TITLE
Urgente wens: Extra event vanuit Map control component als Kaartlagen panel in- en uitgeklapt wordt

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#2033]
... met in het event de info of het panel open of dicht is

**Comment by gofix** [comment]
Cool die `"should emit events"` test, de uitgelezen manier om te bewijzen dat we hier gedaan hebben wat beoogd is.

**Comment by gofix** [comment]
Fijn zo, ik zie in storybook het event doorkomen met in detail -> open de actuele staat van het ding.
![image](https://user-images.githubusercontent.com/2689559/223949856-741db1d7-43c5-4534-8a53-46e242ca2e8b.png)

**Comment by gofix** [comment]
Moet hier nog een ontwikkelaar in een team naar kijken, om te bepalen of dit is wat benodigd is, @hansgrimm ?

**Comment by hansgrimm** [comment]
@gofix ik denk het wel; ik loop straks wel even langs bij PR12, ik ben nu toch in 010 :)

**Comment by hansgrimm** [comment]
https://dso-toolkit.slack.com/archives/CB417GQBC/p1678373526606069
