### ISSUE TITLE
Slide Toggle: Drag bediening ondersteunen

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#2036]
De dso-slide toggle werkt nu goed op basis van de release trigger.
Er zijn ook mensen die proberen de schuif te bedienen door hem fysiek te schuiven. Dat werkt nu niet goed. 
Voorstel is om deze te bedienen op basis van mousedown trigger, zodat ook de "schuifers" de toggle kunnen bedienen.

**Comment by tfrijsewijk** [comment]
Overigens heeft Angular Material Design sinds versie 9.0.0 (en dat is oud) geen drag functionaliteit meer. Zie dit commentaar voor de onderbouwing: https://github.com/angular/components/pull/17102#issuecomment-532056221

@DjangoBlok Volgens ons heb jij dit ingeschoten, willen we het hier nog over hebben?

**Comment by LukeVerlaan** [comment]
Progress tot nu toe: 
https://storybook.dso-toolkit.nl/_2036-Slide-toggle-ook-drag-bediening-ondersteunen/?path=/story/core-slide-toggle--default

https://github.com/dso-toolkit/dso-toolkit/commit/741f498ee4ec15a98da0937eeb9d874c1f0f9d81

Volgens mij redelijk straightforward.

Er moet nog wel een minimale beweging komen voordat het als "drag" wordt gezien.

**Comment by tfrijsewijk** [comment]
@DjangoBlok Nou, Luke is toch al wel mooie dingen aan het maken..

@LukeVerlaan Ik ben zo vrij om wat opmerkingen te plaatsen, laten we die discussie in het PR doen.

**Comment by tfrijsewijk** [comment]
@LukeVerlaan We schuiven deze change op de lange baan. Er zijn nu dringendere zaken die onze aandacht behoeven. Daarnaast gaat het UX team nog ten rade of dit echt een werkvorm is die we zo willen aanbieden.

Maar de inspanning en resultaten worden gewaardeerd ;-)

**Comment by hansgrimm** [comment]
Het is nooit weg; je hebt er sowieso wat van geleerd, dus sla dit stukje code vooral ergens op 😉

**Comment by tfrijsewijk** [comment]
@DjangoBlok Prima, dank!
