### ISSUE TITLE
Icoon a.extern::after en dso-succes a::after bijten elkaar.

### ISSUE THREAD

**Issue by TonD83** [dso-toolkit/dso-toolkit#204]
Zie de link naar cultureelerfgoed.nl in onderstaande afbeelding. Deze anchor heeft de class 'extern', dus we zouden hier een icoontje achter verwachten. Echter, is er een conflict tussen .dso-accordion-section.dso-succes a::after (het groene vinkje) en a.extern::after (het externe icoontje) waardoor e.e.a. niet werkt.

### Waargenomen:
<img width="1673" alt="screen shot 2018-10-11 at 11 44 10" src="https://user-images.githubusercontent.com/18580063/46804762-c7107100-cd63-11e8-8ed2-81e399546c79.png">

### Verwacht:
<img width="1680" alt="screen shot 2018-10-11 at 11 43 57" src="https://user-images.githubusercontent.com/18580063/46804912-1d7daf80-cd64-11e8-9733-ac17c4f4107f.png">

**Comment by tfrijsewijk** [comment]
We gaan 'm oppakken, dank voor het melden!

**Comment by TonD83** [comment]
Fijn, thanks!

**Comment by tfrijsewijk** [comment]
Komt uit in `3.1.0-alpha.1`

**Comment by tfrijsewijk** [comment]
@TonD83 Vandaag is `3.1.0-alpha.1` uitgekomen, ben jij in de gelegenheid om deze bugfix te controleren?

**Comment by TonD83** [comment]
@tfrijsewijk Hertest OK!

![screen shot 2018-11-07 at 17 10 22](https://user-images.githubusercontent.com/18580063/48144061-70d61580-e2b0-11e8-9803-e474486172db.png)

**Comment by MichielDHVD** [comment]
Ik zet deze naar done!
