### ISSUE TITLE
Date picker: Copy-paste in Date picker doet raar (won't do?)

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#2042]
invalide invoer komt in zijn geheel niet door bij kopieren van bijv.
- Aa-10-2022 komt alleen -10-2022 in de het input element maar ook
- aa-aa-aaaa komt er niets door, ook geen validatie fout

Aanvulling 7 juni:

Ik denk dat deze een meer fundamentele discussie triggert op twee punten:
1. Hoe gaan we om met "foute" keyboard invoer? Filteren (zoals hierboven beschreven), of een melding geven als een niet-toegestaan karakter is ingevoerd?
2. Hoe gaan we om met Placeholders? Wat willen we daar wel en niet in zetten? Verhuist de Placeholder buiten de input zodra hij de focus heeft en/of content heeft? (dit is wel gangbaar). Hoe ziet dat er dan uit?

Laten we die in UX overleg meenemen

**Comment by hansgrimm** [comment]
@svrijsewijk ging deze niet naar "won't do"?

**Comment by WidoBurg** [comment]
Met de niet dso-toolkit implementatie hadden we deze terug koppeling wel. Op welke wijze kan uiteraard anders worden ingevuld. Maar dat is de fundamentele vraag die in de intro wordt aangegeven.

**Comment by tfrijsewijk** [comment]
In #2226 gaan we de Date Picker laten opvolgen door `input[type="date"]` waarmee dit issue geen bestaansrecht meer heeft.
