### ISSUE TITLE
Date Picker: Ondersteuning voor aria-describedby

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#2049]
Tbv WCAG compliancy: aria attributen op het invoer element

- *aria-invalid* kan worden meegeven en wordt gezet op het input element. Waardoor aria-invalid=“true” is bij de input bij een error of "false" bij geen error
- *aria-describedby* kan worden meegeven en wordt gezet op het input element

moet van buitenaf worden meegegeven

Originele melding komt bij @WidoBurg vandaan.

**Comment by tfrijsewijk** [comment]
Bug of feature?

**Comment by timveld** [comment]
Bug, in de zin dat deze attributen nodig (kunnen) zijn om aan WCAG te voldoen

**Comment by hansgrimm** [comment]
@timveld gewetensvraagje: als jij de keus hebt tussen een datum inkloppen in een veld of een datepicker gebruiken, wat zou jij dan doen?

**Comment by timveld** [comment]
Een datum die ik al ken (mijn geboortedatum, datum verhuizing etc) zal ik altijd typen. Date picker kan vooral handig zijn om zeker te weten dat ik de juiste weekdag kies, bijvoorbeeld bij het plannen van een reis. 

In de context van DSO denk ik dat de meeste gebruikers de datum zullen typen, vooral voor data in het (verdere) verleden is een date picker erg omslachtig. Maar misschien denken sommige gebruikers daar anders over en het hangt ook af van de context waarin het component gebruikt wordt, daarom moet het component m.i. beide opties goed en gesynchroniseerd ondersteunen.
