### ISSUE TITLE
Externe link icoontje verspringt bij een dubbele regel. 

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#205]
Als er een externe link over een dubbele regel verspreid is de plaatsing van het icoontje niet meer juist. 

Een afbeelding van de normale situatie en eentje waar de fout is te zien. 

<img width="273" alt="screen shot 2018-10-15 at 13 36 39" src="https://user-images.githubusercontent.com/36912722/46948789-81171e00-d07f-11e8-8275-bac0e8327962.png">
<img width="219" alt="screen shot 2018-10-15 at 13 36 49" src="https://user-images.githubusercontent.com/36912722/46948790-81171e00-d07f-11e8-93dc-8ebade83cbd5.png">

De bedoeling is dat het icoontje bij een twee regels link. Achter de tweede regel komt te staan.

**Comment by tfrijsewijk** [comment]
Fixed in `3.1.0-alpha.1`.
* https://www.dso-toolkit.nl/3.1.0-alpha.1/components/detail/anchor.html
* https://www.dso-toolkit.nl/3.1.0-alpha.1/components/detail/anchors.html

Niet foutloos, @PieterVerheij kan jij toelichting geven?

**Comment by MichielDHVD** [comment]
Wat betekent niet Foutloos hier @tfrijsewijk ? 

Wat mij opvalt is dat als je bij anchor.html het frame kleiner maakt het icoontje naar rechts springt over de tekst als er geen ruimte is.

**Comment by tfrijsewijk** [comment]
Bedoel je dat het icoon naar links springt bij een kleiner frame? In dat geval heb je meteen het eerder aangekondigde bestaat van een foutje gevonden ;)

We zitten in dubio: Het lukt ons niet om het icoon naar de volgende regel te laten springen omdat het icoon een float is. Dit doen we ook niet zomaar. Dit heeft met de underline on hover te maken.

Met float:
hover:
![image](https://user-images.githubusercontent.com/9696261/48200751-696e4500-e360-11e8-917d-a5e3d30009bb.png)
te kleine viewport:
![image](https://user-images.githubusercontent.com/9696261/48200787-8145c900-e360-11e8-8c34-3222bcd513c5.png)

zonder float:
hover: 
![image](https://user-images.githubusercontent.com/9696261/48200851-adf9e080-e360-11e8-9b2c-05597c362291.png)
te kleine viewport:
![image](https://user-images.githubusercontent.com/9696261/48200860-b6eab200-e360-11e8-91b7-db81194da1c0.png)

**Comment by MichielDHVD** [comment]
Hoe vaak gaat het uberhaupt gebeuren dat de viewport zo klein wordt dat een link zo wordt afgekapt? Dat moet dan wel een hele extreme edge case zijn. 

Maar als dit perse voorkomen moet worden dan heeft mijn voorkeur zonder float. De underline is namelijk niet altijd in beeld. Terwijl bij een kleine viewport de overlap tussen icoon en tekst wel altijd zichtbaar is. 
Dus die krijgt prioriteit. Dus dan zou ik het zonder float doen.

**Comment by tfrijsewijk** [comment]
@PieterVerheij wil jij het uitvoeren?

**Comment by tfrijsewijk** [comment]
Laatste fix zit in `3.1.0-beta.0`:
* https://www.dso-toolkit.nl/3.1.0-beta.0/components/detail/anchor.html
* https://www.dso-toolkit.nl/3.1.0-beta.0/components/detail/anchors.html

**Comment by MichielDHVD** [comment]
Gezien en verplaatst naar done
