### ISSUE TITLE
Accordion: Margins specifieker scopen zodat de inhoud van een Accordion daar geen last van heeft.

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#2050]
## Aanleiding: 
Bij PR12 vallen twee knoppen tegen elkaar aan doordat de HTML/CSS variant van de Accordion de marges overruled. Bij het Web Component gaat dit wel goed.

## Werkzaamheden: 

- Controleer de css dat niet elke marges wordt verwijderd in een Accordion. 

## Testen:

-Controleer of voor het HTML/CSS component de marges nu niet allemaal verwijderd worden. Gebruik bijvoorbeeld een `.dso-button-row` om een button in een Accordion om te kijken of deze margins nu wel toegepast worden.

![image](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/31cefc0a-8902-4605-b63f-ef323df742cb)

**Comment by tfrijsewijk** [comment]
@MichielDHVD is dit nog steeds van toepassing?

**Comment by MichielDHVD** [comment]
Ik ga het deze week nalopen.

**Comment by tfrijsewijk** [comment]
Zie https://storybook.dso-toolkit.nl/54.0.1/?path=/story/voorbeeldpagina-s-toepassingen-aanvragen-documenten--documenten&args=preferredImplementation:html-css. Wissel tussen preferredImplementation om het effect goed te zien.
