### ISSUE TITLE
Modal: extra tab stop op inhoud optioneel maken

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#2055]
## Waar
Core / modal alle varianten

## Aanleiding
Zelfevaluatie rtr.
Bij tabben stopt de focus na het sluitkruisje ook op de inhoud midden in het dialoog. Dit is noodzakelijk om inhoud die geen focus-bare componenten bevat met het toetsenbord te kunnen scrollen (zie #1989).

Dit gedrag is problematisch bij modals met interactieve inhoud, zoals het dialoog wat verschijnt als je in [RTR](https://pre.omgevingswet.overheid.nl/registratie-toepasbare-regels) op de knop toon 'alle opties' drukt

Het effect is dan namelijk dat de volledige inhoud wordt voorgelezen. Een screen reader gebruiker denkt waarschijnlijk dat hij al op het eerste invoerveld staat, maar dat is niet het geval. Ook bij andere toetsenbord gebruikers kan deze onnodige tab stop irritatie en verwarring veroorzaken.

Omdat alleen de implementator weet of zijn inhoud wel of niet interactief is, moet dit probleem worden opgelost met een property van de modal die bepaalt of de extra tab stop wel of niet wordt gemaakt.

### Wanneer wel / geen tab stop?
Mijn voorstel is voor te schrijven dat de tab stop altijd wordt gemaakt, tenzij a) de inhoud interactieve elementen (niet zijnde links) bevat en b) het eerste interactieve element bij normale zoom direct bij het verschijnen van het modal in beeld is.

Voor tekst is consistent gedrag belangrijk, het is niet wenselijk dat het gedrag anders wordt als toevallig ergens een linkje in de tekst staat.

Bevat het modal een vorm van formulier (zoals het alle opties voorbeeld in rtr) dan is de tab stop verwarrend. Het voorbehoud dat het eerste interactieve element bij normale zoom direct zichtbaar moet zijn, dient om de situatie dat een lange tekst moet worden doorgescrolt voordat het eerste interactieve element wordt gebruikt (voorbeeld: een licentieovereenkomst met onderaan een vakje 'ik ga akkoord') af te vangen. In deze situatie zou het weglaten van de tab stop er namelijk toe leiden dat toetsenbord gebruikers op het selectievakje zouden landen en eerst helemaal terug naar boven moeten scrollen om de tekst te lezen.

## Werkzaamheden
(voorstel)

- een property 'tab stop on content' toevoegen, die standaard true is.

## Gebruikersimpact
Hinderlijk: de extra tab stop op een formulier kan vooral voor screen reader gebruikers zeer verwarrend zijn.

## Refinement 16mar23
component 'slim' maken dat hij 'weet' of er wel of niet interactieve content in de body zit: RFD

**Comment by tfrijsewijk** [comment]
@timveld Ligt de change uit #1989 hier ten grondslag aan?

**Comment by timveld** [comment]
@tfrijsewijk  ja dit is door #1989  ontstaan

**Comment by tfrijsewijk** [comment]
OK!

In je specificaties staat het volgende:

> Omdat alleen de implementator weet of zijn inhoud wel of niet interactief is, moet dit probleem worden opgelost met een property van de modal die bepaalt of de extra tab stop wel of niet wordt gemaakt.

Wij kunnen prima inschatten of er interactieve onderdelen in de Modal staan. @svrijsewijk @LukeVerlaan Wat denken jullie?

Als we deze functionaliteit kunnen borgen in het component heeft dat mijn voorkeur. Maar zijn interactieve elementen de enige voorwaarde voor de `tabindex` op de Modal body?

**Comment by tfrijsewijk** [comment]
@timveld gaat nog antwoord geven.

**Comment by timveld** [comment]
@tfrijsewijk antwoord op je vraag is ja.


Echter, ik realiseer me nu dat mijn voorstel een ander probleem kan introduceren.
Staat de focus op een invoerveld, dan worden pijltoetsen en page up / down afgevangen en is de inhoud  van het modal niet meer met het toetsenbord scrollbaar. Worst case: de inhoud bestaat uit een invoerveld bovenaan met daar onder een lange toelichting, dan kan een deel van de toelichting zonder muis niet meer bereikt worden.

Verder denkend vraag ik me af hoe intuïtief het eigenlijk is dat een gebruiker eerst een paar keer op tab moet drukken voordat hij de modal kan scrollen. Verwacht hij eigenlijk niet dat het - net als buiten een modal - zo is dat pijl omhoog / omlaag meteen de inhoud scrollt, waarbij het sluitkruisje en eventuele 'onderknoppen' op hun plaats blijven staan?


Kortom, ik vraag me af of we de tab stop als oplossing helemaal kunnen schrappen en kunnen zorgen dat scrolltoetsen ook werken als de focus zich op sluitkruisje of 'onderknoppen' bevindt. Dan zou je de scrolltoetsen op de een of andere manier moeten afvangen en doorgeven. Wellicht ingewikkeld maar verreweg de beste aanpak waarmee het scrollgedrag het gedrag buiten de modal het best benadert.


Als dit niet mogelijk of wenselijk is, gaat dit issue waarschijnlijk op won't do en moet ik een andere oplossing voor de situatie in RTR verzinnen.

**Comment by tfrijsewijk** [comment]
> Staat de focus op een invoerveld, dan worden pijltoetsen en page up / down afgevangen en is de inhoud van het modal niet meer met het toetsenbord scrollbaar. Worst case: de inhoud bestaat uit een invoerveld bovenaan met daar onder een lange toelichting, dan kan een deel van de toelichting zonder muis niet meer bereikt worden.

Maar dat is toch hoe het web werkt? Een gebruiker focust een element waar hij mee gaat werken. Als de persoon klaar is met invoeren moet de focus dus terug naar de Modal body waarna pijl omhoog/omlaag weer scrollen.

Maar daarnaast vraag ik mij af, waarom moeten we dit allemaal doen en over nadenken? Dit is toch waarom er screenreaders zijn?

> Kortom, ik vraag me af of we de tab stop als oplossing helemaal kunnen schrappen en kunnen zorgen dat scrolltoetsen ook werken als de focus zich op sluitkruisje of 'onderknoppen' bevindt. Dan zou je de scrolltoetsen op de een of andere manier moeten afvangen en doorgeven. Wellicht ingewikkeld maar verreweg de beste aanpak waarmee het scrollgedrag het gedrag buiten de modal het best benadert.

De tabindex oplossing was nodig omdat screenreaders de inhoud niet voorlezen.

> Als dit niet mogelijk of wenselijk is, gaat dit issue waarschijnlijk op won't do en moet ik een andere oplossing voor de situatie in RTR verzinnen.

Ik denk dat we eerst wat meer research moeten doen. @hansgrimm wil jij hierover meedenken en onderzoeken?

**Comment by timveld** [comment]
"De tabindex oplossing was nodig omdat screenreaders de inhoud niet voorlezen."
Nope, de tabindex is toegevoegd om scrollen met het toetsenbord mogelijk te maken voor gebruikers zonder screen reader. Voor een screen reader heeft deze geen functie of is hij zelfs verwarrend. 
"Als de persoon klaar is met invoeren moet de focus dus terug naar de Modal body"
Correct, en dat is juist het probleem wat ik bij nader inzien met mijn eigen voorstel heb. Het 'afvangen van scrolltoetsen in een invoerveld' is inderdaad hoe het hele web werkt', maar omdat de pagina altijd ook andere focusbare elementen heeft kun je alsnog scrollen door de focus op een willekeurig element te zetten wat de scrolltoetsen niet afvangt. Maar bestaat de inhoud van een modal alleen uit invoervelden en niet-focusbare tekst (een situatie die in de praktijk zeker voorkomt), dan is er zonder de tabindex geen alternatieve mogelijkheid om te blijven scrollen. 

Kortom: als we conform mijn voorstel de tabindex verwijderen om de voor een screen reader gebruiker verwarrende situatie in RTR op te lossen (ik zal maandag eerst goed laten horen wat het probleem precies is!) dan openen we de mogelijkheid dat gebruikers met alleen toetsenbord maar zonder screen reader de inhoud van het modal in bepaalde situaties (zoals mijn worst case scenario met een enkel invoerveld waaronder een lange toelichting) niet meer kunnen scrollen. 

@hansgrimm toevoegen aan ons lijstje voor maandag.

**Comment by hansgrimm** [comment]
@timveld ik zit er zelf over na te denken om te detecteren of het modal met keyboard wordt geopend, en dan vervolgens de modal body in zijn volle lengte te tonen, dus niet als een brievenbus. Uiteraard moet dan wel rekening gehouden worden met uit beeld lopen en dus op en neer kunnen scrollen.

**Comment by hansgrimm** [comment]
Ik begin me steeds meer af te vragen waarom we ooit begonnen zijn met die brievenbus, anders dan om cosmetische redenen. Het gaat ten koste van de scanbaarheid, toont niet altijd visueel dat er meer te lezen is, en het nodigt content uit om er de hele Lord of the Rings trilogie erin te kwakken.

Als we voor iedereen teruggaan naar ‘full length’ zonder scroll hoeven we geen rare hacks in te bouwen, en dwingen we iedereen om de inhoud van een modal kort en bondig te houden.

**Comment by hansgrimm** [comment]
@hansgrimm en @timveld :
Voorstel om de 'brievenbus' af te schaffen naar UX-overleg 
RTR moet overtuigd worden

**Comment by tfrijsewijk** [comment]
Dit issue terug naar Discovery, dit wordt vanuit UX nog besproken.

**Comment by tfrijsewijk** [comment]
@hansgrimm Volgens mij kan dit issue gesloten worden omdat we met `<dialog>` aan de bak gaan, correct?

**Comment by hansgrimm** [comment]
Volgens mij wel.
