### ISSUE TITLE
Npm audit rapporteert 17 high prio security issues

### ISSUE THREAD

**Issue by WiebeCnossen** [dso-toolkit/dso-toolkit#206]
Als je `npm install` (of beter: `npm ci`) doet op de repo, worden 17 high prio security issues gerapporteerd.

**Comment by tfrijsewijk** [comment]
Ik pak 'm op.

Tevens fix ik de gulp dependency op de niet-bestaande ref (`#4.0`) en zal ik in de `package.json` alle dependencies fixed zetten zodat package-lock.json geen changes meer geeft na een `npm install`
