### ISSUE TITLE
Expandable Heading Renvooiweergave ondersteunen 

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#2061]
Renvooiweergave ondersteunen voor het Expandable Heading component

Renvooiweergave biedt de volgende mogelijkheden:

- Ondersteuning van renvooiweergave in de kop (via het Ozon content component [DSOT-633](https://jira.team-dso.nl/jira/browse/DSOT-633))
- Ondersteuning van renvooiweergave in de prefix:
    - Toegevoegde nummer groen markeren
    - verwijderd nummer rood markeren

## Werkzaamheden

Bij verwijderde container

- Achtergrond van de container rood kleuren (rood20 / #F5D8DC)
- Tekst in de container doorgehaald weergeven
- Bovenin het groene kader een tekst "verwijderd:" in cursief

Bij toegevoegde container

- Achtergrond van de container groen kleuren (lime20 / #E4F1D4)
- De container voorzien van een dropshadow 
- Bovenin het groene kader een tekst "toegevoegd:" in cursief

Voor tekst renvooi

- Bij toegevoegde tekst de container voorzien van een dropshadow

is html-slot, dus daar kan html in (`<del>` en `<ins>`). toolkit regelt styling.

zie ook #2060 

![image](https://user-images.githubusercontent.com/506527/235352847-3558cf9b-9362-4783-8d17-cc07aa186f0c.png)

![image](https://user-images.githubusercontent.com/506527/235352880-c1400adf-4c64-4866-9633-5ac7d402200c.png)

![image](https://user-images.githubusercontent.com/506527/235472836-20521ec4-4b73-40e3-8143-d89377263912.png)

**Comment by hansgrimm** [comment]
**Let op: omschrijving gewijzigd, designs toegevoegd!**

**Comment by LiesbethVorst** [comment]
Het annotatieblok dat kan voorkomen in een item heeft normaal een lichtgrijze achtergrond. In de renvooiweergave moet dit blok wel te onderscheiden zijn maar meekleuren met de rode/groene achtergrond.

**specs van het anotatieblok**
achtergrond: wit 40% opacity
border: 1px zwart-20

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/91903058/236484439-653d37a5-2ec8-46dc-aea8-d5719a2a434b.png">
