### ISSUE TITLE
Performance issue grote documenten in de viewers

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#2065]
Het tonen van grote documenten in de viewers levert performance problemen voor de client. Dit lijkt te ontstaan door het toevoegen van webcomponent label en het webcomponent tooltip.

[Liesbeth Vorst](https://github.com/jira/secure/ViewProfile.jspa?name=liesbeth.vorst) : 
de performance is zo slecht dat dit niet gereleased is.
Er moet dus contact zijn tussen developers van het team en IP.

**Comment by kad-tammie** [comment]
Keep me in de loop ;-)

**Comment by svrijsewijk** [comment]
In de volgende release hebben we verbeteringen toegepast op het label component. Zou jij willen kijken of de performance acceptabel is wanneer je alleen `<dso-label>` inzet. (<dso-badge>/<dso-tooltip> komen zodra dit eerste stapje succesvol is)

**Comment by svrijsewijk** [comment]
Ik heb zelf nog wat aandachtiger gekeken. De eerste stap die we hebben gezet in 52.0.1 is niet voldoende. In die release hebben we voor de `<dso-label>` nog maar één `New ResizeObserver()`.

Nadere analyze geeft nog twee grote oorzaken van de performance issues:
* `<dso-label>` las de content uit door middel van HTMLElement.innerText, dit is een dure operatie omdat innerText een reflow forceert. Zie https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent#differences_from_innertext de tekst is nodig voor de tooltip bij `[truncate]` en de knop-tekst bij `[removable]`. Bij 1000 `<dso-label>` instanties scheelde dit bij mij lokaal ongeveer 1500ms time-to-interactive.
* `<dso-tooltip>` instantieerde een popper instance bij initialisatie, dit is een dure operatie. Dit gebeurt nu enkel wanneer de tooltip ook actief is.

Daarnaast:
* `<dso-label>` rendered de `<dso-tooltip>` nu alleen als er ook truncated tekst is.

https://github.com/dso-toolkit/dso-toolkit/pull/2084

**Comment by hansgrimm** [comment]
Top!
