### ISSUE TITLE
Nieuw component "Scrollable".

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#2071]
Eigenschappen

- De schaduw is 24 px hoog, en heeft een lineair gradient verloop van `#B7B7B7` 0% naar `#B7B7B7` 70%.
- Of een panel wel of geen schaduwen vertoont is een optie bij het panel
- De schaduw verschijnt zodra er zich aan die kant buiten de viewport content bevindt
- De schaduw verdwijnt en verschijnt met een fade animatie effect

Dit wordt een apart generiek webcomponent; `<dso-scroll-container>` o.i.d.

![image](https://user-images.githubusercontent.com/506527/230361236-2969d99f-86ae-47ef-80ef-9a0823451709.png)

![image](https://user-images.githubusercontent.com/506527/230361304-2bac832c-dc5a-4b73-b60f-db92443c7541.png)

![image](https://user-images.githubusercontent.com/506527/230361368-fbf61ef2-c8ef-4572-a9ae-a4341b7f5aae.png)

![image](https://user-images.githubusercontent.com/506527/230361435-09f4828c-f026-401d-aa68-4e115247aefa.png)

**Comment by tfrijsewijk** [comment]
Aandachtspunt is dat de het Map Controls component nu geen overflow heeft. De scrollbar in de Storybook omgeving wordt door het iframe gemaakt. 

Ik zie graag een ontwerp met scrollbar, puur vanwege verwachtingsmanagement.

![image](https://user-images.githubusercontent.com/9696261/229745227-cc25790c-789a-4ea4-9890-6b607d241cb0.png)

**Comment by MYpenburg** [comment]
Wat scrollt er dan precies? In mijn voorbeeld scrollt alleen de inhoud van alles wat onder "Kaartlagen" staat.

**Comment by tfrijsewijk** [comment]
Dat begrijp ik, maar dat is dan wel iets wat gemaakt moet worden. Gaat het nieuw-te-maken Web Component ook het scrollgedrag aanbieden? En wie bepaalt dan de (scrollbare) hoogte?

En met mijn verzoek tot ontwerp wil ik benadrukken dat in browsers/OSen die wel een scrollbar toont, de gradient naast de scrollbar komt te staan. Realiseert iedereen zich dat?

**Comment by MYpenburg** [comment]
Zullen we deze donderdag nog een keer langs laten komen in de refinement?

**Comment by hansgrimm** [comment]
LET OP: nieuwe designs!
![image](https://user-images.githubusercontent.com/506527/230361236-2969d99f-86ae-47ef-80ef-9a0823451709.png)

![image](https://user-images.githubusercontent.com/506527/230361304-2bac832c-dc5a-4b73-b60f-db92443c7541.png)

![image](https://user-images.githubusercontent.com/506527/230361368-fbf61ef2-c8ef-4572-a9ae-a4341b7f5aae.png)

![image](https://user-images.githubusercontent.com/506527/230361435-09f4828c-f026-401d-aa68-4e115247aefa.png)

**Comment by tfrijsewijk** [comment]
Terugkoppeling op de eerder gemaakte opmerking: Het Map Controls component regelt al dat er gescrolled kan worden:

![image](https://user-images.githubusercontent.com/9696261/230394906-9e0d0efb-7762-411f-b0a4-6ebeed634eff.png)

Deze functionaliteit moet dus verplaatst worden naar het nieuwe "scroll container component"
