### ISSUE TITLE
List Button: multi select mechanisme "aantal kiezen" is niet goed

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#2072]
## Waar

core / list button-multi select. Alleen core: html/css wordt deprecated.

## Aanleiding

Nav zelfevaluatie / overleg met @MYpenburg:

## Achtergrond

In #1903 is de List Button uitgevoerd naar een selectievakje. In de multi select variant is er daarnaast een optie om een aantal keer dezelfde activiteit te kiezen.

Dit werkt visueel als volgt:
Klik je bij een aangevinkte activiteit op het + ('aantal verhogen') knopje, dan wordt een - ('aantal verlagen') en 2 (het aantal van de aangevinkte activiteit) zichtbaar. Je kunt dit aantal met de + en - knopjes met 1 verhogen resp. verlagen. Klik je op de 2, dan kom je in een numerieke input waar je het gewenste aantal direct kunt typen.

Hierin heeft pr12 een bewuste ontwerpkeuze gemaakt, die gehandhaafd moet blijven. Idee is dat dit (het meerdere keren selecteren van een activiteit) een 'pro' optie is  waarvan het gebruik niet moet worden aangemoedigd. Bovendien is er bewust voor gekozen geen standaard numerieke input te gebruiken, omdat die een onprettige muis-interactie zou geven. Ik ga daarom alleen in op de toetsenbord / screen reader interactie, met als uitgangspunt dat de muis-interactie ongewijzigd moet blijven.

### Huidige toetsenbord interactie

Bij tab vanaf het selectievakje van een geselecteerde activiteit komt de focus op de (niet zichtbare) knop 'handmatig aantal invullen'. Verwarrend voor goed ziende toetsenbordgebruikers die niet zullen begrijpen waar de focus op landt (hij landt in de rand van het + knopje en er is op dat moment niet eens een getal zichtbaar). Bij nog een keer tab kom je op het + ('aantal verhogen') knopje. Als je daar op drukt worden het aantal en - knopje visueel zichtbaar. Ook in die situatie is het de vraag of voor toetsenbordgebruikers het 'handmatig aantal invoeren' knopje visueel duidelijk genoeg is. Hoe dan ook blijft staan dat de acties van de + en - knopjes niet aan een screen reader worden bevestigd en dat de manier waarop na het klikken op 'handmatig aantal invullen' een numerieke input over de + en - knopjes heen valt, met daarbij nog de noodzaak expliciet op het 'opslaan' knopje te drukken, het niet intuïtiever maakt.

### Complicaties

Gegeven de eis dat het visuele ontwerp zo blijft (een mooi gestylede numerieke input zou veel makkelijker zijn...) in combinatie met de noodzaak om naast de + en - knopjes het cijfer te kunnen typen (ivm mogelijk grotere aantallen) is het een puzzel om deze interactie zo te krijgen dat hij voor toetsenbordgebruikers zowel met als zonder screen reader soepel werkt. Enkele complicaties:

- oplossingsrichting ‘+ en - knopjes buiten tabvolgorde houden en zo verbouwen dat de toetsenbordgebruiker alleen direct met de numerieke input interacteert’: Voor screen reader gebruikers een goede oplossingsrichting, maar het probleem is dat andere toetsenbord gebruikers (die de knopjes wel zien) verwachten de knopjes met het toetsenbord te kunnen bereiken. Ze moeten maar net slim genoeg zijn om te bedenken dat pijl omhoog / omlaag dezelfde functie heeft, als dat niet visueel wordt aangegeven zullen veel mensen zich dit niet realiseren en zich in bochten gaan wringen om toch bij de knopjes te komen.
- Het probleem dat de actie van de + en - knopjes niet voor een screen reader wordt bevestigd zou kunnen worden opgelost met een aria live region rond het huidige aantal. Maar dat botst met de noodzaak dit aantal handmatig te kunnen bewerken, er komen waarschijnlijk problemen met dubbel voorlezen en inconsistent gedrag van verschillende user agents.
- Het hele idee van 'eerst klikken, dan tikken' om het getal bewerkbaar te maken is een lastige. Hoe je dit ook maakt: het ziet er al snel wat knullig uit en zal voor veel gebruikers niet intuïtief of zelfs verwarrend aanvoelen.
Voorgestelde oplossing

Ik stel de volgende oplossing voor:

- Het 'knopje' handmatig invullen verdwijnt, in plaats daarvan is het cijfertje altijd een focusbare numerieke input. De styling maakt me weinig uit, het ligt voor de hand dat je niets ziet als het cijfertje geen focus heeft en als hij wel focus heeft is voldoende dat (eventueel zeer subtiel) duidelijk is dat je het cijfertje kunt bewerken. Een screen reader zal dit vanzelf duidelijk aangeven.
- De + en - knopjes blijven focusbaar, en als ze worden geactiveerd springt de focus altijd naar de numerieke input. Effect daarvan is dat de screen reader de actie bevestigd krijgt, en veel toetsenbordgebruikers zullen (als het goed wordt gedaan) begrijpen dat ze sneller het gewenste aantal kunnen opgeven door het in te tikken of pijltjestoetsen te gebruiken. Maar als ze de + en - knopjes gebruiken, is het gedrag in ieder geval consistent.
- Als door het activeren van de - knop het aantal 1 wordt (waardoor het - knopje en de numerieke input verdwijnen) springt de focus terug naar het selectievakje.
Werkzaamheden

Pr12: bovenstaande bestuderen en voorgestelde oplossing eventueel verfijnen, daarna ticket verder specificeren.

Het voorstel van Tim zoals hierboven beschreven is akkoord voor toetsenbord interactie.

Qua styling:

- de numerieke input moet er uitzien als een normaal invoerveld, zonder ^ en v knopjes. Onderwater kan het veld prima reageren op de pijltjestoetsen, maar deze moeten altijd onzichtbaar blijven.
- Het invoerveld mag niet de knoppen - en + overlappen, wel verschuiven als dat nodig is. Als getallen van 3 of meer cijfers niet meer helemaal lekker in het veld passen is dat geen probleem, beter dan een te groot invoerveld.
- Tijdens de interactie met -, + en invoerveld mogen deze 3 niet van positie of omvang veranderen

## Gebruikersimpact

Hinderlijk: door de onvolkomenheden van het huidige ontwerp wordt het voor minder ervaren gebruikers snel verwarrend.

**Comment by tfrijsewijk** [comment]
@MYpenburg In dit issue wil je dat de handmatige vorm wordt verbeterd, in #2132 heb je aangegeven dat de handmatige vorm uitgeschakeld moet kunnen worden omdat het team de complexiteit bij het veranderen van een aantal (van "5" naar "7") in de applicatiecode niet kan verwerken.

Nu is dit issue ouder dan #2132, dus misschien dat dit ticket is ingehaald?

**Comment by tfrijsewijk** [comment]
Dit issue heb ik naar de volgende sprint gezet, we hebben antwoord op bovenstaande vraag nodig. Zodra Martin van vakantie is kunnen we het meteen oppakken en releasen.

**Comment by MYpenburg** [comment]
In eerste instantie gaan we deze functionaliteit niet gebruiken (direct invullen van aantallen). Ooit gaat het er wel van komen, maar er is voor iwt geen tijd bij ons om dit te implementeren. Dus het is een afweging: of het nu fixen in het component zodat het later as is gebruikt kan worden, of tzt de aanpassing oppakken als wij het gaan gebruiken. Ook even met het oog op publicatie van het component naar de buitenwereld. Overigens ben ik even lost met het ticket waaraan gerefereerd wordtm want dat is niet #2132.

**Comment by hansgrimm** [comment]
@MYpenburg we zijn de a11y-issues aan het schiften in 2 categorieën: wat moet in PI27 "voor het a-stickertje" en wat kan later. Als 'tzt' betekent dat dit na PI27 (of zelfs na IWT) pas gebruikt gaat worden, dan zou deze voor nu even aan de kant kunnen (tenzij het gezien de commits eigenlijk al gedaan is, en alleen nog even door review en/of test moet; maar dat _lijkt_ niet het geval).

**Comment by MYpenburg** [comment]
Volgens mij kan deze issue door naar Done. De interactie is volgens spec, en de numerieke input (die PR12 nu nog niet kan handelen) is via de software uit te zetten. Er zijn nog een paar andere issues met de listbutton maar die zijn apart ingeschoten.

**Comment by hansgrimm** [comment]
@timveld kunnen we deze naar de eeuwige issuevelden sturen?

**Comment by tfrijsewijk** [comment]
De gewenste functionaliteit is in #2132 opgelost met het attribuut `manual="false"`

**Comment by LukeVerlaan** [comment]
Als de specs beschreven in dit issue nog gewenst zijn, haal ik hem van draft af.

**Comment by tfrijsewijk** [comment]
Volgens mij is het wel goed zo.
