### ISSUE TITLE
In Firefox kun je niet helemaal naar beneden scrollen

### ISSUE THREAD

**Issue by WiebeCnossen** [dso-toolkit/dso-toolkit#208]
Gezien in Firefox 62.0.3, zowel in de navigatiebalk als in de console rechtsonder op https://dso-toolkit.nl kom je niet tot helemaal onderaan.

**Comment by WiebeCnossen** [comment]
In Firefox 63 is het nog steeds. Het treedt op als de inhoud van de linkerbalk hoger is dan in het scherm past.

**Comment by PieterVerheij** [comment]
Eerste analyse is dat dit geen probleem is dat bij de DSO-styling ligt, maar bij Fractal/Firefox. Wellicht zit er een bug in de flexbox-implementatie van Firefox. Ik zoek verder.

**Comment by PieterVerheij** [comment]
Het gaat mis in Fractal zodra er gerommeld wordt met de hoogte van de header. Vgl. https://style.eurostar.com/ (fout), https://styleguide.liip.ch/ (paar pixeltjes fout) en https://bits.24ways.org/ (standaard, dus goed).

**Comment by tfrijsewijk** [comment]
#158

**Comment by tfrijsewijk** [comment]
Uitgekomen in `3.1.0-alpha.1`, @WiebeCnossen wil jij deze bugfix bekijken?

**Comment by tfrijsewijk** [comment]
Dank voor melden en testen!
