### ISSUE TITLE
Stijlen op Web Component attributes

### ISSUE THREAD

**Issue by svrijsewijk** [dso-toolkit/dso-toolkit#2080]
Momenteel wordt in een aantal webcomponenten styling gedaan door middel van attribuut selectors. bijvoorbeeld `dso-date-picker[invalid]` dit is best een charmante constructie maar geeft problemen wanneer `invalid="false"` is gezet, het attribuut bestaat hier nog steeds waardoor de css-selector hierop triggered.

In dit issue bekijken we of het logisch is om nog steeds op deze manier op het attribuut te stijlen en leggen we de uitkomst vast binnen ARCHITECTURE.md

**Comment by MichielDHVD** [comment]
@tfrijsewijk Prioriteit?

**Comment by tfrijsewijk** [comment]
Ja wel enigszins, maar ik laat dit niet voor bugs gaan. Ik zet 'm om RFD en dan komt ie bij mij wel bovendrijven :+1:

**Comment by tfrijsewijk** [comment]
Zie https://github.com/dso-toolkit/dso-toolkit/commit/bebdfeca314a4ae5d94f687844f942120bb73ba7 🎉
