### ISSUE TITLE
Header bugs / Header met sublogo: menu valt deels buiten 320px breedte

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#2081]
## Aanleiding: 
Routine test header leverde wat bugs op

## Werkzaamheden:

- Dropdown Menu op kleinste scherm klapt tegen de linker kant van het scherm. Deze moet net zoveel ruimte hebben als aan de rechterkant
- Wanneer er geen hoofd-menu items zijn, maar wel inloggen en mijn omgevingsloket links zijn. Is er op een klein scherm geen dropdown menu 

## toegevoegd 11 mei:

Bij de header met sublogo is de positie van het uitklapmenu op een smal scherm niet goed. Het menu staat te ver naar rechts en valt deels buiten beeld, zowel de knop als de dropdown.

## Test:

Visueel responsive testen

## screenshots

![image](https://github.com/dso-toolkit/dso-toolkit/assets/506527/b9354d2f-55f0-4b18-968c-e1642567b7df)

![image](https://github.com/dso-toolkit/dso-toolkit/assets/506527/35fa703b-14aa-4707-afc8-8661b664acfc)

![image](https://github.com/dso-toolkit/dso-toolkit/assets/506527/b2d28bc6-9427-4086-ba18-293888461a86)

![image](https://github.com/dso-toolkit/dso-toolkit/assets/506527/b42cb8ab-c8f2-4552-922c-1d0e9884d777)

**Comment by LukeVerlaan** [comment]
Naast de 2 punten in de omschrijving, heb ik nog een punt gevonden. De dropdown opties moeten vanaf de onderrand van de header uitklappen.

**Comment by hansgrimm** [comment]
@LukeVerlaan de andere dsot is hier nu aan toegevoegd, zoals afgesproken

**Comment by tfrijsewijk** [comment]
Vervolg actie https://github.com/dso-toolkit/dso-toolkit/pull/2111#discussion_r1203922518. @svrijsewijk @hansgrimm @LukeVerlaan Is dit werk wat we meteen gaan inplannen of wachten we eerst tot het nodig is?
