### ISSUE TITLE
Upgrade naar 52.0.1 geeft foutmelding m.b.t. ResizeObserver

### ISSUE THREAD

**Issue by micheldebree** [dso-toolkit/dso-toolkit#2085]
Upgrade van 52.0.0 naar 52.0.1 van @dso-toolkit/core breekt onze applicatie.

Uit de tests:

```
  ReferenceError: ResizeObserver is not defined

      1 | import React, { useEffect, useState } from 'react';
    > 2 | import { DsoTreeView } from '@dso-toolkit/react';
 ```

**Comment by hansgrimm** [comment]
@svrijsewijk kan jij even kijken hiernaar?

**Comment by svrijsewijk** [comment]
In 52.0.3 hebben we de ResizeObserver verplaatsing ongedaan gemaakt. Als dit nog steeds speelt zal je de ResizeObserver moeten mocken in je jest tests.

Ik sluit het ticket.
