### ISSUE TITLE
Modal: Visuele en responsive verbeteringen

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#2092]
Zie screenshots.

modal sizes en marges: de normale modal

kantelpunt lage viewport: marges t/m 380 px viewport hoogte

Marges lage viewport: marges < 380 px viewport hoogte

minimale hoogte modal: bij viewport hoogte < 232 px wordt de modal niet meer kleiner

overflow in content: met scrollbar (niet in screenshot)

![image](https://user-images.githubusercontent.com/506527/233383043-7f527e8c-df61-4e86-bad9-4d44e51304f5.png)

![image](https://user-images.githubusercontent.com/506527/233383096-e78c3c15-4549-4a46-b091-439a6a5ecb87.png)

![image](https://user-images.githubusercontent.com/506527/233383191-43fd8fdc-b256-43df-b48d-23c671fd8e53.png)

![image](https://user-images.githubusercontent.com/506527/233383307-3d5e6ae9-8161-49c7-a0bb-060f4e770b70.png)

![image](https://user-images.githubusercontent.com/506527/233383371-8005fd8b-285d-450b-a0e3-7a2cbb50318e.png)

**Comment by tfrijsewijk** [comment]
@MYpenburg ik kan niet goed inschatten of dit issue compleet is, @svrijsewijk kan jij hier wat over zeggen? Is deze READY?

**Comment by tfrijsewijk** [comment]
Hoe verhoudt deze zich tot #2152 ?

**Comment by MYpenburg** [comment]
Dat ze alletwee gedaan moeten worden. Maar ze zijn onafhankelijk te doen. In #2152 doet het geneuzel buiten de modal niet mee (maar staat vrij helder in dat ticket beschreven). Anders morgen even door de refinement halen?

**Comment by HalloJo** [comment]
Tijdens het rommelen kwam ik dit nog tegen:

![Image](https://github.com/dso-toolkit/dso-toolkit/assets/65867508/5fbd2161-66d5-4386-993c-fb254938c790)

De padding aan de rechterkant wordt naar binnen gedrukt voor de scrollbar. Daardoor lijnt de tekst niet meer mooi uit met de buttons. Iemand een idee hoe we dat kunnen omzeilen/aanpakken? 🛠️

**Comment by hansgrimm** [comment]
@HalloJo probeer dit eens: `scrollbar-gutter: stable;`
Zit nu in de Canarische zon, dus kan het zelf even niet testen 😉

**Comment by hansgrimm** [comment]
@HalloJo het reserveert (als het goed is) altijd plek voor de scrollbar, zodat je de padding kan aanpassen totdat het weer uitlijnt. Dat is de theorie. Praktijk is een ander ding, heb dit zelf nog nooit uitgeprobeerd ;)

**Comment by tfrijsewijk** [comment]
Dus dan zou je het op zowel de header, body en footer van het Modal moeten plaatsen, zodat het altijd uitlijnt?

**Comment by hansgrimm** [comment]
Ik denk het. Was zelf op de iPad al bezig met een codepen (geen laptop mee), maar bedacht me ineens: o ja, Safari ondersteunt `scrollbar-gutter` niet… 😂

**Comment by HalloJo** [comment]
Ik heb er even mee zitten rommelen en het enige wat doet met breedte is `scrollbar-gutter: stable both-edges`. Dit voegt de breedte van de scrollbar toe aan de algemene breedte van het object. Maar, om dat nuttig te gebruiken moet ik de padding links en rechts verminderen (20px) zodat het wel netjes is. Ik denk niet dat dit de beste oplossing is. Thoughts?

![Screenshot 2023-06-22 095419](https://github.com/dso-toolkit/dso-toolkit/assets/65867508/5359d860-5f9b-4bde-b0f1-db31494b3260)

**Comment by hansgrimm** [comment]
Vraag is ook: is de gutter in iedere browser gelijk? Anders moet je chromium en mozilla (Safari doet sowieso niet mee) apart gaan selecteren (zie browserhacks.com), en daar word je ook niet blij van…
Is er behalve padding nog een andere manier om de boel uit te lijnen?

**Comment by HalloJo** [comment]
Yes, die zijn niet gelijk. Gaat tussen de `12` en `17px`. En ik dacht spelen met de padding als oplossing, maar dan moeten we weer gaan checken zodra er geen scrollbar is, dat we de padding 'weer' aanpassen.

**Comment by hansgrimm** [comment]
Ik zit te denken hier. Zit er nog een container in `dso-body`? In dat geval kan je de horizontale padding in `dso-body` weglaten en de container daarbinnen een `inline-size` geven van 100%-64px en een `margin-inline: auto`. Dat in combi met een `scrollbar-gutter: stable both-edges` op de `dso-body` zou het moeten fixen.
Staat of valt met de aanwezigheid van die container.
Ik zit dit op mijn ligbedje theoretisch uit te plussen, dus aan jou de schone taak om te kijken of dit wat is 😉

**Comment by tfrijsewijk** [comment]
@HalloJo Ga maar voor praktisch: dan maar geen tekst die net niet met knoppen uitlijnt.

Mooi werk verder!

**Comment by hansgrimm** [comment]
Sowieso is uitlijnen van tekst aan de rechterkant slechts theoretisch als de boel standaard links uitgelijnd staat. Maar net hoe het aan het eind vd regel uitkomt qua woordlengte. In dat geval idd de praktische oplossing.

that said: ik vond het wel een leuke technische uitdaging 😉

**Comment by MYpenburg** [comment]
Ik mis de ScrollContainer in de Modal, klopt dat?

**Comment by HalloJo** [comment]
@tfrijsewijk Zie commit hierboven. ⬆️

**Comment by tfrijsewijk** [comment]
@HalloJo 🤘nice. Ik zal de volgende keer beter kijken 🤪

**Comment by tfrijsewijk** [comment]
De rest pakken we in #2223 op.
