### ISSUE TITLE
Buttons en Buttons in example

### ISSUE THREAD

**Issue by daverhelst** [dso-toolkit/dso-toolkit#210]
We hebben twee plekken waar de buttons gestyled worden:

- https://github.com/dso-toolkit/dso-toolkit/blob/master/components/03-forms/10-misc/01-buttons/_buttons.scss
- https://github.com/dso-toolkit/dso-toolkit/blob/master/src/styles/components/_button.scss

In de _buttons.scss neutraliseren we natuurlijk de :hover states zodat de voorbeeld pagina niet vervuild wordt met daadwerkelijke button styling (op hover).

Maar is het niet zo dat wanneer de eigenlijke buttons een aanpassing krijgen, dit dan dubbel gedaan moet worden in de example pagina styling? Kunnen we dit niet eenvoudig aan elkaar linken?

**Comment by PieterVerheij** [comment]
De class '.example' uit _button**s**.scss kan natuurlijk in de _button.scss verwerkt worden.
