### ISSUE TITLE
Het is niet mogelijk om Mijn Omgevingsloket een paarse underline te geven in header

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#2104]
## Aanleiding

Huidige menu items worden aangegeven met een Aria-current page en een paarse underline in de header. Voor Mijn Omgevingsloket is die parameter er niet. 

## Werkzaamheden: 

- Maak het mogelijk om voor Mijn Omgevingsloket ook een active state mee te geven

## Test: 

- Controleer of je active state ook mee kan geven aan Mijn Omgevingsloket.

**Comment by tfrijsewijk** [comment]
Wat is "Mijn Omgevingsloket" ? Kunnen we dit in onze Storybook reproduceren?

**Comment by LukeVerlaan** [comment]
https://storybook.dso-toolkit.nl/_2034-webcomponent-dso-expandable/?path=/story/core-header--default

Het gaat om de "Mijn omgevingsloket" die je aan de rechterkant van de navigatie ziet.

**Comment by MichielDHVD** [comment]
![Image](https://github.com/dso-toolkit/dso-toolkit/assets/36912722/f7efc81d-853c-4598-a5ef-ed706466545b)

Afbeelding toegevoegd.
