### ISSUE TITLE
Tabs: Tabindex op inhoud tabs

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#2117]
Momenteel wordt er in het toolkit tab component op de inhoud van de actieve tab een tabindex=1 geplaatst. Bij tabben krijg je dan focus op de inhoud van de tab maar dat is geen interactief element. Dit is toch overbodig/niet handig?

**Comment by tfrijsewijk** [comment]
@svrijsewijk Waren we niet tot de conclusie gekomen dat die `tabindex="-1"` gewoon uit de template moest worden gehaald?

**Comment by tfrijsewijk** [comment]
@hansgrimm Kan jij hier nog wat research voor doen?

**Comment by hansgrimm** [comment]
@tfrijsewijk Volgens mij is er geen tabindex meer aanwezig in het component...

**Comment by tfrijsewijk** [comment]
Ik heb iets obscuurs gevonden: https://github.com/dso-toolkit/dso-toolkit/blob/master/storybook/src/components/tabs/tabs.css-template.ts#L31

In de markup voorschriften voor het HTML/CSS component verwachten wij dus dat afnemers iets doen als "active tabs krijgen `tabindex="1"`. Wat best wel raar is.

Na wat archeologisch git blaming heb ik de oorsprong gevonden:

* Issue: https://github.com/dso-toolkit/dso-toolkit/issues/1059
* Pull request: https://github.com/dso-toolkit/dso-toolkit/pull/1066/files#diff-bfa1878ca2fa83f2597f9c27306449bcf08e08c5067ad3514ee12f8b0ef5a0f5R16
* Squash merge commit in master: https://github.com/dso-toolkit/dso-toolkit/commit/0a5d74e7329499f4b10cfa11ee2439511bdbb29d#diff-bfa1878ca2fa83f2597f9c27306449bcf08e08c5067ad3514ee12f8b0ef5a0f5R16

Issue is door Bram gemaakt en door Pieter opgepakt, door Ad gereviewed. Het was geen punt van discussie tijdens het ontwikkelen (geen opmerking in PR). Geen idee dus waarom dit is gedaan 🤷 

Voor Modal hebben we iets soortgelijks gedaan (https://github.com/dso-toolkit/dso-toolkit/issues/1989 & https://github.com/dso-toolkit/dso-toolkit/commit/e3d02139b98b023b0ab55ba54148dd9bd40ddaa0#diff-7fb4c73444f6323ac7310269fc6ccc9463cb97edd3cd3e634c88916598732ccdR88) maar daar hebben we juist `tabindex="0"` gezet.

Zouden we bij tab inhoud niet tussen `tabindex="-1"` (voor niet-actieve-maar-wel-in-het-DOM-aanwezige-tabs) en `tabindex="0"` moeten wisselen? Nu wisselen we tussen `tabindex="0"` en `tabindex="1"`.

**Comment by hansgrimm** [comment]
`tabindex="1"` is m.i. bad practice, dus die optie valt sowieso af ;)

**Comment by tfrijsewijk** [comment]
Maandag gaan @hansgrimm en @timveld dit bespreken.

**Comment by hansgrimm** [comment]
de `tabindex="1"` staat op de tabpanel (de content), en hoort daar niet.
kan eraf.

**Comment by hansgrimm** [comment]
`tabindex="-1"` is de juiste (voor programmatische focus), en die gaat er nu op, ongeacht 'state' van de tab.
