### ISSUE TITLE
Angular 16

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#2122]
~~Eerst moet Storybook 7 (#2083), maar hoe dit tot Stencil 3 (#2120) verhoudt weet ik nog niet..~~

Angular 16 compatible. In #2083 doen we de daadwerkelijke update naar Angular 16, icm. Storybook 7.

**Comment by yktoo** [comment]
@tfrijsewijk Is er een ETA hiervoor? We willen graag naar Angular 16 maar dat levert een compile error op:

```typescript
Error: node_modules/@dso-toolkit/core/dist/types/components.d.ts:788:15 - error TS2320: Interface 'HTMLDsoModalElement' cannot simultaneously extend types 'DsoModal' and 'HTMLStencilElement'.
  Named property 'role' of types 'DsoModal' and 'HTMLStencilElement' are not identical.

788     interface HTMLDsoModalElement extends Components.DsoModal, HTMLStencilElement {
                  ~~~~~~~~~~~~~~~~~~~
```

**Comment by tfrijsewijk** [comment]
Hi @yktoo, niet per se maar we kunnen hier natuurlijk gewoon druk opzetten. Stencil 3 heb ik gisteren afgerond. Eerst moet Storybook 7 nog, dus ik kan dit morgen of maandag oppakken en dinsdag/woensdag releasen. Is dat iets waar je wat mee kan?

**Comment by tfrijsewijk** [comment]
Ik zal morgen wel wat onderzoek doen, dan laat ik je het weten :+1:

**Comment by yktoo** [comment]
@tfrijsewijk Zeker, geweldig!
