### ISSUE TITLE
Document Header: Underline ontbreekt bij hover van "overige versies"

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#2129]
In de documentheader zitten 2 knopjes die extra informatie openklappen. Op de ene zit wel een hover en op de andere niet.

![image](https://github.com/dso-toolkit/dso-toolkit/assets/506527/055c8b1b-b082-4db1-9eee-02a8c2d00fa9)

https://storybook.dso-toolkit.nl/53.0.0/?path=/story/html-css-document-header–default&viewMode=story

## Acceptatiecriteria

Bij hover op de knop "overige versies" wordt de tekst bosgroen en onderstreept weergegeven (net als op de knop "Meer kenmerken").

**Comment by tfrijsewijk** [comment]
Code review ✅ en ik heb 'm getest op de branch deployment. Mooie compacte change 👍

**Comment by hansgrimm** [comment]
Citaat uit mijn LinkedIn profiel:
“ - Fixing bugs/issues by not adding code is a job well done.
- Fixing bugs/issues by removing code is a job extremely well done”
#practiceWhatYouPreach :)
