### ISSUE TITLE
Accordion: Stateless maken

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#2130]
Zodat de `allowMultipleOpen` over meerdere accordeons geldt.

Let op nested accordions. Eigenschappen van group niet doorgeven aan nested accordions.

**Comment by tfrijsewijk** [comment]
Ik zat aan de volgende opzet te denken:

```html
<dso-accordion group="mijn-groep">[...]</dso-accordion>
<dso-accordion group="mijn-groep">[...]</dso-accordion>
```

Maar waar/hoe zetten we dan `allowMultipleOpen`? Op elke?

Een alternatief is met een container:

```html
<dso-accordion-group name="mijn-groep" allow-multiple-open="false">
  <dso-accordion>[...]</dso-accordion
</dso-accordion-group>
```

Maar hier was @MYpenburg weer niet zo van gecharmeerd.

@dso-toolkit/maintainers wat denken jullie?

**Comment by hansgrimm** [comment]
Ik kan ook niks anders verzinnen dan een container... 🤔

**Comment by MYpenburg** [comment]
Gewoon default allowMultipleOpen op false zetten? Dan ben je er toch?

**Comment by LukeVerlaan** [comment]
De default van `allowMultipleOpen` is `false`. Een accordion met `allowMultipleOpen` op `true` zal niet in een groep komen. Wat er dus moet gebeuren is dat bij het openen van een sectie, een open sectie in een andere accordion binnen de group dicht moet klappen. De eerste opzet van @tfrijsewijk zou dus kunnen door een `group` property te maken en bij het openen de accordions met dezelfde `group` te queryen en de open sectie (als er een open staat) te zoeken en die dicht te klappen. Maar binnen welke scope wordt er gequeried?

Een aantal aandachtspunten:
- Als bij het openen van een sectie een sectie in een ander accordion dichtklapt, kan dit verschuiving van het beeld veroorzaken
- Stel er zit een accordion van het groep in een shadow van een ander component, dan is die accordion eigenlijk niet bereikbaar. Lijkt mij dat je geen accordion van een groep in de shadow van een component wilt plaatsen (en dus niet ondersteunen?).
- Moet er iets van een parent/container worden aangewezen waarbinnen de accordions worden gequeried?

**Comment by tfrijsewijk** [comment]
> Een accordion met `allowMultipleOpen` op `true` zal niet in een groep komen.

Ik denk dat we het groeperen niet moeten koppelen aan `allowMultipleOpen`. We kunnen beter rekening houden met uitbreidingen die ook in groepsverband een toepassing kunnen hebben.

Ik denk dat een Accordion in een groep de configuratie op groepsniveau moet accepteren. Lokale configuratie moet worden genegeerd.

Ik denk niet dat we binnen het DOM moeten queryen, maar dat een Accordion in een groep zich bij een service moet aanmelden. Daarnaast moeten we bedenken hoe een groep wordt geconfigureerd.

Wat ideetjes:

```html
<dso-accordion group="wortel">[..]</dso-accordion>
<dso-accordion group="wortel">[..]</dso-accordion>

<script>
import { accordionGroups } from '@dso-toolkit/core';

const group = accordionGroups.create('wortel', { allowMultipleOpen: true }); // Binnen accordionGroups wordt een lijstje bijgehouden.

group.setConfig({ allowMultipleOpen: false }); // group is een object met verwijzing naar de group binnen accordionGroups

group.destroy(); // Geen idee nog wat de consequenties zijn, maar als je 'm kan maken moet je 'm ook kunnen verwijderen.

accordionGroups.list(); // [{ name: "wortel", config: { allowMultipleOpen: false }}]
</script>
```

In de Accordion wordt ook van `accordionGroups` gebruik gemaakt. Zodra er een group is gedefinieerd moeten alle accordions in die group de configuratie overnemen. Tijdens de runtime van een accordion kan de configuratie wijzigen of de definitie verdwijnen (`.destroy()`). De accordion moet dan terugvallen op de lokale configuratie.

Wat denk je hiervan?

**Comment by LukeVerlaan** [comment]
@tfrijsewijk Zou jij nog even willen beschrijven welke richting we hiermee op willen gaan?

**Comment by tfrijsewijk** [comment]
Ja, dat ga ik doen 👍

**Comment by LukeVerlaan** [comment]
We gaan het accordion (en accordion section) stateless maken. Dit komt nu bij de afnemer te liggen. Er gaan dus mogelijk meer events getriggerd moeten worden.
