### ISSUE TITLE
Nieuw component "Document Fragment" en Ozon Content: Renvooiweergave ondersteuning uitbreiden.

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#2133]
Nieuw component "Document Fragment". Dit is een minder generieke Expandable Heading. De gewenste functionaliteit zit zo dicht op Ozon en STOP dat we dit niet weggezet krijgen in een generiek component. Ik vermoed dat Expandable Heading met deze change wordt verwijderd. De in/uitklap functionaliteit zit in Expandable.

# Document Fragment

- De "editAction" values "insert" en "delete" gelijktrekken met STOP definitie "voegtoe" en "verwijder"
- Ondersteuning voor `edit-action="nieuweContainer"` en `edit-action="verwijderContainer"` op `<dso-expandable-heading>`. (Zie STOP specificatie: https://koop.gitlab.io/STOP/standaard/2.0.0-rc/tekst_xsd_Attribute_Group_tekst_agWijzigactie.html)
- De waardes voor "editAction" worden dan:
  - "Voegtoe" Zowel kop als onderliggende container wordt groen gemarkeerd. (huidige gedrag van insert)
  - "Verwijder" Zowel kop als onderliggende container wordt rood gemarkeerd. (huidige gedrag van delete)
  - "nieuweContainer" Alleen de kop wordt groen gemarkeerd, de onderliggende container niet
  - "verwijderContainer" Alleen de kop wordt rood gemarkeerd, de onderliggende container niet
- Ondersteuning voor `<Label>` en `<Nummer>`.
-`[slot="prefix"]` aanpassen naar voorbeeld uit de JSON `labelXml` en `nummerXml` en `opschrift`.

Let op dat inhoud van Document Fragment onder labels en annotaties van titels door moet lopen.

In smalle containers moeten de Document Fragments niet inspringen (`dso-responsive-element[small]`). Deze wens is opgevoerd als feature voor Expandable Heading in #2190.

Als gebruiker wil ik kunnen zien welke content er hoort bij het filter dat ik heb gekozen.

### Eigenschap "gefilterd".

In de viewer kan de inhoud (document componenten) van een document worden gefilterd. De gefilterde tekst is herkenbaar aan een blauwe markering in de kantlijn. Het is ook mogelijk om de tekst van het gehele document te bekijken waarbij de tekst die hoort bij het filter goed herkenbaar blijft door de blauwe kantlijn.

Als de headings worden dichtgeklapt is het handig om toch te kunnen zien of er gefilterde tekst aanwezig is in de dichtgeklapte content. Daarom wordt er bij zo'n dichtgeklapte headings een blauwe kantlijn getoond. Als de heading wordt opengeklapt verdwijnt de blauwe markering bij de heading en wordt deze markering getoond bij de nu zichtbare content (of bij een geneste heading).

![Image](https://user-images.githubusercontent.com/91903058/248295929-aad96254-2128-440d-b1ec-c3ce18ccd850.png)

De technische benaming van deze functionaliteit is `filtered`.

# Ozon Content changes

- Inline achter elkaar plaatsen, uitzoeken waarom `inline="true"` op `display: block;` blijft.
- Hernoemen naar Stop Content ?
- `<Opschrift>` en `<Inhoud>` uitbreiden met ondersteuning voor `wijzigactie="voegtoe"` en `wijzigactie="verwijder"`. 

# Aandachtspunten

## Dropshadow

Komt uit #2182. Bij toegevoegde items is de drowshadow niet altijd zichtbaar. Zie bijgevoegd plaatje.

![Image](https://github.com/dso-toolkit/dso-toolkit/assets/34900082/e5b7628d-5ea9-4ed3-ad58-3d713eca8b35)

Dit komt vanwege `overflow`. Let op dat Document Component niet hetzelfde probleem krijgt.

**Comment by MichielKadaster** [comment]
@tfrijsewijk Lijkt me een goede opzet. Eventueel dus nog de optie om het DocumentComponent uit Ozon in zijn geheel door te geven. Slots zijn dan niet meer nodig en de viewer hoeft zelf geen logica te hebben voor speciale cases (bijv. bijlage zonder nummer -> Bijlage [ongenummerd])

**Comment by DjangoBlok** [comment]
Hierbij de MeaXure export
[Github 2133 - Document Fragment.zip](https://github.com/dso-toolkit/dso-toolkit/files/11916029/Github.2133.-.Document.Fragment.zip)

**Comment by tfrijsewijk** [comment]
@DjangoBlok 

![image](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/1d77a44f-944a-48cc-a446-f409a3d5be2e)

Als een DocumentComponent zowel `inhoud` als embedded DocumentComponents heeft, staat de inhoud dan altijd boven de Document Components? Ofwel, in mijn screenshot markeer ik `inhoud`, klopt dit?

Of zijn de punten 1 en 2 beide 'n Lid en heeft deze geen toggle om te openen en sluiten? Zo nee: Dan moeten we bellen over hoe we dat Ontwerp label op die plek krijgen..

**Comment by DjangoBlok** [comment]
Aangepaste versie 
[Document Fragment.zip](https://github.com/dso-toolkit/dso-toolkit/files/11936116/Document.Fragment.zip)

**Comment by tfrijsewijk** [comment]
Ik heb het label renvooiweergave verwijderd. Alle issues die met dit onderdeel te maken hadden hebben zich vertaald in een nieuw component "DocumentComponent".
