### ISSUE TITLE
Label: Door `it.only()` worden niet alle tests gedraaid

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#2134]
Dit is geen kwestie van `.only` weghalen, want dan falen er andere tests.

![image](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/68d400be-c7d1-40a5-811b-8dda8a1669f9)

* https://github.com/dso-toolkit/dso-toolkit/blob/master/storybook/cypress/e2e/label.cy.ts#L95

**Comment by tfrijsewijk** [comment]
@LukeVerlaan: Dit issue heeft 'n branch met tests die slagen (afgezien van Percy false positives). Het lijkt erop dat we dit kunnen mergen?

**Comment by LukeVerlaan** [comment]
Nee, er is nog een test waarbij de laatste check faalt. En ik zie gewoon niet waarom het niet wil slagen

**Comment by tfrijsewijk** [comment]
OK, ik probeer wel wat 🤷
