### ISSUE TITLE
Fundament: Categorisering componenten

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#2137]
De navigatie wordt wel erg lang, helemaal sinds we de drie verschillende Storybooks als één Storybook publiceren (Storybook Composition).

Daarom wil ik de componenten gaan categoriseren, ik weet alleen niet op welke criteria.

**Comment by tfrijsewijk** [comment]
Ook Docusaurus componentenlijst bijwerken.

**Comment by MichielDHVD** [comment]
@DjangoBlok Wat is de status. Bespreken tijdens UX-Overleg?

**Comment by tfrijsewijk** [comment]
@dso-toolkit/dso-ux opzet van Django bespreken.

**Comment by tfrijsewijk** [comment]
Ivm. de vakantie van @DjangoBlok doorgeschoven

**Comment by tfrijsewijk** [comment]
Volgende week gaan @tfrijsewijk en @DjangoBlok een voorstel doen en uitvoeren.

**Comment by tfrijsewijk** [comment]
Thomas gaat in Utrecht een meeting organiseren

**Comment by hansgrimm** [comment]
@tfrijsewijk zou jij hier verder mee gaan?

**Comment by tfrijsewijk** [comment]
Ja! Goed opgemerkt. Ik zet 'm verder.

**Comment by daverhelst** [comment]
@DjangoBlok Ik zie dat een aantal componenten niet in die nieuwe onderverdeling staan. Hieronder de lijst met mijn suggestie in haakjes erachter. Kun je laten weten of mijn aannames goed zijn, of dat je ze liever ergens anders onder geplaatst wilt hebben Django?

- Application Heading (DSO Identiteit / Tekst)
- Search Bar (On Page Interacties)
- Selectable (Form)
- Tooltip (On Page Interacties)
- Document Component (Domeinspecifiek / ?)
- Expandable (On Page Interacties)
- Scrollable (On Page Interacties)
- Slide Toggle (On Page Interacties)

**Comment by DjangoBlok** [comment]
@daverhelst 
Hieronder mijn suggesties.
- Application Heading (DSO Identiteit / Tekst)  - Hij stond onder lay-out maar DSO-identiteit zou ook kunnen
- Search Bar (On Page Interacties) - Ik had hem gezet onder form elementen
- Selectable (Form) - Ja, prima 
- Tooltip (On Page Interacties) - Ja, prima
- Document Component (Domeinspecifiek / ?)  - Ja inderdaad onder juridisch
- Expandable (On Page Interacties) - prima
- Scrollable (On Page Interacties) - prima
- Slide Toggle (On Page Interacties) - twijfelgeval, ik dacht zelf onder form

**Comment by daverhelst** [comment]
@DjangoBlok 
Fijn! Dan heb ik nog 2 vondelingen bij de Docusaurus componenten, namelijk:

- Input Number (Form)
- Step Counter (Form)

Wat vind jij?

**Comment by DjangoBlok** [comment]
Ja, dat lijkt me functioneel ook goed passen bij de Form componenten.
