### ISSUE TITLE
Button: Ellipsis op tertiary button

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#2140]
## Waar

In de viewer kun je zoeken naar een adres en als je dan een document opent staat linksboven het adres waarop je hebt gezocht. Als je prikt in de kaart dan wordt de content binnen het document gefilterd op de nieuwe plek. Je kunt dan met een tertiary button terug naar het adres waarop je hebt gezocht. 

Voorbeeld:
* Open https://preprod.document-viewer.dso.kadaster.nl/viewer/(documenten/gemeente//rechter-paneel:document/%2Fakn%2Fnl%2Fact%2Fgm0355%2F2020%2Fomgevingsplan/plekinfo)?regelsbeleid=regels&locatie=Godfried%20van%20Seijstlaan%2027A-10,%203703BR%20Zeist
* Prik in de kaart naast het perceel.

Voor deze situatie willen we graag het adres op de knop kunnen afbreken, zodat deze niet naar een volgende regel springt en daardoor teveel aandacht vraagt.

![image](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/1f044bad-3e01-462d-ab71-ff454cc9198f)

Het Label component kent al een truncate variant: https://storybook.dso-toolkit.nl/53.0.0/?path=/story/core-label--truncate&args=compact:true&viewMode=story

## Acceptatiecriteria
 * Knop breekt de tekst af en toont ... als de tekst niet in de bovenliggende container past.
 * In de documentatie vermelden onder welke voorwaarden het afbreken van tekst is toegestaan, indien mogelijk met een verwijzing naar WCAG.

cc: @LiesbethVorst

**Comment by hansgrimm** [comment]
Afbreken van tekst is een potentiële WCAG-issue, TENZIJ voldoende duidelijk is wat de volledige tekst zou moeten zijn. Voorleessoftware heeft daar geen last van, want die leest de 'onderhuidse' tekst voor, of die nou visueel wordt afgebroken of niet. Niet-visueel beperkten met voorleessoftware (bijv. ernstig dyslectisch) hebben wel een beetje een 'disconnect' als ze dit tegenkomen. *proceed with caution*

**Comment by tfrijsewijk** [comment]
Een systeem waarmee de grensen worden aangegeven en een eigenschap op de button waarmee wordt aangegeven of ie mag afbreken.

Idee: Kan ook een impliciete container zijn, zoals button-row of wellicht de directe parent.

**Comment by MichielDHVD** [comment]
Refinement 22 juni - Ready for development.

**Comment by HalloJo** [comment]
Voldoen we eigenlijk wel aan de eis: `Dit gepaard met een indicatie dat deze informatie toegankelijk is voor de gebruiker,` , als we geen tooltip kunnen tonen voor de `button`?

**Comment by HalloJo** [comment]
@dso-toolkit/dso-ux Gaat nog gericht kijken naar de beschrijving over ellipsis die in de documentatie komt voor zowel de `Button` als de `Label`. Deze wordt dus waarschijnlijk nog aangepast.
