### ISSUE TITLE
Form: Fix error messages

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#2141]
### Waar
form
### Aanleiding 
Deze melding kwam van stichting accessibility. 

> Als een veld van een van de onderstaande formulieren niet goed wordt ingevuld (bijvoorbeeld als deze leeg blijft terwijl het veld verplicht is om in te vullen) dan verschijnt een melding hierover. Deze statusupdate kan op dit moment niet programmatisch worden bepaald. Dit komt bijvoorbeeld ook voor bij het verkeerde invoerformaat van een e-mailadres en/of huisnummer.

PR02 heeft de foutmeldingen conform de toolkit geimplementeerd: https://pre.omgevingswet.overheid.nl/aanvraag-inloggegevens/burger.
Wat we al goed doen is dat we aria-invalid op het veld zetten en de foutmelding met aria-describedby / errormessage aan het veld koppelen. Dat moeten we zo laten. 

Maar het is inderdaad nog niet voldoende, omdat de foutmelding verschijnt op het moment dat het veld focus verliest.
Gevolg is dat er iets op het scherm verschijnt waar een blinde gebruiker niets van merkt. 

Volgens mij stelt het alert beleid al dat je de melding in zo'n geval een alert role moet geven (anders moeten we dat verduidelijken). 

Bovendien is de tekst 'dit veld is verplicht' onvoldoende. Er moet een formulering worden gekozen waaruit blijkt dat het een foutmelding betreft, en over welk veld de foutmelding gaat. 

### werkzaamheden
* In documentatie en alert beleid (voor zover nog nodig) uitleggen dat de foutmelding een alert role moet hebben en waarom
* De alert role in de toolkit toevoegen
* Een formulering voor de foutmeldingen in de voorbeelden bedenken, en doorvoeren, voorlopig voorstel:
	* Veld [label] mag niet leeg zijn. 

### Gebruikersimpact
Hinderlijk: als een gebruiker niet door heeft dat een foutmelding verschijnt, moet hij die handmatig opzoeken. 
(prioriteit verhoogd naar kritiek ivm correctie accessibility bevindingen)

**Comment by hansgrimm** [comment]
Zekers! @timveld is hier al mee bezig, ik geef 'm nog even de tijd om zijn licht erover te laten schijnen :)

Alvast my two cents: de foutmelding mist nu een aria `role="alert"` (https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/alert_role). Volgens mij lost dat het direct voorlezen probleem (a.k.a. programmatisch bepalen) op, en het zou elegant zijn als de focus daarbij weer in het betreffende veld wordt teruggezet.

**Comment by timveld** [comment]
Ik heb de issue beschrijving aangepast. Zoals Hans al opmerkte de alert role, daarnaast zorgen dat de foutmeldingen goed geformuleerd zijn. Ook zorgen dat een en ander goed is gedocumenteerd.

**Comment by hansgrimm** [comment]
Werkzaamheden/aanpassingen:
- `role="alert"` op de foutmelding
- foutmelding aftrappen bij verlaten veld
- focus terugzetten in het veld
- goed formulieren foutmeldingen: kort en to the point, geen misverstand mogelijk.
- documenteren waar nodig.

eens, @timveld ?

**Comment by timveld** [comment]
@hansgrimm ja, alleen het punt "focus terugplaatsen" heb ik bewust niet genoemd en vind ik tricky. Het is de vraag of gebruikers dit gedrag verwachten en het risico is een soort keyboard trap. Dus ik stel voor dat in ieder geval niet in dit issue mee te nemen.

**Comment by hansgrimm** [comment]
Je vangt de focus niet, maar zo kan de gebruiker meteen gaan kloppen

**Comment by MichielDHVD** [comment]
@MichielDHVD gaat de documentatie schrijven voor dit issue.

**Comment by timveld** [comment]
@tfrijsewijk Inmiddels heeft PR02 het aanvraagformulier al aangepast, en wat mij betreft is het zo goed. Dus hun aanpak  documenteren en dan kan het issue gesloten worden.

@hansgrimm Ik ben het eens met je bovenstaande voorstel behalve voor wat betreft het bij een fout terugplaatsen van de focus in het betreffende veld. Pr02 heeft dit ook niet gedaan.

Hoewel het terugplaatsen van de focus op het eerste gezicht gebruiksvriendelijk is, lijkt het te veel op een keyboard trap en/of een change of context. Voor bepaalde gebruikers, die het formulier met de tabtoets willen verkennen (zeker niet de slimste manier maar de behoefte om alles vooraf te verkennen kan juist bestaan bij mensen met cognitieve beperkingen die een wat meer rigide manier van werken hebben) kan het vastlopen / 'gedwongen invullen' frustratie opleveren. Bovendien is het niet gebruikelijk om de focus op deze manier 'vast te zetten', als de tabtoets niet doet wat een gebruiker verwacht kan dat verwarring opleveren. Last but not least: als tegelijkertijd een melding wordt gegeven en de focus wordt verplaatst, is het de vraag wat een screen reader uitspreekt en in welke volgorde dat gebeurt. De melding zou kunnen worden overgeslagen of zowel het oude als het nieuwe veld zouden kunnen worden uitgesproken, toevallig gisteren bij het 'focus naar een foutmelding verplaatsen' nog ervaren hoe ingewikkeld dit is en het verschilt per screen reader. 

Kortom, ik heb te veel twijfels bij dit idee om het nu door te voeren. Hooguit als het in gebruikersonderzoeken wordt gevraagd.

**Comment by tfrijsewijk** [comment]
Dank voor het onderzoek, ik zet dit issue voor nu op de backlog

**Comment by hansgrimm** [comment]
Gaan we hier nog iets mee doen?

**Comment by tfrijsewijk** [comment]
Goeie vraag. @hansgrimm kan jij eens uitzoeken wat PR02 heeft gedaan? @timveld Welk formulier is aangepast? En kan je dat aan Hans laten zien?

**Comment by MichielDHVD** [comment]
In de huidige situatie wordt de error melding niet opgelezen. 

PR02 heeft een role=alert toegevoegd. 

De twijfel in deze story was
a) moeten we aria live region gebruiken of role alert. Keuze is op role alert gevallen. 
b) moet de focus terug in een veld gezet worden? Dit is afgeschoten en gaan we niet doen. 

Wat resteert is dat voor forms er wanneer een veld een invalid status krijgt dan moet de rode foutmelding eronder een role=alert krijgen zodat deze altijd wordt opgelezen

**Comment by tfrijsewijk** [comment]
Documentatie aanpassen: Een foutmelding moet voorzien worden van een role=alert. Dit is door PR02 gedaan en goed bevonden.

**Comment by hansgrimm** [comment]
Wanneer wordt er een foutmelding afgevuurd? [documentatie]
- onBlur: direct bij het veld gegenereerde foutmelding krijgt `aria-errormessage` en `role="alert"`.
- onSubmit: verzamelfoutmelding met `role="alert"` + verwijzingen naar de velden die niet voldoen.
Uitwerken met voorbeelden?

**Comment by tfrijsewijk** [comment]
Ook bij onSubmit validatie moet `aria-errormessage` worden gebruikt.

**Comment by hansgrimm** [comment]
> Ook bij onSubmit validatie moet `aria-errormessage` worden gebruikt.

klopt, want dat attribuut zit op het veld zelf en verwijst naar de `id` van de foutmelding.

**Comment by hansgrimm** [comment]
hmmmm: https://github.com/nvaccess/nvda/issues/8318

**Comment by timveld** [comment]
NVDA leest aria-errormessage niet, maar in dit geval is dat een duidelijke afwijking van de relevante standaard die al is onderkend. We kunnen zo lang dit ticket niet is opgelost aria-describedby gebruiken, maar dat moet dan later weer worden aangepast en kan wel eens een breaking change zijn. Dat NVDA deel is van het referentie platform kan betekenen dat we ons hier aan aanpassen, maar omdat NVDA in dit geval zo duidelijk de standaard niet volgt ben ik daar niet toe geneigd. 'Wij bouwen de snelweg conform de standaard, zij moeten maar zorgen dat hun auto goed rijdt op een weg die aan de standaard voldoet'. Hoewel het niet horen van de foutmelding voor gebruikers vervelend kan zijn, is er wel goed omheen te werken.

**Comment by hansgrimm** [comment]
OK, wat nu te doen? PR02 heeft de foutmelding voorzien van `role=alert` en men zag dat het goed was. We zijn hiermee door de audit gekomen, dus kennelijk is de Orde van Velleman ook tevreden (formulieren zijn een verplicht onderdeel van hun sample). Wat moeten wij van de Toolkit nu nog doen?

**Comment by hansgrimm** [comment]
In de vergunningcheck wordt een foutmelding afgevuurd als je geen lokatie kiest. de `input` heeft echter `role=combobox` dus m.i. heeft `aria-invalid` hier geen plek. melding en input staan op afstand van elkaar, zonder link.

**Comment by hansgrimm** [comment]
@timveld Interessante pagina over de support voor `aria-errormessage`. Het is me alleen niet helemaal duidelijk wat men hier bedoelt met 'pertinent' en 'not pertinent'. Ik heb echter het gevoel dat we wel kunnen wegkomen met dit attribuut. 
Zie hier: https://a11ysupport.io/tech/aria/aria-errormessage_attribute

**Comment by timveld** [comment]
@hansgrimm  We kunnen er in ieder geval mee 'wegkomen', het is onderdeel van de Aria specificatie en daarmee ongetwijfeld een sufficient WCAG technique. 
Ze bedoelen met 'pertinent / not pertinent' volgens mij de vraag of een melding nu zichtbaar is / voorgelezen moet worden. Dus als een melding wel in het DOM staat maar het formulierveld niet invalid is, mag  de melding niet worden voorgelezen omdat hij niet 'pertinent' is. Je hoeft dus geen (extra) maatregelen te nemen om de foutmelding te 'verbergen', maar moet wel zorgen dat de invalid tag alleen op het veld staat als het invalid is.

**Comment by hansgrimm** [comment]
@timveld @tfrijsewijk Het zit me toch niet helemaal lekker. Ik ga kijken of ik een opzetje kan maken die ook rekening houdt met NVDA, mss als discussievoedsel voor maandag in 055

**Comment by hansgrimm** [comment]
Codepen hier: https://codepen.io/picturit/live/QWPRVLw/a0e8264ee26f0d4d816db2fe08de4971 
NVDA krijg de errormessage, die onblur wordt afgevuurd, alleen door als je er `role="alert"` op zet. Zonder dat wordt er onblur niks opgelezen. @timveld kan jij met JAWS even kijken of in dat geval er 2 keer wordt opgelezen?

**Comment by hansgrimm** [comment]
NVDA zonder `role="alert"`:
![Image](https://github.com/dso-toolkit/dso-toolkit/assets/506527/f8c64370-298d-47d2-a7b3-960a784d8a72)
NVDA met `role="alert"`:
![Image](https://github.com/dso-toolkit/dso-toolkit/assets/506527/db04d339-78fe-4849-a79c-d3d27b44529b)

**Comment by hansgrimm** [comment]
In de toolkit is een veld qua markup al helemaal zoals we het zouden willen, met `aria-errormessage` en `aria-invalid`. Foutmelding keurig gekoppeld dmv `id`. Het enige dat ontbreekt is de `role="alert"` als we qua backward compatibility met NVDA die kant op zouden willen.
![Image](https://github.com/dso-toolkit/dso-toolkit/assets/506527/fcc8714e-23d2-4f86-ba56-a9c193f5c7b1)

**Comment by hansgrimm** [comment]
https://www.davidmacd.com/blog/test-aria-describedby-errormessage-aria-live.html

**Comment by timveld** [comment]
@hans In het artikel waar je naar verwijst kan ik niet alles volgen en volgens mij roepen ze een paar dingen die niet kloppen. 

Ik heb jouw codepen aangepast naar hoe dit moet:
https://codepen.io/timveld/pen/jORjOMd
Dus verwijzen met errormessage en de role=alert op de melding zetten zodra die verschijnt. Niet eerder, in ieder geval niet als de melding al in het DOM staat; je 'css-trucje' om hem zichtbaar te maken als je aria-invalid zet leidt er niet toe dat de melding ook wordt uitgesproken. 

De role = alert zorgt er voor dat de melding wordt gelezen als die verschijnt, en dat moet in ieder geval. Dat staat los van de errormessage vs. describedby discussie. 

Het enige 'nadeel' van errormessage is dat NVDA de foutmelding niet herhaalt als de focus in het veld komt. 
Willen we NVDA maximaal tegemoet komen dan kunnen we dus kiezen voor describedby, maar daarmee wijken we af van de standaard en maken we het onze implementators moeilijker. Ze moeten de foutmelding namelijk uit het DOM houden zo lang hij niet zichtbaar is, anders wordt hij voorgelezen. Met aria-errormessage speelt dat niet: die wordt alleen voorgelezen als het veld invalid is. 

Overigens: moet aria-invalid gezet worden of kan dit ook met native html? (Ik kan even niet vinden hoe dit precies zit)

Kortom:
* De role = alert plaatsen op het moment dat de melding zichtbaar wordt moet hoe dan ook
* Aria-invalid (of een native manier die dit impliceert) moet worden gezet als het veld invalid is en verwijderd als het veld valid is
* Enige vraag is: gebruiken we aria-errormessage of aria-describedby? Ik neig naar de eerste.

**Comment by hansgrimm** [comment]
>> je 'css-trucje' om hem zichtbaar te maken als je aria-invalid zet leidt er niet toe dat de melding ook wordt uitgesproken.

I beg to differ, sir. NVDA leest 'm keurig voor zodra het CSS-trucje hem onthult.

In de Toolkit werkt het overigens anders: daar wordt de melding pas in de dom geschoten als het veld 'invalid' is. 
zie https://storybook.dso-toolkit.nl/_2141-form-fix-error-messages/?path=/story/html-css-form-groups-input--input&args=state:invalid;errorText:error

**Comment by hansgrimm** [comment]
Getest door @timveld op 6 mei 2024., en akkoord bevonden.

**Comment by timveld** [comment]
Vannacht kwam er een mailtje van github dat het NVDA issue over aria-errormessage gesloten is. En jawel: de nieuwste development snapshot van NVDA ondersteunt aria-errormessage! Dus het laatste argument om het niet te gebruiken vervalt.
