### ISSUE TITLE
Header: Logo met sublogo, menu valt deels buiten 320px breedte

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#2143]
Bij de header met sublogo is de positie van het uitklapmenu op een smal scherm niet goed. Het menu staat te ver naar rechts en valt deels buiten beeld, zowel de knop als de dropdown. 

## Fout

![image](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/ab9b6165-a241-43a7-ab43-99abc02b3216)

## Header zonder sublogo

Bij de header zonder sublogo gaat het beter. De knop past net naast het hoofdlogo. Van het opengeklapte menu valt de linkerkant weg, maar de tekst is nog wel leesbaar.

## Acceptatiecriteria
* Op een schermresolutie van minimaal 320px
  * de knop van het menu past naast het hoofdlogo
  * het uitgeklapte menu past in de breedte helemaal in beeld
* Op een schermresolutie < 320px
  * ??

cc: @LiesbethVorst

**Comment by MichielDHVD** [comment]
@LukeVerlaan gaat uitzoeken of deze gesloten kan worden.
