### ISSUE TITLE
Date picker: DD-MM-JJJJ placeholder

### ISSUE THREAD

**Issue by timveld** [dso-toolkit/dso-toolkit#2145]
### Waar
Date picker
### Aanleiding
Volgens het rapport van stichting accessibility betreffende omgevingsloket bevat de date picker een afwijking op succescriterium SUCCESCRITERIUM 3.3.2 (Labels of instructies), want:
"Met de placeholder tekst wordt de instructie gegeven hoe het datumformaat ingevoerd moet worden. Instructies dienen zowel voor ziende bezoekers als voor blinde bezoekers te achterhalen zijn. Een placeholdertekst is niet voldoende, omdat deze weer verdwijnt zodra de gebruiker begint met typen."

Ik weet niet hoe terecht deze bevinding is maar we zouden het intypen van een datum wel wat intuïtiever kunnen maken, bijvoorbeeld door de placeholder groter te maken en 'cijfer voor cijfer' te vervangen als de gebruiker tikt. Ontwerpvraag.

### Werkzaamheden

In overleg met teams nieuw ontwerp bepalen en doorvoeren.

### Gebruikersimpact

Beperkt: De meeste gebruikers zullen de datum prima kunnen invoeren, dit is een optimalisatie om het wat makkelijker te maken.

**Comment by MichielDHVD** [comment]
- Ontwerp toevoegen. @MichielDHVD 
- Toelichting onder veld met juiste invoer formaat toevoegen. 
- Discussie voor @tfrijsewijk en @svrijsewijk over hoe stories gedisplayed worden zodat het duidelijk is voor de afnemer hoe een component geimplementeerd moet worden.

**Comment by svrijsewijk** [comment]
Het component wordt door de toolkit 'atomic' geleverd. zonder label en zonder instructieteksten. Om dit goed te krijgen zijn er denk ik twee opties.

* Story uitbreiden om te laten zien dat de afnemer een aria-describedby op de datepicker zet, met een span waarin het gewenste format wordt uitgelegd. Dan staat in de story meer dan enkel het component.
* Een span met de instructietekst opnemen it het component, en in de aria-describedby hiernaar verwijzen, _en_ ruimte laten voor een tweede id wanneer de afnemer extra instructietekst toevoegd. Hier komen er mogelijk twee instructieteksten. Dit behoeft een ontwerp.

![image](https://github.com/dso-toolkit/dso-toolkit/assets/21218284/a973970c-fb87-49c9-a254-84c5707b266b)

**Comment by timveld** [comment]
Sterke voorkeur om dit niet aan de implementator over te laten, maar een oplossing te bouwen waarbij deze hint op een visueel mooie manier wordt gegeven. De implementator mag dit niet kunnen 'uitschakelen' omdat hij dan een WCAG afwijking veroorzaakt, dit uitleggen in documentatie. 

Specificatie aria-describedby: 
Als gisteren besproken kan de implementator een optionele toelichting meegeven. 
```aria-describedby = "optionele_toelichting DDMMJJJJ"``` 
Heeft op het referentie platform het effect dat eerst de inhoud van optionele_toelichting, dan spatie, dan de inhoud van DDMMJJJJ wordt voorgelezen. 
Volgorde "van hoofdzaak naar bijzaak", dus optionele_toelichting voor DDMMJJJJ. 
Toevoegen van spaties is niet nodig, doet NVDA zelf goed.

**Comment by svrijsewijk** [comment]
@timveld optie twee behelst wat je aangeeft. Laten we dat pad bewandelen dan kan de implementator dit niet langer uitschakelen. Vraag is nog wel hoe beiden instructies visueel getoond worden.

**Comment by hansgrimm** [comment]
De implementator zou ook gewoon bijvoorbeeld in het label kunnen zetten: “Geboortedatum (dd-mm-jjjj)”. Dan ben je in meteen klaar, en is het voor _iedereen_ duidelijk. Placeholders zijn heel decoratief, maar worden niet voorgelezen en verdwijnen bij typen of direct bij plaatsing cursor in het veld. 

Toelichtingen bij velden kan altijd kort; als er een roman voor geschreven moet worden, is er iets fundamenteel fout met de usability van het formulier 😉

**Comment by tfrijsewijk** [comment]
@tfrijsewijk refinen met met @HalloJo en @LukeVerlaan doornemen.

**Comment by timveld** [comment]
Na overleg is de conclusie dat Accessibility hier onterecht een afwijking constateert en dat we de hint in de placeholder willen houden. Het volgende is naar Accessibility gemaild: 

Hoewel ik het er mee eens ben dat de DD-MM-JJJJ hint noodzakelijk is om dit succescriterium te behalen, vind ik dat de placeholder een aanvaardbare plaats voor deze hint is. Ik heb uitgezocht of uit WCAG kan worden afgeleid dat een placeholder niet voldoende is en daaruit blijkt eerder het tegendeel. In [Understanding SC 3.3.2: Labels or Instructions](https://www.w3.org/WAI/WCAG21/Understanding/labels-or-instructions.html) staat namelijk onder examples: "A field for entering a date contains initial text which indicates the correct format for the date."

Voor iemand die de datum gaat typen is na lezing van de hint duidelijk welk formaat hij moet gebruiken. Dit is bovendien het enige in Nederland gangbare formaat. Tenslotte is er ook de mogelijkheid om de datum met een toegankelijke date picker te kiezen, juist omdat niet alle gebruikers dezelfde voorkeur hebben.  

Hoewel er discussie mogelijk is over de vraag wat het meest gebruiksvriendelijke ontwerp is en er manieren te bedenken zijn om het bepaalde gebruikersgroepen nog makkelijker te maken, zie ik geen doorslaggevende argumenten om te spreken van een WCAG afwijking. Ik denk dat je daarmee te veel op de stoel van de ontwerper gaat zitten. 

Ik heb met de visuele ontwerpers nagedacht over alternatieve plaatsen voor de DD-MM-JJJJ hint. Het is echter moeilijk een goede plaats te vinden waar hij er mooi uitziet terwijl de bedoeling duidelijk blijft. Bovendien neemt hij plaats op het scherm in en wordt het ontwerp drukker. Tenslotte ziet het er, als de hint ook in de placeholder zou blijven staan (en dat is juist wel handig voor mensen die overzicht missen), visueel heel 'dubbelop' uit.

**Comment by hansgrimm** [comment]
Top!

Met vriendelijke groet,
Hans Grimm | Grimm.nl<http://grimm.nl/> BV

[Afbeelding met tekst, klok    Automatisch gegenereerde beschrijving]
T +31 6 22275783<tel:+31%206%2022275783>
E ***@***.******@***.***> :: W www.grimm.nl<http://www.grimm.nl/>
Grimm.nl<http://grimm.nl/> BV, Valeriuslaan 55, 1422 HS Uithoorn<x-apple-data-detectors://4/0> – NL
KvK: 70294674<tel:70294674> – BTW: NL858241997B01
LinkedIn: http://www.linkedin.com/in/hansgrimm


Op 4 jul. 2023 om 14:14 heeft timveld ***@***.***> het volgende geschreven:

﻿

Na overleg is de conclusie dat Accessibility hier onterecht een afwijking constateert en dat we de hint in de placeholder willen houden. Het volgende is naar Accessibility gemaild:

Hoewel ik het er mee eens ben dat de DD-MM-JJJJ hint noodzakelijk is om dit succescriterium te behalen, vind ik dat de placeholder een aanvaardbare plaats voor deze hint is. Ik heb uitgezocht of uit WCAG kan worden afgeleid dat een placeholder niet voldoende is en daaruit blijkt eerder het tegendeel. In Understanding SC 3.3.2: Labels or Instructions<https://www.w3.org/WAI/WCAG21/Understanding/labels-or-instructions.html> staat namelijk onder examples: "A field for entering a date contains initial text which indicates the correct format for the date."

Voor iemand die de datum gaat typen is na lezing van de hint duidelijk welk formaat hij moet gebruiken. Dit is bovendien het enige in Nederland gangbare formaat. Tenslotte is er ook de mogelijkheid om de datum met een toegankelijke date picker te kiezen, juist omdat niet alle gebruikers dezelfde voorkeur hebben.

Hoewel er discussie mogelijk is over de vraag wat het meest gebruiksvriendelijke ontwerp is en er manieren te bedenken zijn om het bepaalde gebruikersgroepen nog makkelijker te maken, zie ik geen doorslaggevende argumenten om te spreken van een WCAG afwijking. Ik denk dat je daarmee te veel op de stoel van de ontwerper gaat zitten.

Ik heb met de visuele ontwerpers nagedacht over alternatieve plaatsen voor de DD-MM-JJJJ hint. Het is echter moeilijk een goede plaats te vinden waar hij er mooi uitziet terwijl de bedoeling duidelijk blijft. Bovendien neemt hij plaats op het scherm in en wordt het ontwerp drukker. Tenslotte ziet het er, als de hint ook in de placeholder zou blijven staan (en dat is juist wel handig voor mensen die overzicht missen), visueel heel 'dubbelop' uit.

**Comment by hansgrimm** [comment]
Iets met knuppels in hoenderhokken: als ik kijk naar hoe goed de `<input type="date">` inmiddels is geworden, vraag ik me af waarom we nog zelf het wiel willen uitvinden:
- hij heeft hele goede input-hulp (dag -> maand -> jaar)
- hij heeft een prima datepicker
- keyboardbediening is top
- positie onder/boven/links/rechts regelt zichzelf

Nadeel is dat je de styling niet echt kan aanpassen (mss zijn daar hacks voor, maar dat is nooit ideaal), maar dat is nou eenmaal de trade-off.

I'll see myself out 😅

**Comment by timveld** [comment]
Een voor meerdere interpretaties vatbare reactie op mijn mail gehad. Ik zal dit punt in komend UX overleg agenderen. Input=date is vanuit toegankelijkheid een mooie oplossing en scheelt een hoop gedoe, maar ten koste van styling.

**Comment by gofix** [comment]
Tot een paar jaar terug was `<input type="date" />` geen optie, met name omdat toetsenbordbediening rampzalig was. Gelukkig zijn hier dingen veranderd in de actuele(re) browsers.

In dit artikel is goed onderzocht https://www.hassellinclusion.com/blog/input-type-date-ready-for-use/ hoe (per 2020) het ding het tegenwoordig doet, en ik denk dat ik de conclusie van @hansgrimm kan onderschrijven. En... zodoende kunnen we uit de hoek van de `placeholder` wegblijven (want: die wil je ECHT niet, omdat ie verdwijnt zodra je begint in te voeren).

**Comment by tfrijsewijk** [comment]
De weg is `<input type="date">`, @hansgrimm gaat een ander issue maken. Deze sluiten we.

**Comment by tfrijsewijk** [comment]
Zie #2226.
