### ISSUE TITLE
ScrollContainer toepassen in Map Controls

### ISSUE THREAD

**Issue by MYpenburg** [dso-toolkit/dso-toolkit#2148]
De scrollcontainer toepassen in MapControls zodat de overflow-schaduwrandjes ook in het Kaartlagen paneel zichtbaar worden

**Comment by tfrijsewijk** [comment]
@LukeVerlaan Volgens mij is dit issue niet nodig, want dat heb je al meteen in #2071 gedaan.. toch?

**Comment by LukeVerlaan** [comment]
Ja, dat heb ik meegenomen in dat issue
