### ISSUE TITLE
Modal: Schermvullende weergave

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#2152]
## Voor Wie

RTR

## Waar

Het klikken op "Bekijk STTR" toont een schermvullende modal. 

Zie ook https://pre.omgevingswet.overheid.nl/registratie-toepasbare-regels/id/Conclusienl.imow-gm0344.activiteit.AfscheidingDakterras

## Aanleiding

Bij RTR is men bezig om op WCAG vlak de applicatie te refactoren. Voor de modal is intussen een Web Component beschikbaar. Bij het RTR team is het vertrekpunt om waar mogelijk naar Web Components over te gaan. Schermvullende weergave voor Web Component modal is vooralsnog niet beschikbaar. Zodoende dit verzoek. 

## Werkzaamheden
* Full-screen weergave ontwikkelen.
* Full-screen als control parameter beschikbaar maken in Storybook.

## Ontwerp
* Geen drop-shadow. Volledig dekkend in viewport. 
* Dezelfde positionering voor de elementen als titel en knoppen blijven gehanteerd. 

![Image](https://user-images.githubusercontent.com/9696261/243783689-f7e4afc1-b033-49aa-8e01-4b43d5d5d8cc.png)

Originele melding is van @DHvD-Michael.

**Comment by tfrijsewijk** [comment]
@MichielDHVD neemt dit issue over en gaat dit bij RTR inventariseren.

**Comment by tfrijsewijk** [comment]
* Modal uitbreiden met `fullscreen`
* Image Overlay en Table fullscreen hier gebruik van laten maken.

**Comment by tfrijsewijk** [comment]
@HalloJo Staat deze terecht "In progress" ? En hoe gaat dit? Overlapt dit met het werk/research van @hansgrimm mbt. `<dialog>` ?

**Comment by HalloJo** [comment]
Deze was inderdaad in progress, maar toen hoorde ik dat @LukeVerlaan ook bezig was met de scrollable van de `modal`. Dus besloot ik deze even on hold te zetten, maar heb de status nog niet aangepast zie ik.. Excuus.

**Comment by tfrijsewijk** [comment]
Gefuseerd in #2223.
