### ISSUE TITLE
Aanpassen lineheights H1, H2 en H3

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#2153]
Reden: ziet er beter uit, en waarden binnen het 8px grid trekken. 

Medeverantwoordelijke en aanstichter: @DHvD-Michael.

H1: Lineheight aanpassen naar `32px` (= lettergrootte, was `40px` is veel te groot)

H2: Lineheight aanpassen naar `24px` (= lettergrootte, was `36px` is veel te groot en rare maat)

H3: Lineheight aanpassen naar `24px` (was `26px` is rare maat)

### Huidig

> ![Image](https://user-images.githubusercontent.com/9696261/243784662-ebfbf1d1-622f-4013-be23-82e13d76013e.png)

### Voorstel

> ![Image](https://user-images.githubusercontent.com/9696261/243784734-d367af7a-2124-43c2-b4ad-240636758652.png)

### Side-by-side

> ![Image](https://user-images.githubusercontent.com/9696261/243784787-50b137a0-569b-463f-92b6-77b0d8d7c845.png)

> ![Image](https://user-images.githubusercontent.com/9696261/243784819-1e3c5140-5fd2-4f67-883f-003beafd69b7.png)

**Comment by MichielDHVD** [comment]
Eerste visuele test via storybook 
https://storybook.dso-toolkit.nl/_2153-aanpassen-lineheight-headings/iframe.html?args=&id=voorbeeldpagina-s-toepassingen-componenten-line-height-test--line-height-test&viewMode=story 

Voorstel *1.2 
Voorstel *1.25
Voorstel *1.3 
Voorstel *1.4

**Comment by tfrijsewijk** [comment]
@dso-toolkit/dso-ux Graag bij UX overleg doornemen

**Comment by MichielDHVD** [comment]
Conclusie UX-Overleg: 
fontsize * 1.25 Is de gewenste lineheight geworden. 

Vervolg issues die uitgezocht moeten worden. 
H1, H2, H3 op kleine viewports en horizontale ruimtes tussen Headings en broodtekst

**Comment by tfrijsewijk** [comment]
> Conclusie UX-Overleg:
> fontsize * 1.25 Is de gewenste lineheight geworden.

Dit gaan we dan in dit issue oplossen.

> Vervolg issues die uitgezocht moeten worden.
> H1, H2, H3 op kleine viewports en verticaal ruimtes tussen Headings en broodtekst

Dit gaan we in #2217 oplossen.
