### ISSUE TITLE
Accessibility: Links en iconen op achtergrondkleur altijd zwart

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#2154]
## Aanleiding

Grasgroen heeft niet genoeg contrast met de grijze achtergrondkleur (zwart 5%). Daarom moeten links + icon voor externe links en tertiaire buttons zwart zijn op een grijze achtergrond. **Misschien wel op elke gekleurde achtergrond??**

Het zou handig zijn als voor alle situaties waarin er een grijze achtergrond wordt gebruikt de links/icons/buttons zwart worden weergegeven.

## Mouse over
 * De mouse over kleur moet nog bepaald worden, in de Highlight Box is dit nu donkergrijs en in de Document Header is het paars (icon only button rechtsboven).
 * Zwarte inline/tekst links zijn underlined en hebben geen mouse over effect. Bijv. in document list https://storybook.dso-toolkit.nl/master/?path=/story/html-css-document-list--default
 * In de alerts (die een andere achtergrondkleur hebben) hebben de inline links geen mouse over effect https://storybook.dso-toolkit.nl/master/?path=/story/core-alert–error

## Componenten met gekleurde achtergrond
* Alert
* Banner
* Card: mouse over het i-tje
* Document Header
* Document List
* Highlight Box
* Info (variant: fixed)
* Link List (in footer)
* Shopping Cart (https://storybook.dso-toolkit.nl/master/?path=/story/html-css-shopping-cart--items-non-collapsable&viewMode=story)
* **nog iets vergeten??**

## Werkzaamheden
Iconen geplaatst door class external + download bij een link blijven groen voor de volgende onderdelen, deze moeten zwart worden:
- Highlightbox 
- Info
- Document header
- Document list

### Shopping cart
Aan de rechterkant van de shopping cart staan verschillende iconen (verwijderen en wijzigen) deze zijn allemaal grasgroen. Dit is tegenstrijdig met document header en document list iconen 
Voor shopping cart de iconen zwart maken op dezelfde manier als document header en document list.

### Toggletip en Tooltip:
Wanneer een toggletip of tooltip op een gekleurde achtergrond geplaatst worden dan blijven deze grasgroen. 
Wanneer een toggletip in een van de volgende componenten staat dan kleur zwart maken:
- Alert
- Banner
- Document header
- Document List
- Highlightbox (yellow en default) 
- Info 
- Shoppingcart
- Footer 

## Ontwerp

**n.t.b.**

**Comment by MichielDHVD** [comment]
@MichielDHVD uitzoeken status

**Comment by MichielDHVD** [comment]
Heeft dit issue niet veel overlap met dit reeds opgeloste issue? Hier zijn alle interactieve elementen op zwart gezet (expliciet op #000) 
https://github.com/dso-toolkit/dso-toolkit/issues/2005 

In dat beschreven issue staat wel dat hover/mouse buitenscope was. Dat lijkt juist voor dit issue in scope te zijn. 

Situatie die nog niet klopt:
Iconen geplaatst door class external + download bij een link blijven groen voor de volgende onderdelen. 
- Highlightbox
- Info
- Document header
- Document list

Shopping cart:
Aan de rechterkant van de shopping cart staan verschillende iconen (verwijderen en wijzigen) deze zijn allemaal grasgroen. Dit is wel tegenstrijdig hoe document header en document list iconen behandelen deze maken ze altijd zwart. 
Voorstel: Shopping Cart iconen zwart maken? 

Verder moet er afgestemd worden wat we met Mouse-Over willen doen lijkt me. 

Vervolg actie:
UX: Ontwerp mouse-over buttons en links op gekleurde achtergrond. 
UX: Shopping cart icons beslissing nemen
Toolkit dev ready: External en Download class altijd zwart op gekleurde achtergrond voor bovenstaande onderdelen.

**Comment by hansgrimm** [comment]
@MichielDHVD neemt deze nog even door

**Comment by MichielDHVD** [comment]
Deze story wordt gesplits. Concreet gaat deze story alleen over vergeten kleur aanpassingen. 

Een losse story wordt gemaakt om een spitsing voor te stellen tussen tertiare knop en icon only. Zodat een icon-only button specifieker gestijld kan worden.

**Comment by hansgrimm** [comment]
W3C methode voor bepalen brightness/contrast: https://www.w3.org/TR/AERT/#color-contrast
Codepens voor Sass-oplossingen: 
- https://codepen.io/jonnykates/pen/aYaBEM
- https://codepen.io/davidhalford/pen/ALrbEP

**Comment by hansgrimm** [comment]
![Scherm­afbeelding 2023-10-24 om 16 19 05](https://github.com/dso-toolkit/dso-toolkit/assets/506527/2309881c-7831-422b-a24f-9714bb40855d)

**Comment by hansgrimm** [comment]
Laatste toevoeging: functionaliteit die automatisch bepaalt wat de juiste contrastverhouding is (licht op donker, of donker op licht). NB: blijven testen!

**Comment by hansgrimm** [comment]
@tfrijsewijk aanpassingen getest, ziet er schadevrij uit :)
