### ISSUE TITLE
List Button: `@Prop() sublabel` vervangen met `<slot name="sublabel">`

### ISSUE THREAD

**Issue by rblanconeira** [dso-toolkit/dso-toolkit#2156]
De gebruiker van het component moet de mogelijkheid hebben om `.sr-only` teksten toe te voegen aan sublabel en subcontent. Subcontent is al een slot. Sublabel nog niet.

Graag hiervoor ook een slot maken zodat we zelf controle hebben over de inhoud.

**Comment by rblanconeira** [comment]
Ik weet alleen niet of het heel veel zin heeft. Het doel is om er voor te zorgen dat subcontent en sublabel worden voorgelezen door de screenreader.
Ik heb net bij het slot subcontent eigen span sr-only meegegeven, maar de screenreader lijkt het niet voor te lezen. Geen idee of het aan de gebruikte screenreader ligt of aan het (gebruik van) webcomponent ligt.

**Comment by rblanconeira** [comment]
Voor activiteiten:
![activiteiten-markup](https://github.com/dso-toolkit/dso-toolkit/assets/24987027/79e5df81-299d-43c6-9da0-4f67f2661431)

Voor werkzaamheden:
![werkzaamheden-markup](https://github.com/dso-toolkit/dso-toolkit/assets/24987027/d481a2b0-b157-4255-b13b-885428bb267b)

**Comment by tfrijsewijk** [comment]
Staan daar twee divs met `slot="subcontent"` ?

```html
<div slot="subcontent">
  <div slot="subcontent">
    <span id="keywords">[...]</span>
  </div>
</div>
```

En heb je al een testje buiten het Web Component gedaan? Gewoon wat tekst naast wat tekst met `.sr-only` ?

**Comment by rblanconeira** [comment]
Klopt, die dubbele div slot is niet goed, was een develop-modus foutje.
Ben er achter dat andere screenreader het wel voorleest (NVDA).

In dat geval, in een slot voor sublabel dus niet (meer) noodzakelijk.

**Comment by tfrijsewijk** [comment]
> Klopt, die dubbele div slot is niet goed, was een develop-modus foutje. 

:+1:

> Ben er achter dat andere screenreader het wel voorleest (NVDA).

OK, gelukkig. Ben nog wel benieuwd welke screenreader jij hebt gebruikt. Ik maak voor mijn testjes gebruik van Screen Reader in Chrome (ondanks dat die in maintenance is).

> In dat geval, in een slot voor sublabel dus niet (meer) noodzakelijk.

Dat begrijp ik niet helemaal. Ik ben in de veronderstelling dat jij meer tekst wilt laten voorlezen dan dat er zichtbaar is. Dan moet je gebruik maken van iets als `.sr-only`:

```html
<div>
  <span class="sr-only">Bevat: </span>
  <span>Wortel</span>
  <span>Tomaat</span>
</div>
```

Dit kan niet met de property `sublabel`, want dat is een string. 

Maar mocht ik het inderdaad verkeerd begrijpen en je het slot sublabel niet meer nodig hebt, kan dit issue gewoon worden gesloten :)

**Comment by rblanconeira** [comment]
En wat betreft het issue.
Voor werkzaamheden gebruiken we subcontent, met eigen markup en extra sr-only tekst, namelijk Trefwoorden.

Voor activiteiten gebruiken we sublabel met uitsluitend string waarden, zoals Gemeente of Provincie.
Ook gebruiken we hier subcontent, zoals 'Bevat: subactiviteit 1'. Deze hele tekst is displayed en heeft geen extra sr-only tekst.
Ik denk door deze verschillende scenarios ben ik even in de war geraakt. Geen aanpassing nodig dus.

**Comment by tfrijsewijk** [comment]
@rblanconeira Helder! Succes
