### ISSUE TITLE
List Button: Geen onderlinge marges

### ISSUE THREAD

**Issue by rblanconeira** [dso-toolkit/dso-toolkit#2157]
Bij het gebruiken van het ListButton component in een lijst hebben deze componenten geen marges ten opzichte van elkaar.

Het 'oude' html/css component had dit wel. Zie screenshots.

![oud](https://github.com/dso-toolkit/dso-toolkit/assets/24987027/79cda7c9-3c5e-461d-b927-0f5300d5e061)
![nieuw](https://github.com/dso-toolkit/dso-toolkit/assets/24987027/13b5e37b-6e3f-4ee3-b1e7-fb1f38809911)

**Edit Thomas:**
De voorbeeldpagina https://storybook.dso-toolkit.nl/54.0.1/?path=/story/voorbeeldpagina-s-toepassingen-aanvragen-activiteiten--activiteiten&args=preferredImplementation:html-css heeft het ook. Wissel met preferredImplementation voor het verschil. Overigens zijn de Core en HTML/CSS implementaties niet gelijk aan elkaar. Het gaat om de onderlinge margins die gelijk moeten zijn.

**Comment by DjangoBlok** [comment]
Voor de viewer is de werkvorm zonder marges wel gewenst. 
Dus als er ook behoefte is aan een werkvorm met marges dan zouden we beide moeten kunnen gebruiken.

**Comment by tfrijsewijk** [comment]
Weet je dat zeker? Het kan toch niet de bedoeling zijn dat meerdere List Buttons zo tegen elkaar aanzitten? 2px border, raar deukje links en rechts..

![image](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/5e86d961-9303-430b-b760-8c2a2f647496)

**Comment by MYpenburg** [comment]
Viewer gebruikt geen list buttons toch?

**Comment by DjangoBlok** [comment]
oh ik dacht dat dit gewoon cards waren. En inderdaad deze afstand is wel erg slordig.

**Comment by MYpenburg** [comment]
👍

**Comment by LukeVerlaan** [comment]
in #2191 wordt aangegeven dat de margin 8px moet zijn. In de HTML/CSS uitwerking is het 4px. Als het 8px moet zijn, dan moet het zeker ook daar worden aangepast?

**Comment by MYpenburg** [comment]
<img width="1250" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/7289928/0dc430f8-6c4f-4c87-8cfa-e89615427822">
Dit moet m zijn, kan nu even niet meten voor je

**Comment by tfrijsewijk** [comment]
Dat lijkt mij 4px. Ik denk dat dit een screenshot van de huidige afname van het HTML/CSS component in de applicatie is.

**Comment by LukeVerlaan** [comment]
Deze stijling is er al wel, maar omdat host geen display heeft word dit niet getoond.

**Comment by hansgrimm** [comment]
> Deze stijling is er al wel, maar omdat host geen display heeft word dit niet getoond.

Precies. daar viel ik laatst ook al over.
