### ISSUE TITLE
Default height textarea

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#216]
Er was verwarring ontstaan over de grootte van de text area. Er was namelijk visueel een verschil tussen wat er in de toolkit staat en wat er geimplementeerd is. 

In de productie omgeving had de text area 2 rows en in de toolkit 5 rows. 

https://dso-toolkit.nl/3.0.0/components/detail/group-textarea.html

De grootte van een group-textarea wordt bepaald door het attribuut rows. In de toolkit staat deze op 5 rows. Maar als dit attribuut niet wordt toegevoegd aan de html van de group-textarea is het de browser die bepaalt hoe groot de textarea is. Voor safari en chrome is dit bijv. 2 rows. 

De wens is om de grootte van de group-textarea niet door de browser te laten bepalen als er geen row attribuut wordt gebruikt.  Het verzoek is om de grootte zonder row-attribuut 4 rows te maken. 

Nu heeft @tfrijsewijk aangegeven dat deze grootte alleen ongeveer benaderd kan worden. En dat is bij deze prima.

**Comment by MichielDHVD** [comment]
@tfrijsewijk Kan deze ook gesloten worden ? Deze is uiteindelijk behandeld in #218 toch?

**Comment by tfrijsewijk** [comment]
#218 is gesloten. Pieter had de originele scope van deze issue anders geinterpreteerd dan ik. Toen ik de code ging reviewen en onze aannames niet met elkaar overeen kwamen heb ik op 31 oktober met jou contact opgenomen en hebben we het volgende gesprek gehad:

```
[...]
thomas: als een `textarea` zonder rows is krijg je default gedrag _van de browser_
michiel: Aha dus browser bepaalt hoe hoog de text area is.
thomas: in de basis wel, en daar kun je met het attribuut `rows` sturing aan geven
thomas: maar, ik begrijp het issue #216 niet.
thomas: en: wat is de wens?
thomas: een `textarea` zonder rows geeft default gedrag van de browser. als je weet dat een textarea veel text krijgt, kun je als implementator de gebruiker helpen door `rows=20` te doen
thomas: maar voor nu is er geen regelgeving over het aantal rows, het is aan de implementator om na te denken 'wat gaat hier in komen'
michiel: De wens is dat als je geen row=..... definitie toevoegt hij op 4 komt te staan
thomas: dat kan niet
michiel: Maar de textfield kan dus niet standaard 4 gemaakt wordt moet perse implementatie zijn
thomas: de textfield kan niet standaard op 4 worden gezet vanuit markup
thomas: wat wel kan is standaard de hoogte op _ongeveer_ 4 regels zetten vanuit de CSS
thomas: met nadruk op ONGEVEER :wink:
thomas: het mooie van het attribuut rows is dat het waar is: ongeacht styling zal de browser 4 tekstregels hoogte rekenen
thomas: met CSS kunnen we het wel op dezelfde manier uitrekenen maar het zal altijd een benadering zijn
michiel: En als iemand vervolgens zelf rows toevoegd komt deze hoogte dan te vervallen want er zullen wel situaties zijn waar we misschien meer willen.
michiel: Nou voordat we dit gaan doen ga ik dit even overleggen met de teams. Wat wij willen.
michiel: Want wordt deze hoogte vervolgens ovverruled door rows?
thomas: dat kan geregeld worden
thomas: als we stijlen op `textarea:not([rows])` kunnen we vanuit de CSS een 'default hoogte' zetten
michiel: Ok dan is de benadering prima. Zo nauw zal het niet komen.
michiel: Probleem waar ik mee zit namelijk is dat developers zelf niet altijd rows definieren merk ik. Dus dan springt deze terug naar die 2 rows (Of de browser interpretatie)
michiel: Dan heb ik liever toch een consistent start punt vanuit ons gedefinieerd
thomas: prima, wij laten deze issue even liggen tot je weet wat we willen
```

Sinds dit gesprek hebben wij niets meer over dit onderwerp vernomen

**Comment by MichielDHVD** [comment]
@tfrijsewijk De standaard hoogte mag op 3 rows gezeten worden. Via het css trucje dat je hebt besproken.

**Comment by tfrijsewijk** [comment]
Laatste fix zit in `master`, komt bij de volgende release mee

**Comment by tfrijsewijk** [comment]
Testable: https://www.dso-toolkit.nl/3.1.0/components/detail/group-textarea.html
