### ISSUE TITLE
Viewer Grid: VDK layout

### ISSUE THREAD

**Issue by gzeilstra** [dso-toolkit/dso-toolkit#2161]
# Aanleiding
Door de WCAG en de naderende IWT is het van belang dat het viewer grid wordt uitgebreid, zodat de VDK hier ook op kan aansluiten. Op dit moment heeft de VDK zijn eigen viewer grid geïmplementeerd. Echter voldoet deze implementatie niet aan de WCAG eisen. 

# Verschillende situaties
## Situatie 1: Geen rechterpaneel
Als de gebruiker nog geen document heeft open geklikt, dan is er nog geen rechter paneel. 
In deze situatie heb je het linker paneel en de kaart. 
**vraag: in de VDK kunnen we het paneel links niet groter en kleiner maken. Maar willen we dit wel?** 
![Image](https://github.com/dso-toolkit/dso-toolkit/assets/67144239/cca1c999-7c98-4bc8-89d8-868c915f6d40)

## Situatie 2: Een gebruiker heeft het document geopend en dus een rechterpaneel
Als een gebruiker een document opent dan verschijnt het rechterpaneel en wordt het linker paneel klein. 
Het linker paneel ligt nu als het ware op de kaart en is smaller dan het oorspronkelijke formaat. 
Daarnaast kun je het linker paneel wegklikken door middel van het pijltje.
Het rechter paneel kun je groter en kleiner maken door middel van de pijltjes. De formaten komen overeen met het huidige linker paneel in het viewer grid. 
![Image](https://github.com/dso-toolkit/dso-toolkit/assets/67144239/ee73fcb6-603a-4ab7-ab0e-2c0dbca3216f)
![Image](https://github.com/dso-toolkit/dso-toolkit/assets/67144239/7a12b4dc-e976-4c04-90f3-c4d3b7073f7f)

## Situatie 3: Een gebruiker wil de documentenlijst zien en klapt als het ware het linkerpaneel open.
De gebruiker kan het linker paneel die in de vorige situatie klein was ook open klappen. Dan valt het paneel niet meer over de kaart, maar deze drukt de kaart dan als het ware weg. 
Het linkerpaneel kan in deze situatie ook worden weggeklapt. 
![Image](https://github.com/dso-toolkit/dso-toolkit/assets/67144239/0273a9d8-64c0-4c52-88bb-d7ee2ed729f2)
![Image](https://github.com/dso-toolkit/dso-toolkit/assets/67144239/01c595a8-7c48-448f-9031-7800f1d048fe)

## Situatie 4: Een gebruiker kan werken op een kleiner scherm. 
De gebruiker kan werkzaam zijn op een kleiner scherm. Het linker en het rechterpaneel mag elkaar niet overlappen. Als de focus op het document ligt en er is niet genoeg ruimte om het linker paneel open te houden, dan klapt deze weg naar de zijkant. Maar ook als de gebruiker het rechter paneel op de breedste stand heeft staan en hij/zij klapt het linker paneel open, dan moet het rechter paneel kleiner worden. Het rechterpaneel zal niet dichtklappen. Deze wordt alleen kleiner. 
![Image](https://github.com/dso-toolkit/dso-toolkit/assets/67144239/3cd70b73-d8ce-4837-8097-ac71a1b69818)
![Image](https://github.com/dso-toolkit/dso-toolkit/assets/67144239/eb1cd670-129f-4514-8ff7-de1a75ea89ca)

## Situatie 5: Als een gebruiker op een link klikt in het document wordt een modal geopend
**Twijfel of deze ook in deze story thuis hoort.** 
![Image](https://github.com/dso-toolkit/dso-toolkit/assets/67144239/f0f438ec-b91b-4bc7-aa80-f79561defdff)

Zie voor de werking: https://snapshot.document-viewer.dso.kadaster.nl/viewer/locatie

# Aandachtspunten
- Het linker en het rechter paneel mag elkaar niet overlappen
- De tabinxdex moet op de juiste manier switchen. Dus als iemand een document opent, dan moet de tabindex naar het rechterpaneel en andersom. 
- Deze uitbreiding moet rekening houden met de tabjes die we in #2254 hebben gemaakt. Er komt een paneel bij die een plekje in die tabs moet krijgen.

# Toekomstig
In de toekomst moet het grid voor de viewers ook responsive worden. Dit is tevens een eis vanuit de WCAG. 
Het responsive maken lijkt me een goede tweede stap. Zodat we hier ook een passend design voor kunnen aanleveren.

**Comment by gzeilstra** [comment]
@tfrijsewijk @LiesbethVorst 
Ik heb een eerste voorzet gedaan voor deze story. Kunnen jullie hier naar kijken en mogelijk aanvullen?

**Comment by LiesbethVorst** [comment]
Deze pas oppakken na #2254

**Comment by DjangoBlok** [comment]
@LukeVerlaan Ziet er al goed uit
Nog twee bevindingen:

- De hierboven beschreven situatie 4 lijkt nog niet te werken. 
-- Het rechterpaneel mag het linkerpaneel "dicht" duwen, als beide panelen niet tegelijk passen.
-- Bij tevoorschijn halen van het linkerpaneel, mag deze het rechterpaneel naar de smalle versie sturen als beide panelen niet tegelijk passen.
- Het overlay ziet er in de VDK modus anders uit. Nog steeds rechts uitgelijnd, maar met een kleine marge eromheen.

**Comment by DjangoBlok** [comment]
Bij VRK zijn de namen van de tabjes goed. 
Vandaag besproken op te tabjes voor VDK te hernoemen naar 'Zoeken', 'Kaart' en 'Document'.
