### ISSUE TITLE
Header: Uitloggen als button krijgt de verkeerde styling

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#2163]
Aanleiding: 
Bij het stichting accessibility rapport waren er een aantal bevinding voor de header. 

Werkzaamheden: 
- PR02 gebruikt voor uitloggen een button, omdat het de functie heeft van een button. Maar alleen links hebben styling in de header. Waardoor de volgende situatie ontstaat en wanneer uitloggen gefocused wordt de tekst "onzichtbaar" wordt. 
![Screenshot 2023-06-12 at 08 21 25](https://github.com/dso-toolkit/dso-toolkit/assets/36912722/1748cc88-ac4e-4f01-8a57-62b94682a41f)
![Screenshot 2023-06-12 at 08 21 36](https://github.com/dso-toolkit/dso-toolkit/assets/36912722/e206dd2e-fa16-4c4a-bdaf-cafb24a72067)
- Als de website bekeken wordt in een schermresolutie van 1280px
bij 1024px en ingezoomd is op 400% dan verschijnt rechtsboven
in beeld een hamburger menu knop. Zodra een bezoeker met een
toetsenbordbediening door de geopende hamburger navigeert is
de focus niet zichtbaar (vanaf de hyperlink "Vergunningscheck")
doordat de geopende hamburger menu niet scrolbaar is.
- Als de website bekeken wordt in een schermresolutie van 1024px
bij 768px en ingezoomd is op 200% dan verschijnt rechtsboven in
beeld een hamburger menu knop. Zodra een bezoeker met een
toetsenbordbediening door de geopende hamburger navigeert is
de focus niet zichtbaar (vanaf de hyperlink "Maatregelen op
maat") doordat de geopende hamburger menu niet scrolbaar is.
- Bij implementatie van de toolkit blijken de marges van het openklap menu nog niet te kloppen. Uitklapper staat niet altijd netjes uitgelijn onder aan de rand van de header. 
![Screenshot 2023-06-12 at 08 26 03](https://github.com/dso-toolkit/dso-toolkit/assets/36912722/b8e1cb0a-b850-4071-89af-4b25a77daee9)
![Screenshot 2023-06-12 at 08 26 59](https://github.com/dso-toolkit/dso-toolkit/assets/36912722/6cd2ce62-06c1-4a2a-b632-93e79eb9c0b6)

Testen:
Responsive testen op volgende viewports:
- Schermresolutie van 1280px
bij 1024px en ingezoomd is op 400%
-Schermresolutie van 1024px
bij 768px en ingezoomd is op 200%

**Comment by HalloJo** [comment]
De uitlijning van het dropdown menu was al door @LukeVerlaan opgelost in een ander ticket. En het navigeren in de dropdown met een keyboard lijkt te werken verwacht. Maar fijn als iemand dat even kan dubbelchecken.

**Comment by LukeVerlaan** [comment]
De uitloggen knop is zichtbaar in storybook met controls: Authenticatie: loggedIn & Uitloggen url leegmaken

**Comment by timveld** [comment]
Nieuwe situatie gechecked en lijkt op alle punten goed te zijn. Scrollt bij gebruik, uitloggen link zichtbaar bij focus en geen problemen met NVDA.
