### ISSUE TITLE
Opengeklapte header menu kan chrome laten crashen 

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#2164]
Reproduceren: 
(Chrome MacOS) 
Open het menu op een kleine schermbreedte. Sleep je browser window naar volledige breedte vervolgens blijft het scherm hangen en crashed de browser tab. 
Zichtbaar op pre, acc en int
https://pre.omgevingswet.overheid.nl/home
![Screenshot 2023-06-12 at 08 32 17](https://github.com/dso-toolkit/dso-toolkit/assets/36912722/077bf610-c762-4f01-9472-65d9700536c9)

**Comment by hansgrimm** [comment]
@tfrijsewijk nou en of...
<img width="1712" alt="Scherm­afbeelding 2023-06-13 om 08 09 19" src="https://github.com/dso-toolkit/dso-toolkit/assets/506527/d6aad3b7-8741-4f7d-90ef-17288d682441">

**Comment by MichielDHVD** [comment]
Nee is niet te reproduceren in de toolkit, zet deze ticket ook even op Discovery. De vraag is namelijk of de toolkit hier uberhaupt iets aan kan doen. Dus eerste vraag is dus: Moet de toolkit dit fixen?

**Comment by gofix** [comment]
NB: het is (gelukkig, nou ja...) ook op Windows. Maar inderdaad niet als we het header component los in Storybook bekijken. Misschien iets met de `debounce()` die niet helemaal lekker loopt in de context van de website? :(

**Comment by LukeVerlaan** [comment]
Ik heb de header in een lege applicatie gegooid en daar ervaar ik ook het crashen. Dit ga ik dus nog verder in de toolkit onderzoeken.

**Comment by LukeVerlaan** [comment]
De crash gebeurt bij de trigger van het resize event. Wanneer de header groot genoeg is dat de dropdown-menu moet verdwijnen en het navigatie menu weer verschijnt. Ik vermoed dat popper voor deze crash zorgt. De popper is op dat moment open en wordt mogelijk niet goed gesloten. Daarom heb ik nu als oplossing dat bij het resize event de dropdown menu wordt gesloten, voordat het zetten van het menu gebeurt.
