### ISSUE TITLE
Accordion: Spec "should emit dsoToggleSectionAnimationEnd event for all toggle animations end" wait(1500) weghalen

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#2169]
Met de update naar Stencil 3 (#2120) is de asynchroniteit in deze test een grotere rol gaan spelen. De test faalt nagenoeg altijd.

Ik vermoed dat dit komt omdat er al op de section wordt geklikt voordat deze klaar is om het event dmv. een animatie te verwerken. De animatie wordt door animejs geregeld, maar het component klapt gewoon keihard open waardoor animejs geen weet van de animatie had. Hierdoor wordt het event nooit afgevuurd.

Ik heb dit nu opgelost met een pijnlijke `.wait(1500)`, maar dat is natuurlijk geen permanente oplossing.

**Comment by tfrijsewijk** [comment]
@LukeVerlaan iets voor jou?

**Comment by LukeVerlaan** [comment]
Ja, dat wil ik wel doen

**Comment by tfrijsewijk** [comment]
Haal je dat nog voor je vakantie?

**Comment by LukeVerlaan** [comment]
Met het stateless maken van de accordion (https://github.com/dso-toolkit/dso-toolkit/issues/2130) zijn de tests aangepast/herschreven en is dit niet meer van toepassing.
