### ISSUE TITLE
Accesskeys invoeren

### ISSUE THREAD

**Issue by timveld** [dso-toolkit/dso-toolkit#2173]
### Waar
Diverse focusbare elementen
### Aanleiding
Bij het werken met het omgevingsloket moeten toetsenbord gebruikers soms erg veel tabben om focus op een element te krijgen. Waar dit mij nu het meest stoort is de vergunningcheck, waar je vaak gewoon snel naar de "volgende" knop wilt springen zonder door al die werkzaamheden en dergelijke te moeten tabben.

In enkele gevallen is het gebruik van het html accesskey attribuut een goede oplossing. Je zou dan bijvoorbeeld met alt (+ shift) + v naar volgende kunnen springen, alt (+ shift) + f naar een zoekveld enzovoort.

Ik denk dat deze functie toetsenbord gebruikers helpt om veel efficiënter te werken. Vooral omdat onze applicaties zo complex zijn en ze voor veel gebruikers onderdeel zijn van hun dagelijkse werk, voor deze gebruikers loont het de moeite om dit soort efficiëntieverhogende trucjes aan te leren.

Een voorwaarde is wel dat de sneltoetsen DSO-breed op een consistente manier worden ingevoerd. Ik denk daarom dat we niet kunnen volstaan met de simpele mogelijkheid voor een implementator om een accesskey mee te geven, maar dat we de implementator een keuze moeten laten maken uit een aantal 'elementtypen'. Daarmee houden we op toolkit niveau controle over de sneltoetsen en kunnen we die wijzigen (belangrijk voor bijv. toekomstige vertalingen). Ik denk bijvoorbeeld aan de volgende typen waarvoor het handig is met alt (+ shift) + letter heen te springen:

* Volgende (v) en vorige (r) knoppen

* Zoom kaart in (=) of uit (-)

* De knop rechtsboven voor inloggen of het gebruikersprofiel menu (l)

* Een toevoegen knop (t)

* Zoeken (z of f)

#### Onderzoeksvragen

Voordat we deze functie eventueel verder specificeren moeten we een paar vragen beantwoorden, onder meer:

* Willen we dit / is er draagvlak bij de teams?

* Is mijn idee optioneel een 'elementtype' te laten kiezen goed en technisch uitvoerbaar?

* Welke sneltoetsen gebruiken we (al dan niet met shift, welke letters?), is er een standaard die we kunnen volgen?

* Kunnen we een visuele hint geven, en zo ja hoe doen we dat? (zowel qua styling als techniek - mooiste zou zijn als de toolkit dit zelf kan zonder dat de implementator de letter moet markeren)

* Hoe en waar documenteren we deze functie voor gebruikers?

* Wanneer gaan we dit bouwen en implementeren? Kan me voorstellen dat een moment na inwerkingtreding beter is.

#### Vervolg

Ik agendeer dit voor UX overleg 27 juni, graag voor die tijd over nadenken.

### Gebruikersimpact

Dit is een feature request maar geen bug, het 'probleem wat dit oplost' heeft echter gebruikersimpact Hinderlijk: het kan toetsenbord gebruikers veel tijd kosten om bepaalde elementen te bereiken in ons complexe portaal. We zijn niet 'verplicht' om deze sneltoetsen in te voeren, maar ze kunnen voor toetsenbordgebruikers wel veel waarde toevoegen.

**Comment by tfrijsewijk** [comment]
Ik voorzie een versplintering van de verantwoordelijkheid voor het invoeren van accesskeys. De toolkit kan maar zoveel: We kunnen bijvoorbeeld accesskeys op de zoomknoppen voor de kaart zetten, maar alle andere knoppen op de kaart (bv tekenen) kent de toolkit niet.

Ik denk dat het beter is om applicatiebouwers deze verantwoordelijkheid te geven zodat er geen misverstand ontstaat "ik dacht dat de toolkit dit zou doen".

We kunnen dit ondersteunen en begeleiden met documentatie. Deze documentatie kan bv. een tabel bevatten met logische accesskeys. @timveld wat denk je hiervan?

**Comment by tfrijsewijk** [comment]
@sanderhaa Wil jij deze op de aanstaande UX agenda zetten?

**Comment by tfrijsewijk** [comment]
@timveld Dit issue graag nog aanvullen.

**Comment by timveld** [comment]
Conclusie is dat de implementator zelf een access key moet toevoegen, de toolkit kan dit documenteren en een lijst van voorgestelde access keys geven. Tot daar toe een goed en uitvoerbaar idee. 

Maar dan is het volgende probleem dat we de gebruiker duidelijk moeten maken welke access key hij kan gebruiken. Sr-only is dat nog te doen, maar visueel? Volgens mij heb je globaal de keuze tussen het markeren van de letter of een oplossing met een tooltip / title (dat laatste doet Wikipedia met het zoekveld alt + shift + f). Beide oplossingen hebben veel impact, een onderstreepte letter kan storend / verwarrend zijn en dat geldt helemaal voor een tooltip. Interessant [achtergrondartikel](https://alistapart.com/article/accesskeys). 

Het is best veel gedoe voor een kleine functie en ik ben bij nader inzien niet voldoende zeker van nut en noodzaak. Dit is een mooi onderwerp om in komende gebruikerstesten of een kleine enquête aan toetsenbord gebruikers met en zonder visuele beperking voor te leggen. Kennen ze het access key mechanisme, denken ze dat ze het gebruiken, op welke elementen zouden ze het willen gebruiken, hoe verwachten ze dat we de access key aangeven?

@tfrijsewijk als je het daar mee eens bent kunnen we dit issue voor nu sluiten of ergens parkeren waar het niet in de weg staat.

**Comment by tfrijsewijk** [comment]
Lijkt mij prima @timveld! Dank voor je input.
