### ISSUE TITLE
core / header:, menu bij inzoomen: tekstkleur laatste item past niet aan

### ISSUE THREAD

**Issue by timveld** [dso-toolkit/dso-toolkit#2174]
### Waar
core / header

### Aanleiding
Een bevinding van stichting accessibility.
Steps to reproduce (probleem treedt alleen in dit specifieke geval op!):
* Ga naar int.omgevingswet.overheid.nl
* Klik op inloggen en log in.
* Zoom in totdat je rechts bovenin de menu knop krijgt.
* Activeer deze menu knop met het toetsenbord, je kunt nu met pijl omhoog / omlaag door dit menu navigeren.
* Ga met pijltjestoetsen naar het laatste item "uitloggen", je zult nu zien dat de tekst "uitloggen" niet meer leesbaar is (geen contrast met de groene selectiebalk, tekstkleur past zich niet aan)
### Werkzaamheden
volgens @MichielDHVD  een toolkit issue.
Oorzaak opsporen en verhelpen.
### Gebruikersimpact
Hinderlijk: De gebruiker kan de tekst uitloggen niet lezen als de balk er op staat. Hij kan de tekst wel lezen door de selectiebalk er af te halen.

**Comment by tfrijsewijk** [comment]
@tfrijsewijk Fuseren met #2163
