### ISSUE TITLE
Core / Header: menu knopje kan buiten beeld vallen

### ISSUE THREAD

**Issue by timveld** [dso-toolkit/dso-toolkit#2176]
### Waar
core / header
### Aanleiding
Bevinding stichting accessibility. Bij inzoomen op bijvoorbeeld https://beheerportaal.acc.omgevingswet.overheid.nl/inloggen kan de menu knop deels buiten beeld vallen. 
Als ik bij deze pagina tot 400% inzoom valt de knop inderdaad buiten beeld. Op storybook bij 400% nog niet maar 500% wel. 

### Werkzaamheden
Oorzaak onderzoeken en ontwerp aanpassen.
### Gebruikersimpact
Kritiek: mogelijk kan de knop onder bepaalde omstandigheden helemaal buiten beeld vallen, dan is hij niet meer bedienbaar.

**Comment by MichielDHVD** [comment]
@MichielDHVD Ontwerpen voor uiterste zoom niveaus.

**Comment by tfrijsewijk** [comment]
@dso-toolkit/dso-ux Doornemen tijdens UX overleg.

**Comment by MichielDHVD** [comment]
Als ik in de toolkit inzoom op 500% dan blijft het menu gewoon netjes in beeld staan. 

Afbeelding is op 500% ingezoomed .
https://storybook.dso-toolkit.nl/!angular/54.3.0/iframe.html?args=useDropDownMenu:always&id=header--with-sub-logo&viewMode=story

Afbeelding en Link naar implementatie waar het fout gaat. 
<img width="1477" alt="Screenshot 2023-07-03 at 13 49 53" src="https://github.com/dso-toolkit/dso-toolkit/assets/36912722/194fc744-b774-466c-8615-66d4f8d1758c">

https://pre.omgevingswet.overheid.nl/orienteren/viewer?regelsbeleid=regels 

<img width="1452" alt="Screenshot 2023-07-03 at 13 47 28" src="https://github.com/dso-toolkit/dso-toolkit/assets/36912722/9b80dd19-77ad-411a-9e12-8a0b7681e1bb">


Hulp nodig staat echt gigantisch in de weg op grootte zoom niveau's

**Comment by MichielDHVD** [comment]
Header voorstel ux overleg
![Header voorstel](https://github.com/dso-toolkit/dso-toolkit/assets/36912722/69171b37-70ef-4e03-800f-18d1a689b799)

**Comment by tfrijsewijk** [comment]
@MichielDHVD was bij de refinement van 13-7 niet aanwezig. Dit behandelen we bij het eerst volgende UX-overleg. Zet jij het op de agenda?

**Comment by MichielDHVD** [comment]
@hansgrimm gaat samen met een pr02 developer kijken waar het misgaat.

**Comment by MichielDHVD** [comment]
Lijkt opgelost te zijn. Is niet te reproduceren op dit moment. Zelfs niet op 500% 


https://pre.omgevingswet.overheid.nl/orienteren/viewer?regelsbeleid=regels

**Comment by hansgrimm** [comment]
Vlgs Statcounter is wereldwijd de kleinste in gebruik zijnde viewportbreedte 360px: https://gs.statcounter.com/screen-resolution-stats/mobile/worldwide
In NL is 360 ook de kleinste, en zelfs heel erg in de minderheid: https://gs.statcounter.com/screen-resolution-stats/mobile/netherlands

Voordat de WCAG de 320 een keer gaat ophogen, zijn we jaren verder...

**Comment by tfrijsewijk** [comment]
@MichielDHVD gaat met @hansgrimm bij PR02 shoppen.

@LiesbethVorst heeft een soortgelijke bevinding, kan jij hier wat plaatsen?

**Comment by LiesbethVorst** [comment]
Dit is de Stelselcatalogus op 1280 breed 400% ingezoomd. 
<img width="1280" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/91903058/dc260452-1348-414d-a092-72e2caeb6316">


Kennelijk zit het probleem in het formaat van het logo. Als afnemer zou ik wel verwachten dat ik het logo (in het juiste formaat) in de toolkit kan vinden. Is dat nu zo?

**Comment by tfrijsewijk** [comment]
@MichielDHVD @hansgrimm hebben jullie nog contact gehad met PR02?

**Comment by hansgrimm** [comment]
@tfrijsewijk @MichielDHVD we weten waar het aan ligt: de SVG van het logo. Die moet vervangen worden.

**Comment by tfrijsewijk** [comment]
OK. Is dit verwerkt in 'n issue en hoe verhoudt de bevinding van Liesbeth zich tot jullie conclusie?

**Comment by tfrijsewijk** [comment]
@hansgrimm Wil jij dit afnotuleren en daarna sluiten?

**Comment by hansgrimm** [comment]
Logo komt niet bij ons vandaan, issue lijkt (mede) veroorzaakt door een tweede plaatje met de subtitel.
Plan is om een separaat logo-component te ontwikkelen.
deze issue kan gesloten worden.

**Comment by tfrijsewijk** [comment]
Zie ook #2265 🎉

**Comment by timveld** [comment]
Bij de discussie met stichting Accessibility hebben ze een mogelijk gerelateerd issue gevonden: als je de stelselcatalogus bekijkt in 1024X768 ingezoomd op 125%, en op het meer knopje drukt, komt de uitklapper helemaal aan de linkerkant en valt goeddeels buiten beeld. Ik kan dit reproduceren.
