### ISSUE TITLE
DSO Expandable Heading - Dropshadow valt soms weg

### ISSUE THREAD

**Issue by DjangoBlok** [dso-toolkit/dso-toolkit#2182]

**Comment by DjangoBlok** [comment]
Bij toegevoegde items is de drowshadow niet altijd zichtbaar.
Zie bijgevoegd plaatje.



![Image](https://github.com/dso-toolkit/dso-toolkit/assets/34900082/e5b7628d-5ea9-4ed3-ad58-3d713eca8b35)

**Comment by tfrijsewijk** [comment]
Aha. Bij rode vlakken is helemaal geen dropshadow trouwens, is dat de bedoeling?

![image](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/8e9026ef-7716-4adc-8423-a3be332d15ff)

Overigens zal ik dit issue oppakken bij de Renvooi refactor 👍

**Comment by DjangoBlok** [comment]
Bij rood is inderdaad geen dropshadow om het meer onderscheidend te maken dan alleen kleur.
Prima om het mee te nemen in de andere story

**Comment by tfrijsewijk** [comment]
Dit issie is als aandachtspunt ondergebracht in #2133. In de basis is de bevinding in dit issue geen probleem omdat de opzet van het nieuwe Document Component fundamenteel anders is.

Ik sluit dit issue.
