### ISSUE TITLE
Geneste suppressed DSO Expandable Heading mag geen opacity 0.6 hebben

### ISSUE THREAD

**Issue by kad-tammie** [dso-toolkit/dso-toolkit#2183]
Geneste suppressed DSO expandable heading ontvangt ook opacity: 0.6 met als gevolg dat diepere niveaus onleesbaar/onzichtbaar worden.  De opacity: 0.6 moet alleen worden toegepast op de hoogste suppressed dso expandable heading.

Zie afbeelding:

<img width="616" alt="Screenshot 2023-06-23 at 09 58 40" src="https://github.com/dso-toolkit/dso-toolkit/assets/77613213/82154fbf-4846-4811-8c5e-3374d943685c">

Tijdelijk opgelost in VDK met:
`dso-expandable-heading[suppressed] dso-expandable-heading[suppressed] {
  opacity: 1;
}`

**Comment by tfrijsewijk** [comment]
Ik heb hier nog eens over nagedacht en zit met het volgende:
* Zou de afnemer niet verantwoordelijk moeten zijn voor het juist plaatsen van het `suppressed` attribuut?
* In #2175 is namelijk alleen de visuele uiting gemaakt, maar eigenlijk moet hier nog een toegankelijke eigenschap voor worden gemaakt.

Ik kan mij voorstellen dat het toegankelijke gedrag achter `suppressed` ongewenst is voor geneste componenten. Er wordt dan dubbel voorgelezen. Of is het juist wel gewenst om elke titel te prefixen met een toegankelijke variant van `suppressed` ?

Bv: "Overige content: Afdeling 1.4 Bouwvoorschriften".

Maar wellicht begrijp ik de feature niet helemaal. @LiesbethVorst @timveld kunnen jullie hier iets van vinden? In https://github.com/dso-toolkit/dso-toolkit/issues/2189#issuecomment-1607113117 staat een overzicht van de verschillende uitingen.

**Comment by tfrijsewijk** [comment]
Bovenstaande is alweer ingehaald door een toegankelijkheids overweging. Elk kind dat volgens de data niet meer van toepassing is krijgt deze marking. Het component is verantwoordelijk voor de correcte visuele uiting.

Ofwel, de fix van Eric krijgt een plekje in de toolkit :+1:.

Inhoudelijk wordt dit issue opgepakt in #2133 omdat er een nieuw component wordt aangeboden. Expandable Heading komt daarmee te vervallen. De "fix" wordt in dat component direct als feature toegepast.
