### ISSUE TITLE
Expandable heading: visuele details

### ISSUE THREAD

**Issue by LiesbethVorst** [dso-toolkit/dso-toolkit#2186]
2 details moeten aangepast worden

![Image](https://user-images.githubusercontent.com/91903058/248285436-1528f451-4e53-4873-90ed-f0d3d739ba0b.png)

### 1. Teveel verticale witruimte tussen heading en content
De afstand tussen de koppen is goed, dat is 8px. Maar tussen koppen en content/tekst is de afstand te groot, die moet ook 8px zijn.

### 2. Verticale uitlijning van label/icon naast kop
De uitlijning moet "top" zijn en niet "middle"

**Comment by tfrijsewijk** [comment]
Hoe verhoudt punt 1 zich tot #2153 ?

**Comment by LiesbethVorst** [comment]
Volgens mij heeft dat niets met elkaar te maken.

**Comment by tfrijsewijk** [comment]
Ok, dank voor de reactie. Ik heb dit opgepakt in #2133
