### ISSUE TITLE
Expandable heading: content door laten lopen onder label/icon

### ISSUE THREAD

**Issue by LiesbethVorst** [dso-toolkit/dso-toolkit#2188]
Als er rechtsboven aan de content een label en/of icon wordt getoond blijft nu de verticale ruimte eronder leeg. Dit kost teveel witruimte, de content moet eronder doorlopen.

![Image](https://github.com/dso-toolkit/dso-toolkit/assets/91903058/9ccb0edf-ace0-4812-9873-adcab8fd16f4)

**Comment by tfrijsewijk** [comment]
@LiesbethVorst Ik kan dit niet zo snel in de toolkit vinden, de situatie die we tentoonstellen lijkt het goed te doen: https://storybook.dso-toolkit.nl/54.3.0/?path=/story/core-expandable-heading--renvooiweergave&args=editAction:delete&viewMode=story

Kan je een linkje delen?

**Comment by tfrijsewijk** [comment]
Opgepakt in #2133.

**Comment by tfrijsewijk** [comment]
Correctie: Dit kan niet opgelost worden:

Punt 2 is namelijk een `type: "LID"` en bij dat type doen we iets speciaals: Omdat ze geen `label` en `opschrift` hebben verplaatsen we de `inhoud` omhoog en zetten we die naast `nummer`. Er ontstaan dus drie kolommen (nummer, inhoud, "addons").

**Comment by tfrijsewijk** [comment]
Correctie 2: We doen het simpeler. We pakken eerst het stramien zoals we het ook voor andere type DocumentComponenten hebben. Daarna kunnen we refinen.

**Comment by tfrijsewijk** [comment]
Dit issue gaat op in #2133.
