### ISSUE TITLE
Expandable heading: markering in de kantlijn

### ISSUE THREAD

**Issue by LiesbethVorst** [dso-toolkit/dso-toolkit#2189]
Als gebruiker wil ik kunnen zien welke content er hoort bij het filter dat ik heb gekozen.

### Wens
In de viewer kan de inhoud van een document worden gefilterd. De gefilterde tekst is herkenbaar aan een blauwe markering in de kantlijn. Het is ook mogelijk om de tekst van het gehele document te bekijken waarbij de tekst die hoort bij het filter goed herkenbaar blijft door de blauwe kantlijn.

Als de headings worden dichtgeklapt is het handig om toch te kunnen zien of er gefilterde tekst aanwezig is in de dichtgeklapte content. Daarom wordt er bij zo'n dichtgeklapte headings een blauwe kantlijn getoond. Als de heading wordt opengeklapt verdwijnt de blauwe markering bij de heading en wordt deze markering getoond bij de nu zichtbare content (of bij een geneste heading).

![Image](https://user-images.githubusercontent.com/91903058/248295929-aad96254-2128-440d-b1ec-c3ce18ccd850.png)

**Comment by tfrijsewijk** [comment]
Hoe verhoudt dit zich tot #2175 ?

**Comment by LiesbethVorst** [comment]
Er zijn 3 varianten binnen de content van documenten. De combinatie gefilterd (blauwe kantlijn) en grijs komt niet voor. De varianten zijn:
- content dit hoort bij een filter (blauwe kantlijn, zwarte tekst)
- content die geldt op de gekozen locatie (zwarte tekst)
- overige content van het gehele document (grijze tekst)

**Comment by tfrijsewijk** [comment]
En hoe gaan we dit toegankelijk maken? @timveld @hansgrimm @LiesbethVorst @DjangoBlok suggesties?

**Comment by hansgrimm** [comment]
Met tekstalternatieven.
Maar weet een niet-beperkte gebruiker wat dat blauwe lijntje en de tekstkleuren betekenen?

**Comment by tfrijsewijk** [comment]
De uitwerking van dit issue wordt in #2133 gedaan.

**Comment by tfrijsewijk** [comment]
Gefuseerd met #2133.
