### ISSUE TITLE
Expandable heading: niet inspringen in smal paneel

### ISSUE THREAD

**Issue by LiesbethVorst** [dso-toolkit/dso-toolkit#2190]
Op een smal scherm of smal paneel moeten de headings niet inspringen omdat er te weinig ruimte overblijft voor de tekst. Als er een label staat bij een heading kan dit al buiten beeld vallen.

![Image](https://github.com/dso-toolkit/dso-toolkit/assets/91903058/a2d70efa-14c7-4a19-83db-780be585ea3c)

### Ontwerp

**Comment by tfrijsewijk** [comment]
Ik zal dit oppakken met #2133.

**Comment by tfrijsewijk** [comment]
Verwerkt in #2133.
