### ISSUE TITLE
Marge tussen ListButtons ontbreekt

### ISSUE THREAD

**Issue by MYpenburg** [dso-toolkit/dso-toolkit#2191]
Tussen de ListButton componenten is de marge 0, zou 8px moeten zijn
<img width="1504" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/7289928/ddb6c5ab-16b6-4469-802d-4aa399b692a6">

**Comment by tfrijsewijk** [comment]
Volgens mij is deze al bekend onder #2157. @HalloJo heeft al een fix gemaakt (PR #2179). Heb je hier haast bij? Ik kan 'n gelegenheidsrelease uitbrengen.
