### ISSUE TITLE
Listbutton gaat stuk onder de 768 pixel viewport

### ISSUE THREAD

**Issue by MYpenburg** [dso-toolkit/dso-toolkit#2192]
Screenshot uit Storybook:

<img width="942" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/7289928/ac51618f-e636-4559-8e4b-160e6ce979b5">

**Comment by tfrijsewijk** [comment]
@hansgrimm kan jij hier naar kijken, en evt. fixen? Het Web Component is ook stuk.

**Comment by hansgrimm** [comment]
hmm, ik zie niks stukgaan:
![Scherm­afbeelding 2023-06-28 om 10 28 29](https://github.com/dso-toolkit/dso-toolkit/assets/506527/1519c6bc-112d-4df4-8b7b-495bf0d3c430)

**Comment by hansgrimm** [comment]
deze verschijningsvorm van de listbutton ("dso-single-count") staat niet als los losse variatie van de list-button in storybook, alleen op de voorbeeldpagina. is dat iets wat ik ook nog kan regelen?

**Comment by tfrijsewijk** [comment]
Goed idee. Dat betekent een change in `list-button.stories-of.ts` voor een extra variant waar de count op 1 wordt gezet. Daarnaast moet de template voor het HTML/CSS component (`list-button.css-template.ts`) worden aangepast zodat de uitzondering ook in de markup voorschriften wordt toegepast. Het Web Component doet dit al zoals het hoort.

**Comment by tfrijsewijk** [comment]
Ik zie nu jouw reactie dat je het niet stuk ziet gaan. Maar gaat #2197 hier niet ook over? Alleen poneert dit issue het als een bug terwijl het een feature is die in #2197 moet worden ontmanteld?

@HalloJo @MYpenburg @hansgrimm ?

**Comment by MYpenburg** [comment]
Voortschrijdend inzicht. Deze melding kan inmiddels idd komen te vervallen
