### ISSUE TITLE
Selectable: Focus styling toont onterecht bij interactie met muis

### ISSUE THREAD

**Issue by MYpenburg** [dso-toolkit/dso-toolkit#2195]
<img width="615" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/7289928/3cdffe9b-3919-4527-a308-4e7be8449902">
Dit was een hack

**Comment by tfrijsewijk** [comment]
Iets met `:focus` en `:focus-visible`.

**Comment by HalloJo** [comment]
Update: Heel veel al mee gerommeld, maar tot nu toe nog geen succes, behalve als we dit zouden doen:
`&:has(:focus-visible) {
      @include utilities.focus-outline();
    }`. Maar dat kan nog niet helaas. 
    `:focus-visible` zorgt niet voor de oplossing, want hetgene wat de border moet krijgen is een `div`. @svrijsewijk, komt er op neer dat het niet mogelijk is. Maar correct me if I'm wrong.

**Comment by MYpenburg** [comment]
De blauwe border is beter

**Comment by hansgrimm** [comment]
> De blauwe border is beter

Yep. Dat andere is denk ik niet WCAG 2.2 compliant.

**Comment by MYpenburg** [comment]
Ziet er goed uit, wat mij betreft kan deze door.
