### ISSUE TITLE
Map Controls: buttonLabel, buttonLabelMode, button slot & buttons uitlijnen

### ISSUE THREAD

**Issue by gzeilstra** [dso-toolkit/dso-toolkit#2196]
## De aanleiding
Naar aanleiding van het WCAG onderzoek is er naar voren gekomen dat de zoom knoppen voor de kaart van de viewer niet voldoen aan de WCAG eisen. Uit overleg met de toolkit is naar voren gekomen dat de zoom knoppen uit het map controls component wel voldoen en dat we deze hiermee kunnen vervangen. Echter zijn we bij het implementeren van het map controls component tegen een aantal zaken aangelopen, namelijk: 
- Je kan de zoom knoppen niet alleen implementeren. Je krijgt de kaartdetails en het uitschuifpaneel van de kaart details erbij.
- Je kan de titel van kaartdetails niet wijzigen. Niet in de knop, maar ook niet als het extra paneel open is. 
- Je kan kaart details ook niet weglaten, dat je dus alleen het icoon over houdt bij de knop.
- De kaart details knop staat links van de zoom knoppen. 
- Je kan geen extra knoppen toevoegen aan het map controls component.
- Je kan het event van de kaart details knop niet afvangen, zodat je deze zelf kan gebruiken. 

## Oplossing
- API uitbreiden met `buttonLabel: string = "Kaartlagen";`;
- API uitbreiden met `buttonLabeMode: "hidden" | "responsive" = "responsive";`
- Slot toevoegen waarin afnemer buttons of button groups kan toevoegen;
- Kaartlagen knop komt boven de zoom buttons te staan;

![Image](https://github.com/dso-toolkit/dso-toolkit/assets/67144239/ebe2084f-d4e7-4cec-ba16-6618bf371e9e)

Een belangrijke toevoeging is is `<dso-map-controls mode="sidebar|floating">`. Default is `sidebar`.

- Met `sidebar` benoemen we het huidige uitschuif gedrag: Het paneel schuift van rechts naar links.
- Met de nieuwe `floating` positioneren we de inhoud uit het paneel in een Modal. Deze "floating panel" komt linksonder op de kaart en heeft responsive gedrag over de x en y assen.

## legenda
Als de gebruiker op de kaart tab zit, dan zijn de map control knoppen naar beneden verhuist, en valt de legenda over het scherm. De legenda groeit mee in de hoogte. De hoogte van de legenda wordt dus bepaald door de hoeveelheid informatie die wordt gegeven bij de legenda. Als de legenda scherm vullend is door de hoeveelheid items, dan krijgt de gebruiker een scrolbalk. 
![Image](https://github.com/dso-toolkit/dso-toolkit/assets/67144239/e79276dd-66bd-4fa4-bc90-231d0dee08bb)
![Image](https://github.com/dso-toolkit/dso-toolkit/assets/67144239/e71dbf24-3645-4045-a74d-fe8f04accf04)

## Aandachtspunt
- Als we de maps control niet kunnen implementeren zonder uitbreidingsknoppen, dan schuift het paneel over de andere knoppen. Dit is niet wenselijk.

**Comment by tfrijsewijk** [comment]
@dso-toolkit/dso-ux Doornemen tijdens UX overleg.

**Comment by tfrijsewijk** [comment]
Uitgangspositie is oplossing 3:
* API uitbreiden met button label (default = huidige waarde), button label modus "hidden" of responsive (default = huidige waarde), enable map layers (default = huidige waarde) zodat VDK een eigen legenda kan gebruiken. Bij het uischakelen van de native map layers moet wel een event worden afgevuurd.
* Slot toevoegen waarin afnemer buttons of button groups kan toevoegen
* Kaartlagen knop komt boven de zoom buttons te staan

cc @gzeilstra

**Comment by tfrijsewijk** [comment]
Een belangrijke toevoeging is is `layers-mode="panel|modal"`. Default is `panel`.

Met `panel` benoemen we het huidige uitschuif gedrag. Een paneel schuift naar links.

Met de nieuwe `modal` positioneren we de inhoud uit `panel` in een Modal. Deze modal komt linksonder op de kaart en heeft responsive gedrag over de x en y assen.

@LiesbethVorst ik wil hier graag met jou over sparren. Wellicht dat we samen dit issue kunnen afrefinen zodat we het kunnen estimaten. Hoe zit jij maandag?

**Comment by tfrijsewijk** [comment]
In #2254 is aangegeven dat de kaartknoppen bij een smalle kaart horizontaal onderin de kaart komen te staan.

Dit doen we in dit issue en met Responsive Element.

**Comment by DjangoBlok** [comment]
Ziet er goed uit. Twee puntjes:
- In storybook kan disable zoom niet meer uitzetten. Moet die waarde er nog bij?
- Het floating sidepanel lijkt niet rechts te zijn uitgelijnd. Dat is wel de bedoeling.

**Comment by DjangoBlok** [comment]
Ziet er goed uit! Ik heb er even wat mee zitten spelen en volgens mij moeten we hier alles mee kunnen doen nu.

**Comment by tfrijsewijk** [comment]
Dit issue zet ik terug op RFD: Ik kom er gewoon niet aan toe en ik heb ondertussen ook niet het gevoel dat er veel prioriteit ligt. @DjangoBlok Ik denk dat jij en ik hier eens 'n keertje naar moeten kijken...

**Comment by hansgrimm** [comment]
@tfrijsewijk kan deze dicht? een WCAG issue die de audit overleefd heeft, lijkt me gefixt.

**Comment by tfrijsewijk** [comment]
Ja, laten we dat maar doen
