### ISSUE TITLE
List Button "narrow mode" ontmantelen

### ISSUE THREAD

**Issue by MYpenburg** [dso-toolkit/dso-toolkit#2197]
Verschijnt nu bij viewport S en XS, mag voor nu helemaal weg. De oplossing is nu niet fijn, er moet een beter patroon worden uitwerken maar dat is nu niet opportuun. Er zal een moment zijn dat "mobiele geschiktheid" een issue wordt, dan kunnen we deze daarin meenemen.

Wide mode: 
<img width="818" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/7289928/32e64e56-0ed3-4224-8109-77c7644cf18b">
<img width="934" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/7289928/f38689c5-f35e-4cf5-89a6-e26d4da3bc32">

Narrow mode:
<img width="332" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/7289928/156bfbe6-a6ab-4080-884c-ade2dd00a155">
<img width="332" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/7289928/459478e6-531b-4754-b7f5-fb762d93c43c">

**Comment by tfrijsewijk** [comment]
Aandachtspunt: De tekst moet natuurlijk doorlopen als er geen [min], [aantal], [plus] knoppen zijn.

**Comment by LukeVerlaan** [comment]
Wat in #2192 is gedaan kan hier weer ontmanteld worden denk ik.

**Comment by tfrijsewijk** [comment]
Als je daarmee bedoelt dat de fix uit #2192 sneuvelt omdat die voorziet in styling die in dit issue als ongewenst is verklaard: mee eens.
