### ISSUE TITLE
Alert design improvements

### ISSUE THREAD

**Issue by VolleMelk** [dso-toolkit/dso-toolkit#22]

**Comment by Poofy83** [comment]
Hoe gaan we met langere teksten om? Een tekst is al snel te lang op een smalle viewport

/Original commenter: Thomas - 09-02-18 14:03

-----

Refeer je naar de 56 pixels height die in de afbeelding staat?

Uiteindelijk bepaalt de body tekst de hoogte van de notificatie. Dus als er een tekst langer en extra regels nodig heeft wordt het blok gewoon groter. Belangrijk is dat er boven een grens van 16px is.

Ik zal voor de zekerheid nog even wat afbeeldingen maken en voor kleinere schermen,

/Original commenter: Michael - 09-02-18 14:11

-----

https://www.dso-toolkit.nl/unstable/components/detail/alert.html

Welke iconenset gebruik jij in je ontwerpen? In de toolkit zijn FontAwesome 4.7 en de glyphicons van Bootstrap 3.3 aanwezig: Geen van die iconen lijken op de iconen uit het ontwerp.

Ik heb nu FontAwesome iconen ingesleuteld, mee eens?

/Original commenter: Thomas - 19-02-18 09:39

-----

Mee eens.

/Original commenter: Michael - 19-02-18 10:09
