### ISSUE TITLE
Button row uitbreiden met achtergrondkleur

### ISSUE THREAD

**Issue by LiesbethVorst** [dso-toolkit/dso-toolkit#2208]
### Achtergrond
In de beheeromgeving van de stelselcatalogus is behoefte aan een menubalk om een aantal knoppen te groeperen. 

![Image](https://github.com/dso-toolkit/dso-toolkit/assets/91903058/fb981092-ee71-4e0b-9f81-b5f89a42e34a)

### Oplossing

- Button row uitbreiden met een achtergrondkleur
- Afstand tussen tertiaire buttons: 32px

## Specs
achtergrondkleur: F2F2F2
buttons: 000000 

![Image](https://github.com/dso-toolkit/dso-toolkit/assets/91903058/16282d60-2ab6-4072-87a4-2fb8004e4f8b)

**Comment by tfrijsewijk** [comment]
We denken aan een variant met de naam "emphasized".

**Comment by HalloJo** [comment]
@tfrijsewijk @LiesbethVorst Welke kleur is de achtergrondkleur? En de button tekst kleur moet zwart worden?
