### ISSUE TITLE
Action List en Form Buttons hebben geen verticaal ritme

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#2209]
Waardoor de twee componenten plat tegen elkaar aan vallen.

**Comment by rblanconeira** [comment]
![image](https://github.com/dso-toolkit/dso-toolkit/assets/24987027/6303f1f3-7f97-44a8-adf0-a6dbf7e6b893)

**Comment by hansgrimm** [comment]
Waar kan ik deze issue live bewonderen en fixen?

**Comment by tfrijsewijk** [comment]
@hansgrimm gaat over een verticaal ritme systeem nadenken. Graag nog een los issue voor maken.

**Comment by MYpenburg** [comment]
Zo willen we hem: (32px boven en onder de buttons)
<img width="397" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/7289928/97e4027c-98b4-43eb-bf43-7dd3c31032ec">

**Comment by tfrijsewijk** [comment]
@hansgrimm wil jij dit issue oppakken? Ik heb beloofd dat we dit vrijdag opleveren.

**Comment by hansgrimm** [comment]
@tfrijsewijk heb je een url waar ik kan kijken naar de markup?

**Comment by hansgrimm** [comment]
fix in place:
![simulatie-#2209](https://github.com/dso-toolkit/dso-toolkit/assets/506527/90852e7b-cf59-419b-8d63-dbcb3a267952)
