### ISSUE TITLE
Onderzoek: Verticale ruimte tussen headings en broodtekst

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#2211]
Is de verticale ruimte te groot? Onderzoeken of dit het geval is. 

Voorbeeldpagina maken met representatieve content voor een realistische situatie. Voorleggen aan UX team.

**Comment by hansgrimm** [comment]
UX overleg 5/9

**Comment by MichielDHVD** [comment]
Voorstel hiervoor is verwerkt in https://www.dso-toolkit.nl/_2210-small-viewport-headings/intro

**Comment by tfrijsewijk** [comment]
En nu? Behandelen bij de UX meeting op de 17e?

**Comment by MichielDHVD** [comment]
Ux overleg @MichielDHVD met verbeter voorstel van Hans omtrent verticale ruimte na lopen of deze nog relevant is. Vervolg op 16 januari.

**Comment by tfrijsewijk** [comment]
Ik link deze aan #2217, als die is gedaan nemen we dit issue onder de loep.
