### ISSUE TITLE
Accordion: Nieuwe variant "compact-black" zonder i-tje en zonder kader bij uitvouwen

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#2214]
In de viewer hebben we behoefte aan een 'echte' neutral accordion
Dat wil zeggen:

- Accordion met zwarte titels (zoals in de neutral variant)
- Geen openklap i-tje aan de rechterkant
- Geen zwart kader na het uitklappen

**Comment by tfrijsewijk** [comment]
@dso-toolkit/dso-ux Graag tijdens UX meeting bespreken en afhameren.

**Comment by HalloJo** [comment]
De nieuwe variant heb ik `bare` genoemd. Aangezien hij behoorlijk blanco/kaal is. Hover en active state is op de afbeelding te zien. 

![Screenshot 2023-07-14 142301](https://github.com/dso-toolkit/dso-toolkit/assets/65867508/985bbfa0-c087-4571-9983-91402c2d7e00)

**Comment by LiesbethVorst** [comment]
Hmm, dit is niet wat ik gister heb besproken met @tfrijsewijk. De wens is de compacte variant met alleen een andere kleur (geen grasgroen maar zwart voor de koppen en icons).

**Comment by HalloJo** [comment]
Okee @LiesbethVorst , duidelijk. Dan ga ik deze aanpassen.

**Comment by HalloJo** [comment]
Aangepast 🔧

**Comment by LiesbethVorst** [comment]
Klinkt goed :drum_with_drumsticks: Kan ik het ook ergens zelf bekijken?

**Comment by tfrijsewijk** [comment]
@LiesbethVorst Hier staat de laatste versie: https://storybook.dso-toolkit.nl/_2214-accordion-variant-bare-toevoegen/?path=/story/core-accordion--compact-black&viewMode=story

**Comment by LiesbethVorst** [comment]
Dankjewel. 
De varianten compact en compact black zijn netjes gelijk, op de kleur na. Maar de styling is niet meer netjes. Alleen de onderste uitklapper "Wat kan ik met de uitkomst van de Vergunningcheck?" ziet er goed uit.
<img width="519" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/91903058/272f0284-0797-4bf3-b1e7-4ad3823b5ab8">

**Comment by LiesbethVorst** [comment]
Opengeklapt zit er nog teveel witruimte aan de onderkant:
![image](https://github.com/dso-toolkit/dso-toolkit/assets/91903058/42d76cc3-551c-4ab8-8cca-1f5c19643a86)

**Comment by LiesbethVorst** [comment]
Dit zijn de oorspronkelijke specs
<img width="962" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/91903058/853e21ab-41a3-4cf2-8f69-b6a3ce69a54c">

**Comment by tfrijsewijk** [comment]
Ik heb het uitlijnen van de tekst ten opzichte van de chevron opgelost.

Het probleem met de witruimtes komen ergens anders vandaan. De echte oplossing ligt bij het verticale ritme systeem. Het overschot aan ruimte komt omdat er op de ul uit het screenshot van Liesbeth margin-top en bottom wordt geplaatst. Het lijkt erop alsof de maten van de Accordion kloppen, @hansgrimm kan jij dit dubbelchecken?

En als je dan toch in de code zit, kan jij nadenken hoe we de bevinding van Liesbeth kunnen oplossen? Wat denk je ervan om deze styling in spacing.scss van de Accordion uit te zetten? Dan houden we het in het zicht en komt een goede oplossing later mee.

**Comment by hansgrimm** [comment]
> 

Deze issue kan ik tackelen, en heb dat dus ook gedaan :)
Verkeerd gebruik van de `not()`-selector (correctie, `not()`-selector IS verkeerd gebruik ;)) stuurde e.e.a. in de war.
Overgebracht naar `spacing.scss` met `:where`, en zonder `not()`. Uit `accordion.scss` verwijderd.

**Comment by hansgrimm** [comment]
![image](https://github.com/dso-toolkit/dso-toolkit/assets/506527/95648c4d-7280-48ac-9094-77dc9b10fe54)

Deze is lastiger, want dit zijn standaard algemene regels uit `dso-rich-content` v.w.b. ruimte onder een `<ul>`. Als we daaraan gaan sleutelen, geldt dat voor alles.

**Comment by LiesbethVorst** [comment]
Mooi @hansgrimm, dat de dichtgeklapte accordions nu allemaal weer dezelfde hoogte hebben. Die witruimte onder de opsomming is minder belangrijk.

**Comment by hansgrimm** [comment]
@LiesbethVorst de laatste fix ruimt ook nog die laatste 8px op. Onder voorbehoud van review 😉

**Comment by hansgrimm** [comment]
`align-items` fixt dit niet, want er zat nog een collapsing margin in de weg (4px). 
de `:not()` is niet verhuisd, maar gewoon weg.

**Comment by tfrijsewijk** [comment]
`align-items: flex-start` (oude situatie):

![image](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/c95e4766-87a6-4bca-8a0f-2d40c687734d)

`align-items: center` (nieuwe situatie):

![image](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/318bc19d-c8c3-4815-b485-5956a6a121bf)

🤷

**Comment by hansgrimm** [comment]
Haha, zoek de 7 verschillen 😁

**Comment by hansgrimm** [comment]
![Scherm­afbeelding 2023-07-31 om 22 46 23](https://github.com/dso-toolkit/dso-toolkit/assets/506527/50ea450d-a6e0-44b2-b23e-08902304c6ed)
^^ hier zie je de overflowing margin nog

![Scherm­afbeelding 2023-07-31 om 22 46 44](https://github.com/dso-toolkit/dso-toolkit/assets/506527/69832c84-454d-4086-9e8d-6eb148ead40d)
^^ en hier niet meer

**Comment by tfrijsewijk** [comment]
Aha. Dank voor de toelichting, we hebben het over een ander issue. Ik had het over de verticale uitlijning tussen de chevron en de tekst.

Goed gevonden 👍

**Comment by hansgrimm** [comment]
@tfrijsewijk het ging mij om deze:
![](https://user-images.githubusercontent.com/506527/257229476-246884b8-da90-4bbd-b632-cc512773be5d.png)

er zat bij de eerste 3 meer ruimte onder dan boven; dat was de issue waar Liesbeth het over had. Die ruimte kwam door de overflowing margin van onderaf.

**Comment by tfrijsewijk** [comment]
Helder.

Betekent dit dat we weer klaar zijn voor een testrondje door @LiesbethVorst ?

**Comment by hansgrimm** [comment]
Yeps. Ook de issue met de rich content kan ze bekijken.

**Comment by LiesbethVorst** [comment]
@hansgrimm De hoogte van de dichtgeklapte accordions was al prima. De verticale witruimte in de opengeklapte accordions  met rich content, ziet er ook goed uit!

**Comment by tfrijsewijk** [comment]
🎉 ik ga mergen!
