### ISSUE TITLE
Modal: root element (div) vervangen door dialog element

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#2215]
## Modals
Overgaan op gebruik van het `<dialog>`-element voor _alle_ modals. Dat betekent:
- z-index overbodig, `dialog` wordt met `showModal()` in de `#top-layer` geplaatst, boven alles.
- support is goed: https://caniuse.com/?search=dialog
- krijgt vanuit de browser een stijlbare `::backdrop`, dus geen aparte overlay meer nodig
- focus trap (test: focus is trapped, behalve naar de browser url bar; dat laatste is 'by design'. Test het hier: https://codepen.io/picturit/live/gOQRJyq )
- a11y support: NVDA test (Windows 11, chrome + NVDA - Parallels) op https://codepen.io/picturit/live/gOQRJyq door mij (Hans) uitgevoerd met positief resultaat: modal wordt direct bij openen helemaal voorgelezen, en bij sluiten keert de focus terug op de knop die het modal geopend heeft.
- proeftuintje code: https://codepen.io/picturit/pen/gOQRJyq
- zo te zien kan je nog steeds de pagina eronderdoor scrollen; dat zou je dan indien gewenst apart uit moeten zetten met een `overflow: hidden` zolang het modal getoond wordt.

## Werkzaamheden
- in modal component de buitenste `<div>` vervangen door `<dialog>`
- afvuren modal dmv `showModal()`
- eigen backdrop eraf, styling naar `::backdrop`
- Zorgen voor een accessible name dmv `aria-labelledby`, zoals nu al gebeurt.

**Comment by hansgrimm** [comment]
Modal (web component)

## Markup
- <div class=“dos-modal”>…</div> wordt <dialog class=“dos-modal”>…</dialog>.
- <div class=“dso-modal-overlay”></div> kan weg. ::backdrop neemt het over.
- role=“dialog” en aria-modal kunnen eraf.

## Styling
- .dso-modal
  - alle styling eraf die met positioning te maken heeft (inset, height, position en z-index). Modal wordt vanuit de browser altijd gecentreerd, horizontaal en verticaal.
- ::backdrop
  - background-color: rgba(255, 255, 255, 0.8); (van de oude overlay)
  - de rest van de styling is niet meer nodig
  - blur-filter?

## Gedrag
- om te zorgen dat de dialog zich als een modal gedraagt, moet deze altijd afgevuurd worden met “showModal();”! Dat is (denk ik) iets voor de implementator.
- Sluit sowieso met ESC (standaard browsergedrag), geen standaard ‘light dismiss’. 
- Sluitknoppen (“close();”) bij implementator?
- pagina kan onder modal nog steeds scrollen; “overflow: hidden;” inbouwen op body?
- focus trap is browser standaard, hoeft niet gebouwd te worden.

## A11Y
De <dialog> heeft eigenlijk alle a11y ingebouwd, alleen de accessible name niet. Dit wordt nu geregeld met ‘aria-labelledby’; dat kan zo blijven.

**Comment by tfrijsewijk** [comment]
Is gefuseerd naar #2223.
