### ISSUE TITLE
Nieuwe SVG's voor illustraties

### ISSUE THREAD

**Issue by LiesbethVorst** [dso-toolkit/dso-toolkit#2222]
De huidige SVG's hebben hard coded kleuren.

### Acceptatiecriteria

- grasgroene voorgrondkleur kan vervangen worden
- vlakken die nu wit zijn moeten transparant zijn?

**Comment by tfrijsewijk** [comment]
En wil je dan een soortgelijke opzet zoals we voor Icon hebben? Een Icon wordt ingeladen door het Web Component en kan met `color` worden gestuurd. Dus we zouden 'n `<dso-illustration>` kunnen maken. Aandachtspuntje is dan wel de bundle size, maar laten we eerst we wensen maar in kaart brengen.

**Comment by tfrijsewijk** [comment]
* @LiesbethVorst gaat met @MichielDHVD overleggen.
* Gaan we de bronbestanden of de SVG's in de repository aanpassen?

**Comment by tfrijsewijk** [comment]
@DjangoBlok ik heb dit issue op jouw naam gezet, wil jij deze eventueel doorzetten naar Mieke?

**Comment by DjangoBlok** [comment]
Dit was volgens mij vooral bedoeld zodat we een illustratie konden gebruiken op de landingspagina. We hebben daar nu een aparte illustratie voor toegevoegd. Ik denk dus dat deze voor ons niet meer relevant is.
@tfrijsewijk Ben je het daarmee eens, of zie ik nog iets over het hoofd?

**Comment by tfrijsewijk** [comment]
Prima!
