### ISSUE TITLE
Date Picker: vervangen door `<input type="date">`

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#2226]
## Aanleiding
Op- en aanmerkingen Stichting Accessibility op het gebruik van placeholder (dd-mm-jjjj). Hierdoor het alternatief `<input type="date" />` onder de loep genomen, en het blijkt dat deze qua mogelijkheden en a11y inmiddels behoorlijk volwassen is geworden.

## Realisatie
Tech: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date 
A11y: https://a11ysupport.io/tech/html/input(type-date)_element

## Consequenties
- omgooien diverse formulieren
- eigen date-picker 'end of life' 🥲

**Comment by hansgrimm** [comment]
zie voor stijlbaarheid: https://codepen.io/picturit/pen/RwqZvOJ

**Comment by LukeVerlaan** [comment]
`eigen date-picker 'end of life'`: Een flinke refactor en een stuk simpeler, maar lijkt mij wel dat `<dso-date-picker>` blijft bestaan.

**Comment by LukeVerlaan** [comment]
@hansgrimm ik heb hier een opzetje gemaakt waar je alvast een blik op kan werpen:

https://storybook.dso-toolkit.nl/_2226-Date-Picker-vervangen-door-input-type-date/?path=/story/core-date-picker--default

**Comment by hansgrimm** [comment]
> @hansgrimm ik heb hier een opzetje gemaakt waar je alvast een blik op kan werpen:
> 
> https://storybook.dso-toolkit.nl/_2226-Date-Picker-vervangen-door-input-type-date/?path=/story/core-date-picker--default

Ziet er netjes uit!

**Comment by hansgrimm** [comment]
Misschien een beetje 'late in the game', maar kunnen we dit component niet uitbreiden met de varianten "time", "datetime-local" & "week"*? Het werkt allemaal op dezelfde manier.

* NB: "week" wordt niet ondersteund door firefox en safari
