### ISSUE TITLE
Input: New required indicator

### ISSUE THREAD

**Issue by timveld** [dso-toolkit/dso-toolkit#2235]
### Waar
html|css / Form / Group / Input, met required ingeschakeld 
### Aanleiding
Zelfevaluatie pr02: NVDA leest "labelverplicht" (dus zonder spatie) 

De tekst 'verplicht' wordt vanuit css (met content property) aan het label toegevoegd, waarbij de toolkit niet zorgt voor de spatie. De implementator kan de spatie wel aan zijn label toevoegen maar dit is uiteraard niet de juiste oplossing, de toolkit is er om dit soort dingen te regelen. 

Volgens onze CSS-specialist @hansgrimm is CSS zeker niet de juiste plaats om de tekst 'verplicht' toe te voegen. Dat zal dus vanuit html moeten gebeuren. 

Als het invoerveld focus krijgt, spreekt NVDA door het required attribuut al de tekst "vereist" uit. Het ook voorlezen van de zichtbare tekst 'verplicht' leidt dus tot dubbele informatie en dit wordt door screen reader gebruikers zeker niet gewaardeerd. Daarom moet 'verplicht'in de code buiten het label staan en hoeft ook niet met aria-describedby aan de input gekoppeld te worden. 

Kortom de nieuwe situatie moet worden: 
```
<label for=Input_ID>label</label> <span>verplicht</span>
```
### Gebruikersimpact en planning
Beperkt: de meeste screen reader gebruikers zullen over de ontbrekende spatie en de dubbele verplicht-melding heen luisteren. 
Als het aanpassen van de inputs de teams veel werk oplevert, kunnen we deze change wat mij betreft beter uitstellen tot na inwerkingtreding om de teams te ontlasten. Aan @tfrijsewijk  om dit te inventariseren en een besluit te nemen.

**Comment by hansgrimm** [comment]
@timveld die tekst staat in jouw voorbeeld nu buiten het `label`. Wordt het toch voorgelezen als je het veld focust?

**Comment by timveld** [comment]
Nee, maar dat hoeft ook niet: door het attribuut required wordt al uitgesproken dat het een verplicht veld is. Ook het woord verplicht voorlezen wanneer het veld focus krijgt geeft dus dubbele informatie. 

Bij lezen met de virtuele focus hoor je 'verplicht' nog wel, dat is ook de bedoeling (want in dat geval wordt het required attribuut niet benoemd).

**Comment by hansgrimm** [comment]
@timveld klopt, was domme vraag, has ‘m alweer verwijderd 😉

**Comment by tfrijsewijk** [comment]
En waarom geen

```html
<label for=Input_ID>label</label> <span aria-hidden="true">verplicht</span>
```

Het lijkt mij dat zonder de `aria-hidden="true" een screenreader nog steeds dubbele informatie opleest.

**Comment by timveld** [comment]
Met aria-hidden moeten we zeer terughoudend zijn, die tekst staat er nu eenmaal en wordt bij lezen met de virtuele focus dus voorgelezen.
Semantisch is het echter geen deel van het label, maar een 'invulinstructie'.
Zo'n instructie koppelen we in principe met aria-describedby, maar die koppeling kan achterwege blijven omdat het veld zelf al required is. 
Bij lezen met de virtuele focus hoor je de tekst verplicht nog wel, maar bij invullen met de systeemfocus (waarbij je met tab / shift + tab navigeert) hoor je het woord niet meer. 
Kortom: in mijn voorstel laten we alleen een 'overbodige koppeling' weg.

**Comment by hansgrimm** [comment]
Ik ben geen voorstander van het genereren van tekstcontent dmv CSS, maar vanuit de Toolkit is het wel een optie (1 bron, niet door anderen aanpasbaar). In dit geval kunnen we volstaan met de CSS-oplossing. Daardoor zou de structuur er zo uit kunnen zien:
```
<label for="Input_ID">labeltekst <span aria-hidden="true" class="dso-required-msg"></span></label>
```
De CSS tekst zouden we ook nog met de property `speak: never` kunnen afvangen ipv aria-hidden, maar de ondersteuning is nooit echt goed van de grond gekomen.

**Comment by tfrijsewijk** [comment]
Ik heb dit issue teruggezet naar Discovery, ik weet niet wat het probleem is en wat we willen. Ik weet ook niet of dit een bug of een feature is.

**Comment by hansgrimm** [comment]
Ik zit me nog steeds af te vragen waarom we dit willen. het veld heeft het attribuut 'required', dus alles wat je er bij zet, is voor screenreaders overbodig. er is gewoon een goede foutafhandeling nodig, browser-standaard of van onszelf. 
Hele volksstammen gebruiken nog het sterretje, maar dat is vast niet goed genoeg ;) 

Als we dit toch met alle geweld willen aanpakken, dan lijkt mijn voorstel van 16 augustus (hierboven dus) een prima optie.

**Comment by tfrijsewijk** [comment]
> Ik zit me nog steeds af te vragen waarom we dit willen. het veld heeft het attribuut 'required', dus alles wat je er bij zet, is voor screenreaders overbodig. er is gewoon een goede foutafhandeling nodig, browser-standaard of van onszelf.

Mee eens.

> Hele volksstammen gebruiken nog het sterretje, maar dat is vast niet goed genoeg ;)

Dat weet ik niet, ik heb wel eens gehoord dat dit niet toereikend zou zijn.

> Als we dit toch met alle geweld willen aanpakken, dan lijkt mijn voorstel van 16 augustus (hierboven dus) een prima optie.

Ik zie hier wel iets in. Vind dat ie inderdaad in het label hoort, zodat het tekstveld ook focus krijgt als je erop klikt.

Maar dit is een breaking change. Waar ik mee kan leven, wat moet dat moet. Maar ik zou toch een alternatief willen voorstellen, geinspireerd door https://www.accessibility-developer-guide.com/examples/forms/required/

We vervangen de tekst "verplicht" met een icoon van een asterisk. Dit wordt niet opgelezen doordat het `content` CSS property leeg is.

* Assistive technologies blijven met het attribuut `required` werken, er wordt niets dubbel opgelezen.
* Visuele gebruikers krijgen een visuele hint dat het veld verplicht is;
* Dit is een non-breaking change, applicaties krijgen deze change gratis mee.

Dit valt en staat natuurlijk bij of een asterisk afdoende is om een veld visueel als verplicht te markeren.

<details><summary>Memorylane</summary>
Vroeger hadden we het tegenovergestelde: "optioneel":

![Image](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/b34addde-f2c5-4133-88fd-b6f9cdb7f8f8)

Dit is echter al in versie 3.0.0 gesneuveld. Zie hier versie 2.0.0: https://dso-toolkit.nl/2.0.0/components/detail/group-select.html

</details>

**Comment by hansgrimm** [comment]
haha ja, 'optioneel' was echt onzinnig :)

ik vind dat wel wat die SVG-asterisk, maar deze resource gaat voor het woord 'verplicht': https://a11y-101.com/development/required

**Comment by tfrijsewijk** [comment]
> ik vind dat wel wat die SVG-asterisk, maar deze resource gaat voor het woord 'verplicht': https://a11y-101.com/development/required

Dit document heeft geen datum markering. De bijbehorende video is 5 jaar oud:

![Image](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/5e6b1b32-270d-4dc8-b406-a6b60ad8082c)

Daarnaast maakt geen een voorbeeld gebruik van het `required` attribuut op het interactieve element. Ik twijfel aan de actualiteit van dit artikel.

En:

> [...] but NVDA ignores the `aria-hidden`.

Is dit echt zo?! 🤯

**Comment by hansgrimm** [comment]
Voorgestelde oplossing: 
- attribuut `required` op de `input`
- Asterisk als `::after` op het label
- Aan elkaar hangen met `label:has(+ [required])`
- Wachten tot 21 november? ;)

**Comment by tfrijsewijk** [comment]
> Voorgestelde oplossing:
> 
> * attribuut `required` op de `input`

Dat hebben we al.

> * Asterisk als `::after` op het label

Met illustratie (`background-image`) of karakter ("*")?

> * Aan elkaar hangen met `label:has(+ [required])`
> * Wachten tot 21 november? ;)

Dat zou kunnen, maar onze markup voorschriften schrijven al voor dat een verplicht veld voorzien wordt van een required modifier class op de Form Group:

```html
<div class="form-group dso-required">
```

We hebben dus voldoende haakjes om jouw voorstel zonder `:has()` te implementeren. We hoeven dus niet te wachten.

Is dit voorstel door UX geaccordeerd?

**Comment by hansgrimm** [comment]
> > Voorgestelde oplossing:
> > 
> > * attribuut `required` op de `input`
> 
> Dat hebben we al.
Klopt, maar ik zet het even op een rijtje ;)
> 
> > * Asterisk als `::after` op het label
> 
> Met illustratie (`background-image`) of karakter ("*")?
Wat mij betreft character, maar dat wordt voorgelezen (`speak: never` support is verdampt), dus wss is background-image beter.
> 
> > * Aan elkaar hangen met `label:has(+ [required])`
> > * Wachten tot 21 november? ;)
> 
> Dat zou kunnen, maar onze markup voorschriften schrijven al voor dat een verplicht veld voorzien wordt van een required modifier class op de Form Group:
> 
> ```
> <div class="form-group dso-required">
> ```
> 
> We hebben dus voldoende haakjes om jouw voorstel zonder `:has()` te implementeren. We hoeven dus niet te wachten.
> 
Dat wel, maar de `:has()` automatiseert het. dat heeft over het algemeen mijn voorkeur.
> Is dit voorstel door UX geaccordeerd?
Nog niet, maar eerlijk gezegd verwacht ik daar geen problemen.

**Comment by tfrijsewijk** [comment]
> > > * Asterisk als `::after` op het label
> > 
> > 
> > Met illustratie (`background-image`) of karakter ("*")?
> 
> Wat mij betreft character, maar dat wordt voorgelezen (`speak: never` support is verdampt), dus wss is background-image beter.

👍

> > > * Aan elkaar hangen met `label:has(+ [required])`
> > > * Wachten tot 21 november? ;)
> > 
> > 
> > Dat zou kunnen, maar onze markup voorschriften schrijven al voor dat een verplicht veld voorzien wordt van een required modifier class op de Form Group:
> > ```
> > <div class="form-group dso-required">
> > ```
> > 
> > 
> > We hebben dus voldoende haakjes om jouw voorstel zonder `:has()` te implementeren. We hoeven dus niet te wachten.
> 
> > 
> 
> Dat wel, maar de `:has()` automatiseert het. dat heeft over het algemeen mijn voorkeur.

De mijne ook, maar het is niet blokkerend. En ik wil functionaliteit niet aan twee haakjes ophangen. Dan zie ik liever dat `.dso-required` in z'n geheel wordt vervangen met `:has()`.

> 
> > Is dit voorstel door UX geaccordeerd?
> 
> Nog niet, maar eerlijk gezegd verwacht ik daar geen problemen.

@dso-toolkit/dso-ux Kunnen jullie hier wat over zeggen?

**Comment by MYpenburg** [comment]
Geen asterisk.  En hier is waarom:
- Het symbool in zichzelf is niet duidelijk. 
- Aanvullen met het woordje verplicht: laat m dan weg. 
- En toch gebruiken met ergens onderaan het "formulier" (wat we niet echt meer hebben) een zinnetje *verplichte velden: dat is echt HTML 1.0, vereist mogelijk scrollen en geeft sowieso teveel verwarring terwijl de info (nog) niet nuttig is. 

Even een vraag: waarom willen/moeten we uberhaupt (meteen al) tonen dat een veld verplicht is?  
- Als de gebruiker het veld gewoon invult is er niets aan de hand (wat vaak het geval zal zijn omdat er wel enige logica in de verplichte velden zit)
- Als de gebruiker niets invult wordt hij/zij er wel met een (fout)melding op gewezen.

In een webshop wil je faciliteren dat iemand "zo snel mogelijk zo mager mogelijk" een formulier kan invullen, maar dat is in onze toepassingen toch helemaal geen uitgangspunt? Wij willen juist zo min mogelijk afleiding van de inhoud.

Wat vind de rest hiervan? @dso-toolkit/dso-ux

**Comment by hansgrimm** [comment]
Eens!

**Comment by anneke** [comment]
Deze truc kunnen we nog proberen om de tekst wel in de ::after te hebben maar die niet te laten voorlezen:

https://dev.to/whitep4nth3r/hide-text-in-css-pseudo-elements-from-screen-readers-with-this-one-weird-trick-11eg

**Comment by timveld** [comment]
Even een [code pen](https://codepen.io/timveld/pen/xxMwZwa) aangemaakt met de huidige situatie en twee mogelijke oplossingen. Hiermee kunnen we goed 'horen' wat de diverse oplossingen doen. Heb verplicht niet vanuit CSS toegevoegd maar zou voor het resultaat niet moeten uitmaken.

**Comment by tfrijsewijk** [comment]
Zoals ik gisteren al aangaf wil ik eerst uitzoeken wat mogelijk is zonder een breaking release. De suggesties van Tim zijn fijn, maar zijn pas van toepassing als de het echt niet vanuit CSS kan worden gerealiseerd.

De beruchte asterisk is gisteren ook ter sprake gekomen. Een asterisk wordt met een `background-image` getoond en zal daarom niet in de AOM voorkomen en dus niet zichtbaar voor assistive technologies. Dat komt in dit geval goed uit, want het veld waar het om gaat heeft een `required` attribuut.

Er is geen overeenstemming of de asterisk duidelijk genoeg is om een veld als verplicht te markeren. Ik kom op het internet diverse bronnen tegen die bevestigen dat deze techniek toereikend is. Deze bronnen vinden allemaal dat de asterisk bij de internetgebruiker is ingeburgerd als "verplichte invoer".

In ons design system verwijzen wij veel naar de Nielson Normal Group, en hier raden ze het ook aan: https://www.nngroup.com/articles/required-fields/. 

Dit is een ander artikel wat gaat over het markeren van optionele artikelen: https://uxmovement.com/forms/why-users-fill-out-less-if-you-mark-required-fields/. Hier hebben wij natuurlijk al ervaring mee, maar ik vind vooral de discussies onder dit artikel interessant.

Maar na een nachtje slapen heb ik nog een ander idee. En voordat ik 'm vertel is het goed om er met een "open mind" in te gaan en niet in reflex te schieten ;-)

Het probleem is dat "verplicht" _in_ het `<label>` element staat.

* Ik heb de `::after` op `.dso-field-container` gezet.
* Verder heb ik `.dso-field-container` voorzien van `display: flex;`.
* Het `label` element een `order: -2;` gegeven
* Het `::after` pseudo-element een `order: -1;` gegeven

Na nog wat visuele verbeteringen ziet het er zo uit:

![image](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/f508c3f0-f605-423f-b511-be1f56ea90a3)

Verticaal moet ie nog iets beter worden uitgelijnd, maar daar gaat het nu niet om. Het gaat om het DOM:

![image](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/824a6d45-965d-464b-89a2-9c01ec2dbbf7)

Dus ik realiseer mij natuurlijk dat de visuele volgorde anders is dan de structurele volgorde. Maar laten we het los van dat probleem bekijken: Komen we er zo mee weg?

**Comment by MYpenburg** [comment]
Ik vind het woordje "verplicht" in bovenstaand voorbeeld teveel interfereren met het patroon. Positie tussen label en (i) is wat intrusive, daar is de "informatie" echt niet belangrijk genoeg voor.
Zou het niet rechtsonder het invoerveld uitgelijnd kunnen worden?
<img width="807" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/7289928/820654e1-ee7d-4072-ad6a-2e637b693a3d">

**Comment by tfrijsewijk** [comment]
> Ik vind het woordje "verplicht" in bovenstaand voorbeeld teveel interfereren met het patroon. Positie tussen label en (i) is wat intrusive, daar is de "informatie" echt niet belangrijk genoeg voor.

Voor de oplossing van dit issue maakt het niet uit, maar ik wil graag benadrukken dat het screenshot de huidige situatie is.

> Zou het niet rechtsonder het invoerveld uitgelijnd kunnen worden? <img alt="image" width="807" src="https://user-images.githubusercontent.com/7289928/278980391-820654e1-ee7d-4072-ad6a-2e637b693a3d.png"> <img alt="image" width="807" src="https://user-images.githubusercontent.com/7289928/278982483-df112ac3-3a48-4349-9f25-395fe88ee9f2.png">

Dat kan. In dat geval staat het "verplicht" ook niet in het label. Ik kan mij voorstellen dat het compleet voorlezen van een pagina wel wat verwarrend kan zijn.

Overigens zal het verticale ritme onrustiger worden bij een mix van verplichte en niet-verplichte velden.

Ik stel voor dat jullie dit dinsdag in de UX meeting overleggen.

**Comment by MYpenburg** [comment]
Uitkomst UX overleg: "verplicht" komt rechtsboven. Wide view nog verder uitwerken. Update in dit issue volgt.

**Comment by hansgrimm** [comment]
Uitkomst UX-overleg 07 nov 2023: we gaan toch voor de asterisk, met een uitleg onder- of bovenaan het formulier (eventueel vanuit toolkit te automatiseren?)
@MYpenburg 

issue is RFD
