### ISSUE TITLE
Tabs: Web Component implementatie

### ISSUE THREAD

**Issue by timveld** [dso-toolkit/dso-toolkit#2236]
# Aanleiding

Bij het afnemen van de HTML/CSS implementatie van Tabs komt er veel werk bij het toegankelijkheids aspect en de toetsenbordbediening kijken.

In een Web Component kunnen we die functionaliteit meenemen en onderdeel maken van het component. Dit bespaart de afnemer werk.

# Ontwerp

Visuele en functionele ontwerp is gelijk aan de HTML/CSS implementatie.

# Component Model

```ts
export interface Tabs<TemplateFnReturnType> {
  items: TabsItem<TemplateFnReturnType>[];
}

export interface TabsItem<TemplateFnReturnType> {
  label: string;
  active?: boolean; // Deze is nieuw, is deze nodig?
  id: string;
  modifiers?: "active" | "disabled";
  content: TemplateFnReturnType | string;
}
```

# API

```html
<dso-tabs @dsoTabSwitch=${e => e}>
  <dso-tab label="Zoek op adres" identifier="tabitem-1" active>
    <div class="dso-rich-content">
      <p>Inhoud Zoek op adres</p>
    </div>
  </dso-tab>
  <dso-tab label="Postcode en huisnummer" identifier="tabitem-2">
    <div class="dso-rich-content">
      <p>Postcode en huisnummer</p>
    </div>
  </dso-tab>
  <dso-tab label="Kadastraal nummer" identifier="tabitem-3">
    <div class="dso-rich-content">
      <p>Kadastraal nummer</p>
    </div>
  </dso-tab>
  <dso-tab label="Coordinaten" identifier="tabitem-4" disabled>
    <div class="dso-rich-content">
      <p>Coordinaten</p>
    </div>
  </dso-tab>
</dso-tabs>
```

De API staat nog ter discussie. Er is een andere opzet waarmee de content en tab gescheiden zijn, en dat het label geen attribuut maar een slot is.

* https://www.w3.org/WAI/ARIA/apg/patterns/tabs/examples/tabs-automatic/
* https://opensource.adobe.com/spectrum-web-components/components/tabs/
* https://dev.to/ndesmic/how-to-make-a-tab-control-with-web-components-57on
* https://darn.es/building-tabs-in-web-components/

# WCAG/toetsenbord navigatie

* https://inclusive-components.design/tabbed-interfaces/
* https://www.w3.org/WAI/ARIA/apg/patterns/tabs/examples/tabs-automatic/

**Comment by tfrijsewijk** [comment]
Zoiets https://www.w3.org/WAI/ARIA/apg/patterns/tabs/examples/tabs-automatic/ ?

**Comment by tfrijsewijk** [comment]
Wij staan positief tegenover een Web Component. We wachten met het oppakken van dit issue tot we met @MYpenburg over de mogelijkheden hebben gesproken.

**Comment by tfrijsewijk** [comment]
@MYpenburg kan jij hier jouw hersens eens over breken?

**Comment by MYpenburg** [comment]
Webcomponent lijkt me een goeie oplossing, kan ie meteen goed responsive worden. Gezien de tijdplanning, laten we deze eerst in het UX overleg bespreken.

**Comment by hansgrimm** [comment]
https://inclusive-components.design/tabbed-interfaces/

**Comment by MichielDHVD** [comment]
UX-Overleg 01-08-2023. Dit kan gebouwd worden.

**Comment by timveld** [comment]
@LiesbethVorst stelselvatalogus gebruikt op de pagina waardelijsten ook tabs met hetzelfde probleem. Dus je bent stakeholder in het te bouwen web component.

**Comment by tfrijsewijk** [comment]
Dit pakken we later op. Zie PR voor de laatste stand van zaken.

**Comment by timveld** [comment]
@tfrijsewijk hoe staat het met dit issue?

**Comment by hansgrimm** [comment]
> @tfrijsewijk hoe staat het met dit issue?

Was Raymond Phua hier niet mee bezig?

**Comment by tfrijsewijk** [comment]
Dit issue staat nog steeds op de backlog. Raymond heeft de HTML/CSS implementatie afgenomen.

Misschien gaan we er dit PI wel naar kijken. 🤞
