### ISSUE TITLE
Viewer grid: sr-only tekst bedieningsknoppen inconsistent

### ISSUE THREAD

**Issue by timveld** [dso-toolkit/dso-toolkit#2237]
### Waar
core / viewer grid
### Aanleiding
Als ik op een van de knopjes 'kaartpaneel breder / smaller maken' druk, , geeft NVDA aan "breedte tekstpaneel: [smal / middel / breed]". Op basis van deze tekst ontstaat de indruk dat ik met de knopjes van het kaartpaneel (uitsluitend) de breedte van het tekstpaneel aan het wijzigen ben. De breedte van het tekstpaneel wijzigt inderdaad, maar dat is een bij effect van de actie op het kaartpaneel. Iemand die het scherm niet ziet, heeft aan deze mededeling onvoldoende houvast om te begrijpen wat er visueel gebeurt en kan zich afvragen "heb ik dat kaartpaneel nu wel of niet breder gemaakt?".

We zouden kunnen volstaan met alleen de breedte van het kaartpaneel te melden, maar dan is nog steeds niet helemaal duidelijk wat er visueel gebeurt. Dus om dan maar een volledig tekstalternatief te bieden zoals we eigenlijk moeten doen:
### Werkzaamheden
De sr-only tekst met het aria live gebied aanpassen naar: "Paneelbreedtes: [live region tekstpaneel smal/middel/breed, kaartpaneel smal/middel/breed]"

#### Achtergrondopmerkingen

Woordje 'paneelbreedtes'  buiten de live region omdat het wel nodig is bij lezen met de virtuele focus, maar niet iedere keer herhaald zou moeten worden.
Toch maar eerst tekstpaneel dan kaartpaneel, omdat het anders omgekeerd is TOV de visuele volgorde. Iemand die dit interesseert, moet zijn screen reader maar even uit laten praten en bij dit kleine aantal woorden is dat niet erg.
Knopjes geven niet aan dat ze ook het tekstpaneel beïnvloeden. Maar visueel doen ze dat ook alleen impliciet en het kan worden afgeleid uit de direct er boven staande sr-only tekst. Dus labels niet langer maken dan nodig.

### Gebruikersimpact
Beperkt: de situatie is mogelijk onduidelijk voor iemand die het scherm helemaal niet ziet, maar deze groep zal deze functie niet veel gebruiken; het is eerder een communicatieprobleem. Echter als we zo'n functie inbouwen moeten we het wel goed doen (zonder verwarrende elementen).

**Comment by tfrijsewijk** [comment]
Dit is een foutje: De tekst "kaartpaneel smaller maken" moet zijn "tekstpaneel smaller maken" zijn. De knop gaat namelijk over het tekstpaneel. De knop "kaartpaneel smaller maken" maakt het **tekstpaneel smaller** en dus wordt het **kaartpaneel breder**.

Volgens mij is de verwarring dan weg, mee eens?

**Comment by tfrijsewijk** [comment]
@hansgrimm Pak jij dit op? Graag ook de titel van dit issue bijwerken zodat de change duidelijk is. Mag opgevoerd worden als bug.

**Comment by hansgrimm** [comment]
Gebruikersimpact is beperkt. Hoeveel prio heeft dit?

**Comment by timveld** [comment]
Anders dan ik gisteren dacht doet het knopje precies het omgekeerde van wat het claimt te doen, gebruiker wordt daarmee op het verkeerde been gezet. Gebruikersimpact is daarmee hinderlijk. Dus heeft wel enige prioriteit om dit woordje aan te passen.
