### ISSUE TITLE
Document Component: Diverse bevindingen

### ISSUE THREAD

**Issue by LiesbethVorst** [dso-toolkit/dso-toolkit#2240]
Er zijn nog een aantal punten die verbeterd kunnen worden in het document component:

- [x] is het mogelijk in Storybook de rode hulp-stipellijntjes aan de zijkant niet te tonen?
- [x] qua styling zou er minder verticale witruimte boven en tussen de leden van opsommingen getoond moeten worden
- [x] de noten duwen de tekst in een opsomming omlaag, zie screenshot. Tevens is er geen handje bij hover.
![1](https://github.com/dso-toolkit/dso-toolkit/assets/91903058/e35bf5cc-2118-4cc3-a693-b1ccf6d28a5d)
- [x] bij externe links lijken de iconen te missen die aangeven dat je naar een andere website gaat, zie screenshot:
![2](https://github.com/dso-toolkit/dso-toolkit/assets/91903058/5ad79dde-685a-477d-9a90-1a7913d4b12a)
- [x] Tabellijnen lijken wel aan te staan maar niet getoond te worden:
![3](https://github.com/dso-toolkit/dso-toolkit/assets/91903058/655d2de2-5b76-45b5-afce-6dda28c094d6)
- [x] @LiesbethVorst gaat naar wijzigacties voor Opschrift en Alinea kijken
- [x] Al "wijzigactie"
- [x] Opschrift "wijzigactie"
- [x] README.md is stuk, alleen de relaties tussen componenten worden getoond.
- [x] Betere `console.error` bij ongeldige XML (`{ message: string, error: Error, inputXml: string })`.
- [x] `onDsoAnchorClick` uit Ozon doorzetten
- [x] Externe link icon in Ozon Content fixen
- [x] Uitzoeken of `dso-ozon-content[interactive]` nog nodig is.
- [x] Het component bevat nu een melding voor gereserveerde onderdelen. Zo'n zelfde soort melding moet ook getoond worden bij vervallen onderdelen. Alert info met tekst: Dit onderdeel is vervallen.
![image](https://github.com/dso-toolkit/dso-toolkit/assets/91903058/51bed51d-8581-4b63-aadd-b253647813b1)
- [ ] Bij vrije tekst documenten kun je een divisietekst hebben zonder titel. Dan wordt nu een lege titel met chevron getoond en daaronder de inhoud terwijl je alleen de inhoud verwacht.
![image](https://github.com/dso-toolkit/dso-toolkit/assets/111350940/d7d73aa7-e921-4507-ab46-26547857c9dd)
- [x] Bij een kleine viewport springen de componenten niet meer in maar worden ze onder elkaar uitgelijnd. Echter, de leden worden tegen de linker kantlijn aan gedrukt en lijnen niet uit met de artikelen (zie afbeelding)
![image](https://github.com/dso-toolkit/dso-toolkit/assets/111350940/59689b9e-2b38-4114-98b1-117df42c0cb1)
- [ ] Wanneer we zelf de content toevoegen (dus `inhoud` leeg laten en via het slot content toevoegen) dan lijkt de content niet in te springen.
![image](https://github.com/dso-toolkit/dso-toolkit/assets/111350940/403ef356-ebcf-413c-986f-885d16e16737)
- [x] Ik zie dat de padding erg krap is aan de rechterkant. Kunnen we daar 8px van maken?
![image](https://github.com/dso-toolkit/dso-toolkit/assets/34900082/b7168c25-b01c-4d77-adff-ea9e0badf44a)
- [ ] Mogelijkheid om de toggle/chevron niet te tonen. Dit om de mogelijkheid om open en dichtklappen voor de gebruiker uit te schakelen.
 
----

~~Subtitel element (https://koop.gitlab.io/STOP/standaard/1.3.0/tekst_xsd_Element_tekst_Subtitel.html) ? Wat is dit dan? Dit lijkt in het rijtje "Label", "Nummer", "Opschrift" te staan.~~ In overleg met KOOP & Ozon niet meer van toepassing.

~~Het is niet mogelijk om op "Hoofdstuk 1.4 Konijntjes" te zoeken. Mogelijk ligt dat aan 3x `dso-ozon-content` met Shadow root.~~ Voor nu ga ik dit niet aanpassen, er zijn gesprekken gaande om `<Kop>` als één element uit te geven (in het kader van de performance optimalisaties). Mocht dat gebeuren is dit opgelost. Daarnaast wordt er over een client-side search funtionaliteit gesproken. Ik wil eerst deze trajecten afwachten voordat we besluiten Shadow uit te zetten voor Ozon Content.

**Comment by MichielKadaster** [comment]
@tfrijsewijk 
Bij een kleine viewport springen de componenten niet meer in maar worden ze onder elkaar uitgelijnd.
Echter, de leden worden tegen de linker kantlijn aan gedrukt en lijnen niet uit met de artikelen (zie afbeelding)


![image](https://github.com/dso-toolkit/dso-toolkit/assets/111350940/59689b9e-2b38-4114-98b1-117df42c0cb1)

**Comment by tfrijsewijk** [comment]
* Betere `console.error` bij ongeldige XML (`{ message: string, error: Error, inputXml: string })`.

**Comment by tfrijsewijk** [comment]
* Opschrift "wijzigactie"
* Subtitel element (https://koop.gitlab.io/STOP/standaard/1.3.0/tekst_xsd_Element_tekst_Subtitel.html) ? Wat is dit dan? Dit lijkt in het rijtje "Label", "Nummer", "Opschrift" te staan.
* Al "wijzigactie"

**Comment by tfrijsewijk** [comment]
* @LiesbethVorst gaat naar wijzigacties voor Opschrift en Alinea kijken
* @tfrijsewijk gaat issue met screenshots van Arjan uitbreiden en gaat contact met Jeroen opnemen mbt. de planning.
* Wat denk Ozon over `<Subtitel>`.

**Comment by MichielKadaster** [comment]
@tfrijsewijk door de toolkit styling lijkt het component aan de linker- en rechterkant buiten de box te vallen.
Hierdoor mist aan de linkerkant het blauwe lijntje en een stukje van de border van de nieuweContainer. Aan de rechterkant mist ook een stukje border van de nieuweContainer.
![image](https://github.com/dso-toolkit/dso-toolkit/assets/111350940/e6c7be3f-54d8-4565-a726-b62b924d9cf0)

Volgens mij komt het door dit stukje styling:
![image](https://github.com/dso-toolkit/dso-toolkit/assets/111350940/6533ede0-e923-449c-9872-3b6560a942fc)

Maar misschien doen wij ook iets verkeerd

**Comment by MichielKadaster** [comment]
@tfrijsewijk de inhoudsopgave is ook nog een puntje van aandacht.
Hierin tonen wij het label, nummer en opschrift nu met XML door meerdere `dso-ozon-content` componentjes achter elkaar te zetten.
Maar ik denk dat we hier eigenlijk ook een component van de toolkit nodig hebben. We tonen nu namelijk wel de wijzigingen in de titel (nummer, label, opschrift) maar we zijn niet in staat om de nieuweContainer / verwijderdeContainer etc. weer te geven.

In de afbeelding hieronder zou:

- Artikel 4 Gebruik van siervuurwerk Groen moeten zijn
- Artikel 4 Gebruik van fop- en schertsvuurwerk rood moeten zijn

Dit is denk nog nieuwe wens / aparte story verwacht ik als vervolg op de document component. Wat denk jij hiervan?

![image](https://github.com/dso-toolkit/dso-toolkit/assets/111350940/4da0bd3d-2758-4da1-9002-9c5b633a8715)

**Comment by tfrijsewijk** [comment]
> @tfrijsewijk door de toolkit styling lijkt het component aan de linker- en rechterkant buiten de box te vallen. Hierdoor mist aan de linkerkant het blauwe lijntje en een stukje van de border van de nieuweContainer. Aan de rechterkant mist ook een stukje border van de nieuweContainer.
> 
> Dit lijkt met name te gebeuren wanneer een element zowel `filtered` als een `wijzigActie` heeft.
> 
> ![image](https://user-images.githubusercontent.com/111350940/257507233-e6c7be3f-54d8-4565-a726-b62b924d9cf0.png)
> 
> Volgens mij komt het door dit stukje styling: ![image](https://user-images.githubusercontent.com/111350940/257507306-6533ede0-e923-449c-9872-3b6560a942fc.png)
> 
> Maar misschien doen wij ook iets verkeerd

In de dev/demo omgeving gaat het goed:

![image](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/2293d9ec-b6f9-437f-a7e7-3dad94a71336)

https://storybook.dso-toolkit.nl/56.1.0/iframe.html?args=&id=core-document-component--demo&viewMode=story

Heb je niet nog ergens op een hoger niveau 'n `overflow` actief?

> @tfrijsewijk de inhoudsopgave is ook nog een puntje van aandacht. Hierin tonen wij het label, nummer en opschrift nu met XML door meerdere `dso-ozon-content` componentjes achter elkaar te zetten. Maar ik denk dat we hier eigenlijk ook een component van de toolkit nodig hebben. We tonen nu namelijk wel de wijzigingen in de titel (nummer, label, opschrift) maar we zijn niet in staat om de nieuweContainer / verwijderdeContainer etc. weer te geven.
> 
> In de afbeelding hieronder zou:
> 
> * Artikel 4 Gebruik van siervuurwerk Groen moeten zijn
> * Artikel 4 Gebruik van fop- en schertsvuurwerk rood moeten zijn
> 
> Dit is denk nog nieuwe wens / aparte story verwacht ik als vervolg op de document component. Wat denk jij hiervan?
> 
> ![image](https://user-images.githubusercontent.com/111350940/257508277-4da0bd3d-2758-4da1-9002-9c5b633a8715.png)

Dat denk ik ook. Laten we @dso-toolkit/dso-ux hierbij betrekken. Hoe zat het ook alweer, ben je geblokkeerd of is de oplossing dat je meerdere `<dso-ozon-content>` componenten toont en is de nieuweContainer/verwijderContainer de volgende blokkade?

Los van de naamgeving van Document Component, biedt het je wel alle functionaliteit die je zoekt?

**Comment by MichielKadaster** [comment]
Het zou volgens mij een component moeten zijn die heel veel lijkt op de DocumentComponent (filtered, label, nummer, opschrift, alternatieve-titel, not-applicable,  ontwerp labels etc. zijn allemaal van toepassing). Het volgende is er anders aan:

- Geen inhoud
- Geen annotatie label
- Moet niet open kunnen klappen / geen pijltje voor de tekst

Het is niet blokkerend en bij ons moet dit ook een nieuwe story worden want dit hadden we niet meegenomen. Nu gebruik ik meerdere `dso-ozon-content` componenten achter elkaar. De functionaliteit die dan mist is dat je in de inhoudsopgave niet ziet welke structuur elementen zijn toegevoegd en welke verwijderd. Er moet denk ik ook nog door UX over nagedacht worden hoe dit eruit moet komen te zien.

**Comment by tfrijsewijk** [comment]
Ik weet nog niet of het per se een nieuw component moet worden, of dat het een functionele uitbreiding op Document Component is. Laten we de discussie over de inhoudsopgave verplaatsen naar #2271, dan blijven de bevindingen op bestaande functionaliteit los van de inhoudsopgave.

**Comment by LiesbethVorst** [comment]
Het component bevat nu een melding voor gereserveerde onderdelen.
 
 Zo'n zelfde soort melding moet ook getoond worden bij vervallen onderdelen. De precieze tekst ga ik nog even afstemmen.

**Comment by MichielKadaster** [comment]
@tfrijsewijk hier het issue wat ik de mail met Arjan besprak.
Bij vrije tekst documenten kun je een divisietekst hebben zonder titel.
Dan wordt nu een lege titel met chevron getoond en daaronder de inhoud terwijl je alleen de inhoud verwacht.
Zou je die case nog kunnen ondersteunen?

![image](https://github.com/dso-toolkit/dso-toolkit/assets/111350940/d7d73aa7-e921-4507-ab46-26547857c9dd)

**Comment by MichielKadaster** [comment]
@tfrijsewijk
Wanneer we zelf de content toevoegen (dus `inhoud` leeg laten en via het slot content toevoegen) dan lijkt de content niet in te springen.
![image](https://github.com/dso-toolkit/dso-toolkit/assets/111350940/403ef356-ebcf-413c-986f-885d16e16737)

**Comment by tfrijsewijk** [comment]
> @tfrijsewijk Wanneer we zelf de content toevoegen (dus `inhoud` leeg laten en via het slot content toevoegen) dan lijkt de content niet in te springen. ![image](https://user-images.githubusercontent.com/111350940/259063300-403ef356-ebcf-413c-986f-885d16e16737.png)

Ah, en dit is zeker een IHR document?

**Comment by DjangoBlok** [comment]
Ik zie dat de padding erg krap is aan de rechterkant. Kunnen we daar 8px van maken?
<img width="862" alt="Schermafbeelding 2023-08-22 om 11 48 19" src="https://github.com/dso-toolkit/dso-toolkit/assets/34900082/b7168c25-b01c-4d77-adff-ea9e0badf44a">

**Comment by DjangoBlok** [comment]
Afbeelding vergroten werkt niet meer. 
Als er een afbeelding voorkomt, dan verscheen voorheen de mogelijkheid om de afbeelding te vergroten. Die mogelijkheid lijkt te zijn weggevallen. Daarnaast staat het bijschrift van de afbeelding nu zowel boven als onder de afbeelding. Dit zou alleen onder de afbeelding moeten staan.
![Uploading Schermafbeelding 2023-08-22 om 14.17.24.png…]()

**Comment by tfrijsewijk** [comment]
@DjangoBlok je was te vroeg met het opslaan van het screenshot, de plaat is verdwenen.

**Comment by tfrijsewijk** [comment]
Aha ik zie het.. Heb je 'n linkje?

**Comment by DjangoBlok** [comment]
https://snapshot.document-viewer.dso.kadaster.nl/viewer/(documentresult//rechter-paneel:document/_akn_nl_act_gm0546_2020_OVILEI002_akn_nl_bill_gm0546_2021_besluitjeLeiden/beleid)?id=%2Fakn%2Fnl%2Fact%2Fgm0546%2F2020%2FOVILEI002&isOntwerp=true
Maar hier ook al:
https://snapshot.viewer.dso.kadaster.nl/viewer/document/_akn_nl_act_gm0546_2020_OVILEI002_akn_nl_bill_gm0546_2021_besluitjeLeiden/beleid

**Comment by tfrijsewijk** [comment]
Dit heeft te maken met #2193, ik denk dat iemand de tijdelijke fix uit de Viewer codebase heeft verwijderd.

**Comment by tfrijsewijk** [comment]
@DjangoBlok Ik heb jouw laatste bevinding met Sander Leeffers besproken, hij weet ervan. Dit is een bug in de toolkit (#2193) maar ik heb 'm een snelle fix geleverd waar hij tot die tijd mee uit de voeten kan.

**Comment by tfrijsewijk** [comment]
Uitlijnen van leden in artikelen was niet heel triviaal, want een Artikel hoeft geen leden te hebben. Uiteindelijk heb ik dit gemaakt:



![Image](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/54be4201-f4fe-4916-b86b-06e5cbdfa863)

Graag bevestiging of dit gewenst is.

**Comment by kad-leeffs** [comment]
[] Mogelijkheid om de toggle/chevron niet te tonen. Dit om de mogelijkheid om open en dichtklappen door te gebruiker uit te schakelen.

**Comment by DjangoBlok** [comment]
Variant van document component voor regels op maat

![Image](https://github.com/dso-toolkit/dso-toolkit/assets/34900082/08962c40-97a1-487c-a9f4-3275952fbfad)

**Comment by DjangoBlok** [comment]
@tfrijsewijk in je comment van 3 weken geleden schreef je iets over uitlijning van artikelenm. Maar in het plaatje zijn twee verschillende situaties te zien vooral van de leden. De onderste (Artikel 1.2) is hoe ik het verwacht, de bovenste (Artikel 1.1) is hoe het nu gerealiseerd lijkt te zijn.

**Comment by tfrijsewijk** [comment]
> @tfrijsewijk in je comment van 3 weken geleden schreef je iets over uitlijning van artikelenm. Maar in het plaatje zijn twee verschillende situaties te zien vooral van de leden. De onderste (Artikel 1.2) is hoe ik het verwacht, de bovenste (Artikel 1.1) is hoe het nu gerealiseerd lijkt te zijn.

Dit is een beetje vertekenend:

- Artikel 1.1 bevat geen leden maar is inhoud met een lijst (`<Lijst>`).
- Artikel 1.2 is een artikel met leden.
