### ISSUE TITLE
Accordion animeert niet meer (en reserveert ruimte waardoor er verspringing is)

### ISSUE THREAD

**Issue by QuinteroRivera** [dso-toolkit/dso-toolkit#2245]
Het voorbeeld zal niet al te goed zijn..
Bij het gaan van een `open=true` naar een `open=false` verwachtte ik de gebruikelijke animatie te zien, deze leek er niet (correct) te zijn, ook zodra het gesloten is lijkt hij nog ruimte geserveerd te houden voor 0.1-0.2 seconden waardoor er een (kleine) verspringing is.

Net na sluiten:
![image](https://github.com/dso-toolkit/dso-toolkit/assets/85926021/980e9ec1-4994-46e9-b3cc-370a47753a4c)
Na 0.2 seconden:
![image](https://github.com/dso-toolkit/dso-toolkit/assets/85926021/c30408f7-fe53-4d43-bffd-5a0558c4ea9d)

Excuses voor het super slechte voorbeeld, maar als je hem dus dichtzet zul je een kleine verspringing zien van 1-3 pixels
(indien gewenst kan ik dit ook demo'en in een slack call (Alexander Quintero Rivera)

**Comment by LukeVerlaan** [comment]
Dit is volgens mij opgelost in https://github.com/dso-toolkit/dso-toolkit/issues/2242. Maar verdient nog wel een nacheck

**Comment by LukeVerlaan** [comment]
Ik heb het verkeerd, het verspringen is nog steeds aanwezig.
