### ISSUE TITLE
Viewer Grid: Panelen als Tabs op smalle viewport

### ISSUE THREAD

**Issue by gzeilstra** [dso-toolkit/dso-toolkit#2254]
# Aanleiding
Uit het WCAG rapport is naar voren gekomen dat het zoomen op de VRK niet lekker gaat. Panelen gaan over elkaar heen, waardoor niet alle informatie beschikbaar is.  Om dit probleem op te lossen, is er een mobiele variant gemaakt. 

# Uitwerking
Als de gebruiker inzoomd en panelen dreigen elkaar te overlappen, dan moeten de panelen overgaan naar tabjes "Hoofdpaneel" en "Kaart". 

## Zoekpagina Hoofdpaneel
![Zoom - zoeken](https://github.com/dso-toolkit/dso-toolkit/assets/34900082/24170517-2784-445f-bcec-790a8d565834)

## Zoekpagina kaart 
![Zoom - zoeken - kaart](https://github.com/dso-toolkit/dso-toolkit/assets/34900082/e6c71176-12e3-460d-8bff-20d564420ebb)

## Hoofdpaneel
<img width="344" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/34900082/6f4dadca-02c3-4ec7-ba30-1a83c90931be">

## Kaart
![Zoom - documenten - kaart](https://github.com/dso-toolkit/dso-toolkit/assets/34900082/4d83cbe7-1979-477a-a2a4-cccbb1f9912d)

## Dialog
binnen de VRK kennen we ook dialogs. Deze moeten scherm vullend zijn. 
![Image](https://github.com/dso-toolkit/dso-toolkit/assets/67144239/b85367b1-e6aa-43aa-931b-dad3d8df8d99)

# Aandachtspunten
Uiteindelijk gaat de VDK ook naar het viewer grid en dan zal de VDK ook gebruik maken van deze functionaliteit.

**Comment by DjangoBlok** [comment]
@tfrijsewijk Ik ben het met je eens dat we het simpel moeten houden. 

Mijn suggestie:
- De uitzondering voor het zoekscherm lijkt me niet zo nodig.
- De oriëntatie van de iconen gelijk houden.
- Als de tabjes via de toolkit op een gridpaneel worden geplaatst, dan kunnen ze niet halverwege een paneel (onder het adres) maar of bovenin, of onderin.

**Comment by tfrijsewijk** [comment]
@LukeVerlaan heeft prachtig werk geleverd! @DjangoBlok en @LiesbethVorst jullie kunnen het alvast bekijken op https://storybook.dso-toolkit.nl/_2254-Viewer-grid-small-screen/?path=/story/core-viewer-grid.

Ik vraag mij af of het filterpaneel nog gebruikt wordt? Dit is een paneel wat de er links overheen kan komen te liggen.

**Comment by DjangoBlok** [comment]
Ja ziet er inderdaad goed uit!
Er is 1 situatie die nog wat onhandig is. Bij het linker paneel in breedste vorm kan bij een smalle viewport het knopje om het paneel te verkleinen net uit beeld verdwijnen bij een breedte tussen 768 en 800.  
Het filterpaneel wordt inderdaad nog gebruikt. Mijn verwachting is dat die er gewoon in de volle breedte overheen schuift.

**Comment by LiesbethVorst** [comment]
De tabs zijn nu die van de hoofdnavigatie. Dat is niet de bedoeling, het moet de subnavigatie (dso-nav-sub) zijn.

**Comment by tfrijsewijk** [comment]
Uit de ontwerpen lijkt het eerder op die van hoofdnavigatie:

| Hoofdpagina | Subnavigatie |
|---|---|
| ![image](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/a9289bee-03c9-4b84-ab3f-0f9c483ec4dd) | ![image](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/f52c07d3-3053-4612-8e45-95d25a4738d1) |

Welke willen we?

**Comment by LiesbethVorst** [comment]
In het ontwerp staat echt de subnavigatie...

**Comment by tfrijsewijk** [comment]
Het maakt mij niet uit welke we kiezen, maar voor jouw beeldvorming.. ik vind het niet heel duidelijk:

![image](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/4b131aa9-6a86-4b0f-93e1-ceedfb1cf5fd)

![image](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/eacee745-f3e6-4f3f-b917-0b90db6de6d0)

Maar misschien moeten we de designs van hoofd- en subnavigatie tussen UX en de toolkit nog een keertje ijken.

@LukeVerlaan Kan jij er nog subnavigatie van maken?

**Comment by LukeVerlaan** [comment]
Ik heb alle comments verwerkt en is deployed naar [de site](https://storybook.dso-toolkit.nl/_2254-Viewer-grid-small-screen/?path=/story/core-viewer-grid--viewer-grid)

**Comment by tfrijsewijk** [comment]
@LiesbethVorst @DjangoBlok kunnen jullie nog een keertje hertesten?

Ik vraag mij af of het dialog goed staat:



![Image](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/5ffecc65-a239-4d5d-adfd-5febeb65c9f0)

**Comment by LiesbethVorst** [comment]
De marges moeten inderdaad 16px rondom zijn, dus ook onder en boven. Verder zou de shadow niet zo hard moeten zijn, bijvoorbeeld zoals bij de modal.

**Comment by tfrijsewijk** [comment]
- Overlay en Filterpanel moeten op smalle viewport maximale hoogte pakken en geen margin rondom;
- Overlay en Filterpanel gaan van `dialog` gebruik maken;
- Research naar animatie;

**Comment by tfrijsewijk** [comment]
@hansgrimm Wil jij nog naar "Research naar animatie" kijken? Geen halszaak, het gaat erom of we `dialog` kunnen laten schuiven/animeren.

@DjangoBlok & @LiesbethVorst Verwachtingsmanagement: Deze gaat de release van aanstaande maandag waarschijnlijk niet halen.

**Comment by hansgrimm** [comment]
> 

ja, dat kan (binnen redelijke grenzen); zie https://codepen.io/picturit/pen/gOQRJyq en druk op 'open modal dialog'.

**Comment by hansgrimm** [comment]
> @hansgrimm Wil jij nog naar "Research naar animatie" kijken? Geen halszaak, het gaat erom of we `dialog` kunnen laten schuiven/animeren.
> 
> @DjangoBlok & @LiesbethVorst Verwachtingsmanagement: Deze gaat de release van aanstaande maandag waarschijnlijk niet halen.

ja, dat kan (binnen redelijke grenzen); zie https://codepen.io/picturit/pen/gOQRJyq en druk op 'open modal dialog'.
