### ISSUE TITLE
Banner: Nieuwe variant "info", nieuwe functionaliteit "noIcon" en "compact"

### ISSUE THREAD

**Issue by LiesbethVorst** [dso-toolkit/dso-toolkit#2255]
In de viewer is er behoefte aan het doorlopend tonen van een melding. De huidige alert en de banner zijn net niet geschikt.

### Accepatatiecriteria

- 48px hoog
- rich text, om bijv. toggle tip te kunnen gebruiken
- info blauw / warning geel / alert rood
- optioneel: 
   - icon
   - sluitknop

### Specs

<img width="1085" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/91903058/6d78aa8f-05e3-41a3-aefb-6cb39f028878">

### In VRK:

![Image](https://github.com/dso-toolkit/dso-toolkit/assets/91903058/b77ae1ba-a506-4c3b-8720-bba7a62bcd2c)

**Comment by tfrijsewijk** [comment]
De basis wordt het Banner component. We introduceren daar een informatieve variant. De informatieve variant wordt blauw zoals in het ontwerp. Daarnaast breiden we de API uit met "compact=true". Mag niet sluitbaar zijn.

@LiesbethVorst kijkt het design nog even na met Banner in het achterhoofd.

**Comment by tfrijsewijk** [comment]
@LiesbethVorst gaat dit issue nog een kleine beetje aanvullen.

**Comment by LiesbethVorst** [comment]
Issue aangevuld en op Ready for development gezet.

**Comment by tfrijsewijk** [comment]
@LukeVerlaan kan jij deze oppakken?
