### ISSUE TITLE
Uitloggen button variant is bold in dropdown menu waardoor het een actief menu-item lijkt te representeren. 

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#2268]
In https://github.com/dso-toolkit/dso-toolkit/issues/2163 was het probleem dat wanneer je voor uitloggen een button gebruikt. Deze niet de styling mee kreeg van het menu. 

Dit was opgelost, maar nu het geimplementeerd is door PR02 lijkt alsof de button wel de styling van het menu heeft. Maar deze is altijd bold waar het op een actief menu-item lijkt. (Zie afbeelding) 

<img width="777" alt="Screenshot 2023-08-02 at 11 17 04" src="https://github.com/dso-toolkit/dso-toolkit/assets/36912722/cc891964-4668-444f-b9cc-2f70141355d2">

Deze moet dezelfde styling hebben als de ander onderdelen. 

In issue #2163 stond dat je de juiste versie kon zien als je: " De uitloggen knop is zichtbaar in storybook met controls: Authenticatie: loggedIn & Uitloggen url leegmaken" https://storybook.dso-toolkit.nl/56.1.0/iframe.html?args=authStatus:loggedIn;logoutUrl:&id=core-header--default&viewMode=story 

Hier kun je zien dat ook in storybook de button een bold uiterlijk heeft in het dropdown menu

**Comment by tfrijsewijk** [comment]
@hansgrimm kan jij dit uitzoeken?

**Comment by hansgrimm** [comment]
![Scherm­afbeelding 2023-08-02 om 14 14 10](https://github.com/dso-toolkit/dso-toolkit/assets/506527/7bb2986e-f276-4cf1-aaf0-f10577e4d9a7)
Het feit dat het een `<button>` is, doet 'm de das om. Zodra je er een `<a>` van maakt (net als de andere menu-items) is het weg.

**Comment by hansgrimm** [comment]
![Scherm­afbeelding 2023-08-02 om 14 14 10 kopie](https://github.com/dso-toolkit/dso-toolkit/assets/506527/33966df1-681d-4712-b938-0208b4431462)
Dat is dan kennelijk niet gelukt...

**Comment by hansgrimm** [comment]
![Scherm­afbeelding 2023-08-02 om 14 32 22 kopie](https://github.com/dso-toolkit/dso-toolkit/assets/506527/b23fa488-4445-42e6-8245-69d3aaae3a4b)
In de brede view heeft de button (terecht) een bold. we moeten even een haakje zien te vinden om een uitzondering te forceren, op een nette en gescopete manier.

**Comment by tfrijsewijk** [comment]
Of de huidige styling voor `button` specifieker maken. Ik denk dat die namelijk niet bedoeld is om in het menu te tonen.

**Comment by hansgrimm** [comment]
De tertiary button is van zichzelf niet bold, dus die krijgt hij hier ergens mee. Morgen effe verder speuren.
