### ISSUE TITLE
Button: Element "anchor" :hover/:visited heeft zwarte tekst in Info

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#2270]
Wanneer je op een button hebt geklikt in Info component dan verandert de tekst in de primaire en secundaire button naar zwart. Dit moet voor Primaire knop wit blijven en voor de secundaire knop grasgroen. 

(Gek genoeg gebeurt dit niet in de highlightbox de inhoud van dit component is identiek aan Info. Dus kun je vergelijken en controleren waarom het bij de ene goed gaat en bij de andere fout) 

<img width="1250" alt="Screenshot 2023-08-02 at 12 33 15" src="https://github.com/dso-toolkit/dso-toolkit/assets/36912722/fd3512b5-f001-4510-ae29-62d5efc3132e">

**Comment by hansgrimm** [comment]
anchor seconday hover klopt ook niet. gefixt.
