### ISSUE TITLE
Iconen (status-warning en forbidden) kunnen weergeven ipv bullet in unordered list

### ISSUE THREAD

**Issue by MYpenburg** [dso-toolkit/dso-toolkit#2274]
Hans heeft dit al uitgewerkt in codepen, graag opnemen in toolkit

**Comment by hansgrimm** [comment]
https://codepen.io/picturit/pen/MWzVqBK

**Comment by tfrijsewijk** [comment]
@MYpenburg Luke heeft dit issue opgepakt, maar zijn enige referentie was de codepen van Hans. In jouw ontwerp laat jij een rood forbidden icon zien, maar dat wist Luke niet. Daarnaast hebben we dat icoon niet in de toolkit.

Ik ga dit issue zoals het is mergen, dan moet in de volgende release maar een rood icoon worden aangeleverd/gemaakt.
