### ISSUE TITLE
Tooltip: Ondersteuning voor disabled elementen

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#2281]
Een tooltip die naar een `button[disabled]` verwijst toont niet.

Dit issue kan een research of feature zijn, afhankelijk van wat mogelijk is.

**Comment by tfrijsewijk** [comment]
cc: @tjedrowald (vet: je voornaam als GitHub handle)

**Comment by tfrijsewijk** [comment]
@LukeVerlaan kan jij hier onderzoek naar doen? Laten we samen de conclusie bespreken. Afhankelijk daarvan beslissen we of we in dit issue ondersteuning implementeren.

**Comment by tfrijsewijk** [comment]
@LukeVerlaan Dit issue heb jij in behandeling genomen, kan jij jouw conclusie hierin zetten?

**Comment by LukeVerlaan** [comment]
Ik heb (onder dit issue) aan storybook toegevoegd dat je bij tooltip de buttons kan disablen. Daar toont de tooltip wel, maar dat lijkt "schijn". Want een disabled element emit geen events, dus aanhaken op de "mouseenter", "mouseleave", "focus"en "blur" gaat niet. Ik probeerde er tests voor te schrijven,  maar die gaan niet werken.

Hoe het dan wel mogelijk gemaakt kan worden, heb ik nog geen antwoord voor

**Comment by LukeVerlaan** [comment]
Een idee dat mogelijk kan werken is door een div om de button heen te plaatsen die de events wel uitvoert.

**Comment by hansgrimm** [comment]
Waar gaat het over hier? Wat wordt er ge-disabled?

**Comment by tfrijsewijk** [comment]
Een button met tooltip:

```html
<button type="button" class="primary" aria-describedby="mijn-tooltip" disabled>
  <span>Klik</span>
</button>
<dso-tooltip id="mijn-tooltip">Klak</dso-tooltip>
```

De tooltip toont niet. We willen dat wel. Hoe kunnen we dat doen?

**Comment by hansgrimm** [comment]
Ja maar wacht eventjes.. als ik het goed begrijp is de button die de tooltip moet aftrappen disabled. Dan is het toch logisch dat er niks gebeurt?

**Comment by hansgrimm** [comment]
Als je dat toch met alle geweld wil, is dit misschien een manier: https://accessibleweb.com/question-answer/how-can-i-make-a-disabled-button-clickable-focusable-in-general-interact-able/

**Comment by tfrijsewijk** [comment]
> Ja maar wacht eventjes.. als ik het goed begrijp is de button die de tooltip moet aftrappen disabled. Dan is het toch logisch dat er niks gebeurt?

Dat is inderdaad de oorsprong van dit issue ;-) We stellen de logica ook niet ter discusie, we zoeken een oplossing dat we tooltips bij disabled buttons kunnen tonen. We willen namelijk een toelichting bij de disabled state kunnen geven.

> Als je dat toch met alle geweld wil, is dit misschien een manier: https://accessibleweb.com/question-answer/how-can-i-make-a-disabled-button-clickable-focusable-in-general-interact-able/

Tsja, geen gek idee natuurlijk.. Maar dan moeten afnemers inderdaad meer werk doen. Want de click moet ook echt niet gebeuren. Met deze manier is de button ook focusable waarmee de tooltip ook onfocus toont.

Maar echt dolenthousiast worden we er ook niet echt van.. Nog maar even met de UX-er praten.

@LukeVerlaan @hansgrimm dank voor de input!

**Comment by hansgrimm** [comment]
@tfrijsewijk we moeten sowieso zorgen dat de disabled button focus kan krijgen. Dat kan met die `aria-disabled`, want die dicteert geen browsergedrag. We kunnen de disabled styling aan dat attribuut ophangen.

**Comment by tfrijsewijk** [comment]
> @tfrijsewijk we moeten sowieso zorgen dat de disabled button focus kan krijgen. Dat kan met die `aria-disabled`, want die dicteert geen browsergedrag. We kunnen de disabled styling aan dat attribuut ophangen.

Ja, ik begrijp 'm. Waar ik mee zit is dat 'n afnemer de click moet afvangen (en dus op twee plekken de in de weer is met de disabled state: in de code en in de templates).

Toch even voortboorduren op het idee van Luke..

```html
<span tabindex="0" aria-describedby="f5bc1c2a-72f1-4e66-b2d4-cce7518213a8">
  <button type="button" class="dso-primary" disabled>
    <span>Klik</span>
  </button>
</span>
<dso-tooltip id="f5bc1c2a-72f1-4e66-b2d4-cce7518213a8">
  Klak
</dso-tooltip>
```

* De button heeft een `disabled` state (en styling uiteraard);
* De `aria-describedby` staat niet op de button maar op de wrapping span;
* De wrapping span heeft een `tabindex=0` zodat het element ook focusbaar is;

![image](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/a455afbb-427a-4bd0-8876-6a7cb9d5b853)

Deze styling kunnen we natuurlijk verfijnen, maar laten we eerst bepalen of dit een goede oplossing is.

@hansgrimm Wat denk jij?

**Comment by hansgrimm** [comment]
Wat ik denk is dat dit een goed moment is om @timveld er bij te sleuren :)

**Comment by tfrijsewijk** [comment]
Er zijn technische oplossingen mogelijk, maar daar missen we eigenlijk een cruciale Web Component implementatie van Button voor. We willen voorkomen dat we in Tooltip achtige situaties terechtkomen waar de documentatie groter en onderhoudsrijker is dan de daadwerkelijke markupvoorschriften.

Daarnaast is Team UX niet enthousiast over interactie op disabled buttons.

Tijdens de UX meeting op dinsdag 19 september is besloten dat @DjangoBlok contact opneemt met @tjedrowald om naar een alternatieve werkvorm te kijken.
