### ISSUE TITLE
Example Pages: Update steps markup

### ISSUE THREAD

**Issue by MYpenburg** [dso-toolkit/dso-toolkit#2282]
Er was een WCAG issue omtrent de genummerde bolletjes in de stepcounter. Thomas had daar een idee over, dat is geimplementeerd door Wido en getest door Tim. Thomas' idee is niet 100% gevolgd, zie screenshot van de conversatie tussen Tim en Wido (PR12). 

De taak van deze issue is om de voorbeeldpagina in Storybook ook aan te passen met deze aangepaste markup.
https://storybook.dso-toolkit.nl/56.1.0/?path=/story/voorbeeldpagina-s-toepassingen-aanvragen-landingspagina--landingspagina. 

![image](https://github.com/dso-toolkit/dso-toolkit/assets/7289928/5a533a7e-0069-492f-b407-d956439b5ac8)

**Comment by tfrijsewijk** [comment]
Ik ben mijn idee vergeten eigenlijk, kan iemand dat nog aanvullen?

**Comment by MYpenburg** [comment]
<img width="997" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/7289928/2a0d807f-833e-4da3-8d61-6b0f202ee125">

**Comment by MYpenburg** [comment]
![image](https://github.com/dso-toolkit/dso-toolkit/assets/7289928/5fb6985c-9073-4311-9cf8-24653a341a0d)

**Comment by tfrijsewijk** [comment]
Ohja dat idee.

Maar ik begrijp niet wat ik lees.

- De bevinding was dat het nummer niet werd opgelezen in relatie tot de titel. Het nummer staat immers buiten de `h3.
- Mijn suggestie was om de `div.row/div.col-xxx` te vervangen met `ol.row/li.col-xxx` zodat het nummer bij de list-items wordt belegd. Om te voorkomen dat het nummer dubbel wordt voorgelezen had ik bedacht om `.dso-step-counter` van `aria-hidden="true"` te voorzien.
- Mijn idee is kennelijk niet helemaal gevolgd (de afwijkingen zijn mij niet geheel duidelijk). Voor zover ik kan zien is er geen `ol/li` gemaakt maar is er wel `aria-hidden="true"` gezet. Natuurlijk wordt er dan helemaal nergens 'n nummer voorgelezen.
- De opvolgende bevinding is dat het bijna werkt, alleen moet de `aria-hidden="true"` eraf gehaald worden.

Het lijkt erop alsof we nu bij dezelfde markup terecht zijn gekomen. Alleen komt het nu wel door de test?

Mis ik iets?

@timveld kan jij hier wat over zeggen?

**Comment by MYpenburg** [comment]
Het screenshot is van onze oude code. Ik weet niet hoe die er nu uitziet. @timveld weet jij dit wel? Jij hebt de hertest gedaan met Wido.

**Comment by timveld** [comment]
Het gaat er om dat de 5 stappen in een lijst staan, zodat NVDA aangeeft dat er een lijst met 5 items is.
De relatie tussen titel en nummer volgt uit het feit dat ze in hetzelfde listitem staan, aanvankelijk was inderdaad het idee het nummer (ook) in de h3 te zetten maar dat is bij nader inzien geen goed idee.

Of het nummer door de browser wordt gezet (doordat hij een ordered list rendert) of door jullie in een div wordt toegevoegd, maakt niet uit. Eerste is code-technisch wellicht eleganter maar waarschijnlijk moeilijk om dan de gewenste layout te krijgen.

In de eerste werkende versie die Wido me voorlegde hoorde ik wel een lijst met 5 items, maar helemaal geen nummers. Daarom heb ik aangegeven dat de aria-hidden weg moest.

De oplossing met aria-hidden op het nummer zou prima zijn als het nummer sr-only voor de titel stond, maar lijkt me onnodig ingewikkeld. Als je de div moet zetten, laat dan maar gewoon voorlezen.

Kortom: de tweede oplossing die Wido me heeft voorgelegd (staat nog niet op int dus code eventueel bij Wido opvragen) is wat mij betreft prima, ik zou gezien de drukte geen tijd meer stoppen in een code-technisch elegantere oplossing.

Als de oplossing live staat, zal ik hem vast aan Accessibility voorleggen zodat we het zo snel mogelijk weten als ze nog niet tevreden zijn.

**Comment by tfrijsewijk** [comment]
> In de eerste werkende versie die Wido me voorlegde hoorde ik wel een lijst met 5 items, maar helemaal geen nummers. Daarom heb ik aangegeven dat de aria-hidden weg moest.

Waarom hoorde je geen nummers? Een `ol/li` wordt door VoiceOver voorgelezen als

"list 3 items. 1: Aanvragen, 1 of 3. 2: Checken, 2 of 3. 3: Afronden, 3 of 3. end of list".

Ik ben bang dat als we ook een nummer in de `li` plaatsen dat er screen readers zijn die dubbel gaan voorlezen: Zowel het native nummer van `li` als het nummer wat wij in de `li` zetten.

https://pqina.nl/blog/what-do-html-elements-sound-like/#what-does-a-list-sound-like%3F

**Comment by hansgrimm** [comment]
@timveld kan jij a.s. dinsdag rond 11:00 in Utrecht zijn? dan kunnen we op jouw machine even naar je bevindingen tot nu toe kijken, want het is mij een beetje onduidelijk hoe de boel er nu bij staat ;)

**Comment by hansgrimm** [comment]
zie https://int12.omgevingswet.overheid.nl/checken - werkt als een speer
@tfrijsewijk issue is opgelost, kan dicht

**Comment by tfrijsewijk** [comment]
@hansgrimm zijn jullie er nog achtergekomen hoe dat zit met `<ol>` en de list item nummers? Als ik nu in de AOM kijk zie ik geen nummer bij de list items, en het nummer van de Card staat niet in de titel. Gaat dat goed?

**Comment by hansgrimm** [comment]
Om deze om te bouwen heb ik nog wel wat ondersteuning nodig.

**Comment by MYpenburg** [comment]
Code was er op prod en is gesloopt door PR12. Wordt teruggedraaid in https://jira.team-dso.nl/jira/browse/PR12-22355. Als die gedaan is, dan de markup kopiëren in de voorbeeldpagina's

**Comment by tfrijsewijk** [comment]
Anders staat het tenminste op acc

**Comment by tfrijsewijk** [comment]
Ik ben eruit.

De Highlight Box is ingezet om een reeks aan stappen te tonen. Deze stappen hebben een nummer (dat kan, met Highlight Box). De bevinding is dat er een reeks werd gevisualiseerd, maar dat dit niet door AT kon worden opgepakt.

De opbouw was grofweg:

```html
<div class="row">
  <div class="col">
    <dso-highlight-box step="1"></dso-highlight-box>
  </div>
  <div class="col">
    <dso-highlight-box step="2"></dso-highlight-box>
  </div>
  <div class="col">
    <dso-highlight-box step="3"></dso-highlight-box>
  </div>
  <div class="col">
    <dso-highlight-box step="4"></dso-highlight-box>
  </div>
</div>
```

Ik heb de volgende suggestie gedaan:

```html
<ol class="row">
  <li class="col">
    <dso-highlight-box step="1"></dso-highlight-box>
  </li>
  <li class="col">
    <dso-highlight-box step="2"></dso-highlight-box>
  </li>
  <li class="col">
    <dso-highlight-box step="3"></dso-highlight-box>
  </li>
  <li class="col">
    <dso-highlight-box step="4"></dso-highlight-box>
  </li>
</ol>
```

Hoe dit is goedgekomen met de styling weet ik niet, maar dit is geimplementeerd door PR12, zie bijvoorbeeld hier: https://acc.omgevingswet.overheid.nl/checken onder het kopje "De stappen".

Deze opzet is getest en goed bevonden.

In dit issue gaan we mijn suggestie terugzetten naar de voorbeeldpagina's in de DSO Toolkit Storybook. Wij tonen een soortgelijke situatie op 3 plekken:

![image](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/127f8ca0-dbd4-4652-98c8-dbdc70f8381a)

In deze voorbeeldpagina's gaan we de `div.row` omzetten naar `ol.row` en de `div.col-xxx-xxx` naar `li.col-xxx-xxx`.

Dan zullen we er ook achterkomen waar de list item numbers zijn gebleven, want dat is mij nog niet helemaal duidelijk waar die zijn gebleven (en door wie ze worden weggestijld).

Mochten die list item numbers in onze voorbeeldpagina's zichbaar zijn, dan moeten we even nadenken hoe we die gaan verbergen.
