### ISSUE TITLE
Header: i n c r e a s e d - l e t t e r s p a c i n g - i s s u e

### ISSUE THREAD

**Issue by timveld** [dso-toolkit/dso-toolkit#2283]
### Waar

core / header - default en with sub logo

### Aanleiding

In de stelselcatalogus treden bij de navigatiebalk twee problemen op:
1. Bij een schermresolutie van 1024X768 en zoom 125% verschijnt het 'meer' knopje, klik je daar op dan klapt het links buiten beeld uit.
2. Volgens stichting accessibility wordt succescriterium 1.4.12 text spacing niet behaald. Als je met viewport 1024X768 met zoom 100% in de inspector CSS property ‘letter-spacing: 1em;’ opgeeft, valt het laatste item "over de catalogus" deels buiten beeld. We betwijfelen overigens of dit de juiste testmethode is, want als deze property aanwezig is bij het (re-)renderen van de pagina (en dat zal buiten een testsituatie altijd het geval zijn) dan past de pagina zich keurig aan, maar we gaan Accessibility daarvan waarschijnlijk niet overtuigen.

Opmerking: problemen treden in de toolkit voorbeelden niet op, omdat daar minder / kortere links in de navigatiebalk staan.

Na uitgebreide bespreking met @hansgrimm tot de conclusie gekomen dat we in ieder geval punt 2 kunnen oplossen door mogelijk te maken dat de navigatiebalk bij ruimtegebrek hoger wordt, zodat de laatste link onder de eerste komt. Mocht deze voorkeursoplossing niet mogelijk blijken dan kunnen we ook zorgen dat langere links bij ruimtegebrek ingekort worden (met ellipsis), dat is toegestaan zo lang de volledige tekst te lezen is op de pagina waarnaar gelinkt wordt.

De bedoeling is dat het bestaande gedrag bij wijziging van viewport gehandhaafd blijft: bij ruimtegebrek zal worden overgegaan naar de layout met het 'meer' knopje. Ofwel, hoogstwaarschijnlijk zal geen enkele gebruiker de over twee regels verdeelde navigatiebalk te zien krijgen. De enige die hem gaan zien zijn de testers van Accessibility. Waar we onze ontwikkeltijd al niet in stoppen ;-(

Wat betreft punt 1: we moeten garanderen dat de uitklapper van het meer knopje altijd op de juiste plaats komt. Misschien helpt het al als de navigatiebalk in de hoogte mag groeien, anders moet hier nog een aanvullende oplossing voor komen.

### Testcondities

Voor acceptatie goed controleren dat:
1. Bij de door Accessibility gebruikte testmethode van succescriterium 1.4.12 geen tekst buiten beeld valt of andere afwijkingen optreden.
2. Goed nagaan of de uitklapper onder het 'meer' knopje niet buiten beeld kan vallen.
### Gebruikersimpact
Kritiek: gebruikers die het eerstgenoemde probleem ervaren zien de links onder het meer knopje niet en kunnen ze niet / heel moeilijk activeren.

**Comment by hansgrimm** [comment]
Oplossingsrichting: op `.dso-nav.dso-nav-main.sc-dso-header` de property `flex-wrap: wrap` zetten, die kan dit oplossen. Wel het risico op onverwachte complicaties.

**Comment by tfrijsewijk** [comment]
@hansgrimm Wat gaan we met dit issue doen?

**Comment by hansgrimm** [comment]
Heel kort: niks. deze gaat na de meeting met Stichting Accessibility de prullebak in.

**Comment by tfrijsewijk** [comment]
Klinkt goed.

**Comment by hansgrimm** [comment]
Net 1 dag te vroeg 😎

**Comment by hansgrimm** [comment]
Thank you! 🙏

**Comment by hansgrimm** [comment]
Het Utrechts Orakel heeft gesproken:

"Hi Sander,
Over de afgekeurde bevinding onder 1.4.12, op de site: https://stelselcatalogus.dmo.omgevingswet.overheid.nl/home:
Uit een relaas met onderzoekers:
“Ja technisch gezien is dit een afkeur, zie ook het voorbeeld bij Deque: https://dequeuniversity.com/resources/wcag2.1/1.4.12-text-spacing 1.4.12 Text Spacing | New Success Criteria in WCAG 2.1
Er staat ook onder wat de dev kan doen.”
“Ik persoonlijk heb er meer moeite mee als tekst overlapt of het contrast slecht is, maar wat dit doet is dat het voor mensen rommelig en druk kan overkomen en dat kan voor mensen met een cognitieve beperking een belemmering zijn.”
“Ja, het ding is. Het succes criterium zegt niks over de specifieke methode. Sommige gebruikers zullen een bookmarklet gebruiken om dit soms te veranderen, net zoals wij.
Dus het is alsnog een afkeur.”
“Ik denk dat we dit nog steeds hard kunnen afkeuren op het feit dat tekst buiten de kaders komt als de gebruiker de tekstwaarden instelt zoals het SC suggereert.
Want wat de gebruiker vervolgens zelf doet, dus schermbreedte gaat aanpassen of andere instellingen aanpast en het dan wel goed, is geen duidelijk argument.”
Het gaat hier dus met name om dat de wijze waarom wij testen/onderzoeken:
Bookmarklet aanzetten om tekst beter te lezen, kan een gebruiker een ook doen en dan valt de tekst buiten beeld.
Ik hoop dat we het zo duidelijk hebben verwoord.
Als je vragen hebt hoor ik het graag."

m.a.w.: deze issue moet gefixt worden: het JS dat regelt dat de headerlinks al dan niet met een 'meer'-knopje worden getooid, moet (ook) aftrappen als de letter-spacing aangepast wordt dmv de bookmarklet/extensie.

**Comment by tfrijsewijk** [comment]
Dit issie is niet meer van toepassing: De testmethode blijkt niet representatief te zijn. Dit item is van de lijst afgehaald, als dit wordt getest zoals de eindgebruiker de applicatie gebruikt is de bevinding niet te reproduceren.
