### ISSUE TITLE
List Button: Trefwoorden worden niet voorgelezen als onderdeel van het resultaat/werkzaamheid.

### ISSUE THREAD

**Issue by MYpenburg** [dso-toolkit/dso-toolkit#2294]
Melding van onze tester, https://jira.team-dso.nl/jira/browse/PR12-19116

Ditzelfde geldt voor Activiteiten met subcontent (Bevat: ...) (en subactiviteiten)

Geschetste oplossing van @timveld : aria-describedby. Tim wil deze testen voor release

**Comment by tfrijsewijk** [comment]
@MYpenburg Wil jij het issue aanvullen met informatie uit het ticket? Wij kunnen niet bij dat project.

**Comment by MYpenburg** [comment]
<img width="1026" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/7289928/d39ce061-9425-4a58-bdaf-c9a5c51c4e68">

**Comment by hansgrimm** [comment]
`aria-describedby` toevoegen

**Comment by hansgrimm** [comment]
dit is wat er nu gebeurt in NVDA: je moet eerst langs allerlei andere controls om uiteindelijk op e goede plek te belanden. Hoe te fixen: above my pay grade :)
![Scherm­afbeelding 2023-09-20 om 16 16 34](https://github.com/dso-toolkit/dso-toolkit/assets/506527/d3b05353-52f5-49f9-b84f-37f59117a1a2)

**Comment by tfrijsewijk** [comment]
En wat stel je dan voor?

**Comment by hansgrimm** [comment]
Ik spreek @MYpenburg vanmiddag, we hebben het er wel even over

**Comment by hansgrimm** [comment]
En misschien heeft @timveld hier ook nog een mening over.

**Comment by tfrijsewijk** [comment]
Ok. Ik merkte bij @MYpenburg 'n lichte vorm van urgentie, maar ik heb 't gevoel dat de doorlooptijd van dit issue daar niet aan voldoet. Martin, kan jij hier wat over zeggen?

**Comment by MYpenburg** [comment]
In het screenshot van Hans zou ik overal waar nu "{naam van de werkzaamheid}" staat willen horen: "{naam van de werkzaamheid} trefwoorden {trefwoorden}". In termen van listbutton: "{titel} trefwoorden {trefwoorden}"

**Comment by MYpenburg** [comment]
<img width="1155" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/7289928/c8de7593-5641-4a7c-a16e-e89788355ae8">

**Comment by tfrijsewijk** [comment]
@hansgrimm Kan jij naar deze kijken?

**Comment by hansgrimm** [comment]
Ik vraag me af of dit in het component zelf moet worden geregeld. In de implementatie is het een en ander al toegevoegd om de `subcontent` aan te passen:
![Scherm­afbeelding 2023-10-16 om 12 07 33](https://github.com/dso-toolkit/dso-toolkit/assets/506527/da4f44a1-5261-408d-bb3a-6c1f7e07486c)
Er zit zelfs al een `id` op de `subcontent`, dus volgens mij is het enige dat nog moet gebeuren: het `label` moet een `aria-describedby` attribuut krijgen met als value het `id` van de `subcontent`. Volgens mij zit die actie bij PR12; correct me if I'm wrong.
Nog een paar aandachtspuntjes:
- Het zou elegant zijn als achter 'trefwoorden' een ':' komt. 
- let op: een `mark` gebruiken om delen van een trefwoord te benadrukken is heel mooi, maar kan resulteren in het voorlezen als los(se) woord(en).
@MYpenburg @tfrijsewijk

**Comment by hansgrimm** [comment]
@MYpenburg Ben jij alweer op de barricaden?

**Comment by MYpenburg** [comment]
: achter trefwoorden heb ik in overleg met Tim weggelaten (omdat je anders ook "dubbele punt" moet uitluisteren voordat je relevante info krijgt)
Als die <mark> een (mogelijk) WCAG probleem oplevert dan moeten we dat sowieso fixen, maar tot nu toe heeft het alle zelfevaluaties en audits doorstaan. Kan jij dit kortsluiten met @timveld ?

**Comment by MYpenburg** [comment]
Na overleg met PR12 (31 okt) wordt dit binnen de toolkit opgelost.

**Comment by tfrijsewijk** [comment]
Het label element wordt beschreven door 'n element in een light DOM. Hierdoor werkt de traditionele aria-describedby niet. We staan aan de vooravond van de oplossing, maar alleen Safari heeft nog ondersteuning. Dit is straks voor iedereen beschikbaar, Stencil heeft er ook al een API voor gemaakt.

Wat we specifiek zoeken is `ariaDescribedByElements`. Met de ariaXxxElements properties is het mogelijk om twee elementen scriptend met elkaar te linken. En dat gaat cross-DOM.

Maar zolang dat niet kan zullen we iets anders moeten bedenken.

Zou de volgende markup werken?

```html
<dso-list-button label="Milieubelastende activiteit - Melding" count="5" min="0" max="99" class="hydrated">
  # shadow-root
  | <div class="dso-button-group">
  |  <div class="dso-list-button dso-selected">
  |    <div class="dso-selectable">
  |      <input id="dso-list-button-checkbox" type="checkbox" value="list-button" name="naam" aria-describedby="thomas">
  |        <label for="dso-list-button-checkbox" aria-describedby="description">
  |          Milieubelastende activiteit - Melding
  |        </label>
  |      <p aria-hidden="true" class="sr-only" id="description">Hier <strong>staan</strong> termen</p>
  |      <!-- ^ Inhoud uit light DOM slot="subcontent" is gedupliceerd. Met aria-hidden verstopt voor AOM en met class="sr-only" visueel verstopt. -->
  |    </div>
  |    <slot name="subcontent"></slot>
  | </div>
  <div slot="subcontent">Hier <strong>staan</strong> termen</div>
</dso-list-button>
```

Los van hoe ik dit technisch zou bouwen: Zou dit werken? @hansgrimm

**Comment by hansgrimm** [comment]
Volgens mij wordt nu de `describedby` teniet gedaan door de `aria-hidden`, maar dit is voor mij 'virgin territory'. als ik een plek heb om dat met NVDA te checken doe ik dat met alle soorten van genoegen ;)
NB: je hebt in je voorbeeld je id's verhaspeld: 'thomas' vs 'description', of mis ik wat?

**Comment by timveld** [comment]
@tfrijsewijk Ik heb een [pennetje](https://codepen.io/timveld/pen/bGzgQzW) van je codefragment gemaakt. 
Je oplossing werkt op het selectievakje, op de list button kan ik hem niet testen maar waarschijnlijk ook. 
'Hier staan termen' wordt als beschrijving van het selectievakje voorgelezen en niet dubbel gelezen bij lezen met de virtuele focus. 

Echter, in je oorspronkelijke code stond op de checkbox aria-describedby="thomas" en op het label aria-labeledby="description". 
Aria-describedby op het label doet niets, hij moet op het element zelf staan. Ik weet niet wat je bedoelde met de niet bestaande ID "Thomas", maar als je op de checkbox zou zetten aria-describedby="Thomas description" dan worden beide teksten als beschrijving voorgelezen.

**Comment by hansgrimm** [comment]
wow, die aria hidden wordt toch 'gezien' door NVDA. ja, dan zou dit moeten werken.
testcase: https://codepen.io/picturit/pen/vYbgzoW/f05366c2decd9fd463cf7086dd8a8c61

**Comment by hansgrimm** [comment]
^^ wel kans op dubbel voorlezen: 1 x op focus, en nog een keer bij arrow down

**Comment by tfrijsewijk** [comment]
Sorry, ik heb mijn markup bijgewerkt. `aria-describedby` staat op het input element.

**Comment by iterox** [comment]
@timveld Zou de fix voor dit issue willen beoordelen?

Zie onderstaande link: 
https://storybook.dso-toolkit.nl/_2294-ListButton-Trefwoorden-worden-niet-voorgelezen-als-onderdeel-van-het-resultaat-werkzaamheid/iframe.html?args=subcontent:zoekterm;subcontentPrefix:Trefwoorden&id=core-list-button--single-select&viewMode=story

**Comment by timveld** [comment]
De tweede regel heeft de vorm
```<div aria-hidden="true" class="sr-only">Trefwoorden:<div>Zoekterm</div></div>```
Daaraan moeten twee dingen anders:
* aria-hidden is hier niet gewenst. Kennelijk toegevoegd om dubbel voorlezen te voorkomen maar het effect is dat iemand die met de virtuele focus leest de regel niet meekrijgt, dat is niet de bedoeling. 
* Effect van een <div> binnen een <div> is dat bij lezen met de virtuele focus een regelafbreking wordt ingevoegd. Bovendien lijkt me de sr-only class op de buitenste div niet de juiste plek, het gaat in de praktijk goed maar valt die binnenste div nu wel of niet onder deze class? 
Kortom zou ervan maken 
```<div><span class="sr-only">Trefwoorden: </span><span>Zoekterm</span></div>

**Comment by iterox** [comment]
> De tweede regel heeft de vorm `<div aria-hidden="true" class="sr-only">Trefwoorden:<div>Zoekterm</div></div>` Daaraan moeten twee dingen anders:
> 
> * aria-hidden is hier niet gewenst. Kennelijk toegevoegd om dubbel voorlezen te voorkomen maar het effect is dat iemand die met de virtuele focus leest de regel niet meekrijgt, dat is niet de bedoeling.
> * Effect van een div binnen een div is dat bij lezen met de virtuele focus een regelafbreking wordt ingevoegd. Bovendien lijkt me de sr-only class op de buitenste div niet de juiste plek, het gaat in de praktijk goed maar valt die binnenste div nu wel of niet onder deze class?
>   Kortom zou ervan maken

Werd je plotseling weggeroepen @timveld? Want je wilde er nog iets bij zetten, maar het is nog niet te lezen.

**Comment by timveld** [comment]
@iterox  laatste regel was weggevallen door een tikfout, aangepast

**Comment by iterox** [comment]
> De tweede regel heeft de vorm `<div aria-hidden="true" class="sr-only">Trefwoorden:<div>Zoekterm</div></div>` Daaraan moeten twee dingen anders:
> 
> * aria-hidden is hier niet gewenst. Kennelijk toegevoegd om dubbel voorlezen te voorkomen maar het effect is dat iemand die met de virtuele focus leest de regel niet meekrijgt, dat is niet de bedoeling.
> * Effect van een div binnen een div is dat bij lezen met de virtuele focus een regelafbreking wordt ingevoegd. Bovendien lijkt me de sr-only class op de buitenste div niet de juiste plek, het gaat in de praktijk goed maar valt die binnenste div nu wel of niet onder deze class?
>   Kortom zou ervan maken
>   `<div><span class="sr-only">Trefwoorden: </span><span>Zoekterm</span></div>`

Buitenste div met sr-only zorgt ervoor dat e.e.a. juiste niet getoond wordt aan een visueel ingestelde gebruiker, dus daarom zit ie daar. Wat ik niet goed begrijp is zorgt het feit dat de sr-only op die buitenste div ervoor dat e.e.a. niet goed accessible is cq. verkeerd of niet wordt voorgelezen? 

Denk wel dat de span om de zoekterm een div moet blijven omdat er door de afnemers HTML op die plek geïnjecteerd kan worden.

Wat is lezen met virtuele focus?

**Comment by iterox** [comment]
@timveld Kunnen we hier even over gaan sparren?

**Comment by timveld** [comment]
@iterox  
> "Buitenste div met sr-only zorgt ervoor dat e.e.a. juiste niet getoond wordt aan een visueel ingestelde gebruiker, dus daarom zit ie daar. Wat ik niet goed begrijp is zorgt het feit dat de sr-only op die buitenste div ervoor dat e.e.a. niet goed accessible is cq. verkeerd of niet wordt voorgelezen?"
	Visueel is alleen "trefwoorden: " verborgen. In dezelfde div staat echter ook "zoekterm", die is wel zichtbaar. Voor de screen reader maakt dit niet uit maar ik vind het code-technisch vreemd dat binnen een sr-only div een andere div staat die wel zichtbaar is en moet zijn.  	
> "Denk wel dat de span om de zoekterm een div moet blijven omdat er door de afnemers HTML op die plek geïnjecteerd kan worden."
	De regelafbreking is niet ideaal maar wel aanvaardbaar, en ik ben met je eens dat html in een <span> laten injecteren problematisch is. Dit punt kunnen we dus laten vallen. 
> "Wat is lezen met virtuele focus?"
	Tijd voor een kleine screen reader cursus ;-) Ik zal je laten zien / horen waarom precies maar de aria-hidden moet er in dit geval echt af gehaald worden.

**Comment by tfrijsewijk** [comment]
@timveld Je hebt gelijk, er klopt iets niet. 

Maar ik denk dat alleen `aria-hidden="true"` weghalen ervoor zorgt dat we onderdelen dubbel voorlezen. Het subcontentSlot is namelijk ook onderdeel van het DOM. Wellicht is mijn zorg onterecht, maar ik heb het volgende bedacht.

Zie de twee commentaren in de volgende markup.

```html
<dso-list-button label="Milieubelastende activiteit - Melding" count="5" min="0" max="99" class="hydrated">
  # shadow-root
  | <div class="dso-button-group">
  |  <div class="dso-list-button dso-selected">
  |    <div class="dso-selectable">
  |      <input id="dso-list-button-checkbox" type="checkbox" value="list-button" name="naam" aria-describedby="description">
  |      <label for="dso-list-button-checkbox">
  |        Milieubelastende activiteit - Melding
  |      </label>
  |      <div class="sr-only" id="description"> <!-- aria-hidden="true" is weggehaald -->
  |        <p>Hier <strong>staan</strong> termen</p>
  |      </div>
  |    </div>
  |    <slot name="subcontent"></slot>
  | </div>
  <p slot="subcontent" aria-hidden="true">Hier <strong>staan</strong> termen</p> <!-- Hier aria-hidden="true" toegevoegd -->
</dso-list-button>
```

De AOM voor `<input type="checkbox">` ziet er dan zo uit:

<img width="458" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/9696261/5c7375bb-5919-4379-8ed7-5c659e4b3dc3">

Je kan het hier zien: https://storybook.dso-toolkit.nl/_2294-ListButton-Trefwoorden-worden-niet-voorgelezen-als-onderdeel-van-het-resultaat-werkzaamheid/?path=/story/core-list-button--single-select.

Bij "Controls" instellen:
* subcontentPrefix: `Trefwoorden:`
* subcontent: `Fiets, konijn, stoel, <strong>groen</strong>`

@iterox: Bovenstaande suggestie kan je zien op de commit https://github.com/dso-toolkit/dso-toolkit/commit/34a8d3e350784bce4970042dfaa2fb4a19a5f98c

**Comment by timveld** [comment]
Het gedrag van je fix is goed. 

Maar ik denk dat je vrees voor dubbel voorlezen ongegrond is. In dit [voorbeeld van de slot constructie](https://codepen.io/web-dot-dev/pen/dyqbYme) wordt in ieder geval niets dubbel voorgelezen. Ik heb getest of met aria-describedby kan worden verwezen naar een paragraaf binnen een <star-rating> en dat is het geval. Kortom de herhaalde tekst en aria-hidden / sr-only kunnen er vrijwel zeker uit. 

Overigens ontdekte ik bij het spelen met je fix nog iets: als ik de control 'sublabel' invul verschijnt het sublabel, maar lijkt het niet met aria-describedby gekoppeld te zijn. Als de checkbox zowel subcontent als sublabel heeft moet er ```aria-describedby="id_subcontent id_sublabel"``` op staan, als het goed is worden beiden dan voorgelezen gescheiden door een spatie. Zal ik controleren als je het gedaan hebt.

**Comment by tfrijsewijk** [comment]
> Maar ik denk dat je vrees voor dubbel voorlezen ongegrond is. In dit [voorbeeld van de slot constructie](https://codepen.io/web-dot-dev/pen/dyqbYme) wordt in ieder geval niets dubbel voorgelezen.

Het voorbeeld wat je aanhaalt is niet representatief:

Het Web Component `<star-rating>` heeft één named slot "star-rating-legend". De paragraaf die als slottable node wordt meegegeven (`<p>Is this text visible?</p>`) wordt niet getoond omdat het Web Component geen unnamed slot heeft. Dit zorgt ervoor dat het element niet wordt gerendered, en daarom niet zichtbaar is.

> Ik heb getest of met aria-describedby kan worden verwezen naar een paragraaf binnen een ```<star-rating>``` en dat is het geval. 

Kan je dit verder toelichten?

> Kortom de herhaalde tekst en aria-hidden / sr-only kunnen er vrijwel zeker uit. 

Als ik dat doe ziet het er visueel zo uit:

![image](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/2b907f19-337d-4c19-8c3c-aea98992218d)

`<dso-list-button>` heeft een named slot "subcontent" (`<slot name="subcontent">`) en wordt aangeroepen met een named slottable node voor "subcontent" (`<span slot="subcontent">`).

De span wordt dus gerendered. Maar omdat het niet mogelijk is om verwijzingen door een DOM boundary heen te maken, kopieren wij `<span slot="subcontent">` en renderen die in de Shadow DOM om er vervolgens naar te verwijzen.

Dus dezelfde content is twee keer aanwezig: Eén keer voor het visuele aspect, en één keer voor toegankelijkheid. Het lijkt mij dat we dus met `aria-hidden="true"` en `.sr-only` de content voor de juiste doelgroepen moeten selecteren.

> Overigens ontdekte ik bij het spelen met je fix nog iets: als ik de control 'sublabel' invul verschijnt het sublabel, maar lijkt het niet met aria-describedby gekoppeld te zijn. Als de checkbox zowel subcontent als sublabel heeft moet er ```aria-describedby="id_subcontent id_sublabel"``` op staan, als het goed is worden beiden dan voorgelezen gescheiden door een spatie. Zal ik controleren als je het gedaan hebt.

Ok, voegen we die ook toe. In het DOM komt sublabel eerst, daarna subcontent. Is het verstandig om dezelfde volgorde in `aria-describedby` aan te houden?

**Comment by timveld** [comment]
@tfrijsewijk  ik begrijp niet helemaal waarom (ligt aan mijn kennisgebrek op dit punt) maar als het echt nodig is de content te herhalen, is je oplossing goed -> kan zo de release in.

> Ok, voegen we die ook toe. In het DOM komt sublabel eerst, daarna subcontent. Is het verstandig om dezelfde volgorde in aria-describedby aan te houden?

Lijkt me wel, visueel staat het label ook boven de content.  

Wil dit als gezegd voor de release wel even testen, niet helemaal zeker of het goed gaat.

**Comment by tfrijsewijk** [comment]
> @tfrijsewijk ik begrijp niet helemaal waarom (ligt aan mijn kennisgebrek op dit punt) maar als het echt nodig is de content te herhalen, is je oplossing goed -> kan zo de release in.
> 
> > Ok, voegen we die ook toe. In het DOM komt sublabel eerst, daarna subcontent. Is het verstandig om dezelfde volgorde in aria-describedby aan te houden?
> 
> Lijkt me wel, visueel staat het label ook boven de content.

Jouw suggestie van 16 januari had eerst subcontent en daarna sublabel, dus omgekeerd.

> Wil dit als gezegd voor de release wel even testen, niet helemaal zeker of het goed gaat.

Check, ik maak 'm vanavond af en wil morgenavond de release uitbrengen. Ben jij morgen in de gelegenheid om te testen?

**Comment by timveld** [comment]
Heb label en content waarschijnlijk door elkaar gehaald. 

Zal vanavond / morgenochtend even testen

**Comment by tfrijsewijk** [comment]
@timveld Zie branch deploy op dso-toolkit.nl: https://storybook.dso-toolkit.nl/_2294-ListButton-Trefwoorden-worden-niet-voorgelezen-als-onderdeel-van-het-resultaat-werkzaamheid/?path=/story/core-list-button--single-select&args=sublabel:Sublabel;subcontent:Dit+zijn+fietsen;subcontentPrefix:Trefwoorden

<img width="395" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/9696261/6413ffd8-a73a-4fae-b413-31baaf38356f">
