### ISSUE TITLE
Toggletip: Open Toggletip scrolled mee met de pagina

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#2301]
Wanneer je een toggletip opent en vervolgens naar beneden scrollt dan scrolled deze mee over heel de pagina. 

Voorstel: Uitklapper moet vastgepind zijn op de positie van de toggletip. 

![Screenshot 2023-08-28 at 13 52 04](https://github.com/dso-toolkit/dso-toolkit/assets/36912722/72198534-af51-4524-a7ed-f152c90d8d94)

**Comment by tfrijsewijk** [comment]
Dit is reproduceerbaar in Storybook op de Toggletip pagina, maar wel even de pagina lang genoeg maken dat er kan worden gescrolled.

@LukeVerlaan wil jij hiernaar kijken? Misschien is het iets voor @HalloJo, maar dat laat ik bij jullie.
