### ISSUE TITLE
Banner: No dependency on grid system

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#2303]
* De `.row` en `.col-` elementen verdwijnen, ze voegen niets toe: Een row met 1 col over de hele breedte is hetzelfde als achterwege laten.
* De functionaliteit van `.container` komt op Banner.

![Image](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/65cdd1f5-764a-46f1-875c-cafab9fd32ca)

(Zowel HTML/CSS als Web Component)

**Comment by hansgrimm** [comment]
8/4 bespreken

**Comment by hansgrimm** [comment]
even tijdelijk teruggezet naar refinement voor impact
