### ISSUE TITLE
Banner: Tooltip/toggletip verkeerde link-kleur

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#2305]
link-kleur wordt in de banner door overerving zwart/grijs ipv groen.

**Comment by LukeVerlaan** [comment]
Dit heeft te maken met de property `secondary` die hier op de toggletip is gezet. Dit is dus geen fout/bug.

**Comment by hansgrimm** [comment]
> Dit heeft te maken met de property `secondary` die hier op de toggletip is gezet. Dit is dus geen fout/bug.

hee, interessant. verklaar je nader. waar kan je dat zien?

**Comment by LukeVerlaan** [comment]
https://storybook.dso-toolkit.nl/58.1.0/?path=/story/core-toggletip--toggletip zet hier maar de control `secondary` op true.

**Comment by hansgrimm** [comment]
> https://storybook.dso-toolkit.nl/58.1.0/?path=/story/core-toggletip--toggletip zet hier maar de control `secondary` op true.

Het gaat in deze om de link(s) in de tekst van de tool/toggletip.

![image](https://github.com/dso-toolkit/dso-toolkit/assets/506527/31670106-af60-4797-9ff2-b86af2a1f943)

**Comment by LukeVerlaan** [comment]
Ah ik zie het. Dan kan je negeren wat ik zei.

**Comment by hansgrimm** [comment]
> Ah ik zie het. Dan kan je negeren wat ik zei.

doe ik. toch bedankt, voor hetzelfde geld was het het ei van Columbus geweest :)

**Comment by HalloJo** [comment]
@hansgrimm Waar kom je deze situatie tegen 'in het echt' in Storybook? Dan kan ik het nader inspecteren en oppakken.
