### ISSUE TITLE
Illustraties: Nieuwe illustratie "Bodem in ontwikkeling"

### ISSUE THREAD

**Issue by mduijsens** [dso-toolkit/dso-toolkit#2317]
Voor de nieuwe landingspagina moet er een illustratie toegevoegd worden aan de toolkit.

![bodem_in_ontwikkeling](https://github.com/dso-toolkit/dso-toolkit/assets/144002683/109784f1-a813-46cf-82ad-36c738b11108)

Bestandsnaam: `bodem_in_ontwikkeling.svg`

Een eerder voorstel was een oranje met witte tekst:

![bodem_in_ontwikkeling](https://github.com/dso-toolkit/dso-toolkit/assets/144002683/9d5920c1-9934-4ae7-a3b6-f5a2aa193c6c)

**Comment by mduijsens** [comment]
Hier de context waar hij in leeft straks: [DSOV-3297](https://dev.kadaster.nl/jira/browse/DSOV-3297)
![image](https://github.com/dso-toolkit/dso-toolkit/assets/144002683/37e19c66-1734-4943-a933-3b062ad432ee)

**Comment by mduijsens** [comment]
Je geeft aan dat het contrast 4.5:1 moet zijn. Ik introduceer niet graag een nieuwe kleur naast alle reeds bestaande kleuren in het palet. Ik kan de illustratie als volgt aanpassen: Grasgroen afbeelding. Donkerblauw label met witte tekst. Dan kom ik voor het label uit op een contrast van:
<img width="1196" alt="Screenshot 2023-09-14 at 13 59 44" src="https://github.com/dso-toolkit/dso-toolkit/assets/144002683/549c2846-9c2c-4a4b-a9e0-e479068a6dee">

Het ziet er dan zo uit in de context (even los van de discussie of dit wel echte verduidelijking geeft aan de gebruiker):
<img width="635" alt="Screenshot 2023-09-14 at 14 00 41" src="https://github.com/dso-toolkit/dso-toolkit/assets/144002683/b262a182-d7dc-4d88-b725-77875fa15bd9">

Dan wordt dit het SVG bestand: 
![bodem_in_ontwikkeling](https://github.com/dso-toolkit/dso-toolkit/assets/144002683/c66da43e-bd8b-4f58-94bf-17d280441387)

p.s. hebben we dit probleem dan ook niet in het Beta label?

**Comment by hansgrimm** [comment]
Op zich wel, maar ik vind dat zelf totaal onbelangrijke info, en volgens mij is die tekst groter :)

**Comment by hansgrimm** [comment]
Nee dat maakt voor de contrastratio niks uit.

**Comment by hansgrimm** [comment]
![IMG_4250](https://github.com/dso-toolkit/dso-toolkit/assets/506527/f71b7c2b-b688-4fe4-806b-ece5641938b9)
Er is nog wel een soort van escape, als je het gooit op ‘Graphical objects and user interface components’, wat een SVG uiteraard is. In dit geval sta ik daar niet achter, omdat de SVG informatieve tekst bevat.

**Comment by mduijsens** [comment]
Omdat het textueel is, zoals in Normal/Large zou ik er toch voor opteren om een andere kleur te kiezen. Ik heb nu donkerblauw gebruikt in de illustratie, maar Mauve werkt ook (die heeft een score van 6.39:1).

**Comment by tfrijsewijk** [comment]
Leuk! Waar gaan we voor? Gebruiken we deze kleur dan ook voor het lint in het nieuwe Logo component?

**Comment by DjangoBlok** [comment]
Op oranje moet volgens de contrast analysers een zwart (#000000) lettertype worden gebruikt, dan voldoet hij wel. (6.5:1)

**Comment by hansgrimm** [comment]
Klopt, zwart is veel beter qua contrast, maar veel mensen hebben een esthetisch probleempje met de combi oranje en zwart op de een of andere manier 🤷‍♂️.
Die bloedstollende discussie heb ik bij ING ook gevoerd, en als je nu naar ing.nl gaat zie je daar een inlogknop hangen, die nog steeds niet voldoet aan de contrasteisen. Dit ondanks het feit dat de toegankelijkheid bij ING als een cerberus bewaakt wordt door Jake Abma, die namens ING zelfs een ‘seat at the table’ heeft bij het W3C… toch zien ze geen kans om zoiets simpels te regelen. Als ik Jake weer eens zie zal ik er nog eens naar informeren 😉
In de tussentijd: by all means, paint it black 😁

**Comment by mduijsens** [comment]
Eindconclusie is dat we voor Mauve gaan. Hier de juiste versie:

![bodem_in_ontwikkeling](https://github.com/dso-toolkit/dso-toolkit/assets/144002683/109784f1-a813-46cf-82ad-36c738b11108)
