### ISSUE TITLE
Anchor: Icon no wrap

### ISSUE THREAD

**Issue by MYpenburg** [dso-toolkit/dso-toolkit#2329]
En, mocht het mogelijk zijn, de kleur van icoon gelijk aan die van de tekst.

**Comment by anneke** [comment]
Gisteren na het overleg heb ik een voorbeeld aangedragen om met een pseudo-element en absolute positionering het icoontje aan de link te plakken; dit is misschien een oplossing maar moet even door Hans en Tim worden bekeken:
https://codepen.io/annekesinnema/pen/bGOppGy??editors=1100

**Comment by hansgrimm** [comment]
Wat mij betreft een prima oplossing, al vind ik zelf die base64 in de CSS altijd een beetje vies ;)
Qua a11y zie ik verder geen beletsel; de visuele toevoeging wordt niet door de AT's opgepakt, en de linktekst moet altijd duidelijk genoeg zijn, zodat de visuele toevoeging een illustratief extraatje is.

cc @timveld

**Comment by tfrijsewijk** [comment]
Wellicht ten overvloede, maar we gaan dit op dezelfde manier bouwen zoals de `&.download` en `&.extern` hebben geimplementeerd. We hoeven geen base64 icoon te gebruiken.

**Comment by hansgrimm** [comment]
> Wellicht ten overvloede, maar we gaan dit op dezelfde manier bouwen zoals de `&.download` en `&.extern` hebben geimplementeerd. We hoeven geen base64 icoon te gebruiken.

Daar wilde ik zelf ook al even een onderzoekje naar doen, aangezien een base64 allesbehalve ideaal is. OK, dank, ik neem dat mee.

**Comment by hansgrimm** [comment]
Wat was ook alweer de url van die site waar ze dit voor mekaar hadden? Ik ben een beetje aan het eind van m'n latijn hier.

**Comment by hansgrimm** [comment]
![Image](https://github.com/dso-toolkit/dso-toolkit/assets/506527/a91be699-d64b-4de7-83ac-9f6d5f6130f3)

Ook digitoegankelijk.nl krijgt het niet voor mekaar, ik dacht ooit gehoord te hebben van wel.

**Comment by anneke** [comment]
Ja, digitoegankelijk lukte het ook niet. Die base64 afbeeldingen waren niet voor productie bedoeld hoor, dat was om snel te experimenteren met afbeeldingen op Codepen. Ik zit ook nog even te proberen :)

**Comment by hansgrimm** [comment]
Cross-browsertest: Safari toonde de iconen niet. Oorzaak is kennelijk een bug mbt `background-size: contain`. Opgelost door de background-size expliciet te maken. Dat werkt overal, en dus ook in Safari. Uiteraard wel in relatieve units, `em`, zodat de iconen keurig meegroeien met de fontsize; dat doen ze in de huidige versie niet.
