### ISSUE TITLE
Interlinie in .dso-rich-content

### ISSUE THREAD

**Issue by PieterVerheij** [dso-toolkit/dso-toolkit#233]
de interlinie (tussen bv. de box en een paragraaf) laat wat te wensen over. Bv. ruimte tussen `hightlight-box` en `paragraaf` en `definition list` en `paragraaf` is te klein.

**Comment by PieterVerheij** [comment]
@MichielDHVD Zou jij hier een ei over kunnen leggen: de interlinie in ds-rich-content is niet helemaal consquent: ruimte tussen tabel en paragraaf en definition list en paragraaf is te klein. 
We zouden bv. de definition list en highlight-box ook een margin-bottom van 12 px (of misschien zelfs 24px) moeten geven? 
Zie afbeelding: 
![dso-rich-content](https://user-images.githubusercontent.com/25430835/48546098-b35aac00-e8c7-11e8-969a-8c6e5fb3ddf3.png)

**Comment by MichielDHVD** [comment]
Ik ga deze week hier een update over geven.

**Comment by MichielDHVD** [comment]
Voor de definition list en de highlight box is een ophoging van 24 px het beste. 16 px is niet genoeg ruimte. Voor elementen die losser moeten staan van de rest is 24px vaak het minimale wat nodig is om een fijn onderscheid te maken. 

Voeg ook twee afbeeldingen toe waar je het verschil van 16 en 24 px ziet. 

12px moet sowieso verdwijnen.  De bedoeling is dat  het begin bij 8px en vervolgens 16, 24 etc.  Nu zal dit veel impact hebben. 

Maar de eerste vraag hierin is.  Is de 12px een vaste baseline die ergens vast staat ? Want dat is de minimale waarde die ik op dit moment zie.

**Comment by PieterVerheij** [comment]
12px is een waarde die uit bootstrap komt. Ik ben bezig om te achterhalen waar en hoe ik dat kan overrulen.

**Comment by PieterVerheij** [comment]
@MichielDHVD We hebben hier nog een beetje lopen stoeien met de margins. 

Hieronder een opsomming van de rich-content elementen die een margin/padding van 12px aanhouden:
`h1, .h1,
h2, .h2,
h3, .h3 {
  margin-bottom: 12px; }

h4, .h4,
h5, .h5,
h6, .h6 {
  margin-top: 12px;
  margin-bottom: 12px;
 }

p {
  margin: 0 0 12px;
 }

ul,
ol {
  margin-bottom: 12px;
 }

blockquote {
  padding: 12px 24px;
}

pre {
  margin: 0 0 12px;
}

dl dd .highlight-box, .dso-jumbotron .dso-jumbotron-body .highlight-box, .list-group > .list-group-item .highlight-box, .dso-modal .dso-body .highlight-box, .panel-body .highlight-box, table.table td .highlight-box, table.table th .highlight-box,
.dso-rich-content .highlight-box {
  margin-bottom: 12px;
}`

Doormiddel van een stukje css hebben we de minimale tussenruimte op 16px gezet. Zie afbeelding.
![dso-rich-content-margin-top-16px](https://user-images.githubusercontent.com/25430835/49724668-21498780-fc6a-11e8-9f8d-2135abc208a0.png)

Aandachtspunten:
- Op de tabel hebben we ook een border-top en border-bottom gezet, omdat anders de tussenruimte groter lijkt, veroorzaakt door de padding van de tabel-cellen.-
- Voor de elementen van de hightlightbox kan nog een andere (grotere) waarden gekoze worden.

**Comment by MichielDHVD** [comment]
Ik zie dat ik deze op 13 Dec naar In Progress heb verplaatst. Ik weet niet of dat de bedoeling was. 

Is er genoeg informatie of kan deze naar To Do? @PieterVerheij

**Comment by PieterVerheij** [comment]
@MichielDHVD : als jij het eens bent met mijn post van Dec 10, 2018 en kan reageren op de aandachtspunten, kan ik er mee aan de slag.

**Comment by MichielDHVD** [comment]
Ik ben het eens met de post van Dec 10, 2018. 

Betreffend de aandachtspunten: 

de bovenkant van de tabel is prima. Aan de onder kant van de tabel zou een extra 8px niet misstaan. Waarschijnlijk is dat nu 16px. Denk dat 24px beter overkomt. We willen in de toekomst grotere componenten aan de onderkant meer ruimte geven voor een rustigere uitstraling. 

De highlight box vind ik op deze manier eigenlijk heel sterk in de flow van de tekst passen. Dit is vooral mooi omdat in het geval van een toelichting deze vaak dicht op het antwoord moet staan. Dus deze mag gewoon blijven staan. 

Bij deze verplaatst ik dan dit issue naar To Do.

**Comment by MichielDHVD** [comment]
Gezien en verplaatst naar Done.
