### ISSUE TITLE
Accordion: variant van compact-black zonder horizontale lijnen

### ISSUE THREAD

**Issue by MYpenburg** [dso-toolkit/dso-toolkit#2333]
Precies dezelfde accordion, maar dan zonder de lijnen. 
Tbv. Lees meer / lees minder alternatief.

**Comment by MYpenburg** [comment]
Overview
<img width="1142" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/7289928/a27872c1-3023-47f2-87d1-72134c4b4140">
Ingeklapt
<img width="1142" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/7289928/3fd42534-e111-432a-8701-1ec6be686f73">
Uitgeklapt
<img width="1142" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/7289928/6e45bebd-8f57-4416-9e22-475ecdb414e7">

**Comment by tfrijsewijk** [comment]
@sanderhaa @MYpenburg Waarom is dit issue gesloten?

**Comment by MYpenburg** [comment]
@tfrijsewijk omdat dit niet binnen enige tijd opgepakt gaat worden binnen mijn team.
