### ISSUE TITLE
Accordion: Reverse align werkt niet in compact

### ISSUE THREAD

**Issue by DjangoBlok** [dso-toolkit/dso-toolkit#2343]
In de accordions is de optie op via ReverseAlign de chevrons rechts te positioneren. 
In de compacte vorm werkt deze optie niet.

Zie https://storybook.dso-toolkit.nl/58.3.1/?path=/story/html-css-accordion--compact&args=reverseAlign:!true

**Comment by tfrijsewijk** [comment]
@hansgrimm kan jij hier wat onderzoek naar doen waarom dit zo is? En let dan vooral op de twee verschillende implementaties (HTML/CSS en Web Component)

**Comment by hansgrimm** [comment]
Even uitzoeken waarom dat in hemelsnaam qua styling zo complex is opgezet. Je zou zeggen dat die reverseAlign over alle varianten hetzelfde moet werken

**Comment by hansgrimm** [comment]
Ik zie denk ik al waar het in zit. als dat klopt, heeft het nooit gewerkt.
[knutsel knutsel]
en inderdaad, cascade issue (source order) selectors omgeswitcht, en nu werkt het.
PR:  https://github.com/dso-toolkit/dso-toolkit/pull/2350
