### ISSUE TITLE
Document Component: Ondersteuning voor vrije tekstdocumenten zonder titel & IMRO documenten inspringen

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#2346]
- [x] Bij vrije tekst documenten kun je een divisietekst hebben zonder titel. Dan wordt nu een lege titel met chevron getoond en daaronder de inhoud terwijl je alleen de inhoud verwacht.
![image](https://github.com/dso-toolkit/dso-toolkit/assets/111350940/d7d73aa7-e921-4507-ab46-26547857c9dd)

* Als een Divisietekst geen Kop heeft dan is het Document Component niet inklapbaar (geen chevron)
* De tekst hoeft dan ook niet in te springen
* In dat geval staat een eventueel Ontwerp label en/of annotatieknopje boven de inhoud.

- [x] Wanneer we zelf de content toevoegen (dus `inhoud` leeg laten en via het slot content toevoegen) dan lijkt de content niet in te springen.
![image](https://github.com/dso-toolkit/dso-toolkit/assets/111350940/403ef356-ebcf-413c-986f-885d16e16737)

**Comment by tfrijsewijk** [comment]
@DjangoBlok Hoe gaan we punt 1 eigenlijk oplossen?

**Comment by tfrijsewijk** [comment]
@DjangoBlok Kan jij testen?
* https://storybook.dso-toolkit.nl/_2346-imro-and-vrije-tekstdocumenten-support/?path=/story/core-document-component--demo 
* https://storybook.dso-toolkit.nl/_2346-imro-and-vrije-tekstdocumenten-support/?path=/story/core-document-component--imro

**Comment by DjangoBlok** [comment]
Het eerste issue gaat over vrije tekststructuur, heb je daar ook een voorbeeld van?

**Comment by DjangoBlok** [comment]
IMRO inspringing lijkt er goed uit te zien.
Wel veel afstand tussen de kopjes en de tekst eronder. Was dat al zo?
