### ISSUE TITLE
Document Component: type "regels-op-maat"

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#2347]
Variant van document component voor regels op maat
De eerste koppen worden alleen voor de context weergegeven en hoeven niet interactief te zijn.

- Niet vetgedrukt
- Geen chevron (links uitgelijnd) 

![Image](https://github.com/dso-toolkit/dso-toolkit/assets/34900082/08962c40-97a1-487c-a9f4-3275952fbfad)

**Comment by tfrijsewijk** [comment]
@DjangoBlok @mduijsens Is dit nog actueel?

**Comment by DjangoBlok** [comment]
Nee, is niet meer actueel. Ik denk dat het beter is om deze weg te gooien en te wachten op andere plannen.

**Comment by tfrijsewijk** [comment]
Prima! Dank
