### ISSUE TITLE
Anchor: Custom opmaak van hyperlinks in toelichtingen

### ISSUE THREAD

**Issue by MYpenburg** [dso-toolkit/dso-toolkit#2351]
**tel: link**
De link alleen (non-breaking) laten voorafgaan door een 'call' icoon in de kleur van de lopende tekst. Geen 'external-link' aan het eind

**mailto: link**
De link alleen (non-breaking) laten voorafgaan door een 'email' icoon in de kleur van de lopende tekst. Geen 'external-link' aan het eind

**Comment by anneke** [comment]
@MYpenburg Welke tekst moeten we voorlezen als iemand een screenreader gebruikt?

**Comment by hansgrimm** [comment]
> De iconen staan al in de toolkit onder de naam tussen quotes. De externe link heeft natuurlijk de "opent in een nieuw venster" toevoeging, maar die hoeft hier in principe niet als mensen doorhebben dat het een nummer of een mailadres is. Misschien kunnen Grimm & Tim iets zeggen over het correcte voorleesgedrag van mailto: en tel: links? (@timveld @hansgrimm).

Die worden voor zover ik weet correct door de screenreaders herkend en voorgelezen.

**Comment by anneke** [comment]
VoiceOver op Mac met Safari leest niet voor wat voor soort link het is. (Heb het net getest). Er wordt alleen "link" voorgelezen.

**Comment by tfrijsewijk** [comment]
@anneke Ik zag een branch met dit issuenummer dus ben zo vrij geweest dit issue in progress in de sprint te zetten 🙏
