### ISSUE TITLE
Docusaurus: toon versie in navigatie

### ISSUE THREAD

**Issue by anneke** [dso-toolkit/dso-toolkit#2353]
<img width="1133" alt="docusaurus-desktop" src="https://github.com/dso-toolkit/dso-toolkit/assets/7202272/65063273-dba5-47ce-b102-280f592d360b">

<img width="395" alt="docusaurus-iphone-SE" src="https://github.com/dso-toolkit/dso-toolkit/assets/7202272/2e585cb6-c862-42c4-bfc1-c7faedc045cd">

**Comment by tfrijsewijk** [comment]
🎉
