### ISSUE TITLE
Form-group: Top spacing after image list

### ISSUE THREAD

**Issue by MYpenburg** [dso-toolkit/dso-toolkit#2357]
![image](https://github.com/dso-toolkit/dso-toolkit/assets/7289928/062c9c92-7579-496f-9094-b522cfa91009)

Op de pre te reproduceren:
- Locatie ergens in Delft met water
- Werkzaamheid Afvalwater lozen
- In de vragenboom Lozen op oppervlaktewater

Vraag aan Toolkit: is dit iets voor ons om aan te passen in de markup of is dit een side effect van de verticale ritme refactoring?

**Comment by hansgrimm** [comment]
Hmm, ik vind juist die afstand bij het groene cirkeltje veel te fors..

**Comment by hansgrimm** [comment]
@MYpenburg waar kan ik dit bekijken/debuggen?

**Comment by hansgrimm** [comment]
> Op de pre te reproduceren:

> - Locatie ergens in Delft met water
> - Werkzaamheid Afvalwater lozen
> - In de vragenboom Lozen op oppervlaktewater

@MYpenburg ik kom hiermee niet in een scherm terecht zoals getoond. mis ik iets?

**Comment by MYpenburg** [comment]
Die content is blijkbaar weer verdwenen. Ik zal eens verder zoeken. Misschien zijn er andere test-trucs te bedenken om de inhoud op te rekken?

**Comment by hansgrimm** [comment]
Als er in de voorbeeldpagina’s in storybook een vergelijkbare opzet zit houd ik me aanbevolen, maar ik ben die nog niet tegengekomen. Sowieso is de verticaal ritme operatie hier niet de oorzaak, want dit zit nog niet in de toolkit.

**Comment by MYpenburg** [comment]
Als je in Delft met water kiest voor: Rioolwater lozen vanuit een overstort. Dan komt er een geovraag.

**Comment by hansgrimm** [comment]
Waar start ik? Vergunningcheck?

**Comment by MYpenburg** [comment]
Sorry, ja Vergunningcheck

**Comment by hansgrimm** [comment]
Got it!

**Comment by hansgrimm** [comment]
Oorzaak: een `.form-group` na een `.form-group` heeft een bovenmarge van 32px, dus de eerste `.form-group` heeft dat niet, wat op zich hartstikke logisch en OK is, alleen hier even niet ;)

Volgens mij is dit dus een issue die al langer speelt, maar misschien was deze opzet nog niet eerder zo toegepast.

Heeft deze fix prio voor nu, of kan ik die opnemen in de verticaal ritme operatie? Let wel: het kan nog even duren voordat die erin gaat; dat heeft te maken met browsersupport die eraan komt, maar er nog niet is.

**Comment by MYpenburg** [comment]
Liefst zsm meenemen met een fix, bevoegd gezagen zijn nu als een gek aan het oefenen/afronden dus als ie nog mee kan met de release van volgende week zou dat tof zijn

**Comment by tfrijsewijk** [comment]
> Liefst zsm meenemen met een fix, bevoegd gezagen zijn nu als een gek aan het oefenen/afronden dus als ie nog mee kan met de release van volgende week zou dat tof zijn

Kan! Hij is gemerged en rolt dinsdag mee.
