### ISSUE TITLE
Form group: Table overflow in rich content

### ISSUE THREAD

**Issue by MYpenburg** [dso-toolkit/dso-toolkit#2358]
Het probleem: sommige waterschappen stoppen tabellen in de markup, wat eigenlijk niet ondersteund wordt maar wel tot een probleem leidt:
<img width="1322" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/7289928/62d4aece-f70a-4f76-8efa-bfea7b27c3bd">

Het speelt zich allemaal af in een dso-info:
<img width="383" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/7289928/0d75e459-ea05-4ee3-9dcf-e5fc7f86b163">

Er zijn meerdere nette oplossingen. Ik zoek een pre-IWT quick fix die het liefst helemaal vanuit de Toolkit kan worden gerealiseerd. Na IWT kunnen we kijken hoe we dit soort content beter kunnen afweren of omarmen, dat is nog een politieke keuze.

**Comment by tfrijsewijk** [comment]
In overleg met Martin gaan we voor een autoscroll op overflow-x. Idealiter gaat `<dso-table>` ingezet worden maar dat is voor nu geen optie.

Voorzien jullie (@hansgrimm @anneke) problemen door op elke `.dso-field-container .dso-info` dit soort stijling te zetten?

**Comment by hansgrimm** [comment]
Zou normaal gesproken moeten kunnen, zolang het maar duidelijk is voor de gebruiker. Hou er wel rekening mee dat dan de hele zwik horizontaal scrollt, ook het deel dat wel binnen het vlak past. Niet echt heel elegant.
Domme vraag misschien: waarom is `dso-table` geen optie?

**Comment by MYpenburg** [comment]
Van oudsher waren tabellen niet toegestaan in toelichtingen. Ze worden ook niet ondersteund maar ook niet geweerd. Totdat die beslissing gevallen is wil ik iig. dat de interface niet stuk gaat door overlappende teksten. PR12 heeft ook geen tijd om hier iets extra's voor in te bouwen nu. 
Sowieso is het eeen goed idee om de grijze boxen te begrenzen qua overflow.

**Comment by hansgrimm** [comment]
Ik zal eens kijken of ik hier een werkbare oplossing voor kan bedenken. Is er een url waar ik dit aan gort kan hacken? 😁

**Comment by tfrijsewijk** [comment]
Je kan dit lokaal reproduceren door een tabel in een formulier toelichting te plaatsen. Daarnaast is het goed dat deze variant/uitbreiding wordt ingecheckt zodat we het kunnen meenemen in de visuele regressietesten.

**Comment by hansgrimm** [comment]
@MYpenburg met `overflow` kunnen we niks, want rich content dus geen mogelijkheid om de html aan te pakken. ik kan wel de propert `table-layout: fixed` op de tabel zetten, maar dan heeft-ie wel heel erg tussen de deur gezeten :)

Before:
![Scherm­afbeelding 2023-10-09 om 17 44 19](https://github.com/dso-toolkit/dso-toolkit/assets/506527/2aec7ff5-7c17-41b1-bb60-5e2ad26a340e)

After:
![Scherm­afbeelding 2023-10-09 om 17 43 59](https://github.com/dso-toolkit/dso-toolkit/assets/506527/04feb398-7011-4d45-a932-80a98eb6044c)

**Comment by MYpenburg** [comment]
Als het aan mij ligt: niks doen met styling van de tabel en de overflow-x van de juiste container laten scrollen.

**Comment by hansgrimm** [comment]
> Als het aan mij ligt: niks doen met styling van de tabel en de overflow-x van de juiste container laten scrollen.

Dat betekent dat alles links het beeld uit scrollt als je de tabel rechts naar binnen scrollt. Acceptabel? Echt?

**Comment by MYpenburg** [comment]
Ja, echt.

**Comment by hansgrimm** [comment]
> Ja, echt.

Okee 😎

**Comment by hansgrimm** [comment]
@MYpenburg dit dus:
![Scherm­afbeelding 2023-10-10 om 11 27 04](https://github.com/dso-toolkit/dso-toolkit/assets/506527/ff3fd5a3-718b-4c1d-a9c9-deac56f97af0)
We gaan het regelen, maar alleen op deze plek.

**Comment by MYpenburg** [comment]
Ja, dit is hem. Op welke plek bedoel je precies?

**Comment by hansgrimm** [comment]
> Ja, dit is hem. Op welke plek bedoel je precies?

Op de plek waar het zich nu voordoet, `.dso-rich-content` binnen `dso-label-container`. Ik wil dit niet laten lekken naar andere plekken waar `.dso-rich-content` wordt gebruikt. het is een tijdelijke pleister, totdat we `.dso-table` kunnen toepassen op die plek.

**Comment by MYpenburg** [comment]
Prima. Wordt dit dan ook toegepast in de toelichtingen bij de antwoorden? (Voorbeeld is toelichting bij de vraag)

**Comment by hansgrimm** [comment]
> Prima. Wordt dit dan ook toegepast in de toelichtingen bij de antwoorden? (Voorbeeld is toelichting bij de vraag)

als je de toelichting onder de (i) bedoelt, dan ja. die luistert naar dezelfde selector

**Comment by MYpenburg** [comment]
Mooi!
