### ISSUE TITLE
Selectable: Inline werkt niet als verwacht

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#2370]
zie https://dso-toolkit.slack.com/archives/CB417GQBC/p1696408235155559

Als je op een `form-group dso-radios` de class `dso-inline` toevoegt, blijven de `dso-selectable` componenten onder elkaar staan (`display: block` wordt niet overschreven). Zodra je aan de componenten de _class_ `dso-selectable` toevoegt, gebeurt dat wel, zoals in de css geregeld. Echter, die class zit niet standaard op het component.

**Comment by petervannes** [comment]
Aanvullend, zonder de 'dso-selectable' class in de `DsoSelectable` component worden de radiobuttons niet relatief geplaatst ten opzichte van de container. Oorzaak hiervan is een margin van `-16` op de fieldset met class `form-group` en `dso-inline`.

![image](https://github.com/dso-toolkit/dso-toolkit/assets/7499676/f03706a2-d87c-49e5-983f-79060383fafa)

Indien `dso-selectable` class op `DsoSelectable` component wordt gezet heeft de eerste `dso-selectable` een left-padding van 32px afkomstig uit `dso-selectable`, het tweede een left margin van 24px en een padding van 32px. 

![image](https://github.com/dso-toolkit/dso-toolkit/assets/7499676/80de901b-44d0-4378-bcc1-3b7503b5bd4c)

Indien de left-padding uit `dso-selectable` wordt gehaald ziet hier er volgens mij uit zoals gewenst.

![image](https://github.com/dso-toolkit/dso-toolkit/assets/7499676/a892734d-31b3-4f99-bd3f-261aa4216b0d)
