### ISSUE TITLE
Readme: Verwijs naar de juiste dso.css

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#2377]
Tijdens het bouwen van een voorbeeldpagina door de link https://cdn.dso-toolkit.nl/master/dso.css te gebruiken direct op een html pagina. Kwam ik erachter dat bepaalde stijlen niet meegestuurd worden. 

Stijl die niet mee gestuurd wordt. (deze stijl is terug te vinden in grid.scss) 

`.row.dso-banner+.row.dso-featured {
    margin-top: 0
}
`

Ik weet niet of er nog meer stijlen zijn die niet meegestuurd worden. 

Al samen met @hansgrimm bekeken en die kon in de master dso.css ook niet deze specifieke styling terug vinden.

**Comment by tfrijsewijk** [comment]
Hi Michiel,

Je maakt gebruik van het verkeerde patroon: Zie de CDN documentatie (https://dso-toolkit.nl/60.0.0/voor-developers/cdn).

Nu vind ik er ook wel wat voor te zeggen dat het knap verwarrend is dat `master` op zowel de oude als de nieuwe locatie is te vinden. Misschien moeten we de oude maar weghalen, voor de zekerheid.

Jij wilt in ieder geval gebruik maken van 

```
https://cdn.dso-toolkit.nl/dso-toolkit/master/dist/dso.css
```

**Comment by MichielDHVD** [comment]
De link had ik gehaald uit de omschrijving op github (zie afbeelding). 
<img width="866" alt="Screenshot 2023-10-13 at 09 28 34" src="https://github.com/dso-toolkit/dso-toolkit/assets/36912722/61b78175-c0c5-406f-80eb-7439ee8e8fec">


Moet deze link aangepast worden?

**Comment by tfrijsewijk** [comment]
Oh inderdaad zeg.. Daar moet wat mee 😱 

@anneke? 👼 :pretty-please:
