### ISSUE TITLE
Highlight Box: aspect ratio banner aanpassen naar 3.5/1

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#2383]
Bij het herontwerp voor de homepage werd duidelijk dat wanneer je een grotere highlightbox gebruikt die een grotere breedte beslaat de afbeelding teveel ruimte inneemt. Het overheerst compleet de content, terwijl een de rol van de afbeelding is visuele ondersteuning. 

Werkzaamheden: 

Verander de aspect-ratio van dso-highlighbox-banner.
Van 2.38/1 -> naar 3.5/1

@tfrijsewijk Dit is volgens mij een kleine aanpassing. Verzoek vanuit mij is of dit zsm opgepakt kan worden.

**Comment by hansgrimm** [comment]
Container queries, hoe breed is de card?
