### ISSUE TITLE
Logo: Fix contrast in ribbon and enable accessibility test

### ISSUE THREAD

**Issue by anneke** [dso-toolkit/dso-toolkit#2384]
`Ribbon` heeft nu een contrast issue (witte tekst op oranje achtergrond), dit willen we graag aanpassen.
Hierna kan de (tot nu toe) blocking accessibility test in Cypress opnieuw aangezet.

**Comment by tfrijsewijk** [comment]
Relates to #2265 

@dso-toolkit/dso-ux: Kunnen jullie ons helpen? Welke kleur oranje gaan we in het Logo voor de ribbon gebruiken? Dit lijkt op de discussie in #2317

**Comment by MichielDHVD** [comment]
Ribbon wordt Mauve,  26-10-2023
