### ISSUE TITLE
Toevoegen Role="alert" aan autocomplete melding

### ISSUE THREAD

**Issue by mduijsens** [dso-toolkit/dso-toolkit#2385]
Tijdens WCAG meeting komen we er achter dat er nu geen role="alert" zit op de melding 'Zoekterm is niet gevonden' in de autocomplete. Hier moet een Role="alert" op komen.

![Image](https://github.com/dso-toolkit/dso-toolkit/assets/144002683/8044a506-2f2a-4e16-bdaa-692d53a1550b)

**Comment by mduijsens** [comment]
Ter context: we gaan zelf ook de gele melding weg halen, dus dan blijft deze als enige over.

**Comment by hansgrimm** [comment]
Op de lijst (`<ul>`) waar de melding deel van uitmaakt, staat al een `aria-live="polite"`-attribuut, wat betekent dat deze melding wordt voorgelezen als de gebruiker stopt met typen. Ik zou zelf zeggen dat dat voldoende is. @timveld eens?

**Comment by mduijsens** [comment]
We veranderen dit NIET, we passen de oplossing aan in het WCAG rapport.
