### ISSUE TITLE
Document Component: Mark en highlight functionaliteit

### ISSUE THREAD

**Issue by mduijsens** [dso-toolkit/dso-toolkit#2386]
Voor het zoeken in een document hebben we een highlight functie nodig in de content van een document.
Eerder besproken dat dit aan de hand van de Mark functionaliteit zou moeten gebeuren. We verwachten de volgende styling:

![Image](https://github.com/dso-toolkit/dso-toolkit/assets/144002683/4c467250-5b0a-4ea9-8d49-19050bfcc3c9)

Geel voor de actieve geselecteerde markering (we steppen namelijk door de resultaten) en een geel-20 voor wel gevonden maar niet actief.

**Renvooi**
Er hoeft geen andere kleurpallet gedaan te worden voor Renvooi omdat de tekst al een specifieke renvooi styling heeft (schuingedrukt en overstreept voor toegevoegd en schuingedrukt en doorstreept voor verwijderd). Zie voorbeeld:
<img width="1440" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/144002683/8e71d84d-8513-44de-a2c6-f612f20f714b">

**Comment by hansgrimm** [comment]
Moet nog nader uitgewerkt worden.

**Comment by mduijsens** [comment]
Ik heb Renvooi bekeken en toegevoegd. :) Conclusie is markeren veranderd wél de kleur, maar niet te tekststyling.

**Comment by tfrijsewijk** [comment]
De gevonden term wint van de renvooiweergave. Voor termen die kleiner zijn dan de renvooiweergave is dat prima, en in het geval van een verwijder-instructie is het helemaal duidelijk vanwege de doorgehaalde tekst.

Maar heb je rekening gehouden met de situatie waar de zoekterm gelijk is aan een toegevoegde term? Ofwel, "het geel" bedekt "het groen" in z'n geheel.

**Comment by tfrijsewijk** [comment]
@mduijsens Heb jij mijn opmerking hierboven nog gezien?

**Comment by mduijsens** [comment]
Antwoord op je message van vorige week: Ja, groene teksten zijn schuingedrukt, daarmee nog steeds zichtbaar.

Sessie 30 oktober 2023
Wat deze story moet doen:
1. Alle matches highlighten.
2. Current item tonen met identificatie.
3. Scroll to functionaliteit toepassen voor het geval dat hij buiten de viewport valt.

**Comment by tfrijsewijk** [comment]
@mduijsens Het valt mij nu pas op dat bij de "voegtoe" renvooiweergave een underline is toegevoegd. Een underline wordt over het algemeen geassocieerd met een link en kan daarom verwarrend zijn. Zullen we eerst alleen de schuingedrukte tekst proberen?

**Comment by hansgrimm** [comment]
Eens. **nooit** een underline op tekst waar dat geen link is.

**Comment by hansgrimm** [comment]
Er zijn nog alternatieve underline-stijlen, maar daar is de support niet ideaal van.

**Comment by mduijsens** [comment]
Ik wil niet zo maar nu Renvooi gaan veranderen. Ik neem het mee om te bespreken, maar zou willen opteren om nu niet aan Renvooi te gaat zitten. ;) Ik ben zelf niet betrokken geweest bij die keuzes en de signalen van mensen tot nu toe mbt Renvooi zijn volgens mij heel positief, dus voor ons nu geen reden om dat anders toen. Ik ga dit wel even dubbel checken.

**Comment by tfrijsewijk** [comment]
> Ik wil niet zo maar nu Renvooi gaan veranderen. Ik neem het mee om te bespreken, maar zou willen opteren om nu niet aan Renvooi te gaat zitten. ;)

Dus jouw aanpassingen (schuin en onderstreept) op de renvooiweergave in bovenstaand ontwerp gaan we niet doorvoeren? In dat geval zie je geen renvooiweergave voor tekst die in z'n geheel is gemarkeerd.

**Comment by hansgrimm** [comment]
In dat geval kunnen we ook nog sleutelen aan de underline style ;)

**Comment by DjangoBlok** [comment]
Er blijkt een misverstand te zijn over de styling van renvooi weergave.
Die underline en cursieve tekst hoort er niet in te zitten.
Het ontwerp was gebaseerd op dit voorbeeld: 
https://snapshot.document-viewer.dso.kadaster.nl/viewer/(documentresult//rechter-paneel:document/_akn_nl_act_gm9920_2023_AD_Proefversie_akn_nl_bill_gm9920_2023_B_AD_ProefversieONTW/regels)?id=_akn_nl_act_gm9920_2023_AD_Proefversie_akn_nl_bill_gm9920_2023_B_AD_ProefversieONTW

In dat document blijkt een definition list te zitten die nog niet bewust is gestyled en nu wordt onderstreept en cursief wordt weergegeven. Dat is niet de bedoeling.
@tfrijsewijk kun jij een story aanmaken om in ieder geval de onderstreping van de definition list af te halen.

We hoeven dus niet te sleutelen aan de underline stijl.

**Comment by tfrijsewijk** [comment]
Stavaza:

![image](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/9347496d-6613-4fe5-afb9-0b15e2749742)

cc: @DjangoBlok @mduijsens

**Comment by tfrijsewijk** [comment]
Ik heb de kleuren met een color picker uit de ontwerpen gehaald:

```scss
$mark-color: #f8f5ce;
$highlight-color: #dbd136;
```

Deze kleuren zitten niet in het palet.

* De kleur die eerst op `<mark>` stond was `$geel-20: #f8f6cc`.
* De kleur voor het highlighten van een zoekopdracht lijkt vreselijk veel op de kleur die we bij Label: Warning gebruiken: `$geel: #dcd400`.

@mduijsens hoe ben jij aan deze kleuren gekomen? Zijn de kleuren die in het palet zitten niet toereikend?

**Comment by mduijsens** [comment]
Ik heb gewoon de geel uit sketch library gebruikt :)
<img width="256" alt="Screenshot 2023-11-10 at 13 37 01" src="https://github.com/dso-toolkit/dso-toolkit/assets/144002683/dfa5d424-12ac-4c19-b5d1-56450cdc7610">

**Comment by tfrijsewijk** [comment]
Ah dan ligt het aan de image picker icm. image compression. Ik pas ze aan.
