### ISSUE TITLE
Zoekoverlay: "Nav Bar" uitbreiding "extension" en nieuw component "Mark Bar"

### ISSUE THREAD

**Issue by mduijsens** [dso-toolkit/dso-toolkit#2387]
Om een zoekfunctie beschikbaar te stellen voor de gebruiker (in plaats van CTRL+F) willen we de zoekknop toevoegen. De locatie daarvan is laatste positie van de tabs.
<img width="627" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/144002683/44ecbaba-6da7-411a-bca0-6fe1e1b1277d">

<img width="627" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/144002683/fc25e058-7c67-4e78-aba4-f5e415408b2e">

Vervolgens moet er een paneel openen waar die zoekactie in gedaan kan worden. Dit ziet er als volgt uit:
**Zonder te hebben gezocht**
<img width="602" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/144002683/b3df6223-a4d0-4467-a465-f8c4484e1824">

**Er is gezocht**
<img width="602" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/144002683/dc7f796b-035c-4ca6-9123-b41e4a2f81cf">

**Soms zit er een melding bij**
<img width="602" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/144002683/ccd40c2f-c321-423a-9179-f9464dc25728">
<img width="602" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/144002683/be0ce70f-6b2d-422a-8be4-c2b1ed68f65c">

**Comment by hansgrimm** [comment]
![Image](https://github.com/dso-toolkit/dso-toolkit/assets/506527/e59b2572-4d13-45bc-adf5-1a39b186d218)

Wat zien we als die up/down-pijltjes gebruikt worden?

**Comment by hansgrimm** [comment]
"gezocht op:" gaat eruit.

**Comment by tfrijsewijk** [comment]
> Hangt deze nu nog? @tfrijsewijk :)

Nou sec gesproken hangt ie nog op een memo over zoeken 😱 Maar Rick durft het wel aan met mij ;-) Dus wat ons betreft is performance geen argument meer voor de Zoeken knop. Als je 'm eruit wilt hebben is het aan jou.

Zou je nog de maten willen doorgeven? Sketch heeft plugins zoals Sketch Meaxure om dit soort exports te maken.

En ik vroeg mij af wat de hover en focus states van alle niet-standaard knoppen zoals "Zoeken" en "Stoppen" in de menubalk zijn. Kan je die nog toevoegen?

**Comment by MichielDHVD** [comment]
Besproken Donderdag 26 oktober. 

Story is ready for development wanneer: 
- Afmetingen duidelijk zijn (Sketch meaxure) 
- Hover state van stoppen knop is uitgewerkt. 

@mduijsens

**Comment by mduijsens** [comment]
Hier de afmetingen voor desktop:

![Image](https://github.com/dso-toolkit/dso-toolkit/assets/144002683/717925f3-749c-48a0-a7bb-c8d72a2f6360)
![Image](https://github.com/dso-toolkit/dso-toolkit/assets/144002683/92e12714-ede8-4ec5-8840-4500e228f6a8)

Hover en focus zijn het zelfde als tertiare buttons. 
![Image](https://github.com/dso-toolkit/dso-toolkit/assets/144002683/0e46513e-b426-4dd0-a228-c6bafa01f63f)


Responsive komt eraan.

**Comment by tfrijsewijk** [comment]
@mduijsens Ik vraag mij nu ineens af, waarom heet dit component "overlay" ? Ik kan uit de ontwerpen niet goed opmaken over de overlay ook echt ergens _overheen_ valt, of dat het onder de navbar verschijnt en de content naar beneden duwt.

**Comment by hansgrimm** [comment]
Is het eigenlijk ook niet denk ik. Even laten uitkristalliseren

**Comment by mduijsens** [comment]
Aan de kant van de viewer willen we dit stuk 'over' het filter blok heen laten vallen of eigenlijk iets netter gezegd: We willen als dit venster geopend wordt, dat we de dsov-document-structuur-filters-vdk binnen de viewer NIET tonen. Dus vervanging van het een voor het ander. (Ik vermoed dat dit aan de kant van de viewer opgelost wordt?) We willen dus niet dat content naar beneden schuift o.i.d.

Voorheen was de bedoeling dat dit gewoon als hoogste Z-index getoond zou gaan worden en dus over alles heen zou vallen en daarmee implicit de onderliggende content zou verstoppen, daarom heb ik het toen der tijd overlay genoemd. Mogelijk nu voor jullie minder relevant doordat we echt het ene component gaan uitwisselen voor het ander. 

Maakt het het zo iets duidelijker?

**Comment by tfrijsewijk** [comment]
> Maakt het het zo iets duidelijker?

Nee :(

1. Gaat "overlay" over iets heen vallen, of
2. Valt "overlay" nergens overheen en duwt het de content onder navbar naar beneden.

Het lijkt erop alsof je 1. wilt, maar dan met 2. door iets met overlay te vervangen.

Ik raad dit af: er is geen garantie dat de werkvorm die je weghaalt dezelfde hoogte heeft van de overlay. Hierdoor is de kans aanzienlijk dat de interface gaat "stuiteren" tijdens het tonen/verbergen van de overlay.

Wat is jouw motivatie voor geen overlay?

**Comment by mduijsens** [comment]
Ja daar hebben we inderdaad wel ook over nagedacht dat het mogelijk ietsjes zou stuiteren. De reden voor het verstoppen is dat we die elementen die in het filterblok tijdelijk echt even onbereikbaar willen maken zodat er niet zoekacties, filteracties en weergave wisselingen allemaal door elkaar heen gebruikt kunnen worden. Dan gaan we namelijk scenario's krijgen die mogellijk zo onduidelijk/onvoorspelbaar zijn dat deze story te groot word. Dus daarom nu 1 van de 2 content blokken tegelijkertijd beschikbaar. Als je zelf zegt Overlay maken is daar nogsteeds geschikt voor dan vind ik dat ook oke. Het is vooral dat we dus NIET willen dat de gebruiker skippers/filters/etc etc kan gebruiken tijdens zoeken. Als je aan het zoeken bent, heb je écht even focus op zoeken.

**Comment by hansgrimm** [comment]
Dit is wat ik nu heb in de zandbak waar ik dit aan het bouwen ben:
![Image](https://github.com/dso-toolkit/dso-toolkit/assets/506527/03d4f10c-fccb-4996-a3db-69453011ae34)
![Image](https://github.com/dso-toolkit/dso-toolkit/assets/506527/0a5c8108-0d08-416b-9564-750de275c4e9)
De corporate mumbojumbo tekst staat er even onder voor het overlay effect.
@mduijsens ik ben zo vrij geweest er een slagschaduwtje onder te zetten. eens of niet eens? ;)

**Comment by hansgrimm** [comment]
@mduijsens die variant met die groene 'zoeken'-knop, is die nodig? we gingen toch de browser-zoekfunctie (ctrl/cmd+f) emuleren?

**Comment by mduijsens** [comment]
Hallo! Ziet er al zeeeker goed uit! Daar hebben we het inderdaad later over gehad dat de groene zoekknop niet required was als we dus na stopen met typen gelijk aan de slag gaan! :) Daarom zie je in de gene waar de afmetingen bij staan had ik de knop er al uit gehaald. :)

**Comment by hansgrimm** [comment]
> Hallo! Ziet er al zeeeker goed uit! Daar hebben we het inderdaad later over gehad dat de groene zoekknop niet required was als we dus na stopen met typen gelijk aan de slag gaan! :) Daarom zie je in de gene waar de afmetingen bij staan had ik de knop er al uit gehaald. :)

Top! Ik zit er nu middenin, dus die vraag was even voor de zekerheid ;)

**Comment by tfrijsewijk** [comment]
@hansgrimm Let op: De overlay valt niet over de content heen, maar duwt de content naar beneden. Ik weet niet hoe toepasselijk de shadow in dat geval dan nog is 🤷 

En heb je nog over de kleuren gesproken?

**Comment by hansgrimm** [comment]
> @hansgrimm Let op: De overlay valt niet over de content heen, maar duwt de content naar beneden. Ik weet niet hoe toepasselijk de shadow in dat geval dan nog is 🤷
OK, ik dacht dat daar nog niet echt een ei over gelegd was. maar aangepast.
zoals het goed modulair werken betaamt, een kleine aanpassinf ;)
> 
> En heb je nog over de kleuren gesproken?
Nog niet, dat doe ik hier wel.

**Comment by hansgrimm** [comment]
@mduijsens ik heb de standaard grijstinten uit de toolkit gebruikt, want de designkleuren weken af. akkoord neem ik aan?

**Comment by hansgrimm** [comment]
@mduijsens ^^ ook heb ik de grasgroen op grijze achtergrond vervangen door bosgroen i.v.m. contrasteisen WCAG.

**Comment by tfrijsewijk** [comment]
Overigens hebben we de regel dat tekst en iconen op een gekleurde achtergrondkleur altijd zwart zijn.

**Comment by hansgrimm** [comment]
> Overigens hebben we de regel dat tekst en iconen op een gekleurde achtergrondkleur altijd zwart zijn.

Geldt dat ook voor controls?

**Comment by tfrijsewijk** [comment]
> > Overigens hebben we de regel dat tekst en iconen op een gekleurde achtergrondkleur altijd zwart zijn.
> 
> Geldt dat ook voor controls?

Ik denk het wel. Zie jouw issue mbt. de "background color mixin" https://github.com/dso-toolkit/dso-toolkit/issues/2154 "Werkzaamheden" -> "Shopping Cart"

> Aan de rechterkant van de shopping cart staan verschillende iconen (verwijderen en wijzigen) deze zijn allemaal grasgroen. Dit is tegenstrijdig met document header en document list iconen
> Voor shopping cart de iconen zwart maken op dezelfde manier als document header en document list.

Volgens mij staat deze regel los van of het een control betreft. Maar daar kan UX ons natuurlijk meer over vertellen.
