### ISSUE TITLE
Definition List component modifiers: columns en headings

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#239]
In nieuwe gemaakte ontwerpen komt een patroon voor dat naar mijn mening veel lijkt op de definition list. Maar misschien is dit iets heel anders en daar wil ik even over sparren. 

![image](https://user-images.githubusercontent.com/36912722/48888653-ac85e900-ee33-11e8-95d6-8ec3f7711a77.png)

![image](https://user-images.githubusercontent.com/36912722/48888665-b4de2400-ee33-11e8-9e1f-dde2451ff5f8.png)

Nu gaat het hier om het stukje e-mailadres: asdfaf@adfs. 

Dit lijkt voor mij veel op de definition list alleen het wijkt af op een paar plekken. Deze voldoet niet aan de 200 px verhouding. Hier wordt de breedte geregeld door de columns in bootstrap het wordt niet vastgezet wat meer in lijn is met ons systeem. 

Verder is niks gehighlight, bold of heeft een andere kleur. Alles is meer neutraal. Nu zou dit bijv een neutrale versie van de definition list kunnen zijn waar niks gehighlight wordt. 

Maar vooral het niet hebben van een vaste breedte brengt mogelijk een conflict met zich mee. 

Maar de essentie van wat deze lijst communiceert vind ik heel erg lijken op de definition list. 

Een ander argument om een los component hier voor te maken is de volgende schermen. Want daar zit iets meer variatie in. 

![stap_6_bevoegd_gezag_overzicht_-_omgedraaide_termen](https://user-images.githubusercontent.com/36912722/48889707-063be280-ee37-11e8-9e3c-42b06f507bdd.png)

Daar zie je dat de achterste waardes bold zwart kunnen zijn en sommige kunnen groen bold zijn. 

Misschien zijn dit weer compleet losse componenten, of moet dit opgelost worden in een table. Ik haal hier mogelijk dingen door elkaar die niet bij elkaar horen. 

Ik ben vooral op zoek naar werkvorm(en) die nuttig zijn en geschikt zijn voor hergebruik. 

@tfrijsewijk @DjangoBlok @PieterVerheij

**Comment by DjangoBlok** [comment]
Dit is in de bovenste schermen ook op een definition list.
Het verschil is wel dat er een edit mogelijkheid in deze list zit.
Niet helemaal consequent naar mijn idee: Zet je het potloodje op de titel boven de lijst of naast de waarde bij een mouse over (of beide)
Het onderste voorbeeld roept wel vragen op:
Ik begrijp dat het bevoegd gezag bold is gemaakt, maar wellicht is het beter dat in een definition list niet te doen.
Wat zijn die groene waardes? Is dat de mouseover?
En het bovenste potloodje staat op een vreemde plek. Die hoort toch op de regel bevoegd gezag te staan?

**Comment by MichielDHVD** [comment]
Verkeerde afb  geupload  zorgt voor onnodige verwarring @DjangoBlok.  

Groene waardes zijn de verzoeknamen en deze zijn aan te passen. 

Bevoegd gezag willen we ontmoedigen dus daar is de knop elders indienen voor gebruikt. Gebruikerstesten geven aan dat mensen hier compleet over heen lezen. 

Ik snap de opmerking over inconsequentie. Bij het Mijn gegevens scherm, klik je maar een keer op het potloodje om meteen alles te kunnen aanpassen.  

Maar bij het scherm met bevoegde gezagen willen we alleen aanmoedigen om project naam te wijzigen. 

Als we dan het potloodje links boven zetten zou er een scherm moeten komen om alles meteen aan te passen. Dit zou ervoor zorgen dat bevoegd gezag aanpassen en verzoeknaam aanpassen op een pagina komt te staan. 

Dit is iets dat we willen ontmoedigen omdat gebruikers gewoon het aangewezen bevoegd gezag door het systeem moeten overnemen. 

Maar voor jouw is de bovenste wel een definition list en wat daar onder staat valt er buiten. Als ik het goed begrijp

**Comment by MichielDHVD** [comment]
Ik heb nog een variatie gevonden die veel overeenkomsten heeft met bovenstaande onderdelen. Ik ga ook nog even na bij developers hoe zij hier tegen aan kijken. Of zij een werkvorm hebben die ze makkelijk vinden. 

![32_pro_dank voor uw verzoeken](https://user-images.githubusercontent.com/36912722/48904183-e0760400-ee5d-11e8-8de1-e55875f090db.jpg)

**Comment by tfrijsewijk** [comment]
In #78 is de huidige definition list component gemaakt. Daar is voor 200px gekozen, maar met modifier classes kan een implementator daar best sturing mee gaan geven:

```html
<dl class="dso-wide">
  [..]
</dl>
```

`dl.dso-wide` zorgt ervoor dat de term-kolom breder wordt (bv 300px?) Responsive zal het nog steeds onder elkaar klappen.

Ik ben alleen niet zo gecharmeerd van `.dso-wide` en het is vrijdag dus iets mooiers ga ik niet bedenken. @PieterVerheij heb jij nog suggesties?

**Comment by DjangoBlok** [comment]
Ik begrijp wel de behoefte om een definitiegroep een kop mee te kunnen geven. 
Semantisch en qua patroon heb ik wat moeite om dat binnen de definities op te lossen.
Je zou de titel van zo'n blok er ook buiten kunnen houden toch?
Waarbij je de twee termen aan elkaar kunt plakken tot 1 titel.
Verzoek 1: Aanleg ....

**Comment by MichielDHVD** [comment]
Het aan elkaar plakken lijkt me geen goed idee. De werkvorm van de definition list met deze spatiering komt vaak terug in onze ontwerpen.  

Dus om een opsomming te maken voor de wensen van de definition list. 

Breedte aanpasbaar maken doormiddel van van verhoudingen. 

Benodigde varianten op dit moment lijken me. 

1:3 - 2:2 (Zijn er meer nodig ? ) 

Kleuren en bold
Alleen de kleur #39870C moet worden toegevoegd als class. Vervolgens samen met bold zijn er genoeg combinaties om de definition list te customizen. 
(Ik ben ook niet meer kleuren tegen gekomen in ontwerpen)  

Dan heb ik volgens mij alles toegevoegd wat dit component nodig heeft om gerealiseerd te worden.

**Comment by MichielDHVD** [comment]
Dan stel ik voor om die ook toe te voegen.

**Comment by tfrijsewijk** [comment]
Is dit niet gewoon een `table`? `Verzoek 4` is geen term die gedefinieerd moet worden, hetzelfde geldt voor "Datum ingediend".

Dit zijn 4 opeenvolgende tabellen, lijkt mij

**Comment by MichielDHVD** [comment]
Hoe bedoel je een table? Want de vormgeving matched totaal niet met dit onderwerp. Een standaard definition list zou dan meer in de buurt komen.

**Comment by tfrijsewijk** [comment]
Vormgeving mag niet bepalend zijn voor de semantische werkvorm.

>The HTML `<table>` element represents tabular data — that is, information presented in a two-dimensional table comprised of rows and columns of cells containing data.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table

>The HTML `<dl>` element represents a description list. The element encloses a list of groups of terms (specified using the <dt> element) and descriptions (provided by <dd> elements). Common uses for this element are to implement a glossary or to display metadata (a list of key-value pairs).

Nu ik de toelichting bij het `dl` element weer lees, neig ik wel weer naar de DL

Maar: Ik denk niet dat "Verzoek 4" een term is die gedefinieerd ("Aanleg rondweg") moet worden. Volgens mij is "Verzoek 4 - Aanslag rondweg" de kop van de daaropvolgende lijst.

**Comment by MichielDHVD** [comment]
Dan zouden we meer naar een suggestie van Django neigen. Die gaf dit aan

> Ik begrijp wel de behoefte om een definitiegroep een kop mee te kunnen geven.
> Semantisch en qua patroon heb ik wat moeite om dat binnen de definities op te lossen.
> Je zou de titel van zo'n blok er ook buiten kunnen houden toch?
> Waarbij je de twee termen aan elkaar kunt plakken tot 1 titel.
> Verzoek 1: Aanleg ....

Laat me dit even bespreken met de rest. Want dat zou makkelijk de oplossing kunnen geven denk ik.

**Comment by MichielDHVD** [comment]
Het aan elkaar plakken van de term verzoek zal niet werken. Stuur even een afbeelding mee, het wordt niet als wenselijk gezien. Ook niet in de flow van verschillende schermen waar deze werkvorm voor komt. 

<img width="866" alt="screen shot 2019-02-13 at 08 28 56" src="https://user-images.githubusercontent.com/36912722/52694676-c171a480-2f6a-11e9-8233-fd018fbb603a.png">


Maar om de definition list zuiver te houden zal er dus een definition list header moeten komen? Is dat een werkbare situatie? 

@tfrijsewijk

**Comment by MichielDHVD** [comment]
Heb je al de kans gekregen om hier naar te kijken. 

Mijn voorstel hierin was om een definition list header te maken. 

@tfrijsewijk

**Comment by tfrijsewijk** [comment]
Opgeleverd in 7.0.0: https://www.dso-toolkit.nl/7.0.0/components/detail/definition-list.html

Het is toch een "ordinaire" dt/dd geworden. De alternatieven maakte het er allemaal ook niet veel fraaier op. Laten we het eerst zo proberen.

**Comment by MichielDHVD** [comment]
Top mooi werk! verplaatst naar done
