### ISSUE TITLE
Call to action component

### ISSUE THREAD

**Issue by Poofy83** [dso-toolkit/dso-toolkit#24]

**Comment by Poofy83** [comment]
Tijdens de button refactor is Bootstrap's btn-primary visueel identiek aan de CTA geworden. Deze modifier kan ook op een anchor gezet worden.

`<a href="#" class="btn btn-primary">
  Volgende
</a>`

Ik zet mijn vraagtekens bij het bestaansrecht van een ander component, wat visueel identiek is. Hoe denk jij hierover?

/Original commenter: Thomas - 28-02-18

-----

Deze gaan inderdaad samenvallen.

Met de uitleg van de tekst uit de Button ticket zal een extra los component niet nodig zijn. Dat is alleen maar dubbelop.

Dus de call to action mag wegvallen omdat de er genoeg uitleg bij de buttons zelf zal staan.

/Original commenter: Michael - 28-02-18

**Comment by VolleMelk** [comment]
Opgegaan in #25
