### ISSUE TITLE
Begrippen in tekst

### ISSUE THREAD

**Issue by DjangoBlok** [dso-toolkit/dso-toolkit#240]
In de viewer hebben we een speciale interactie voor begrippen nodig.
Van een begrip kan de betekenis worden achterhaald door er op te klikken.
Wanneer er in een tekst een begrip staat, moet deze zichtbaar zijn gemarkeerd op zo'n manier dat het duidelijk is dat het wat anders is dan een gewone link.
Zie bijgevoegd voorstel.
In HTML kan hiervoor de `<abbr>` tag voor gebruikt worden.
Zie werkend voorbeeld: https://veiliginternetten.nl/doe-de-appk-check/
![ovrek-283 begrippen](https://user-images.githubusercontent.com/34900082/49218443-bcbc3c00-f3d0-11e8-91ff-b277ef9b91b0.png)

**Comment by DjangoBlok** [comment]
@MichielDHVD hebben jullie iets vergelijkbaars? Ik heb het [i] icoontje weggehaald.

**Comment by MichielDHVD** [comment]
@DjangoBlok Wij hebben niet iets vergelijkbaars. Acht jij een icoontje nodig. In lopende teksten vind ik dat er zo min mogelijk icoontjes in moeten staan. Dus het weghalen van het icoontje is prima. 

Het stippellijntje ziet er prima uit zou onderscheidend genoeg moeten zijn van standaard links (Deze zijn momenteel groen en niet geunderlined) 
Ik ga het even aan het team voorleggen of we deze interactie vorm zo willen gaan introduceren. 

Het kruisje in het blauwe blok is wel nieuw. We hebben in het toelichtingen blok een ander soort kruisje gebruikt 

https://github.com/dso-toolkit/dso-toolkit/issues/203

Deze is groen dus niet toepasbaar op dit blauw blok. Maar lijkt me slim om zulke blokken proberen gelijk te houden in vormgeving en interactie vormen

**Comment by DjangoBlok** [comment]
Prima.
Ik ben het helemaal eens met weghalen van het icoon.
Ander soort kruisje is ook prima.

**Comment by tfrijsewijk** [comment]
@MichielDHVD: Plan jij deze in? Ik denk dat dit pas bij de volgende release meekan.

**Comment by MichielDHVD** [comment]
Zal ik alvast een Project board gaan opzetten voor de release voor volgende increment?

**Comment by tfrijsewijk** [comment]
Ja, klinkt goed

**Comment by PieterVerheij** [comment]
Hij staat nog 'To be specified' maar vormgeving is afgetikt? Of moet het sluitkruijse nog ontworpen worden?

**Comment by DjangoBlok** [comment]
@tfrijsewijk Deze is inmiddels afgestemd met @MichielDHVD 
We hebben ook een werkende versie. Kunnen jullie daar iets mee om hem aan de toolkit toe te voegen?

**Comment by DjangoBlok** [comment]
Ja,
https://dso-viewer.acceptatie.kadaster.nl/dso-viewer/document/NL.IMRO.0518.OP0274
Artikel 3 Regels Verkeer, Dan 9.1 -> Ambulante handel
Ik zie wel dat styling nog niet heelmaal 100% in orde is.

**Comment by PieterVerheij** [comment]
@MichielDHVD Is dit de juiste stijl van het sluitkruisje? Ik heb het idee dat er meerdere varianten door elkaar heen lopen?

**Comment by PieterVerheij** [comment]
Is het aannemelijk dat er rich-content in dit blok komt?

**Comment by DjangoBlok** [comment]
Verwacht ik niet.

**Comment by tfrijsewijk** [comment]
Hoe willen we dit technisch vorm geven? In de basis is de markup niet heel moeilijk. Het begint allemaal met een `abbr` element.. Maar dan?

Ik speel met de gedachte om een CSS-only oplossing aan te leveren.

```html
<p>The Space Shuttle was a partially reusable low Earth orbital spacecraft system operated by the U.S. <abbr title="National Aeronautics and Space Administration">NASA</abbr> as part of the Space Shuttle program</p>
```

Met pseudoclasses en CSS functies kan ik een heel eind komen. Ik zat aan het volgende te denken:

```scss
abbr:hover::after {
  content: attr(title);
}

abbr:hover::before {
  left: var(--pointer-position);
}
```

Scriptend moet bepaald worden waar het woord staat en moet worden meegegeven als CSS variable:

```html
<abbr style="--pointer-position" title="..">...</abbr>
```

Pseudoelements worden niet door screenreaders opgelezen, dus de screenreader blijft verantwoordelijk voor het juist afvangen van `abbr`-elementen. Het nadeel is dat het op `:hover` wordt gestyled, er is geen `:focus` TENZIJ er een `tabindex="0"` wordt gezet maar dat is weer heel vervelend voor een gebruiker die TABbed door zijn pagina.

De grote vraag in dit concept is: Wordt de beschrijving in het blauwe vlak dezelfde tekst die in het title attribuut staat? Ik zou aanraden van wel, anders is het NOG een tekst die onderhouden moet worden.

Het ontwerp laat nu zien dat de begeleidende TUSSEN de tekst valt. Ik denk dat dat erg onrustig is, kan het er niet beter overheen vallen? Mochten we voor de CSS oplossing gaan toont de schrijving al zodra er wordt gehovered.

Een scriptende oplossing is ook een optie, dan kan er met een onClick handler worden gewerkt en is er meer controle over het tonen van de begeleidende tekst (en nu ik dit type: hoe zouden we `:hover` op een tablet afvangen... Misschien toch maar scriptend?)

Dus.. Wat willen jullie? Hoe zien jullie de markup voor je? Scriptend zat ik aan iets als dit te denken:

```html
<abbr title="InfoProjects" class="dso-open">IP</abbr><span class="dso-expansion" aria-hidden="true">InfoProjects</span> <!-- met extra element -->

<abbr title="InfoProjects" class="dso-open">IP</abbr> <!-- zonder extra element, begeleidende tekst wordt getoond dmv content: attr(title) -->
```

**Comment by DjangoBlok** [comment]
@tfrijsewijk De bedoeling was om de tekst niet bij een hover te laten verschijnen maar na een click. Hij blijft dan staan tot hij weer wordt weggeklikt. Het wordt te onrustig als je dit bij hover doet. En dat werkt inderdaad ook niet op tablets.

Ik weet niet of je dat qua code helpt...

Zoals gemeld kun je de interactie zien op: https://veiliginternetten.nl/doe-de-appk-check/ (onder de video)
Ik weet niet of deze code WCAG proof is, maar zie dat ze daar ook met <abbr> werken

**Comment by PieterVerheij** [comment]
Links of rechtsom: dit moet ook gaan werken voor `dnf` en niet alleen voor `abbr`.

**Comment by tfrijsewijk** [comment]
OK, dus de trigger voor het tonen van de begeleidende tekst wordt scriptend gezet.

Het aangedragen voorbeeld heeft toevallig de begrippen aan het einde van de zin staan. Houden jullie er rekening mee dat de zin wordt "opgebroken" ? Zie het volgende ASCII art voorbeeld:

```
De bedoeling was om de tekst niet bij een hover te laten verschijnen maar na
een click. Hij blijft dan staan tot hij weer wordt weggeklikt. Het wordt te
onrustig als je dit bij hover
                          ^
***************************************************************************
* The :hover CSS pseudo-class matches when the user interacts with an     *
* element with a pointing device, but does not necessarily activate it.   *
***************************************************************************

doet. En dat werkt inderdaad ook niet op tablets.
```

Het element die de begeleidende tekst toont komt na het woordje "hover" en voor het woordje "doet" te staan. Als dit ongewenst is zijn daar ook wel oplossingen voor, maar dan maken we het wel vreselijk complex...

Een makkelijkere oplossing zou zijn dat het blauwe blok waar de begeleidende tekst in staat over de tekst zweeft

**Comment by tfrijsewijk** [comment]
Hoe meer ik lees over het `abbr` element hoe minder geschikt ik het voor deze issue vind. Maar een alternatief kan ik ook niet vinden.. 

Wat willen we mbt. toegankelijkheid? Hoe/wanneer gaat een screenreader deze tekst oplezen? Hoe kan iemand zonder muis deze tekst te zien krijgen?

* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/abbr

**Comment by tfrijsewijk** [comment]
Bedoel je met "de Mouseover", de `title` ?

**Comment by DjangoBlok** [comment]
Ik weet niet zeker of ik je vraag goed begrijp. "toon uitleg" zou in de title kunnen staan.
Is dat wat je bedoelt?

**Comment by tfrijsewijk** [comment]
Ja. We gaan 't oppakken

**Comment by tfrijsewijk** [comment]
Ik heb bekeken of https://veiliginternetten.nl/doe-de-appk-check/ als uitgangspunt kan dienen voor onze implementatie. Ik denk van niet. Deze site is niet toegankelijk:
* Het lukt mij niet om zonder muis een begrip te tonen
* Mijn screenreader (ChromeVox) leest op geen enkele manier het begrip voor.

Ik heb meer nodig dan alleen een ontwerp.

Mijn overwegingen:

1) Het abbr element gebruiken
```html
<p>Een <abbr title="Definitie">begrip</abbr><span>Definitie</span></p>
```
De abbr heeft een title met de Definitie. De abbr krijgt een `onclick` event waarna scriptend de een `span` element met de definitie wordt getoond.

* Een mouse-over toont de title
* Een click toont de definitie zoals in het ontwerp (blauw en alinea breed)
* Niet mogelijk om zonder muis de definitie te tonen: De abbr zit niet in de taborder en kan niet met een toetsenbord worden benaderd
* Mijn screenreader (ChromeVox) leest nooit de definitie op

2) Een button
```html
<p>Een <button type="button" title="Definitie">begrip</button><span>Definitie</span></p>
* Een element wat gemaakt is om inputs af te vangen, doet default mee in de taborder
* Geen `abbr` element
* Doordat de button meedoet in de taborder is het onrustig om tekst te laten oplezen. Focussen naar volgende stuk tekst gaat altijd langs mogelijke buttons en dus krijg je geen lopend verhaal.

Verder is mijn opmerking hier https://github.com/dso-toolkit/dso-toolkit/issues/240#issuecomment-461473134 nog steeds van toepassing.

Ik zet 'm even bij @MichielDHVD, kunnen we hier nog een keertje over speccen?

**Comment by DjangoBlok** [comment]
Van wat ik heb gelezen, wordt het <abbr> voor afkortingen wel aangeraden.
Als ik het goed begrijp is het in de screenreader in te stellen hoe deze met het <abbr> element omgaat (voorlezen of niet)
Mocht je willen afwijken van het <abbr> element. Zou een link variant dan niet logischer zijn in plaats van een button. 

In dit specifieke geval gaat het niet echt om afkortingen en vraag ik me af of je als gebruiker wil dat de volledige tekst van een begrip steeds wordt voorgelezen.
Hier is overslaan niet superkritisch omdat in regeldocumenten de hier gebruikte definities ook nog apart zijn gedefinieerd in de lopende tekst. En de begrippen dus op deze manier ook toegankelijk zijn. 

Maar ik ben met je eens dat het dan niet de ideale oplossing is.

**Comment by tfrijsewijk** [comment]
Ik heb het niet eens over oplezen, maar een `abbr` is uit zichzelf niet focusable. Toetsenbord gebruikers zullen dus nooit de uitleg kunnen openen.

Dit kan wel gerealiseerd worden met een `tabindex` attribuut maar dan gaat het weer meedoen in het oplezen van de tekst voor screenreaders.

Wat betreft link/button:
* Een anchor zonder href linkt niet (en is ook niet focusable met het toetsenbord)
* Een anchor met href moet wel ergens naar anchoren: de URL moet aangepast worden
* Een button is de ideale kandidaat om de state van de applicatie aan te passen (uitleg open/dicht) zonder de URL aan te passen

Met de wens die in dit ticket wordt geuit spelen we pingpong:
* Of: we komen de screanreaders tegemoet (geen focussable `abbr` - want de screenreader regelt ZELF hoe met `abbr` om te gaan)
* Of: we komen de toetsenbordgebruikers tegemoet (focusable `abbr` zodat definitie kan worden opengeklapt) en de screenreader leest "raar" op (bevestiging nodig)

Maar om toch ook ergens te komen: We gaan het naar beste inzicht maken en voorzien deze functionaliteit van een goede demopagina. Deze demopagina kan dan aan de WCAG/screenreader/toegankelijkheids specialisten worden voorgelegd

**Comment by MichielDHVD** [comment]
Goed voorstel om het even te bouwen en vervolgens de demopagina te gebruiken als test. Want we kunnen waarschijnlijk wcag compliant zijn zonder de screenreaders expliciet te bedienen maar voor de usability van screen reader gebruikers is het mogelijk wel een kriem.  

Allemaal afweging die beter gemaakt kunnen worden op gerealiseerde software

**Comment by tfrijsewijk** [comment]
@timveld alvorens wij dit component gaan bouwen, heb jij hier nog gedachtes/tips over?

**Comment by timveld** [comment]
Interessante discussie, ben hier even ingedoken. Ik vraag me af of we hier <abr> moeten gebruiken. 

Het gaat hier niet om afkortingen, maar om definities. De <a href="https://www.w3schools.com/tags/tag_abbr.asp">W3Schools pagina over de abr tag</a> stelt onder meer: 
"Marking up abbreviations can give useful information to browsers, translation systems and search-engines." 
Het lijkt er ook op dat abr vooral hiervoor bedoeld is: geen ondersteuning in screen readers of op touchscreens. Abr gebruiken voor een begripsomschrijving is dus 'het verkeerde gereedschap voor deze klus' en kon wel eens tot ellende leiden met bijvoorbeeld zoekmachines en vertaalsoftware. Dus als het geen afkortingen zijn, gebruik dan ook geen abr tag... Er is ook een <a href="https://www.w3schools.com/tags/tag_dfn.asp">dfn tag</a> maar die doet evenmin wat we hier willen. 

Ik denk dus dat we vooral zelf een scripted oplossing moeten bouwen. Deze oplossing moet in ieder geval voldoen aan:
* Wordt door screen reader gezien als link of knop
* Focusable met toetsenbord
* Bij klikken moet de definitie worden voorgelezen, 2 opties:
	* Definitie wordt als een alert / tooltip weergegeven en DMV een Aria alert uitgesproken. Dat is prima als het gaat om korte omschrijvingen; je zou er dan zelfs voor kunnen kiezen om bij klikken de 'popup' na een paar seconden automatisch te laten verdwijnen zodat de gebruiker niet naar een sluitknopje hoeft te navigeren (bij hover blijft hij staan zolang de muis op het begrip rust).
	* Maar ik vermoed dat het om langere omschrijvingen gaat, dan zou ik gewoon een klein poput venstertje openen waar de focus naartoe wordt geplaatst zodat de gebruiker de definitie rustig kan lezen; sluitknopje verplaatst de focus terug naar de oude plaats (link naar definitie)


Afkortingen en definities kun je overigens wel met abr en dfn tags markeren. Volgens WCAG 2.1(AA) is dat niet verplicht maar op niveau AAA dacht ik wel en het is naar de toekomst toe beter dat we dit zo veel mogelijk hebben.

**Comment by DjangoBlok** [comment]
Nog even de uitgangspunten op een rij:
**De basis**
1. In de viewer wordt juridische regelgeving getoond.
2. Begrippen en bijbehorende uitleg maken deel uit van een omgevingsdocument.
3. Voor een gebruiker is het nodig de uitleg van een begrip te kunnen lezen om de regel goed te kunnen interpreteren.
**Bij voorkeur**
4. Het is voor gebruikers prettig als ze de uitleg van een begrip kunnen lezen, zonder direct de tekstuele context te moeten verlaten.
5. Functioneel lijkt dit erg op de preview die bij wikipedia wordt getoond als een link/woord wordt geactiveerd.

**Comment by PieterVerheij** [comment]
Hi Django, heb je voor mij een sketch (of measure) bestand met de definitieve vormgeving? Ik zie nl. twee versies: met en zonder linker en rechter borders op de uitklapper?

**Comment by PieterVerheij** [comment]
Hi @timveld , zie https://www.dso-toolkit.nl/_240.Begrippen-in-tekst/components/detail/description.html . 
Is dit een constructie die werkbaar is? Scriptend wordt `aria-hidden` op de `.dso-description-content` getoggled (van true naar false).

**Comment by MichielDHVD** [comment]
Het kruisje is nu groen. Is het mogelijk dat deze zwart wordt of #191919 om precies te zijn?

**Comment by tfrijsewijk** [comment]
Uiteraard, het behoeft nog verdere finetuning:

![image](https://user-images.githubusercontent.com/9696261/69322784-c96f1b00-0c45-11ea-8e0f-fa8e0f47320b.png)

Maar de semantische werking is nu niet anders en voordat we verder gaan willen we van @timveld horen wat hij van de opzet vindt

**Comment by DjangoBlok** [comment]
Ok goed werk! Wachten we eerst even op reactie van @timveld 
Kruisje mag inderdaad zwart. Kader kan denk ik aan de zijkant doorlopen. 
Als iemand andere suggesties heeft voor vormgeving ook prima.

**Comment by timveld** [comment]
1. Als ik het goed begrijp moet de term HTML klikbaar zijn, maar in het voorbeeld leest NVDA hier geen knop / link in. In de code lijkt het alsof een button is gebruikt met daarbinnen een paragraaf, of misschien begrijp ik iets helemaal verkeerd?  
2. De sluiten knop wordt wel goed voorgelezen, maar is sr-only in dit geval de beste manier om hem te labelen?
3. Wil dit goed werken dan moet de focus op de juiste manier verspringen, dat ligt bij javascript / implementator. Komt neem ik aan documentatie over?

**Comment by tfrijsewijk** [comment]
>Als ik het goed begrijp moet de term HTML klikbaar zijn, maar in het voorbeeld leest NVDA hier geen knop / link in.
Een van mijn zorgen is dat een klikbaar/focusbaar element in een tekst juist de flow van een screenreader onrustig maakt. Maar laten we vooral wat proberen.

Wat kunnen we er het beste van maken? Bovenstaande discussie gaat ook over "wat" het moet zijn. Een `a` of `button` (zelfs `abbr` en `dfn` met `tabindex=0` zijn voorbijgekomen).

>In de code lijkt het alsof een button is gebruikt met daarbinnen een paragraaf, of misschien begrijp ik iets helemaal verkeerd?
Er staat geen paragraaf in een button. Er staat een button in span in een paragraaf.

>De sluiten knop wordt wel goed voorgelezen, maar is sr-only in dit geval de beste manier om hem te labelen?
Ik denk van wel. Wat voor alternatief stel je voor?

>Wil dit goed werken dan moet de focus op de juiste manier verspringen, dat ligt bij javascript / implementator. Komt neem ik aan documentatie over?
Welke focus moet van waar naar waar verspringen?

**Comment by timveld** [comment]
1. Link of button begrippen: ik zou van de begrippen links maken met als argument dat het uiteindelijk een verwijzing is naar meer informatie; dat deze in een soort popup opent maakt nog niet dat de button in de eerste plaats een actie uitvoert. Links verstoren de flow van de tekst ook minder dan buttons. Dat de screen reader af en toe het woordje link door de tekst gooit kan vervelend zijn maar is niet te voorkomen, je zult toch op de een of andere manier duidelijk moeten maken dat het begrip aanklikbaar is. Als gebruiker van een screen reader ben ik hier wel aan gewend, Wikipedia doet het ook zo. Zo lang maar niet ieder woord een aanklikbaar begrip is maar het zal om hooguit 2 of 3 begrippen per paragraaf gaan. 
2. Sr-only op button: ik heb dit nader uitgezocht en sr-only is in dit geval (button met decoratief icoontje) inderdaad het beste. Het elegante aan deze oplossing is dat het ook goed gaat als je CSS uitschakelt (text-only browsers), met alternatieven title / aria-label ben ik daar niet zo zeker van en die worden bovendien minder goed ondersteund. Aanpak met label / aria-labeledby is alleen maar omslachtiger en heeft geen voordelen, andere opties zie ik niet. 
3. Focus: als ik op een begrip klik, dan moet de focus van de screen reader naar het dialoogje springen wat de omschrijving van het begrip bevat; blijft de focus op dezelfde plaats dan komt het over alsof er geen reactie op mijn klik is. Als ik het dialoogje met de sluiten button sluit dan moet de focus weer terugkeren naar het punt waar ik aan het lezen was. Wat je daarvoor precies moet doen weet ik niet (hangt ook van gebruikte javascript oplossing af) maar kan ik wel helpen uitzoeken als er een werkende implementatie is, het kan zeker goed opgelost worden. 
4. Ook dacht ik nog aan de optie de begripsomschrijving als aria-alert uit te voeren, dan hoef je niet met de focus te springen en is misschien zelfs een oplossing mogelijk zonder sluitknopje (on mouse over popup met slimme oplossing voor keyboard / touch). Iets ingewikkelder maar kunnen we in het achterhoofd houden.

**Comment by PieterVerheij** [comment]
3. Bij het openen van het dialoogje kan de focus naar de sluiten-knop springen. Het enige is dat dan of er geen links en andere focusable componenten in de tekst mogen staan als het knopje in de flow na de tekst komt, of dat we de flow moeten aanpassen en het sluiten-knopje voor de tekst in de dialoog komt te staan.

Zou dat werkbaar zijn, @timveld ?

**Comment by timveld** [comment]
Het probleem van de focus naar een dialoog verplaatsen speelt op meer plaatsen waar een dialoog wordt weergegeven, zoals het welkomstdialoog op als je de site voor het eerst opent. Volgens mij moeten we daar dus een algemene richtlijn voor maken of is die er al? Ter inspiratie zie https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/dialog.html 
De focus op het sluitknopje zetten is niet ideaal; de screen reader zou moeten beginnen met het lezen van de bovenste heading / melding, het OK / sluiten knopje daaronder lijkt me logischer. Weet niet of dit technisch haalbaar is, bij de cookie melding van NS lijkt het wel goed te gaan (daar hebben ze het dialoog in een frame gezet wat misschien ook niet geweldig is) In toolkit overleg (ben er bij) bespreken, waarschijnlijk aan mij de taak om de mogelijkheden te onderzoeken en een advies te geven maar dan moeten we ook even inventariseren waar dit probleem speelt.

**Comment by gofix** [comment]
Foutje in huidige implementatie:
```
<span class="dso-description-term">Html</span>
```
... zal een `<a>` moeten zijn, en dan natuurlijk met een `href="#toelichting"` naar de `#toelichting`

**Comment by PieterVerheij** [comment]
@timveld @MichielDHVD Was de conclusie afgelopen donderdag nu dat de huidige opzet van het sluitkruis toch ok is?

**Comment by timveld** [comment]
De sr-only beschrijving van de knop is goed, de span moet vervangen worden door een a. Conclusie was dat we het begrip een anker link maken waarbij de begripsomschrijving uitklapt en de focus naar het anker verspringt, mijn idee was om de sluiten knop ook een anker link (of button) te maken die het begrip sluit en terugspringt naar het punt in de tekst waarvandaan hij werd geopend, met de nodige scripting is dit zelfs mooi te maken in geval het begrip meerdere keren voorkomt. Zie ter inspiratie de manier waarop genummerde referenties werken in grotere Engelstalige wikipedia artikelen.

**Comment by PieterVerheij** [comment]
Hi @timveld, ik heb het aangepast met anchor links. Pagina had bij mij een harde refresh nodig om de wijzigingen te kunnen zien.

**Comment by timveld** [comment]
Wat je hier hebt gemaakt is geen dialoogje meer, het is iets wat uitklapt. Vind ik wel mooi. Maar moet het in dit geval niet gewoon een collapse / expand link zijn met aria-collapsed / expanded? Veel simpeler dan die ankers en het is ook met de muis wel handig als je de beschrijving weer kunt inklappen met dezelfde link waarmee je hem uitklapt...

**Comment by PieterVerheij** [comment]
Ik denk dat het wel fijn is als je als gebruiker een visuele clue hebt dat je hem weer ook kunt sluiten, dus ik zou een sluitenkruis als gebruiker wel waarderen. 
Ik heb op de gelinkte term nu een `aria-collapsed` en `aria-controls` gezet. 
De aanpassing staat op https://www.dso-toolkit.nl/_240.Begrippen-in-tekst/components/detail/description.html

**Comment by timveld** [comment]
@PieterVerheij  er lijkt niets te zijn veranderd aan de code? Die visuele hint is zeker belangrijk jk, als ik het goed zie heb je het zwarte kruisje vervangen door een soort pijltje onder de link en dat is goed. Waar ik nog een beetje mee worstel is dat de begripsomschrijving in dit ontwerp "tussen de tekst doorgegooid wordt" terwijl een link met omschrijving "sluiten" suggereert dat je een dialoog sluit,, misschien zou "verbergen" een betere formulering zijn. Ik denk wel dat de huidige oplossing in ieder geval acceptabel is als die aria-collapsed er aan wordt toegevoegd, ik zal nadenken of ik een betere oplossing kan bedenken maar je kunt hem in deze vorm releasen.

**Comment by PieterVerheij** [comment]
@timveld Ik denk dat er sprake is van een hardnekkige cache. Probeer even een harde refresh: ik zie wel de `.aria-collapsed`.
Ik zal de linktekst aanpassen.

**Comment by timveld** [comment]
@PieterVerheij  nu werkt het wel. Alleen werkt het niet, aria-collapsed bestaat niet (moet aria-expanded zijn).

**Comment by PieterVerheij** [comment]
Oepsie: Pieter gaat mee in de zak van Sinterklaas.

Maar aangepast...

**Comment by timveld** [comment]
@PieterVerheij  gelukkig dat die stoomboot net is weggevaren, want het is ook niet aria-expandend. Eigenlijk zou er een XHTML validator in de buildstraat moeten zitten zodat je bij dit soort fouten automatisch een waarschuwing krijgt,

**Comment by timveld** [comment]
Ik kwam begripsomschrijvingen tegen bij de SVB: https://www.svb.nl/nl/pgb/storyline-pgb-in-het-kort#storyline-2 (klik op volgende dan wordt zorgverlener omschreven) In deze vorm is het absoluut niet toegankelijk (wel toegankelijk te maken natuurlijk, even een opdrachtje scoren haha) maar in dit ontwerp zitten goede elementen. Wat aan ons ontwerp wel duidelijk beter is: de omschrijving verbergt bij ons niet de tekst.
