### ISSUE TITLE
Veel witruimte tussen legend en div.dso-field-container in fieldset

### ISSUE THREAD

**Issue by Mennowm** [dso-toolkit/dso-toolkit#2404]
De 'form fieldset > legend' krijgt een 'margin-bottom: 32px' dit zorgt een behoorlijke lege ruimte. Als deze margin-bottom zou weg vallen heeft de legend zelf ook nog een 'margin-bottom: 24px'. Ook dan is er nog behoorlijk wat witruimte.

![image](https://github.com/dso-toolkit/dso-toolkit/assets/41022367/a1768700-eb9e-43a2-b9da-b03473f1c5e3)

**Comment by tfrijsewijk** [comment]
@hansgrimm kan jij een analyse doen?

**Comment by hansgrimm** [comment]
Hallo9 @Mennowm als ik op de pre kijk, dan doen jullie daar iets anders met de legend< waardoor de kwestie met de margin niet speelt:
![Image](https://github.com/dso-toolkit/dso-toolkit/assets/506527/cedcdc97-bc29-4e89-9e79-6c4f43621228)
![Image](https://github.com/dso-toolkit/dso-toolkit/assets/506527/2e9cf6be-7f93-4426-bfb0-ee55d9515bad)
Ik vind die oplossing enigszins 'questionable' maar het lost de afstandskwestie wel op. is bovenstaande een andere versie?

**Comment by Mennowm** [comment]
Hoi Hans, dat is op een andere plek waar de situatie ook echt anders is. In de situatie waar het fout gaat zit een form `<fieldset className="form-group">` omheen.

**Comment by hansgrimm** [comment]
@Mennowm Herb je een url waar dat in het wild voorkomt?

**Comment by Mennowm** [comment]
@hansgrimm ik kan wel een url geven maar daar kan je niet bij omdat het in aanvragen zit. Hiervoor moet je ingelogd zijn. Ik weet niet of je een omgevingsloket account hebt op pre?

**Comment by hansgrimm** [comment]
> @hansgrimm ik kan wel een url geven maar daar kan je niet bij omdat het in aanvragen zit. Hiervoor moet je ingelogd zijn. Ik weet niet of je een omgevingsloket account hebt op pre?

Volgens mij niet

**Comment by tfrijsewijk** [comment]
@Mennowm Wat staat er in de `<fieldset class="form-group">` ?

Form groups moeten altijd voorzien zijn van een typering: `<div class="form-group dso-radios">`. Daarnaast is het element meestal een `div`, uitgezonderd Checkboxes en Radios.

**Comment by hansgrimm** [comment]
Checkboxes en radios zijn impliciet al een setje, daar hoeft niet et alle geweld een fieldset omheen, wat mij betreft liever niet zelfs. Fieldsets zijn bedoeld om grote complexe formulieren in behapbare stukken te hakken, niet om bepaalde controls te wrappen.

**Comment by Mennowm** [comment]
Dit issue is in overleg met @hansgrimm (9 nov 2023) opgelost aan onze kant. Daar is de fieldset ook weggehaald. Dit issue kon gesloten worden. Hierbij is deze gesloten
