### ISSUE TITLE
Veel witruimte onder dso-accordion

### ISSUE THREAD

**Issue by Mennowm** [dso-toolkit/dso-toolkit#2405]
Er zit veel witruimte onder accordions. Er wordt op de class .dso-accordion een 'margin-bottom: 32px' gebruikt. Dit geeft wel veel witruimte een 16px zou hier beter passen.

![image](https://github.com/dso-toolkit/dso-toolkit/assets/41022367/93aaffed-c9cc-4478-9abf-0b93382969c9)

**Comment by MYpenburg** [comment]
Deze afstand is prima hier, ik stel voor om deze issue te sluiten.
