### ISSUE TITLE
Searchbar z-index bug

### ISSUE THREAD

**Issue by daverhelst** [dso-toolkit/dso-toolkit#241]
De searchbar heeft een klein issue omtrent z-indexing. Het label, welke klikbaar is en de input moet openen, ligt bovenop de input. Als er dus focus is op de input, die de boel open houdt, kun je nog steeds op het "verborgen" label klikken en dat ziet er een beetje funky uit.

![dso-searchbar-bug](https://user-images.githubusercontent.com/5871330/49280898-898ab300-f48b-11e8-8b26-fe3817821ae7.gif)

**Comment by MichielDHVD** [comment]
Gezien en verplaatst naar Done
