### ISSUE TITLE
Banner: Responsive behavior

### ISSUE THREAD

**Issue by MYpenburg** [dso-toolkit/dso-toolkit#2414]
Probleem: het onderwerp van het beeld is in de huidige narrow view niet te herkennen.

**Huidige wide view landingspagina's:**
<img width="1628" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/7289928/77b8e9e4-205f-40af-8d39-799231de9f9e">
<hr>

**Huidige narrow view landingspagina's:** 
<img width="725" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/7289928/eb8cde50-b88c-4d2e-bdfd-ca6c366944b4">
<hr>

**Gewenste narrow view: zoals de highlightboxes, maar dan niet in een box maar 100% width:**

<img width="662" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/7289928/84da5ee1-affe-406b-a7cc-4dcc427c221c">

**Comment by hansgrimm** [comment]
Bootstrap layoutje. hele markup moet sowieso op de schop.
