### ISSUE TITLE
Ozon Content: Tabel toevoegingen STOP implementeren in Ozon documentweergave

### ISSUE THREAD

**Issue by DjangoBlok** [dso-toolkit/dso-toolkit#2423]
De STOP standaard kent een aantal specifieke toevoegingen voor tabellen.  (https://koop.gitlab.io/STOP/standaard/1.0.4/tekst_xsd_Element_tekst_table.html
). 
meer informatie over tabellen: https://koop.gitlab.io/STOP/standaard/2.0.0-rc/regeltekst_tabel.html

Die specifieke toevoegingen worden nu genegeerd.  
In deze story worden deze specifieke toevoegingen opgepakt in de documentweergave. 

- colsep
- frame
- orient
- pgwide
- rowsep
- tabstyle

**Comment by tfrijsewijk** [comment]
@DjangoBlok Ik wil deze aan @iterox geven, kunnen jullie elkaar vinden om over de inhoud te praten?

**Comment by iterox** [comment]
@DjangoBlok Is er een ontwerp? Dat ik kan zien wat de visuele effecten van deze 6 table-attributen zijn?

**Comment by DjangoBlok** [comment]
Ja, lijkt mij ook,. 
@tfrijsewijk weet jij wat deze toevoegingen betekenen/doen?

Bij colsep en rowsep kan ik me wel iets voorstellen. 
colsep: 1 (geeft een lijntje tussen kolommen)  0 (geeft geen lijntje tussen kolommen)
rowsep: 1 (geeft een lijntje tussen rijen) 0 (geeft geen lijntje tussen de kolommen)

In document component context geven we beide default weer en zou 0 het lijntje moeten verbergen.

**Comment by tfrijsewijk** [comment]
Overgeslagen tijdens de refinement ivm #2136 en Ozon/Viewer/Toolkit STOP inventarisatie.

**Comment by iterox** [comment]
@iterox Gaat de discrepantie tussen standaard 2.0.0-rc en de huidige implementatie inde dso-toolkit inventarisen.

**Comment by iterox** [comment]
https://www.oasis-open.org/specs/tm9901.htm bevat nadere specificering van de 6 specifieke toevoegingen voor tabellen.

**Comment by iterox** [comment]
https://koop.gitlab.io/STOP/standaard/2.0.0-rc/tekst_xsd_Element_tekst_table.html verwijst naar https://www.oasis-open.org/specs/tm9901.htm 

Op basis van deze documentatie en een aantal tabellen uit Besluit Kwaliteit Leefomgeving op wetten.overheid.nl en test.document-viewer.dso.kadaster.nl en de xml van de tabellen uit de response van het OZON enpoint api/presenteren/v7/regelingen/_akn_nl_act_mnre1034_2018_OW048813c4cf59d4a689xx2bc9x82e5a/tekststructuur zijn er 3 van de 6 attributen relevant:

1. colsep
Definieert de aanwezigheid van een scheidingslijn tussen kolommen
Mogelijke waarden: 0 of 1
Waarde 0 betekent geen lijn aan de rechterzijde van de entry.
Waarde 1 betekent een lijn aan de rechterzijde van de entry.
Wordt genegeerd voor de meest rechter kolom: daar geldt de waarde van attribuut frame.
Dit attribuut kan voorkomen op table, tgroup, colspec, tbody, row of entry. De aanwezigheid van colsep op het diepst geneste niveau bepaalt de waarde voor de onderliggende niveau’s.
2. rowsep
Mogelijke waarden: 0 of 1
Waarde 0 betekent geen lijn onder de entry.
Waarde 1 betekent een lijn onder de entry.
Wordt genegeerd voor de laatste rij van de tabel.
Dit attribuut kan voorkomen op table, tgroup, colspec, tbody, row of entry. De aanwezigheid van rowsep op het diepst geneste niveau bepaalt de waarde voor de onderliggende niveau’s.
3. frame
Mogelijke waarden: top|bottom|topbot|all|sides|none
Bepaalt de lijnen aan de buitenkant van de tabel

De attributen pgwide, orient en tabstyle hebben momenteel geen relevantie binnen het DSO.

**Comment by iterox** [comment]
De styling van de lijnen volgt die van het table component
