### ISSUE TITLE
Webfont Asap: Strikethrough in Firefox

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#2424]
Bug in het webfont Asap: een strikethrough toont in firefox als een underline.
Zie https://github.com/google/fonts/issues/2436

**Comment by hansgrimm** [comment]
Bug nr. 2: font-weight 500 toone in sommige OS/browser combinaties als bold (700).
Zie https://dso-toolkit.slack.com/archives/G01AZEKEXUZ/p1699860068167699

**Comment by hansgrimm** [comment]
Deze is wss opgelost met #2437 - pr #2508

**Comment by tfrijsewijk** [comment]
Opgelost in #2437

**Comment by hansgrimm** [comment]
Deze bug, zoals gisteren zichtbaar tijdens de demo, is in de actuele versie van Asap nog steeds aanwezig.
<img width="2056" alt="Scherm­afbeelding 2024-10-30 om 09 41 44" src="https://github.com/user-attachments/assets/351446f1-6786-42e9-bed8-c80f7130d0c5">
https://fonts.google.com/specimen/Asap/tester?preview.text=Whereas%20recognition%20of%20the%20inherent%20dhttps:%2F%2Fstorybook.dso-toolkit.nl%2F66.0.0%2F%3Fpath%3D%2Fstory%2Fhtml-css-rich-content--rich-contentignity (voeg toe in inspector: `text-decaration: line-through;`

**Comment by hansgrimm** [comment]
Firefox/mac gaat wel goed:
<img width="1806" alt="Scherm­afbeelding 2024-10-30 om 09 47 23" src="https://github.com/user-attachments/assets/a7c1d2f3-5514-4db9-a0c9-c890f266d690">

**Comment by tfrijsewijk** [comment]
Hebben we gekeken of er een nieuwere versie van Asap beschikbaar is waar het is opgelost? Ik zie hier https://github.com/google/fonts/issues/2436#issuecomment-718184482 iets met nieuwe instructies die op een of andere manier leiden tot een nieuwe commit op https://github.com/Omnibus-Type/Asap/commit/83b5b2566789401e3d3112f1a6a61264256d95af ?

**Comment by hansgrimm** [comment]
Ik heb getest met de type-tester van Asap, en de underline ging nog steeds fout in Firefox/win. Ik ga er vanuit dat in die type-tester de laatste versie zit.

Het zou me niks verbazen als ze het bij Google fonts zien als een Firefox probleem. Niet onterecht, want het gebeurt alleen op Windows.

**Comment by tfrijsewijk** [comment]
Ik heb de fonts gedownload uit de discussie die jij hebt gevonden:

<img width="1919" alt="image" src="https://github.com/user-attachments/assets/3e9ee4af-977d-434f-98de-b417cb9ff5b2">

* Strikethrough bug is weg
* Fonts zijn aanzienlijk kleiner (~500kb -> ~120kb)
* Het font zonder bug heeft alleen variable weight, geen variable width? Wat is dat? Willen we dat? Verklaart wellicht het verschil in filesize.

![image](https://github.com/user-attachments/assets/26425297-59f7-47a5-acaf-36ff834e644a)

<img width="1181" alt="image" src="https://github.com/user-attachments/assets/517b6762-be6e-4d59-ba63-8d6b3fe24060">

**Comment by hansgrimm** [comment]
Eeehh, wacht effe.. die download van jou, komt die van Google? Of ergens anders vandaan?

Vwb de variable breedte: volgens mij gebruiken we die nu niet, of wel?

**Comment by hansgrimm** [comment]
Als die hack er weer uit kan, dan is dat prima. Dat soort dingen wil je eigenlijk liever niet.

**Comment by tfrijsewijk** [comment]
> Eeehh, wacht effe.. die download van jou, komt die van Google? Of ergens anders vandaan?

Nee, die komt uit die github discussie die jij vorig jaar had gelinkt:

<img width="1200" alt="image" src="https://github.com/user-attachments/assets/3f71cfef-8d99-428a-a7e5-5f32cdf01307">

> Vwb de variable breedte: volgens mij gebruiken we die nu niet, of wel?

Het font wat nu in de toolkit zit heeft ondersteuning voor variabele breedte, volgens mij maken we daar geen gebruik van.

> Als die hack er weer uit kan, dan is dat prima. Dat soort dingen wil je eigenlijk liever niet.

Dat heeft ook mijn voorkeur, maar de versie die ik heb gevonden is ouder dan die in de toolkit zit (lijkt het op).

Ik ga nu naar die op de google font site kijken
