### ISSUE TITLE
Deprecate plus-square en minus-square iconen

### ISSUE THREAD

**Issue by MYpenburg** [dso-toolkit/dso-toolkit#2426]
Want die worden toch niet meer gebruikt

**Comment by DjangoBlok** [comment]
Weet je zeker dat ze door niemand meer worden gebruikt?

**Comment by hansgrimm** [comment]
ze eten geen brood i.i.g ;)

**Comment by MYpenburg** [comment]
Weet niet zeker, maar ze zijn ooit gemaakt voor de list-button en die gebruikt ze niet meer. We moeten nog even dubbelchecken wat we doen met de HTML/CSS variant vd list-button want die had ze nog wel, maar verder weten we het niet. Overigens had ik begrepen dat deprecaten betekent dat ze eerst een half jaar in het rood oid worden weergegeven zodat het direct opvalt dat er iets mee is, dus als er echt problemen mee zijn dan zouden we dat via die weg moeten vernemen.

**Comment by MYpenburg** [comment]
> ze eten geen brood i.i.g ;)

Nee, maar je wilt ook niet dat ze wel gebruikt gaan worden nog, naast de plus-circle en min-circle (die zijn ervoor in de plaats gekomen nl)

**Comment by DjangoBlok** [comment]
Ik weet het niet zeker maar het zou kunnen dat ze in de stelselcatalogus worden gebruikt op knoppen om iets toe te voegen. Is toch ook wel een mooi icoon daarvoor?

**Comment by tfrijsewijk** [comment]
En? https://www.youtube.com/watch?v=xMaE6toi4mk 🎵

**Comment by DjangoBlok** [comment]
Ik moet dat bij de stelselcatalogus even navragen. Waar vind ik het overzicht van de iconen (inclusief deze) in de toolkit?

**Comment by hansgrimm** [comment]
> Ik moet dat bij de stelselcatalogus even navragen. Waar vind ik het overzicht van de iconen (inclusief deze) in de toolkit?

https://storybook.dso-toolkit.nl/62.17.0/?path=/story/voorbeeldpagina-s-iconen--iconen

**Comment by DjangoBlok** [comment]
https://www.youtube.com/watch?v=piTvLuHWLyg

Wordt gebruikt in de beheerpagina's van de stelselcatalogus. 
 
![Scherm­afbeelding 2024-04-04 om 11 04 36](https://github.com/dso-toolkit/dso-toolkit/assets/34900082/40f76147-3f1f-41db-9d72-dee1436cefb2)

**Comment by hansgrimm** [comment]
Dan kan deze dus dicht.
