### ISSUE TITLE
Ozon Content: Afbeeldingen in renvooi kunnen weergeven

### ISSUE THREAD

**Issue by DjangoBlok** [dso-toolkit/dso-toolkit#2433]
In de document component hebben we nog geen ondersteuning voor het weergeven van verwijderde en toegevoegde afbeeldingen.

In dit issue wordt duidelijk weergegeven of een afbeelding is verwijderd of toegevoegd.

**Voorbeelddocument:**
https://preprod.document-viewer.dso.kadaster.nl/viewer/(documentresult//rechter-paneel:document/_akn_nl_act_gm0344_2022_Regeling8b802b5bc4a4408da3cf3f84d687fccc_akn_nl_bill_gm0344_2023_besluit95e665034e5c46f398743e569cb207da/regels)?id=_akn_nl_act_gm0344_2022_Regeling8b802b5bc4a4408da3cf3f84d687fccc_akn_nl_bill_gm0344_2023_besluit95e665034e5c46f398743e569cb207da

In Hoofdstuk 17 is een afbeelding verwijderd en toegevoegd

![Github 2433 - Afbeeldingen in renvooi](https://github.com/dso-toolkit/dso-toolkit/assets/34900082/31342595-f465-4fb5-942e-aff61673a4a6)

**Comment by tfrijsewijk** [comment]
De betreffende markup is op dit moment

```html
<div class="dso-rich-content">
  <div class="dso-ozon-figuur bijschrift-onder">
    <dso-image-overlay>
      <img
        src="https://service.pre.omgevingswet.overheid.nl/publiek/omgevingsdocumenten/api/presenteren/v7/ontwerpafbeeldingen/gm0344/_akn_nl_bill_gm0344_2023_besluit95e665034e5c46f398743e569cb207da/testafbeelding.jpeg"
        alt=""
      />
      <div slot="bijschrift">
        <span class="figuur-bijschrift">
          (bron: <span class="dso-ozon-bron"> </span>)
        </span>
      </div>
    </dso-image-overlay>
    <span class="figuur-bijschrift">
      (bron: <span class="dso-ozon-bron"> </span>)
    </span>
  </div>
  <div class="dso-ozon-figuur bijschrift-onder">
    <dso-image-overlay>
      <img
        src="https://service.pre.omgevingswet.overheid.nl/publiek/omgevingsdocumenten/api/presenteren/v7/ontwerpafbeeldingen/gm0344/_akn_nl_bill_gm0344_2023_besluit95e665034e5c46f398743e569cb207da/testafbeelding_6ba8448dbbd14ffaa4b3d95c86f25778.jpeg"
        alt=""
      />
      <div slot="bijschrift">
        <span class="figuur-bijschrift">
          (bron: <span class="dso-ozon-bron"> </span>)
        </span>
      </div>
    </dso-image-overlay>
    <span class="figuur-bijschrift">
      (bron: <span class="dso-ozon-bron"> </span>)
    </span>
  </div>
</div>
```

Natuurlijk gaat deze change niet alleen maar om het visuele aspect, maar ook om de semantiek. Ik heb goede resultaten met `<ins>` en `<del>` geboekt. Ik denk dat we deze elementen om of in `<dso-image-overlay>` moeten zetten. Dan gaan eventuele bijschriften ook mee.

@DjangoBlok Jouw voorbeeld heeft geen bijschrift. Ik neem aan dat we die teksten dan ook doorstrepen, zoals we dat bij andere verwijderde tekst ook doen?

**Comment by DjangoBlok** [comment]
@thomas ja dat is goed! Je kan het bijschrift ook binnen het kader trekken.

**Comment by hansgrimm** [comment]
Ik zeg *om* `dso-image-overlay` want dan kan je die gebruiken om iets te doen met pseudo's. als het om de `img` gaat kunnen we alleen filters toepassen.

**Comment by hansgrimm** [comment]
voor wat probeersels zie https://codepen.io/picturit/pen/NWojYMG/99779acd734d33e49e52a42638b50abd

**Comment by tfrijsewijk** [comment]
Btw, de markup wordt door ons gegenereerd. We kunnen dus gewoon 'n element bijfietsen als we die nodig hebben

**Comment by hansgrimm** [comment]
👍🚴‍♂️😎

**Comment by tfrijsewijk** [comment]
@DjangoBlok Jouw voorstel is lastig haalbaar, daarnaast vraag ik mij af hoe verstandig het is om de plaat visueel aan te passen. Hoewel weinig, verstopt het kruis ook informatie. Je zal maar net zien dat de lijnen van het kruis een grens verbergt.

Heb je naar de voorbeelden van Hans gekeken? Ik denk dat we het beste voor jouw variant maar dan zonder het kruis moeten gaan. Dus alleen de tekst "toegevoegd/verwijderd" en de groen/rode kaders.

**Comment by hansgrimm** [comment]
Kaderen kan altijd idd, en misschien kunnen we ook nog iets lijps doen met box-shadow. Ik zal eens kijken of Lea Verou nog wat leuks ‘up her sleeve’ heeft ;)

**Comment by iterox** [comment]
@DjangoBlok Zou jij op https://storybook.dso-toolkit.nl/_2528-Ozon-Content-Ondersteuning-voor-Inhoud-wijzigactie-voegtoe-verwijder/?path=/story/core-ozon-content--renvooi-weergave onder Lid 6 willen beoordelen of de renvooi weergave van een verwijderde en toegevoegde afbeelding zo naar wens is?

![Uploading Screenshot 2024-02-19 at 13.30.51.png…]()

**Comment by DjangoBlok** [comment]
@iterox Een paar bevindingen:

1. Het label "toegevoegd"/"verwijderd" moet zelf niet worden doorgehaald of onderstreept. Bij andere elementen die zijn toegevoegd, wordt dit label cursief weergegeven. Zie: https://omgevingswet.overheid.nl/regels-op-de-kaart/viewer/(documenten/gemeente//rechter-paneel:document/_akn_nl_act_gm0505_2020_omgevingsplan_akn_nl_bill_gm0505_2020_ontwerpwijzing2024_02/regels)?regelsandere=regels&locatie-x=106477&locatie-y=423984&locatie-stelsel=RD&no-zoom=false&geodocId=akn-nl-act-gm0505-2020-omgevingsplan-akn-nl-bill-gm0505-2020-ontwerpwijzing2024-02&isOntwerp=true&session=1e8adf47-fd07-40ae-a2d2-58cbacd55aa5
2. Zowel bij toegevoegd als bij verwijderd, wordt de titel van van de afbeelding nu met rode letters weergegeven. Dit moet gewoon de normale kleur zijn. 
3. De toegevoegde titel/tekst hoeft ook niet onderstreept te worden.

**Comment by DjangoBlok** [comment]
Ah, inderdaad. Het is dus mauve. Dan kun je mijn punt 2 vergeten.
