### ISSUE TITLE
Logo weergave is te dik weergeven 

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#2435]
De weergave van het logo is niet conform de communicatie richtlijnen. 

De teksten zijn te dikgedrukt. 

Let op! mogelijk zijn er verschillen per machine. Dit issue is eerder aangekaart en er werd destijds aangegeven dat het was opgelost. 

Werkzaamheden:
- Logo aanpassen zodat het op elke machine weergeven wordt conform communicatie richtlijnen 
- Onderzoek, indien nodig, waarom logo op verschillende systemen anders wordt weergeven. 

<img width="405" alt="Screenshot 2023-11-13 at 08 22 59" src="https://github.com/dso-toolkit/dso-toolkit/assets/36912722/136935cc-ab46-4866-9a51-d9858b786c2c">

![Screenshot 2023-11-13 at 08 23 50](https://github.com/dso-toolkit/dso-toolkit/assets/36912722/103c8581-ad26-4913-a1b5-dda0989cbb3d)

**Comment by hansgrimm** [comment]
UX-overleg 14/11: tekst wordt onderdeel van SVG.

**Comment by MichielDHVD** [comment]
Wanneer je een <a> element toepast op het logo dan krijgt het logo een underline om het tekst is geworden.  

Logo hoort geen underline te krijgen wanneer er een a element op is geplaatst.

**Comment by tfrijsewijk** [comment]
Opgelost met #2437
