### ISSUE TITLE
Webfont Asap: Semibold displays as bold

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#2437]
Font-weight 500 tonen in sommige OS/browser combinaties als bold (700).
Zie https://dso-toolkit.slack.com/archives/G01AZEKEXUZ/p1699860068167699

zie ook #2424

**Comment by hansgrimm** [comment]
UX-overleg 14/11: tekst wordt onderdeel van SVG.

**Comment by hansgrimm** [comment]
zie ook #2435

**Comment by tfrijsewijk** [comment]
Hans kijken wat het impliceert om Asap variable font in de toolkit te plaatsen. Wellicht dat de font issues in #2435 dan ook zijn opgelost.

**Comment by hansgrimm** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_fonts/Variable_fonts_guide
