### ISSUE TITLE
Horizontale scrollbalk vanwege verticale scrollbalk

### ISSUE THREAD

**Issue by MYpenburg** [dso-toolkit/dso-toolkit#2439]
Is daar iets aan te doen?

<img width="580" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/7289928/edfd253e-020c-4670-b2b7-ef5c05c98c6f">

**Comment by hansgrimm** [comment]
@MYpenburg ik kan dit op mijn Mac niet reproduceren: 
![Image](https://github.com/dso-toolkit/dso-toolkit/assets/506527/55929bc7-29c6-4158-aaf6-c4e75ea5e6e9)

Als jij dat nog steeds wel kan, hoe doe je dat?

**Comment by MYpenburg** [comment]
Bij mij ziet het er nu goed ook goed uit. Automagisch...

**Comment by hansgrimm** [comment]
Dan zeg i,: sluiten die handel. Eens?
