### ISSUE TITLE
Button Row: Verticale ruimte ontbreekt

### ISSUE THREAD

**Issue by MYpenburg** [dso-toolkit/dso-toolkit#2440]
<img width="1627" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/7289928/c82cbf06-fbbd-497a-b04e-c03a60f264d6">

**Comment by hansgrimm** [comment]
deze zit al in de vertical rhythm branch.

**Comment by hansgrimm** [comment]
is dit wat? https://storybook.dso-toolkit.nl/_2217-fundament-systeem-voor-verticaal-ritme/?path=/story/voorbeeldpagina-s-toepassingen-mijn-omgevingsloket-mijn-projecten--mijn-projecten

**Comment by MYpenburg** [comment]
Akkoord, ziet er goed uit. Wanneer komt deze branch mee met de Toolkit?

**Comment by hansgrimm** [comment]
Zodra Firefox de in deze branch hier en daar gebruikte `:has()` pseudoclass ondersteunt. Dat zit eraan te komen, versie 121.

**Comment by tfrijsewijk** [comment]
Snelle fix met todo naar #2217 in `spacing.scss` maken.

**Comment by hansgrimm** [comment]
dit kan alleen met `:has()` worden opgelost.
