### ISSUE TITLE
Document Component: Recursief in- en uitklappen van geneste document componenten

### ISSUE THREAD

**Issue by mduijsens** [dso-toolkit/dso-toolkit#2449]
**Context:**
Er is een wens ontstaan dat men een groep van artikelen in 1x wilt open klikken, hiervoor hebben we samen met Thomas een oplossing bedacht.

https://github.com/dso-toolkit/dso-toolkit/assets/144002683/0e1f00eb-4501-498f-b7be-0416b35f2017
In dit filmpje kan je de interactie die we bedacht hebben bekijken.

**De styling van de knop:**
- Oog icoon (24px) grasgroen met padding left/right: 3px en top/bottom: 4px. Border-radius van 4px. Achtergrond grasgroen-10 zodat het niet te veel afleid van de belangrijkere content.
- Met deze afmetingen komt hij uit op een totale breedte (incl. lijn) van 32px. Nu is er rekening gehouden met 24px margin left bij de artikelen, maar dat moet dus eigenlijk herberekend worden om dit netjes passen te krijgen. Indien dit heel ingewikkeld is zou ik willen opteren voor een verkleining van dit icoon om het geheel binnen de 24px te laten passen (zonder padding ziet er namelijk heel slordig uit en haalt het gevoel dat het een knop is weg).
- Aan de rechterkant komt een lijn die over de volledige hoogte van de artikelen groep gaat, deze is 2px dik en kleurt mee met de achtergrond van het knopje. Of dit een stroke inside/center/outside of een balk wordt, maakt ons niet zo heel veel uit zolang het maar netjes uitlijnt.
- Om duidelijk te maken dat het een knop is zit er een hover interactie op, de achtergrondkleur gaat van grasgroen-10 naar grasgroen-40.
- De cursor moet een pointer zijn.

Hier de gewenste uitlijning van de iconen:
<img width="350" alt="Screenshot 2023-11-24 at 10 17 29" src="https://github.com/dso-toolkit/dso-toolkit/assets/144002683/bc144f8e-2a6a-41f6-8724-c8366e5df2b6">

**De gewenste interactie is als volgt:**
- Daar waar een groep van artikelen zit, dus dat kan een afdeling, paragraaf of subparagraaf zijn, maken we deze oplossing.
- Aan de linker kant zit ruimte om een knop toe te voegen, daar willen we een oogje (gesloten in geval van alles dicht, open in geval van alles open) laten zien.
- Door op het gesloten oogje te klikken gaan alle artikelen binnen die groep open. 
- Door op het open oogje te klikken gaan alle artikelen binnen die groep dicht.
- De gehele interactie van de accordions blijven gewoon werken zoals ze nu ook al werken, incl alle hover states etc (ook al zitten die niet in het filmpje).
- Als de gebruiker zelf een van de artikelen opent, blijft het oogje op gesloten, tot alle artikelen open zijn (al dan niet door ze zelf een voor een aan te klikken of door alsnog op het gesloten oogje te klikken).
- Dichtklikken van een heel hoofdstuk en deze daarna weer openen zorgt voor een reset, alleen de structuur is zichtbaar, alle artikelen zitten dicht.
- In de voorbeelden zie je ook de blauwe balk voor gefilterde items, het is met deze oplossing belangrijk dat deze helemaal links uitgelijnd is, anders conflicteren deze twee met elkaar.
- Deze oplossing bestaat alleen maar op een groep van artikelen, nooit op hogere niveaus.

**Comment by mduijsens** [comment]
@tfrijsewijk hier de story van het verhaal van gisteren. Kan je kijken of je nu nog info mist?

**Comment by tfrijsewijk** [comment]
Ik ben hier mee begonnen maar kan dit niet opleveren. Om Wesley tenminste te kunnen laten beginnen heb ik een pragmatische oplossing neergezet. Dan kunnen we het rustig over de interactie hebben.

Wij hebben namelijk iets gruwelijk over het hoofd gezien: De smalle viewport:

<img width="287" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/9696261/768578f3-0ab2-441b-9f3e-542148d99bae">

Er is geen ruimte voor een knop "in de gutter", zodra het document in een smal paneel wordt getoond, is er geen nesting. En dus geen ruimte.

Dit was een dusdanig beperking dat ik niet kan leveren. Ik heb het volgende gemaakt:

<img width="284" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/9696261/ac49136e-127a-4079-98b6-c4594a4c454c">

Ik rol dit straks als feature release uit, zodat Wesley aan de slag kan. Dit zit dus niet in een echte release.

> * Oog icoon (24px) grasgroen met padding left/right: 3px en top/bottom: 4px. Border-radius van 4px. Achtergrond grasgroen-10 zodat het niet te veel afleid van de belangrijkere content.
> * Met deze afmetingen komt hij uit op een totale breedte (incl. lijn) van 32px. Nu is er rekening gehouden met 24px margin left bij de artikelen, maar dat moet dus eigenlijk herberekend worden om dit netjes passen te krijgen. Indien dit heel ingewikkeld is zou ik willen opteren voor een verkleining van dit icoon om het geheel binnen de 24px te laten passen (zonder padding ziet er namelijk heel slordig uit en haalt het gevoel dat het een knop is weg).

De 24px indenting heeft te maken met de icon size en de button size. Daar zit een direct verband in zodat er een 45 graden hierarchie ontstaat. Dit programmerend uittesten is echt te duur, dit moet in een representatief ontwerp worden gedaan.

Verder: Iconen zijn 24x24, daar gaan wij niet in resizen. Ik geloof dat jij je ooit had opgeworpen om iconen te uniformeren? ;-)

> * Daar waar een groep van artikelen zit, dus dat kan een afdeling, paragraaf of subparagraaf zijn, maken we deze oplossing.

Dit ligt bij de implementator.

> * Aan de linker kant zit ruimte om een knop toe te voegen, daar willen we een oogje (gesloten in geval van alles dicht, open in geval van alles open) laten zien.

Dit is niet het geval in de smalle weergave, zie opmerking hierboven.

> * Door op het gesloten oogje te klikken gaan alle artikelen binnen die groep open.
> * Door op het open oogje te klikken gaan alle artikelen binnen die groep dicht.

Ik weet dat we dit hebben gedaan om gelijk te zijn met de chevrons op de buttons, maar achteraf gezien voelt dit niet intuïtief. Met name in de "intermediate" state (een document component met een mix van open en gesloten artikelen). Doordat wij pretenderen de huidige staat in de knop te plaatsen, communiceren we iets wat niet waar is: Het oogje staat gesloten, maar er zijn open artikelen.

Door de actie op de knop te zetten (open oog voor openen, gesloten oog voor inklappen) zetten we de gebruiker niet op het verkeerde been. De knop laat immers zien wat er gaat gebeuren. Bij de "intermediate" state (de mix) toont het open oog. Bij het activeren van de button worden alle artikelen geopend en het oog sluit zich.

> * Dichtklikken van een heel hoofdstuk en deze daarna weer openen zorgt voor een reset, alleen de structuur is zichtbaar, alle artikelen zitten dicht.

Dit gedrag ligt bij de implementator. Ik heb in mijn demo omgeving alles uitgewerkt, behalve deze. Het is laat.

Ik ga nu de feature release publiceren. Ik ben morgen niet aan het werk, vanaf vrijdag ben ik weer beschikbaar.

**Comment by tfrijsewijk** [comment]
@Hendriksie:

Ik heb `@dso-toolkit/core@62.5.0-ghi-2449.0` en `@dso-toolkit/angular@62.5.0-ghi-2449.0` uitgebracht.

De documentatie wordt as we speak gebuild en zou over 'n halfuurtje in de versie selector rechtsboven op dso-toolkit.nl beschikbaar moeten zijn. Vanaf daar naar Storybook navigeren en naar het component "Document Component" de Docs openen. Jij bent in het kader van dit issue vooral geinteresseerd in de prop `recursiveToggle` (`@Input()`) en het event `dsoRecursiveToggle` (`@Output()`) op `<dso-document-component>`.

Succes!

PS: Lees mijn vorige reactie in dit issue, boven deze.
