### ISSUE TITLE
Build: SCSS compileert niet meer

### ISSUE THREAD

**Issue by WiebeCnossen** [dso-toolkit/dso-toolkit#2452]
Sinds #2235 compileert de SCSS niet meer (met `sass` 1.69.5).

In` packages/dso-toolkit/src/components/form/form.mixins.scss` staat op regel 1 `@use config` maar in die map is er geen `config.scss`. De hele regel lijkt overigens gewoon weg te kunnen.

**Comment by tfrijsewijk** [comment]
Ah, ik heb die over het hoofd gezien. Bijzonder dat de toolkit buildstraat wel goed gaat, ik vind dat eigenlijk onterecht.

Ik heb in de Sass documentatie niets over dit gedrag gevonden, het lijkt mij eerder iets wat gulp-sass impliceert: https://github.com/dlmanning/gulp-sass/blob/master/index.js#L123

Ik ga 'm weghalen.
