### ISSUE TITLE
Form: Explanation required asterisk

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#2453]
A required field is visually marked with an asterisk (*). This should be textually explained within the form (bottom), using a special component.

@MichielDHVD will submit a design for this component.

En verplicht veld is visueel gemarkeerd met een asterisk (*). Dit moet tekstueel uitgelegd worden binnen het formulier (onderin), m.b.v. een speciaal component.

@MichielDHVD zal een ontwerp leveren voor dit component.

**Comment by hansgrimm** [comment]
asterisk: kleiner (.75rem) en zwart (tekstkleur)

**Comment by hansgrimm** [comment]
We wachten nog op een design + tekst.

**Comment by MichielDHVD** [comment]
Tekst: Velden met een * zijn verplicht. 

![Image](https://github.com/dso-toolkit/dso-toolkit/assets/36912722/8e02e30e-6982-4341-84ed-aef56b352c46)
![Image](https://github.com/dso-toolkit/dso-toolkit/assets/36912722/6bdb1af1-ec19-4685-926c-130544e60561)

**Comment by hansgrimm** [comment]
@MichielDHVD jij had een nieuwe asterisk gebouwd. heb je die voor me? dan kan ik die als onderdeel van deze issue toevoegen. thanks!
