### ISSUE TITLE
Docusaurus: Componenten preview op dso-toolkit.nl wordt afgekapt

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#2458]
De preview zichtbaar is bij de documentatie van componenten groeit/schaalt niet mee met het component dat getoond wordt. 
![Screenshot 2023-11-30 at 14 35 17](https://github.com/dso-toolkit/dso-toolkit/assets/36912722/2acac6e2-818b-41fc-a269-218e600cad12)

In de vorige versie (62.40) wordt het nog wel goed getoond. 
![Screenshot 2023-11-30 at 14 34 59](https://github.com/dso-toolkit/dso-toolkit/assets/36912722/066ced35-69d8-4c1a-958a-acddf0b6a864)

Werkzaamheden:
- Laat het component preview weer mee schalen met de grootte van het component. 

@tfrijsewijk  Deze bug lijkt me ready for development toch?

**Comment by iterox** [comment]
Oorzaak:

<img width="1262" alt="Screenshot 2024-03-12 at 11 13 19" src="https://github.com/dso-toolkit/dso-toolkit/assets/4646174/f6dabc74-4140-4767-a8a2-322e7754378b">

Nog niet kunnen uitdokteren wat er gedaan moet worden omdat te fixen. Google search levert mij nog niets begrijpbaars op.
