### ISSUE TITLE
Form Buttons: Responsive behavior

### ISSUE THREAD

**Issue by MYpenburg** [dso-toolkit/dso-toolkit#2464]
1. Normal view (> 480px): Verticale afstand 16px toevoegen tussen buttons onderling
<img width="800" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/7289928/4051a0c1-0020-46c3-bbf9-07957c58e09c">

2. Narrow view (<= 480px): Inhoud van de knoppen centreren, knoppen volle breedte, tertiaire knop krijgt backdrop grasgroen 10% #EBF3E6, tekstkleur grasgroen 110% #33790A, volgorde van de knoppen: vlnr -> boven naar beneden, onderlinge afstand 16px
<img width="268" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/7289928/08295e8f-ebc7-447d-a0c3-038d664b6684">

<img width="575" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/7289928/0dd24446-f484-46c2-b384-86b8e02e575b">

**Comment by MYpenburg** [comment]
Staat erin

**Comment by hansgrimm** [comment]
@MYpenburg Kijk hier en laat me weten of je er tevreden mee bent: https://storybook.dso-toolkit.nl/_2464-form-buttons-responsive-behavior/?path=/story/html-css-form-form-buttons--multi-page (maak venster smaller en presto :))

**Comment by hansgrimm** [comment]
@MYpenburg volgens mij zijn alle zaken die je aangemeld hebt en die naar boven kwamen tijdens onze "2 heren 1 scherm"-sessie nu verwerkt. check nog even of dat idd klopt & let me know :)

**Comment by hansgrimm** [comment]
U is een heer.

**Comment by hansgrimm** [comment]
NB: layout gaat naar horizontaal bij een vw > 480px, niet de gebruikelijke >= 480px. Just sayin’ 😉
