### ISSUE TITLE
Form Group "input", "select" & "textarea": Ongeldige waarde in `aria-invalid`

### ISSUE THREAD

**Issue by timveld** [dso-toolkit/dso-toolkit#2467]
### Waar
html|css / form / grout / input (en mogelijk andere componenten waar deze attributen gebruikt worden)
### Aanleiding
Ik heb ontdekt dat dit component bij gebruik van required en state controls produceert: `<input ... required="" aria-invalid="[valid / invalid]">`

Ten eerste lijkt 'required' me voldoende, de '=""' is technisch niet fout maar wel overbodig.

Ten tweede wordt  aria-invalid verkeerd gebruikt. "valid" en "invalid" zijn namelijk niet bestaande waarden, die moeten resp. "false" en "true" zijn. Zie [de mdn documentatie voor aria-invalid](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-invalid).

Bij een geldige invoer (state control op valid) heb ik het liefst geen aria-invalid attribuut, false is de standaard en een overbodig attribuut kan alleen maar problemen opleveren.

### Werkzaamheden
* Uitzoeken of de '=""' na required inderdaad overbodig is, en zo ja, verwijderen
* Bij een ongeldige invoer aria-invalid="true"
* bij een geldige invoer geen aria-invalid attribuut.

### gebruikersimpact
Kritiek: NVDA interpreteert aria-invalid="valid" als aria-invalid="true" zodat het veld ten onrechte als ongeldig wordt voorgelezen.

**Comment by timveld** [comment]
### Waar
html|css / form / grout / input (en mogelijk andere componenten waar deze attributen gebruikt worden)
### Aanleiding
Ik heb ontdekt dat dit component bij gebruik van required en state controls produceert: <input> ... required="" aria-invalid="[valid / invalid]">

Ten eerste lijkt 'required' me voldoende, de '=""' is technisch niet fout maar wel overbodig.

Ten tweede wordt  aria-invalid verkeerd gebruikt. "valid" en "invalid" zijn namelijk niet bestaande waarden, die moeten resp. "false" en "true" zijn. Zie [de mdn documentatie voor aria-invalid](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-invalid).

Bij een geldige invoer (state control op valid) heb ik het liefst geen aria-invalid attribuut, false is de standaard en een overbodig attribuut kan alleen maar problemen opleveren.

### Werkzaamheden
* Uitzoeken of de '=""' na required inderdaad overbodig is, en zo ja, verwijderen
* Bij een ongeldige invoer aria-invalid="true"
* bij een geldige invoer geen aria-invalid element

### gebruikersimpact
Kritiek: NVDA interpreteert aria-invalid="valid" als aria-invalid="true" zodat het veld ten onrechte als ongeldig wordt voorgelezen.

**Comment by tfrijsewijk** [comment]
> ### Waar
> html|css / form / grout / input (en mogelijk andere componenten waar deze attributen gebruikt worden)
> 

Ik ben ongeldige `aria-invalid` situaties op de volgende locaties tegengekomen:
* Form Group: Input
* Form Group: Select
* Form Group: Textarea

> ### Aanleiding
> Ik heb ontdekt dat dit component bij gebruik van required en state controls produceert: `<input ... required="" aria-invalid="[valid / invalid]">`
> 
> Ten eerste lijkt 'required' me voldoende, de '=""' is technisch niet fout maar wel overbodig.
> 

HTML5 boolean attributes kunnen op 3 manieren worden gezet:
* `<element attribute>`
* `<element attribute="">`
* `<element attribute="attribute">`.

https://developer.mozilla.org/en-US/docs/Glossary/Boolean/HTML

Het een is niet beter dan het ander. Alle 3 de opties zijn even geldig.

Maar ik vermoed dat jij dit in Firefox ziet. Zij zijn het namelijk niet met je eens dat het overbodig is ;-) Wij maken namelijk expliciet een empty boolean attribute, maar Firefox normaliseert dat naar een empty string.

> Ten tweede wordt aria-invalid verkeerd gebruikt. "valid" en "invalid" zijn namelijk niet bestaande waarden, die moeten resp. "false" en "true" zijn. Zie [de mdn documentatie voor aria-invalid](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-invalid).

Dit is een typefout: We tonen direct de waarde uit de mogelijke opties (`valid`, `invalid` en `undefined`) terwijl we voor `aria-invalid` natuurlijk op `state === "invalid"` moeten testen.

> Bij een geldige invoer (state control op valid) heb ik het liefst geen aria-invalid attribuut, false is de standaard en een overbodig attribuut kan alleen maar problemen opleveren.

In dat laatste kan ik mij niet vinden, we maken gebruik van moderne browsers en `aria-invalid="false"` is wellicht wat verbose maar zal geen problemen opleveren.

Overigens was ik ervan overtuigd dat het juist netjes was om op elementen met `aria-hidden="false"` te wisselen naar `aria-hidden="true"` ipv het `aria-hidden` attribuut weg te halen. We doen nu extra ons best om dit ook te doen, terwijl het makkelijker is om `aria-hidden="true"` weg te halen.

Voor onze Web Componenten zal ik nog een analyse maken in hoeverre we dit doen.

Voor onze HTMl/CSS componenten wil ik graag de volgende overweging meegeven: Door in onze markup voorschriften expliciet `aria-invalid="false"` te tonen, verleiden wij afnemers om gedrag voor `aria-invalid="true"` te implementeren. Als we geen `aria-invalid="false"` meer voorschrijven en een afnemer leest alleen de markup voorschriften voor het "happy path", krijg de afnemer geen hint meer voor `aria-invalid="true"`.

Ik sta niet negatief tegen het achterwege laten van `aria-invalid="false"`. Mochten we toch besluiten om dit weg te halen, wil ik ook de discussie voeren over waarom we uberhaupt `aria-invalid="true"` op zo'n simpel niveau voorschrijven, terwijl het beter is om dit alleen in bijzondere (niet-standaard) te gebruiken.

> ### Werkzaamheden
> * Uitzoeken of de '=""' na required inderdaad overbodig is, en zo ja, verwijderen

Niet overbodig en browser afhankelijk. Geen actiepunt.

> * Bij een ongeldige invoer aria-invalid="true"

Ga ik fixen.

> * bij een geldige invoer geen aria-invalid attribuut.

Hier gaan we op een later moment een kerstboom over opzetten.
