### ISSUE TITLE
Expandable: Overflow stays hidden when fully expanded

### ISSUE THREAD

**Issue by MYpenburg** [dso-toolkit/dso-toolkit#2471]
Aka: "Date picker: date panel binnen accordion verdwijnt half".

`overflow-y: hidden`

<img width="1658" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/7289928/586ad5c5-ffd2-4cb9-89f4-8011798b8c94">

overflow-y: niet hidden

<img width="1658" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/7289928/bbbe0bce-d588-49db-bfeb-032247ad7673">

Let op: de screenshots zijn van de legacy variant van de datepicker,  dus 2x checken (tenzij het in de accordion zit natuurlijk).

Date picker is cut off
![Scherm­afbeelding 2023-12-19 om 10 32 09](https://github.com/dso-toolkit/dso-toolkit/assets/506527/488b17f4-1525-4f67-97a7-838debfee593)

Switching off `overflow-y: hidden` fixes the problem
![Scherm­afbeelding 2023-12-19 om 10 34 36](https://github.com/dso-toolkit/dso-toolkit/assets/506527/1f4fc37b-dbfd-43dd-ade7-67a94ee3084a)

SCSS file 
![Scherm­afbeelding 2023-12-19 om 10 25 28](https://github.com/dso-toolkit/dso-toolkit/assets/506527/39a733ee-33ad-4f11-b142-d369c2455aff)

**Comment by tfrijsewijk** [comment]
Volgens mij een duplicat van #2476, @hansgrimm wat denk jij?

**Comment by hansgrimm** [comment]
Yes.
