### ISSUE TITLE
Expandable: Overflow stays hidden when fully expanded

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#2476]
Date picker is cut off
![Scherm­afbeelding 2023-12-19 om 10 32 09](https://github.com/dso-toolkit/dso-toolkit/assets/506527/488b17f4-1525-4f67-97a7-838debfee593)

Switching off `overflow-y: hidden` fixes the problem
![Scherm­afbeelding 2023-12-19 om 10 34 36](https://github.com/dso-toolkit/dso-toolkit/assets/506527/1f4fc37b-dbfd-43dd-ade7-67a94ee3084a)

SCSS file 
![Scherm­afbeelding 2023-12-19 om 10 25 28](https://github.com/dso-toolkit/dso-toolkit/assets/506527/39a733ee-33ad-4f11-b142-d369c2455aff)

**Comment by tfrijsewijk** [comment]
Duplicate van #2471
