### ISSUE TITLE
Toggletip: Wordt niet getoond bij position: bottom

### ISSUE THREAD

**Issue by MichielKadaster** [dso-toolkit/dso-toolkit#2477]
In de onderstaande situatie `dso-tooltip` niet getoond wanneer op de `dso-toggletip` wordt geklikt met `position="bottom"`.
Wanneer we de `position` op `left` zetten verschijnt deze wel.
Mogelijk heeft dit te maken met de `strategy` van de `dso-tooltip` deze is expliciet op `absolute` gezet door de toolkit maar het werkt wel wanneer deze op `fixed` wordt gezet (maar mogelijk is deze niet zonder reden op `absolute` gezet).
Als afnemer kunnen wij dit niet wijzigen.

URL: https://preprod.document-viewer.dso.kadaster.nl/viewer/(documenten/gemeente//rechter-paneel:document/%2Fakn%2Fnl%2Fact%2Fgm0344%2F2022%2FRegeling8b802b5bc4a4408da3cf3f84d687fccc/plekinfo)?regelsandere=regels&locatie-x=131873&locatie-y=460117&locatie-stelsel=RD&no-zoom=false&geodocId=akn-nl-act-gm0344-2022-regeling8b802b5bc4a4408da3cf3f84d687fccc-27

![image](https://github.com/dso-toolkit/dso-toolkit/assets/111350940/f31da811-c2b4-4f41-8041-9e94cec73a68)

**Comment by tfrijsewijk** [comment]
@iterox Wil jij hier wat onderzoek naar doen? Ik kom er gewoon niet aan toe

**Comment by iterox** [comment]
Zoals @MichielKadaster beschrijft werkt het wel wanneer de strategy op `fixed` wordt gezet. Strategy `absolute` is in het kader van [issue 2301](https://github.com/dso-toolkit/dso-toolkit/issues/2301) geïntroduceerd. Echter wanneer ik naar bovenstaande URL ga en dan switch naar de Regels-tab, vervolgens de toggletip achter de titel Regels uit andere besluiten aanklik en dan ga scrollen beweegt de tooltip niet mee, dus lijkt de strategy `absolute` issue 2301 niet gefixt te hebben. Daarvoor is dus verder onderzoek nodig.

Voor dit issue lijkt dus de stargey op `fixed` te zetten een stap voorwaarts.

**Comment by iterox** [comment]
@tfrijsewijk Issue #2301 heropenen?

**Comment by tfrijsewijk** [comment]
> @tfrijsewijk Issue #2301 heropenen?

Een issue heropenen we niet als een issue is gesloten omdat het in een release is opgelost. Als een bevinding zich (opnieuw) voordoet, wordt dat een nieuw issue wat aan een nieuwe milestone wordt gekoppeld.

**Comment by iterox** [comment]
Alhoewel de Toggletip position volgens de documentatie slechts de waarden "top" | "right" | "bottom" | "left" zou mogen hebben, biedt de onderligende library (popperjs/core) voor de placement van de tooltip ook nog meer opties, waaronder de optie "bottom-end". Wanneer deze waarde aan de property "position" van Toogletip wordt gegeven, dan wordt de tooptip wel getoond. Zie afbeelding:

<img width="1508" alt="Screenshot 2024-03-01 at 15 05 34" src="https://github.com/dso-toolkit/dso-toolkit/assets/4646174/145c8efd-6312-4c93-a6f2-e49d59607e2b">

@tfrijsewijk Waarom is bij toggletip de position ene beperktere set dan wat uiteindelijk binnen popper mogelijk is. Ik kwam hierop doordat ik zag dat in dropdown-menu r.208 andere waardes gezet worden, zoals "bottom-end" of "bottom-start".

**Comment by iterox** [comment]
@MichielKadaster Zuu jij eens ipv 'bottom' 'bottom-end' willen proberen als waarde voor de property position?

**Comment by MichielKadaster** [comment]
@iterox Dank, dat werkt goed! Neem het meteen mee in een openstaand PR :)
