### ISSUE TITLE
Document Component: Inspringen werkt niet in Firefox en Safari

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#2479]
Ik heb onterecht aangenomen dat `:host-context()` net zoals `:host()` "gewoon" zou werken. Echter, Firefox en Safari hebbend deze selector niet geimplementeerd en het lijkt erop dat deze selector zelfs uit de spec gehaald gaat worden.

https://bugzilla.mozilla.org/show_bug.cgi?id=1082060

**Comment by tfrijsewijk** [comment]
Overigens is er nog meer `:host-context()`:

* `packages/core/src/components/highlight-box/highlight-box.scss`
* `packages/core/src/components/tooltip/tooltip.scss`

cc @hansgrimm Kan jij eens kijken of we dit kunnen ombouwen tot global styling?

**Comment by hansgrimm** [comment]
Vwb highlight-box zou ik willen voorstellen even te wachten tot #2154 erin zit. Ihkv deze issue is highlight-box aardig door elkaar gerammeld ;)
