### ISSUE TITLE
Document Component: Titel knop mist aria-expanded en sluit voor titel tekst

### ISSUE THREAD

**Issue by timveld** [dso-toolkit/dso-toolkit#2480]
## Waar
core / document component - default en demo
## aanleiding
De ```<button>``` die dient om een artikel uit te klappen, heeft geen aria-expanded. Bovendien wordt de ```<button>``` gesloten voor de ```<div class=title>```, deze div moet binnen de button staan omdat dit de accessible name van de knop moet zijn (vergelijk hoe dit is gedaan in accordion).
## Werkzaamheden
* Aria-expanded toevoegen en zorgen dat dit in core / document - demo werkt
* De tittle div binnen de button plaatsen
## Gebruikersimpact
Kritiek: door het ontbreken van aria-expanded weet een screen reader gebruiker niet of het artikel is in / uit geklapt

**Comment by tfrijsewijk** [comment]
Het is niet mogelijk om de titel in de button te plaatsen:

* Het is een `div`
* De titel wordt opgebouwd uit data met `<dso-ozon-content>` en daar kunnen block level elementen uitkomen
* En de belangrijkste: Het is mogelijk dat er voetnoten of zelfs links in de titel staan (🤯). Daarom dat de titel gescheiden is van de button.

Kunnen we ook met `aria-labelledby` naar het titel element verwijzen?

**Comment by timveld** [comment]
@tfrijsewijk Als ik je verhaal goed begrijp, kunnen binnen een titel (die een h2 moet zijn) block level elements en links staan.

Maar heb je er bij stil gestaan dat block level elements en links geen descendant van button of heading elementen mogen zijn?

"block level elements binnen een uitklapbare heading" is nog wel op een elegante manier mogelijk, maar als er in de heading ook links moeten staan kan ik binnen de eisen van WCAG en de html validator alleen dit bedenken:
```<button aria-describedby="titel" aria-expanded="false"><span class="sr-only">Uitvouwen</span></button>
<div id="titel" role="heading" aria-level="2">
        <p>Een paragraaf met <a href="">een link</a> er in.</p>
</div>```

De door jou voorgestelde oplossing met aria-label op de knop vereist dat aria-hidden op de tekst waarnaar wordt verwezen staat, omdat de titel anders dubbel wordt voorgelezen. Zonder link in de titel werkt dat perfect, maar als er een link in staat wordt deze door de aria-hidden onbereikbaar. 

Voelt als een gevalletje "als het moeilijk kan, moeten we het niet te makkelijk maken"...

**Comment by tfrijsewijk** [comment]
> @tfrijsewijk Als ik je verhaal goed begrijp, kunnen binnen een titel (die een h2 moet zijn) block level elements en links staan.

Klopt.

> Maar heb je er bij stil gestaan dat block level elements en links geen descendant van button of heading elementen mogen zijn?

Klopt ook: Daarom dat ik juist het tegenovergestelde voorstel.

> "block level elements binnen een uitklapbare heading" is nog wel op een elegante manier mogelijk, maar als er in de heading ook links moeten staan kan ik binnen de eisen van WCAG en de html validator alleen dit bedenken:
> 
> ```
> <button aria-describedby="titel" aria-expanded="false"><span class="sr-only">Uitvouwen</span></button>
> <div id="titel" role="heading" aria-level="2">
>         <p>Een paragraaf met <a href="">een link</a> er in.</p>
> </div>
> ```

Dit gaan we doen, maar dan met een "echt" heading element. Een link mag in een h1-h6 als er in de link alleen phrasing content staat.

**Comment by tfrijsewijk** [comment]
Refinement 29-2-2024: Geen `aria-expanded` attribuut omdat het dubbelop is met de accessible name van de knop.

**Comment by tfrijsewijk** [comment]
@timveld Wij zijn de weg kwijt:
* In de originele specs staat dat `div` in `button` moet, maar dat mag niet.
* De button moet verwijzen naar de titel maar de button staat al in de titel, wat een `h2` is, wat niet mag.

Wij zetten dit issue terug naar refinement, graag samen met @hansgrimm @iterox naar kijken.

**Comment by iterox** [comment]
Er is een afspraak met @timveld @hansgrimm en @iterox op maandag 8 april 2024

**Comment by iterox** [comment]
@timveld Zou jij willen/kunnen verifiëren of dit issue met de implementatie alhier https://storybook.dso-toolkit.nl/_2480-Document-Component--Titel-knop-mist-aria-expanded-en-sluit-voor-titel-tekst/iframe.html?args=&id=core-document-component--demo&viewMode=story akkoord is?

**Comment by timveld** [comment]
@iterox  check, werkt conform verwachting / specificatie.
