### ISSUE TITLE
Document Component: Scrollen in tabel na vergroten werkt niet meer

### ISSUE THREAD

**Issue by Hendriksie** [dso-toolkit/dso-toolkit#2486]
Reproductie:
- Open https://storybook.dso-toolkit.nl/62.8.4/?path=/story/core-document-component--demo
- Scroll naar beneden naar tabel "Tabel 3.3.24"
- Klik op "vergroten"
- Zie dat je niet meer verticaal kan scrollen

Slack thread: https://dso-toolkit.slack.com/archives/CB417GQBC/p1704190681019059

ℹ️ Getest in Google Chrome

**Comment by iterox** [comment]
Het lijkt erop dat dit inmiddels gefixt is.

**Comment by Hendriksie** [comment]
Het gebeurt helaas nog wel. Ik zie wel dat het alleen gebeurt in Chrome en niet in Firefox. Safari kan ik helaas niet testen.

- Open https://storybook.dso-toolkit.nl/62.12.0/?path=/story/core-document-component--demo
- Scroll naar Tabel "Tabel 2.3.26 Emissiegrenswaarden"
- Klik op "Vergroten"
- Zie dat je niet meer verticaal kan scrollen in het modal.

![scroll](https://github.com/dso-toolkit/dso-toolkit/assets/6705457/492316cc-a9be-46b3-a932-fa7af74f20ea)

**Comment by iterox** [comment]
Best wel verwarrend dit issue, want op mijn iMac in Chrome Version 121.0.6167.184 gaat het gewoon goed:

Uploading Screen Recording 2024-02-21 at 11.52.53.mov…

**Comment by Hendriksie** [comment]
Hhmm, dit maakt het wel een beetje gek inderdaad. Werkt het bij jou ook gewoon in VDK?

1. Open VDK (Pre): https://preprod.document-viewer.dso.kadaster.nl/viewer/locatie
2. Zoek op document: "/akn/nl/act/pv25/2022/omgevingsverordeninggk" (22-12-2023)
3. Open de tab "Bijlagen"
4. Zoek op "Ontwikkeltijd natuurbeheertypen"
5. Vergoot de tabel die daaronder staat

![scroll-vdk](https://github.com/dso-toolkit/dso-toolkit/assets/6705457/5f330100-dfee-4ae4-8acb-e61261d5efe9)

**Comment by iterox** [comment]
Ja, die gaat ook goed:

https://github.com/dso-toolkit/dso-toolkit/assets/4646174/0ed86328-e846-4cd7-b232-b454adb3bce1
