### ISSUE TITLE
Logo: Responsiveness stuk

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#2489]
Ik bekeek beheerportaal en regels op de kaart op een klein scherm en zag het volgende gebeuren.

<img width="310" alt="Screenshot 2024-01-03 at 08 40 07" src="https://github.com/dso-toolkit/dso-toolkit/assets/36912722/c8aef659-42cd-4c1d-abad-64f838320a13">
<img width="314" alt="Screenshot 2024-01-03 at 08 39 25" src="https://github.com/dso-toolkit/dso-toolkit/assets/36912722/b48585d4-3387-4523-89bf-62214d63ec2b">

Bedoeling zou zijn dat omgevingsloket wegvalt en de dat regels op de kaart en beheerportaal zou blijven staan. 

Maar dit lijkt niet te werken

**Comment by hansgrimm** [comment]
<img width="310" alt="293857053-c8aef659-42cd-4c1d-abad-64f838320a13" src="https://github.com/dso-toolkit/dso-toolkit/assets/506527/d2008005-fe4f-446d-aefd-621d2964e530">
Ik vind dit ook best wel niet heel erg OK..

**Comment by MichielDHVD** [comment]
Eens maar 1 ding tegelijk. Dit verdient een eigen issue @DjangoBlok of @mduijsens  pakken jullie dit issue voor de responsiveness van de viewer op?

**Comment by tfrijsewijk** [comment]
De oorzaak is een attribuut `label` wat mist op `<dso-logo>`. Het label door de afnemer als property gezet, waarschijnlijk met Angular: `<dso-logo [label]="'Regels op de kaart'">`. De styling die het label verbergt werkt alleen als het host element een label attribuut heeft.

Dit is een bug in de toolkit. Stencil's `@Prop()` synchroniseert een attribute en property met dezelfde identifier, zie de Stencil documentatie (https://stenciljs.com/docs/properties).

Normaal gesproken synchroniseert Stencil alleen vanuit attribute naar property. Andersom synchroniseren noemt Stencil "reflecteren": `@Prop({ reflect: true })`. Zie ook https://stenciljs.com/docs/properties#reflect-properties-values-to-attributes-reflect.

@iterox Ik denk dat dit een leuk issue voor jou is. Zou jij verder een inventarisatie willen maken of er nog andere properties van het type `string` en `number` zijn die geen `@Prop({ refect: true })` hebben? Mogelijk dat er dan ook nog styling in die hoek mist. Maar laten we dat in een ander issue oplossen.

In dit issue graag reflect toepassen en vastleggen in een Cypress test. Succes!

**Comment by iterox** [comment]
Ik ga het opakken 👍

**Comment by iterox** [comment]
[PR](https://github.com/dso-toolkit/dso-toolkit/pull/2492) staat klaar.

Ga nu verder met het inventariseren of er nog andere properties van het type string en number zijn die geen @Prop({ refect: true }) hebben.

**Comment by tfrijsewijk** [comment]
@MichielDHVD: Dit is gefixed en komt uit in de release van maandag. Omdat ik geen gevoel heb bij de toolkit updates vs. deploy schema van het Portaal heb, wil ik jullie ook een "intermediate-fix" meegeven.

De oorzaak staat in mijn vorige comment (https://github.com/dso-toolkit/dso-toolkit/issues/2489#issuecomment-1875412469) uitgebreid omschreven. De bevinding is ondubbelzinnig een toolkit bug, maar het Portaal kan de bevinding ook zonder de fix in de toolkit oplossen.

Dit kunnen ze doen door het label niet met een property binding te zetten maar als attribute:

```html
<!-- ❌ -->
<dso-logo [label]="'Het label'"></dso-logo>

<!-- ✅ -->
<dso-logo label="Het Label"></dso-logo>
```

De werking van het component is hetzelfde, alleen is er nu een label attribuut aanwezig waardoor de styling in het toolkit component z'n werk doet.

Deze fix is compatible met de toolkit update waar dit issue in is opgelost.
