### ISSUE TITLE
Header: Aparte link voor applicatienaam in compacte header

### ISSUE THREAD

**Issue by DjangoBlok** [dso-toolkit/dso-toolkit#2498]
In de header linkt het logo naar de landingspagina van het omgevingsloket.
Regels op de kaart wordt weergegeven met een compacte header. In deze compacte header verschijnt naar het logo ook de naam van de actieve applicatie. Deze naam is ook klikbaar, en verwijst nu ook naar de landingspagina van het omgevingsloket. 
De verwachting is dat klikken op de naam 'regels op de kaart' verwijst naar de landingspagina van regels op de kaart. 

In deze story willen we dat klikken op de naam van de applicatie hetzelfde doet als klikken op de naam van het corresponderende menu item. 

![Compacte header](https://github.com/dso-toolkit/dso-toolkit/assets/34900082/844ced9a-6c02-44a8-b70c-f3fe672a2569)

**Comment by tfrijsewijk** [comment]
* Oplossing waarbij "Omgevingsloket Beheerportaal" als "Omgevingsloket" en "Regels op de kaart" klikbaar zijn (doorgaan op concept "label" van Logo)
* Tevens meenemen: Te groot interactievlak voor de anchor, zie beheerportaal.

**Comment by hansgrimm** [comment]
soms apart klikbaar, soms samen
