### ISSUE TITLE
Card: Externe link ondersteunen

### ISSUE THREAD

**Issue by MichielKadaster** [dso-toolkit/dso-toolkit#2505]
De `dso-card` is aangepast in versie 62.7.0 ivm https://github.com/dso-toolkit/dso-toolkit/issues/2390.
Sindsdien is de afnemer niet meer verantwoordelijk voor het maken van de `<a>` tag en wordt dit door de toolkit gedaan.
Wat nog ontbreekt is de mogelijkheid om van deze link een externe link te maken.

Het volgende zou in ieder geval moeten gebeuren wanneer een link extern wordt gemaakt:
- icoontje dat aangeeft dat het een externe link is (incl. tekst voor toegankelijkheid)
- target: _blank
- rel: noopener noreferrer

![image](https://github.com/dso-toolkit/dso-toolkit/assets/111350940/80389c21-7fd0-4a1b-b90a-95da1d9c92da)

**Comment by tfrijsewijk** [comment]
Akkoord

**Comment by tfrijsewijk** [comment]
```ts
// card.models.ts
export interface Card<TemplateFnReturnType> {
  label: string;
  /** Use only with `clickable: false`. */
  href?: string;
  anchorMode?: Anchor['mode']; // of "download" | "extern"; ? Zie anchor.models.ts 🤷 En misschien is de property name mode beter, de property href heet immers ook geen anchorHref
  selectable?: Selectable<TemplateFnReturnType>;
  content?: TemplateFnReturnType;
  interactions?: Array<Button | Label | Toggletip<TemplateFnReturnType>>;
  image?: string;
  imageShape?: (typeof imageShapes)[number];
  /** @deprecated use `href` */
  clickable?: boolean;
  dsoCardClicked?: (e: CustomEvent<DsoCardClickedEvent>) => void;
}
```

Web Component API:

```html
<dso-card mode="download|extern"></dso-card>
```

HTML/CSS:
* In `card.css-template.ts` de data uit `Card` model doorgeven aan de anchor waar ook `href` op wordt gezet.
