### ISSUE TITLE
Card: Link selecteren met href werkt niet

### ISSUE THREAD

**Issue by maartenwest** [dso-toolkit/dso-toolkit#2506]
* Ga naar het voorbeeld van Card met href in Storybook,  https://storybook.dso-toolkit.nl/master/?path=/story/core-card--href
* Vul in de Controls tab in bij href: `/abc`
* Klik op de link "Omgevingsplan Niewegein"

Verwacht:
* De browser navigeert naar https://storybook.dso-toolkit.nl/abc (wat 404 Not found geeft)

Daadwerkelijk:
* De Card blijft zichtbaar

Ter vergelijking: klikken terwijl control ingedrukt is, opent wel https://storybook.dso-toolkit.nl/abc in een nieuwe tab.

**Comment by tfrijsewijk** [comment]
Hi @maartenwest 👋 

Om de minder-technische gebruikers niet "kwijt te raken" hebben we dezelfde logica geimplementeerd die afnemers met router implementeren: https://github.com/dso-toolkit/dso-toolkit/blob/v62.9.0/storybook/src/components/card/card.core-template.ts#L29

**Comment by maartenwest** [comment]
Zou dit in de documentatie in de Storybook duidelijk gemaakt kunnen worden?

**Comment by tfrijsewijk** [comment]
Ja, gaan we doen 👍

**Comment by tfrijsewijk** [comment]
@iterox Kleine klusje, ff kort de documentatie bijwerken. Zie de comments

**Comment by iterox** [comment]
@tfrijsewijk Dit kleine klusje behoefte toch nog enige toelichting voor mij.
