### ISSUE TITLE
Card: Anchor chevron visited color

### ISSUE THREAD

**Issue by MichielKadaster** [dso-toolkit/dso-toolkit#2510]
De `dso-card` bevat nu zelf een anchor tag.
Daarin wordt een chevron meegegeven.
Echter, de chevron wordt paars (visited) wanneer je de link bezocht hebt. De tekst van de link zelf behoud de originele kleur.

![image](https://github.com/dso-toolkit/dso-toolkit/assets/111350940/98f150e0-e053-4a11-8edf-4f1eb41de6fe)

**Comment by MichielKadaster** [comment]
@tfrijsewijk nog een kleine bug in de `dso-card`

**Comment by tfrijsewijk** [comment]
Goed gevonden! @dso-toolkit/dso-ux ik neem aan ook gewoon groen maken? Of willen we de visited state zichtbaar maken over de hele title?

**Comment by tfrijsewijk** [comment]
Geen visited state styling. Chevron wordt bosgroen

**Comment by hansgrimm** [comment]
Hoi @MichielKadaster Ik krijg dit in de toolkit _en_ op productie niet gereproduceerd; als ik de link volg en weer terugga, blijft alles keurig bosgroen, inclusief de chevron, ook na een reload en ook als ik de link via de inspector op 'visited' zet. Kan je me aanwijzen waar dit exact gebeurt?
