### ISSUE TITLE
Card: default mousepointer boven "interactive slot"

### ISSUE THREAD

**Issue by MYpenburg** [dso-toolkit/dso-toolkit#2511]
In een Card kan een zgn Interactive slot leven. Daarin kunnen allerlei zaken worden geplaatst die on click iets anders moeten doen dan de hele card klikken. Echter, als er non-clickables in dat gebied staan (zoals tekst), dan gaat de click toch door naar de card. Dat willen we niet. Kan de hele interactive slot zelf dienen als event-schild naar de onderliggende Card, en dat dus ook de mousepointer afhangt van het al of niet interactief zijn van het geplaatste element?
Wij hebben een issue met een (jawel) tekst naast een toggletip. 
We zouden ook de toggletip kunnen voorzien van een label, maar dat is een ander verhaal.

**Comment by tfrijsewijk** [comment]
Card is een component wat steeds complexer is geworden. En we zijn eigenlijk de grenzen van redelijkheid aan het overschrijven.

Card beschikt over een aantal parameters waarmee (voor zover wij kunnen zien) voornamelijk 3 werkvormen worden gemaakt:

* Static
* Link
* Link met checkbox/interactions

**Static** heeft een hover, terwijl er geen enkele interactiviteit mogelijk is:

![Image](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/f5b7534c-0833-411f-abca-cbd6a5d1e49d) ![Image](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/06605c1c-93e5-45dd-89ba-7b38c3224ace)

**Link** krijgt een background-color bij hoveren (maar niet bij focus). Het afnemen van Card met Link betekent voor afnemers luisteren naar `dsoCardClicked` en aansluiten op de router. 

![Image](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/90b20afe-de90-4e71-afa5-1d300d0cf9b1) ![Image](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/cf32e656-ed8d-4f5f-ad14-bb04f1201f17)

![Image](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/bb9d8373-9549-48d3-8594-d74ad6de69f2)

Het component vangt het click event af en redirect dat naar `dsoCardClicked`. Maar de begeleidende tekst in Card is geen onderdeel van de `<a>` waardoor browser standaard gedrag (ctrl+click = nieuw tab, rechtermuisknop -> Kopieer link) niet werkt. Dit wordt als bug in #2507 opgevoerd.

**Link met checkbox/interactions**

![Image](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/8292fb03-22ef-44d7-b0d5-18c504d148f5) ![Image](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/3b931ed3-8728-4859-9504-5de95f14073a)

Click events "bubblen in HTML5 door naar boven". De bevinding in dit issue wordt daardoor veroorzaakt. In de Card zit logica die het clickevent afvangt als deze op een interactief element wordt gedaan.

> Echter, als er non-clickables in dat gebied staan (zoals tekst), dan gaat de click toch door naar de card. Dat willen we niet. Kan de hele interactive slot zelf dienen als event-schild naar de onderliggende Card, en dat dus ook de mousepointer afhangt van het al of niet interactief zijn van het geplaatste element?

Als ik het goed begrijp wil jij naast een interaction een tekst tonen en als er op die tekst wordt geklikt er niets gebeurd?

Hoe verhoudt dat zich tot de background-color hover state?

Door dit issue en #2507 denk ik dat we dit component opnieuw tegen het licht moeten gaan houden. Voor beide issues is het onderliggende probleem dat we "interactieve elementen in/over interactieve elementen" plaatsen. De HTML5 specificatie staat dat niet toe, en daarom dat wij scriptende truuken uithalen om het te simuleren. Maar eigenlijk begin ik daar steeds minder in te geloven en achter te staan.

@hansgrimm gaat dit behandelen tijdens het UX overleg.

**Comment by tfrijsewijk** [comment]
@hansgrimm Dit was het agendapunt wat afgelopen UX meeting op de agenda moest worden geplaatst 💡 Kan je dit morgen doen?

**Comment by hansgrimm** [comment]
Geen rechten 😬

**Comment by tfrijsewijk** [comment]
Toolkit advies:
* Alleen de anchor interactief maken
* Kiezen of de achtergrond naar grijs gaat bij on hover, maar in ieder geval geen handje.

Dit lost ook #2507 op.

**Comment by tfrijsewijk** [comment]
@sanderhaa samen met deze dus

**Comment by tfrijsewijk** [comment]
Interessante gedachte:
* Geen statische card meer, dat is wellicht meer iets voor Highlight Box of Whitebox

**Comment by DjangoBlok** [comment]
Mijn voorstel:
**Voor static card:**
Niet duidelijk waar het voor wordt gebruikt. Er zou in ieder geen hover actie moeten zijn, omdat hij niet klikbaar is.

**Link**
Van de hele card een anchor maken.
Ik verwacht dat de hele card klikbaar is, en dat de hele card een hover interactie en een handje geeft.
De focus zou wat mij betreft de hele rand van de card mogen oplichten.

**Link met checkbox/interactions**
De onderdelen zelf hun interactie laten afvangen.
De titel is nog steeds de basisactie en bij hover over de titel mag de hele card oplichten.
De card zelf hoeft niet meer klikbaar te zijn.

**Comment by MichielDHVD** [comment]
Bespreken UX overleg 6 augustus. @MichielDHVD

**Comment by tfrijsewijk** [comment]
Dit issue wordt opgelost met #2797.

**Comment by tfrijsewijk** [comment]
Dit issue is opgelost met #2797.
