### ISSUE TITLE
Modal: showModal() alleen aanroepen als dialog.isConnected

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#2512]
Soms toont er een foutmelding als `this.htmlDialogElement?.showModal()` wordt aangeroepen, dit is ongewenst en daarom gaan we testen op `isConnected`. De foutmelding gaat erover dat het Dialog element niet in het DOM hangt. Met deze voorwaarde vangen we dat af.

Mogelijk komen we tegen een ander probleem aan, namelijk dat er een Modal wordt verwacht maar niet zichtbaar is. Dat is nu ook het geval, alleen dan met foutmelding in de console.

**Comment by petervannes** [comment]
![SCR-20240110-lwnx](https://github.com/dso-toolkit/dso-toolkit/assets/7499676/4c83d374-12cd-4bf2-9f7c-1d84c5fa9419)
![Screenshot 2024-01-11 at 09 47 07](https://github.com/dso-toolkit/dso-toolkit/assets/7499676/9884542a-41b9-4ce4-a76d-22a411468370)
