### ISSUE TITLE
DSO Card met Switch-Toggle

### ISSUE THREAD

**Issue by mduijsens** [dso-toolkit/dso-toolkit#2513]
We maken op dit moment in de viewer gebruik van de card functionaliteit op Plekinfo. https://storybook.dso-toolkit.nl/62.3.2/?path=/story/core-card--with-image
![Image](https://github.com/dso-toolkit/dso-toolkit/assets/144002683/069dd84e-8e76-459b-86ce-c60096b743a3)

We willen nu deze uitbreiden met een dso-slide-toggle (bestaand item uit de toolkit https://storybook.dso-toolkit.nl/62.3.2/?path=/docs/core-slide-toggle--docs)
![Image](https://github.com/dso-toolkit/dso-toolkit/assets/144002683/8381c21f-016c-4d8a-bf53-dccbb5c47a40)

De gehele rij blijft clickable en stuurt ons naar een andere pagina. De hover reageert nog altijd om verbeelding aan te zetten op de kaart en deze switch-toggle zet zaken aan en uit op de legenda. Het zijn dus 3 verschillende interacties.

**Comment by tfrijsewijk** [comment]
Duplicaat van #2516
