### ISSUE TITLE
Range: New component

### ISSUE THREAD

**Issue by mduijsens** [dso-toolkit/dso-toolkit#2514]
In de viewer wordt nu een slider gebruikt, die niet beschikbaar is in de toolkit. Dit willen we overhevelen naar Toolkit.

Zie hier een voorbeeld van hoe het nu beschikbaar is in de viewer:
![Image](https://github.com/dso-toolkit/dso-toolkit/assets/144002683/68dabd35-6cdf-4061-a3ed-cd1d83dae1af)
Reprosteps: https://omgevingswet.overheid.nl/regels-op-de-kaart/viewer Open rechts boven in de legenda, ga naar Achtergrond, kies bijv. de 3 puntjes achter Luchtfoto. Nu zie je de slider, hier is hij overduidelijk niet zo netjes neer gezet.

Zie #2515 voor meer uitleg over de slider in combinatie met de legenda. Echter lijkt het ons logisch dat de slider ook een losstaand element kan zijn en niet alleen maar vast zit in een legenda item :)

Laten we ook eens goed praten over de gebruiksvriendelijkheid met toetsenbord gebruik etc. Op dit moment is er een stap interval van 1% bepaald, je kan het helemaal op 0% zetten of op 100% en alles er tussen in.

**Comment by hansgrimm** [comment]
zie ook #2515

**Comment by tfrijsewijk** [comment]
Basis: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range

**Comment by hansgrimm** [comment]
@mduijsens dit is hoe hij eruit moet gaan zien neem ik aan:
![Image](https://github.com/dso-toolkit/dso-toolkit/assets/506527/bcd026ba-2d17-405a-98a3-df482576aeba)

**Comment by hansgrimm** [comment]
de kleur van de slider strack (lichtgrijs) voldoet niet aan de minimale non-text contrastwaarde WCAG. Belangrijk als je wil zien waar je zit in de slider. als je de waarde aanpast wordt de track een flink stuk donkerder, en dat gaat dan weer clashen met het groen van de schuifknop.
Daarom dit voorstel mijnerzijds:
![Image](https://github.com/dso-toolkit/dso-toolkit/assets/506527/d9ee876f-4610-40ea-ab26-b199b9a96567)

1px donkergrijze border om de lichtgrijze track (@timveld is 1px voldoende?), en een 2px witte border om de groene schuifknop, zodat-ie een beetje "loskomt" van de track. Is dat wat, @mduijsens ?

Voor wie er mee wil spelen, hier de codepen: https://codepen.io/picturit/pen/wvORRVJ/e58ab34144ca6ba89ebb667c3cc4cedb

@timveld volgens mij is de input type range standaard toegankelijk; de attributen 'min', 'max' en 'value' zitten erin, dus daar is verder geen ARIA vereist als het goed is. klopt dat of mis ik nog iets? toetsenboerdbedienbaarheid is goed.

**Comment by DjangoBlok** [comment]
Maak je nog wel gebruik van het native slider component?

**Comment by hansgrimm** [comment]
> Border om de track lijkt me prima. Dan mag het grijs erin weer wat lichter? Wordt het linkerdeel van de track gevuld met groen? Het wit om het bolletje vind ik wat minder. In Firefox werkt het wel vanwege de dropshadow. Kan ook een zwarte border zijn.

- grijs mag lichter. roep maar welke tint uit de toolkit gewenst is.
- linkerdeel met groen vullen lijkt me geen haalbare zaak
- kan ook idd :)

**Comment by tfrijsewijk** [comment]
@hansgrimm Kijk eens naar https://developer.mozilla.org/en-US/docs/Web/CSS/accent-color

**Comment by hansgrimm** [comment]
> @hansgrimm Kijk eens naar https://developer.mozilla.org/en-US/docs/Web/CSS/accent-color

Hmm, interessant. Zal morgen eens even kijken of dat hier wil pakken op de manier die we willen.

**Comment by hansgrimm** [comment]
Als we een grote-stappen-snel-thuis oplossing willen met alleen `accent-color` ^^, dan _moet_ de `appearance` aan blijven staan, en krijg je dus te maken met de vormgeving die de browservendors zelf bedacht hebben. Het is een optie, maar dit is het resultaat (zie de onderste van de twee):

Chrome:
![Image](https://github.com/dso-toolkit/dso-toolkit/assets/506527/d5fdf5a2-f3de-4abe-861f-97587e875e1b)

Edge:
![Image](https://github.com/dso-toolkit/dso-toolkit/assets/506527/0da564bd-6d82-40d8-b877-f3e9ff455691)

Firefox:
![Image](https://github.com/dso-toolkit/dso-toolkit/assets/506527/91784b2e-b03f-454f-888b-3449cd0aa1f0)

Safari:
![Image](https://github.com/dso-toolkit/dso-toolkit/assets/506527/343f1166-f079-46f9-8e1c-db3a35c5fd44)

Misschien is het hier en daar nog wat te tweaken (al verwacht ik dat niet echt); wat we in de Chromium browsers (Chrome/Edge) en Firefox nu wel hebben is een groene linkertrack, @DjangoBlok :)

Laat maar weten of dit een acceptabele optie is, of dat we toch moeten gaan voor de versie die overal hetzelfde is. 

laat maar weten!

**Comment by DjangoBlok** [comment]
Liefst wel overal hetzelfde als dat geen WCAG of andere problemen met zich mee brengt.
Maar ik kan de impact voor jullie niet goed inschatten.

**Comment by hansgrimm** [comment]
> Liefst wel overal hetzelfde als dat geen WCAG of andere problemen met zich mee brengt. Maar ik kan de impact voor jullie niet goed inschatten.

WCAG problemen verwacht ik niet. Bovenstaande laat alleen zien welke benadering welke consequenties heeft qua look & feel.
