### ISSUE TITLE
Card: Slide Toggle toevoegen

### ISSUE THREAD

**Issue by mduijsens** [dso-toolkit/dso-toolkit#2516]
Aan de DSO card willen we graag een Toggle toegevoegd hebben.

![Card met slider](https://github.com/dso-toolkit/dso-toolkit/assets/34900082/626355c3-99e5-4f17-855c-b76cbce1d17b)

We willen de slide toggle rechts uitgelijnd toe kunnen voegen aan de card zoals hierboven afgebeeld.

We gebruiken nu deze  https://storybook.dso-toolkit.nl/62.3.2/?path=/story/core-card--with-image 
En we willen op het einde een toggle toe gaan voegen.
https://storybook.dso-toolkit.nl/62.3.2/?path=/story/core-slide-toggle--default

**Comment by hansgrimm** [comment]
in interactive slot plaatsen?

**Comment by tfrijsewijk** [comment]
<img width="400" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/9696261/6da839c0-f1f3-4c74-ba78-e5023f264a38">

Zoiets?

Want dit is namelijk gewoon de Slide Toggle als interaction toegevoegd aan Card:

```html
<dso-card>
  <div slot="interactions">
    <div class="dso-card-interaction">
      <dso-slide-toggle></dso-slide-toggle>
    </div>
  </div>
</dso-card>
```

Ik vind het een goed idee om in het kader van dit issue deze ondersteuning te formaliseren zodat het meegetest/geborgd kan worden, maar in de basis is dit wel hoe de toolkit zou moeten worden ingezet.
