### ISSUE TITLE
Feature initialFocus en returnFocus van Modal is niet meer beschikbaar

### ISSUE THREAD

**Issue by WidoBurg** [dso-toolkit/dso-toolkit#2518]
Bug is 2 ledig, beide gaan over focus van een modal. 

1. Modal initialFocus feature is niet meer beschikbaar. Toegevoegd in: https://github.com/dso-toolkit/dso-toolkit/issues/1934. Issue waarmee de feature niet meer meer werkt: https://github.com/dso-toolkit/dso-toolkit/issues/2223
2. De modal returnFocus opgeven is niet meer beschikbaar (idem verwijderd in https://github.com/dso-toolkit/dso-toolkit/issues/2223). De focus wordt nu gezet op het element wat eerder de focus had. Wij hebben de functionele spec dat we dit zelf kunnen opgeven zodat hier van afgeweken kan worden omdat het element waarvan de de modal is geopend is komen te vervallen. Bijv iets verwijderen uit het winkelmandje.

**Comment by tfrijsewijk** [comment]
Hi @WidoBurg 👋 

**1: initialFocus**

Klopt, `initialFocus` is met #2223 in release 58.0.0 verwijderd. De blogpost die bij die release hoort gaf aan dat deze functionaliteit is vervangen met het `autofocus` attribuut.

* https://dso-toolkit.nl/62.10.0/blog/2023/08/21/dso-toolkit-58.0.0
* https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autofocus

**2: returnFocus**

Met dat scenario heb ik inderdaad geen rekening gehouden. Maar ik ben ook terughoudend met het herimplementeren van `returnFocus`: In de pre-58.0.0 Modal maakten we gebruik van `focus-trap`. De signature van `returnFocus` is geinspireerd door `FocusTrap.setReturnFocus`. Ik heb even gekeken wat ze precies doen, maar het is best wel veel voor "gewoon `.focus()`".

Als we voor returnFocus zouden gaan, zullen jullie een verwijzing naar een element met `useRef()` bijhouden. Het enige wat wij dan doen is op dat element `.focus()` aanroepen. Zou het een optie zijn dat jullie zelf de focus terugzetten tijdens `Modal.onDsoClose` ?

```
<DsoModal onDsoClose={() => buttonRef.focus()} />
```

Let me know!

**Comment by MYpenburg** [comment]
Als ik de waarschuwing van mozilla lees is het autofocus attribuut niet iets wat wij moeten willen gebruiken, dat levert dan dezelfde WCAG issue op waarvoor we initialFocus er juist uit hebben gehaald. Klopt dat?

**Comment by tfrijsewijk** [comment]
> Als ik de waarschuwing van mozilla lees is het autofocus attribuut niet iets wat wij moeten willen gebruiken, dat levert dan dezelfde WCAG issue op waarvoor we initialFocus er juist uit hebben gehaald. Klopt dat?

Tot op zekere hoogte heb je gelijk: Maar we komen ermee weg omdat `autofocus` in `<dialog>` wordt gebruikt. De eindgebruiker krijgt eerst het dialog element voorgelezen en daarna het gefocuste element.

**Comment by WidoBurg** [comment]
**1. initialFocus** 
Beide opties zie ik nog niet werken (toolkit versie 62.8.0)
1. zonder autofocus en geen sluit icon
2. met expliciet autofocus op element. 

Nog wat verder gekeken, en zie het ook bij de autosuggest web component met een child input type text met autofocus niet werken. Zou je eens willen kijken of jij het ook kan reproduceren?
bijv. bij https://storybook.dso-toolkit.nl/62.10.0/?path=/story/core-autosuggest--in-searchbar, daar het input element autofocus geven. 

**2. returnFocus**
Zelf de return focus zetten doen vind ik prima. Echter, als er toch een toevoeging wordt gedaan voor het zetten van de focus dan is die return als component eigenschap van de modal niet onaardig. Dus kan in die zin 2 kanten op.

**Comment by tfrijsewijk** [comment]
> **1. initialFocus** Beide opties zie ik nog niet werken (toolkit versie 62.8.0)
> 
> 1. zonder autofocus en geen sluit icon
> 2. met expliciet autofocus op element.
> 
> Nog wat verder gekeken, en zie het ook bij de autosuggest web component met een child input type text met autofocus niet werken. Zou je eens willen kijken of jij het ook kan reproduceren? bijv. bij https://storybook.dso-toolkit.nl/62.10.0/?path=/story/core-autosuggest--in-searchbar, daar het input element autofocus geven.

Heb je het in de element inspector toegevoegd? Want dan werkt het inderdaad niet. Het `autofocus` attribuut werkt alleen als `document` wordt ingeladen, of als `dialog` in het DOM wordt geplaatst.

1: zonder autofocus en geen sluit icoon.

Dit kan ik ook niet meer reproduceren. Ik denk dat dit komt door de shadow boundary: De focusbare elementen zitten niet in `<dialog>`. Maar gelukkig kan ik punt 2 wel aan de praat krijgen.

2: met expliciet autofocus op element.

<img width="421" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/9696261/4dc3418d-2bde-4a65-aa5d-8b24688bba0a">

In dit screenshot heb ik een `<input type="text" autofocus>` in de `<dso-modal>` geplaatst. Bij het renderen wordt de focus op het invoerveld gezet.

<img width="724" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/9696261/2bb555ea-3fd4-4c86-a13c-67d01a0921f0">

> **2. returnFocus** Zelf de return focus zetten doen vind ik prima. Echter, als er toch een toevoeging wordt gedaan voor het zetten van de focus dan is die return als component eigenschap van de modal niet onaardig. Dus kan in die zin 2 kanten op.

Het zetten van de return focus wordt doordat we van `<dialog>` gebruik maken door de browser geregeld. Mocht daar een afwijking in voorkomen, zoals in jullie geval dat het oorspronkelijke element verdwijnt, dan heeft het mijn voorkeur om de afwijking in z'n geheel in de applicatie op te lossen.

Ik wil voorkomen dat de API van Modal onnodig toeneemt. Het aanbieden van een `returnFocus` eigenschap conflicteert met het native `<dialog>` gedrag: Ik denk dat de toolkit en de afnemers dan in elkaars vaarwater zitten: Wie roept (wanneer) `event.preventDefault()` aan? Moet Modal een check doen op aanwezigheid van `returnFocus` of ook of het trigger element niet meer focusbaar is?

Mocht je nog een goed idee hebben, laten we dan vooral meeten. Ik ben dinsdag de 6e weer in Utrecht! Ik denk dat je in ieder geval loskomt met `autofocus`.

**Comment by WidoBurg** [comment]
1. initialFocus

Idd met renderen. Laten we dinsdag even samen zitten, dan laat ik het zien (voor de modal en autosuggest).

**Comment by tfrijsewijk** [comment]
> 1. initialFocus
> 
> Idd met renderen. Laten we dinsdag even samen zitten, dan laat ik het zien (voor de modal en autosuggest).

Prima! Ik loop direct na de plenaire opening met je mee

**Comment by tfrijsewijk** [comment]
Vandaag hebben we twee situaties getest:
* Autosuggest met `<input type="text" autoFocus />`
* Modal met `<input type="text" autoFocus />`

In beide situaties is het gewenste gedrag dat de focus op het input element komt. Maar dat is dus niet zo.

Ik kan beide situaties reproduceren in de DSO Toolkit React Storybook. In de Core Storybook werkt het wel naar behoren.

Tijd voor 'n beetje onderzoek.

React werkt met een property `autoFocus` (let op de hoofdletter F). Dit is iets anders dan het _attribuut_ `autofocus`. Als ik een `<input type="text" autofocus>` in het DOM plaats en vervolgens de property `autofocus` (lage letter f) inspecteer, krijg ik `true`:

<img width="236" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/9696261/e07c4943-772b-45f7-8ab5-88e6b8bac3ff">

Echter, als ik met React `<input type="text" autoFocus />` plaats, komt er geen `autofocus` property `true`:

<img width="224" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/9696261/2712e9ce-0561-4a2a-a0c7-869388b93394">

Het grote verschil tussen de browsder native `autofocus` en React's `autoFocus` is dat `autoFocus` een soort van polyfill is, kennelijk om cross browser gelijk gedrag te maken. Ik ben niet bekend verschillen tussen browsers met `autofocus`, het zal mij niet verbazen als React ondertussen is ingehaald door de werkelijkheid.

Maar dat terzijde.

Als ik React forceer het `autofocus` attribuut te zetten met `<input type="text" autofocus="true" />` (en dan de errors in de console even vergeet), dan krijgt mijn input focus. Verder is `document.querySelector('input').autofocus === true`, zoals in het eerste screenshot.

Let wel: bovenstaande is zonder `<DsoAutosuggest>`. Want hier werkt het attribuut `autofocus` ook niet.

Maar waarom begrijp ik nog niet helemaal:

* Stencil genereert framework bindings: `<DsoAutosuggest>` is gegenereerde code: https://github.com/ionic-team/stencil-ds-output-targets/blob/main/packages/react-output-target/react-component-lib/createComponent.tsx#L92 Kan misschien in de weg zitten
* Maar als ik direct `<dso-autosuggest>` aanroep (het Web Component) werkt het ook niet.

Interessante artikelen:
* https://github.com/facebook/react/issues/11851#issuecomment-351672131
* https://blog.maisie.ink/react-ref-autofocus/#how-does-the-autofocus-prop-work

In de Core Storybook werkt het: Daar wordt het Web Component aangeroepen (geen framework bindings oid). Het DOM wordt door lit-html gemaakt, en een codesearch in de repo lijkt aan te geven dat er geen speciaal gedrag is geimplementeerd (https://github.com/search?q=repo%3Alit%2Flit%20autofocus&type=code).

Tot nu toe is mijn conclusie dat dit een React issue is.

Ik ga morgen verder debuggen met `<dialog><input type="text" autoFocus /></dialog>` in React, maar ik wil alvast voorzichtig een balletje opgooien... wat zou je ervan vinden om ook het initiele focussen voor je rekening te nemen? 😐 Op dezelfde manier zoals we `returnFocus` zouden oplossen? Ik begrijp dat dit een antwoord is waar je niet op zit te wachten..

Dank en tot morgen!

**Comment by timveld** [comment]
Ik begrijp het issue niet helemaal, @tfrijsewijk maandag in Apeldoorn bespreken. 

[MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autofocus) maakt terecht het punt dat je er bij gebruik van autofocus op moet letten dat gebruikers geen belangrijke informatie missen die boven het te focussen element staat. Maar in een modal moet je de focus toch expliciet plaatsen, waar precies is situatieafhankelijk. 

> je zou kunnen overwegen om het sluitenkruis met <DsoModal showCloseButton={false} /> uit te zetten waardoor het invoerveld op een natuurlijke manier focus krijgt.
	Ik denk niet dat het wel / niet tonen van het sluitkruisje een verschil maakt, weet niet wat je met 'op een natuurlijke manier' bedoelt maar tegen het (op onnatuurlijke wijze) expliciet plaatsen van de focus is geen bezwaar (volgens mij in een modal zelfs altijd nodig) mits er goed over is nagedacht welk element dan de focus moet krijgen.

**Comment by WidoBurg** [comment]
Voor het antwoord op de vraag of wij zelf de initiële en returnFocus willen gaan zetten: dat is ok.

**Comment by tfrijsewijk** [comment]
> Ik begrijp het issue niet helemaal, @tfrijsewijk maandag in Apeldoorn bespreken.
> 
> [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autofocus) maakt terecht het punt dat je er bij gebruik van autofocus op moet letten dat gebruikers geen belangrijke informatie missen die boven het te focussen element staat. Maar in een modal moet je de focus toch expliciet plaatsen, waar precies is situatieafhankelijk.

Dit issue is een technisch vraagstuk: Het lukt ons niet om op de gangbare manieren focus te plaatsen.

> > je zou kunnen overwegen om het sluitenkruis met  uit te zetten waardoor het invoerveld op een natuurlijke manier focus krijgt.
> 
> Ik denk niet dat het wel / niet tonen van het sluitkruisje een verschil maakt, weet niet wat je met 'op een natuurlijke manier' bedoelt maar tegen het (op onnatuurlijke wijze) expliciet plaatsen van de focus is geen bezwaar (volgens mij in een modal zelfs altijd nodig) mits er goed over is nagedacht welk element dan de focus moet krijgen.

`<dialog>` heeft een native focus trap, die regelt in principe zelf hoe de focus loop eruit ziet. Met `autofocus` kan je binnen `document` of `<dialog>` het eerste focus element selecteren. Als je geen expliciete focus zet, krijgt het eerst focusbare element focus.

> Voor het antwoord op de vraag of wij zelf de initiële en returnFocus willen gaan zetten: dat is ok.

Dank 👍 Ik weet het ook niet meer. Volgens mij lopen we tegen een implementatiedetail van React aan, voor zowel `autoFocus` als `autofocus`.

**Comment by tfrijsewijk** [comment]
@WidoBurg FYI: Nav van nieuwe inzichten in #2531 heb ik toch `setReturnFocus` geintroduceerd, maar dan met een iets andere API: Waar `setReturnFocus` een functie was waar het te-focussen werd teruggeven, is `returnFocus` een property waar direct het element aan wordt meegegeven.

Ik heb dit gedaan omdat er een edge case was waardoor bleek dat Modal toch iets met focus management moest gaan doen. Ik moest toch aan dit issue denken en heb toen doorgepakt en het mogelijk gemaakt naar welk element er return focus moet komen.

Jouw huidige implementatie blijft gewoon werken natuurlijk.
