### ISSUE TITLE
Input Number: Deprecate component

### ISSUE THREAD

**Issue by MYpenburg** [dso-toolkit/dso-toolkit#2519]
Het control met de - en + knop was ooit onderdeel van de list-button. Nu niet meer, en het is ook niet wenselijk als apart control. 

https://storybook.dso-toolkit.nl/master/?path=/story/html-css-input-number--input-number

**Comment by tfrijsewijk** [comment]
Prima! De rest van @dso-toolkit/dso-ux ook akkoord?

**Comment by MYpenburg** [comment]
Ja, was vorige week in UX meeting besproken. + square en - square moeten wel blijven als iconen want die worden in de viewers gebruikt.

**Comment by tfrijsewijk** [comment]
:+1:

**Comment by iterox** [comment]
@tfrijsewijk Ik zou deze wel willen oppakken, maar weet niet wat er gedaan moet worden.

**Comment by tfrijsewijk** [comment]
* [ ] Deprecation policy uitwerken
* [ ] Naam van implementatie suffixen met (deprecated) of (DEPRECATED)
* [ ] Deprecaten met HTML in `input-number.css-template.ts`, voor en na het root element
* [ ] Changelog entry
* [ ] Remove issue aanmaken

**Comment by tfrijsewijk** [comment]
Dus voor de duidelijkheid, dit issue is geen breaking release omdat het component blijft werken. Dit beschrijven we uitgebreid onder het eerste actiepunt in mijn voorgaande comment.

@iterox Ff samen briefen voordat je 'm oppakt?
