### ISSUE TITLE
Tooltip in lijn brengen met bootstrap

### ISSUE THREAD

**Issue by WidoBurg** [dso-toolkit/dso-toolkit#252]
De tooltip is nu niet conform bootstrap markup en classes. 
Dso kent dso-tooltip. In bootstrap wordt gebruik gemaakt van tooltip-arrow  en tooltip-inner. 

Graag in lijn brengen zodat gewerkt kan worden met standaard implementaties (in ons geval React Bootstrap). 

![tooltip dso](https://user-images.githubusercontent.com/8705247/50818056-1d228f80-1326-11e9-8bf2-f8b6ef63b186.png)

![bootstrap inner en arrow](https://user-images.githubusercontent.com/8705247/50818057-1d228f80-1326-11e9-88de-c9fb9e296b9c.png)

**Comment by PieterVerheij** [comment]
De reden dat wij een eigen markup hebben, is omdat 'onze' tooltip een aparte borderkleur en achtergrondkleur hebben. De standaard bootstrap tooltip is gewoon uitgevuld (dus geen aparte border). We kunnen onze styling nu wel op de bootstrap tooltip markup zetten, maar dat impliceert wel dat de markup van de tooltip voor alle applicaties gaat wijzigen...

**Comment by WidoBurg** [comment]
Ik begrijp de consequentie maar Bootstrap zou in principe altijd de voorkeur moeten hebben. Alleen afwijken als het niet echt niet anders kan. Immers, dat is ook als uitgangspunt opgenomen in de dso-toolkit: 

> The toolkit is framework-agnostic and based on Bootstrap v3.3.7 ....

Nu dien ik de standaard Tooltip van React-Bootstrap (https://react-bootstrap.github.io/components/tooltips/) te dupliceren om hem de markup en class te laten renderen zoals de dso toolkit doet. Dupliceren is zo gedaan maar onderhouden is een ander verhaal (denk aan unit tests en upgrades van React-Bootstrap). 

Dit zou niet alleen voor onze app gelden maar ook voor andere apps die een Tooltip renderen met andere implementatie (bijv. Angular).

**Comment by PieterVerheij** [comment]
Ik bouw dit met alle liefde om, maar ik weet niet hoeveel mensen de oude (dso-) markup gebruiken? Twee varianten naast elkaar laten bestaan is ook weer zo wat...

**Comment by WidoBurg** [comment]
Nee, geen twee varianten. Je wilt 1 variant, de bootstrap variant.

Bij de huidige dso-tooltip variant onderkennen dat er een ontwerp fout is gemaakt en dat die daardoor wordt verwijdert. 
Het wordt dan een breaking change, dat is dan het gevolg.

**Comment by MichielDHVD** [comment]
@DjangoBlok Ik tag jouw even in deze story. Omdat deze uitgevoergd gaat worden. Maar dat gaat wel een breaking change opleveren. 

Julie gebruiken immers de tooltip al. Dus lijkt me slim dat je hier al vanaf weet, om er later rekening mee te houden.

**Comment by DjangoBlok** [comment]
@michiel Ik kan niet goed overzien wat de consequenties zijn.

**Comment by MichielDHVD** [comment]
Gezien en gecontroleerd. Mark up vergeleken met bootstrap. 

https://getbootstrap.com/docs/4.1/components/tooltips/

Verplaatst naar Done

**Comment by WidoBurg** [comment]
@MichielDHVD Wel graag vergelijken met bootstrap v3, niet v4.
