### ISSUE TITLE
Accordion: Rare klapper bij sluiten van een sectie

### ISSUE THREAD

**Issue by MYpenburg** [dso-toolkit/dso-toolkit#2524]
Zie video's.
Bij het sluiten wordt eerst de inhoud weggehaald, waardoor het frame ineens dichtklapt. Daarna wordt dat lege frame nog eens teruggeschaald naar de eerdere hoogte en langzaam terug geanimeerd tot sluiten. 

Het mooist zou zijn als het dicht animeren direct zou plaatsvinden zonder eerst de content weg te halen. 

https://github.com/dso-toolkit/dso-toolkit/assets/7289928/e5640af9-fa3c-4d95-a13b-23cf1004a705

https://github.com/dso-toolkit/dso-toolkit/assets/7289928/7dc64078-fdb2-4254-83ad-85d886937159

**Comment by iterox** [comment]
@MYpenburg Kun jij mij aangeven waar in welke gebruikerstoepassing dit zich voor doet? Zodat ik er zelf naartoe kan om te kijken?

**Comment by MYpenburg** [comment]
Ja, het is de conclusiepagina van de Vergunningcheck.

**Comment by iterox** [comment]
Zitten er in de Vergunningscheck nog op andere plakken dso-accordions? Hebben die ook last van dit gedrag?

**Comment by iterox** [comment]
Ik constateer dat het open animeren (ook) niet vloeiend verloopt: 

https://github.com/dso-toolkit/dso-toolkit/assets/4646174/55ecdd45-5f58-4eb4-8648-e74d878ca2c8

**Comment by MYpenburg** [comment]
Versie kan ik niet zeggen, het valt me nu op.
