### ISSUE TITLE
Advanced Select: Nieuw component

### ISSUE THREAD

**Issue by mduijsens** [dso-toolkit/dso-toolkit#2525]
We willen minimaal de optie hebben bij de Select om een groepering aan te brengen. 
https://storybook.dso-toolkit.nl/62.3.2/?path=/story/html-css-form-groups-select--select
Zie hieronder het voorbeeld:
<img width="588" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/144002683/d6321c3a-f16c-4fb0-ba7b-8d798ae38d8b">

![Image](https://github.com/dso-toolkit/dso-toolkit/assets/144002683/a20a98f2-9b94-4e32-96c5-413e6e4482f5)
Je ziet dat we nu meerdere clusters hebben met een titel er boven ('Geldende versie', 'Toekomstige versies' en 'Ontwerp versies ter inzage').

Gebasseerd op de HTML  optgroup mogelijkheid. Thomas gaf al aan dat dit niet op die manier kan werken, maar anders opgebouwd moet worden maar we willen wel het zelfde principe. https://www.w3schools.com/tags/tag_optgroup.asp

Daarnaast is het handig als we per groep de optie hebben om een 'Bekijk meer' achtige optie te hebben. In ons geval opent dat een ander venster.

Nice to have: Gekleurde bolletjes, die geven in ons geval een status aan en maken het voor de gebruiker wat gemakkelijker (zonder lezen) om verschil te maken maar zeggen eigenlijk het zelfde als de titel van de groep.

**Comment by hansgrimm** [comment]
Misschien moeten we een keer naar de <datalist> optie kijken. Misschien biedt die meer mogelijkheden?

**Comment by mduijsens** [comment]
Nog verder uit te zoeken: 
- Wat zijn realistische lengtes, wat doen we als het langere teksten zijn en hoe gaan we om met de hoogte van de 'select' balk?
- WCAG voorleesfunctie moet wel werken met de groepen (ook al zijn ze niet selecteerbaar)
- Welke stijling gaat realistisch gezien goed werken? Martijn gaf aan dat hij de groep titels nu niet duidelijk genoeg vond t.o.v. de overige uitingen. Flexibiliteit hiervan hangt af van de technische implementatie.

**Comment by tfrijsewijk** [comment]
> Wat zijn realistische lengtes, wat doen we als het langere teksten zijn en hoe gaan we om met de hoogte van de 'select' balk?

De native select wordt niet hoger als de actieveoption niet meer past:

<img width="344" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/9696261/6795993b-3fdf-41cd-8c97-d61550a16c57">

Het renderen van de dropdown is de verantwoordelijkheid van OS/browser. Chrome op Windows laat de lijst buiten beeld lopen als het niet meer past:

<img width="1139" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/9696261/3323345b-c142-4f3e-b8b6-506e52e662c8">

Het laatste is eerder een FYI, maar met het eerste punt wil ik aangeven dat ik denk dat we er wel mee wegkomen als het niet meer past. Daarnaast: De volledige tekst is zonder wegnavigeren direct beschikbaar door de uitklapper weer te activeren.

Wat niet wegneemt: Als het lange teksten zijn waar de versie achteraan staat, valt de informatie waar je juist in bent geïnteresseerd (namelijk de versie) structureel buiten beeld. Ik kan mij voorstellen dat we dan de actieve selectie over meerdere regels moeten laten vallen, of toch over een andere werkvorm moeten nadenken.

> WCAG voorleesfunctie moet wel werken met de groepen (ook al zijn ze niet selecteerbaar)

Dat zal wel met iets als `role="group"` kunnen: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/group_role

> Welke stijling gaat realistisch gezien goed werken? Marti~~j~~n gaf aan dat hij de groep titels nu niet duidelijk genoeg vond t.o.v. de overige uitingen. Flexibiliteit hiervan hangt af van de technische implementatie.

We kunnen alle kanten op, ik zie geen technische beperkingen. Dit wordt een Web Component: we kunnen hier prima een iteratief proces voor volgen, of een eerste versie opleveren die in de Viewer wordt opgenomen en als één geheel aan de gebruikersgroep wordt voorgelegd.

> Conclusie was wel dat dit een generieke oplossing moet worden, groepen zijn hiervoor niet verplicht. Zodat men een 'gefilterde' lijst met Bekijk meer > functie ook zonder groepen kan gebruiken. Daarmee wordt deze uiting ook toepasbaar voor andere applicaties.

Dus:

* Lijst van opties;
* Lijst van gegroepeerde opties;
* Een groep kan een secundaire actie (button+link) hebben;
* Een groep kan een kleurcode hebben, die voor elke optie in die groep hetzelfde is. Dit is uitsluitend een visuele hint, er zal geen toegankelijke variant worden gemaakt: Het rubriceren van opties is al geregeld.
* Kunnen groepen en lijsten door elkaar staan? Anders gezegd: Kunnen groeploze opties naar groepen staan?
* Groepen worden niet genest.

Voorlopige werktitel van dit component: Rich Select (of Advanced Select?).

**Comment by mduijsens** [comment]
Keuze is gemaakt om in geval van lange teksten in 1 item die in de open versie wél te tonen, maar in de gesloten versie als een truncate te tonen.

**Comment by tfrijsewijk** [comment]
@mduijsens Wat zou je ervan vinden om die kleuren als "variant" of "status" te benoemen? Mogelijk opties zijn dan "success", "warning", "info", "danger", "default", etc? Zoals bij Label: https://storybook.dso-toolkit.nl/62.11.0/?path=/story/core-label--default (Zie Control -> "status")

En ik zou graag een relatie tussen de visuele weergave van de cumulatieven en groepen willen: Geel zou dan status "warn" zijn, en zou naar dezelfde kleur geel vertalen in de cumulatieven. De grijze zouden "default" zijn, en dan naar een grijs vlakje bij de cumulatieven vertalen en niet naar een wit omkaderd vlak.

**Comment by tfrijsewijk** [comment]
@Hendriksie is begonnen met dit issue
