### ISSUE TITLE
Map Layers: Scroll overlay stacking

### ISSUE THREAD

**Issue by MYpenburg** [dso-toolkit/dso-toolkit#2526]
De onderste schaduwrand ligt over de content heen (maar je kunt er wel doorheen klikken):
<img width="318" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/7289928/7c6f215d-6d5c-48b3-a1fd-ade4ac74e28e">

De bovenste schaduwrand ligt echter onder de content, waardoor de schaduw niet over de content heen valt maar andersom:
<img width="318" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/7289928/11c8d3ec-ce60-479a-bd2c-ac9c34af88bb">

Beide schaduwen moeten boven de  content vallen, maar de gebruiker moet er wel "doorheen kunnen klikken".

**Comment by tfrijsewijk** [comment]
> Beide schaduwen moeten onder de content vallen, maar de gebruiker moet er wel "doorheen kunnen klikken".

Ik zou verwachten dat de content onder de schaduw ligt? Want waar moet de gebruiker anders "doorheen kunnen klikken" ?

**Comment by MYpenburg** [comment]
Uiteraard, sorry voor de typo

**Comment by hansgrimm** [comment]
@MYpenburg als ik dit in de toolkit bekijk (bijv op https://storybook.dso-toolkit.nl/62.12.0/?path=/story/voorbeeldpagina-s-toepassingen-regels-op-de-kaart-locatie-overzicht--locatie-overzicht), dan vallen beide schaduwrandjes over de content heen, en kan je erdoorheen klikken. 

![Image](https://github.com/dso-toolkit/dso-toolkit/assets/506527/19953685-c29a-4fba-9be5-4227259bfe19)

Ook hier (https://omgevingswet.overheid.nl/checken/stap/1) werkt het gewoon: 

![Image](https://github.com/dso-toolkit/dso-toolkit/assets/506527/e07573df-5b85-4d8c-a237-dacc1b342f28)

**Comment by hansgrimm** [comment]
@MYpenburg er gaat m.i. niet al teveel mis, maar ik zal de stacking van de schaduwrandjes ietsje ophogen; ik zie dat bepaalde controls inderdaad boven het randje uit komen.

**Comment by tfrijsewijk** [comment]
@hansgrimm heeft @MYpenburg dit gezien/getest?

**Comment by hansgrimm** [comment]
> @hansgrimm heeft @MYpenburg dit gezien/getest?

Ik heb het vorige week laten zien, maar formeel getest: nee.
