### ISSUE TITLE
Form: Remove icon replace times by trash

### ISSUE THREAD

**Issue by MYpenburg** [dso-toolkit/dso-toolkit#2527]
In het form-files wordt een kruis icoon gebruikt voor de actie Verwijderen. Dat kan beter een prullenbakje zijn, in DSO wordt het kruisje verder vooral gebruikt voor de actie Sluiten.

<img width="1248" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/7289928/a3495423-95b9-4888-8887-e4a1d6e31b9a">

**Comment by tfrijsewijk** [comment]
@dso-toolkit/dso-ux Akkoord?

**Comment by tfrijsewijk** [comment]
UX is akkoord 🎉
