### ISSUE TITLE
Ozon Content: Ondersteuning voor `<Inhoud wijzigactie="voegtoe|verwijder">`

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#2528]
De toolkit heeft géén ondersteuning voor een wijzigactie op `<Inhoud>`. In het kader van dit issue gaan we die maken.

## Huidige situatie

Zie de presentatie van een `<Inhoud>` element oranje gemarkeerd:

Brede (inspringende) weergave
![image](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/3045cfd5-a446-4d85-8ef5-5e4c26dec580)

Smalle weergave
![image](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/35d99555-7cd4-4557-b4c5-c9b0db416259)

## Gewenste situatie

@DjangoBlok @mduijsens Kunnen jullie helpen met ontwerpen? Ik neem aan dat het ongeveer gelijk zal zijn aan de wijzigacties op structuur niveau (Tot Artikel).

* https://koop.gitlab.io/STOP/standaard/2.0.0-rc/tekst_xsd_Attribute_Group_tekst_agWijzigactie.html#agWijzigactie

**Comment by iterox** [comment]
@DjangoBlok Zou jij op https://storybook.dso-toolkit.nl/_2528-Ozon-Content-Ondersteuning-voor-Inhoud-wijzigactie-voegtoe-verwijder/?path=/story/core-ozon-content--renvooi-weergave onder Lid 3 willen beoordelen of de renvooi van verwijderde en toegevoegde inhoud zo naar wens is?

<img width="1101" alt="Screenshot 2024-02-19 at 13 33 30" src="https://github.com/dso-toolkit/dso-toolkit/assets/4646174/dee80a63-6a32-4483-b932-5a3f5f27d8aa">

**Comment by DjangoBlok** [comment]
1. De toegevoegde tekst hoeft niet onderstreept te worden. Als ik me niet vergis, doen we dat in andere renvooisituaties ook niet. 
2. De margin (op de <p>) aan de onderkant binnen het kader lijkt wat onnodig in de situatie.
