### ISSUE TITLE
CSS: Remove host context

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#2530]
Deze pseudo-class selector geniet geen goede browser support en het lijkt erop alsof dit ook nooit zal gebeuren. Wij maken op twee plekken gebruik van deze selector:

* Highlight Box
* Tooltip

In dit issue halen we deze selectors weg en trachten we de huidige functionaliteit op een andere manier te bouwen.

https://www.google.com/search?q=mdn+host-context&oq=mdn+host-context&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIGCAEQRRg7MgYIAhBFGDsyBggDEEUYPNIBBzU1MWowajeoAgCwAgA&sourceid=chrome&ie=UTF-8

**Comment by hansgrimm** [comment]
Ik moet even wat kwijt hier: `:host-context` heeft dus _nooit_ gewerkt in Firefox en Safari, wat o.a. betekent dat op een pagina als https://omgevingswet.overheid.nl/checken de genummerde boxjes in die browsers vanaf dag 1 getoond worden als een slecht gebit.
Aan de andere kant hebben we giga koudwatervrees bij het gebruik van technieken als `:has()`, zelfs als het maar gaat om kleine cosmetische zaken. Beetje meten met 2 maten, niet? ;)

Naja, met deze issue moet het gebitje nu ook goed staan in FF en Safari.
