### ISSUE TITLE
Form: File add download button

### ISSUE THREAD

**Issue by MYpenburg** [dso-toolkit/dso-toolkit#2531]
Download knopje erbij.

<img width="525" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/7289928/0e90d610-ee81-4248-b67c-071b70de4f81">

**Comment by tfrijsewijk** [comment]
@MYpenburg Mieke vraagt zich af of het een optie is om de bestandsnaam interactief te kunnen maken? Dit maakt de information density lager.

**Comment by MYpenburg** [comment]
Ik zie nu pas jouw vraag @hansgrimm. We gebruiken sowieso overal een download icoon als er gedownload kan worden. Soms staat ie voor de filenaam en is die groen onderstreept als link, maar hier gaat het specifiek om het uploaden / managen van bestanden. Dus willen we de bestandsnaam niet "vervuilen" met teveel interactie of kleur.
Welk grappig trouwens dat de viewer iets vindt van "onze" informatiedichtheid ;)

**Comment by tfrijsewijk** [comment]
> Welk grappig trouwens dat de viewer iets vindt van "onze" informatiedichtheid ;)

De S in DSO staat voor Samen en de O voor Ons, ik hoop dat jij iets _onze_ van de Viewer vindt 😄
