### ISSUE TITLE
Highlight Box: Separate variants

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#2533]
# Status

Highlight Box kent 4 varianten:

* Default
* Yellow
* White met Drop Shadow
* Met border

Daarnaast is het mogelijk om elke variant te voorzien van een Banner of een Icon.

# Aanleiding

Tijdens #2154 kwam dit naar voren.

# Bevinding

De bevinding wordt uiteengezet met het Web Component en attributen. Voor het HTML/CSS component geldt dezelfde bevinding, alleen dan met classes.

Om bovenstaande 4 varianten te krijgen moeten er attributen worden geactiveerd:

* Default: `<dso-highlight-box>` / `<div class="dso-highlight-box">`.
* Yellow: `<dso-highlight-box yellow>` / `<div class="dso-highlight-box dso-yellow">`.
* White met Drop Shadow: `<dso-highlight-box white drop-shadow>` / `<div class="dso-highlight-box dso-white dso-drop-shadow">`.
* Met border: `<dso-highlight-box border>` / `<div class="dso-highlight-box dso-border">`.

Deze modifiers kruislinks combineren werkt niet altijd: Dat komt door de het cascadende effect. Yellow kan niet met Border maar wel met Drop Shadow

# Probleem

In de CSS moeten we nu een truuk uithalen om de "gemengde" constructie te ondersteunen: De default moeten we expliciet selecteren, anders is de styling van andere varianten te zwaar.

# Voorstel

1. Achtergrondkleur lostrekken van modifier. Dat betekent dat de variant "Met border" geen standaard witte achtergrond meer krijgt. Varianten: Default, Yellow, White. Outline: None, Border, Drop Shadow.
2. Drop Shadow fuseren met White. Drop Shadow heeft dan altijd een witte achtergrond, net zoals het nu al voor "Border" is. Varianten: Default, Yellow, Drop Shadow, Border

**Comment by tfrijsewijk** [comment]
Het wordt optie 1 (Dus breaking).

Maar kijken of we een non-breaking variant kunnen maken...

**Comment by MYpenburg** [comment]
Grote voorkeur om het NIET breaking te maken!!

**Comment by hansgrimm** [comment]
Gefixt op een non-breaking manier. een highlight box met alleen de class `dso-border` krijgt nog steeeds een witte achtergrond. om dat eventueel te corrigeren is de class `dso-grey` toegevoegd.
