### ISSUE TITLE
Pagination: Long numbers overlap

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#2541]
![image](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/9c08fbf1-602a-4b51-8c42-fabe0a794e2f)

cc: @Lutske

**Comment by tfrijsewijk** [comment]
@dso-toolkit/dso-ux Wat zullen we doen? Pil-vormige indicators als het niet past?

**Comment by MYpenburg** [comment]
Ja, doen. Want dit is echt onleesbaar. Bij ons zijn meer dan 100 pagina's eigenlijk ondenkbaar, maar bij de viewers kan het makkelijk lijkt me :P

**Comment by hansgrimm** [comment]
checken bij @tfrijsewijk of dit een realistische issue is.

**Comment by tfrijsewijk** [comment]
Dit is een praktijk bevinding.

Oplossing: Pil vorm maken en meer breedte pakken. Bij pagina's tot 3 cijfers geen visuele wijziging (ofwel: De huidige functionaliteit blijft bestaan).

**Comment by tfrijsewijk** [comment]
Sehr schön

![image](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/36045ec5-ae62-48fe-beb8-dbe08562a73f)
