### ISSUE TITLE
Viewer Grid: Align sizing buttons to bottom

### ISSUE THREAD

**Issue by mduijsens** [dso-toolkit/dso-toolkit#2552]
We hebben een melding gekregen van de gebruiker dat de knoppen van het rechterpaneel over de knoppen van de kaart heen vallen:
![image](https://github.com/dso-toolkit/dso-toolkit/assets/144002683/277cceda-d994-4c90-8b5c-b54a9110e9ab)

Dit was een known issue maar misschien is het nu het moment om er iets mee te doen?

Gekozen oplossing: 
De pijltjesknoppen niet halverwege positioneren, maar helemaal onderaan in het scherm (met een marge boven de versiebalk)

**Comment by mduijsens** [comment]
Of oplossing B (even niet kijkend naar de volgorde van de knopjes maar wel de algehele positie) 
![image](https://github.com/dso-toolkit/dso-toolkit/assets/144002683/30349ef9-d904-4b84-9ac4-4719910ef10b)

**Comment by DjangoBlok** [comment]
Oplossing B:

- De verschuifknoppen bovenaan uitlijnen (gelijk met de knop van het linkerpaneel)
- De overige knoppen naar onderen verschuiven (wel in de huidige volgorde)
Daarmee wordt de kans dat ze elkaar overlappen minder groot.

**Comment by hansgrimm** [comment]
@tfrijsewijk @iterox even een vraagje: ik heb de sizing buttons van het rechterpaneel nu bovenin geplaatst, maar nu gaan ze natuurlijk over de kaartknoppen heen vallen. de positionering van die kaartknoppen, gaan wij daarover of het viewerteam?

**Comment by iterox** [comment]
> @tfrijsewijk @iterox even een vraagje: ik heb de sizing buttons van het rechterpaneel nu bovenin geplaatst, maar nu gaan ze natuurlijk over de kaartknoppen heen vallen. de positionering van die kaartknoppen, gaan wij daarover of het viewerteam?
> 
> Edit: Als ik in prod naar de naamgeving kijk van die kaartknoppen (`<dsov-..>`) dan vermoed ik dat hierna de viewerboys aan zet zijn. kloptat?

@hansgrimm Correct. En tevens juist. Viewerteam aan zet wannneer ze de release met deze change gaan gebruiken.

**Comment by hansgrimm** [comment]
@iterox top, thanks! In dat geval kan deze door.

**Comment by DjangoBlok** [comment]
We hadden tijdens refinement afgesproken om de sizing knoppen juist naar onderen te verplaatsen.

**Comment by hansgrimm** [comment]
> We hadden tijdens refinement afgesproken om de sizing knoppen juist naar onderen te verplaatsen.

dat lijkt me heel raar, en onlogisch voor de gebruiker

**Comment by iterox** [comment]
> We hadden tijdens refinement afgesproken om de sizing knoppen juist naar onderen te verplaatsen.

Als dat zo is, waarom staat het dan niet vermeld; er staat juist vermeld dat de knopen bovenaan moeten worden uitgelijnd.

**Comment by DjangoBlok** [comment]
Sorry, er lijkt iets misgegaan te zijn in de communicatie. Tijdens de vorige planningssessie kwam naar boven dat PO optie B niet acceptabel vond, en is optie C naar boven gekomen:
Om de bug op korte termijn op te lossen de pijltjesknoppen helemaal naar onderen verplaatsen. Er hoeft dan geen wijziging in de viewer plaats te vinden.

**Comment by hansgrimm** [comment]
> Sorry, er lijkt iets misgegaan te zijn in de communicatie. Tijdens de vorige planningssessie kwam naar boven dat PO optie B niet acceptabel vond, en is optie C naar boven gekomen: Om de bug op korte termijn op te lossen de pijltjesknoppen helemaal naar onderen verplaatsen. Er hoeft dan geen wijziging in de viewer plaats te vinden.

@DjangoBlok Ze staan nu onderin. Ik blijf dat wel onhandig vinden, daar vallen ze veel minder op. Nou ja, als tijdelijke oplossing... ;)
