### ISSUE TITLE
core / action list: niet als lijst gecodeerd

### ISSUE THREAD

**Issue by timveld** [dso-toolkit/dso-toolkit#2556]
### Waar

Core / action list

### Aanleiding

Soms akker ik gewoon wat componenten door en dat blijft nodig. Deze action list is visueel een lijst maar lijkt gecodeerd te zijn als divjes. Dit is zo'n klassiek inkoppertje in een WCAG audit wat we niet meer zouden moeten tegenkomen... 

### Werkdzaamheden

Lijst correct coderen; @hansgrimm heeft indertijd een oplossing gebouwd voor een vergelijkbare lijst (de lijst op pagina vergunningcheck onder de kop "e stappen", waar de gemaakte wijziging gek genoeg lijkt te zijn teruggedraaid)

### Gebruikersimpact

Hinderlijk: gebruiker moet zelf concluderen dat het een lijst is en hoe lang hij is.

**Comment by MYpenburg** [comment]
Is hetzelfde als https://github.com/dso-toolkit/dso-toolkit/issues/2282

**Comment by tfrijsewijk** [comment]
Dubbel, gesloten...
