### ISSUE TITLE
Autosuggest: Multi row variant

### ISSUE THREAD

**Issue by mduijsens** [dso-toolkit/dso-toolkit#2557]
Verandering op: https://storybook.dso-toolkit.nl/62.12.0/?path=/story/core-autosuggest--in-searchbar

We willen eigenlijk een multi row resultaat omdat we nu heel veel data in zo'n resultaat veldje stoppen. Dit wordt mega onoverzichtelijk.

Nu gebeurd dit:
![Image](https://github.com/dso-toolkit/dso-toolkit/assets/144002683/be57bb4e-301d-4bf8-aea7-d6b219a68595)

We willen dit:
![Image](https://github.com/dso-toolkit/dso-toolkit/assets/144002683/44d40040-13b6-44ca-a42f-1b79ee6811c5)

**Comment by iterox** [comment]
Ter info: in Regels op de kaart wordt momenteel de data uit de backend gemapt:

`public getSelectorData(): PlanSuggestieSelectorData {
    return {
      id: this.id,
      type: this.type,
      value: `${this.naam} | ${this.status} | ${this.id} | `,
      date: new Date(this.planstatusInfo.datum),
    };
  }`

**Comment by mduijsens** [comment]
Hallo Eric,

Hier de design specs:
- [ ] Eerste row heeft Body tekst als styling (Regular 16, 24 lineheight)
- [ ] Overige rows hebben Small als styling (Regular 14, 21 lineheight) 
(zo kunnen we steeds goed het begin van een nieuwe row identificeren)
- [ ] Ik heb ik design geen verticale spacing gebruikt tussen de elementen in 1 multi row, de lineheight bepaald dus de afstanden binnen 1 zo'n multi row element.
- [ ] 1 multi row element heeft een padding rondom van top bottom 4px, links rechts 16px. Dus dat creeert een padding van 8px tussen laatste tekstje van multi-row element 1 en bovenste tekstje van multi-row 2. Dat is inderdaad iets anders dan in het design voorbeeldje.
- [ ] Font-weight Bold voor de matches t.o.v. searchterm. 

Verder mogen de hover en focus styling het zelfde blijven als bij de single row nu al is bij https://storybook.dso-toolkit.nl/62.12.0/?path=/story/core-autosuggest--in-searchbar
De fontkleuren mogen ook gematcht blijven met hoe het bij de single row nu al is (links donker, rechts lichter).
