### ISSUE TITLE
Modal: Bij sluiten van modal wordt focus niet teruggezet

### ISSUE THREAD

**Issue by petervannes** [dso-toolkit/dso-toolkit#2560]
Wij gebruiken de DsoModal tijdens het bijwerken van de vragen. Deze vragen kunnen bijgewerkt worden indien een gebruiker in een TextArea of TextArea gegevens invoert. Indien de gebruiker een dergelijk veld zit en de DsoModal wordt getoond, verliest het veld de focus en krijgt deze ook niet meer terug bij het sluiten van de Modal. Gevolg is dat indien een gebruiker aan het typen is de invoer niet doorgaat na het sluiten van de modal.
Gewenst gedrag en geconstateerde gedrag met DsoModal is bijgevoegd

https://github.com/dso-toolkit/dso-toolkit/assets/7499676/9dcde5cc-af7c-4854-b0a8-e18fe5d33036

https://github.com/dso-toolkit/dso-toolkit/assets/7499676/d2caca6c-c62e-4a65-8d25-816a69fdc260

Ook in storybook lijkt het patroon [Modal Focus Return](https://storybook.dso-toolkit.nl/62.12.0/?path=/story/voorbeeldpagina-s-patronen-modal-return-focus--modal-return-focus) niet te werken. Na sluiten van de modal heeft de button geen focus meer.
Ik vermoed dat het in commit 46106869 stuk is gegaan door het verwijderen van de returnFocus.

**Comment by tfrijsewijk** [comment]
> Ik heb iets gevonden
> Modal maakt gebruik van `<dialog>`. Dit HTML5 element heeft het gedrag waarmee de return focus wordt teruggeplaatst bij het sluiten van de dialog
> De flow is:
> dialog maken
> dialog openen met `document.querySelector('dialog').showModal()`
> gebruiker interacteert met dialog
> dialog wordt gesluiten met `document.querySelector('dialog').close()`
> dialog wordt uit het DOM verwijderd.
> De toolkit tracht de imperatieve code weg te houden bij de afnemer: Zodra er een `<dso-modal>` wordt gemaakt zorgt het Web Component ervoor dat de dialog wordt geopend. Als het `<dso-modal>` web component wordt weggegooid sluiten we het dialog.
> Maar hier is een timing issue geintroduceerd:
> afnemer maakt `<dso-modal>`
> `<dso-modal>` maakt dialog en opent deze
> gebruiker interacteert met modal
> gebruiker/scripting sluit modal
> afnemer verwijdert `<dso-modal>` (wat wij ook voorschrijven)
> modal sluit dialog. **Dit kan niet: `<dialog>` moet worden gesloten terwijl deze nog connected is (in het DOM hangt)**
