### ISSUE TITLE
Toolkit scrolled niet op Firefox

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#257]
Bij meerdere mensen is het probleem naar voren gekomen. Dat in de toolkit er niet gescrolled kan worden. 

Het gaat dan voornamelijk om de linkerbalk. 

Ik weet niet of dit ook bij jullie bekend is.

**Comment by PieterVerheij** [comment]
@MichielDHVD ik kan dit in mijn Firefox niet reproduceren. Verschijnt er wel een scrollbalk?

Ik ga er gemakshalve vanuit dat het gaat om een windows machine, welke versie van FF? Ik kijk met 64.0.2

**Comment by MichielDHVD** [comment]
Dit zijn de gegevens van de desbetreffende laptop waar het op plaats vind. 

OS X El Capitan

Version 10.11.6

MacBook Air (13-inch, Mid 2012)

2 GHz Intel Core i7

 

Firefox 64.0.2 (20190108160530)

**Comment by tfrijsewijk** [comment]
Welke URL gaat dit over? De documentatie pagina's zijn namelijk ook geversioneerd. Iets in oudere releases fixen gaat dus heel lastig worden..

**Comment by MichielDHVD** [comment]
Ik ga dit nog een keer nalopen. Als het niet meer te reproduceren valt dan sluit ik dit issue.

**Comment by MichielDHVD** [comment]
Ik ga dit issue sluiten. Mocht het optreden in de toekomst dan open ik deze pas weer als het duidelijk reproduceerbaar is.
