### ISSUE TITLE
File upload: Upload knop staat de dicht op bovenliggende content

### ISSUE THREAD

**Issue by MYpenburg** [dso-toolkit/dso-toolkit#2570]
Dit is te dicht:
<img width="945" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/7289928/26a210d5-a9d8-45ca-89c1-19e195b62f25">

Hier valt het mee: 
<img width="945" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/7289928/a0ad7ee4-7f88-41d2-91ba-f37b007c5277">

Kan wel 16px extra tussen boven en onder:
<img width="1230" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/7289928/6ab7ccab-d478-4599-8ed5-ec7aee6f03be">

<img width="1556" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/7289928/6b18e140-4952-4145-9c01-11c537c56a69">

**Comment by hansgrimm** [comment]
verschil tussen toolkit en prod

**Comment by MYpenburg** [comment]
Prod markup
<img width="1619" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/7289928/5cea2bd6-6d24-4d1b-8dda-9975a8d22e33">

Storybook
<img width="1619" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/7289928/936054a2-4c76-4d28-9161-155af4f79996">

**Comment by hansgrimm** [comment]
Ik denk dat dit op markup-niveau opgelost moet worden.

In de toolkit heeft de upload genoeg ruimte:
![Image](https://github.com/dso-toolkit/dso-toolkit/assets/506527/b20235ab-adea-4b7e-9a08-a610ebb92b19)
en dat komt door deze markup:
![Image](https://github.com/dso-toolkit/dso-toolkit/assets/506527/c7773c63-4ada-4665-972b-e0d5f41f49af)

In prod zit deze markup:
![Image](https://github.com/dso-toolkit/dso-toolkit/assets/506527/3ba5779b-9f7b-4de5-a8db-07800254293b)

Het lijkt mij dat de markup op prod gewijzigd moet worden naar de structuur die voor `dso-files` is voorgeschreven.
Dat levert dan de gewenste spacing volautomagisch op.

**Comment by hansgrimm** [comment]
@MYpenburg maakt een issue voor PR12 (aanpassing markup). deze kan gesloten worden
