### ISSUE TITLE
List "Image List": Option spaced

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#2574]
![image](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/90d498fb-2923-41f8-9f1d-176bd805b250)

In bovenstaand ontwerp is een List voorzien. Maar list is op dit moment ontoereikend. De variant die het meest in de buurt komt is "Image List":

![image](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/5f849df5-b416-4e69-ab0b-7531ee8cf1ca)

Over het verticale en horizontale vlak moet er wat meer lucht komen. Als we de `<img>` vervangen met `<dso-icon>` lijnt dat goed:

<img width="205" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/9696261/975e0a14-fdb0-45ec-80f8-ded7fc21f736">

Hoe dit lijnt na #2542 moeten we nog over nadenken.

De werkzaamheden in dit issue is de ruimte over het verticale en horizontale vlak aanbieden onder een modifier. Ik denk dat we deze het beste kunnen beperken tot de Image List variant van List.

```ts
export interface List {
  type?: Type;
  items: ListItem[];
  modifier?: string;
  spacious?: boolean; // Geen specifieke optie voor uitsluitend List: Image List variant, maar de basis is daar niet naar.
}
```

```html
<!-- Voorstel 1 -->
<ul class="dso-img-list dso-img-list-spacious">

<!-- Voorstel 2 -->
<ul class="dso-img-list dso-spacious">
```

## Toegankelijkheid

De changes in dit issue zijn louter visueel. Maar we maken deze wijziging voor PR12. Zij gaan deze nieuwe optie icm met List "Image List" toepassen zoals in het eerste screenshot.

In dit issue gaan we ook de markup voorschriften opstellen waarmee de afnemer dit toegankelijk kan aanbieden.

Stap 1: Heel snel/instantaan
Stap 2: Kan even duren
Stap 3: Heel snel/instantaan

Hoe kunnen we de voortgang toegankelijk aanbieden?

In de ruwe opzet van Wido lijkt het erop alsof deze spinners ook parallel kunnen verschijnen:

![image](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/a33a0487-e285-400b-bade-f85c2b962809)

**Comment by MYpenburg** [comment]
Het simultaan verschijnen: het patroon van deze pagina is dat verzoek voor verzoek wordt afgewerkt. Een verzoek gaat goed of niet. Een verzoek dat goed gaat wordt afgesloten met een vinkje. Een verzoek dat niet goed gaat wordt niet zichtbaar afgesloten, maar er blijft een spinner staan waardoor de gebruiker niet direct in paniek schiet. Op de volgende pagina wordt uitvoerig toegelicht wat wel en niet goed is gegaan en wat het gevolg hiervan is.

**Comment by timveld** [comment]
Een spinnen moeten we met aria ongeveer zo coderen als we doen in modal / loading, of je zou een tekstalternatief moeten geven. 
@tfrijsewijk  maandag bespreken.

**Comment by hansgrimm** [comment]
Aanpassing aangebracht in de Image list. Met die optie toont hij nu zo:
![Scherm­afbeelding 2024-03-07 om 14 41 02](https://github.com/dso-toolkit/dso-toolkit/assets/506527/74ae7f14-78c8-4df0-bd98-2da472623d83)

**Comment by tfrijsewijk** [comment]
Ik denk dat ie nog wel wat ruimer mag. @MYpenburg kan jij wat over de maten zeggen?

**Comment by hansgrimm** [comment]
> Ik denk dat ie nog wel wat ruimer mag. @MYpenburg kan jij wat over de maten zeggen?

De gap is van 8 naar 16px gegaan.

**Comment by MYpenburg** [comment]
Zo is ie prachtig ^^
