### ISSUE TITLE
Accordion: Remove duplicate colon

### ISSUE THREAD

**Issue by timveld** [dso-toolkit/dso-toolkit#2576]
### Waar
html|css - accordion varianten
### Aanleiding
Als ik de control "status" op "danger" zet krijgt het icoontje wat dan verschijnt tekstalternatief "fout::" dus met een extra ':'. Hetzelfde geldt voor status warning. 
### Werkzaamheden
Overbodige ':' verwijderen
### Gebruikersimpact
Beperkt: slordigheidsfoutje.

**Comment by hansgrimm** [comment]
@timveld Op https://storybook.dso-toolkit.nl/_2576-accordion-remove-duplicate-colon/?path=/story/html-css-accordion--addonssections kan je checken of deze issue gefixt is. Onder water zie ik iig geen dubbele colon meer.
