### ISSUE TITLE
Ozon Content: Toegevoegde teksten zorgen ervoor dat anchors niet meer identificeerbaar zijn

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#2582]
In de renvooiweergave krijg nieuwe tekst een underline. Als er in deze tekst een anchor zit, is deze niet meer te herkennen:

![Screenshot 2024-03-14 155538](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/0cf6b04a-23e9-42a4-9282-8a702837dd57)

* In bovenstaand screenshot is de anchor gefocussed. Het zwarte kader is de focus stijling.
* Check of dit ook geldt voor `<NieuweTekst>` en/of alleen voor `wijzigactie="voegtoe"`.

---

Bij verwijderde teksten zijn anchors wel te identificeren:

![Screenshot 2024-03-14 155624](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/6ff8acdd-d3ae-49f5-b23b-eb55fcb812c6)

**Comment by DjangoBlok** [comment]
@tfrijsewijk Bij mijn weten hebben we nooit gespecificeerd dat toegevoegde tekst onderstreept moet worden. Ook precies om deze reden. 
Voor het onderscheid tussen rood en groen hebben we een schaduw toegevoegd aan de groene vlakjes.

Wat mij betreft is de oplossing dat we de onderstreping er vanaf halen.

**Comment by tfrijsewijk** [comment]
> @tfrijsewijk Bij mijn weten hebben we nooit gespecificeerd dat toegevoegde tekst onderstreept moet worden. Ook precies om deze reden. Voor het onderscheid tussen rood en groen hebben we een schaduw toegevoegd aan de groene vlakjes.

Ik denk dat je gelijk hebt. Ik kom niets tegen. Het is in release 59.0.0 met #2240 geintroduceerd 🤷 

> Wat mij betreft is de oplossing dat we de onderstreping er vanaf halen.

Prima!

**Comment by iterox** [comment]
Het opmerkelijke is dat ik dit niet in de master storybook van de dso-toolkit kan vinden.
@DjangoBlok Heb jij een reproductie pad of document waarin zich dit in de viewer voordoet?

**Comment by tfrijsewijk** [comment]
Gevonden & gefixed
