### ISSUE TITLE
Dropdown Menu: Werkt niet in ShadowRoot

### ISSUE THREAD

**Issue by yktoo** [dso-toolkit/dso-toolkit#2585]
Als je op de knop van een `<dso-dropdown-menu ...>` klikt, verschijnt er geen dropdown. Dat werkte vroeger wel.

Dit is onze code:
```html
<dso-dropdown-menu checkable="true" dropdownAlign="left" >
    <button type="button" slot="toggle" class="dso-tertiary" aria-haspopup="menu" id="meerOpties">
        <span>Meer opties</span>
    </button>
    <div class="dso-dropdown-options text-left" role="menu" aria-labelledby="meerOpties" data-popper-placement="bottom-start">
        <ul>
              ...
        </ul>
    </div>
</dso-dropdown-menu>
```

Dit is ook van toepassing op 62.11.1. Met de toolkit 62.10.0 werkt de dropdown wel.

**Comment by tfrijsewijk** [comment]
Ik heb iets gevonden: Het lijkt erop alsof het niet werkt als een Dropdown Menu _in_ een Shadow root staat:

![image](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/f2bfa7bc-fc5e-4985-a3d2-a8a019d65834)

Ik heb een test Web Component gemaakt. Deze heeft een Shadow root. In deze Shadow root heb ik een `<dso-dropdown-menu>` geplaatst. En deze werkt niet.

**Comment by yktoo** [comment]
Meeste applicaties binnen het portaal werken binnen Shadow DOM, dit is de aanbevolen manier.
