### ISSUE TITLE
Banner: Fix background color

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#2586]
Met de aanpassing van een klein image op de kleinste schermgroottes is er een onverwacht effect. 

PR12 heeft zelf er altijd een groene achtergrond onder liggen (Custom CSS) 
<img width="564" alt="Screenshot 2024-03-18 at 13 32 59" src="https://github.com/dso-toolkit/dso-toolkit/assets/36912722/9a235597-730b-4f2b-a9b9-9b0bec799828">

Maar PR02 niet. 
<img width="562" alt="Screenshot 2024-03-18 at 13 33 06" src="https://github.com/dso-toolkit/dso-toolkit/assets/36912722/fecfbcb1-72d3-4082-a9ea-29a1d77b035a">

De versie van PR12 is de gewenste stijl. Maar die zit nu niet in de toolkit. 

De wens is om de een dso-banner eronder altijd een groene achtergrond te geven net als dso-featured. 

Extra voordeel als de pagina laadt en deze is langzaam en dan zie je wel eerst de groene topbalk dat helpt bij het gevoel dat de pagina al aan het laden is. (Het is bijna een mini skeleton loader)

**Comment by hansgrimm** [comment]
Deze is interessant (op z'n chinees dan): de property `background-size: 0` lijkt hier ook de achtergrondkleur uit te zetten, want hij verschijnt als je die property uit toggelt. MAAR, als je 'm dan weer aan toggelt, dan blijft de achtergrondkleur staan. Hier lijkt wat inconsistent browsergedrag de kop op te steken. Ik heb dat nu gefixt door een `::after` met de juiste achtergrondkleur te zetten, met een `z-index: -1;`. dat fixt het sowieso. Ik moest daarvoor wel de bestaande clearfix mollen en dat opvangen met een `overflow: hidden`, die in principe hetzelfde doet als de clearfix (containercollapse voorkomen).

Daarnaast hebben we nog te maken met het feit dat er op prod op minimaal 3 verschillende manieren de banner ingevuld wordt; dat maakt het er niet simpeler op, maar zolang men maar de class `dso-banner` op de `row` zet, dan knalt de `::after` erin en hebben we een groene background.

@MichielDHVD straks even samen naar kijken?
