### ISSUE TITLE
Modal: Focus strategie

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#2594]
Originele melding:

> Goedemiddag!
> 
> Wij gebruiken de `dso-date-picker` binnen een `dso-modal`. Als de modal opent, dan staat de focus op de Annuleren knop. Graag zouden we de focus op de date picker willen hebben. Nu heeft de date picker een `[dsoAutofocus]` directive, maar deze lijkt niet te functioneren.
> 
> Zou de modal niet standaard de focus moeten leggen op het eerste input element?
> Zo nee, hoe dan wel?
> 
> ![image](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/f6229e38-27ae-4848-ad77-7a75aee8e0e1)

Er spelen een aantal dingen:

* Ik kan dit niet reproduceren. Bij mij is het eerst gefocuste element altijd de `<div class="dso-body">` in Modal, omdat deze een `tabindex="0"` krijgt. Maar dit is nooit zichtbaar, omdat er geen focusstijling is.
* De Auto Focus functionaliteit van Date Picker werkt niet (in Modal?).
* Een gewoon `<input type="text">` element krijgt ook geen focus.

Maar Auto Focus van Date Picker fixen is symptoombestrijding, want een gewoon `<input type="text">` veld krijgt ook geen focus. Auto Focus wil je inzetten als je buiten de (standaard) browser autofocus routines om een element wilt laten focussen (bij pageload of modal activatie).

Wat ik verder mis zijn richtlijnen voor de Modal. Hoe zet je een Modal correct in? Een veel gebruikt argument is dat de sluitenknop altijd als eerste de focus moet hebben, maar volgens MDN ligt dat genuanceerder.

Daarnaast, niet alle Modals hebben sluitknoppen. En de annuleren knop kan invasiever zijn dat je lief is, ik denk dat het daarom niet automatisch het volgende focuswaardige element is.

Sommige Modals zijn ter kennisgeving en hebben een primaire knop. Het ligt voor de hand om de focus daar dan te zetten.

In dit issue wil ik:
* `<div class="dso-body" tabindex="0">` opnieuw tegen het licht houden; (UX+Accessibility+dev)
* Richtlijnen opstellen hoe Modals gebruikt moeten worden; (UX+Accessibility)
* Uitzoeken waarom in bovenstaande melding de initiele focus op de "Annuleren"-knop komt, en niet op de focusbare div. (Dev)
* Uitzoeken waarom `dsoAutoFocus` van Date Picker niet werkt (Dev).

**Comment by tfrijsewijk** [comment]
@timveld @dso-toolkit/dso-ux @hansgrimm @iterox kunnen jullie meedenken?

**Comment by tfrijsewijk** [comment]
@tfrijsewijk gaat een voorstel uitwerken

**Comment by tfrijsewijk** [comment]
Mijn bevindingen:

* We moeten twee soorten Modals ondersteunen. Een impliciet sluitbare en expliciet sluitbare.
* Een impliciet sluitbare Modal sluit als de gebruiker de sluiten knop (in de vorm van een kruis, rechtsboven) activeert, naast de Modal klikt, of op Esc drukt.
* Een expliciet sluitbare sluit pas als een gebruiker een actie heeft gedaan: "Wilt u dit project verwijderen? [Ja/Nee]". "U bent uitgelogd. [Ok]" Deze Modal sluit niet zoals een impliciet sluitbare Modal dat doet.
* Het eerste focusbare element is het eerste interactieve element. Bij een impliciet sluitbare Modal is dat altijd het sluitenkruis. Bij een expliciet sluitbare modal is dat een interactief element in de body van de Modal, of de eerste actieknop (Ja/Nee/Annuleren/Whaver) in de footer van de Modal.

Het lukt mij niet om de bevinding mbt. `dsoAutofocus` te reproduceren.

Vervolg:
* Met UX bespreken. Openstaand punt: 
  * Beperken tot impliciet/expliciet of uitbreiden naar impliciet/expliciet (acties vrije invoer)/alert (alleen OK)/confirm (ja/nee of ok/annuleren)
  * Is er een use case voor impliciet sluitbare Modals?
* Na akkoord/verfijning: Uitwerken hoe we bovenstaande richtlijnen en regels technisch gaan implementeren.
* Bouwen.

**Comment by tfrijsewijk** [comment]
Bespreken tijdens UX overleg op maandag 1 juli.

**Comment by DjangoBlok** [comment]
Ziet er goed uit @tfrijsewijk Thomas!
Mijn voorzet:
Use Case van impliciet sluitbaar:
- Vergroting van afbeelding
- Vergroting van tabel
- Informatieve meldingen?

Use case van expliciet sluitbaar:
- Melding met juridische achtergrond (akkoord van gebruiker, accepteren voorwaarden etc)
- Het systeem kan niet verder zonder keuze van de gebruiker. (zoals bevestiging van de gebruiker)

**Comment by tfrijsewijk** [comment]
> Use Case van impliciet sluitbaar:
> 
> * Vergroting van afbeelding
> * Vergroting van tabel

Hierbij refereer je naar Image Overlay en Responsive Table. Deze componenten maken geen gebruik van het Modal component.

Vanuit het design systeem gedachtegoed zou ik bovenstaande Modal functionaliteit daarom niet automatisch willen koppelen.

Ik stel voor dat we ons voor nu beperken tot Modal. De twee varianten opleveren zoals hierboven omschreven. Daarna kijken of Modal toepasbaar is in Image Overlay en Responsive Table. Als dat niet zo is, expliciet benoemen dat Image Overlay en Responsive Table impliciet sluitbaar zijn: Dit is al zo geimplementeerd.

> * Informatieve meldingen?

Lijkt mij een goed voorbeeld om bij de documentatie te zetten.

> Use case van expliciet sluitbaar:
> 
> * Melding met juridische achtergrond (akkoord van gebruiker, accepteren voorwaarden etc)
> * Het systeem kan niet verder zonder keuze van de gebruiker. (zoals bevestiging van de gebruiker)

Lijkt mij prima!

Ik ga dit issue sluiten en een vervolg issue maken.
