### ISSUE TITLE
Selectable: Focus outline to include input

### ISSUE THREAD

**Issue by MYpenburg** [dso-toolkit/dso-toolkit#2598]
Nu is het dit:
<img width="787" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/7289928/fdd90865-c295-4fdc-be62-cf46ab5e6e37">

<img width="778" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/7289928/d8f69291-546e-4ec6-9601-dc8139a7f6ec">

Liever de border doortrekken tot om de radio/checkbox

**Comment by hansgrimm** [comment]
@MYpenburg Ik heb nu de focus een treetje hoger gezet, zodat de 'input' nu ook binnen de outline valt. Consequentie is wel dat dat element de hele beschikbare breedte pakt, zie screenshot.

In de praktijk zal dat zelden een probleem zijn, maar in storybook gaat-i-e "kamerbreed".

![Image](https://github.com/dso-toolkit/dso-toolkit/assets/506527/186cbbe5-d5bb-4c7b-a1d2-154a85c0b8ad)

**Comment by tfrijsewijk** [comment]
> @MYpenburg Ik heb nu de focus een treetje hoger gezet, zodat de 'input' nu ook binnen de outline valt. Consequentie is wel dat dat element de hele beschikbare breedte pakt, zie screenshot.
> 
> In de praktijk zal dat zelden een probleem zijn, maar in storybook gaat-i-e "kamerbreed".
> 
> ![Image](https://private-user-images.githubusercontent.com/506527/317730901-186cbbe5-d5bb-4c7b-a1d2-154a85c0b8ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2NTU4NTUsIm5iZiI6MTcxMTY1NTU1NSwicGF0aCI6Ii81MDY1MjcvMzE3NzMwOTAxLTE4NmNiYmU1LWQ1YmItNGM3Yi1hMWQyLTE1NGE4NWMwYjhhZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOFQxOTUyMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MmQ1ZGE2NDhiODdkMzViYzcyYWQ1NmExMTMwMzc1YTRjZGVlNjE3NWNmZGFiY2E5MGEzOTI1ZTQ5ZGZmOGFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WWVWEcSgQrISutr_VM5MLuQLisc0S3EpXBUn4fGIK34)

Ik ben het er niet mee eens dat het in de praktijk zelden een probleem zal zijn:
- Selectable is een block styled element (vandaar de breedte). Dit element zal vrijwel altijd in een block level element geplaatst worden. En die pakken ook alle ruimte die er is.
- Daarnaast vind ik het niet meer duidelijk welk interactief element er is gefocust, doordat Selectable en Info Button in het focus gebied vallen.
- Verder vind ik dit vergelijkbaar met block styled `<a>` elementen waarbij je dus "op niets" kan klikken en er toch iets gebeurt. Deze situatie is precies andersom: Het focus gebied is breder dan het klikbare actiegebied.

**Comment by hansgrimm** [comment]
Het is `focus-visible` dus met klikken gebeurt er niks. Het is puur keyboard interactie.

**Comment by MYpenburg** [comment]
Dit is niet fijn. Kan de hierarchie niet worden aangepast zodat er een niveau ontstaat waar de selectable en het label in zit, maar niet de (i)? Dan zijn we er toch?

**Comment by hansgrimm** [comment]
Dan vrees ik dat we naar een breaking change gaan, maar ik zal eens kijken wat ik nog in de trukendoos heb zitten 😉

**Comment by hansgrimm** [comment]
> Dan vrees ik dat we naar een breaking change gaan, maar ik zal eens kijken wat ik nog in de trukendoos heb zitten 😉

Gelukkig toch non-breaking kunnen fixen :)

Overigens is er een groot verschil is focusgedrag tussen de html/css-versie en het webcomponent. by design?

**Comment by hansgrimm** [comment]
@MYpenburg de aangepaste versie is hier te bewonderen: 
https://storybook.dso-toolkit.nl/_2598-selectable-focus-outline-to-include-input/?path=/story/core-selectable--checkbox
