### ISSUE TITLE
Brakke keyboard interactie in radio group

### ISSUE THREAD

**Issue by MYpenburg** [dso-toolkit/dso-toolkit#2599]
Als je met tab/shift tab de focus krijgt op een radio group, wordt met tab het eerste element gefocust, met shift-tab het laatste element. Weet even niet of dat wel de bedoeling is, omdat je de groep focust als geheel lijkt het me logischer dat je altijd het eerste element, of het geselecteerde element pakt. Maar dit is ter discussie, benieuwd wat Tim en Hans daarvan vinden.

Storender is het dat, wanneer je met de pijltjes door de groep heen gaat, dat het gefocuste element direct geselecteerd wordt, wat zeker in de vragenbomen vervelende bijeffecten heeft (vragen submitten en verversen enzo). Het lijkt me dat je vrijblijvend door de lijst moet kunnen gaan met de pijltjestoetsen en dat je pas met enter of spatie je selectie maakt. 

<img width="787" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/7289928/7b4bcd63-3ab2-4d38-a12e-7142e72c4acc">

**Comment by tfrijsewijk** [comment]
@MYpenburg @hansgrimm Waarom is dit issue gesloten?

**Comment by hansgrimm** [comment]
> @MYpenburg @hansgrimm Waarom is dit issue gesloten?

Omdat de keyboard-interactie gewoon klopt, ook volgens @timveld. Het gaat hier gewoon zoals het hoort, dus er valt niets te fixen.

**Comment by tfrijsewijk** [comment]
Dank voor de toelichting 👍
