### ISSUE TITLE
Documentation: Colors update

### ISSUE THREAD

**Issue by VolleMelk** [dso-toolkit/dso-toolkit#26]

**Comment by Poofy83** [comment]
Testable: https://www.dso-toolkit.nl/unstable/docs/colors.html

Er waren veel discrepanties tussen de geplakte tekst en de tekst uit de bijgesloten afbeelding. Ik heb van beide het beste gemaakt.

Ik wil voorstellen documentatie pagina's in het vervolg al in Markdown aan te leveren, wat denk jij daarvan?

Idealiter check je de repository zelf uit en leg je een PR voor, dan kun je het meteen maken zoals je het wilt: Scheelt weer het speccen van een ticket.

/Original commenter: Thomas

**Comment by legolas** [comment]
Markdown heeft ook mijn voorkeur.
