### ISSUE TITLE
Form Group: Rich content overflow

### ISSUE THREAD

**Issue by MYpenburg** [dso-toolkit/dso-toolkit#2600]
<img width="778" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/7289928/120a3e94-1241-44a0-b841-58e003c6c4b1">

**Comment by tfrijsewijk** [comment]
Dit lijkt erg op wat er in #2333 wordt gevraagd, maar dat issue hebben we nog niet opgepakt. Hoe hebben we dit afgerond?

Mogelijk dat in dit issue het wel om dat grijze vlak eromheen gaat, Info heet dat component geloof ik. Dat daar een overflow hidden oid op staat.

**Comment by hansgrimm** [comment]
> Dit lijkt erg op wat er in #2333 wordt gevraagd, maar dat issue hebben we nog niet opgepakt. Hoe hebben we dit afgerond?
> 
> Mogelijk dat in dit issue het wel om dat grijze vlak eromheen gaat, Info heet dat component geloof ik. Dat daar een overflow hidden oid op staat.

Deze vind ik toch wel heel anders dan #2333 . ik doe deze iig

**Comment by hansgrimm** [comment]
@MYpenburg oorzaak is dat `dso-rich-content` de property `overflow-x: auto` heeft, waardoor de overflow op de x-as niet meer default zichtbaar is, en (heel naar) op de y-as ook niet.. Aangezien de `outline`-property niet meedoet in de layout, valt die bij alle elementen die strak tegen de rand van hun container staan (in dit geval links en onder) weg.
Zie hier: 
![Image](https://github.com/dso-toolkit/dso-toolkit/assets/506527/8d0e9dd2-2b48-41cc-b57d-fcf757f11dcd)
Hier is niet 1-2-3 een goeie oplossing voor te bedenken, want die `overflow-x` hebben we nodig om hier tabellen te faciliteren.

Lastig.

**Comment by tfrijsewijk** [comment]
Overigens vind ik die underline zeer storend. Kunnen we die underline en dit focus problem wellicht oplossen door deze werkvorm als component aan te bieden? Ofwel, lost #2333 deze bevindingen op?

**Comment by hansgrimm** [comment]
> Overigens vind ik die underline zeer storend. 
welke underline?

> Kunnen we die underline en dit focus problem wellicht oplossen door deze werkvorm als component aan te bieden? Ofwel, lost #2333 deze bevindingen op?
Die kwestie met de focus-outline niet denk ik.

**Comment by tfrijsewijk** [comment]
> > Overigens vind ik die underline zeer storend.
> 
> welke underline?

<img width="548" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/9696261/8356db36-2d1f-43ad-b581-2dcd5b276faa">


> > Kunnen we die underline en dit focus problem wellicht oplossen door deze werkvorm als component aan te bieden? Ofwel, lost #2333 deze bevindingen op?
> 
> Die kwestie met de focus-outline niet denk ik.

Zo'n vermoeden had ik al... Jammer :(

**Comment by hansgrimm** [comment]
> > > Overigens vind ik die underline zeer storend.
> > 
> > 
> > welke underline?
> 
> <img alt="image" width="548" src="https://private-user-images.githubusercontent.com/9696261/319567653-8356db36-2d1f-43ad-b581-2dcd5b276faa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMzExMzUsIm5iZiI6MTcxMjIzMDgzNSwicGF0aCI6Ii85Njk2MjYxLzMxOTU2NzY1My04MzU2ZGIzNi0yZDFmLTQzYWQtYjU4MS0yZGNkNWIyNzZmYWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDRUMTE0MDM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGM0YmE1ZWY2ZTRhMjdjYmMwYTk3OGZkNjJiNTAxMDJlMjI1NDAyNGQ4ZDk0YzZmNWE4NWIyMzIzYzExYjFiMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.qes4KHOSt2FBDsh69TNdnKAcYCoGnlFPQXKjwsNZ5Xo">

Dat is raar zeg.. als ik de knop wat naar boven haal, is dit de focus-state:|
![Scherm­afbeelding 2024-04-04 om 13 42 21](https://github.com/dso-toolkit/dso-toolkit/assets/506527/d20ce16d-d8dc-426c-a58c-1aba4ba34f95)

en hover:
![Scherm­afbeelding 2024-04-04 om 13 42 37](https://github.com/dso-toolkit/dso-toolkit/assets/506527/2300f22e-39bf-4e10-b7c4-a48832abd3a7)
Met een echte underline..

**Comment by tfrijsewijk** [comment]
🤷

**Comment by hansgrimm** [comment]
@tfrijsewijk Misschien kunnen we hier iets met `:has(button:last-child):not(:has(table))` of zoiets dergelijks. dat zou de meeste scenario's moeten dekken.

Voelt wel extreem hacky-hacky-hacky :)

**Comment by hansgrimm** [comment]
^^ iets met paarden en zebra's: natuurlijk kunnen we ook volstaan met `:has(table) { overflow-x: auto; }`.

**Comment by tfrijsewijk** [comment]
Ja, idd.. Waarom niet 🤷 

Kunnen we niet iets met negatieve margins/positieve paddings doen? Ik heb dat border-box model niet helemaal scherp, maar creeeren we dan niet wat lucht om de focus in z'n geheel te tonen? Of groeit de scrollbar dan ook onlogisch mee?

**Comment by hansgrimm** [comment]
> Ja, idd.. Waarom niet 🤷
> 
> Kunnen we niet iets met negatieve margins/positieve paddings doen? Ik heb dat border-box model niet helemaal scherp, maar creeeren we dan niet wat lucht om de focus in z'n geheel te tonen? Of groeit de scrollbar dan ook onlogisch mee?

Omdat het hier gaat om de outline, kan je die alleen tevoorschijn halen door inderdaad iets met margins te doen, maar dan komt de knop weer visueel uit het lood te staan t.o.v. de rest van de content, met name als hij niet gefocust is. dat maakt het alleen maar erger.
De enige situatie waar het nu niet goed gaat met de focus outline van een knop, is als hij samen met een tabel in de rich content staat, en die knop ook nog eens het laatste element is. Daarbij is het m.i. geen echte a11y-issue, want er is een outline, al is die maar deels zichtbaar.
