### ISSUE TITLE
DSO IconFont

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#261]
In de alerts staan icoontjes. https://dso-toolkit.nl/3.1.0/components/detail/alert.html

Deze icoontjes zijn niet los beschikbaar. Dit is wel wenselijk zodat op verschillende plekken de icoontjes gebruikt kunnen worden. 

Is het mogelijk deze op dezelfde manier te implementeren als font awesome ? 

In dit issue gaat het alleen om de 4 icons bij de verschillende alerts. 

Een voorbeeld pagina waar dit van toepassing is staat hieronder beschreven. 

Lijkt me handig om deze verschillende icons onder het kopje icons in de toolkit te stoppen. 

![image](https://user-images.githubusercontent.com/36912722/51186746-a6176900-18da-11e9-9e25-c67c7b3bab33.png)

*Sidenote* De kleur van het rondje bij de succes (groene) alert klopt niet. Deze is nu #39870c deze moet zijn #79b929. Kan dit meegenomen worden in dit issue. Of moet er een los issue voor gemaakt worden?

**Comment by PieterVerheij** [comment]
@MichielDHVD het is handiger om de kleur aanpassing in een apart issue te stoppen.

**Comment by tfrijsewijk** [comment]
Implementeren zoals FontAwesome dat ook doet is een brede definitie.

Tot en met FontAwesome 4 zaten alle iconen in een font. Met `<i class="fa fa-rocket"></i>` werden fonts getoond. Vanaf FontAwesome 5 is er _ook_ een SVG+gescripte variant. Ongeveer dezelfde notatie maar de icons worden dmv. javascript ingevlogen: De daadwerkelijke SVG wordt in het DOM geplaatst.

Voor meer info zie de FA site: https://fontawesome.com/start Er staat een question mark waar de verschillen van de twee strategiën worden uiteengezet.

Je voelt 'm al aankomen, maar als we net zoals FA5 een scriptende oplossing gaan aanbieden zal deze voor de verschillende front-end frameworks geimplementeerd moeten worden.

Alternatief is de CSS `@font-face` oplossing of het icoon opnemen als `background` met base64 (zoals nu bij accordion gebeurd).

Deze oplossing is overigens ook niet waterdicht: De aangeleverde iconen omvatten best veel:

![image](https://user-images.githubusercontent.com/9696261/51301657-40d58c00-1a30-11e9-87d2-fa5da3f7c6fa.png)

Het icoon begint bij de ronde achtergrond met kleur. Het icoon bestaat uit twee kleuren: van de achtergrond en van het symbool.

Zoals bij FontAwesome kun je een kleur zetten (CSS `color`-property), maar welke kleur wordt dat? Of gaan we dat niet ondersteunen en is de kleurstelling fixed.

Bij een base64 `background` oplossing is er helemaal geen styling nodig.

Overigens zijn er op de `@font-face` en `background` met base64 oplossingen nog varianten te bedenken.

**Comment by MichielDHVD** [comment]
De kleurstelling gaan we fixed houden. 

Qua techniek maakt het niet uit, het wordt in ieder geval aangeroepen in deze vorm <i class="fa fa-rocket"></i>  neem ik aan ? 

Daar draait het om. Verder lijkt me het beste de manier te gebruiken waar we niet alles omgooien. Dus zo min mogelijk de scriptende oplossing waar teams zelf eerst nog in hun frame work verschillende acties moeten uitvoeren

**Comment by PieterVerheij** [comment]
Een base64 oplossing is de beste oplossing voor dit speicifiek scenario met vaste icon-varianten.
 
Echter: als we in de toekomst iconen willen toevoegen die ook in verschillende kleurvarianten gebruikt moeten kunnen worden, is het beter om voor een eigen icon-font te gaan.

**Comment by MichielDHVD** [comment]
Op dit moment wordt er een iconen set ontwikkeld. Deze wordt vervolgens in een font gebakken. Vandaag nog met @tfrijsewijk overlegd dat we het systeem zo willen gaan inrichten om dit te gaan ondersteunen.

**Comment by tfrijsewijk** [comment]
Ik lees nu dat de bal bij mij ligt, ik kom hier op terug

**Comment by MichielDHVD** [comment]
Is hier al meer bekend over @tfrijsewijk ?

**Comment by tfrijsewijk** [comment]
How gaat het met de iconen? Hoe worden die gemaakt?

En vooral: Wat willen jullie? Gaan we voor SVG's of gaan we voor een icon-font set? Zo min mogelijk scriptwerk ga je naar een icon-font.

Ik kwam op http://fontastic.me/, ziet er veelbelovend uit

**Comment by PieterVerheij** [comment]
> Ik kwam op http://fontastic.me/, ziet er veelbelovend uit
Inderdaad!

**Comment by MichielDHVD** [comment]
Het verhaal over de iconen. 

Eerst zou een extern bureau deze gaan ontwikkelen. Maar daar is nooit de uitvraag over gedaan. 
Toen werd er gekeken naar inhouse ontwikkeling.  
Om vervolgens te informeren of de iconen van de rijkshuisstijl gebruikt mochten worden. 
Hier hebben we deze week bericht over terug gekregen dat we deze niet mogen gebruiken. 
Nu gaat een ontwerper hier inhouse weer mee aan de slag. Deze eerste iconen zullen ontwikkeld worden voor de homepage. 

Dat betekent dat voorlopig de iconen van font awesome gebruikt zullen worden. 

Maar zodra de Homepage iconen klaar zijn lijkt het me slim om de oplossing die jullie hier beschrijven. 

De fontastic oplossing te gebruiken. 

Dat neemt niet weg dat we nog steeds zitten met het originele onderdeel van dit issue. Namelijk het beschikbaar stellen van de losse icoontjes van de alerts. Zodat de developers deze kunnen gebruiken.

**Comment by PieterVerheij** [comment]
> > Ik kwam op http://fontastic.me/, ziet er veelbelovend uit
> Inderdaad!

Echter, snel testje doet anders concluderen: timeouts en slechte preview van de karakters. Ik vermoed dat wanneer we alleen eigen iconen gaan gebruiken Glyphter.com een betere, stabielere optie is.

**Comment by MichielDHVD** [comment]
De situatie is ook dat we in gradaties onze eigen iconen gaan gebruiken. Dus er zal een afwisseling zijn tussen nieuwe iconen en bestaande font awesome iconen totdat alle font awesome iconen zijn veranderd. 

Belangrijkste is dat het voor developers niet anders moet zijn om iconen te implementeren. Of is dat niet mogelijk?

**Comment by PieterVerheij** [comment]
Dan gaan we twee fonts naast elkaar gebruiken: `font awesome` en het eigen `dso webfont`. Met classes (bv. `fa` en `di`) kan je dan het juiste icon gebruiken. 

Mee eens, @tfrijsewijk ?

**Comment by tfrijsewijk** [comment]
Alternatief is dat we direct overgaan naar `di` modifiers. De iconen die we missen stijlen we naar de FontAwesome variant, maar de API van de icons blijft gelijk.

Dus:
* `di di-exclamation-mark` geeft het DSO icoon, omdat deze aangeleverd wordt door DSO.
* Maar er is ook een hamburger icoon nodig. Dit icoon heeft DSO (nog) niet aangeleverd maar we maken wel `di di-bars` maar we stijlen het icoon alsof je `fa fa-bars` inzet.

**Comment by PieterVerheij** [comment]
@tfrijsewijk uiteindelijke naamgeving van iconen moeten we even bespreken.

**Comment by MichielDHVD** [comment]
Klinkt goed! Lijkt me een praktische oplossing. Ik ga ook achter het hamburger icoon aan. De huidige stoort me al een tijdje, past niet goed in de stijl.

**Comment by MichielDHVD** [comment]
De specifieke voorkeur weet ik niet. @TonD83 @WidoBurg hoe kijken jullie hier tegen aan?

**Comment by TonD83** [comment]
Liever een span, een i misbruiken is 'fout' in het kader van a11y/wcag. 

https://stackoverflow.com/questions/23015537/how-do-i-make-font-awesome-wcag-2-0-compatible

**Comment by MichielDHVD** [comment]
Dan lijkt het met slim om met <span> te gaan werken als dat de voorkeur heeft.

**Comment by tfrijsewijk** [comment]
Uitgekomen in 7.2.0:

* https://dso-toolkit.nl/7.2.0/components/detail/icon.html
* https://dso-toolkit.nl/7.2.0/components/detail/accordion.html
* https://dso-toolkit.nl/7.2.0/components/detail/conclusion.html
* https://dso-toolkit.nl/7.2.0/components/detail/alert.html

Hier zijn de visuele verschillen te zien: https://percy.io/dso-toolkit/dso-toolkit/builds/1936543

**Comment by TonD83** [comment]
Toegegeven, het is nergens gespecificeerd, maar nu we 7.2.0 gaan gebruiken en dus ook deze iconen, lopen we er tegenaan dat deze te groot zijn voor onze toepassing. Ik heb nu even een di-small modifier aan onze code toegevoegd, omdat we de iconen ook als 16px variant gebruiken in onze schermen.

@MichielDHVD Zou je hier over willen nadenken welke afmetingen we allemaal nodig hebben en bij @tfrijsewijk een set aan mooie modifiers willen bestellen? Alvast bedankt! Voor nu doen we het dus even met onderstaand... 

`
span.di.di-small::before {
    height: 16px;
    width: 16px;
    line-height: 16px;
    font-size: 10px;
}`

**Comment by MichielDHVD** [comment]
Goed voorstel. We zijn steeds meer bezig om de toolkit te specificeren. Dit zal een uitstekende toevoeging zijn. Ik ga het meenemen.
