### ISSUE TITLE
Image Overlay: Kleine afbeelding krijgt ten onrechte een vergroot icoon

### ISSUE THREAD

**Issue by DjangoBlok** [dso-toolkit/dso-toolkit#2611]
In onderstaand document zijn kleine afbeeldingen toegevoegd. Deze kleine afbeledingen lijken ten onrechte een vergroot icoon te krijgen.  

**Reproductie**
Op productieomgeving
Open document Omgevingsvisie Valkenburg aan de Geul (19-03-2024)  /akn/nl/act/gm0994/2024/Regelingee464d192a194e72ac0944f82ae8d434
(https://omgevingswet.overheid.nl/regels-op-de-kaart/viewer/(documenten/gemeente//rechter-paneel:document/_akn_nl_act_gm0994_2024_Regelingee464d192a194e72ac0944f82ae8d434_akn_nl_bill_gm0994_2024_besluit58eab5bae0b34199b885be2ea7551ef1/inhoud)?regelsandere=regels,andere&locatie-stelsel=RD&locatie-x=186094&locatie-y=320068&geodocId=akn-nl-act-gm0994-2024-regelingee464d192a194e72ac0944f82ae8d434-akn-nl-bill-gm0994-2024-besluit58eab5bae0b34199b885be2ea7551ef1&session=62e240e2-941f-4edc-9845-c3264d630bca)
In de inhoud tab zie bij bv. Hoodstuk 3.1 tabel '1.1 Leidende principes' een niet werkend 'vergroot afbeelding' symbool

![Image](https://github.com/dso-toolkit/dso-toolkit/assets/34900082/b5a1d050-708b-4c77-a433-47ec4540b455)

**Comment by tfrijsewijk** [comment]
Er zijn meerdere afbeeldingen die wel een vergrootglas krijgen maar waar het inzoomen vervolgens niets doet. Mogelijk gerelateerd..



![Image](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/19699457-f0f5-403c-99bc-11c3af19ac30)

**Comment by iterox** [comment]
Er moet gekeken worden naar de functionaliteit van de web component image-overlay om te bepalen hoe groot is de afbeelding en hoeveel ruimte is er beschikbaar.

**Comment by DjangoBlok** [comment]
Ik dacht dat het zoiets was: 
- Als een afbeelding op 100% is gezet door de planmaker dan moeten we een vergrootfunctie aanbieden. 
- Als een afbeelding een vaste grootte heeft meegekregen, dan kunnen we ervan uitgaan dat vergroten niet nodig is?

**Comment by tfrijsewijk** [comment]
> Als een afbeelding een vaste grootte heeft meegekregen, dan kunnen we ervan uitgaan dat vergroten niet nodig is?

Die planmaker kan niet weten hoeveel ruimte er op de locatie van presenteren is, lijkt mij.

@iterox Overigens: Ik meld in dit issue (https://github.com/dso-toolkit/dso-toolkit/issues/2611#issuecomment-2039899346) een andere bevinding die mogelijk gerelateerd is.

**Comment by iterox** [comment]
De afbeelding (In de inhoud tab zie bij bv. Hoodstuk 3.1 tabel '1.1 Leidende principes' een niet werkend 'vergroot afbeelding' symbool) die ten onrechte een vergrootglas lijkt te krijgen, krijgt deze echter wel terecht, want de intirinsieke of natural height en width zijn groter dan de gettonde:
![Screenshot 2024-04-30 at 15 42 26](https://github.com/dso-toolkit/dso-toolkit/assets/4646174/3b0bad0f-04b4-4a2c-98c8-a116e1dc94fc)
Echter, omdat in het Image Overlay component als 1 van de voorwaarden voor het vergroot tonen van een afbeelding geldt dat het attribuut `alt` gevuld moet zijn en dat NIET is wordt er geen vergroting getoond. De vraag is waarom is het gevuld zijn van het attribuut `alt` een voorwaarde voor het tonen van een vergrote of werkelijke formaat afbeelding.
NB: in dit document worden alle afbeeldingen zonder alt-attribuut aangeleverd. Zie dat het een optioneel attribuut is in https://koop.gitlab.io/STOP/standaard/1.3.0/tekst_xsd_Element_tekst_Illustratie.html

**Comment by tfrijsewijk** [comment]
Ik denk dat het te maken heeft met de semantiek van de afbeelding. Een `<img alt="">` geeft aan dat het een decoratieve afbeelding is: Inhoudelijk zou de afbeelding achterwege gelaten kunnen worden zonder de boodschap aan te passen.

Het inzoomen op decoratieve afbeeldingen voegt daarmee niets toe.

Maar wellicht dat @hansgrimm hier wat over kan toevoegen?

**Comment by hansgrimm** [comment]
Ik denk dat we inderdaad een onderscheid kunnen maken tussen een informatieve afbeelding (moet kunnen inzoomen, gevuld alt attribuut) en een decoratieve afbeelding (niet inzoomen, leeg alt attribuut). `[alt=""]` is de onderscheidende selector.

**Comment by iterox** [comment]
Ok. Een leeg alt attribuut is een decoratieve afbeelding. Prima. Betekent wel dat in de betrffende omgevingsvisie geen enkele afbeelding meer vergroot kan worden. Zijn allemaal zonder alt attribuut. Het zij zo.

**Comment by DjangoBlok** [comment]
Ik zie in de STOP beschrijving een schaal attribuut. 
"Een (inline) Illustratie MAG GEEN attribuut @schaal hebben."
Kunnen we daar iets mee? Gaat het goed als een afbeelding zonder schaal niet kunnen vergroten?

**Comment by hansgrimm** [comment]
> Ik zie in de STOP beschrijving een schaal attribuut. "Een (inline) Illustratie MAG GEEN attribuut @schaal hebben." Kunnen we daar iets mee? Gaat het goed als een afbeelding zonder schaal niet kunnen vergroten?

Als we in de markup een "handvatje" hebben om CSS en/of JS aan vast te knopen, dan moet dat helemaal goed komen.

**Comment by iterox** [comment]
In `figuur.node.tsx` wordt het alt-attribuut van de img binnen de `dso-image-overlay` gevuld op basis van de volgende expressie `alt={illustratie.alt ?? titel ?? illustratie.naam ?? undefined}`. Deze resolved voor alle Illustraties in de ontwerp-omgevingsvisie tot lege string, omdat Illustratie.alt null is en titel een lege string is.

Dit is een Figuur-node:
```<Figuur eId='div_2__content_2.3__img_o_1' wId='gm0994_b83e070a1e0b499799f1140e90cc7913__div_2__content_2.3__img_o_1'><Titel/><Illustratie naam='https://pro.ozon.dso.kadaster.nl/publiek/omgevingsdocumenten/api/presenteren/v7/ontwerpafbeeldingen/gm0994/_akn_nl_bill_gm0994_2024_besluit58eab5bae0b34199b885be2ea7551ef1/8b221acc786d4e62998a416eb036a27b.jpg' breedte='1176' hoogte='833'/><Bijschrift locatie='onder'/><Bron/></Figuur>`

**Comment by iterox** [comment]
Het lijkt erop dat de STOP standaard niet voldoende mogelijkheden biedt om op een eenduidige manier te kunnen bepalen of een vergooting van de afbeelding getoond moet/mag worden. @iterox  en @DjangoBlok gaan samen optrekken in deze.

**Comment by tfrijsewijk** [comment]
En het component doet in principe wat het moet doen: De afbeelding die is geplaatst kan niet op de maten worden getoond zoals de auteur (bevoegd gezag) wilt omdat de afbeelding niet past. En dan krijg wordt de eindgebruiker de zoom mogelijkheden aangeboden.

Ter behoeve van het overzicht sluit ik het bijbehorende PR maar de branch laten we nog even staan.

**Comment by tfrijsewijk** [comment]
In overleg met @DjangoBlok besloten dit issue te sluiten. Het component werkt naar behoren, in de basis is dit een content issue. We kunnen het verschil tussen decoratieve en informatieve afbeeldingen niet zien.

**Comment by iterox** [comment]
> En het component doet in principe wat het moet doen: De afbeelding die is geplaatst kan niet op de maten worden getoond zoals de auteur (bevoegd gezag) wilt omdat de afbeelding niet past. En dan krijg wordt de eindgebruiker de zoom mogelijkheden aangeboden.
> 
> Ter behoeve van het overzicht sluit ik het bijbehorende PR maar de branch laten we nog even staan.

Zullen we de branch dan ook maar elimineren?

**Comment by tfrijsewijk** [comment]
Lijkt mij een puik plan
