### ISSUE TITLE
Form Group Files: Ondersteuning voor een spinner (progress indicator) tijdens upload van bestand

### ISSUE THREAD

**Issue by MYpenburg** [dso-toolkit/dso-toolkit#2616]
Zie https://storybook.dso-toolkit.nl/62.18.0/?path=/story/html-css-form-groups-files--files

Op de plek van de dso-select willen we (ook) een spinner met een label (progress indicator) kunnen tonen (tijdens het uploaden van het bestand). Hieronder staat goed beschreven wat we willen.

![Image](https://github.com/dso-toolkit/dso-toolkit/assets/7289928/3713c788-e8ef-4494-88d5-671cfea253a5)

Marge horizontaal: 16px 
Marge verticaal: 8px

**Comment by MYpenburg** [comment]
Zie https://storybook.dso-toolkit.nl/62.18.0/?path=/docs/core-progress-indicator--docs

De Tiny variant zorgt ervoor dat het verticale gedrag van de tekstregel niet verandert met of zonder spinner.

**Comment by tfrijsewijk** [comment]
Het component "Form Group: Files" (ja, dat is een component) is helemaal niet voorbereid op deze spinner.

Markup voorschriften zijn absoluut: Je kan niet mix 'n matchen of van de markup voorschriften afstappen. Afnemers en UX designers kunnen "componeren" met componenten. Maar dat kunnen ze alleen in de daarvoor bestempelde "gaten" (excuus voor de oncharmante term).

Highlight Box heeft 'n gat voor de content, Info heeft een gat voor content, Accordion heeft ook een gat. Dit zijn simpele voorbeelden, maar Modal heeft bijvoorbeeld 3 gaten: header, body en footer.

"Form Group: Files" heeft geen gat, je kan dus niet "verder componeren": De muziek eindigt bij dit component.

Ofwel, het tonen van de spinner betekent een uitbreiding op dit component.

De aanpassing op de modellering zou dan zijn:

```ts
export interface FormGroupFiles<TemplateFnReturnType> extends FormGroupBase<TemplateFnReturnType> {
  group: "files";
  addFileButtonVariant: "primary" | "secondary";
  files: FormGroupFilesFile[];
  warning: string;
}

export interface FormGroupFilesFile {
  filename: string;
  confidential?: boolean;
  uploading?: boolean; // <-- Toegevoegd.
}
```

We leveren dan markup voorschriften waarmee je in de applicatie dit component een upload status toont.

Zullen we dit proces voortzetten? Dit is echt een betere opzet dan Progress Indicator verkleinen en forceren.

**Comment by MYpenburg** [comment]
Ja, helemaal goed. En bedankt voor de uitleg

**Comment by iterox** [comment]
@MYpenburg Is hier verder nog iets aan te specificeren? Of kan deze verder naar Refinement?

**Comment by MYpenburg** [comment]
Ik denk dat ie door kan, gisteren dacht @hansgrimm dat ook.
