### ISSUE TITLE
Card: chevron rechts uitlijnen

### ISSUE THREAD

**Issue by iterox** [dso-toolkit/dso-toolkit#2618]
Als afnemer van het component card wil ik over de mogelijkheid beschikken om de chevron van een card met href (https://storybook.dso-toolkit.nl/master/?path=/story/core-card--href-with-button) rechts uit  te lijnen:

<img width="855" alt="Screenshot 2024-04-08 at 16 08 21" src="https://github.com/dso-toolkit/dso-toolkit/assets/4646174/fd7a7b17-86e3-4b80-9a66-7766711feff8">

Mogelijk moeten we dit beperken tot alleen deze variant (https://storybook.dso-toolkit.nl/master/?path=/story/core-card--href-with-button).

**Comment by iterox** [comment]
Is gerelateerd aan #2619

**Comment by tfrijsewijk** [comment]
Dit issue sluit ik, is overlappend met #2666.
