### ISSUE TITLE
Accordion: Geneste accordions

### ISSUE THREAD

**Issue by iterox** [dso-toolkit/dso-toolkit#2619]
Als afnemer van het component accordion wil ik accordions genest weergeven, waarbij de volgende requirements nog niet gerealiseerd kunnen worden:

- Het eerste geneste accordion heeft geen ‘border-top’ ( op de h2 ).
- Teveel padding op ‘:host(.dso-accordion-compact-black) .dso-section-body .dso-section-body-content’ ( de padding-bottom moet volgens design ‘0’ zijn )
- Dubbele border ( op ‘dso-accordion-section.dso-accordion-compact:last-child, dso-accordion-section.dso-accordion-compact-black:last-child’ )

Design:
![image-2024-02-01-16-09-15-391](https://github.com/dso-toolkit/dso-toolkit/assets/4646174/558f3469-59a4-47bc-a3c0-03108a4f64ec)
Voorlopige realisatie in VDK:
![Scherm_afbeelding 2024-04-08 om 11 10 09](https://github.com/dso-toolkit/dso-toolkit/assets/4646174/cefc3722-8db3-454a-948c-1ae0a8da0d60)

Werkzaamheden:
- storybook story hiervoor aanmaken
- styleaanpassingen

**Comment by mduijsens** [comment]
@iterox zijn er hiervoor nog zaken vanuit mij nodig? Ik geloof het niet echt he?

**Comment by hansgrimm** [comment]
De 'nested' versie in Storybook werkt niet, dus momenteel geen geneste versie beschikbaar om om te stijlen.

**Comment by hansgrimm** [comment]
https://dso-toolkit.slack.com/archives/CB417GQBC/p1724676134375099?thread_ts=1712568549.156379&cid=CB417GQBC

**Comment by hansgrimm** [comment]
Deze issue is niet meer relevant (zie Slack link)
