### ISSUE TITLE
Advanced Select: Geselecteerd item prefixen met symbool van de groep

### ISSUE THREAD

**Issue by mduijsens** [dso-toolkit/dso-toolkit#2620]
<h1>Introductie</h1>
<p>We komen er achter dat we nu in een gesloten variant van het nieuwe versie mechanisme voor de gebruiker niet snel te herleiden is of het een ontwerp is. Je kiest hier natuurlijk echt voor als gebruiker, maar tijdens het lezen van de regels kan je dit wel 'vergeten' en je ziet het niet meteen. Dit is ook voor toekomstige regelingdelen. Gaat om de **dso-advanced-select.**</p>
<h1>Oplossing</h1>
<p>In de toolkit gaan we een geel label met de tekst 'ontwerp' aan de voorkant toevoegen in de gesloten versie. Zo kan de gebruiker direct zien of het een vastgestelde (niks), ontwerp (geel label 'ontwerp') of een toekomstige versie (grijs label met 'toekomstig') is. Hier onder een voorbeeld:</p>

<img width="844" alt="labels" src="https://github.com/dso-toolkit/dso-toolkit/assets/170416199/421feaa6-e5c3-44ce-bcf7-68ee9c22891d">

_De bolletjes die worden gebruikt bij openklappen blijven in gebruik, maar nu dus enkel bij de opengeklapte versie_

<h2>Acceptatiecriteria</h2>
<ul>
<li>Het identificatie stukje (label) aan het begin toevoegen op basis van de gemaakte keuze van de gebruiker. 
<ul>
<li>Geen label voor vastgesteld</li>
<li>Grijs label met 'toekomstig' voor toekomstig</li>
<li>Geel label met 'ontwerp' voor ontwerp</li>
</ul>
</li>
</ul>

**Comment by tfrijsewijk** [comment]
We begrijpen het probleem: Een gebruiker moet de Advanced Select open klappen om te zien in welke groep een item zit. In de context van een omgevingsdocument betekent het dat een gebruiker niet in één oogopslag ziet welke status een regeling heeft.

Maar de oplossing zijn we nog over verdeeld.

Want dit is een uitsluitend visuele oplossing waar niet elk type gebruiker mee is geholpen. Een screenreader gebruiker kun je nog servicen met een ouderwetse `<span class="sr-only">`, maar een kleurenblinde is daar niet mee geholpen.

En ik wil dit niet laten uitdraaien op een discussie dat "toegankelijkheid betekent dat het voor iedereen even slecht werkt". De aanleiding voor de wens is voor iedereen een probleem, maar de geschetste oplossing (met toegankelijkheidstruukjes) is niet voor iedereen een oplossing.

Het makkelijkste is het label van de groep voor het gekozen item te zetten, maar wij begrijpen ook wel dat dit geen zaligmakende oplossing is. Immers, het staat dan wel erg veel tekst in het label:

o Ontwerp versie met afgeronde inzage termijn: Omgevingsplan gemeente Dordrecht - Einde inzage: 27-03-2024

Een oplossing weet ik niet, en uitsluitend het gele bolletje willen we ook niet afschieten. Maar we wilden in ieder geval onze overwegingen delen.

cc @mduijsens @DjangoBlok

**Comment by mduijsens** [comment]
Is het niet mogelijk om het gele bolletje te gebruiken en die voor screenreader "ontwerp" te laten oplezen? We willen eigenlijk niet dit soort teksten erbij, neemt gewoon heel veel ruimte in. 

Geel = Ontwerp versie
Groen = Vastgestelde versie
Grijs = Toekomstige versie
Paars = Regel uit andere besluiten

Die teksten zijn veel te lang als we daarmee de dropdown moeten vullen + datum + citeertitel. Voorbeeld zou dan zijn:
"Regels uit andere besluiten - Voorbeschermingsregels hyperscale datacentra in werking per 01-03-2024" En dat is dan nog met een korte titel. Daarom keuze voor bolletje, de herleidbaarheid zit dus als je het open klikt, dan staat er een header boven.

We kwamen zelf ook even niet tot een heel veel betere oplossing, onze hoop was wel dat de verschillende kleuren ver genoeg uit elkaar liggen om echt een probleem te veroorzaken voor kleurenblinden.

**Comment by tfrijsewijk** [comment]
Het gaat niet per se om de screenreader. De toetsenbord gebruiker wilt ook wat, of de kleurenblinde. Met een screenreader only tekst bedienen we die doelgroep niet.

Dat de teksten te lang worden begrijp ik. Dus we kunnen kijken hoe ver we komen door van de gebruiker te verwachten dat de betekenis van de gele bolletjes in de uitklapper staan.

**Comment by mduijsens** [comment]
@Hendriksie volgens mij hebben we nu een dubbele story (#2655)

**Comment by Hendriksie** [comment]
@mduijsens Je hebt gelijk, al gaat het in #2655 over de opties in het uitklap-menu'tje en dit over het verduidelijken van de geselecteerde optie. Maar ik denk dat de 2 prima te combineren zijn. @mduijsens Zal ik dit issue aanvullen met de gegevens uit #2655 ?

**Comment by elinemosterd98** [comment]
Ik heb de oplossing van Mieke aangepast, labels in plaats van bolletjes voor de ingeklapte versie. @tfrijsewijk
