### ISSUE TITLE
Panel resize: Smalste weergave responsive gedrag werkt niet altijd

### ISSUE THREAD

**Issue by mduijsens** [dso-toolkit/dso-toolkit#2622]
In viewer zit een rechter paneel, die kunnen we kleiner maken. De document header wordt nu niet altijd goed responsive.

![Image](https://github.com/dso-toolkit/dso-toolkit/assets/144002683/4d3c13c1-cc96-4c23-aac2-c1d16a8c4263)

Hier hadden label en value onder elkaar moeten staan ipv naast elkaar.

**Comment by tfrijsewijk** [comment]
@mduijsens Maandag gaan we hier voor zitten

**Comment by mduijsens** [comment]
We hebben het niet kunnen reproduceren, dus voor nu afgesloten.

**Comment by mduijsens** [comment]
Ja lijkt mij een goed idee om dat aan te passen, ik zag ook in mobiele weergave dat het daar ook niet werkt. Meteen meenemen dat het voor mobiel ook werkt?

**Comment by tfrijsewijk** [comment]
Ik denk dat het meekomt, maar laten we het zeker testen :+1:

**Comment by iterox** [comment]
Ik wil dit issue challengen. Viewer Regels op de kaart heeft styling gebruikt die dit issue veroorzaakt.

De 1e afbeelding toont een div met class rechter-paneel en row.
De 2e afbeelding toont een h1 met class title.
Wanneer van rechter-paneel de overflow-y en -x worden uitgezet en van de class row de margin-right en -left worden uitgezet en margin: 0 16px van de getoonde selector wordt uitgezet dan toont alles correct.
<img width="2556" alt="Screenshot 2024-06-28 at 13 20 32" src="https://github.com/dso-toolkit/dso-toolkit/assets/4646174/047409c0-6382-4072-8090-ca9293a44d84">

<img width="2554" alt="Screenshot 2024-06-28 at 13 18 49" src="https://github.com/dso-toolkit/dso-toolkit/assets/4646174/0411e94e-4207-4920-b6ae-cd93c5b7428f">

**Comment by iterox** [comment]
Dit issue sluiten we.

**Comment by Hani-AS** [comment]
@iterox, we gebruiken de class "row" om ervoor te zorgen dat de document-page (voorheen het rechter-paneel) full-width wordt. De class row is een utility class vanuit de toolkit die de marges rechts en links toepast. Het issue wordt niet opgelost door deze class te verwijderen, want dan hebben we geen full-width meer.

**Comment by iterox** [comment]
Op 15 juli 2024 met Hani gezeten en de aanpassingen aan de Viewer Regels op de Kaart doorgenomen. Team Viewer Regels op de Kaart gaat dit oppakken.
