### ISSUE TITLE
Form Group Files: Remove parts if no files

### ISSUE THREAD

**Issue by iterox** [dso-toolkit/dso-toolkit#2627]
Het HTML/CSS component Form Group Files kent nog geen formele markup en styling instructies wanneer er (nog) geen bestanden geüpload zijn. Met dit issue willen we hier invulling aan gegeven.

Momenteel ziet het component er als volgt uit wanneer er (4) bestanden zijn geüpload:
<img width="1034" alt="Screenshot 2024-04-15 at 16 34 58" src="https://github.com/dso-toolkit/dso-toolkit/assets/4646174/b98c518c-e261-478d-83ef-dcda368a4143">
(Zie ook https://storybook.dso-toolkit.nl/master/?path=/story/html-css-form-groups-files--files)

Hoe willen we dat dit component er uit ziet wanneer er nog geen bestanden zijn geüpload?
Moet het er hetzelfde of anders uit zien als er eerder wel bestanden waren geüpload?

**Comment by MYpenburg** [comment]
Empty state: alleen groene knop tonen (geen titel, geen lijst)

**Comment by tfrijsewijk** [comment]
Maar wel eventueel de warning.

Is het een optie om de titel wel te laten staan? Ik denk dat dit het beeld rustiger maakt als er een file wordt toegevoegd. Daarnaast maakt het de markup voorschriften makkelijker en consistenter.

**Comment by hansgrimm** [comment]
> Maar wel eventueel de warning.
> 
> Is het een optie om de titel wel te laten staan? Ik denk dat dit het beeld rustiger maakt als er een file wordt toegevoegd. Daarnaast maakt het de markup voorschriften makkelijker en consistenter.

@tfrijsewijk @MYpenburg  De 'titel' is ook het label van het upload-veld. hij moet dus sowieso beschikbaar blijven voor screenreaders.

We kunnen dit volgens mij zonder markup voorschriften doen. ik heb hier eens mee zitten stoeien, en we kunnen de hele zwik dmv CSS verbergen zolang de lijst leeg is.
Ik weet niet of er ueberhaupt een melding kan zijn zolang er nog geen bestanden zijn.

**Comment by hansgrimm** [comment]
Samen met @MYpenburg gespect. Oplossing zoals nu getoond (lijst en titel boven weg bij geen bestanden) is zo akkoord.

**Comment by MYpenburg** [comment]
Ik ben volgende week vrij; 6 mei weer terug.

**Comment by iterox** [comment]
Opvolger van deze is #2650.
