### ISSUE TITLE
Accordeon Tabel Component

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#263]
In issue stond deze al licht beschreven / werd er gepeild wat de mogelijkheden zijn. Nu is de vraag dat deze daadwerkelijk gerealiseerd wordt. 

Het gaat om dit component. 

![marges 1](https://user-images.githubusercontent.com/36912722/51245839-1aa8e100-1989-11e9-9fbc-c213f0d63e9c.png)

Het is een table waar van de verschillende rows in de table functioneren als accordeon. 

Het uiterlijk en gedrag van de accordeon mag over worden genomen van de standaard accordeon. Maar in de naamgeving van classes is wel het verzoek om dit weg te houden van het standaard accordeon om verwarring te voorkomen. 

De specs 
![afbakening](https://user-images.githubusercontent.com/36912722/51246320-7d4eac80-198a-11e9-8564-f3fb2ddadd75.png)

Belangrijk is dat de uitlijning blijft kloppen zoals bij een table.

**Comment by PieterVerheij** [comment]
@MichielDHVD  Zijn dit niet twee issues? Eentje voor het in- en uitklapgedrag van een tabel-accordeon en eentje voor de stijling van de specifieke cellen in dit voorbeeld. Zo zorg je er ook voor dat het in- en uitklapgedrag van deze tabelvorm ook inzetbaar is los van welke inhoud een/of functionaliteit die erin zou komen. 
Wat betreft de uitklappende content: hoe zien jullie dat voor je? Is dat een losse table row die in ingeklapte toestand verborgen is? Dat lijkt mij wel de meest voordehand liggende oplossing...

**Comment by MichielDHVD** [comment]
Het opbreken van dit component in de tabel lijkt me slim. Dan kan het inderdaad hergebruikt gaan worden. 

Het verdwijnen in de DOM-structuur vraag ik ook even aan de developers.

**Comment by MichielDHVD** [comment]
Dit component wordt gesplitst in twee verschillende issues #266 gaat over de inhoud van een table row.  

Dit betekent dat als dit component klaar is de verwachting is dat deze er als volgt uit ziet.

**Comment by PieterVerheij** [comment]
@MichielDHVD Ik ga er vanuit dat de tabs boven de accordeon ook buiten de scope van dit ticket vallen. In de basis komt het hier op neer:
![image](https://user-images.githubusercontent.com/25430835/51547904-77b00580-1e67-11e9-983a-412dfd60360c.png)

**Comment by MichielDHVD** [comment]
Aha. Nee die hoeven inderdaad niet meegenomen worden. Die staan immers al in de toolkit. 

Prima!

**Comment by tfrijsewijk** [comment]
Wat zouden jullie ervan vinden als we de kolom indeling met de responsive bootstrap classes maken? En moet het een `table` element zijn of is dat een aanname?

**Comment by tfrijsewijk** [comment]
Als proef heb ik gekeken hoever we kunnen komen zonder een nieuw component/werkvorm:

![image](https://user-images.githubusercontent.com/9696261/53739325-c3f05b80-3e91-11e9-8077-31489faa19ef.png)

Dit is een "normale" `table.table`. Het vlak na "Boom 23 kappen" is een `td[colspan=7]`. Niet heel lastig. Ofwel, ik ben een heel eind zonder iets nieuws te maken.

Los van de witNu zijn er wel wezenlijke verschillen met het ontwerp:
* kleur van de active chevron (als ik `active` op de button zet wordt deze donkergroen - is oranje wel de juiste active state of zou juist oranje de active state _moeten zijn_?)
* de boldness en kleur van een openklapte rij
* Het grijze tintje van het aantal bijlagen

Verder vraag ik mij af
* Hoe actueel is het ontwerp van de tabel in de toolkit nog?
* Hoe dwingend is het ontwerp?

Alternatief is natuurlijk een `table.dso-accordeon` modifier. Dan is dit het haakje om de tabel (meer) te laten lijnen naar het ontwerp.

Ik ben op zoek naar een manier om meer bouwstenen te gebruiken en te voorkomen dat er een heel nieuw component wordt gemaakt. Een bestaand component verrijken met een modifier is een mooie middenweg

**Comment by MichielDHVD** [comment]
We zijn sowieso extensief bezig met het herontwerpen van de normale accordion om deze visueel te verbeteren. 

Deze zal dus nog meer los gaan lopen met deze. Wat dus de mogelijk open stelt om meer af te wijken van het oorspronkelijke ontwerp. Ik ga dit na lopen en ga wel meteen kijken hoe dit past in het scherm waar het oorspronkelijk terecht zou moeten komen.

**Comment by MichielDHVD** [comment]
Overleg gehad met UX en deze afwijking van het ontwerp is prima bevonden. 

Hoe kijk jij naar deze implementatie @TonD83 we lossen het op doormiddel van bestaande componenten en er komt geen custom css aan te pas.

**Comment by TonD83** [comment]
@MichielDHVD ik ben alleen maar voorstander van geen nieuwe componenten/werkvormen introduceren als het niet nodig is, dus goed initiatief van @tfrijsewijk. Thomas, zou jij misschien even de markup kunnen sturen/posten zodat ik die even kan bekijken? Ziet er veelbelovend uit, maar wil graag even zien wat je precies moest doen om tot deze schermafbeelding te komen.

**Comment by tfrijsewijk** [comment]
@TonD83: Je bent uit mijn aandacht ontsnapt, excuses. Hier de markup die bij bovenstaand screenshot hoort:

```html
<table class="table">
  <caption class="sr-only">{{ caption }}</caption>
  <thead>
    <tr>
      <th scope="col" width="1"></th>
      <th scope="col">Aanvraag/melding</th>
      <th scope="col">Status</th>
      <th scope="col">Ingediend</th>
      <th scope="col">Type</th>
      <th scope="col" width="50"></th>
      <th scope="col" width="250"></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">
        <button type="button" class="btn btn-link btn-xs">
          <span class="fa fa-chevron-up"></span>
        </button>
      </th>
      <td>Vergunning kappen</td>
      <td>Verzonden</td>
      <td>21/11/2017</td>
      <td>Aanvraag</td>
      <td class="text-center">2 <span class="fa fa-paperclip"></span></td>
      <td class="text-right">
        <button type="button" class="btn btn-link">
          <span class="fas fa-pencil-alt"></span>
        </button>
        <button type="button" class="btn btn-link">
          <span class="fas fa-redo-alt"></span>
        </button>
        <button type="button" class="btn btn-link">
          <span class="far fa-copy"></span>
        </button>
        <button type="button" class="btn btn-link">
          <span class="far fa-trash-alt"></span>
        </button>
      </td>
    </tr>
    <tr>
      <th scope="row">
        <button type="button" class="btn btn-link btn-xs active">
          <span class="fa fa-chevron-down"></span>
        </button>
      </th>
      <td>Boom 23 kappen</td>
      <td>Verzonden</td>
      <td>15/10/2017</td>
      <td>Verzoek</td>
      <td class="text-center">7 <span class="fa fa-paperclip"></span></td>
      <td class="text-right">
        <button type="button" class="btn btn-link">
          <span class="fas fa-pencil-alt"></span>
        </button>
        <button type="button" class="btn btn-link">
          <span class="fas fa-redo-alt"></span>
        </button>
        <button type="button" class="btn btn-link">
          <span class="far fa-copy"></span>
        </button>
        <button type="button" class="btn btn-link">
          <span class="far fa-trash-alt"></span>
        </button>
      </td>
    </tr>
    <tr>
      <td colspan="7" class="text-center" style="line-height: 300px;">
        Container cel
      </td>
    </tr>
    <tr>
      <th scope="row">
        <button type="button" class="btn btn-link btn-xs">
          <span class="fa fa-chevron-up"></span>
        </button>
      </th>
      <td>Pand 24 slopen</td>
      <td>Aangevuld</td>
      <td>13/09/2017</td>
      <td>Melding</td>
      <td class="text-center">6 <span class="fa fa-paperclip"></span></td>
      <td class="text-right">
        <button type="button" class="btn btn-link">
          <span class="far fa-copy"></span>
        </button>
        <button type="button" class="btn btn-link">
          <span class="far fa-trash-alt"></span>
        </button>
      </td>
    </tr>
    <tr>
      <th scope="row">
        <button type="button" class="btn btn-link btn-xs">
          <span class="fa fa-chevron-up"></span>
        </button>
      </th>
      <td>Kerkstraat 10 tuin uitgraven</td>
      <td>Ingetrokken</td>
      <td>11/07/2017</td>
      <td>Aanvraag</td>
      <td></td>
      <td class="text-right">
        <button type="button" class="btn btn-link">
          <span class="far fa-trash-alt"></span>
        </button>
      </td>
    </tr>
    <tr>
      <th scope="row">
        <button type="button" class="btn btn-link btn-xs">
          <span class="fa fa-chevron-up"></span>
        </button>
      </th>
      <td>Grote Markt 31 kabels leggen</td>
      <td>Concept</td>
      <td>28/06/2017</td>
      <td>Aanvraag</td>
      <td></td>
      <td class="text-right">
        <button type="button" class="btn btn-link">
          <span class="far fa-trash-alt"></span>
        </button>
      </td>
    </tr>
  </tbody>
</table>
```

**Comment by tfrijsewijk** [comment]
ping @TonD83 :)

**Comment by TonD83** [comment]
Dank voor de reminder. Ik wil dit graag even met @MichielDHVD doornemen maar die is vandaag niet aan het werk. Als morgen einde dag nog niks gehoord hebt, moet je me nog maar een keer pingen ;)

**Comment by TonD83** [comment]
@tfrijsewijk Ik kom er vandaag niet echt aan toe om uitgebreid te bespreken met @MichielDHVD vrees ik, wel gister even kort met @WidoBurg over gesproken. 

Als we deze kant op zouden gaan heeft dit nogal wat impact op het moeten refactoren van al onze huidige accordeons. Aangezien dit dan de tweede keer zou zijn dat we dit grondig overhoop moeten gooien zijn we daar niet zo happig op. Wat dat betreft neigen wij bij nader inzien toch naar dan toch twee aparte componenten. De accordeon blijft dan zoals die al is.

**Comment by MichielDHVD** [comment]
@TonD83  Denk dat we het slim is om sowieso morgen dit bespreken. Ik wil wel dat we dan een definitief duidelijk beeld hebben wat we gaan maken. 
Want het wordt tijd dat we er een streep onder trekken denk ik. Dat er in ieder geval een component komt.

**Comment by tfrijsewijk** [comment]
@TonD83: Dat kan ik mij voorstellen. Kun je eens een stuk markup delen wat jullie nu gebruiken? Wellicht is het fijner dat we het omdraaien en jullie markup opnemen. Hebben jullie nog styling gemaakt?

**Comment by TonD83** [comment]
@tfrijsewijk Ik ga morgen hier met Michiel en ik denk Wido nog even over verder babbelen. Dan kom ik er op terug.

**Comment by MichielDHVD** [comment]
We hebben het met elkaar besproken en zijn tot de conclusie gekomen dat we het ontwerp dat we willen kunnen realiseren met bestaande componenten. Dus er is geen behoefte meer aan een nieuw component. 

Wat ik wel nog wil gaan doen maar dat is een aandachtspunt voor mij. Is deze werkvorm of combinatie van elementen documenteren in de toolkit. Zodat indien nodig andere developers makkelijk gebruiken kunnen maken deze "combinatie" van componenten. 

Zodat als het component dat nu door 12 gerealiseerd wordt ook door andere teams snel kan worden overgenomen.
