### ISSUE TITLE
White boxes component

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#264]
Op de huidige homepage staan elementen die nog niet zijn verwerkt zijn in de toolkit. Deze zijn gebouwd door PR02 en moeten een plek krijgen in de toolkit. 

https://pre.omgevingswet.overheid.nl/home

Het gaat om de white boxes hieronder voeg ik de afbeelding van de specs waar de developers het op hebben gebaseerd. 

![image](https://user-images.githubusercontent.com/36912722/51247841-99544d00-198e-11e9-919d-674034dd39d4.png)

![image](https://user-images.githubusercontent.com/36912722/51247855-a3764b80-198e-11e9-9658-5e2775bc7e2d.png)

Maar in de toekomst wordt de homepage uitgebreid. En dan komt er een vorm met kleinere white boxes erbij. Deze zien er als volgt uit. 

![homepage - 2021](https://user-images.githubusercontent.com/36912722/51248113-69f21000-198f-11e9-848f-f1eab352ed71.png)

De specs voor de kleiner white boxes. 

![small white boxes](https://user-images.githubusercontent.com/36912722/51249168-bd199200-1992-11e9-857e-4e1c5239a185.png)

Nu heeft Samir de boxes voor de huidige homepage al zo ontworpen dat ze bij bepaalde scherm groottes kleiner worden. 

Misschien is het net als bij Django en het begrippencomponent mogelijk om de css om te bouwen en te gebruiken voor de toolkit.

**Comment by PieterVerheij** [comment]
Er lijkt iets mis te zijn met het bootstrap-grid? Wil je op small/mobiel de blokken niet onder elkaar?

**Comment by PieterVerheij** [comment]
Ik heb de classes `.whitebox, .function-title, .function-link, .function-icon, .desciption` een prefix "dso" gegeven: `.dso-whitebox, .dso-function-title, .dso-function-link, .dso-function-icon, .dso-desciption`

**Comment by PieterVerheij** [comment]
@MichielDHVD Ik neem aan dat de lijst en het blok met de groene achtergrond buiten de scope van dit issue vallen?

**Comment by MichielDHVD** [comment]
De met groene achtergrond moet ook komen. Ik dacht dat deze al in een werkvorm in de toolkit zat. 

Maar ik heb even met @tfrijsewijk gesproken vandaag. En hij stelde voor dat we dit issue op breken in de losse blokken. Zoals we net als bij de accordeon gaan splitsen willen we dat hier ook gaan doen. 
 
Dus de white boxes ( en ook groene box). Zijn dan componenten waar de content in geplaatst kan worden. 

De grootte van de white boxes zijn dus te bepalen met bootstrap in columns. 

Voor de inhoud maak ik dus een losse story. Thomas heb je een idee hoe dit samen te stellen? Want deze inhoud is namelijk betekenisloos zonder een white box.

**Comment by MichielDHVD** [comment]
> Er lijkt iets mis te zijn met het bootstrap-grid? Wil je op small/mobiel de blokken niet onder elkaar?

Het liefst wel. 

De reden dat het development team daar nu niet voor heeft gekozen is omdat we alleen voor tablet en groter ontwerpen. Mobile wordt in het begin niet ondersteund.

**Comment by tfrijsewijk** [comment]
Komt mee in de release van maandag 4 maart. Let op bovenstaand commentaar van Pieter: de markup is niet 1-op-1 overgenomen uit het aangedragen voorbeeld

**Comment by tfrijsewijk** [comment]
Uitgekomen in 5.1.0: https://www.dso-toolkit.nl/5.1.0/components/detail/examples.html

**Comment by MichielDHVD** [comment]
Bij de bomen kappen of struiken verwijderen voorbeeld staat er een underline onder de link. Terwijl voor die white box eigenlijk als geheeld geldt dat het als een button functioneert. 

Ik zie in de css ook als: a not button is dat de underline aan staat. Misschien is het handig om de white boxes als buttons neer te zetten. Op dit moment is enigste functie van de white boxes dat ze doorlinken naar andere pagina's.

De white boxes kunnen wel gevuld worden met tekst en afbeeldingen maar uiteindelijk linkt het door naar een andere pagina. Dus misschien kunnen we het wel hanteren dat white boxes alleen als buttons gebruikt mogen worden. Vanuit ux wil ik de white boxes ook alleen voor deze rol gebruiken. 

Verder moet de h2 's in white boxes een text-align: center krijgen. 

@tfrijsewijk moet deze issue gereopend worden of gaan we deze aanpassingen in een nieuw issue beschrijven?

**Comment by tfrijsewijk** [comment]
Deze is aan mijn ook ontsnapt. Dit is een bug en moet opgelost worden in een nieuw issue. Wil jij deze maken?

Een issue op Github kan maar aan 1 milestone worden gekoppeld.
