### ISSUE TITLE
Form Group: Errormessage error icon

### ISSUE THREAD

**Issue by MYpenburg** [dso-toolkit/dso-toolkit#2640]
Nu:
<img width="759" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/7289928/d8ea6cd5-439d-4231-bf90-1b31020af9b2">

Gewenst:
<img width="759" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/7289928/fcbf0180-7746-459f-a36a-f57148d2c224">

**Comment by hansgrimm** [comment]
![Scherm­afbeelding 2024-05-02 om 08 57 07](https://github.com/dso-toolkit/dso-toolkit/assets/506527/fd89e24f-6c5b-4220-88f6-e3a8ee069f2a)
^^ bewijs van goed gedrag :)
