### ISSUE TITLE
Form Group Files: Label-container wordt bij document upload niet getoond

### ISSUE THREAD

**Issue by WidoBurg** [dso-toolkit/dso-toolkit#2642]
Dso-label-container wordt bij een document upload niet getoond (en ook de info).
Op stap 5 is deze markup anders, daar gaat het goed. Op stap 7 dus wel deze markup. 

Op int12 in aanvragen na te spelen.

Toolkit versie 62.20.0. 

stap 7 niet correct
<img width="1594" alt="stap 7 - niet correct" src="https://github.com/dso-toolkit/dso-toolkit/assets/8705247/6c1cd15f-9e6f-4453-9cad-bde83e513a39">

stap 5 correct
<img width="1495" alt="stap 5 - correct" src="https://github.com/dso-toolkit/dso-toolkit/assets/8705247/10194275-ee53-4030-9c1a-cf0a2da9cd13">

huidige stap 7 (productie)
<img width="1654" alt="productie - stap 7" src="https://github.com/dso-toolkit/dso-toolkit/assets/8705247/159f67e0-10a2-4b0d-bb6f-16fe8baa7542">

**Comment by WidoBurg** [comment]
na upload staat hij er wel.

<img width="1581" alt="Screenshot 2024-04-26 at 11 37 40" src="https://github.com/dso-toolkit/dso-toolkit/assets/8705247/4d16c451-61ca-4337-b464-c768d8156de8">

**Comment by iterox** [comment]
Oorzaak: https://github.com/dso-toolkit/dso-toolkit/issues/2627. Wordt teruggedraaid en patch release 62.20.1 zal worden uitgebracht.
