### ISSUE TITLE
Icon: HTML/CSS icon "spinner" toont niet

### ISSUE THREAD

**Issue by iterox** [dso-toolkit/dso-toolkit#2644]
Voor #2616 moet er een HTML/CSS versie van het icon "spinner" getoond worden. Echter het blijkt dat de HTML/CSS versie van dit icon niet zichtbaar is. De Core versie toont wel.

```
<svg class="di di-spinner">
    <use href="dso-toolkit/dist/dso-icons.svg#spinner"></use>
</svg>
```
bovenstaande toont niets

Ihkv #2573 is de icon spinner afgesplitst uit het component progress-indicator.

**Comment by hansgrimm** [comment]
In Storybook wordt de spinner prima getoond (geanimeerd en wel):
![Image](https://github.com/dso-toolkit/dso-toolkit/assets/506527/f9415a78-9b15-44e4-bba5-72534f3f506c)

**Comment by tfrijsewijk** [comment]
Ik denk dat dit een issue met de spritesheet compiler is. Misschien dat we 'm maandag even kunnen behandelen

**Comment by tfrijsewijk** [comment]
Na lang wikken en wegen, dit gaan we niet doen. Voorkeur heeft het Web Component. Op termijn willen we het HTML/CSS component deprecaten.
