### ISSUE TITLE
Link color in Alerts en Highlight box naar tekstkleur

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#265]
In de alerts in de toolkit 

https://dso-toolkit.nl/3.1.0/components/preview/alert.html

Is de wens om ook links op te nemen. Maar dat zorgt voor problemen. Namelijk dat de huidige link kleur groen(#39870C) niet door de wcag contrast komt in combinatie met de links. 

Daarom moet er voor deze alerts een uitzonderingsregel komen. Dus zodra er een link in deze alerts of highlightbox komt. Moet deze automatisch een andere kleur meegeven. 

Welke kleur deze wordt moet eerst nog afgestemd worden. 

Als dit duidelijk is wordt deze verplaatst van to be specified naar to do

**Comment by MichielDHVD** [comment]
We gaan ervoor dat links en wat voor block met een andere background kleur dan wit. Een zwarte kleur krijgt met underline. De zwarte kleur is de standaard #191919

![meldingen links](https://user-images.githubusercontent.com/36912722/53564138-5cb36e00-3b56-11e9-82c8-8eeb16f7ba50.png)

**Comment by tfrijsewijk** [comment]
Uitgekomen in 5.1.0: https://www.dso-toolkit.nl/5.1.0/components/detail/alert.html

**Comment by MichielDHVD** [comment]
Gezien en verplaatst naar done.
