### ISSUE TITLE
Form Group Files: Remove parts if no files

### ISSUE THREAD

**Issue by iterox** [dso-toolkit/dso-toolkit#2650]
Het HTML/CSS component Form Group Files kent nog geen formele markup en styling instructies wanneer er (nog) geen bestanden geüpload zijn. Met dit issue willen we hier invulling aan gegeven.

Momenteel ziet het component er als volgt uit wanneer er (4) bestanden zijn geüpload:
![Screenshot 2024-04-30 at 10 04 03](https://github.com/dso-toolkit/dso-toolkit/assets/4646174/4ed0deaf-5e7f-4d70-8cd5-558c88c3a5f7)

(Zie ook https://storybook.dso-toolkit.nl/master/?path=/story/html-css-form-groups-files--files)

Hoe willen we dat dit component er uit ziet wanneer er nog geen bestanden zijn geüpload?
Moet het er hetzelfde of anders uit zien als er eerder wel bestanden waren geüpload?

In #2627 is deze change eerder opgeleverd geweest, echter met ongewenste side-effects: #2642, waardoor #2627 is teruggedraaid.

**Comment by hansgrimm** [comment]
@MYpenburg in de horizontale versie van het formulier staat het een beetje raar als er geen titel inb de linker kolom staat. zie screenshot:
![Scherm­afbeelding 2024-05-06 om 15 51 07](https://github.com/dso-toolkit/dso-toolkit/assets/506527/42768dcf-b433-4e97-b6c9-1d9e979794f8)
Wil je dit zo, of toch anders? en dan in de verticale weergave geen titel?

**Comment by hansgrimm** [comment]
<img width="1441" alt="Scherm­afbeelding 2024-05-07 om 10 44 53" src="https://github.com/dso-toolkit/dso-toolkit/assets/506527/3ed5c6cc-1185-4814-8782-2c706140fa11">

**Comment by tfrijsewijk** [comment]
> <img alt="Scherm­afbeelding 2024-05-07 om 10 44 53" width="1441" src="https://private-user-images.githubusercontent.com/506527/328453247-3ed5c6cc-1185-4814-8782-2c706140fa11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwOTQ3MzQsIm5iZiI6MTcxNTA5NDQzNCwicGF0aCI6Ii81MDY1MjcvMzI4NDUzMjQ3LTNlZDVjNmNjLTExODUtNDgxNC04NzgyLTJjNzA2MTQwZmExMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwN1QxNTA3MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZDFiNTY4OGY4ZjI1ZTU4NzRhZjBhNThmNjk5MTFkZmZmYzNkMjBjZDU0ZTFkYmJmZGJkMDA2NjU1MTk4ZmRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2PQ467bK5GPjgWV3WYaD6eIWr0gdH1BtmgjBzs_QLg4"> ^^ enige overgebleven ingreep: eventueel in de dom aanwezige lege lijst verbergen met `display: none;`. Is dit in de praktijk nodig, m.a.w. wordt die lege lijst ueberhaupt geplaatst/achtergelaten? Zo niet, dan zou deze hele aanpassing niet nodig zijn.

Ja, en daar zit ik ook precies mee: is het de verantwoordelijkheid van CSS om deze lijst te verstoppen, of is het de verantwoordelijkheid van de afnemer om bij geen items geen lijst te maken.

Ik neig naar het laatste.

Waarom tonen we eigenlijk geen melding, zoals "Er zijn (nog) geen bestanden toegevoegd" ?

**Comment by MYpenburg** [comment]
Eens met Thomas, gewoon lege lijst tonen zonder inhoud (en ook zonder opmerking). Ik had eerder al naar Hans geslackt: Hey Hans, even over 2650. Ik snap de titel [van het control] veel beter ineens. Ook waarom het voorbeeld wat vreemd oogt: "Files" resoneert niet lekker met "Document toevoegen". Zijn beide titels instelbaar in het control?
In dat geval mag van mij de titel nl. toch blijven staan. Dan is het aan de "auteur" om daar iets logisch van te maken.

**Comment by MYpenburg** [comment]
Misschien kan in het Storybook voorbeeld de lijst niet Files maarr Documenten worden genoemd; dat past beter bij de knop Document toevoegen.

**Comment by hansgrimm** [comment]
Een lege lijst die verder geen uiterlijke kenmerken heeft en geen plek inneemt kan geen kwaad, maar de screenreader zal 'm oplezen als "list with zero items" of woorden van gelijke strekking, en dat wil je niet. Weg dat ding.

**Comment by hansgrimm** [comment]
"files" is instelbaar, kan van alles wezen, zie hieronder. de default is kennelijk "files".
![Image](https://github.com/dso-toolkit/dso-toolkit/assets/506527/3a8fd039-f90e-4129-9c25-ef47a5dbbda5)
