### ISSUE TITLE
Advanced Select: Een optie van afwijkende kleur & icoon kunnen voorzien

### ISSUE THREAD

**Issue by Hendriksie** [dso-toolkit/dso-toolkit#2655]
We willen in het Advanced Select component opties (`AdvancedSelectOption`) weergeven die afwijken van de `variant` property in de groep (`AdvancedSelectGroup`). Door bijvoorbeeld de kleur aan te passen, en/of het bolletje te veranderen in een icoon willen we extra duiding geven aan bepaalde opties. Is het (bijvoorbeeld) een idee om `AdvancedSelectOption` uit te breiden met een `variant` property en/of een `icon` property? De `variant` van de `AdvancedSelectOption` zou dan voorrang hebben op de `variant` van `AdvancedSelectGroup` waar het in zit, en de `icon` zou een keuze kunnen zijn uit de Icon-library van de Toolkit.

Voorbeeld (paarse tekst + pijl):

![image](https://github.com/dso-toolkit/dso-toolkit/assets/6705457/e59be0f9-0e20-4887-8849-db5dc137b1ee)

**Comment by hansgrimm** [comment]
Aangezien deze (het paarse pijltje/paarse tekst) niet onder z'n eigen heading staat, is kennelijk de kleur en het pijltje op zichzelf essentieel om te weten wat hier aan de hand is. In tegenstelling tot de bolletjes is hier dus wel een flink aandachtspunt vwb toegankelijkheid, voor alle gebruikers (niet alleen blind). Over to you, @timveld :)

**Comment by tfrijsewijk** [comment]
Goed punt! cc: @elinemosterd98 @DjangoBlok

**Comment by DjangoBlok** [comment]
Net dit met @hansgrimm besproken.
De kleur en het icoon worden gebruikt om aan te geven dat het hier om een tijdelijk regelingdeel gaat.
In de archieflijst met versies wordt er bij tijdelijk regelingdelen het woordje "toegevoegd" of "verwijderd" aan de titel toegevoegd. Die toevoeging geeft aan wat er aan de hand is. De kleur en het icoon zouden dan als illustratief kunnen worden beschouwd.
![Scherm­afbeelding 2024-05-27 om 13 06 14](https://github.com/dso-toolkit/dso-toolkit/assets/34900082/eaa484d7-b622-4530-870f-bfac0fe7ed96)

Het voorstel is dat we in de viewer de titel ook verduidelijken zodat de kleur puur illustratief wordt.

**Comment by tfrijsewijk** [comment]
@elinemosterd98 @DjangoBlok Jullie aandacht voor dit issue graag

**Comment by elinemosterd98** [comment]
Laten we hier maandag even gezamenlijk naar kijken @tfrijsewijk @DjangoBlok @hansgrimm

**Comment by tfrijsewijk** [comment]
@emosterd98 Het is maandag. Schiet jij ons aan?

**Comment by tfrijsewijk** [comment]
Bevindingen nav. bespreking 24-6:

* Een toekomstig document kan een tijdelijk regelingsdeel in ontwerp krijgen. De groep conflicteert met de status.
* Het icoon en de paarse kleur hebben betekenis en ik vind het lastig om dat toegankelijk te maken.

@emosterd98 @DjangoBlok gaan terug naar de tekentafel ✏️

**Comment by DjangoBlok** [comment]
De mauve vermelding is vanuit designers verwijderd uit dit component.
