### ISSUE TITLE
Accordion: Badge toevoegen

### ISSUE THREAD

**Issue by mduijsens** [dso-toolkit/dso-toolkit#2657]
De wens is om een badge toe te voegen aan de accordion.

![Image](https://github.com/dso-toolkit/dso-toolkit/assets/144002683/a10bbfa7-aedd-4417-870c-a968be0b8f6d)

**Comment by tfrijsewijk** [comment]
@DjangoBlok @elinemosterd98 Graag jullie aandacht voor dit issue

**Comment by tfrijsewijk** [comment]
Dit issue pakken we nog op volgens de klassieke manier van werken: Maintainers gaan in overleg met UX dit issue uitwerken.

**Comment by iterox** [comment]
@DjangoBlok 

Zou jij willen beoordelen of dit zo naar wens is?

De control waar het hier om gaat is **badgeMessage**, die in onderstaande storybook story staat ingesteld op het woord **Onbepaald**.

**Core implementati (Web-component)**
https://storybook.dso-toolkit.nl/_2657-Accordion-Badge-toevoegen/?path=/story/core-accordion--alignment-sections

**HTML/CSS implementatie**
https://storybook.dso-toolkit.nl/_2657-Accordion-Badge-toevoegen/?path=/story/html-css-accordion--alignment-sections

Speciale aandacht voor de situatie dat op een smalle viewpoort er 2 of meer losse woorden in de badge staan, dan worden dis momenteel over 2 of meer regels geplaatst. Is dat ok?
