### ISSUE TITLE
Tooltip: Long words overflow box

### ISSUE THREAD

**Issue by Hendriksie** [dso-toolkit/dso-toolkit#2658]
De inhoud van de Tooltip kan soms buiten het element springen als het een heel lang woord heeft. Dit gebeurt alleen in Chrome.

Reproductie:

- Open [Aanwijzingsbesluit Natura 2000-gebied Canisvliet](https://document-viewer.dso.kadaster.nl/viewer/(documentresult//rechter-paneel:document/%2Fakn%2Fnl%2Fact%2Fmnre1153%2F2023%2FCanisvliet/bijlage)?id=%2Fakn%2Fnl%2Fact%2Fmnre1153%2F2023%2FCanisvliet) in Regels op de Kaart.
- Open "Bijlagen"-tab
- Klik op voetnoot 17 in de 2e bijlage ("Gebiedsbegrenzingen")

![image](https://github.com/dso-toolkit/dso-toolkit/assets/6705457/5f192699-0d58-4006-ba1e-bbe65367e6f1)

**Comment by mduijsens** [comment]
@tfrijsewijk Ik zie dat dit ook gebeurt op mobiele website. Voor repro steps:

1. Ga naar https://omgevingswet.overheid.nl/regels-op-de-kaart/viewer
2. Kies een random locatie
3. Je landt op de documentenlijst, daar zie je (i)tjes
4. Klik op 1 en de tooltip valt buiten beeld.
