### ISSUE TITLE
inhoud - Table accordeon

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#266]
In issue https://github.com/dso-toolkit/dso-toolkit/issues/263 

Wordt er table uitgewerkt waar de rows functioneren als accordeons. 
Soms zullen deze rows specifieke informatie nodig hebben. Dit component bespreekt de inhoud van zo'n row. 

![image](https://user-images.githubusercontent.com/36912722/51322446-c6bffa00-1a65-11e9-81d1-b490bb7cef2e.png)

Specs voor de inhoud

![image](https://user-images.githubusercontent.com/36912722/51322502-e525f580-1a65-11e9-9d9b-d0f09942cf9a.png)

**Comment by tfrijsewijk** [comment]
In overleg met Michiel gesloten, inhoud staat los van dit component
