### ISSUE TITLE
Autosuggest: Markeren van zoekresultaten onderdeel van API maken

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#2660]
# Aanleiding

Het Autosuggest component highlight de invoer in suggesties:

![image](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/1bdff36b-38b1-47f4-b433-7f77ced78b92)

Echter, de zoekresultaten die worden aangeleverd hoeven niet op dezelfde manier te zijn gefilterd. Bijvoorbeeld een backend met fuzzy searching:

* De gebruiker voert "Busum" in
* Er komt een zoekresultaat voor "Bussum"
* Het Autosuggest component kan met "Busum" geen "Bussum" highlighten.

# Oplossing

Het Autosuggest component een extra optie krijgen waarmee afnemers invloed kunnen uitoefenen op de markeerfunctionaliteit. Net zoals Ozon Content en Document Component.

```ts
interface Autosuggest {
  mark?: (text: string, type: "value" | "type" | "extra", extraIndex?: number) => AutosuggestMarkItem[];
}

type AutosuggestMarkItem = { mark: string } | string;
```

Autosuggest krijgt een optionele property `mark` voor een markeerfunctie. Als deze functie door de afnemer wordt meegegeven, roept het Autosuggest component deze functie voor elke suggestie de functie aan.

De afnemer krijgt de tekst (`value: string`) en de type (`type: string`) mee. Een type kan bv. de primaire suggestie zijn, of de type aanduiding, of een van de extra's.

![Image](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/3c842478-bf76-4fcf-a0ff-a906898ce180)

De markeerfunctie wordt per suggestie voor alle onderdelen aangeroepen. Label, het optionele type, en voor elke extra.

De afnemer kan aangeven welke tekst er gemarkeerd moet worden door die term in een object te zetten:

```ts
["Dit is ", { mark: "Groningen" }, " en dat ligt in ", { mark: "Ned" }, "erland"]
```

Wordt:

Dit is **Groningen** en dat ligt in **Ned**erland.

Markeren gaat natuurlijk met `<mark>`.

Als de optionele markeer functie niet is meegegeven wordt de huidige markeerfunctionaliteit toegepast. Daarmee is deze change non-breaking.

**Comment by hansgrimm** [comment]
Moet daarvoor een een lijst worden gemaakt met mogelijke typo's? Dat is monnikenwerk.
Google doet dit met "resultaten voor ......." met de juiste spelling, en toont een lijst met die spelling. De gebruiker kan dan alsnog voor de "foute" kiezen, maar dan wss geen resultaten, of veel minder.
![image](https://github.com/dso-toolkit/dso-toolkit/assets/506527/f93d8fa5-d957-4a04-9a81-d46b94c4ed50)

**Comment by tfrijsewijk** [comment]
De backend geeft alle informatie mee om de juiste zoekresultaten te tonen en welke onderdelen daarvan gemarkeerd moet worden.
