### ISSUE TITLE
Annotation: Nieuw component

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#2665]
# `<dso-annotation>`

Voor het presenteren van annotaties wordt er een nieuw component "Annotation" gemaakt.

<img width="373" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/9696261/6e07b548-e5c7-40ea-ae44-fff0d5fb563c">

Eén Annotation (instantie) toont één annotatie. In bovenstaand voorbeeld staan 2 annotaties, dus twee Annotation components (instanties). _Annotation toont géén lijst van annotaties._

# Todo

- [x] Modellering voor renvooiweergave
- [x] Nieuwste ontwerpen van Django (na 6 mei 2024) bijwerken.
- [x] Renvooisuggestie toevoegen

# Modellering

In dit hoofdstuk wordt de modellering tegen de ontwerpen uiteen gezet. We beginnen met ondersteunende models, waarna we de component models behandelen.

Na de component models staat pseudo HTML-markup.

De modellering en pseudo markup laat in het midden hoe renvooiweergave ("diff") wordt doorgegeven.

Zie het einde van dit issue voor wat vrije ideeen.

Domeinspecificieke termen in het Nederlands, de rest in het Engels. Namen van componenten zijn tot nu toe uitgezonderd geweest, die zijn altijd in het Engels.

### AnnotationWijzigactie

```ts
type AnnotationWijzigactie = "voegtoe" | "verwijder";
```

Mogelijke wijzigacties op de annotatie zelf. Een wijzigactie kan worden toegevoegd of verwijderd.

### ActiveChangeEvent

```ts
interface AnnotationActiveChangeEvent {
  /**
   * De huidige status van de annotatie.
   */
  current: boolean;

  /**
   * De gewenste status van de annotatie.
   */
  next: boolean;
}
```

### Renvooi models

```ts
type AnnotationDiff = { toegevoegd: string } | { was: string, wordt: string } | { verwijderd: string };
```

De termen `toegevoegd`, `was`, `wordt`, `verwijderd` worden mogelijk nog gewijzigd.

Een Annotation heeft een actief/passief zijn. De gebruiker kan de Slide Toggle activeren om de wisselen tussen deze twee statussen. De afnemer kan aan deze status gedrag koppelen.

Het model `AnnotationActiveChangeEvent` wordt ge-emit zodra de gebruiker de Slide Toggle activeert.

## Component models

Component models zijn het contract tussen de functionele en visuele ontwerp en de technische implementatie.

### Annotation

Dit is een basis model. Deze eigenschappen gelden voor alle 4 de varianten.

<img width="617" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/9696261/5b08d231-8a39-4e81-8938-435112a8b543">

```ts
/**
 * Basis model voor de verschillende annotaties.
 */
interface Annotation {
  /**
   * Een URL naar de verbeelding van de legenda.
   */
  legenda: string;

  /**
   * Een optionele wijzigactie die aangeeft of de annotatie toegevoegd of verwijderd is.
   */
  wijzigactie?: AnnotationWijzigActie;

  /**
   * Een optionele boolean die aangeeft of de annotatie actief is.
   */
  active?: boolean;

  /**
   * Een optionele boolean die aangeeft of de locatie van de annotatie gewijzigd is.
   */
  gewijzigdeLocatie?: boolean;

  /**
   * Een optionele event listener voor wijzigingen aan de status van de annotatie.
   */
  dsoActiveChange?(event: AnnotationActiveChangeEvent): void;
}
```

---

### Activiteit

![image](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/087d6a7a-30bb-4de9-a602-08a06fe1e201)

```ts
interface AnnotationActiviteit extends Annotation {
  type: "activiteit";

  /**
   * De naam van de activiteit.
   */
  naam: AnnotationDiff | string;

  /**
   * De activiteit regel kwalificatie.
   */
  regelKwalificatie: AnnotationDiff | string;

  /**
   * De noemer van de locatie.
   */
  locatieNoemers: Array<AnnotationDiff | string>;

  /**
   * Voorzetsel van de regelKwalificatie. Exclusief dubbele punt.
   */
  regelKwalificatieVoorzetsel?: string;
}
```

```html
<dso-annotation
  legenda="kaartje.png"
  wijzigactie="voegtoe|verwijderd"
  (dsoActiveChange)="toonOpKaart($event)"
  gewijzigde-locatie="true"
  
  type="activiteit"
  naam="Toegevoegde activiteit"
  regel-kwalificatie="toegestaan"
  [locatieNoemers]="['industriezone']"
  regel-kwalificatie-voorzetsel="in"
></dso-annotation>
```

---

### Gebiedsaanwijzing

![image](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/303fb640-5e8c-42aa-b87a-da278c0f5b12)

```ts
interface AnnotationGebiedsaanwijzing extends Annotation {
  type: "gebiedsaanwijzing";

  /**
   * De naam van de gebiedsaanwijzing.
   */
  naam: AnnotationDiff | string;
}
```

```html
<dso-annotation
  legenda="kaartje.png"
  wijzigactie="voegtoe|verwijderd"
  (dsoActiveChange)="toonOpKaart($event)"
  gewijzigde-locatie="true|false"

  type="gebiedsaanwijzing"
  naam="Dit is de naam"
></dso-annotation>
```

---

### Omgevingsnorm

![image](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/9abd33a4-acae-48f5-9d0a-37bd9ddd7eb9)

```ts
interface AnnotationOmgevingsnorm extends Annotation {
  type: "omgevingsnorm";

  /**
   * De naam van de omgevingsnorm
   */
  naam: AnnotationDiff | string;

  /**
   * De waardes van de omgevingsnorm.
   */
  waardes: Array<AnnotationDiff | string>;

  /**
   * De eenheid van de omgevingsnorm.
   */
  eenheid: AnnotationDiff | string;
}
```

```html
<dso-annotation
  legenda="kaartje.png"
  wijzigactie="voegtoe|verwijderd"
  (dsoActiveChange)="toonOpKaart($event)"
  gewijzigde-locatie="true|false"

  type="omgevingsnorm"
  naam="Dit is de naam"
  [waardes]="['1', '2']"
  eenheid="meter"
></dso-annotation>
```

---

### Werkingsgebied

![image](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/3873fad7-fa8c-4f4c-a2c9-0ffcf0ddd5af)

```ts
interface AnnotationWerkingsgebied extends Annotation {
  type: "werkingsgebied";

  /**
   * De noemer van de locatie.
   */
  locatieNoemer: Array<AnnotationDiff | string>;
}
```

```html
<dso-annotation
  legenda="kaartje.png"
  wijzigactie="voegtoe|verwijderd"
  (dsoActiveChange)="toonOpKaart($event)"
  gewijzigde-locatie="true|false"

  type="werkingsgebied"
  [locatieNoemer]="['1', '2']"
></dso-annotation>
```

## Renvooiweergave data ("diff")

Renvooiweergave toont de verschillen tussen de oude en de nieuwe versie en kent twee verschillende presentaties: inhoudelijk/tekstueel en structureel.

![image](https://github.com/dso-toolkit/dso-toolkit/assets/9696261/0618b02d-3d46-47b3-a626-6272d842720f)

**Comment by Hendriksie** [comment]
@tfrijsewijk Optie 2 zou je wellicht minder verbose kunnen maken door, net als bij [Document Component](https://storybook.dso-toolkit.nl/62.21.0/?path=/docs/core-document-component--docs#properties) een `XMLDocument` als input mee te geven. Maar dat neemt niet weg dat de renvooi data alsnog door iemand moet worden opgesteld.

**Comment by MichielKadaster** [comment]
@tfrijsewijk hoe werkt het eigenlijk met de het `type` attribuut? Stel wij zetten die op `omgevingsnorm` worden dan `eenheid` en `waardes` verplicht vanuit de interface?

Dat zou wel het mooist zijn want dan zijn de checks 'strict' en kunnen we niet per ongeluk attributen vergeten voor een bepaald type

**Comment by tfrijsewijk** [comment]
> @tfrijsewijk hoe werkt het eigenlijk met de het `type` attribuut? Stel wij zetten die op `omgevingsnorm` worden dan `eenheid` en `waardes` verplicht vanuit de interface?
> 
> Dat zou wel het mooist zijn want dan zijn de checks 'strict' en kunnen we niet per ongeluk attributen vergeten voor een bepaald type

Ik vroeg mij al af wanneer ik die vraag zou krijgen, en het verbaast mij niets dat jij 'm stelt 😁

Maar je hebt gelijk, dat zou het mooiste zijn. Maar ik moet je teleurstellen, dat gaat mij niet lukken.

Het alternatief is een lijst aan Web Componenten:
* `<dso-annotation-omgevingsnorm>`
* `<dso-annotation-activiteit>`
* `<dso-annotation-gebiedsaanwijzing>`
* `<dso-annotation-werkingsgebied>`

Waar ik nog naar kan kijken is een soort `config` attribuut, maar dat zit het (efficiente) change mechanisme detectie van Stencil in de weg.

**Comment by MichielKadaster** [comment]
Dat lijkt me op zich geen slecht idee en dwingt ons om altijd het juiste component te gebruiken.

Had je mijn andere opmerkingen ook nog gezien over de naamgeving?

**Comment by tfrijsewijk** [comment]
Ja, excuus! Die zal ik nog verwerken in de scope.
