### ISSUE TITLE
Component: Card with href aanpassingen

### ISSUE THREAD

**Issue by mduijsens** [dso-toolkit/dso-toolkit#2666]
We willen de interface voor de documentenlijst verbeteren.

### Introductie

We hebben nu in de viewer de documenten lijst. Hier zie je het ook vanuit toolkit: https://storybook.dso-toolkit.nl/62.20.1/?path=/story/core-card--href-with-label 
Dat ziet er in de huidige applicatie als volgt uit:
![Image](https://github.com/dso-toolkit/dso-toolkit/assets/144002683/e6df63a7-aeae-4ae0-a1cc-7183c687c207)

Hiervoor willen we graag een nieuwe interface om de leesbaarheid te vergroten:
<img width="387" alt="Screenshot 2024-05-14 at 11 54 14" src="https://github.com/dso-toolkit/dso-toolkit/assets/144002683/c5f3fc8b-d2ed-48cf-9ba2-b2e840525c2b">

### Verbeteringen
Geen veranderingen aan spacings etc alleen maar verplaatsen van inhoud.
1. Het informatieballonnetje bevat alleen maar inhoud over type document, dus die wil ik achter de indicatie type document hebben.
2. Het resultaat dat je hier krijgt zijn documenten, daarom voor de interpretatie (zeker van first-time users) wil ik er een icoon voorzetten. Tevens helpt ook met de scanbaarheid van waar een nieuw item begint en eindigt.
3. De ontwerplabels verschuiven nu de hele content, dit zorgt voor een onrustiger en moeilijker te scannen beeld. Ik zou willen opteren voor ontwerplabel altijd rechts uitlijnen, zo schuift het nooit de content op. Ik heb ook de compact versie gebruikt ipv. normal (bestaat al in toolkit), zodat het iets minder hoogte inneemt.
4. Hetzelfde geldt voor de > waar men op zou moeten kunnen klikken. De hele rij is klikbaar, niet alleen de titel, daarom zou ik willen opteren voor de > helemaal rechts uitlijnen. Dit doet wat met de rust van de interface en dus ook hoe snel een gebruiker de interface tot zich kan nemen.

Sizing
![image](https://github.com/dso-toolkit/dso-toolkit/assets/144002683/8845d7f7-44fd-4f75-9409-68e5001d655c)

**Comment by tfrijsewijk** [comment]
@emosterd98 was jij hier ook niet mee bezig? Is dit issue nog actueel/relevant?

**Comment by emosterd98** [comment]
@tfrijsewijk Hier ben ik niet mee bezig maar lijkt mij zeker relevant.

**Comment by tfrijsewijk** [comment]
Dit issue wordt opgelost met #2797.

**Comment by tfrijsewijk** [comment]
Dit issue is opgelost met #2797.
