### ISSUE TITLE
Mobiel gebruik in de viewer

### ISSUE THREAD

**Issue by mduijsens** [dso-toolkit/dso-toolkit#2669]
Het is me nog niet duidelijk of dit toolkit issues zijn.

1. Gebruikers hebben gemeld niet te kunnen scrollen in de regels van de viewer (bij een open document). Alsof hij 'blijft hangen'. Dit heb ik ook soms gezien bij de documentenlijst.
2. Tooltips vallen soms buiten beeld 
![Image](https://github.com/dso-toolkit/dso-toolkit/assets/144002683/58cecb78-cbc3-40f9-a0e9-32df407aca7f)
3. Open zetten van 'Datum uit het verleden' bij zoeken zorgt ervoor dat ik niet meer kan scrollen en dus niet kan zoeken. Dit gebeurt ook bij coordinaten, kan maar de helft van de content zien.
4. De datum selector houdt me niet meer tegen om een te oude datum te kiezen (ik krijg wel nog een foutmelding dus niet mega urgent)

**Comment by MichielDHVD** [comment]
@hansgrimm  @MichielDHVD  gaan Donderdag 30 Mei doornemen om te kijken naar het Header probleem.

**Comment by hansgrimm** [comment]
Probleem bij scrollen zoekvenster zit in `.dso-main-panel .content`, dus in de toolkit. Bij een viewport van < 880px gaat de `overflow: auto` eraf. Waarom? een raadsel.

![Scherm­afbeelding 2024-05-30 om 13 02 03](https://github.com/dso-toolkit/dso-toolkit/assets/506527/2e5eb10f-ca12-4c7d-a39a-26e69dbb936e)

![Scherm­afbeelding 2024-05-30 om 13 02 24](https://github.com/dso-toolkit/dso-toolkit/assets/506527/899ea9a3-976c-484d-849b-691baffc9540)

**Comment by hansgrimm** [comment]
@mduijsens @elinemosterd98 De issue met het scrollen in de regels bij open document, en de buiten beeld vallende tooltip kan ik op mijn foon (en de virtualisatie in Chrome) niet reproduceren.

**Comment by hansgrimm** [comment]
k heb wat! Na een wilde tocht met `overflow: auto` door de verschillende containers (wat niks deed..) kwam ik bij de `iframe` terecht. Deze heeft een attribuut `scrolling="no"` , en als je die eraf butst is het ingezoomde scrollprobleem weg.
![Scherm­afbeelding 2024-06-10 om 10 06 13](https://github.com/dso-toolkit/dso-toolkit/assets/506527/47f4ff75-c26a-4bbc-b0ed-b250413a4abb)

**Comment by hansgrimm** [comment]
@MichielDHVD checkt de iframe issue bij PR02

**Comment by DjangoBlok** [comment]
We moeten wel even controleren of dat geen negatieve 'bijwerkingen' heeft. Of doe je dat alleen in een kleine viewport?

**Comment by tfrijsewijk** [comment]
@MichielDHVD Heb jij nog met PR02 overlegd?

**Comment by MichielDHVD** [comment]
Team lijkt aan te geven dat die no scroll een default waarde is die automatisch wordt geplaatst wanneer je niks anders doet. 

Maar een groot punt is. 

Een kan het niet kunnen scrollen niet reproduceren. Welke specifieke stappen of browsers treed dit probleem op?

**Comment by tfrijsewijk** [comment]
Ik weet niet precies hoe dit wordt gereproduceerd, maar ik denk dat het een iframe aangelegenheid is. Het `scrolling="no"` attribuut is te rechtvaardigen omdat het iframe de volledige hoogte van de content wordt. Het lijkt erop dat de hoogte van de viewer wijzigt waarna het iframe ook moet worden aangepast, maar dit niet wordt gedaan.

@DjangoBlok Hoe dan ook, dit is geen toolkit aangelegenheid. We ondersteunen natuurlijk graag, maar de voortgang hoeft niet op dit bord te worden bijgehouden. Ik sluit dit issue, maar voel je vrij ons bij de discussie te betrekken.
