### ISSUE TITLE
Logo: waar hoor ik thuis?

### ISSUE THREAD

**Issue by iterox** [dso-toolkit/dso-toolkit#2678]
Op de dso-toolkit website worden alle componenten onder een categorie getoond. Met 1 uitzondering: het `Logo` component.

<img width="848" alt="Screenshot 2024-05-23 at 16 42 52" src="https://github.com/dso-toolkit/dso-toolkit/assets/4646174/33eeb4d7-8dc2-439a-a811-fc0f0ebc6c4f">

Vragen aan UX:
Is deze uitzondering doelbewust?
Behoort Logo onder 1 van de categorieën?
Zo ja, welke?

**Comment by DjangoBlok** [comment]
Ik vind die thuishoren bij DSO Identiteit
