### ISSUE TITLE
Tabs in lijn brengen met bootstrap markup

### ISSUE THREAD

**Issue by TonD83** [dso-toolkit/dso-toolkit#268]
Het tabs component is nu niet conform bootstrap markup en classes.
Dso kent dso-tabs met een dso-tabcount-x mechanisme. In bootstrap wordt gebruik gemaakt van nav en nav-tabs.

Graag in lijn brengen zodat gewerkt kan worden met standaard implementaties (in ons geval React Bootstrap).

DSO Tabs:
<img width="1318" alt="screenshot 2019-01-21 at 10 00 21" src="https://user-images.githubusercontent.com/18580063/51463495-99c05f80-1d63-11e9-9a8b-fffccfb058c8.png">

Bootstrap 3 tabs:
<img width="597" alt="screenshot 2019-01-21 at 10 01 17" src="https://user-images.githubusercontent.com/18580063/51463513-a644b800-1d63-11e9-8394-1ba9115e99a8.png">

**Comment by PieterVerheij** [comment]
Het ontwerp vraagt om uitgevulde (justified) tabs. Ik heb daarvoor display: flex gebruikt, wat ook de manier is in Bootstrap 4.

**Comment by tfrijsewijk** [comment]
Voor zover ik weet moet de toolkit nog steeds aan IE9 vasthouden. Dit is destijds door Michael besloten. Ook nadat er is aangegeven dat de applicaties die gebruik maken van de toolkit _geen_ IE9 hoeven ondersteunen is hier aan vastgehouden.

Dus tenzij @MichielDHVD nog wat voor ons kan betekenen, kunnen we geen `display: flex` gebruiken

**Comment by TonD83** [comment]
Pardon, IE9? We (gebruikerstoepassingen) ondersteunen IE10 niet eens! Uitgangspunt vanuit architectuur is alle grote browsers (Chrome, Safari, IE/Edge, Firefox) de laatste twee versies.

**Comment by tfrijsewijk** [comment]
Mag ik bij jullie komen werken? :-)

**Comment by TonD83** [comment]
Van mij wel! Ik ga er alleen helaas niet over...

**Comment by MichielDHVD** [comment]
Wat er volgens mij aan de hand is is er dat er een tijd terug een beslissing is genomen met betrekking tot de toolkit. 

Ik tag even @DHvD-Michael en app hem ook meteen. Want ik heb geen inzicht waarom en wanneer deze beslissing is gemaakt.

**Comment by DHvD-Michael** [comment]
IE9 mag gelukkig los worden gelaten. IE11 is de oudste versie dat momenteel vanuit architectuur nog ondersteund dient te worden. 

Deze beslissing had ik destijds in 2016 genomen omdat:
- IE9 was end-of-life per januari 2016. Echter, overheden kunnen dan nog steeds verouderde browsers zoals IE9 binnen hun organisaties gebruiken. Ik heb zodoende rekening gehouden met het scenario dat bepaalde overheden de wens kunnen hebben om ook voor hun browser een ondersteunde versie van het DSO te krijgen. De tijdlijn van het programma was destijds anders; dit is onderhand bijgesteld naar 2021.
-  Vanuit het programma of architectuur waren op dat moment geen kaders bepaald. 
- Bootstrap v3.3.7 was de meest stabiele versie. Bootstrap v4 was in alpha stadium. 
- Uitgangspunt: kies voor robuuste software boven bleeding edge software. Zodoende is v.3.3.7 als basis genomen. 
- IE9 ligt goed binnen de capabilities van v3.3.7
- Uitgangspunt: houdt zo goed mogelijk v3.3.7 aan totdat er kaders bepaald zijn.

Afgelopen jaren had ik wel gecommuniceerd dat vanuit de ontwikkelteams alleen vrij recente browsers ondersteund worden (zie ook comment Ton hierboven). Destijds was vanuit architectuur dit nog niet definitief vastgesteld. 

Voor de compleetheid: bijgaand een afbeelding met de ondersteunde browsers zoals geformuleerd in het Project Start Architectuur voor Checken en Opstellen.
<img width="573" alt="ondersteunde browsers" src="https://user-images.githubusercontent.com/4227175/52198321-b8921c00-2862-11e9-90a4-ef8e27f5b1e3.png">

**Comment by tfrijsewijk** [comment]
Uitgekomen in v5.0.0: https://www.dso-toolkit.nl/5.0.0/components/detail/tabs.html

**Comment by MichielDHVD** [comment]
Gecontrollerd of het overeenkomt met Bootstrap 3.3.7.  Dat klopt. 

Deze wordt verplaats naar Done.
