### ISSUE TITLE
Build: Artifact integrity

### ISSUE THREAD

**Issue by yktoo** [dso-toolkit/dso-toolkit#2688]
We willen graag het `integrity`-attribuut meegeven met de `<link>`-tag die naar de toolkit files verwijst. Waar kunnen we de hashes (bijv. `sha384`) vandaan downloaden voor een bepaalde versie van de toolkit?

**Comment by hansgrimm** [comment]
@MichielDHVD liet mij weten dat hier enige druk op staat

**Comment by tfrijsewijk** [comment]
# Aanleiding

Afnemers van de DSO Toolkit willen de assets met een integrity check inladen. Dit gaat om `<script>` en `<link>` assets, met het `integrity` attribuut.

Een hash wordt gegenereerd aan de hand van de content. Dit is met name voor de CDN interessant. Met een integrity check voorkom je MITM attacks. De browser genereert ook hashes en vergelijkt deze met de hash in het `integrity` attribuut. Pas als deze attributen overeenkomen wordt de styling of scripting toegepast.

# Werkzaamheden

Alle packages gaan we verrijken met een file waar voor alle files de hash instaat.

Voorbeeld:

```jsonc
// hashes.json
[
  {
    "file": "package.json",
    "hash386": "abcefg...."
  },
  {
    "file": "dist/readme.md",
    "sha386": "abcefg...."
  }
]
```

## Packages

Alle packages die we publiceren naar NPM:

* `dso-toolkit`
* `@dso-toolkit/core`
* `@dso-toolkit/angular`
* `@dso-toolkit/react`

## `hashes.json` locatie

Deze file bevindt zich in de root van elke package. Hierdoor wordt deze file ook gepubliceerd naar de CDN, en is daarmee machine-verwerkbaar.

## Oplossingsrichting

Met `yarn pack --dry-run --json` worden alle files in een NDJSON stream geoutput. Deze informatie kan als basis dienen voor `hashes.json`.

Let op dat in een Yarn monorepo dit commando per workspace moet worden uitgevoerd: `yarn workspace dso-toolkit pack --dry-run --json`. Of: de CWD moet al een workspace zijn.

Deze stream zou opgevangen kunnen worden in een Node proces. Hiermee kunnen we in een taal schrijven die ons bekend is (JavaScript/TypeScript). Bijvoorbeeld met een TypeScript file in `scripts/create-hashes/main.ts` die de STDIN stream verwerkt en mapt tot JSON, wat met de "redirect to file" operator (`>`) wordt opgeslagen.

```
yarn workspace dso-toolkit pack --dry-run --json | tsx scripts/create-hashes/main --package dso-toolkit > packages/dso-toolkit/hashes.json
```

## Koppelvlak

Gedocumenteerd koppelvlak (API) van DSO Toolkit uitbreiden met `hashes.json`. Zie dso-toolkit.nl documentatie.

**Comment by iterox** [comment]
Commando is geworden: yarn workspace dso-toolkit pack --dry-run --json | tsx scripts/create-hashes/main > packages/dso-toolkit/hashes.json

**Comment by yktoo** [comment]
@tfrijsewijk Heb je een voorbeeld URL voor zo'n `hashes.json`?

**Comment by iterox** [comment]
@yktoo Excuus voor de (ver)late reactie.

Dit zijn de url's:

https://cdn.dso-toolkit.nl/@dso-toolkit/core/master/hashes.json
https://cdn.dso-toolkit.nl/dso-toolkit/master/hashes.json

**Comment by tfrijsewijk** [comment]
En vanaf de eerstvolgende release (63.0.0) kan op de plek van `master` ook het versienummer worden ingevuld.
