### ISSUE TITLE
Verkleinen fontsize badges. 

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#269]
Toen de badges en labels gelijktijdig werden ontworpen was de minimale fontsize gezet op 16px vanuit het 8px grid. 

We lopen nu tegen het probleem aan dat deze grootte van labels te fors is als we de labels willen gebruiken achter links als een nummer indicator. 

Zoals hier getoond bij links in de toolkit. 
https://dso-toolkit.nl/3.1.0/components/detail/anchor.html

Toen we de tooltip aan het ontwikkelen kwamen we ook al tegen het probleem van de 16px. Toen is besloten om toch een versie van de kleine tekst te gebruiken. 14px is geintroduceerd als optie voor kleine tekst. 

Als we kijken naar een oude versie van de badge in eerdere release. Geeft bootstrap als standaard 14px mee. Dit is dan ook de font grootte die we nu willen aanhouden. 

14px regular (in de oude bootstrap versie is deze namelijk wel bold, maar onze labels en badges zijn beide niet bold) 

<img width="167" alt="screen shot 2019-01-21 at 11 16 33" src="https://user-images.githubusercontent.com/36912722/51468150-88c91b80-1d6e-11e9-8e19-f2f924f16fcb.png">

~~Verder moet er ook een modifier komen op de badge iets hoger langs een element te kunnen plaatsen zoals getoond word in de afbeelding hieronder. Deze mag 4px hoger staan dan de lijn waar de tekst op staat. Maar dit mogelijk te specifiek en moet mogelijk op het oog gedaan worden.~~

![image](https://user-images.githubusercontent.com/36912722/51468273-d5145b80-1d6e-11e9-855f-5d6231e25fbf.png)

**Comment by MichielDHVD** [comment]
De tekst van de badge mag verkleind worden naar 14 px normal. De modifier gaan we niet toepassen we gaan deze er direct achter zetten.

**Comment by tfrijsewijk** [comment]
Opgeleverd in 7.0.0: https://www.dso-toolkit.nl/7.0.0/components/detail/badge.html

Overigens, zie de pixel diff in Percy: https://percy.io/dso-toolkit/dso-toolkit/builds/1704037 Gaaf he?

**Comment by MichielDHVD** [comment]
Mooi! Verplaatst naar done
