### ISSUE TITLE
Alert: variant `compact`

### ISSUE THREAD

**Issue by emosterd98** [dso-toolkit/dso-toolkit#2690]
Het alert-component is opgedeeld in 4 varianten: success, info, warning en error. We hebben dit component uitgebreid met een compacte versie van alle soorten, deze heten "small alerts". Deze kun je gebruiken als kanttekening, om de gebruiker van informatie te voorzien die onderbouwend fungeert/ naast een ander soort feedback of bijvoorbeeld mindere urgentie heeft dan de default alerts. 

**Welke varianten omvat dit component nu?**

Alert - success
Alert - info
Alert - warning
Alert - error
-----------------
Compact alert - success
Compact alert - info
Compact alert - warning
Compact alert - error

![Alerts](https://github.com/dso-toolkit/dso-toolkit/assets/170416199/87108b8e-c309-443f-8b46-265b999decbd)
![Small alerts](https://github.com/dso-toolkit/dso-toolkit/assets/170416199/c8f75f56-2a7d-46e8-94be-9cb7cba0a6e8)

**Comment by tfrijsewijk** [comment]
Is dit issue al akkoord bevonden door UX? Qua specs is het een duidelijk verhaal en zouden we dit kunnen oppakken.

cc @MichielDHVD @MYpenburg

**Comment by MichielDHVD** [comment]
Ik heb dit niet eerder gezien maar heb geen bezwaar.
