### ISSUE TITLE
Annotation Component: Doorontwikkeling

### ISSUE THREAD

**Issue by Hendriksie** [dso-toolkit/dso-toolkit#2691]
## Verwijder / Verwijderd ✅
In de documentatie staat `export type AnnotationWijzigactie = "voegtoe" | "verwijderd";`, maar in Storybook staat dat het `voegtoe` of `verwijder` kan zijn. Welke is het?

## Eenheid optioneel maken voor Omgevingswaarde en Omgevingsnorm ✅
Omdat omgevingsnormen en omgevingswaarden de zelfde properties heeft gebruiken we het `dso-annotation-omgevingsnorm` om ook de omgevingswaarden te tonen. Echter is bij omgevingswaarden de `eenheid` optioneel.

Dit zorgt er voor dat er achter de `naam` een lege `eenheid` getoond wordt: `(in )`. De eenheid is optioneel omdat het `waarde staat in regeltekst` als `waarde` hebben.

* Als de eenheid niet wordt meegegeven, toon dan geen `(in: x)`.
* De tekst "Waardes worden weergegeven op de kaart" wordt onderdeel van de API waardoor de afnemer kan bepalen welke tekst er staat.

ℹ️ Omgevingsnormen kunnen ook `Waarde staat in regeltekst` als waarde hebben, maar wij zijn nog zoekende naar een voorbeeld document waarin dit voorkomt. Aanname is dat dit mogelijk is.

![image](https://github.com/dso-toolkit/dso-toolkit/assets/6705457/a2415570-f5a7-488a-a713-b81f537364db)

## Kleiner font bij "subregels" in Annotation ✅
Dit is wel in het ontwerp, maar niet in de implementatie gedaan. Was ooit mauve, nu niet meer.

Dus nog kleiner font implementeren.

## Annotation variant "Omgevingsnorm" hernoemen naar "Omgevingsnorm/waarde" ✅
Voor Omgevingsnorm en Omgevingswaarde gelden dezelfde presentatie eisen. Component herbruiken.

## Annotation variant "Werkingsgebied" hernoemen naar "Locatie" ✅
Werkingsgebied blijkt achteraf niet de juiste naam voor deze variant.

## Style wijziging wanneer symbool niet bestaat ✅
Is het mogelijk om de wit ruimte die links van de titel onstaat als er geen symbool bestaat weg te halen?
![image](https://github.com/dso-toolkit/dso-toolkit/assets/6705457/aa7d595a-98d1-4074-ad3f-1f9a889551a5)

## Renvooi als los component aanbieden ✅
De functionaliteit achter `const AnnotationDiffRenderer: FunctionalComponent<AnnotationDiffRendererProps>` als los Web Component aanbieden.

* Compleet vertalen naar Web Component?
* Web Component die doorzet naar hetzelfde functional component?

## Annotation variant "Kaart" ✅
* Een nieuwe variant van het type annotation ("kaart")
* Deze variant bestaat uit een icoon en een link. 

Zie onderstaand voorbeeld.

![Kenmerken en kaart - Kaarten en hoofdlijnen](https://github.com/dso-toolkit/dso-toolkit/assets/34900082/ff96b1a3-cd01-4314-8658-9d06a5782e22)

**Comment by tfrijsewijk** [comment]
@DjangoBlok Heb jij dit issue doorgenomen en verfijnd? Dan gaan we 'm oppakken.

**Comment by DjangoBlok** [comment]
@tfrijsewijk Ik heb het issue verfijnd en waar nodig aangevuld.

**Comment by tfrijsewijk** [comment]
In de scope stond:

> ## Small variant van label voor in de onderregels met kleiner font (14 pts)

Echter, het blijkt dat Label deze functionaliteit al heeft. De font-size in het label is de font-size waar het in is geplaatst. De default/compact variant zegt iets over de factor van de hoogte:
* Default: `font-size * 2 (16px * 2 = 32px)`
* Compact: `font-size * 1.5 (16px * 2 = 24px, 14px * 2 = 21px)`.

cc @DjangoBlok
