### ISSUE TITLE
Responsive-element: e2e test schrijven

### ISSUE THREAD

**Issue by iterox** [dso-toolkit/dso-toolkit#2692]
Ten behoeve van het visueel regressie testen van het web-component `responsive-element` is het noodzakelijk dat het nemen van de imageSnapShot() op het juiste moment gebeurt.

Voor de storybook-story van het responsive-element (https://storybook.dso-toolkit.nl/master/iframe.html?args=&id=core-responsive-element--responsive-element&viewMode=story) is het noodzakelijk dat er gewacht wordt op alle responsive-elements met class `hydrated` en 1 van de 3 attributen `small`, `medium` of `large`. 

Verder zal de e2e-test alle relevante viewports moeten afdekken.

Tevens deze entry uit `image-snapshot-components.json` verwijderen:

```javascript
  {
    "name": "responsive-element",
    "selector": "",
    "stories": ["responsive-element"],
    "type": "core",
    "wait": ["dso-responsive-element.hydrated[small]", "dso-responsive-element.hydrated[medium]", "dso-responsive-element.hydrated[large]"]
  },
``` 
en `image-snapshot-components.cy.ts` de `function waitForExist` verwijderen.

**Comment by cvanderleij-ilionx** [comment]
@iterox waarom de function waitForExist uit image-snapshot-components.cy.ts halen? Deze wordt door meerdere entries uit de image-snapshot-components.json gebruikt
