### ISSUE TITLE
Kaarten (als variant van linklist?)

### ISSUE THREAD

**Issue by DjangoBlok** [dso-toolkit/dso-toolkit#2697]

**Comment by DjangoBlok** [comment]
@tfrijsewijk In mijn perceptie is dit niet meer nodig. Er is al een apart renvooi component voor gemaakt toch?

**Comment by MichielDHVD** [comment]
@DjangoBlok als je deze niet meer nodig vind. Kun je deze sluiten met een comment

**Comment by DjangoBlok** [comment]
Niet meer van toepassing, de behoefte is al op een andere manier vervuld.
