### ISSUE TITLE
Button Secondary: Hover and active state

### ISSUE THREAD

**Issue by MYpenburg** [dso-toolkit/dso-toolkit#2699]
<img width="370" alt="image" src="https://github.com/dso-toolkit/dso-toolkit/assets/7289928/7f53dfda-4ad2-4572-8959-60c382beed25">

default state: ongewijzigd
disabled state: ongewijzigd

hover state: border grasgroen #39870C, achtergrond #D7E7CE (grasgroen-20, nieuwe tint in palet), tekst grasgroen #39870C

active state: border grasgroen #39870C, achtergrond grasgroen #39870C, tekst wit #FFFFFF

**Comment by hansgrimm** [comment]
Ik kan hier op de Canarias geen contrast meten, maar is bij de hover state het contrast tussen tekst en achtergrond nog steeds OK?

**Comment by MYpenburg** [comment]
@hansgrimm , je bent op vakantie! Foei. En je spreekt jezelf tegen want in Slack postte je een artikel waarin stond dat de contrast vereiste voor hover state minder belangrijk was (helemaal mee eens, hover moet vooral tijdens de mouseover aangeven dat iets klikbaar is). Contrast is iets te weinig, maar omdat het geen "status in rust" is geldt die eis hier niet.
