### ISSUE TITLE
core / document component - imro: tussenkopjes zijn geen headings

### ISSUE THREAD

**Issue by timveld** [dso-toolkit/dso-toolkit#2700]
### Waar
core / document component - imro\
### Aanleiding
De tussenkopjes zijn vetgedrukt, geen headings. Niet acceptabel in het kader van 'het goede voorbeeld geven'. 
### Werkzaamheden
html headings toevoegen (in het voorbeeld en eventueel onderliggende component)
### Gebruikersimpact
Hinderlijk: bemoeilijkt navigatie voor screen reader gebruikers aanzienlijk

**Comment by hansgrimm** [comment]
![Scherm­afbeelding 2024-06-20 om 11 38 30](https://github.com/dso-toolkit/dso-toolkit/assets/506527/ba33a616-614c-4c3c-87bb-afb2eabad7f1)
HMTL is sowieso niet echt 'lean & mean' ;)

**Comment by tfrijsewijk** [comment]
Hi Tim, de markup die je aanhaalt komt as-is uit de backend. De toolkit kan met de huidige opzet hier niets in betekenen.
