### ISSUE TITLE
Document Component: Asynchroon inladen afbeeldingen zorgt voor instabiele scrollTo() bij afnemer

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#2701]
# Aanleiding

Een omgevingsdocument met (grote) afbeeldingen zorgt ervoor dat het scrollen naar document componenten instabiel is. Bij het bepalen van de positie voor het scrollen wordt er geen rekening gehouden met het inladen van afbeeldingen.

Scrollen is geen Document Component functionaliteit. Echter, de afnemer weet ook niet wanneer de browser klaar is met het inladen van afbeeldingen en kan er dus ook geen rekening mee houden.

# Oplossingsrichtingen

* Ozon Content via Document Component een event laten emitten wanneer alle content is gerendered en ingeladen
* De XML bevat ook afmetingen van de afbeeldingen. Mogelijk dat deze afmetingen gebruikt kunnen worden om de `<img>` alvast te voorzien van dimensies. Het fraaie van deze opzet is dat de gebruiker niet hoeft te wachten tot alle afbeeldingen zijn ingeladen alvorens er wordt gescrolled.

# Noot

Ik heb er een bug & feature van gemaakt, afhankelijk van de geboden oplossing.

**Comment by hansgrimm** [comment]
Het probleem wordt hier best goed uitgelegd: https://www.smashingmagazine.com/2020/03/setting-height-width-images-important-again/

**Comment by iterox** [comment]
De 4 afbeeldingen in `ozon-response.json` hebben allemaal een breedte en hoogte.

```
<google-sheets-html-origin><style type="text/css"><!--td {border: 1px solid #cccccc;}br {mso-data-placement:same-7937 | 4295
-- | --
3969 | 3997
7813 | 4228


```

**Comment by tfrijsewijk** [comment]
In overleg met Eric teruggezet naar RFD.

**Comment by iterox** [comment]
Nogmaals naar de waarden van de attributen breedte en hoogte van element Illustratie in ozon-response.json gekeken:
|  |  | waarden in ozon-response |  |  | waarden browser |  |
| Afbeelding (paragraaf) | Breedte  | Hoogte | Aspect-ratio | Breedte  | Hoogte | Aspect-ratio |
|--------|--------|--------|--------|--------|--------|--------| 
| image1.png (§13.71) |  7813 | 4228 | 1.85 | 1280 | 692 | 1.85 |
| image2.jpeg (§13.91) |  7937 | 4295 | 1,85 | 1220 | 888 | 1.37 |
| image3.png (§13.92) | 3969 | 3997 | 0,99 | 592 | 596 | 0,99 |

**Comment by iterox** [comment]
Oplossing in PR maakt van dit issue een `feature`
