### ISSUE TITLE
Panel: New component

### ISSUE THREAD

**Issue by DjangoBlok** [dso-toolkit/dso-toolkit#2711]
Een generiek paneel dat gebruikt kan worden om bepaalde inhoud uit te lichten. 
Wordt toegepast in het document component van regels op de kaart.
In regels op de kaart is het paneel door de gebruiker op te roepen, en te sluiten via het sluiten kruisje.

Design met voorbeeld van het gebruik in regels op de kaart. 
![2024 Panel](https://github.com/dso-toolkit/dso-toolkit/assets/34900082/f77d7f17-405d-471c-b7c5-126acf3f6441)

**Comment by tfrijsewijk** [comment]
```
yarn plop new-stencil-component
```

@hansgrimm probeer dit eens. Naam van het component is `panel`.

**Comment by iterox** [comment]
@DjangoBlok Klopt het dat het sluitkruisje als openen/sluiten toggle knopje gebruikt wordt? In ieder geval zo interpreteer ik de volgende zin uit de beschrijving

`In regels op de kaart is het paneel door de gebruiker op te roepen, en te sluiten via het sluiten kruisje.`

**Comment by DjangoBlok** [comment]
Oh dat klopt niet helemaal. Als het paneel "dicht" is, is het helemaal niet zichtbaar. 
Het label icoontje (naast de kop van het artikel) kan het paneel openen en werkt als toggle.
Het sluitenkruisje is alleen zichtbaar in het geopende paneel.

**Comment by hansgrimm** [comment]
> Oh dat klopt niet helemaal. Als het paneel "dicht" is, is het helemaal niet zichtbaar. Het label icoontje (naast de kop van het artikel) kan het paneel openen en werkt als toggle. Het sluitenkruisje is alleen zichtbaar in het geopende paneel.

zo had ik het ook begrepen idd
