### ISSUE TITLE
Stylelint: Hele repository linten

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#2714]
Deze directory staat nu (per abuis?) in `.stylelintignore`. Daarnaast linten we alleen `/packages`.

In dit issue:

- [ ] `/packages/dso-toolkit` uit `.stylelintignore` halen
- [ ] In `/package.json` veranderen we `"lint:stylelint": "stylelint 'packages/**/*.scss'",` naar `"lint:stylelint": "stylelint '**/*.scss'",`
- [ ] Alle ~150 issues oplossen (met name gemiste physical properties uit #2366)

**Comment by hansgrimm** [comment]
Ik ga daar kijken wat ik aan files gemist heb
