### ISSUE TITLE
group radios / checkboxes: fieldset zonder legend mogelijk volgens Accessibility rapport

### ISSUE THREAD

**Issue by timveld** [dso-toolkit/dso-toolkit#2716]
#### Aanleiding
Bevinding accessibility audit, mij is niet duidelijk wie wat moet doen maar ik zie wel dubbele fieldsets en een fieldset zonder legend zou niet mogelijk moeten zijn. 
Op de volgende pagina's staan er een aantal formulieren. Zoals bijvoorbeeld in het accordeon element 'Bouwwerken waarvoor een melding moet worden gedaan (vragen van het Rijk)'. In dit component staan radio buttons die gegroepeerd en gelabeled worden dankzij het fieldset en legend element. Dit is goed gedaan. Echter wordt het fieldset element dubbel gebruikt en wordt er bij het 'tweede' fieldset element geen legend gebruikt, waardoor er alsnog een group role ontstaat zonder label. Hoogstwaarschijnlijk is dit een bug, maar toch goed om dit op te lossen om verwarring te voorkomen. Zie het verschil tussen DOMNode ".dso-label-container" (goed) vs DOMNode ".dsoradios" (fout, kan beter verwijderd worden). Hetzelfde probleem komt voor bij de checkboxes, bijvoorbeeld in het accordeon 
 
 
	 	De onderzochte set webpagina's voldoet niet aan dit succescriterium.
element "Beschermde dieren of planten". Dit probleem komt voor op de volgende pagina's:
https://beheerportaal.omgevingswet.overheid.nl/checken/nieuw/ stap/3?session=17e2e287-61dc-45c3-aee7-297e7af862ee (In stap 3 van de vergunningscheck)
https://beheerportaal.omgevingswet.overheid.nl/aanvragen/ 46045f3d-14ec-4e17-aeae-31fc3a3c883e-0/verzoek/1995/stap/ 4?session=34c69e2b-c3e1-41d8-891c-2c2f81eca171 (Stap 4 vragen beantwoorden in het 
#### Werkzaamheden
TBD
#### Gebruikersimpact
Beperkt: zou kunnen leiden tot het onnodig uitspreken van 'groepering'. 
Wel prioriteit want van belang voor hertest.

**Comment by MichielDHVD** [comment]
@timveld  gaat naar het toolkit component kijken.

**Comment by iterox** [comment]
Input van PR12: oplossing van de dubbele fieldsets waarvan 1 zonder legend was om bij radio-buttons de binnenste fieldset te verwijderen:

```html
<fieldset
      class="form-group dso-radios dso-invalid"
      aria-errormessage="mijn-id-error-text"
    >
``` 

Vraag uitgezet bij PR12 wat er gedaan is met de attributen op die filedset.

**Comment by MichielDHVD** [comment]
Dit issue blijft open ter verificatie als #2741 afgerond is.

**Comment by tfrijsewijk** [comment]
Ik sluit dit issue toch alvast, de bevinding gaat strikt genomen niet over dit project
