### ISSUE TITLE
Pagination naar bootstrap v3 markup

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#272]
Zoals gemerkt wordt komt er vanuit de developers steeds meer de vraag om elementen meer richting Bootstrap te trekken. 

Nu is dat het geval met de pagination. 

Als de pagination meer richting de bootstrap implementatie moet. Wat is daar dan voor nodig. Moet er nog naar het ontwerp gekeken worden?  
Of is het vooral code technisch dat de implementatie verschilt.  

@WidoBurg

**Comment by WidoBurg** [comment]
Ontwerp, markup en naamgeving classes graag conform https://getbootstrap.com/docs/3.3/components/#pagination

**Comment by PieterVerheij** [comment]
Er zal een hoop weggestijld moeten worden. Ik zie ook geen voorziening voor de puntjes?

**Comment by WidoBurg** [comment]
Klopt. Geen puntjes. 

Ik zou het daarom juist ook andersom doen. Neem over wat er in bootstrap zit. Ik kan mij niet voorstellen dat we met de standaard paginering in bootstrap niet in productie zou kunnen. Het kan altijd anders maar dat kost tijd/geld. 

Samenvattend mijn advies: maak het ontwerp conform bootstrap. Niet andersom.

**Comment by PieterVerheij** [comment]
@MichielDHVD Maak jij een ontwerp, of leg ik zoveel mogelijk de huidige dso-styling op de bootstrap markup en that's it?.

**Comment by tfrijsewijk** [comment]
>Samenvattend mijn advies: maak het ontwerp conform bootstrap. Niet andersom.
Precies wat er gisteren ook is besloten 🎉 

@PieterVerheij: Wat trap jij maar vast af met bootstrap markup en zoveel mogelijk DSO styling. Plak een screenshot tot hoever je komt, dan mag de DSO Toolkit Product Owner in overleg met de UX-ers bepalen of dit toereikend is

**Comment by MichielDHVD** [comment]
Prima!

**Comment by PieterVerheij** [comment]
Hier kan ik op https://getbootstrap.com/docs/3.3/components/#pagination geen uitsluitsel vinden.
Weet iemand of er een standaard gedrag is voor Bootstrap pagination wanneer er in de pager een x aantal stappen (lees pagina's) getoond wordt en het aantal pagina's is hoger (dus bv. de pager heeft 5 stappen maar het aantal pagina's is 13)?

Is die 5 getoonde stappen een vast gegeven?
Wordt altijd de eerste en de laatste stap getoond of de huidge -2 en +2?

Of is dat iets wat de implementator bepaalt (lijkt mij niet)?

Wordt het dan 
```< 8  | 9 | 10 | 11 | 13 >```
of
```< 1  | 9 | 10 | 11 | 13 >```
?

**Comment by NathanAtKadaster** [comment]
Nee hier is geen standaard geedrag voor (want misschien wil jij als implementator juist wel 9 stappen). Het is dan ook aan de implementator om dit gedrag te bepalen. Bij google komen er ook meer `O`'s te staan naarmate je meer resultaten hebt ;) 

Ik heb even een voorbeeldje gemaakt waarin je dit gedrag kunt zien.
https://www.w3schools.com/code/tryit.asp?filename=G1Z76W9K4MJQ
Bootstrap doet hierin alleen de styling op de elementen die je zelf neerzet en bemoeid zich (gelukkig) niet met de inhoud en hoeveel het er zijn.

**Comment by MichielDHVD** [comment]
Het is neem ik aan wel wenselijk om gezamelijk een max aantal te beslissen dat we niet willen overschrijden. Dit betekent dat de hoeveelheid tabjes/pagination opties bij de implementatoren komt te liggen en niet in de toolkit. Of kunnen we de max ook vanuit de toolkit mee geven of is dit niet wenselijk voor de developers?

**Comment by NathanAtKadaster** [comment]
Ik zou de daadwerkelijke implementatie lekker aan de applicatie overlaten. De DSO-toolkit wordt vanuit verschillende frameworks gebruik dus als je dat wil ondersteunen zul je dus voor de verschillende frameworks manieren moeten bedenken om dat af te dwingen. Ik heb er even mee zitten spelen in angular, maar dan kan ik ook op soortgelijke manier (zoals voorbeeld hierboven) navbar menu items specificeren en voor zover ik weet zit daar ook geen maximum aan.

Ik zou hier mijn vingers niet aan branden en het lekker aan de developers overlaten. Eventueel in de documentatie wat richtlijnen opnemen hoe je het zou kunnen gebruiken en hoe je bijvoorbeeld exact dit probleem zou kunnen tackelen.

iets als:
`< 1 | 2 | ... | 11 | 12 >`
`< 1 | 2 | 3 | ... | 10 | 11 | 12 >`
`< 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 >`

Is dan aan de implementerende partij. Als ik de ruimte heb en die wil kunnen benutten dan is het zonde om dat niet te doen.

**Comment by PieterVerheij** [comment]
Ik ben er ook voor om het vrij te laten, maar wel in een richtlijn een max aantal tabjes te definieren. Bootstrap heeft overigens geen voorziening voor de puntjes, dat betekent dan een uitbreiding vanuit 'onze' kant.
```< 1 | 2 | 3 | ... | 10 | 11 | 12 >```

**Comment by NathanAtKadaster** [comment]
Nee toch? dat kun je toch gewoon met `&hellips;` doen? Alleen zul je dan wel dynamisch moeten bepalen waar de `&hellips;` komt. Dat is het lastigste denk ik.
dus zoiets: https://www.w3schools.com/code/tryit.asp?filename=G1ZBXJCWY384

**Comment by PieterVerheij** [comment]
Prima, als de implementator dat doet ;)

**Comment by PieterVerheij** [comment]
@MichielDHVD Klopt de onderlijning van de getallen eigenlijk wel? https://dso-toolkit.nl/5.1.0/components/detail/pagination.html

**Comment by NathanAtKadaster** [comment]
Het viel mij op dat dit bij de [https://dso-toolkit.nl/5.1.0/components/detail/navs.html](navbar)  en de [https://dso-toolkit.nl/5.1.0/components/detail/pager.html](pager) ook aanwezig was. Vooral bij de disabled knopjes is het apart dat de hover effecten nog wel aanwezig zijn.

**Comment by NathanAtKadaster** [comment]
@PieterVerheij Ik zie dat je nog wel klikgedrag hebt op de `&hellips;`. Dan krijg je het lichtgroene rondje kort te zien.

**Comment by NathanAtKadaster** [comment]
ander dingetje is dat het `<` of `>` teken (next previous) verdwijnt bij hover en bij een klik ook niet meer terugkomt. Kan dit komen doordat de pagina in de examples stiekem eigenlijk niet wijzigd waardoor de view niet gereset wordt?

**Comment by PieterVerheij** [comment]
Nee, maar dat wordt wel opgelost.

**Comment by MichielDHVD** [comment]
Die underline klopt niet pieter, lijkt erop bij het aanzetten van de underline van de links dat dit ook een van de componenten blijkt te zijn die is geraakt door deze aanpassing. 

Mischien even issue https://github.com/dso-toolkit/dso-toolkit/issues/286 Aanpassen om deze onderdelen erbij te betrekken.  Het lijkt meerdere componenten te hebben geraakt 

@tfrijsewijk

**Comment by tfrijsewijk** [comment]
De underline is een bug. Dit was een uitgelezen kans geweest voor CSS regressietesting.. Het is geimplementeerd, draaide een tijdje, maar nu zitten we verstrikt in contractuele voorwaarden :-) Ik zal hier vandaag nog eens achteraan gaan.

Nog even over de puntjes in de pager. Het beste is hier vanuit de toolkit een component voor aan te leveren. Zo kunnen we de hover styling sturen en hebben we grip op de "puntjes". @NathanAtKadaster komt netjes met een `&hellips;` maar het weerhoudt een andere developer niet om er `..`, `...`, of zelfs `<span class="fa fa-ellipsis-h"></span>` te plaatsen.

Het blijft een los "item" van de pager, het is nog steeds aan de implementator om deze op het juiste moment op het juiste plekje in het DOM te plaatsen: maar door er een los component van te maken garanderen we uniforme look en feel.

**Comment by tfrijsewijk** [comment]
Preview uitgekomen in 6.0.0: https://www.dso-toolkit.nl/6.0.1/components/detail/pagination-preview.html

**Comment by tfrijsewijk** [comment]
@MichielDHVD Kun je er zo wat mee? Ik denk dat je ook met UX-ers samen moet zitten aangezien de pager visueel echt anders is

**Comment by tfrijsewijk** [comment]
Gebruik vooral die mooie versie selector om het verschil met de vorige release te bekijken :)

**Comment by NathanAtKadaster** [comment]
> Gebruik vooral die mooie versie selector om het verschil met de vorige release te bekijken :)

Bij mij geven alle versies anders dan 6.0.1 een 404 not found terug. Is dit de bedoeling of is er een issue met de webserver?

**Comment by tfrijsewijk** [comment]
Ah jammer, ik pronkte onterecht.

De gehele documentatie is geversioneerd. In de URL staat ook een versie. De versie selector wordt door de webserver tijdens het request geinjecteerd. Deze versie selector leest vervolgens een lijst met alle gepubliceerde versies uit en maakt de dropdown. Het enige wat een selectie doet, is de versie in de url wijzigen.

Mocht je dus op een component zitten wat in vorige versies niet bestaat krijg je inderdaad een 404.

Maar, los van dit alles: De pager is als nieuw component geintroduceerd: "Pagination (Preview)". Dus mijn vlieger gaat in dit geval sowiezo niet op! Sorry voor de verwarring.

Vergelijken gaat dus tussen "Pagination" en "Pagination (Preview)". Overigens kun je voor Pagination wel naar andere versies stappen, maar ik geloof niet dat je daar in bent geinteresseerd.

**Comment by NathanAtKadaster** [comment]
ah oke, maar dan weten we dus waarom dat fout gaat. Dan is er geen man overboord gelukkig. 

Het is wel handige functionaliteit namelijk

**Comment by tfrijsewijk** [comment]
@MichielDHVD: Heb jij hier al naar gekeken?

**Comment by MichielDHVD** [comment]
Is dit de versie die ook te zien is in 7.3.0? 

Het geen wat me opvalt is dat bij de hover van het rondje het pijltje wegvalt/wit wordt. 

Eerder werd het rondje met een pijltje op een hover groen(background) met een wit pijlltje.

**Comment by PieterVerheij** [comment]
De a hoort bij hover een achtergrondkleur te krijgen, die wordt nu overruled door de shorthand notatie van de achtergrondafbeelding `@include icon($dso-icon-button-icon-chevron-right-white-12x12);`

**Comment by MichielDHVD** [comment]
Maar daar wordt nu naar gekeken. Denk dat we deze daarna gewoon kunnen doorzetten.

**Comment by MichielDHVD** [comment]
Ik moet trouwens bij de preview versie kijken. Deze ziet er goed uit. Dit mag doorgezet worden

**Comment by tfrijsewijk** [comment]
Opgeleverrd in 8.2.0:
* https://dso-toolkit.nl/8.2.0/components/detail/pagination-deprecated.html
* https://dso-toolkit.nl/8.2.0/components/detail/pagination.html
