### ISSUE TITLE
Renvooi ondersteuning op Card 

### ISSUE THREAD

**Issue by DjangoBlok** [dso-toolkit/dso-toolkit#2733]
In regels op de kaart hebben we renvooiondesteuning nodig op de card.

Voorbeeld in context
![Plekinfo in renvooi](https://github.com/user-attachments/assets/2df5377c-df0e-4e9f-9d65-13e7a1a2c257)

De benodigde renvooiopties op de card.
![Card in Renvooi](https://github.com/user-attachments/assets/abd6c124-e78b-4c19-bd80-af318e86b0b6)

Wij gebruiken hiervoor alleen de compact black variant. Dus wellicht wordt dit een aparte variant @tfrijsewijk 

Specificaties zijn in Figma te vinden.

**Comment by hansgrimm** [comment]
@tfrijsewijk wat is de status? moet hier nog een ei over gelegd worden?

**Comment by tfrijsewijk** [comment]
Dit issue wordt geblokkeerd door #2666, #2511 en #2507.

**Comment by tfrijsewijk** [comment]
Dit issue is opgelost met #2797.
