### ISSUE TITLE
Dropdown Menu: Safari crasht bij navigatie vanuit compacte Header

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#2735]
- Als je op safari naar regels op de kaart gaat. 
- De kaart applicatie opent. 
- Dan het menu open 
-  Klik op een item 
- Crash 

PR02 heeft al onderzoek gedaan en kunnen het niet in onze eigen code vinden. 

Dubbel check of dit PR02, Toolkit of Kadaster (Webcomponent + iframe issue?)  is waardoor dit komt

**Comment by hansgrimm** [comment]
dat kan ik idd naadloos reproduceren (Safari 17.5, MacOS Sonoma 14.5). Nu de oorzaak nog..

**Comment by tfrijsewijk** [comment]
Mogelijk gerelateerd: #2164
