### ISSUE TITLE
Form And Form Group Radios: Update markup

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#2741]
# Form

In de markup voorschriften geven we aan dat er een "root fieldset" moet zijn. Dit is achterhaald. Dit moet weggehaald worden. In een Form komen Form Groups en Form Buttons.

# Form Group (Radios)

Form Group (Radios) en Form Group (Checkboxes) lijken qua structuur heel erg op elkaar. Radio's heeft nog een inline optie, maar verder zijn ze gelijk.

Maar Radios mist een `fieldset` en `legend` zoals Checkboxes die wel heeft. Daarnaast heeft Radios een label element wat naar geen goed element kan verwijzen.

In dit issue gaan we Radios meer naar Checkboxes trekken: fieldset en legend, geen label. We gaan geen inline optie maken, die blijft exclusief aan Radios.

# Waarom een BREAKING en change label?

"BREAKING" omdat de markup voorschriften, en dus de API wijzigen.
"change" omdat we geen nieuwe functionaliteit toevoegen. In de praktijk wordt deze markup al gebruikt omdat we dit via informele kanalen ook doorgeven. We hebben echter nooit doorgepakt en onze visie uitgewerkt in de voorschriften.

**Comment by iterox** [comment]
Is dit mogelijk een duplicaat van https://github.com/dso-toolkit/dso-toolkit/issues/2716?

**Comment by hansgrimm** [comment]
> Is dit mogelijk een duplicaat van [#2716](https://github.com/dso-toolkit/dso-toolkit/issues/2716)?

Dat zou zomaar kunnen. In de beschrijving van deze issue staat dat Radios een fieldset mist; dat klopt niet, hij heeft wel een fieldset, alleen geen legend. zoals eerder opgemerkt is dat op zich geen invalid html, maar hier pst sowieso wel een legend. aangepast dus. Dat verhaal over 'root fieldset' moet ik nog even checken. 

Later even kijken of met deze operatie ook #2716 nu gefixt is.

**Comment by hansgrimm** [comment]
@tfrijsewijk dus deze tekst moet eruit?
![Image](https://github.com/user-attachments/assets/7528c597-170a-4c8a-9bf7-3b06ab85ccc6)

**Comment by tfrijsewijk** [comment]
> @tfrijsewijk dus deze tekst moet eruit? ![Image](https://private-user-images.githubusercontent.com/506527/356125099-7528c597-170a-4c8a-9bf7-3b06ab85ccc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4ODY4NDIsIm5iZiI6MTcyMzg4NjU0MiwicGF0aCI6Ii81MDY1MjcvMzU2MTI1MDk5LTc1MjhjNTk3LTE3MGEtNGM4YS05YmY3LTNiMDZhYjg1Y2NjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxN1QwOTIyMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ODE5MGZhNTJiYjYwMjFkZjIzZDYyMjZlNGE2NjZmNzUxYjRlOTNkNmFiYTJkZWZiODQ5OGJlYjI3NTA2ZjM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Lel_Z1ewcXDzKzZP0V6K4I8iVGlV0xBCpBnSzfrErcw)

Ja! 🙏 Ik zie dat je het al hebt gedaan :+1:
