### ISSUE TITLE
Skiplink: New component

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#2746]
Voor die applicaties die niet via het portaal worden uitgeserveerd, is het wenselijk dat er een skiplink component beschikbaar is.
2 verwijzingen:

1. naar navigatie
2. naar inhoud

**Comment by MichielDHVD** [comment]
Ontwerp zijn de skiplinks die nu live staan op het loket. Zie loket. 



![Image](https://github.com/user-attachments/assets/b27f8444-1bdb-447f-86bf-36ce403bd109)

**Comment by tfrijsewijk** [comment]
```ts
interface Skiplink {
  /** id of element to scroll to */
  to: string;
  label: string;
  dsoClick: CustomEvent<SkiplinkClickEvent>;
}

interface SkiplinkClickEvent {
  originalEvent: MouseEvent;
  isModifiedEvent: boolean;
}
```

Voorstel
```html
<dso-skiplink to="inhoud" label="Ga naar inhoud">
  #shadow-root
    <a href="#{this.to}">{this.label}</a>
  #/shadow-root
</dso-skiplink>

<main id="inhoud">[...]</main>
```

**Comment by hansgrimm** [comment]
Moeten de skiplink targets niet instelbaar zijn? Alleen navigatie en inhoud is wat star.

**Comment by hansgrimm** [comment]
https://codepen.io/picturit/pen/GRVMBOE/e71f540affb346a0e26df0ab505e1ecb?editors=1100

**Comment by hansgrimm** [comment]
Ik heb alvast wat neergezet, maar misschien kan ik dat nog wat naar bovengenoemd voorstel toe werken.

**Comment by tfrijsewijk** [comment]
> Moeten de skiplink targets niet instelbaar zijn? Alleen navigatie en inhoud is wat star.

Ik lees deze vraag nu pas: Wat bedoel je met skiplink targets?

**Comment by hansgrimm** [comment]
Waar ze naartoe moeten verwijzen. Maar dat is allang beantwoord, en instelbaar.
