### ISSUE TITLE
In modals sluitenkruis standaard tonen

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#275]
Op dit moment vragen wij ons af wat de default is bij een modal. Dat het kruisje rechtsboven aan staat of uit staat ? 

Deze is gedefinieerd door de modal-close of modal-no-close . 

Op dit moment is het volgens mij zo dat de default modal-no-close is. De voorkeur is er om modal-close de default te maken.

**Comment by tfrijsewijk** [comment]
De termen `modal-close` en `modal-no-close` zijn aliassen van de demo componenten. Deze aliassen worden in de markup als ID gebruikt om naar te verwijzen. In het geval van de modal wordt er met een ARIA attribuut `aria-labelledby` verwezen naar de kop `h2`.

Het wel of niet tonen van het sluiten kruis heeft hier niets mee te maken. Het enige wat telt is dat de waarde in `aria-labelledby` gelijk is aan het `id` van de kop.

Het tonen van het sluitenkruis kan vanuit de toolkit niet afgedwongen worden. Los van dat het een interactief element is, moet er ook gedrag aan de knop worden gehangen.

![image](https://user-images.githubusercontent.com/9696261/55714710-69e43800-59f3-11e9-8722-7e7fcfca2f17.png)

Beantwoord ik zo jouw vraag?

**Comment by MichielDHVD** [comment]
Ok dat is dan prima. Maar kunnen we vanuit de toolkit wel het sluitenkruis in alle test versies stoppen. Mochten developers dan de code uit de toolkit overnemen dan staat het kruis altijd in de modal. 

Neem niet weg dat ik zelf bij developers moet langs gaan waar dit kruis nog niet aanwezig is dat deze moet worden toegevoegd.

**Comment by tfrijsewijk** [comment]
OK, ik zal in elke modal het sluitenkruis opnemen

**Comment by tfrijsewijk** [comment]
Opgeleverd in 7.0.0: https://www.dso-toolkit.nl/7.0.0/components/detail/modal--modal.html

**Comment by MichielDHVD** [comment]
Verplaatst naar done
