### ISSUE TITLE
Autosuggest: Fix text align

### ISSUE THREAD

**Issue by Hendriksie** [dso-toolkit/dso-toolkit#2753]
Wanneer de tekst in het `type`-veld (`suggestion`) van het `<dso-autosuggest>`-component een te lange tekst bevat, wordt de tekst naar de linkerzijde uitgelijnt.

![image](https://github.com/user-attachments/assets/647adaf4-295e-4676-bcf8-71ce2fd6bcaf)
![image](https://github.com/user-attachments/assets/560cfd35-4a61-45e2-8a01-2a6ae4910ca6)

**Comment by hansgrimm** [comment]
@Hendriksie heb je een url waar ik deze bug kan bewonderen? Ik heb afaik in de toolkit geen gelijkwaardige situatie, vandaar. thanks! :)

**Comment by Hendriksie** [comment]
@hansgrimm Zekers!

* Open VDK (acceptatie-omgeving):
  * https://ketenacceptatie.document-viewer.dso.kadaster.nl/zoeken/document
* Type "1962" in het zoekveld
* Zie dat optie 4 dit probleem toont

![image](https://github.com/user-attachments/assets/4f79b800-ac73-4981-8f37-839b33b34f80)

**Comment by hansgrimm** [comment]
@Hendriksie dank! heb je een gebruikersnaam en wachtwoord voor me?

**Comment by hansgrimm** [comment]
Door deze aanpassing klopt de uitlijning weer. dit kan ook weer zo z'n nadelen hebben, maar iig beter dan hert alternatief.
![Scherm­afbeelding 2024-08-15 om 10 47 32](https://github.com/user-attachments/assets/30aaa48c-1fe5-478d-9564-35132cde8202)
Nu even kijken of dit in de toolkit te fixen is.

**Comment by tfrijsewijk** [comment]
* Uitlijning ook bij lange extra en value (de titel) testen
* Lang voorbeeld opnemen in `packages/dso-toolkit/src/components/autosuggest/autosuggest.demo.ts`

**Comment by hansgrimm** [comment]
Ik heb in `packages/dso-toolkit/src/components/autosuggest/autosuggest.demo.ts` een resultaat toegevoegd met de content zoals in de bug. nu nog voor mekaar krijgen dat die ook getoond wordt...

**Comment by hansgrimm** [comment]
> Ik heb in `packages/dso-toolkit/src/components/autosuggest/autosuggest.demo.ts` een resultaat toegevoegd met de content zoals in de bug. nu nog voor mekaar krijgen dat die ook getoond wordt...

YES! geef een 'g' in en scroll naar beneden in de autosuggest :)
