### ISSUE TITLE
Files: Change focus state

### ISSUE THREAD

**Issue by MYpenburg** [dso-toolkit/dso-toolkit#2757]
Als deze knop (zowel primary als secondary) de keyboard focus krijgt wordt hij visueel gestyled als een hover. Wat je zou verwachten is dat de keyboard focus getoond wordt als een blauwe outline, zoals ook op andere plekken waar de button wordt gebruikt.
Keyboard focus ziet er zo uit (primary en secondary)
<img width="234" alt="image" src="https://github.com/user-attachments/assets/6bee0aeb-f6e9-413e-9daf-40b57147a7a3">
<img width="234" alt="image" src="https://github.com/user-attachments/assets/2ff90a52-3360-46ae-82d4-ec19ef3b4dda">

Zou moeten zijn:
<img width="234" alt="image" src="https://github.com/user-attachments/assets/8f9b5796-7753-49ce-8657-7a36b9deb781">
<img width="234" alt="image" src="https://github.com/user-attachments/assets/9e38a6bd-92e4-4ff6-aaa2-9829a83b9aa3">

**Comment by hansgrimm** [comment]
Volgens mij is deze duidelijk genoeg voor RFD. ip pak 'm op, kan ik morgen in 010 meteen even afstemmen of dat zo OK is.

**Comment by hansgrimm** [comment]
@MYpenburg UX-check kan hier: https://storybook.dso-toolkit.nl/_2757-Files-change-focus-state/?path=/story/html-css-form-groups-files--files

**Comment by tfrijsewijk** [comment]
@MYpenburg De focus styling die jij aandraagt is denk ik een screenshot van de standaard focusstyling van jouw browser. De knop waar we het over hebben is eigenlijk geen knop (lang verhaal) en kunnen we dus niet de user agent styling toepassen.

Daarom moeten we eigen focus styling toepassen. Daar hebben we een voorziening voor, maar Hans heeft een aanpassing gedaan omdat die niet overeenkomt met jouw ontwerp/screenshot. En ik denk dat we dat niet moeten doen:

Huidige focus styling:
![image](https://github.com/user-attachments/assets/26a79e80-d5ee-4fe4-b397-818a395611c3)

Door Hans volgens ontwerp toegepast:
![image](https://github.com/user-attachments/assets/406d1ceb-1cad-473e-a3b4-a7c104678825)

Wat het in mijn optiek zou moeten zijn:
![image](https://github.com/user-attachments/assets/4be5f31c-cdce-48fe-bfdd-857cbde9a284)

Waar het mij om gaat is dat we één (maatwerk, niet-browser native) focus styling hebben. Samen met de default focus styling zijn er voor de eindgebruiker twee focus stylings. Met de aanpassing van Hans gaan we wat mij betreft naar 3 focus stylings, en dat vind ik geen goed idee.

Een alternatief is dat we van onze focus styling voorziening de ruimte afhalen, dan ziet het er voor de Selectable als volgt uit:

![image](https://github.com/user-attachments/assets/44b55b3c-3fdd-4a78-9ece-da6c53ced25f)

**Comment by hansgrimm** [comment]
Eens. alvast aangepast naar de standaard focus styling, inclusief outline offset.

**Comment by MYpenburg** [comment]
Eens, ziet er beter en consistenter uit.
