### ISSUE TITLE
Form: Markup herzien

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#2760]
# Aanleiding

In het PR #2756 horend bij issue #2741 vraagt Eric zich af waarom er `<legend class="sr-only">` en `<span aria-hidden="true">` nodig zijn:

>Naast een formulier label ook een icoon kan staan. En om die correct te positioneren hebben we een container element nodig. Aangezien een `legend` direct het eerste kind moet zijn en `div.form-group` te ver weg staat om een element naast het formulier label te positioneren, hebben we deze vreselijke constructie moeten bedenken.
>
>Neemt niet weg dat ik graag kijk naar alternatieve oplossingen om dit anders te doen. Blij ben ik er namelijk niet mee. Misschien is het ontwerp van het Formulier inmiddels dusdanig aangepast (of de browsers voldoende ge-evolueerd) om dit anders te doen.

_Originally posted by @tfrijsewijk in https://github.com/dso-toolkit/dso-toolkit/pull/2756#discussion_r1713192291_

In dit issue gaan we:
- [ ] Met UX het visuele en functionele ontwerp in Figma onderbrengen
- [ ] Met een frisse blik naar de markup kijken. Wellicht is het niet meer nodig.

# Noodzaak
Bij het selecteren van tekst op de pagina wordt beide labels geselecteerd. Een copy/paste betekent dus dubbele labels.

**Comment by tfrijsewijk** [comment]
@hansgrimm Ik heb van dit issue een research gemaakt.

Ik wil uitzoeken of we het label van een Form Group: Checkboxes en Form Group: Radios nog steeds dubbel in de markup moeten hebben staan:

```html
<fieldset class="form-group dso-checkboxes">
  <legend class="sr-only">${formGroup.label}</legend>
  <div class="dso-label-container">
    <span class="control-label" aria-hidden="true">${formGroup.label}</span>
  </div>
  <div class="dso-field-container">[...]</div>
</fieldset>
```

Dat hebben we gedaan omdat `legend` het eerste directe kind van `fieldset` moet zijn, en we het volgende visuele ontwerp willen:

![Image](https://github.com/user-attachments/assets/96bff3e7-8a94-4fce-bc71-399c34687738)

Deze markup gaat echter al een paar jaartjes mee. Wil jij eens kijken of we dezelfde functionele en visuele wensen kunnen realiseren met de volgende simpelere markup?

```html
<fieldset class="form-group dso-checkboxes">
  <legend class="dso-label-container">${formGroup.label}</legend>
  <div class="dso-field-container">[...]</div>
</fieldset>
```

Aandachtspunten zijn natuurlijk de informatie buttons (Info Button) en de toelichting (Info).

Deze changes zijn BREAKING, dat realiseren we ons. We willen uitzoeken of het de moeite waard is om deze change door te voeren.

Daarnaast: Mocht het NIET mogelijk zijn om de huidige functionele en visuele specificaties te realiseren, dan ben ik benieuwd tot hoever je WEL komt. Ofwel, kan het ontwerp richting de implementatie schuiven?

**Comment by hansgrimm** [comment]
- In eerste instantie bedachte 'oplossing' (legend weer gewoon exposed, info daarin) geen optie, want html valideert niet.
- in tweede instantie bedachte oplossing (legend in grid) niet uitvoerbaar, want legend layoutmatig niet van zn plek te krijgen, tenzij je hem met `position: absolute` uit de flow trekt, maar dat geeft direct andere problemen.
- in derde instantie bedachte 'oplossing' (legend-tekst verplaatsen naar aria-label om iig het dubbele copieren op te lossen) is niet correct qua aria-regels:
![Scherm­afbeelding 2024-10-17 om 14 54 48](https://github.com/user-attachments/assets/03a98318-aad1-4a6e-9ca0-8e269fb037b0)

**Comment by hansgrimm** [comment]
zie speeltuin: https://codepen.io/picturit/pen/VwobQzj?editors=1100

**Comment by hansgrimm** [comment]
We gaan deze issue weer sluiten, en wel hierom:
- de `legend` is niet in een layout op te nemen zonder hem uit de flow te halen, wat geen optie is
- de toggletip bevat elementen die binnen een `legend` niet zijn toegestaan
- attribuut `aria-label` is niet toegestaan op een `legend`.

De bestaande situatie zal dus voortleven totdat iemenad weer een lumineus idee heeft, *of* de techniek wijzigt.
