### ISSUE TITLE
Paragraph: Nieuwe variant disclaimer

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#2762]
Styling overnemen van `.text-muted` en verrijken met `font-style: italic`.

Alles erop en eraan, dit is een volwaardige variant van het Paragraph component. Dus Storybook variant, screenshots, etc. 

![Image](https://github.com/user-attachments/assets/b6fc7370-d562-435b-a6da-69a7fb40cfe1)

**Comment by MYpenburg** [comment]
Nadat deze is opgeleverd: https://jira.team-dso.nl/jira/browse/PR12-24053

**Comment by hansgrimm** [comment]
@MYpenburg Het schuingedrukt presenteren van tekst, en dan met name van blokken tekst (zoals hier) is een toegankelijkheids-issue voor mensen met dyslexie.
Zie hier: https://www.bdadyslexia.org.uk/advice/employers/creating-a-dyslexia-friendly-workplace/dyslexia-friendly-style-guide ("Avoid underlining and italics as this can make the text appear to run together and cause crowding. Use bold for emphasis."). Ik raad dus schuingedrukt af, en ik hoop @timveld ook ;)
Misschien heb je een ander voorstel om de tekst onderscheidend te maken?

**Comment by MYpenburg** [comment]
Nee, en wel hierom.
Tenzij het een keiharde eis is en wij er een A status mee verliezen.
We willen liever niet dat mensen deze tekst echt lezen.
Zie het als een blok dat communiceert: hier staan de kleine lettertjes, omdat het moet. 
Dat is de functie, niet de tekst zelf. 

Wat mij betreft: mocht er een (veel) betere tekst voor de disclaimer op tafel komen (en dat is geen makkelijk traject), dan kunnen we het ontwerp heroverwegen. Het is nu een gedrocht dat met heel veel persen en wurgen tot stand is gekomen.

Nogmaals: Als er een harde eis ligt vanuit Accessibility dan is het natuurlijk een ander verhaal. Maar voor nu vind ik het acceptabel als we hier een beetje tegen de grens aanschuren.

**Comment by hansgrimm** [comment]
Of het al dan niet de A-status kan kosten, is heel subjectief; ik verwacht het niet, maar je weet maar nooit..
Afgezien daarvan, blijf ik het een slecht idee vinden om een groep uit te sluiten van het (makkelijk) lezen van een blok tekst, in het geval dat ze dat echt zouden willen. 
Daarbij zie ik in dit verband de toegevoegde waarde van cursief niet. Dat zou imho juist aandacht vragen voor een tekst waarvan je liever niet wil dat mensen die lezen.
Ik heb een ander voorstel: als we het toch hebben over kleine lettertjes, waarom het tekstblok niet een tandje kleiner (75%)? Een gebruiker kan dan altijd nog inzoomen, wat sowieso al moet kunnen, en hoeft dan niet de fontstyle aan te passen, wat meer handigheid vereist.
De 'zware' dyslectische gevallen zetten hun eigen font/fontsyles erin dmv de user-styles, dus die zien onze content sowieso heel anders dan anderen (zie https://opendyslexic.org/). daar hoeven we niet zo veel rekening mee te houden, die trekken huin eigen plan wel.
_Echte_ kleine lettertjes, is dat wat?

**Comment by timveld** [comment]
Ik ben het met @hansgrimm  eens, dit ontwerp is afkeurenswaardig. Maar niet in de zin van WCAG, ik kan geen succescriterium bedenken waarop de auditor een afwijking kan vaststellen. En in termen van gebruikersimpact lig ik er niet wakker van. Zelfs als er mensen zijn die deze tekst (bijna) niet kunnen lezen missen ze hooguit een onbelangrijke disclaimer, kans dat iemand hierop vastloopt is minimaal. Kortom als het team dit ontwerp wil handhaven vind ik dat betreurenswaardig maar ga ik er in mijn adviserende rol niet verder tegen 'protesteren'.

**Comment by hansgrimm** [comment]
Ook gij, Brutus 😉
