### ISSUE TITLE
Build: Bij releasen ook dso-toolkit dependencies versioneren

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#2768]
De packages die gepubliceerd worden krijgen door het release script een versie. Dat is in #1337 gemaakt.

Maar ik ben vergeten de _dependencies_ van diezelfde packages te zetten: In de package.json van `@dso-toolkit/angular` staat nog een verwijzing naar `"@dso-toolkit/core": ">=45"`. En dat is niet meer nodig.

In dit issue de juiste versies zetten

**Comment by iterox** [comment]
Wat zijn dan de juiste versie(s)?
