### ISSUE TITLE
Website: Couldn't find story matching 'annotation--default'

### ISSUE THREAD

**Issue by iterox** [dso-toolkit/dso-toolkit#2776]
Wanneer ik naar https://www.dso-toolkit.nl/master/components/domeinspecifiek/juridisch/annotation navigeer dan verschijnt 

<img width="916" alt="Screenshot 2024-08-22 at 16 50 02" src="https://github.com/user-attachments/assets/e724f62f-1340-4369-9c82-0fd05eef392d">

Momenteel bestaan er 5 Storybook Annotation Stories:

- core-annotation--activiteit
- core-annotation--gebiedsaanwijzing
- core-annotation--kaart
- core-annotation--locatie
- core-annotation--omgevingsnormwaarde

De Storybook Annotation Story 'core-annotation--default' verwijst nog naar een gedateerde story.

`website/docs/components/domeinspecifiek/juridisch/annotation.mdx`:
```mdx
import { StorybookComponent } from "@site/src/components/StorybookComponent";

# Annotation

<StorybookComponent variant="default" />
``` 

Gaan we deze naar 1 van de 5 huidige stories laten verwijzen of gaan we deze uitbreiden en gaan we alle 5 de annotations etaleren?

**Comment by tfrijsewijk** [comment]
Alle 5 varianten etaleren, ieder met eigen `##` kop.
