### ISSUE TITLE
Project Item: Nieuw component

### ISSUE THREAD

**Issue by MYpenburg** [dso-toolkit/dso-toolkit#2779]
Layout
<img width="1180" alt="image" src="https://github.com/user-attachments/assets/8634fa65-04ef-4241-aa89-99e52db332bd">

Markeringen
<img width="1147" alt="image" src="https://github.com/user-attachments/assets/12b9a341-b0bb-4dc7-af5e-37d400b5689e">

**Inhoud / Slots**
- Projectnaam: altijd tonen. Klik wordt doorgegeven.
- Wordt Verwijderd label: tonen als niet leeg
- Knop Edit (potlood): wel/niet tonen als parameter. Klik wordt doorgegeven. (denk aan hover en sr-only met Projectnaam erin)
- Knop Delete (prullenbak): wel/niet tonen als parameter. Klik wordt doorgegeven. (denk aan hover en sr-only met Projectnaam erin)
- In te dienen aanvullingen (#): tonen als niet leeg, gemarkeerd tonen als optie
- Ingediende verzoeken (#): tonen als niet leeg, gemarkeerd tonen als optie
- In te dienen activiteiten (#): tonen als niet leeg EN geen aanvullingen
- Locatie: tonen als niet leeg, gemarkeerd tonen als optie
- Mijn rol: tonen als niet leeg
- Laatste wijziging: tonen als niet leeg
- Het slot "status" heeft een kleine font-size van 14px

**Layout**
De twee knoppen staan altijd rechtsboven uitgelijnd. 
In het blok dat links daarvan overblijft wordt de projectnaam altijd linksboven uitgelijnd.In datzelfde blok wordt het Wordt Verwijderd label rechts uitgelijnd, als daar ruimte voor is. Anders Links uitgelijnd op de volgende regel.

De aanvullingen, verzoeken en activiteiten worden in deze volgorde getoond (max 2 tegelijk) en als blok links uitgelijnd.
De Locatie, mijn rol en Laatste wijziging worden als blok rechts uitgelijnd op dezelfde hoogte als aanvullingen/verzoeken/activiteiten als daar ruimte voor over is. Anders komt dit blok links uitgelijnd op de regel eronder.

Smalle viewport: blokken lopen gewoon door in de volgende regel met gepaste verticale afstand.

## Toelichting

<img width="1158" alt="image" src="https://github.com/user-attachments/assets/4adb7f3c-5cc6-4a0f-8df8-58a296dbafe0">

_(In bovenstaande schets is "Status" omgezet naar "Progress", en "Meta" naar "Status")_

```ts
export interface ProjectItem<TemplateFnReturnType> {
  title: string;
  href: string;
  headingLevel?: HeadingLevel;
  label?: string;
  progress?: DefinitionList<TemplateFnReturnType>;
  status: DefinitionList<TemplateFnReturnType>;
  actions?: Button[];
}
```

```html
<ul>
  <li>
    <dso-project-item name="Mijn project" label="Wordt binnenkort verwijderd">
      <dl slot="progress">
        <dt>Ingediende verzoeken:</dt>
        <dd>4</dd>
        <dt>In te dienen activiteiten:</dt>
        <dd>16</dd>
      </dl>

      <dl slot="status">
        <dt>Locatie:</dt>
        <dd>Getekend gebied</dd>
        <dt>Mijn rol:</dt>
        <dd>Gemachtigde</dd>
        <dt>Laatste wijziging:</dt>
        <dd>12-09-2023</dd>
      </dl>

      <div slot="actions">
        <button class="dso-tertiary"></button>
      </div>
    </dso-project-item>
  </li>
</dso-projects>
```

```html
// ❌ global-stylesheet -> dso.css
dso-project-item dl[slot="status"] {
  // horizontaal uitlijnen
}

// ✅ Styling met shadow-root <style>

// packages/dso-toolkit/src/components/definition-list/definition-list.scss
dl {
  display: var(--_dl-display, inline-block);
}

dd {
  margin-inline-start: var(--_dl-dd-margin-inline-start, 0);
}

// Web Component stylesheet voorzet
<dso-project-item>
  #shadow-root
    <style>
      // packages/core/src/components/project-item/project-item.scss
      ::slotted(dl[slot="status"]) {
        --_dl-display: flex;
        --_dl-dd-margin-inline-start: 16px;
      }
    </style>
  #/shadow-root
  <dl slot="status"></dl>
</project-item>
```

**Comment by hansgrimm** [comment]
@timveld wat doet NVDA met een <mark>?

**Comment by timveld** [comment]
@hansgrimm  zowel NVDA als JAWS lezen in Firefox en Chrome voor "gemarkeerd [tekst[ einde gemarkeerd". In Edge niet maar dat lijkt me een bug.

**Comment by hansgrimm** [comment]
Okee, dan lijkt mij de `<mark>` een goede optie. Zij het met aangepaste styling

**Comment by tfrijsewijk** [comment]
@MYpenburg Tijdens de refinement kwam naar boven toe dat we voor "status" dezelfde opzet voor "meta" willen toepassen. We denken dat dat vanuit toegankelijkheidsperspectief beter uitpakt. Dat zou betekenen dat Status ook met dubbele punt gaat werken:

```
Ingediende verzoeken: 4   In te dienen activiteiten: 16          Locatie: Getekend gebied    Mijn rol: Gemachtigde    Laatste wijziging: 12-09-2023
```

Is dit een optie?

**Comment by MYpenburg** [comment]
Ja, dat is prima. Vanuit eerdere ontwerpen was het nog een idee om links te maken van de status items, van daaruit zijn de haken ontstaan. Maar nu dat weg is is het gebruik van : ook prima (en je bent van enkelvoud/meervoud af). 
Ik heb nog eens nagedacht over de termen. Eigenlijk is Status meer Progress en Meta meer Status. Kan dat nog worden meegenomen in het component?

**Comment by tfrijsewijk** [comment]
> Ja, dat is prima. Vanuit eerdere ontwerpen was het nog een idee om links te maken van de status items, van daaruit zijn de haken ontstaan. Maar nu dat weg is is het gebruik van : ook prima (en je bent van enkelvoud/meervoud af).

👍

> Ik heb nog eens nagedacht over de termen. Eigenlijk is Status meer Progress en Meta meer Status. Kan dat nog worden meegenomen in het component?

Ja, prima. Ik begrijp het. Ik zal de modellering bijwerken.
