### ISSUE TITLE
Component status bijwerken

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#278]
Diverse componenten hebben geen READY vlag, maar WIP of UNSTABLE. Accoderen welke zijn voltooid en doorvoeren in de library

**Comment by MichielDHVD** [comment]
Deze staat assigned op mij zie ik nu. Moet ik langs de toolkit lopen en kijken welke naar Ready verplaatst mogen worden?

**Comment by tfrijsewijk** [comment]
Ja graag. Ik heb het over de groene/oranje/rode indicators in het menu naast de naam van het component

**Comment by MichielDHVD** [comment]
De volgende componenten mogen de status Ready krijgen. De andere staan voorlopig nog open voor verandering. 

Modal: Ready
Form Field info/Form field info button: ready
Form vertical/horizontal: ready

Alert: ready
Badge: ready
Label: ready
Navigations: ready
Steps: ready
Footer: ready
Full width: ready

**Comment by tfrijsewijk** [comment]
Doorgevoerd in 5.1.0: https://www.dso-toolkit.nl/5.1.0/

**Comment by MichielDHVD** [comment]
Gezien en verplaatst naar Done
