### ISSUE TITLE
Map Controls: Button styling broken

### ISSUE THREAD

**Issue by MYpenburg** [dso-toolkit/dso-toolkit#2794]
## knoppen tonen hover state bij keyboard focus

![Image](https://github.com/user-attachments/assets/a4fedc75-a7ee-4cd6-96c0-c7a9e5f88ace)

## Sass styling uit #2724 

Heeft net zoals in #2822 de styling omver getrapt.

**Meteen proactief de rest van de codebase doorzoeken of er meer van dit soort gevallen zijn. Het verband lijkt te zijn bij web componenten waar de `button` mixins worden toegepast.**

**Comment by hansgrimm** [comment]
Gedaan. Bijvangst door proactief doorzoeken: image overlay knopje was ook sjtuk. reparee overflakkee.

**Comment by hansgrimm** [comment]
Gewetensvraagje: volgens mij wordt de mixin `map-focus()` nu nergens meer aangeroepen; eruit slopen maar?

**Comment by tfrijsewijk** [comment]
> Gewetensvraagje: volgens mij wordt de mixin `map-focus()` nu nergens meer aangeroepen; eruit slopen maar?

Aha, dit heb ik als feedback op de review geplaatst. Antwoord: Ja, weg ermee.
