### ISSUE TITLE
Card: Opsplitsen naar Card, Plekinfo Card en Document Card

### ISSUE THREAD

**Issue by emosterd98** [dso-toolkit/dso-toolkit#2797]
We willen de interface van de cards verbeteren en opsplitsen in 3 componenten. 
1. Card (basis)
2. Plekinfo card
3. Document card.

![3 opties](https://github.com/user-attachments/assets/0223a2c7-9380-4c3d-9038-ec08f9841f08)

## Algemene eigenschappen:
- Alleen de titel is klikbaar, niet de hele kaart. 
- Bij hover over de titel wordt het duidelijk dat dit de anchor is en deze klikbaar is door een underline en het grijs worden van de volledige kaart. 
- Bij focus op de titel zal de gehele card grijs gearceerd worden.
- Focus en hover styling zijn hetzelfde. Kader bij focus om de anchor. Underline onder de titel bij hover.
- 4px tussen de titel en de chevron
- Chevron nooit alleen op een regel plaatsen, indien dit het geval is het laatste woord meenemen naar de volgende regel.

**Aanpassingen**
- Static card kan eruit, deze wordt momenteel niet gebruikt en denken we ook niet meer nodig te hebben. (@tfrijsewijk zoekt nog uit of hij wordt gebruikt)
- Card is dus per definitie interactief door de titel (anchor). Dus de card is niet volledig klikbaar en hoverbaar. Hierdoor kun je “i” ook klikbaar maken nu en hoverbaar. 

## Card

![Card](https://github.com/user-attachments/assets/93f01341-5d96-4cd2-bd7f-2385bb3193cb)

- Anchor achter de anchor wordt inline een chevron geplaatst
- Optioneel Selectable (nog nodig voor VRK viewer)
- Optioneel rich content slot. (Hier kunnen ook interactieve elementen in worden geplaatst?)
- Optioneel een interactive slot geplaatst aan de rechterzijde van de card

Aanpassingen aan model, de volgende properties gaan weg:

```ts
interface Card {
  /** @deprecated use `href` */
  clickable?: boolean;
  image?: string;
  imageShape?: (typeof imageShapes)[number];
}
```

`clickable` is de default, en in geval van werken met statische variant moet dit een niet-default-true boolean property worden. De stencil eslint klaagt.

`image` en `imageShape` zijn functioneel verhuisd naar Card Plekinfo.

Uiteindelijk zal het ongeveer dit model krijgen:

```ts
interface Card {
  label: string;
  href?: string; // verplicht als statische variant verdwijnt
  mode?: Anchor["mode"];
  selectable?: Selectable<TemplateFnReturnType>;
  content?: TemplateFnReturnType;
  interactions?: Array<Button | Label | Toggletip<TemplateFnReturnType> | SlideToggle>;
  dsoCardClicked?: (e: CustomEvent<DsoCardClickedEvent>) => void;
}
```

## Plekinfo Card

<img width="1081" alt="Card:Plekinfo" src="https://github.com/user-attachments/assets/e993b614-c7eb-4d85-9249-ea8abb9d9326">

- Legenda slot (hier wordt het legenda icoon in geplaatst)
- Anchor (objectnaam) achter de anchor wordt inline een chevron geplaatst
- Optioneel content slot (wordt gebruikt voor een subtitel)
- Renvooi opties, verwijderd, toegevoegd voor de hele card, ook mogelijk op de anchornaam en in het contentslot

```ts
interface PlekinfoCard {
  label: Renvooi;
  href: string;
  meta?: TemplateFnReturnType;
  content?: TemplateFnReturnType;
  symbool: TemplateFnReturnType;
  symboolShape?: (typeof imageShapes)[number]; // Aan viewer developer vragen of dit nog steeds nodig is
  wijzigactie?: unknown; // nog uitwerken
  dsoCardClicked?: (e: CustomEvent<DsoCardClickedEvent>) => void;
}
```

## Document Card
<img width="1041" alt="document card" src="https://github.com/user-attachments/assets/e705f886-8156-4291-a6c9-ab2094ff5e3d">

- Anchor (documentnaam) achter de anchor wordt inline een chevron geplaatst
- Optioneel een meta slot geplaatst aan de rechterzijde van het anchor (gebruikt voor ontwerplabel,  ontwerpmarkering, toekomstig label)
- Type document
- Naam bevoegd gezag (optioneel toegevoegd achter type)
- Onderste regel datum met status (kan ook een ontwerplabel in worden geplaatst)

```ts
interface DocumentCard {
  label: string;
  href: string;
  meta?: TemplateFnReturnType;
  type: string;
  typeToelichting: TemplateFnReturnType;
  status: TemplateFnReturnType;
  dsoCardClicked?: (e: CustomEvent<DsoCardClickedEvent>) => void;
}
```

## Hover:
Color/grijs/grijs-5

## Active:
Color/grijs/grijs-10

**Comment by hansgrimm** [comment]
Qua styling hebben wij een probleem: het hover/focus-effect (card krijgt grijze achtergrond bij hover/focus van de link) is op het webcomponent niet aan de praat te krijgen. 

Oorzaak volgens mij: de gebruikte `:has(a:hover, a:focus)` kan niet in de shadowroot van het webcomponent 'kijken' of er sprake is van hover/focus.

Mogelijke oplossingsrichting: het webcomponent voorzien van een 'binnenbandje' (een '-inner' div), want binnen de shadowroot werkt `:has()` wel. Op die inner kan dan het hover/focus effect gezet worden.

Nadeel: markup html/css-versie en webcomponentversie gaat nog verder uit elkaar lopen, en de styling ook, want de padding die op het root-element zit moet in het geval van het webcomponent 1 stapje naar binnen (op de inner).

Andere suggesties? Deze jongen houdt zich aanbevolen :)

**Comment by iterox** [comment]
Ik ga me eens inlezen in `::part`

**Comment by hansgrimm** [comment]
Net wat geprobeerd met `::part`, maar niks nie werke nie.

**Comment by iterox** [comment]
Ik heb een commit gedaan: https://github.com/dso-toolkit/dso-toolkit/pull/2826/commits/1361aba8e48cda95f82328dbe7677f4ca15e831d

**Comment by hansgrimm** [comment]
Haha, dat is wel vies inderdaad... :)

de `:focus-within` moet ook nog vervangen worden door hetzelfde, want het bg-effect mag alleen als de link wordt gefocust, niks anders binnen de card.

**Comment by iterox** [comment]
Nou, ik ben al weer behoorlijk de weg kwijt aan het raken op dit punt. Je hebt helemaal gelijk @hansgrimm . Maaar, vraag ik me af, hoe gaan we deze eis vertalen naar het HTML/CSS Card component:

[] niet
[] instructie geven
[] implementeren in de css-template

**Comment by iterox** [comment]
@emosterd98 @DjangoBlok Over de kleuren. In dit issue staat het volgende vermeldt:

Hover:
Color/grijs/grijs-5

Active:
Color/grijs/grijs-10

Het is duidelijk dat die 2 kleuren gelden voor een Plekinfo-card zonder wijzigactie voegtoe/verwijder en de Document Card wanneer er resp. gehoverd wordt over de card en wanneer de card active is.
Maar geldt de hover kleur grijs-5 ook als de card active is? Als de card niet active is dan zorgt de hover voor een donkere grijs 5 achtergrondkleur. Als de card active is dan is de achtergrondkleur grijs-10 en wordt dan bij hover grijs-5? In dat geval dus lichter. Is dat wat gewenst is?

Een plekinfocard kan wijzigactie voegtoe of verwijder hebben.
De achtergrondkleur van voegtoe is $lime-20: #e4f1d4;. Wat wordt dan de active kleur? Wat is dan de hover kleur?
De achtergrondkleur van verwijder is $rood-20: #f5d8dc;. Wat wordt dan de active kleur? Wat is dan de hover kleur?

**Comment by DjangoBlok** [comment]
Hover en Active state:
Ik ben van mening dat de active state geen hover kleurverandering hoeft te hebben. Dus dan blijft de active state grijs-10

**Comment by DjangoBlok** [comment]
Kleuren voor renvooi:
Voegtoe
Lime-20
Hover: Lime-20 5% zwart  = #D8E5C9
Active: Lime-20 10% zwart = #CED9BF

Verwijder 
Rood-20
Hover: Rood-20 5% zwart  = #E9CDD1
Active: Rood-20 10% zwart = #DDC3C6

**Comment by iterox** [comment]
@DjangoBlok 

Aaangaande document-card staat er in de ontwerpen een Label status warning compact rechtsbovenin de card. De 2e bullet zegt idd "Optioneel een meta slot geplaatst aan de rechterzijde van het anchor (gebruikt voor ontwerplabel, ontwerpmarkering, toekomstig label)". De 5e bullet zegt echter ook "Onderste regel datum met status (kan ook een ontwerplabel in worden geplaatst)". Edoch zie ik in de ontwerpen geen ontwerplabel terugkeren in de statusregel.

Vraag: Zit er wel of niet een Label in de status regel van de Document Card?

**Comment by hansgrimm** [comment]
We hebben 2 varianten die ik nog niet in het rijtje zie staan:
- with image (legenda blokje voor de titel); deze is qua layout gelijk aan `is-selectable`. ik zal vast zorgen dat de css dat faciliteert (`[has-image]` op de core, `.dso-has-image` op de html/css.
- active (wat wordt daar exact mee bedoeld?)

**Comment by DjangoBlok** [comment]
> We hebben 2 varianten die ik nog niet in het rijtje zie staan:
> 
> * with image (legenda blokje voor de titel); deze is qua layout gelijk aan `is-selectable`. ik zal vast zorgen dat de css dat faciliteert (`[has-image]` op de core, `.dso-has-image` op de html/css.
> * active (wat wordt daar exact mee bedoeld, als in wanneer is de card 'active'?) <-- @DjangoBlok @emosterd98

- De plekinfo card heeft als optie een legenda blokje.
- Er zit altijd een link achter de titel van de card. De active state geeft aan of de link de active state heeft.

**Comment by hansgrimm** [comment]
Aha, het gaat hier dus over de `:active` state van de link, dus dat hele korte momentje dat de link wordt aangeklikt. duidelijk, on it.

**Comment by hansgrimm** [comment]
Die is gelijk aan hover, als ik alles goed lees.

**Comment by DjangoBlok** [comment]
De active state in het design ging om het aangeven welk van de cards actief is (dus geselecteerd)

**Comment by hansgrimm** [comment]
Dus als de checkbox is aangevinkt?

**Comment by iterox** [comment]
Na overleg tussen @emosterd98 en @iterox is er besloten dat ook Card op dezelfde wijze als Plekinfo Card en Document Card een active state heeft die gekoppeld is aan een door de afnemer van het component te zetten property `active` op de Card.
