### ISSUE TITLE
Document Component: Panel heading  wordt "Kenmerken en kaart"

### ISSUE THREAD

**Issue by iterox** [dso-toolkit/dso-toolkit#2798]
In #2765 is het `dso-panel` geïmplementeerd met als vaste heading "Annotaties".

Het verzoek vanuit team Viewer Regels op de kaart is dat de vaste heading "Kenmerken en kaart" moet zijn.

**Comment by iterox** [comment]
Willen we deze nog langs de refinement hebben of zal ik hem asap oppakken, want lijkt me duidelijk, toch @tfrijsewijk ?

**Comment by tfrijsewijk** [comment]
panelHeading. Ik begrijp helemaal waar het vandaan komt, maar het bekt nog niet echt lekker.

De functionaliteit wat in de Panel komt te staan is toegespitst op het tonen van Annotaties. Dat zien we terug in code (property `annotated`, de naam van het event heet `dsoAnnotationToggle`, etc). De accessible name van de toggle button is overigens weer "Toelichting bekijken" (ondanks de open/close status?!).

De uitbreiding die wij hier technisch implementeren moet een UXer (@DjangoBlok @emosterd98) ook wat van vinden. Willen jullie samen naar de wens kijken?

**Comment by DjangoBlok** [comment]
Gisteren even met @tfrijsewijk besproken. Wat ons betreft prima om gewoon de tekst aan te passen naar "Kenmerken en kaart".
