### ISSUE TITLE
Modal: herevalueer gebruik reserved name `role` als property

### ISSUE THREAD

**Issue by iterox** [dso-toolkit/dso-toolkit#2799]
# Aanleiding

In #1988 zijn alle e2e-test voorzien van een accessibilty violations test middels de `checkA11y` functie van de plugin `cypress-axe`. Dit is geïmplementeerd via een custom cypress command `dsoCheckA11y`, waarbij ook gedetailleerde logging is geïmplementeerd. 

Daarin is de volgende accessibility violation op het web-component `dso-modal` aan het licht gekomen:

```
1 accessibility violation was detected
[
  {
    id: 'aria-dialog-name',
    impact: 'serious',
    description: 'Ensure every ARIA dialog and alertdialog node has an accessible name',
    nodes: 1
  }
]
```
Deze melding is overigens ook zichtbaar in de accessibility paneel van storybook:
<img width="875" alt="Screenshot 2024-09-13 at 14 14 17" src="https://github.com/user-attachments/assets/08f17a2e-3a40-42d2-a088-6cf73dfe5545">

# Wat is het geval?

Het component `modal` heeft een property `role`, dat een reserved member name is:

```typescript
/**
   * the role for the modal `dialog` | `alert` | `alertdialog`.
   */
  @Prop()
  // eslint-disable-next-line @stencil-community/reserved-member-names
  role: string | null = "dialog";
  ```
De property manifesteert zich als attribuut op het elemet `dso-modal`:

```html
<dso-modal role="dialog" modal-title="Disclaimer" class="hydrated">
```

Dit is wat de accessibility violation addresseert.

# Oplossing

In `modal.tsx` hernoem de property `role` en map de hernoemde property naar het attribuut role van het `dialog` element in de `render`-functie. Als dit gedaan is kan in `modal.cy.ts` in de test "should be accessible" de regel `cy.dsoCheckA11y("dso-modal.hydrated");` weer aangezet worden.

~~Door deze change is er geen conflict meer met `@stencil-community/reserved-member-names` en kan in `package.json` de `--max-warnings=4` worden bijgesteld naar 3.~~

**Comment by iterox** [comment]
role => dsoRole

**Comment by iterox** [comment]
Of misschien wel `componentRole`?

**Comment by tfrijsewijk** [comment]
> Of misschien wel `componentRole`?

Sorry, ik lees deze nu pas. Ik vind `componentRole` verwarrend.

* `dsoRole`: Dit past mooi in de eerdere conventies met nameconflicten (zoals dsoClick).
* `dialogRole`: Hiermee krijgt het attribuut een beetje semantische betekenis doordat we een klein stukje implementatie/doel ontsluiten: "Dit is de role voor het dialog [element in het component]".
