### ISSUE TITLE
Underline aanzetten bij standaard text links. 

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#280]
het besluit is genomen om de underline in links aan te zetten, en bij hover gaat deze uit. Er zijn een aantal factoren die hier voor gezorgd hebben. 

Namelijk de links in alerts boxes en de toelichten boxes. Door de verschillende kleur gebruiken van de boxes haalt de standaard niet het vereiste om alleen contrast te gebruiken als onderscheidend element: 

So if you combine these two requirements, in order to be Level AA conformant, your page must have all of the following:

A 4.5:1 contrast between the non-link text color and the background.
A 4.5:1 contrast between the link text color and the background.
A 3:1 contrast between the link text color and the surrounding non-link text color.

Dus waar de links op een witte achtergrond al deze voorwaarden halen is het bij een gekleurde achtergrond vrijwel onmogelijk om deze waardes te halen. 

Daarom moet voor text links de underline aangezet worden zodat elke link een onderscheidend element heeft behalve kleur ongeacht op welk kleurvlak deze stat. (kleur en contrast zijn niet hetzelfde, wcag erkent dit verschil). 

Ook wordt er nog gekeken naar de kleur stelling van de textlinks omdat het standaard grasgroen op de grijze achtergrond het minimaal contrast verschil niet haalt om leesbaarheid te garanderen. Dit probleem wordt opgepakt in issue #265

**Comment by tfrijsewijk** [comment]
Uitgekomen in 5.1.0:
* https://www.dso-toolkit.nl/5.1.0/components/detail/anchors.html
* https://www.dso-toolkit.nl/5.1.0/components/detail/anchor.html

**Comment by MichielDHVD** [comment]
Gezien en verplaatst naar done
