### ISSUE TITLE
Button Row: No block margin

### ISSUE THREAD

**Issue by hansgrimm** [dso-toolkit/dso-toolkit#2800]
https://dso-toolkit.slack.com/archives/CB417GQBC/p1726212291169449

![lines_buttons](https://github.com/user-attachments/assets/c2ded7b1-8068-44b9-8a28-c7dee3e418aa)

**Comment by iterox** [comment]
Dit is stuk gegaan in release 63.0.0

Vergelijk release 62.0.0

<img width="1276" alt="Screenshot 2024-09-27 at 10 21 56" src="https://github.com/user-attachments/assets/7ee4c395-f880-47b8-a11e-a601c4ae5eee">

met release 63.0.0

<img width="1282" alt="Screenshot 2024-09-27 at 10 22 06" src="https://github.com/user-attachments/assets/3dc6f4d6-f285-46ef-9d88-77519b8d004a">

**Comment by iterox** [comment]
De oorzaak zit hem in het ontbreken van de class `dso-form-group-collection` op de fieldset die boven de `dso-button-row` staat.

Ihkv #2741 zijn de markup voorschriften binnen een form aangepast. Deze Breaking aanpassing is wel doorgeveoerd in de voorbeeld-pagina Aanvragen Verzoeken, maar bijv. niet in de voorbeeld-pagina Aanvragen Activiteiten.

Actie: Verder onderzoeken of er meer voorbeeld-pagina's zijn waar deze markup voorschriften nog niet goed worden geëtaleerd.

**Comment by hansgrimm** [comment]
> De oorzaak zit hem in het ontbreken van de class `dso-form-group-collection` op de fieldset die boven de `dso-form-buttons` staat.
> 
> Ihkv #2741 zijn de markup voorschriften binnen een form aangepast. Deze Breaking aanpassing is wel doorgevoerd in de voorbeeld-pagina Aanvragen Verzoeken, maar bijv. niet in de voorbeeld-pagina Aanvragen Activiteiten.
> 
> Actie: Verder onderzoeken of er meer voorbeeld-pagina's zijn waar deze markup voorschriften nog niet goed worden geëtaleerd.

Hee, good catch!!

heb in #2800 de CSS-aanpassing verwijderd en de class op 2 fieldsets toegevoegd. de boel staat nu recht. Ik heb al met Sjoerd een afspraak staan voor aristo om te spieken hoe hun markup erbij staat.
