### ISSUE TITLE
Autosuggest: Onzichtbare suggestielijst blokkeert onderliggende elementen

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#2801]
In #2638 is de suggestielijst scrollable gemaakt. Echter, als de suggesties niet zichtbaar zijn is het `<dso-scrollable>` component nog steeds in het DOM aanwezig.

Dit is de Autosuggest "at rest":

![image](https://github.com/user-attachments/assets/722177c0-80ff-4dda-995b-f9f3633098f9)

Het element met de tekst `null` is een `<pre>` waar de gebruiker niet mee kan interactieren, bijvoorbeeld tekst selecteren:

![image](https://github.com/user-attachments/assets/2a4692ae-d648-4b94-adf7-c23e924281f2)

- [ ] Bug fixen: Als er geen suggesties moeten worden getoond, dan het `<dso-scrollable>` element niet renderen in het DOM.
- [ ] Bijvangst: uitzoeken waarom dit component geen shadow root heeft: In `autosuggest.tsx` in de decorator `scoped: true` vervangen met `shadow: true` en testen of dit nog goed werkt.

**Comment by hansgrimm** [comment]
@tfrijsewijk alles wat ik in autosuggest.tsx doe, resulteert in een oerwoud van foutmeldingen, maar in css is de grote-stappen-snel-thuis oplossing als volgt:
```scss

.listbox-container {
  inset-inline: 0;
  inset-block-start: 100%;
  block-size: auto;
  max-block-size: var(--max-block-size);
  min-block-size: core-autosuggest-variables.$listbox-min-block-size;
  overflow-y: auto;
  position: absolute;
  z-index: zindex.$autosuggest;

  &:not(:has([role="option"])) {
    display: none;
  }
}```
