### ISSUE TITLE
Mark Bar: Pointer on empty field button

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#2806]
<img width="454" alt="image" src="https://github.com/user-attachments/assets/7c5bf44e-bf2f-43a0-8b7b-28539dc9e32d">

Die button krijgt bij mouseover geen handje.

![image](https://github.com/user-attachments/assets/03f52e66-8df1-4079-8e5b-0c5208bf401f)

**Comment by hansgrimm** [comment]
Het is een button, dus geen handje "out of the box". Simpele ingreep (denk ik).

**Comment by hansgrimm** [comment]
@tfrijsewijk @DjangoBlok De up- en down buttons rechts hebben ook geen handjes. moet dat bij de enabled state niet ook meteen?

**Comment by tfrijsewijk** [comment]
Zoiets

```scss
@use "button.mixins" as "button-mixins";

@include button-mixins.element();
```
