### ISSUE TITLE
Ozon Content: Een Figuur zonder Titel of alt kan niet worden ingezoomd

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#2808]
# Bevinding

Als bij de volgende data het `<Titel>` element en het `alt` attribuut worden geleegd, is het niet mogelijk om de afbeelding in te zoomen:

```xml
<Inhoud xmlns="https://standaarden.overheid.nl/stop/imop/tekst/">
  <Figuur
    eId="chp_2__subchp_2.1__art_2.5__para_3__img_o_1"
    wId="gm9901_1fb2e118fb6343bba8f0f96f29e1ecdd__chp_2__subchp_2.1__art_2.5__para_3__img_o_1"
  >
    <Titel>titel</Titel>
    <Illustratie
      naam="https://pre.document-viewer-api.dso.kadaster.nl/ozon/presenteren/ontwerpafbeeldingen/gm9901/_akn_nl_bill_gm9901_2024_besluitf9bdc951546d4a4595aef99bdb33071a/Groen_a0701e6788cc48589746055425768349.png"
      breedte="419"
      hoogte="285"
      alt="alternatieve tekst"
    />
    <Bijschrift locatie="onder">
      Groen vlak, alleen bijschrift, rechts gepositioneerd
    </Bijschrift>
    <Bron></Bron>
  </Figuur>
</Inhoud>
```

# Reproductie

Reproduceerbaar op https://storybook.dso-toolkit.nl/64.0.0/?path=/story/core-ozon-content--figuur met een viewport die smal genoeg is dat de "zoom"-button in zicht komt. Plak bovenstaande markup in het "content" veld.

**Comment by iterox** [comment]
In `figuur.node.tsx` wordt de `nullish coalescing operator (??)` ingezet om het alt-attribuut van het `img`-element te zetten.

```
The nullish coalescing (??) operator is a logical operator that returns its right-hand side operand when its left-hand side operand is [null](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/null) or [undefined](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined), and otherwise returns its left-hand side operand.
```(https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing)

```tsx
alt={illustratie.alt ?? titel ?? illustratie.naam ?? undefined}
```
Echter, indien in de STOP XML het alt-attribuut van de Illustratie-node geleegd wordt, wordt `illustratie.alt` gelijk aan een lege string en aangezien een lege string niet null en niet undefined is wordt van de bovenstaande expressie met `nullish coalescing operator (??)` de meest linker operand geretourneerd.

In `image-overlay.tsx` r.32 wordt alt gebruikt als voorwaarde om het FunctionalComponent `Dimmer` te renderen.
