### ISSUE TITLE
Tooltip positioneren

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#281]
In bootstrap 4 is er de optie om de tooltip een richting mee te geven. Top right left en bottom. 

Volgens mij zit dit niet verwerkt in bootstrap 3.3.7. 

Maar er zijn scenarios waar het nodig is om de tooltip op een andere plek te laten verschijnen dan boven. 

Is dit makelijk over te nemen en dat we dan ook standaard bootstrap implementatie hanteren ? 

Tag even @TonD83 jij liep tegen dit issue aan.

**Comment by MichielDHVD** [comment]
Deze heb ik volgens mij per ongeluk gesloten op 21 februari. Maar we zijn benieuwd of deze standaard bootstrap implementatie niet gebruikt kan worden.

**Comment by TonD83** [comment]
Deze had ik even gemist...

@tfrijsewijk Zou je hier eens naar kunnen kijken? https://github.com/TonD83/dso-toolkit/commit/c2fb4ff36512677b11bc136b8097819287d3036a

Wat we (@MichielDHVD  en ik) graag willen is de mogelijkheid om de tooltip (en dus ook het pijltje) links, rechts, boven of onder de content te zetten. Bovendien het pijltje in het midden, omdat we anders tegen problemen aanlopen met lange tekst en een klein stukje content (icoontje bijvoorbeeld) dat het pijltje boven het verkeerde item staat. 

Zie ook:
<img width="361" alt="Screenshot 2019-04-04 at 10 50 13" src="https://user-images.githubusercontent.com/18580063/55543779-06dc6380-56ca-11e9-8010-6701b94458a7.png">
<img width="1149" alt="Screenshot 2019-04-04 at 11 04 23" src="https://user-images.githubusercontent.com/18580063/55543780-06dc6380-56ca-11e9-923a-de779488ac22.png">

@MichielDHVD Met Rick besproken, dit heeft voor ons grote prioriteit omdat momenteel de tooltips stuk zijn als we de huidige versie van toolkit gaan gebruiken (en dat gaan we). Dus dit zou z.s.m. moeten worden opgelost.

**Comment by tfrijsewijk** [comment]
@TonD83: Ziet er goed uit, mooi stukje code!

Zal ik dit verder administratief afwerken en uitbrengen in een release? Volgens mij is dit een compleet pakketje wat "af" is?

**Comment by tfrijsewijk** [comment]
Je hebt het container element van de toolkit uitgebreid met twee class modifiers `fade` en `in`

```html
<div class="tooltip {{ position }} fade in" role="tooltip">
```

Waar leeft de styling voor deze classes? Ik zie wel styling op `.in`, maar `.fade` nergens

**Comment by TonD83** [comment]
Wat ik in feite heb gedaan is een stuk van standaard bootstrap 3.3.7 overgenomen omdat ik er vanuit ging dat het een bewuste afweging was om _tooltip.scss uit bootstrap-sass niet te importeren in de dso-toolkit. Ik heb hier vervolgens een beetje in gesneden en kleine aanpassingen gedaan, maar de fade en in heb ik niet zelf verzonnen.

**Comment by tfrijsewijk** [comment]
Toen de tooltip nog niet-bootstrap markup was hebben we `_tooltip.scss` niet geimporteerd. Later is de bootstrap markup weer doorgevoerd maar hebben we met eigen styling het DSO design doorgezet.

Als jij liever alsnog `_tooltip.scss` wil importeren kunnen we dat doen. Maar wellicht ben je blijer met de oplossing zoals jij 'm nu aandraagt, we hoeven immers niet tegen te stijlen.

Ik neem aan dat je de positie van de tooltip scriptend bepaald. Kunnen we hier nog wat over zeggen in de notities van het component?

**Comment by TonD83** [comment]
@tfrijsewijk Ik duik hier vanmiddag weer even in en kom er dan gelijk bij je op terug, vrees dat ik het niet red voor onze standup en lunch etc :) 

Inderdaad, positie wordt scriptend bepaald, goed idee om hier een opmerking over op te nemen.

**Comment by TonD83** [comment]
De `.fade` is inderdaad standaard bootstrap en komt uit `bootstrap-sass/assets/stylesheets/bootstrap/component-animations`. Deze is echter wel optioneel, ik kan 'm dus ook uit de voorbeelden weglaten. Misschien beter om verwarring te voorkomen? 

Ik zal het vanmiddag even afstoffen allemaal en een seintje geven. Zou jij het daarna willen 'afmutsen' zoals je het zelf zo mooi noemt ;) ? Zou fantastisch zijn als dat nog deze sprint lukt.

**Comment by tfrijsewijk** [comment]
Zeker, dan zal ik het uitbrengen met #291

**Comment by MichielDHVD** [comment]
@TonD83 Met afmaken van deze sprint bedoel je dan dat je deze update nog kan toepassen voor aanstaande Sprint review demo? Huidige oplever momenten proberen we altijd op Maandag te houden. 

Ik neem aan dat voor deze story dat wel mogelijk moet zijn toch @tfrijsewijk ?

**Comment by TonD83** [comment]
@michieldhvd ik bedoelde inderdaad vandaag of morgen (gister had ook gemogen), zodat wij onze impediment alsnog kunnen oppakken.

**Comment by tfrijsewijk** [comment]
Ik zal vandaag een release uitbrengen. Wat mij betreft hoeven de releasedagen niet per-se op maandag te zijn. Semver is toch leidend in de naamgeving van de release

**Comment by tfrijsewijk** [comment]
Opgeleverd in 7.0.0: https://www.dso-toolkit.nl/7.0.0/components/detail/tooltip.html

@TonD83 Ik heb een paar kleine wijzigingen gedaan:
* CHANGELOG entry toegevoegd
* De config omgezet van .yml naar .js waardoor ik een custom collator kan toevoegen. Hiermee heb ik ervoor gezorgd dat elke tooltip in de demopagina een div met wat styling krijgt zodat de demo pagina iets duidelijker is
* De whitespace zorgde ervoor dat er een pixel anomaly kwam:
![image](https://user-images.githubusercontent.com/9696261/55876437-edd72500-5b97-11e9-9439-017b4e92ba1a.png)
Opgelost door met handlebars no-whitespace-operator (`~`) weggehaald waardoor de tekst op dezelfde regel als de `<div>` staat. Bij het resizen van mijn venster verdween het ook.

Zie ook: https://github.com/dso-toolkit/dso-toolkit/commit/f518ea8e70028e9c94a3fbad0836543d02b6fd03

**Comment by TonD83** [comment]
@tfrijsewijk Top, dank voor het snelle afhandelen!

**Comment by MichielDHVD** [comment]
Gezien en verplaatst naar done
