### ISSUE TITLE
Header engelse variant 

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#2810]
Header component heeft een term als inloggen in de header staan. Maar er moet ook de mogelijkheid zijn om van dat woordje een engelse variant te maken.  Dus dat er Login komt te staan.

**Comment by yktoo** [comment]
Het betreft niet alleen **Inloggen** maar in ieder geval ook **Uitloggen** en de **Meer**-knop; ik weet niet of de projecten-map (Mijn Omgevingsloket) hierbij ook speelt:
![image](https://github.com/user-attachments/assets/1a3c4700-3886-42ed-8e7f-c6951154a3ab)

**Comment by tfrijsewijk** [comment]
Dit issue pakken we op in #2830.

**Comment by yktoo** [comment]
@tfrijsewijk We hebben de meertaligheid niet kunnen gebruiken met 66.2.0, enig idee?
![image](https://github.com/user-attachments/assets/e9e7ced6-b5ab-4330-8998-5dfc24546041)
