### ISSUE TITLE
DSO Toolkit styling zorgt voor zeer hoog CPU gebruik

### ISSUE THREAD

**Issue by yktoo** [dso-toolkit/dso-toolkit#2813]
Zie het bijgevoegde statische HTML-bestand ([cpu.zip](https://github.com/user-attachments/files/17128921/cpu.zip)).

Vooral in Chrome zorgen de icoontjes (die de toolkit in `:before` of `:after` rendert) voor een zeer hoog gebruik, rond 40% op mijn machine voor de bovengenoemde simpele, statische HTML-pagina:

![image](https://github.com/user-attachments/assets/7e7e365b-1c7c-48c0-87fc-06cf72aaf1ab)

In Firefox is het wat minder (10-15%) maar toch aanzienlijk hoger dan aanvaardbaar:
![image](https://github.com/user-attachments/assets/447202fa-acf2-4821-be38-e47b0c28dbab)

En als ik die icoontjes in de Inspector uitzet dan gaat het CPU-gebruik naar 0%.

Dit is ook goed te zien op bijv. https://omgevingswet.overheid.nl/inloggen — daar komt het voornamelijk door de chevron-icoontjes naast footer-links.

**Comment by tfrijsewijk** [comment]
Heftig! We gaan er naar kijken, dank voor het onderzoek tot zover.

**Comment by tfrijsewijk** [comment]
Hoeveel cores heeft jouw CPU? Bij mij blijft volgens Chrome het geheugenverbruik rond ~20% hangen.

Verder is het mij opgevallen dat het CPU verbruik volgens windows task manager aanzienlijk lager ligt:

<img width="1746" alt="image" src="https://github.com/user-attachments/assets/bb4b54eb-a1b5-41c5-918a-8a4a85af6fc4">

Dat er "iets" op de achtergrond gebeurt is duidelijk, maar ik geef meer gewicht aan de statistieken van Windows Task Manager. Als ik in de inspector de icoontjes uitzet zakt de CPU usage in de Windows Task Manager voor het proces stabiel naar 0%.

Een andere constatering is dat het niet alleen voor de `:before: & `:after` selector het geval is. Jou static page heeft een `background-image` op een element:

<img width="335" alt="image" src="https://github.com/user-attachments/assets/1ed780b6-fee3-4e4c-9877-5b07a25565ec">

_Tussentijdse update, restant volgt_

**Comment by yktoo** [comment]
> Hoeveel cores heeft jouw CPU? Bij mij blijft volgens Chrome het geheugenverbruik rond ~20% hangen.

16 cores, 64 GB RAM

**Comment by tfrijsewijk** [comment]
Ik denk dat het door de SVG spritesheet komt: https://cdn.dso-toolkit.nl/dso-toolkit/64.0.0/dist/dso-icons.svg

Ik kan het lokaal reproduceren. Als ik de spritesheet compileer met 1 icon is het probleem weg:

<img width="1919" alt="image" src="https://github.com/user-attachments/assets/ef81d4e7-8450-41bd-9a0d-ceaf315ec290">

Het kan ook komen doordat er twee technieken in één spritesheet zitten. We maken gebruik van `<symbol>` voor `<svg class="di di-***"><use href="dso-icons.svg#***" /></svg>` en `<view>` voor `background-image: url(dso-icons.svg#img-***);`.

**Comment by tfrijsewijk** [comment]
cc @yktoo

**Comment by hansgrimm** [comment]
ben ook -gezien de kleinste impact- voorstander van optie 1.
- blijft de andere spritesheet dan ook gebruikt worden? lijkt er wel op. geeft dat nog hoge cpu, of wordt dat minder omdat je er 50 overzet naar de aparte sheet?
- als het hoge cpu-gebruik niet reproduceerbaar is, willen we dan wel ingrijpen?

**Comment by tfrijsewijk** [comment]
> * blijft de andere spritesheet dan ook gebruikt worden? lijkt er wel op. geeft dat nog hoge cpu, of wordt dat minder omdat je er 50 overzet naar de aparte sheet?

Er zijn dan twee spreadsheets:
* `dso-icons.svg`, alleen voor de HTML/CSS implementatie van Icon (`<svg class="di di-***"><use href="dso-icons.svg#***" /></svg>`)
* De andere spreadsheet, alleen voor de `di` mixins.

> * als het hoge cpu-gebruik niet reproduceerbaar is, willen we dan wel ingrijpen?

Het hoge CPU verbruik wat @yktoo meldt kan ik niet reproduceren, maar er is wel degelijk iets aan de hand. De CPU is op de achtergrond constant "iets" aan het doen. Hoe hoog het verbruik is lijkt ook van de omgeving (OS/architecture) af te hangen.

Het is evident dat we iets moeten. De bevinding die in dit issue wordt gemeld is een eigen bevinding (niet van een gebruiker). Ik stel voor dat we dit issue omdopen tot een research issue en het werk in een ander issue inplannen.

@yktoo: Merk je ook iets aan de performance van de DSO applicatie? Omdat dit ook impact heeft op het buildproces van de toolkit ben ik geneigd om dit in de laatste sprint van het jaar op te lossen. Wat denk jij daarvan?

**Comment by iterox** [comment]
Op mijm iMac
<img width="278" alt="Screenshot 2024-10-09 at 17 31 43" src="https://github.com/user-attachments/assets/5c4fa386-727e-4595-aa92-99ccc30977a1">

ziet het er zzo uit:

<img width="1089" alt="Screenshot 2024-10-09 at 16 56 17" src="https://github.com/user-attachments/assets/2c0a9051-37bc-40b0-8155-b452417a7b7f">

**Comment by iterox** [comment]
Na de voortreffelijk uitleg van @tfrijsewijk is Optie 1 de meeste gain met de minste impact. Optie 1 dus.

**Comment by tfrijsewijk** [comment]
Zie #2844 voor het vervolg. Dank voor jullie input!
