### ISSUE TITLE
Card: Block-end spacing too small

### ISSUE THREAD

**Issue by MYpenburg** [dso-toolkit/dso-toolkit#2818]
Kijk maar:
<img width="562" alt="image" src="https://github.com/user-attachments/assets/c10288e5-bc76-4bb9-9ce2-cace3d821504">

<img width="1632" alt="image" src="https://github.com/user-attachments/assets/53d179cd-c84c-4512-8922-c87a74e8620c">

Gewenste marge: 24 px

<img width="916" alt="image" src="https://github.com/user-attachments/assets/1507efaf-57c6-4563-a438-a3b1df319fad">

**Comment by tfrijsewijk** [comment]
Ik denk dat we deze change het beste kunnen meepakken in #2797. @hansgrimm @iterox wat jullie?

**Comment by hansgrimm** [comment]
@MYpenburg de padding onderin de card is opgehoogd naar 1rem(16px), gelijk aan de andere 3 zijden, volgens Django's oorspronkelijke ontwerp. 
Oorzaken van jouw bug:
- de padding onderin was slechts 0.5rem(8px) omdat ten onrechte rekening werd gehouden met een collapsing margin van 8px die hing aan een paragraaf die in het rich content veld stond.
- de button row had geen margin, dus die stond te dicht tegen de rand vanwege de padding van slechts 8px.
Remedie:
- collapsing margin verwijderd, en
- de padding onderin opgehoogd naar 16px.
