### ISSUE TITLE
Viewer Grid: Button styling broken

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#2822]
# Bug

<img width="1199" alt="image" src="https://github.com/user-attachments/assets/01bf5448-2e31-4d89-804d-23c982daa107">

De sizing buttons in Viewer Grid zijn sinds #2724 stil.

# Analyze

De `& {}` selector heeft ervoor gezorgd dat groepen properties in een andere volgorde staan:

<img width="1092" alt="image" src="https://github.com/user-attachments/assets/eccc1e27-d4dc-42a0-a361-bb6bc9a5c1c1">

Daarnaast hebben we een aantal knoppen voorzien van "basis styling" die we VOLLEDIG overstijlen.

**Comment by hansgrimm** [comment]
Button.mixins.scss

3 - r32
1 - r24 mixin base r161
2 - r28 mixin shared-variant r14
4 - ?

**Comment by hansgrimm** [comment]
@tfrijsewijk volgens mij heb ik 'm gefixt. Briljante ingeving icm een flesje cola zero.

**Comment by tfrijsewijk** [comment]
# Onderzoek oorzaak

In #2724 is de styling aangepast die deze bug heeft geintroduceerd. De primaire regressietest van de toolkit zijn de visuele regressietesten. Deze visuele bug is door de mazen van het net geglipt omdat deze situatie niet werd getest. Er werd één screenshot gemaakt, maar dat was met de overlay open waardoor de button niet zichtbaar was:

![Viewer Grid -- should show overlay snap](https://github.com/user-attachments/assets/2ce43289-4413-4cda-80e9-7ae03142f082)

In #1988 heeft @iterox de vrijheid genomen om ook een visuele regressietest toe te voegen zonder overlay:

![Viewer Grid -- should not show overlay snap](https://github.com/user-attachments/assets/43530675-42c8-4b37-8e8a-262e9777177f)

Echter, omdat dit screenshot als "nieuw" werd toegevoegd is zoals gebruikelijk niet gekeken of het screenshot er goed uitzag maar is aangenomen dat het de gewenste situatie was.

In het PR wat bij dit issue hoort zijn dus geen extra voorzorgmaatregelen getroffen: De testdekking is voor deze situatie op orde en het referentiescreenshot is aangepast.
