### ISSUE TITLE
Map Controls: Info no background color

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#2829]
<img width="417" alt="image" src="https://github.com/user-attachments/assets/cd1c5eb3-0b0a-40b4-9706-3d855f0f7b14">

Ik vermoed dat dit stuk is gegaan bij het implementeren bij `@mixin set-colors()`.

**Comment by hansgrimm** [comment]
@tfrijsewijk waar zit die specifieke view in storybook? ik zie wel iets dat er vaag op lijkt, maar niet dit ^. thanks!

**Comment by hansgrimm** [comment]
In 62.10.0 was het nog OK, in 62.11.0-ghi-2525.0 ging het stuk.
