### ISSUE TITLE
Document Card: Aanvullende functionaliteit

### ISSUE THREAD

**Issue by iterox** [dso-toolkit/dso-toolkit#2835]
In https://github.com/dso-toolkit/dso-toolkit/issues/2797 heeft het webcomponent `Document Card` het levenslicht gezien. Tijdens de gecombineerd UX- en Dev-review met @DjangoBlok en @emosterd98 en een drietal developers van het viewerteam is geconstateerd dat dat er functionaliteit ontbrak in het initiële ontwerp van de `Document Card'. Deze gaan we met dit issue alsnog realiseren.

1. Optioneel 1 of 2 Badge’s met Tooltip plaatsen achter status
2. Responsive ontwerpen tbv smallere weergaven
3. Optioneel label wordt inline weergegeven met de titel. (mag op een nieuwe regel beginnen)

Ontwerpen volgen

**Comment by DjangoBlok** [comment]
Twee ontbrekende functionaliteiten in het ontwerp toegevoegd
![Document-card](https://github.com/user-attachments/assets/f255544a-4d15-4cc4-84a4-884483441c48)

**Comment by iterox** [comment]
@DjangoBlok gaat het juiste design nog bijvoegen.

**Comment by DjangoBlok** [comment]
@iterox Gedaan

**Comment by tfrijsewijk** [comment]
Ik heb geen idee 🤷 Volgens de history issie niet uit Specification gegaan. Maar ik zet 'm terug naar refinement

**Comment by cvanderleij-ilionx** [comment]
Tip van flip (aka Eric) Een badge is niet toegankelijk en kan niet opgefocused worden. Is het een idee om de info-button te gebruiken en daar het icoon configureerbaar te maken?
