### ISSUE TITLE
Document Component: Renvooiweergave kenmerken paneel

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#2836]
Nu is de achtergrondkleur transparant, wat er voor zorgt bij toegevoegd of verwijderde Document Componenten:

![image](https://github.com/user-attachments/assets/2756bf96-b00a-4a43-8db2-d8c26cbbf047)

### Gewenste oplossing:
**Kenmerken paneel bij toegevoegd artikel**
- vulling titelbalk : grijs-10 
- titel en sluitenkruis: zwart
- stroke color van het paneel: grijs-30
- vulling paneel: lime-10 (#F2F8EA)
![Artikel toegevoegd](https://github.com/user-attachments/assets/9a205027-98cb-4930-852b-fd74f6651664)

**Kenmerken paneel bij verwijderd artikel**
- vulling titelbalk : grijs-10 
- titel en sluitenkruis: zwart
- stroke color van het paneel: grijs-30
- vulling paneel: rood-10 (#FAECEE)
- alleen de waardes worden doorgehaald, niet de labels (in dit plaatjes zijn de doorhalingen niet correct weergegeven)
![Artikel verwijderd](https://github.com/user-attachments/assets/4f43a7ff-333b-4979-a413-2509bd8cc7e2)

**Comment by tfrijsewijk** [comment]
Of is het beter om de achtergrondkleur vanuit Document Component op Panel te zetten?

**Comment by tfrijsewijk** [comment]
Er is onduidelijkheid over de gewenste situatie, we wachten even

**Comment by DjangoBlok** [comment]
@tfrijsewijk Ik heb een voorstel bijgevoegd.

**Comment by tfrijsewijk** [comment]
Ziet er goed uit. Ik denk dat dit volledig vanuit de toolkit wordt geregeld.
