### ISSUE TITLE
core / tabs: extra tab stop op inhoud verwijderen

### ISSUE THREAD

**Issue by timveld** [dso-toolkit/dso-toolkit#2837]
### Waar
core / tabs (zowel as anchors als as buttons)
### Aanleiding
Pr12  heeft tabs geïmplementeerd. Bij testen bleek dat er een tab stop op de inhoud van de tab zit, met als gevolg dat bij tabben tussen tab strip en het eerste component in de tab een keer extra op tab moet worden gedrukt en de hele inhoud van het tabblad wordt voorgelezen.

In sommige modals zit ook een tab stop op de inhoud, maar dat kan noodzakelijk zijn om text-only inhoud scrollbaar te maken. Zelfs als text-only inhoud op tabs voorkomt (lijkt me geen goed ontwerp) is die volgens mij zonder tab stop perfect scrollbaar, dus de extra tab stop heeft geen functie; schrappen dus.

### Werkzaamheden

Extra tab stop verwijderen

### Gebruikersimpact

Hinderlijk: een screen reader gebruiker die niet ziet dat de hele inhoud gefocust is en deze inhoud voorgelezen krijgt, kan denken dat hij al in het eerste focusbare component zit en moeite hebben te concluderen dat hij een keer extra op tab moet drukken. Niet blokkerend maar wel verwarrend.

**Comment by tfrijsewijk** [comment]
Ik begrijp wat je zegt. Bij deze de onderbouwing van de huidige implementatie:

We zijn ons bewust van de afweging bij `tabindex="0"` op panelen zoals een tabpanel of Modal. Dit staat in relatie met een focusbaar element _in_ de container.

We baseren ons met name op het volgende:

> To make it easy for screen reader users to navigate from a tab to the beginning of content in the active tabpanel, the tabpanel element has tabindex="0" to include the panel in the page Tab sequence. It is recommended that all tabpanel elements in a tab set are focusable if there are any panels in the set that contain content where the first element in the panel is not focusable.

_(https://www.w3.org/WAI/ARIA/apg/patterns/tabs/examples/tabs-automatic/)_

De tweede zin geeft aan dat het aan te raden is om _alle_ tabpanels van `tabindex="0"` te voorzien, als er tenminste één tabpanel een focusbaar element heeft. Dit kunnen we omdraaien: Pas als ALLE tabpanels géén focusbare elementen bevatten hebben de tabpanels geen `tabindex="0"`.

Omdat dit "aan te raden is" heb ik het geinterpreteerd als "niet-verplicht" en het technisch een uitdaging is om te bepalen of tabpanel focusbare inhoud heeft (niet alle content is beschikbaar, asynchroniteit), heb ik meer gewicht gegeven aan een consistente interface: namelijk altijd focusbare tabpanels.

Stel je het volgende voor: Bij het inladen van de applicatie worden er 4 tabs getoond waar de eerste actief is. Alleen voor het actieve tab wordt de inhoud opgehaald. De eerste tab heeft focusbare inhoud. Het is onbekend of de overige 3 tabs focusbare elementen hebben.

De gebruiker selecteert het tweede tab en daar blijkt geen focusbare inhoud in te zitten. Moeten alle tabpanels daarmee focusbaar worden? Dan verandert te interface. Dat lijkt mij ongewenst.

Een ander scenario: Er zijn twee instanties van Tabs, bijvoorbeeld naast elkaar (of onder elkaar).

De ene heeft op elke tab geen interactieve elementen, de andere wel. Visueel en functioneel zijn de twee instanties Tabs identiek aan elkaar. Ik denk dat het verwarrend is dat de ene instantie wel focusbare tabpanels heeft en de andere niet.

Wat zijn jouw gedachten?

**Comment by tfrijsewijk** [comment]
Dit issue sluiten we. Ik ben nog steeds overtuigd van de huidige implementatie.

**Comment by timveld** [comment]
@tfrijsewijk Ik blijf de tab stop overbodig en verwarrend vinden, maar begrijp ook de complicaties rond wel / geen interactieve content en consistentie met de vergelijkbare situatie van modals. Ik kan er dus mee leven, maar zet dit issue wel op de checklist voor mijn opvolger en zal het vanuit de DSO-hemel met belangstelling volgen.

**Comment by timveld** [comment]
@tfrijsewijk @DjangoBlok @MYpenburg @MarjonBakker  inmiddels is de extra tab stop in regels op de kaart en vergunningcheck een realiteit en dat blijkt problematischer dan wellicht gedacht.  Een [video waarin ik laat horen wat het effect is](https://.www.blindmobility.eu/extratabstoptk.mp4)

**Comment by timveld** [comment]
@tfrijsewijk  @MarjonBakker @MYpenburg @DjangoBlok  Ik probeerde de vergunningcheck met VoiceOver op mijn iPhone te doen, dat lukte niet; de adres autocomplete in stap 1 geeft dan geen tekstinvoermogelijkheid. De autocomplete in Storybook werkt prima, dus het lijkt er op dat VoiceOver de focus op de tab IPV de autocomplete zet. Kritieke bevinding (gebruiker loopt vast)!

**Comment by tfrijsewijk** [comment]
> [@tfrijsewijk](https://github.com/tfrijsewijk) [@MarjonBakker](https://github.com/MarjonBakker) [@MYpenburg](https://github.com/MYpenburg) [@DjangoBlok](https://github.com/DjangoBlok) Ik probeerde de vergunningcheck met VoiceOver op mijn iPhone te doen, dat lukte niet; de adres autocomplete in stap 1 geeft dan geen tekstinvoermogelijkheid. De autocomplete in Storybook werkt prima, dus het lijkt er op dat VoiceOver de focus op de tab IPV de autocomplete zet. Kritieke bevinding (gebruiker loopt vast)!

Hi Tim, mobiel gebruik is buiten de scope van het DSO-LV geplaatst.
