### ISSUE TITLE
Anchor visited state in .alert en .highlightbox naar tekstkleur

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#285]
Zojuist gespot dat de visited states paars worden, had bij het controleren vergeten er op te controleren. 

Deze paars kleur haalt vaak de contrast waardes niet. Mijn voorstel is dat de visited state ook op zwart wordt gezet. 

Normaal ben ik voor visited states maar omdat deze link alleen in alerts / boxes voorkomt is het vaak de enigste link in een stuk tekst. Plus voor elke andere alert een kleur verzinnen creeert ook een chaotische en niet consistent gebruikerspatroon. Daarom de visited link keur op zwart zetten

**Comment by tfrijsewijk** [comment]
Opgeleverd in 6.0.0

**Comment by MichielDHVD** [comment]
Gezien en verplaatst naar done
