### ISSUE TITLE
Uitbreiding kaart: disabled mode (zonder gebruikersinteractie)

### ISSUE THREAD

**Issue by MYpenburg** [dso-toolkit/dso-toolkit#2855]
Op deze plek zouden we alleen een kaartje willen tonen zonder knoppen en zonder verdere gebruikersinteractie (pannen/zoomen via muis etc). 
Hangt aan https://jira.team-dso.nl/jira/browse/PR12-25253

![image](https://github.com/user-attachments/assets/c35a74fb-30bb-42fc-94af-6f0302b16886)

**Comment by tfrijsewijk** [comment]
@MYpenburg Hi Martin, deze is van mijn radar gevallen

Dit is geen feature, het is al mogelijk. Als er geen Map Controls nodig zijn, kan het hele `<dso-map-controls>` element uit het DOM worden verwijderd.
