### ISSUE TITLE
Anchor text-decoration: underline scopen tot .alert, .highlight-box, .dso-rich-content, en .dso-info

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#286]
In issue #264 is geconstateerd dat er een underline is geplaatst in de links die in een white box staan. 

Deze moet verwijderd worden. De whitebox dient in zijn geheel als een soort link.

**Comment by MichielDHVD** [comment]
Nu is ook gebleken dat bij andere onderdelen dit van toepassing is de volgende zijn eerste constateringen:

https://dso-toolkit.nl/5.1.0/components/detail/pagination.html
https://dso-toolkit.nl/5.1.0/components/detail/pager.html
https://dso-toolkit.nl/5.1.0/components/detail/navs.html

Ik ga morgen alle componenten nalopen kijken of er meer zijn. Maar voor deze componenten is deze situatie niet wenselijk.

**Comment by tfrijsewijk** [comment]
Zal ik de scoping strenger maken? Alleen anchors in lopende tekst (`.dso-rich-content`) krijgen underline. Anchors die niet in lopende tekst gebruikt worden EN die niet WCAG-compliant zijn moeten dan op een andere manier WCAG-compliant worden

**Comment by MichielDHVD** [comment]
Goed idee. Zet maar door!

**Comment by tfrijsewijk** [comment]
De underline is in #265 gemaakt. De scope is niet `.dso-rich-content`, maar juist de bestelde componenten: `.alert` en `.highlight-box`.

Ofwel: Strakker gescoped op de originele wens

**Comment by tfrijsewijk** [comment]
Opgeleverd in 6.0.0

**Comment by MichielDHVD** [comment]
gezien en verplaatst naar done
