### ISSUE TITLE
Kleur succes-icoon aanpassen naar #79b929

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#288]

**Comment by tfrijsewijk** [comment]
@MichielDHVD: In #284 is doorgegeven dat de kleur van het succes icoon aangepast moet woren van `#39870C` naar `#79b929`, maar als ik zoek op de 79b929 krijg ik op heel veel plekken nog deze oude kleurcode door:

![image](https://user-images.githubusercontent.com/9696261/54816293-3172f900-4c94-11e9-8956-a3bdf67d1e7e.png)

Kloppen deze kleuren wel?

**Comment by tfrijsewijk** [comment]
Opgeleverd in 6.0.0: https://www.dso-toolkit.nl/6.0.0/components/detail/alert.html

**Comment by MichielDHVD** [comment]
Gezien en verplaatst naar done
