### ISSUE TITLE
I18n: Werkt niet in Angular app

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#2880]
# Aanleiding

Dmitry geeft aan dat de automatische Engelse vertaling beleving suboptimaal is: deze werkt namelijk niet.

https://github.com/dso-toolkit/dso-toolkit/issues/2810#issuecomment-2472773945

# Onderzoek

Het lijkt erop alsof de Storybook Angular een andere component lifecycle aanhoudt dan een Angular App.

Bij het initialiseren van een Angular Component in een kale Angular App is het bijbehorende Web Component nog niet in het DOM gemount waardoor er geen DOM is om te inspecteren voor het `lang` attribuut.

In Storybook Angular werkt dit prima.

# Bijvangst

~~"Mijn Omgevingsloket" (userHome) is niet vertaald naar Engels: https://github.com/dso-toolkit/dso-toolkit/blob/v66.2.0/packages/core/src/components/header/header.i18n.ts#L11~~

Blijkt bewust niet te zijn vertaald, aangezien dit niet van toepassing is in SDG. Ik vraag me af of dit de juiste weg is, maar dat is een andere discussie.

**Comment by iterox** [comment]
Staat SDG voor Single Digital Gateway? Valt Get in Touch daaronder?

**Comment by tfrijsewijk** [comment]
> Staat SDG voor Single Digital Gateway? Valt Get in Touch daaronder?

Ja, dat klopt
