### ISSUE TITLE
.dso-info als status-indicator in .dso-accordion krijgt onterecht achtergrondkleur

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#289]
De achtergrond kleur komt van het Informatie component `.dso-info`. `.dso-info` wordt ook als status indicator gebruikt in de accordion.

**Comment by tfrijsewijk** [comment]
Uitgekomen in 6.0.1: https://www.dso-toolkit.nl/6.0.1/components/detail/accordion.html

https://percy.io/dso-toolkit/dso-toolkit/builds/1644577

**Comment by MichielDHVD** [comment]
Gezien en verplaatst naar done
