### ISSUE TITLE
Accordion: Html-css compact black broken

### ISSUE THREAD

**Issue by cvanderleij-ilionx** [dso-toolkit/dso-toolkit#2901]
<img width="602" alt="Screenshot 2024-11-26 at 13 29 32" src="https://github.com/user-attachments/assets/eb193f3c-6612-49ba-9a17-b2cac5cc7d33">

**Comment by iterox** [comment]
In #2214 heeft de varaint compact-black het levenslicht gezien.
De bij #2214 PR is #2233
