### ISSUE TITLE
Margins van geneste paragraph in Conclusie component niet helemaal lekker.

### ISSUE THREAD

**Issue by TonD83** [dso-toolkit/dso-toolkit#295]
De marges van een p genest in dso-conclusion hebben niet de gewenste waardes, dit kwam aan het licht nadat wij een issue hebben opgepakt om links in het voorbehoud te ondersteunen en onze markdown parser een extra p'tje toevoegt.

Zie: ![image](https://user-images.githubusercontent.com/18580063/56033706-67504e00-5d25-11e9-8a8e-f8314ebb68a2.png)

Zie: https://github.com/dso-toolkit/dso-toolkit/pull/294

**Comment by tfrijsewijk** [comment]
Uitgekomen in 7.0.1

**Comment by MichielDHVD** [comment]
Gezien en verplaatst naar done
