### ISSUE TITLE
Header margin-bottom naar 8px

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#297]
De header heeft op dit moment een `margin-bottom` van 40px. Deze afstand in combinatie met de ruimte gecreeerd door de `margin-top` van een `h1` zorgt voor extreem veel witruimte. Wat niet nodig is. 

<img width="1182" alt="Screen Shot 2019-04-24 at 12 17 43" src="https://user-images.githubusercontent.com/36912722/56652463-be421580-668b-11e9-8dcf-915a229474e5.png">

Het principe van pagina ontwerp moet zo zijn dat er vrijwel altijd een `h1` is. Dit vanwege accessibility en common practice. Dit zorgt ervoor dat de ruimte tussen `header` en `h1` altijd in balans zal zijn. 

De aanpassing moet zijn dat de header ipv een `margin-bottom` van 40px naar een `margin-bottom` van 8px gaat.

**Comment by tfrijsewijk** [comment]
Het eerste punt is natuurlijk geen probleem (header margin-bottom 40px naar 8px).

Maar dat tweede punt is nog wel een stukje lastiger. De border zit namelijk op `.dso-navbar` en deze zit in `header`. Als ik de header breder maak zodat `.dso-navbar` ruimte heeft wordt de hele header ontwricht.

Ik kan hetzelfde truukje uithalen als bij de footer:
* Ik zet de border op het `header` element.
* De border loopt van rand tot rand

Echter: Onder `.dso-navbar` kan een kruimelpad staan. Zoals het nu is opgebouwd staat het kruimelpad onder de border. Als de border van `.dso-navbar` naar `header` gaat staat het kruimelpad _boven_ de border. Is dit erg?

Tot nu toe zijn het non-breaking changes. Als het wel een probleem is moeten we verder kijken.

**Comment by tfrijsewijk** [comment]
In overleg met @MichielDHVD is het tweede punt out-of-scope. Dit wordt in een nieuwe issue opgepakt

**Comment by tfrijsewijk** [comment]
Opgeleverd in 7.1.0
