### ISSUE TITLE
Expliciete zoek knop bij zoekbalken

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#298]
Er is meerdere keren terug gekomen uit gebruikers evaluatie dat de huidige zoekbalk niet toereikend is. Er moet een expliciete zoek knop komen. 

Hierdoor zijn er al door verschillende teams en portalen/websites variaties op de zoekbalk gemaakt. 

![Slide3](https://user-images.githubusercontent.com/36912722/56654474-72de3600-6690-11e9-841c-54bb34247c71.jpg)

Dit is het ontwerp voor de nieuwe zoekknop. 

![Zoeken knop](https://user-images.githubusercontent.com/36912722/56654881-7d4cff80-6691-11e9-88f6-88f7d23a11a7.png)

Focus gedrag mag standaard browser interpretatie zijn. De focus states voor de gehele toolkit worden onder ogen genomen.

**Comment by tfrijsewijk** [comment]
Wil je niet liever een zoekformulier component? Hoe breed wordt de input?

**Comment by PieterVerheij** [comment]
Ik denk niet dat er een vaste breedte te bepalen is. Ik zou de breedte van het hele component laten afhangen van de breedte van de omliggende container (bv. breedte content vlak). Breedte van het text input veld is dan de breedte van die container minus de knop minus de marge van 8px. Met `display: flex` valt er wel wat te klussen.
Een opmerking: op mobiel is de zoeken knop aan de brede kant. Misschien dan een zoekloepje in de tekst ipv 'Zoeken'?

**Comment by PieterVerheij** [comment]
Protootje: https://codepen.io/pieterverheij/pen/gJpPvr?editors=1111

**Comment by MichielDHVD** [comment]
Ik ben het eens met het voorstel van @PieterVerheij om de breed van het input veld de breedte van de container te geven minus knop en marge. 

Voor mobiel het zoekloepje gebruiken lijkt me een prima oplossing.

**Comment by MichielDHVD** [comment]
Kan deze nu doorgevoerd worden. Of wordt deze nog geblokkeerd op dit moment.

**Comment by bramhoosemans** [comment]
Hey allen, 

Ik heb nog een toevoeging voor de zoekbalk. Naast de optionele zoekknop zijn er nog een aantal gewenste aanpassingen, namelijk:

- Geen animatie of verschil tussen open/close zoekbalk
- Flexibele breedte van de zoekbalk
- Loep icoon vast links in het zoekveld
- Bij invoer een 'wis knop' tonen doormiddel van een kruisje rechts in het zoekveld

De vraag is of dit direct meegenomen kan worden in deze 'story' of dat hier een apart issue voor geopend moet worden?

Implementatie voor PR12 staat gepland in sprint 3 (23 juli); gaat dat lukken?

<img width="1261" alt="Schermafbeelding 2019-07-02 om 09 23 45" src="https://user-images.githubusercontent.com/598735/60495021-465a2200-9cb0-11e9-963d-76aa1683bd53.png">

Ontwerp specificaties: [Zoekbalk.zip](https://github.com/dso-toolkit/dso-toolkit/files/3348938/Zoekbalk.zip)

**Comment by bramhoosemans** [comment]
@tfrijsewijk Even voor de zekerheid: worden bovenstaande wijzigingen ook meegenomen in het component?

**Comment by tfrijsewijk** [comment]
Uitgekomen in 8.0.0: https://dso-toolkit.nl/8.0.0/components/detail/search-bar.html

Dit betreft een breaking change

**Comment by bramhoosemans** [comment]
Nog een paar opmerkingen:
- De placeholder tekst ziet er zwaarder uit dan andere invulvelden, dit mag zijn #A8BCAF.
- Er wordt nu een primary button achter het veld gezet, dit mag een default button worden.
- De kleine button is nu enkel gedefineerd binnen dit component. Zouden we hier geen algemene button stijl van moeten maken? Dan kan een kleine button ook op andere plekken worden ingezet.
- Volgens mij gaat de scholing van de kleine button nog niet helemaal goed: zie screenshot.

<img width="484" alt="Schermafbeelding 2019-07-23 om 11 55 43" src="https://user-images.githubusercontent.com/598735/61703304-97a28200-ad41-11e9-8bd6-57c96bc5f769.png">

**Comment by tfrijsewijk** [comment]
Placeholder: Geldt dit voor elke tekstveld?

Primary/default button: Helder, ik heb niet goed naar het ontwerp gekeken

Kleine button: Zeker, hoe zie je dit voor je? We kunnen met de bootstrap `btn-sm` classmodifiers aan de slag, volgens mij doen deze nu niets.. Anderzijds kan ik er een mixin van maken, mocht er een ander component worden besteld waar een kleine button in zit is het een kwestie van aanroepen. Dan is de styling alsnog gecentraliseerd.

Gaat deze kleinere button ook op andere plekken gebruikt worden?

Schaling: gaat helemaal niet goed zelfs. Wordt gefixed

**Comment by bramhoosemans** [comment]
Placeholder: ja, zo staat het ook al in https://dso-toolkit.nl/8.0.0/components/detail/group-input.html

Kleine button: ik zal nagaan of deze gebruikt gaat worden op andere locaties. De keuze of het met bootstrap btn-sm of een mixin wordt gestyled kan ik niet maken, maar ben altijd voorstander van gecentraliseerde styling :)

**Comment by PieterVerheij** [comment]
Hoe zien jullie die kleine button voor je? Dat de padding minder wordt, of dat het op smalle viewports een knopje zonder tekst maar met een loepje wordt?

**Comment by bramhoosemans** [comment]
Hi Pieter,

Het enige verschil met de standaard button is de padding boven en onder (8px ipv 12px). Ik zou verwachten dat de padding vast staat en niet kleiner wordt op smalle viewports.

De zoekknop vervangen naar een loepje is niet nodig (dit zou dan ook dubbel zijn met het zoekveld).

<img width="272" alt="Schermafbeelding 2019-07-25 om 12 51 19" src="https://user-images.githubusercontent.com/598735/61869012-f2bbac80-aeda-11e9-936d-afd2eef124b7.png">
