### ISSUE TITLE
Underline bij hover op anchor

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#299]
Als er in een table een link geplaatst moet worden is er op een hover geen underline. Dit zou wel moeten. 

![Hover in table](https://user-images.githubusercontent.com/36912722/56804649-c8e4e200-6826-11e9-974f-58f3e938e15e.jpg)

**Comment by tfrijsewijk** [comment]
Opgeleverd in 7.1.0
