### ISSUE TITLE
Accordeon chevron wordt nog steeds kleiner op hover. 

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#303]
Er was een issue waarin de chevron op hover kleiner werd. Deze bug zou zijn opgelost. 
Maar deze komt nog steeds terug zien wij terwijl de laatste versie van de toolkit is geimplementeerd. 

<img width="1432" alt="Screen Shot 2019-05-03 at 10 11 45" src="https://user-images.githubusercontent.com/36912722/57126349-fd0f5400-6d8c-11e9-94e8-f66c1c610ecb.png">

Dit is reproduceerbaar op de link https://int.omgevingswet.overheid.nl/checken (Moet je wel een certificaat hebben, ik neem aan dat er wel iemand is bij infoprojects die toegang heeft tot de int. ) 
Er moet een locatie geselecteerd worden en een activiteit. Er kan gezocht worden op bouwen en een selectie gemaakt worden. Vervolgens kun je op volgende drukken totdat je bij stap 3 activiteiten komt en daar staat een accordeon waar dit probleem voorkomt.

**Comment by PieterVerheij** [comment]
@MichielDHVD Wij kunnen er niet bij, ik heb een rondje gedaan maar niemand heeft een certificaat. Kan jij toegang regelen, of misschien de situatie nabouwen op een plek waar wij wel bij kunnen?

**Comment by MichielDHVD** [comment]
Ik zal eens gaan kijken hoe we dit kunnen regelen. Lijkt me wel slim dat Info Projects toegang heeft to de int-omgeving

**Comment by PieterVerheij** [comment]
Graag. ;)

**Comment by PieterVerheij** [comment]
@MichielDHVD Enige voortgang? Ik sta te trappelen om het op te lossen ;)

**Comment by MichielDHVD** [comment]
Ik ben er nog mee bezig. Hopelijk kan ik vandaag al iets meer van een antwoord geven.

**Comment by PieterVerheij** [comment]
@MichielDHVD  Tumtiedumtiedum ;)

**Comment by MichielDHVD** [comment]
Nou ik kan je het probleem presenteren. (We hoeven niet meer naar de int omgeving. Want het certificaat aanvragen was een flinke onderneming. Ik moest OIN-nummers gaan gebruiken etc.) Maar dat is dus nu niet meer nodig. 

Op https://pre.omgevingswet.overheid.nl/checken is het probleem nu ook waar te nemen.

Je kan een willekeurige locatie aan klikken. 
Bij zoeken werkzaamheid type dan bouwen
Vink alle drie de opties aan. 

dan heb je als het goed is de volgende 3 opties: 

Brug of andere overkluizing over een watergang plaatsen

Dakkapel bouwen

Dakterras aanleggen


Klik dan op volgende. Dan kom je als het goed is bij stap 3 en dan zie je de accordeon. Waar de hover nog niet werkt zoals het hoort.

**Comment by PieterVerheij** [comment]
Ik kan geen andere conclusie trekken dan dat er daar toch een oudere versie van de toolkit staat.

Dit is de svg aanroep op https://pre.omgevingswet.overheid.nl/checken, waar het plaatje 12x12 is: 
data:image/svg+xml;charset=utf8,%3Csvg width='**12**' height='**12**' viewBox='0 0 **12 12**' xmlns='http://www.w3.org/2000/svg'%3E%3Ctitle%3EButton-Icon/Chevron-Up_**12x12**%3C/title%3E%3Cpath d='M1 8l5-5 5 5' stroke='%23e17000' stroke-width='2' fill='none' fill-rule='evenodd' stroke-linecap='round' stroke-linejoin='round'/%3E%3C/svg%3E

Dit is de svg aanroep in de toolkit, 
data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 **16 16**'%3E%3Cpath fill='none' stroke='%23e17000' stroke-width='2.66' stroke-linecap='round' stroke-linejoin='round' d='M1.3 10.6L8 4l6.6 6.6'/%3E%3C/svg%3E

**Comment by TonD83** [comment]
@MichielDHVD @PieterVerheij  Op de PRE omgeving staat inderdaad een versie van 18 maart, dus dat is ongetwijfeld een oude versie van de toolkit. Desalniettemin treedt het toch echt nog steeds op in versie 7.2.0. Even wachten tot er een nieuwe versie op PRE staat? Geen idee wanneer dat is overigens, dat is niet in onze handen.

**Comment by TonD83** [comment]
Gevonden! Mea culpa, de bug zat in een eigen stukje custom css, wat we hadden gebaseerd op een oude versie van de toolkit en dus het 12x12 icoon gebruikte.

**Comment by MichielDHVD** [comment]
Ok prima.  Dan ga ik dit issue bij deze sluiten. Goed dat het is opgelost!
