### ISSUE TITLE
"Accordeon" Table row stippellijn wordt een door getrokken lijn als deze expanded is.

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#304]
In de accordeon tabel vorm die met bestaande componenten is gerealiseerd gebeurt er iets raars wanneer een row expanded wordt. 

Onder het kopje aanvraag/melding ook in de afbeelding die je oorspronkelijk hebt geupload is de lijn geen stippellijn meer maar een doorgetrokken streep. Maar dit is alleen onder het kopje aanvraag/melding. 

Dit gebeurt zowel boven als onder in het opengeklapte element.

Dit is te zien in onderstaande afbeelding

@WidoBurg

![image](https://user-images.githubusercontent.com/36912722/57354899-176e7680-716d-11e9-9ee7-2a38fd4954bb.png)

**Comment by PieterVerheij** [comment]
@MichielDHVD Is dit ergens live te zien?

**Comment by PieterVerheij** [comment]
Voorlopige conclusie: het is een verschijnsle dat specifiek in Chrome optreedt. Niet te reproduceren in Firefox en Edge. De combinatie van een <tr> met losse <td>'s en een <tr> met een enkele, brede <td> lijkt ook parten te spelen.

**Comment by PieterVerheij** [comment]
Bekende Chroium (=Chrome) bug met status `Wontfix (Closed)`. https://bugs.chromium.org/p/chromium/issues/detail?id=157106

**Comment by tfrijsewijk** [comment]
@MichielDHVD Wil je dat we hier nog iets mee doen? Komt er wellicht een redesign van de tabel styling aan waardoor dit geen probleem meer is?

**Comment by MichielDHVD** [comment]
Ik denk dat dat de route is voor dit issue. Aangezien dit een bug is die niet gefixed wordt. Ik zet het als actie voor het ux team om de tabel te redesignen zodat deze bug wordt voorkomen. 

Bij deze sluit ik dit issue.
