### ISSUE TITLE
Verticale uitlijning table button-span elementen en tekst elementen

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#305]
De verticale uitlijning van tekst in combinatie met button iconen is nog niet helemaal strak.

Namelijk de buttons(met icons) staan net iets lager dan de text elementen. Nu is dat voor de achterliggende buttons niet een probleem omdat die wat groter zijn. Maar bij de chevron staat dat nog niet helemaal optimaal. 

![Uitlijning](https://user-images.githubusercontent.com/36912722/57356990-15f37d00-7172-11e9-8fae-0766d4c14cee.jpg)

Hoe kunnen we ervoor zorgen dat dit strakker komt te staan? 

@WidoBurg.

**Comment by tfrijsewijk** [comment]
Gefixed in 7.2.0: https://dso-toolkit.nl/7.2.0/components/detail/accordion-table.html

**Comment by WidoBurg** [comment]
De wijziging geeft ander gedrag wat niet wenselijk is. Namelijk, zo was het met 7.1.0. 
<img width="127" alt="met 7 1 0" src="https://user-images.githubusercontent.com/8705247/58586736-0987af00-825c-11e9-899d-c0f99df40e1c.png">

Met 7.2.0
<img width="132" alt="met 7 2 0" src="https://user-images.githubusercontent.com/8705247/58586755-14424400-825c-11e9-9620-ad1d1346805a.png">

En de bijbehorende html
<img width="368" alt="html" src="https://user-images.githubusercontent.com/8705247/58586772-1e644280-825c-11e9-9808-1a8c7b252cc5.png">

Issue heropenen?

**Comment by MichielDHVD** [comment]
Issue bij deze heropend. 

Alleen de uitlijning van de chevron moest geraakt worden en nu zijn er meerdere elementen geraakt. 

Staat dit al op de int omgeving @WidoBurg dan kijk ik meteen of er nog andere elementen geraakt zijn.

**Comment by WidoBurg** [comment]
Nog niet. Eind van deze sprint zal die er staan.

**Comment by PieterVerheij** [comment]
De aanpassingen van de uitlijning zijn gebaseerd op de door Michiel aangeleverde screenshots. Met een andere knop (chevron met border) is inderdaad geen rekening gehouden.

**Comment by MichielDHVD** [comment]
Hoe kunnen we dit oplossen?

**Comment by tfrijsewijk** [comment]
Op GitHub kan 'n issue maar 1 milestone hebben. Graag een nieuwe bug aanmaken (Wellicht dat @PieterVerheij dat wilt doen).

**Comment by PieterVerheij** [comment]
https://github.com/dso-toolkit/dso-toolkit/issues/317 aangemaakt

**Comment by MichielDHVD** [comment]
gezien en verwijderd van project board
