### ISSUE TITLE
Accordeon Redesigns. 

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#307]
Hier is het nieuwe ontwerp voor de accordion. 

![Normale accordions](https://user-images.githubusercontent.com/36912722/57927260-c6b5f680-78ad-11e9-8a49-67b227db0617.png)

Wat strak ontwikkeld moet worden zijn de geneste accordeons. Deze zijn momenteel al in gebruik door Team 12 en daar hebben we ook een opzet voor gemaakt. 

![Geneste accordions](https://user-images.githubusercontent.com/36912722/57927259-c6b5f680-78ad-11e9-8306-2f2fdda82057.png)

Ik heb dit al eens met @TonD83 besproken. En het leek hem mogelijk dat we dit in de toolkit in de css kunnen oplossen zonder dat het team iets aan hun implementatie hoeft te veranderen. 

Ton heb je een stukje van jullie code zodat iedereen even mee kan kijken hoe de CSS het efficients gestyled kan worden. Of heb jij misschien al een idee hierbij @tfrijsewijk  

Als we het eens zijn over hoe we dit gaan toepassen komt deze bovenaan de ontwikkellijst te staan.

**Comment by MichielDHVD** [comment]
@tfrijsewijk @PieterVerheij  Kunnen deze visuele aanpassingen gedaan worden zonder dat er iets verandert aan de implementatie. Kun jullie hier ook een voorstel voor doen

**Comment by PieterVerheij** [comment]
@MichielDHVD Voor de duidelijkheid: een geneste accordeon heeft op het hoogste nivo een lichtpaarse achtergrond? 
Ik voorzie geen problemen voor een ombouw, maar ben wel benieuwd naar de gebruikte markup voor de nesting: ik zie zo snel niet hoe je zonder een extra class het nivo kunt aangeven. Als in: naar mijn weten is er geen 'haschild' achtige selector in css waarmee we de paarse achtergrondkleur kunnen forceren.

**Comment by MichielDHVD** [comment]
@PieterVerheij betekent dit dat als de lichtpaarse achtergrond achterwege gelaten wordt, deze aanpassingen zo doorgevoerd kunnen worden?

**Comment by PieterVerheij** [comment]
@MichielDHVD Dat maakt het inderdaad wel makkelijker. Zie dan geen probleem om het zonder markup wijzigingen door de te voeren.

Heb ik nog vraag; wat doen we met de iconen (alert, warning, etc)) rechts in de handler? Blijven die nog of komen die te vervallen? https://www.dso-toolkit.nl/7.1.0/components/detail/accordion.html

**Comment by PieterVerheij** [comment]
@MichielDHVD Klopt dit wel: zou je niet verwachten dat en 'Bijgebouw plaatsen'en 'Type bouwwerk' een paarse achtergrond en een chevron naar boven zouden moeten hebben?

![image](https://user-images.githubusercontent.com/25430835/58416701-be667400-8082-11e9-904f-6ffbfd3381fd.png)

**Comment by PieterVerheij** [comment]
@MichielDHVD Dit is wat ik nu heb. De stijl van de chevron is bij ons anders (dunner). Dat is de custom chevron stijl, die uit jullie ontwerp is de FontAwesome chevron, neem ik aan? Welke moet aangehouden worden?
![image](https://user-images.githubusercontent.com/25430835/58418626-91b55b00-8088-11e9-9d68-87c2c20a7485.png)

**Comment by MichielDHVD** [comment]
Dat de bijgebouw plaatsen niet paars is en een chevron naar boven heeft is een bewuste keuze geweest. 

De chevron zal geen probleem zijn. 

Over de icons gaan we nog even overleggen.

**Comment by MichielDHVD** [comment]
De iconen gaan blijven. 

Plus de achtergrond bij nested accordeons gaat er komen. DIt betekent dat er een class toevoeging bij nodig zal zijn en dat dit geimplementeerd moet worden door developers.

**Comment by PieterVerheij** [comment]
@MichielDHVD Tot hoe ver kan de nesting gaan van de uitklappers? Kan je een uitklapper in een uitklapper hebben en hoe zit het dan met de achtergrondkleuren?

**Comment by MichielDHVD** [comment]
De nesting zal vanuit ons systeem nooit verder gaan als dit. Dus maximaal 1 keer genest.

**Comment by PieterVerheij** [comment]
> Dat de bijgebouw plaatsen niet paars is en een chevron naar boven heeft is een bewuste keuze geweest.

Maar het nivo eronder (nivo 2), daar moet het pijltje toch juist omgedraaid zijn? Als in: dezelfde logica als op het hoogste nivo: bij ingeklapte section pijltje naar beneden, bij uitgeklapte section pijltje naar boven?

**Comment by MichielDHVD** [comment]
Inderdaad je hebt helemaal gelijk over de pijltjes ik heb het door elkaar gehaald. 

Ingeklapt pijltje naar beneden
Opengeklapt pijltje naar boven.

**Comment by PieterVerheij** [comment]
Zo dan ;)
![image](https://user-images.githubusercontent.com/25430835/58557853-ad069e80-821f-11e9-9556-33931d5d364f.png)

**Comment by MichielDHVD** [comment]
Kijk eens aan prima!

**Comment by PieterVerheij** [comment]
In jullie ontwerp staat een formulier met lijnen doorlopen over de volledige breedte. De uitklapper (`.dso-section-body`) heeft nu een padding, waardoor die lijnen niet zouden kunnen doorlopen. Er zijn een paar scenarios mogelijk:

1. de lijnen lopen niet door
2. de lijnen lopen door door het formulier links en rechts een negatieve margin te geven 
3. de uitklapper (`.dso-section-body`) krijg bij formulieren een extra class die de padding links en rechts op nul zet.

Maar die hele formulierstijl is nog niet uitgewerkt in een ticket/issue?

**Comment by MichielDHVD** [comment]
Nee deze formulier stijl is nog niet uitgewerkt in een issue. 

Maar de lijn onder een vraag is wel wenselijk. De lijnen moeten sowieso doorlopen. Vraag is of dit in dit issue moet worden afgehandeld. 

Verder zie ik nog een andere kleine aanpassingen. Wanneer een accordeon genest is is er een licht paarse achtergrond. deze achtergrond heeft nu ook een paarse 1px border. 

De licht paarse achtergrond heeft geen border. Zoals te zien is in de spec-afbeelding.

**Comment by PieterVerheij** [comment]
Ik zie het: ik ga het aanpassen!

**Comment by tfrijsewijk** [comment]
Opgeleverd in 7.3.0: https://dso-toolkit.nl/7.3.0/components/detail/accordion.html

**Comment by MichielDHVD** [comment]
Gezien en verwijderd van projectboard!
