### ISSUE TITLE
Button redesign

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#308]
Ook de buttons krijgen een redesign deze is vooral css aan de implementatie zal niet veranderen. 

![Button spec](https://user-images.githubusercontent.com/36912722/57927572-b81c0f00-78ae-11e9-9c5f-a56eac98de80.png)

**Comment by PieterVerheij** [comment]
@MichielDHVD de active-state wordt niet apart gestijld?

**Comment by MichielDHVD** [comment]
@PieterVerheij  Ik zorg morgen voor een antwoord hierop.

**Comment by PieterVerheij** [comment]
@MichielDHVD 👍

**Comment by PieterVerheij** [comment]
Semibold versie van font is nog pending, afhankelijk hoe we een nieuwere versie van Asap kunnen gebruiken (analoog aan heading ticket).

**Comment by PieterVerheij** [comment]
@MichielDHVD De tertiaire/link buttons: moeten die ook semibold worden?
![image](https://user-images.githubusercontent.com/25430835/58959892-50b6f800-87a6-11e9-9b27-65355937f009.png)

**Comment by MichielDHVD** [comment]
De active state voor de primary mag #15301e woden 

De active state van de Secundaire mag bosgroen #275937 worden  (Dan is Normal: ghost met groene outline -> Hover:  Grasgroen -> Active Bosgroen. Zelfde als bij de tertiare zoals hierboven is te zijn

**Comment by PieterVerheij** [comment]
@MichielDHVD : de borer van de tertiaire button is automatisch meeveranderd met de border van de secundaire, dus ook 1px. Maar we vragen ons nu af of dat eigenlijk wel de bedoeling was?
![image](https://user-images.githubusercontent.com/25430835/59444412-24325a00-8dfe-11e9-9146-96bdd5b4ac2e.png)

**Comment by MichielDHVD** [comment]
Nee dit was niet voorzien in het ontwerp. Aan de tertiare button moest niks veranderd worden.

**Comment by PieterVerheij** [comment]
Ok, aangepast.

**Comment by tfrijsewijk** [comment]
Opgeleverd in 7.3.0: https://dso-toolkit.nl/7.3.0/components/detail/buttons.html

Overigens heeft de Pager wel nog steeds ronde knoppen, wat wil je daarmee doen?

**Comment by MichielDHVD** [comment]
Gezien en verwijderd van projectboard.
