### ISSUE TITLE
Pagination redesign

### ISSUE THREAD

**Issue by daverhelst** [dso-toolkit/dso-toolkit#31]
Lange lijsten, zoals bijvoorbeeld een lijst met zoekresultaten, kunnen worden ingedeeld in pagina’s met paginering. Gebruik niet meer dan vijf stappen in de paginering, zodat deze ook op een mobiel scherm goed wordt getoond. Wanneer er meer dan vijf pagina’s zijn kan dit in de paginering worden weergeven met ellipsis.

![image](https://user-images.githubusercontent.com/5871330/37093701-95797f78-2210-11e8-961a-6556e2ab1104.png)

![image](https://user-images.githubusercontent.com/5871330/37093730-af284724-2210-11e8-9af8-4a4116295496.png)

Kleur:
Voor de groene onderden wordt de kleur #39870C gebruikt in overeenstemming met het de weergave van de secundaire knop. 

/Original reporter: Michael

**Comment by TonD83** [comment]
Zou hier een screenshot van het beoogde nieuwe design kunnen worden toegevoegd? Dan weten wij (PR12 DSO) beter wat we kunnen verwachten als dit issue wordt opgepakt.

**Comment by VolleMelk** [comment]
Hi Ton, alle content uit onze JIRA tickets wordt as we speak overgezet. Tickets die het label 'approved' hebben zijn al over. Voor het einde van de dag is alles over.

**Comment by Poofy83** [comment]
Ik loop tegen het volgende punt aan. In de omschrijving staat dat er een max. van 5 items is, zodat het ook lekker past op een mobiel scherm. Nu schets ik de volgende situatie:

![image](https://user-images.githubusercontent.com/5871330/37093764-cd98bd74-2210-11e8-9cd8-d40222220f41.png)

Hier kun je alleen verder en terug dmv van de pijlen, is dit de bedoeling?

/Original commenter: Dion - 16-02-18 15:31

-----

Nee, maar dat wordt als volgt opgelost.

De puntjes verwijzen hierbij 
links: Terug naar 1 
rechts: Naar de laatste resultaten

![image](https://user-images.githubusercontent.com/5871330/37093785-e006a066-2210-11e8-856d-7758b0deda9c.png)

/Original commenter: Michael - 19-02-18 14:24

-----

Ik zou toch er toch voor pleiten om voor de uitvoering van Dion te gaan: In jouw uitwerking heb je twee knoppen die hetzelfde doen. [Vorige] en [4] geven hetzelfde resultaat, net zoals [Volgende] en [6].

De uitvoering van Dion geeft meer navigatie-opties.

/Original commenter: Thomas - 19-02-18 20:11

-----

Dat 2 knoppen hetzelfde doen is niet het probleem. 
Consistentie is belangrijker.

Als een gebruiker in de flow zit om telkens het volgende getal te klikken ipv van pijlen wordt visueel die mogelijkheid ontnomen. Dat kan voor verwarring zorgen, verwarring die we willen voorkomen.

De informatie van de 4 en 6 en de interactie die daar bij hoort is belangrijker dan de extra keuze.

/Original commenter: Michael - 21-02-18 13:55

-----

Wij hebben net 'n halfuurtje de verschillende states besproken, en wij komen er niet uit. Wij zijn teveel met de UX-pet aan het kijken. Ik zet dit ticket terug in specification. Ik zou graag meer uitgewerkte varianten zien. De aangegeven platen zijn niet voldoende.

Hier een lijstje (Sorry, het zijn er best veel) die ik graag uitgewerkt zou zien:

```
1/1

1/2
2/2

1/3
2/3
3/3

1/4
2/4
3/4
4/4

1/5
2/5
3/5
4/5
5/5

1/6
2/6
3/6
4/6
5/6
6/6

1/100
50/500
100/100
```

Het eerste getal is de geselecteerde pagina, het tweede getal is het totaal aantal pagina's. Ik realiseer mij dat dit veel werk is, maar wij hebben nu al de nodige tijd in dit component zitten zonder dat we ergens komen. Onze suggesties/bedenkingen druisen altijd wel in tegen een van jouw aangedragen oplossingen. Wij zien het gewoon niet meer.

Dan een reactie op jouw laatste reactie. Ik ben geen UX designer, en heb absoluut niet de ambitie om het te worden (ik vind het wel fijn eigenlijk, dat ik aan jouw kan vragen hoe het moet worden ) maar ik heb mijn sterke vraagtekens bij het maken van een paginator waar twee knoppen hetzelfde gedrag hebben. Als ik jouw reactie op 'n andere manier interpreteer, lijkt het wel alsof "pijltje links" terug naar PAGINA 1 gaat. Dat lijkt mij ook niet logisch, aangezien het 1 pijltje is. Ik zou de 'Spring naar het begin/einde'-actie eerder bij een dubbele pijl associëren.

Maar het is jouw paginator, jij bent de UX expert: Wij maken wat jij vraagt. Ik hoop niet dat je het vervelend vind dat ik dit component nogmaals ter discussie stel, en dat ik om zoveel uitgewerkte varianten vraag

Kleine aanvulling: Gezien de complexiteit in het gedrag, zou jij misschien ook een stuk tekst kunnen aanleveren wat onder het kopje 'Notes' komt te zitten?

Nog een klein verzoek: Kun je aangeven hoe de pager moet uitlijnen onder inhoud?

/Original commenter: Thomas - 28-02-18

-----

Ik zal deze varianten gaan uitwerken.

En het is verder geen probleem. Ik heb ook specs mee gekregen die de handen binden. Namelijk de maximaal 5 elementen tussen de pijltjes. Als er 7 elementen tussen staan dan zijn alle problemen meteen opgelost.

Dus ik ga hier nog even mee terug naar de tekentafel om te kijken hoe we dit werkend kunnen krijgen.

/Original commenter: Michael - 28-02-18

**Comment by Poofy83** [comment]
@MichielDHVD Ik denk dat bovenstaand verzoek een beetje gestrand is. Kun je mij vertellen wat hiervan de status is?

**Comment by MichielDHVD** [comment]
Niet gestrand. Ik ben vooral aan het vechten met de vormgeving voor mobile en kleine schermen want dan valt de pagination hoe deze is bedacht helemaal uit elkaar. 

Daarom ben ik voor de kleinste schermen een aparte vorm aan het bedenken. Die ook fijn is om te gebruiken. Maar dat bewijst nog een uitdaging. 

Ik geef hier alvast de vorm voor standaard schermen. Die wijkt niet veel af van wat er eerder is gegeven. 

![pagination](https://user-images.githubusercontent.com/36912722/38719415-2b0ebd7a-3ef2-11e8-9f41-ef86d5df2fe8.png)

Grootste verschil is dat de regel max 5 items wordt losgelaten . En dat lost veel van de problemen op die de vorige pagination onmogelijk maakte. 

Ik zal hieronder een paar ontwerpen voor mobile en kleine schermen toevoegen. Misschien ontstaat er dan een kleine discussie is misschien handiger voor dit onderwerp. Plus kunnen jullie visie voor wat fijn is voor mobile pagination. 

Probleem is simpelweg niet de zelfde hoeveelheid informatie op een lijn krijgen. Dus zal er informatie wegvallen. En zal de gebruiker minder functionaliteiten hebben dan op een scherm met een gewone grootte. Vraag is hoe hij je het nog steeds fijn voor gebruikers. 

Ik vind voorbeeld C het meest in lijn van de pagination. De knoppen zijn alleen wat klein. Ik heb op ionic ook een klein buildje hiervoor gemaakt hoe de bediening hiervan op een mobiel daadwerkelijk aanvoelt. 

![pagination mobile](https://user-images.githubusercontent.com/36912722/38719789-1275b23a-3ef4-11e8-8d6f-e359f102d6fe.png)

**Comment by Poofy83** [comment]
@MichielDHVD Is er al een besluit genomen over de mobiele variant? Ik stel voor om zo dicht mogelijk bij de desktop variant te blijven waarbij een aantal items zullen moeten worden "weggesneden".

Ik kom dan uit op bijv. : 

< 1 ... 50 ... 500 >

Waarbij de pijlen aan de zijkanten nog steeds de single-steps zijn, het eerste en laatste nummer de knoppen zijn die naar het begin en het eind gaan, en het middelste getal de huidige pagina is.

**Comment by MichielDHVD** [comment]
Die variant is prima. Mobile heeft geen prioriteit meer dus alles simpel houden is uitstekend. 

De functionaliteit in de  < 1 ... 50 ... 500 > variant zitten alle essentials. 

Dus prima om het zo te bouwen.

**Comment by VolleMelk** [comment]
Ja, dit gaat zeker verwerkt worden in 2.0. Nog steeds 22 juni releasen?

**Comment by MichielDHVD** [comment]
Hebben jullie een demo versie hiervan ? Een link waar ik het kan checken ?

**Comment by VolleMelk** [comment]
Ik rol deze change vandaag uit in 2.0.0-alpha.2

**Comment by MichielDHVD** [comment]
![pagination-streepje](https://user-images.githubusercontent.com/36912722/41229432-442ae58c-6d7c-11e8-8da9-a9bfba40f70d.png)

Na de pagination te hebben bekeken is het slimmer om het cirkeltje bij hover en focus te veranderen naar een streepje. Is rustiger, het component is nu erg druk

**Comment by PieterVerheij** [comment]
@MichielDHVD We ontkomen er -vanwege de gebruiksvriendelijkheid op touch devices- niet aan om de <a> een vaste breedte te geven. Gevolg is dat de onderlijning ook een vaste breedte heeft. ZIe afbeelding:
![image](https://user-images.githubusercontent.com/25430835/47802126-f47f8780-dd2f-11e8-9e92-862c74b20e11.png)

Is dit bezwaarlijk?

**Comment by MichielDHVD** [comment]
Even of ik het begrijp. Dit zou alleen betekenen dat de streep onder de 1 iets breder is dan andere nummers. 

Kan ik het ergens zien waar de streep onder bijv de 99 staat.

**Comment by PieterVerheij** [comment]
U vraagt, wij draaien 😄 
![image](https://user-images.githubusercontent.com/25430835/47853938-ad050400-dde0-11e8-998d-42c89454037c.png)
De lijn is net zo breed als de <a>: 32px. Theoretisch moeten er 3 karakters in passen (bv. 500), daarom kunnen we bv. niet werken met een smallere <a> met horizontale margin. En je wilt het vlak op touch devices ook niet te klein maken.
Enige andere optie is aanpassing van de html (bv een span binnen de <a>, maar daar worden de implementators niet blij van.

**Comment by MichielDHVD** [comment]
Is goed zet maar door!

**Comment by PieterVerheij** [comment]
Komt met de volgende release mee.

**Comment by tfrijsewijk** [comment]
Fixed in `3.1.0-alpha.1`: https://www.dso-toolkit.nl/3.1.0-alpha.1/components/detail/pagination.html

**Comment by MichielDHVD** [comment]
Ziet er goed uit, ik zet deze op done.
