### ISSUE TITLE
Accessibility, definition list: wordt door screen reader zonder enige structuur voorgelezen

### ISSUE THREAD

**Issue by timveld** [dso-toolkit/dso-toolkit#310]
Betreft: [Definition list](https://www.dso-toolkit.nl/7.1.0/components/detail/definition-list.html)

Dit is erg verwarrend voor de screen reader gebruiker omdat screen readers (JAWS en NVDA) deze lijst regel voor regel oplezen zonder onderscheid te maken tussen wat in dt en dd staat. Je krijgt dus:
"Lijst met 15 items
Thema
Wonen
Werken
Regelkwalificatie
Instructieregels
Onderwerp
Bedrijventerrein
..."

Omdat er geen enkel onderscheid is weet ik bijvoorbeeld niet of "werken" nu bij de description van het eerste item hoort of de title van het tweede item is. 

Voor zover ik kan nagaan is de definition list zoals hier gebruikt binnen WCAG toegestaan (zal daar nog even zorgvuldig naar kijken) maar is dit vooral iets wat de screen readers niet goed doen, als je gaat Googlen op "definition list screen reader" zie je die klacht vaker voorbij komen en kom ik geen alternatieven tegen. Het enige waar je aan kunt denken is om dit als tabel te presenteren maar betwijfel of dat hier wel de juiste aanpak is, afhankelijk van jullie reactie zal ik hier nader induiken. 

Mijn voorlopige voorstel is om een : achter alle titles te plaatsen, denk dat dit ook visueel de zaak eerder verbetert (mocht iemand om een bepaalde reden niet goed zien dat de titel vetgedrukt is dan zal de extra ':' hem helpen te begrijpen wat er aan de hand is). In ieder geval voor mij persoonlijk is de ':' zeker afdoende om te begrijpen wat er aan de hand is. 
Ook zou je het dl element een title attribuut moeten geven `<dl title="resultaten">`. Het voorbeeld wordt dan met een screen reader: 
"Resultaten lijst met 15 items 
Thema:  
Wonen
Werken
Regelkwalificatie:
Instructieregels
Onderwerp:
Bedrijventerrein
..."

Als in bovenstaande dan ook nog "thema's" (meervoud) zou staan wordt het helemaal een stuk duidelijker, ook belangrijk voor mensen die door sterke vergroting het overzicht missen. 

Een andere optie is dat we de titels als headings markeren, vanuit het perspectief van screen reader navigatie is dat zeker een goed idee maar ik twijfel of het technisch en praktisch ook een goede optie is in dit geval. Misschien komen we nog op een beter idee, zal kijken of WCAG over deze situaties wat zegt. 

_Edit @tfrijsewijk: HTML als code snippet geformat_

**Comment by PieterVerheij** [comment]
Ik twijfel of het gebruik van een heading in een DT correct is? Gebruik van een ':' lijkt mij een veiligere optie.

**Comment by MichielDHVD** [comment]
De opties van headings en tables zijn wat extreem. De dubbele punt lijkt me een charmante oplossing. Ik moet wel even kijken naar de implicatie op alle huidige ontwerpen. Ik verwacht geen problemen, maar het moet voor de zekerheid doorgelopen worden.

**Comment by PieterVerheij** [comment]
Voorstel: spatie en dubbele punt achter de title.

![image](https://user-images.githubusercontent.com/25430835/59041692-69dca900-8879-11e9-8321-83e91bdcbee5.png)

**Comment by PieterVerheij** [comment]
Spatie gaf bij een niet-bold `<dt>` een raar gezicht. Spatie verwijderd.

**Comment by tfrijsewijk** [comment]
Dit issue begint met een probleem over screenreaders maar draagt een visuele oplossing aan.

Daarbij is het gebruik van het `dl` element zoals in de toolkit conform WCAG.

https://freedomscientific.github.io/VFO-standards-support/html.html
Deze site heeft een overzicht van HTML5 elementen met hun support state door JAWS. De site wordt bijgehouden door "Freedom Scientific". Zij maken JAWS.

De visuele change kan doorgevoerd worden, maar het echte probleem van deze issue is daar niet mee opgelost

**Comment by MichielDHVD** [comment]
De dubbele punt is niet alleen een visuele oplossing maar als deze opgelezen wordt door een screenreader ook een audio cue. 

Hoewel volgens mij dit component al wcag compatible was, kan de dubbele punt wel helpen bij het verduidelijken. 

Volgens mij kunnen we dan met iets relatiefs kleins het component toch verbeteren voor een groep mensen.

**Comment by tfrijsewijk** [comment]
>De dubbele punt is niet alleen een visuele oplossing maar **als** deze opgelezen wordt door een screenreader ook een audio cue.
**Als** is het sleutelwoord uit deze zin. Mijn screenreader (ChromeVox) doet namelijk niets met de voorgestelde oplossing (`::after` met `content: ":").

ChromeVox doet wel degelijk iets met een dubbele punt, maar pas als deze in het DOM staat. Bij het oplezen wordt er kort (heel kort zelfs) gepauzeerd bij de dubbele punt.

Voor zover ik kan zien interpreteert JAWS ook het DOM (en gebruikt het geen OCR voor websites). Dus tenzij JAWS ook de CSS verwerkt en er dan achterkomt dat er met een pseudo element een dubbele punt is geplaatst zal ook JAWS niks doen.

Een betere oplossing is de implementator een dubbele punt in het DOM laten plaatsen. Dan weten we zeker dat wij niets meer kunnen doen om de dubbele punt bij de screenreader te krijgen. Als we met styling de dubbele punt gaan plaatsen, kan de implementator deze niet meer in de markup plaatsen. Er staan dan twee dubbele punten achter elkaar op het scherm.

>Volgens mij kunnen we dan met iets relatiefs kleins het component toch verbeteren voor een groep mensen.
Dit ben ik absoluut met je eens. Maar nogmaals: dit issue is dan niet opgelost.

En daarbij is het belangrijk dat wij enigszins weten voor welke groep mensen deze oplossing is. Want volgens mij is deze best beperkt en zit het een beter oplossing in de weg.

Ik denk dat we de oplossing in documentatie moeten zoeken:
* Stel een `title` attribuut op het `<dl>` element verplicht
* Stel het plaatsen van een dubbele punt in de `<dt>` verplicht

**Comment by PieterVerheij** [comment]
@MichielDHVD @bramhoosemans @timveld 
Eens met de suggestie van @tfrijsewijk ?

**Comment by bramhoosemans** [comment]
@PieterVerheij @tfrijsewijk Eens met de voorgestelde aanpak. Laten we zorgen dat de instructie en voorbeeld wordt opgenomen in de DSO Toolkit. Daarna kan dit issue gesloten worden wat mij betreft.

https://www.dso-toolkit.nl/8.0.1/components/detail/definition-list.html

**Comment by MichielDHVD** [comment]
Mee eens met de aanpak van de title en dubbele punt. Ik ga een klein (nadruk op klein) stukje documentatie opstellen om dit zo simpel en efficient mogelijk te communiceren.

**Comment by timveld** [comment]
Denk ook dat title en dubbele punt in DOM de beste optie is. Een dubbele punt plaatsen DMV CSS helpt niet want die zal JAWS negeren. Klopt het dat dit nog niet in het voorbeeld is geimplementeerd?

**Comment by MichielDHVD** [comment]
Vervolg actie is de oplossing: 

Er moet bij definition lists dubbele punten gebruikt worden. Dit is de verantwoordelijkheid van de implementator. 

Dit moet worden verwerkt in de documentatie.

**Comment by tfrijsewijk** [comment]
Uitgekomen in 8.5.0: https://dso-toolkit.nl/8.5.0/components/detail/definition-list.html

**Comment by timveld** [comment]
Getest, zo is het een stuk beter! Of zo'n definition list de best mogelijke oplossing is blijft een beetje de vraag maar zoals het nu is denk ik in ieder geval dat alle gebruikersgroepen zich in de praktijk kunnen redden.
