### ISSUE TITLE
Headings aanpassen

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#311]
Er zijn wat kleine aanpassingen voor de headings. 

<img width="623" alt="Screen Shot 2019-05-20 at 08 26 02" src="https://user-images.githubusercontent.com/36912722/58000392-f1d05e00-7ad8-11e9-85b4-cf308d73d6b4.png">

De paarse heeft betrekking op de accordeons. De standaard is de groene versie.

**Comment by PieterVerheij** [comment]
@MichielDHVD Voor de H1 vervalt dus het onderscheid tussen L, M, S en XS?

**Comment by MichielDHVD** [comment]
Ja klopt die vervalt. Er zijn altijd dezelfde headings.

**Comment by PieterVerheij** [comment]
Voor deze wijziging is ook de semibold versie van Asap gebruikt. Daarvoor is het nodig te updaten naar een nieuwere versie van Asap (bijvoorkeur de nieuwste: 0.0.69). Echter, in https://github.com/dso-toolkit/dso-toolkit/issues/69 is besloten niet verder te gaan dan 0.0.35 vanwege problemen met pixels/antialiasing bij het renderen van het font. 
Echter, in https://github.com/google/fonts/issues/1190 wordt verwezen naar https://github.com/Omnibus-Type/Asap/tree/master/fonts, daar staat een (nog niet door ons geteste) nieuwere variant van het font.

**Comment by PieterVerheij** [comment]
Met de gedownloade (8 maanden oude) fonts, rendert het font wel weer goed: 
![image](https://user-images.githubusercontent.com/25430835/58478052-60ef2780-8155-11e9-8f4b-f2291e35f30d.png)

**Comment by MichielDHVD** [comment]
Zolang het goed rendered. Dat is het allerbelangrijkste. Maar zelfs met de huidige versie waren er problemen met firefox op windows machines. Dat het soms korrelig werd. Dus ik ben benieuwd als we naar de versie overgaan of die problemen dan blijven aanhouden

**Comment by tfrijsewijk** [comment]
Het updaten van het font "Asap" heb ik verplaatst naar #318

**Comment by tfrijsewijk** [comment]
Opgeleverd in 7.3.0:
* https://dso-toolkit.nl/7.3.0/docs/typography.html
* https://dso-toolkit.nl/7.3.0/components/detail/layout.html

**Comment by MichielDHVD** [comment]
Gezien en verwijderd van project board
