### ISSUE TITLE
Margins hr-element aanpassingen

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#312]
De hr heeft nu aan de bovenkant en onderkant een margin van 24px. 

<img width="1154" alt="Screen Shot 2019-05-20 at 09 11 25" src="https://user-images.githubusercontent.com/36912722/58002759-92298100-7adf-11e9-9629-11db12e1b6b2.png">

De boven kant krijgt een margin van 8px. 
De onderkant blijft 24px. 

<img width="1146" alt="Screen Shot 2019-05-20 at 09 12 13" src="https://user-images.githubusercontent.com/36912722/58002771-98b7f880-7adf-11e9-8877-b4c956b4f32f.png">

**Comment by PieterVerheij** [comment]
Margin-top: 24px -> 8px;

**Comment by tfrijsewijk** [comment]
Aangepast in 7.2.0: https://dso-toolkit.nl/7.2.0/components/detail/rich-content.html
