### ISSUE TITLE
Verticale uitlijning table button-span elementen en tekst elementen gaat niet bij alle button-elementen goed

### ISSUE THREAD

**Issue by PieterVerheij** [dso-toolkit/dso-toolkit#317]
In https://github.com/dso-toolkit/dso-toolkit/issues/305 is de verticale uitlijing aangepast. Echter, niet bij alle elementen gaat dit goed:
![image](https://user-images.githubusercontent.com/25430835/59039262-ca1d1c00-8874-11e9-8e68-0115a3ad93be.png)

Met 7.2.0
![image](https://user-images.githubusercontent.com/25430835/59039371-02bcf580-8875-11e9-88e7-42b7a70aabef.png)

De aanpassingen van de uitlijning zijn gebaseerd op de door Michiel in #305  aangeleverde screenshots. Met een andere knop (chevron met border) is geen rekening gehouden. Daar moet dus een uitbreiding op komen.

**Comment by PieterVerheij** [comment]
Overigens is het wel zo dat een knop met border zo hoog is dat hij de standaardhoogte van een `<td>` hoger maakt. (43/44px ipv 41px).

**Comment by MichielDHVD** [comment]
Ik denk dat het niet erg is dat een <td> groter wordt. Bij tables wordt de hele row dan toch meteen verhoogd. 

Misschien als er een afbeelding is kan ik de implicaties beter zien.

**Comment by tfrijsewijk** [comment]
Opgeleverd in 7.3.0. Bovenstaande bug hebben we in een demo component verwerkt waardoor het meedoet in Percy

https://dso-toolkit.nl/7.3.0/components/detail/accordion-table.html

**Comment by MichielDHVD** [comment]
Gezien en verwijderd van projectboard.
