### ISSUE TITLE
Font Asap update

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#318]
Nieuwste versie van het webfont Asap bundlen

**Comment by tfrijsewijk** [comment]
Opgeleverd in 7.3.0: https://dso-toolkit.nl/7.3.0/docs/typography.html

Het is scherp, ook op de beruchte 14px op een niet high density scherm. Zie #311 voor de geschiedenis

**Comment by MichielDHVD** [comment]
Gezien en verwijderd van projectboard.
