### ISSUE TITLE
Formulieren: Tekstvelden en labels redesign

### ISSUE THREAD

**Issue by Poofy83** [dso-toolkit/dso-toolkit#32]
Voor alle formulieren met een vorm van een tekstveld moet het volgende aangepast worden. 

![image](https://user-images.githubusercontent.com/5871330/37089147-e7a5afe4-21ff-11e8-93fd-7a4f98147d18.png)

**Comment by Poofy83** [comment]
Verdwijnt de de werkvorm "Verticale formulieren" (https://www.dso-toolkit.nl/1.1.0/components/detail/form-vertical.html): Is de werkvorm zoals beschreven in dit ticket de enige?

Dit is een vrij fors ticket wat uit meerdere subtasks gaat bestaan

/Original commenter: Thomas - 09-02-18 14:36

-----

Verticale formulieren blijft gewoon.

De aanpassingen die in de afbeeldingen staan moeten toegepast worden op de formulier onderdelen in de DSO stijlgids. Dus de huidige indeling/werkvorm zal blijven. De look en feel zal alleen anders worden.

Dat alles opgeteld maakt dit inderdaad een vrij forse ticket.

/Original commenter: Michael - 09-02-18 14:44

-----

Ok. Wat is de onderliggende ruimte tussen een rij met label/input ?

/Original commenter: Thomas - 09-02-18 15:33

-----

![image](https://user-images.githubusercontent.com/5871330/37089227-25fddaaa-2200-11e8-8dac-28424fcb245e.png)

Even voor de zekerheid een afbeelding er bij geplaatst, dat we het over hetzelfde element hebben.

Deze onderliggende ruimte moet 16px worden.

/Original commenter: Michael - 12-02-18 07:11

-----

- Als een veld ongeldig is ingevuld, wordt het veld rood omrand. Wat is de tekstkleur bij een ongeldig ingevuld veld?
- Als daarna het veld wordt gecorrigeerd, wat is dan de kleurstelling?
- Kunnen velden een toelichting hebben? Zo ja, kun je deze dan uitwerken? Ook in combinatie met een foutmelding graag

/Original commenter: Thomas - 02-03-18

-----

![image](https://user-images.githubusercontent.com/5871330/37089269-4ccd5516-2200-11e8-8e6c-d878d8564865.png)

Hier de verschillende uitwerkingen. Als er nog meer nodig zijn laat maar weten.

/Original commenter: Michael - 05-03-18

**Comment by VolleMelk** [comment]
@MichielDHVD 
![image](https://user-images.githubusercontent.com/9696261/37092116-d3fba16e-220a-11e8-8822-98be0e8cecad.png)

In de huidige opzet is het label een block element wat de helft van het formulier inneemt. Klik je op de lege ruimte, dan klik je alsnog op het label en krijg je op het bijbehorende veld focus.

Het is "maar focus", geen navigeer actie maar alsnog kan een gebruiker het als "onverklaarbaar" ervaren. Is dit gewenst? Het voordeel is dat een touch/tap op een mobile device wat ruimer is.

**Comment by MichielDHVD** [comment]
@VolleMelk 

Het is beter als de lege ruimte niet klikbaar is. 
Het wordt niet verwacht en de elementen staan te ver uit elkaar. Als elementen dicht op elkaar staan is het geen probleem maar hier werkt het niet. 

Hoeveel ruimer is het voor een mobile device of is dat lastig te testen.

**Comment by VolleMelk** [comment]
@MichielDHVD Hoe ziet een disabled input/radio/checkbox eruit?

**Comment by VolleMelk** [comment]
En doen we iets met readonly?

**Comment by MichielDHVD** [comment]
Disabled border: Border: 2px solid E8E8E8 

Met readonly bedoel je alleen de formulieren neem ik aan. Want dat is niet vaak van toepassing op checkboxes en radiobuttons.

Read-only:  Border: 1px solid A8BCAE

**Comment by VolleMelk** [comment]
Fixed:
* https://www.dso-toolkit.nl/1.2.0-beta.0/components/detail/form--form-horizontal.html
* https://www.dso-toolkit.nl/1.2.0-beta.0/components/detail/form--form-vertical.html

**Comment by DjangoBlok** [comment]
Oef ik zie deze dingen nu ineens in de viewer verschijnen.
Over smaak valt uiteraard te twisten, er vallen me wel een paar dingen op:
- Erg dikke randen
- Erg grote afronding
- Afronding niet hetzelfde als de afronding van multiselect? Ziet er gek uit als die twee naast elkaar staan.
- Geen innershadow
- Hierdoor lijkt het meer een knop dan een invoerveld

**Comment by VolleMelk** [comment]
Ik weet niet precies over welk component je het hebt, kun je een screenshot laten zien?

https://www.dso-toolkit.nl/1.2.0-beta.0/components/detail/form--form-horizontal.html Dit is hoe het formulier er uit hoort te zien in de 1.2.0-beta.0

**Comment by DjangoBlok** [comment]
Het gaat inderdaad oer de formuliervelden die nu in 1.2.0 beta zitten. 
Ook in de stijlgids heeft het veld met type auto een andere afronding dan de invoervelden. 
Bij ons komt hij naar voren bij o.a. zoeken: https://pre.omgevingswet.overheid.nl/content/orienteren
De rest is smaak en moet ik denk ik met Michael bespreken.

**Comment by VolleMelk** [comment]
We hebben het gevonden: Dit is safari op mac styling. Zullen we oppakken in nog in de release van vandaag meepakken

**Comment by Poofy83** [comment]
Ik heb uitvoerig onderzoek gedaan naar een oplossing voor dit probleem en heb een antwoord kunnen vinden, helaas haalt deze niet alleen de "glossy" look weg van het <select> element, maar sloopt ook de caret uit het beeld.

Graag wil ik deze discussie voortzetten in #93 waar ik al het een en ander heb uitgezet voor een beter passende en globale oplossing.
