### ISSUE TITLE
Documentatie: Startgids en toelichting Modal component

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#322]
Het uiteindelijk doel van de toolkit is dat niet alleen developers maar ook product owners en designers gebruik gaan maken van de toolkit. 

Dat betekent dat er wel toevoeging gedaan moeten worden op documentatie vlak. 

1) Er moet een start gids gemaakt worden die de mogelijkheden van de toolkit uitlegt. 
2) Een voorbeeld van een component met extra uitleg. Dat wordt in dit geval het modal component. Hier worden de do's en don'ts van een component uitgelegd plus op welke gedrag en accessibility issues gelet moeten worden bij implementatie van het component. 

bijhorend Pull request #321 

Toegevoegd:
* Modal Documentation info page

Aangepast:
* Modal tree structure betreffende links. Kopje variaties toegevoegd
* page index naamswijziging naar Startgids. Plus inhoud startgids veranderd
* Typografie stuk tekst betreffende Asap naar Typografie.

**Comment by tfrijsewijk** [comment]
Opgeleverd in 7.3.0.

* De landingspagina is aangepast: https://dso-toolkit.nl/7.3.0/
* De documentatiepagina van de Modal is een documentatiepagina geworden. Vanuit deze documentatiepagina is het mogelijk om naar de echte componenten te verwijzen. Met een beetje Fractal/Handelbars magie met een beetje CSS heb ik mijn inziens een zeer fraaie documentatiepagina opgeleverd: https://dso-toolkit.nl/7.3.0/docs/modals.html

Fractal faciliteert in het schrijven van documentatiepagina's. Documentatie komt als markdown in `/docs`. Het voordeel van verwijzen naar echte componenten (en niet naar screenshots):
* Het rendered zoals de browser dat als enige kan. Het aangeleverde screenshot was hoge resolutie, onnodig veel data en attribuut styling. Daarbij was er in het screenshot een visuele werkvorm die onmogelijk is om met de huidige toolkit te maken
* Responsive gedrag
* En de belangrijkste: actuele componenten! Het aangeleverde screenshot had nog de oude visuele weergave van de knoppen terwijl nota bene in tandem de nieuwe styling is gemerged.

Ofwel: alleen maar voordelen, ik hoop dat je het mooi vindt!
