### ISSUE TITLE
highlight box restyling  en variaties. 

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#325]
Er zijn variaties nodig op de highlight box. 

Er is een landingspagina ontwikkeld en daar komt de behoefte naar voren om meer variaties te hebben op de highlight box. 

![page-1-100_aanvragen](https://user-images.githubusercontent.com/36912722/60015568-16919580-9684-11e9-807f-13ab1ba873ad.png)

Hier zijn twee nieuwe vormen te zien. 

De gele en de witte met een kader eromheen. 

Een derde vorm is met de kleur #e4f1d4 

Deze is in een vorm te bekijken op de homepage 

https://acc.omgevingswet.overheid.nl/home

De grootte en breedtes van de blokken worden bepaald door bootstrap en de content. 

Om de specs te bekijken stuur ik ook meteen een nieuwe vorm door. Namelijk een html file opgesteld door sketch waarin je alle specs kan bekijken. 

[14 Landingspagina's V2.zip](https://github.com/dso-toolkit/dso-toolkit/files/3320655/14.Landingspagina.s.V2.zip)

**Comment by PieterVerheij** [comment]
@tfrijsewijk zip uitgepakt in P:\RWS Leefomgeving\2016 - DSO\extern\14 Landingspagina's V2

**Comment by tfrijsewijk** [comment]
Ik denk dat er ook wat van de padding af moet. Verder kunnen we best wat modifiers maken:
* `dso-bordered`: randje eromheen
* `dso-yellow`: gele achtergrond

Implementator kan dan zelf de juiste vorm kiezen.

Of heb je liever een `primary`, `secondary`, `default` methode?
* Primary -> geel
* secondary -> randje
* default -> grijs

Wordt de grijze highlightbox nog ingezet? Zo niet, dan kunnen we de default highlightbox wit maken. Zodra je de whitebox zonder modifiers gebruikt springt de tekst alleen naar rechts in

**Comment by MichielDHVD** [comment]
Ja de grijze highlight box wordt op dit moment ingezet. Namelijk in het "winkelmandje" deze kun je bekijken bij de vergunningcheck nadat je de locatie hebt doorgevoerd. 
https://acc.omgevingswet.overheid.nl/checken

De padding aanpassen wordt dan wel een probleem want dat heeft invloed op het winkelmandje. 

@TonD83 Ik zie in het huidige winkelmandje nog wel wat custom css My-Selected-Class klopt dit. Misschien moeten we kijken of we dit kunnen verwerken, 


De naamgeving wil ik ook even bij de developers neer leggen, vragen wat het meest logische zou zijn. 

Enigste want nog miste in je opmerkin Thomas was dat er ook een groene optie #e4f1d4 moest komen.

**Comment by TonD83** [comment]
@MichielDHVD Als je `my-selected-tasks` bedoelt, klopt dit inderdaad. Heeft met wat custom margins en padding te maken, wat weer nodig was door die icoontjes voor de gekozen werkzaamheden. Liefst halen we dit er natuurlijk uit, maar dan moet hier wel rekening mee worden gehouden. Wat ik hier boven zie in afbeeldingen is alleen totaal iets anders?

**Comment by MichielDHVD** [comment]
@TonD83 Ja dat klopt, bovenstaande onderdelen lopen wel heel erg uit elkaar met het winkelmandje. Ben eigenlijk wel van mening dat het winkelmandje zijn eigen component verdiend. Kunnen jouw nieuwe specs meteen meegenomen worden.

**Comment by MichielDHVD** [comment]
Eerder gaf je aan dat de padding minder moet worden. Dit blijkt nu een reeele wens te zijn. 

In het volgende ontwerp dat gerealiseerd wordt is ook een highlight box verwerkt. Maar voor dit ontwerp zijn de marges in de huidige highlight box ook te groot. 

![image](https://user-images.githubusercontent.com/36912722/60667307-83b5df80-9e69-11e9-94e4-694126e6063c.png)

Voorstel is om de top en bottom naar 16px te stellen. 

@WidoBurg @BramHoosemans

**Comment by tfrijsewijk** [comment]
Volgens mij staan er nog teveel "vraagtekens" in dit issue om het te kunnen oppakken.

* Wat is `my-selected-tasks` en verwacht men (binnen dit issue?) een oplossing vanuit de toolkit?
* Welke """top en bottom""" moet er naar 16px? Hebben we het over de CSS `top` en `bottom` properties?
* Is de naamgeving van de whitebox uitbreidingen al bij de developers neergelegd?
* In hoeverre is een aanpassing van de padding van invloed op het winkelmandje?

Ofwel, iets meet specs graag :-)

**Comment by MichielDHVD** [comment]
* my-selected-tasks* is een stukje custom css van Ton zelf en heeft betrekking op het winkelmandje. My-selected-tasks zou " als het goed is "  de veranderingen aan de top en bottom paddings moeten overrulen.  Het enigste wat dat doet is de left-padding op 32px zetten ipv 25px maar de rest . Maar dit heeft alleen betrekking op het winkelmandje. 

* Er wordt gerefereerd naar de top en bottom padding van de highlightbox

* Naamgeving moet ik nog nalopen.  (hoop vrijdag een antwoord te hebben) 

Voor het grootste gedeelte zijn de specs te vinden in het zip document dat was meegestuurd.

**Comment by tfrijsewijk** [comment]
Ik wacht de naamgeving af

**Comment by bramhoosemans** [comment]
Ik heb de varianten van de highlightbox verzameld (zie bijgevoegde afbeelding). Hierin heb ik de margins binnen het component aangeven. Als er meer specificaties nodig zijn hoor ik het graag! Wat naamgeving betreft is de wens om specifieke modifiers te maken voor de highlightbox, zoals:

- highlightbox-yellow
- highlightbox-bordered

Verder ben ik ook van mening dat de ‘winkelwagen’ een eigen component verdient. Zeker nu we variaties gaan toevoegen aan de highlightbox en de interactie met de winkelwagen gewijzigd is. Hier voor zal ik een nieuw issue aanmaken.

![specificaties-highlightbox](https://user-images.githubusercontent.com/598735/61864036-ff3b0780-aed0-11e9-9a5a-ee77d5230d3e.png)

**Comment by MichielDHVD** [comment]
In issue #327 zijn we er achter gekomen dat de whitebox niet uitgebreid kan worden om het witte vlak te realiseren die ook in de landingspagina zit. Dit zou dus variatie nr. 4 zijn. 

Qua naamgeving zouden we dan komen op:

highlightbox
highlightbox-yellow
highlightbox-bordered 
highlightbox-dropshadow

Eerder in dit gesprek begon ik over een variatie met de kleur #E4F1D4 deze mag vergeten worden. Deze komt alleen op dit moment op de homepage voor. En de functionaliteit van dit vlak kan makkelijk overgenomen worden door bijv. de highlightbox-bordered.  

Dit heeft ook consequenties voor issue #326 namelijk de stappen teller. Deze stappen teller moet boven een highlightbox-dropshadow komen. @bramhoosemans  en ik gaan hier naar kijken om georderend te krijgen.

**Comment by bramhoosemans** [comment]
Is het mogelijk ook de 'stappenteller' als modifier toe te voegen op highlightbox-dropshadow? @tfrijsewijk

**Comment by PieterVerheij** [comment]
> Is het mogelijk ook de 'stappenteller' als modifier toe te voegen op highlightbox-dropshadow? 

@bramhoosemans Is deze vraag nu niet beantwoord in #326 ?

**Comment by PieterVerheij** [comment]
@bramhoosemans Gaat de rest van dit issue nu niet over https://www.dso-toolkit.nl/8.0.1/components/detail/highlight-box.html?

Specifiek:
- uitbreiding met kleuren (`highlightbox-yellow` en `highlightbox-bordered`)
- aanpassing padding van 25px naar 16px

highlightbox-dropshadow passen we niet doe, omdat dat slaat op #326 ?

**Comment by bramhoosemans** [comment]
@PieterVerheij Klopt!

**Comment by tfrijsewijk** [comment]
Dit uitgekomen in 8.1.0:
* https://dso-toolkit.nl/8.1.0/components/detail/highlight-box--default.html
* https://dso-toolkit.nl/8.1.0/components/detail/highlight-box--yellow.html
* https://dso-toolkit.nl/8.1.0/components/detail/highlight-box--bordered.html

Bij de bordered uitvoering is er een padding van 15px toegepast ivm de 1px border. De tekst in highlightboxen lijnt dan verticaal
