### ISSUE TITLE
Stappenteller boven whitebox

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#326]
In de landingspagina zitten ook white boxes met daarboven een stappen teller. 

Mijn vraag is als volgt hoe kunnen we deze het beste implementeren. Een nieuwe component of een modifier op bijvoorbeeld de white box in de toolkit?

![page-1-100_aanvragen](https://user-images.githubusercontent.com/36912722/60017219-873ab100-9688-11e9-9d7a-677a22e0da68.png)

Als we hier een antwoord op hebben kan ik de specs sturen. Specs zijn ook te vinden in issue #325 daar is een zip file met sketch/html bestanden waar alle onderdelen staan.

**Comment by PieterVerheij** [comment]
@MichielDHVD Gaan die nummertjes redactioneel bijgehouden worden? Neem aan van wel?

**Comment by MichielDHVD** [comment]
Die stappen/nummertjes liggen op dit moment behoorlijk vast. Dus die zullen 1 keer worden neergezet en daarna wordt er vrij weinig aangepast. 

Dit is wel een content pagina, en de het idee is wel dat het makkelijk redactioneel moet aan te passen zijn. 

De nummertjes moeten ook opgelezen kunnen worden door een screenreader want ze verschaffen immers ook informatie.

**Comment by tfrijsewijk** [comment]
Waar zit de interactie in de kleine whitebox? De huidige whitebox is in zijn geheel klikbaar, maar bij stap 1 zie ik al een link staan.

Ik neig nu naar een modifier.

Er zit trouwens een dropshadow boven, de huidige whitebox heeft die niet. Wil je dat ook gedaan hebben?

**Comment by MichielDHVD** [comment]
Deze whitebox zal niet interactief zijn behalve misschien een link in de tekst. 


De dropshadow boven mag ik voorzie daar geen conflict in met eerdere ontwerpen.

**Comment by tfrijsewijk** [comment]
De voorgestelde feature wordt gevraagd op een component wat nu niet bestaat zoals weergegeven:

Zie de whitebox uit versie 8 en vergelijk met het ontwerp: https://dso-toolkit.nl/8.0.0/components/detail/examples.html

Wat is de verwachting zodra dit ticket wordt opgeleverd? Het lijkt erop dat de whitebox ook aangepakt moet worden?

**Comment by bramhoosemans** [comment]
@tfrijsewijk Ook goed om mee te nemen in de afweging is het feit dat de 'stappen' naast de rondjes equal heights hebben! Daarnaast kan de nummering redactioneel worden bijgehouden.

Én als laatste: we zouden het nummer soms willen vervangen door een icoon, is dat mogelijk?

<img width="1185" alt="Schermafbeelding 2019-07-26 om 14 16 36" src="https://user-images.githubusercontent.com/598735/61951074-1dc40000-afb0-11e9-830a-a4c3a1a02c25.png">

**Comment by PieterVerheij** [comment]
Zonder iets getest te hebben, denk ik dat het equal height issue zonder veel problemen met `display: flex;` is te realiseren. Zie bv. http://www.lottejackson.com/learning/an-equal-height-grid-using-flexbox.

@bramhoosemans Gaat het om nieuwe, redactioneel in te stellen, iconen?

Mijn  voorkeur gaat uit naar een nieuw element.

**Comment by bramhoosemans** [comment]
Het zou mooi zijn als we de highlightbox zo flexibel kunnen inzetten dat als je er meerdere naast elkaar plaatst er een class 'equal heights' aan toegevoegd kan worden. Er lopen nu eigenlijk 2 issues over dit vraagstuk (zie ook https://github.com/dso-toolkit/dso-toolkit/issues/325).

@PieterVerheij Goed om helder te krijgen wat we met een Highlightbox kunnen oppakken en/of wat een nieuw component krijgt.

Ik heb het laatste ontwerp van de volledige pagina toegevoegd:
![100_aanvragen](https://user-images.githubusercontent.com/598735/62131865-4c0d4c80-b2dc-11e9-95b6-ab6fcc34dfd4.png)

**Comment by PieterVerheij** [comment]
@bramhoosemans Vraagje: we hebben het idee dat er een paar zaken door elkaar heen lopen. Maar is er niet sprake van een naamsverwarring? Gaat dit ticket niet eigenlijk specifiek over de whiteboxes ipv de highlightboxes?

Een highlightbox is een vlak met een gekleurde achtergrond, zoals het gele accentvalk in jouw afbeelding? Zie ook https://www.dso-toolkit.nl/8.0.1/components/detail/highlight-box.html

Whitebox is een wit vlak met dropshadow, waar dan evt. een teller in zou kunnen komen? Zie ook https://www.dso-toolkit.nl/8.0.1/components/detail/examples.html

**Comment by bramhoosemans** [comment]
@PieterVerheij Er is inderdaad wat verwarring omtrent de highlightbox en whitebox... onduidelijk wat de verschillen zijn (functioneel). Maar de vraag is juist of één van de twee componenten uitgebreid kan worden met de 'rondjes' of niet?

Gezien wij de pagina op korte termijn willen oppakken is het wel goed om een duidelijk beeld te krijgen van de componenten en hoeveelheid werk aan jullie kant.

**Comment by PieterVerheij** [comment]
Laten we uitgaan van dit element:
![image](https://user-images.githubusercontent.com/25430835/62274629-88f25400-b440-11e9-8914-4ffb4c2a5e22.png)

Dan maken we een uitbreiding voor een rondje, die met `position: absolute;` buiten de box geplaatst wordt. Met eerder genoemde oplossing (getriggerd door een modifier) voor equal heights (http://www.lottejackson.com/learning/an-equal-height-grid-using-flexbox) moeten de blokken uitgelijnd kunnen worden. 

@bramhoosemans Vraag is nog wel wat voor icoon jullie zouden willen plaatsen? Wordt dit een redactioneel instelbaar icoon?

**Comment by bramhoosemans** [comment]
Ja, dit wordt een redactioneel instelbaar icoon. Het idee is dat het nummer vervangen kan worden door een 'vinkje'.

**Comment by PieterVerheij** [comment]
Ok, dan maken we twee modifiers op het rondje: `dso-has-counter` en `dso-has-icon` oid.

Heb je voor mij het Sketch bestand van dit ontwerp?

**Comment by bramhoosemans** [comment]
Hierbij een export vanuit Sketch van de gehele pagina:
[Landingspagina aanvragen.zip](https://github.com/dso-toolkit/dso-toolkit/files/3455768/Landingspagina.aanvragen.zip)

**Comment by PieterVerheij** [comment]
@bramhoosemans Nog een vraag over het icoon: gaan dat plaatjes zijn in de zin van png of svg of wordt het een icoon uit het dso-web-font?

**Comment by bramhoosemans** [comment]
@PieterVerheij Geen idee. We gebruiken al een vink icoon in het dso-web-font, dus ik denk dat het daaruit komt.

We zullen de implementatie van iconen nog een keer moeten afstemmen/rechttrekken.

**Comment by PieterVerheij** [comment]
Ok, dan ga ik voorlopig uit van het dso-web-font. Als er plaatjes in de counter geplaatst moeten gaan worden, wordt dat een nieuw issue.

**Comment by tfrijsewijk** [comment]
Na een hoop ruis en onduidelijkheid heb ik de scope beperkt tot puur de stappenteller. Deze is uitgekomen in 8.1.0:
* https://dso-toolkit.nl/8.1.0/components/detail/whitebox-regular--whitebox-regular-counter.html
* https://dso-toolkit.nl/8.1.0/components/detail/whitebox-regular--whitebox-regular-icon.html
* https://dso-toolkit.nl/8.1.0/components/detail/examples.html

De inhoud van de whitebox is destijds keihard (#267)  gespecced en is daarop gemaakt. Er leeft nu een wens dat er andere inhoud in moet komen. Ik zet deze discussie graag voort in een ander issue #327
