### ISSUE TITLE
whitebox uitbreiding

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#327]
In de nieuwe landingspagina komt de white ook weer naar voren. De vraag is hoe vast staan de onderdelen in de white box of kan deze al gebouwd worden met de onderdelen hoe deze nu beschikbaar zijn? 

Zie afbeelding van de implementatie. White box in de banner en de kleinere white boxes. Staat de content van de inhoud vast of is de implementator vrij om deze aan te passen?

![page-1-100_aanvragen](https://user-images.githubusercontent.com/36912722/60017484-1e076d80-9689-11e9-92b5-1f7c311e8cb8.png)

**Comment by PieterVerheij** [comment]
De volgorde, en vooral de marges, van de elementen staat vast. Misschien kunnen we het zo ombouwen dat de implementator vrij is in de volgorde van de knop en tekst, maar dat durf ik niet zo 100% te zeggen. Wat mij wel opvalt is dat er nu in de whitebox een andere buttons-style wordt gebruikt (tertiair, met bolletje).

**Comment by MichielDHVD** [comment]
Ja dat is dus precies mijn vraag. Kan de implementator ook een button styling aanpassen. Of liggen alle onderdelen in de whitebox helemaal vast?

**Comment by PieterVerheij** [comment]
De markup van de styling is standaard. Als je de class van de link verandert van `"btn btn-link"` naar `"btn btn-primary"`, dan verandert gelijk de styling. Waar wij voor moeten zorgen, is dat de marges van de elementen kloppen als een implementator gaat schuiven met de elementen. Vraag is hoeveel vrijheid je een implementator daarin wilt geven.
![image](https://user-images.githubusercontent.com/25430835/60021475-6414ff00-9692-11e9-9808-b3cd92c43c7a.png)

**Comment by tfrijsewijk** [comment]
Worden de whiteboxes zoals in 7.3.0 nog ergens gebruikt?

**Comment by MichielDHVD** [comment]
Jazeker hier zijn deze te bewonderen. 

https://acc.omgevingswet.overheid.nl/home

De grootte whiteboxes hadden nog wat issues waar ik nog een ander issue voor zal aanmaken.

**Comment by tfrijsewijk** [comment]
@MichielDHVD: Is jouw vraag door Pieter beantwoord?

**Comment by MichielDHVD** [comment]
@PieterVerheij  geeft aan dat als er andere knoppen gebruikt worden de styling uit elkaar kan vallen. De vraag is hoe kunnen we ervoor zorgen dat de white box gebruikt kan worden voor meerdere doeleinden. 

Want in de afbeelding van de landingspagina staat een whitebox zonder afbeelding. Betreffende de inhoud van de whitebox zou ik de implementator wel veel vrijheid willen geven.

**Comment by tfrijsewijk** [comment]
>[..] Betreffende de inhoud van de whitebox zou ik de implementator wel veel vrijheid willen geven.

In jouw eerdere specificate in #264 staat iets anders. Daar is een "whitebox component als geheel" besteld. 

Zoals je in jouw eigen specificatie ziet, staat alles zo vast als een huis. Ik weet niet zo goed hoe de toolkit nu een whitebox met een "onbekende" inhoud kan faciliteren

**Comment by MichielDHVD** [comment]
hmm hier was ik al bang voor. Ik hoopte dat er een manier was dat we een component konden hergebruiken die vooral als visuele ondersteuning geldt. Ik wil voorkomen dat er teveel opties/smaakjes komen om content pagina's op te bouwen. 

@bramhoosemans en ik zullen sowieso even samen moeten gaan zitten om te kijken hoe we het systeem zo inrichten dat er geen rare pagina's ontstaan. 

Verder heb ik nog een idee. Dit issue was sowieso als Question opgezet om puur te informeren of deze optie mogelijk was. Dat is dus niet gebleken. 

Is het wel mogelijk om een variatie toe te voegen aan de highlight box deze variatie zal dan dezelfde dropshadow bevatten als de whitebox. @tfrijsewijk 

Als ik antwoord hierop heb ga ik dit issue sluiten.

**Comment by tfrijsewijk** [comment]
In #325 en #326 was er sprake van lichte onduidelijkheid. De componenten werden door elkaar gehaald en er was een change nodig op een component wat niet in die werkvorm bestond.

Samengevat:
* De whitebox zoals deze tot nu toe (8.1.0) bestaat is gemaakt volgens #267.
* In #326 is een change verzocht op een component wat in het aangeleverde ontwerp niet bestaat
* Uiteindelijk is precies de change uitgebracht, andere geluiden zoals "gelijke hoogtes" en "andere inhoud" is niet geimplementeerd

Nu staan de volgende wensen open:
* Whiteboxes naast elkaar moeten even hoog worden. Dit is nu tot zekere hoogte gemaakt dmv. `min-height: 520px`
* Een whitebox moet andere inhoud hebben.

Als ik naar het ontwerp van de nieuwe whitebox kijk, vind ik dat ie veel op de highlightbox lijkt. De vraag die we ons moeten stellen is: wat zien wij voor ons als wij 'whitebox' zeggen.. Dekt de naam eigenlijk wel de lading?

Moeten we highlightbox en whitebox niet fuseren tot 1 component (naamgeving laat ik in het midden: nieuwe naam, of een van de twee aanhouden).

Dit ene component kan met alle modifiers worden aangestuurd
* Modifiers voor achergrond kleuren (geel, wit, groen, transparant, etc)
* Modifiers voor randen (border of dropshadow)
* Modifier met kind element voor de stappenteller (voorstel: laten we 'm status noemen - er kunnen immers ook iconen staan)

Wordt de whitebox zoals deze NU bestaat nog wel geimplementeerd?

**Comment by bramhoosemans** [comment]
Inderdaad erg verwarrend. Door de laatste reactie van Pieter in https://github.com/dso-toolkit/dso-toolkit/issues/326 ging ik ervan uit dat we verder konden bouwen op het bestaande component.

Om eerlijk te zijn snap ik de verschillen niet tussen de whitebox en highlightbox. Deze combineren tot één component en aansturen met modifiers lijkt me een betere oplossing. Alleen zullen we dan de huidige implementaties moeten omgooien (=werk).

Het huidige whitebox component wordt gebruikt op de homepage, zie https://acc.omgevingswet.overheid.nl/home

**Comment by tfrijsewijk** [comment]
Als we de whitebox laten zoals deze nu is, begrijp ik het verschil:
* Whitebox heeft een vast stramien;
* Highlightbox geeft een accent en is vrij in te vullen;

De verwarring begon toen er werd gevraagd naar het vrij invullen van de whitebox, terwijl er een highlightbox ingezet kon worden.

Dus volgens mij hebben we de teller op het verkeerde component gezet.

Aangezien de whitebox in zijn huidige vorm gebruikt wordt (en blijft) gaan we daar niks aan veranderen.

Ik stel voor
* highlight-box van een modifier te voorzien zodat deze dropshadows kan krijgen waardoor de higlightbox overeenkomt zoals in het ontwerp;
* daarbij implementeren we de stappenteller ook voor highlightbox;

Volgens mij kunnen jullie dan maken wat nodig is. Inmiddels zijn jullie al met de sprint begonnen en hebben jullie deze functionaliteit nodig, klopt dat?

**Comment by bramhoosemans** [comment]
Waarschijnlijk ligt het ook deels aan de naamgeving; whitebox klinkt als een algemene naam.

Wij zijn inderdaad al begonnen met de bouw van de pagina. Zoals verwacht zorgen de stappen (whitebox) met een minimale hoogte van 520px voor erg veel witruimte ;) Als we de teller op de highlightbox zetten betekend dat straks extra werk om dit om te bouwen bij een toolkit update. Maar volgens mij wel 'the way to go'. 

We zouden er al op kunnen voorsorteren als de html, classnamen, e.d. bekent zijn... dan ziet het er nu anders uit, maar zal het met een update geen extra werk opleveren. Wat denk jij?

**Comment by tfrijsewijk** [comment]
Iedereen staat open voor een betere naam voor de Whitebox :) al hernoemen we het component alleen al in de documentatie. De markup kunnen we dan onaangetast laten, maar dan hebben we tenminste een andere noemer

Dat laatste is zeker waar. Als jullie voor nu kunnen accepteren dat het er "niet uitziet" kan ik markup uitgeven waar we de toolkit op aan laten sluiten. Dan kan er maandag/dinsdag wel een release uit

**Comment by bramhoosemans** [comment]
Net besproken met de ontwikkelaars en we gaan volgende sprint pas weer een toolkit update doorvoeren. Als deze aanpassing er dan in zit kunnen we het direct verwerken.

Geen bloedspoed dus..

**Comment by tfrijsewijk** [comment]
Dus markup is voldoende? Als we mijn suggestie gaan doen, moeten de implementatoren dus het highlightbox component gaan implementeren

**Comment by bramhoosemans** [comment]
Ik snap je vraag 'is markup voldoende?' niet helemaal. Zoals ik het begrijp is dat we bij een volgende release niet de whitebox moeten gebruiken, maar een aangepaste highlightbox.

Dit is wat mij betreft prima. Hier houden we dan rekening mee in de implementatie van de volgende toolkit release.

**Comment by tfrijsewijk** [comment]
Prima!

Dan sluit ik dit issue. In een ander issue zullen we de stappenteller voor de highlight-box maken
