### ISSUE TITLE
Formulier file group

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#328]
Bij het uploaden van documenten moeten we kunnen aangeven of een document vertrouwelijke informatie bevat (geheim). Op dit moment wordt het 'label' component gebruikt; de vraag is of deze uitgebreid kan worden met deze functionaliteit?

Wat zijn jullie ideeën en/of voorstellen?

------

![102_nieuwe-stijl-stap-5-documenten--vertrouwelijk](https://user-images.githubusercontent.com/598735/60019709-d2f05900-968e-11e9-8d4d-f17d2de2e56b.png)

**Comment by PieterVerheij** [comment]
Wat is de interactie?
- je uploadt het bestand
- in het overzicht krijg je de checkbox 'Geheim'

Dan is het grijze element toch opgebouwd uit een link, checkbox met label en een sluitenkruis? Of interpreteer ik de vraag verkeerd?

**Comment by bramhoosemans** [comment]
Hoi Pieter,

Klopt helemaal. Het gaat om het grijze element. Enige toevoeging die ik heb is dat de checkbox optioneel is, dus bij de ene vraag kun je wel documenten als geheim markeren en bij de andere niet.

1. je upload één of meerdere bestanden
2. als de bestanden zijn geladen verschijnen ze op het scherm
3. de gebruiker kan middels een checkbox aangeven of deze vertrouwelijke informatie bevat

**Comment by tfrijsewijk** [comment]
Het grijze element lijkt op het label component, maar er is wel de nodige CSS nodig geweest om het label component er zo uit te laten zien.

Samen met de nodige CSS om de _inhoud_ (tekst + checkbox) te stijlen, rechtvaardigd dit niet een eigen component? Misschien wel een eigen werkvorm in een formulier?

**Comment by bramhoosemans** [comment]
Mee eens. Ik ga hier nog even puzzelen wat de definitieve vorm wordt, maar mogelijk dus een eigen component.

**Comment by tfrijsewijk** [comment]
Mijn voorstel is om het een component _binnen het formulier_ van te maken, ik leg er nog even de nadruk op :)

**Comment by MichielDHVD** [comment]
Op dit moment is ook de enige plek waar dit component zou voorkomen ook binnen het formulier het gaat namelijk om het uploaden van documenten. Ik ga dit component ook even verwerken in het samenwerkingsontwerp @bramhoosemans. Want als dit alleen plaats vind binnen een formulier moet ik ervoor zorgen dat ik ook een formulier in het ontwerp gebruik.

**Comment by bramhoosemans** [comment]
Hey, het lijkt me prima om een eigen component binnen het formulier hiervoor te ontwikkelen. Hierbij stuur ik je het actuele ontwerp als Sketch Measure export, zie zip bestand. Meer info vind je op https://github.com/utom/sketch-measure

Export:
[Documenten potentieel vertrouwelijk V5.zip](https://github.com/dso-toolkit/dso-toolkit/files/3338289/Documenten.potentieel.vertrouwelijk.V5.zip)

Flow voor uploaden van documenten (optioneel met checkbox vertrouwelijk & waarschuwing icoon):
[Documenten upload vertrouwelijk.pdf](https://github.com/dso-toolkit/dso-toolkit/files/3338288/Documenten.upload.vertrouwelijk.pdf)

**Comment by bramhoosemans** [comment]
Nemen jullie dit component mee in de sprint planning?

**Comment by tfrijsewijk** [comment]
@bramhoosemans: Jouw attachments bevatten het woord "vertrouwelijk", je weet dat dit een publiekelijk kanaal is? Het hele internet kan jouw attachments downloaden

**Comment by bramhoosemans** [comment]
@tfrijsewijk haha het gaat hier inderdaad om de functionaliteit.

**Comment by tfrijsewijk** [comment]
Dit component is uitgekomen in 8.0.0:
* https://dso-toolkit.nl/8.0.0/components/detail/group-files.html
* https://dso-toolkit.nl/8.0.0/components/detail/form--form-horizontal.html
* https://dso-toolkit.nl/8.0.0/components/detail/aanvragen-file-upload.html

**Comment by bramhoosemans** [comment]
Een aantal opmerkingen:
- Er staat een extra 4px margin boven en onder op de filename, waarom is dit? In het ontwerp zie de line-height overal 24px met 8px margin eromheen (7px + 1px border).
- Een lange bestandsnaam loopt nu tegen de checkbox aan; kun je hier 8px tussen laten?
- De iconen lijken erg groot, met name het kruisje. Dit mag 24 x 24px worden.
- Is er een reden dat het kruisje groen is? Kunnen we deze binnen het component niet zwart kleuren (#191919)?
- De unordered list overschrijft de margin van de paragraaf en heeft een eigen margin bottom van 12px. Volgens mij is het consistenter om de 16px van de < p > te behouden en ook 16px margin bottom te hanteren.

Screenshots:
<img width="1286" alt="Schermafbeelding 2019-07-23 om 11 25 43" src="https://user-images.githubusercontent.com/598735/61701666-d71b9f00-ad3e-11e9-9db5-1ee9a7403148.png">
<img width="1425" alt="Schermafbeelding 2019-07-23 om 11 29 59" src="https://user-images.githubusercontent.com/598735/61701688-dc78e980-ad3e-11e9-8970-33f1d496d379.png">

**Comment by bramhoosemans** [comment]
Volgens mij gaat er ook iets mis met de uitlijning van de 'volgende' knop...

<img width="1269" alt="Schermafbeelding 2019-07-23 om 11 47 00" src="https://user-images.githubusercontent.com/598735/61702171-a25c1780-ad3f-11e9-8723-8272687d6a20.png">

**Comment by tfrijsewijk** [comment]
Hi Bram:

De `margin-top` + `margin-bottom`: is gezet om het geheel met het icoon te laten lijnen.. Maar we hebben niet goed naar het ontwerp gekeken, daar is de boel op 40px height gezet. Als we het icoon kleiner maken kan de marge weg en dan lijnt het alsnog. Nu is een file entry 49px hoog, dus dat ene pixeltje poetsen we dan ook wel weg;

Lange filename: Goed gevonden, we zullen `.dso-filename` een `padding-right: 8px;` geven;

Icoon: maken we "DSO zwart";

margin lists: Dit is een lijst binnen het Alert component. Het Alert component maakt impliciet weer gebruik van het Rich content component (dmv. een sass extend). Ik ben het met je eens dat de margins niet goed gaan, maar ik wil dit oplossen in een ander issue

Het uitlijnen van de volgende knop: Het leek mij het beste dit component een onderdeel te laten zijn van het formulier. En dit is hoe de knoppen onder een horizontaal formulier uitlijnen. De "volgende" knop is geen onderdeel van het Files component, maar van het formulier

**Comment by tfrijsewijk** [comment]
Ik heb #346 aangemaakt waarin we jouw bevindingen zullen aanpakken. Dit betreft alleen CSS changes, de markup zal gelijk blijven. Implementatoren kunnen dus met dit component aan de slag. Ik heb voor vrijdag een release in gedachten waar dit mee zal komen. Na een package upgrade door de implementoren zullen jouw bevindingen doorkomen

**Comment by bramhoosemans** [comment]
Hi Thomas,

Dank voor je reactie. In het ontwerp gebruiken we momenteel twee icoon formaten, namelijk 24 en 32px. We moeten volgens mij samen eens afstemmen hoe we beter met iconen omgaan in de Toolkit. Antoinette is bezig met een inventarisatie, dus dat komt t.z.t. wel.

Wat betreft de marge lists, prima.

De uitlijning van de volgende knop snap ik nog niet helemaal. Die zou altijd rechts in de accordeon moeten staan.

**Comment by tfrijsewijk** [comment]
Helderheid over de iconen wordt zeer gewaardeerd. Om dit moment maken we gebruik van SVG's die we inlinen dmv. een build proces, FontAwesome, ons eigen icon font face, en ik geloof dat er nog ergens een Bootstrap glyph zwerft :)

Mijn voorkeur gaat uit naar 1 bron. Deze iconen zijn beschikbaar dmv een mixin en een class a la FontAwesome ([we zijn al begonnen](https://dso-toolkit.nl/8.0.0/components/detail/icon.html), we hebben nu bijvoorbeeld `di di-cross`).

>De uitlijning van de volgende knop snap ik nog niet helemaal. Die zou altijd rechts in de accordeon moeten staan.
Formulier elementen moeten altijd in een `form` staan. Wij kennen twee formulier werkvormen: [vertical](https://dso-toolkit.nl/8.0.0/components/detail/form--form-vertical.html) en [horizontal](https://dso-toolkit.nl/8.0.0/components/detail/form--form-horizontal.html).

Als we kunnen stellen dat een formulier in een accordion de formulier knoppen altijd rechts moeten uitlijnen, maken we dat natuurlijk graag

**Comment by bramhoosemans** [comment]
Oei. Ik wist dat het proces nog niet gestroomlijnd was, maar 3 verschillende bronnen is inderdaad niet wenselijk! Ik neem het mee in het UX overleg met de andere designers.

Volgens mij gebruiken we de submit knoppen van een formulier nu overal rechts... zie screenshot (helaas werkt de INT omgeving met nieuwe accordeon stijl nu niet). Ik ben van plan ergens de komende sprint(s) het gebruik van formulieren na te lopen. Mogelijk volgen daar wat optimalisaties uit ;)

Voor nu: als het al zo stond maar laten staan.

**Comment by tfrijsewijk** [comment]
Prima, wacht ik het uitlijnen van de knop af. Overigens is dat geen major change en kan opgenomen worden in de toolkit zonder dat de implementator zijn markup aan moet passen

Overigens ben ik dan wel benieuwd hoe die knoppen rechts zijn komen staan, daar voorziet de toolkit namelijk niet in. Toen het formulier-component werd gemaakt is er eindeloos gediscusseerd over de markup, css en gebruikerservaring
