### ISSUE TITLE
Uitbreiding van templates

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#329]
Om het verband tussen de gebouwde omgevingen en de toolkit beter te illustreren. Moeten er templates komen die meer in lijn liggen met de huidige stand van zaken. 

Ook moeten deze templates gechecked worden of deze opgebouwd zijn volgens best practices. 

Dit issue zal kijken naar templates voor 

Aanvragen, Checken en Samenwerken.

**Comment by tfrijsewijk** [comment]
Opgeleverd in 8.3.0
