### ISSUE TITLE
release 8.0.0

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#331]
https://github.com/dso-toolkit/dso-toolkit/milestone/25

**Comment by tfrijsewijk** [comment]
Omdat het plannen van een release niet transparant was (namelijk Michiel en ik dmv. prive berichten) maak ik vanaf nu voor elke release een Pinned issue met een link naar de milestone.

@MichielDHVD: Wat moet er in de komende release zitten?

**Comment by MichielDHVD** [comment]
Uitstekend plan! 

#298 
#325 
#326 
#327 

Hebben de voorkeur voor dit release. Ik weet niet of deze allemaal mogelijk zijn. 

@bramhoosemans Is er voor jouw nog een prioritering. Ik weet dat @djangoblok nog zit te wachten op #298

**Comment by bramhoosemans** [comment]
Fijn! Ik heb een toevoeging; in de planning gaan wij (PR12) eerder aan de slag met "potentieel vertrouwelijk" en zou die iets hoger in prio willen hebben ;)

1. Zoekveld met optionele button - https://github.com/dso-toolkit/dso-toolkit/issues/298
2. Document vertrouwelijk - https://github.com/dso-toolkit/dso-toolkit/issues/328
3. Landingspagina - Highlight box variaties - https://github.com/dso-toolkit/dso-toolkit/issues/325
4. Landingspagina - Stappen rondje boven whitebox - https://github.com/dso-toolkit/dso-toolkit/issues/326
5. Landingspagina - whitebox uitbreiding - https://github.com/dso-toolkit/dso-toolkit/issues/327

**Comment by tfrijsewijk** [comment]
Ik heb de volgende verdeling gemaakt: https://github.com/dso-toolkit/dso-toolkit/milestones?with_issues=no

Dat betekent woensdag en maandag een release. Wanneer begint de sprint waar jullie functionaliteit uit de toolkit willen gebruiken? Ik heb de release van woensdag ingepland als "spoedje" zodat jullie ermee kunnen beginnen, maar mijn voorkeur gaat naar natuurlijk naar 1 release

**Comment by MichielDHVD** [comment]
Volgens mij is 15 juli op tijd voor het team dus dat betekent dat we er mogelijk 1 release van kunnen maken. 

Klopt dit @bramhoosemans ?

**Comment by bramhoosemans** [comment]
Je zou er prima 1 release van kunnen maken. Bij ons start de nieuwe sprint op dinsdag (morgen) en duurt 2 weken. Deze sprint gaan we geen toolkit update doorvoeren, dus als alle wijzigingen voor de volgende sprint verwerkt zijn is het top!

**Comment by tfrijsewijk** [comment]
Ok, deal. Ik plan deze release dan in voor maandag 22 juli

**Comment by tfrijsewijk** [comment]
Na overleg met @MichielDHVD is besloten deze release in te krimpen. Wat er niet in past komt morgen de 23e uit

**Comment by tfrijsewijk** [comment]
Zojuist is 8.0.0 uitgekomen
