### ISSUE TITLE
Variabele voor DSO's icon-font mist

### ISSUE THREAD

**Issue by hoest** [dso-toolkit/dso-toolkit#333]
Deze is noodzakelijk als je de toolkit wilt gebruiken vanuit eigen `SCSS`.

Introduceren van `$dso-icon-font-path` hiervoor nodig.

**Comment by tfrijsewijk** [comment]
Uitgekomen in 7.3.1. Deze versie staat nog niet op dso-toolkit.nl maar wel op npm
