### ISSUE TITLE
Het is niet vanzelfspreken hoe de layout gebruikt moet worden. (PI12)

### ISSUE THREAD

**Issue by antek-drzewiecki** [dso-toolkit/dso-toolkit#335]
Hallo,

Bij het inlezen over het layout is het niet geheel duidelijk hoe deze gebruikt moet worden. 

De bijgevoegde afbeelding omschrijft bijvoorbeeld niet de class prefixes die gebruikt moeten worden voor een kolom. Ook staan geen hands on voorbeelden om direct mee aan de slag te gaan. 
![layout](https://dso-toolkit.nl/7.3.0/docs/layout/layout_1.png)

Misschien is het makkelijker om de grid tabel over te nemen zoals https://getbootstrap.com/docs/4.0/layout/grid/#grid-options .

**Comment by antek-drzewiecki** [comment]
Ik zag dat er ook verwezen wordt naar bootstrap. Dus wellicht is dit niet nodig.

**Comment by MichielDHVD** [comment]
We zijn bezig om de structuur en documentatie van de toolkit te verbeteren en ik denk dat als het gaat om de layout dat we daar qua documentatie inderdaad een verbeteringslag kunnen maken. 

Misschien is het slimmer om de bootstrap specifieke documentatie hoger te zetten want nu staat deze helemaal onderaan. 

Voor mijn beeldvorming, vanuit welk team ben je aangesloten op het DSO?

**Comment by tfrijsewijk** [comment]
Hi @antek-drzewiecki, welkom!

Ik neem aan dat je het alleen over https://dso-toolkit.nl/7.3.0/docs/layout.html hebt? De enige verwijzing die ik over bootstrap tegenkom is halverwege een zin het woordje "bootstrap": ik ben het met je eens dat het weinig informatief is.

Je komt zelf met een link naar de bootstrap 4 documentatie, terwijl de DSO Toolkit is gebasseerd op 3.3.7.. Dus hier zijn zeker kansen voor verbetering

@MichielDHVD: De Layout pagina heeft op alle vlakken verbetering nodig:
* Teksten zijn niet toereikend/niet meer van toepassing;
* Afbeeldingen zijn achterhaald;

Wil jij hier verdere beeldvorming aan geven?

**Comment by MichielDHVD** [comment]
Ja ik zal dit op mij nemen. 

Zal wel een stretch goal voor mij dit increment er zijn meerdere onderdelen in de toolkit waar ik naar moet kijken. Maar mogelijk zal ik deze prio wel omhoog schijven. Voor het goed gebruik van de toolkit is dit misschien een van de belangrijkste.

**Comment by bramhoosemans** [comment]
@MichielDHVD Het lijkt me slim om de documentatie op te pakken met issue https://github.com/dso-toolkit/dso-toolkit/issues/420. In dat geval kan deze gesloten worden.

**Comment by MichielDHVD** [comment]
Prima dan sluit ik deze en focus is op #420.
