### ISSUE TITLE
Full width Image

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#336]
In de landingspagina maar ook op de huidige homepage pagina. Zijn er afbeeldingen die niet full width zijn. 

Nu hebben we een tab full width. Maar daar zie ik alleen de class dso-featured waarmee een groene background mee gerealiseerd wordt. 

Het lijkt me slim dat de toolkit een oplossing biedt om makkelijk full width afbeeldingen te implementeren. Hoe kunnen we dit het beste aanpakken @tfrijsewijk

**Comment by tfrijsewijk** [comment]
Ik weet niet precies waar je het over hebt, kun je een ontwerp leveren? Dan hebben we wat tastbaars om over te praten

**Comment by bramhoosemans** [comment]
@MichielDHVD Kan jij dit verder duiden?

**Comment by MichielDHVD** [comment]
Op de https://acc.omgevingswet.overheid.nl/  staat een full width image en voor de informatie pagina wordt ook een image gebruikt over de volle breedte van een pagina. 

![image](https://user-images.githubusercontent.com/36912722/62923318-c5617080-bdad-11e9-921a-ac8411074371.png)

De verschillende gebruikerstoepassing hebben nu volledig toegang tot de breedte van het scherm deze staat niet meer vast op 1200px. Moeten er vanuit de toolkit een oplossing aangeboden worden om fullwidth images zo mooi mogelijk te weergeven. 
Zelfs op gigantisch brede schermen (of meer dan 1 scherm). Vanuit de documentatie zouden wij dan ook regels moeten opstellen over het gebruiken van fullwidth images. 

Mijn vraag is wat kunnen wij bieden vanuit de toolkit/css is daar een consistentie in aan te bieden.

**Comment by bramhoosemans** [comment]
Ter aanvulling, voor de bovenstaande pagina voegen we nu zelf de volgende css toe:

`.banner-image {
background: url('../images/hands-on-trackpad.jpg') no-repeat;
    background-size: cover;
    background-position: center;
    background-color: #ebf3e6;
    height: 400px;
    padding-top: 2rem;
    margin-bottom: 2rem;
}`

**Comment by PieterVerheij** [comment]
Praktisch gezien gaat het altijd om een div met een achtergrondafbeelding? 

Dan kan het alleen een illustratieve afbeelding zijn, niet een afbeelding die informatie overdraagt (er mag bv. geen tekst in de afbeelding staan).

**Comment by tfrijsewijk** [comment]
@bramhoosemans Dank voor de CSS.

Ik neem aan dat een `.banner-image` buiten het grid staat en dus `body` breed is. Dan zit ik aan ongeveer het volgende component te denken:

```html
<div class="dso-banner-image" style="background-image: url('../images/plaat.jpg');></div>
```

```css
.dso-banner-image {
  background-repeat: no-repeat;
  background-size: cover;
  background-position: center;
  background-color: #ebf3e6;
  height: 400px;
  padding-top: 2rem;
  margin-bottom: 2rem;
}
```

Ik zie op https://acc.omgevingswet.overheid.nl/ ook een brede plaat, maar met andere styling. Bestaan er meerdere werkvormen?

**Comment by PieterVerheij** [comment]
Inline css is niet aan te raden. Een alternatied is (als het cms dat toestaat) om er een extra class aan te hangen. Dus:

`<div class="dso-banner-image bg-img-12345"></div>`

```
.bg-img-12345 {
background-image: url('../images/plaat.jpg');
}

```
```
.dso-banner-image {
  background-repeat: no-repeat;
  background-size: cover;
  background-position: center;
  background-color: #ebf3e6;
  height: 400px;
  padding-top: 2rem;
  margin-bottom: 2rem;
}
```

**Comment by MichielDHVD** [comment]
Er zijn verschillende vragen gesteld. 

@PieterVerheij De afbeeldingen mogen dan alleen decoratief / illustratief zijn?  Dat klopt helemaal er mag geen informatie via de afbeeldingen overgedragen worden. 

@tfrijsewijk Zijn er meerdere werkvormen? Op dit moment zijn er twee werkvormen, degene waarvan Bram de CSS heeft aangeleverd en degen op de acc omgeving. 
Daarom het verzoek om hier een oplossing voor in de toolkit te plaatsen. Zodat we consistentie kunnen bieden, plus belangrijke pointers om het behoud van kwaliteit te garanderen.

**Comment by bramhoosemans** [comment]
We gaan een element maken dat over de hele breedte komt, maar in een container zit

**Comment by tfrijsewijk** [comment]
En de suggestie van [Pieter](https://github.com/dso-toolkit/dso-toolkit/issues/336#issuecomment-521305867) uitvoeren. We hebben zojuist een argument gevonden om _wel_ CSS buiten de toolkit om te gebruiken :-)

**Comment by tfrijsewijk** [comment]
Ik heb de pagina uit het screenshot nagemaakt, maar ik vind toch wel dat er veel verschillen in verticale marges is. Ik heb zelfs ergens een `<br>` geplaatst, maar eigenlijk wil je dat niet..

Zodra ik de release heb uitgerold naar dso-toolkit.nl kunnen we hier over bomen. De oplossing is een modifier class op een `.row`, dus minimale change aan jullie kant :)

**Comment by tfrijsewijk** [comment]
Opgeleverd in 8.2.0: https://dso-toolkit.nl/8.2.0/components/detail/stappenteller.html
