### ISSUE TITLE
Buttons verbeteringen

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#337]
Huidige primaire en secondaire buttons hebben een te grote padding en line-height. Daarnaast vraag ik me af waarom er een 1px margin aan de onderkant wordt meegegeven?

Huidige situatie:
- Padding 0 47px + 1px border mag veel kleiner
- Line height staat extreem hoog 46px
- Margin-bottom 1px

Mag worden:
- Padding 0 15px + 1px border
- Line height 24px (font size 1em = 16px)

Zie bijgevoegd screenshot en Measure export voor detail specificaties.
[Buttons.zip](https://github.com/dso-toolkit/dso-toolkit/files/3396773/Buttons.zip)

**Comment by tfrijsewijk** [comment]
De `margin-bottom`: geen idee waarom, maar ik ben er niet aan gehecht :-)

Waarom wil je de line-height anders? Ik begrijp dat het een extreem hoog is maar volgens mij is dit een truuk om het icoon van de tertiare button over het verticale vlak te laten lijnen. De primary en secundary buttons hebben dit ook gekregen zodat de 3 verschillende buttons naast elkaar netjes uitlijnen.

Maar als je er graag vanaf wilt, kunnen we er natuurlijk naar kijken. 

De Measure-export geeft de volgende maten:

![image](https://user-images.githubusercontent.com/9696261/63024268-2f117580-bea7-11e9-8320-6d0f4442e409.png)

Ik kan die 12px nergens kwijt. We zijn gebasseerd op het 8px grid. 15px + 1px kan ik nog inkomen, maar voor 12px moeten we ergens 4px vandaan halen. Zou je hier nog naar willen kijken?

**Comment by bramhoosemans** [comment]
De reden dat ik de line-height wil aanpassen is om buttons flexibeler te maken. Op dit moment wordt de breedte veelal bepaald door het grid (x kolommen). En bij lange(re) button labels loopt de tekst erbuiten. Zie gewenste situatie hieronder.

De 12px komen voort uit een button hoogte van 48px en een line-height van de tekst/icoon van 24px...

<img width="679" alt="Schermafbeelding 2019-08-16 om 11 34 32" src="https://user-images.githubusercontent.com/598735/63158597-e3330d80-c019-11e9-8e18-0dd14c76f2b4.png">

**Comment by tfrijsewijk** [comment]
Als we 12px gaan aanhouden, stappen we af van [het 8px grid](https://dso-toolkit.nl/8.1.0/docs/layout.html#verticale-layout). Wat ik prima vind, maar het is wel iets om even bij stil te staan en vooral: Documentatie aanpassen of expliciet aangeven dat de knoppen niet aan het 8 punt grid voldoen

**Comment by bramhoosemans** [comment]
Dat zie ik toch anders; de huidige knop is gestyled op 48px wat past in het 8px grid. De huidige line-height van 46px is een hack om icoon uitlijning te optimaliseren (begrijp ik) en valt ook niet in het 8px grid. Door deze optimalisatie zouden we flexibeler met knoppen kunnen omgaan.. zodat labels ook over meerdere regels lopen als de horizontale ruimte beperkt is.

Het lijkt me prima om dit mee te nemen in de documentatie van het button component.

**Comment by tfrijsewijk** [comment]
Ik begrijp het: De lineheight van 46px + 2 keer een border van 1px (onder en boven) zorgt ervoor dat de hele button op 48px komt (en dus in het 8px grid past).

[Jouw sketch export](https://github.com/dso-toolkit/dso-toolkit/issues/337#issuecomment-521243660) heeft zet 12 (padding-bottom) + 12 (padding-top) + 24 (line-height) is nog steeds 48. `</groep-3>` :-)

**Comment by tfrijsewijk** [comment]
Als gevolg van dit issue zou de button 40px hoog zijn. Maar in #377 vraag je om een `btn-sm` modifiers om de buttons van 48px naar 40px te zetten.

Deze issues conflicteren met elkaar. Wil je dat de `btn-sm` de knop van 40px naar 32px zet? Hoe zie je deze twee issues samen?

**Comment by bramhoosemans** [comment]
> Ik begrijp het: De lineheight van 46px + 2 keer een border van 1px (onder en boven) zorgt ervoor dat de hele button op 48px komt (en dus in het 8px grid past).
> 
> [Jouw sketch export](https://github.com/dso-toolkit/dso-toolkit/issues/337#issuecomment-521243660) heeft zet 12 (padding-bottom) + 12 (padding-top) + 24 (line-height) is nog steeds 48. `</groep-3>` :-)

Hoezo worden buttons door dit issue 40px hoog?

**Comment by tfrijsewijk** [comment]
Geen idee. Typisch gevalletje maandag

**Comment by PieterVerheij** [comment]
Ik denk door deze redenering:
De Measure-export geeft de volgende maten:

image

**Comment by PieterVerheij** [comment]
Die margin-bottom is er ooit opgekomen icm met uitlijning met andere elementen. In welke context weet ik niet meer.

**Comment by PieterVerheij** [comment]
Aanpassing: 
padding: 12px 16px;

Bij line-height: 16px is de hoogte van de buttons 40px
Bij line-height; 24px is de hoogte van de buttons 48px

Voorlopig staat de line-height op 24px;

**Comment by tfrijsewijk** [comment]
Uitgekomen in 8.4.1: https://dso-toolkit.nl/8.4.1/components/detail/buttons.html
