### ISSUE TITLE
Buttons in alerts

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#339]
Nieuwe toevoeging van buttons in sectieberichten (alerts). Naast navigatie links willen we ook een button component in sectieberichten gebruiken om acties uit te voeren.

Specificaties:
[Buttons.zip](https://github.com/dso-toolkit/dso-toolkit/files/3396773/Buttons.zip)

![buttons-in-sectieberichten](https://user-images.githubusercontent.com/598735/61289958-f0669d80-a7ca-11e9-853c-5fe5f68ed0d9.png)

**Comment by tfrijsewijk** [comment]
Wat is de hover state van de andere 3 alerts? En is focus dezelfde kleur als hover?

**Comment by bramhoosemans** [comment]
In het ontwerp heb ik de volgende waarden opgenomen:
- Normaal 5 procent #191919 oftewel rgba(25, 25, 25, 0.05)
- Hover 20 procent #191919 oftewel rgba(25, 25, 25, 0.2)

Focus states zijn een onderwerp waar we momenteel mee bezig zijn en willen we generiek doorvoeren. Voor nu is focus dezelfde kleur als hover prima.

**Comment by tfrijsewijk** [comment]
Uitgekomen in 8.4.1: https://dso-toolkit.nl/8.4.1/components/detail/alert.html
