### ISSUE TITLE
Dropdown Button Redesign

### ISSUE THREAD

**Issue by Poofy83** [dso-toolkit/dso-toolkit#34]
Aanpassingen voor de dropdown button

padding boven/onder 8px;
padding links/recht 16px;

Radius compleet afgerond. 

Font-size 20px en Bold

![image](https://user-images.githubusercontent.com/5871330/37093564-1047618a-2210-11e8-8694-b32e8c0ab080.png)

/Original reporter: Michael

**Comment by Poofy83** [comment]
Gezien de comments versus de bijgesloten plaat, is dit wat je in gedachte had?

![image](https://user-images.githubusercontent.com/5871330/37093597-2c984a16-2210-11e8-86ef-958d7520cdce.png)

/Original commenter: Thomas - 28-02-18

**Comment by VolleMelk** [comment]
@MichielDHVD Ik denk dat bovenstaande vraag aan je is ontschoten, vandaar een kleine ping.

Zoals je ziet is onze uitwerking anders dan in het ontwerp, aangezien wij de padding van 16px hebben meegenomen in de berekening. Hierdoor is de knop een stuk breder geworden.

De vraag is, waar staat die padding van 16px voor? De knop heeft een border-radius van 24px, binnen de border is er over het horizontale vlak binnen de border al 10px padding. Daarbij nog eens 16px?

Ik vermoed dat je de kleinere variant uit jouw ontwerp wilt, maar daar hebben wij te weinig exacte gegevens voor. Kun je deze verder aanvullen?

**Comment by MichielDHVD** [comment]
@VolleMelk Hoe die 16px daar komt is een uitstekende vraag, ik heb hier een fout gemaakt. Ik heb hier interpretatie fout gemaakt van het ontwerp. 

Die 16px is gewoon compleet fout, de standaard styling van de buttons is alles wat hier nodig is. De styling is hetzelfde als de styling van de secundaire button bij de component buttons. Meer is er niet nodig. 

Excuses voor de verwarring.

**Comment by VolleMelk** [comment]
@MichielDHVD: Dus visueel wordt het een btn-default met een caret rechts van de tekst? Dit is dus geen smalle button zoals deze in het eerste ontwerp staat (check, check dubbelcheck ;-))

Hoe vind je de styling van het contextmenu wat uitklapt van de eerste opzet zoals https://www.dso-toolkit.nl/unstable/components/detail/dropdown-button.html ?

@Poofy83: Kun jij kijken of we de caret uit Ton's `Icons.zip` als icoon hebben?

**Comment by MichielDHVD** [comment]
@VolleMelk  Nee dit is inderdaad _geen_ small button. 

En de styling van het context menu is prima valt mooi samen met de rest. Afgeronde hoeken plus  hover states zijn ook in lijn met de rest dus prima.

**Comment by Poofy83** [comment]
@VolleMelk Ik heb gekeken of er een 'caret' icoon in de set zit, en dat is niet het geval.

**Comment by VolleMelk** [comment]
Ok, dan leveren we 'm op met de FA icon. Mocht er een DSO caret gewenst zijn, kan dat (zonder breaking changes) in de volgende versie geregeld worden
