### ISSUE TITLE
Accordeon titels met koppen

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#340]
In de huidige accordeon implementatie worden een H3 (20px) gebruikt voor de titels. Daarbij is staat de line-height extreem hoog op 45px, waardoor als de titel over meerdere regels loopt er grote gaten ontstaan.

Om de hiërarchie van de pagina in stand te houden (zie afbeelding) zal de accordeon een H4 (16px) moeten hebben met de daarbij horende line-height van 24px.

Specificaties: 
[Accordeon.zip](https://github.com/dso-toolkit/dso-toolkit/files/3396831/Accordeon.zip)

<img width="793" alt="Schermafbeelding 2019-06-27 om 15 32 44" src="https://user-images.githubusercontent.com/598735/61290710-ce6e1a80-a7cc-11e9-9fb7-35ade3dd9c1d.png">

**Comment by tfrijsewijk** [comment]
De stelling _[..] zal de accordeon een H4 (16px) moeten hebben [..]_ is te beperkt: Een accordeon kan immers ook in een accordeon zitten. Wordt het dan geen `h5`?

Volgens mij doen we er beter aan elk type kop in de accordeon toe te staan. We zullen de line-height troubles fixen en een extra variant met een kop opnemen zodat deze gewaarborgd blijft

**Comment by bramhoosemans** [comment]
Helemaal goed om mogelijk te maken dat er verschillende headings in het component gedefineerd kunnen worden. Op dit moment wijkt de tekstgrootte af van de verwachte heading; vandaar dit issue.

**Comment by tfrijsewijk** [comment]
Nu ik dit issue nog een keer lees, is het nu de bedoeling dat er ook andere font-sizes zijn als er andere headings worden gebruikt? Of is de specificatie uit #307 leidend? Ongeacht heading altijd 20px? Op die manier kan er een semantisch kloppende pagina gemaakt worden.

Of interpreteer ik de wens nu verkeerd?

**Comment by bramhoosemans** [comment]
Wat mij betreft zouden we de headings in de accordeon met een vaste font-size kunnen stijlen, zodat de semantiek kloppend blijft. Ongeacht heading zou ik dan de volgende waardes willen:
- font-size: 16px; (1em?)
- line-height: 24px;

**Comment by tfrijsewijk** [comment]
Opgeleverd in 8.3.0: https://dso-toolkit.nl/8.3.0/components/preview/accordion.html
