### ISSUE TITLE
Loaders: spinner en progress bar

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#341]
In de toolkit zit momenteel een Bootstrap progress bar (die we volgens mij nog niet toepassen in de applicaties), maar ontbreekt een spinner. We hebben een visie ontwikkeld omtrent het gebruik van loaders, zie bijgevoegde afbeelding.

In PR12 is destijds een eigen spinner gebouwd o.b.v. een Fontawesome icoon (circle-notch); deze graag opnemen in de Toolkit zodat andere teams er ook gebruik van kunnen maken.

Specificaties: 
[Loaders.zip](https://github.com/dso-toolkit/dso-toolkit/files/3397223/Loaders.zip)

![Loaders](https://user-images.githubusercontent.com/598735/61297539-ba321980-a7dc-11e9-9614-fa64c243f8ff.png)

**Comment by MichielDHVD** [comment]
@tfrijsewijk Heb jij een idee hoe we dit toepasselijk in de toolkit kunnen plaatsen. Want in principe is het enigste wat we kunnen doen is de assets aanbieden en de implementatie verder is puur in handen van de developer. Is dit dan een component of documentatie?

**Comment by PieterVerheij** [comment]
Vgl. https://patternlab-amsterdam.infoprojects.nl/?p=viewall-atoms-progress-indicator

Ik zou zeggen een compontent: wij bepalen de markup (gebruikmakend van bij voorkeur het Fontawesome icoon) en dan kunnen de developers dat implementeren. Qua markup zal het allemaal niet zo spannend zijn.

De uitdaging zit hem in het implementeren van de juiste loader door de developer. Weet je bv. vantevoren al hoe lang iets gaat duren?

**Comment by tfrijsewijk** [comment]
Prima. Dus in dit issue passen we ook de progress bars aan, volgens aangeleverd Measure export?

**Comment by bramhoosemans** [comment]
@tfrijsewijk ja, deze mag worden aangepast volgens aangeleverd Measure export.

**Comment by PieterVerheij** [comment]
Ik heb het gebouwd, gebruikmakende van het fa icoon circle-notch. Echter: bij animatie blijkt het icoon niet helemaal goed te zijn: hij wiebelt een beetje (want het is niet goed gecentreerd of de breedte en hoogte zijn niet gelijk).

Dit is een known-issue: https://github.com/FortAwesome/Font-Awesome/issues/15396

**Comment by tfrijsewijk** [comment]
Uitgekomen in 8.5.0:
* https://dso-toolkit.nl/8.5.0/components/detail/progress-bar.html
* https://dso-toolkit.nl/8.5.0/components/detail/progress-indicator.html
