### ISSUE TITLE
Inline radios met error heeft teveel ruimte tussen keuzes en foutmelding

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#342]
Als radio buttons inline gebruikt worden blijft er 16px margin-bottom op staan. Hierdoor staan validatie meldingen te ver naar beneden en is het lastig te relateren. Wens is om deze margin-bottom weg te halen als radio buttons naast elkaar worden weergegeven.

![Screenshot from 2019-07-18 12-08-14](https://user-images.githubusercontent.com/598735/61452157-70237200-a95b-11e9-925c-e39bf9a65946.png)

**Comment by tfrijsewijk** [comment]
Ik pak 'm op en maak meteen extra varianten voor de inline-radio zodat het gewaarborgd is in de CSS regressie testing.

**Comment by tfrijsewijk** [comment]
Fixed in 8.2.0: https://dso-toolkit.nl/8.2.0/components/detail/group-radios.html
