### ISSUE TITLE
8.1.0 Release

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#345]
https://github.com/dso-toolkit/dso-toolkit/milestone/26

**Comment by bramhoosemans** [comment]
https://github.com/dso-toolkit/dso-toolkit/issues/349 zou eigenlijk mee moeten in de volgende release... hier gaan we namelijk met PR12 volgende sprint mee aan de slag.

Is het mogelijk deze toe te voegen aan de release van 5 augustus?

**Comment by bramhoosemans** [comment]
@PieterVerheij @tfrijsewijk Wat is de verwachting voor de release op 5 augustus?

**Comment by tfrijsewijk** [comment]
Deze release is vandaag uitgekomen
