### ISSUE TITLE
Formulier Files groep niet conform ontwerp

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#346]
De `margin-top` + `margin-bottom`: is gezet om het geheel met het icoon te laten lijnen.. Maar we hebben niet goed naar het ontwerp gekeken, daar is de boel op 40px height gezet. Als we het icoon kleiner maken kan de marge weg en dan lijnt het alsnog. Nu is een file entry 49px hoog, dus dat ene pixeltje poetsen we dan ook wel weg;

Lange filename: `.dso-filename` een `padding-right: 8px;` geven;

Icoon: moet "DSO zwart" (`#191919`)

https://github.com/dso-toolkit/dso-toolkit/issues/328#issuecomment-514554589

**Comment by PieterVerheij** [comment]
De verticale margin is nodig om de div's even hoog te krijgen als de button. Ik heb daarom de padding aangepast.

**Comment by tfrijsewijk** [comment]
Uitgekomen in v8.0.1: https://dso-toolkit.nl/8.0.1/components/detail/group-files.html

Note: Aan de icon size is niets gedaan
