### ISSUE TITLE
Search bar niet conform ontwerp

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#347]
Placeholder: `#A8BCAF`;

Zoek knop is verkeerde type, dit moet een `btn-default` zijn

Schaling: Bij smalle viewports zie je dat het schalen niet goed gaat, maar het gaat op elke viewport niet goed. Kijk naar de `min-width` op `.btn`.

Dit zijn de bevindingen uit https://github.com/dso-toolkit/dso-toolkit/issues/298#issuecomment-514566372

Verder het verzoek het loepje optioneel te maken. Als dit loepje niet in de markup staat, dan moet de input ook niet de padding links geven.

**Comment by bramhoosemans** [comment]
Ton is begonnen met de implementatie van de search bar. Daar lopen we tegen een scenario aan die we nog niet voorzien hebben, namelijk dat het loop-icoon optioneel moet zijn. Zou je dit mee kunnen nemen in dit issue?

<img width="859" alt="Schermafbeelding 2019-07-25 om 11 03 34" src="https://user-images.githubusercontent.com/598735/61861549-74f0a480-aecc-11e9-847e-a16a949cbc9d.png">

**Comment by tfrijsewijk** [comment]
Dat is mogelijk, ik heb het in de scope van het issue gezet

**Comment by PieterVerheij** [comment]
Eigen initiatiefje: ik heb voor de smalle viewports de horizontale padding aangepast: 4px. Anders neemt de knop wel heel veel ruimte in tov de text input. Eindresultaat:
![image](https://user-images.githubusercontent.com/25430835/61948107-41cf1380-afa7-11e9-8ff9-6b9698eff9c9.png)

**Comment by bramhoosemans** [comment]
Hi Pieter, Ik zou verwachten dat de padding vast staat en niet kleiner wordt op smalle viewports. Dit had ik ook al doorgegeven in het originele issue https://github.com/dso-toolkit/dso-toolkit/issues/298

**Comment by PieterVerheij** [comment]
Hi Bram,

Dan krijg je dit, is dat ok?

![image](https://user-images.githubusercontent.com/25430835/61949860-6ed1f500-afac-11e9-942e-a18202acb662.png)

**Comment by bramhoosemans** [comment]
Ja prima :)

**Comment by tfrijsewijk** [comment]
Uitgekomen in 8.0.1: https://dso-toolkit.nl/8.0.1/components/detail/search-bar.html
