### ISSUE TITLE
Winkelwagen component

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#349]
In de discussie over de uitbreiding van het highlightbox component kwam naar voren dat we graag het 'winkelwagen' component lostrekken en een eigen podium geven. Hieronder vind je de nieuwe specificaties van de winkelwagen:

- Empty state met caption tekst (16px italic #191919)
- Als er items worden toegevoegd worden deze opgeteld in een gesloten weergave
- De gebruiker kan de winkelwagen 'openklappen' door op de regel te klikken
- In de winkelwagen kennen we twee niveau's
- Er wordt optioneel een waarschuwing icoon voor het item getoond; er verschijnt dan een tekst onder de winkelwagen. Deze tekst verdwijnt bij het inklappen van de winkelwagen.
- Elke regel kan los worden verwijderd; als het eerste niveau wordt verwijderd verdwijnen ook de items die eronder hangen
- De inhoud van de winkelwagen moet ook toonbaar zijn zonder in-en uitklap functionaliteit.

**Specificaties:**
[winkelwagen specs.zip](https://github.com/dso-toolkit/dso-toolkit/files/3508859/winkelwagen.specs.zip)

![winkelwagen](https://user-images.githubusercontent.com/598735/63156818-d3b1c580-c015-11e9-9586-dc5977a9cf9c.png)

**Comment by tfrijsewijk** [comment]
Dit is een component wat al in implementaties leeft, wellicht dat we die markup als basis kunnen gebruiken. Kan jij eens rondvragen bij developers wat voor markup zijn genereren?

**Comment by TonD83** [comment]
```html
<div class="highlight-box my-selected-items">
    <div class="row">
        <div class="col-xs-11">
            <h4 id="my-activity-http://toepasbare-regels.omgevingswet.overheid.nl/00000001821699180000/id/concept/IndieningsvereistenMeldingBouwactiviteit">Bouwactiviteit - Melding</h4></div>
        <div class="col-xs-1 text-right">
            <button id="delete-button-http://toepasbare-regels.omgevingswet.overheid.nl/00000001821699180000/id/concept/IndieningsvereistenMeldingBouwactiviteit" class="btn-delete" aria-label="Verwijder activiteit Bouwactiviteit - Melding"><span class="icon fa fa-trash-alt" aria-hidden="true"></span></button>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-11">
            <h5 id="my-activity-http://toepasbare-regels.omgevingswet.overheid.nl/00000001821699180000/id/concept/IndieningsvereistenMeldingBouwactiviteit/sub1" class="subtask">Bouwen van een muur</h5></div>
        <div class="col-xs-1 text-right">
            <button id="delete-button-http://toepasbare-regels.omgevingswet.overheid.nl/00000001821699180000/id/concept/IndieningsvereistenMeldingBouwactiviteit/sub1" class="btn-delete" aria-label="Verwijder activiteit Bouwen van een muur"><span class="icon fa fa-trash-alt" aria-hidden="true"></span></button>
        </div>
    </div>
</div>
```

**Comment by tfrijsewijk** [comment]
In het ontwerp: Wat is het winkelwagen component, eigenlijk.

Want om eerlijk te zijn is het best wel cool dat dit uit bestaande componenten is opgebouwd.. Het enige waar ik mee zit is `my-selected-items`. Wat doet dit precies?

**Comment by tfrijsewijk** [comment]
Zoals overlegd met @bramhoosemans gaat er een los winkelwagen component komen

**Comment by tfrijsewijk** [comment]
Opgeleverd in 8.2.0:
* https://dso-toolkit.nl/8.2.0/components/detail/shopping-cart--open.html
* https://dso-toolkit.nl/8.2.0/components/detail/shopping-cart--empty.html
* https://dso-toolkit.nl/8.2.0/components/detail/shopping-cart--closed.html
* https://dso-toolkit.nl/8.2.0/components/detail/shopping-cart--no-toggle.html
