### ISSUE TITLE
Button stijlen als link

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#352]
We lopen in een aantal gevallen tegen issues aan waarvoor we een button willen stijlen als een link. Omdat het een "single-page" applicatie is voeren we (button) acties uit om content te tonen aan de gebruiker, maar voor de gebruiker voelt dit aan als navigeren (links).

Vandaar dat we een modifier/class willen waarmee we een button stijlen als link.
.btn-link

`<button type="button" class="btn btn-link">Link</button>`

**Comment by tfrijsewijk** [comment]
Tsja, dat gaat niet lukken ben ik bang. Historisch gezien is de `.btn-link` als "tertiare" button gestijld.

Als we per-se aan bootstrap classes willen blijven hangen kunnen we een breaking change maken dat een `.btn-link` doet wat ie moet doen (namelijk een button als een anchor stijlen). Overigens is de `btn-link` van bootstrap niet plaatsbaar in tekst, het blijft een "log" element:

![image](https://user-images.githubusercontent.com/9696261/62037108-6e776b00-b1f3-11e9-8e41-8c1d6ffac53a.png)

Alternatief is een `button.dso-link` selector, dit is geen breaking change.

Kun je iets meer toelichten wat de verwachting is? Wil je een modifier dat een button echt op een anchor gaat lijken?

Maar bovenal nog het volgende:
* Als het voor de gebruiker _voelt_ alsof het een link is.. laat het dan een link zijn
* Als het voor de gebruiker _voelt_ alsof het navigeert.. laat het dan navigeren

De gebruiker in de maling nemen staat gelijk aan de toegankelijkheid van de pagina verlagen.

Ik verwacht namelijk bij een link dat ik de pagina kan openen in een nieuw venster dmv. {{shift + click}}. Of de URL naar mijn klembord kan kopieeren. Om nog niks te zeggen over screenreaders (die lezen namelijk gewoon "button" op, terwijl zijn ziende medegebruiker denkt dat het een link is.

Mijn ervaring leert dat `.btn-link` (of in dit voorstel: `button.dso-link`) is altijd een slecht idee is. **Technisch gezien** heb ik nog nooit een situatie gehad waar ik echt een button nodig had, waar een anchor toepasselijk was.

**Comment by bramhoosemans** [comment]
Hi Thomas, dank voor je antwoord. We zijn er hier dieper ingedoken en zijn het volledig met je eens! Daarom gaan we het proberen anders op te lossen. Ik zal dit issue sluiten.

ps. uit nieuwsgierigheid ben ik wel benieuwd hoe je onderstaand scherm zou opbouwen; de wens is om de projectnaam ook te laten navigeren naar het project (zelfde als de button openen).

<img width="850" alt="Schermafbeelding 2019-07-29 om 14 58 36" src="https://user-images.githubusercontent.com/598735/62051054-d5f0e300-b212-11e9-9643-265b3cb26222.png">

**Comment by tfrijsewijk** [comment]
Openen-knop laten vallen, prullenbak naar rechts toe, anchor om de projectnaam heen. @PieterVerheij jij?

**Comment by PieterVerheij** [comment]
Dat is wel het meet pragmatische. Of tekst 'Openen' laten vallen en het rondje voor het projectnaam zetten? 
Wat nu namelijk een beetje raar is, is de volgorde `link project` - `weggooien` - `link project`. Als gebruiker zijnde komt dat een beetje raar over?
