### ISSUE TITLE
Tabs optimalisatie

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#354]
In het tabs component meer visueel onderscheid tussen active en inactieve tab (`class="disabled"` > tekst `#A3A3A3`). Aangepaste hover state, voor specificaties zie [Tabs.zip](https://github.com/dso-toolkit/dso-toolkit/files/3460585/Tabs.zip).

![102_tabs](https://user-images.githubusercontent.com/598735/62360065-5582f880-b518-11e9-8a3a-ba6b6cffc197.png)

**Comment by tfrijsewijk** [comment]
Uitgekomen in 8.4.1: https://dso-toolkit.nl/8.4.1/components/detail/tabs.html
