### ISSUE TITLE
Release 8.2.0

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#356]
Overleghoek voor de volgende release.

Staat nu ingepland op 19 augustus, maar kan indien wenselijk eerder uitkomen

**Comment by tfrijsewijk** [comment]
@bramhoosemans of @MichielDHVD Willen jullie de release op volgorde zetten en aangeven wat de bare minimum is voor de release van maandag? Ik begin maandagochtend met #359 en dan #336

**Comment by MichielDHVD** [comment]
Gaan we doen.

**Comment by MichielDHVD** [comment]
De next release is geprioriteerd. We hopen dat de eerste 4 issues meekunnen. #349 #359 #336 #360

**Comment by tfrijsewijk** [comment]
Ik heb de release uitgebracht, maar ik krijg 'm niet uitgerold naar www.dso-toolkit.nl. Woensdag zal ik er naar kijken. De issues sluit ik pas als ik het werk heb opgeleverd. Via GitHub kan de release al worden gedownload en lokaal bekeken

**Comment by bramhoosemans** [comment]
Top! ik heb hem even lokaal bekeken.
- Jammer van de equal heights niet gelukt is, maar dat komt dan wel.
- We zullen echt naar verticale afstanden moeten kijken... die gaan zeker nog niet lekker.

**Comment by tfrijsewijk** [comment]
Opgeleverd: https://dso-toolkit.nl/8.2.0
