### ISSUE TITLE
Andere iconen voor status indicatoren (success, info, warning en danger)

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#357]
De iconen voor sectieberichten en indicatoren hebben we verbeterd en zouden we graag ontsluiten in de toolkit. Deze zijn opgemaakt in twee formaten, namelijk: 24x en 32px. Via bijgevoegde zip zijn de svg bestanden te downloaden.

[iconen.zip](https://github.com/dso-toolkit/dso-toolkit/files/3492257/iconen.zip)

**24px**
<img width="146" alt="Schermafbeelding 2019-08-12 om 14 12 07" src="https://user-images.githubusercontent.com/598735/62864145-37cd4480-bd0b-11e9-9740-bd264c1eb853.png">

**32px**
<img width="585" alt="Schermafbeelding 2019-08-12 om 14 11 57" src="https://user-images.githubusercontent.com/598735/62864491-2b95b700-bd0c-11e9-95ee-f2ed76911d9a.png">

**Comment by PieterVerheij** [comment]
De iconen komen nu uit het DSO icon font. Is het de bedoeling dat dit nu weer komt te vervallen? 
Wat zijn de aanpassingen precies (waar moeten wij op letten) en de reden erachter?

**Comment by bramhoosemans** [comment]
De aanpassingen zijn inhoudelijk; het fout-icoon was een kruisje en hebben we veranderd in een uitroepteken. Daarnaast is de cirkel van de fout en waarschuwing veranderd is een driehoek. Het 24px icoon wordt gebruikt bij invoer-validatie en de 32px iconen in de sectieberichten (meldingen).

Of we custom iconen in een DSO icon font laden of op een andere wijze implementeren is een aanvullende vraag. Wat ik heb begrepen is dat er momenteel op 4 verschillende methodes iconen gebruikt kunnen worden in de applicatie... Goed om hier op korte termijn gezamenlijk een beslissing in te nemen.

**Comment by tfrijsewijk** [comment]
Er zijn twee maten SVGs aangeleverd, waarom?

**Comment by bramhoosemans** [comment]
Zodat iconen op de gebruikte afmeting scherp blijven. Als je een 24px ontworpen icoon toont op 32px zal je altijd onscherpe lijnen krijgen, omdat er geen hele pixels worden gebruikt.

**Comment by gofix** [comment]
Van dit fenomeen had ik bij iconen eigenlijk nog nooit eerder gehoord. Bij fonts kennen we het fenomeen wel.

**Comment by bramhoosemans** [comment]
Het principe van pixel rendering is natuurlijk hetzelfde, maar ik ben het met je eens dat het idealer is om één formaat te hebben. Laten we hier in de discussie over icon implementatie (font, spread, etc.) eens kritisch naar kijken.

**Comment by tfrijsewijk** [comment]
Lijkt mij een goed plan! We kunnen voor nu de iconen pragmatisch vervangen, maar dan stel ik voor 1 setje te doen: 24px of 32px. Welke heeft jouw voorkeur?

**Comment by bramhoosemans** [comment]
Prima, dan 24px :)

**Comment by PieterVerheij** [comment]
Iconen in alerts komen uit het dso iconfont, niet de svg's.

**Comment by tfrijsewijk** [comment]
Pieter en ik hebben langs elkaar heen gekletst. De nieuwe SVG's zijn nu wel ingecheckt, maar ze moeten ook tonen in de alert. Dat is nu niet gerealiseerd. Ik schuif dit ticket op naar de volgende milestone, we pakken 'm dan op

**Comment by bramhoosemans** [comment]
@PieterVerheij Wellicht interessant om mee te nemen met de nieuwe iconen; bij alerts wordt nu ook de 'letter' van het iconfont voorgelezen door screenreaders... dit kwam uit een gebruikerstest met Tim.

<img width="1176" alt="Schermafbeelding 2019-09-19 om 15 32 53" src="https://user-images.githubusercontent.com/598735/65248645-cbf0af80-daf2-11e9-9abd-8ff1402b65ad.png">

**Comment by PieterVerheij** [comment]
@bramhoosemans 
Dat is inderdaad suboptimaal. :-/ Dit pleit voor een containertje (`<i>` of `<span>`) met een `aria-hidden="true"`. 

https://www.w3.org/WAI/GL/wiki/Icon_Font_with_an_On-Screen_Text_Alternative

**Comment by MichielDHVD** [comment]
@tfrijsewijk  hier is een zipje met een set iconen die een basis kunnen vormen de werk vorm met iconen. 

[illustratieve_iconen.zip](https://github.com/dso-toolkit/dso-toolkit/files/3661875/illustratieve_iconen.zip)

**Comment by tfrijsewijk** [comment]
Dit issue is meegekomen in het pull request voor #414 iconen (PR: #413)

**Comment by tfrijsewijk** [comment]
Opgeleverd in 9.0.0: https://dso-toolkit.nl/9.0.0/components/detail/alert.html
