### ISSUE TITLE
Highlight box stappenteller

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#359]
Vervolg uit https://github.com/dso-toolkit/dso-toolkit/issues/327 Nieuw issue om stappenteller en equal heights in highlightbox te implementeren.

**Comment by bramhoosemans** [comment]
Flexbox oplossing met equal heights op alle kindjes in de `.row` is geaccepteerd

**Comment by bramhoosemans** [comment]
Ook modifier voor transparante highlightbox toevoegen

**Comment by tfrijsewijk** [comment]
Ik heb de scope van dit ticket aan moeten passen.

De truuk van Pieter om de kolommen even hoog te krijgen maakt het responsive gedrag kapot. Ik weet dat responsive niet een hele hoge prio is, maar toch houd ik deze change even achter om in 1x met een goede suggestie te komen.
