### ISSUE TITLE
Standaard lijn in .row element verwijderen

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#360]
Elke row in de main krijgt standaard een lijn aan de onderzijde; deze mag weggehaald worden. Padding weghalen? Graag oplossing beoordelen en design specs afstemmen :)

**Comment by MichielDHVD** [comment]
@tfrijsewijk Precies het gene waar we gister ook naar hebben gekeken. 

De lijn moet inderdaad weg. 

De dso featured als class kan wel mogelijk blijven. Hoe kijk je daar tegen aan @bramhoosemans

**Comment by bramhoosemans** [comment]
@MichielDHVD Klopt. We hebben afgestemd dat de lijn weggehaald wordt en dat er naar de afstanden (padding/margin) gekeken moet worden. Volgens mij zou dit 48px (3em) moeten zijn aan de onderzijde van een .row

De class dso-featured blijft bestaan, maar maken we flexibeler. Deze hoeft niet perse in de main voor te komen bijvoorbeeld.

**Comment by MichielDHVD** [comment]
48px aan een onder kant gooit dat niet het systeem flink in de war? Kan best wel wat gevolgen hebben denk ik. Meer dan dat we nu denken.

**Comment by bramhoosemans** [comment]
Geen idee. Ik weet niet wat er met de huidige implementatie meegegeven wordt. Vandaar dat ik ook "Padding weghalen? Graag oplossing beoordelen en design specs afstemmen :)" had geschreven.

**Comment by tfrijsewijk** [comment]
Komt goed :-)

**Comment by MichielDHVD** [comment]
Qua padding/margin is het volgende wenselijk. Top padding moeten sowieso weg. 

De padding van 48px aan de onderkant blijven behouden. 

De lijn bij de not:dso-featured mag compleet weg.

**Comment by tfrijsewijk** [comment]
De `padding-top` moest toch blijven: Rows aan het begin van de pagina zagen er niet goed uit. Maar wellicht zijn mijn test pagina's geen goede referenties. Als de conclusie dan toch is dat die padding-top weg moet, kan dat in een patch release

**Comment by bramhoosemans** [comment]
@tfrijsewijk prima.

**Comment by tfrijsewijk** [comment]
Opgeleverd in 8.2.0: https://dso-toolkit.nl/8.2.0/components/detail/full-width.html

Nogmaals: Volgens mij moet deze pagina aangepast worden om de gewenste functionaliteit beter te waarborgen. Kan iemand daar een opzetje voor doen (@bramhoosemans of @MichielDHVD ?) of anders een URL geven?
