### ISSUE TITLE
Gelijke hoogte kolommen voor highlight-box

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#365]
Wens om meerdere highlightboxen op een regel gelijke hoogte te geven (equal heights). Voorkomend uit issue https://github.com/dso-toolkit/dso-toolkit/issues/359

**Comment by tfrijsewijk** [comment]
@PieterVerheij: Jij had een oplossing bedacht, maar die oplossing breekt het responsive gedrag van het grid. Wil je hier nog een keer naar kijken? Misschien implementeer ik het verkeerd

**Comment by tfrijsewijk** [comment]
Opgeleverd in 8.3.0: https://dso-toolkit.nl/8.3.0/components/detail/row-equal-heights.html

De change zit 'm in het toevoegen van een extra class modifier `.dso-equal-heights` aan een `.row`. Highlight box moet wel een direct child van de kolom zijn
