### ISSUE TITLE
Focus states

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#367]
Op dit moment maken veel componenten gebruik van de standaard browser implementatie als het om focus gaat. Er zijn enkele componenten die een custom focus state hebben. 

Er is daarom een custom focus state gemaakt die vertaald moet worden naar verschillende componenten. Er is een eerste opzet in sketch gemaakt.

 @bramhoosemans  moet je daar nog een speciale printout van maken of kan ik de versie uploaden die ik heb. 

Verder moet er alle interactieve elementen nagelopen worden en waar nodig gestyled worden. 

@tfrijsewijk  ik ga een eerste pullrequest maken om te kijken of ik de juiste lijn heb te pakken en werk methode heb. Dus pas hier maar een of twee componenten aan. Zodat als er iets niet klopt we straks alles moeten veranderen.

**Comment by bramhoosemans** [comment]
Hierbij een aantal voorbeelden van de huidige focus state (#676CB0) ontwerpen:

![focus-state](https://user-images.githubusercontent.com/598735/63431529-4ad4c880-c41f-11e9-98b0-cb0478f2efa1.png)
![formulier-elementen](https://user-images.githubusercontent.com/598735/63431530-4ad4c880-c41f-11e9-9376-51986798467f.png)

**Comment by tfrijsewijk** [comment]
Ziet er goed uit!

Dit issue gaat over focus states, maar gaan we nog wat aan {{:active}} doen? Misschien zelfs {{:focus:active}}, wat bv. Bootstrap ook doet?

Voor nu werken we alleen de focus states uit

**Comment by MichielDHVD** [comment]
Ik denk dat het in de toekomst zeker interessant is om naar de focus active states te kijken. Vooral bij de accordeon kan dit belangrijk zijn.

**Comment by tfrijsewijk** [comment]
Zijn de contrast waarden voldoende wanneer een link wordt gefocussed in een yellow highlightbox? Kunnen we andere situaties verzinnen waar de achtergrondkleur niet wit is, waar welk tekst kan staan?

**Comment by MichielDHVD** [comment]
ja op geel heeft de focus state ook voldoende contrast. 
<img width="731" alt="Screen Shot 2019-08-29 at 12 22 18" src="https://user-images.githubusercontent.com/36912722/63932657-ec7b9b80-ca57-11e9-8177-26c182afb766.png">

**Comment by tfrijsewijk** [comment]
Ik heb zojuist uit betrouwbare bron vernomen dat amsterdam.nl en de provincie Drenthe van al hun focus styling afstappen en de verantwoordelijkheid bij de browser neerleggen

**Comment by MichielDHVD** [comment]
Voorstel is om accordion niet mee te nemen in dit issue. En er een los issue voor aan te maken omdat hiervoor een html markup aanpassing nodig is. 

De a href wordt hoger getild op het niveau van de div handle

**Comment by MichielDHVD** [comment]
De markup change blijkt een grote impact te hebben op het ontwikkel team en is daarom ook afgeraden. 
Daarom zal een tijdelijke oplossing worden gecreëerd voor de focus states. 

Verder zijn er een aantal componenten waar het verder gaat dan alleen de focus states (om een goede focus state te implementeren) en deze worden niet met dit issue meegenomen. 

Dit zijn onder andere: 
Pagination
Label component
Tabs

**Comment by tfrijsewijk** [comment]
Bugs/regressies:

![image](https://user-images.githubusercontent.com/9696261/64954060-c726c400-d884-11e9-802a-ce43bc35673f.png)

![stuiter](https://user-images.githubusercontent.com/9696261/64954095-dc9bee00-d884-11e9-9f2d-153b65ce5b20.gif)

**Comment by tfrijsewijk** [comment]
Uitgekomen in 8.4.1. Zie de diverse componenten.

@MichielDHVD Gefeliciteerd, mooi werk geleverd! 🎉
