### ISSUE TITLE
Feedback highlightbox element

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#369]
Optimalisatie highlightbox element:

- Modifier (class) namen eenduidig prefixen met 'dso-' of in geheel weghalen? Zo bestaat er nu een 'highlight-box-yellow' én 'dso-yellow' in de highlightbox.
- De links in een witte highlightbox (bordered en drop-shadow) mogen grasgroen blijven. Deze worden momenteel omgezet naar zwart, maar zorgen voor een vreemde inconsistentie op de pagina.

**Comment by tfrijsewijk** [comment]
https://percy.io/dso-toolkit/dso-toolkit/builds/2814157 Mooi he

**Comment by tfrijsewijk** [comment]
Opgeleverd in 9.0.0: https://dso-toolkit.nl/9.0.0/components/detail/highlight-box--default.html
