### ISSUE TITLE
Afbeelding over de volledige breedte: onnodige margin bottom en typefout in SCSS variable

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#370]
In de afbeelding over de volledige breedte (row dso-banner banner-image) mag het volgende weggehaald worden:

- margin-bottom: 2rem;

Verder hier een typefout: https://github.com/dso-toolkit/dso-toolkit/blob/e6c91dd69dd4c1536be7af13c3d5b85030c1d32e/src/styles/mixins/_grid.scss#L15
 Moet zijn `$grasgroen-10`

**Comment by sanderhaa** [comment]
IS dit geen improvement?

**Comment by tfrijsewijk** [comment]
Ik heb er een bug van gemaakt, dan kan ik meteen een typefout in de SCSS meenemen:

```scss
// fout:
background-color: grasgroen-10;
// moet zijn:
background-color: $grasgroen-10;
```

**Comment by tfrijsewijk** [comment]
Opgeleverd in 8.3.0: https://dso-toolkit.nl/8.3.0/components/preview/stappenteller.html
