### ISSUE TITLE
next release

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#371]
De eerstvolgende release staat voor 2 augustus. Pieter is op vakantie dus we zitten iets krapper in de resources.

Staat de milestone op volgorde? Ik zal later op de dag terugkomen hoeveel we af gaan krijgen. Willen jullie aangeven wat jullie heel graag in de release willen?

cc @bramhoosemans @MichielDHVD

**Comment by MichielDHVD** [comment]
Hee Thomas ik heb ook het issue toegevoegd betreffende templates waar ik mee bezig ben. Hopelijk kan deze ook mee in de release en als er aanpassingen zijn even aangeven dan pas ik die aan voor aanstaande maandag.

**Comment by tfrijsewijk** [comment]
Deze release heeft vandaag het licht gezien onder de noemer `v8.3.0`. Wat er niet inzit is naar de release van week 38 verschoven
