### ISSUE TITLE
Titels H1-H4 bosgroen

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#374]
Kleurgebruik van titels aanpassen naar bosgroen `#275937`. Op dit moment wordt er grasgroen gebruikt voor zowel titels als tekstlinks, buttons, etc. Om het verschil tussen content en interactieve elementen beter te duiden graag aanpassen.

<img width="736" alt="Schermafbeelding 2019-08-29 om 10 27 12" src="https://user-images.githubusercontent.com/598735/63923940-b1716c00-ca47-11e9-8712-8bc7faa9c0a8.png">

**Comment by tfrijsewijk** [comment]
Note: Ook de titels in mandelbrot.css aanpassen zodat de toolkit handleiding ook meegaat

**Comment by tfrijsewijk** [comment]
Opgeleverd in 8.3.0:
* https://dso-toolkit.nl/8.3.0/components/detail/layout.html
* https://dso-toolkit.nl/8.3.0/docs/typography.html
