### ISSUE TITLE
Icon buttons

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#376]
**Vraag: Is een los component wenselijk -of- moet dit een variant van de tertiaire button zijn?**

<img width="592" alt="Schermafbeelding 2019-08-29 om 12 39 00" src="https://user-images.githubusercontent.com/598735/63934572-f7382f80-ca5b-11e9-842d-f5dfad4e3add.png">

Toevoegen van een icon button. Deze kan gebruikt worden voor het oproepen van een toelichting of voor acties op een regel in een tabel.
- Hiermee zou de info-button mogen(lijk) komen te vervallen. https://dso-toolkit.nl/8.2.0/components/detail/info-button.html
- Er bestaan meerdere implementatie vormen voor icon-buttons op dit moment, zie voorbeeld in screenshot hieronder. Wens is om dit te stroomlijnen.
<img width="559" alt="Schermafbeelding 2019-08-29 om 12 49 19" src="https://user-images.githubusercontent.com/598735/63934440-9dd00080-ca5b-11e9-9f35-8e3383599cc1.png">

**Comment by DjangoBlok** [comment]
De context dat hij alleen in een tabel kan worden gebruikt is naar mijn idee wat te beperkt.
In de viewer wordt deze ook gebruikt met een tandwiel om settings te veranderen, en een icoon om de laagvolgorde te veranderen. 
Daarnaast hebben we er een om annotaties bij een artikel weer te geven.
Ik weet niet of het nodig is alle varianten uit te werken.

**Comment by bramhoosemans** [comment]
Deze story gesloten en wordt verder opgepakt in https://github.com/dso-toolkit/dso-toolkit/issues/372.
