### ISSUE TITLE
Kleine buttons mogelijk maken

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#377]
In sommige gevallen, met name in de Regels op de kaart, zouden we buttons kleiner willen tonen. Hiervoor zouden we een extra modifier kunnen toepassen, namelijk ‘btn-sm’. Standaard zijn primaire en secondaire buttons 48px hoog, en worden dan 40px hoog (zelfde hoogte als invoervelden).

<img width="1167" alt="Schermafbeelding 2019-08-29 om 13 00 18" src="https://user-images.githubusercontent.com/598735/63935040-f6ec6400-ca5c-11e9-95a9-23ced9d05a97.png">

**Comment by DjangoBlok** [comment]
Wat mij betreft komt er ook nog een 'btn-xs' die 32px hoog is.

**Comment by bramhoosemans** [comment]
@DjangoBlok zou je mij de specificaties kunnen sturen? Dan moeten we eens kijken of de Bootstrap class 'btn-sm' voldoende is, want er is standaard geen nog kleinere variant.

**Comment by DjangoBlok** [comment]
@bramhoosemans welke specificaties wil je hebben?
Ik kan ook even wachten en kijken of de kleine button klein genoeg is. Is in ieder geval een verbetering ten opzichte van wat we nu hebben.

**Comment by bramhoosemans** [comment]
> @bramhoosemans welke specificaties wil je hebben?
De fontgrootte, padding, hoogte (en breedte)... ronde hoeken, states, etc. Alles wat afwijkt van de huidige buttons :)

**Comment by bramhoosemans** [comment]
Besproken met @DjangoBlok: één kleiner formaat button is voorlopig voldoende. Bovenstaande uitgangspunt met extra modifier hanteren (gelijke hoogte aan invoervelden 40px).

**Comment by tfrijsewijk** [comment]
Opgeleverd in 9.0.0: https://dso-toolkit.nl/9.0.0/components/detail/buttons.html
