### ISSUE TITLE
Vraag: implementatie accordion open- en dichtklappen

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#378]
In de huidige implementatie van accordeon tabel wordt er geen tekst als link meegenomen. Voor de veelgestelde vragen wordt er zelfde een link én button gebruikt, zie onderaan https://acc.omgevingswet.overheid.nl/aanvragen

Dit lijkt me niet wenselijk. Zouden we een voorbeeld in de toolkit kunnen opnemen met de juiste markup? Is het bijvoorbeeld mogelijk hier een <a> link van te maken met :before icoon?

Twee gebruiksscenario's zijn:
![accordeon-tabel](https://user-images.githubusercontent.com/598735/63940772-77659180-ca6a-11e9-93c9-d36ec3b5f67b.png)

**Comment by bramhoosemans** [comment]
@DHvD-Michael Neemt dit mee in de inventarisatie van gewenste tabel functionaliteit. Dit issue wordt voor nu gesloten.

**Comment by bramhoosemans** [comment]
In het rapport van Stichting Accessibility wordt dit component aangehaald. Graag samen kijken wat de gewenste implementatie is. 

**Succescriterium 4.1.2 (niveau A): Naam, rol, waarde Op pagina** https://dmo.omgevingswet.overheid.nl/aanvragen staat een tabel. In de tweede kolom staan links die kunnen in- en uitklappen. Deze toestand (in- of uitgeklapt) is niet door software te bepalen.

**Comment by PieterVerheij** [comment]
@tfrijsewijk span achter label in tweede kolom met class `sr-only`?

**Comment by PieterVerheij** [comment]
Op https://www.dso-toolkit.nl/9.4.0/components/detail/accordion-table.html kent de "uitklap-chevron-button" al een `<span class="sr-only">Open</span>`. 
Als de chevron en linktekst 1 klikbaar element moeten worden, betekent dit een aanpassing van component (kink met een icon in de ::before en een `<span class="sr-only">Open</span>` achter de link).

**Comment by bramhoosemans** [comment]
> Als de chevron en linktekst 1 klikbaar element moeten worden, betekent dit een aanpassing van component (kink met een icon in de ::before en een <span class="sr-only">Open</span> achter de link).

Dit lijkt me de juiste aanpak. Is het een idee om een voorbeeld te maken in de toolkit van de 2 gebruiksscenario's? Dat maakt de juiste implementatie een stuk eenvoudiger.

**Comment by PieterVerheij** [comment]
@bramhoosemans Zie https://www.dso-toolkit.nl/_378.implementatie-accordion-open-dichtklappen/components/detail/accordion-table.html . 
Ik heb een tabel gemaakt met buttons voor het in- en uitklappen ipv van twee losse links (voor chevron en label)

**Comment by bramhoosemans** [comment]
> @bramhoosemans Zie https://www.dso-toolkit.nl/_378.implementatie-accordion-open-dichtklappen/components/detail/accordion-table.html .
> Ik heb een tabel gemaakt met buttons voor het in- en uitklappen ipv van twee losse links (voor chevron en label)

@timveld Is dit een juiste werkvorm voor in- en uitklappen van een regel in de tabel?

**Comment by timveld** [comment]
@bramhoosemans  ik zou hier gewoon aria-expanded gebruiken, veel simpeler en doet in dit geval precies wat je wilt.
Aan de tabel zelf mankeert ook nog veel: moet volgens mij een grid zijn en er zijn lege kolommen.

**Comment by PieterVerheij** [comment]
@timveld Hoe zie je dat dan voor je: `aria-expanded` en `aria-controls` op de button en een `id` op de volgende `tr` of de `div` daarin?

Ik ben het met je eens dat een tabel niet de juiste werkvorm is, maar die keuze is nu eenmaal in een eerder stadium gemaakt. Als we dat willen oplossen, moet er een nieuw issue aangemaakt worden.

**Comment by PieterVerheij** [comment]
@timveld De beste wensen!
Zou je nog een keer naar mijn vraag willen kijken?

**Comment by timveld** [comment]
Ook een goed 2020! 

In ieder geval aria-expanded, het is de vraag of aria-controlls nuttig / nodig is. Het volgende artikel heeft daar een duidelijke mening over: https://www.heydonworks.com/article/aria-controls-is-poop  

Een tr 'uitklappen'? Klinkt alsof je dan wel heel ver van het doel van een tabel gaat afwijken. Als ik het plaatje goed begrijp worden er dan heel veel details tussen de tabel doorgegooid, moet je hier niet eerder een soort dialoog van maken? 

Iets wat in ieder geval zo niet kan: kolom 6 heeft geen heading en er staan alleen getalletjes in met een plaatje er achter, ik heb geen idee wat deze getalletjes betekenen.

**Comment by DHvD-Michael** [comment]
@timveld Kun je even naar het volgende tabel voorbeeld kijken?

Dit is naar aanleiding van de discussie van vandaag over het open- en dichtklappen van tabellen.
Ik herinner mij net een WAI ARIA voorbeeld waarin de inhoud van een tabel wordt dichtgeklapt en opengeklapt.

Ik ben benieuwd wat jouw feedback is op dit tabel voorbeeld:

Naam van het voorbeeld is: "Example 3: Scrollable Data Grid With Column Hiding"
https://www.w3.org/TR/2017/NOTE-wai-aria-practices-1.1-20171214/examples/grid/dataGrids.html

**Comment by PieterVerheij** [comment]
@timveld ik heb aria-expanded toegevoegd aan de button

**Comment by timveld** [comment]
OK zo is het veel duidelijker. Op de uitgeklapte rij leest NVDA overigens: "rij 5 kolom 1 tot en met 7 container cel". Het blijft een wat gammele constructie maar NVDA kan er dus kennelijk wel mee omgaan, moet voor het overleg van volgende week even uitzoeken wat volgens de specificaties wel / niet kan met tabellen en grids. Ik zal dan ook een demo geven van dit component.

**Comment by PieterVerheij** [comment]
Testable (let op: nieuwe iconen zijn hier nog niet ingefietst want oudere branch): 
https://www.dso-toolkit.nl/_378.implementatie-accordion-open-dichtklappen/components/detail/accordion-table.html

**Comment by bramhoosemans** [comment]
> Testable (let op: nieuwe iconen zijn hier nog niet ingefietst want oudere branch)

Is niet nodig. Dit issue is 23 januari besproken met o.a Tim en Thomas; openklappen van tabellen is niet toegankelijk te maken. Het is niet uit te leggen dat er een rij bijkomt die een relatie heeft met een andere rij.

Er is besloten het ontwerp hierop aan te passen waar nodig en voor de veelgestelde vragen een variatie op de accordion te maken, zie issue https://github.com/dso-toolkit/dso-toolkit/issues/523
