### ISSUE TITLE
Verbeterde contrastverhouding formulier elementen

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#380]
Nieuwe styling en contrastverhouding voor formulier elementen om te voldoen aan de WCAG AA standaard. Aanpassing lijndikte, kleur en placeholder tekstkleur. Note: de focus states worden door @MichielDHVD separaat opgepakt.

Het betreft de volgende componenten:
- Tekstvelden
- Tekstgebieden
- Zoekbalk
- Dropdown selectie
- Radio selectie
- Checkboxen

Specificaties:
[formulier-elementen.zip](https://github.com/dso-toolkit/dso-toolkit/files/3555911/formulier-elementen.zip)

![formulier-elementen](https://user-images.githubusercontent.com/598735/63947513-57889a80-ca77-11e9-8022-aef6793eb4d9.png)

**Comment by tfrijsewijk** [comment]
Uitgekomen in 8.4.1:
* https://dso-toolkit.nl/8.4.1/components/detail/form--form-vertical.html
* https://dso-toolkit.nl/8.4.1/components/detail/form--form-horizontal.html
