### ISSUE TITLE
Line-height in sectieberichten (alerts)

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#381]
De line-height in sectieberichten staat momenteel op 32px. Dit wordt gedaan om de tekst met icoon uit te lijnen, maar bij langere teksten wordt er ook veel ruimte tussen de regels meegegeven.

De wens is om de line-height van de tekst gelijk te maken met de body: font-size 16px, line-height 24px.

![Schermafbeelding 2019-08-30 om 14 26 50](https://user-images.githubusercontent.com/598735/64020615-5f594500-cb32-11e9-8bd3-b56b8de630c5.png)

**Comment by tfrijsewijk** [comment]
Uitgekomen in 8.4.1: https://dso-toolkit.nl/8.4.1/components/detail/alert.html
