### ISSUE TITLE
8.4.0 / 8.4.1 release (week 38)

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#387]
cc @bramhoosemans en @MichielDHVD. Volgorde check?

**Comment by bramhoosemans** [comment]
We hebben de issues op prio gezet :)

**Comment by tfrijsewijk** [comment]
Vandaag is versie 8.4.1 uitgekomen. Het was eerst de bedoeling dat de release de titel 8.4.0 zou dragen, maar ik heb een foutje waar ik pas achter kwam nadat ik een `npm publish` had gedaan. Vandaar dat het 8.4.1 heet
