### ISSUE TITLE
Accordeon focus states -Markup change

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#389]
In de toolkit refinement is gesproken over de situatie met betrekking tot focus states in een accordion. 

De oplossing gemaakt door mij is niet wenselijk omdat deze gebruikt maakt van een css selector die niet compatible is met edge en internet explorer 11. 

De besproken oplossing is dat de Ahref die in de accordion naar boven getild word en op het niveau komt te staan van de accordion handle. Zodat ook de complete breedte van de accordion aanklikbaar is en gestyled kan worden. 

De afbeelding die ook in issue #367  staat 

![image](https://user-images.githubusercontent.com/36912722/64341858-91165400-cfe9-11e9-8005-3faf594577ab.png)

**Comment by MichielDHVD** [comment]
@bramhoosemans  Heeft met het team overlegd en deze markup verandering bleek toch grote impact te hebben op het ontwikkel team. 

Dus daarom is het af te raden om het in dit stadium aan te passen. In issue #367 worden de focus states van de accordion aangepast. 

Nog wel een vraag aan @tfrijsewijk wat voor opties hebben we om dichtbij het ontwerp te komen zonder markup wijzigingen.

**Comment by bramhoosemans** [comment]
Besluit gemaakt om browser default focus states te gebruiken.
