### ISSUE TITLE
Accordion redesign

### ISSUE THREAD

**Issue by Poofy83** [dso-toolkit/dso-toolkit#39]
De volgende aanpassingen moeten worden gedaan aan de Accordeon. 

![image](https://user-images.githubusercontent.com/5871330/37093255-05980614-220f-11e8-8cda-cb8208ef807f.png)

Veranderingen

Alle Titels worden een h4, dat volgens de nieuwe typografie regels 18px bold worden met de kleur #39870C

Het pijltje moet een grote krijgen van 32px en de kleur #39870C

Het Accordeon die de zogezegde **Active state** heeft moet de kleur #e17000 krijgen , Oranje uit het kleurenpalet.  Dit geldt ook voor de border. 

De border van de titels
border-bottom: 2px solid #C3DAB6;

Verder moet de pijltjes de kleuren krijgen die bij de Titels horen. Momenteel zijn ze allemaal zwart. Dus deze moeten #39870C (Grasgroen) zijn als ze zijn ingeklapt en #e170000 (oranje) als deze is opgeklapt

De margins en padding moeten voldoen aan de de afbeelding. 
In de stijlgids is er een overlap tussen margins en paddings. Ik neem aan dat dat zo zal blijven? 

/Original reporter: Michael

**Comment by TonD83** [comment]
Zou hier een screenshot van het beoogde nieuwe design kunnen worden toegevoegd? Dan weten wij (PR12 DSO) beter wat we kunnen verwachten als dit issue wordt opgepakt.

**Comment by Poofy83** [comment]
Over de iconen: Is de checkmark de enige die er kan komen? Of wil je dat we de 4 iconen van Alert (https://www.dso-toolkit.nl/unstable/components/detail/alert.html) als modifiers uitwerken (success, warning, error en info) ?

Of wil je de implementator van de toolkit de vrijheid geven om elk icoon daar te plaatsen?

/Original commenter: Thomas - 02-03-18

-----

Het beste lijkt me om de implementator de vrijheid te geven. Houd onze opties open.

/Original commenter: Michael - 03-03-18

-----

En hoe zie je de kleuren voor je? Altijd groen?

/Original commenter: Thomas - 05-03-18

-----

Bedoel je hier de hover/focus/active states mee?

Want nu hebben we Groen voor gesloten accordion en Oranje voor de open accordion. Qua hoofdkleuren zijn dat de enige.

/Original commenter: Michael - 05-03-18

-----

Ik was niet heel duidelijk, mee eens.

Ik bedoelde het checkmark-icoon op rechts. Je geeft aan dat je hier de ruimte bij de implementator wil houden. Wij stylen het icoon dan groen, maar als de implementator een kruis wil plaatsen (bv. omdat de formvalidatie bij de vorige accordion niet voldoet), wordt dat een groen kruis.

Vandaar mijn suggestie om dezelfde 4 iconen (check, info, warning en error) van de alert boxen op https://www.dso-toolkit.nl/unstable/components/detail/alert.html te maken. Als er een <div class="accordion accordion-error"> wordt gemaakt, komt er een oranje uitroepteken. Lekker uniform, en met deze 4 states zal een implementator er wel mee wegkomen.

Anders moeten we naar een oplossing voor de kleuren toe, en ik zie het niet echt zitten om classnames als "background-color-grasgroen" te introduceren.

/Original commenter: Thomas - 05-03-18

-----

Ah zo.

Ik ben het met je eens om de kleuren simpel te houden. Niet alleen is dat makkelijker voor jullie maar zorgt ook voor meer rust op het scherm. Veel verschillende kleuren zou vloeken en zorgt voor onrust.

Dus die optie klinkt goed om door te voeren.

/Original commenter: Michael - 05-03-18

**Comment by VolleMelk** [comment]
Opgeleverd: https://www.dso-toolkit.nl/1.2.0-beta.0/components/detail/accordion.html
