### ISSUE TITLE
Navigatie verbeteringen (PI12)

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#394]
Bij het verwerken van de nieuwe kleurstelling kwam ik erachter dat het huidige navigatie component nog 'oude bootstrap' waardes bevat. Zoals een fontsize van 1.2 em (=19,2 px).

Voorstel is om de kleurstelling én fontgrootte/afstand te optimaliseren, met behoud van de 2 varianten (hoofd- en subnavigatie). Daarnaast heb ik de :hover state verbeterd en de :focus state toegevoegd aan het ontwerp.

Specificaties:
[Navigatie.zip](https://github.com/dso-toolkit/dso-toolkit/files/3595586/Navigatie.zip)

<img width="1258" alt="Schermafbeelding 2019-09-09 om 15 23 20" src="https://user-images.githubusercontent.com/598735/64613720-22fdd280-d3d7-11e9-93cf-97d2a90068a4.png">

**Comment by PieterVerheij** [comment]
Even voor de duidelijkheid:
selected: paarse border-bottom
hover: groene underline
focus: paars-blauwe border ?

**Comment by MichielDHVD** [comment]
Ivm met veranderde focus states moeten we even kijken of de story van dit onderdeel moet worden aangepast.

**Comment by MichielDHVD** [comment]
Wat komt te vervallen in dit issue is alleen de focus states. De rest van het issue blijft nog staan. 

Dit betekent aanpassing op de volgende onderdelen:
Tekst groottes menu en sub-nav
Selected state -> Paarse underline

**Comment by bramhoosemans** [comment]
dso-nav-main ziet er goed uit.

Hoe bouwen we de rest van het scherm op? Zou de header geen margin-bottom moeten hebben van 32px?

Resterende opmerkingen, maar ik volgens mij heb je die niet gewijzigd ten opzichte van de huidige situatie:

- Het logo wordt met een vaste breedte getoond waardoor de hoogte op een vreemde waarde staat. Ik ben van mening dat de hoogte moet worden vastgelegd op de baseline (responsive en ivm uitlijning dso-tools-bar).
- dso-tools-bar heeft een margin top van 25px. Dit past niet op de 8px baseline en zou eerder 24px moeten zijn.
- breadcrumb styling is wel erg groot. In het ontwerp heeft dit een 14px fontgrootte met een margin top van 16px.

**Comment by PieterVerheij** [comment]
@bramhoosemans De enige wijziging die ik heb doorgevoerd, vallen binnen het menu. Doordat die 4px (48px ipv 44px) hoger is geworden, verschuift e.e.a.
Zie ook https://www.dso-toolkit.nl/_394.navigatie-verbeteringen/components/detail/aanvragen.html voor de effecten.

**Comment by bramhoosemans** [comment]
Klopt, het ontwerp is ook 48px. Dus helemaal prima zo :)

**Comment by tfrijsewijk** [comment]
De WIP is hier: https://dso-toolkit.nl/_394.navigatie-verbeteringen/components/detail/header.html

Is er rekening gehouden met de `:visited` state? Bij mij ziet het er nu zo uit:

![image](https://user-images.githubusercontent.com/9696261/69439653-acbb0c00-0d47-11ea-9cfc-15be1cdef323.png)

* Alles is `:visited`
* "Vergunningcheck" is `:focus`
* "Aanvragen" is `:hover`
* "Regels op de kaart" is `.dso-active`

**Comment by DjangoBlok** [comment]
In een menu wordt normaal gesproken toch geen gebruik gemaakt van een visited state?
Visited state zou ik negeren / gelijk maken aan up state.
Wordt naar mijn idee anders erg rommelig. Of hebben jullie daar andere ideeën over?

**Comment by bramhoosemans** [comment]
@DjangoBlok Mee eens; een navigatie menu is een compleet ander element dat tekstlinks. Daarom zouden we prima af kunnen wijken van de algemene richtlijnen. Dus visited state is gelijk aan default/up state.

@tfrijsewijk Was de vraag aan ons bedoelt?

**Comment by PieterVerheij** [comment]
@bramhoosemans Wat bedoel je met de up-state? Gewoon bosgroen?

**Comment by bramhoosemans** [comment]
> @bramhoosemans Wat bedoel je met de up-state? Gewoon bosgroen?

Bosgroen inderdaad.

**Comment by PieterVerheij** [comment]
ok, aangepast!

**Comment by PieterVerheij** [comment]
@bramhoosemans zie work in progress: https://www.dso-toolkit.nl/_394.navigatie-verbeteringen/components/detail/navs.html

**Comment by timveld** [comment]
Goed werk zowel voor screen reader als visueel
