### ISSUE TITLE
Nieuw component: toggle uit de Viewer

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#399]
@django ontwerp- en gebruik specificaties toevoegen

**Comment by DjangoBlok** [comment]
In de viewer wordt de aan/uit schakelaar (toggle switch) gebruikt als selectiemechanisme.  Met het aanzetten van de schakelaar kan een bijbehorend gebied op de kaart worden weergegeven. In de uitstand zien de schakelaars er allemaal hetzelfde uit.  In de aanstand wordt in de schuif de verbeelding weergegeven zoals die ook op de kaart wordt weergegeven. Indien geen verbeelding aanwezig is, wordt de neutrale aanstand weergegeven.

![formulier-elementen Schakelaar](https://user-images.githubusercontent.com/34900082/65771278-24016480-e138-11e9-9a93-a6be1537d095.png)

**Comment by PieterVerheij** [comment]
@bramhoosemans @DjangoBlok Hebben jullie een sketch bestand of export?

**Comment by bramhoosemans** [comment]
@DjangoBlok Zou je ook de gewenste states en label uitlijning kunnen documenteren? Zie bijvoorbeeld https://material.io/components/selection-controls/#switches

**Comment by DjangoBlok** [comment]
@PieterVerheij hier mijn sketch bestand
[DSO Componenten Viewer Schakelaar.sketch.zip](https://github.com/dso-toolkit/dso-toolkit/files/3671597/DSO.Componenten.Viewer.Schakelaar.sketch.zip)

**Comment by PieterVerheij** [comment]
@DjangoBlok Paar vragen:
- ik snap het verschil tussen `geselecteerd` en `groengebied` niet? 
- geselecteerd neutraal heeft een witte achtergrond, moet niet-geselecteerd neutraal dan ook een witte achtergrond hebben?
- de eerste toggle `geselecteerd met lijnpatroon`, met rode border?
- ik zie in Sketch bij de symbols nog meer varianten, die worden niet gebruikt?

**Comment by DjangoBlok** [comment]
Hmm, misschien lastig uit te leggen zonder context.
Geselecteerd neutraal is de "default" voor als er geen verbeelding is gedefinieerd.
niet-geselecteerd heeft altijd een een grijze achtergrond.
De opties daaronder zijn verbeeldingen die we zelf aan de toggle mee moeten kunnen geven om in de schuif van de geselecteerde schakelaar een verbeelding te krijgen.
Het gaat er niet om dat in de toolkit alle mogelijke varianten worden uitgewerkt.
Het gaat erom dat we in markup iets kunnen aanpassen om de toggleschuif te kunnen aanpassen.
Voorbeeld van sliders in werking:
https://pre.omgevingswet.overheid.nl/orienteren/document/NL.IMRO.0297.ZBMBP20120021-VS01

**Comment by PieterVerheij** [comment]
@DjangoBlok In jouw voorbeeld zie ik trouwens ook hover en active gedrag op het bolletje (in de code `ripple` genoemd). Dat komt niet in de dso-versie van de toggle?

**Comment by tfrijsewijk** [comment]
Gaan jullie dit component implementeren? Ik zie namelijk dat de link van Django gebruik maakt van de Angular Material Design Toggle. De markup van dit component is niet aan te passen, maar de markup van dat component komt ook niet overeen met de markup die wij gaan maken.

Ofwel: Waarom maken we dit component?

**Comment by sanderhaa** [comment]
Beslissing tijdens refinement: 
De viewer Toggle wordt niet als component opgenomen in Toolkit. dit is te specifiek voor de context van de viewer.  Wel wordt generiek component opgenomen in de Toolkit in ander issue.

**Comment by bramhoosemans** [comment]
Nieuw issue aangemaakt: https://github.com/dso-toolkit/dso-toolkit/issues/419
