### ISSUE TITLE
Nieuw component: cards uit de Viewer

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#400]
@django ontwerp- en gebruik specificaties toevoegen.

**Comment by DjangoBlok** [comment]
In een lijstweergave kunnen kaarten (cards) worden weergegeven als alternatief voor een tabel. Per kaart wordt naar een object verwezen. 
Een kaartweergave onderscheidt zich van de tabelweergave doordat  elementen op de kaart anders kunnen worden weergegeven. Een kaart kan diverse elementen bevatten zoals tekst, rich media, knoppen, afbeeldingen etc. Zo kan een gebruikerservaring gecreëerd worden die duidelijker, evenwichtiger, esthetischer, eenvoudiger en stijlvoller is.  Alle elementen bevinden zich binnen de grenzen van de kaartcontainer. 

De primaire actie van de kaart is het hele gebied van de kaart. Meestal verwijst dit naar een detailweergave scherm van het bertreffende object.

**Comment by DjangoBlok** [comment]
![Cards](https://user-images.githubusercontent.com/34900082/65884874-e1d75d80-e399-11e9-9d08-3847a3291667.png)

**Comment by PieterVerheij** [comment]
Hi @DjangoBlok , heb je hier een Sketch bestand of Measure export van?

**Comment by tfrijsewijk** [comment]
>Een kaart kan diverse elementen bevatten zoals tekst, rich media, knoppen, afbeeldingen etc
Wil je voorbeelden van deze werkvormen aanleveren?

Wil je ook een voorbeeld aanleveren voor de "Gemeente Zantvoort en Hoogelande" maken?

De scope van het issue lijkt het over een generiek component te hebben, maar het ontwerp is heel specifiek op een bepaalde werkvorm gemaakt:
* Informatie knopje en toggle switch rechtsboven uitgelijnd
* Daaronder een datum met status

Het _lijkt_ erop alsof dit generieke component een generieke naam verdient, maar de inhoud spreekt dat tegen.

**Comment by sanderhaa** [comment]
Besproken tijdens refinement: 
Component bestaat ook in Bootstrap 4. Naam component zelfde laten als twitter bootstrap 4

**Comment by tfrijsewijk** [comment]
Kan iemand de URL naar het bootstrap 4 component delen? Ik kan geen component vinden wat lijkt op de toepassing van het component wat gevraagd is in dit issue

**Comment by MichielDHVD** [comment]
https://getbootstrap.com/docs/4.3/components/card/ Dit is volgens mij het component waar naar gerefereed werd. @bramhoosemans  @sanderhaa

**Comment by DjangoBlok** [comment]
Toch nog even terugkomend op het interactiepatroon.
Ik blijf van mening dat in de basis de hele card klikbaar moet zijn. Dat is de primaire actie van een card. Het is eventueel mogelijk secundaire acties toe te voegen. Zolang dit secundaire acties zijn, voorzie ik weinig probleem met digitoegankelijkheid.
Dit wordt ook onderbouwd in diverse bronnen die ik hierover heb nageslagen:
https://material.io/components/cards/#actions
https://uxplanet.org/best-practices-for-cards-fa45e3ad94dd
https://www.nngroup.com/articles/cards-component/
http://ui-patterns.com/patterns/cards

Ik kan nog wel een generieker voorbeeld uitwerken.

**Comment by tfrijsewijk** [comment]
>Ik blijf van mening dat in de basis de hele card klikbaar moet zijn. Dat is de primaire actie van een card.

Mee eens

>Het is eventueel mogelijk secundaire acties toe te voegen.

Absoluut, maar niet _in_ het primaire actie vlak.

Om jouw eigen bronnen even aan te halen:

![image](https://user-images.githubusercontent.com/9696261/66892304-a53b7100-efeb-11e9-8846-44f069e8cb12.png)

Dit vind ik een mooi voorbeeld, er staat haarscherp aangegeven waar welke interactie is.

Jouw andere bronnen hebben het niet zo expliciet over complexe interactie (anders dan "make the whole card clickable").

Ik vond nog een ander complex voorbeeld:
![image](https://user-images.githubusercontent.com/9696261/66892551-46c2c280-efec-11e9-805f-ffc87279acbc.png) 

Hier zijn duidelijk 3 verschillende acties.

Jouw ontwerp heeft secundaire acties IN de primaire acties:

![image](https://user-images.githubusercontent.com/9696261/66892782-dbc5bb80-efec-11e9-9e29-c2ecbe5a7ef7.png)

* Als het hele kaartje klikbaar moet zijn spreekt het voor zich om het hele kaartje (of het root element) een `<a>` te laten zijn, maar IN een interactief element mag je geen andere interactie elementen zetten
* Als het root element geen `<a>` is moet er een ander element worden aangewezen, de kop van de kaart leent zich daar goed voor maar vervolgens moet de implementator scriptend de hele kaart clickable maken
* Er is geen ruimte voor een foutje: Als je naast een secundaire actie klikt/tapt wordt direct de primaire actie uitgevoerd

**Comment by DjangoBlok** [comment]
> IN een interactief element mag je geen andere interactie elementen zetten
Ok Thomas, ik kende die regel niet.
Ik ging er van uit dat als je twee interactieve elementen boven op elkaar legt, alleen het bovenste element de mouse/click events ontvangt.

> Er is geen ruimte voor een foutje: Als je naast een secundaire actie klikt/tapt wordt direct de primaire actie uitgevoerd.
Zolang de primaire actie primair is en geen destructieve actie, wat mij betreft niet het grootste probleem.  
Wel een voorbeeldje uit de IOS Mail app waar ik door was geïnspireerd (maar dat is geen HTML) 
![Mail APP IOS](https://user-images.githubusercontent.com/34900082/66992810-c3c46980-f0ca-11e9-98de-4af06ba1fbce.png)
De hele mail is klikbaar, maar als er een thread is, komt er een blauw pijltje rechtsboven.
Druk op het pijltje om in de lijst de thread open te vouwen. 
Druk ernaast en de mail opent.

**Comment by tfrijsewijk** [comment]
>Ik ging er van uit dat als je twee interactieve elementen boven op elkaar legt, alleen het bovenste element de mouse/click events ontvangt.

Twee interactieve elementen boven op elkaar leggen is iets anders dan het ene interactieve element IN het andere interactieve element. Dat eerste is technisch toegestaan (met CSS positioneren), maar dan moet het clickevent afgevangen worden zodat het onderste element niet reageert.

**Comment by MichielDHVD** [comment]
![Cards](https://user-images.githubusercontent.com/36912722/67459482-f9240680-f638-11e9-90e6-0a98ffb56bc9.jpg)

Even een opzetje op te bespreken voor toekomstige refinements.

**Comment by DjangoBlok** [comment]
Dank Michiel, Hierbij een nieuwe versie op basis van je verschillende voorbeelden. 
![Cards](https://user-images.githubusercontent.com/34900082/67685980-43d5b380-f996-11e9-93f9-fc44e871aca5.png)

**Comment by MichielDHVD** [comment]
Uitschrijven verbeteringen  besproken in Donderdag 7 November.  @MichielDHVD

**Comment by MichielDHVD** [comment]
Sketch bestand meegeleverd. 

Toevoegingen besproken in de refiniment:

- Underline op heading als een complete card hover heeft. 

- Focus-state = Browser default. Vraag is hoe richten we dat in. Gaat de card als button functioneren waarmee het opgeroepen kan worden of wordt het misschien in <a> gewrapped. Vanuit bootstrap zijn het gewoon div's dus voor screenreaders ben ik benieuwd wat het fijnste is. Ik denk <a> link. Typisch iets om een opzet te maken en deze aan Tim voor te leggen. 

-  Interactieve elementen kunnen zowel rechts als onder op een card terechtkomen. 

[DSO Componenten Viewer Kaarten v0.8.sketch.zip](https://github.com/dso-toolkit/dso-toolkit/files/3824107/DSO.Componenten.Viewer.Kaarten.v0.8.sketch.zip)

**Comment by DjangoBlok** [comment]
Card lijkt me geen button maar een link.

**Comment by PieterVerheij** [comment]
> Interactieve elementen kunnen zowel rechts als onder op een card terechtkomen.

@MichielDHVD @DjangoBlok Ik mis een uitwerking van de interactieve elementen onder op een card?

**Comment by MichielDHVD** [comment]
Is dit genoeg @PieterVerheij Komt vrijwel overheen met aan de zijkant. 

[DSO Componenten Viewer Kaarten v0.92.sketch.zip](https://github.com/dso-toolkit/dso-toolkit/files/3891418/DSO.Componenten.Viewer.Kaarten.v0.92.sketch.zip)

**Comment by PieterVerheij** [comment]
@MichielDHVD margins van de interactive elementen heb ik een beetje moeten gokken, maar wel gebaseerd op de `dso-unit` van 8px;

Het toggle element is niet uitgewerkt (zie ook https://github.com/dso-toolkit/dso-toolkit/issues/419), ik gebruik voorlopig een checkbox.

**Comment by MichielDHVD** [comment]
Prima. Maar komt de hoogte van het interactieve gedeelte helemaal vast te staan. Of kan de implementator plaatsen wat hij wil in het interactieve elementen onderdeel, om het generiek te houden.

**Comment by PieterVerheij** [comment]
@MichielDHVD 
Wanneer de interactieve elementen naast de inhoud staan, staat de breedte van het interactieve gedeelte vast.
Wanneer de interactieve elementen onder de inhoud staan, staat de hoogte van het interactieve gedeelte vast.

Is dat een probleem?

**Comment by gofix** [comment]
Over de toggle/checkbox/switch in het ontwerpvoorstel, de discussie (https://github.com/dso-toolkit/dso-toolkit/issues/419, https://github.com/dso-toolkit/dso-toolkit/issues/399) daarover moet wellicht weer worden opgepakt, omdat er toch echt behoefte lijkt te bestaan aan deze werkvorm.

https://material-components.github.io/material-components-web-catalog/#/component/switch
In material design is deze gewoon met een checkbox en een label gemaakt, en zodoende is dat ook direct een toegankelijk element. Detail: van zo'n switch-werkvorm moet wel het label zichtbaar zijn, dat is immers eigenlijk het interactieve element in deze.

**Comment by gofix** [comment]
Omdat deze discussie dus nog moet worden voortgezet, heeft @PieterVerheij er nu nog even voor gekozen slechts een standaard checkbox te plaatsen. Die moet natuurlijk nog wel van een zinvol label (al dan niet visually hidden) worden voorzien, bv. "Brouwersmolen geselecteerd", om toegankelijk te worden. Nu blijkt slechts visueel dat je met die checkbox wsl. selecteert waar de kaart over gaat.

**Comment by PieterVerheij** [comment]
https://patternlab-amsterdam.infoprojects.nl/?p=viewall-molecules-switch

**Comment by PieterVerheij** [comment]
Het label van de checkbox is aangepast, maar @MichielDHVD, @DjangoBlok : zouden jullie nog met een voorstel komen voor de markering van de zone met de interactieve elementen (lijntje, achtergrondkleurtje oid)?

**Comment by MichielDHVD** [comment]
![Cards Copy](https://user-images.githubusercontent.com/36912722/70226503-41166d00-1751-11ea-8a78-d6570e6368f1.jpg)

Bespreken tijdens refinement. wat we willen

**Comment by MichielDHVD** [comment]
Besproken in refiniment zou dit de manier zijn hoe cards weergeven zouden moeten worden op een hover state. 
![Cards 3](https://user-images.githubusercontent.com/36912722/70506452-9e803480-1b2a-11ea-8e8c-e436cf348714.jpg)

**Comment by DjangoBlok** [comment]
Ik heb wat moeite met de uitlijning en het label bij de slider.  
Maar goed ik beschouw het even als een voorbeeld component. 
We kunnen dit zelf hopelijk anders inrichten.

**Comment by MichielDHVD** [comment]
Klopt. Het gaat in de afbeelding die ik heb gestuurd puur en alleen over het hover gedrag en wanneer het hover gebied te zien is. Labels en andere onderdelen moeten genegeerd worden daar heb je gelijk in @DjangoBlok.

**Comment by MichielDHVD** [comment]
Ziet er goed uit. Ik vind de hover state goed werken om het klikbare gebied te tonen. 

De link voor mensen om zelf even te kijken. 
https://dso-toolkit.nl/_400.card-component/components/preview/card.html#

**Comment by bramhoosemans** [comment]
Aantal opmerkingen:
- Hebben we een active state nodig?
Waarom gebruiken we hier niet de checkbox uit de toolkit?
- Als er op de card geklikt wordt en je er dan met de muis vanaf gaat verschijnen er underlines. Active state?
- Hoe gaan we om met verschillende headings in de card? Deze lijken compleet af te wijken van de gedefinieerde typografie.
- Bij hover op de tweede card is 1px wit te zien onder de scheidingslijn.
- @DjangoBlok Is dit de gewenste dropshadow?
- Zouden we er geen minimale (en maximale) breedte moeten zetten?

**Comment by timveld** [comment]
Er is een sr-only label "omgevingsplan Nieuwegein geselecteerd" wat kennelijk aan het selectievakje moet worden gekoppeld. Dat "geselecteerd" hoeft er niet bij (de screen reader geeft zelf al aan of het selectievakje al dan niet geselecteerd is). Ook zou je het de gebruiker wat makkelijker kunnen maken door het knopje "toelichting bij omgevingsplan Nieuwegein" te noemen. 
Met deze aanpassingen verwacht ik dat het effectief werkt, verschillende items uit elkaar houden met een goede heading structuur is prima. Maar uiteraard kunnen er bij een volledig werkend voorbeeld nog problemen boven komen drijven...

**Comment by PieterVerheij** [comment]
'Geselecteerd' bij sr-only label "omgevingsplan Nieuwegein geselecteerd" verwijderd
"**toelichting bij** omgevingsplan Nieuwegein" bij sr-only label toegevoegd

@bramhoosemans Ik heb nog wat vragen/opmerkingen:
_Hebben we een active state nodig?_
Die beslissing is aan jullie, ook de vormgeving van de active state?

_Waarom gebruiken we hier niet de checkbox uit de toolkit?_
Het ontwerp bevatte een toggle, maar dat zou in een apart ticket worden meegenomen. De checkbox staat er alleen als placeholder/voorbeeld. Maar natuurlijk kunnen er allerlei interactieve elementen geplaatst worden. Daarvoor zou idd wel de styling gecheckt moeten worden. Is er een overzicht van mogelijke elementen?

_Als er op de card geklikt wordt en je er dan met de muis vanaf gaat verschijnen er underlines. Active state?_
Opgelost

_Hoe gaan we om met verschillende headings in de card? Deze lijken compleet af te wijken van de gedefinieerde typografie._
Tot nu toe is de h2 gestijld, moeten h3 en h4 dezelfde styling krijgen?

_Bij hover op de tweede card is 1px wit te zien onder de scheidingslijn._
Dat zie ik niet? Welke browser/OS gebruik je voor deze check?

_Zouden we er geen minimale (en maximale) breedte moeten zetten?_
We gaan de cards nog in een voorbeeldpagina zetten, de breedte van de card wordt bepaald door het bootsdtrap grid.

**Comment by timveld** [comment]
De zijzigingen lijken nog niet live te staan - lijkt geen cache probleem te zijn...

**Comment by bramhoosemans** [comment]
> _Bij hover op de tweede card is 1px wit te zien onder de scheidingslijn._
> Dat zie ik niet? Welke browser/OS gebruik je voor deze check?

Ik zit op Google Chrome Versie 79.0.3945.130 (Officiële build) (64-bits) op MacOS 10.15.2

**Comment by tfrijsewijk** [comment]
Opgeleverd in 9.7.0:

* https://dso-toolkit.nl/9.7.0/components/detail/cards--default.html
* https://dso-toolkit.nl/9.7.0/components/detail/cards--interactions-bottom.html

**Comment by timveld** [comment]
Lijkt OK maar ben uiteraard benieuwd naar de genoemde voorbeeld pagina
