### ISSUE TITLE
Button positionering

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#401]
Buttons worden uitgelijnd afhankelijk van de context:

- Buttons worden gesorteerd op belangrijkheid van rechts naar links, met de primaire actie aan de rechterkant. Wanneer knoppen gebruikt worden om door een reeks schermen te navigeren, wordt de primaire knop rechts uitgelijnd en de 'terug' actie helemaal links om de navigatie visueel te ondersteunen.
- Uitgezonderd zijn formulieren met één pagina en gerichte taken, buttons links uitlijnen en sorteren op belangrijkheid van links naar rechts.

![patronen](https://user-images.githubusercontent.com/598735/66211530-946e2f80-e6bc-11e9-8f10-e3479acd497a.png)

**Comment by PieterVerheij** [comment]
Hier ligt de verantwoordelijkheid bij de implentator: wij kunnen de juiste css aanleveren, maar in de markup zal ook moeten staan welk type formulier het betreft.

**Comment by MichielDHVD** [comment]
Bootstrap levert de standaard class pull-right mee. Dit is wat ik developers aanraad als ze een button op een andere plek moeten plaatsen. Dit wordt immers meegeleverd met bootstrap zelf

**Comment by tfrijsewijk** [comment]
En toch zou ik met `pull-right` uiterst voorzichtig zijn:
* Responsive
* Positioneren van buttons binnen werkvormen **niet doen**

@bramhoosemans: Welke change verwacht je in het kader van deze issue? Hoe zie je de modal voor je?

**Comment by bramhoosemans** [comment]
Het klopt dat de verantwoordelijkheid hier bij de implementator ligt. Maar zitten alle mogelijkheden in de toolkit -of- hoeven we hier niks voor te doen?
- Grotere formulieren (incl meerdere stappen), modals = primaire actie rechts
- Kleine formulieren, sectieberichten, highlightbox = primaire actie links

**Comment by PieterVerheij** [comment]
Wie bepaalt wat een klein en een groot formulier is? Waar ligt de grens? Het is een beetje subjectief: als ik een lang formulier zonder stappen maak, is het dan een formulier met de primaire actie links of rechts?

**Comment by bramhoosemans** [comment]
Het is inderdaad een beetje vaag omschreven van mijn kant. Hierbij een meer gedetailleerde definitie van grote en kleine formulieren:

- Formulier met meerdere stappen of secties kan worden gezien als groot formulier (primaire actie rechts)
- Formulier op één enkele pagina is een klein formulier ongeacht aantal velden (primaire actie links)

Meer achtergrond: https://uxmovement.com/forms/where-to-align-form-buttons-on-different-layouts/

**Comment by PieterVerheij** [comment]
Ik heb het even verder uitgewerkt:

Multipage
-primaire button (btn-primary): rechts
-pager knop (btn-default): links
-annuleren knop (btn-link): links van primaire

Singlepage
- primaire button: links
- pager knop (btn-default): niet
- annuleren knop (btn-link): niet

Mobiel
-primaire button (btn-primary): rechts
-pager knop (btn-default): links
Automatisch centreren van de knoppen: bepalen met css wanneer de knoppen te breed zijn, gaat niet met css. We moeten gewoon een omslagpunt bepalen (bv. 480px), waaronder de knoppen (gencentreerd) onder elkaar worden gezet.

**Comment by bramhoosemans** [comment]
@PieterVerheij twee opmerkingen:

1. Pager knop is ook een tertiaire (btn-link) met icoon voor.
2. Mobiel is voorlopig 'buiten scope' dus een lange discussie zou ik hier niet over willen voeren. Verder kan ik prima leven met het voorbeeld dat je hebt gemaakt; als ze niet meer op één regel passen worden ze onder elkaar links uitgelijnd.

**Comment by PieterVerheij** [comment]
@bramhoosemans zie https://www.dso-toolkit.nl/_401.Button-positionering/components/detail/button-row.html

**Comment by bramhoosemans** [comment]
@PieterVerheij Wellicht goed om in het voorbeeld dan ook altijd een secondaire actie op te nemen:

<img width="899" alt="Schermafbeelding 2019-12-02 om 16 14 35" src="https://user-images.githubusercontent.com/598735/69970679-eeee0580-151e-11ea-981f-c5b42ce4a515.png">

**Comment by PieterVerheij** [comment]
@bramhoosemans Zijn er nog meer scenarios?

**Comment by bramhoosemans** [comment]
Volgens mij niet. Ik zou me willen beperken tot formulieren en deze 3 scenario's dekken volgens mij de lading wel.

**Comment by PieterVerheij** [comment]
@bramhoosemans zo dan: https://www.dso-toolkit.nl/_401.Button-positionering/components/detail/button-row.html ! :)

**Comment by bramhoosemans** [comment]
Ja, ziet er goed uit!

**Comment by tfrijsewijk** [comment]
Ik ben toch aan de bak gegaan en heb wat kleine aanpassingen gedaan. Dit waren mijn overwegingen:

**Toegankelijkheid**
De primaire ("belangrijkste") actie moet als eerste focus krijgen (Dus: veld, veld, verstuur, annuleer).

Dus de buttons moeten ook op deze manier in het DOM staan. Dit was niet zo.

**Eenvoud**
De huidige oplossing is nu non-breaking: De knoppen in een formulier met 1 knop lijnt links uit, meerdere knoppen lijnen rechts uit.

Vanaf nu moeten formulieren als multipage worden gemarkeerd dmv `form.dso-multipage`. Ook deze change is non-breaking, het is nieuwe functionaliteit.

@bramhoosemans Kan je nog een keer kijken naar de topic branch release op www.dso-toolkit.nl met de volgende kanttekeningen:
* Ik heb een multipage variant toegevoegd en de vorige/volgende knoppen met iconen toegevoegd. Iconen in default/primary buttons krijgen geen ruimte naast de tekst. Dit wordt (volgens mij?) in #438 opgelost
* Het icoon is in de vorige-knop (btn-link) niet even groot als in de volgende-knop (btn-primary). btn-link krijgt een font-size 1.5 op het icoon. Hoe wil je dit oplossen? Ik denk dat we de font-size 1.5 van het icoon in een btn-link niet meer moeten doen

**Comment by bramhoosemans** [comment]
@tfrijsewijk Wat mij betreft een goede verbetering om de tab-volgorde logisch te maken.

De aandachtspunten wat betreft padding/margin en icoon formaat zal ik verder uitwerken in issue https://github.com/dso-toolkit/dso-toolkit/issues/438.

**Comment by tfrijsewijk** [comment]
Dan toch nog een footnote...

Zie de volgende pagina's:
* https://www.digitoegankelijk.nl/onderwerpen/lijst-met-alle-eisen/2.4.3
* https://www.digitoegankelijk.nl/onderwerpen/techniek--code/toetsenbordbediening
* https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0&showtechniques=243#focus-order
* https://www.w3.org/WAI/WCAG21/Techniques/html/H4.html

Vooral deze zin:
>In situaties waarbij de volgorde in de broncode niet gelijk is aan de visuele volgorde moet de focusvolgorde toch logisch zijn.

Is vrij aan interpretatie.. Wie weet vind iemand het wel weer onlogisch dat je "zwabberend" door je formulier focust.

Windows doet dit overigens ook niet:

![image](https://user-images.githubusercontent.com/9696261/71172742-55825b80-2261-11ea-8fa5-88508fd8170f.png)

Focus is: OK, Cancel, Apply

En GitHub ook anders:

![image](https://user-images.githubusercontent.com/9696261/71172773-6af78580-2261-11ea-87f9-18201cd8db22.png)

Textarea - Close and Comment - Comment

Wat stel je voor?
* Voorschrijven dat de buttons op primaire volgorde in het DOM staan en met styling "andersom" plaatsen, en mogelijk bovenstaande toegankelijkheidsrichtlijnen breken
* Voorschrijven dat de buttons in het DOM staan waar ze visueel tonen, tabbend kom je dus EERST langs "Annuleren" en daarna langs "Verstuur" (idem voor Vorige/Volgende)
* Ander ontwerp?

**Comment by bramhoosemans** [comment]
Een logische tabvolgorde is inderdaad vrij aan interpretatie. 

Het onderwerp button positionering en leesvolgorde zal altijd een discussiepunt blijven. Er is namelijk geen éénduidige button volgorde (en positie) die in alle situaties verwacht wordt. Het hangt in veel gevallen af van de context.

Wat betreft leesvolgorde:
- We lezen in de westerse cultuur van links naar rechts. Als de primaire actie altijd rechts staat hoef ik niet terug te keren naar de primaire actie. Dit is een veelgebruikt interactie patroon gebaseerd op het Z-patroon (Gutenberg diagram).
- Aan de andere kant denken mensen op basis van hoogste prioriteit naar laagste, en van positief naar negatief, niet in omgekeerde volgorde. Als de primaire actie als laatste voorgelezen wordt kan het ook als vervelend worden ervaren.

@timveld  heb jij hier ervaring mee?

https://uxdesign.cc/buttons-placement-and-order-bb1c4abadfcb
https://www.lukew.com/ff/entry.asp?571
https://uxmovement.com/forms/where-to-align-form-buttons-on-different-layouts/
https://uxmovement.com/buttons/why-users-click-right-call-to-actions-more-than-left-ones/

**Comment by timveld** [comment]
Het ligt niet voor de hand de volgorde in het DOM af te laten wijken van de visuele presentatie, iemand die het scherm ook ziet verwacht navigatie 'van boven naar beneden en van links naar rechts'. Dus een knop die visueel rechts staat lezen voor een knop die visueel links staat wordt eerder verwarrend. 

Ik ben aan rommel gewend, over een knopje meer of minder springen maakt niet zo veel uit. 

In sommige gevallen moet je de default button markeren, dat is wel belangrijk; als ik tijdens het tikken in een zoekveld op enter druk hoort de zoeken knop bijvoorbeeld geactiveerd te worden. En in een ja / nee / annuleren dialoog verwacht ik dat de focus op ja komt. 

Dat soort aspecten zijn veel belangrijker dan de leesvolgorde van knoppen, in het zoekvoorbeeld kom ik in de praktijk namelijk niet eens in aanraking met de zoek-knop.

**Comment by gofix** [comment]
> Ik ben aan rommel gewend 
De lat voor DSO ligt wel wat hoger dan dat denk ik ;)

Als ik naar de argumenten van @bramhoosemans kijk zou ik bijna willen concluderen dat de primaire actie toch als eerste na de input-werkvorm zou moeten komen. Zowel visueel als ook in tabvolgorde. 

Wie hakt de knoop door. Of valt er niks door te hakken: in dat geval gaan we denk ik in ieder geval NIET rommelen met positioneringsflipflops, want een andere tabvolgorde dan een visuele volgorde is volgens mij (en volgens @timveld ) altijd onwenselijk. Dan liever een paar tabjes extra om de rechts-staande knop te bereiken (zoals ik nu hier in github ook ga doen)

**Comment by timveld** [comment]
Eens, mijn tabtoets is allang afgesleten dus een tabje meer of minder is niet belangrijk. Tabvolgorde moet volgens WCAG logisch zijn (het mag bijvoorbeeld niet zo zijn dat na de verzendknop nog invoervelden komen of voor de verzendknop dingen komen die niet met het formulier te maken hebben) en moet redelijk overeenstemmen met de visuele presentatie. Zoals het artikel waarnaar Bram verwijst al aangeeft± consistentie is belangrijk.

**Comment by bramhoosemans** [comment]
Dan houden we de tabvolgorde gelijk aan de visuele presentatie.

De button positionering zal per situatie kunnen verschillen afhankelijk van de context (verwachting van de gebruiker). Belangrijk is dat we deze situaties in kaart brengen en consistent gebruiken. Daar hebben we voor formulieren nu een goede opzet voor gemaakt volgens mij.

**Comment by tfrijsewijk** [comment]
Ga je dan andere ontwerpen aanleveren? Zodat de primaire actie als eerste focusable is en visueel zichtbaar is?

Of blijven de ontwerpen gelijk en moet er meer werk gedaan worden om de primaire knop te bereiken?

(Ik verwijs nog een keertje naar het Windows dialoog, zie screenshot eerder in dit issue: Daar is de primaire knop de linker knop, en niet de rechterknop)

**Comment by bramhoosemans** [comment]
> Ga je dan andere ontwerpen aanleveren? Zodat de primaire actie als eerste focusable is en visueel zichtbaar is?

Nee. Bij een formulier op enkele pagina staat de primaire actie als eerste; bij de formulieren met meerdere pagina's of met meerdere secties niet. 

> Of blijven de ontwerpen gelijk en moet er meer werk gedaan worden om de primaire knop te bereiken?

De button positionering zal per situatie kunnen verschillen afhankelijk van de context (verwachting van de gebruiker). We houden de tabvolgorde aan van de visuele presentatie, dus zal er in sommige gevallen een meerdere keren op tab moeten worden gedrukt om bij de primaire actie te komen.

**Comment by tfrijsewijk** [comment]
OK!

@PieterVerheij: Wil jij het PR aanpassen? Die floats kunnen eraf, in de markup de knoppen aanpassen, en met een text-align naar rechts zetten

**Comment by PieterVerheij** [comment]
@tfrijsewijk aangepast

**Comment by tfrijsewijk** [comment]
Merged #478 into master

**Comment by tfrijsewijk** [comment]
Opgeleverd in 9.7.0:
* https://dso-toolkit.nl/9.7.0/components/detail/form--multi-page.html
* https://dso-toolkit.nl/9.7.0/components/detail/form--sections.html
* https://dso-toolkit.nl/9.7.0/components/detail/form--single-page.html
