### ISSUE TITLE
Toolkit menu structuur aanpassen

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#403]
Nieuwe indeling in hoofdlijnen doorvoeren. Schrijftaal documentatie Nederlands, maar naamgeving componenten Engels ivm implementatie.

Voorstel om toch enkele naamswijzigingen door te voeren en componenten samen te voegen ten behoeve van vindbaarheid. Zie tabel hieronder.

- URL's doorverwijzen in oude/nieuwe release? of kunnen we leven met 404 pagina's bij wisselende versies? Wat mij betreft ook prima mits goed afgevangen.
- Deprecated componenten afvoeren?

![screencapture-jira-team-dso-nl-confluence-display-DSOUX-DSO-toolkit-indeling-2019-12-10-14_35_58](https://user-images.githubusercontent.com/598735/70534348-267e3280-1b5b-11ea-8de9-51748bd1bc6a.png)

**Comment by bramhoosemans** [comment]
> * URL's doorverwijzen in oude/nieuwe release? of kunnen we leven met 404 pagina's bij wisselende versies? Wat mij betreft ook prima mits goed afgevangen.

Besproken 12-12: eigen 404 pagina's maken voor de toolkit (separaat issue).
> * Deprecated componenten afvoeren?

Ja. De volgende componenten worden niet (meer) gebruikt:
- Carousel
- Image
- Jumbotron
- Progress Block
- Panel

Wellicht aankondigen in volgende release dat deze componenten komen te vervallen. Dan erop volgende release weghalen. Info & info button worden nog wel gebruikt, maar kunnen mogelijk worden vervangen.

**Comment by DjangoBlok** [comment]
@bramhoosemans Ben je er zeker van dat deze componenten nergens worden gebruikt?

**Comment by bramhoosemans** [comment]
> @bramhoosemans Ben je er zeker van dat deze componenten nergens worden gebruikt?

@DjangoBlok Dat heb ik gevraagd in ons Slack kanaal; en extra nagelopen met Michiel en Michael. Gisteren vernam ik van dat het panel component waarschijnlijk nog wel op dso-toolkit.nl wordt gebruikt in documentatie.

**Comment by PieterVerheij** [comment]
@bramhoosemans waar komen `navigation` en `layout`, ook in de hoofdstructuur net als nu het geval is?

**Comment by bramhoosemans** [comment]
@PieterVerheij Ik snap je vraag niet helemaal; welke hoofdstructuur bedoel je?

Navigation is volgens mij een component en kan onder de header vallen.
Layout is naar mijn idee een documentatie pagina (oftewel Grid).

**Comment by PieterVerheij** [comment]
Ik bedoelde de navigatie van de toolkit zelf. Maar zo is het duidelijk. 👍

**Comment by PieterVerheij** [comment]
@tfrijsewijk https://github.com/dso-toolkit/dso-toolkit/pull/579

**Comment by PieterVerheij** [comment]
zie https://www.dso-toolkit.nl/master/

We liepen tegen een aantal zaken aan:
- we krijgen door de mappen structuur 'gratis' koppen erbij (`Documentatie` en `Componenten`), die gaan we wegstijlen in #499 
- startgids pagina is nu de homepage, zijn kindjes (`toegankelijkheid`, `voor ontwerpers`, `voor ontwikkelaars`) staan in dezelfde pagina. Die zouden we moeten opknippen? Of anders een nieuwe startpagina en startgids weer een kindje van documentatie laten zijn?
- in je ontwerpen voor #499 staat ook een item 'versies' onder documentatie? Moet die er komen (er is al een versie selector?)

- Wij hebben meer items dan in jouw voorstel onder `Fundament staan`. Die hebben we voorlopig onder `Unassigned` geplaatst. Die indeling moet nog een keer onder de loep worden genomen.
- Het component `Layout` lijkt bij `Grid` te horen, maar hebben we voorlopig in Unsassigned laten staan. Zo zijn er nog wel wat componenten, zoals `Lijsten`, waar kritisch naar moet worden gekeken.

Bij `Componenten` staat ook een map `Unassigned` met componenten waarover we twijfelen waar deze moet komen te staan.

**Comment by bramhoosemans** [comment]
> zie https://www.dso-toolkit.nl/master/
> 
> We liepen tegen een aantal zaken aan:
> 
> * we krijgen door de mappen structuur 'gratis' koppen erbij (`Documentatie` en `Componenten`), die gaan we wegstijlen in #499

Oké, ik begrijp dat je ze dubbel krijgt? Als https://github.com/dso-toolkit/dso-toolkit/issues/499 aangehouden wordt moet het goed komen :-)

> * startgids pagina is nu de homepage, zijn kindjes (`toegankelijkheid`, `voor ontwerpers`, `voor ontwikkelaars`) staan in dezelfde pagina. Die zouden we moeten opknippen? Of anders een nieuwe startpagina en startgids weer een kindje van documentatie laten zijn?

Ja, het idee is dat we de startpagina gaan opknippen. Maar dat kunnen we ook zelf doen hoor.

> * in je ontwerpen voor #499 staat ook een item 'versies' onder documentatie? Moet die er komen (er is al een versie selector?)

Het ontwerp in https://github.com/dso-toolkit/dso-toolkit/issues/499 toont altijd 'versies' onder documentatie. Hier kunnen we uitleggen hoe versies in elkaar zitten en waar de changelog en roadmap te vinden zijn. Ook zou hier een overzichtspagina onder vallen met alle versies (in de selector tonen we dan enkel de laatste 5 versies).

> * Wij hebben meer items dan in jouw voorstel onder `Fundament staan`. Die hebben we voorlopig onder `Unassigned` geplaatst. Die indeling moet nog een keer onder de loep worden genomen.
> * Het component `Layout` lijkt bij `Grid` te horen, maar hebben we voorlopig in Unsassigned laten staan. Zo zijn er nog wel wat componenten, zoals `Lijsten`, waar kritisch naar moet worden gekeken.
> 
> Bij `Componenten` staat ook een map `Unassigned` met componenten waarover we twijfelen waar deze moet komen te staan.

Prima! De eerste grote stap is gemaakt, de juiste indeling zal langzaam meer vorm krijgen.

**Comment by tfrijsewijk** [comment]
>Ja, het idee is dat we de startpagina gaan opknippen. Maar dat kunnen we ook zelf doen hoor.

Ik heb vast een voorzet gedaan, maar ik vermoed dat je nog wat refinement wilt doen. Dit kan mee in toekomstige versies. Voor nu is het meegekomen in versie 10 :tada:
