### ISSUE TITLE
Active Focus states en bugs. 

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#406]
De noodzaak voor active focus states lijkt groter te zijn dan verwacht. Daarom gaat er snel gekeken worden naar een verder ontwerp om deze toe te passen.

**Comment by bramhoosemans** [comment]
Focus states bevindingen:
- Bij de focus state van een tekstgebied wordt de border dikte aangepast; hierbij zouden overige formulier elementen niet moeten verspringen. Zie bijvoorbeeld: https://design-system.service.gov.uk/patterns/addresses/
- Focus state van buttons in sectieberichten klopt niet.
- Focus states blijven zichtbaar na klik (erg vervelend bij accordeons/buttons/etc.)
- Secondaire buttons hebben een vreemde ‘grijze state’ als je deze indrukt en er vanaf sleept met de cursor.

**Comment by MichielDHVD** [comment]
Dit issue wordt gesloten nadat is gebleken dat aanpassingen op de korte termijn niet de grotere problemen met de focus states oplossen. 

Er moet vanuit UX als team gekeken worden naar de verdere implementatie van Focus states, welke oplossing er geboden worden. 

Anders blijven de focus states een onderwerp waarbij constant pleisters geplakt blijven worden.
