### ISSUE TITLE
Bevindingen formulier elementen

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#407]
Bevindingen formulier elementen o.b.v. release 8.4.1:

- Verticale checkboxes en radio selecties hebben tussen de items een marge bottom van 16px, in het ontwerp is dit 8px. Zo worden de items beter gegroepeerd.
- Border radius van tekstvelden en tekstgebieden staat nu op 8px, in het ontwerp is dit 4px.

**Comment by tfrijsewijk** [comment]
Uitgekomen in 8.5.0: https://percy.io/dso-toolkit/dso-toolkit/builds/2627718
