### ISSUE TITLE
Documentatie voor Iconen, logo's, Buttons, en Notificaties

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#411]
Voor iconen wordt een documentatie pagina gemaakt deze moet geimplementeerd worden in de toolkit.

**Comment by MichielDHVD** [comment]
Dit issue wordt uitgebreid en gaat alle pagina's bevatten die gereleased worden deze release. 

Documentatie pagina's die opgeleverd worden in week 42:

* Iconen
* Logo's
* Buttons
* Notificaties

**Comment by tfrijsewijk** [comment]
Ik schuif dit issue 'n release op

**Comment by tfrijsewijk** [comment]
Opgeleverd in 9.2.0:
* https://dso-toolkit.nl/9.2.0/docs/icons.html
* https://dso-toolkit.nl/9.2.0/docs/graphics.html
* https://dso-toolkit.nl/9.2.0/docs/logo.html
* https://dso-toolkit.nl/9.2.0/docs/buttons.html
* https://dso-toolkit.nl/9.2.0/docs/status-feedback.html
