### ISSUE TITLE
Iconen

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#414]
[Memo iconen.pdf](https://github.com/dso-toolkit/dso-toolkit/files/3663432/Memo.iconen.pdf)

@MichielDHVD en @bramhoosemans: Willen jullie deze memo verspreiden?

**Comment by MichielDHVD** [comment]
Ik laat de developers er na kijken.

**Comment by TonD83** [comment]
> Vragen:
> - Wat denken jullie van het gebruik van SVG’s?
> - Zien jullie obstakels met het implementeren van SVG’s?
> - Willen jullie dat er ook React/Angular icon componenten worden aangeleverd?

1. Goed idee, moeten we zeker doen!
2. Behalve het al genoemde probleem van external sprites laden in IE11/Edge, niet direct nee.
3. Ik denk, maar ben benieuwd wat mijn collega's daar van vinden, dat we die liever zelf maken zodat ze 100% passen in onze werkwijze, code style standaarden etc. 

Misschien dat iets als [react-sprite](https://www.npmjs.com/package/react-sprite) voor ons een oplossing kan zijn voor het IE11/Edge vraagstuk. Verder geen ervaring mee, maar klinkt alsof het doet wat het moet doen :)

**Comment by jeroenpeeters** [comment]
Ik denk dat het aanleveren van React/Angular componenten vanuit de toolkit niet heel veel toevoegd. We zullen de SVG-icons op eenzelfde manier gebruiker zoals we nu ook FA en Bootstrap icons gebruiken.

**Comment by tfrijsewijk** [comment]
>We zullen de SVG-icons op eenzelfde manier gebruiker zoals we nu ook FA en Bootstrap icons gebruiken.

Dat gaat niet lukken. In mijn memo heb ik aangegeven dat er echt verschillen zijn, waaronder:
* De API: `<span class="fa fa-user">` vs `<svg class="di di-user"><use href="icons.svg#user" /></svg>`
* IE/Edge issues: `<use href>` naar een externe spritesheet of DATA uri werkt niet. svg4everybody kan gebruikt worden, maar het is wel toegevoegde complexiteit mbt. timing issues/SPA.

Een React/Angular oplossing/alternatief/aanvulling voor svg4everybody (of soortgelijk) is geen complexe aangelegenheid. Ik verwacht niet dat jullie er moeite mee hebben het te implementeren, ik wil alleen aangeven dat het geen drop-in-replacement is.

**Comment by WidoBurg** [comment]
@tfrijsewijk Zou je bij de oplevering van dit issue een mapping tussen de oude en nieuwe icons willen bijvoegen? 
Als het telkens een mapping van fa naar di prefix is, dan is het vrij duidelijker wat we moeten gaan gebruiken.

**Comment by tfrijsewijk** [comment]
Goed punt!

Maar dat kan ik niet:
* Ik weet niet welke iconen implementaties er uit FontAwesome en Glyphicon gebruiken;
* Er zijn nu "maar" 32 iconen in de toolkit;

![image](https://user-images.githubusercontent.com/9696261/66751344-24fff900-ee8f-11e9-905a-3d80290ba779.png)

Maar je brengt mij nu wel op een idee wat ik ben vergeten uit te werken. Tijdens UX-overleg is er aangegeven dat er geen iconen inventarisatie wordt gedaan:
* Het is teveel werk om alle teams een lijst te laten maken met de iconen die nu in gebruik zijn;
* De UX-ers willen deze kans aangrijpen om elk icoon voorbij te zien komen;

Daarom is er gekozen voor een wildcard icoon: `di di-wip-wip`. Als je tijdens de upgrade naar versie 9 merkt dat je een icoon mist ga je als volgt te werk:
* Waar je het icoon mist gebruik je `di-wip-wip`.
* Bij het UX team aangeven welk icoon je in welke context mist.

We kunnen met goede zekerheid zeggen dat `wip-wip` nooit een echt icoon gaat worden. Het is daarom een ideaal placeholder-icoon met een ID om je broncode te doorzoeken naar missende iconen.

Het UX team zal een icoon maken en bij de toolkit aanleveren. In de CHANGELOG zal ik duidelijk aangeven welke iconen nieuw zijn.

Je hebt nu een sneak-preview, maar ik zal bovenstaande instructies opnemen in de toolkit. Ik verwacht dat dit geen bevredigend antwoord zal zijn, maar meer dan dit kan ik nu niet voor je betekenen. Als je inhoudelijk meer wilt weten kan je het beste naar @MichielDHVD, @bramhoosemans of @sanderhaa stappen.

PS: Even dubbelchecken: Je vraagt specifiek naar een icon map, maar je hebt de memo gelezen waarin staat dat het meer werk is dan alleen een paar classes omzetten?

**Comment by WidoBurg** [comment]
> PS: Even dubbelchecken: Je vraagt specifiek naar een icon map, maar je hebt de memo gelezen waarin staat dat het meer werk is dan alleen een paar classes omzetten?

Ja

**Comment by tfrijsewijk** [comment]
@WidoBurg Onder het genot van een kopje koffie toch nog even doorgefilosofeerd over de komende upgrade-problematiek...

Ik neem aan dat jullie een icoon-component gaan maken (of misschien al zelfs hebben) wat ongeveer als volgt werkt:

* React: `<Icoon icon="user" />`;
* Angular: `<dso-icon [icon]="'user'"></dso-icon>` of `<dso-icon icon="user"></dso-icon>`;

Dit is natuurlijk een uitgelezen kans om de IE11 tekortkomingen te compenseren, maar los daarvan: Als ik nou een .json bestand genereer waar alle iconen in staan:

```json
[
  {
    "icon": "user"
  },
  {
    "icon": "chevron-left"
  }
]
```

Dan zou je een fallback naar `wip-wip` kunnen schrijven en een error in de console tonen dat er een icoon mist.

Dit is dan wel een runtime-check, maar wellicht dat met deze routine het makkelijker is om bij elk icoon `fa fa-` te laten vervallen. Bijvoorbeeld met [codemod](https://github.com/facebook/codemod)

Een ander alternatief: Maken jullie gebruik van TypeScript? In dat geval kunnen we er zelfs een compile-time error van maken met wat TypeScript magie:

![image](https://user-images.githubusercontent.com/9696261/66758918-83cd6e80-ee9f-11e9-93ab-9db4cfbb9091.png)

**Comment by tfrijsewijk** [comment]
Opgeleverd in 9.0.0: https://dso-toolkit.nl/9.0.0/components/detail/icon.html

**Comment by WidoBurg** [comment]
Ter info. Geen wip-wip kandidaten gevonden bij het toepassen van deze change.
