### ISSUE TITLE
Focus states formulier elementen

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#416]
Gezien het eerdere besluit custom focus styling eruit te halen en zoveel mogelijk default :focus styling aan te houden zullen formulier elementen opnieuw gedefineerd moeten worden. Het idee is om borders 1px dikker te maken op focus, zie ontwerp hieronder.

Tekstvelden, tekstgebieden en dropdown
focus: 2px border #275937

Radio selectie en checkbox
focus: 3px border #275937

![formulier-elementen](https://user-images.githubusercontent.com/598735/66030756-52998980-e502-11e9-982f-9ddf0b0eadbd.png)

**Comment by gofix** [comment]
Zoals ik al opmerk in https://github.com/dso-toolkit/dso-toolkit/pull/444:

> Op zich is nu gedaan wat de bedoeling was, maar... het valt op dat door verdikking van de border bij focus de werkvorm nogal 'schuift' (bv. de multiple select wordt groterm in in textinvoerboxes schuift de tekst). Dit was overigens ook al bij de vorige (actuele) versie van focus styling.
> Wsl. is het een beter idee om deze styling niet met border-width, maar met een inner box shadow te doen: die neemt namelijk geen ruimte in!

**Comment by MichielDHVD** [comment]
Zal de styling hetzelfde eruit zien als het ontwerp? 

Is er een snel opzetje mogelijk waar we naar kunnen kijken?

**Comment by MichielDHVD** [comment]
Met team afgestemd en de voorkeur om inner box shadow te gebruiken is afgestemd.

**Comment by gofix** [comment]
Opzetje gemaakt. Eigenlijk meer dan een opzetje, dit is 'm volgens mij wel.

**Comment by MichielDHVD** [comment]
Afgestemd met Michael, Antoinette en ik. Goed bevonden, doorzetten.

**Comment by tfrijsewijk** [comment]
Opgeleverd in 9.2.0: https://dso-toolkit.nl/9.2.0/components/preview/form--form-vertical.html
