### ISSUE TITLE
Terug naar default focus states

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#418]
Volgorde is gebaseerd op toolkit behalve de anchors/ links die zijn boven aangezet vanwege invloed op de rest. Afwijkende onderdelen van bootstrap staan genoteerd waar dit brekend was met onderdelen uit de toolkit. 

Anchors / Links <a>
  Bootstrap overruled default browser outline niet.  Bootstrap geeft wel zijn eigen theme mee.  Voorstel is om betreffende links terug te gaan naar release 8.3.0 om de styling van de links te blijven te behouden. 

Accordion,
 Mag terug gezet worden naar 8.3.0  De ahref zorgt voor een browser outline default.   Carousel,  Bootstrap overruled browser default outline. Zet een outline = 0;  Op focus/hover verandert kleur van icoon en achtergrond transparantie.  Opmerking: Carousel wordt volgens mij nu nergens gebruikt. Eruit halen, overleggen? 

Highlightbox,  Heeft een custom a styling, mag terug gezet worden naar 8.3.0 en de browser default outline van <a> overnemen

  Modal,
Modal bevat 3 buttons.  De primary button en tertiare/link-btn hebben outlines die bootstrap niet overruled. Wel background color en color.  Op de modal close button wordt de outline wel overruled en op nul gezet.  Bij de modal close button moet dus de outline=0 verwijderd worden. 

  Shopping cart,  Opgebouwd uit verscheidene buttons,  Geen afwijkend gedrag qua focus states browser default outline is altijd zichtbaar in versie 8.3.0. Voorstel terugzetten  

Whitebox In versie 8.3.0 wordt de focus state niet overruled in latere versie is er geen enkele focus state waar te nemen. Terug naar 8.3.0  

Formulieren
 De outline van formulieren wordt overruled door bestaande vormgeving. Bram heeft hier een herontwerp voor toegevoegd en de focus state voor formulieren in issue #416

  Buttons,  
Bij versie 8.3.0 zijn de default browser outlines zichtbaar bij alle buttons.  
Primaire button: Outline van browser wordt niet overruled. Geen afwijkende kleur onderdelen. 
Secundaire/Default button: Outline is zichtbaar. Maar de background-color van het standaard bootstrap thema wordt niet overruled hierdoor zie je een licht grijze achtergrond in versie 8.3.0. Voor de focus state mag de focus state gelijk getrokken worden met de hover qua kleuren. Grasgroen background color + witte tekst.   
Tertaire-button / Lnk-button: Outline is zichtbaar in 8.3.0, geen afwijkende kleur stellingen gedetecteerd. 

  Dropdown-button Bootstrap overruled hier default browser focus state en zet een outline van 0 neer. Waarschijnlijk omdat ander de outline blijft staan als er een dropdown menu is. In het menu wordt in standaard bootstrap de outline niet overruled. In de toolkit wordt dit wel overruled. Outline = 0 moet uit worden gezet voor menu items.  Verder kan kleurgebruik hoe het toegepast was in 8.3.0 wel overgenomen worden.

Alert 
Hebben custom styling qua kleuren maar als de a-links weer default browser outline bevatten zal dat voor alerts ook meegenomen worden. 

 Badges 
als de a-links weer default browser outline bevatten zal dat voor badges ook meegenomen worden.
 
 Info
 Bij het component info overrulen wij de outline en zetten we deze op nul. Deze outline = 0 moet weg gehaald worden. Verder mag de styling terug naar 8.3.0

  Info-button 
Default browser outline is nooit verwijderd hoeft niets voor te worden aangepast. 

  Label 
Voor labels overrulen wij zelf de outline naar nul. Outline  = 0 verwijderen   

Breadcrumbs
 Mag terug gezet worden naar versie 8.3.0. Daar is default browser outline zichtbaar.   

Menu/navs 
Gaat hier vooral om het component navs. De focus styling mag terug gezet worden naar 8.3.0 daar is de browser default weer actief.   

Pager 
Wij hebben zelf een outline = 0 geplaatst deze moet worden verwijderd. Kleurgebruik mag overgenomen worden van 8.3.0   

Pagination
 Wij hebben zelf een outline = 0 geplaatst deze moet worden verwijderd. Kleurgebruik mag overgenomen worden van 8.3.0

  Searchbar 
Het kruisje voor verwijderen in de zoekbalk heeft in 8.3.0 een browser default outline. De zoek knop heeft het zelfde probleem als de secundaire knop dat de focus state bg-color uit bootstrap nog gebruikt wordt.   Bg-color voor focus state mag in dit geval grasgroen met tekst kleur wit worden.   

Tabs 
Wij overrulen de default browser outline. De outline = 0 moet verwijderd worden dan is de default weer zichtbaar.

**Comment by MichielDHVD** [comment]
@tfrijsewijk Kun je even kijken of deze inventarisatie duidelijk genoeg is om mee te werken.

**Comment by gofix** [comment]
Op zich is het verwijderen van de dso-specifieke styling op focus al wel gelukt, maar omdat alles op bootstrap gebaseerd is, komt daar ook nog wat uit naar boven. In bootstrap zelf wordt sommige focus styling toegepast op een manier die voorkomt dat de standaard browser focus z'n werk kan doen. Dat is bv. het geval bij dropdown-buttons (zoals in de beschrijving van het ticket ook al wordt genoemd).

Er wordt gesteld "Outline = 0 moet uit worden gezet voor menu items.". Probleem is, dat kan niet. Je kunt voor een stijlregel niet 'terug' (op zich zijn daar in css initial en/of unset voor bedoeld, maar die pakken voor `outline` niet uit zoals je zou willen.

Daarom hebben we in de meest recente commits bv. ook de standaard `normalize.css` van bootstrap buitenspel gezet en er een eigen variant van ingevlogen (namelijk in de `normalize.css` van bootstrap zat nog een `outline: 0` op `:hover` en `:focus`, waardoor je 'netto' van de focusstyling toch weer niks zag, bij bepaalde elementen.

We twijfelen nu over of we dat voor dropdown-button ook moeten doen.

**Comment by gofix** [comment]
NB: voor sommige andere componenten, waar wordt genoemd dat bootstrap ook overrulet, is dat niet problematisch omdat dan niet de standaard bootstrap markup wordt gehanteerd (bv. accordion is een eigen `dso-accordion`.

**Comment by gofix** [comment]
Mijn voorstel zou nu zijn om het hier nu bij te laten, en in een later ticket nog een keer specifiek te kijken naar dropdown-button.

**Comment by MichielDHVD** [comment]
Akkoord.

**Comment by tfrijsewijk** [comment]
Opgeleverd in 9.2.0: https://dso-toolkit.nl/9.2.0/
