### ISSUE TITLE
Toggle component

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#419]
Specificaties generiek toggle component toevoegen.

**Comment by timveld** [comment]
Let er op dat dit component een checkbox is (liefst semantic HTML, Aria kan hier eigenlijk niet omdat een niet Aria client dan geen manier heeft om de state van de toggle op te vragen); let op correcte en niet-dubbele labeling; let er op dat kleurcontrasten kloppen en dat de state visueel ook zonder kleur (monochroom instelling) geen verwarring kan geven.

**Comment by sanderhaa** [comment]
Dit is wel anders dan een checkbox. Qua gedrag zou dit component echt anders moeten werken. Native checkbox is multiple choice. Toggle is een lichtknopje. We zetten iets aan of uit.. Dus het btreft een checkbox waar een directe actie op volgt.

**Comment by tfrijsewijk** [comment]
Een checkbox is multiple choice in de zin dat het "aan" of "uit" is :-)

Dat er een "multiple choice" werkvorm mee wordt gemaakt is een kwestie van implementatie.

Wat mij betreft is de basis voor dit toggle component een checkbox.

@bramhoosemans: Wat is het bestaansrecht van dit ticket ten opzichte van #400 ?

**Comment by bramhoosemans** [comment]
@tfrijsewijk Wat ik heb begrepen is dat het toggle component ook in andere applicaties wordt gebruikt. De specifieke implementatie van de Viewer https://github.com/dso-toolkit/dso-toolkit/issues/399 is tijdens de refinement afgeschoten, maar er is nog wel een generiek component nodig.

**Comment by PieterVerheij** [comment]
@bramhoosemans 
In de specs staat geen focus-state gedefinieerd (of kijk ik er overheen?). 
Omdat de checkbox is weggestijld, zullen we een eigen focus-state moeten stijlen. Ik heb er nu dit van gemnaakt (achtergrond van het bollejte wordt lichtgrijs):
![image](https://user-images.githubusercontent.com/25430835/66303194-c1a82100-e8fa-11e9-963a-ee916b9f9232.png)
Of geven jullie de voorkeur aan een paarse border, a la de text inputs e.d.?

**Comment by bramhoosemans** [comment]
@PieterVerheij issue https://github.com/dso-toolkit/dso-toolkit/issues/399 is gesloten. Dit is een nieuw issue waar nog specificaties voor worden toegevoegd.

**Comment by PieterVerheij** [comment]
Ik neem aan dat er qua styling niet veel gaat veranderen?

**Comment by timveld** [comment]
Agendapunt voor donderdag, hoe wordt zo'n toggle gebruikt? Als er op het in / uitschakelen direct een actie volgt kun je er inderdaad beter een knop van maken met als label "zet ... aan / zet ... uit".

**Comment by MichielDHVD** [comment]
Dit issue gaat gesloten worden vanwege de volgende reden, besproken in de refinement van 31 oktober: 

De toggle button heeft een zelfde issue als de typeahead. Namelijk dat de technische implementatie en taal (angular of react) de html zodanig beinvloed dat er geen framework agnostische versie van de toggle button gemaakt kan worden. 

Wat hoogstens gerealiseerd kan worden is een afbakening van gedrag en gebruik. Dit moeten worden beschreven in de documentatie. 

Deze leidraad wordt opgesteld aan de hand van de huidige implementatie in de viewer. Deze wordt voorgelegd aan Tim int Veld, mocht deze implementatie niet toereikend zijn wordt de documentatie aan gescherpt. En wordt verwacht dat in de toekomst teams proberen te voldoen aan deze implementatie. 

@DjangoBlok (weet niet zeker of ik je gister hier over had bijgepraat maar zelfde probleem als de typeahead dus. Toggle is niet framework agnostisch te maken)
