### ISSUE TITLE
Checkboxes redesign

### ISSUE THREAD

**Issue by Poofy83** [dso-toolkit/dso-toolkit#42]
Herontwerp checkboxes

![image](https://user-images.githubusercontent.com/5871330/37092858-a07b6696-220d-11e8-887a-11b97a361a20.png)

Kleuren / Border / Radius

Border: 2px, #A8BCAE, radius 6px
Kleur Vinkje: #39870C

/Original reporter: Michael

**Comment by Poofy83** [comment]
- Wat is dat vraagteken rechtsboven?
- In het bovenste voorbeeld is er een ruimte van 32px aangegeven. Ik neem aan dat dit de gutter is. De gutter is op dit moment 30px (15 links, 15 rechts). Het lijkt mij dat dit twee col-md-6 zijn. Moet de gutter van 15px naar 16px worden opgehoogd? (Dit geldt dan voor het hele grid)
- Als de 32px de gutter is, houd er dan rekening mee dat links en rechts van de rij (.row) ook 16px is
- Hoe verwacht je de :active, :hover en :focus states?

/Original commenter: Thomas - 09-02-18 13:49

-----

Het vraag teken rechtsboven is voor extra informatie.

Het Horizontale grid dat met Bootstrap is gemaakt heeft voorrang op het 8px grid. 
Het 8px grid werkt binnen het kader van bootstrap en de instellingen hiervan. 
Losse elementen worden gemaakt volgens het 8px grid.

Maar de 32px is geen gutter. Als je gaat naar de huidge vormgeving in bijv. 
https://dso-toolkit.nl/1.1.0/components/detail/form-horizontal.html 
Dan hebben deze onderdelen ook geen eigen col-md toewijzing.

In de huidige situatie staat bijv. bij het Label 25% width en Checkboxes 75% width.

Dit kan veranderd worden naar 50% En als je dan een padding meegeeft van 16px links/rechts dan heb je precies die 32px in het midden.

Standaard hebben checkboxes geen hover dus die wordt voorlopig achterwege gelaten. Maar de click state geeft wel feedback.

Border 2px #275937 6px
Fill in de checkbox zelf is: #EBF3E6

/Original commenter: Michael - 12-02-18 09:47

-----

**Vraagteken**
Voor het vraagteken zie ik graag een los ticket. Ik neem aan dat er een pop-over komt?

**Grid/gutter/8px**
Ik geloof dat wij langs elkaar praten wat betreft de gutter/grid.

De "Form Horizontal" werkvorm van bootstrap heeft een slimmigheid:

  Use Bootstrap's predefined grid classes to align labels and groups of form controls in a horizontal 
  layout by adding .form-horizontal to the form (which doesn't have to be a <form>). Doing so changes 
  .form-groups to behave as grid rows, so no need for .row.

https://getbootstrap.com/docs/3.3/css/#forms-horizontal

Ofwel, de volgende markup is geldig:

<form class="form-horizontal">
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-10">
      <input type="email" class="form-control" id="inputEmail3" placeholder="Email">
    </div>
  </div>
</div>
Zoals je ziet is een .row niet nodig en mag een gridkolom definitie direct op de label.

Tot zover basic Bootstrap, niets nieuws onder de zon. Wat minder bekend is, zijn de mixins die Bootstrap tot z'n beschikking stelt. Tijdens een overleg van een paar maanden geleden hebben wij voorgesteld de kolomverdeling van de formulieren niet in de markup voor te schrijven, maar volledig vanuit de toolkit te sturen. Dit is in   DSOCOMLIB-78 DONE  gerealiseerd. Bovenstaand voorbeeld wordt dan:

<form class="form-horizontal">
  <div class="form-group">
    <label for="inputEmail3" class="control-label">Email</label>
    <div class="field-container">
      <input type="email" class="form-control" id="inputEmail3" placeholder="Email">
    </div>
  </div>
</div>
Bovenstaande markup bevat dan wel geen kolomdefinitie classnames, maar vanuit de styling wordt dit wel degelijk met dezelfde mixins gegenereerd zoals Bootstrap zijn eigen grid maakt. Zie onderstaande SCSS uit de toolkit broncode:

$label-column: $grid-columns / 4;

.form-horizontal {
  .form-group {
    > .control-label {
      @include make-sm-column($label-column);
      text-align: left;
    }

    > .field-container {
      @include make-sm-column($grid-columns - $label-column);
    }
  }
}
Ofwel, de label en .field-container zijn ook kolommen in het grid geworden MITS deze in een .form-group en .form-horizontal zijn geplaatst. Een gevolg hiervan, is dat deze kolommen ook met een gutter gaan werken. De .form-group in en .form-horizontal gedraagt zich al als een .row en heeft negatieve margins.

Van bovenstaande beslissing gaan wij nu al de vruchten plukken: Je geeft aan dat de 25/75 verdeling niet goed is. Zonder dat de implementatoren van de toolkit hun markup moeten aanpassen (anders had er overal col-sm-6 gestaan, kunnen wij vanuit de toolkit de verdeling op een 50/50 zetten.

Ik heb hier een aangepaste versie van jouw plaat bijgevoegd, welke aan het grid voldoet.
Screen Shot 2018-02-01 at 13.32.50 (1).png

:focus, :hover en :active states
In CSS bestaat er geen "click state". Het bijgesloten overzicht mist een :focus en :active state.

**Comment by VolleMelk** [comment]
Opgeleverd: https://www.dso-toolkit.nl/1.2.0-beta.0/components/detail/group-checkboxes.html
