### ISSUE TITLE
Marges formulier elementen

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#421]
Afstand tussen formulier elementen vergroten van 16px naar 32px. Hierdoor creëren we meer rust en witruimte tussen de vragen, en wordt het duidelijker wat bij elkaar hoort.

.form-group { margin-bottom: 32px; }

**Specificaties:**
[Marges formulier elementen.pdf](https://github.com/dso-toolkit/dso-toolkit/files/3690694/Marges.formulier.elementen.pdf)

**Comment by PieterVerheij** [comment]
Testable:
https://www.dso-toolkit.nl/_421.Marges-formulier-elementen/components/detail/form--form-vertical.html
https://www.dso-toolkit.nl/_421.Marges-formulier-elementen/components/detail/aanvragen.html
