### ISSUE TITLE
knop navigatiemenu dso-toolkit.nl labelen

### ISSUE THREAD

**Issue by timveld** [dso-toolkit/dso-toolkit#423]
Het knopje om het navigatiemenu te openen en sluiten heeft geen label. Aangezien dat een echte showstopper is stel ik voor dat we zo snel mogelijk een title attribuut met "toom navigatiemenu" resp. "verberg navigatiemenu", dat kun je met 2 regeltjes javascript doen. Er zijn ook problemen met het menu zelf (landmarks / focus) maar dat is minder storend en we moeten even nadenken hoe we dit willen oplossen, kom ik later op terug.

**Comment by MichielDHVD** [comment]
Reperatie responsive gedrag. 

Toevoegen van meta tag viewport  om responsive gedrag aan te zetten. Voor zowel de toolkit als de voorbeeld pagina's in de toolkit

**Comment by gofix** [comment]
@PieterVerheij jij bestudeert wat er moet gebeuren en doet een voorstel (PR)

**Comment by PieterVerheij** [comment]
@tfrijsewijk correcte labeling staat in een commit van de nunjcks-ombouw. meta tag nog niet.

**Comment by bramhoosemans** [comment]
Niet meer relevant; open en dichtklappen navigatie niet meer mogelijk.
