### ISSUE TITLE
Shopping cart uitbreiding

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#425]
Uitbreiding op https://dso-toolkit.nl/8.5.0/components/detail/shopping-cart--open.html waarbij de initiatiefnemer een kenmerk kan toevoegen/wijzigen bij een activiteit.

Om visueel meer onderscheid te maken tussen de items wordt de padding vergroot naar 16px boven/onder, scheidingslijn 1px en 4px border radius toegevoegd, zie specificaties hieronder.

**Specificaties:**
[winkelwagen-uitbreiding.zip](https://github.com/dso-toolkit/dso-toolkit/files/3696834/winkelwagen-uitbreiding.zip)

![winkelwagen-uitbreiding](https://user-images.githubusercontent.com/598735/66306683-8dd0f980-e902-11e9-9fe1-53897e261ebe.png)

**Comment by PieterVerheij** [comment]
@bramhoosemans work in progress: https://www.dso-toolkit.nl/_425.Shopping-cart-uitbreiding/components/detail/shopping-cart--open.html

**Comment by gofix** [comment]
Ineens vraag ik me af of alle contrastregels wel correct worden nageleefd:
- het alert driehoekje (geel) lijkt een wat slecht contrast te hebben met het vrij donkere grijs;
- het groene pruillenbakje lijkt ook wat slecht te contrasteren met dat grijs;
@PieterVerheij kun jij die waarden even opmeten?

**Comment by bramhoosemans** [comment]
> * het alert driehoekje (geel) lijkt een wat slecht contrast te hebben met het vrij donkere grijs;

Klopt, dit is echter wel een 'grijs' gebied ;) Het belangrijkste element uit het icoon is het uitroepteken; die is volledig zwart en heeft voldoende contrast met de omgeving. In dit geval zou je kunnen stellen dat het driehoekje een decoratieve -of- versterkende functie heeft.

Nu merk ik echter wel dat er inconsistenties ontstaan in de presentatie van de indicatoren (iconen), want in de accodion https://github.com/dso-toolkit/dso-toolkit/issues/457 zetten we er een witte border omheen. Mijn voorstel is dan ook om overal een 1px wit in de indicatoren op te gaan nemen. Ik zal dit verder afstemmen met de andere UX designers.

Voor dit issue laten zoals het is; dit lossen we op met een icoon update.

> * het groene pruillenbakje lijkt ook wat slecht te contrasteren met dat grijs;

De groene iconen hebben een contrast van 3.59:1 ten opzichte van de grijze achtergrond, dus voldoen aan de vereiste 3.1:1 contrastverhouding.

**Comment by bramhoosemans** [comment]
@PieterVerheij het branche voorbeeld ziet er al goed uit!

Ik vroeg me af of jullie het formaat van de iconen nu nog zelf zetten of (straks) gebruik maken van de viewBox="0 0 24 24" in de svg?

**Comment by PieterVerheij** [comment]
Die wordt hier css-end gezet. In de sprite is hij groter.

**Comment by bramhoosemans** [comment]
Voor ik het vergeet; @tfrijsewijk en ik hebben nog wel vraagtekens bij de toegankelijkheid van het wijzigen van de activiteitsnaam. In het ontwerp is gebruik gemaakt van een patroon dat ook wordt ingezet bij het wijzigen van de verzoeknaam. Door het ontbreken van de 'submit' knop zou er verwarring kunnen ontstaan.

Graag zouden we dit testen middels een branche release; maar ik vraag me af of dit mogelijk is (zonder js)?

**Comment by tfrijsewijk** [comment]
Ik heb de edit state toegevoegd, die miste nog. Ik heb twee varianten toegevoegd, een plat tekstveld zonder iets extra's. De tweede is een variant met form, label, input, en submit button. Ik heb er een input group van gemaakt met een klein beetje custom styling. Het gaat mij niet om de visuele uiting, maar om de markup.

Bij de eerste variant is blur en enter het save-moment. Bij de tweede variant is het form "submit" het save-moment. Overigens mist de tweede variant nog een optie om te annuleren, maar de eerste variant voorziet daar trouwens ook niet in.

Enfin, @timveld en UX-ers.. Hoe verder? https://dso-toolkit.nl/_425.Shopping-cart-uitbreiding/components/preview/shopping-cart.html

**Comment by timveld** [comment]
* Ik krijg "u heeft 2 activiteiten gekozen knop" -> een label moet duidelijk maken wat de knop doet
* Eerste invoerveld heeft geen label

**Comment by tfrijsewijk** [comment]
>Eerste invoerveld heeft geen label

Ja, zover waren we al. Maar zijn we er als er alleen een label bij wordt geplaatst? Begrijp jij wat het invoerveld dan doet en kan je het versturen? Hoe toegankelijk is een input veld (met label) ZONDER een `form` ?

**Comment by bramhoosemans** [comment]
@timveld zou je naar bovenstaande vraag kunnen kijken?

**Comment by timveld** [comment]
Toegankelijkheid input: of er wel of geen form omheen staat maakt op zichzelf niet uit, het wordt gewoon voorgelezen
Het label moet uiteraard duidelijk beschrijven wat het invoerveld doet. 
Verzenden verwacht ik met een (default) verzendknop, als N.A.V. de invoer een dynamische update plaatsvindt moeten we goed opletten of dit te volgen is. Deze vraag donderdag agenderen?

**Comment by gofix** [comment]
Dit issue was closed, maar @bramhoosemans gaf aan dat we wel degelijk nog moeten kunnen gaan testen/zien of de relevante werkvormen nog correct tonen ook zonder dat er een `form` omheen staat (oid.).

**Comment by bramhoosemans** [comment]
Op basis van de huidige master heb ik nog een paar bevindingen:
- Buttons voldoen niet aan de minimale contrastwaardes op een grijze achtergrond. Hiervoor zal ik een apart issue aanmaken (design issue).
- List item moet 8px marge onder krijgen bij inputfield.
- Tekst in het inputfield 'gewoon' regular weergeven.

<img width="936" alt="Schermafbeelding 2020-02-27 om 14 50 37" src="https://user-images.githubusercontent.com/598735/75451456-e1ef7f80-5970-11ea-8044-c30be20695e8.png">

**Comment by gofix** [comment]
@bramhoosemans volgens mij zijn je bevindingen nu gecorrigeerd, please check https://dso-toolkit.nl/_425.shopping-cart-uitbreiding/components/detail/shopping-cart.html

**Comment by bramhoosemans** [comment]
> @bramhoosemans volgens mij zijn je bevindingen nu gecorrigeerd, please check https://dso-toolkit.nl/_425.shopping-cart-uitbreiding/components/detail/shopping-cart.html

Ziet er goed uit!
