### ISSUE TITLE
Toevoegen button component

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#426]
Nieuwe weergave van activiteiten als button lijst. Als de initiatiefnemer hierop klikt wordt deze zichtbaar geselecteerd en toegevoegd aan ‘Mijn activiteiten’.

Als er meer dan één keer op dezelfde activiteit geklikt wordt verschijnt er ‘x2’ ipv het vinkje. De activiteit wordt nogmaals toegevoegd. In ‘Mijn activiteiten’ wordt de tweede activiteit automatisch doorgenummerd, bijvoorbeeld: Milieubelastende activiteit - Melding 2.

Er is geen beperking in het aantal keer dat een activiteit kan worden geselecteerd.

**Specificaties:**
[Toevoegen.zip](https://github.com/dso-toolkit/dso-toolkit/files/3697187/Toevoegen.zip)

![toevoegen-button](https://user-images.githubusercontent.com/598735/66312032-2326ba80-e910-11e9-897e-b10020d70fa5.png)

![activiteiten-1](https://user-images.githubusercontent.com/598735/66312041-28840500-e910-11e9-935a-52a8b4d08ee7.png)
![activiteiten-2-winkelwagen](https://user-images.githubusercontent.com/598735/66312057-2f127c80-e910-11e9-80bb-0a1fd87a73c3.png)

**Comment by PieterVerheij** [comment]
@bramhoosemans als je per ongeluk op een button klikt, moet je naar boven om het product weer te verwijderen. Zou je in de button ook niet een minnetje willen hebben waarmee je je keuze weer kunt verwijderen (lees aantal verminderen)?

**Comment by bramhoosemans** [comment]
@PieterVerheij Dat heb ik bewust niet gedaan. Het idee is namelijk dat je 2x dezelfde activiteit kan selecteren, bijvoorbeeld om 2 bomen te kappen. Als ik vervolgens vragen heb beantwoord voor boom A en boom B en ik klik in de lijst op een 'min', welke halen we dan weg?

In de toekomst zou ik graag werken aan een betere layout zodat je niet hoeft te scrollen om bij de selectie te komen.

**Comment by PieterVerheij** [comment]
@bramhoosemans daar heb je een punt ;) We gaan er mee aan de slag!

**Comment by PieterVerheij** [comment]
@bramhoosemans hoe zou je deze knop in de navigatie van de toolkit (dus in het engels noemen)? We komen zelf niet verder dan 'Add button' maar dat denkt de landing niet helemaal?

**Comment by bramhoosemans** [comment]
@PieterVerheij er is een directe link met de winkelwagen, dus wellicht is 'tocart' een betere beschrijving?

**Comment by MichielDHVD** [comment]
We gaan dit component nooit ergens anders gebruiken dan wanneer er een shoppingcart. Is wel heel specifiek. Is List Button een optie?

**Comment by PieterVerheij** [comment]
Niet denken dat je het nergens anders gaat gebruiken, is soms een beetje gevaarlijk ;-) Laten we voorlopig 'list button' aanhouden, dat is neutraler.

**Comment by PieterVerheij** [comment]
@bramhoosemans zie https://www.dso-toolkit.nl/_426.Toevoegen-button-component/components/detail/list-button--default.html . In de navigatie zijn de andere varianten te selecteren.

**Comment by gofix** [comment]
Zoals in mijn comments op de PR te lezen, denk ik dat nog aandacht besteed moet worden aan de toegankelijkheid van de bouwsteen. Het 'vinkje' als iemand iets geselecteerd heeft zegt visueel wel iets, maar een screenreader kan daar niets mee. Zelfde geldt voor de '2x' als iemand '2 bomen' heeft geklikt. 

Op zijn minst zullen we ergens moeten duiden wat de staat van de knop is: misschien is `aria-pressed` een eenvoudige oplossing. Maar explicieter kan natuurlijk ook, dat er bv. bij het 'checked' icoon een visually hidden tekstje ("geselecteerd") komt, en bv. bij de "2x" ook (dat leest dan als "2x geselecteerd).

**Comment by PieterVerheij** [comment]
@timveld zie https://www.dso-toolkit.nl/_426.Toevoegen-button-component/components/detail/list-button--button-selected.html en https://www.dso-toolkit.nl/_426.Toevoegen-button-component/components/detail/list-button--button-multiple-selected.html
Is dit een juiste uitwerking (met "geselecteerd" in de `span.sr-only`) of verwacht je ook nog een `aria-pressed`?

**Comment by timveld** [comment]
Ik begrijp het niet helemaal (kan de grafische schetsen niet bekijken alleen de live demo) maar als het bedoeld is als toggle button kun je beter aria-pressed gebruiken dan de sr-only in dit voorbeeld. 2 keer dezelfde activiteit in een lijst (onder dezelfde naam) klinkt ook verwarrend, maar begrijp niet helemaal wat de context hiervan is. Donderdag bespreken?

**Comment by bramhoosemans** [comment]
@timveld Op dit moment is de lijst activiteiten een checkbox lijst, oftewel een activiteit is slechts één keer te selecteren. De functionele wens is dat dezelfde activiteit meerdere keren geselecteerd kan worden. Hierdoor kan de initiatiefnemer een vragenlijst invullen voor een specifieke situatie, bijvoorbeeld bij het plaatsen van verschillende opslagtanks.

Hiervoor is een button element bedacht met een 'tellertje' dat aangeeft hoevaak een activiteit geselecteerd is. In de winkelwagen krijgt de activiteit een volgnummer én kan de initiatiefnemer een extra label toevoegen voor de herkenbaarheid.

**Comment by timveld** [comment]
OK begrijp het beter, klinkt naar een grid met doordacht gelabelde elementen zoals we de vorige keer hebben uitgetest. Komt in een van de komende overleggen ongetwijfeld nog voorbij.

**Comment by timveld** [comment]
Zijn we het niet veel moeilijker aan het maken dan nodig?

Als ik het goed samenvat: de aanvraag bestaat uit meerdere activiteiten en elke activiteit valt onder een bepaalde categorie (activiteiten "schuurtje" en "tuinhuisje" in de categorie "bijbehorend bouwwerk plaatsen", activiteit "huisbatterijverwerker in voortuin" in "milieubelastende activiteit" enzovoort). 

Voor iedere activiteit moet een categorie-afhankelijke vragenlijst worden ingevuld. 

Dat is dan toch 1 statusoverzicht met op (heading) niveau 2 de categorieën ('bijbehorend bouwwerk plaatsen') met op niveau 3 de activiteiten waarvoor de vragenlijst al dan niet is ingevuld ('schuurtje ingevuld', 'tuinhuisje niet ingevuld')? En de activiteiten moet je dan kunnen verwijderen. Natuurlijk prima om de categorieën inklapbaar te maken en het totale aantal per categorie tussen haakjes er achter te zetten als dat overzichtelijker is.

Als je een activiteit toevoegt, moet je gedwongen worden deze meteen een naam te geven. Het is prima als je de vragenlijst pas later gaat invullen maar als we de gebruiker toestaan om "10X milieubelastende activiteit" toe te voegen, dan gaat hij de weg kwijtraken. Ik weet niet of er überhaupt geldige redenen zijn om 'naamloze activiteiten' toe te willen voegen, maar als naamloze activiteiten al voordelen hebben dan moeten we de gebruiker misschien toch tegen zijn eigen rommelige gedrag beschermen om te voorkomen dat hij later activiteiten finaal door elkaar gaat halen.

Kortom: ik zou voorstellen 1 statusoverzicht en afdwingen dat de gebruiker iedere activiteit een naam geeft.

**Comment by bramhoosemans** [comment]
Zojuist met @timveld afgestemd. Technische werking van de buttons is prima, met uitzondering van een typefout "geselecteed" in https://www.dso-toolkit.nl/_426.Toevoegen-button-component/components/detail/list-button--button-multiple-selected.html :)

Het component in context, samenwerking met de winkelwagen, kan op dit moment niet beoordeeld worden. Dit volgt na implementatie.

**Comment by PieterVerheij** [comment]
> typefout "geselecteed"

Sorry, dat is mijn haagse accent wat ik af en toe niet kan onderdrukken ;-)

**Comment by timveld** [comment]
check, zo is de button technisch goed
