### ISSUE TITLE
Font awesome verdwijnend icoon

### ISSUE THREAD

**Issue by micheldebree** [dso-toolkit/dso-toolkit#427]
Dit gedrag doet zich voor sinds toolkit 8.4 (npm versie), we zijn nu genoodzaakt op 8.3 te blijven.

We hebben een React frontend (RTR) waar we een boom in- en uitklappen, waarbij het icoontje voor een 'tak' verandert tussen plus en min al naar gelang die tak is uitgeklapt of niet.

De DOM switched tussen de volgende twee classes:
```html
<a role="link" tabindex="0"><i class="fa fa-plus-square"></i></a>
```
en
```html
<a role="link" tabindex="0"><i class="fa fa-minus-square"></i></a>
```
Na de eerste klik verdwijnt het icoon, nieuwe klikken op de plek van het icoon werken wel, maar het icoon blijft weg. Pas na klikken ergens anders waar dan ook binnen het browser scherm (zelfs in het debug 'onderwater' scherm) komt de icoon terug, dus ook bij kliks die geen verandering in de DOM tot gevolg hebben.

**Comment by tfrijsewijk** [comment]
@micheldebree Ik denk dat je tegen focus styling aanloopt. Kan je eens kijken of je het met `:focus` op de `a` vanuit de developer tools kan reproduceren? Michiel heeft hard aan focus styling gewerkt in #367, wellicht dat dit een regressie is

**Comment by tfrijsewijk** [comment]
PS: Wat is RTR?

**Comment by tfrijsewijk** [comment]
Zoals het er nu uitziet wordt de aankomende release breaking, juist vanwege iconen. De toolkit gaat over naar een SVG spritesheet. Zie #414 voor meer informatie.

Als het geen showstopper is, stel ik voor het nu te laten. Wij gaan waarschijnlijk geen fix uitbrengen om dit probleem op te lossen, aangezien er al een hele andere oplossing is.

Je kan het zelf oplossen met wat inline styling. Ik verwacht dat je er met `style="{ color: 'inherit' }"` er al bent: Het style attribuut is specifieker dan de problematische selector (`a:hover`) en met `color: 'inherit'` overrule je de kleur wijziging uit `a:hover`.

**Comment by tfrijsewijk** [comment]
Hi @micheldebree, begin deze week is versie 9.0.0 uitgekomen met de SVG spritesheet. Ik sluit dit issue, ik vermoed dat je er geen last meer van hebt zodra je over bent naar versie 9.

Mocht je nog steeds hetzelfde probleem hebben, voel je vrij dit issue weer te openen en dan lossen we het voor je op!
