### ISSUE TITLE
Radiobuttons redesign

### ISSUE THREAD

**Issue by Poofy83** [dso-toolkit/dso-toolkit#43]
Radio buttons zijn herontworpen. 

![image](https://user-images.githubusercontent.com/5871330/37092604-c5175bb4-220c-11e8-9911-a3feb46fcba3.png)

Kleuren en border: 

Border: 2px solid #A8BCAE
Kleur selected: #39870C 

/Original reporter: Michael

**Comment by VolleMelk** [comment]
Opgeleverd: https://www.dso-toolkit.nl/1.2.0-beta.0/components/detail/group-radios.html
