### ISSUE TITLE
dso-icons.svg via instelbaar pad inlezen

### ISSUE THREAD

**Issue by gofix** [dso-toolkit/dso-toolkit#435]
Als ik in mijn react-applicatie de dso-toolkitversie naar 9.0.0 breng, krijg ik een foutmelding wanneer ik `@import "dso-toolkit/src/dso";`, bij het bouwen van de react-app.
```
Can't resolve '../dso-icons.svg'
```

Dat komt omdat in de gegenereerde css dat als pad staat. Dat pad kan in een applicatie anders zijn en moet dus instelbaar zijn, net zoals het geval is voor:
`$asap-font-path` en eerder voor `$fa-font-path`,`$icon-font-path` en `$dso-icon-font-path`.

**Comment by gofix** [comment]
Deels 'my bad', ik had me dit moeten realiseren toen ik in https://github.com/dso-toolkit/dso-toolkit/commit/d092c04274ed488d1fa63938e2cb5140c53a9612#diff-f8cddc0976d18bac712da02c1266df0cL110 heb gezien dat inderdaad `$icon-font-path` en `$dso-icon-font-path` verwijderd zijn.

**Comment by gofix** [comment]
Ik zie in het https://github.com/dso-toolkit/dso-toolkit/blob/master/CHANGELOG.md wel staan:

> Als de toolkit scss files worden gecompileerd, moet de implementatie zorg dragen dat uiteindelijk node_modules/dso-toolkit/dist/library/dso-icons.svg wordt gebundled;

🤔

**Comment by gofix** [comment]
Dat klopt niet, `dso-icons.svg` staat niet in `node_modules/dso-toolkit/dist/library/` maar in `node_modules/dso-toolkit/dist/`

**Comment by tfrijsewijk** [comment]
He Ad, wat vervelend dat je problemen hebt met versie 9.0.0.

Als ik het goed begrijp krijg je tijdens het builden een foutmelding dat het niet lukt om de SVG spritesheet te resolven.

Kan je de de `package.json` delen, of in ieder geval de property's `dependencies`, `devDependencies`, en `scripts` ?

>Dat klopt niet, `dso-icons.svg` staat niet in `node_modules/dso-toolkit/dist/library/` maar in `node_modules/dso-toolkit/dist/`

Je hebt gelijk dat er een typefout staat. Eigenlijk moet er verwezen worden naar de `dso-icons.svg` in de `dist/toolkit` directory. Ik zal hier een bug issue voor aanmaken.

Neemt niet weg dat `dso-icons.svg` toch wel echt in `dist/library` en in `dist/toolkit` staat:

![image](https://user-images.githubusercontent.com/9696261/66896422-0b78c180-eff5-11e9-9072-b3ada2eec50d.png) 
![image](https://user-images.githubusercontent.com/9696261/66896439-129fcf80-eff5-11e9-83e4-b2b93726077d.png)

**Comment by gofix** [comment]
Relevant gedeelte van de `package.json`:
```
  "dependencies": {
    "async-lifecycle": "^0.2.10",
    "babel-polyfill": "^6.26.0",
    "classnames": "^2.2.5",
    "dso-toolkit": "^9",
    "empty": "^0.10.1",
    "isomorphic-fetch": "^2.2.1",
    "lodash": "^4.17.4",
    "moment": "^2.20.1",
    "prop-types": "^15.5.10",
    "react": "16.8.6",
    "react-dom": "16.8.6",
    "react-router": "^5",
    "react-router-dom": "^5",
    "react-safeinnerhtml": "^0.2",
    "redux": "^4",
    "redux-react-hook": "^3.0.4",
    "redux-thunk": "^2.2.0",
    "reselect": "^4"
  },
  "devDependencies": {
    "@storybook/react": "^5",
    "autoprefixer": "^9",
    "eslint-config-airbnb": "^18",
    "eslint-config-prettier": "^6",
    "eslint-plugin-import": "^2.9.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-lodash-fp": "^2.1.3",
    "eslint-plugin-prettier": "^3",
    "eslint-plugin-react": "^7.7.0",
    "eslint-plugin-react-hooks": "^2.0.0",
    "node-sass": "^4.7.2",
    "npm-run-all": "^4.1.2",
    "postcss-cli": "^6",
    "prettier": "^1.11.1",
    "react-scripts": "^3"
  },
  "scripts": {
    "build-css": "node-sass --include-path=node_modules/dso-toolkit/node_modules --include-path=node_modules src/styles/main.scss --output src/styles/ --output-style compressed && postcss -u autoprefixer --local-plugins -o ./src/styles/main.css ./src/styles/main.css",
    "watch-css": "npm run build-css && node-sass --include-path=node_modules/dso-toolkit/node_modules --include-path=node_modules src/styles/main.scss --output src/styles/ --watch --recursive",
    "start-react": "react-scripts start",
    "build-react": "react-scripts build",
    "start": "npm-run-all -p watch-css start-react",
    "build": "npm-run-all -s build-css build-react",
    "test": "react-scripts test --env=jsdom --setupTestFrameworkScriptFile=./src/jest.init.js",
    "start-storybook": "start-storybook -p 9009 -s public",
    "storybook": "npm-run-all -p watch-css start-storybook",
    "publish-storybook": "build-storybook -s public",
    "build-storybook": "npm-run-all -s build-css publish-storybook",
    "prettier": "prettier --write src/**/*.js* package.json",
    "lint": "eslint -c .eslintrc.yml src/**/*.js*",
    "edge": "yarn && yarn upgrade && yarn prettier"
  }
```
In de `main.scss` van mijn toepassing stond:
```
$asap-font-path: "~dso-toolkit/dist/toolkit/fonts/asap/";
$fa-font-path: "~dso-toolkit/dist/toolkit/fonts/fontawesome/";
$icon-font-path: "~dso-toolkit/dist/toolkit/fonts/bootstrap/";
$dso-icon-font-path: "~dso-toolkit/dist/toolkit/fonts/DSO-IconFont/";

@import "dso-toolkit/src/dso";
```

Daaruit kunnen nu weg:
```
// $fa-font-path: "~dso-toolkit/dist/toolkit/fonts/fontawesome/";
// $icon-font-path: "~dso-toolkit/dist/toolkit/fonts/bootstrap/";
// $dso-icon-font-path: "~dso-toolkit/dist/toolkit/fonts/DSO-IconFont/";
```

**Comment by tfrijsewijk** [comment]
Klopt het dat je deze error krijgt omdat je geen gebruik maakt van de webpack van CRA/react-script tijdens het builden?

Je hebt een prima actuele `react-scripts`. Hiet zit een configuratie in dat .svg files gebundled worden. Dan moet je natuurlijk wel gebruik maken van webpack.

Ik zie dat je ook direct `node-sass` kan starten, daar zit geen enkel bundling mechansime achter. Dan zul je inderdaad zelf die svg moeten verplaatsen. Gelukkig heb je al een PR (#437) aangemaakt waarin je die variable kan aanpassen :-)

**Comment by tfrijsewijk** [comment]
Instelbaar vanaf versie 9.1.0
