### ISSUE TITLE
Icons in (primaire, secundaire en default) buttons, verloren gegane modifiers, margins

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#438]
Er is een icon button bij gekomen. 

Maar dit neemt niet weg dat het voor kan komen dat er bij een secundaire knop soms ook een icoon gebruikt kan worden. Er zijn bestaande ontwerpen die dit geimplementeerd hebben en deze vorm mag dan ook blijven bestaan. 

Nu lijkt dit weg gehaald te zijn en is ook de margin tussen icoon en tekst weg gehaald. 

In toolkit versie 8.5.0 was er nog een margin van 4px tussen iconen en tekst. Dit mag terug gezet worden. 

![Screenshot 2019-10-21 at 12 17 48](https://user-images.githubusercontent.com/36912722/67200070-153e6280-f403-11e9-8412-53ce67121bda.png)

In deze afbeelding heeft de developer een margin van 8px neergezet. Maar de eerdere 4px uit 8.5.0 is prima

**Comment by gofix** [comment]
In het CMS kun je ook links markeren als knop, en als zo'n link een externe of downloadlink is dan krijgt 'ie nog een extra modifier class.

Dat lijkt nu niet 'zomaar' meer te werken:
![image](https://user-images.githubusercontent.com/2689559/67239435-7be96d80-f44f-11e9-8c29-1e52dc1e2117.png)

En/maar als ik terugkijk naar hoe dit was < 9.x.x zie ik dit:
![image](https://user-images.githubusercontent.com/2689559/67239486-96bbe200-f44f-11e9-9f86-42662e2ab081.png)

Da's inderdaad die 4px margin die je noemt, @MichielDHVD , we gaan uitzoeken wat hier nu eigenlijk de beste oplossing voor is.

**Comment by gofix** [comment]
Ik zie nu dat wat ik in het CMS ervaar een gevolg is van de wijzigingen van issue https://github.com/dso-toolkit/dso-toolkit/issues/372 

Zoals in de changelog.md te lezen:
https://github.com/dso-toolkit/dso-toolkit/blob/master/CHANGELOG.md#tertiaire-button-btn-link-redesign-372

"De modifier .download en .extern zijn op .btn niet meer toegestaan. Het label van een .btn dient vanaf nu in een span te zitten."

**Comment by gofix** [comment]
Kortom: mijn bevindingen hierboven betreffen puur de breaking changes van de 9.x.x die nog doorgevoerd moeten worden in de markup/output van het CMS, zodat de styling uit deze toolkit versie z'n werk kan doen.

Als we echter naar de concrete melding van @MichielDHVD kijken, en naar https://dso-toolkit.nl/9.1.0/components/detail/buttons.html, zie ik dat de mogelijkheid tot het opnemen van iconen IN een knop nu eigenlijk alleen ondersteund wordt voor de tertiaire button. 

Als we puur naar die tertiaire button kijken lijkt daarin alles wel prima in orde, zie deze voorbeelden die zijn opgenomen:
![image](https://user-images.githubusercontent.com/2689559/67264489-7cafed00-f4ab-11e9-8572-7458c6d82e40.png)
(paarse rectangles zijn om duidelijk te maken welke 4 knoppen we hier nu eigenlijk zien).
1. `btn btn-link` zonder iconen;
2. `btn btn-link` met een `sr-only` linktekst en icoon (geen marges);
3. `btn btn-link` met een icoon links van de linktekst (dan krijgt de linktekst een `margin-left: 8px`;
4. `btn btn-link` met een icoon rechts van de linktekst (dan krijgt het icoon een `margin-left: 8px`;

Als ik de wens goed interpreteer is deze dus eigenlijk dat dit alles OOK moet gelden voor de secundaire button (dus: `btn btn-default`).
Vragen (@MichielDHVD ):
1. Zou ook voor de primaire button / call-to-action moeten gelden dat je daar iconen in mag opnemen? Vanuit het CMS is dat bv. prima mogelijk.
2. Moet die marge van `8px` inderdaad `4px` worden, in al deze button vormen?

**Comment by MichielDHVD** [comment]
Ik ga met developers en ux'rs overleggen wat wenselijk is.

**Comment by gofix** [comment]
N.a.v. mijn eerste bevindingen met de toolkit update op het CMS. In content kun je dit maken:
![image](https://user-images.githubusercontent.com/2689559/67460850-53729680-f63c-11e9-9fbe-5f81de2077b1.png)

Maar, die iconen IN de knoppen doen het na de toolkit update niet meer. Omdat met 9.x.x we geacht worden het icoon (als `<svg>`) expliciet in de `.btn` op te nemen. Maar... zo is de inhoud niet ingevoerd, en de opgeslagen pagina's (en: versiehistorie daarvan) bevat nog markup waarin dat niet zo was.

Eigenlijk is een dergelijke breaking change verboden, want nu zou content 'uit het verleden' niet meer correct getoond kunnen worden. Theoretisch zou het mogelijk zijn aan CMS-kant of in een gebruikende applicatie een transformatie toe te passen, maar dat is niet wenselijk.

Ik zou willen voorstellen voor de modifiers `.extern` en `.download` - net als in lopende tekst - toch toestaan dat deze op buttons wordt toegepast. En dat dan (met de `:after`) het beoogde icoon verschijnt.

![image](https://user-images.githubusercontent.com/2689559/67461308-4f934400-f63d-11e9-8ac5-c4ccbec56774.png)

**Comment by gofix** [comment]
Concrete vragen/voorstellen:
- Staan we ook in primaire en secundaire buttons toch (net als voorheen) iconen toe;
- Wat is de afstand tussen icoon en label in een knop (ik denk gewoon 8px);
- Gaan we modifiers `.extern` en `.download` op buttons weer toestaan;

NB: als we dat laatste NIET doen, moeten we - ook met CMS-stakeholders - een overleg hebben over hoe we omgaan met dit soort changes.

**Comment by gofix** [comment]
Over https://github.com/dso-toolkit/dso-toolkit/blob/master/CHANGELOG.md#tertiaire-button-btn-link-redesign-372 -> voor het CMS (en met name voor de reeds ingevoerde content) is het op zich voldoende als we de `.extern` en `.download` modifiers alleen voor `a.btn` (dus niet zozeer `button.btn` weer tot leven wekken.

**Comment by gofix** [comment]
Het probleem blijkt nog ietsje groter te zijn dan alleen die `.extern` en `.download` modifiers. De tertiaire button (`btn-link`) bevat standaard een pointer links van het label (al zijn de mogelijkheden sinds deze release dus wat uitgebreider geworden).

In _opgeslagen_ content in het CMS is de markup hiervan:
```
<a href="#" class="btn btn-link"><span class="icon fas fa-angle-right" aria-hidden="true"></span>Levenscyclus</a>
```

Volgens de voorschriften zou dit nu moeten worden:
```
<a href="#" class="btn btn-link">
  <svg class="di di-angle-right">
    <use href="../../dso-icons.svg#angle-right"></use>
  </svg>
  <span>Levenscyclus</span>
</a>
```

Maar, dat is dus nu niet zo. Als er content bestaat waarin de oude notatie werd gehanteerd, zal deze tot het "einde der tijden" als zodanig opgeslagen blijven.

**Comment by gofix** [comment]
Na een uitgebreide impact-analyse zijn we tot de conclusie gekomen dat het zeer onwaarschijnlijk is dat in een van de DSO omgevingen al dergelijke links zijn ingevoerd. Wat dat betreft hoeven we dus ietsje minder bang te zijn voor dat we eerder ingevoerde inhoud geinvalideerd hebben.

Toch - of eigenlijk juist - is nu dan het moment om de juiste keuzes te maken.

**Comment by gofix** [comment]
Nieuw voorstel voor de concrete vragen/voorstellen:

- Ook in primaire en secundaire buttons staan we (net als voorheen) iconen toe;
- Afstand tussen icoon en label in een knop is 8px;
- Modifiers `.extern` en `.download` op (alle!) buttons worden weer toegestaan. In die gevallen hoef/mag je geen `<svg class="di di-external-link">` resp. `<svg class="di di-download">` IN de `.btn` te plaatsen (maar gebeurt dat net als in lopende tekst met een `:after`);
- Op `.btn-link` komt een extra modifier `.btn-link-default` beschikbaar, die visueel hetzelfde doet als wanneer je in een `.btn-link` een `<svg class="di di-angle-right">` zou plaatsen (en dat programmeren we dan met een `:before`).

Dit laatste (en eigenlijk ook het voorstel voor `.extern` en `.download`) is om meer redenen essentieel. Namelijk: als content dergelijke bouwstenen bevat, zou volgens de huidige voorschriften er in de `<svg>` een `<use href>` moeten komen. Maar... het pad naar de `dso-icons.svg` is onbekend! Dat varieert namelijk met hoe dat in een applicatie wordt geimplementeerd. Het lijkt me volstrekt onwenselijk voor developers om dat dan nog weer te moeten omschrijven.

Tegenargument tegen mijn voorstel voor het ondersteunen van de modifier-classes is natuurlijk dat er dan meerdere manieren zijn om 'hetzelfde' te maken. Dat is inderdaad strikt genomen jammer, maar mijns inziens overkomelijk.

**Comment by MichielDHVD** [comment]
Waar ligt het actiepunt. Wie moet wat doen. Ben het nu even kwijt.

**Comment by gofix** [comment]
Ik snap je verwarring @MichielDHVD. In het voorgaande lopen eigenlijk een aantal dingen door elkaar. Voor DSO-toolkit geldt dat volgens mij de volgende zaken wenselijk zijn:
- Ook in primaire en secundaire buttons staan we (net als voorheen) iconen toe;
- Afstand tussen icoon en label in een knop is 8px;

De andere zaken die genoemd worden hebben te maken met het feit dat DSO-toolkit de laatste tijd een enorme evolutie doormaakt, hetgeen resulteert in opeenvolgende breaking changes. Dat zal ongetwijfeld lastig zijn voor applicaties die DSO-toolkit gebruiken, maar voor het CMS levert dit momenteel helemaal een probleem op, omdat daarin markup kan worden gemaakt/ingevoerd die na een major change van de toolkit eigenlijk helemaal niet meer ondersteund wordt. We moeten een strategie bedenken over hoe met deze problematiek om te gaan. Laten we dat loskoppelen van _dit_ issue.

**Comment by bramhoosemans** [comment]
Hierbij de uitgewerkte specificaties van buttons. Zoals besproken zal er nog uitgezocht worden of de .btn-link wordt gebruikt in het CMS. En of 'decoratieve' wijzigingen zijn toegestaan in reeds gepubliceerde teksten in de toekomst.

Als er vragen zijn hoor ik het graag.

![button-specs](https://user-images.githubusercontent.com/598735/71246730-8c1aad80-2317-11ea-89d2-007aa1108950.png)

**Comment by PieterVerheij** [comment]
@bramhoosemans er is nog een `.btn-sm` modifier, die de hoogte van de knop verandert van 48px in 40px. Ik neem aan dat die behouden moet blijven?

**Comment by PieterVerheij** [comment]
@bramhoosemans 
![image](https://user-images.githubusercontent.com/25430835/73055049-31332380-3e8c-11ea-8d11-9b7655442495.png)

In de specs staat Asap Bold, maar dat toont vetter dan in jouw Sketch ontwerp. In de huidige css staat ook font-weight: 500, dat is semi-bold. Wat zullen we doen?

**Comment by bramhoosemans** [comment]
@PieterVerheij Excuses, we gebruiken inderdaad overal Asap Semi-Bold.

**Comment by PieterVerheij** [comment]
Hi Bram, vergelijk het eerste en het derde scenario: allebei zijn het formulieren met meerdere stappen en in beide gevallen is de eerste knop een secundaire knop. Zonder een wijziging in de markup is er geen onderscheid te maken. 
Maar ik vraag mij af of het derde scenario wel goed is: in een volgende stap kan je dan twee secundaire en 1 primaire knoppen hebben: [< Vorige stap][Standaard button][Volgende stap >]? Zou je in dat geval niet ook een Link button ipv Standaard button gebruiken (dus het tweede scenario)?
![image](https://user-images.githubusercontent.com/25430835/73365469-9b90fd00-42ac-11ea-9b72-2dd00a43b705.png)

**Comment by bramhoosemans** [comment]
Scenario 3 zou inderdaad de eerste stap kunnen zijn van een formulier over meerdere pagina's -of- een formulier met meerdere secties. Deze scenario's hebben we volgens mij vastgelegd in https://github.com/dso-toolkit/dso-toolkit/issues/401.

Of de secondaire actie een link-button of standaard-button is wordt nergens afgedwongen. Dit zou volgens mij dus per situatie kunnen verschillen.

<img width="787" alt="Schermafbeelding 2020-01-30 om 08 59 34" src="https://user-images.githubusercontent.com/598735/73430639-db082980-433e-11ea-9a1a-34f885d0ec11.png">

**Comment by PieterVerheij** [comment]
@bramhoosemans Ik heb de positie van de buttons in de modal gelijkgetrokken met die van het formulier. Maar de logica van wanneer een link-button of secundaire button gebruikt wordt en wanneer er een X bij Annuleren staat heb ik niet aangepast. Ik denk dat we daar nog een keertje kritisch naar moeten kijken en regels moeten vastleggen.

**Comment by bramhoosemans** [comment]
@PieterVerheij Ik begrijp niet hoe modals in dit issue terecht zijn gekomen -en- wat er nu is gewijzigd?

In deze branche release staan de buttons op verschillende posities:
https://dso-toolkit.nl/_438.Icons-in-buttons-modifiers-margins/docs/modals.html
https://dso-toolkit.nl/_438.Icons-in-buttons-modifiers-margins/components/detail/modal--modal.html

**Comment by PieterVerheij** [comment]
Buttons in modals hadden we rechtgetrokken met de formulieren, ervan uitgaande dat dat ook de bedoeling is. Maar die wijziging is teruggedraaid.

**Comment by PieterVerheij** [comment]
https://www.dso-toolkit.nl/_438.Icons-in-buttons-modifiers-margins/components/detail/buttons.html
https://www.dso-toolkit.nl/_438.Icons-in-buttons-modifiers-margins/components/detail/form--form-vertical.html
https://www.dso-toolkit.nl/_438.Icons-in-buttons-modifiers-margins/components/detail/form--multi-page.html
https://www.dso-toolkit.nl/_438.Icons-in-buttons-modifiers-margins/components/detail/form--sections.html
https://www.dso-toolkit.nl/_438.Icons-in-buttons-modifiers-margins/components/detail/form--single-page.html

**Comment by gofix** [comment]
We zien met de recente changes hier (concreet: door de geintroduceerde ruimte TUSSEN buttons), dat de icon-only buttons wat ver uit elkaar staan. Ik denk dat we daar een apart issue aan moeten wijden:
![image](https://user-images.githubusercontent.com/2689559/74254777-36e49200-4cf1-11ea-835d-43d8a14862bc.png)
