### ISSUE TITLE
Iconen accordeon table te groot. 

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#440]
Tijdens de implementatie is gebleken dat soms de iconen te groot zijn. 
<img width="1010" alt="Screen Shot 2019-10-21 at 13 35 37" src="https://user-images.githubusercontent.com/36912722/67202404-d7443d00-f408-11e9-9ac7-b68f75fedea4.png">

Er zijn verschillende variaties in groottes nodig. 

Dit is iets waar vanuit ux naar gekeken moet worden en een guideline voor moet worden opgezet.

**Comment by MichielDHVD** [comment]
huidige status. Afhankelijk van oplevering Iconen zodat we kunnen zien wat er gebeurt als de font awesome iconen vervangen worden.

**Comment by MichielDHVD** [comment]
Bij het opleveren van de nieuwe iconenset ziet de accordeon table met icon-buttons er als volgt uit. 

<img width="976" alt="Screen Shot 2020-01-16 at 07 39 43" src="https://user-images.githubusercontent.com/36912722/72499905-68258b80-3833-11ea-9751-6b0a42be3dfa.png">


PS. reminder we moeten echt iets gaan doen aan de active state van de link-button

**Comment by PieterVerheij** [comment]
Persoonlijk dingetje: ik heb wel steeds het idee dat de chevron-up met groene achtergrond een foutje is. Maar dit hoort zo?

**Comment by MichielDHVD** [comment]
Volgens mij is dit nog een restant van de focus states. Dus ik beschouw het ook als een foutje. Niemand bij ons wil dit volgens mij.

**Comment by MichielDHVD** [comment]
Door nieuwe oplevering iconen en hersizing van iconen in issues #563 en #497 is dit issue opgelost en kan gesloten worden.
