### ISSUE TITLE
Uitlijning info-button met tekst is onjuist. 

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#441]
De info-button staat een paar pixels te laag. 

Met een margin 2px staat deze netter uitgelijnd. 

Info-button plus label terug te zien hier:
https://www.dso-toolkit.nl/9.1.0/components/detail/group-input.html

**Comment by gofix** [comment]
Inderdaad lijkt dat icoon gevoelsmatig wat te laag te staan. Ik heb nog even gechecked of dit wellicht met de recente ombouw naar svg-icons te maken heeft, en alhoewel daar vanuit de visuele regressietest-snapshots wel een minimale shift kan worden gezien, zie ik dat ook voor deze wijzigingen dat symbooltje al wel wat hoger had gemogen.

https://percy.io/dso-toolkit/dso-toolkit/builds/2813024/view/179817727/1280?browser=firefox&mode=diff

**Comment by gofix** [comment]
Ik krijg sterk het idee dat ook dit icoon er baat bij heeft als de magische offset wordt toegepast die we ook op `svg.di` in de `vertical-align` zetten: `$dso-icon-vertical-align: -.17em;`.

**Comment by tfrijsewijk** [comment]
Opgeleverd in 9.2.0: https://dso-toolkit.nl/9.2.0/components/preview/form--form-horizontal.html
