### ISSUE TITLE
Shopping kart toelichting mist icoon in lopende tekst

### ISSUE THREAD

**Issue by gofix** [dso-toolkit/dso-toolkit#445]
In https://www.dso-toolkit.nl/9.1.0/components/detail/shopping-cart--open.html mist in het stuk lopen de tekst onder de werkvorm het icoon:

![image](https://user-images.githubusercontent.com/2689559/67368522-bfd79200-f577-11e9-93d5-c61e4f2d8ddb.png)

(oorzaak lijkt te zijn dat de `.di-warning` hoort te zijn `.di-status-warning`, en dat ook de href van de svg moet wijzen naar `#status-warning`)

**Comment by tfrijsewijk** [comment]
Opgeleverd in 9.2.0: https://dso-toolkit.nl/9.2.0/components/preview/shopping-cart--open.html
