### ISSUE TITLE
Contrastkleur links op gekleurde achtergronden

### ISSUE THREAD

**Issue by gofix** [dso-toolkit/dso-toolkit#446]
Wanneer tabelrijen speciale modifierclasses krijgen om de achtergrondkleur te manipuleren, is de linkkleur soms niet contrastrijk genoeg:
https://www.dso-toolkit.nl/9.1.0/components/detail/rich-content.html

![image](https://user-images.githubusercontent.com/2689559/67369145-cadef200-f578-11e9-800b-8601b82e8b57.png)

Iets dergelijks speelt bij de info indicator:
![image](https://user-images.githubusercontent.com/2689559/67370677-61acae00-f57b-11e9-8d72-f1ee00000623.png)

(zowel de gewone linkkleur (groen) als de hoverkleur (scampi) contrasteren niet genoeg met de achtergrond)

NB. in de highlight box is hier specifiek aandacht aan besteed.

**Comment by MichielDHVD** [comment]
Ik ga even een opzetje maken over welke gedrag wenselijk is.

**Comment by MichielDHVD** [comment]
De oplossing voor dit issue is niet zo simpel als gehoopt. Er zijn componenten die exact dezelfde kleuren gebruiken. In de alerts wordt dit probleem namelijk opgelost door de link kleuren aan te passen naar zwart. 

Vraag aan de rest is, willen we dit? Willen we alleen de links op gekleurde vlakken zwart maken? Of alles Zwart ivm met consistentie. 

Probleem met met alles zwart maken is dat de leesbaarheid van onze bestaande tabellen flink achteruit zal gaan. Want gaan de buttons dan ook naar zwart toe? Handige aan de groene kleur is dat we het vaak als signaal gebruiken. Grasgroen = interactief. 

Misschien ook handig om voor te schrijven wanneer we kleuren willen gebruiken in een tabel. Of misschien of dit uberhaupt wenselijk is.

**Comment by PieterVerheij** [comment]
@MichielDHVD kunnen jullie dit verder oppakken?

**Comment by MichielDHVD** [comment]
dit ligt idd bij ons.

**Comment by bramhoosemans** [comment]
Tekstlinks op achtergrondkleur voldoen niet aan de vereiste contrastverhouding. Voor tabellen gaan we de contextual classes weghalen en links zwart met underline weergeven. Zie https://github.com/dso-toolkit/dso-toolkit/issues/564
