### ISSUE TITLE
In sluitknop van modal is het icoon niet netjes gecentreerd

### ISSUE THREAD

**Issue by gofix** [dso-toolkit/dso-toolkit#447]
![image](https://user-images.githubusercontent.com/2689559/67371079-11821b80-f57c-11e9-88d7-5b71954e0c37.png)

https://www.dso-toolkit.nl/9.1.0/components/detail/modal--modal-close.html

**Comment by tfrijsewijk** [comment]
Opgeleverd in 9.2.0: https://dso-toolkit.nl/9.2.0/components/preview/shopping-cart--open.html
