### ISSUE TITLE
Toggle documentatie

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#453]
In issue #419 was geprobeerd om het toggle component toe te voegen aan de toolkit. 

Maar omdat de bouw van het toggle component teveel samenhang heeft met de taal waarin het geprogrammeerd wordt kan het niet framework agnostisch worden gebouwd. 

Wat wel kan worden geleverd is een Documentatie pagina's met de beschrijving van de toggle button en hoe deze geimplementeerd wordt. 

Hier aan gekoppeld zal een sketch bestand zijn. Zodat duidelijk de afmetingen, kleurgebruik gecommuniceerd kunnen worden.

**Comment by timveld** [comment]
Ik heb NAV de discussie donderdag wat onderzoek gedaan en goed gebruik van aria-pressed lijkt voor toggle buttons in principe voldoende, NVDA kondigt het netjes aan als een toggle button. Uiteraard is het wel belangrijk dat het label duidelijk is, bedenk dat een screen reader gebruiker iets hoort als: "historische bouwvergunningen weergeven schakelknop [ingedrukt / niet ingedrukt]", laat je in dit voorbeeld 'weergeven' weg dan is het doel van de knop mogelijk niet duidelijk. Ook heel lange labels zijn vervelend, een voorbeeld uit Windows:  
"Let apps use advertizing ID to make adds more interesting to you based on your app activity (turning this will reset your ID) toggle button [pressed / not pressed]" 
Interessant (zeer uitgebreid) artikel over onder meer dit thema 
https://www.deque.com/blog/accessible-aria-buttons/

**Comment by bramhoosemans** [comment]
@DHvD-Michael Gebruiken we nog een andere toggle vorm dan de Viewer? Anders kunnen we dit issue sluiten wat mij betreft.

**Comment by DHvD-Michael** [comment]
Dit issue kan wat mij betreft worden gesloten. Zover ik weet word buiten de Viewer geen andere toggle vorm gebruikt. N.B. Dit is ook tijdens het UX overleg van 24 maart besproken.
