### ISSUE TITLE
Icoon .status-danger toevoegen aan conclusion component

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#454]
In het conclusion component willen we ook gebruik maken van het .status-danger icoon.
https://dso-toolkit.nl/9.2.0/components/detail/conclusion.html

<img width="863" alt="Schermafbeelding 2019-11-05 om 10 05 58" src="https://user-images.githubusercontent.com/598735/68193751-f2d84780-ffb3-11e9-90ab-9d23497f3346.png">

**Comment by DjangoBlok** [comment]
Ik zie twee verschillende statussen die hetzelfde icoon gebruiken (alleen de kleur is anders). 
Qua toegankelijkheid en duidelijkeid, lijkt het mij belangrijk hier verschil in te maken.

**Comment by bramhoosemans** [comment]
> Ik zie twee verschillende statussen die hetzelfde icoon gebruiken (alleen de kleur is anders).
> Qua toegankelijkheid en duidelijkeid, lijkt het mij belangrijk hier verschil in te maken.

De gebruikte iconen geven een extra indicatie van het type conclusie en zijn ondergeschikt aan de tekst. Daarnaast geven we zelfs in 'bold' weer wat de conclusie is. Je zou kunnen stellen dat de iconen hier decoratief gebruikt worden.

**Comment by tfrijsewijk** [comment]
Opgeleverd in 9.3.0:
* https://dso-toolkit.nl/9.3.0/components/detail/group-checkboxes.html (en andere form groups)
