### ISSUE TITLE
Accordion component uitbreiding

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#457]
Aanpassingen:
1. Volledigheid aanvraag; bij het verlaten van een vragengroep wordt rechts in de accordion titel getoond hoeveel vragen er beantwoord zijn.
2. Beter contrast iconen in accordion titel; 1px #FFF border toevoegen. Willen we dit in de SVG of in de code specifiek voor de accordion?
3. Bijlage indicator op het moment dat een document wordt toegevoegd.

Specificaties:
[Accordion component.zip](https://github.com/dso-toolkit/dso-toolkit/files/3862938/Accordion.component.zip)

![desktop](https://user-images.githubusercontent.com/598735/69133278-f096e280-0ab5-11ea-8b29-242eb5d144ed.png)
![mobiel](https://user-images.githubusercontent.com/598735/69133288-f260a600-0ab5-11ea-8bb9-48b2639d059e.png)

**Comment by PieterVerheij** [comment]
@bramhoosemans De border zal in het plaatje van het error-icon moeten zitten. Wordt deze dan 26*26 inclusief border, of 24*24? En in dat laatste geval: verkleinen we de versie van het error-icon zonder border dan naar 22*22 om hem visueel even groot te laten lijken?

**Comment by bramhoosemans** [comment]
@PieterVerheij Ai, daar was ik al bang voor. Na overleg denk ik dat de beste oplossing is om een variant met witte border te maken van het 'status-danger' icoon.

Antoinette is bezig met de iconenset en neemt deze gelijk mee. De overige status iconen worden dan optisch gelijk getrokken.

**Comment by PieterVerheij** [comment]
Hi @bramhoosemans Is het theoretische mogelijk dat je twee iconen tegelijk hebt: een paperclip en het error-icon?

**Comment by bramhoosemans** [comment]
Nee, zover ik weet niet.

- Als er één of meerdere documenten wordt toegevoegd als bijlage verschijnt een teller (met paperclip).
- Als een verplichte bijlage niet is toegevoegd verschijnt er een error-icon.
- Als er een validatiefout optreedt, bijvoorbeeld verkeerd bestandsformaat, dan wordt het document niet toegevoegd.

**Comment by PieterVerheij** [comment]
@bramhoosemans zie https://www.dso-toolkit.nl/_457-v2.Accordion-component-uitbreiding/components/detail/accordion.html

1. Volledigheid aanvraag; bij het verlaten van een vragengroep wordt rechts in de accordion titel getoond hoeveel vragen er beantwoord zijn.
`span` met class `dso-accordion-counter` toegevoegd
2. Beter contrast iconen in accordion titel; 1px #FFF border toevoegen. Willen we dit in de SVG of in de code specifiek voor de accordion?
Die iconen kunnen jullie aanleveren. Zie ook opmerking in #480 
3. Bijlage indicator op het moment dat een document wordt toegevoegd.
Class 'dso-attachemnt` triggert het icoontje.

**Comment by bramhoosemans** [comment]
@PieterVerheij Cool, ziet er goed uit. Ik voorzie geen problemen bij implementatie. De witte rand bij de indicatoren (iconen) worden in de SVG toegevoegd en hoeven dus niet in de code te worden gezet.

**Comment by tfrijsewijk** [comment]
Merged #496 into master

**Comment by tfrijsewijk** [comment]
Opgeleverd in 9.7.0: https://dso-toolkit.nl/9.7.0/components/detail/accordion.html
