### ISSUE TITLE
Iconen in tables te groot

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#464]
Bij het overstappen naar de svg's zijn de iconen in de tables ontzettend groot geworden. Het verschil is duidelijk te zien bij de accordion table en vervolgens te switchen naar een oudere versie. 

https://dso-toolkit.nl/9.3.0/components/detail/accordion-table.html
https://dso-toolkit.nl/8.5.0/components/detail/accordion-table.html

De oorspronkelijke iconen in een table waren 16*16 nu zijn ze 24*24. 

Iconen voor tables mogen terug gezet worden naar de 16*16 grootte.

**Comment by MichielDHVD** [comment]
In samenspraak met @bramhoosemans we gaan deze even parkeren totdat de nieuwe iconen er in zitten vervolgens gaan we kijken of er aanpassingen zijn en waar deze moten gebeuren. Wordt uiteindelijk bevonden dat deze issue overbodig is wordt deze gesloten.

**Comment by bramhoosemans** [comment]
Issue gelijk aan https://github.com/dso-toolkit/dso-toolkit/issues/440, vandaar gesloten.
