### ISSUE TITLE
Het icoon van de info button is te klein.

### ISSUE THREAD

**Issue by PieterVerheij** [dso-toolkit/dso-toolkit#468]
Het lijkt erop dat deze te klein in de sprite terechtkomt : https://www.dso-toolkit.nl/9.3.1/dso-icons.svg#img-info-active

**Comment by PieterVerheij** [comment]
Ze komen te klein in de sprite, omdat in de source svg's nog een `@width` en `@height` op de `<svg>` node staan. Weggehaald en sprite opnieuw gecreeerd.

**Comment by tfrijsewijk** [comment]
Dit is veroorzaakt door een `gulp-svgmin` update in `package.json` in #375. Ik heb de change kleiner gemaakt: alleen `@width` en `@height` verwijderd ipv de bronbestanden door svgomg te trekken en in te checken.

Overigens is dit alleen een probleem als `@width` en `@height` dezelfde width/height in `@viewBox` hebben. De routine verwijderd dan alle 3 de attributen waardoor niets meer weet wat het moet doen

**Comment by tfrijsewijk** [comment]
9.3.1 is geen "echte" release, dit is mijn testrelease. De bug zit alleen nog in master en daarom fix ik het in het kader van #375. Thanks voor het melden!
