### ISSUE TITLE
Sketch implementatie voor Toolkit

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#471]
Soms kunnen we geen live view tonen van componenten omdat deze te sterk samenhangen met de framework implementatie. 

Om developers toch te helpen moeten we een visuele representatie van het component geven. 

Om het gevoel te geven dat we voor deze situatie ook een bron van waarheid creëeren willen we een sketch implementatie zodat daar alle vormgeving uit ontsloten kan worden als we geen live view van componenten kunnen tonen.

**Comment by MichielDHVD** [comment]
@tfrijsewijk ik neem aan dat het vooral even experimenteren is wat mogelijk is of niet? Dat vervolgens inbakken en combineren met onze huidige werkwijze

**Comment by PieterVerheij** [comment]
Ik ben benieuwd wat de "developer handoff" gaat inhouden bij de volgende release van Sletch in januari: zie filmpje onderaan de pagina op https://blog.sketchapp.com/whats-next-for-sketch-in-2020-fbac2317e7b4

**Comment by bramhoosemans** [comment]
De 'developer handoff' ziet er inderdaad interessant uit! Wat ik zo kan zien moeten de bestanden dan op de Sketch Cloud staan en kun je een link genereren met inspect mode.

**Comment by bramhoosemans** [comment]
Voorlopig gaan we handmatig een Measure export toevoegen. In afwachting van verdere ontwikkelingen in gebruik van Sketch Cloud (en daarin Developer Handoff) wordt dit issue gesloten.
