### ISSUE TITLE
Banners

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#472]
Gebruik banners bovenaan het scherm om foutmeldingen (rood) of waarschuwingsmeldingen (geel) te geven met informatie die van invloed is op het vermogen van de gebruiker om het product te gebruiken. 

Banners moeten één voor één verschijnen, mogen alleen verdwijnen als het betreffende probleem is opgelost of door de gebruiker worden weggeklikt. Ze kunnen puur informatief zijn of een link bevatten.

Openstaande vragen:

- Moeten banners ook een 'role-alert' krijgen?

Specificaties:
[banners.zip](https://github.com/dso-toolkit/dso-toolkit/files/3932521/banners.zip)

![banners](https://user-images.githubusercontent.com/598735/70329208-1ef91980-183b-11ea-8a22-b6a7feacb5a1.png)

**Comment by PieterVerheij** [comment]
- Moet deze met een animatie in beeld komen, dat bv. de hoogte 'groeit' bij verschijnen? 
- Voor de zekerheid: hij drukt de content naar beneden, dus niet er overheen?
- Bedoelen jullie met 1 voor 1 dat er maar 1 banner tegelijk kan verschijnen?

**Comment by bramhoosemans** [comment]
> * Moet deze met een animatie in beeld komen, dat bv. de hoogte 'groeit' bij verschijnen?

Het zou mooi zijn als de geanimeerd de content naar beneden drukken. Het component zelf in hoogte laten groeien lijkt me minder geslaagd (maar laat me graag overtuigen).

> * Voor de zekerheid: hij drukt de content naar beneden, dus niet er overheen?

Klopt.

> * Bedoelen jullie met 1 voor 1 dat er maar 1 banner tegelijk kan verschijnen?

Er zijn twee type banners mogelijk die niet tegelijk in beeld moeten komen. In het uitzonderlijke geval dat er in content een waarschuwing én foutmelding gedefineerd is zullen deze  één voor één moeten verschijnen. Hierbij zouden we kunnen stellen dat een foutmelding altijd als eerste wordt getoond.

**Comment by PieterVerheij** [comment]
https://www.dso-toolkit.nl/_472.banners/components/detail/banner.html
https://www.dso-toolkit.nl/_472.banners/components/detail/pagina-met-banner.html

**Comment by PieterVerheij** [comment]
Ik heb geprobeerd de banner met css geanimeerd in beeld te krijgen (door de hoogte te laten groeien), maar elke css animatie vergt grafische processor kracht en dat levert (in ieder geval op mijn pc met toch geen lullige videokaart) een schokkende animatie op.

**Comment by MichielDHVD** [comment]
Ik zet deze naar accepted (dit is dan vanuit een visueel standpunt). 

Bram en Pieter hebben al besproken dat de lnk-button niet 24px hoog is en daar is een los issue voor aangemaakt.

**Comment by gofix** [comment]
Banner en alert liggen best dicht bij elkaar, maar zijn toch ook weer best anders. In een eventueel vervolg issue willen we eens kijken hoe groot die verschillen nu echt moeten zijn. Bovendien lijkt het me raadzaam dat er een toelichtende tekst komt die aan developers en anderen duidelijk maakt wanneer je de ene danwel de andere werkvorm inzet.
