### ISSUE TITLE
Iconen set vervangen door DSO huisstijl iconen

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#480]
Bij deze de custom iconenset die de fontawesome iconen moet vervangen. 

[SVGs.zip](https://github.com/dso-toolkit/dso-toolkit/files/3939577/SVGs.zip)

Als er vragen zijn of we dingen zijn vergeten in het klaarmaken van de iconen laat het maar weten.

**Comment by Anto1nette** [comment]
Zoals afgesproken bij deze de nieuwe set in het zwart me de alerts in kleur
[SVGs zwart.zip](https://github.com/dso-toolkit/dso-toolkit/files/3939834/SVGs.zwart.zip)

**Comment by PieterVerheij** [comment]
In de huidige iconen set staan een aantal iconen die niet in de nieuwe aangeleverde set zitten:

- angle-down.svg
- angle-left.svg
- angle-right.svg
- angle-up.svg
- at.svg
- redo.svg
- wip-wip.svg

Zijn die bewust weggelaten?

**Comment by Anto1nette** [comment]
@PieterVerheij Hi Pieter, nee er zijn nog steeds een aantal in de maak. Gisteren kwam Bram erachter dat er ook nog 'rommel' in de bestanden zit, zoals kleuren die er niet in horen en ik kwam erachter dat de zwart die er nu inzit niet 100% zwart is. Ik ben nu alle iconen aan t doorlopen weer en aanpassen zodat de output in SVG klopt.

Het 'at' teken wordt naar mijn weten niet gebruikt (?) dus die heb ik wel bewust eruit gelaten

**Comment by bramhoosemans** [comment]
Voorbeeld SVG wordt aangeleverd ivm color=custom color

**Comment by Anto1nette** [comment]
[test.zip](https://github.com/dso-toolkit/dso-toolkit/files/3978012/test.zip)
@PieterVerheij hierbij alvast wat test iconen, ik zet de rest om zodra ik hoor dat deze ok zijn :)

**Comment by PieterVerheij** [comment]
@Anto1nette 
een aantal opmerkingen:

1. niet alle `path` en `rect` hebben een ` fill="currentColor"`, bv. in user-line.svg
2. de `<title>` tag kan overal weggelaten worden
3. in search.svg, undo.svg en user.svg staat nog een `style="fill: #1d1d1b"`, die moet weg
4. er komen (voor issue #457 ) ook iconen met een outline (bv het danger icoon). Die outline moet een witte fill krijgen, dus `fill="#fff"` ipv ` fill="currentColor"`

**Comment by Anto1nette** [comment]
@PieterVerheij dank je wel, ik ga ermee aan de slag :)

**Comment by Anto1nette** [comment]
Hierbij de complete set iconen, @PieterVerheij zou je voor mij de allert iconen willen controleren of ze zo goed werken of dat ze anders aangeleverd moeten worden. Ik heb alles 3x nagelopen maar er zit ongetwijfeld nog wat in... Graag hoor ik je/jullie feedback
[20200109_SVGs.zip](https://github.com/dso-toolkit/dso-toolkit/files/4039688/20200109_SVGs.zip)

**Comment by PieterVerheij** [comment]
Hi @Anto1nette,

Zie https://www.dso-toolkit.nl/_480.Iconen-vervangen/components/detail/icon.html. 
Bijna daar! 

1 opmerkingen: 
- in forbidden.svg staat de kleur met een `style=` gedefinieerd. Dat impliceert dat er nooit een kleurvariant van kan komen. Nu kan ik geen andere versie van dit icon dan een rode, dus het zal in principe wel goed zijn?

**Comment by Anto1nette** [comment]
Hoi @PieterVerheij top! Dank je wel :)
Qua kleur rood was dat volgens mij de bedoeling maar daar kan @bramhoosemans ongetwijfeld uitsluitsel over geven, Bram?

Mooi werk Pieter, dank je!

**Comment by bramhoosemans** [comment]
De forbidden.svg wordt enkel gebruikt in https://dso-toolkit.nl/9.5.0/components/detail/conclusion.html en zou in het verlengde van de status-symbolen liggen. Een vaste kleurstelling is dus geen probleem.

Ik had nog wel 2 opmerkingen:

- De iconen worden nu 40x40px weergegeven in de toolkit; graag aanpassen naar de standaard 24px weergave.
- @Anto1nette We hadden afgestemd dat alle status iconen een witte rand krijgen. Deze ontbreekt nog en status-danger-line.svg is dan overbodig.

**Comment by Anto1nette** [comment]
@bramhoosemans nee ik zou een extra set maken met een witte rand :) Maar die hebben we naar komend increment geschoven omdat deze set eerst voorrang kreeg. Maandag gaan we daar dus mee verder.

**Comment by bramhoosemans** [comment]
Prima. Dan komt dat in een volgende update :)

**Comment by PieterVerheij** [comment]
@Anto1nette 

Het blauw van het info-icoontje is anders, klopt dat?
![image](https://user-images.githubusercontent.com/25430835/72155646-d1307d80-33b3-11ea-85c2-557692b7c86a.png)

**Comment by Anto1nette** [comment]
Ja die kleur is aangepast ook :)

**Comment by PieterVerheij** [comment]
👍

**Comment by PieterVerheij** [comment]
@Anto1nette Klopt het dat `angle-down` `angle-left` `angle-right` `angle-up` en `times` een stukje kleiner zijn? https://www.dso-toolkit.nl/_480.Iconen-vervangen/components/detail/icon.html

**Comment by tfrijsewijk** [comment]
Ik heb `status-danger-line` hernoemd naar `status-danger-outline`

**Comment by tfrijsewijk** [comment]
https://dso-toolkit.nl/9.6.0/components/detail/icon.html Uitgekomen in 9.6.0!
