### ISSUE TITLE
Accordion: aria-expanded knoppen en/of links

### ISSUE THREAD

**Issue by timveld** [dso-toolkit/dso-toolkit#482]
In het accordion staat nog geen aria-expanded tag op de elementen, en dit kunnen beter knoppen dan links zijn (redenering: het is geen verwijzing naar informatie maar een functie om een deel van de pagina al dan niet te tonen) Een goed voorbeeld van een accordion op https://designsystem.digital.gov/components/accordion/

**Comment by PieterVerheij** [comment]
Dit moet dan ook gelden voor de accordion-table. Maar waar komt dan de `ID` op te staan: op de `TR`, `TD` of een `DIV` daarin?

**Comment by PieterVerheij** [comment]
@timveld In genoemd voorbeeld wordt toch juist een `button` ipv `a` gebruikt voor het in- en uitklappen? Ik zie dat daar ook `aria-controls` wordt gebruikt, maar daarvan leef ik in de veronderstelling dat dat niet zoveel doet, zie ook https://heydonworks.com/article/aria-controls-is-poop/

**Comment by tfrijsewijk** [comment]
Ik heb deze op de backlog gezet omdat het een BREAKING change betreft, ik wil hier een beter moment voor kiezen om versie 10 te releasen

**Comment by timveld** [comment]
Als donderdag besproken is mijn voorstel inderdaad knoppen te gebruiken (excuses voor de verwarring), maar het gebruik van links is niet fout. @tfrijsewijk  ik weet niet hoe lang de backlog in zo'n geval duurt maar het ontbreken van aria-expanded is wel ernstig, mtoevoegen daarvan moet dus wel prioriteit krijgen. @PieterVerheij  aria-controls lijkt mij inderdaad niet nodig, waarom ze het in het US design system doen weet ik niet maar in de praktijk doet het dus niet zo veel (behalve misschien instabiliteit veroorzaken) en in de situatie dat de uitgeklapte content direct onder de knop komt zie ik het nut er al helemaal niet van in.

**Comment by PieterVerheij** [comment]
https://www.dso-toolkit.nl/_482.Accordion--aria-expanded-en-knoppen-ipv-links/components/detail/accordion--default.html
https://www.dso-toolkit.nl/_482.Accordion--aria-expanded-en-knoppen-ipv-links/components/detail/accordion--compact.html

**Comment by gofix** [comment]
We willen deze change niet breaking laten zijn, en ook de vorm met hyperlinks ipv. buttons actief blijven ondersteunen: @PieterVerheij  past dit aan.

**Comment by timveld** [comment]
De 2 voorbeelden lijken OK maar bij het tweede voorbeeld staat nog geen expanded voorbeeld? Zal waarschijnlijk wel goed gaan

**Comment by PieterVerheij** [comment]
@timveld ik snap je opmerking niet? Het tweede voorbeeld, compact, heeft een button met aria-expanded="true"?

**Comment by PieterVerheij** [comment]
Versies met links en buttons gemaakt.

**Comment by gofix** [comment]
@timveld (en/of bv. @bramhoosemans) zou jij kunnen checken of de hier gedane changes akkoord zijn: https://dso-toolkit.nl/_482.Accordion--aria-expanded-en-knoppen-ipv-links/components/detail/accordion--default-met-links.html

NB: we hebben dus nu van:
- Default
- Compact

... ook voorbeelden opgenomen van hoe het eruit zou zien als de uitklappers met a/hrefs ipv. buttons gedaan worden:
- Default Met Links
- Compact Met Links

**Comment by bramhoosemans** [comment]
Ziet er wat mij betreft prima uit (visueel geen wijzigingen) :)

**Comment by timveld** [comment]
Lijkt goed (heb de code niet heel gedetailleerd gechecked) maar 3 puntjes: 
* Op woning(div) staat geen aria-expanded
* Waarom heten sommige iconen "gevaar", wat is het verschil met een waarschuwing? Denk dat deze omschrijving te vaag is
* Taalfout in documentatie: zinnetje "Dit zorgt het “chevron-up”-icoon. " (woordje voor ontbreekt)

**Comment by PieterVerheij** [comment]
Lijkt goed (heb de code niet heel gedetailleerd gechecked) maar 3 puntjes:

Op woning(div) staat geen aria-expanded
- Fnx, ik ga het aanpassen
Waarom heten sommige iconen "gevaar", wat is het verschil met een waarschuwing? Denk dat deze omschrijving te vaag is
- het zijn letterlijke vertalingen van 'danger' en 'warning', 2 van de 4 mogelijke statussen. Heb je een andere suggestie?
Taalfout in documentatie: zinnetje "Dit zorgt het “chevron-up”-icoon. " (woordje voor ontbreekt)
- Fnx, ik ga het aanpassen

**Comment by timveld** [comment]
Misschien "let op"? Ik weet niet precies in welke context dit icoontje gebruikt wordt dus vind het moeilijk met een goede suggestie te komen, maar "gevaar" klinkt wel heel alarmerend. Eventueel een zaak voor de implementator om de juiste formulering te kiezen.

**Comment by PieterVerheij** [comment]
@bramhoosemans @MichielDHVD Hebben jullie een suggestie?

**Comment by bramhoosemans** [comment]
De error status heeft in Bootstrap de class 'danger'. Geen idee waarom, maar je kunt er in het Nederlands het beste naar verwijzen met 'fout'.

- Danger (=Error): Fout
- Warning: Waarschuwing
- Info: Informatie
- Success: Succes

**Comment by PieterVerheij** [comment]
Ok, aangepast!
