### ISSUE TITLE
Verbetering tabel documentatie

### ISSUE THREAD

**Issue by DHvD-Michael** [dso-toolkit/dso-toolkit#483]
Bij de inventarisatie naar beheerpatronen is het gebruik van tabellen binnen DSO verder verkend.
 
Op basis van de uitkomsten van UX break-out sessie op 12-11-2019 wordt de tabel documentatie uitgebreid in de toolkit.

**Comment by DHvD-Michael** [comment]
Toegevoegde documentatie is hier te zien:
https://www.dso-toolkit.nl/_483-Verbetering-tabel-documentatie/docs/tables.html

**Comment by DHvD-Michael** [comment]
Ik ga dit issue ook even nalopen op basis van feedback op: 
https://github.com/dso-toolkit/dso-toolkit/pull/487

**Comment by gofix** [comment]
Zoals vanmorgen besproken op de conference call: als niemand meer iets op of aan te merken heeft op dit stuk documentatie, is het klaar.
