### ISSUE TITLE
Voorbeeld van skelet beheerscherm toevoegen met gebruik definition list en tabel

### ISSUE THREAD

**Issue by DHvD-Michael** [dso-toolkit/dso-toolkit#484]
Bij de inventarisatie van beheerpatronen worden als resultaat o.a. voorbeelden van "skelet beheerschermen" opgeleverd. 

In de afgelopen periode is ingezoomd op het gebruik van definition lists en tabellen. Hiervoor wordt een of meerdere voorbeelden als "skelet beheerscherm" toegevoegd aan DSO-toolkit.

**Comment by DHvD-Michael** [comment]
Voorbeeld is hier te zien:
https://dso-toolkit.nl/_484-Voorbeeld-van-skelet-beheerscherm-toevoegen-met-gebruik-definition-list-en-tabel/components/detail/beheer-basis.html

**Comment by tfrijsewijk** [comment]
Merged into master, testable op dso-toolkit.nl/master

**Comment by tfrijsewijk** [comment]
Opgeleverd in 9.7.0: https://dso-toolkit.nl/master/components/detail/beheer-basis.html
