### ISSUE TITLE
Verbetering definition list documentatie

### ISSUE THREAD

**Issue by DHvD-Michael** [dso-toolkit/dso-toolkit#485]
Bij de inventarisatie naar beheerpatronen is het gebruik van tabellen binnen DSO verder verkend.

Op basis van de uitkomsten van UX break-out sessie op 12-11-2019 wordt de definition list documentatie uitgebreid in de toolkit.

**Comment by MichielDHVD** [comment]
Ik sluit dit issue. In release 15.0.0 is er een definition list documentatie pagina toegevoegd. Die bevat de meest recente informatie omtrent Definition list gebruik vanuit UX en dit issue gaat precies daarover.
