### ISSUE TITLE
Ontwerp Inloggen en Machtiging discussie

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#489]
Vanwege nieuwe functionaliteit krijgen de inlogpagina's een herontwerp. Deze is gebaseerd op het inlog systeem van de belasting dienst(besproken met belastingdienst).

In een branchrelease is een prototype gemaakt

https://dso-toolkit.nl/_489-Machtigen-Inloggen-Herontwerp/components/detail/machtigen.html

De hoofdvragen over deze ontwerpen zijn: 

- Is dit de juiste implementatie van de toolkit @tfrijsewijk 
- Zou dit een patroon moeten zijn voor toevoeging aan toolkit of zijn er onderdelen. 
- Zijn de pagina's digitoegankelijk @timveld 

Er is custom css toegepast plus er zijn onderdelen die nog niet goed werken. 

-  De highlightbox heeft custom margins 
- De uitlijning van de lnk-buttons in de highlight box kan niet verticaal gecentreerd worden
- Ook werken de pagina's nog niet goed op mobiel ivm het niet kunnen wrappen van buttons. Moeten buttons kunnen wrappen anders moeten we miss max lengths gaan voorschrijven. 

Visuele opmerkingen: 
Als het laatste tablad op een tabblad actief is zie je nog een klein haakje aan de achterkan. Hier zou je eigenlijk een strakke lijn willen. Zoals bij de voorkant als het eerste tabblad actief is. 
Visited states op tabbladen. Is dit wenselijk?

**Comment by timveld** [comment]
Ik denk dat het zo wel goed is, enige waar ik over twijfel is of inloggen voor mezelf / inloggen voor een ander aria tabs moeten worden (maar ik zou dat zelf in dit geval niet doen, nodeloos ingewikkeld)
Enige wat je in ieder geval moet aanpassen: 
* spelling DigiD in alt tag en op knop
* Plaatje met alt tag "afbeelding Europese vlag" dat afbeelding ervoor is niet nodig.

**Comment by tfrijsewijk** [comment]
@MichielDHVD Wil je opgenomen hebben in de toolkit of is dit enkel een markup demo?

**Comment by MichielDHVD** [comment]
Dit is een pure markup demo om feedback en suggesties over te verzamelen. 

Er staat namelijk ook custom css in waar mijn vraag is hoe gaan we hier mee om (kan niet altijd vermeden worden denk ik)

**Comment by tfrijsewijk** [comment]
Custom CSS in de toolkit bestaat niet: De toolkit schrijft voor, alle CSS die in de toolkit staat mag gebruikt worden.

Ik vermoed echter dat jij op de inline style attributen doelt. Dit is geen optie.

Dus dit hoef je niet gemerged te hebben? Ik ben nu met een review bezig maar dan stop ik daar mee

**Comment by MichielDHVD** [comment]
Dit hoeft inderdaad niet gemerged te worden. Dit issue was puur advies vraag om digitoegankelijkheid en toolkit implementatie.

**Comment by tfrijsewijk** [comment]
OK, je hebt wel een PR geopend: vandaar de verwarring aan mijn kant. Het PR kan gesloten worden? Ga je wat met de review doen of kan ik dit helemaal van mijn radar halen?

Overigens, als het niets bijdraagt aan de toolkit is een milestone en `status` label ook niet zo interessant. Eens?

**Comment by MichielDHVD** [comment]
Je hebt een pr nodig voor een branch release toch? Anders kon ik Tim er niet naar laten kijken. 

Neemt niet weg dat dit ontwerp doorgevoerd gaat worden alleen kijken wat er voor nodig is om dit in de toolkit te realiseren .

Dus je review heeft zeker geholpen en ga ik de aanpassingen zeker doorvoeren. Maar de belangrijkste vragen voor mij waren dit. 

1. Digitoegankelijkheid voor Tim 
2. Moet een component zoals dit worden verwerkt in de toolkit? 

Milestone weet ik niet zeker? Ben bang dat deze anders rond blijft drijven.

**Comment by tfrijsewijk** [comment]
Voor een branch release hoeft de branch alleen met een `#` te beginnen. We bespreken dit issue donderdag wel verder

**Comment by MichielDHVD** [comment]
Dit issue wordt gesloten. Er komen nog hervormingen en mogelijk zal er dan een herontwerp met toolkit plaatsvinden

**Comment by gofix** [comment]
(branch is inmiddels ook verwijderd)
