### ISSUE TITLE
Standaard Tabel Responsive maken

### ISSUE THREAD

**Issue by DjangoBlok** [dso-toolkit/dso-toolkit#491]
Responsive functionaliteit is voor de tabel is nog niet verwerkt in de toolkit. 

Besloten is op Donderdag 16 juli het als volgt aan te pakken: 

Er zijn twee werken vormen 

1. De tabel is gekoppeld aan de breedte van het scherm. 
Hierbij wordt de bootstrap wijze gebruikt waar een wrapper met table-responsive om een tabel wordt geplaatst. Zodat op kleinere beeldschermen de tabel horizontaal kan scrollen. 

Verder wordt er ook een boodschap op het scherm geplaatst wanneer het scrollen mogelijk is. Zoals te zien is op: 
https://www.zorgwijzer.nl/zorgverzekering-2021/heb-ik-het-coronavirus-gehad
<img width="309" alt="Screen Shot 2020-07-16 at 11 47 19" src="https://user-images.githubusercontent.com/36912722/87656805-3ea1da00-c75a-11ea-9c89-8ba502d61589.png">

2. Tabel breedte is gekoppeld aan de bovenliggende container
Hiervoor moet een oplossing komen wanneer de tabel breedte de container breedte overschrijdt dat dan de tabel horizontaal gaat scrollen. 

Deze opties maakt de toolkit beschikbaar voor het responsive maken van de tabellen. Het is aan de implementator/ontwerpen om de keuze van deze opties goed toe te passen. Daarom moet er documentatie geschreven worden waar de gewenste toepassing van de 2 opties wordt uitgelegd (Seperaat issue)

**Comment by PieterVerheij** [comment]
Kan dit verder uitgewerkt worden?

**Comment by PieterVerheij** [comment]
Paar opmerkingen:

> Voorstel is om regels bij elkaar te houden en te collapsen als een tabel in de breedte niet past.
Dit gaat moeilijk werken wanneer er cellen met een rowspan zijn.

Bootstrap kent een ander (scrollend) responsive gedrag: https://getbootstrap.com/docs/4.0/content/tables/#responsive-tables

**Comment by DjangoBlok** [comment]
Het lijkt erop dat daar een compleet andere HTML markup voor nodig is. 
Ik kwam eerder op deze post uit met voorbeelden om het in de CSS op te lossen:
https://css-tricks.com/responsive-data-tables/

**Comment by PieterVerheij** [comment]
Ik denk dat je niet aan een aanpassing van de HTML ontkomt. Die css oplossingen zijn vrij specifiek (label in een ::before e.d.)

Loop net tegen deze aan: https://nl-design-system.gitlab.io/nl-design-system/componenten/table/index.html#complexe-tabel

**Comment by bramhoosemans** [comment]
@DjangoBlok Voorbeeld opzoeken van grote tabel weergave in de Viewer.

**Comment by MichielDHVD** [comment]
PR02 heeft ook wat issues met responsive gedrag van tabellen namelijk

Namelijk dat tabellen niet horizontaal te scrollen zijn. De WCAG maakt hier expliciet een uitzondering voor.

Dit valt op dit moment nog niet te testen in de toolkit omdat in de toolkit nog geen meta tag met viewport heeft. Waardoor de tabel altijd in zijn geheel getoond wordt en niet verkleind. Waardoor in de toolkit het scrollen van tabellen overbodig is.

Pr02 probeert dit nu wel toegankelijk te maken, maar lopen tegen wat issues aan. Namelijk zodra de tabellen horizontaal scrollbaar worden gemaakt op kleinere viewports dan is dit het resultaat op grotere viewports.

![image](https://user-images.githubusercontent.com/36912722/87306824-e3cd7000-c518-11ea-9899-5457605ed0f4.png)

**Comment by MichielDHVD** [comment]
Issue is herschreven om intentie issue duidelijk te maken.

**Comment by PieterVerheij** [comment]
Twee varianten toegevoegd aan de table-pagina:
https://www.dso-toolkit.nl/_491.Standaard-Tabel-Responsive-maken/components/detail/table.html

**Comment by gofix** [comment]
Als ik de betreffende toolkit pagina bekijk op ca. 800px, zie ik ineens wel heel veel scrollbalken:
![image](https://user-images.githubusercontent.com/2689559/89006401-fad8d400-d306-11ea-956a-89ffda556f44.png)
... maar ik denk niet dat dit per se met dit issue te maken heeft, maakt het alleen wel lastig om nu goed te bestuderen hoe het zit met die tabellen en hun gedrag als de viewport kleiner wordt.

**Comment by gofix** [comment]
Als ik alleen de tabellen-pagina zelf bekijk gaat het een stuk beter (dus: zonder toolkit header en menu eromheen) : https://www.dso-toolkit.nl/_491.Standaard-Tabel-Responsive-maken/components/preview/table.html

**Comment by gofix** [comment]
@PieterVerheij wat is nu het wezenlijke verschil tussen de voorbeelden VIEWPORT RESPONSIVE en TABEL BREDER DAN ZIJN CONTAINER ?

**Comment by PieterVerheij** [comment]
VIEWPORT RESPONSIVE: In de smalle viewport wordt de tabel responsive. De logica van `.dso-table-responsive` is identiek aan de bootstrap class `.table-responsive` die in de toolit niet voorradig is.

TABEL BREDER DAN ZIJN CONTAINER: scriptend moet de class `.viewport-out-of-bounds` op de omliggende container gezet worden als de tabel breder is dan zijn container.
