### ISSUE TITLE
Toegankelijke structuur voor juridische documenten 

### ISSUE THREAD

**Issue by DjangoBlok** [dso-toolkit/dso-toolkit#492]
De structuur van juridische plannen kan erg gelaagd zijn. 
In potentie bevat een plan meer dan de 6 kopniveaus die in HTML worden onderscheiden.

Er moet een oplossing komen om die juridische structuur te vertalen naar toegankelijke HTML markup.
Het voorstel is om <article> en <section> te gebruiken. Dit zijn elementen met een semantische meerwaarde. Daarbinnen mag weer opnieuw begonnen worden met de headingniveaus.

Op basis van dit principe heb ik een voorstel uitgewerkt. (zie attachment)
[Tekststructuur v0.98.1.xlsx](https://github.com/dso-toolkit/dso-toolkit/files/4046161/Tekststructuur.v0.98.1.xlsx)

Nu blijkt echter dat dit toch niet helemaal toegankelijk is voor screenreaders:
https://www.w3.org/WAI/GL/wiki/Using_HTML5_section_element

Goed om hier ene voorbeeld pagina van te maken en te kijken welke bevindingen we (@timveld ) hiermee hebben.

**Comment by timveld** [comment]
Heeft iemand voorbeelden van teksten waarbij dit probleem speelt? Een voorbeeldpagina is ook goed maar ik vraag me wel af of dit probleem algemeen genoeg is voor de toolkit. 

Een tekst met subsubsubsubsectie 1.2.3.4.5 lijkt me vrij uitzonderlijk en als dieper genest moet worden dan heading level 6 is een heading-loze oplossing voor niveau 7 en verder misschien beter. Je kunt altijd nog een lijst maken. Vanaf een bepaald punt neemt het praktisch nut van headings waarschijnlijk sterk af. 

Als ik het goed begrijp wordt een oplossing gezocht om meerdere heading level 1 op een pagina te gebruiken. WCAG staat dit op niveau AA in principe toe; headings zijn in bepaalde gevallen feitelijk wel noodzakelijk maar een correcte structuur is geen eis. 

Theoretisch voorbeeld: Op een pagina met subsubsecties verwacht ik op niveau 1 de paginatitel, niveau 2 hoofdstukken, niveau 3 subsecties, niveau 4 subsubsecties. Als je alle headings op niveau 1 zet ga ik zeker steigeren maar in de zin van WCAG is dit formeel geen afwijking, aangenomen dat je alle headings hetzelfde uiterlijk geeft (als je headings een class zou gaan geven om het font te verkleinen behaal je succescriterium 1.3.1 "info en relaties" niet omdat je de structuur alleen visueel presenteert). 

Maar in bijzondere gevallen kan een structuur met meerdere headings op niveau 1 - al dan niet met sections - waarschijnlijk wel goedgekeurd worden. 
 
Volgens mij is het artikel "using html5 section element" gedateerd, ik lees het jaartal 2012; inmiddels ondersteunen screen readers dit wel

**Comment by DjangoBlok** [comment]
Dank voor je reactie Tim.
Goed dat screen readers de section inmiddels ondersteunen. 

Wat mij betreft prima als het niet algemeen genoeg is om in de toolkit op te nemen hoor. 
Blijf ik voor de viewer nog wel op zoek naar een oplossing doe toegankelijk is.

Hier een voorbeeld van een regeling gepubliceerd bij Koop. (Daar zitten overigens niet alle mogelijke niveaus in)
Koop heeft een soort flexibele manier van structuur toepassen:

> We gebruiken <h1> t/m <h6> en gaan daarna over op <p>. Welk element een hoofdstuk, artikel, etc krijgt toebedeeld, is afhankelijk van het niveau waarop het zich bevindt. Stel een hoofdstuk is een <h2>, dan is een artikel een <h3> als het er rechtstreeks onder valt, maar een <h4> als er nog een optioneel niveau tussen zit. Al deze elementen geven we een class mee die aangeeft of het een hoofdstuk, artikel, etc is. Deze class zorgt voor de opmaak in de HTML, zodat een artikelkop er altijd hetzelfde uitziet, ongeacht het niveau waarop deze zich bevindt. 

https://zoek.officielebekendmakingen.nl/stcrt-2019-56288.html

Ik had een excel gemaakt met een voorstel, maar weet niet of je die goed kan lezen. Ik zal proberen hem plat hieronder weer te geven:
- H1 Pagina titel: Geselecteerde regels
- Section: per document 
- Header: bevat de naam van het document maar ook enkele metadata
- H1 Naam van het document
- H2 Hoofdstuk
- H3 Titel (optioneel structuurelement)
- H4 Afdeling (optioneel structuurelement)
- Article
- H1 Paragraaf (optioneel structuurelement)
- H2 Subparagraaf (optioneel structuurelement)
- H3 Subsubparagraaf (optioneel structuurelement)
- H4 Artikel 
- p lid
- p alinea

**Comment by bramhoosemans** [comment]
@DjangoBlok @timveld https://dso-toolkit.nl/master/components/detail/legal-document--complete.html

**Comment by gofix** [comment]
Zoals vanmorgen besproken tijdens de conference call: het lijkt inderdaad dat hiermee een nuttige voorziening in het leven is geroepen (namelijk, dat met classes een andere visuele headinggrootte kan worden geprogrammeerd dan de heading in werkelijkheid is). Maar... @bramhoosemans  vraagt zich af of dit wel een realistische oplossing biedt: het vereist namelijk dat de headings met voorbedachten rade van classes worden voorzien, en juist voor dit soort juridische inhoud geldt dat deze soms van externe bronnen afkomstig zal zijn, waardoor die classes er niet zonder meer zullen komen.

De vraag is even of wellicht ook een voorbeeld in de toolkit moet worden opgenomen dat duidelijk maakt hoe een en ander eruit ziet als die nieuwe classes NIET worden toegepast. En, of @DjangoBlok ueberhaupt iets heeft aan de nu gerealiseerde change.

**Comment by timveld** [comment]
Ik heb het voorbeeld in de toolkit gechecked en dat lijkt me een goede opzet. 2 koppen op niveau 1 is niet heel mooi maar lijkt me in dit geval de meest logische oplossing inderdaad, in ieder geval is dit binnen WCAG mogelijk

**Comment by gofix** [comment]
@DjangoBlok heb jij hier toevallig al naar kunnen kijken?

**Comment by gofix** [comment]
Na intern overleg: we denken dat de huidige voorziening iig geen kwaad kan, dus we gaan dit afronden.

**Comment by DjangoBlok** [comment]
Kan er zoals aangegeven nog een H1 boven de section komen?
Verder klopt de HTML structuur, maar op de voorbeeldpagina ziet het er nog niet uit zoals ik had beschreven. 
@gofix @tfrijsewijk Hoe gaan we hiermee om? Ik zie dat de issue al is gesloten.

**Comment by tfrijsewijk** [comment]
We maken een nieuwe issue, een GitHub issue kan maar aan 1 milestone hangen. In dat issue geven we aan wat er anders moet en kan het in een volgende release mee.

Als je er om staat te springen kunnen we dit wel tussendoor oppakken, maar eigenlijk zijn we nu met een toolkit sprint bezig en is het wel heel moeilijk om wat tussendoor te doen. Is de nood hoog of kan het wachten tot na de toolkit sprint in een patch release?
