### ISSUE TITLE
Waarschuwing (icoon) wordt niet voorgelezen in de shopping cart

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#493]
Het waarschuwing icoon voor de regel, en onder de winkelwagen, is niet zichtbaar voor een screenreader. Deze iconen (indicatoren) zijn niet alleen decoratief en zullen een tekst alternatief moeten bieden, bijvoorbeeld met sr-only?

**Comment by timveld** [comment]
Inderdaad met sr-only, hebben we bij andere iconen ook gedaan en deze situatie is vergelijkbaar.

**Comment by PieterVerheij** [comment]
Wat zou een goede inhoud van de `span.sr-only' zijn in dit geval? Gewoon 'waarschuwing'?

**Comment by bramhoosemans** [comment]
> Gewoon 'waarschuwing'?

Ja, ik denk van wel. @timveld heb jij een ander idee?

**Comment by tfrijsewijk** [comment]
Merged #507 into master

**Comment by tfrijsewijk** [comment]
Opgeleverd in 9.7.0: https://dso-toolkit.nl/9.7.0/components/detail/shopping-cart--no-toggle.html

**Comment by timveld** [comment]
Op de onderste regel ("let op: ..." wordt het waarschuwings icoontje nog steeds niet gelezen
