### ISSUE TITLE
2FA verplicht stellen

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#494]
In #375 hebben wij branch deployments. Bij de volgende voorwaarden wordt er automatisch een uitrol gedaan naar dso-toolkit.nl:
* Een branch deployment waar de branch begint met een `#` OF een merge naar `master` OF een nieuwe tag;
* Binnen de `dso-toolkit/dso-toolkit` repository;

Concreet;
* Alleen maintainers (@tfrijsewijk en @gofix) mogen mergen naar `master` of een tag aanmaken;
* Leden `dso-toolkit/dso-toolkit` met push rechten (Zie de [People](https://github.com/dso-toolkit/dso-toolkit/people) pagina) kunnen branch deployments maken;
* Bij een fork wordt er GEEN build gedraaid en zal er GEEN deployment zijn;

Als een user met deploy rechten compromised is, kan deze persoon malicious code deployen naar dso-toolkit.nl of zelfs naar NPM. Dit is zeer ongewenst.

Ik stel daarom voor dat wij 2FA gaan forceren. GitHub implementeert het nogal geforceerd: Iedereen die _geen_ 2FA heeft, wordt uit de organisatie gezet. Ik wil daarom een grace period instellen.

2FA status:
- [x] @bramhoosemans
- [x] @gofix
- [x] @DHvD-Michael
- [x] @sanderhaa
- [x] @daverhelst
- [x] @tfrijsewijk
- [x] @PieterVerheij
- [x] @MichielDHVD
- [x] @timveld 

Ik ga vrijdag 17 januari 2020 2FA forceren. Iedereen die dan geen 2FA heeft ingesteld raken hun rechten tot de `dso-toolkit/dso-toolkit` repository kwijt.

2FA stel je bij jouw "Settings" -> "Security" in: https://github.com/settings/security

**Comment by tfrijsewijk** [comment]
Iedereen heeft 2FA aangezet en zojuist heb ik (een dag eerder) de 2FA aangezet voor de `dso-toolkit` organisatie.

@Anto1nette en @DjangoBlok hebben nog een uitnodiging open staan om lid te worden. Willen jullie hier op acteren?

**Comment by DjangoBlok** [comment]
@tfrijsewijk Op welke manier kan ik die uitnodiging zien en erop acteren?
Ik heb hem niet voorbij zien komen.

**Comment by tfrijsewijk** [comment]
GitHub beweert een e-mail te hebben verstuurd, maar ik zie dat er ook een deelbare link bestaat: https://github.com/dso-toolkit/dso-toolkit/invitations

Deze zou ook voor @Anto1nette moeten werken

**Comment by DjangoBlok** [comment]
ok, was niet heel toegankelijk, maar volgens mij is het gelukt.

**Comment by Anto1nette** [comment]
Vorige week gedaan, deed t gewoon  goed hoor :)
