### ISSUE TITLE
Rendering iconen niet overal 24x24

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#497]
Iconen worden veel te klein weergegeven in de componenten (niet 24x24):

- https://dso-toolkit.nl/9.6.0/components/detail/accordion.html
- https://dso-toolkit.nl/9.6.0/components/detail/modal--modal.html
- https://dso-toolkit.nl/9.6.0/components/detail/info.html
- https://dso-toolkit.nl/9.6.0/components/detail/info-button.html
- https://dso-toolkit.nl/9.6.0/components/detail/pagination.html
- https://dso-toolkit.nl/9.6.0/components/detail/search-bar.html
- https://dso-toolkit.nl/9.6.0/docs/buttons.html

**Comment by PieterVerheij** [comment]
@bramhoosemans 
Ik had in het #480 issue al vraag gesteld over de sizing van de arrow en times iconen: die vullen niet uit in hun viewbox. 
Bij de info-button valt op dat de knop 16px groot is, die zal dan 24px moeten worden?

**Comment by bramhoosemans** [comment]
Het klopt dat sommige iconen kleiner zijn dan de viewbox van 24px. Op deze manier zouden wij (designers) controle hebben over de optische uitlijning/formaat.

Op dit moment wordt in de componenten soms "hard" 16px toegepast voor de icoon weergave. De bedoeling is dat dit overal 24px gaat worden.

**Comment by PieterVerheij** [comment]
Hi @bramhoosemans, aanpassingen in https://www.dso-toolkit.nl/_497.Rendering-iconen-te-klein/

**Comment by PieterVerheij** [comment]
De sizing is aangepast. Aandachtspunten:

- de paperclip in de accordion-table is nu ook 24px. Moet die kleiner?
- de inline iconen lijken te groot?
- de iconen in form elementen (bv. triangle bij een select, kalender icon in datumveld) zijn nu ook 24px, moeten die kleiner?
- De info-button is nu ook 24px, moet die kleiner?

**Comment by bramhoosemans** [comment]
> De sizing is aangepast. Aandachtspunten:
> 
> * de paperclip in de accordion-table is nu ook 24px. Moet die kleiner?
> * de inline iconen lijken te groot?
> * de iconen in form elementen (bv. triangle bij een select, kalender icon in datumveld) zijn nu ook 24px, moeten die kleiner?
> * De info-button is nu ook 24px, moet die kleiner?

Iconen moeten overal als 24px worden weergegeven. Als we ze optisch kleiner willen maken, ten opzichte van andere iconen, is dat iets wat we binnen de SVG oppakken.

Wat me nog wel opvalt is dat de uitlijning nu niet overal goed gaat. Zo staan de iconen in form elementen niet in het midden en wordt de paperclip op een volgende regel getoond in de accordion-table.

> * Het @-icon zit niet meer in de icon-set, die mist nu in het emailadres-veld.

Zover ik weet wordt deze niet buiten het toolkit voorbeeld gebruikt. Vandaar dat hij ook niet meer in de iconen set was opgenomen.

**Comment by PieterVerheij** [comment]
> Wat me nog wel opvalt is dat de uitlijning nu niet overal goed gaat. Zo staan de iconen in form elementen niet in het midden en wordt de paperclip op een volgende regel getoond in de accordion-table.

De foute uitlijning van iconen in de form-elementen is gelieerd aan de grootte van het icoon. Maar omdat het icon sowieso al vrij groot (lees hoog) is in verhouding tot de hoogte van het invoerveld, leek mij dat deze misschien niet 24px moet worden. Dat geldt wat mij betreft voor het calender-icoontje en de triangle-down.

Omdat de paperclip groter is geworden, floept hij nu naar de volgende regel. Dat is eigenlijk een issue van de omliggende tabelcel. Sowieso zal dit een markup change gaan betekenen (extra class, non-breaking space oid).

**Comment by bramhoosemans** [comment]
- In het ontwerp heeft een inputfield/dropdown een hoogte van 40px; het icoon staat daarmee 8px van de randen (rekening houdend met 1px border = 7px).
<img width="381" alt="Schermafbeelding 2020-01-23 om 09 50 28" src="https://user-images.githubusercontent.com/598735/72969467-cddebe00-3dc5-11ea-8993-8581a2564cbe.png">

- We moeten inderdaad nog naar de tabellen kijken. In het ontwerp zijn de rijen 48px hoog... maar goed, dat komt later nog wel.
<img width="943" alt="Schermafbeelding 2020-01-23 om 10 05 35" src="https://user-images.githubusercontent.com/598735/72970460-02537980-3dc8-11ea-9988-c642ff19ba70.png">

**Comment by PieterVerheij** [comment]
Ik heb de margin van de iconen in inputs aangepast. Wat mij opviel, is dat de hoogte 38px ipx 40px is, daar zal ik een los issue voor aanmaken.

**Comment by tfrijsewijk** [comment]
Merged #504 into master

**Comment by tfrijsewijk** [comment]
Opgeleverd in 9.7.0
