### ISSUE TITLE
Toolkit layout verbeteren

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#499]
Naast de structuur hebben we ook een concept gemaakt voor enkele wijzigingen in de DSO Toolkit layout. Graag afstemmen wat mogelijk is en eventueel opdelen in verschillende issues.

**Schermontwerpen:**
- [DSO toolkit layout 1440.pdf](https://github.com/dso-toolkit/dso-toolkit/files/4091532/DSO.toolkit.layout.1440.pdf) - met notities!
- [DSO toolkit layout 1024.pdf](https://github.com/dso-toolkit/dso-toolkit/files/4091539/DSO.toolkit.layout.1024.pdf)
- [DSO toolkit layout 768.pdf](https://github.com/dso-toolkit/dso-toolkit/files/4091540/DSO.toolkit.layout.768.pdf)
- [DSO toolkit layout 667.pdf](https://github.com/dso-toolkit/dso-toolkit/files/4091541/DSO.toolkit.layout.667.pdf)
- [DSO toolkit layout 375.pdf](https://github.com/dso-toolkit/dso-toolkit/files/4091542/DSO.toolkit.layout.375.pdf)

**Bronbestand:**
- [2020-01-10 DSO Toolkit layout.sketch.zip](https://github.com/dso-toolkit/dso-toolkit/files/4091543/2020-01-10.DSO.Toolkit.layout.sketch.zip)

**Overzicht wijzigingen:**
- Aangepaste header met nieuw logo
- Laatste versie label
- Context/dropdown menu in header (versie en branche releases)
- Filteren in alle pagina's
- Vaste sidebar
- Subnav/tab bar bovenin bij componenten
- Branche release toont enkel gewijzigde pagina (en alle voorbeelden)
- Versie documentatie pagina
- Versie overzicht pagina met alle versies

**Comment by bramhoosemans** [comment]
@PieterVerheij Hierbij een export van het Sketch bestand: 
[2020-01-10 DSO Toolkit layout.zip](https://github.com/dso-toolkit/dso-toolkit/files/4343226/2020-01-10.DSO.Toolkit.layout.zip)

**Comment by tfrijsewijk** [comment]
Uit deze change zijn de volgende issues ontstaan:
* #591 
* #592 
* #593
