### ISSUE TITLE
Onderzoek en Analyse Marges in de toolkit

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#500]
In de huidige constructie van de toolkit is de ruimte tussen de componenten nog niet optimaal afgestemd. 

Om ervoor te zorgen dat de componenten beter met elkaar gaan samenwerken voor een strakker en meer rustig geheel worden bestaande pagina's nagebouwd. 

Zodat vervolgens bekeken kan worden waar een betere afstemming nodig is qua marges in de toolkit. Dit kan op component, patroon en pagina niveau. 

Dit issue is een doorlopend issue dit gehele kwartaal waar constant updates worden geplaatst over nieuwe bevindingen.

**Comment by MichielDHVD** [comment]
Eerste opmerking zijn de componenten die marges hebben die niet in het 8px grid vallen. 

Een flink aantal componenten bevat margins die niet in het 8px valleen wanneer ze niet in de "juiste" context gebruikt worden. 

Deze context is het component dso-rich-content(DRC). De volgende onderdelen hebben binnen DRC  8px marges of een veelvoud daarvan en daarbuiten niet. 
Verschil is in alle gevallen dat margin-bottom buiten DRC 12px is en binnen DRC 16px/ 

Dit geldt voor de volgende onderdelen:

-  Headings -> Hier valt ook het steps component onder

-

**Comment by MichielDHVD** [comment]
Verander voorstellen: 

row: padding-top: 48px, padding-bottom: 48px; -> padding-top: 8px, padding-bottom: 8px;

**Nieuwe specificatie** : row + dso-featured: margin-bottom 48px; 

Highlight box: margin-top: 48px -> margin-top: 16px; 
**Nieuwe specificatie**: Highlight box + Stappenteller: margin-top: 48px; (De highlightbox+stappenteller heeft de 48px nodig anders overlapt het met andere content) 

Last child in dso-richt-content: margin-top: 0 -> margin-top: 8px
First child in dso-rich-content margin-bottom: 0 -> margin-bottom: 8px

Pagina's waar dit effect duidelijk is te zien. Stappenteller pagina en landingspagina.

**Comment by PieterVerheij** [comment]
Hi @MichielDHVD , 

Is die kleine margin op de stappenteller pagina echt de bedoeling?
![image](https://user-images.githubusercontent.com/25430835/78799431-685c9f80-79ba-11ea-97dd-f8356c23be64.png)

**Comment by MichielDHVD** [comment]
Nope. 

Daarom morgen even bespreken. Hoe wat verder, ik loop. namelijk een beetje vast.

**Comment by MichielDHVD** [comment]
Ik heb ook een tweede branch aangemaakt deze volgt het principe van alle margins op de bottom van componenten. 

Onderwerpen die ik wil bespreken zijn: 
Invloed angular op markup en consequent margins
Centrale principe margins en paddings.

**Comment by MichielDHVD** [comment]
Losse sessie organiseren voor het bespreken van de verscheidene issues. 

Belangrijk dat Infoprojects toegang krijgt tot code van developers zodat ze kunnen zien hoe de toolkit gebruikt wordt.

**Comment by gofix** [comment]
Inmiddels hebben wij toegang (jay!), dus wellicht kunnen we hier nu verder mee. @MichielDHVD wil je de 2 openstaande branches in de repo nog wel behouden?

**Comment by MichielDHVD** [comment]
Dumpen en met een schone lei beginnen zou ik zeggen.

**Comment by gofix** [comment]
Bij deze dan:

- #500-Margins-test-2 Deleted just now by gofix
- #500-Margins-Testbuilds Deleted just now by gofix

**Comment by MichielDHVD** [comment]
Huidige problemen met de Margins:

1. Veruit het grootste probleem is de top en bottom margin op een row voor gigantisch veel tussen ruimte zorgt. Zie bijv. 
https://dso-toolkit.nl/10.8.0/components/detail/beheer-basis.html

Oorspronkelijke reden voor aanpassing:
Landingspagina, https://dso-toolkit.nl/10.8.0/components/detail/landingspagina.html Hier is het gebruikt van de margins visueel nog te pruimen. Maar voor andere voorbeeld pagina's valt het uit elkaar

Hier heb ik al zelf een keer naar gekeken. En kwam toen met de volgende suggestie:

> Verander voorstellen:
> 
> row: padding-top: 48px, padding-bottom: 48px; -> padding-top: 8px, padding-bottom: 8px;
> 
> **Nieuwe specificatie** : row + dso-featured: margin-bottom 48px;
> 
> Highlight box: margin-top: 48px -> margin-top: 16px;
> **Nieuwe specificatie**: Highlight box + Stappenteller: margin-top: 48px; (De highlightbox+stappenteller heeft de 48px nodig anders overlapt het met andere content)
> 
> Last child in dso-richt-content: margin-top: 0 -> margin-top: 8px
> First child in dso-rich-content margin-bottom: 0 -> margin-bottom: 8px
> 
> Pagina's waar dit effect duidelijk is te zien. Stappenteller pagina en landingspagina.



2.  Componenten buiten dso-rich-content vallen niet binnen 8px grid.  Dit geld voor de volgende componenten.
 
> * Headings -> Hier valt ook het steps component onder
> * Paragraaf
> * Lists (**Belangrijk** gevolg is dat alle sub-componenten die uit een list op zijn gebouwd deze margin-bottom ook overnemen. Tenzij anders gespecificeerd)  -> Cards, Footnotes, Pagination
> * Blockquote
> * Highlightbox
> 
> Het is prima om verschillende marges binnen DRC te hanteren maar buiten DRC moeten marges nog steeds voldoen aan het 8px grid
> 
> **Voorstel:** Margin-bottom: 12px -> Margin-bottom -> 16px

3. Header bottom heeft 8px margin. 
Dit zorgt voor een conflict met de image die eronder ligt. Er komt een lelijke witte rand onder de header
<img width="1261" alt="Screen Shot 2020-07-17 at 08 55 31" src="https://user-images.githubusercontent.com/36912722/87757668-51281c00-c80b-11ea-885c-5a8eb3cf4e8a.png">
<img width="1166" alt="Screen Shot 2020-07-17 at 08 55 35" src="https://user-images.githubusercontent.com/36912722/87757685-55543980-c80b-11ea-8192-fa72b4afce40.png">

Dit zijn de eerste punten die opgelost moeten worden. Omdat de fijnere details van de marges en paddings te kunnen zien is het denk ik belangrijk om eerst de 48px op te lossen.

**Comment by PieterVerheij** [comment]
@MichielDHVD Bedoel je met **nieuwe specificatie** en en ?

Dus in onderstaande specs

> row: padding-top: 48px, padding-bottom: 48px; -> padding-top: 8px, padding-bottom: 8px;
> 
> Nieuwe specificatie : row + dso-featured: margin-bottom 48px;
> 
> Highlight box: margin-top: 48px -> margin-top: 16px;
> Nieuwe specificatie: Highlight box + Stappenteller: margin-top: 48px; (De highlightbox+stappenteller heeft de 48px nodig anders overlapt het met andere content)

heeft een row standaard `padding-top: 8px, padding-bottom: 8px;`, maar een row.dso-featured een `margin-bottom: 48px`? Ik zou dan eerder zeggen dat hij een `margin-top 48px;` moet hebben?

**Comment by MichielDHVD** [comment]
Ik denk dat het experimenteren is wat het beste er uit zal zien. Hou vooral deze pagina https://dso-toolkit.nl/11.0.0/components/detail/landingspagina.html in de gaten als het gaat om de featured row. Omdat dat een live voorbeeld is dat draait en effect zal hebben op die pagina

**Comment by PieterVerheij** [comment]
@MichielDHVD 
Zie https://www.dso-toolkit.nl/_500.Onderzoek-en-Analyse-Marges-in-de-toolkit/index.html

Ik heb je marge aanpassingen niet 1 op 1 kunnen overnemen, maar volgens mij zitten we er wel dichtbij. Hete hangstukken zijn wat mij betreft de ruimtes tussen de rows (als er eentje een gekleurde achtergrond heeft) en `margin-top` en `margin-bottom` die vanuit de `dso-rich-content` komen.

Check https://percy.io/dso-toolkit/dso-toolkit/builds/6452726?utm_content=finished_unreviewed_snapshots  voor de huidige status.

Dit is wat mij nu al opviel: 
Margin-top 8px
Info: wil je daar wel zo'n marge op de heading?
https://www.dso-toolkit.nl/_500.Onderzoek-en-Analyse-Marges-in-de-toolkit/components/detail/info.html

Banner: wil je daar zo'n marge en het icoon omlaag of geen marge? Zelfde geld voor Alert
https://www.dso-toolkit.nl/_500.Onderzoek-en-Analyse-Marges-in-de-toolkit/components/detail/banner.html
https://www.dso-toolkit.nl/_500.Onderzoek-en-Analyse-Marges-in-de-toolkit/components/detail/alert.html

Full-width: de marge onder een dso-featured is nog niet juist, daar moet ik nog wat tweaken
https://www.dso-toolkit.nl/_500.Onderzoek-en-Analyse-Marges-in-de-toolkit/components/detail/full-width.html

De combinatie `<hr> + <h2>` is nog ongelukkig
https://www.dso-toolkit.nl/_500.Onderzoek-en-Analyse-Marges-in-de-toolkit/components/detail/beheer-basis.html 

De margin-top eerste element in de `dso-jumbotron-body` zou ik op 0 zetten
https://www.dso-toolkit.nl/_500.Onderzoek-en-Analyse-Marges-in-de-toolkit/components/detail/jumbotron.html

De margin-bottom op de `panel-body` zou ik op 0 zetten (of .dso-rich-content er als extra class bij)
https://www.dso-toolkit.nl/_500.Onderzoek-en-Analyse-Marges-in-de-toolkit/components/detail/panel.html

De padding-bottom van de `dso-section-body` zou ik aanpassen (24px ip 32px)
https://www.dso-toolkit.nl/_500.Onderzoek-en-Analyse-Marges-in-de-toolkit/components/detail/accordion.html

**Comment by MichielDHVD** [comment]
Ik zag percy al voorbij komen ik was benieuwd. Zal er even naar kijken en suggesties doen. Voor de banner in ieder geval geen marge, maar bij de alert zie ik geen verschil.

**Comment by MichielDHVD** [comment]
Info heading: 
De margin-top 8px lijkt inderdaad onnodig in het  component

Banner geen marge
Alert, ik zie geen verschil wat is er veranderd? 

DSO-row featured, Hier kun je aan de onder kant wel wat forsere margin neerzetten, is volgens mij ook de reden dat de row zon agressieve 48px had om de featured goed te laten werken. Dus bij featured kun je miss zelfs beginnen op 48 en dan naar beneden werken 40 -> 32 etc om te kijken wat goed werkt

Hr + H2, Ik vind de Hr sowieso veels te fors. Voor hr mag het gerust van 24 -> 8 zowel boven als onder vind ik. Lost nog steeds niet de extra ruimte plus h2 op, maar komt wel in de buurt. 

Jumbotron is extreem verouderd wordt niet gebruikt geen aandacht aan besteden. Liever deprecaten

Panel-body margin bottom 0 is prima

dso-section-body 24 vs 32px oogt idd beter. 

Als ik nog naar meer dingen moet kijken zal ik dat doen. Ga ik ook zelf nog even alles nalopen, of er andere dingen opvallen. Maar dat komt waarschijnlijk in een vervolg issue.

**Comment by PieterVerheij** [comment]
Info heading:
V De margin-top 8px lijkt inderdaad onnodig in het component

Banner geen marge
V Alert, ik zie geen verschil wat is er veranderd?
Door een andere (marge-)aanpassing is dit weer automagisch goed gekomen. Deze melding kan genegeerd worden

V DSO-row featured, Hier kun je aan de onder kant wel wat forsere margin neerzetten, is volgens mij ook de reden dat de row zon agressieve 48px had om de featured goed te laten werken. Dus bij featured kun je miss zelfs beginnen op 48 en dan naar beneden werken 40 -> 32 etc om te kijken wat goed werkt
Hier heb ik een trucendoos moeten uithalen voor headings na een headings die direct na .dso-featured.row komen.

V Hr + H2, Ik vind de Hr sowieso veels te fors. Voor hr mag het gerust van 24 -> 8 zowel boven als onder vind ik. Lost nog steeds niet de extra ruimte plus h2 op, maar komt wel in de buurt.

Jumbotron is extreem verouderd wordt niet gebruikt geen aandacht aan besteden. Liever deprecaten

V Panel-body margin bottom 0 is prima

V dso-section-body 24 vs 32px oogt idd beter.

De marge aanpassingen hebben trouwens ook effect op een highlightbox over een image (https://percy.io/dso-toolkit/dso-toolkit/builds/6528757/view/374197268/1280?mode=diff&browser=firefox&snapshot=374197268). Misschien zou je willen dat hij verticaal gecentreerd wordt (nieuw/ander issue)?

**Comment by MichielDHVD** [comment]
Centreren van de afbeelding lijkt me prima voor een ander issue mochten we dat willen.

**Comment by PieterVerheij** [comment]
Prima.
Nemen we deze aanpassingen mee in deze release?

**Comment by MichielDHVD** [comment]
We hebben straks toolkit refinement miss even bespreken
