### ISSUE TITLE
External/download link icon bij visited state verandert niet van kleur. 

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#501]
De visited links hebben een paarse kleur maar voor de icons verandert de kleur niet mee. (Mogelijk ook meteen de icon grootte veranderen. De external link is 16px en erg klein) 

<img width="696" alt="Screen Shot 2020-01-20 at 11 58 25" src="https://user-images.githubusercontent.com/36912722/72721390-376b8c00-3b7c-11ea-9523-09541dd7aead.png">
<img width="973" alt="Screen Shot 2020-01-20 at 11 58 32" src="https://user-images.githubusercontent.com/36912722/72721391-376b8c00-3b7c-11ea-8593-cc4e21712836.png">

https://dso-toolkit.nl/9.6.0/components/detail/anchors.html

_edit @tfrijsewijk: URL naar situatie toegevoegd_

**Comment by tfrijsewijk** [comment]
Ik heb dit gedrag al eens aangekaart en ik meen mij te herinneren dat we dit onderwerp al eens hebben besproken, ik weet alleen niet waar en hoe.

Dit is een bug die we niet vanuit de toolkit kunnen fixen. Dit heeft me privacy overwegingen te maken, zie dit artikel op MDN:

>Before about 2010, the CSS :visited selector allowed websites to uncover a user's browsing history and figure out what sites the user had visited. This was done through window.getComputedStyle and other techniques. This process was quick to execute, and made it possible not only to determine where the user had been on the web, but could also be used to guess a lot of information about the user's identity.
https://developer.mozilla.org/en-US/docs/Web/CSS/Privacy_and_the_:visited_selector

Het icoon wordt getoont dmv. een `::after` selector op `.download` en `.extern` met een `background-image` verwijzend naar de SVG spritesheet. Het is niet mogelijk om de background image te wijzigen met `:visited` state selector.

Dit werkte in de pre-SVG versies wel: Het icoon was een karakter uit een font welke de kleur van `color` kreeg.

Een aantal oplossingen:

**Het extern en download icoon onderbrengen in een eigen font en deze exclusief gebruiken voor `.download` en `.extern`.**
Nadelen:
* Extra build artifact
* Weer een font (wat we er net uit hebben gehaald)

Voordelen:
* Alles blijft stuurbaar vanuit de toolkit, mits de implementator het font bundled (maar dat wordt voor Asap ook al gedaan)
* Styling gaat met `color` property

**De implementator de SVGs in de markup laten zetten**
Nadelen:
* Breaking change
* De implementator moet SVG's plaatsen
* Iets minder sturing vanuit de toolkit, maar nog steeds prima
* CMS gaat hier niet makkelijk mee over weg kunnen

Voordelen:
* Styling gaat met `color` property

**Voor download en externe links geen visited state markeren**
Voordelen:
* Snelste oplossing :-)

Nadelen:
* Geen indicatie meer of de download al is gedownload of de externe link al is geopend, maar misschien is dit wel helemaal geen probleem?

Andere oplossingen: graag!

**Comment by bramhoosemans** [comment]
Mijn voorkeur gaat uit naar 'Voor download en externe links geen visited state markeren'.

Het betreft link classes die hoofdzakelijk vanuit het CMS zullen worden meegegeven. Een eigen font levert dubbele beheerslast op en hebben we net eruit gehaald. Met een aparte SVG kan het CMS niet goed omgaan, dus die optie valt ook af.

**Comment by MichielDHVD** [comment]
Ik kwam deze css property tegen is dit misschien een optie. Het zal even proberen worden om de juiste kleur te vinden. 

gaat om de filter optie 

filter: invert(56%) sepia(26%) saturate(586%) hue-rotate(278deg) brightness(100%) contrast(89%);  

Ik kan de kleur van het element hier mee aanpassen. 

Qua ondersteuning ziet het er zo uit.  (IE11 niet ondersteund, maar IE11 ligt hier momenteel onder vuur en gaat mogelijk afvallen) 

https://caniuse.com/#feat=css-filters

**Comment by tfrijsewijk** [comment]
Dat zal ook niet werken. `filter` staat niet in het lijstje van stijlbare properties in de `:visited` state: https://developer.mozilla.org/en-US/docs/Web/CSS/Privacy_and_the_:visited_selector#Limits_to_visited_link_styles

**Comment by MichielDHVD** [comment]
Issue kan niet gefixed worden voor nu zo laten.
