### ISSUE TITLE
Iconen wijziging - indicatoren

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#502]
Wijziging indicatoren iconen met witte rand.

**Comment by Anto1nette** [comment]
Bij deze de vier aangepaste indicatoren
[status-outline.zip](https://github.com/dso-toolkit/dso-toolkit/files/4103238/status-outline.zip)

**Comment by tfrijsewijk** [comment]
Merged #508 into master

**Comment by tfrijsewijk** [comment]
Opgeleverd in 9.7.0: https://dso-toolkit.nl/9.7.0/dso-icons.svg

@bramhoosemans Moesten deze iconen ook niet ergens geimplementeerd worden?
