### ISSUE TITLE
Menu knop bij kleine header is niet in lijn met huidige stijl

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#503]
<img width="356" alt="Screen Shot 2020-01-21 at 09 38 22" src="https://user-images.githubusercontent.com/36912722/72788236-cdadb980-3c31-11ea-9ecc-d14b649df965.png">

Er is een herontwerp nodig voor de menu knop zodat deze meer aansluit op de huidige stijl knoppen.

**Comment by MichielDHVD** [comment]
Om te beginnen is het beste om deze knop in lijn te brengen met de secundaire knoppen en al het gedrag dat erbij komt. 
![menu button](https://user-images.githubusercontent.com/36912722/88793202-bd583780-d19c-11ea-8b90-16fc63eed2a7.jpg)

**Comment by PieterVerheij** [comment]
@MichielDHVD https://www.dso-toolkit.nl/_503.Menu-knop-bij-kleine-header-is-niet-in-lijn-met-huidige-stijl/components/detail/header.html

Misschien moeten we in een ander issue de horizontale uitlijning oppakken?

**Comment by MichielDHVD** [comment]
Mee eens. De header gaat nog gereworked worden maar voor nu hoeft dat niet.
