### ISSUE TITLE
Hoogte inputfields en dropdowns niet juist

### ISSUE THREAD

**Issue by PieterVerheij** [dso-toolkit/dso-toolkit#506]
In de toolkit zijn de inputfields en dropdowns 38px hoog, dat dient 40px te zijn.

![image](https://user-images.githubusercontent.com/25430835/72984409-ebbb1b80-3de3-11ea-897c-361c70e2d41f.png)

**Comment by gofix** [comment]
De hoogte die standaard vanuit bootstrap van toepassing is, wordt bepaald door de volgende sommetjes en variabelen:
```
//** Computed "line-height" (`font-size` * `line-height`) for use with `margin`, `padding`, etc.
$line-height-computed:    floor(($font-size-base * $line-height-base)) !default; // ~20px

//** Default `.form-control` height
$input-height-base:              ($line-height-computed + ($padding-base-vertical * 2) + 2) !default;
```

Uiteraard zou je liefst aan de variabelen tweaken waaruit dit soort basismaten vandaan komen. Zodat andere (bootstrap) componenten met dezelfde factoren werken. Echter... aanpassen van die superwezenlijke basisvariabelen kunnen zomaar onverwachte bij-effecten hebben, die dan weer zouden moeten worden gecorrigeerd (gelukkig is er natuurlijk percy die ons daarop wijst).

Voor nu vind ik de lokale oplossing acceptabel. Op de longlist zou ik echter nog wel misschien een keer een momentje willen nemen om het gebruik en de uitwerking van de bootstrap variabelen neen keer te heroverwegen.
