### ISSUE TITLE
Toolkit 404 pagina

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#509]
Op dit moment krijgen we een prachtige 'server error' 404 pagina. Laten we een 404 in ieder geval goed afvangen. De 'homepage' link verwijst naar de pagina waar de bezoeker op binnenkomt (introductie).

Zijn er nog andere error codes die we kunnen/willen afvangen, zoals 500?

![toolkit-404](https://user-images.githubusercontent.com/598735/73057754-95f17c80-3e92-11ea-947b-6adff326c97c.png)

**Comment by PieterVerheij** [comment]
https://github.com/dso-toolkit/dso-toolkit/pull/576
