### ISSUE TITLE
Ongewenste Styling active tertiare buttons

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#511]
Ten tijden van het ontwerpen van de focus states voor de toolkit. Zijn ook de active states van de tertiare buttons aangeraakt. 

Deze styling is niet veranderd sinds de focus states. Maar met de restyling van de lnk-buttons heeft er voor gezorgd dat tertiare buttons qua styling een rare active state hebben 

<img width="136" alt="Screen Shot 2020-01-27 at 12 49 16" src="https://user-images.githubusercontent.com/36912722/73172505-757c2900-4103-11ea-9ab9-98e566deda91.png">

<img width="586" alt="Screen Shot 2020-04-29 at 11 32 22" src="https://user-images.githubusercontent.com/36912722/80583132-1edaff80-8a10-11ea-83b3-644eb55a2d0b.png">

Het geen wat aangepast moet worden is:

- de kleur deze wordt: #676cb0 net als de hover state. 
- geen underline
- Vierkantje moet weg en icoon krijgt ook een #676cb0 kleur

**Comment by MichielDHVD** [comment]
In de button documentatie viel me het volgende op. Namelijk dat de hover state van de tertiare button in de documentatie niet overeen komt met de hover state wat onder het tabblad component staat. (los issue?) 

Button states in de documentatie
<img width="895" alt="Screen Shot 2020-04-29 at 11 57 35" src="https://user-images.githubusercontent.com/36912722/80583652-c9ebb900-8a10-11ea-8a31-08b085630eb8.png">

Button states in het tabblad component
<img width="648" alt="Screen Shot 2020-04-29 at 11 59 07" src="https://user-images.githubusercontent.com/36912722/80583726-e0921000-8a10-11ea-9cd4-43b8dcb2b250.png">

**Comment by PieterVerheij** [comment]
https://www.dso-toolkit.nl/_511.ongewenste-Styling-active-tertiare-buttons/components/detail/buttons.html
