### ISSUE TITLE
Uitlijning knoppen in modal

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#513]
De uitlijning van knoppen in de modal is nogal rommelig. Met name het 'sluit' icoon verspringt in de hover-state. 

- Icoon wordt niet getoond in linkbutton 'Annuleren' (mag zonder icoon, maar staat nu wel in de code)
- Sluit icoon te klein
- Sluit icoon verspringt op hover (volgens mij moeten we hier de hover state herzien!)
- Dropschaduw toevoegen? box-shadow: 0 8px 24px 0 rgba(25,25,25,0.40);

![Schermafbeelding 2020-01-27 om 15 44 10](https://user-images.githubusercontent.com/598735/73184055-1971ce80-411c-11ea-9a77-1fba5d54e775.png)

**Comment by PieterVerheij** [comment]
Waarschijnlijk zitten hier de wijzigingen voor de issues van de icoongrootte en uitlijning knoppen elkaar in de weg.

Ik pak hem op.

**Comment by PieterVerheij** [comment]
@bramhoosemans Ik heb het idee dat er sprake is van caching? Ik ging nog een keer kijken, maar nu is het goed? Zou jij nog een keer willen kijken?

![image](https://user-images.githubusercontent.com/25430835/73370909-3a215c00-42b5-11ea-956a-9ca9ab1c7e87.png)

Los daarvan is positie van de "Annuleren" knop niet goed (althans: de padding), maar dat komt goed in het button-margins issue.

**Comment by bramhoosemans** [comment]
Ik zie inderdaad dat het formaat van het icoon en het verspringen opgelost is in Release 9.7.0. Er lijkt alleen wel een icoon op te staan die niet weergegeven wordt (mag van mij weg).

<img width="238" alt="Schermafbeelding 2020-01-30 om 09 14 04" src="https://user-images.githubusercontent.com/598735/73431522-e65c5480-4340-11ea-9e29-f422146e72cb.png">

Dan blijven er voor de rest ontwerp vragen over:
- Hover state van het sluit icoon herzien
- Dropschaduw toevoegen? box-shadow: 0 8px 24px 0 rgba(25,25,25,0.40);

**Comment by bramhoosemans** [comment]
@MichielDHVD zal het ontwerp beoordelen en direct button positionering in het modal meenemen. Hier wordt een nieuw issue voor aangemaakt.
