### ISSUE TITLE
Paperclip en teller (`.dso-attachments`) worden niet wit wanneer het paneel van het accordion is uitgeklapt

### ISSUE THREAD

**Issue by jeroenpeeters** [dso-toolkit/dso-toolkit#514]
Zoals de titel al aangeeft blijft de paperclip en bijbehorende text (tellertje) grijs wanneer het accordion paneel is uitgeklapt (`.dso-open`). De achtergrond wordt dan namelijk paars waarop een grijze tekst en icoontje lastig te lezen is.

Ik zie dat er wel een css-selector voor is, maar volgens mij klopt deze niet.

```
.dso-accordion .dso-accordion-section.dso-open:not(.dso-nested-accordion) .dso-attachments a::after {
      background-image: url("../dso-icons.svg#img-paperclip-wit"); }
```

Volgens mij moet de selector zijn
```
.dso-accordion .dso-accordion-section.dso-open:not(.dso-nested-accordion) .dso-section-handle a .dso-attachments::after {
....
}
```

Ook de tekst (tellertje) in .dso-attachments blijft grijs en neemt niet de kleur over van de boveliggende `a` omdat deze kleur hard wordt overschreven door `.dso-attachments`

Zie:
```
.dso-accordion .dso-section-handle a .dso-attachments {
      color: #666;
      display: block;
      float: right;
      font-weight: 400;
      text-decoration: none; }
```

Ook als ik het voorbeeld aanpas krijg ik het niet werkend. Kijk er aub even goed naar.

**Comment by PieterVerheij** [comment]
Ik pak hem op.

**Comment by PieterVerheij** [comment]
Testable (onderaan de apgina):
https://www.dso-toolkit.nl/_514.Paperclip-teller-niet-wit-wanneer-uitgeklapt/components/detail/accordion.html

**Comment by gofix** [comment]
@PieterVerheij kijk nog even naar mijn comment in de PR
