### ISSUE TITLE
Positie info button bij een label over meerdere regels

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#517]
Info button staat bij een label over meerdere regels onder van de vraag. Hierdoor is de relatie met het label weg. Het verwachte gedrag is dat deze:
- Meebeweegt met tekst (op 8px afstand van het laatste woord in de zin);
- Rechts blijft staan en het label eerder afgebroken wordt.

<img width="1207" alt="Schermafbeelding 2020-01-30 om 15 54 27" src="https://user-images.githubusercontent.com/598735/73460513-e5471980-4378-11ea-82cd-3a4086881ede.png">

**Comment by PieterVerheij** [comment]
Om de button met de tekst met de laten 'flowen', moet er een breaking change uitgevoerd worden: de button staat nu NAAST het label, die zou nu IN het label moeten komen te staan.

**Comment by bramhoosemans** [comment]
Geen idee of het IN het label mag staan... De wens is dat de info-button altijd in relatie met het label of input-item (radio of checkbox) blijft staan.

**Comment by PieterVerheij** [comment]
Hier wordt iig wel een argument gegeven om het niet te doen, 
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label

Een optie is om de button met de huidige markup rechtsboven absoluut te postioneren, en het label er links van te late wrappen. Alleen staat hij dan altijd uitertst rechts gepotioneerd, ook bij korte labels.

**Comment by PieterVerheij** [comment]
@timveld Wat vind jij van een dergelijke constructie, waarbij de button voor de toelichting IN het label geplaatst is? De input die bij het label hoort, staat dan nog steeds naast het label.

`<div class="form-group dso-input dso-input-textd">
  <div class="dso-label-container">
    <label for="input-text-infobutton-open" class="control-label">
      E-mailadres
      <button type="button" class="btn dso-info-button dso-open">
        <span class="sr-only">
          Toelichting
        </span>
      </button>
    </label>
  </div>
  <div class="dso-field-container">
    <input type="text" id="input-text-infobutton-open" class="form-control">
  </div>
</div>`

**Comment by PieterVerheij** [comment]
Nevermind, ik lijk toch een css oplossing te hebben gevonden. Die wel even goed geverifieerd moet worden.

**Comment by PieterVerheij** [comment]
Opgelost, maar build faalt op de server.

**Comment by gofix** [comment]
Falende build: https://travis-ci.com/dso-toolkit/dso-toolkit/builds/147756088
Er worden changes gemeld in de reference files, die we even nader moeten bestuderen: Starting 'testAgainstReference'...

**Comment by PieterVerheij** [comment]
Testable https://www.dso-toolkit.nl/_517.Positie-info-button-label-meerdere-regels/

**Comment by bramhoosemans** [comment]
Bij het label van de vraag gaat het goed, maar bij het label van een radiobutton niet (zie screenshot).

![Schermafbeelding 2020-02-10 om 21 24 21](https://user-images.githubusercontent.com/598735/74186872-bc156b80-4c4b-11ea-8332-3b70191722f9.png)

**Comment by gofix** [comment]
Verwerk nog even een casus met een heel lang label in een radio-buttons werkvorm, zoals @bramhoosemans hierboven meldt. Dan kunnen we mooi zien in de percy screenshots hoe dat er nu uit gaat zien (en voortaan wordt deze situatie dan ook bewaakt).

**Comment by gofix** [comment]
Dit is nu netjes opgelost. @bramhoosemans kun jij dat nog bevestigen?

**Comment by bramhoosemans** [comment]
Ziet er goed uit!
