### ISSUE TITLE
Fieldset legend styling

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#518]
De fieldset legend aanpassen naar H3 styling:
- Asap SemiBold, font size 20px, line height 26px, #275937
- 32px ruimte onder
- Divider tussen fieldsets (onder toevoegen en dat niet op de laatste?) 

![Gegevens](https://user-images.githubusercontent.com/598735/73545677-16d4e900-443c-11ea-89e3-59e35ff419cf.png)

![Verzoek--meerdere-vraaggroepen](https://user-images.githubusercontent.com/598735/73545678-16d4e900-443c-11ea-9bed-077bd3ab7acc.png)

**Comment by PieterVerheij** [comment]
@bramhoosemans de standaard line-height van de H3 is 30px (20px * 1.5). Moet dat dan ook aangepast worden?

**Comment by PieterVerheij** [comment]
https://www.dso-toolkit.nl/_518.Fieldset-legend-styling/components/detail/form--form-vertical.html
https://www.dso-toolkit.nl/_518.Fieldset-legend-styling/components/detail/form--form-horizontal.html

**Comment by MichielDHVD** [comment]
Ik laat Bram nog reageren op je laatste vraag voordat ik deze op accepted zet.

**Comment by bramhoosemans** [comment]
@PieterVerheij Dat is grappig: op https://dso-toolkit.nl/master/docs/typography.html staat de line-height van de H3 op 26.666px.

Dit heb ik destijds overgenomen in de ontwerpen.

**Comment by PieterVerheij** [comment]
@bramhoosemans ik vermoed dat dat komt omdat hier niet de standaard Bootstrap line-height wordt gebruikt (zelfs niet de dso.css maar een default.css!). Is ook voor het eerst dat ik dit zie :-/

**Comment by PieterVerheij** [comment]
@bramhoosemans toch maar 30px aanhouden?

**Comment by bramhoosemans** [comment]
Hou maar 30px aan, dat klinkt in ieder geval beter dan 26,666px.

**Comment by bramhoosemans** [comment]
Er zit een margin-bottom op van 24px; dit mag verhoogd worden naar 32px (gelijk aan de .form-group).

**Comment by PieterVerheij** [comment]
Aangepast: https://www.dso-toolkit.nl/_518.Fieldset-legend-styling/components/detail/form--form-vertical.html

**Comment by gofix** [comment]
In https://github.com/dso-toolkit/dso-toolkit/commit/9a5229fd41aa59b2e04dffb6737be2c2616f3f32 (#421) heeft de `.form-group` al extra marge gekregen, waardoor nu soms een DUBBELE marge ontstaat. Dat is uiteraard niet wenselijk:
![image](https://user-images.githubusercontent.com/2689559/74241559-94221880-4cdc-11ea-8819-ffa0a5572ef8.png)

**Comment by bramhoosemans** [comment]
> In [9a5229f](https://github.com/dso-toolkit/dso-toolkit/commit/9a5229fd41aa59b2e04dffb6737be2c2616f3f32) (#421) heeft de `.form-group` al extra marge gekregen, waardoor nu soms een DUBBELE marge ontstaat. Dat is uiteraard niet wenselijk:
> ![image](https://user-images.githubusercontent.com/2689559/74241559-94221880-4cdc-11ea-8819-ffa0a5572ef8.png)

Die heeft er dus altijd al gezeten; we hebben enkel de .form-group margin vergroot.

**Comment by gofix** [comment]
Dus, @bramhoosemans jij stelt dat dit nu WEL acceptabel is? En dus, dat in form-groups met fieldsets de ruimte onderin gewoon flink is?

**Comment by bramhoosemans** [comment]
@gofix Nee, ik stel dat er al eerder sprake was van dubbele marge.

We zouden dit wellicht kunnen oplossen door de laatste .form-group in de fieldset géén marge te geven. Maar @MichielDHVD is bezig met een inventarisatie van foutieve marges, dus deze mag sowieso daarin meegenomen worden.
