### ISSUE TITLE
Gebruik laatste (3.4.1) versie van bootstrap-sass

### ISSUE THREAD

**Issue by WidoBurg** [dso-toolkit/dso-toolkit#522]
Dso-toolkit gebruikt bootstrap-sass versie 3.3.7. 
In bootstrap-sass 3.4.0 en 3.4.1 zijn vulnerabilities gefixd. 
Zie: https://github.com/twbs/bootstrap-sass/releases.

Graag de toolkit updaten met de laatste (op moment van schrijven dus de 3.4.1).
Zodat deze nieuwe versie ook meekomt en dus de vulnerabilities niet meer als issue terugkomen in de apps die de dso-toolkit gebruiken.

**Comment by PieterVerheij** [comment]
Ik heb de bootstrap versie geupdate, zie zelf geen visuele changes. Volgens https://github.com/twbs/bootstrap-sass/releases waren die ook niet te verwachten.

**Comment by PieterVerheij** [comment]
https://www.dso-toolkit.nl/_522.Gebruik-laatste-versie-bootstrap-sass/

**Comment by bramhoosemans** [comment]
Zover ik kan zien geen veranderingen.
