### ISSUE TITLE
Accordion faq styling

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#523]
![faq](https://user-images.githubusercontent.com/598735/73852143-fb4c5280-482e-11ea-8082-da5ee662edba.png)

Specificaties:
[accordion-faq.zip](https://github.com/dso-toolkit/dso-toolkit/files/4160121/accordion-faq.zip)

**Comment by PieterVerheij** [comment]
@bramhoosemans wordt dit een nieuw component?

**Comment by bramhoosemans** [comment]
Nee, het idee was om een alternatieve styling van de accordion mogelijk te maken.

**Comment by PieterVerheij** [comment]
Met dezelfde markup? Dat kan, maar zou ik niet adviseren: de huidige accordion maakt gebruik van een link voor het in- en uitklappen. Dat zou eigenlijk een `button` moeten zijn, maar dat betekent een breaking change.

Ik heb nu een nieuwe "accordion-light" gemaakt, die een `button` gebruikt. https://www.dso-toolkit.nl/_523.accordion-faq-styling/components/detail/accordion-light.html

**Comment by bramhoosemans** [comment]
Visueel prima!

@tfrijsewijk zou jij kunnen beoordelen of dit volgens plan is wat betreft toegankelijke accodions? Volgens mij gaf Tim toen ook al aan dat het eigenlijk een button component moet zijn, maar kan me de uitkomst van die discussie niet voor de geest halen.

**Comment by gofix** [comment]
Doorgesproken met @tfrijsewijk. We denken dat het een beter idee is om de light en de default variant van de accordion toch door hetzelfde component ta laten bouwen (waarbij de light variant dan puur door een modifier class ontstaat). In de standaard accordion gaan we zowel `<button>` als `<a href="">` ondersteunen (want ook al is 'on-page' `<button>` wellicht de betere oplossing, de vorm met `<a href>` is niet per se fout en kent wellicht juist ook zelf bestaansrecht. In de styling (voor zowel de default als light variant) gaan we gewoon beide ondersteund houden, dan wordt deze change ook niet breaking.

**Comment by gofix** [comment]
@bramhoosemans  check: https://dso-toolkit.nl/_523.accordion-light-faq-v2/components/detail/accordion--compact.html (en https://dso-toolkit.nl/_523.accordion-light-faq-v2/components/detail/accordion--default.html). VIsueel niet anders dan voorheen, maar nu simpelweg te implementeren door een modifier class `dso-accordion-compact` toe te voegen aan de `dso-accordion`.

**Comment by gofix** [comment]
Verder viel ons bij het aandachtig bestuderen van de visuele changes op dat we met #532 een breaking change hebben geintroduceerd. Dat willen we liever terugdraaien, hetgeen we in dit issue eenvoudig nog even zouden kunnen doen.

**Comment by bramhoosemans** [comment]
> Verder viel ons bij het aandachtig bestuderen van de visuele changes op dat we met #532 een breaking change hebben geintroduceerd. Dat willen we liever terugdraaien, hetgeen we in dit issue eenvoudig nog even zouden kunnen doen.

Klinkt goed.

Verder viel me op dat:
- De font rendering erg afwijkt van het ontwerp; in de accordion zouden we Semi Bold moeten gebruiken. Kan zijn dat dit een Sketch vs Browser ding is.
- Er in de default accordion een regular font gebruikt in sommige gevallen. Dit lijkt in release 9.7.0 te zijn omgevallen.

**Comment by daverhelst** [comment]
@bramhoosemans ik heb er voor gezorgd dat de `.dso-section-handle` nu altijd een font-weight heeft van 600 (semi-bold).

In de loop van enige tijd te zien op: https://dso-toolkit.nl/_523.accordion-light-faq-v2/components/detail/accordion--default.html

Is dit wat je voor ogen had?

**Comment by bramhoosemans** [comment]
Helemaal top!
