### ISSUE TITLE
Bijzondere tekstverbeeldingen

### ISSUE THREAD

**Issue by DjangoBlok** [dso-toolkit/dso-toolkit#530]
In (juridische) teksten kunnen een aantal bijzondere elementen voorkomen. De verbeelding van deze elementen is nog niet opgenomen in de toolkit.

Bijgevoegd een voorbeeld van de elementen:
[ins] : doorgehaald en background #E4F1D4
[del] : background #F5D8DC 
[sup] : font size 10px superscript
[sub] : font size 10px subscript
[a class="voetnoot-link" href=”#voetnoot14” aria-describedby=”voetnoot14” /] : superscript,  font size 12px, medium
[ul class="voetnoten/] :  lijn erboven

![typografie toevoeging](https://user-images.githubusercontent.com/34900082/74033054-ab4bc800-49b5-11ea-86bd-977cadd4347f.png)

**Comment by DjangoBlok** [comment]
Del en ins elementen worden niet door alle screenreaders goed opgepakt.
Hierbij een oplossing in de css
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/del

**Comment by DjangoBlok** [comment]
@timveld ik begreep dat jij voor Koop ook hiermee bezig bent. Hier het issue voor de toolkit.

**Comment by timveld** [comment]
Ik ben dinsdag bij Koop geweest en heb onderstaand conceptmemo geschreven. Dat zou op confluence moeten maar wacht eerst de reactie van Koop af, misschien kunnen wij dit dinsdag / donderdag bespreken. @DjangoBlok kun je hier wat mee? Je noemt ook andere tags waar we misschien wat mee moeten. 
1. In html worden del en ins tags gebruikt. NVDA leest die redelijk voor, JAWS niet. Del en ins tags niet gebruiken is geen optie, aangezien browsers deze goed ondersteunen en het in elkaar knutselen van een alternatief om allerlei redenen een slecht idee is.
2. Het aanvankelijke plan was om [begin ingevoegd] ... [einde ingevoegd] sr-only in te voegen. Daarmee is de pagina in principe voor alle screen reader gebruikers duidelijk.
2.1 Een bezwaar is dat daarmee de tekst (in ieder geval voor blinde en andere gebruikers van user agents die CSS negeren) wordt gewijzigd. In een juridische tekst is zo'n wijziging minst genomen onwenselijk. 
2.2 De doorslaggevende reden om deze oplossing niet te kiezen is echter dat de del en ins tags voor screen readers verborgen zouden moeten worden, omdat NVDA (en andere screen readers die del en ins in de toekomst ondersteunen) anders dubbel gaan voorlezen waarmee de tekst niet meer goed leesbaar is. Het verbergen van deze tags is met Aria waarschijnlijk wel mogelijk, maar het is ingewikkeld en kan allerlei onvoorziene bijwerkingen hebben.
2.3 Er is een compromis overwogen waarbij we sr-only accolades (of andere weinig voorkomende tekens) rond de ingevoegde en verwijderde stukken tekst zouden invoegen. NVDA zou de tekst dan ook nog goed lezen zonder dat we de del en ins tags hoeven te slopen, waarbij meteen begin en einde van de ingevoegde / verwijderde delen tekst worden aangegeven. Het onder 2.1 genoemde bezwaar dat de tekst wordt gewijzigd is daarbij echter (in verhoogde mate) van toepassing, waarbij grote problemen ontstaan als de tekst al accolades bevat.
2.4 De conclusie is dat we in HTML alleen de del en ins tags gaan gebruiken. Daarmee voldoen we M.I. aan de eisen van WCAG aangezien programmatisch bepaald kan worden welke tekst is ingevoegd en verwijderd.
2.5 Dat de meeste screen readers (JAWS, Supernova, Apple) del en ins tags niet ondersteunen is niet onze verantwoordelijkheid; van een goede screen reader mogen wij als ontwikkelaars verwachten dat hij semantische HTML tags adequaat ondersteunt. Aan de andere kant hebben we als overheidsinstelling wel een bepaalde 'zorgplicht' tegenover de groep die deze screen readers gebruikt, waaraan we invulling geven door de DSO toegankelijkheidsexpert dit probleem bij de diverse screen reader bouwers te laten aankaarten.
2.6 In de documentatie moet te zijner tijd worden aangegeven dat alleen NVDA (en hopelijk tegen die tijd andere screen readers) de revisies goed kunnen aangeven. In andere screen readers is het wel mogelijk de revisies te lezen door het uitspreken van tekstattributen aan te zetten, de screen reader kan namelijk wel voorlezen dat de verwijderde tekst doorgestreept en de ingevoegde tekst onderstreept is.  
3. Ook NVDA doet het helaas nog niet helemaal goed: het einde van de ingevoegde en verwijderde delen wordt niet voorgelezen. Dit probleem is inmiddels gerapporteerd: https://github.com/nvaccess/nvda/issues/10789
4. In PDF zijn geen del en ins tags of sr-only class beschikbaar. Wel blijkt het mogelijk de sr-only class na te bootsen door tekstelementen een alt tag te geven, zodat 'begin / einde ingevoegd / verwijderd' voor screen readers kan worden toegevoegd. Deze oplossing zal worden gebruikt. 
4.1 Dat de tekst voor screen reader gebruikers veranderd (zie 2.1) is een bezwaar maar dit is de enige manier om in PDF de toegevoegde en verwijderde stukken te markeren, het alternatief is deze markeringen helemaal weglaten maar dan wordt de PDF feitelijk onleesbaar. 
4.2 In de documentatie kan worden opgenomen dat de HTML versie de meer toegankelijke versie is.
4.3 Als de verwijderde / toegevoegde delen tekstattribuut doorgestreept / onderstreept krijgen kunnen screen reader gebruikers wel de delen uit elkaar houden, mits ze de instellingen van hun screen reader aanpassen. Dat kan dus mogelijk een alternatieve oplossing zijn.

**Comment by DjangoBlok** [comment]
@timveld Dank voor je uitgebreide onderzoek.
Voor wat betreft de ins en del tags kan ik me goed vinden in conclusie 2.4.
Lijkt mij ook dat we de standaarden moeten volgen en niet de daarvan afwijkende screenreaders.

Mocht er op een platform geen mogelijkheid zijn om hiermee om te gaan, dan zou je dat kunnen oplossen door de tekst tussen del tags weg kunnen laten en de tekst tussen ins tags wel weer te geven. Je krijgt dan de juridische tekst correct te lezen, maar verliest het zicht op de veranderingen.

**Comment by tfrijsewijk** [comment]
Over de markup voor footnotes. Wij hebben de volgende markup geimplementeerd:

```html
Een<a href="#voetnoot1" aria-describedby="voetnoot1" class="dso-footnote-link">1</a> voetnoot

<ol class="dso-footnotes">
  <li class="dso-footnote" id="voetnoot1"><span class="dso-indicator">1.</span> definitie</li>
</ol>
```

Maar wikipedia heeft een mooi systeem dat je kan terugstappen naar de voetnoot verwijzing. Wat denken jullie van de volgende markup?

```html
Een<sup id="referentie1"><a href="#voetnoot1" class="dso-footnote-link">1</a></sup> voetnoot

<ol class="dso-footnotes">
  <li class="dso-footnote" id="voetnoot1"><a href="#referentie1" class="dso-indicator">1.</a> definitie</li>
</ol>
```

Mijn voorstel heeft geen aria-describedby, hoe verplicht is deze? Ik denk namelijk niet dat deze nodig is

**Comment by timveld** [comment]
Als je niet weet hoe noodzakelijk een Aria-element is: niet gebruiken en dat geldt ook hier. Genummerde referenties / voetnoten zijn in teksten zeer gebruikelijk [1]. Het systeem van Wikipedia is goed, jouw voorstel lijkt me prima zo.

**Comment by timveld** [comment]
Wat betreft sub / sup tags: NVDA ziet dit als font attributes en zegt dus standaard "oppervlakte: 25 m2". Het uitspreken van font attributes kan wel worden aangezet, dan wordt het goed uitgesproken. Dit is een ontwerpkeuze van NVDA (en andere screen readers) die wij hier volgens mij niet ter discussie moeten stellen. Ik schrijf wel eens "oppervlakte: 25 m^2", ik weet niet of dat ook voor andere groepen handiger zou zijn maar het lijkt me voor een goedziende lezer minder mooi. Dus ik denk dat we gewoon sub / sup moeten gebruiken, iedere redelijk opgeleide lezer begrijpt dat "oppervlakte: 25 m2" een oppervlakte van vijfentwintig vierkante meter voorstelt. Alleen als sub / superscript functionele informatie overbrengt zou dit anders kunnen zijn maar waarschijnlijk zou informatie in zo'n opmaakeigenschap verstoppen sowieso in strijd met WCAG zijn.

**Comment by gofix** [comment]
Over `aria-describedby` bij een dergelijke footnootlink: omdat de 'linktekst' (in het voorbeeld `1`) eigenlijk niks 'zegt', lijkt me het toch wel beter.
https://www.digitoegankelijk.nl/onderwerpen/lijst-met-alle-eisen/2.4.4:
> "Schrijf linkteksten zo dat het linkdoel uit de tekst zelf of de context van de link afgeleid kan worden."

of vinden we in dit geval dat het linkdoel prima uit de context van de link afgeleid kan worden...?

**Comment by gofix** [comment]
Met 'groene cijfers' (die geen link zijn) heb ik persoonlijk niet zo'n moeite, ik weet niet of anderen dan @tfrijsewijk dit wellicht ook verwarrend vinden?

**Comment by gofix** [comment]
Mij is nu nog even niet duidelijk of de 'terugverwijzing' (naar de tekst waarvanuit naar de voetnoot verwezen werd) nu wel of niet gewenst is. Zoals dus op WIKIpedia wordt gedaan. Persoonlijk vind ik dat wel een must, eigenlijk.

**Comment by gofix** [comment]
Zoals vanmorgen besproken op de conference call: 
- `aria-describedby` is niet nodig;
- de link naar de voetnoot moet nog sterker gaan lijken op hoe wikipedia het doet, dus met vierkante haken (dus: `[2]`): dit is wat men in wetenschappelijke/juridische documenten gewend is, en wat de gemiddelde gebruiker ook zal herkennen van wikipedia.
- de teruglink (eventueel meerdere) moet expliciet worden opgenomen, eigenlijk gewoon vrijwel zoals wikipedia het doet: het huidige voorstel van @tfrijsewijk is volgens @timveld niet voldoende duidelijk. Een (eventueel visueel verborgen) linktekst als "terug naar leestekst" is essentieel.

Afgesproken is dat we een verder uitgewerkt voorstel inchecken, @daverhelst  pak jij dat op?

**Comment by bramhoosemans** [comment]
> Met 'groene cijfers' (die geen link zijn) heb ik persoonlijk niet zo'n moeite, ik weet niet of anderen dan @tfrijsewijk dit wellicht ook verwarrend vinden?

Ik vind dit ook verwarrend. We hanteren het principe dat 'grasgroen' een interactief element duidt. Volgens mij zouden we onderscheid moeten maken tussen superscript `[2]` groen met link naar voetnoot en de cijfers bij de voetnoot gewoon zwart.

**Comment by gofix** [comment]
@daverhelst waarom is die tabel van accordion nu zo gek geworden: https://percy.io/dso-toolkit/dso-toolkit/builds/4329678

**Comment by gofix** [comment]
Inmiddels is het tussentijdse foutje met het paperclipje weer verdwenen (werd wsl. veroorzaakt door wat branchitis).

**Comment by gofix** [comment]
Testbaar op https://dso-toolkit.nl/_530.bijzondere-tekstverbeeldingen/components/detail/footnotes.html

Waar ik nog over twijfel: we linken TERUG naar de `<sup>`, en dat betekent dat je toetsenbord-navigerend daarna opnieuw langs de link naar de voetnoot komt. Ik weet niet of dat erg is. Wat vind jij @timveld

**Comment by gofix** [comment]
't is wel precies hoe het bij wikipedia werkt, dus ik neig ernaar dit ticket nu te accepteren...https://nl.wikipedia.org/wiki/Willem_van_Oranje#cite_ref-29

**Comment by gofix** [comment]
1 ding nog: we halen `aria-label` nog even weg.
