### ISSUE TITLE
.dso-attachments teller ook buiten de accordion gebruiken

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#532]
De bijlage indicator wordt naast de accordion (https://github.com/dso-toolkit/dso-toolkit/issues/457) ook toegepast in een tabel. Zie bijgevoegd screenshot.

In de gebruikerstoepassing is dit een 'component' die nu stuk gaat, omdat .dso-attachments enkel op de accordion mag worden gezet. We zouden dit graag generiek(er) kunnen gebruiken.

![Screenshot 20200204 0001](https://user-images.githubusercontent.com/598735/74157352-6c697c80-4c18-11ea-8256-26a15825404f.png)

**Comment by PieterVerheij** [comment]
@bramhoosemans In welke context zou je dat willen gebruiken? Of wil je gewoon een los componentje `.dso-attachments` wat je overal kan inzetten? En wil je dan ook altijd de paperclip erbij?

**Comment by bramhoosemans** [comment]
Ik weet niet of het gelijk een 'component' moet worden met eigen documentatie e.d. maar de wens is om het ook op andere plekken te kunnen gebruiken. dso-attachments is nu enkel te gebruiken in de accordion.

Het componentje zou dat altijd een teller + paperclip icoon zijn.

Klopt dat @TonD83 ?

**Comment by PieterVerheij** [comment]
Ok, we trekken de styling van `.dso-attachments` uit de context van de accordion en zorgen ervoor dat het paperclipje er automagisch bij komt.

**Comment by PieterVerheij** [comment]
@bramhoosemans is hij standaard altijd grijs-60/#666 of standaard zwart en in de accordion grijs-60 en wit op de paarse achtergrond?

**Comment by bramhoosemans** [comment]
@PieterVerheij Zover ik weet is hij standaard grijs #666 en in de accordion wit #fff op de paarse achtergrond.

**Comment by PieterVerheij** [comment]
@bramhoosemans Dus ook buiten de context van de accordion #666?

**Comment by bramhoosemans** [comment]
> @bramhoosemans Dus ook buiten de context van de accordion #666?

Ja.

**Comment by PieterVerheij** [comment]
@bramhoosemans te zien op https://www.dso-toolkit.nl/_532.dso-attachments-teller-ook-buiten-de-accordion/components/detail/attachments.html : lekker minimale component ;)

**Comment by bramhoosemans** [comment]
@PieterVerheij Ziet er prima uit :)

**Comment by gofix** [comment]
Hmmm. Eigenlijk is dit een breaking change. Want: https://github.com/dso-toolkit/dso-toolkit/pull/559/files

`<span class="dso-attachments">` moet blijkbaar nu genoteerd worden als `<span class="dso-attachments-counter">`

Dit kwam naar boven bij het reviewen en testen van #523

**Comment by gofix** [comment]
Willen we dat wel @daverhelst , @tfrijsewijk , @PieterVerheij 
Of trekken we dit nog even recht in #523

**Comment by gofix** [comment]
Intern besproken: we lossen dit op (in/na #523). En dus is de komende release niet meer breaking.
