### ISSUE TITLE
Pdf-bestanden documentatie

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#550]
Pdf-bestanden documentatie toevoegen aan de toolkit.

**Comment by bramhoosemans** [comment]
https://dso-toolkit.nl/_550-pdf-documentatie/docs/pdf-bestanden.html

**Comment by gofix** [comment]
Hier wordt geclaimd:
> Een bestand opslaan als PDF/A is niet nodig voor toegankelijkheid. Opslaan als PDF 1.7 is voldoende. Al jarenlang adviseert de overheid om voor toegankelijkheid pdf-bestanden op te slaan als PDF/A. Maar dat is intussen achterhaald.

https://www.theinternetacademy.nl/artikelen/stop-met-pdfa-voor-toegankelijke-bestanden

Niet een bijzonder sterk artikel, maar toch de moeite waard om even in het achterhoofd te houden.

**Comment by timveld** [comment]
Inderdaad geen sterk stuk en een paar van de genoemde PDF/A nadelen lijken me discutabel, maar hij heeft zeker gelijk dat pdf/a niet nodig is om een toegankelijk resultaat op te leveren. Het gaat er om dat het document op de juiste manier getagged is.

**Comment by gofix** [comment]
Zoals vanmorgen besproken op de conference call: als niemand meer iets op of aan te merken heeft op dit stuk documentatie, is het klaar. Al is het zo dat de inzichten over toegankelijkheid van PDF wel nogal in beweging zijn.
