### ISSUE TITLE
Nieuw component: Tree view uit RTR

### ISSUE THREAD

**Issue by DHvD-Michael** [dso-toolkit/dso-toolkit#552]
Binnen de Registratie Toepasbare Regels (RTR) wordt een "tree view" gebruikt als navigatie. De "tree view" wordt ook bij de navigatie van de DSO-toolkit gebruikt. 
De verwachting is dat de "tree view" ook bij een aantal beheer applicaties binnen DSO gebruikt gaat worden. 

De huidige implementaties hebben verbeterpunten nodig op Digitoegankelijkheid. 
Het nieuwe "tree view" component draagt hierin bij. 

Beoogd is om een basisopzet te maken en indien nodig visuele varianten voor DSO-toolkit en RTR. 
![Voorbeeld tree view in RTR](https://user-images.githubusercontent.com/4227175/74665946-e5308180-51a0-11ea-9cc9-a8d6c181bfa1.png)

**Comment by smvandermeulen** [comment]
@timveld We hebben een opzet gemaakt voor de Tree-view, deze is te zien op https://core.dso-toolkit.nl/_552-Tree-view-web-component/?path=/story/tree-view--tree-view

Toetsenbordgebruik:
- klikken en daarna Tab zorgt voor de focus in het component
- pijltje omhoog/omlaag wandelt door de items in de tree
- pijltje naar rechts opent een gesloten node
- pijltje naar rechts selecteert eerste item van een open node
- pijltje naar links sluit een open node
- pijltje naar links selecteert voorgaande item van een gesloten node (twijfelachtig of dat gewenst is)
- spatie opent/sluit een node

NVDA leest voor:
- item niveau
- item tekst
- item expanded/collapsed
- item positie in set

Om een of andere reden leest NVDA nog niet altijd de expand/collapse acties voor.

Extra: Als je het item "bouwwerken" opent, verschijnt er een spinner en worden de kind-items na 2,5 seconden ingeladen. Dit mimickt een async API call. 

Wat vind jij van de toegankelijkheid?

**Comment by smvandermeulen** [comment]
@timveld Lukt het om naar de toegankelijkheid te kijken? Ik wil graag weten of we hiermee verder kunnen.

**Comment by timveld** [comment]
Dit werkt goed en bij mij wordt collapsed / expanded keurig voorgelezen. 

De toetsenbord interactie behoeft wel verbeteringen. Ik stel voor: 
* Pijl links: deze werkt nu alleen als de focus op een geopende node staat. Echter als de focus op een child van een uitgeklapte node staat, moet hij ook de parent sluiten. Als hij op een gesloten root node staat moet hij niets doen (het huidige gedrag is in dat geval een duplicatie van pijl honhoog, dat komt de consistentie niet ten goede). 
* Pijl rechts moet alleen gebruikt worden om een gesloten node te openen, verder niets (dus ook geen alias voor pijl omlaag). 

Wat betreft de spinner: is die wel echt nodig? Ik weet niet hoe deze treeview gebruikt wordt maar als je 2 seconden nodig hebt om subitems te laden denk ik als simpele UX-er "kom op jongens, maak je caching in orde". Ik vind de spinner zo vrij verwarrend. 
Maar als het echt moet zou ik er een aria alert "laden..." geven. Als het laden is voltooid kun je dat afleiden aan het opengaan van de node (NVDA zegt dan netjes uitgevouwen) dus een afzonderlijke alert bij voltooing lijkt me niet nodig. 

Verder mooi ding, wat mij betreft de release in met deze kleine aanpassingen.

**Comment by gofix** [comment]
Over de spinner: als we de aanwijzingen volgen die in de documentatie staat van progress-bar / progress-indicator (zie met name https://dso-toolkit.nl/27.4.0/components/detail/progress-bar.html) lijkt een spinner voor een dergelijke actie die een 'onbepaalde tijd' toch wel gerechtvaardigd. Natuurlijk heb je gelijk @timveld dat 'idealiter' het ophalen van de data om uit te klappen niet al te lang zou moeten duren, maar je weet het nooit natuurlijk.

Als we nu iets anders gaan doen (wat jij voorstelt: aria alert "laden..."?) moeten we dat wel ook echt als werkvorm gaan vastleggen. 

Over spinners anders dan de bestaande progress-indicator: elders loopt nu ook een brainstorm over een vorm a la https://getbootstrap.com/docs/4.5/components/spinners/#buttons. Daar geef jij aan @timveld "Als ik op de verzenden knop druk en de spinner verschijnt daar in, leest de screen reader dit waarschijnlijk automatisch voor (dan hoef je geen expliciete aria alert te geven). In ieder geval de visuele spinner wordt door een screen reader genegeerd".

Al met al zou ik nu adviseren om de officiële "progress indicator" te blijven voeren. En kunnen we elders in refinement overleg, of DSO zelf in UX overleg, bepalen wat te doen met 'andere' spinner-achtigen...

**Comment by DHvD-Michael** [comment]
In aanvulling, er hebben al optimalisaties plaatsgevonden voor de treeview services bij implementatie. De verlaging naar een paar seconden laadtijd is hierbij een significante verbetering van deze services. 
Qua use-case: de treeview haalt niet enkel sub-items op. De sub-items worden gecompileerd uit verschillende data-bronnen. Zodoende hebben we een laad-scenario te pakken. 

Er kan geen progress bar worden gebruikt in deze situatie: Er is geen signaal wat teruggegeven kan worden in hoeverre de treeview gegenereerd is. Een progress bar geeft daarmee geen ander percentage weer. De spinner (progress-indicator) is zodoende noodzakelijk.

In een ver verleden hebben we afgestemd over de aria alert tekst. "Een moment geduld a.u.b." was hierbij acceptabel. De laadtijden waren destijds wel langer. 

Ik ben het met Ad eens dat we een werkvorm moeten vastleggen als deze aria alert tekst wordt omgezet naar "Laden..."
@timveld Laten we hier binnenkort even samen naar kijken.

**Comment by smvandermeulen** [comment]
@timveld We hebben de toetsenbord interactie aangepast, zou je dat nog een keer willen bekijken? 

Voor de spinner geldt nu dat deze niet standaard wordt getoond bij 'bijladen' van items in de tree view. De implementator kan er voor kiezen om de "loading" property van het tree item op `true` te zetten tijdens het inladen. Is de onderliggende API snel genoeg dan kan volstaan worden met enkel de node alvast op "open" is `true` te zetten. 
Dit is nu uitgewerkt voor de nodes "bouwwerken" (snel laden (max 500ms?)) en "complexen" (langere laadtijd).

Tenslotte: bij een tree item kunnen nu icons worden geplaatst, zoals gevraagd bij RTR.

**Comment by timveld** [comment]
##Verzoek snelle test spinner
Ik weet niet precies wat veranderd is maar met NVDA krijg ik nog steeds niets van de spinner mee. Zou je even kunnen zorgen dat aria-busy="true" op het item (complexen) staat zo lang de spinner te zien is en verdwijnt als de spinner klaar is? Ik moet dit testen maar denk dat dit het probleem helemaal gaat oplossen.
##Bug en nadere wensen keyboard
* Als ik op een node op niveau 2 sta en ik druk pijl links, vouwt de parent nog niet samen. Bij leafs gaat dat wel goed.
* Met home en end moet naar het eerste resp laatste item gesprongen kunnen worden. Dat is een belangrijke functie.
* Page up / down is in grotere treeviews ook belangrijk. Dit zou ongeveer het aantal items wat op het scherm past omhoog / omlaag moeten bewegen, maar dat hangt af van de scaling en dat wordt een redelijk ingewikkelde discussie. Zullen we voorlopig standaard 10 items tegelijk doen? Simpel, consistent en lijkt me ook bij grotere zoom nog voldoende werkbaar.
* Ik weet niet hoe groot de treeview wordt, maar in lange lijsten (denk aan een lijst met alle landen) is first letter navigation erg belangrijk. Dat wil zeggen, dat bij het indrukken van een letter het eerstvolgende item geselecteerd wordt dat met die letter begint. Lijkt me ook niet heel moeilijk te implementeren.

**Comment by smvandermeulen** [comment]
@timveld Ik heb eerder een aantal van je aanwijzingen m.b.t. de toetsenbord interactie doorgevoerd. Je laatste opmerking over pijl links kan ik wat moeilijk plaatsen, omdat ik dacht dat je juist dit gedrag wilde. Ik heb de tree view van Windows Explorer erbij gepakt en twijfel nu toch over een aantal zaken. Je stelt:

> Pijl rechts moet alleen gebruikt worden om een gesloten node te openen, verder niets (dus ook geen alias voor pijl omlaag).

In Windows Explorer gebeurt dit bijvoorbeeld wel (en ook in de Treeviewer proto v4). 

> Pijl links ... Echter als de focus op een child van een uitgeklapte node staat, moet hij ook de parent sluiten. 

Windows Explorer brengt eerst de focus naar parent en bij volgende pijl link sluit die node (gebeurt ook in de Treeviewer proto v4).

Er lijken nu ook nieuwe specs bij te komen (Home, End, PageUp, PageDown, letter navigatie), ik vind die super interessant maar heb ze dan liever allemaal gespect. @MichielDHVD Kan jij helpen om de specs voor de keyboard interactie van de tree view vast te leggen?

**Comment by timveld** [comment]
Zie dat ik een laatste update gemist heb...
Toetsenbordinteractie werkt nu foutloos.
Aria-busy doet nog niets, op welk element wordt die precies gezet? Zou volgens mij op het treeview item moeten zijn. 
Als dat al zo is moet ik een andere oplossing onderzoeken.
Dit heeft overigens geen hoge prioriteit dus zeker releasen als dat nog niet gebeurd is.
