### ISSUE TITLE
8px onder menubalk in conflict met banner image. 

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#553]
Bij het herontwerp van de menubalk in release 9.7 is de 8px margin verplaats van onder de letter naar onder de underline van het gehele menu. 

Dit zorgt ervoor dat bij wanneer er een dso-banner plus image gebruikt wordt er een raar beeld ontstaat. 

<img width="1213" alt="Screen Shot 2020-02-18 at 08 40 46" src="https://user-images.githubusercontent.com/36912722/74714283-8e6f8a00-522a-11ea-9484-04b5cfd397c6.png">

Daarom moet de 8px wit ruimte en de lijn onder de header wegvallen wanneer het opvolgende component een dso-banner is zodat er geen witruimte en scheiding is tussen banner en image. 

Het resultaat zou er zo moeten uitzien. 

<img width="1176" alt="Screen Shot 2020-02-18 at 09 00 08" src="https://user-images.githubusercontent.com/36912722/74715714-4d2ca980-522d-11ea-8825-5b5e5df04a42.png">

@tfrijsewijk @PieterVerheij  Kan dit zo specifiek ingesteld worden als componenten elkaar opvolgen? Wat is er mogelijk?

**Comment by DjangoBlok** [comment]
Wat mij betreft halen we die 8px overal weg. Is dat niet logischer?
Waar kom je dan in de knoop?

**Comment by MichielDHVD** [comment]
Het is niet zo zeer dat we in de knoop komen. 

Het gaat meer over hoe we onze pagina's qua margins willen opbouwen. 
Zijn margin-bottoms dominant. De we geven componenten geen margin-top mee. Dan zou een header zonder margin-bottom niet kunnen. 

Maar het is een goede vraag. Valt onder een van de mogelijke oplossingen.

**Comment by MichielDHVD** [comment]
Dit issue wordt meegenomen in issue #500 . Daarom wordt deze gesloten.
