### ISSUE TITLE
Modal aanpassingen

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#554]
1. Dropshadow toevoegen
Om een gevoel van diepte te geven mag de volgende dropshadow worden toegevoegd:
box-shadow: 0 8px 24px 0 rgba(25,25,25,0.40);

2. Hoverstate kruisje 
Huidige hoverstate is een cirkeltje wat een restant is van een verouderde stijl. Voor de nieuwe hoverstate mag het cirkeltje verwijderd worden. Alleen het handje met vinger blijft over voor de hover state. Dit is in lijn met de andere componenten met kruisjes (description, info/toelichting, banner en group files).

3. De volgende variaties moeten beschikbaar zijn. 
![Modals2](https://user-images.githubusercontent.com/36912722/74833106-1f249380-5319-11ea-883d-6200afd19f92.png)

Single-cancel en confirm mogen vervallen in de toolkit als variatie. 
Verder bij steps is het gewenst dat behalve de twee secundaire knoppen aan de rechterkant er ook een variatie komt waar er een secundaire en primaire knop staan. Zie variatie 3 in de afbeelding. 

4. Tab volgorde
Op dit moment gaat bij voorbeeld bij voorbeeld 2 de focus van het sluiten knopje naar de primaire knop en dan pas de annuleren knop. 
In de discussie rondom de focus volgorde van knoppen is besloten de visuele volgorde te hanteren. Dit betekent dat de knoppen links altijd eerder de focus krijgen dan de knoppen die rechts staan. 
Voor modal voorbeeld geldt dus sluiten -> annuleren -> Opslaan

**Comment by PieterVerheij** [comment]
@MichielDHVD Als de margins niet aangepast zijn, kan deze op Ready?

**Comment by gofix** [comment]
Belangrijke change, behalve CSS, is dat de [Annuleren]-knop in al deze modals in de toolkit van volgorde zijn gewijzigd. Strikt genomen dus een wijziging in markup-voorschriften, en dus BREAKING. Tenzij dit eigenlijk altijd al de bedoeling was, en dit eigenlijk alleen maar een correctie is van wat hier wordt getoond.

**Comment by gofix** [comment]
@daverhelst controleer even hoe dit tot nu toe werd gedemonstreerd, om te bepalen of deze change breaking is of niet.

**Comment by gofix** [comment]
Aangezien de CSS ook de 'andersom'-volgorde gewoon honoreert, is dit NIET breaking.

**Comment by gofix** [comment]
Zie bv. https://dso-toolkit.nl/_554.modal-component/components/detail/modal--modal-close.html
@MichielDHVD is dit wat je van de change verwacht?

**Comment by bramhoosemans** [comment]
- 1px border mag weg :)
- Tab focus gaat na de laatste actie in de modal verder in de achtergrond... is dat de bedoeling?
- Verder valt het mij op dat de H2 hier ook een line-height van 26.4px heeft; volgens mij iets wat nog uit Bootstrap komt. Maar anders moeten we een apart issue aanmaken om naar de line-height van headings te kijken.

**Comment by gofix** [comment]
> Tab focus gaat na de laatste actie in de modal verder in de achtergrond... is dat de bedoeling?

Dat lijkt me niet, sterker nog, het is echt fout als dit in een implementatie gebeurt, ik heb hier al vaker bij klanten oplossingen voor moeten realiseren. Betreft WCAG succescriterium 2.4.3 (zie ook  https://www.digitoegankelijk.nl/onderwerpen/lijst-met-alle-eisen/2.4.3).

Maar... die oplossingen bestonden er altijd +/- uit dat met scripting de elementen onder/achter de modal een tabindex -1 krijgen (en dat bij het sluiten van de modal de oorspronkelijke tabindex weer wordt teruggezet). Dat is iets wat dus wellicht in een toelichtende tekst zou moeten.

**Comment by gofix** [comment]
Zie ook https://www.w3.org/TR/wai-aria-practices/#dialog_modal
Het is me nog niet zomaar duidelijk of door het zetten van `role=dialog` en/of `aria-modal=true` we verlost worden van de noodzaak met aanvullende scripting te werken. Eerlijk gezegd zou ik willen voorstellen het (toetsenbord-)toegankelijkheidsaspect van de modal naar in een eigen issue te behandelen, want daar zijn we hoogstwaarschijnlijk niet snel over uitgepraat.

**Comment by gofix** [comment]
@daverhelst de opmerkingen over styling-details kun je prima verwerken natuurlijk. Please do.

**Comment by daverhelst** [comment]
@bramhoosemans de line-height lijkt inderdaad vanuit bootstrap te komen, die zetten namelijk het volgende:

`$headings-line-height:    1.1 !default;`

We kunnen deze variabele eenvoudig overschrijven, maar dan krijgt elke header dezelfde line-height. Wat we ook kunnen doen is dit per header instellen. Hoe dan ook stel ik voor om hier inderdaad even over na te denken en een nieuw issue aan te maken.

**Comment by bramhoosemans** [comment]
> Hoe dan ook stel ik voor om hier inderdaad even over na te denken en een nieuw issue aan te maken.

Done. https://github.com/dso-toolkit/dso-toolkit/issues/606
