### ISSUE TITLE
Iconen update

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#563]

**Comment by Anto1nette** [comment]
Hierbij de set iconen. De uitlijning van het vinkje in het status-success-outline icoon was verschoven, deze heb ik goed gezet (dank aan Bram die t opmerkte). Er zijn een aantal iconen bijgekomen voor Django en de overige iconen zijn groter gemaakt zodat ze beter uitlijnen in tabellen, het gaat voorlopig om: exlamation, pencil, paperclip, redo, download.

Daarnaast moet het 'sort' icoon voor tabellen waarschijnlijk losse elementen worden, dus driehoekje naar boven los icoon en driehoekje naar beneden los icoon. Hoe doen jullie dit technisch in de achterkant, zijn dit losse iconen @PieterVerheij ? Voldoet het dan om ze apart aan te leveren?

Ze zitten er nu nog niet bij ik kan dat morgen nog aanleveren mocht dat nodig zijn (ben vanmiddag afwezig, morgen na de lunch weer aanwezig)

[20202702_iconen_update.zip](https://github.com/dso-toolkit/dso-toolkit/files/4261605/20202702_iconen_update.zip)

**Comment by PieterVerheij** [comment]
Hi, @Anto1nette . Elke icoon variant is een los icon, alleen kleurvarianten niet. Maar als het gewoon een kwestie is van iconen roteren, kunnen wij er hier ook wel een slinger aangeven in Illustrator.

**Comment by Anto1nette** [comment]
Ah, duidelijk. Maar t gaat om onderstaand icoon, deze moet denk ik los getrokken worden toch? Deze zit al in de vorige set maar niet als twee aparte iconen, moet ik dan nog aanleveren los van elkaar?

<img width="90" alt="Screenshot 2020-02-27 at 13 47 01" src="https://user-images.githubusercontent.com/1033595/75446459-c03dca80-5967-11ea-8af8-826f3ccbeed7.png">

**Comment by daverhelst** [comment]
Na overleg met @PieterVerheij lever deze inderdaad maar los van elkaar aan
