### ISSUE TITLE
Table redesign

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#564]
**Table redesign**

Change
- Header Asap-SemiBold 16px line-height 24px `#191919`
- Header border-bottom 1px `#666666`
- Cel Asap-Regular 16px line-height 24px `#191919`
- Cel border-bottom 1px `#cccccc`
- Links met underline weergeven (normale tekstlink) / op grijze achtergrond `#191919`
- Active state van een rij heeft achtergrond `#E5E5E5`

Add
- Column uitlijning links, rechts of midden.

Remove
- Geen rij kleuren meer beschikbaar maken (contextual classes).
- Verwijder mogelijkheid om zebra stripping aan te brengen.
- Verwijder mogelijkheid condensed tabellen weer te geven

Specificaties
[Tables.zip](https://github.com/dso-toolkit/dso-toolkit/files/4262373/Tables.zip)

![Tables](https://user-images.githubusercontent.com/598735/75457199-89be7a80-597c-11ea-8cfd-0eacfa68d10e.png)

**Comment by PieterVerheij** [comment]
NB. in overleg met @bramhoosemans besloten het afbreken van lange tekst in een cel onder te brengen in #491 (standaard tabel responsive maken).

**Comment by PieterVerheij** [comment]
https://dso-toolkit.nl/_564.Table-redesign/components/detail/table--default.html

**Comment by bramhoosemans** [comment]
@PieterVerheij zou je ook een voorbeeld kunnen toevoegen met uitlijning links, rechts of midden?

**Comment by PieterVerheij** [comment]
@bramhoosemans Bedoel je andere dan deze?
![image](https://user-images.githubusercontent.com/25430835/77627469-40475800-6f47-11ea-8c2f-2a22cb25a930.png)

**Comment by bramhoosemans** [comment]
Ik had beter moeten kijken 👍 Zouden we de verschijningsvormen niet op één pagina kunnen zetten, scheelt ook weer klikken/navigatie-items in de toolkit.

Component ziet er wat mij betreft goed uit :)

**Comment by gofix** [comment]
> Zouden we de verschijningsvormen niet op één pagina kunnen zetten, scheelt ook weer klikken/navigatie-items in de toolkit.

Daar hebben we het vorige week op de videoconference-standup over gehad, @bramhoosemans, het punt dat we naar een heldere structuur moeten in de toolkit: wanneer wel opsplitsen in subs in de navigatie, wanneer niet. Maar ook: wat zetten we in documentatie, welke voorbeelden halen we daarbij aan in de iframes, en voor welke moet de bezoeker dan maar gewoon naar het 'component' tabblad kijken. Etc.

Daarvoor zouden we een los issue inschieten, volgens mij.

**Comment by bramhoosemans** [comment]
@gofix Klopt, die is er ook https://github.com/dso-toolkit/dso-toolkit/issues/604. Alleen niet meer naar verwezen in deze story.

**Comment by gofix** [comment]
Na overleg: we zetten deze even door naar volgende release.
Er is geen team dat hier nu door vastloopt.

NB: @PieterVerheij ik heb de relevante changes uit jouw eerdere branch gecherrypicked naar een nieuwe schone branch die ik vanaf een recente master geboren heb laten worden, omdat de start van jouw branch niet helemaal clean was. 

Branch https://github.com/dso-toolkit/dso-toolkit/tree/%23564.Table-redesign verwijder ik, werk gaat verder in https://github.com/dso-toolkit/dso-toolkit/tree/%23564.table-redesign-v2

**Comment by gofix** [comment]
@PieterVerheij nu ik https://github.com/dso-toolkit/dso-toolkit/pull/612 heb gemerged, is deze eigenlijk ook klaar toch? Verdient dan nog wel een regeltje in changelog.

Is branch `#564.table-redesign-v2` nog relevant nu?

**Comment by PieterVerheij** [comment]
@gofix 
nu ik #612 heb gemerged, is deze eigenlijk ook klaar toch? Verdient dan nog wel een regeltje in changelog.
Klopt, ik zal het aanpassen

Is branch #564.table-redesign-v2 nog relevant nu?
Nee, niet meer. Ik zal hem verwijderen.

**Comment by gofix** [comment]
https://github.com/dso-toolkit/dso-toolkit/commit/b9133f9554c1c9a6ca6e4d15760c466a9d346276
