### ISSUE TITLE
Table filter

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#567]
In een tabel kan ook gefilterd worden op basis van gebruikersinvoer doormiddel van een zoekveld boven de tabel. Er wordt direct automatisch gefilterd in de tabel.

Voorbeeld https://assets.cms.gov/resources/framework/3.4.1/Pages/#datatablessort

Specificaties
[Table-filter.zip](https://github.com/dso-toolkit/dso-toolkit/files/4265878/Table-filter.zip)

![Table-filter](https://user-images.githubusercontent.com/598735/75521460-1b26fe80-5a08-11ea-83c8-70c5ce061844.png)

**Comment by PieterVerheij** [comment]
@bramhoosemans de searchbar is 224px breed. Zit daar een logica achter en moet hij altijd deze breedte hebben?

**Comment by bramhoosemans** [comment]
@PieterVerheij Ik ben aan het graven, maar kan me niet bedenken waarom deze een breedte van 224px moet hebben. Wat stel jij voor? x aantal columns?

**Comment by PieterVerheij** [comment]
Uitgaand van de minimale schermbreedte op mobiel (320px) en dan de juiste margins eraf? Dan kom je op al een breedte die breder is dan die 224px en dat lijkt mij meer dan voldoende?

**Comment by bramhoosemans** [comment]
Dus wel een vaste breedte vanuit de toolkit? In dat geval, met 320px met 16px margins aan beide zijde, kom je op 288px breedte.

**Comment by PieterVerheij** [comment]
Lijkt mij prima, toch?

**Comment by bramhoosemans** [comment]
Ik heb geen tegen argumenten; laten we dit zo doen :)

**Comment by PieterVerheij** [comment]
@bramhoosemans Behold the table filter!
https://www.dso-toolkit.nl/_567.Table-filter/components/detail/table-filter--default.html
https://www.dso-toolkit.nl/_567.Table-filter/components/detail/table-filter--no-results.html

**Comment by bramhoosemans** [comment]
Volgens mij ontbreekt de focus state nog van het zoekveld :) Verder ziet het er goed uit!

**Comment by PieterVerheij** [comment]
Wel als je er in klikt, toch? Of wil je hem ook specifiek getoond hebben?

**Comment by bramhoosemans** [comment]
> Wel als je er in klikt, toch? Of wil je hem ook specifiek getoond hebben?

Bij focus in het zoekveld verwacht ik dezelfde styling als invoervelden (2px border). Dit hebben we laatst ook gefixt in de zoekbalk https://dso-toolkit.nl/10.1.0/components/detail/search-bar.html

**Comment by PieterVerheij** [comment]
Ah, die searchbar wijziging zat nog niet in deze branch. Komt goed!

**Comment by gofix** [comment]
Zoals ook al opgemerkt in de PR, ik snap het `role="row"` niet zo op een `<tr>` -> https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Row_Role

> The first rule of ARIA use is you can use a native feature with the semantics and behavior you require already built in, instead of re-purposing an element and adding an ARIA role, state or property to make it accessible, then do so. Employ the HTML <table> element instead of the ARIA role of table whenever possible.

Oftewel: volgens mij hoef je de `role` attributen om tabel-onderdelen te duiden alleen toe te passen als je een tabel maakt met iets anders dan een `<table>`. Of begrijp ik het nu helemaal verkeerd, @timveld ?

**Comment by gofix** [comment]
Ik lees overigens zojuist:

> A relevant use case for the ARIA table role is when the native semantics of a table are overridden by CSS's display property, such as by `display: grid`. In this case, you can use the ARIA table roles to add the semantics back in.

Maar... da's niet het geval toch?

**Comment by gofix** [comment]
Volgens mij ziet het er nu goed uit, zowel qua code als qua wat eruit komt:
- https://www.dso-toolkit.nl/_567.table-filteren/components/detail/table.html (onderaan)
- https://www.dso-toolkit.nl/_567.table-filteren/components/detail/search-bar.html

Mee eens @bramhoosemans , dan gaan we 'm mergen...

**Comment by timveld** [comment]
* Knopje "zoekopdracht legen" Kan dat niet beter "zoekopdracht wissen" worden? (kwestie van conventies)
* Het zoekknopje staat visueel links van het zoekveld, ik verwacht het knopje rechts (maar ik weet niet precies wat de conventies hier zijn of wat vergrotingsgebruikers hiervan denken) non-visueel is het verder in orde.
