### ISSUE TITLE
Table sorteren

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#568]
Bij sortering wordt standaard de eerste kolom gesorteerd op zowel A-Z als 0-100. Sorteermogelijkheden worden aangegeven met een icoon naast de kolomkoppen. Er kan slechts op één kolom tegelijk gesorteerd worden.

![Table-sort](https://user-images.githubusercontent.com/598735/75521702-925c9280-5a08-11ea-81af-39ecfdae170d.png)

**Comment by PieterVerheij** [comment]
@bramhoosemans Staat de button direct naast de label tekst of zit er 8px tussen?

**Comment by bramhoosemans** [comment]
Direct naast het label. Zie hier een snelle export:
[Table.zip](https://github.com/dso-toolkit/dso-toolkit/files/4374439/Table.zip)

**Comment by PieterVerheij** [comment]
Okidoki!

**Comment by PieterVerheij** [comment]
@bramhoosemans Actieve sorteer button is #000, anderen #666. Is dat niet een tikje te subtiel? ;)

**Comment by bramhoosemans** [comment]
@PieterVerheij haha de actieve is zelfs #191919, andere #666666. Met het huidige kleurenpallet leek me dit een subtiele oplossing... zonder interactief te lijken of teveel aandacht te trekken.

Antoinette is deze week met vakantie, dus hierbij de gebruikte iconen. Dan worden deze automatisch een keer bijgewerkt bij een iconen update. Download: [iconen.zip](https://github.com/dso-toolkit/dso-toolkit/files/4386044/iconen.zip)

**Comment by PieterVerheij** [comment]
@bramhoosemans Behold the sort buttons!
https://www.dso-toolkit.nl/_568.Table-sorteren/components/detail/table-sortable--default.html
https://www.dso-toolkit.nl/_568.Table-sorteren/components/detail/table-sortable--descending.html

(note: structuur in de navigatiebalk van de toolit moet nog uitgewerkt worden)

**Comment by bramhoosemans** [comment]
- Zouden we de gehele `th` klikbaar kunnen maken? Zoals https://www.w3.org/TR/wai-aria-practices/examples/grid/dataGrids.html
- De active state veranderen we nog in https://github.com/dso-toolkit/dso-toolkit/issues/511, toch?

**Comment by PieterVerheij** [comment]
- Zouden we de gehele th klikbaar kunnen maken? Zoals https://www.w3.org/TR/wai-aria-practices/examples/grid/dataGrids.html
Niet de hele TH, maar we kunnen wel het losse label en de button samenvoegen tot een reguliere tertiaire button (misschien hebben we dan ook gelijk dat wrapping probleem opgelost ;))

- De active state veranderen we nog in #511, toch?
Ja, dat moet daar opgelost worden.

**Comment by PieterVerheij** [comment]
@bramhoosemans zie https://www.dso-toolkit.nl/_568.sortable-table/components/detail/table.html

Ik heb in de <TH> label en button samengevoegd. Gevolg is wel dat er meer marge zit tussen de tekst in knop:

**Comment by bramhoosemans** [comment]
Nice! Ik ben er helemaal blij mee :)

**Comment by bramhoosemans** [comment]
@timveld Zou je kunnen beoordelen of de opzet bij 'sortable ascending' en 'sortable descending' goed is? Je vind ze onderaan de pagina https://www.dso-toolkit.nl/_568.sortable-table/components/detail/table.html

**Comment by gofix** [comment]
@PieterVerheij rebase deze changes even op `#567.table-filteren`, want nu zitten in deze branch die onnodige `scope=row` zaken nog.

**Comment by PieterVerheij** [comment]
@timveld zou je willen kijken naar de sortable tables: https://github.com/dso-toolkit/dso-toolkit/issues/568#issuecomment-610267660 ?

**Comment by timveld** [comment]
bij de sorteerbare tabellen hebben de knoppen alleen de kolomtitel als label, ik hoor dus "naam knop". Daar blijkt niet uit dat ik de tabel kan sorteren door de knop te activeren. 

Bezwaar van het label veranderen is dat het nieuwe label dan onderdeel wordt van de kolomtitel (die bij navigeren door de tabel steeds wordt uitgesproken). 

Na wat zoeken en experimenteren heb ik de juiste oplossing gevonden: aria-roledescription. Daarmee kun je de beschrijving van het elementtype ("knop") veranderen in wat anders. 
Als role description stel ik voor "sorteer oplopend knop" resp "sorteer aflopend knop". 

Deze oplossing lijkt met alle screen readers (inclusief Apple) goed te werken, behalve met combinatie Jaws / Edge (dat is een bug die ik rapporteer want met NVDA in edge gaat het wel goed) Een oude JAWS versie ondersteunde aria-roledescription nog niet maar ook in dat geval is de site wel te bedienen (het wordt als gewone knop aangeduid dus je mist alleen de handige hint, er is bovendien geen alternatief voor aria-roledescription)

**Comment by timveld** [comment]
Nog een punt: sommige tabellen krijgen aria-role grid. Waarom is dat precies nodig / onvermeidelijk? Kan me herinneren dat we een richtlijn hadden gevonden dat table geen interactieve elementen zouden moeten bevatten (die richtlijn is volgens mij sowieso niet bindend) maar in HTML een table gebruiken en daar dan met Aria een grid van maken lijkt me niet goed, "the first rule of aria is not to use it" en de tabel werkt zonder deze aria role prima. Dus de aria role verwijderen en er eventueel een HTML grid van maken, maar ik kan nu niet meer vinden wat in dit geval de richtlijn is... Grids komen voor zover ik nu lees vooral in beeld als je hele uitgebreide interacties zoals spreadsheets hebt.

**Comment by timveld** [comment]
Tenslotte: 
* In de documentatie wordt afgeraden meerdere niveaus te gebruiken, begrijp ik niet helemaal; donderdag bespreken? De tabel zo simpel mogelijk houden is wel een goede richtlijn
* In sommige tabellen is een kolom met titel "#", niet iedereen zal (direct) weten dat je dit als "nummerteken" moet lezen; beter om er nummer of eventueel ID van te maken
* Taalfout: onder h2 "sorteerbare data-grid" 2 keer is ("In het voorbeeld hieronder is de data is oplopend gesorteerd")

**Comment by PieterVerheij** [comment]
> Na wat zoeken en experimenteren heb ik de juiste oplossing gevonden: aria-roledescription. Daarmee kun je de beschrijving van het elementtype ("knop") veranderen in wat anders.
Als role description stel ik voor "sorteer oplopend knop" resp "sorteer aflopend knop".

@bramhoosemans is hierover nagedacht: wat is het gedrag van de knoppen als er nog geen sorteeraktie op een kolom geselecteerd is (knop met dubbele pijltjes) en de gebruiker klikt op de knop? Wat is dan de eerste sorteeraktie: oplopen selecteren? Want dat zou dan in de `aria-roledescription` moeten staan, @timveld ?

Dus niks geselecteerd: knop met dubbele pijltjes, aria-roledescription="sorteer oplopend knop"
Oplopend geselecteerd: knop met naar boven wijzend pijltje, aria-roledescription="sorteer aflopend knop"
Aflopend geselecteerd: knop met naar beneden wijzend pijltje, aria-roledescription="sorteer oplopend knop"

Wat een beetje wringt, maar uiteindelijk wel klopt: de visuele weergave op de knop en aria-roledescription komen niet met elkaar overeen, maar dat is omdat de visuele weergave de huidige status weergeeft en de aria-roledescription de aktie van de knop beschrijft.

**Comment by bramhoosemans** [comment]
> @bramhoosemans is hierover nagedacht: wat is het gedrag van de knoppen als er nog geen sorteeraktie op een kolom geselecteerd is (knop met dubbele pijltjes) en de gebruiker klikt op de knop?

Nee, hier had ik nog niet bij stil gestaan. Het scenario wat je hierboven beschrijft klinkt mij ook heel logisch (dus eerste sorteeractie = oplopend sorteren).

**Comment by PieterVerheij** [comment]
> Nog een punt: sommige tabellen krijgen aria-role grid. Waarom is dat precies nodig / onvermeidelijk? Kan me herinneren dat we een richtlijn hadden gevonden dat table geen interactieve elementen zouden moeten bevatten (die richtlijn is volgens mij sowieso niet bindend) maar in HTML een table gebruiken en daar dan met Aria een grid van maken lijkt me niet goed, "the first rule of aria is not to use it" en de tabel werkt zonder deze aria role prima. Dus de aria role verwijderen en er eventueel een HTML grid van maken, maar ik kan nu niet meer vinden wat in dit geval de richtlijn is... Grids komen voor zover ik nu lees vooral in beeld als je hele uitgebreide interacties zoals spreadsheets hebt.

@timveld @bramhoosemans `role="grid"` verwijderen en hoogstens een oprmerking over het gebhruik ervan in de documentatie plaatsen?

**Comment by DHvD-Michael** [comment]
@timveld Ik wil graag dat we onze leidraad de tabellen zo zuiver mogelijk houden. Dus als er wel interactieve elementen zijn in een tabel, dat er dan `role="grid"` wordt gehanteerd.
Als we daarnaast nog moeten bepalen of de tabel complex genoeg is (bijvoorbeeld of het genoeg lijkt op een spreadsheet) om een `role="grid"` te gebruiken, dan wordt het voor implementatoren nog lastiger om de leidraad te hanteren.

Deze leidraad is op basis van de WAI-ARIA documentatie. Hierin staat over tabellen:
"[...]  it is not an interactive widget. Thus, its cells are not focusable or selectable. The grid pattern is used to make an interactive widget that has a tabular structure."

Zie ook:
https://www.w3.org/TR/wai-aria-practices/#table

In de documentatie van DSO-toolkit heb ik geprobeerd dit zo zuiver mogelijk aan te houden.
Hierin wordt onderscheid gemaakt tussen data-tabellen en data-grids. 
Zodra er interactieve elementen zijn, zoals een sorteer-functie, dan dient het als data-grid te worden opgezet. Zodoende de toevoeging `role="grid"`. 

Zie ook:
https://www.dso-toolkit.nl/10.1.0/components/detail/table--default.html

**Comment by DHvD-Michael** [comment]
> Dus niks geselecteerd: knop met dubbele pijltjes, aria-roledescription="sorteer oplopend knop"
> Oplopend geselecteerd: knop met naar boven wijzend pijltje, aria-roledescription="sorteer aflopend knop"
> Aflopend geselecteerd: knop met naar beneden wijzend pijltje, aria-roledescription="sorteer oplopend knop"
> 
> Wat een beetje wringt, maar uiteindelijk wel klopt: de visuele weergave op de knop en aria-roledescription komen niet met elkaar overeen, maar dat is omdat de visuele weergave de huidige status weergeeft en de aria-roledescription de aktie van de knop beschrijft.

Er is een aria tag beschikbaar voor deze sorteer-situaties: `aria-sort="ascending"`. We hoeven niet `roledescription` hiervoor te gebruiken.

Hierover heb ik al een stukje geschreven onder het kopje: "Sorteren in een data-grid"
Zie ook: https://www.dso-toolkit.nl/10.1.0/components/detail/table--default.html

Dit is op basis van de WAI-ARIA documentatie:
https://www.w3.org/TR/wai-aria-1.1/#aria-sort

**Comment by PieterVerheij** [comment]
> Er is een aria tag beschikbaar voor deze sorteer-situaties: aria-sort="ascending". We hoeven niet roledescription hiervoor te gebruiken.

Staat dat niet los van elkaar? `aria-sort` staat op de `TH`. `roledesciption` staat op de `button`. Ik begrijp van @timveld dat een beschrijving van de aktie van de knop gewenst is?

**Comment by PieterVerheij** [comment]
> Dus als er wel interactieve elementen zijn in een tabel, dat er dan role="grid" wordt gehanteerd.

@DHvD-Michael wil je dan bij de table filter en sorteerbare tabel `role="grid"` ?

**Comment by DHvD-Michael** [comment]
> > Er is een aria tag beschikbaar voor deze sorteer-situaties: aria-sort="ascending". We hoeven niet roledescription hiervoor te gebruiken.
> 
> Staat dat niet los van elkaar? `aria-sort` staat op de `TH`. `roledesciption` staat op de `button`. Ik begrijp van @timveld dat een beschrijving van de aktie van de knop gewenst is?

Net even dit WAI-ARIA voorbeeld weer nagelopen:
https://www.w3.org/TR/wai-aria-practices/examples/grid/dataGrids.html

Bij VoiceOver wordt niet opgelezen in welke sortering de tabel zich bevindt als alleen `aria-sort `wordt gebruikt. `roledescription` kan hier inderdaad bij helpen om de knop te verduidelijken en om de status te duiden.

Mijn voorstel is dan om de huidige status van de sortering weer te geven bij roledescription:
- Een eindgebruiker kan snappen waar de knop voor dient (om te sorteren)
- Een eindgebruiker hoort in welke volgorde de tabel gesorteerd is (huidige status)

@timveld Is dit voorstel hierboven prima om te hanteren? 

Daarmee: 
Bij niks geselecteerd: knop met dubbele pijltjes, aria-roledescription="sorteer ongesorteerd knop"
Bij oplopend geselecteerd: knop met naar boven wijzend pijltje, aria-roledescription="sorteer oplopend knop"
Bij aflopend geselecteerd: knop met naar beneden wijzend pijltje, aria-roledescription="sorteer aflopend knop"

Verder nog een vraag @timveld : Zijn de bovenstaande `aria-roledescription` teksten niet wat lang?

**Comment by DHvD-Michael** [comment]
> > Dus als er wel interactieve elementen zijn in een tabel, dat er dan role="grid" wordt gehanteerd.
> 
> @DHvD-Michael wil je dan bij de table filter en sorteerbare tabel `role="grid"` ?

Graag inderdaad bij table filter en sorteerbare tabel `role="grid"`. 

Ik heb even een dubbelcheck gedaan of `role="grid"` blokkerend kan werken bij screenreaders. Zo te zien is het goed ondersteund.
Zie: https://www.powermapper.com/tests/screen-readers/tables/table-role-grid/

Daarnaast, het `role="grid"` breidt de toetsenbord interactie mogelijkheden uit voor eindgebruikers. Het lijkt mij prettig voor mensen die afhankelijk zijn van het gebruik van een toetsenbord. Je kan dan een tabel doorlopen zoals bij een spreadsheet.

Bijgaand ook twee afbeeldingen die het illustreren. 
![Data Tabel vs Data Grid 2](https://user-images.githubusercontent.com/4227175/79225158-9c254280-7e5c-11ea-90ef-a5cd7288a6f8.png)
![Data Tabel vs Data Grid 3](https://user-images.githubusercontent.com/4227175/79225162-9d566f80-7e5c-11ea-89a7-4dcf46f1f807.png)

**Comment by DHvD-Michael** [comment]
> Tenslotte:
> 
> * In de documentatie wordt afgeraden meerdere niveaus te gebruiken, begrijp ik niet helemaal; donderdag bespreken? De tabel zo simpel mogelijk houden is wel een goede richtlijn
> * In sommige tabellen is een kolom met titel "#", niet iedereen zal (direct) weten dat je dit als "nummerteken" moet lezen; beter om er nummer of eventueel ID van te maken
> * Taalfout: onder h2 "sorteerbare data-grid" 2 keer is ("In het voorbeeld hieronder is de data is oplopend gesorteerd")

@timveld 
Bijgaand feedback op jouw punten:

- Het gebruik van meerdere niveaus in tabellen wordt afgeraden, omdat screenreaders hier moeite mee kunnen hebben. In deze lijn van gedachte heb ik de tekst opgetuigd.
- In de voorbeelden is # gebruikt in plaats van de term "nummer" om de kolombreedte van de tabel smal te kunnen houden. Bij implementatoren kan dit spelen. Vind je de afkorting "nr." ook acceptabel?
- De taalfout onder h2 "sorteerbare data-grid" kan ik niet reproduceren. Het staat er 1 keer in.

**Comment by PieterVerheij** [comment]
> •	In de voorbeelden is # gebruikt in plaats van de term "nummer" om de kolombreedte van de tabel smal te kunnen houden. Bij implementatoren kan dit spelen. Vind je de afkorting "nr." ook acceptabel?

Ik had het al vervangen door "Nummer". Anders moet je weer een `<abbr>` tag gebruiken en dat lijtk mij in deze context een beetje overdreven?

**Comment by DHvD-Michael** [comment]
Tnx voor de aanpassingen. 
Lijkt mij prima om het volledig als "nummer" uit te schrijven.

**Comment by DHvD-Michael** [comment]
Verder, ik ben even het sorteerbare tabel voorbeeld op van assets.cms.gov aan het bekijken:
https://assets.cms.gov/resources/framework/3.4.1/Pages/#datatablessort

Daar hebben ze het opgelost door aan de sorteerknop iconen een alt tekst toe te voegen: 
`alt="sortable column, sorted ascending, : activate to sort column descending"`

Hierin zit zowel de huidige status "sorted ascending" als de actie wanneer je op de knop drukt " activate to sort column descending".

@timveld wat vind je van deze oplossingsrichting? Wat vind je van de lengte van de tekst?

**Comment by Anto1nette** [comment]
Bij deze de 'sort' iconen en het 'more' icoon tbv de tabel 
[sort-more.zip](https://github.com/dso-toolkit/dso-toolkit/files/4485797/sort-more.zip)

**Comment by PieterVerheij** [comment]
Toegevoegd! 👍

**Comment by timveld** [comment]
NAV de discussie met Michael nog wat uitgezocht: we moeten geen role="grid" op de tabellen zetten. 

Zie allereerst "[wai-aria authoring practices](https://www.w3.org/TR/wai-aria-practices-1.1)" sectie 2.1 Principle 1: A role is a promise. Als je een element een role geeft, hoort daar bepaald gedrag bij wat je moet implementeren; alleen een aria role geven doet niets (behalve de screen reader in de war sturen)!  

In sectie 3.11 staat over de grid: 
"A grid widget is a container that enables users to navigate the information or interactive elements it contains using directional navigation keys, such as arrow keys, Home, and End." 

Anders gezegd, de belangrijkste "promice" die je geeft met role grid is dat je met pijltjestoetsen door de tabel kunt navigeren. Maar dat heeft hier geen toegevoegde waarde, er zijn maar een paar cellen die knopjes bevatten en dat werkt gewoon met tab / shift + tab ('knopjes in een spreadsheet' wordt voor een screen reader zelfs heel onhandig, je moet dan constant tussen bladermodus en focusmodus switchen) Een aria grid is wel noodzakelijk als je de inhoud van cellen wilt kunnen bewerken maar daarvan is hier geen sprake. Hoewel de tabel knoppen en links bevat is de tabel nog altijd statisch (je kunt zeggen dat je door op de sorteerknop te drukken een nieuwe tabel laadt, maar je bewerkt de tabel niet direct).  


Voor het idee dat we geen table mogen gebruiken omdat er interactieve elementen in voorkomen kan ik geen onderbouwing vinden. Sectie 3.21 zegt daarover: 
"... [a table] is not an interactive widget. Thus, its cells are not focusable or selectable. "
Maar dat sluit helemaal niet uit dat er knoppen of links in de cellen zouden kunnen voorkomen; deze knoppen / links zijn dan focusable, de cellen zelf niet.

**Comment by PieterVerheij** [comment]
Ik heb role=grid verwijderd.
