### ISSUE TITLE
Illustraties tbv storingsschermen

### ISSUE THREAD

**Issue by Anto1nette** [dso-toolkit/dso-toolkit#570]
Bijgaand twee illustraties ten behoeve van storingsschermen (80x80 pixels, SVG). Zouden deze vandaag nog meegenomen kunnen worden met de huidige release? Het team van Bram heeft ze nodig, ze zijn per ongeluk nog niet in de toolkit beland.

[Illustraties.zip](https://github.com/dso-toolkit/dso-toolkit/files/4275393/Illustraties.zip)

**Comment by daverhelst** [comment]
@Anto1nette natuurlijk, ik ben er mee bezig, maar als ik ze open dan zijn ze nog niet echt schoon. Er zit o.a. een <title> en een slecht ID in. Kun je ze nog snel opschonen?

**Comment by Anto1nette** [comment]
@daverhelst dat is bij de vorige set ook niet gebeurt, wil wel doen hoor :)

**Comment by Anto1nette** [comment]
Bij deze, dank je wel!
[Illustraties_opgeschoond.zip](https://github.com/dso-toolkit/dso-toolkit/files/4275503/Illustraties_opgeschoond.zip)
