### ISSUE TITLE
Pager uiterlijk gelijktrekken met de buttons 

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#575]
Het pager component https://dso-toolkit.nl/master/components/preview/pager.html 

Is nooit meegenomen in het herontwerp waar we afgestapt zijn van de afgeronde buttons. 
De styling van de pager buttons moet gelijk getrokken worden met de secundaire buttons. 

<img width="1218" alt="Screen Shot 2020-03-05 at 08 23 51" src="https://user-images.githubusercontent.com/36912722/75957759-fecd0b00-5eba-11ea-9d20-dff7d788a4ca.png">

**Comment by daverhelst** [comment]
@MichielDHVD Ik zie dat er nog wel enige ronding op de hoekjes zit. Zou je me misschien een Measure export vanuit Sketch kunnen leveren zodat ik precies weet wat de maatvoering is?

**Comment by bramhoosemans** [comment]
@daverhelst ik had eerder al via Slack de vraag gesteld of we dit component nog nodig hebben met de huidige button positionering van formulieren? Anders mag tie van mij uit de toolkit worden gehaald.

**Comment by bramhoosemans** [comment]
Button styling vind je ook in de toolkit https://dso-toolkit.nl/10.0.0/components/detail/buttons.html :)

**Comment by MichielDHVD** [comment]
Het is een kleine aanpassing en ik ben er zelf nog niet uit of de pager uit de toolkit moet. 

Miss handig om deze aanpassing door te voeren, dan is het in ieder geval consistent. 

De afgeronde hoeken is het zelfde als de button styling waar Bram de link voor heeft gegeven.

**Comment by daverhelst** [comment]
Ah, top!

**Comment by gofix** [comment]
@MichielDHVD zie https://dso-toolkit.nl/_575.pager-herstyling/components/detail/pager.html

**Comment by gofix** [comment]
@MichielDHVD akkoord? Dan zie ik graag een labeltje `status:accepted` :)

**Comment by MichielDHVD** [comment]
Akkoord. 


PS. Ad het is Zaterdag he. In de war met de dagen :p
