### ISSUE TITLE
Focus style search bar gelijk aan invoervelden

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#577]
Focus style van de search bar gelijktrekken met die van de invoervelden. Focus 2px lijn `#275937`

https://dso-toolkit.nl/9.9.0/components/detail/search-bar.html

<img width="611" alt="Schermafbeelding 2020-03-10 om 15 28 36" src="https://user-images.githubusercontent.com/598735/76322563-d8a4d200-62e3-11ea-9328-0a9313e040d2.png">

**Comment by PieterVerheij** [comment]
https://www.dso-toolkit.nl/_577.Focus-style-search-bar-gelijk-aan-invoervelden/components/detail/search-bar.html

**Comment by bramhoosemans** [comment]
Ziet er goed uit.
