### ISSUE TITLE
Componentenfilter in navigatie

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#578]
Zoals https://stijlgids.stad.gent/v3/

**Comment by gofix** [comment]
Deze gaat het toch nog niet halen in deze milestone, we schuiven 'm door.

**Comment by tfrijsewijk** [comment]
Testable: https://dso-toolkit.nl/_578-Componentenfilter-in-navigatie/

Hij is nog niet helemaal toegankelijk, het search bar component voorziet nog niet in een `label` voor de `input type="text"`

**Comment by gofix** [comment]
Verder, het komt nu vrij snel voor dat er met een zoekterm een hele categorie (dus: FUNDAMENT, COMPONENTEN, of VOORBEELDEN) compleet leeg blijft. Misschien zouden we dan die hele kop niet willen zien?

**Comment by gofix** [comment]
Verder, je stelt al "Hij is nog niet helemaal toegankelijk", en dat is inderdaad zo: dat ontbrekende `<label>` moet er nog in (met kloppende `for`-attribuut). Ik vraag me echter ook af wat correcte aria-attributen zijn als je met een filter dingen gaat verbergen. Voor in- en uitklappen zou het toepassen van `aria-expanded` volgens mij moeten (dat gebeurt overigens volgens mij ook nog niet in die treeview-navigatie), maar wat nu voor 'filters' bruikbare markup is. Kun jij daar iets over zeggen @timveld ?

**Comment by bramhoosemans** [comment]
> Verder, het komt nu vrij snel voor dat er met een zoekterm een hele categorie (dus: FUNDAMENT, COMPONENTEN, of VOORBEELDEN) compleet leeg blijft. Misschien zouden we dan die hele kop niet willen zien?

Ik vind het juist goed dat de koppen blijven staan; dat maakt de context van de pagina direct duidelijk. Ook als er niks gevonden wordt.

Andere aandachtspunten:
- Kruisje pas tonen als er gebruikersinvoer is (ook weghalen als er geen invoer is).
- Placeholder tekst veranderen in "Filteren" (we filteren immers in meer dan alleen componenten).

**Comment by PieterVerheij** [comment]
> Verder, het komt nu vrij snel voor dat er met een zoekterm een hele categorie (dus: FUNDAMENT, COMPONENTEN, of VOORBEELDEN) compleet leeg blijft. Misschien zouden we dan die hele kop niet willen zien?

Ik zou een melding 'geen resultaten gevonden' geven.

**Comment by gofix** [comment]
> Ik zou een melding 'geen resultaten gevonden' geven.
Ik niet, want dat past niet echt bij zo'n 'filter', maar meer bij een zoekopdracht. Maar, als we toch even gaan speuren naar wat 'anderen' doen met de markup bij dit soort filters, kunnen we ook wel even kijken wat die 'anderen' doen bij 'geen resultaten'.

Verder, suggestie voor placeholder van @bramhoosemans vind ik goed, alleen is een placeholder natuurlijk geen toegankelijk iets en wordt dit zelfs door sommigen een usability anti-pattern genoemd. Zo ver wil ik niet gaan, maar in ieder geval zou het `<label>` dezelfde waarde moeten hebben: "Filteren" dus.

**Comment by gofix** [comment]
Als ik nog even spiek bij "Gent", zie ik dat het menu dat we 'besturen' met een filter, een `aria-live` attribuut krijgt. EIgenlijk denk ik dat dat inderdaad de "way to go" is.

**Comment by gofix** [comment]
Nee, niet waar: het menu krijgt geen `aria-live`, maar er komt een extra elementje dat vertelt "x resultaten gevonden" met die aria-attribuut.
