### ISSUE TITLE
Shopping cart - Button voldoet niet aan WCAG contrastverhouding

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#581]
Tertiaire button voor ‘naam wijzigen’ voldoet niet aan de WCAG contrastverhouding (min. 4.5:1 voor tekst). Voorstel is om een icoon te gebruiken; deze heeft voldoende aan een contrast van 3.1:1.

Specificaties:
[shopping-cart.zip](https://github.com/dso-toolkit/dso-toolkit/files/4324784/shopping-cart.zip)

![shopping-cart-name](https://user-images.githubusercontent.com/598735/76533485-729d8380-6478-11ea-8558-6b448249a9da.png)

**Comment by PieterVerheij** [comment]
https://www.dso-toolkit.nl/_581.Shopping-cart-Button-voldoet-niet-aan-WCAG-contrastverhouding/components/detail/shopping-cart.html
