### ISSUE TITLE
Voetnoten in IHR plannen ondersteunen

### ISSUE THREAD

**Issue by DjangoBlok** [dso-toolkit/dso-toolkit#584]
De huidige implementatie van voetnoten is voor de DSO viewer en de IHR plannen een probleem.
IHR maakt voor voetnoten gebruik van een xslt van Ruimtelijke Plannen. Ze kunnen dit niet zelf aanpassen.  Het zou fijn zijn als de DSO-Toolkit wordt aangepast (aanvullen met de IHR stijlklassen, niet vervangen). 
Zie voorbeeld IHR implementatie.
![image](https://user-images.githubusercontent.com/34900082/76541099-56531400-6483-11ea-99c6-d5047a9e6105.png)

**Comment by DjangoBlok** [comment]
IHR gaat het toch zelf oplossen en maken volgens de toolkit.

**Comment by tfrijsewijk** [comment]
Dat is echt heel cool van ze!
