### ISSUE TITLE
Tekststructuur vervolg

### ISSUE THREAD

**Issue by DjangoBlok** [dso-toolkit/dso-toolkit#585]
In https://github.com/dso-toolkit/dso-toolkit/issues/492 lijkt de styling niet te zijn meegenomen.
Deze story is bedoeld om de tekststructuur verder doorontwikkelen zodat die overeenkomt met de bijgevoegde excel.

**Comment by bramhoosemans** [comment]
Besproken 19-03: Graag een vaste heading structuur gebruiken. Een artikel op H4 niveau blijft altijd een H4, ongeacht of er optionele niveaus wegvallen.

Hiermee wijken we bewust af van de logische heading structuur (H1,H2,H3), maar zorgen we ervoor dat de visuele representatie overal gelijk blijft én er consistentie is over documenten heen. Er hoeven dus ook geen extra classes toegevoegd te worden voor specifieke styling.

**Comment by gofix** [comment]
Ik heb hier het label [BREAKING] aan gegeven, omdat we met deze change de onlangs geintroduceerde classes `.dso-is-title`, `.dso-is-subsubparagraph`, `.dso-is-department` weer laten vallen.

**Comment by gofix** [comment]
Verder, @DjangoBlok is dit wat je van onze change verwacht? Zie https://dso-toolkit.nl/_585-tekststructuur-vervolg/components/detail/legal-document--no-optionals.html

Overigens ik vind "no optionals" echt een slechte naam. Kan dat niet beter "skipping headings" heten of zo (@daverhelst), want dat is wat hier gedemonstreerd worden.

**Comment by daverhelst** [comment]
@bramhoosemans @DjangoBlok 

Bij deze mijn opzet voor de Typografie pagina met uitbreiding van de Juridisch Document headings:
https://dso-toolkit.nl/_585-tekststructuur-vervolg/docs/fundament/typography.html

Wanneer dit akkoord is zal ik het legal-document component "opruimen/verwijderen"

**Comment by bramhoosemans** [comment]
@daverhelst Waarom hebben we `<section class="dso-legal-document">` nodig? Mijn aanname was dat we H1 t/m H5 normaal gebruiken, en afwijkende styling toepassen als deze binnen een `<article>` tag geplaatst worden.

Dit hangt natuurlijk samen met het volgende:

@DjangoBlok De Regeling, Hoofdstuk en Titel wijken amper af van de normale headings. Zou je er naar kunnen kijken of hier een afwijking nodig is? Afdeling (H4) is wel wezenlijk anders...

**Comment by daverhelst** [comment]
@bramhoosemans De vraag die je hierboven aan Django stelt, is inderdaad de reden waarom dit nu nog leeft. Als de keuze wordt gemaakt om deze headings gelijk te trekken aan de reguliere headings, dan zullen die uiteraard verdwijnen.

**Comment by bramhoosemans** [comment]
@DjangoBlok Zou mooi zijn om dit generiek te maken zodat we geen extra classes nodig hebben ;)

**Comment by DjangoBlok** [comment]
Het uitgewerkte voorbeeld klopt nog niet helemaal. Er ontbreekt nog een bovenste niveau: De H1 als naam van de pagina. Ik zal een voorbeeld uitwerken om dit te illustreren.

**Comment by DjangoBlok** [comment]
Hierbij de aangepaste excel sheet en twee schermuitwerkingen waarop deze structuur van toepassing is:
1. 5. Plandocument: Het scherm waarop één plan wordt getoond met documentstructuur.
2. 4.1 Geselecteerde regels: Het scherm waarop juridische regels vanuit meerdere plandocumenten worden weergegeven.
[Tekststructuur v0.98.2.xlsx](https://github.com/dso-toolkit/dso-toolkit/files/4388465/Tekststructuur.v0.98.2.xlsx)
![5 - Plan Document](https://user-images.githubusercontent.com/34900082/77671624-2e39d980-6f88-11ea-9ec3-0f9bcf2e53a3.png)
![4 1 - Geselecteerde Regels - meer documenten](https://user-images.githubusercontent.com/34900082/77671634-3134ca00-6f88-11ea-8bc7-d601dcc5f208.png)

**Comment by daverhelst** [comment]
@DjangoBlok @bramhoosemans Is hier ondertussen al een antwoord op gekomen?

**Comment by DjangoBlok** [comment]
@daverhelst Volgens mij niet. Wat bedoel je precies?

**Comment by daverhelst** [comment]
@DjangoBlok Sorry, blijkbaar liep mijn scherm nog achter, ik zie nu je uitgebreide antwoord.

**Comment by daverhelst** [comment]
Ter aanvulling, als ik het goed begrijp blijven de "juridisch document headers" (deze buiten de artice) dus bestaan? Ze zullen niet gelijk getrokken worden met de globale headings?

**Comment by DjangoBlok** [comment]
@daverhelst Waarschijnlijk zal de structuur/stijl in "dso-legal-document" blijven afwijken.
Heb jij voldoende aan de voorbeelden die ik heb gestuurd?

**Comment by daverhelst** [comment]
@DjangoBlok Dat ligt aan de vraag die ik eerder aan @bramhoosemans heb gesteld. Zijn dit documentatie pagina's, en wie zet die in elkaar?

Ik zie namelijk wat zaken die niet in de toolkit bestaan (?) bijvoorbeeld de headers zitten nu in een soort uitklappers, met chevron icoon ervoor. Ook staat er een kaart naast etc.

Technisch gezien zijn deze voorbeelden geen componenten (je gaat ze nooit in zijn geheel op deze manier ergens als component aanroepen). Maar ik laat Bram hier even zijn antwoord op geven.

**Comment by DjangoBlok** [comment]
Ok, de chevron in de headers heb ik weggehaald inmiddels.
Dit zijn inderdaad geen componenten maar eerder voorbeelden.
De kaart hoeft zeker niet meegenomen te worden, het gaat om het linkergedeelte.

**Comment by bramhoosemans** [comment]
@daverhelst dit zijn géén documentatie pagina's. Het zijn ontwerpen van @DjangoBlok voor de toepassing 'Regels op de kaart'. Sommige zaken zijn zo specifiek en zullen niet in de toolkit komen, zoals de kaart ernaast.

Voor mij werd het nu pas duidelijk waar de tekststructuur voor gevraagd is. Het probleem is dat deze "verweven" zit in meerdere interactieve componenten en dus niet generiek te maken is. Volgens mij moet Django even met jullie afstemmen wat zijn (eind)doel is voor we onnodige componenten/styling toevoegen aan de toolkit.

**Comment by daverhelst** [comment]
@bramhoosemans Aha, dat verklaart het enigzins. Dan stel ik voor om even te kijken naar: https://dso-toolkit.nl/_585-tekststructuur-vervolg/docs/fundament/typography.html

Hier zijn inmiddels de laatste wijzigingen op doorgevoerd.

@DjangoBlok gaf aan dat de dso-legal-document headers toch zullen blijven bestaan. Daarnaast gaf je eerder aan Django, dat de pagina titel h1 op deze pagina ontbrak, maar dat is gewoon de generieke h1 die bovenaan staat.

Verder zal ik dus de legal-document componenten verwijderen uit de toolkit (die zijn immers niet meer nodig). Verder lijkt me alleen deze documentatie aanpassing op de Typografie pagina nodig. Zijn jullie het daar mee eens?

**Comment by daverhelst** [comment]
Naar aanleiding van net gevoerd bel-gesprek laten we dit issue even voor wat het is. Er is besproken dat het toch iets complexer is dan hier boven blijkt.

We zitten over het volgende te denken:
- 2 nieuwe componenten introduceren; legal-document, plan-header en hieruit vervolgens een voorbeeld pagina fabriceren
of
- dit stukje legal-document uit de toolkit halen, aangezien er maar 1 partij gebruik van zal maken en ze al bezig zijn met bouwen (gevalletje, te specifiek)

Volgende week dinsdag is er een UX-overleg bij DSO en zal deze kwestie ter sprake worden gebracht.

**Comment by bramhoosemans** [comment]
Besproken in UX overleg 31-03:

Een juridisch document niet als component in de toolkit opnemen. Deze is specifiek voor de Viewer en wordt niet gebruikt in andere toepassingen. Indien mogelijk wel de gekozen heading opbouw documenteren na validatie. Voor documentatie wordt een nieuw issue opgevoerd.

**Comment by MichielDHVD** [comment]
Legal document gaat verwijderd worden, issue wordt gesloten. Structurering van juridische document krijgt eigen documentatie pagina. 

Kill issue

**Comment by gofix** [comment]
![image](https://user-images.githubusercontent.com/2689559/78231919-cf1e1c80-74d3-11ea-805b-77b7cb6d6178.png)

**Comment by gofix** [comment]
Het zijn me nogal een comments in dit issue, dus even samengevat wat er nu precies gebeurd is in 
* Correctie documentatie van kleurwaarden voor headings in `docs/02-Fundament/03-typography.md`;
* Component `legal-document` in z'n geheel verwijderd;
* Styling voor `.legal-document` in z'n geheel verwijderd, dus: alle H1/H6 in scope van `.legal-document`, alsmede de classes:

- .dso-is-document,	
- .dso-is-paragraph,
- .dso-is-chapter,	
- .dso-is-subparagraph,
- .dso-is-title,	
- .dso-is-subsubparagraph,
- .dso-is-department,	
- .dso-is-article
