### ISSUE TITLE
Status iconen altijd met witte border

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#586]
In de toolkit zijn nu 2 varianten van de status iconen opgenomen. De "outline" varianten mogen deprecated/verwijderd worden. Volgens mij worden ze nergens gebruikt en hoeven de teams zo ook niks te wijzigen.

Het is de bedoeling dat er altijd een witte border omheen zit.

![Schermafbeelding 2020-03-17 om 15 59 39](https://user-images.githubusercontent.com/598735/76869579-d654f180-6868-11ea-979c-4e7f272c6eb9.png)

**Comment by PieterVerheij** [comment]
https://www.dso-toolkit.nl/_586.Status-iconen-altijd-met-witte-border/components/detail/icon.html
