### ISSUE TITLE
Versie selector in huisstijl

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#591]
Wellicht version-selector.js maar upgraden naar een Angular/React component. Het wordt een steeds complexer component. Nu moet het rekening houden met de verschillende markups die wordt voorgeschreven door de oude en de nieuwe stijl van de toolkit library

**Comment by bramhoosemans** [comment]
Op dit moment opent https://dso-toolkit.nl/ op versie 9.9.0 en zijn de 10.0.0 versies onderin de dropdown te vinden. In dit issue ook graag de volgorde fixen :)

**Comment by gofix** [comment]
Betreft een change in https://github.com/dso-toolkit/version-selector

**Comment by gofix** [comment]
Zie ook #424

**Comment by tfrijsewijk** [comment]
De eerste versie staat online. Het volgende werk staat nog open:
* Oplossing voor pre-versie 10 toolkits
* Huidige selectie in dropdown (gebruikte vue component zet de class `dso-selectable` niet op de `ul`
* Pagina waar alle versies staan.
* Changelog link voor huidige versie
*  In #592 wordt de GitHub link gemaakt

**Comment by gofix** [comment]
Aanvullend, dit onderdeel wordt in een andere codebase gemaakt en heeft daar z'n eigen issue: https://github.com/dso-toolkit/version-selector/issues/10

**Comment by tfrijsewijk** [comment]
Ontwerpen staan in #499

**Comment by gofix** [comment]
Ik kijk nog eens goed naar de selector, en denk dat deze niet goed toegankelijk is. Immers: dit is een custom pulldown, gemaakt met een `<ul>`, die je open en dichtklapt met een `<button>`. Op zijn minst zou de lijst een aria-expanded attribuut moeten krijgen volgens mij, en wellicht zou de knop een `aria-controls` attribuut moeten krijgen, verwijzend naar die lijst (hoewel we elders ook wel eens lezen dat als het te bedienen element een directe sibling is van het bedienend element, dat `aria-controls` achterwege gelaten mag worden).

Kun jij hierop reageren @timveld ?

**Comment by gofix** [comment]
Tijdens ons overleg afgelopen donderdag (4/6) hebben we geconstateerd dat de dropdown button eigenlijk op nog meer punten helemaal geen goed toegankelijke werkvorm is. Namelijk: de visuele groeperingen zijn alleen voor 'ziende' gebruikers te onderscheiden. De kopjes "Versions" en "Branch releases" zijn semantisch helemaal geen kopjes, maar gewoon list items met een class:

![image](https://user-images.githubusercontent.com/2689559/84002439-bc5b1480-a968-11ea-9c4c-f6f84e7da26e.png)

Verder hebben we al vastgesteld dat de `<button>` een `aria-expanded` attribuut moet krijgen (nog fraaier zou zijn dat ook de `<ul>` een `role=listbox` krijgt, maar support daarvoor schijnt niet optimaal te zijn, dus zover hoeven we ook weer niet te gaan. Wel moet duidelijk zijn uit de tekst die IN de button staat wat er nu geselecteerd is, en wat de knop doet.

Kortom: dit schreeuwt om een breaking change van https://dso-toolkit.nl/10.5.0/components/detail/dropdown-button.html

**Comment by gofix** [comment]
NB: in de Dropdown button zelf staan wel al de attributen `aria-haspopup="true" aria-expanded="true"`, maar deze zijn nog niet geimplementeerd in de version selector.

**Comment by gofix** [comment]
In https://github.com/dso-toolkit/dso-toolkit/issues/663 wordt de nieuwe markup voorgeschreven, maar gelukkig toont de oude markup ook nog acceptabel.

**Comment by gofix** [comment]
In https://github.com/dso-toolkit/dso-toolkit/issues/424 (of eigenlijk in https://github.com/dso-toolkit/version-selector/commit/0a0db732e7b07b186ab1753c29a739fbc1716f87) is de button van de dropdown nu voorzien van een beter label (zij het `sr-only`). 

Het ombouwen van de werkvorm zelf naar de nieuwe markup van de dropdown is nog een andere uitdaging.

Namelijk:
- tot voor kort baseerden we ons met de dropdown button eigenlijk nog vrijwel volledig op de werkvorm van bootstrap;
- sinds #663 echter (in de 10.7.0) is deze markup wezenlijk gewijzigd (voor een betere toegankelijkheid);
- daarmee zou het eigenlijk beter zijn dit component en de css ervoor niet meer 'dropdown', maar 'dso-dropdown' te noemen. Immers met de (bootstrap) dropdown heeft het niet veel meer te maken;
- tot nu toe konden we de versieselector relatief eenvoudig laten renderen door van een standaard op bootstrap gebaseerde bibliotheek gebruik te maken: https://uiv.wxsm.space/dropdown. Nu echter de markup behoorlijk anders is geworden, is dat niet meer bruikbaar, en zullen we deze component zelf moeten realiseren. Omdat we in de toolkit al meer met VueJS doen, willen we dat hiervoor dan ook doen.

**Comment by tfrijsewijk** [comment]
Zoals besproken zijn de losse items uit [deze](https://github.com/dso-toolkit/dso-toolkit/issues/591#issuecomment-629281012) reactie opgesplitst in losse issues: #697, #698, #700 en #701
