### ISSUE TITLE
GitHub link in header

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#592]
In de header moet een logo en anchor naar de GitHub pagina. Deze is gesneuveld in #499

**Comment by gofix** [comment]
Betreft een change in https://github.com/dso-toolkit/version-selector (toch?)

**Comment by gofix** [comment]
Zie ook#424

**Comment by gofix** [comment]
Hij is er! Hoera, ziet er goed uit, werkt EN heeft keurig (omdat het een externe link betreft) de attribuut `rel="noreferrer noopener"`. Toch vraag ik me af of hij qua WCAG klopt, zie mijn vraag alhier: https://github.com/dso-toolkit/dso-toolkit/issues/424#issuecomment-635929381

@timveld  kun jij input geven?

**Comment by MichielDHVD** [comment]
Title van de <a>weghalen en verplaatsten naar de Alt text van de <img>.

**Comment by gofix** [comment]
Dit zit in de codebase van https://github.com/dso-toolkit/version-selector, @tfrijsewijk  kun jij die up to date maken met wat nu op de server staat, dan kan ik de gewenste change aanbrengen (die we daarna dan weer op de server zetten)

**Comment by gofix** [comment]
De `alt` wordt: "source code repository op GitHub"

**Comment by timveld** [comment]
OK

**Comment by gofix** [comment]
@tfrijsewijk ?

**Comment by gofix** [comment]
Fixed en op server geplaatst:
https://github.com/dso-toolkit/version-selector/pull/13/files
