### ISSUE TITLE
Datum en tijdnotatie

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#598]
**Verkorte datumnotatie**
In een verkorte datumnotatie wordt de dag- en maandaanduiding met een cijfer van 01 tot 12 weergegeven. Het jaartal bestaat uit vier cijfers. De notatie wordt gescheiden met een koppelteken.

01-01-2012
11-11-2001
28-10-1975

**Lange datumnotatie**
Als uit de context niet volkomen duidelijk is om welke datum het gaat, heeft het voluit schrijven van de maandnaam de voorkeur. De dag wordt als cijfer genoteerd, de naam van de maand wordt met kleine letters voluit geschreven en het jaartal bestaat uit vier cijfers.

1 januari 2012
11 september 2001
28 oktober 1975

**Tijdnotatie**
De notatie 12.00 uur heeft de voorkeur. Het scheidingsteken om de uren aan te geven is de punt. Uur kan eventueel afgekort worden tot u. (inclusief punt). De uren lopen daarbij van 0 tot en met 23. Gebruik van een voorloopnul is optioneel.

8.30 uur
9.30 - 12.30 u.; 13.30 - 18.30 u.

**Comment by gofix** [comment]
@bramhoosemans voeg jij zelf zo'n stuk documentatie toe of wil je dat wij een voorzet doen...?

**Comment by bramhoosemans** [comment]
In principe zouden wij zelf documentatie moeten toevoegen, dus lijkt me slimmer als wij dat doen. Dan worden we er ook handiger in ;)

**Comment by bramhoosemans** [comment]
https://dso-toolkit.nl/_598.datum-tijd-notatie/docs/fundament/datum-tijd.html

**Comment by PieterVerheij** [comment]
Staat 'Lange datumnotatie' bewust in een H3 ipb H2?

Zou dit niet onderdeel kunnen zijn van een langere pagina (of zelfs sectie) met meerdere items, a la Schrijfwijzer Amsterdam? https://www.amsterdam.nl/schrijfwijzer/tekstonderdelen-heldere-taal/ ?

**Comment by bramhoosemans** [comment]
> Staat 'Lange datumnotatie' bewust in een H3 ipv H2?

Ja dat wel, maar ik heb hem toch veranderd in een H2. Eerste idee was dat het onder 'datumnotatie' viel, maar we zouden het ook prima los kunnen zetten.

> Zou dit niet onderdeel kunnen zijn van een langere pagina (of zelfs sectie) met meerdere items, a la Schrijfwijzer Amsterdam? https://www.amsterdam.nl/schrijfwijzer/tekstonderdelen-heldere-taal/ ?

Als er meer schrijf-afspraken in de toolkit gedocumenteerd worden lijkt het me zeker goed deze te bundelen. We hebben reeds een Schrijfwijzer voor DSO, maar om te zorgen dat we dit niet op verschillende plekken moeten bijwerken staat deze niet in de Toolkit, zie https://aandeslagmetdeomgevingswet.nl/digitaal-stelsel/toepasbare-regels-vragenbomen/schrijfwijzer/.

Deze moeten we nog wel 'linken' vind ik.

**Comment by gofix** [comment]
> Deze moeten we nog wel 'linken' vind ik.
Goed idee @bramhoosemans! Maak je een pull request op je branch?
