### ISSUE TITLE
Typeahead component

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#6]
Bij typen wordt het gezochte woord in bold gezet:

<img width="393" alt="screen shot 2017-11-27 at 07 07 02" src="https://user-images.githubusercontent.com/9696261/36042149-2ae927f2-0dcb-11e8-8ce2-58d400cb0b6b.png">

Scope:
* Dit betreft enkel de markup.
* Dit wordt een uitbreiding op de {{input-group}}
* Een beschrijving van het gedrag
* Open en gesloten variant demo
* Highlighten van de matchende tekst
* CSS regressietesting opnemen als scenario

Zie ook:
https://nuaxnu.axshare.com/#g=1&p=2_zoekresultaat__adres_&c=1

/Original reporter: Michael Höhne

**Comment by Poofy83** [comment]
Zie story voor aanpassingen in scope. Mee eens?

Ik zal een opzet doen voor de beschrijving van het gedrag voor de autocomplete

/Original commenter: Thomas - 28-11-17 09:43 

-----

Testable in de unstable channel: https://www.dso-toolkit.nl/unstable/components/detail/typeahead.html

/Original commenter: Thomas - 01-12-17 15:25

-----

Ziet er goed uit.

WCAG tabblad toont echter een aantal errors. Graag aria-labels toevoegen. Zodoende voor nu rejected.

/Original commenter: Michael - 08-12-17 17:09

-----

Errors zijn gefixed

/Original commenter: Thomas - 11-12-17 13:39

-----

graag doorschuiven naar v1.2

De bold van "een" in het voorbeeld zit visueel erg dicht op de normal tekst

/Original commenter: Michael - 19-01-18 10:37

-----

Ter referentie een screenshot:

![image](https://user-images.githubusercontent.com/5871330/37094996-f43a5b50-2214-11e8-9ebf-769b357d427f.png)

Hoe wil je het anders hebben? Als er met "een" 'n match is in het woord "eendenhuis"?

/Original commenter: Thomas - 19-01-18 10:49

-----

Michael Höhne Kun jij nog naar dit ticket en bovenstaande opmerkingen kijken?

/Original commenter: Thomas - 09-02-18 13:38

-----

Er was een probleem met chrome zelf. In andere browsers is het duidelijk te zien, maar in chrome is de weergave een stuk zwakker. Ben je dat ook tegen gekomen?

Heb je ook nog een link waar ik het even kan na lopen.

/Original commenter: Michael - 09-02-18 14:28

-----

Ik zit nu middenin de verhuizing van de broncode, ik kan nu niet een versie uitbrengen waar de typeahead in zit.

Zodra de verhuizing erop zit, zal ik een link geven. In de tussentijd kun je ook bovenstaand screenshot als onderwerp gebruiken: Hoe ziet de letterspacing er daar uit?

/Original commenter: Thomas - 09-02-18 15:48

-----

Daar ziet het er prima uit.

Voor deze sprint hoeft dit niet worden meegenomen. Als de versie kan worden getest dan controleren we nogmaals of in Chrome de bold goed is te zien.

Anders nemen we stappen om dit te verbeteren.

/Original commenter: Michael - 12-02-18 14:27

-----

Ok, dan gaan we deze uitrollen naar unstable

/Original commenter: Thomas - 12-02-18 14:37

-----

Weer testable op de unstable branch: https://www.dso-toolkit.nl/unstable/components/detail/typeahead.html

/Original commenter: Thomas - 13-02-18 13:37

-----

Nu is het verschil tussen bold en normaal wel duidelijk te zien In chrome en anders browsers. Dus goed.

/Original commenter: Michael - 19-02-18 14:33

-----

Zie voorstel in   DSOCOMLIB-109 ACCEPTED  , ticket terug naar "In Specification" ?

/Original commenter: Thomas - 19-02-18 20:04

**Comment by MichielDHVD** [comment]
Hier waren problemen met de bold. Maar daar was een fix voor geregeld. 

Vervolgens was deze even terug gezet om tegelijk met de search balk op te pakken. Maar nu lijkt het dat deze ook opgelost kan worden. 

Zolang het bold, **bold** is dan is het prima. 

Heeft het gebruik van een ouder asap font hier mogelijk invloed op?  @VolleMelk

**Comment by VolleMelk** [comment]
De geschiedenis van dit ticket is vervuild. Er was ooit een typeahead gemaakt, die kwam niet door de WCAG checker heen. Vervolgens werden er omringende componenten opgepakt en viel de typeahead uit de toon.

Aangezien de aangeleverde fix de typeahead niet 'in het gareel' zou laten vallen is er voor gekozen de typeahead niet WCAG proof te maken maar in z'n geheel uit de toolkit te halen.

Dus eigenlijk moet je bovenstaande tekst vergeten (maar hebben we het wel overgenomen uit JIRA om de geschiedenis compleet te houden) en hebben wij een ontwerp nodig.

De typeahead is een aanvulling op elk tekstveld en heeft neit direct een relatie met de zoeker. Kunnen jullie een generiek ontwerp aanleveren?

**Comment by MichielDHVD** [comment]
We gaan er mee aan de slag!

**Comment by MichielDHVD** [comment]
Er zijn wat problemen met de formfields die we gaan aanpassen. Deze komen namelijk niet door de wcag heen. de Codesniffer pikt dit zelfs niet op. 

Maar omdat de formfields aangepast gaan worden is het slimmer om dit op te pakken op hetzelfde moment als we de formfields aanpassen. 

Dan leveren we voor beiden een ontwerp op.

**Comment by MichielDHVD** [comment]
<img width="1126" alt="screen shot 2018-10-11 at 12 34 39" src="https://user-images.githubusercontent.com/36912722/46799041-fb7c3100-cd53-11e8-88d1-1a94974edf05.png">

Dit is de huidige situatie van de Typeahead die gebruikt wordt in het omgevingsloket bij gebruikerstoepassingen. 

Bij een hover wordt de typeahead groen. Misschien voor een active state (Als deze uberhaupt nodig is in een typeahead)  kan de kleur #275937 worden toegevoegd. Zodat het gelijk is getrokken met de secundaire buttons. 

@DjangoBlok op dit moment is in de viewer de type ahead altijd groen. Elke aanvulling wordt groen gehighlight. Dat is behoorlijk intens. 

Kun jij het eens worden om in de toolkit de typeahead gelijk te trekken hoe deze nu in gebruikerstoepassingen wordt weergegeven. Alleen groen dus op focus.  

(Over het uiterlijk van de zoekbalk zelf kunnen we nog een keer praten, om die ook gelijk te krijgen in de viewer en gebruikers toepassingen)

**Comment by DjangoBlok** [comment]
@MichielDHVD Dit ziet er vrijwel hetzelfde uit als bij ons. Wat bedoel je met "in de viewer de type ahead altijd groen"? 
Bedoel je de tekst? Ik zie dat die bij ons groen is en in dit voorstel zwart. Lijkt me prima.
Bedoel je het gedrag? Bij ons wordt de eerste regel automatisch de hover state, je kunt met de enter toets meteen beginnen met zoeken op de bovenste waarde. (net zo als Google dat doet)
Hoe werkt dat bij jullie?

**Comment by DjangoBlok** [comment]
onze productie is: https://dso-viewer.kadaster.nl/dso-viewer/zoeken 
Er komen ook suggesties van de browser die moet je even wegdenken. Hebben we al aangepast.

**Comment by MichielDHVD** [comment]
Ok wel als jij het er mee eens bent @DjangoBlok dan zou ik de type ahead hoe deze nu in op de checker staat: https://int.omgevingswet.overheid.nl/checken als leidend beschouwen. 

Enigste verschil is dat de er een iets duidelijkere rand om de typeahead zit de de tekst zwart is ipv groen. En als je typt dat tekst die overeenkomt met suggesties bold wordt gehighlight.

**Comment by MichielDHVD** [comment]
Ik sluit deze. Als er een wens komt in de toekomst maken we er een nieuwe issue voor.
