### ISSUE TITLE
Toolkit structuur platslaan

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#604]
Hoe gaan we de structuur van DSO Toolkit beter inrichten? Wanneer bestaat een component uit meerdere pagina's / nesting / voorbeelden in documentatie / welke tab als eerste?

... en nog meer vragen worden allemaal besproken. Dit issue gebruiken om een moment in te plannen binnen de release en vervolgstappen te definiëren (in de comments).

**Comment by MichielDHVD** [comment]
Voorstel: Woensdag 8 April voor dit overleg.

**Comment by MichielDHVD** [comment]
Punten Overleg:
1. Plat slaan van verzameling componenten. Componenten zoveel mogelijk variaties op dezelfde pagina. In documentatie mogelijkheden en variaties benoemen. 

2.Lijst maken van ontbrekende documentatie. (DSO-UX)

3. Extra contact tussen Infoprojects en Developers, wat zijn de mogelijkheden?

**Comment by PieterVerheij** [comment]
@bramhoosemans @MichielDHVD 
Zie https://www.dso-toolkit.nl/_604.Toolkit-structuur-platslaan/

Een aantal items onder componenten zijn nog niet platgeslagen, omdat de onderliggende items in een mappenstructuur geordend zijn. 
Voor een aantal items is het mogelijk om die een nivo hoger te tillen en een los item te laten zijn. Als we bv. kijken naar Header, dan is de structuur nu
Header
- Menu
- Navigations

Die zouden we kunnen ombouwen naar (zonder tussenkop Header)
- Mobiele navigatie
- Navigatie (main and sub)

De structuur onder Formulieren is een grotere uitdaginng, die is nu
Formulieren
- Form
- Groups
 - Group Checkboxes
 - Group Confirm
 - Group Files
 - Group Input
 - etc
- Pager
- Steps

Ik denk dat wel deze uit elkaar moeten trekken en platslaan. Alleen Groups zal dan een hele lange pagina worden. Of we staan daar wel een subnivo toe.

Los hiervan: gaan we nu definitief de items in losse panels tonen? Dan zullen daar ook goede titles bij gefefinieerd moeten worden.
![image](https://user-images.githubusercontent.com/25430835/80079467-9ca29500-8550-11ea-9e13-5da61149363f.png)

**Comment by bramhoosemans** [comment]
> Ik denk dat wel deze uit elkaar moeten trekken en platslaan. Alleen Groups zal dan een hele lange pagina worden. Of we staan daar wel een subnivo toe.

Het lijkt me prima om header niet als tussenkop te gebruiken, dus losse items.

Wat betreft formulieren vindt ik dit ook lastiger. Ik ben voorstander om alles zo veel mogelijk uit elkaar te halen en platslaan, maar denk wel dat we 'Groups' moeten behouden met subniveau. Deze formulier elementen zijn té verschillend van elkaar om onder één pagina/component te zetten. (Groups is ook wel een erg verwarrende benaming)

> Los hiervan: gaan we nu definitief de items in losse panels tonen? Dan zullen daar ook goede titles bij gefefinieerd moeten worden.

Volgens mij wel, dus goede titels is zeker wenselijk!

**Comment by PieterVerheij** [comment]
Door het platslaan van de lijst wordt hij wel langer. Misschien is het een idee om het filter-zoekboxje altijd fixed bovenaan te zetten?

**Comment by PieterVerheij** [comment]
Ik heb bij de meeste compontenten titles toegevoegd, zodat ze netjes in een panel komen te staan.
Uitzonderingen zijn gevallen waarj het onderscheid tussen de varianten klein en duidelijk is waardoor een title niks toevoegd (bv. pagination en label) of bij panel, omdat de panel al een panel is.

**Comment by PieterVerheij** [comment]
@tfrijsewijk De build in travis werkt voor deze branch niet, lokaal wel. Jij weet van wanten ;)

**Comment by PieterVerheij** [comment]
https://www.dso-toolkit.nl/_604.Toolkit-structuur-platslaan/

**Comment by PieterVerheij** [comment]
@bramhoosemans zou jij deze aanpassingen willen reviewen?

https://www.dso-toolkit.nl/_604.Toolkit-structuur-platslaan/

Ik heb bij de meeste compontenten titles toegevoegd, zodat ze netjes in een panel komen te staan.
Uitzonderingen zijn gevallen waarbij het onderscheid tussen de varianten klein en duidelijk is en een title niks toevoegt (bv. pagination en label) of bij panel, omdat de panel al een panel is ;).

En misschien hebben jullie een betere suggestie voor de benaming van de navigatie items:

- Navigation mobile
- Navigations (primary & secondary)

**Comment by bramhoosemans** [comment]
Ziet er op het eerste gezicht prima uit, paar kleine opmerkingen:
- Is Navigation mobile een ander component dan Navigation? Ik zou verwachten dat het een mobiele ‘state’ is van het Navigation component (primary & secondary is overbodig).
- Link staat als derde van boven; wordt de lijst niet automatisch op alfabetische volgorde gezet?
- Is Paragraph is component?

**Comment by PieterVerheij** [comment]
Is Navigation mobile een ander component dan Navigation? Ik zou verwachten dat het een mobiele ‘state’ is van het Navigation component (primary & secondary is overbodig).
- De functionaliteit is overgenomen uit de oude situatie. Maar ik geef toen dat het een beetje raar is (daarom zat ik ook met de naamgeving te stoeien).
Voorstel: twee nav entries : 'Navigation primary' en 'Navigation secondary', beiden met het checkboxje waarmee je de mobiele navigatie kan openen en sluiten.

Link staat als derde van boven; wordt de lijst niet automatisch op alfabetische volgorde gezet?
- Ja, het is het 'Anchor'-component, wat je ziet is het label van dit component: 'Link'. Eerlijk gezegd had ik ook verwacht dat het daarop gealfabetiseerd zou worden. Hoe dit te fixen (zonder de naam terug te draaien naar 'Anchor') moet ik uitzoeken. Dit is overigens al langer aan de gang: https://www.dso-toolkit.nl/10.3.1/

Is Paragraph is component?
- Kritisch beschouwd niet, maar ik heb deze overgenomen uit de oude situatie waar het ook als component in de navigatie staat. Weghalen?

**Comment by bramhoosemans** [comment]
> Voorstel: twee nav entries : 'Navigation primary' en 'Navigation secondary', beiden met het checkboxje waarmee je de mobiele navigatie kan openen en sluiten.

Klinkt goed!

> Hoe dit te fixen (zonder de naam terug te draaien naar 'Anchor') moet ik uitzoeken.

Volgens mij zou je deze best kunnen veranderen in Anchor, want we hebben besloten alle componenten in het Engels te houden ivm implementatie.

> Kritisch beschouwd niet, maar ik heb deze overgenomen uit de oude situatie waar het ook als component in de navigatie staat. Weghalen?

Als het niks toevoegt weghalen (is html 101 toch?).

**Comment by PieterVerheij** [comment]
@bramhoosemans 
https://www.dso-toolkit.nl/_604.Toolkit-structuur-platslaan/components/detail/navigations.html
- Navigatie samengevoegd onder 1 kopje 'Navigations'
- Link hernoemt naar Anchor
- Paragraph weggehaald
