### ISSUE TITLE
Line-height headings definiëren

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#606]
De line-height lijkt inderdaad vanuit bootstrap te komen, die zetten namelijk het volgende:

$headings-line-height: 1.1 !default;

We kunnen deze variabele eenvoudig overschrijven, maar dan krijgt elke header dezelfde line-height. Wat we ook kunnen doen is dit per header instellen.

**Comment by bramhoosemans** [comment]
Voorstel gemaakt waarbij de font-size gelijk blijft en de line-height zoveel mogelijk op het 8px grid valt. Enige uitzondering is de `<small>` tekst; deze heeft een percentuele schaling van de body tekst.

Het is erg verwarrend dat typografische stylen zicht anders gedragen binnen/buiten `dso-rich-content`. De documentatie over gebruik hiervan en de juiste positie in de markup roepen veel vragen op.

![typografie concept](https://user-images.githubusercontent.com/598735/79229766-d8a86c80-7e63-11ea-9825-a85c07e2d3ec.png)

**Comment by PieterVerheij** [comment]
@bramhoosemans zie https://www.dso-toolkit.nl/_606.line-height-headings/docs/fundament/typography.html

`small` heeft een font-size 14px en line-height 1.5. Dat valt niet op het 8px gid (21 ipv 24).  Ik had even het idee dat dat een probleem zou zijn, maar omdat het een inline element in een <p> is, heeft de font-size van de <small> geen effect op de uiteindelijke regelhoogte.

![image](https://user-images.githubusercontent.com/25430835/79559318-c7e73900-80a5-11ea-88be-260fb75dce4f.png)

**Comment by bramhoosemans** [comment]
@PieterVerheij Ik snap niet helemaal wat er nu gebeurd. De `small` met line-height van 21px valt binnen een `<p>` waar de line-height 24px is.

Wordt er nu extra ruimte boven en onder geplaatst, zodat deze in een 8px grid valt?

**Comment by PieterVerheij** [comment]
Ik zie dat een stukje tekst in mijn comment wegvalt. Maar uiteindelijk hoefde er niks te gebeuren omdat de `small` binnen de `p` staat en daardoor de line-height toch juist is (24px).

**Comment by bramhoosemans** [comment]
Helder. Voor iedereen die meeleest, zie voorbeeld hieronder :-)

De `small` tekst heeft een gecombineerde  hoogte van 184px (delen door 24 = 7,666). De `<p>` zorgt dat dit netjes wordt aangevuld naar een veelvoud van 24, in dit geval 192px (delen door 24 = 8).

![Schermafbeelding 2020-04-17 om 14 11 39](https://user-images.githubusercontent.com/598735/79568011-6f1f9c80-80b5-11ea-8020-e429fcfab6f8.png)
![Schermafbeelding 2020-04-17 om 14 11 09](https://user-images.githubusercontent.com/598735/79568009-6d55d900-80b5-11ea-8624-98ee05594353.png)

**Comment by PieterVerheij** [comment]
@bramhoosemans de rest is ok?

**Comment by bramhoosemans** [comment]
@PieterVerheij Ik zat nog te kijken naar de H2, doordat we een line-height van 1.33 gebruiken staat daar nu 31.92px

Heb jij nog een idee om dit 32px te krijgen? Het zou natuurlijk 1.333333 etc. moeten zijn..

Verder vallen mij de marges op, maar dat moet een apart issue worden.

**Comment by tfrijsewijk** [comment]
Ter referentie nog de percy screenshots: https://percy.io/dso-toolkit/dso-toolkit/builds/5073084
