### ISSUE TITLE
Voorbeeld pagina 404 / storingspagina's 

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#608]
Een voorbeeld pagina voor de standaard 404 pagina's

![301_omgevingsloket-404-niet-gevonden](https://user-images.githubusercontent.com/598735/78018047-7cb2f380-734d-11ea-84eb-517d840488b0.png)

**Comment by PieterVerheij** [comment]
@MichielDHVD bedoel je met dit issue dat het ook een component moet worden?

**Comment by MichielDHVD** [comment]
Nee, ik ga hier een voorbeeld pagina voor bouwen dus hoeven jullie niks voor te doen vanaf jullie kant. 

Er komt wel een pullrequest die kant op.
