### ISSUE TITLE
Jumbotron component

### ISSUE THREAD

**Issue by Poofy83** [dso-toolkit/dso-toolkit#61]
Bijgaand een nieuwe opzet voor het jumbotron voor Homepagina:

![image](https://user-images.githubusercontent.com/5871330/37091382-3e1055b6-2208-11e8-9779-39e8faea78aa.png)

![image](https://user-images.githubusercontent.com/5871330/37091396-448fceee-2208-11e8-982a-f4219663f40a.png)

Indeling 8 - 4 koloms voor tekstuele onderdelen.

Titel per blok heeft 12 koloms breedte

Doorlopende tekst is max 8 koloms breed, om leesbaarheid van multi-regel teksten te vergroten. 

1 "Featured image" is per Jumbotron blok mogelijk. Deze afbeelding wordt 4 kolomsbreed naast de tekst geplaatst. Editors dienen zelf zorg te dragen voor een acceptabele hoogte van een afbeelding.

Actueel krijgt 6 - 6 koloms indeling voor Nieuws en Evenementen

Mogelijkheid tot steunkleur "lichtgroen" #EBF2E6 . 

Editor kan zelf kiezen welke jumbotron blokken een steunkleur krijgen. Bij geen gebruik van steunkleur, dan wordt een wit kader met een dunne lijn boven en beneden het jumbotron gehanteerd.  

Deze lijn bij de jumbtron  ,zowel boven en onder,  moet **niet** worden opgeteld door een bottom-border en top-border van twee verschillende elementen dat het eruitziet als een border van 2px . Kan dit in het systeem verwerkt worden dat het eruitziet zoals in deze afbeelding

![image](https://user-images.githubusercontent.com/5871330/37091408-4d023422-2208-11e8-9fbf-15cde049f9dc.png)

Foto's die zijn toegevoegd laten het ontwerp zien in mogelijke configuraties. 

![image](https://user-images.githubusercontent.com/5871330/37091415-54a83a14-2208-11e8-9448-640b394d0e5d.png)
![image](https://user-images.githubusercontent.com/5871330/37091420-58e61740-2208-11e8-94a3-31dad223d086.png)
![image](https://user-images.githubusercontent.com/5871330/37091424-5d51e8ae-2208-11e8-8f31-0bc5eeffe8e4.png)
![image](https://user-images.githubusercontent.com/5871330/37091427-6133c460-2208-11e8-9d87-8f555e6e7c54.png)

/Original reporter: Michael

**Comment by Poofy83** [comment]
Dit ticket lijkt te gaan over de huidige jumbotron (https://www.dso-toolkit.nl/1.1.0/components/detail/paragraph.html).

Ik kan de opmerkingen over de foto, col-md-4 en col-md-7 niet plaatsen.
Welke viewport versta jij onder "kleine schermen" ? (Uit jouw zin "Belangrijk detail bij kleine schermen moet de foto tussen Titel en tekst inkomen en de volgende margins hebben")
Aan het einde van dit ticket staat "(Vul story in)"

/Original commenter: Thomas - 09-02-18 10:45

-----

De col md 4 en 7 ging over twee dingen die niet veranderd hoeven te worden dus zaait meer verwarring dan dat het helpt. Dus die heb ik er even tussen uit gehaald.

Kleine schermen houdt xs en sm uit bootstrap aan.

/Original commenter: Michael - 09-02-18 12:44

-----

- Kan er naast een jumbotron ook nog iets anders dan een jumobotron komen te staan?
- Waarom heeft de tertaire knop een col-3 specificatie?
- Jumbotron - specs.png laat een border ONDER een achtergrondkleur zien, klopt dat?

Ik heb er moeite mee om jouw omschreven 'Nieuws/evenementen'-werkvorm te typeren als 'jumbotron':

- Nieuws/evenementen en de 'klassieke' jumbotron hebben als enig visueel overeenkomst de achtergrondkleur of een border.
- Blijft het bij deze twee varianten, of komt er later nog een variant bij?

Ik denk dat we deze story in een aantal componenten moeten opsplitsen:

1. Een mechanisme waarmee we een horizontaal vlak kunnen voorzien van een border OF een achtergrondkleur
2. Een "echte" jumbotron: Kop, tekst, knop, eventueel een plaat
3. Een lijstweergave voor evenementen
4. Een lijstweergave voor nieuws

Ik denk vooral dat punt 1 een krachtig concept is. Als we dit realiseren als een modifier op de .row, zijn de mogelijkheden eindeloos.

Overigens: ik vind de vormgeving van nieuws en evenementen niet duidelijk.

/Original commenter: Thomas - 26-02-18 09:04

-----

**Kan er naast een jumbotron ook nog iets anders dan een jumobotron komen te staan?**
Ja dat kan. Nieuws en Evenementen is zo'n onderdeel. Dus niet alles is een Jumbotron Er komen mogelijk nog meer varianten maar hoe of wat valt niet te voorzien.

Enigste mogelijk overeenkomst is inderdaad de achtergrondkleur of border. Hoewel border altijd de voorkeur heeft omdat dit onderdeel niet goed samenwerkt met de achtergrondkleur. Maar dat zijn implementatie regels.

**Tertiare knop col-3 spec**
De knop moet niet breder zijn dan 3 col. Dus als er tekst is dan breken.

**De border in jumbotron-spec.png**
Deze heeft niks te maken met het groene onderdeel. Groen onderdeel heeft geen bottom border. Deze border is er visueel bijgezet om een duidelijk afgebakend beeld van de jumbotron zonder achtergrond kleur te weergeven.

Het opsplitsen van de componenten klinkt ook als een goed idee. Vooral omdat het ons extra speel ruimte geeft voor de toekomst.

Breek jij de componenten op?

Ik kan dan kijken naar toepassingsregels wat wanneer gebruikt moet worden.

**Weergave nieuwe en evenementen**
Ik neem aan dat je hier mee bedoelt dat de hierarchie niet duidelijk is. Misschien moeten de titels naar bold ipv italic. Ik maak hier even een opzetje van om het te vergelijken.

/Original commenter: Michael - 26-02-18 13:26

**Comment by TonD83** [comment]
Bij het jumbotron component staat het vlaggetje 'ready', ik heb mijn twijfels of dit wel klopt? Zie:

![screen shot 2018-03-08 at 17 22 12](https://user-images.githubusercontent.com/18580063/37162428-8489b580-22f5-11e8-8c24-564498884c19.png)

Lijkt weinig op wat ik hier boven zie.

**Comment by VolleMelk** [comment]
Laten we deze ook maar oppakken voor de 1.2.0, dit is ook geen porum.

@Poofy83: Wat ik nu tegenkom, de border-radius is niet voor alle button sizes gezet:

![image](https://user-images.githubusercontent.com/9696261/37676086-3df4951e-2c77-11e8-9755-7a5b6e49d103.png)

Kun jij dat onder het issue #25 nog oppakken?
