### ISSUE TITLE
Voorbeeld: Documentatie opbouw juridische documenten

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#610]
Documentatie toevoegen van header structuur uit juridische documenten. Implementatie specifiek voor de Viewer. Voorgaand issue https://github.com/dso-toolkit/dso-toolkit/issues/585.

**Comment by MichielDHVD** [comment]
@DjangoBlok gaat links aanleveren op die de opbouw van juridische documenten toont van informatie huis ruimte en Ozon.

**Comment by DjangoBlok** [comment]
De structuur van een document uit IHR: https://preprod.viewer.dso.kadaster.nl/document/NL.IMRO.0344.BPDICKENSHALVEMAAN-VA01
https://preprod.viewer.dso.kadaster.nl/document/NL.IMRO.0344.BPVELDHUIZENDEMEER-VA01

De structuur van een omgevingsdocument uit Ozon met juridische tekst: 


De officiële regeling op officiële bekendmakingen.nl
https://zoek.officielebekendmakingen.nl/stcrt-2019-56288.html


De structuur van een omgevingsdocument uit Ozon met vrije tekststructuur:

**Comment by gofix** [comment]
Waar ligt nu de actie -> @MichielDHVD doe jij een voorzet?

**Comment by MichielDHVD** [comment]
Ja ik doe een voorzet. Maar lijkt erop dat het lastig is de pagina na te bouwen met huidige componenten maar ik ga kijken hoe ver ik kom.

**Comment by MichielDHVD** [comment]
Zo ver kan ik komen met huidige componenten. En dan zitten we niet eens in de rare situaties van de tweede trap waar we nog dieper gaan en een dubbele set aan h1 tm h5 hebben. 

https://dso-toolkit.nl/_610-Documentatie-Juridisch-Document/components/preview/viewer-juridische-documenten.html

Verder ontkomen we er denk ik niet aan om voor de viewer specifiek een component te maken voor dit probleem. Als ik kijk naar de huidige stand van zaken zou dit ook geen probleem moeten zijn vind ik. 

Aangezien we de wizard van pr 12 compleet in de toolkit aan het verwerken zijn. 

Plus ik kan me scenarios voorstellen waar andere onderdelen misschien ook een juridische document willen tonen. Plus als design systeem zou het een dikke plus zijn als we een component weten te maken voor juridische documenten dat leesbaar, overzichtelijk en toegankelijk is.

**Comment by MichielDHVD** [comment]
Als laatste moeten we ook kijken naar highlightboxes. Tekst kan buiten een highlightbox vallen als het aan elkaar geschreven is. Dit moeten we toch gaan afkappen neem ik aan. 

<img width="604" alt="Screenshot 2020-11-25 at 11 54 42" src="https://user-images.githubusercontent.com/36912722/100218418-06cf4e00-2f15-11eb-81bd-436dab0f6e4a.png">

**Comment by hansgrimm** [comment]
Gaat dit nog wat worden?

**Comment by MichielDHVD** [comment]
Denk het niet. Dit is inmiddels eigen component geworden: De document header. Laatste opmerking is meer dan een jaar geleden dus ik zeg cancelen.

**Comment by hansgrimm** [comment]
consider it done ;)
