### ISSUE TITLE
Gedeelte van weergave Dropdown-button valt weg in DSO-Toolkit

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#616]
Het dropdown menu is niet te zien in dropdown button weergave. Iframe lijkt de weergave af te kappen. Alleen te zien bij dropdown button. 

<img width="1118" alt="Screen Shot 2020-04-08 at 12 56 16" src="https://user-images.githubusercontent.com/36912722/78776584-5ff36d00-7998-11ea-8c99-d40763371f91.png">
<img width="1192" alt="Screen Shot 2020-04-08 at 12 56 22" src="https://user-images.githubusercontent.com/36912722/78776589-61bd3080-7998-11ea-9025-6d07f3c64702.png">

**Comment by PieterVerheij** [comment]
Het probleem is breder, de hoogte berekening van de iframes gaat niet goed:
dropdown buttons:
https://www.dso-toolkit.nl/10.2.0/components/detail/dropdown-button.html

tabellen: 
https://www.dso-toolkit.nl/10.2.0/components/detail/table.html

**Comment by bramhoosemans** [comment]
Ziet er beter uit zo :)
