### ISSUE TITLE
Modal zonder header en footer heeft geen margin meer

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#618]
![Screenshot 2020-04-09 at 09 28 08](https://user-images.githubusercontent.com/598735/78870251-1cefd300-7a46-11ea-894e-c2ae1f2b717c.png)

**Comment by PieterVerheij** [comment]
Dit is geintroduceerd met deze aanpassing:
915c587 - #456 Modal uitzoomen geeft vreemde rendering
