### ISSUE TITLE
Search Bar voorzien van label

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#621]
De search bar heeft geen label waardoor het component niet toegankelijk wordt voorgeschreven.

Ik stel voor een non-breaking change. Het `span`-element waar het icoon op staat _kan_ een `label` worden. Het is ook mogelijk om een label zonder icoon te plaatsen.

Het huidige gedrag (geen label maar wel icoon of helemaal niets) blijft in stand.

**Comment by gofix** [comment]
> Het huidige gedrag (geen label maar wel icoon of helemaal niets) blijft in stand.

Maar... de varianten
- Geen icoon en geen label
- Alleen icoon
hebben dan dus bewust GEEN `<label>`, en die varianten zijn dan dus NIET toegankelijk. Zijn dat dan wel varianten die je nog steeds wilt laten zien?

**Comment by gofix** [comment]
https://dso-toolkit.nl/_578-Componentenfilter-in-navigatie/components/detail/search-bar.html

**Comment by tfrijsewijk** [comment]
Klopt. Ik wil er nu geen breaking change van maken.
