### ISSUE TITLE
HTML in toolkit heeft geen highlighting meer

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#622]
Het pad naar de css is incorrect

**Comment by gofix** [comment]
Dat ziet er weer lekker uit:
https://dso-toolkit.nl/_578-Componentenfilter-in-navigatie/components/detail/form--sections.html

Vergelijk:
![image](https://user-images.githubusercontent.com/2689559/79332906-ede1d180-7f1d-11ea-96bb-d7f5eb59000f.png)
