### ISSUE TITLE
Externe link mist rel="noopener noreferrer"

### ISSUE THREAD

**Issue by WiebeCnossen** [dso-toolkit/dso-toolkit#623]
Zie bv https://developers.google.com/web/tools/lighthouse/audits/noopener

**Comment by bramhoosemans** [comment]
@WiebeCnossen Zou je iets meer toelichten over de consequenties hiervan?

Meestal zijn externe sites vaak bijv. gemeenten die content plaatsen op het Omgevingsloket en best mogen weten dat verkeer via ons loopt.

Maar volgens mij gaat het niet alleen over 'tracking' en is het een beveiligingsrisico. Dan is er geen keuze te maken en zouden we dit gewoon moeten toepassen. 

> Add rel="noopener" or rel="noreferrer" to each of the links that Lighthouse has identified in your report. In general, when you use target="_blank", always add rel="noopener" or rel="noreferrer".

Wat is het verschil tussen rel="noopener" en rel="noreferrer"? Zouden we ze niet beiden moeten toevoegen?

**Comment by WiebeCnossen** [comment]
Bij het volgen van een link zal een browser standaard doorgeven vanaf welke site de link gevolg is. Dit kun je voorkomen met `rel=noreferrer`, maar zoals @bramhoosemans aangeeft, is dit op zich geen probleem. De reden dat `rel=noreferrer` genoemd wordt, is dat dit _ook_ het gedrag van `rel=noopener` implicieert.

Als je een link met `target=_blank` opent, dan zal in het nieuw geopende venster/tabblad `window.opener` verwijzen naar het venster/tabblad dat waar de link op staat. Het enige wat je hiermee kunt, is in `window.opener` een _andere_ site/pagina laden. Hiermee zou een aanvaller de gebruiker kunnen misleiden, omdat de gebruiker denkt dat hij deze pagina zelf heeft opgeroepen. Overigens blijft `window.opener` steeds in het venster/tabblad beschikbaar _ook_ nadat bv een totaal ander adres in de adresbalk is ingetikt.

Mijn advies is kortom: voeg `rel=noopener` toe, want dit voorkomt dat `window.opener` geset is.

**Comment by bramhoosemans** [comment]
Het toeval wil dat we volgende sprint in team 12 een security bevinding oppakken waarbij het advies wordt gegeven `target="_blank" rel="noopener noreferrer"` te gebruiken.

Ik ben er even achter de reden aangegaan. Het advies om ook `noreferrer` toe te voegen komt doordat er altijd onzekerheid is over compatibiliteit tussen browsers. `noreferrer` / referrer-headers weglaten heeft wel de voorkeur omdat ze in logs terecht kunnen komen en een privacy + securityzorg kunnen zijn (https://developer.mozilla.org/en-US/docs/Web/Security/Referer_header:_privacy_and_security_concerns).

Met noreferrer is een nadeel dat trackers zoals google analytics het verkeer dan categoriseren als "direct traffic". Alternatief kan wel zijn een "origin" header meegeven (die alleen het domein doorgeeft). Maar dat is nader uit te zoeken door een expert.

Ik stel voor om vanuit de toolkit dezelfde strategie te hanteren en `target="_blank" rel="noopener noreferrer"` te gebruiken. Mee eens?

**Comment by WiebeCnossen** [comment]
Ik kan daar prima mee leven.

**Comment by MichielDHVD** [comment]
Op externe link wordt altijd `target="_blank" rel="noopener noreferrer" ` toegepast. 

Documentatie volgt later

**Comment by gofix** [comment]
Op https://dso-toolkit.nl/_623.Externe-link-mist-rel-noopener-noreferrer/components/detail/anchor.html is dit nu te zien, lijkt me prima zo.

Echter, ook buttons kunnen als externe links worden ingezet: https://dso-toolkit.nl/_623.Externe-link-mist-rel-noopener-noreferrer/components/detail/buttons.html dus daar moet dit dan ook nog op (al heeft het geen visuele impact, we willen ook hier het goede voorbeeld geven).
