### ISSUE TITLE
Search Bar toegankelijk inzetten

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#624]
In dit issue zorgen we dat de Search Bar altijd toegankelijk wordt ingezet. Dit betekent een breaking change.

Besproken in refinement 16-04: aria-live="polite" (=documentatie) en mogelijk label zichtbaar maken (apart issue https://github.com/dso-toolkit/dso-toolkit/issues/631)

**Comment by gofix** [comment]
Zijn we het er al over eens dan HOE "de Search Bar altijd toegankelijk wordt ingezet"? Met wat @PieterVerheij in #631 heeft gerealiseerd is dat hoe dan ook het geval: het label is dan altijd zichtbaar, maar op zich zou dat niet per se hoeven volgens mij. Als wenselijk is dat in sommige werkvormen het label TOCH niet visueel zichtbaar is, kan dat nog steeds op een toegankelijke manier, nl. door het label slechts 'visueel verborgen' te maken. Voor de 'ziende' gebruiker is het dan wel belangrijk dat onomstotelijk duidelijk is wat de search-bar doet. Dat kan bv. door dan de placeholder EXACT dezelfde term te geven als in het visueel verborgen label staat: dat wordt over het algemeen als een acceptabele oplossing gezien.

Hoe dan ook is een daadwerkelijk zichtbaar label natuurlijk altijd het duidelijkst, dus als dat de voorkeur heeft...

**Comment by gofix** [comment]
Bovenstaande is nu verwerkt in #631, maar wat nu nog rest is dat we een oplossing moeten realiseren voor wanneer de search bar zonder expliciete submit ingezet wordt, en er dan een wijziging op de pagina plaatsvindt. Zoals bv. het geval is met de searchbar in de toolkit zelf die gebruikt wordt voor het filteren van de componenten. Mijns inziens zou boven de lijst van componenten een element moeten staan waarin het aantal resulterende componenten vermeld wordt. Dit hoeft op zich niet per se 'zichtbaar' - omdat de ziende gebruiker toch wel duidelijk ziet dat de lijst van componenten wijzigt - maar op zich is er ook weer niet heel veel op tegen.

Maar, dit is natuurlijk maar 1 voorbeeld van een toepassing van de searchbar die aanvullende werkzaamheden vereist om een volledig toegankelijke werkvorm te realiseren. Er zijn er vast meer. Oftewel: dit lijkt me bij uitstek een casus voor aanvullende documentatie!

**Comment by bramhoosemans** [comment]
Eens; we kunnen in documentatie de verschillende werkvormen van het searchbar-component beschrijven. Als daar extra werkzaamheden nodig zijn om het component toegankelijk te maken kunnen we een voorbeeld opnemen in de toolkit.

Kortom:
- In https://github.com/dso-toolkit/dso-toolkit/issues/631 zijn alle nodige wijzigingen gemaakt.
- Nieuw issue maken (of dit issue omvormen) voor uitgebreide documentatie 'searchbar' component.
- Onvoorziene werkvormen toevoegen aan toolkit (documentatie en/of voorbeelden).

_Dit vereist een inventarisatie van alle searchbar werkvormen uit de verschillende applicaties. Naar verwachting niet af te ronden voor release week 23._

**Comment by bramhoosemans** [comment]
Nieuw issue aangemaakt om 'filteren in een lijst' te documenteren, zie https://github.com/dso-toolkit/dso-toolkit/issues/681. Voor verdere documentatie van het component geen apart issue opgenomen; hiervan bestaat reeds een lijst met componenten met ontbrekende documentatie.
