### ISSUE TITLE
Searchbar kapt onderkant letters af. 

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#625]
<img width="1077" alt="Screen Shot 2020-04-16 at 11 18 26" src="https://user-images.githubusercontent.com/36912722/79438589-044a6480-7fd4-11ea-80d1-c1dce69c98ca.png">

Onderkant van lange letters zoals 'g' worden afgekapt.

**Comment by bramhoosemans** [comment]
Lijkt nog niet goed te gaan:
https://dso-toolkit.nl/_625.Input-kapt-onderkant-letters-af/components/detail/search-bar.html

**Comment by PieterVerheij** [comment]
Ah, de tekst in de placeholder wordt anders afgebroken dan de value van de input zelf. Logisch natuurlijk *rolling eyes*

**Comment by PieterVerheij** [comment]
@bramhoosemans recheck please! :)

**Comment by bramhoosemans** [comment]
Ziet er goed uit!
