### ISSUE TITLE
Search bar met zichtbaar label

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#631]
Search bar met zichtbaar label mogelijk maken. Styling is gelijk aan formulier elementen; Asap SemiBold 16px #191919 op 8px van het invoerveld.

Specificaties: [search-bar.zip](https://github.com/dso-toolkit/dso-toolkit/files/4574443/search-bar.zip)

![search-bar](https://user-images.githubusercontent.com/598735/80963330-03f0fc80-8e0f-11ea-94da-11320225420a.png)

**Comment by PieterVerheij** [comment]
@bramhoosemans Blijft de variant met verborgen zoekknop wel bestaan? https://www.dso-toolkit.nl/10.4.0/components/detail/search-bar.html

**Comment by bramhoosemans** [comment]
> @bramhoosemans Blijft de variant met verborgen zoekknop wel bestaan? https://www.dso-toolkit.nl/10.4.0/components/detail/search-bar.html

ja, zoekknop blijft optioneel ivm filteren op lijst.

**Comment by PieterVerheij** [comment]
Ok, dan moet in #624 ook een vermelding komen over `aria-live="polite"`.

**Comment by gofix** [comment]
Ik weet niet of @PieterVerheij en @bramhoosemans  nog onderling overleg hebben gepleegd, maar ik lees met "Search bar met zichtbaar label mogelijk maken." niet dat voortaan de search-bar ALTIJD een zichtbaar label heeft. En dat is wel wat @PieterVerheij nu heeft gemaakt:
https://dso-toolkit.nl/_631.Search-bar-met-zichtbaar-label/components/detail/search-bar.html

De vraag dus: mag de search bar zowel **met** als **zonder** zichtbaar label bestaan?

Als ie ook nog steeds ZONDER zichtbaar label mag bestaan, moet dat label natuurlijk alleen maar 'visueel verborgen' zijn, zodat de werkvorm wel een zgn. 'accessible name' heeft (want: de placeholder is geen bruikbare oplossing daarvoor).

**Comment by bramhoosemans** [comment]
Het is de bedoeling dat de search bar **met én zonder** zichtbaar label kan bestaan. Als het nu zo is gebouwd dat er altijd een zichtbaar label bij staat, moet dit nog worden aangepast.

**Comment by gofix** [comment]
Dus, @PieterVerheij , zoals @bramhoosemans hier aangeeft, is de versie ZONDER zichtbaar label nog steeds nodig. Dat niet alleen, @tfrijsewijk heeft in #621 aangegeven dat zelfs de variant 'met helemaal geen label' nog wenselijk zou kunnen zijn, als elders op de pagina (bv. in een formulier) dat label wordt gemaakt (uiteraard dan met z'n `@for` wijzend naar het `@id` van de search bar input).

Verder lijkt met deze change nu de search bar van de toolkit zelf kapot.

**Comment by PieterVerheij** [comment]
@bramhoosemans 3 smaken: met, verborgen en zonder label. En dan alledrie met en zonder icon. :)
https://www.dso-toolkit.nl/_631.Search-bar-met-zichtbaar-label/components/detail/search-bar.html

**Comment by bramhoosemans** [comment]
@PieterVerheij @gofix Volgens mij zijn er maar 2 varianten:

1. Zichtbaar label
2. Verborgen label

In https://github.com/dso-toolkit/dso-toolkit/issues/621 hebben we er bewust voor gekozen om het mogelijk te maken geen label erbij te plaatsen, zodat het geen breaking change werd. Deze variant is ook niet toegankelijk.

Anders zou dit issue niet breaking zijn toch?

**Comment by PieterVerheij** [comment]
Zie https://github.com/dso-toolkit/dso-toolkit/issues/631#issuecomment-633513232 : "@tfrijsewijk heeft in #621 aangegeven dat zelfs de variant 'met helemaal geen label' nog wenselijk zou kunnen zijn, als elders op de pagina (bv. in een formulier) dat label wordt gemaakt (uiteraard dan met z'n @for wijzend naar het @id van de search bar input)"

**Comment by bramhoosemans** [comment]
Ja, ik zie die comment alleen niet terugkomen in https://github.com/dso-toolkit/dso-toolkit/issues/621. Maar misschien kijk ik verkeerd...

Als dat het geval is, dan inderdaad 3 varianten én geen breaking change.

**Comment by tfrijsewijk** [comment]
In #621 staat niet de opmerking die wij zoeken, maar ik kan 'm ook niet meer vinden. Wellicht Slack oid.

Context: Ergens is mij ten hore gekomen dat de search-bar ook in een formulier toegepast moet/kan worden. Het formulier voorziet in dat geval van het label. De search-bar moet dan nog steeds een icoon krijgen en dus "ontoegankelijk" in te zetten zijn, de toegankelijkheid komt op een hoger niveau (het formulier) tot stand.

Maar ik weet niet meer waar dit is besproken en of dit uberhaupt nog actueel is. Doet dit bij @bramhoosemans een lampje branden?

**Comment by bramhoosemans** [comment]
Oef.. dat durf ik niet te zeggen. In de huidige 'wizard' van Vergunningcheck en Aanvragen maken we (nog) geen gebruik van <form> tags ;-) Maar wellicht elders wel.

Wat mij betreft prima om alle varianten te ondersteunen. Met documentatie dat er een @for wijzend naar het @id van de search bar input moet worden toegevoegd als er geen label wordt gebruikt.

**Comment by gofix** [comment]
@PieterVerheij ziet er goed uit op https://dso-toolkit.nl/_631.Search-bar-met-zichtbaar-label/components/detail/search-bar.html maar... in de documentatie staat: "Pas bij een waarde toont de reset-knop, initieel is deze knop verborgen". Dat is inderdaad zo met de search bar die wordt ingezet in de toolkit voor het filteren van componenten, maar in de voorbeelden is het niet echt te zien. Wordt een implementator geacht dit altijd (bv. middels scripting) te implementeren, of zou dit toch eigenlijk ook gewoon met CSS kunnen (bv. met een `:not(:empty)`-constructie?)

**Comment by PieterVerheij** [comment]
Aangepast, met alleen een clear-button bij het voorbeeld met ingevulde waarde.

**Comment by gofix** [comment]
@bramhoosemans wat vind je ervan: https://dso-toolkit.nl/_631.Search-bar-met-zichtbaar-label/components/detail/search-bar.html 
Klaar? merge naar master?

**Comment by bramhoosemans** [comment]
Helemaal top!
