### ISSUE TITLE
dso-toolkit.nl: uitklapbare knopjes in navigatiebalk missen heading en aria-expanded

### ISSUE THREAD

**Issue by timveld** [dso-toolkit/dso-toolkit#632]
Op dso-toolkit.nl staan in de navigatiebalk uitklapbare knopjes zoals 'buttons'. Deze hebben geen aria-expanded. Ze moeten ook een h3 krijgen. Ik heb overwogen om van deze knopjes links te maken omdat in een lijst met links een button mogelijk gemist wordt. Maar het nadeel is dat we dan afwijken van de accordion conventies en dso-brede consistentie is erg belangrijk in dit soort zaken, als de knopjes ook een heading hebben is het in ieder geval logisch opgebouwd.

**Comment by MichielDHVD** [comment]
Betreft Treeview in de toolkit zelf.

**Comment by gofix** [comment]
Ik zie dit nog niet terug in de toolkit: https://dso-toolkit.nl/_632.dso-toolkit.nl--uitklapbare-knopjes-in-navigatiebalk-missen-heading-en-aria-collapsed/

Daartoe zul je nog ergens in de scripting aan de bak moeten, @PieterVerheij

**Comment by gofix** [comment]
Verder, nu krijgt de button alleen maar een `aria-expanded` attribuut, maar is nergens uit te herleiden WAT je met die knop in en uitklapt (hetgeen met een constructie met een `<a href />` impliciet wel bepaald kan worden, maar met een `<button>` natuurlijk niet).

Een `aria-controls` attribuut, wijzend naar het `@id` van het in/uit te klappen gedeelte, lijkt nodig: https://www.w3.org/WAI/PF/aria-1.1/states_and_properties#aria-controls

**Comment by gofix** [comment]
Na uitwerking van de gewenste markup zal verwerken in scripting nog niet geheel triviaal zijn. Het in/ uitklappen wordt nu door scripting van fractal/mandelbrot gedaan, en daar kunnen we niet zomaar op inhaken (en dat wil je ook niet). Het is wsl. het verstandigst als we het in/uitklappen (en de daarbij horende aria attributen) helemaal zelf gaan regelen. Dan hebben we ook invloed op hoe we bv. een een ander gaan laten gedragen in smalle viewports (zie #423), en zouden we ook het filteren toegankelijker kunnen maken (immers, nu wordt nog niet aan de gebruiker teruggekoppeld dat er op de pagina iets veranderd is).

**Comment by PieterVerheij** [comment]
> Verder, nu krijgt de button alleen maar een `aria-expanded` attribuut, maar is nergens uit te herleiden WAT je met die knop in en uitklapt (hetgeen met een constructie met een `<a href />` impliciet wel bepaald kan worden, maar met een `<button>` natuurlijk niet).
> 
> Een `aria-controls` attribuut, wijzend naar het `@id` van het in/uit te klappen gedeelte, lijkt nodig: https://www.w3.org/WAI/PF/aria-1.1/states_and_properties#aria-controls

Ik heb bewust geen `aria-controls` gebruikt, met dit artikel in het achterhoofd: https://heydonworks.com/article/aria-controls-is-poop/ . Ik interpreteer daaruit dat het gebruik van aria-controls niet nodig is als aan de volgende conditie voldaan wordt:  "Expandable areas that come immediately after their aria-expanded controllers in the source (and in focus order)"

Wat is jouw mening, @timveld?

**Comment by timveld** [comment]
@PieterVerheij  dit artikel heb ik zelf aangedragen, als de content direct onder het knopje staat is aria-controls sowieso niet nodig en het wordt slecht ondersteund

**Comment by PieterVerheij** [comment]
Zonder aria-controls opleveren.

**Comment by PieterVerheij** [comment]
Aangepast: https://www.dso-toolkit.nl/_632.dso-toolkit.nl--uitklapbare-knopjes-in-navigatiebalk-missen-heading-en-aria-collapsed/index.html

**Comment by timveld** [comment]
Het knopje form elements lijkt geen aria-expanded of heading te hebben

**Comment by PieterVerheij** [comment]
@timveld Excuses: ik heb de verkeerde link geplakt. Het beste kan je kijken op https://www.dso-toolkit.nl/_632.dso-toolkit.nl--uitklapbare-knopjes-in-navigatiebalk-missen-heading-en-aria-collapsed/components/preview/tree-view.html

Zodra de code definitief is, dan werken we het uit in de navigatie van de toolkit zelf.

**Comment by timveld** [comment]
Ja deze lijkt wel in orde

**Comment by PieterVerheij** [comment]
OK, dan gaan we het in de coide van de toolkit verwerken. 👍

**Comment by tfrijsewijk** [comment]
Het toevoegen van aria attributen aan het menu kan niet in dit issue opgelost worden, het menu wordt een Vue component. De mandelbrot scripting is niet toereikend en laat zich niet uitbreiden. We kunnen nu door hoepels springen om toch de scope van dit issue te resolven maar het wordt toch helemaal anders.

**Comment by bramhoosemans** [comment]
@tfrijsewijk Hoe staat het hiermee? Kunnen we deze al realiseren?
