### ISSUE TITLE
Marges in implementatie treeview verschillen

### ISSUE THREAD

**Issue by PieterVerheij** [dso-toolkit/dso-toolkit#638]
De marges in de navigatiebalk verschillen met die in het contentvlak:

![image](https://user-images.githubusercontent.com/25430835/80814481-44146d00-8bcc-11ea-87fc-6152d87ac9d9.png)

**Comment by PieterVerheij** [comment]
@bramhoosemans zijn de specs voor een treeview in het contentvlak hetzelfde als in de navigatiebalk?
In https://github.com/dso-toolkit/dso-toolkit/issues/499 is daar niks over te vinden?

**Comment by bramhoosemans** [comment]
@PieterVerheij er is nooit een component gespecificeerd. Met de ontwikkeling van de navigatiebalk (sidebar) in de toolkit is besloten om er een component van te maken. Als je meer nodig hebt dan https://github.com/dso-toolkit/dso-toolkit/issues/499 hoor ik het graag. 

In de toekomst zal er nog een variatie bijkomen waarschijnlijk. Hier is @DHvD-Michael mee bezig.

**Comment by PieterVerheij** [comment]
@bramhoosemans Ok duidelijk, Maar in dit geval geldt dus dat de marges/inspringingen van de navigatiebalk leading zijn en moeten worden toegepast op de treeview in het contentvlak?

**Comment by bramhoosemans** [comment]
Ja, dat is volgens mij wat we besproken hebben. Laten we ze in ieder geval gelijk trekken, dan kunnen we eventuele wijzigingen in de toekomst op één waarheid baseren.
