### ISSUE TITLE
Line-height headings werken alleen binnen class="dso-rich-content"

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#640]
Met de toolkit upgrade naar 10.3.0 had ik een taak aangemaakt om de line-height van de headings te controleren. Nu blijkt dat deze enkel binnen de class="dso-rich-content" worden toegepast. De bedoeling was volgens mij om dit overal toe te passen.

In de gebruikerstoepassingen (van team PR12) wordt nergens class="dso-rich-content" gebruikt. Als dit wel gewenst is zal hier een duidelijke instructie voor moeten worden opgesteld.

**Comment by PieterVerheij** [comment]
@bramhoosemans dan hebben we scope verkeerd begrepen. :( 
Ik zal een pocje maken, met de line-heights buiten de scope `.dso-rich-content` scope. De margin-bottom stond altijd binnen de scope van `.dso-rich-content`, wat wil je daarmee: binnen of buiten? 
Ik verhuis de margin-bottom voor nu mee naar buiten.

**Comment by bramhoosemans** [comment]
Prima, ik zie op het eerste gezicht geen vreemde dingen.

**Comment by gofix** [comment]
@PieterVerheij maak je een PR?

**Comment by gofix** [comment]
@bramhoosemans stelt "ik zie op het eerste gezicht geen vreemde dingen.", en dat klopt. Wel valt op in de screenshots van Percy dat hierdoor zo'n beetje ALLES wijzigt in de toolkit, omdat immers de koppen van dso-example-wrappers ook headings zijn. 

https://percy.io/dso-toolkit/dso-toolkit/builds/5167503

**Comment by gofix** [comment]
Zie ook https://dso-toolkit.nl/_640.Line-height-headings/components/detail/examples.html, waar de lineheight van de koppen in de `dso-whitebox` best een stuk groter is geworden. Is dat werkelijk wenselijk @bramhoosemans

**Comment by gofix** [comment]
Over die whitebox... die heeft een vaste hoogte (yek), en daar zal nu dus ook een nieuwe formule op losgelaten moeten worden, want door de grotere regelhoogte zal de hoogte van die whiteboxes in de meeste gevallen ook hoger zijn.

Zie 
![image](https://user-images.githubusercontent.com/2689559/81645058-2dbaac80-9429-11ea-8f22-c0c0f78e605b.png)
... waar de onderkant nu wat krappig wordt.

**Comment by gofix** [comment]
@MichielDHVD misschien wil jij reageren, bij (tijdelijke) afwezigheid van @bramhoosemans

**Comment by MichielDHVD** [comment]
Lijkt erop dat de lineheight meer impact heeft als gedacht. Misschien slimmer om dit specifieke issue iets meer tijd te geven. 

Vooral omdat dit whitebox issue bijv. niet 1,2,3 opgelost zal zijn neem ik aan?

**Comment by gofix** [comment]
De whitebox hanteert een zgn. 'magic number' voor z'n `min-height`:
```min-height: 520px;``` (en als 'ie een counter heeft `&.dso-has-counter`) komt bovenop die 520 nog een offsetwaarde.

Aangezien die 520 toch al uit een natte vinger komt, is het niet heel kwalijk om daar simpelweg wat pixels bij te tellen...
