### ISSUE TITLE
Rich content (eventueel uit CMS afkomstig) in banner component

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#641]
In PR02 is de banner geimplementeerd maar ze hebben dit niet met de correcte markup kunnen doen vanwege de werking van het cms. 

in de banner wordt de tekst in een <span> gezet. 

Code toolkit: 
```
<section class="banner alert-danger" role="alert">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <button type="button" title="Sluiten" class="btn btn-link"><span class="sr-only">Sluiten</span><svg class="di di-times">
                        <use href="../../dso-icons.svg#times" />
                    </svg></button>
                <span>
                    Op dit moment ervaren wij een storing in de Vergunningcheck. U kunt wel een aanvraag of melding indienen.
                </span>
            </div>
        </div>
    </div>
</section>
```

Maar vanwege het cms  wordt er altijd de volgende elementen tussengestopt als er variable tekst gebruikt wordt

```
<div>
  <p>
  </p>
</div>
```

Code in werking:
```
<section class="banner alert-danger" role="alert">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <button type="button" title="Sluiten" class="btn btn-link"><span class="sr-only">Sluiten</span><svg class="di di-times">
                        <use href="../../dso-icons.svg#times" />
                    </svg></button>
                <span>
                    <div>
                       <p>
                          Op dit moment ervaren wij een storing in de Vergunningcheck. U kunt wel een 
                          aanvraag of melding indienen.
                      </p>
                   </div>
                </span>
            </div>
        </div>
    </div>
</section>
```

Dit zorgt voor het. volgende probleem. Een p heeft namelijk een bottom margin van 8px. Dus zit er onbedoeld meteen een extra margin in het component. PR02 lost dit tijdelijk op door custom CSS. 

Hoe dit opgelost zal worden moet denk ik overleg zijn tussen infoprojects en developers.

**Comment by gofix** [comment]
Zoals @MichielDHVD al stelt:

> Hoe dit opgelost zal worden moet denk ik overleg zijn tussen infoprojects en developers.

Het verzoek staat nog steeds uit dat we kunnen meekijken in de codebase!

**Comment by gofix** [comment]
Anyway: het probleem valt uiteen in een aantal onderdelen:

**div vs span**
Een `<div>` mag niet in een `<span>`. De content die via de CMIS interface uit het CMS komt echter zal voor dit soort 'rich-content' (waar dus paragrafen, koppen, etc. in zouden kunnen voorkomen) altijd een `<div>` als root-element hanteren. Het lijkt het slimste als we de banner component in plaats van een `<span>` een `<div>` laten voorschrijven (en dat we de styling daarop aanpassen, nu wordt namelijk in smallere viewports die `<span>` kleiner gemaakt om het sluitkruis ernaast te laten passen).

**margin op paragraaf**
Als in de tekst een `<p>` voorkomt, (en dat is het geval hier), veroorzaakt dat een `margin-bottom`. Die wordt veroorzaakt door `bootstrap-sass\assets\stylesheets\bootstrap\_type.scss`, waar scopeloos ALLE `<p>` deze marge krijgen. 
```
p {
  margin: 0 0 ($line-height-computed / 2);
}
```

Eigenlijk is dat wellicht ongewenst, want we schrijven natuurlijk voor dat `<p>` eigenlijk in een `.dso-rich-content` component zouden moeten staan, zodat we de marges op paragrafen, koppen etc. daarvoor 'gecontroleerd' kunnen toepassen.
Maar... ook als de inhoud IN een `.dso-rich-content` zou staan, zou er een `margin-bottom` komen:
```
.dso-rich-content {
  p {
    margin: 0 0 $rich-content-margin-bottom;
  }
}
```
Dus dat is nog niet zonder meer 'de' oplossing. Ik denk dat wellicht voor werkvormen WAARIN dergelijke `.dso-rich-content` kan voorkomen, we dan kunnen programmeren dat voor het laatste element daarin GEEN `margin-bottom` wordt gemaakt.

(en dat geeft dan ook gelijk weer het nut van `.dso-rich-content` aan: daarmee wordt gelijk duidelijk dat daarin rijke HTML voor lopende tekst wordt gemaakt)

**Comment by gofix** [comment]
Mijn voorstel zou dus zijn dit issue om te dopen naar "Banner moet rich-content kunnen bevatten", en dat we dat dus dan ondersteunen door de CSS voor dso-rich-content IN dergelijke componten zodanig aan te passen dat het laatste marge-gevende element die marge NIET krijgt.

**Comment by gofix** [comment]
Dit laatste IS zelfs al zo (dus: dat het laatste marge-gevende element die marge NIET krijgt). Oftewel: `.dso-rich-content` is hier wat er moet gebeuren.

**Comment by gofix** [comment]
Ik heb hier geen reactie op gekregen (@bramhoosemans , @MichielDHVD , any thoughts on this?) dus met @PieterVerheij en @tfrijsewijk afgesproken dat we dit maar gewoon oppakken, op een non-breaking manier. Dus: we gaan ondersteunen dat in een banner in plaats van waar nu de ``<span>` staat waarin de tekstregel/melding komt, daar ook een `<div>` met `dso-rich-content` mag staan, waarin het dan mogelijk is rijkere content dan alleen 'plain text' op te nemen. De `<span>` blijft wel ondersteund, dus de change is backwards compatible.

**Comment by MichielDHVD** [comment]
Klinkt als logische oplossing. Straks nog even bespreken in toolkit refiniment, of ik het begrijp.

**Comment by bramhoosemans** [comment]
Altijd `dso-rich-content` variant

**Comment by gofix** [comment]
Ziet er goed uit @PieterVerheij , maar is het nu dan niet een uitgelezen moment om in de documentatie van dit component even iets te noemen over `.dso-rich-content`? Of zullen we dat toch maar centraal doen, bij de documentatie van https://dso-toolkit.nl/_641.banner-tekst-html/components/detail/rich-content.html

Anyway: @MichielDHVD , @bramhoosemans  wat vinden jullie van https://dso-toolkit.nl/_641.banner-tekst-html/components/detail/banner.html
Klaar, lijkt me?

**Comment by PieterVerheij** [comment]
Ik heb een opzetje voor de documentatie in de branch verwerkt.
