### ISSUE TITLE
Zelfevaluatie augustus 2020

### ISSUE THREAD

**Issue by timveld** [dso-toolkit/dso-toolkit#649]
Zoals besproken zal ik in principe ook 2 keer per jaar alle componenten van de DSO toolkit doorwerken en daar komen dan issues uit. Ik ben er mee begonnen en het valt niet mee... In dit issue wordt de lijst steeds bijgewerkt, even kijken of dit goed werkt of Github hiervoor goed werkt. 
* Accordion: TBD (div heeft geen heading)
* Alert: tbd (iconen geen alt tag)
* Anchor:  tbd (geen alt tag icoontjes achter links)
* Attachments Counter 
	Versie 10.4.0: goedgekeurd door @timveld op 14-05-2020
* badge: TBD (goed maar gaat min bij inzoomen, ligt waarschijnlijk aan toolkit site)
* banner: TBD (moet waarschuwingsicoontje tekstalternatief hebben?)
* buttons: tbd (geen tekstalternatief voor externe icoontjes)
* cards:
	Versie 10.4.0: goedgekeurd door @timveld op 14-05-2020
	Opmerking: Moeten "toon informatie" knoppen name "toon informatie over Brouwersmolen" krijgen? (geen WCAG afwijking)

**Comment by gofix** [comment]
Dank @timveld  voor deze eerste aanzet, ik stel echter voor om een complete lijst te maken van alle componenten/pagina's, met daarachter de check-status (met mogelijke waarden: OK, NOK, of TODO).

Ik weet niet of een github issue de handigste plek is om dit in te doen. Misschien een Google docje?

**Comment by timveld** [comment]
Dat is een goed idee, zal een Google spreadsheet maken. Bedoeling is inderdaad om de hele lijst te doen ;-)

**Comment by gofix** [comment]
* Logo
* Kleuren
* Typografie
* Lay-out
* Favicon
* Illustraties
* Pdf-bestanden
* Zoeksuggesties
* Datum en tijd
* COMPONENTEN
* Accordion
* Alert
* Anchor
* Attachments Counter
* Badge
* Banner
* Breadcrumbs
* Buttons
* Cards
* Carousel
* Conclusion
* Definition List
* Description
* Dropdown Button
* Footnotes
* Form
  * Form Elements
    * Group Checkboxes
    * Group Confirm
    * Group Files
    * Group Input
    * Group Radios
    * Group Select
    * Group Static
    * Group Textarea
* Form Pager
* Form Steps
* Highlight Box
* Icons
* Image
* Info
* Info Button
* Jumbotron
* Label
* List Button
* Lists
* Logo
* Modal
* Navigations
* Pagination
* Panel
* Progress Bar
* Progress Block
* Progress Indicator
* Rich Content
* Search Bar
* Shopping Cart
* Table
* Tabs
* Tooltip
* Tree View
* Whitebox*

**Comment by gofix** [comment]
Even voor diegenen die gisteren niet bij het overleg hierover waren (@tfrijsewijk , @DHvD-Michael , @bramhoosemans and some) : @timveld  heeft toegelicht dat binnen alle devteams ieder half jaar een stavaza wordt opgesteld mbt. WCAG, met plannen en prioriteringen mbt. hoe dat dan in het komende halfjaar ingevuld gaat worden. Omdat Toolkit steeds meer het (goede) voorbeeld zal zijn voor teams, gaan we daarin dat ook doen. Te beginnen met deze "nulmeting".

We hebben ook nog even teruggekeken naar Toolkits versies voor 4, toen bestond nog een WCAG tabblad bij de componenten, omdat dat echter maar in enkele gevallen gevuld werd is ooit besloten dat vooralsnog achterwege te laten. In plaats daarvan willen we nu eigenlijk implementatie-aanwijzigingen gaan opnemen, wsl. gewoon in tabblad "Documentatie", maar daarin dan wel duidelijk herkenbaar. En belangrijk onderdeel van die implementatie-aanwijzingen zijn dan de zaken waar een developer op moet letten mbt. WCAG.

Verder heeft @MichielDHVD aangegeven dat in sommige teams geautomatiseerde checks in de build worden opgenomen, en dat we dit wellicht toch ook weer terug zouden moeten gaan brengen in de Toolkit zelf (alternatief: juist documenteren HOE de teams dergelijke checks in hun builds kunnen doen).

**Comment by gofix** [comment]
@timveld is hier al voortgang op, heb je een link naar een online document voor me? Desgewenst wil ik hier ook wel het voortouw in nemen?

**Comment by timveld** [comment]
Bedankt voor de lijst, ga dit uitwerken in https://docs.google.com/spreadsheets/d/1yO54oNEMRZPN-TUNTWORlS0OnsMOfizH5TgRJ0-N6gY/edit?usp=sharing

**Comment by timveld** [comment]
Ik heb een grote stap gezet in de evaluatie, zie de spreadsheet. Onderstaand een concept zelfevaluatie rapport voor TBO: 

## totstandkoming rapport 
DSO-toolkit heeft op 15 augustus 2020 de eerste zelfevaluatie voltooid. De gevolgde procedure wijkt gezien de aard en rol van de DSO toolkit af van de zelfevaluatie procedure voor reguliere DSO subapplicaties.  

De DSO toegankelijkheidsexpert is lid van het DSO toolkit team en doorlopend betrokken bij de ontwikkeling. Hij heeft in de afgelopen weken de zelfevaluatie uitgevoerd door ieder component van de toolkit te beoordelen, waar nodig in overleg met de rest van het team. Daarbij is ook aandacht besteed aan de toegankelijkheid van dso-toolkit.nl zelf.  Gevonden problemen zijn als issues in onze Github vermeld.  

## Stand van zaken
In het afgelopen jaar zijn informeel al veel toegankelijkheidsproblemen opgelost. De DSO toolkit staat er wat betreft toegankelijkheid goed voor maar in deze zelfevaluatie zijn toch veel issues naar voren gekomen. Het goede nieuws is dat de meeste problemen  klein en eenvoudig te verhelpen zijn. Toch verdienen deze issues onze aandacht omdat de toegankelijkheid van onze componenten doorwerkt in het hele DSO portaal. 

Een aandachtspunt is de documentatie van onze toolkit, die schiet in hoge mate tekort. Wij zijn daarom begonnen met een project om systematisch alle componenten te documenteren. Onderdeel van deze documentatie is een "toegankelijkheid checklist" met punten die bij implementatie van een component gecontroleerd moeten worden. In elk van de wekelijkse refinements stellen we onder leiding van de toegankelijkheidsexpert de checklist voor 1 component vast. Dat is tevens een moment waarop andere verbeterpunten voor het betreffende component naar boven kunnen komen. 
## Voortgang sinds vorige rapport
Dit is het  eerste rapport
## Openstaande problemen
Zie (link naar spreadsheet) voor de uitkomst van de zelfevaluatie. 
## Opmerkingen en verwachte ontwikkelingen
In de komende tijd gaan we de gevonden issues oplossen. Uiterlijk in februari 2021 zullen we een nieuwe zelfevaluatie uitvoeren. 

In de jaarlijkse toetsing door stichting accessibility kan de evaluatie van onze componenten niet goed worden meegenomen, maar wij vinden externe toetsing van onze componenten wel nuttig op het moment dat uit onze volgende zelfevaluatie geen of weinig issues voortkomen. De kans is namelijk groot dat een onafhankelijke toegankelijkheidsexpert fouten vindt die we zelf missen. Dit zullen waarschijnlijk kleine problemen zijn, maar het is wel belangrijk die op te lossen omdat ze doorwerken in het hele portaal. In onze volgende zelfevaluatie zullen wij hier op terug komen en TBO mogelijk voorstellen een dergelijke externe toetsing te organiseren. Over de meest effectieve opzet van zo'n toetsing denken wij ondertussen na.

**Comment by timveld** [comment]
De inventarisatie is afgerond en ik heb 30 van de 48 componenten goedgekeurd! Dat voeg ik nog toe aan het zelfevaluatie rapport hier boven. Graag bovenstaande tekst zsm checken en desgewenst commentaar geven.
