### ISSUE TITLE
Stappenteller pagina ombouwen naar landingspagina Aanvragen

### ISSUE THREAD

**Issue by gofix** [dso-toolkit/dso-toolkit#650]
Op https://dso-toolkit.nl/10.4.0/components/detail/stappenteller.html staat een afbeelding die van een publieke site van een waterschap afkomstig is, en waarvoor DSO niet de rechten schijnt te hebben. Hier moet een alternatief voor komen.

@MichielDHVD komen er verder nog afbeeldingen voor in de Toolkit waarvoor dit zou kunnen gelden?

**Comment by MichielDHVD** [comment]
Pagina ombouwen na huidige toepassing in aanvragen op omgevingsloket.

**Comment by MichielDHVD** [comment]
Heb deze op 3 juni gezet als deze wordt goedgekeurd kan die nog mooi mee anders volgende release.

**Comment by gofix** [comment]
Ziet er goed uit, wat mij betreft: https://dso-toolkit.nl/_650-Stappenteller-pagina-ombouwen/components/detail/landingspagina.html
