### ISSUE TITLE
Checklist documentatie voor componenten. 

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#654]
Het is belangrijk dat bij elk component de juiste documentatie komt te staan. Daarom een start inventarisatie van welke documentatie hebben en of deze conform de "nieuwe" standaard documentatie is opgezet. 

~~test~~ Strikethrough betekent klaar

DOCUMENTATIE 
Logo  - Moet mogelijk nog een check opgedaan in combinatie met responsive gedrag. 
Kleuren - Outdated, staat nog in dat oranje voor een call to action 
Typografie - Up to date (ergens zou een juridisch document geupdate worden toegevoegd) 
Lay-out - Outdated, moet herzien worden
Favicon - Documentantie mogelijk niet relevant ? 
Illustraties - Herbeoordelen of het toereikend genoeg is?
Pdf-bestanden - Up to date 
Zoeksuggesties - Herschrijven in lijn met nieuwe stijl 
Datum en tijd - Up to date 

COMPONENTEN
Accordion - UX documentatie ontbreekt , Alleen technische beschrijving infoprojects 
Alert - Bevat documentatie voor meer componenten dan alleen alerts, spinners, loaders, invoervelden
Anchor - UX documentatie ontbreekt, Alleen technische beschrijving infoprojects 
Attachments Counter - UX documentatie ontbreekt, technische beschrijving niet essentieel? 
Badge - UX documentatie ontbreekt, technische beschrijving niet essentieel?
Banner - UX documentatie ontbreekt, technische beschrijving ontbreekt
Breadcrumbs - UX documentatie ontbreekt, technische beschrijving niet essentieel?
Buttons - Herschrijven nieuwe stijl
Cards - UX documentatie ontbreekt, technische beschrijving ontbreekt
Carousel - UX documentatie ontbreekt, technische beschrijving niet essentieel?
Conclusion - UX documentatie ontbreekt, technische beschrijving ontbreekt
Definition List - UX documentatie ontbreekt, technische beschrijving niet essentieel?
Description - UX documentatie ontbreekt, Alleen technische beschrijving infoprojects
Dropdown Button - UX documentatie ontbreekt, technische beschrijving niet essentieel?
Footnotes - UX documentatie ontbreekt, technische beschrijving ontbreekt
Form -  UX documentatie ontbreekt, Alleen technische beschrijving infoprojects
Form Elements -  UX documentatie ontbreekt, Alleen technische beschrijving infoprojects
Group Checkboxes -  UX documentatie ontbreekt, Alleen technische beschrijving infoprojects
Group Confirm -  UX documentatie ontbreekt, technische beschrijving ontbreekt
Group Files -  UX documentatie ontbreekt, Alleen technische beschrijving infoprojects
Group Input -  UX documentatie ontbreekt, technische beschrijving ontbreekt
Group Radios -  UX documentatie ontbreekt, Alleen technische beschrijving infoprojects
Group Select -  UX documentatie ontbreekt, technische beschrijving ontbreekt
Group Static -  UX documentatie ontbreekt, technische beschrijving ontbreekt
Group Textarea -  UX documentatie ontbreekt, Alleen technische beschrijving infoprojects
Form Pager  -  UX documentatie ontbreekt, Alleen technische beschrijving infoprojects
Form Steps - UX documentatie ontbreekt, technische beschrijving ontbreekt
Highlight Box -  UX documentatie ontbreekt, Alleen technische beschrijving infoprojects
Icons - Documentatie herschrijven nieuwe stijl 
Image -  UX documentatie ontbreekt, Alleen technische beschrijving infoprojects
Info -  UX documentatie ontbreekt, Alleen technische beschrijving infoprojects
Info Button -  UX documentatie ontbreekt, Alleen technische beschrijving infoprojects
Jumbotron -  UX documentatie ontbreekt, Alleen technische beschrijving infoprojects
Label - UX documentatie ontbreekt, technische beschrijving ontbreekt
List Button - UX documentatie ontbreekt, technische beschrijving ontbreekt
Lists -  UX documentatie ontbreekt, Alleen technische beschrijving infoprojects
Logo - fundament documentatie herschrijven en hier naar toe verplaatsen ? Samenvoegen ? 
Modal - Herschrijven nieuwe stijl documentatie
Navigations -  UX documentatie ontbreekt, Alleen technische beschrijving infoprojects 
Pagination -  UX documentatie ontbreekt, Alleen technische beschrijving infoprojects
Panel -  UX documentatie ontbreekt, Alleen technische beschrijving infoprojects
Progress Bar -  UX documentatie ontbreekt, Alleen technische beschrijving infoprojects
Progress Block - UX documentatie ontbreekt, technische beschrijving ontbreekt
Progress Indicator - Onderdelen die bij Alert zijn verplaatsen en hier herschrijven 
Rich Content - Er staat een hele korte beschrijving vanuit IP dit onderdeel verdient miss iets meer aandacht vanwege de onduidelijkheid die het geschept heeft. 
Search Bar -  UX documentatie ontbreekt, Alleen technische beschrijving infoprojects
Shopping Cart - UX documentatie ontbreekt, technische beschrijving ontbreekt
Table - Herschrijven in nieuwe stijl documentatie
Tabs -  UX documentatie ontbreekt, Alleen technische beschrijving infoprojects
Tooltip -  UX documentatie ontbreekt, Alleen technische beschrijving infoprojects
Tree View - UX documentatie ontbreekt, technische beschrijving ontbreekt
Whitebox -  UX documentatie ontbreekt, Alleen technische beschrijving infoprojects

Deze story zal een van de lange adem zijn. Miss is een doelstelling wel handig elke release proberen 1 of 2 onderdelen weg te werken. Sommige onderdelen zullen minder omschrijving nodig hebben dan de ander. Bijv. checkboxes hebben geen giga pagina maar wel een efficiente.

**Comment by Anto1nette** [comment]
Deze mag ook dicht
