### ISSUE TITLE
dso-toolkit.nl: eerste link 'index' heeft onduidelijke naam

### ISSUE THREAD

**Issue by timveld** [dso-toolkit/dso-toolkit#657]
Het logo links bovenin dso-toolkit.nl (link die naar de homepage verwijst) heeft name "index", dat is niet duidelijk. Moet zijn (bijvoorbeeld) "dso-toolkit.nl homepage".

**Comment by gofix** [comment]
Hier moet inderdaad een `alt` attribuut op de `<img>` worden gezet, want nu is er niks anders waar een screenreader de 'accessible name' uit kan bepalen (er is geen linktekst en ook geen `title`).

**Comment by gofix** [comment]
@PieterVerheij heeft in zijn PR nu de `alt` gezet op `dso-toolkit.nl homepage`. Is op zich goed natuurlijk, maar ik twijfel of we de URL hierin moeten noemen, of dat we de naamgeving en casing hanteren zoals verder in leesbare tekst in de DSO Toolkit. Dus `DSO Toolkit homepage` (oftewel, DSO met kapitalen, Toolkit met kapitaal, en geen verbindingsstreepje). Wat denk jij @MichielDHVD

**Comment by PieterVerheij** [comment]
Alt tekst aangepast (had er zelf al wat vraagtekens bij).

**Comment by gofix** [comment]
Ik vind het goed zo.
