### ISSUE TITLE
logo: documentatie tekstalternatief onvoldoende 

### ISSUE THREAD

**Issue by timveld** [dso-toolkit/dso-toolkit#658]
In de documentatie van logo staat een heel algemeen verhaal over tekstalternatieven. Dat is niet voldoende duidelijk. Als een logo naar de homepage is de aanbeveling het logo de alt tag "dso-toolkit.nl [homepage]", dat laatste is optioneel. Zie https://webaim.org/techniques/alttext/#logos.volgens 
Als het logo los gebruikt wordt is het m.i. over het algemeen functioneel, dan krijgt het als alt tag "logo digitaal stelsel omgevingswet". Als er een 'extra tekstregel' bij staat moet die in principe terugkomen in de alt tag.

**Comment by Anto1nette** [comment]
Doorgezet
