### ISSUE TITLE
Documentatie kleuren: kopstructuur en kleurcodes

### ISSUE THREAD

**Issue by timveld** [dso-toolkit/dso-toolkit#659]
2 problemen bij documentatie kleuren: 
* Kopstructuur klopt niet, O.M. h3 "groen" met de voorbeelden daaronder h2
* Onder de kleurvlakken staan 2 kleurcodes in een lijst. De tweede is omschreven (rgb) maar wat het eerste getal precies is staat er niet bij ook niet elders op de pagina. Waarschijnlijk is het voor ontwikkelaars wel ondubbelzinnig duidelijk maar misschien toch verduidelijken (een code zoals RGB is m.i. voldoende, weet zelf niet precies hoe je dit getal kunt beschrijven)

**Comment by Anto1nette** [comment]
Deze is aangepast door Michiel en doorgezet
