### ISSUE TITLE
Alert uses wrong icons

### ISSUE THREAD

**Issue by TonD83** [dso-toolkit/dso-toolkit#66]
Het alert component (https://dso-toolkit.nl/unstable/components/detail/alert.html) gebruikt verkeerde iconen. Het lijkt er op alsof hier font-awesome iconen worden gebruikt, terwijl deze niet overeen komen met de in het ontwerp opgenomen (custom) iconen welke als het goed is als SVG's zijn aangeleverd. 

**Verwacht:**
![screen shot 2018-03-07 at 13 57 58](https://user-images.githubusercontent.com/18580063/37093433-9dc1d5e6-220f-11e8-96b7-4eb0ee487b4a.png)

**Opgeleverd:**
![screen shot 2018-03-07 at 13 58 02](https://user-images.githubusercontent.com/18580063/37093436-9fa072fa-220f-11e8-9203-7adf1a5de369.png)

**Comment by VolleMelk** [comment]
In het vorige PI is de alert opgeleverd zoals hier: https://www.dso-toolkit.nl/1.1.0/components/detail/alert.html

Vervolgens is hier een improvement voor aangemaakt. Er zijn geen SVG's aangeleverd en na goedkeuring van Michael is er teruggevallen op Font Awesome iconen. Zie #22.

@MichielDHVD Kun jij hier meer over zeggen, of met Michael overleggen?

**Comment by TonD83** [comment]
Jammer dat dit niet goed is gegaan in de oplevering. Ik heb de iconen wel van onze designer (destijds) gehad en dus in ons project verwerkt. Zie bijlage.

Antoinette (onze huidige UX-er) en ik bespreken het morgen met @MichielDHVD 
[Icons.zip](https://github.com/dso-toolkit/dso-toolkit/files/1789275/Icons.zip)

**Comment by MichielDHVD** [comment]
Ja deze iconen ontbraken en waren niet opgeleverd naar ons, daarom is er terug gevallen op Font Awesome . 

Fijn dat ze er in ieder geval er nog zijn! Heeft Julien misschien toevallig nog het laatste sketch file naar jullie gestuurd. Want wij hebben alleen de voor laatste versie jammer genoeg.

**Comment by MichielDHVD** [comment]
Ah fijn dat de iconen er in ieder geval nog zijn. Deze waren niet aan ons aangeleverd en daardoor moest er inderdaad terug gevallen worden op de Font Awesome iconen.

**Comment by TonD83** [comment]
Het Sketch document is... een veel besproken onderwerp. Maar uiteindelijk hebben we een nieuwere versie waaraan de opvolger van Julien druk bezig is om door te ontwikkelen en/of te verbeteren. Je zou hiervoor bij Antoinette moeten zijn. Heb je haar contactgegevens al?

**Comment by MichielDHVD** [comment]
Nee nog niet. Deze contactgegevens zouden wel handig zijn. Als zij elementen al aan het doorontwikkelen is is dat wel handig om te weten. Anders worden er misschien telkens contrasterende versies aangeleverd en zitten we niet op een lijn. Wat lastig is voor degene die het moeten bouwen. 

Want waar de ontwerpen van Julien leidend waren, zullen dat nu de ontwerpen van Antoinette worden. 

Ik zal nog met Michael bespreken of het misschien handig is als ik er morgen bij ben. Misschien hebben jullie ook nog vragen of de huidige elementen die zijn opgeleverd.

**Comment by VolleMelk** [comment]
@MichielDHVD Kunnen wij de iconen die @TonD83 heeft bijgevoegd gebruiken? Ik lees iets over een 'nieuwere' versie?

**Comment by MichielDHVD** [comment]
Nieuwere versie heeft voorlopig geen betrekking op de iconen als het goed is. 

De vorige Ux'r die gestopt is is vergeten zijn laatste ontwerp-bestanden door te sturen. Dus die zijn verloren gegaan. 
De nieuwe Ux'r Antoinette is bezig met een nieuwe/nieuwere versie van het laatst geleverde ontwerp bestand. Of hier nieuwe Icons in zullen zitten is de vraag. In de toekomst staat een custom icon set wel op de agenda. Maar ik heb geen idee wanneer die er aan zit te komen. 

Momenteel zijn de meegestuurde Icons van Ton de juiste icons.

**Comment by VolleMelk** [comment]
Fixed: https://www.dso-toolkit.nl/1.2.0-beta.0/components/detail/alert.html

Het lijkt erop dat de iconen uit Icons.zip net een ander kleurschema hebben dan het screenshot uit @TonD83's screenshot. Kan dat?
