### ISSUE TITLE
documentatie, typografie en illustraties: tables mist row headers

### ISSUE THREAD

**Issue by timveld** [dso-toolkit/dso-toolkit#660]
Op pagina's typografie en illustraties staan tabellen waarbij de rijtitel niet als th gemarkeerd zijn. Zou hier volgens mij wel kunnen / moeten. 

De tabellen hebben ook geen caption, dat is niet verplicht: 
* Bij typografie voegt een caption die de tabel omschrijft wat toe
* Bij illustraties blijkt doel van de tabel al voldoende uit bovenliggende h2

**Comment by Anto1nette** [comment]
Tabellen zijn in markdown en copy van eerder opgeleverde documentatie voordat ik ermee begon. Ik kan hier verder niks mee. Bij typografie staat al een caption die heet 'Headings' ik zal die tekst aanpassen.

**Comment by Anto1nette** [comment]
Heading is aangepast naar 'Beschikbare typografie' en wordt doorgezet. Kan gesloten worden wat mij betreft.
