### ISSUE TITLE
Favicon: tabel mist header

### ISSUE THREAD

**Issue by timveld** [dso-toolkit/dso-toolkit#661]
Op pagina favicon:
* De derde kolom van de enige tabel heeft geen header
* Is dit zo (zonder enige omschrijving) duidelijk genoeg?

**Comment by PieterVerheij** [comment]
Ik zal een header toevoegen ("Afbeelding"?), dat is wel zo consequent.

**Comment by timveld** [comment]
Afbeelding lijkt me prima

**Comment by PieterVerheij** [comment]
https://www.dso-toolkit.nl/_661.Favicon--tabel-mist-header/docs/fundament/favicon.html
