### ISSUE TITLE
Badge en label verduidelijken 

### ISSUE THREAD

**Issue by timveld** [dso-toolkit/dso-toolkit#662]
Ik weet niet precies hoe badge en label gebruikt worden maar: 
* Teksten die er nu in staan zijn Engelstalig
* Als het de bedoeling is dat developers er zelf teksten inzetten dan blijkt het type badge alleen nog uit de kleur en dat is waarschijnlijk niet slechts decoratief;  moet dus duidelijk gedocumenteerd worden dat er sr-only iets wordt toegevoegd

**Comment by PieterVerheij** [comment]
>Teksten die er nu in staan zijn Engelstalig
De tekst in het label is de naam van de betreffende class van het label. Zullen we dit vertalen naar het nederlands (de tekst, niet de class)? Eventueel vermelden we de classes in de documentatie.

> Als het de bedoeling is dat developers er zelf teksten inzetten dan blijkt het type badge alleen nog uit de kleur en dat is waarschijnlijk niet slechts decoratief; moet dus duidelijk gedocumenteerd worden dat er sr-only iets wordt toegevoegd
Eigenlijk dezelfde wijzing als doorgevoerd in de accordion (http://localhost:3000/components/detail/accordion): 
```
<span class="sr-only">
  succes:
</span>

**Comment by timveld** [comment]
* Tekst: als het niet de bedoeling is dat deze in een gebruikerstoepassing komt en dit duidelijk is dan hoeft hij niet vertaald te worden, voorbeelden voor programmeurs moeten ook toegankelijk zijn maar de WCAG taaleisen strict toepassen gaat te ver ;-)
* Voor kleuren lijkt me dit inderdaad de oplossing

**Comment by PieterVerheij** [comment]
@timveld dan is hij goed zoals hij nu is.
