### ISSUE TITLE
Dropdown button toegankelijk maken

### ISSUE THREAD

**Issue by gofix** [dso-toolkit/dso-toolkit#663]
In de Tookit wordt de Dropdown button aangeboden:
https://dso-toolkit.nl/master/components/detail/dropdown-button.html

Deze is niet (goed) toegankelijk, zo is gebleken bij bestudering van de werkvorm in de Toolkit zelf (daar wordt ie ingezet voor de 'version selector', zie #591 ).

De dropdown button is gebaseerd op die van bootstrap, waar inmiddels al wel meer aandacht is besteed aan de juiste aria-attributen: https://getbootstrap.com/docs/4.0/components/dropdowns/.
een vorm met 'tussenkopjes' zoals bv. in de version selector komen we daar echter niet tegen, dus hier zal echt een eigen oplossing voor moeten worden gemaakt.

**Comment by gofix** [comment]
NB: in de Dropdown button zelf staan wel al de attributen `aria-haspopup="true" aria-expanded="true"`, maar deze zijn nog niet geimplementeerd in de version selector.

**Comment by tfrijsewijk** [comment]
Dat laatste komt door `uiv` (Vue componenten gebasseerd op Bootstrap 3): https://uiv.wxsm.space/dropdown Deze zet bovengenoemde attributen niet.

Geen excuus overigens, dit moet goed geregeld worden.

PS @gofix heb je deze bewust gesloten?

**Comment by PieterVerheij** [comment]
https://www.dso-toolkit.nl/_663.Dropdown-button-toegankelijk-maken/components/detail/dropdown-button.html

**Comment by timveld** [comment]
OK. 
h2 onder het uitgeklapte knopje is wat opvallend maar ik neem aan dat dit bedoeld is om er een andere kop neer te kunnen zetten, mag wel

**Comment by gofix** [comment]
Ik was nog even vertwijfeld over of het wel zo mag zijn dat er 2 lijstjes beide met hun `aria-labelledby` naar dezelfde button mochten verwijzen, maar krijg daar geen foutmeldingen over gemeld (als ik bv. met de squizlabs codesniffer check).

**Comment by PieterVerheij** [comment]
Inhoud uitklapper aangepast

**Comment by gofix** [comment]
Ik was even bang dat ik deze wijziging (die echt wel 'BREAKING' is, en ook als zodanig in de changelog staat) ons zou verplichten ook gelijk de versieselector zelf qua markup om te vormen. Immers: deze is nu nog gemaakt conform de voorheen voorgeschreven (bootstrap-gebaseerde) markup. Gelukkig blijken de changes ietsjepietsje minder BREAKING dan gedacht: omdat nog steeds bootstrap aanwezig is, toont de oude/huidige versieselector nog goed. Overigens gaan we deze natuurlijk nog wel aanpassen, want de ontoegankelijkheid daarvan (https://github.com/dso-toolkit/dso-toolkit/issues/591) was de aanleiding voor deze change!
