### ISSUE TITLE
tabs: mist aria 

### ISSUE THREAD

**Issue by timveld** [dso-toolkit/dso-toolkit#668]
Het tabs component (inclusief de tabbladen in de toolkit zelf) mist de juiste aria; het moet als tab strip worden gemarkeerd en het geselecteerde tabblad moet worden aangegeven (als ik me goed herinner is dit patroon gedocumenteerd in wai-aria)

**Comment by PieterVerheij** [comment]
https://www.w3.org/TR/wai-aria-practices/examples/tabs/tabs-1/tabs.html

**Comment by gofix** [comment]
Pull request ziet er goed uit, alleen denk ik dat dit typisch een component is waar implementatie informatie in het documentatie tabblad op z'n plek is (om developers erop te wijzen dat de geselecteerde tab `aria-selected="true"` moet krijgen, etc. etc.). Ik stel voor dat wij een voorzet doen voor deze toevoeging, en dan kunnen bv. @bramhoosemans en/of @timveld  dat reviewen.

**Comment by bramhoosemans** [comment]
> Ik stel voor dat wij een voorzet doen voor deze toevoeging, en dan kunnen bv. @bramhoosemans en/of @timveld dat reviewen.

Lijkt me prima.

**Comment by PieterVerheij** [comment]
@gofix Documentatie tekst aangepast.

**Comment by PieterVerheij** [comment]
https://www.dso-toolkit.nl/_668.tabs--mist-aria/components/detail/tabs.html

**Comment by timveld** [comment]
OK
