### ISSUE TITLE
dso.nl homepage valideert niet

### ISSUE THREAD

**Issue by timveld** [dso-toolkit/dso-toolkit#669]
Als ik www.dso-toolkit.nl valideer in de w3c validtor dan krijg ik 6 errors en een paar warnings die volgens mij aandacht behoeven. Zo te zien zijn het dingen die snel zijn te verhelpen.

**Comment by MichielDHVD** [comment]
@timveld  Ik krijg maar 1 error. https://validator.w3.org/ ik gebruik deze. Kun je misschien posten welke errors je allemaal krijgt ?

**Comment by PieterVerheij** [comment]
Verschillende branches geven verschillende resultaten. Maar uitgaande van de Master (https://www.dso-toolkit.nl/master/) komt er idd 1 fout uit die gecorrigeerd moet worden.

Overigens vindt CodeSniffer 0 fouten, maar de W3C validator lijkt mij hierin leidend.

**Comment by timveld** [comment]
Ik kreeg veel meer foutmeldingen maar was dan kennelijk op een andere branch, ik krijg nu maar 1 error over het style attribuut. Dit moet wel worden verholpen

**Comment by PieterVerheij** [comment]
https://www.dso-toolkit.nl/_669.dso.nl-homepage-valideert-niet/

https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.dso-toolkit.nl%2F_669.dso.nl-homepage-valideert-niet%2F

Document checking completed. No errors or warnings to show.

Used the HTML parser.

Total execution time 563 milliseconds.
