### ISSUE TITLE
Gutter width is 15px instead of 16px

### ISSUE THREAD

**Issue by TonD83** [dso-toolkit/dso-toolkit#67]
Gutter zou 16px breed moeten zijn volgens de specificaties. Dit staat ook netjes vermeld op: https://dso-toolkit.nl/unstable/docs/layout.html

Echter, ik zie dit nog niet verwerkt, in de voorbeelden wordt (nog?) de standaard Bootstrap 15px gutter gebruikt: https://dso-toolkit.nl/unstable/components/detail/layout.html 

![screen shot 2018-03-07 at 14 23 36](https://user-images.githubusercontent.com/18580063/37094428-2bc9bef0-2213-11e8-93df-521bf2f5a6aa.png)

**Comment by VolleMelk** [comment]
In https://github.com/dso-toolkit/dso-toolkit/issues/42#issuecomment-371127418 had ik al gevraagd of de gutter aangepast moest worden, ik heb hier geen bevestiging op gekregen.

Maar nu het zelfs in documentatie staat, vermoed ik dat dit toch wel de bedoeling is. Wij gaan 'm oppakken.

@MichielDHVD FYI

**Comment by TonD83** [comment]
Ik zag het, maar wilde dat issue niet 'vervuilen'. Top dat jullie het gaan oppakken.

**Comment by MichielDHVD** [comment]
Helemaal over het hoofd gezien of misschien weg gevallen in het maken van de andere dingen. Bedankt voor het aangeven en bedankt voor het oppakken.

**Comment by VolleMelk** [comment]
Fixed: https://www.dso-toolkit.nl/1.2.0-beta.0
