### ISSUE TITLE
Flexibele buttons in wizard / gebruik van <form>?

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#670]
Op dit moment zijn er enkele issues met de "wizard" van de Vergunningcheck en Aanvragen. De discussie loopt al een tijdje via Slack, maar goed om dit concreet te maken en een klap op te geven.

Issues:

1. Huidige button implementatie van de wizard staat buiten een `.form` class en dit maakt het geheel niet schaalbaar (columns breedte).

2. Het is op dit moment niet mogelijk een derde button op de regel te plaatsen. Bijvoorbeeld: links 'tertiaire' actie en rechts een 'secondaire' en 'primaire' actie.

3. Bug: bij validatie fouten moet er 2x op de button 'volgende stap' geklikt worden om de algemene foutmelding bovenin het scherm te tonen. Komt schijnbaar door onBlur / onClick gedrag van browser. https://stackoverflow.com/questions/17769005/onclick-and-onblur-ordering-issue

Oplossingsrichtingen:

- Huidige wizard binnen een `.form` class zetten.
- Pager component uitbreiden met zelfde button positionering als formulieren https://github.com/dso-toolkit/dso-toolkit/issues/611.
- Nieuw 'wizard' component aanbieden vanuit de DSO Toolkit.

**Comment by bramhoosemans** [comment]
Form pager wordt deprecated. DSO form buttons moet ook functioneren buiten een <form> of .form, maar heeft wel een .dso-multi-page of .dso-single-page nodig.

**Comment by gofix** [comment]
@bramhoosemans zo doen? https://dso-toolkit.nl/_670.Flexibele-buttons-in-wizard--gebruik-van-form/components/detail/buttons.html (afgezien van de spelfoutjes die we nog verbeteren, en de notatie van BREAKING in de changelog)
