### ISSUE TITLE
Forms en group input missen autocomplete

### ISSUE THREAD

**Issue by timveld** [dso-toolkit/dso-toolkit#671]
De voorbeelden in form en group input lijken niet te voldoen aan [WCAG succescriterium 1.3.5](https://www.w3.org/TR/WCAG21/#identify-input-purpose), omdat er geen autocomplete in de HTML staat. Dit moet toegevoegd en gedocumenteerd worden.

**Comment by PieterVerheij** [comment]
Handige link: https://www.w3.org/TR/html52/sec-forms.html#sec-autofill

**Comment by PieterVerheij** [comment]
@MichielDHVD je zou dit nog aanvullen

**Comment by PieterVerheij** [comment]
WIP: https://www.dso-toolkit.nl/_671.Forms-en-group-input-missen-autocomplete/components/detail/form.html

**Comment by timveld** [comment]
Lijkt me mooi alleen was me al eerder opgevallen dat NVDA de labels voor invoervelden meerdere keren herhaalde. De verklaring is simpel: in het voorbeeld hebben meerdere invoervelden hetzelfde id. Lijkt me beter dit wel aan te passsen zodat het voorbeeld ook valideert en ik zeker weet dat het alleen aan die dubbele id's ligt (voornaam werd 4 keer herhaald).

**Comment by PieterVerheij** [comment]
To do:
- definitie lijst velden met autocomplete
- stukje documentatie

**Comment by PieterVerheij** [comment]
@timveld In principe is het niet fout: er staan meerdere formulieren op de pagina. Maar ik zal ze prefixen zodat de melding niet meer voor komt.

**Comment by timveld** [comment]
@PieterVerheij  volgens mij moet een  id altijd uniek zijn voor de pagina, prefixen is een goede oplossing. Ik zie dat je op sommige plaatsen zowel id als name gebruikt, dat kan een goede optie zijn (zie [deze thread](https://stackoverflow.com/questions/7470268/html-input-name-vs-id) maar moeten we een consequente keuze in maken / goed documenteren. Ik denk dat ik alle voorbeelden bij de volgende zelfevaluatie door de validator heen ga halen, met het form zal ik dat na je komende update vast doen om zeker te weten dat we goed zitten.

**Comment by PieterVerheij** [comment]
We moeten er zeker naar kijken, maar dat valt niet binnen de scope van dit issue (autocomplete).

**Comment by MichielDHVD** [comment]
> @MichielDHVD je zou dit nog aanvullen

Je bedoelt een voorbeeld formulier? 

Ik dacht dat ik daarvoor een los issue moest aanmaken? Of wil je dat me dit issue meenemen? Ik heb het zo gedaan

**Comment by PieterVerheij** [comment]
@timveld  Issue #730 aangemaakt voor de dubbele id's

**Comment by MichielDHVD** [comment]
![Autocomplete](https://user-images.githubusercontent.com/36912722/90512998-4ab8f700-e15f-11ea-93b0-313fc1706dbe.png)

Deze velden zouden in voor het voorbeeld formulier mogen. Deze hebben allemaal een expliciet html attribuut gelinked.

**Comment by PieterVerheij** [comment]
@MichielDHVD aangepast!
