### ISSUE TITLE
Download icoon mogelijk vóór link

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#677]
https://dso-toolkit.nl/10.6.0/components/detail/anchor.html

![mijn-omgevingsloket-ingediend-verzoek-bijlagen--2](https://user-images.githubusercontent.com/598735/84992724-8ed05100-b148-11ea-9c1d-fea91da934f2.png)

**Comment by gofix** [comment]
Zou je dit dan ook als mogelijke vorm in https://dso-toolkit.nl/10.3.0/components/detail/buttons.html willen, @bramhoosemans, of zou je dit zelfs DE ENIGE vorm willen laten zijn?

**Comment by PieterVerheij** [comment]
Als button is het gewoon te doen met de modifier `download`.
![image](https://user-images.githubusercontent.com/25430835/85031839-70d21300-b17f-11ea-9e4c-24b4203a4c4c.png)

![image](https://user-images.githubusercontent.com/25430835/85031909-80e9f280-b17f-11ea-877d-f88fb3eb9f1d.png)

Als het een link betreft, zal er een uitbreiding van de css moeten komen waarbij met een extra modifier (bv. `dso-icon-append`) het icon met een `::before` ipv een `::after` voor de linktekst wordt gezet.

**Comment by bramhoosemans** [comment]
De wens is om ook bij een link het icoon ervoor te kunnen zetten. Dus indien een uitbreiding van de css nodig is, graag doorvoeren :)

**Comment by PieterVerheij** [comment]
Ok, gaan we doorvoeren. Maar dan wel met `prepend` ipv van 'append` :-)

**Comment by gofix** [comment]
Op zich is wat @PieterVerheij gerealiseerd heeft in orde, maar... ik vraag me af of het echt wel noodzakelijk is deze nieuwe class (`dso-icon-prepend`) te introduceren. Immers, als je als developer invloed kunt uitoefenen op welke markup je produceert, kun je prima het icoon gewoon in de link opnemen. Zie bv. https://dso-toolkit.nl/master/components/detail/anchor.html, waar in het voorbeeldje "ICON LABEL" de `<svg>` voor de linktekst in de `<a>` komt. 

Er bestaan weliswaar voor downloads en externe links shortcuts om op `<a>` elementen ZONDER expliciet een `<svg>` toe te voegen TOCH dat icoon te krijgen, maar die shortcuts bestaan eigenlijk alleen zodat de output die uit het CMS komt, en waar op de link dus alleen die `download` of `extern` class staat, er toch uitziet zoals beoogd. Als je die output op een andere manier in je applicatie wilt hebben zou je daar met de oplossing die Pieter nu voorstelt toch aan moeten manipuleren (immers: dan moet die `dso-icon-prepend` erbij op). Maar als je dan toch moet manipuleren, zou je ook die `<svg>` er wel bij in kunnen zetten!

Kortom: eigenlijk kun je dus nu al maken wat je wilt, en zouden er geen changes nodig zijn. Argumenten TEGEN deze nieuwe class:
- je wilt zo min mogelijk manieren om dingen te doen;
- we willen zo zuinig mogelijk zijn met modifier classes, want daarmee introduceer je ook de mogelijkheid tot willekeur ("nu maar ff links, want dat is mooier")

**Comment by gofix** [comment]
Argument VOOR:
- het is makkelijk. Veel makkelijker dan zo'n `<svg>` erin rammen, maar als het goed is, wordt dat toch al door javascript gedaan?

**Comment by bramhoosemans** [comment]
@gofix Wat mij betreft prima om developers zelf het icoon te laten toevoegen, zoals in het voorbeeld "ICON LABEL". Als er geen nieuwe class nodig is ben ik daar voorstander van. Zoals ik eerder al zei:

> De wens is om ook bij een link het icoon ervoor te kunnen zetten. Dus indien een uitbreiding van de css nodig is, graag doorvoeren :)

**Comment by gofix** [comment]
En, het is je duidelijk hoe je dit aan de developers kunt briefen? Voor de volledigheid, het moet dan dus zo:
![image](https://user-images.githubusercontent.com/2689559/85303102-57e09f00-b4aa-11ea-94c3-7d6a30e3b781.png)

**Comment by bramhoosemans** [comment]
Ja, dat had ik gezien. Lijkt me geen probleem.

Het enige wat me hierbij opvalt is dat de tekst met een spatie moet beginnen om ruimte tussen tekst en icoon te creëren. Is dat wenselijk?

**Comment by gofix** [comment]
Die spatie is inderdaad best een suffe vereiste. @daverhelst wat was daar ooit de gedachte achter?

**Comment by PieterVerheij** [comment]
We hebben naar de spatie gekeken. Die is nodig omdat er met css geen hook is om op de `<svg>` een margin-left of margin-right te kunnen zetten: tekst in de `<a>` is geen element, dus de `<svg>` wordt als enig element in de `<a>` gezien.
