### ISSUE TITLE
Strategie/beleid gebruik van alerts

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#680]
Strategie gebruik ‘role alert’ en/of ‘aria live region’ bij meerdere meldingen en toelichtingen op het scherm. Op dit moment gaat dit in de gebruikerstoepassingen nog niet goed. Bij het verschijnen van een nieuwe melding worden alle meldingen nogmaals voorgelezen. Strategie bepalen en documenteren in de toolkit voor juiste implementatie is alle toepassingen.

**Comment by bramhoosemans** [comment]
![1_verzoeken-verschillend-toestemmingstype](https://user-images.githubusercontent.com/598735/86122587-5f223100-bad8-11ea-9a4e-23313e37c732.png)
![2_verzoeken-verplichte-keuze](https://user-images.githubusercontent.com/598735/86122594-60535e00-bad8-11ea-962b-dd4c19297e16.png)
![3_verzoeken-verplichte-keuze--fout](https://user-images.githubusercontent.com/598735/86122595-60535e00-bad8-11ea-94c2-bb6176a7f870.png)

**Comment by tfrijsewijk** [comment]
ping @timveld

**Comment by timveld** [comment]
Ik heb een eerste stap gezet maar is nog niet uitgewerkt: https://jira.team-dso.nl/confluence/display/DSOUX/Aria+alert+strategie Ik volg de door @bramhoosemans  voorgestelde indeling in 4 meldingstypen.

**Comment by bramhoosemans** [comment]
Meldingen strategie is verder uitgewerkt, de strategie rondom gebruik ARIA role=alert, live-regions, etc. zal nog explicieter moeten worden gemaakt.

Voor wie mee wilt lezen én feedback wilt geven: https://docs.google.com/document/d/1x8HST2on-X-UQEfT7SoZLv3G8cDGza4qyz4-mqGn7-M/edit

**Comment by MichielDHVD** [comment]
Deadline Aanstaande Woensdag.

**Comment by Anto1nette** [comment]
Staat klaar om doorgezet te worden maar moet nog even langs Michiel (= vrij vandaag en morgen)

**Comment by MichielDHVD** [comment]
Documentatie is te bewonderen op de #680 branch. 

**Opmerking:** 
Afbeeldingen onder Form validatie zijn erg blurry. Die van meldingstrategie weer niet. Komt inconsistent over. 

De links naar alle respectievelijke pagina's:
https://dso-toolkit.nl/_680-Strategie-beleid-Alerts/components/detail/form.html
https://dso-toolkit.nl/_680-Strategie-beleid-Alerts/components/detail/alert.html
https://dso-toolkit.nl/_680-Strategie-beleid-Alerts/docs/fundament/inline-validatie.html
https://dso-toolkit.nl/_680-Strategie-beleid-Alerts/docs/fundament/meldingenstrategie.html
https://dso-toolkit.nl/_680-Strategie-beleid-Alerts/components/detail/banner.html
https://dso-toolkit.nl/_680-Strategie-beleid-Alerts/components/detail/modal.html

**Comment by gofix** [comment]
Inderdaad verschillen kwaliteiten van plaatjes nog wel wat, maar ik denk dat het goed is de huidige stand van zaken toch door te zetten. De documentatie is absoluut een verbetering (overigens heb ik zelf de vrijheid genomen nog wat details te tunen), en verdient het om opgenomen te worden. Verder verbeteren (ook van die plaatjes) kan altijd later nog.
