### ISSUE TITLE
Search Bar gebruiken om te filteren in een lijst

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#681]
Hoe zorgen we ervoor dat filteren in een lijst ook toegankelijk wordt ingezet? Voorbeeld opnemen en documentatie toevoegen.

Voortkomend uit https://github.com/dso-toolkit/dso-toolkit/issues/624

> Bovenstaande is nu verwerkt in #631, maar wat nu nog rest is dat we een oplossing moeten realiseren voor wanneer de search bar zonder expliciete submit ingezet wordt, en er dan een wijziging op de pagina plaatsvindt. Zoals bv. het geval is met de searchbar in de toolkit zelf die gebruikt wordt voor het filteren van de componenten. Mijns inziens zou boven de lijst van componenten een element moeten staan waarin het aantal resulterende componenten vermeld wordt. Dit hoeft op zich niet per se 'zichtbaar' - omdat de ziende gebruiker toch wel duidelijk ziet dat de lijst van componenten wijzigt - maar op zich is er ook weer niet heel veel op tegen.

Enkele voorbeelden uit de praktijk:
![Schermafbeelding 2020-06-19 om 15 20 21](https://user-images.githubusercontent.com/598735/85136910-a985f100-b240-11ea-9bbb-dd74b65ee7cf.png)
![Schermafbeelding 2020-06-19 om 15 20 50](https://user-images.githubusercontent.com/598735/85136923-adb20e80-b240-11ea-82d4-456c6bc0a51f.png)
![Schermafbeelding 2020-06-19 om 15 21 33](https://user-images.githubusercontent.com/598735/85136924-ae4aa500-b240-11ea-876e-e345f87704d1.png)
![Schermafbeelding 2020-06-19 om 15 22 03](https://user-images.githubusercontent.com/598735/85136925-ae4aa500-b240-11ea-919a-949fff3aa9f7.png)

**Comment by bramhoosemans** [comment]
5 minute design: altijd aantal resultaten noemen na gebruik filter. Zichtbaar of sr-only.

**Comment by PieterVerheij** [comment]
> 5 minute design: altijd aantal resultaten noemen na gebruik filter. Zichtbaar of sr-only.

Stiekem al een opzetje gedaan in https://www.dso-toolkit.nl/_682.Form-buttons-in-of-buiten-formulieren/components/detail/search-bar.html

**Comment by bramhoosemans** [comment]
Cool. Hoe flexibel is dit? Neem bijvoorbeeld zoeken in activiteiten, daar zouden we het label 'activiteiten' willen gebruiken om bij filteren het aantal resultaten te noemen.

![Schermafbeelding 2020-07-07 om 15 19 32](https://user-images.githubusercontent.com/598735/86787677-a2931700-c065-11ea-9150-e3c684ab33c6.png)

**Comment by tfrijsewijk** [comment]
Dat kan, maar dan treed je buiten het search bar component. Dit moet volledig worden geimplementeerd door de developer

**Comment by tfrijsewijk** [comment]
Ik weet niet of 't de bedoeling is trouwens. We kunnen een opzet maken dat Tim daar een oordeel over velt

**Comment by bramhoosemans** [comment]
Tekst beter beschrijven voor documentatie: Er zijn 2 werkzaamheden gevonden voor 'tank'.

**Comment by bramhoosemans** [comment]
Besproken tijdens refinement 16-07:

@PieterVerheij Voorbeeld maken waarbij resultaten gebruik filter 'buiten' het Search Bar component wordt weergegeven. Bijvoorbeeld Wizard stap 3 (activiteiten). Link doorgeven aan Tim om te testen.

**Comment by PieterVerheij** [comment]
@timveld zie https://www.dso-toolkit.nl/_693.Verplicht-geneste-fieldsets-eruit-halen/components/preview/wizard-stap-3.html

**Comment by timveld** [comment]
Als in overleg besproken is dit een goed ontwerp maar
* Er is een ongelabeled knopje na het zoekveld legen knopje, heeft waarschijnlijk te maken met inklappen zoekveld; in / uitklappen zoekveld lijkt me in deze wizard niet nuttig
* We moeten in documentatie aria alert benoemen die aangeeft dat er resultaten zijn en ddat je moet doortabben (komt in aria alert beleid)
* Als besproken vraag ik mij af of dit goed gaat als je activiteiten zoekt met woorden die elkaar uitsluiten (denk aan bouwactiviteit en milieuactiviteit samen selecteren) Volgens @DHvD-Michael komt dat in de praktijk niet voor, laat ik aan jullie over

**Comment by gofix** [comment]
@PieterVerheij fix jij dat malle knopje nog even?

**Comment by PieterVerheij** [comment]
Dat malle knopje is de verborgen zoekknop. Er moet dus een zinnig label opkomen.

**Comment by PieterVerheij** [comment]
Knopje is herlabeld: https://www.dso-toolkit.nl/_681.Search-Bar-gebruiken-om-te-filteren-in-een-lijst/components/detail/wizard-stap-3.html
