### ISSUE TITLE
Form met submit button in de wizard voor o.a. positionering buttons

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#682]
Op de development omgeving is `<form class="form-horizontal">` reeds toegepast om stylings issues weg te nemen in de wizard. Legend wordt niet gestyled als form niet wordt toegepast (had iets te maken met juiste toepassing van fieldsets).

De buttons staan momenteel nog buiten het form gepositioneerd. Wat resulteert in een HTML codesniffer fout: "Dit formulier heeft geen submit knop". Uiteraard kunnen we de buttons in het formulier opnemen; hebben we ook gelijk flexibele buttons zie https://github.com/dso-toolkit/dso-toolkit/issues/670.

Maar het is überhaupt de vraag of dit wenselijk is. Graag jullie expert review op de implementatie op development. (URL kan ik aanleveren)

**Comment by gofix** [comment]
Sinds vanmorgen zijn changes in het kader van #670 beschikbaar in de DSO Toolkit, versie 10.7.0. 

Daarin is de noodzaak weggenomen `.dso-form-buttons` in een `<form>` of `.form` op te nemen. Ook BUITEN een formulier kunnen nu dergelijke knoppen worden opgenomen: standaard worden deze uitgelijnd conform de 'multi-page' aanpak (dus de `btn-primary` rechts), maar door op de `.dso-form-buttons` te zetten: `.dso-single-page` lijnt het hele spul links uit. Het is maar waar de toepassing om vraagt.

Anyway: nog steeds is het natuurlijk good practice om de knoppen, als ze echt bij het formulier horen EN er ook echt een formulier op de pagina staat, ook daadwerkelijk IN dat formulier te plaatsen!

**Comment by gofix** [comment]
Als ik op de in slack genoemde voorbeeld URL kijk ( .../loket/aanvragen/nieuw/verzoek/nieuw/stap/1), zie ik inderdaad de `form.form-horizontal`. En als ik daarin de `.dso-form-buttons` opneem, krijgen we met een minimum aan markup bijna het gewenste resultaat (maar vooral ook: het resultaat dat in DSO Toolkit vastligt, dus met juiste buttongrootte, de correcte chevron etc.).

![image](https://user-images.githubusercontent.com/2689559/85410201-182bbd00-b567-11ea-8338-8277978dbf73.png)

Vergelijk: huidige markup (die ook nog in een `btn-group-wizard row` zit)
```<div class="wizard-next-button col-xs-12 col-sm-5 col-sm-push-5 col-sm-offset-2 col-md-3 col-md-push-3 col-md-offset-6">
  <button id="next-button" class="btn btn-primary " type="button">
    <span>Volgende stap</span>
    <svg class="di di-angle-right" aria-hidden="true"><use href="images/dso-icons.svg#angle-right"></use></svg>
  </button>
</div>```
met de in de Toolkit voorgeschreven markup:
```<div class="dso-form-buttons">
  <button type="button" class="btn btn-primary">
    <span>Volgende stap</span>
    <svg class="di di-chevron-right"><use href="images/dso-icons.svg#chevron-right"></use></svg>
  </button>
</div>```

**Comment by gofix** [comment]
Enige is dat de knoppenrij wat strak op de overige `.form-group`s staat. Ik denk dat we dus, net zoals nu tussen opeenvolgende `.form-group`s een marge zit, we die marge ook voor een `.dso-form-buttons`, volgens op een `.form-group` moeten forceren.

Vergelijk
```
.form-group {
  margin-bottom: 0;

  + .form-group {
    margin-top: $dso-form-group-margin;
  }
```

**Comment by gofix** [comment]
Verder, als we van 
`button type="button" class="btn btn-primary"`
maken
`button type="submit" class="btn btn-primary"`
dan valideert de pagina ook als helemaal toegankelijk.

Ik denk dat we dit (dus: neem indien mogelijk een submitknop op) als implementatie informatie moeten opnemen, en dat we deze best practice ook in de Toolkit moeten laten zien. Die `.btn-primary` zal in de meeste gevallen een `type="submit"` moeten zijn!

**Comment by bramhoosemans** [comment]
Super! Zoals afgestemd beide vormen behouden (`.dso-form-buttons` zowel binnen als buiten formulier toepasbaar).

Dit issue gebruiken om margin-top toe te voegen en documentatie/voorbeelden voor gebruik `type="submit"` uit te breiden.

Marge wordt enkel toegevoegd indien `.dso-form-buttons` in een formulier wordt gebruikt; mocht het in de toekomst ook wenselijk zijn marge toe te passen buiten het formulier kan dat altijd worden toegevoegd. In de huidige vorm zal de wizard overwegend uit `<form>` stappen bestaan.

**Comment by gofix** [comment]
We zien, nu we alles een beetje aan het uitwerken zijn, dat er nog wel meer punten zijn waarop de wizard afwijkt van de voorgeschreven markup voor formulieren. Met name missen er `<fieldset>`s. Die zeer waarschijnlijk de beoogde verticale marges zouden opleveren...

Voorstel: zullen we voor bv. deze 3 stappen in de wizard eens in grote lijnen de markup mbt. het form, de fieldsets en de buttons opzetten, om te zien of als dat helemaal conform toolkit gebeurt, dan de layout helemaal klopt?

![image](https://user-images.githubusercontent.com/2689559/85587923-80030600-b642-11ea-8145-00b535eda76d.png)

![image](https://user-images.githubusercontent.com/2689559/85587937-842f2380-b642-11ea-96e6-0554b2605bcd.png)

![image](https://user-images.githubusercontent.com/2689559/85587955-872a1400-b642-11ea-8796-1396db11e9f7.png)

Want, alhoewel de change waar @PieterVerheij mee bezig is weliswaar wsl. geen 'kwaad' kan, de vraag is of het wel echt nodig is als de markup verder klopt.

**Comment by PieterVerheij** [comment]
![image](https://user-images.githubusercontent.com/25430835/85746072-7b078a80-b706-11ea-9e09-3309a130570b.png)

fieldset + dso-form-buttons gaat goed


![image](https://user-images.githubusercontent.com/25430835/85745881-54e1ea80-b706-11ea-999c-b81b3bfe93dc.png)
searchbar in een form heeft te weinig marge.

![image](https://user-images.githubusercontent.com/25430835/85746241-9b374980-b706-11ea-89c3-746899eabd81.png)
form-steps + alert gaat niet goed (de form-steps staan onder de alert).

**Comment by PieterVerheij** [comment]
Door de geneste fieldsets en verborgen legend van de buitenste fieldset, wordt het wel een beetje een koppen feest (maar zo is het wel duidelijk dat het om Activiteiten gaat :))
https://www.dso-toolkit.nl/_682.Form-buttons-in-of-buiten-formulieren/components/detail/wizard-stap-3.html

**Comment by bramhoosemans** [comment]
Pff.. ik weet niet of iedereen hier blij van wordt. Of wel?

Ik zie nu naar geneste 'fieldsets' ook een extra laag met geneste 'rows'. Hebben we ze conceptueel allemaal nodig of kunnen we het simpeler maken @gofix wat denk jij? Ik verwacht namelijk dat we heel wat sr-only legends etc. gaan krijgen.

ps. de verborgen legend heet nu nog "Projectinfomatie" ipv activiteiten

**Comment by PieterVerheij** [comment]
> Ik zie nu naar geneste 'fieldsets' ook een extra laag met geneste 'rows'. Hebben we ze conceptueel allemaal nodig of kunnen we het simpeler maken @gofix wat denk jij?

Ik had eerste alles in een enkele row, alleen dan waren er float en clear issues.

**Comment by PieterVerheij** [comment]
@tfrijsewijk Het wordt nu een groot fieldset feest. Dat is niet wat je wilt. Zou jij hier je licht eens over willen laten schijnen?

**Comment by bramhoosemans** [comment]
In dit issue nemen we de controle op juiste implementatie `<form>` en button positionering in de wizard. Hiervoor zijn 3 voorbeeld stappen in de toolkit opgenomen.
- https://www.dso-toolkit.nl/_682.Form-buttons-in-of-buiten-formulieren/components/detail/wizard-stap-1.html
- https://www.dso-toolkit.nl/_682.Form-buttons-in-of-buiten-formulieren/components/detail/wizard-stap-2.html
- https://www.dso-toolkit.nl/_682.Form-buttons-in-of-buiten-formulieren/components/detail/wizard-stap-3.html

Discussie rondom buitenste fieldset eruit halen is opgenomen in https://github.com/dso-toolkit/dso-toolkit/issues/693

**Comment by PieterVerheij** [comment]
@bramhoosemans kunnen we dit issue dan als afgerond beschouwen en verder met #693 ?

**Comment by bramhoosemans** [comment]
Issue gesloten. Juiste implementatie `<form>` en button positionering in de wizard als voorbeelden opgenomen.
