### ISSUE TITLE
Tertiaire button en links te weinig contrast in Info component

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#686]
Tertiaire buttons en links zijn in het info component nog groen, zie https://dso-toolkit.nl/10.7.0/components/detail/info.html.

Dit hebben we in de Highlightbox laatst aangepast in een zwarte variant. Graag gelijk trekken met https://dso-toolkit.nl/10.7.0/components/detail/highlight-box.html

![Schermafbeelding 2020-07-03 om 10 09 40](https://user-images.githubusercontent.com/598735/86447258-5c604f80-bd15-11ea-8b40-65148dfda234.png)
![Schermafbeelding 2020-07-03 om 10 09 52](https://user-images.githubusercontent.com/598735/86447261-5d917c80-bd15-11ea-926e-2dd41e01df31.png)

**Comment by PieterVerheij** [comment]
https://www.dso-toolkit.nl/_686.Tertiaire-button-en-links-te-weinig-contrast-in-Info-component/components/detail/info.html
