### ISSUE TITLE
Email input niet verwerkt in de toolkit. 

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#687]
Er is een input type email beschikbaar die helpt bij het automatisch valideren van een veld. We hebben zelfs een voorbeeld van incorrecte veld validatie voor een email adres maar input type email wordt niet gebruikt. 
https://www.w3schools.com/tags/att_input_type_email.asp

Is het verstandig om voor deze pagina https://dso-toolkit.nl/10.8.0/components/detail/group-input.html overal waar emailadres staat dit ook zo toe te voegen?  

Lijkt met het correcte gebruik van de beschikbare html.

**Comment by PieterVerheij** [comment]
POCje: https://www.dso-toolkit.nl/_687.Email-input-niet-verwerkt-in-de-toolkit/components/detail/group-input.html
