### ISSUE TITLE
Tabellen op kleinere schermen goed weergeven. 

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#688]
Hoewel we nog niet bezig zijn met het responsive maken van de toolkit. Loopt team PR02 al tegen wat Toegankelijkheidsissues aan met tabellen. 

Namelijk dat tabellen niet horizontaal te scrollen zijn. De WCAG maakt hier expliciet een uitzondering voor. 

Dit valt op dit moment nog niet te testen in de toolkit omdat in de toolkit nog geen meta tag met viewport heeft. Waardoor de tabel altijd in zijn geheel getoond wordt en niet verkleind. Waardoor in de toolkit het scrollen van tabellen overbodig is. 

Pr02 probeert dit nu wel toegankelijk te maken, maar lopen tegen wat issues aan. Namelijk zodra de tabellen horizontaal scrollbaar worden gemaakt op kleinere viewports dan is dit het resultaat op grotere viewports. 

![image](https://user-images.githubusercontent.com/36912722/87303004-b382d300-c512-11ea-87e2-20f6a77dcccc.png)

Wat voor oplossingen hebben jullie voor dit probleem?

**Comment by bramhoosemans** [comment]
Hier bestaat al een issue voor, zie https://github.com/dso-toolkit/dso-toolkit/issues/491.

**Comment by MichielDHVD** [comment]
Oh ja helemaal over het hoofd gezien ik ga deze sluiten en bij het andere issue toevoegen.
