### ISSUE TITLE
Asap font doesn't look sharp

### ISSUE THREAD

**Issue by VolleMelk** [dso-toolkit/dso-toolkit#69]
Over de e-mail al eens aangegeven, nu op GitHub

Op mijn scherm lijnt het Asap font niet mooi uit op 16px:

![image](https://user-images.githubusercontent.com/9696261/37161318-9bd45fa4-22f2-11e8-8b8c-dffceff5f8fa.png)

Dit doet het ook op de font pagina van Google (https://fonts.google.com/specimen/Asap):

![image](https://user-images.githubusercontent.com/9696261/37161367-c0c67b1c-22f2-11e8-915e-48b7f0ef12e8.png)

Pas vanaf 20px ziet het er enigszins strak uit. Michael heeft hier op zijn scherm geen last van:

![image](https://user-images.githubusercontent.com/9696261/37161556-4f89e762-22f3-11e8-9374-7a1d6c7cef82.png)

![image](https://user-images.githubusercontent.com/9696261/37161658-9401cb1c-22f3-11e8-9097-1a9c2eb7a32c.png)

@MichielDHVD Willen jullie hier iets mee? Ik weet niet waar mijn e-mail van 27 februari naar Michael uiteindelijk terecht is gekomen.

Edit: In #14 zijn de Asap Font files en font declaraties onder handen genomen:
* `@font-face` definities zijn rechtgetrokken
* De nieuwste Asap is van Google fonts gedownload
* Verschillende font types (SVG, EOT, TTF, Woff en woff2) ipv alleen TTF.

De vorige versie zag er wel mooi uit (https://www.dso-toolkit.nl/1.1.0/) maar was een oudere versie:

![image](https://user-images.githubusercontent.com/9696261/37162046-8ce7de06-22f4-11e8-81ff-1413dded17b9.png)

**Comment by TonD83** [comment]
Ik heb hier inderdaad ook last van, ziet er niet strak uit bij mij in Chrome 64 op MacOS.

**Comment by DHvD-Michael** [comment]
Ik ga dit bespreken met Communicatie.

@Ton: Heb jij een Retina scherm? Ik kan het zelf niet reproduceren.


Op 8 mrt. 2018 17:23 schreef "Ton Dumans" <notifications@github.com>:

Ik heb hier inderdaad ook last van, ziet er niet strak uit bij mij in
Chrome 64 op MacOS.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/dso-toolkit/dso-toolkit/issues/69#issuecomment-371539059>,
or mute the thread

**Comment by gofix** [comment]
Zit het verschil misschien in Mac vs. Windows, en inderdaad retina vs. niet-retina? Op mijn (niet-retina!) Mac is het font vanaf 13px keurig, pas als het kleiner wordt dan dat beginnen e-tjes etc. dicht te lopen. 

Ik ken dit fenomeen ook met de Avenir en (Avenir Next), die ziet er op Windows, zeker op de kleinere maten, ook ronduit slecht uit. 

Het lijkt erop dat veel font producenten niet helemaal netjes alle platformen testen :(

**Comment by ton** [comment]
@Ton werkt niet als je @TonD83 bedoelt.

Ik heb geen retina scherm trouwens :P

**Comment by VolleMelk** [comment]
@MichielDHVD / @DHvD-Michael: Dit lijkt mij toch bug van de toolkit, ik zou er toch wel graag in versie 1.2.0 opgelost zien

**Comment by DHvD-Michael** [comment]
Melding gemaakt bij Communicatie. Bug wordt voor nu doorgeschoven naar v1.3

**Comment by VolleMelk** [comment]
Wat is de status van deze bug?

**Comment by DHvD-Michael** [comment]
Besproken met afdeling Communicatie; zij willen graag weten of het binnen
Asap kan worden opgelost; switchen naar ander font is niet wenselijk.

Kun je zodoende testen of met de oudere versie van Asap dit probleem
verholpen wordt?

2018-04-10 14:17 GMT+02:00 Thomas Rijsewijk <notifications@github.com>:

**Comment by Poofy83** [comment]
Ter informatie: https://github.com/google/fonts/issues/1190

**Comment by VolleMelk** [comment]
We gaan kijken of we oudere versies uit de GitHub fonts repo van Google kunnen halen: https://github.com/google/fonts

**Comment by VolleMelk** [comment]
Oudere versie gevonden in de vorm van een npm package `typeface-asap` versie 0.0.35. Nieuwere missen de hinting zoals in bovenstaand google/fonts issue.

https://www.npmjs.com/package/typeface-asap

Tevens wordt alleen nog de .woff en .woff2 aangeboden. Volgens caniuse.com https://caniuse.com/#search=woff en https://caniuse.com/#search=woff2 dekken we alle gewenste browsers
