### ISSUE TITLE
Voorbeeld pagina met componenten, Badge, Footnote, Cards, Searchbar

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#690]
In deze pagina staat vooral het cards element centraal maar ook andere componenten zijn meegenomen. 

Kleine issues die me opvallen (hebben geen directe aanpassing nodig):

- De dropshadow stroeft met huidige ontwerp van de toolkit. De versie zonder dropshadow werkt ook niet fijn, dan zijn er helemaal geen borders te zien
- Hoe is de spacing van de interactions neergezet? 

https://dso-toolkit.nl/_690-Componenten-in-voorbeeldpagina-1/components/preview/zoeken-in-lijst-cards.html

**Comment by MichielDHVD** [comment]
Ontwerp dat nu is opgeleverd met @bramhoosemans nagelopen. Dit is gedaan omdat het een pagina is die op dit moment niet echt bestaat. Maar wel duidelijk illustreert hoe het toolkit component in context gebruikt kan worden. 

Net als het badge en searchbar component. 

Aanpassing van de pagina volgt mogelijk in de toekomst wanneer cards is geimplementeerd in een gebruikerstoepassing.

**Comment by PieterVerheij** [comment]
> De dropshadow stroeft met huidige ontwerp van de toolkit.
MIsschien geen dropshadow en de cards uitlijnen met de rest van de content (padding links en rechts weg)?
![image](https://user-images.githubusercontent.com/25430835/88148342-c0808000-cbfe-11ea-8864-a7c2f6225f90.png)

> Hoe is de spacing van de interactions neergezet?
Het werkt met display: flex; maar wellicht dat we een ruimte tussen de items moeten forceren.

**Comment by MichielDHVD** [comment]
Ik denk dat die bevindingen in een apart issue opgepakt kunnen worden in dien nodig. We hebben nu in ieder geval een controle pagina om het na te lopen. 

Kan deze nog mee voor de release van vandaag?

**Comment by PieterVerheij** [comment]
Gaat @tfrijsewijk  voor zorgen :)

**Comment by tfrijsewijk** [comment]
Ik heb 'm merged, maar we moeten nog 'n keertje terugkomen om meer nunjuck features te gebruiken
