### ISSUE TITLE
Progress Indicator uitbreiden

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#692]
1. Zouden we hier een mooiere css only loader voor kunnen gebruiken? Zoals https://projects.lukehaas.me/css-loaders/ (tweede of derde?)
2. Bevinding Tim ook verwerken in Toolkit; tekst a.u.b. vervangen door alstublieft.
3. Schaalbaar maken; verschillende formaten wenselijk (min. 24 en 32px)
4. Twee varianten ondersteunen; onbepaalde tijd en bepaalde tijd (geldt ook voor de Progress Bar https://github.com/dso-toolkit/dso-toolkit/issues/696)

![Schermafbeelding 2020-07-17 om 14 38 20](https://user-images.githubusercontent.com/598735/87787004-3a99b900-c83b-11ea-8c7d-164e42d05f02.png)

**Comment by PieterVerheij** [comment]
@MichielDHVD @bramhoosemans Hebben jullie hier een sktch bestand van? Ik ben vooral benioeuw naar de dikte van de border van de loader bij een grootte van 24, 32 en 48px.

**Comment by PieterVerheij** [comment]
@MichielDHVD @bramhoosemans zie https://www.dso-toolkit.nl/_692.Progress-Indicator-uitbreiden/

**Comment by MichielDHVD** [comment]
Ik heb niet zo een twee drie een sketch bestand hiervoor. Bram mogelijk wel maar die is op vakantie.

**Comment by bramhoosemans** [comment]
Wat mij betreft zou het mooi zijn als de Progress Indicator volledig schaalbaar is (is dat mogelijk?). Dan kunnen we enkele veelgebruikte formaten als voorbeeld tonen (24, 32, 48px).

In het ontwerp had ik de dikte van de border afgerond op hele pixels; 2, 3 en 4px
[Spinner.zip](https://github.com/dso-toolkit/dso-toolkit/files/5027009/Spinner.zip)

**Comment by PieterVerheij** [comment]
Dan had ik de border diktes goed gegokt :). Maar schaalbaar gaat in die opzet niet lukken, want 32px gaat niet gelijk op met het oplopen van de border dikte ( 42 / 3 * 3 = 36, niet 32).

**Comment by bramhoosemans** [comment]
Klopt, ik had 2,67 afgerond naar 3px. Doordat we 8px increments gebruiken zal 36px niet voorkomen. Ik verwacht dat deze 3 formaten afdoende zijn hoor 👍

**Comment by PieterVerheij** [comment]
Dit is nog work in progress, ben met Thomas aan het broeden op een manier om de spinner voor bepaalde tijd instelbaar te maken (qua tijd). 
https://www.dso-toolkit.nl/_692.Progress-Indicator-uitbreiden/components/detail/progress-indicator.html
