### ISSUE TITLE
Verplicht geneste fieldsets eruit halen

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#693]
Voorkomend uit https://github.com/dso-toolkit/dso-toolkit/issues/682

_"Door de geneste fieldsets en verborgen legend van de buitenste fieldset, wordt het wel een beetje een koppen feest."_

Er is momenteel een buitenste fieldset nodig om de juiste styling op elementen in het formulier te krijgen. Dit betekent ook dat er op meerdere niveau's een legend moet worden toegevoegd. In praktijk zijn deze niet noodzakelijk om de structuur van de pagina te begrijpen.

In dit issue zorgen we ervoor dat het niet nodig is fieldsets te nesten.

**Comment by timveld** [comment]
Nu het zo beschreven is begrijp ik het beter. En ben het er uiteraard mee eens al is het maar omdat een fieldset niet misbruikt mag worden voor styling. Een fieldset moet alleen gebruikt worden om velden die bij elkaar horen te groeperen. 

Wanneer fieldset wel / niet gebruiken: in sommige gevallen is het verplicht / zeer wenselijk. Bijvoorbeeld om aan te geven dat meerdere radiobuttons bij elkaar horen of om het verschil tussen bezorg / factuur adres aan te geven. Ook als het formulier in meerdere stukken kan worden opgesplitst zou ik fieldset gebruiken, bijvoorbeeld in een pagina voor een vergunningaanvraag personalia - gegevens contactpersoon - adres vergunningaanvraag - geplande activiteit. Geneste fieldsets komen zeker voor (geslacht keuzerondjes binnen personalia) Bedenk wel altijd dat een fieldset extra informatie is die wordt uitgesproken / weergegeven dus alleen gebruiken als ze helpen om het formulier te begrijpen.

**Comment by PieterVerheij** [comment]
@timveld de buitenste fliedset met formlegend is verwijderd, zie o.a.
https://www.dso-toolkit.nl/_693.Verplicht-geneste-fieldsets-eruit-halen/components/detail/wizard-stap-3.html
https://www.dso-toolkit.nl/_693.Verplicht-geneste-fieldsets-eruit-halen/components/preview/form.html

**Comment by timveld** [comment]
Het gelinkte voorbeeld is goed, de overgebleven fieldsets zijn duidelijk en nuttig (is wel aan de implementator dus we moeten dit TZT goed documenteren)

**Comment by gofix** [comment]
@PieterVerheij begrijp ik nu goed dat eigenlijk de `fieldset` met `.dso-form-fields` nooit meer voorkomt cq. nodig is? Dat verdient dan wel een **breaking** vermelding in het changelog, lijkt me?

**Comment by PieterVerheij** [comment]
Inderdaad!
