### ISSUE TITLE
Ontbrekende Input types verwerken in de toolkit

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#694]
Er zijn verschillende input types die html 5 mogelijk maakt. Hieronder een lijst van welke al in de toolkit zijn opgenomen. Welke nog niet en als laatst erkende htm5 input types maar die niet essentieel zijn voor de toolkit. 

**Niet beschikbaar wel gewenst in de toolkit**
- [x] `<input type="date">`
- [x] `<input type="number">`
- [x] `<input type="password">`
- [x] ` <input type="url">`
- [x] `<input type="tel">` ? (ivm met verhaal thomas over ios toetsenbord) 
- [x] `<input type="submit">` ? (we hebben buttons maar als sec deze input wordt neergezet blijft de styling dan overeind?)

**Beschikbaar in de toolkit**
```
<input type="button">
<input type="checkbox">
<input type="email">
<input type="radio">
<input type="search">
<input type="text">
```

**Niet beschikbaar niet essentieel voor de toolkit**
```
<input type="datetime-local">
<input type="color">
<input type="file">
<input type="hidden">
<input type="image">
<input type="month">
<input type="week">
<input type="time">
<input type="range">
<input type="reset">
```

**Comment by MichielDHVD** [comment]
Onderzoek doen naar submit wat precies het gebruik is van deze input type en of het relevant is. Controle met screenreader input vs button.

**Comment by PieterVerheij** [comment]
Ik ga hier alvast mee aan de gang, kan later aangevuld worden.

**Comment by PieterVerheij** [comment]
@MichielDHVD 
De inputs voor invoer heb ik verwerkt in https://www.dso-toolkit.nl/_694.Ontbrekende-Input-types-verwerken-in-de-toolkit/components/detail/group-input.html

De submit-input heb ik verwerkt in https://www.dso-toolkit.nl/_694.Ontbrekende-Input-types-verwerken-in-de-toolkit/components/detail/buttons.html

**Comment by MichielDHVD** [comment]
Ziet er goed uit, enigste waar ik twijfels bij heb of we een input versie bij de tertiare knop willen plaatsen. Die knop heeft meer een link karakter dan submit karakter. 

Ik zou zelf eerder als practice will promoten dat een tertiare knop nooit als submit knop wordt gebruikt.

**Comment by PieterVerheij** [comment]
Weggehaald bij tertiaire knop.

Meenemen in deze release?

**Comment by MichielDHVD** [comment]
Voor mij prima

**Comment by tfrijsewijk** [comment]
Ik zie nu pas dat er een wens is voor `input[type="submit"]`, maar die kunnen we niet realiseren: `input` is een void element ("zelfsluitend element"). Dit element heeft dus geen inhoud. De tekst die je op een `<input type="submit">` ziet wordt met een `value` attribuut gezet.

Wij schrijven voor dat de tekst in een button altijd in een `<span>` wordt geplaatst. Dat is niet mogelijk met een `input`. Daarnaast betekent het dat we twee componenten moet ondersteunen voor wat feitelijk hetzelfde oogt en gedraagt.

@MichielDHVD: Vanwaar de wens om `input[type="submit"]` op te nemen? Is dit een overwogen beslissing?

**Comment by MichielDHVD** [comment]
Het is een standaard html element, het idee was om zoveel mogelijk common practice te ondersteunen. 

Maar ik was niet bewust dat dit in strijd is met hoe we normaal tekst in buttons verwerken en mogelijk tegenstrijdige opties geven. 

Dalijk bij refinement bespreken?

**Comment by MichielDHVD** [comment]
input type submit verwijderen. Geen dubbele methodes om buttons te plaatsen.
