### ISSUE TITLE
WCAG checklist accordion component

### ISSUE THREAD

**Issue by timveld** [dso-toolkit/dso-toolkit#695]
Let bij implementatie van het accordion op het volgende.
* Gebruik voor de uitklapbare knoppen <code>&lt;button&gt;</code>. 
* Geef deze knoppen een heading op het juiste niveau. 
  * Meestal is dat 1 niveau onder het niveau van de heading die boven het accordion. staat. Stel het accordion staat direct onder de paginatitel (dat is een <code>&lt;h1&gt;</code>). Dan krijgt de knop <code>&lt;h2&gt;</code>. 
  * In een genest accordion heeft de geneste knop een heading 1 niveau onder de heading van de bovenliggende knop. Stel de bovenliggende knop heeft een <code>&lt;h2&gt;</code> dan krijgt de geneste knop een <code>&lt;h3&gt;</code>. 
* Geef de knoppen het aria-expanded attribuut. Dit attribuut is voor screen readers noodzakelijk om te bepalen of de knop ingeklapt of uitgeklapt is.
* Zorg dat je javascript het aria-expanded attribuut op "true"zet bij het uitklappen en op "false"bij het inklappen. 
* zorg daarnaast dat je javascript de bovenliggende div van een uitgeklapte knop de modifier .dso-open meegeeft (zie html) en deze bij inklappen weer weghaalt. Daarmee zorg je dat het verschil tussen een ingeklapte knop en een uitgeklapte knop goed zichtbaar is. 
* Als via een modifier een status icoon wordt toegevoegd aan de uitklapbare knop (.dso-succes, .dso-warning, .dso-info of .dso-danger):
  * Geef in de tekst van de knop met een .sr-only span een tekstalternatief wat de betekenis van het status icoon in de context van dit  akkordion beschrijft. 
  * Voorbeeldtekst voor .dso-succes :  
"Informatie bouwwerkzaamheden <code> &lt;span class=&quot;sr-only&quot;&gt;(afgerond)&lt;/span&gt;</code>"

**Comment by DHvD-Michael** [comment]
Hallo Tim, je had gevraagd of ik de accordion WCAG checklist voor implementatie kon aanvullen. Ik heb even gekeken naar de huidige implementaties op de PRE omgeving. En wat documentatie opgezocht. Bijgaand mijn aanvullingen en bespreekpunten. 

In de basis volgt het jouw punten. Dit is al opgenomen in de toolkit-voorbeelden. Wellicht kan het ook tekstueel worden aangevuld in de documentatie:
- Zorg dat `<button>` tag voor het klikbare gedeelte in de accordion en aria-expanded attribuut worden gebruikt.
- Gebruik `aria-expanded="true"` als de accordion is opengeklapt. `aria-expanded="false"` als het is dichtgeklapt.
- Er zijn 4 status-modifiers beschikbaar: `.dso-succes`, `.dso-warning`, `.dso-info` en `.dso-danger` Als via een modifier een status-icoon gebruikt wordt in de accordion, let op dat een tekstalternatief wordt meegegeven die door een schermlezer wordt opgelezen, bijvoorbeeld bij `.dso-succes` : `<span class="sr-only">(afgerond)</span>`
- Zorg dat `.dso-open` gebruikt wordt voor de opengeklapte accordions. Hiermee verandert ook het uiterlijk van de accordion. 

Bespreekpunten:
- Willen we dat bij implementatie van een accordion, standaard het ARIA tablist patroon wordt gevolgd? Of willen we dat implementatoren hier zelf in kunnen afwegen? Ik zie nu namelijk een implementatie op bij de Check PRE van een accordion met `role="tablist"`.
- Bij de Viewer op PRE zie ik een implementatie van een accordion met `role="switch"`. ARIA switch wordt normaliter gebruikt bij een toggle-achtige interactie, zoals een checkbox voor dag- en nachtmodus. Is implementatie van een accordion met ARIA switch acceptabel voor jou?

Verder, wat mij is opgevallen, is dat de accordion bij de Check op PRE lijkt af te wijken van de best practices voor een ARIA tablist en bijbehorende ARIA tab:

Bij ARIA tab hoort `aria-selected="true"` te worden gebruikt.
Bij de implementatie van de accordion is hier `aria-expanded="true"` gebruikt. 
aria-expanded hoort te worden gebruikt niet in combinatie van een `role="tab"`.
Zie ook "supported states and properties" voor een ARIA tab: https://www.w3.org/TR/wai-aria-1.1/#tab

Voor een voorbeeld van een ARIA tablist met `aria-selected="true"`, zie: 
https://www.w3.org/TR/wai-aria-practices-1.1/examples/tabs/tabs-2/tabs.html

Als laatst heb ik ook de volgende best practice gevonden: Bij een accordion wordt `role="region"` in combinatie met `aria-labelledby` gebruikt om het opengeklapte accordion paneel te kunnen duiden als `landmark`. 
Heeft het duiden van een `landmark` voor een opengeklapte accordion jouw voorkeur?

Voor een accordion voorbeeld met `role="region"`, zie ook: 
https://www.w3.org/TR/wai-aria-practices-1.1/examples/accordion/accordion.html

**Comment by timveld** [comment]
Bedankt ik zal je items in de hoofdtekst verwerken 
MBT discussiepunten: 
* Aria tablist: dat is hoogstwaarschijnlijk verkeerd Aria gebruik, een accordion heeft niets met tabbladen te maken. 
* Aria switch: is ook verkeerd aria gebruik, open / dichtklappen kun je echt alleen met aria-expanded aangeven. 
* Region role: Een region moet een groot deel van een pagina zijn, geen harde richtlijnen voor te geven maar een paragraafje met een antwoord op de vraag (zoals een accordion vaak gebruikt wordt) is onvoldoende. In het voorbeeld wat je geeft gaat het om een flink formulier (waarom gebruiken ze daar geen fieldset?) maar ik zou een region role zeker niet standaard voor alle accordions willen voorschrijven. 
* Zijn er visueel nog zaken waar je op moet letten bij het implementeren van een accordion?

**Comment by DHvD-Michael** [comment]
Het volgende kan in een latere iteratie van deze documentatie mee. 
In aanvulling op onze discussie van net tijdens het toolkit overleg:

1.  Het lijkt mij goed om bij de implementatoren checklist voor accordions het volgende punt op te nemen: 

> Zorg dat je het ARIA patroon voor de accordion volgt, niet andere ARIA patronen. Zie: https://www.w3.org/TR/wai-aria-practices/#accordion

We hebben namelijk nu een tweetal implementaties op de PRE omgeving van een accordion die een ander ARIA patroon volgen, namelijk ARIA Tablist en ARIA switch.

2. Region role is optioneel binnen ARIA, maar wel geprefereerd. In de WAI-ARIA 1.1 documentatie staat hierover het volgende: 

> "Role region is especially helpful to the perception of structure by screen reader users when panels contain heading elements or a nested accordion."

Binnen DSO komen geneste accordions vaak voor binnen de Check. Het lijkt mij goed om de role region hierbij toe te passen. Dan kan een eindgebruiker via ARIA landmarks naar de opengeklapte accordion springen. 
Zie ook, onder de laatste bullet van deze link: https://www.w3.org/TR/wai-aria-practices/#wai-aria-roles-states-and-properties

**Comment by timveld** [comment]
* In de bronvermelding heb ik naar het WAI-Aria pattern verwezen en laten we dat doen voor alle componenten die zo'n pattern hebben. Daarnaast ook nog aangeven dat andere patterns niet gebruikt moeten worden lijkt me onnodige informatie, de verkeerde implementaties worden als het goed is binnenkort aangepast. 
* Ik zou het gebruik van regions niet op toolkit niveau willen voorschrijven. Succescriterium 2.4.4 blokken omzeilen behalen we al dankzij de heading structuur, regions voegen daaraan niet veel toe. Ze kunnen wel in de weg zitten als ze verkeerd gebruikt worden, ik heb wel eens frequently asked questions gezien die dit deden en dan is het effect dat de vraag 2 keer wordt voorgelezen. Misschien heeft het in bepaalde gevallen voordelen maar dat is dan aan de implementator, vind het moeilijk om een sluitende richtlijn te geven voor wanneer wel / niet.
