### ISSUE TITLE
Progress Bar uitbreiden

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#696]
- Twee varianten ondersteunen; onbepaalde tijd en bepaalde tijd (zie ook https://material.io/components/progress-indicators#linear-progress-indicators)

Openstaande vragen:
- Ontwerp aanpassen variant Viewer?
- Waar wordt deze al meer toegepast?

**Comment by PieterVerheij** [comment]
@bramhoosemans Wat gaan we met dit issue doen? Ik kan mij voorstellen dat we dit ook closen of komt er nog een ontwerpaanpassing?

**Comment by bramhoosemans** [comment]
Ik verwacht hier inderdaad een ontwerpaanpassing; @DjangoBlok?

**Comment by DjangoBlok** [comment]
@bramhoosemans , ik had deze op de agenda staan afgelopen dinsdag. 
Er is wat meer nodig dan een ontwerpje toevoegen als je het mij vraagt.

We zien in de Toolkit nu twee componenten
De Progress Bar en de Progress Indicator
De progress bar heeft documentatie, maar daar die loopt niet gelijk met de voorbeelden. Ik denk dat we eerst even moeten afstemmen wat we nu willen met deze componenten. Het is nu niet zo duidelijk wanneer je welke gebruikt. Prima om daar het voorbeeld van Material Design aan te houden. 
Hoe willen we het verschil tussen deze twee componenten definieren?
Mijn voorstel:
**Een “linear progress indicator”**
Vaak gebruikt om de voortgang van een sectie (paneel compleet scherm) weer te geven.
o	Onbepaalde tijd (bij voorkeur wel voorzien van een tekst bijv “document wordt geladen”) Deze moet dus nog worden toegevoegd. 
o	Met tijdsindicatie (nu uitgewerkt in de toolkit?)
**Een “circular progress indicator”**
Wordt vaak wat meer op element niveau gebruikt, om aan te geven dat de voortgang verbonden is met het betreffende element.
o	Onbepaalde tijd (nu uitgewerkt in de toolkit)
o	Met tijdsindicatie


Het lijkt erop dat de huidige uitwerking van de progress bar vooral bedoeld is om voortgang in een proces weer te geven (zoals stappen in een wizzard). 
Is dat zo? 

**Visueel**
In de viewer gebruiken we een in hoogte wat subtielere versie (8px hoog ipv 16).
Als we beiden willen laten bestaan kunnen we hetzelfde doen als bij de spinners. (Een medium 8px en Large versie 16px)
