### ISSUE TITLE
Versie selector voor pre-versie 10 toolkits

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#697]
Komt voort uit #591. De versie selector is aangepast naar een dropdown component, maar in deze vorm bestaat het component pas vanaf versie 10.

Dit betekent dat een versie ouder dan 10 geen versie selector geeft. Hier moet een alternatief voor worden verzonnen. Mogelijk kunnen we daar `<select>` voor gebruiken, zoals deze ook al werd ingezet.

**Comment by tfrijsewijk** [comment]
Ik bedenk mij nu pas dat dit issue pas opgepakt kan worden als er een release is uitgekomen met #698 is gedaan.. Dan pas kan ik de versie selector die nu wordt geinjecteerd worden vervangen. Ik schuif 'm een milestone op

**Comment by tfrijsewijk** [comment]
Testable!

Ik heb de version selector weer teruggezet naar de laatste versie zonder Vue. Verder heb ik vue.js en uiv.js uit de scripts injector gehaald waardoor deze dependencies ook niet meer worden ingeladen.

Versies tot en met `11.2.0` krijgen de oude `select` version selector. In IE11 en hele oude versies lijnt ie niet lekker meer, maar we kunnen tenminste weer terug navigeren naar nieuwere versies. Vanaf versie `11.2.1` wordt de version selector zoals deze is ingecheckt in de toolkit codebase gebruikt.

**Comment by bramhoosemans** [comment]
Top!

- Als ik het goed begrijp kunnen we er dus geen specifieke styling aan meegeven, zoals het component group-select.
- Uitlijning gaat inderdaad niet overal lekker, maar navigeren werkt :-)
- Waar komt 'Topic' vandaan? Ik zie hem ook op de versies pagina staan, maar in de nieuwe version selector noemen we dit 'Branche releases'.

**Comment by gofix** [comment]
Deze dus: 
![image](https://user-images.githubusercontent.com/2689559/96996342-0156a080-1530-11eb-97f6-30c682f2f7c4.png)
