### ISSUE TITLE
Huidige selectie in version selector markeren

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#698]
Er wordt nu gebruik gemaakt van een vue-bootstrap component om het dropdown menu te maken. Het DSO dropdown menu component is geen bootstrap meer, en verwacht modifiers die het component niet gebruikt. Omvormen naar een custom vue component waarmee wel de DSO markup kan worden gehonoreerd

**Comment by tfrijsewijk** [comment]
@bramhoosemans, @MichielDHVD en @timveld: Willen jullie eens een testrondje doen op https://dso-toolkit.nl/_698-version-selector/ ? Zodra je een versie selecteert krijg je wel weer de 'oude' version selector te zien, maar dit is in ieder geval genoeg om een eerste indruk te wekken.

**Comment by bramhoosemans** [comment]
Ziet er goed uit met een vinkje bij de huidige selectie 👍

**Comment by timveld** [comment]
Werkt goed. Ik kan geen versies voor 10.8.0 meer openen, is dat de bedoeling?

**Comment by tfrijsewijk** [comment]
Ja.. Maar dat jij daar niet achterkomt laat wellicht ook zien dat we daar een melding voor moeten maken ;-) Iets als "Voor eerdere versies ga naar de versie pagina"?

**Comment by bramhoosemans** [comment]
Scherp! In het originele ontwerp stond geen 'master', maar juist een link naar 'alle versies'.
Zouden we master niet bij de branche releases kunnen zetten?

![Schermafbeelding 2020-09-10 om 10 36 24](https://user-images.githubusercontent.com/598735/92702474-86577300-f351-11ea-8e4c-c50f7ddbe885.png)
