### ISSUE TITLE
Component 'dso-select' should not be removed

### ISSUE THREAD

**Issue by TonD83** [dso-toolkit/dso-toolkit#70]
Afgelopen dinsdag tijdens de demo door Thomas kwam ter sprake dat de **dso-select** mogelijk zou komen te vervallen nu er nieuwe **checkboxes** en **radiobuttons** zijn gespecificeerd. Dit is wat ons betreft niet wenselijk aangezien wij de dso-select markup in onze applicatie gebruiken. Weliswaar met custom styling zodat deze er uit zien zoals de checkboxes en radios zoals bij jullie bekend.

Wat ons betreft (dit ook met Michael besproken) zouden er dus niet alleen nieuwe radios en checkboxes moeten komen, maar zou ook de dso-select (single en multi) moeten worden bijgewerkt zodat we dit component als volgt kunnen blijven gebruiken:

![screen shot 2018-03-08 at 17 13 10](https://user-images.githubusercontent.com/18580063/37161903-3607e6e4-22f4-11e8-86af-93234f208b0d.png)

**Comment by VolleMelk** [comment]
Als ik naar #43 en #42 kijk zie ik precies de werkvormen gevraagd zoals in jouw ontwerp.

Het klinkt als dubbel werk om twee componenten te onderhouden die er visueel hetzelfde uit gaan zien.. En moet jij (@TonD83) niet vreselijk je best doen om de DSO Select hier naar te stylen?

**Comment by TonD83** [comment]
@VolleMelk Jawel maar dat is reeds gedaan omdat wij er vanuit gaan dat de dso-select er zo uit gaat zien. Er was geen enkel teken dat er op wees dat dit plotsklaps zou gaan verdwijnen in plaats van gerestyled zou worden.

**Comment by VolleMelk** [comment]
@TonD83:

Sorry voor de late reactie, maar ik wilde hier een goed onderbouwde reactie op geven.

Allereerst de geschiedenis van de (door ons "InfoProjects" genoemde) "DSO Select": Wij kregen begin oktober 2017 een ticket ingeschoten waarin wij een klikmodel moesten ombouwen tot herbruikbare componenten (http://ax0c48.axshare.com/#g=1&p=digitale_stijlgids_-_werkzaamheden_checken&c=1):

![image](https://user-images.githubusercontent.com/9696261/37282603-574bc876-25f5-11e8-910b-b8b0ee9b525d.png)

Het checken-klikmodel was een stappenplan om de gebruiker snel naar het juiste formulier te verwijzen, of te vermelden dat er geen verdere actie nodig is. Wat heel tekenend voor deze "beslisboom"-werkvorm is, zijn de grote keuze knoppen.

Semantisch gezien leent deze werkvorm zich om een formulier (`<form>`) met radio buttons (`<input type="radio">`). Het vraag/antwoord gedeelte is een los component geworden: de DSO Select (naar eigen inzicht hebben wij een checkbox variant gemaakt: de multiple).

Dan inhoudelijk: Jij geeft aan de DSO select in een formulier te hebben gebruikt. Met custom styling is het component in lijn getrokken om gebruikt te worden in een formulier. Je wilt niet dat het component komt te vervallen, omdat de markup al in componenten is gebruikt.

* De toolkit evolueert: De PO komt met nieuwe wensen, en niet alles is met de huidige markup te realiseren. Zoal aangegeven willen wij (de toolkit maintainers) het zo makkelijk en leuk mogelijk voor de implementatoren te maken. Markup changes zullen niet makkelijk worden geaccepteerd.
* Het lijkt mij dat voor de gewenste functionaliteit de verkeerde werkvorm is gebruikt: Een beslisboom vraag/antwoord component is als basis gebruikt voor een checklist.
* Ik weet niet of Michael de DSO select variant wil laten bestaan in de huidige vorm: Namelijk het doorwandelen van een beslisboom

Met bovenstaand in het achterhoofd zal de DSO select niet gestijld worden zoals een 'normale' checkbox/radio. Er zijn legio redenen, maar een paar:
* De DSO select werkvorm (en bijbehorende markup) heeft geen ruimte voor een begeleidende tekst en/of foutmelding. Wil je deze toch hebben, zal je zelf markup moeten verzinnen en breek je met de API die dso-toolkit beschikbaar stelt.
* Twee sets markuppen die visueel hetzelfde ogen is onwenselijk: Oplossingen die voor formulieren zijn gemaakt, moeten omgekat worden naar andere (niet-formulier) markup. Denk aan responsiveness, afbreken van teksten, error states en dergelijke
* Door de markup niet aan te passen maar wel visueel gelijk te trekken blijft de dso-select namespace bezet. Mocht er later toch een DSO select werkvorm wenselijk zijn, moet deze een andere naam krijgen
* Dubbele code moet worden onderhouden
* Kans op discrepenaties tussen de DSO select en standaard formulier radios/checboxen neemt aanzienlijk toe
* Aanpassingen die zowel mogelijk zijn op de standaard formulier radios/checkboxen EN de DSO select worden gelimiteerd.

Ja, het is vervelend dat markup aangepast moet worden. Maar op de lange termijn wordt iedereen er blijer van als je dit toch doet. Niet doen is het opbouwen van een technical debt.

Niet geheel on topic maar wel interessant: Ik probeer deze week de formulier changes te mergen met `1_2_0` en eind deze week uit te brengen in een nieuwe alpha. In deze release zullen ook de gewenste radios en checkboxes zitten. Een kleine waarschuwing, door de wensen van DSO waren we genoodzaakt markup van het formulier aan te pakken. Ik zal deze zo gedetailleerd mogelijk uiteen zetten, zodat het migratiepad zo soepel mogelijk is.

Lang verhaal kort: Je zal sowiezo aan de bak moeten om conform DSO Toolkit formulieren te genereren. Wellicht is het 't slimste om tegelijkertijd de DSO select in de huidig geimplementeerde vorm te laten vervallen voor de formulier radios/checkboxes.

/cc @MichielDHVD: Willen jullie nadenken over de DSO select werkvorm?

**Comment by MichielDHVD** [comment]
Gelezen en we gaan er naar kijken.

**Comment by VolleMelk** [comment]
Ik sluit deze issue, als er nog vragen kunnen die in deze issue of een andere. Als er al een nieuwe werkvorm van de DSO select komt, zal dit in een ander issue moeten
