### ISSUE TITLE
CHANGELOG link 

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#701]
Op dso-toolkit.nl moet een link naar CHANGELOG.md komen voor de huidig geselecteerde versie

**Comment by tfrijsewijk** [comment]
In #499 staat het ontwerp, hier een knipsel:

![image](https://user-images.githubusercontent.com/9696261/92924229-e6751480-f438-11ea-972b-d70ddf3dd739.png)

@bramhoosemans Zoals dit is ontworpen kan ik het niet maken: Menu containers kunnen geen pagina zijn, zie bv een aantal componenten in het menu links. Zal ik de tekst maar op de versie pagina plakken?

**Comment by bramhoosemans** [comment]
@tfrijsewijk Ja, is goed. Deze tekst met verwijzingen dan boven de versie-links zetten.
