### ISSUE TITLE
Anchor: tekstalternatief in voorbeelden onvoldoende duidelijk

### ISSUE THREAD

**Issue by timveld** [dso-toolkit/dso-toolkit#704]
Als gisteren besproken willen we misschien het voorbeeld met vermelding aantal zoekresultaten schrappen en enkele voorbeelden moeten worden aangepast. Zie hieronder de Anchor checklist: 

* Ga na of de tekst van de anchor link duidelijk is voor iemand die het bijbehorende icoontje niet ziet en geef eventueel een tekstalternatief. Voorbeelden om dit te illustreren:
* Stel je hebt een link "product" met rechts daarvan een vergrootglas. Visueel is duidelijk dat hier "product zoeken" wordt bedoeld, maar voor iemand die alleen de tekst "product" leest is dit niet duidelijk. Omdat het icoontje in dit geval essentieel is om de functie van de link te begrijpen raden we in dit geval aan de functie ook in de zichtbare tekst duidelijk te maken, bijvoorbeeld met de tekst "product zoeken".
* Stel je hebt een link "Google" met rechts daarvan een icoontje om aan te geven dat een externe website wordt geopend. Voor dit icoontje moet je een tekstalternatief geven maar omdat het icoontje niet essentieel is om te begrijpen wat de link doet hoeft dit tekstalternatief in dit geval niet zichtbaar te zijn. In zo'n geval kun je met een sr-only span een tekstalternatief voor screen reader gebruikers bieden, dus: Google <code>&lt;span class=&quot;sr-only&quot;&gt;(externe link)&lt;/span&gt;</code> 
* Als de anchor link verwijst naar een deel van de huidige pagina ('same page link') dan moet je dit voor gebruikers van screen readers duidelijk maken door "spring naar" sr-only voor de linktekst te zetten. Bijvoorbeeld: <code>&lt;span class=&quot;sr-only&quot;&gt;spring naar&lt;/span&gt; inhoudsopgave</code>

**Comment by daverhelst** [comment]
@timveld Ik heb de teksten bij de anchors aangepast naar voorbeeld hierboven, bij de externe links stond er al een tekst, wil je dat deze nog aangepast wordt of is hij zo al voldoende?

https://dso-toolkit.nl/_704.Anchor-zoekresultaten-en-voorbeelden/components/detail/anchor.html

**Comment by timveld** [comment]
Teksten die er nu staan lijken me prima alleen staat het voorbeeld met '4'er achter nog, dat betekent neem ik aan 4 zoekresultaten? Voorbeeld schrappen of dit in tekst (evt sr only) verduidelijken

**Comment by daverhelst** [comment]
Naar aanleiding van de opmerking van @timveld hierboven, heb ik de voorbeelden met de badges verwijderd.

https://dso-toolkit.nl/_704.Anchor-zoekresultaten-en-voorbeelden/components/detail/anchor.html

@bramhoosemans @timveld graag jullie goedkeuring

**Comment by timveld** [comment]
OK

**Comment by bramhoosemans** [comment]
Wat mij betreft prima.

**Comment by tfrijsewijk** [comment]
Merged!
