### ISSUE TITLE
Checklist attachment counter

### ISSUE THREAD

**Issue by timveld** [dso-toolkit/dso-toolkit#705]
Voorstel checklist attachment counter, graag checken. @DHvD-Michael  nog visuele punten waar we op moeten letten?   
* De sr-only tekst "bijlage"is een tekstalternatief voor de paperclip, neem deze dus op.
* Let op enkelvoud en meervoud: 1 bijlage, 2 bijlagen. Pas dit vanuit je javascript aan of gebruik eventueel de vorm bijlage(n).

**Comment by DHvD-Michael** [comment]
Voorstel lijkt mij prima. Qua visuele punten. Het paperclip icoon in het voorbeeld is grijs. Hiervoor moet een check met Bram plaatsvinden (zodra hij terug is) of dit in lijn is met het gebruik in de ontwerpen.

**Comment by timveld** [comment]
@DHvD-Michael  kun je daar dan een issue voor aanmaken zodat het op de radar is? De grijze paperclip is geen WCAG issue tenzij bijvoorbeeld contrast niet goed is, in het algemeen zijn visueel zeer duidelijke en contrastrijke iconen wenselijk.

**Comment by timveld** [comment]
Opgeleverd aan Antoinette
