### ISSUE TITLE
dso-toolkit.nl: tussenkopjes soort component worden niet voorgelezen

### ISSUE THREAD

**Issue by timveld** [dso-toolkit/dso-toolkit#708]
Zie bijvoorbeeld jumbotron, de kopjes jumbotron / jumbotron met button / jumbotron met image worden niet voorgelezen. 
Ik begrijp niet helemaal hoe dit werkt maar zo te zien maak je een html comment dat dan op de een of andere manier wordt uitgebreid tot een tekst. Het html comment wordt door de screen reader genegeerd maar de alternatieve tekst wordt blijkbaar ook niet doorgegeven...

**Comment by daverhelst** [comment]
Ik zie bij bijna alle "wrappers" een aria-hidden="true" staan. @timveld is het de bedoeling dat deze simpelweg weggehaald gaan worden?

Bij het component Indicatoren staat hij bijvoorbeeld niet. Gaat het daar naar wens?

**Comment by daverhelst** [comment]
ping @timveld

**Comment by timveld** [comment]
Ik kan "indicators" niet vinden maar die aria-hidden moet uiteraard weg. Aria-hidden is iets wat je alleen in heel zeldzame gevallen moet gebruiken en hier zeker niet.

**Comment by tfrijsewijk** [comment]
Merged!
