### ISSUE TITLE
Form, Group files: "Verwijderen" en "Vertrouwelijk selectievakje" refereren naar bestandsnaam met aria-describedby

### ISSUE THREAD

**Issue by timveld** [dso-toolkit/dso-toolkit#709]
Zonder visueel overzicht kan het onduidelijk zijn bij welk bestand de "vertrouwelijk" selectievakjes en "verwijder document" knopjes horen. 
Ik stel voor aan de checkbox vertrouwelijk en de button verwijder aria-describedby toe te voegen met verwijzing naar de bestandsnaam. Het effect daarvan is dat NVDA uitspreekt: 
"vertrouwelijk selectievakje niet geselecterd foto-en-schets1.pdf"
De hoofdreden dat ik dit niet met een sr-only in het label zelf wil doen is dat NVDA dan eerst de hele bestandsnaam zou uitspreken voordat selectievakje niet geselecteerd wordt gezegd. Dat haalt de vaart te veel uit de interactie want de bestandsnaam kan behoorlijk lang zijn. 

In dit geval kan het knopje "verwijder"worden genoemd, document kan uit het tekstalternatief omdat de bestandsnaam al wordt aangegeven. 

Zie ook https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-describedby_attribute

**Comment by tfrijsewijk** [comment]
@timveld: wat denk je hiervan? https://dso-toolkit.nl/_709-Group-files--bestandsnaam-aangeven-met-aria-describedby/components/detail/group-files.html

**Comment by timveld** [comment]
Helemaal goed, wordt voorgelezen zoals ik had verwacht!

**Comment by tfrijsewijk** [comment]
Merged!
