### ISSUE TITLE
Searchbar redesign

### ISSUE THREAD

**Issue by TonD83** [dso-toolkit/dso-toolkit#71]
**Menu** heeft het label 'ready', maar heeft toch nog wel wat aandacht nodig denk ik als ik dit zo zie:

![screen shot 2018-03-08 at 17 28 15](https://user-images.githubusercontent.com/18580063/37162793-6ed0624c-22f6-11e8-91e1-61c475ef6675.png)

**Comment by VolleMelk** [comment]
@TonD83 Ik vermoed dat dit van de unstable branch is. Hier zitten we een beetje in een grijs gebied wat betreft de labels.

Unstable is toolkit breed en heeft invloed op alle componenten. Hetzelfde geldt voor alpha releases. In beide gevallen kunnen we nog alle kanten op.

Labels hebben eigenlijk pas meerwaarde bij gefixeerde versies, hoewel we idealiter geen release uitbrengen waar een component niet het ready-label heeft, kan het voor test-doeleinden interessant zijn. Denk aan een applicatie-specifieke werkvorm welke in de applicatie nog in ontwikkeling is. Zolang een UX design nog niet definitief is, kan het in de toolkit nog geen 'ready'-vlag krijgen.

Alternatief is de funcionaliteit uit de release te halen en een versie opschuiven, maar dat zullen we per werkvorm bekijken en overleggen met de toolkit PO en werkvorm implementator.

Voor alle werkvormen die geraakt zijn door de button redesign uit #25 (zie comments) zal een nieuw ontwerp komen.

/cc @MichielDHVD

**Comment by MichielDHVD** [comment]
@VolleMelk 

![zoekbalk](https://user-images.githubusercontent.com/36912722/37697777-043ebc56-2cdf-11e8-9dc0-a43c802353b7.png)

De zoekbalk moet er als volgt uit gaan zien.  Het is een standaard formfield met een zoek icon. Deze functionaliteit bestaat al als ik naar bepaalde branches kijk. Plus als je op het zoek icoon klikt dan wordt natuurlijk de zoek actie getriggered. 

Ook was er sprake om de zoekbalk dynamisch te maken. Status 1 veranderd dan in 2 wanneer er op geklikt wordt. Maar dat is best veel werk en niet haalbaar voor nu. Maar het is handig om even de richting te vermelden waar de zoekbalk heen gaat. 

![zoekbalk in context](https://user-images.githubusercontent.com/36912722/37697783-12823658-2cdf-11e8-8497-e6e0fb44324e.png)

**Comment by DHvD-Michael** [comment]
Besproken met TonD83: werkafspraak is voor PI6 niet de zoekbalk te gebruiken vanuit de stijlgids. Zodoende kan deze bug worden doorgeschoven naar v1.3

**Comment by VolleMelk** [comment]
@MichielDHVD 
* Ik vermoed dat de dynamiek geen probleem is, ik zal aan @Poofy83 een opzetje vragen zodra 1.2.0 is opgeleverd.
* Kun je ook responsive ontwerpen leveren?

Ik heb deze issue opgeschoven naar 1.3

**Comment by MichielDHVD** [comment]
@VolleMelk 
Ja responsive ontwerpen aanleveren is mogelijk. Ik zal er in de toekomst rekening mee houden, wanneer het mogelijk nodig is bij een component.

**Comment by MichielDHVD** [comment]
xs (for phones - screens less than 768px wide)
sm (for tablets - screens equal to or greater than 768px wide)
md (for small laptops - screens equal to or greater than 992px wide)
lg (for laptops and desktops - screens equal to or greater than 1200px wide)

@VolleMelk Alle 4 de versies is het fijnste neem ik aan?

**Comment by VolleMelk** [comment]
In dit specifieke geval: graag.

Bij andere, meer geisoleerde componenten is er vaak 1 omslagpunt. Maar de header is zo druk bevolkt, die zie ik graag uitgewerkt.

**Comment by MichielDHVD** [comment]
Hier zijn de screens over hoe de zoekbalk in de header zich responsive gaat gedragen. 

1200 px and up 
![xl_screen_search_open](https://user-images.githubusercontent.com/36912722/39175580-fee87468-47aa-11e8-9b2c-983d9c1a1d3a.png)
![xl_screens_search_collapsed](https://user-images.githubusercontent.com/36912722/39175581-ff08c880-47aa-11e8-990c-98c2355483f9.png)
992 px and up
![l_screen_search_collapsed](https://user-images.githubusercontent.com/36912722/39175572-fe318474-47aa-11e8-8686-0eb95621589d.png)
![l_screen_search_open](https://user-images.githubusercontent.com/36912722/39175573-fe5046e8-47aa-11e8-93c7-1305ba53f023.png)

768 and up
![m_screen_search_collapsed](https://user-images.githubusercontent.com/36912722/39175574-fe6cdeb6-47aa-11e8-9de2-beb1115ed63d.png)
![m_screen_search_open](https://user-images.githubusercontent.com/36912722/39175575-fe873f22-47aa-11e8-8b41-336c45e13946.png)

768 and down
![s_screen_search_closed](https://user-images.githubusercontent.com/36912722/39175577-fea2992a-47aa-11e8-8858-1ba066a8b447.png)
![s_screen_search_open](https://user-images.githubusercontent.com/36912722/39175579-fec04c36-47aa-11e8-8b3a-34724f1ddc11.png)

**Comment by Poofy83** [comment]
@MichielDHVD Bedankt voor de ontwerpen, ik zie nog een aantal vraagtekens waarbij de belangrijkste waarschijnlijk is - uitgaanden van de 1200px en groter variant, wat gebeurt er zodra de hoofdnavigatie wordt uitgebreidt met meer items? Het toevoegen van 2 extra items zal de uitgeklapte versie van de zoeker al raken.

Dit "probleem" heb je in smallere versies opgelost door de zoekbalk te verplaatsen naar de regel waar ook het logo staat. Wil je dit niet altijd? Dan hoeft er ook niet lastig gedaan te worden om deze balk telkens te verplaatsen.

**Comment by MichielDHVD** [comment]
Sorry voor late reactie. Glipte er tussendoor. @Poofy83 

Jouw suggestie is inderdaad slimmer om toe te passen.  Dan blijft het ontwerp altijd consistent. Dus de zoekbalk mag op logo niveau komen. 

Zijvraag. Op dit moment staat inloggen heel hoog in de header. Ook is het lettertype niet goed, dit moet asap zijn plus het icoontje klopt ook niet. Als het goed is  hebben jullie een poppetjes icoon in de set die een tijd terug is geleverd.  Kan dit in deze story worden meegenomen?

**Comment by Poofy83** [comment]
Inloggen klopt inderdaad niet met bijgezonden ontwerpen. @MichielDHVD en @VolleMelk is er ooit gesproken over een inloggen component? Als dat het geval is dan zal de header hiervan gebuik kunnen maken.

**Comment by MichielDHVD** [comment]
Een developer vroeg naar de optie om een naam te veranderen. Hoe wordt dat verwerkt in de header. Moeten we hier een aparte issue voor aanmaken. Het staat wel op ongeveer dezelfde plek als de searchbar maar heeft andere functionaliteit. 

Als iemand namelijk inlogt komt er de naam van de ingelogde gebruiker te staan en een knop met uitloggen. Ik heb hier al een ontwerp voor. 

Vraag is willen jullie dit meenemen met dit issue of een andere aanmaken.

**Comment by VolleMelk** [comment]
Graag een nieuw issue

**Comment by MichielDHVD** [comment]
In de searchbar zit nu de animatie met het loepje. 

In de toekomst zal ik hier nog even naar kijken wat voor animatie het meest geschikt is. 

Maar vanuit de developers is er het verzoek om de animatie van de searchbar compleet uit te kunnen zetten. 

Als je bijvoorbeeld een modal opent. Dan zie je het modal openen en daarna de animatie. Dat leidt erg af. 

Daarom is gevraagd voor de optie om de animatie aan of uit te kunnen zetten.

**Comment by Emvium** [comment]
Is het niet slimmer om de animatie standaard uit te zetten en te activeren bij de toevoeging van een class. Ik denk namelijk dat de versie waar de animatie niet inzit vooral wordt gebruikt bij standaard zoek activeiten. 

Deze animatie was bedoeld voor de header om ruimte te besparen. Maar in andere zoekvelden is deze animatie dus niet nodig. 

Daarom is het denk ik makkelijker om een class te gebruiken om het aan te zetten ipv van uitzetten. 

Als dit tenminste mogelijk is.

**Comment by MichielDHVD** [comment]
Is het niet slimmer om de animatie standaard uit te zetten en te activeren bij de toevoeging van een class. Ik denk namelijk dat de versie waar de animatie niet inzit vooral wordt gebruikt bij standaard zoek activeiten.

Deze animatie was bedoeld voor de header om ruimte te besparen. Maar in andere zoekvelden is deze animatie dus niet nodig.

Daarom is het denk ik makkelijker om een class te gebruiken om het aan te zetten ipv van uitzetten.

Als dit tenminste mogelijk is.

(Ik had per ongeluk mijn andere github account gebruikt. Daarom zul je een mailtje met Emvium zien. Dit heb ik even snel aangepast)

**Comment by tfrijsewijk** [comment]
Tuurlijk, de animatie styling zal ik op `dso-animated` zetten. Is dat wat?

**Comment by MichielDHVD** [comment]
Dat is prima. Is deze issue dan afgehandeld? Plus waarom stond deze niet op het project board heb ik die over het hoofd gezien?
