### ISSUE TITLE
Group files: functioneel icoontje naast vertrouwelijk selectievakje zonder tekstalternatief

### ISSUE THREAD

**Issue by timveld** [dso-toolkit/dso-toolkit#710]
Als je een selectievakje vertrouwelijk aanvinkt dan verschijnt naast het selectievakje een waarschuwingssymbool met de functie te verwijzen naar de melding daaronder. Dit mag niet zonder een tekstalternatief te geven. Er zijn 2 oplossingsrichtingen: 
* de simpelste oplossing is dat we altijd de melding over de procedure bij vertrouwelijke documenten weergeven en dan kunnen we mogelijk aria-describedby gebruiken om deze te koppelen aan het selectievakje; je kunt naar meerdere dingen verwijzen
* Als we er toch voor kiezen de melding alleen weer te geven als het vakje wordt aangevinkt is de oplossing ingewikkelder. Tekstalternatief voor het icoontje en een alert. Sowieso minder stabiel dan een vaste melding maar het bespaart wel schermruimte. 

Bespreken in refinement.

**Comment by tfrijsewijk** [comment]
Lossen we dit ook op met de wijzigingen in #709? Ja, er staat een icoon wat nooit uitgeproken zal worden.. Maar in combinatie met het selectievakje en de verwijzing naar de bestandsnaam.. zijn we er dan niet al?

Wat dacht je anders van `<span class="sr-only">(Vertouwelijk document)</span>` naast de bestandsnaam? Maar met de wijzigingen van #709 in het achterhoofd wordt er wel erg vaak "vertouwelijk" opgelezen.

**Comment by tfrijsewijk** [comment]
ping @timveld

**Comment by timveld** [comment]
@tfrijsewijk  Nee #709 gaat over het verduidelijken van de relatie tussen het selectievakje en de bestandsnaam, dit issue gaat over de melding die verschijnt als je het selectievakje aanvinkt. 

Maar nu ik er verder over na denk: deze melding zal sowieso een aria alert moeten zijn omdat hij verschijnt in reactie op een gebruikersactie, dat is een documentatie punt. 

Het horen van de melding op het moment dat je het selectievakje aanvinkt is een op zijn minst volwaardig alternatief voor het zien verschijnen van een waarschuwingssymbooltje. 
Verder dient het waarschuwingssymbooltje om de relatie tussen het selectievakje en de melding visueel te ondersteunen. Ook hiervoor is echter een alternatief omdat de relatie ondubbelzinnig uit de tekst van de melding kan worden afgeleid. 

Dus bij nader inzien is mijn conclusie dat een expliciet tekstalternatief voor het waarschuwingsicoontje niet wenselijk is omdat met de alert en de tekst van de melding dezelfde informatie wordt overgebracht.
Daarbij is voor mij een belangrijke overweging dat het toevoegen van meer tekst die moet worden voorgelezen de interactie vertraagt en de gebruiker misschien juist in verwarring brengt.

In het licht van succescriteria 1.1.1 en 1.3.1 is dit echter een edge case, een andere expert zou hierover anders kunnen oordelen. Misschien moet ik stichting Accessibility om hun standpunt vragen om te voorkomen dat ze hier in de formele WCAG toetsing op afkeuren. 

We zouden als tekstalternatief ook (*) kunnen overwegen, dit is in documenten een veelgebruikte manier om dit soort voetnoten aan te geven. Ik ben daar niet voor omdat het de interactie vertroebelt zonder dat het echt wat toevoegt.

@DHvD-Michael het jij hier vanuit je WCAG kennis een mening over?

Ik wil dit graag donderdag bespreken, ik verwacht dat we het issue dan kunnen sluiten.

**Comment by timveld** [comment]
We gaan het vertrouwelijk icoontje geen direct tekstalternatief geven. Als het selectievakje wordt aangevinkt verschijnt er een alert die zal worden uitgesproken, dit is voor gebruikers die het icoontje niet zien al een voldoende aanduiding van relatie tussen selectievakje en melding. Deze relatie tekstueel nog extra onderstrepen verhoogt de complexiteit en voegt niet veel toe. Mocht iemand hier in een WCAG toetsing over vallen merken we het wel maar ik zou het zo goedkeuren.
