### ISSUE TITLE
Group select: aria-describedby gebruiken

### ISSUE THREAD

**Issue by timveld** [dso-toolkit/dso-toolkit#711]
Bij diverse voorbeelden staan toelichtingen als "kies tussen vleen en vis"Deze moeten dmv aria-describedby verbonden worden met betreffende invoervelden. Bij de multi select listbox kunnen we overwegen een hint toe te voegen hoe de screen reader gebruiker dit met het toetsenbord bedient maar daar moeten we eerst nader onderzoek naar doen.

**Comment by tfrijsewijk** [comment]
`select` met `aria-describedby` aan de helptekst koppelen.

>Bij de multi select listbox kunnen we overwegen een hint toe te voegen hoe de screen reader gebruiker dit met het toetsenbord bedient maar daar moeten we eerst nader onderzoek naar doen.

Kun je dit verder toelichten? Het lijkt erop alsof je verwacht dat de gebruiker wordt uitgelegd hoe om te gaan met een `select multi`, maar is dat niet out of scope voor DSO applicaties? Misschien wel applicaties in z'n geheel? Ik krijg op 'n site ook geen uitleg hoe mijn browser werkt.

Als het nou een custom element zou zijn, zou ik mij er meer in kunnen vinden. Maar dit is het standaard HTML5 `select multi` element.

Maar wellicht begrijp ik je verkeerd :)

**Comment by daverhelst** [comment]
@timveld ik heb alvast de `select` verbonden aan de helptekst doormiddel van een `aria-describedby`. Dit is hier te vinden/testen:
https://dso-toolkit.nl/_711.group-select-aria-describedby/components/detail/group-select.html

Kun je nog wel een extra toelichting geven op de vraag die Thomas hierboven heeft gesteld?

**Comment by timveld** [comment]
Aria-describedby: top, dat werkt

MBT de hint voor bediening van de multi select listbox: ik heb dat bewust voorzichtig gezegd en ben het in principe met Thomas eens dat we geen helpteksten bij standaard componenten hoeven te schrijven.  
De reden dat ik hier mee kwam is dat het met het toetsenbord verre van triviaal is om zo'n multi select listbox te gebruiken. Je moet control ingedrukt houden terwijl je met de pijltjes navigeert en op shift drukken om iets te selecteren. En als je de control loslaat en weer op een pijltje drukt verdwijnt de selectie. Voor de gemiddelde gebruiker niet te volgen.

Is dit component met de muis of het touchscreen eigenlijk wel intuitief? Gaat dit met spraakherkenningssoftware of oogbediening werken? Ik heb mijn twijfels. 

In het voorbeeld ligt het gebruik van selectievakjes veel meer voor de hand. Dit is alleen niet werkbaar als er veel opties zijn (denk aan een lijst waarin je meerdere landen wilt selecteren).
Maar de control toets ingedrukt houden terwijl je tientallen keren op een pijltje drukt werkt ook niet. Op desktop bestaat er een listbox / treeview  met selectievakjes, dat is geen standaard html component maar zoiets zou je voor deze situatie moeten hebben. 

Wordt de multi select listbox momenteel eigenlijk ergens gebruikt? 
Zo niet dan lijkt het me beter hem uit de toolkit te halen, voor het selecteren van een paar items uit een beperkt aantal mogelijkheden zijn selectievakjes altijd beter. 
Als er implementaties voorkomen waar een grote lijst nodig is zoals "meerdere landen uit de lijst selecteren"dan moeten we daar een ander component voor ontwerpen.

**Comment by daverhelst** [comment]
Kunnen we de "oplossing" in dit issue dan als behandeld zien? Het lijkt me dat DSO zelf nog moet bepalen of de multiselect optie wel wenselijk is, en aan de hand van de uitslag van die discussie kunnen we aan de hand van een nieuw ticket bepalen of hij verwijderd moet worden, of niet.

Mee eens @timveld ?

**Comment by tfrijsewijk** [comment]
Ik heb 'm voor nu gemerged. Ik ben het eens met Tim dat selectievakjes een beter alternatief is. Wat mij betreft halen we dit component uit de toolkit
