### ISSUE TITLE
group radios: realistisch voorbeeld van hints bij radio button group, aria-labeledby??

### ISSUE THREAD

**Issue by timveld** [dso-toolkit/dso-toolkit#712]
In de voorbeelden wordt als hint gegeven "kies een oneven getal"Maar een dergelijke hint is onzinnig tenzij je een toetsvraag wilt stellen, in dit geval zou je de oneven getallen niet weergeven. Het voorbeeld zou je moeten veranderen in iets als: "kies soort auto"- opties: benzine en disel - hint: "de meeste mensen kiezen benzine maar vanaf 50000 km per jaar is disel goedkoper". Dan is de vraag nog hoe je dit met aria-described aan de radio group koppelt.

**Comment by tfrijsewijk** [comment]
We zullen het voorbeeld realistischer maken. Wat denk je van `aria-describedby` op de fieldset? Ik denk dat `aria-describedby` op de `input[type=radio]` onrustig is.

We maken een voorzetje met de aria-describedby op de fieldset, dan kan jij jouw software een rondje laten draaien

**Comment by MichielDHVD** [comment]
@timveld Kun je hier even naar de reactie van Thomas kijken

**Comment by timveld** [comment]
Dit werkt heel mooi alleen in het laatste voorbeeld met opengeklapte toelichting wordt het label van de fieldset en de aria-describedby niet voorgelezen, gaat bij de andere voorbeelden wel goed. Weten we zeker dat de html valideert? Het label lijkt niet expliciet aan de fieldset gekoppeld te zijn. Als we zeker weten dat de html klopt dan moet ik dit verder onderzoeken.

**Comment by daverhelst** [comment]
@timveld ik heb het nogmaals bekeken, en de html valideert. Ik zie een aria-describedby staan op de fieldset, met hetzelfde id als die op de help text staat.
