### ISSUE TITLE
Pagination: Huidige pagina markeren met aria-current

### ISSUE THREAD

**Issue by timveld** [dso-toolkit/dso-toolkit#713]
In pagination moet met Aria worden aangegeven welke pagina op dit moment geselecteerd is.

**Comment by tfrijsewijk** [comment]
Hi @timveld,

De markup in het pagination component schrijft voor dat de huidig geselecteerde pagina geen `a` (anchor) is. De voorbeelden die ik op internet tegenkom plaatsen het `aria-current` attribuut elke keer op een anchor, maar ik kom er niet achter of dit verplicht is.

Ik heb hier een voorstel: https://dso-toolkit.nl/_713-Pagination--aria-current-ontbreekt/components/detail/pagination.html

De `aria-current="page"` staat op een `span` in de `li`. Wat denk je hiervan?

**Comment by timveld** [comment]
Dit wordt goed voorgelezen. Denk dat dit prima is, het lijkt mij niet logisch dat het element wat de huidige pagina aangeeft altijd een anchor moet zijn.

**Comment by tfrijsewijk** [comment]
Bedankt, merged into master
