### ISSUE TITLE
Clock Icon en Mail Icon toevoegen aan Toolkit

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#716]
Er is een vraag naar een Clock Icon en Mail Icon om te gebruiken in gebruikerstoepassingen. 

Icons worden aangeleverd door @Anto1nette

**Comment by Anto1nette** [comment]
Bij deze de iconen 'clock' en 'email'
[iconen_clock_email.zip](https://github.com/dso-toolkit/dso-toolkit/files/5069634/iconen_clock_email.zip)

**Comment by PieterVerheij** [comment]
https://www.dso-toolkit.nl/_716.Clock-Icon-en-Mail-Icon-toevoegen-aan-Toolkit/components/detail/icon.html
