### ISSUE TITLE
WCAG checklist badge

### ISSUE THREAD

**Issue by timveld** [dso-toolkit/dso-toolkit#718]
Voor de badge is er 1 punt, @DHvD-Michael nog visuele punten? En willen we onderstaand punt nog verduidelijken met voorbeelden en eventueel standaardformuleringen voor tekstalternatieven? 
  
* Gebruikers met een visuele beperking (waaronder kleurenblindheid) zien de kleur van de badge mogelijk niet (goed). Daarom mag de kleur niet van belang zijn om de informatie te begrijpen. Zorg dat de tekst in de badge ook los van de achtergrondkleur volkomen duidelijk is en alle informatie overbrengt.

**Comment by DHvD-Michael** [comment]
De documentatie tekst voor gebruikers met een visuele beperking lijkt mij prima. 

Het volgende moet wel besproken worden:
- Waarom heeft badge een eigen DSO class? `dso-badge`
- Waarom wijkt badge af met de achterliggende Bootstrap qua componenten en patronen?

Zoals wij het component "Badges" nu gebruiken, staat het in Bootstrap als het component "Labels".
Een badge wordt normaliter gebruikt om een aantal ongelezen of nieuwe items te laten zien.
De voorbeelden in de toolkit zijn echter label voorbeelden, zoals we hier in Github ook labels gebruiken als het label "type: documentation" of het label "accessibilty".

De gebruikte voorbeelden van Badge in de DSO-toolkit zijn de "Available variations" van het component voor Labels. 
Zie ook: 
https://getbootstrap.com/docs/3.3/components/#available-variations

Bootstrap documentatie over badges en labels:
https://getbootstrap.com/docs/3.3/components/#badges
https://getbootstrap.com/docs/3.3/components/#labels

Zodra we duidelijker hebben waarvoor de class `dso-badge` in de praktijk wordt gebruikt, dan kunnen we bepalen wat het gewenste patroon is. Hiermee kunnen we de voorbeelden en documentatie bijstellen.

**Comment by DHvD-Michael** [comment]
Ik zie nu dat in Bootstrap versie 4 het component label is opgenomen bij het component badge. 
Dit verklaart waarom in de DSO-toolkit voorbeelden voor labels gebruikt zijn bij badges. 
DSO-toolkit is gebaseerd op Bootstrap versie 3.3.7

In de DSO-toolkit zijn naast badges ook nog steeds labels in gebruik. We lopen daarmee eigenlijk nog steeds in lijn met Bootstrap versie 3.3.7.
Voor labels in DSO-toolkit, zie: https://www.dso-toolkit.nl/10.9.0/components/detail/label.html

Welke keuze willen we maken:

1. Bootstrap versie 3.3.7 voor badges en labels hanteren? Dan moet badge component worden hervormd tot het bijbehorende patroon. Zie: https://getbootstrap.com/docs/3.3/components/#badges

1. Bootstrap versie 4 hanteren? Dan wordt labels opgenomen in badges. Label component in DSO-toolkit moet dan worden uitgeschakeld. Verder, moet in de toolkit documentatie worden opgenomen dat we Bootstrap versie 4 dan als basis hanteren voor dit Badge component.

**Comment by timveld** [comment]
Daarnet besproken dat dit component gebruikt kan worden om een legenda te maken voor bijvoorbeeld een tabel of kaart, om aan te geven dat de kleuren een betekenis hebben. Het toekennen van betekenis aan een kleur mag niet omdat er veel (ook visueel werkende) gebruikers zijn die kleuren niet of moeilijk kunnen onderscheiden. Als je een kleur een betekenis zou geven moet je een tekstalternatief bieden, maar je mag ook een icoontje gebruiken en daarbij een sr-only alternatief geven. Hoewel kaartmateriaal formeel is uitgezonderd zou ik ook daar niet gebieden met enkel kleur markeren, je kunt een ondersteunend icoontje gebruiken of het gebied naast een andere kleur ook een ander patroontje (iets als kleine horizontale / verticale streepjes) meegeven. Als dit component inderdaad in legenda's gebruikt wordt moeten we hier een opmerking over toevoegen, graag volgende week nogmaals agenderen. We stellen de oplevering hiervan uit naar volgende week.

**Comment by timveld** [comment]
Opgeleverd. Misschien moeten we het later verduidelijken maar dat hangt van de verdere documentatie af.
