### ISSUE TITLE
Cards: selectievakjes verwijderen

### ISSUE THREAD

**Issue by timveld** [dso-toolkit/dso-toolkit#722]
De info knopjes moeten met een aria-describedby worden gelinkt aan de titel van de card. Het beste is waarschijnlijk om dat ook voor de selectievakjes te doen en deze een label te geven dat aangeeft wat de functie van het selectievakje is, dan is het consistent.

**Comment by bramhoosemans** [comment]
@timveld willen we dezelfde implementatie als bij group-files (aria) of een sr-only span?

**Comment by timveld** [comment]
Na wat onderzoek heb ik geconcludeerd dat we toch (consequent) moeten gaan voor de sr-only span in deze situatie.
* Het component heeft een label (dat moet de functie van het component omschrijven) en een description (dat is een toelichting). Voor de knop "verwijder X" hoort x bij het label en niet bij de description. Zeker omdat meerdere knoppen met hetzelfde label aanwezig zijn 
* Gebruikers van spraakherkenningssoftware hebben in deze situatie een groot belang bij een label inclusief de naam omdat ze dan kunnen zeggen "klik verwijder x", ik betwijfel of er een andere manier is om voor spraakherkenningssoftware de relatie duidelijk te maken.
* Een ander nadeel van de aria-describedby oplossing is dat bij mouse echo - NVDA functie voor 'voorlezen onder de muispijl' - de description niet wordt voorgelezen, dat geldt waarschijnlijk ook voor touchscreen interactie. Juist dan is deze extra hint belangrijk. 
* Dat het label nu erg lang kan worden is een nadeel en iets waar bepaalde testers mogelijk kritiek op gaan hebben. Maar bij nader inzien vind ik dat de impact daarvan niet groot is en dat de 3 voorgaande punten in ieder geval zwaarder wegen.   
* Het title attribuut gebruiken is geen goed idee, dat doet in NVDA hetzelfde als aria-describedby en dit attribuut is zeer omstreden. Een tittle en sr-only geeft dubbel uitspreken. Ik heb de titel van dit issue aangepast. 
We moeten dit dus ook in group files weer aanpassen. Steeds opletten dat het label klopt - bij de vertrouwelijk selectievakjes zou ik voorstellen vertrouwelijk &lt;sr-only&gt;: bestandsnaam&lt;/span&gt;. Bij de knopjes: "meer informatie over x" resp " Bij knopjes spatie als eerste teken sr-only deel en evt het woord over bij meer informatie.

**Comment by PieterVerheij** [comment]
Ik mis even waarom de selectievakjes verwijderd moeten worden, is dat tijdens de refinement besproken?

**Comment by timveld** [comment]
@PieterVerheij  ja in refinement besproken, deze selectievakjes worden niet gebruikt in implementatie als ik het goed heb onthouden. Als ze blijven dan moet de functie veel duidelijker uit het label blijken.

**Comment by gofix** [comment]
Ziet er goed uit volgens mij (althans, voor zover te 'zien', het betreft hier natuurlijk vooral een visueel verborgen tekst):
https://dso-toolkit.nl/_722.Cards--selectievakjes-verwijderen-en-info-knopjes-verduidelijken-met-beschrijvend-sr-only-en-title/components/preview/cards.html

Maar: dit tekstje is nu OOK nog als `title` attribuut opgenomen, voor 'zienden', I guess (want die weten anders niet wat die [i] betekent). @timveld stelt hierboven dat die `title` weg moet... Toch? Want (en dat herken ik) dan worden dingen soms dubbel voorgelezen...

**Comment by gofix** [comment]
En: We moeten dit dus ook in group files weer aanpassen. Toch, @timveld ? Of wordt dat een ander ticket...

**Comment by timveld** [comment]
Ja inderdaad ook in group files (weet niet of je dan een nieuw ticket wilt aanmaken of gewoon titel hiervan verandert)

**Comment by gofix** [comment]
En dan nog een vraag, die wellicht in bovenstaande niet expliciet genoeg gesteld is. Screenreaders kunnen na deze changes prima chocola maken van hetgeen aangeboden wordt, uit de voorgelezen (visueel verborgen) tekst gaat helemaal duidelijk worden wat de knop doet. Maar... hoe zit dit met 'ziende' gebruikers. Die begrijpen mogelijk niks van de [i] die in deze knop aangeboden wordt. Zou het icoon voor deze gebruikers niet eigenlijk juist WEL een title moeten krijgen (en dat dan wel {{aria-hidden}}) zodat het niet dubbel voorgelezen wordt? 

Als het icoon met een {{<img/>}} of op z'n font-awesome met een {{<i/>}} of {{<span/>}} zou zijn opgenomen, zou een {{title}} attribuut en een {{aria-hidden}} attribuut hier uitkomst bieden, maar omdat we natuurlijk de iconen met {{<svg/>}} maken levert dat een extra uitdaging: een {{title}} attribuut om een {{<svg/>}} wordt door browsers niet getoond als tooltip, daarvoor moet het als {{<title/>}} element IN de {{<svg/>}} staan.

Is dit nog iets om verder uit te diepen (@bramhoosemans , @timveld )

**Comment by bramhoosemans** [comment]
Wellicht goed om dit donderdag te bespreken. Het is voor mij niet meer helder wat de impact ervan is; het raakt meerdere componenten zoals de info-button, cards, group files, en ?

**Comment by bramhoosemans** [comment]
title attribuut van de tertiaire button afhalen en voorzien van sr-only.
