### ISSUE TITLE
Update Accordion documentatie

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#725]
Documentatie update aangeleverd door @MichielDHVD

**Comment by MichielDHVD** [comment]
Pull request is aangemaakt, maar er is 1 issue:

De link in Component in context. Die moet leiden naar een template pagina. Maar ik krijg dat niet voor mekaar.

Suggesties?

**Comment by tfrijsewijk** [comment]
@MichielDHVD: Ik heb een review gedaan: https://github.com/dso-toolkit/dso-toolkit/pull/726#discussion_r470575446

**Comment by MichielDHVD** [comment]
Aangepast
