### ISSUE TITLE
Accordion requires JQuery and bootstrap inclusion

### ISSUE THREAD

**Issue by legolas** [dso-toolkit/dso-toolkit#73]
These URI are required for the accordion to work,these dependencies should be automatically included:
* <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
* <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>

**Comment by VolleMelk** [comment]
Hi,

De toolkit is sinds versie 1.2.0 framework agnostisch: 100% CSS. React developers worden niet altijd blij van een dependency op jQuery. Vaak is er een beter alternatief, in de vorm van een React component. Hetzelfde geldt voor AngularJS, Angular en andere (SPA) frameworks.

In het specifieke voorbeeld van de accordion: Deze is een klein beetje anders geworden. De component library is ook niet meer interactief maar geeft statisch de verschillende states weer. Het is aan de implementator deze voorgeschreven markup te honoreren. _Hoe_ dit wordt gerealiseerd maakt de toolkit niet uit: Angular directives, React components of een klassieke server roundtrip: Het gaat om het DOM. jQuery is één van de vele manieren om dit te realiseren.

Toen de toolkit 0.8 (beter bekend als de fabricator variant) bij ons (InfoProjects) terecht kwam was er een dependency op jQuery. Deze dependency is een erfenis, en is niet meer aanwezig in 1.2.0.

Ideale wereld: React developers zouden de componenten omzetten naar React components. Op die manier is er in de React DSO wereld één waarheid. Komen er changes in de DSO Toolkit, is er maar één plek waar deze changes doorgevoerd hoeven worden. Als iemand zich geroepen voelt.. `github.com/dso-toolkit/dso-react` is nog vrij ;-) (Hetzelfde geldt voor de rest van het framework spectrum)

**Comment by VolleMelk** [comment]
Ik heb dit ticket gesloten omdat het gewenste werk niet opgepakt gaat worden, maar als er nog vragen zijn: schroom niet
