### ISSUE TITLE
In voorbeeldpagina formulieren kunnen dubbele id's voorkomen

### ISSUE THREAD

**Issue by PieterVerheij** [dso-toolkit/dso-toolkit#730]
Op de voorbeeldpagina komen (omdat verschillende formulier-vormen dezelfde content gebruiken) dubbele id's voor. Hier moet een oplossing voor worden bedacht.

https://www.dso-toolkit.nl/master/components/preview/form.html

**Comment by tfrijsewijk** [comment]
@PieterVerheij en @timveld: Wat denken jullie hiervan? https://dso-toolkit.nl/_730-In-voorbeeldpagina-van-formulieren-id-fix/components/detail/form.html
