### ISSUE TITLE
Search Bar gebruiken om te filteren in voorbeeld Wizard 3

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#732]
In het voorbeeld Wizard 3 ontbreekt de gewenste implementatie voor filterresultaten.

Het is met de huidige voorbeelden in het Search Bar component niet duidelijk hoe we dit het beste toe kunnen passen. Zie hieronder een screenshot van de huidige implementatie:

![Schermafbeelding 2020-08-18 om 15 03 53](https://user-images.githubusercontent.com/598735/90516451-4b07c100-e164-11ea-97ea-87fa14be66e6.png)

**Comment by PieterVerheij** [comment]
@bramhoosemans Wat verwacht je als uitkomst van dit issue: een stukje documentatie?

**Comment by bramhoosemans** [comment]
@PieterVerheij Ik verwacht een uitbreiding van voorbeeld Wizard 3 met gewenste implementatie van de filterresultaten. Ik zie nu nergens `class="dso-results" aria-live="polite"` oid terugkomen.

Zoals je ziet hebben ze het in de huidige opzet anders aangepakt. Met het voorbeeld kunnen we ervoor zorgen dat het direct juist wordt toegepast.

**Comment by PieterVerheij** [comment]
`aria-live="polite"` op label: https://dso-toolkit.nl/_732.Search-Bar-gebruiken-om-te-filteren-in-voorbeeld-Wizard-3/components/detail/wizard-stap-3.html

**Comment by bramhoosemans** [comment]
@timveld wat is wenselijk?

Huidige implementatie bevat een aparte sr-only melding met extra instructie. Deze kun je bekijken via https://pre.omgevingswet.overheid.nl/checken/stap/1 (vul locatie in en zoek werkzaamheid "tank").

"Er zijn 2 werkzaamheden gevonden voor 'tank'. Gebruik Tab om verder te navigeren."

In de toolkit stellen we nu voor een `aria-live="polite"` op het label te zetten. Hierdoor is er geen extra instructie beschikbaar en wordt er voorgelezen wat zichtbaar is op het scherm. Zie https://dso-toolkit.nl/_732.Search-Bar-gebruiken-om-te-filteren-in-voorbeeld-Wizard-3/components/detail/wizard-stap-3.html

"Er zijn 2 werkzaamheden gevonden voor 'tank'."

**Comment by timveld** [comment]
Ik zou hier de sr-only melding over de tabtoets behouden. Omdat de gebruiker geen selectievakjes ziet verschijnen weet hij anders niet hoe hij verder moet. Dit soort sr-only instructies gebruiken we alleen in uitzonderingssituaties maar dit is een voorbeeld waar het moet

**Comment by bramhoosemans** [comment]
Samenvattend; de huidige implementatie in de toepassing behouden. Extra instructie voor gebruik screenreader is in dit geval wenselijk, daardoor kunnen we niet `aria-live="polite"` op het label zetten.

Als iedereen het daarmee eens is kunnen we dit issue sluiten wat mij betreft.

**Comment by tfrijsewijk** [comment]
Ff dubbelchecken: De wijzigingen van Pieter worden dus niet meegenomen in de toolkit codebase?

**Comment by bramhoosemans** [comment]
> Ff dubbelchecken: De wijzigingen van Pieter worden dus niet meegenomen in de toolkit codebase?

Inderdaad. Die wijkt af van wat er nu gebouwd is én Tim heeft bevestigd dat de huidige implementatie (met extra instuctie) gewenst is.
