### ISSUE TITLE
Progress indicator zonder witte achtergrond, enkel onbepaalde tijd ondersteunen

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#734]
Is dit te fixen? Wens is om de Progress indicator op verschillende achtergronden te kunnen gebruiken.

![Screenshot from 2020-08-19 11-42-43](https://user-images.githubusercontent.com/598735/90730610-b5397680-e2c8-11ea-80bb-092e1e0717d8.png)

In refinement 20-08 besloten dat de Progress indicator enkel voor onbepaalde tijd laden kan worden gebruikt. Voor bepaalde tijd laden dient een Progress bar te worden ingezet.

**Comment by PieterVerheij** [comment]
De witte halve cirkel fungeert als masker. De enige oplossing - maar niet echt nette - die mij nu zo te binnenschiet, is varianten maken met verschillende kleuren. Ik ga er dieper induiken.

**Comment by bramhoosemans** [comment]
> De witte halve cirkel fungeert als masker. De enige oplossing - maar niet echt nette - die mij nu zo te binnenschiet, is varianten maken met verschillende kleuren. Ik ga er dieper induiken.

Daar was ik al bang voor. Misschien heb je hier iets aan https://material.angular.io/components/progress-spinner/overview

**Comment by PieterVerheij** [comment]
Die oplossingen is over te nemenvoor de continuous looping variant. Voor de variant met bepaalde tijd moet deze aanpast worden, om het vollopen goed te animeren en versies met verschillende animation-duration (1, 2, 5, 10, 30s, etc...) te maken.
