### ISSUE TITLE
Tekst 'beweeg de tabel van links naar rechts' verschijnt reeds voordat de tabel van links naar rechts bewogen kan worden.

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#735]
Is dit hoe het werkt? Doen we iets fout of is het misschien een iframe gerelateerd issue?
![Schermafbeelding 2020-08-20 om 09 45 35](https://user-images.githubusercontent.com/598735/90731589-288fb800-e2ca-11ea-85b4-5bfb143d5ab9.png)

**Comment by PieterVerheij** [comment]
dso-table-responsive luistert naar de breedte van de viewport en -pin mij er niet op vast- dat is een andere waarde dan de breedte van het iframe (die kan bv. viewport minus de breedte van een zijbalk zijn).

Wellicht is het beter om de andere variant (div.dso-table-scroll-container) te gebruiken, maar dan moet er gescript worden om de class erop te zetten:
Horizontal scrolling
Als het al bekend is dat een tabel in een smalle container wordt geplaatst, zoals in een menu naast een kaart kan de implementator het responsive scroll gedrag forceren met een wrapper div.dso-table-scroll-container.

**Comment by MichielDHVD** [comment]
Is gewenst gedrag, Pr12 gaat de class voorlopig verwijderen en bij mobile design wordt dit nogmaals bekeken.
