### ISSUE TITLE
Highlight box top margin aanpassen. 

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#738]
De Highlight box heeft een margin-top van 48px, dit is gedaan zodat het goed samenwerkt met de stappenteller. Alleen wanneer de stappenteller er niet is, is de margin veels te groot. 

Er is al een css selector die gebruikt kan worden waar de 48px margin top ondergebracht kan worden. 
<img width="253" alt="Screen Shot 2020-08-20 at 11 52 53" src="https://user-images.githubusercontent.com/36912722/90755736-c17aff00-e2db-11ea-86c8-6606f3e4417a.png">

Op de standaard highlight box kan dan een margin van 16px toegepast worden. 

Er moet wel opgelet worden met de dso-equal-heights row. Daar moet een css uitzondering voor gemaakt worden met de stappenteller highlightbox.

**Comment by tfrijsewijk** [comment]
Lokaal gemerged ivm merge conflicten: https://github.com/dso-toolkit/dso-toolkit/commit/1380bf3b2ef83da331787b630d1ab21accca17a8
