### ISSUE TITLE
Validatie teksten verplichte velden bij componenten

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#747]
Er bestaan verschillende teksten om aan te geven dat een verplicht veld niet is ingevuld. Joost maakt een voorstel dat we in de toolkit-voorbeelden en documentatie moeten verwerken. De verschillende teams kunnen vervolgens aan de hand van de toolkit-release de tekstuele wijziging doorvoeren.

**Inline validatie:**

“Vul dit veld in.”
“Maak een keuze.” (bij checkboxen, radio buttons en selecties)

**Samenvatting:**

“U moet de volgende velden nog invullen of verbeteren:”
“Vul in: [veld]"
“Verbeter: [veld]”

![validatie-formulieren](https://user-images.githubusercontent.com/598735/93588496-c949c400-f9ab-11ea-98fa-f91ebf36e499.png)

**Comment by gofix** [comment]
Ziet er goed uit, kijkend naarbv. https://dso-toolkit.nl/_747-validatie-veld-teksten/components/preview/group-input.html

Wat wel opvalt is dat nu soms de aanvullende `dso-help-block` teksten wat suffig combineren met de foutmelding. Maar dat lijkt me buiten scope van die issue.
![image](https://user-images.githubusercontent.com/2689559/93858232-1f747b00-fcbc-11ea-8072-ba741dd3c890.png)

Nu de 'verplicht'-aanwijzingsvalidatietekst bij een veld met een . eindigt, lijkt me het overigens wel zaak dat ook met andere aanwijzingsteksten te doen:
https://dso-toolkit.nl/_747-validatie-veld-teksten/components/preview/group-input.html

Want: "Vul dit veld in." (met punt)
Maar: "Ongeldig e-mailadres ingevuld" (zonder punt)

Zullen we dat maar WEL consequent maken @bramhoosemans ?

**Comment by bramhoosemans** [comment]
> Wat wel opvalt is dat nu soms de aanvullende `dso-help-block` teksten wat suffig combineren met de foutmelding. Maar dat lijkt me buiten scope van die issue.

Je bedoelt de voorbeeldtekst neem ik aan, niet de positie.

> Zullen we dat maar WEL consequent maken @bramhoosemans ?

Goed om dit in de toolkit gelijk te trekken. Al hebben we er in de praktijk niet altijd invloed op; verplichte invoer (regex) validatie wordt meegegeven bij de vragen.
