### ISSUE TITLE
Button modifiers do not work properly on anchors

### ISSUE THREAD

**Issue by VolleMelk** [dso-toolkit/dso-toolkit#75]
```html
<a href="#" class="btn btn-[primary|default|link]">Dit is een link-knop</a>
```

Bovenstaande markup geeft een verkeerd beeld:

![image](https://user-images.githubusercontent.com/9696261/37289397-e2a02d0e-2609-11e8-8f34-582b39af9f1b.png)

![image](https://user-images.githubusercontent.com/9696261/37289390-de2ebaec-2609-11e8-8d09-b513bc154733.png)

@MichielDHVD We gaan in ieder geval de verticale uitlijning fixen. Heb jij nog speciale wensen voor de `:visited` state?

**Comment by MichielDHVD** [comment]
Nee voor visited zijn er geen speciale wensen. Zodra een element op een pagina gestyled is als een button moet alle functionaliteit hetzelfde zijn als alle andere buttons. 

Dus bij een ahref met button styling heeft de button styling prioriteit en komt de visited state te vervallen.

**Comment by VolleMelk** [comment]
Fixed: https://www.dso-toolkit.nl/1.2.0-beta.0/components/detail/buttons.html
