### ISSUE TITLE
Inventarisatie stand van zaken responsive gedrag componenten

### ISSUE THREAD

**Issue by gofix** [dso-toolkit/dso-toolkit#751]
Als vervolg op #649 gaan we een inventarisatie maken van de stand van zaken mbt. het responsive gedrag van de bouwstenen in de Toolkit. 

"Responsive" is een breed begrip, hieronder vallen alle technieken die ervoor zorgen dat een website bruikbaar is op uiteenlopende apparaten. Over het algemeen is men het erover eens dat het belangrijkste aspect hiervan is dat een website op **verschillende schermformaten** bekeken en gebruikt moet kunnen worden. Een goed geïmplementeerd responsive gedrag draagt bij aan het kunnen behalen van enkele WCAG succescriteria, namelijk **1.4.10**: Reflow, en ook deels **1.4.4** Resize text. Wat ik ook wel eens voorbij heb zien komen in toetsingen is dat er op 1.4.12 werd gecontroleerd: dat betreft text-spacing: inhoud moet waarneembaar/bruikbaar blijven als een agent meer spacing forceert. Dat is overigens nog best lastig testen, er is geen browser waarmee je dat standaard kunt toepassen. Om die reden gebruiken we vaak een codesnippet om deze styling toch op de pagina los te laten.

Hoe testen we:
**1.4.10** https://www.w3.org/WAI/WCAG21/Understanding/reflow.html
We openen ieder component in standalone view (dus zonder menubalk en header en zo) op 1280 px, en zoomen naar 400%. Dan mag geen horizontale scrollbalk verschijnen. Iets dergelijks geldt voor vertical scroll, maar volgens mij hebben we geen werkvormen waarvoor dit vereiste zou gelden.

**1.4.4** https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-scale.html
Openen: standalone, zoom naar 200%, werkvorm moet dan nog steeds leesbaar en bruikbaar zijn.

**1.4.12** https://www.w3.org/WAI/WCAG21/Understanding/text-spacing.html
Openen: standalone, en we passen een stukje custom css toe op de pagina, middels de browser plugin 'stylish':
```
* {
  line-height: 1.5 !important;
  letter-spacing: 0.12em !important;
  word-spacing: 0.16em !important;
}
p {
  margin-bottom: 2em !important;
}
```

Wat leggen we vast:
1.4.10: of bij deze zoom er niet gescrolled hoeft te worden;
1.4.4: per viewport (320, 768, 1280) of er issues zijn;
1.4.12: per viewport (320, 768, 1280) of er issues zijn;
(dus: een tabel met 8 kolommen)
Per waarneming melden we GOED, FOUT, en/of opmerkelijk.

**Comment by gofix** [comment]
* Logo
* Kleuren
* Typografie
* Lay-out
* Favicon
* Illustraties
* Pdf-bestanden
* Zoeksuggesties
* Datum en tijd
* COMPONENTEN
* Accordion
* Alert
* Anchor
* Attachments Counter
* Badge
* Banner
* Breadcrumbs
* Buttons
* Cards
* Carousel
* Conclusion
* Definition List
* Description
* Dropdown Button
* Footnotes
* Form
  * Form Elements
    * Group Checkboxes
    * Group Confirm
    * Group Files
    * Group Input
    * Group Radios
    * Group Select
    * Group Static
    * Group Textarea
* Form Pager
* Form Steps
* Highlight Box
* Icons
* Image
* Info
* Info Button
* Jumbotron
* Label
* List Button
* Lists
* Logo
* Modal
* Navigations
* Pagination
* Panel
* Progress Bar
* Progress Block
* Progress Indicator
* Rich Content
* Search Bar
* Shopping Cart
* Table
* Tabs
* Tooltip
* Tree View
* Whitebox

**Comment by daverhelst** [comment]
https://docs.google.com/spreadsheets/d/19eZvX1o2ZAumc-D5uOixHvpS5jX8jijPpERO0qjD1k0/edit?usp=sharing
