### ISSUE TITLE
WCAG checklist breadcrumb

### ISSUE THREAD

**Issue by timveld** [dso-toolkit/dso-toolkit#753]
Ik heb 2 items voor de checklist
* Plaats de breadcrumb in een nav gebied met als aria-label "u bevindt zich  hier", dit maakt voor gebruikers die de breadcrumb niet zien duidelijk wat dit is
* Plaats het aria-current attribuut op de huidige pagina

**Comment by Anto1nette** [comment]
@timveld kun je me dit zoals alle voorgaande keren gewoon weer mailen? Dan zet ik het in confluence zoals we hadden afgesproken en niet hier. Dank je.

**Comment by timveld** [comment]
Opgeleverd aan Antoinette

**Comment by Anto1nette** [comment]
Deze mag gesloten
