### ISSUE TITLE
List button component uitbreiden

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#756]
List button uitbreiden met grotere padding, optionele extra body tekst en responsive weergave (vinkje) verbeteren.

![list-button-uitbreiden](https://user-images.githubusercontent.com/598735/93432712-32570c00-f8c6-11ea-83d1-ae94c5e2beac.png)

**Comment by gofix** [comment]
Ziet er goed uit volgens mij, https://dso-toolkit.nl/_756.List-button-component-uitbreiden/components/preview/list-button.html
- `.sublabel` is de optionele extra body tekst;
- de padding is nu 15px. Met randje erbij is dat natuurlijk 16px, maar ik weet niet precies of dat nu eigenlijk zo de bedoeling was, of dat het toch echt BINNEN de border moet tellen? @bramhoosemans ?
- als de bouwsteen bijzonder smal wordt, kan het natuurlijk voorkomen dat door niet af te breken lange woorden onderdelen over elkaar gaan lopen. Maar, ik denk niet dat dat tot de scope van dit issue behoort.

![image](https://user-images.githubusercontent.com/2689559/93857069-5053b080-fcba-11ea-86c9-fd843b26a176.png)

**Comment by PieterVerheij** [comment]
- de padding is nu 15px. Met randje erbij is dat natuurlijk 16px, maar ik weet niet precies of dat nu eigenlijk zo de bedoeling was, of dat het toch echt BINNEN de border moet tellen? 

Ik heb ervoor gezorgd dat de list-button even hoog (uit mijn hoofd 56px) was als in de voorbeeldafbeelding, dat betekent idd dat de padding dan 15px moet zijn.

**Comment by gofix** [comment]
@bramhoosemans  kun jij hierover uitsluitsel geven? Dit is altijd een verwarrend iets in ontwerpplaatjes, omdat het 'maatstaafje' visueel vaak OP de rand begint.

**Comment by bramhoosemans** [comment]
> * de padding is nu 15px. Met randje erbij is dat natuurlijk 16px, maar ik weet niet precies of dat nu eigenlijk zo de bedoeling was, of dat het toch echt BINNEN de border moet tellen? @bramhoosemans ?

Lijkt me prima, ik zie dat we het bij andere componenten ook zo doen.

In het ontwerp gebruik ik altijd inner-borders, dus krijg je hetzelfde effect (15+1px). Al kan ik niet zeggen dat dit altijd consequent voor alle componenten zo in ontwerp staat. Blijft een punt van aandacht ;)

> * als de bouwsteen bijzonder smal wordt, kan het natuurlijk voorkomen dat door niet af te breken lange woorden onderdelen over elkaar gaan lopen. Maar, ik denk niet dat dat tot de scope van dit issue behoort.

Mee eens. Dit geldt voor veel componenten, dus laten we een algehele responsive strategie afstemmen in https://github.com/dso-toolkit/dso-toolkit/issues/751
