### ISSUE TITLE
table communiceert active state niet naar screenreader

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#758]
Op een row can een class "active" geplaatst worden dit toont dat een row "actief" is 

<img width="1015" alt="Screenshot 2020-09-18 at 13 09 55" src="https://user-images.githubusercontent.com/36912722/93591246-44ad7480-f9b0-11ea-8dee-aaa673755bfa.png">

Maar dit wordt niet gecommuniceerd wanneer een gebruiker dit met een screenreader doorloopt. Er staat immers alleen een class op deze row. 

@timveld  is aria-current hier de juiste oplossing?

**Comment by timveld** [comment]
Zometeen bespreken, is me niet helemaal duidelijk hoe dit gebruikt wordt.

**Comment by bramhoosemans** [comment]
Oplossingsrichting: toevoegen aan th scope row doormiddel van sr-only "actief".
