### ISSUE TITLE
Documentatie bijgewerkt van alerts, modals, logo, kleuren, typografie, lay-out, illustraties en zoeksuggesties

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#760]
Documentatie pagina's meegeleverd in issue: 

- Buttons
- Iconen
- Illustraties
- Layout
- Logo
- Modals
- Status feedback
- Typografie
- Zoeksuggesties

**Comment by MichielDHVD** [comment]
@tfrijsewijk is zoveel documentatie pagina's in een keer een goed idee? Of is minder beter voor de kwaliteitscontrole staan alle frames goed etc. als ik een pullrequest aanmaak?

**Comment by gofix** [comment]
@MichielDHVD alle onderwerpen uit je beschrijving hebben inderdaad bijgewerkte beschrijvingen mogen ontvangen, behalve volgens mij: iconen en buttons

Ik ben zo vrij geweest de titel van dit issue aan te passen, en dat ook als changelog regel op te nemen.
