### ISSUE TITLE
Alert; WCAG verbeteringen

### ISSUE THREAD

**Issue by daverhelst** [dso-toolkit/dso-toolkit#765]
Na het gesprek over verschillende WCAG punten die beschreven staan in https://docs.google.com/spreadsheets/d/19eZvX1o2ZAumc-D5uOixHvpS5jX8jijPpERO0qjD1k0/, is een tweetal punten naar voren gekomen die opgelost moeten worden:

- De button staat nu in een `<p>`, deze uit het `<p>` element halen
- Status iconen hebben geen tekstalternatief

**Comment by daverhelst** [comment]
De status iconen worden nu met een modifier class op een ::before gezet. Maar hoe gaan we de tekstalternatieven neerzetten?

Een simpele span met sr-only, die "alert info", "alert danger" meldt? @timveld @gofix

**Comment by bramhoosemans** [comment]
Zoals besproken in refinement van 05-11: toevoegen `<span class="sr-only">Fout:</span>` als tekstalternatief voor status iconen.

- alert-danger > Fout:
- alert-warning > Waarschuwing:
- alert-success > Gelukt:
- alert-info > Opmerking:

**Comment by timveld** [comment]
Voorgestelde labels lijken me prima, ook goed om dit consistent te doen.
