### ISSUE TITLE
Onderzoek uitbreiding bootstrap grid

### ISSUE THREAD

**Issue by daverhelst** [dso-toolkit/dso-toolkit#766]
Na het gesprek over verschillende WCAG punten die beschreven staan in https://docs.google.com/spreadsheets/d/19eZvX1o2ZAumc-D5uOixHvpS5jX8jijPpERO0qjD1k0/, is naar voren gekomen dat er een responsive ontwerp gemaakt moet worden voor de alerts

**Comment by daverhelst** [comment]
Een eerste snelle opmerking (over buttons), wat nou als er meerdere buttons staan? Maar dat staat los van dit issue, aangezien het over de alerts gaat.

**Comment by MichielDHVD** [comment]
Onder elkaar in de "custom" wizard van PR12  zit deze implementatie al. 

![Uploading Screenshot 2020-10-28 at 15.00.16.png…]()

**Comment by bramhoosemans** [comment]
> Onder elkaar in de "custom" wizard van PR12 zit deze implementatie al.

Die gaan we er komende sprint uithalen; aangezien dit custom css is en we de positionering van de buttons vanuit de toolkit willen aansturen. Zie issue https://github.com/dso-toolkit/dso-toolkit/issues/682

**Comment by MichielDHVD** [comment]
Bij Alert stel ik de volgende wijzigingen voor: 

**Wijzigingen XS-viewport (<768)**

- Icoon moet boven de tekst komen te staan 
- Padding van 20px boven en onder 16px van maken. Bespaart verticale ruimte. Anders wordt de verdeling 16px boven en 20px onder (vanwege herindeling icoon). 

Alerts moeten ook kleiner op de pagina worden weergeven. Dus heeft een small-view class nodig om goed te renderen op kleinere plekken op een pagina. 
**Specificatie class Alert-small-view**
- Icoon moet boven de tekst komen te staan
- Paddings en margins gaan wel mee met viewport om consistentie te bewaren tussen elementen. Dus _geen_ 16px in small view verwerken

![Alert667](https://user-images.githubusercontent.com/36912722/104443024-2807fe80-5596-11eb-8738-6dcd18dd1c1f.png)

![Alert Link uitgelijnd 16px gutters](https://user-images.githubusercontent.com/36912722/104443087-3f46ec00-5596-11eb-8ddc-4b426bb3f916.png)

**Comment by bramhoosemans** [comment]
@MichielDHVD eens met de voorgestelde wijzigingen. Enige waar ik mee zit is dat de wijzigingen pas nodig zijn op een kleiner breakpunt ≤320px, en die hebben we nu niet... Om ze nu door te voeren op XS (≤768px) voelt niet goed.
![responsive-alerts](https://user-images.githubusercontent.com/598735/104564198-e9804b80-564a-11eb-80ea-2a17cdedaf96.png)

**Comment by MichielDHVD** [comment]
Wat vind je ervan om het breakpunt op 425px te zetten? Ik vind namelijk dat daar al aan de zijkant de ruimte onnatuurlijk groot is. (zie afbeelding) 

<img width="413" alt="Screenshot 2021-02-23 at 07 32 15" src="https://user-images.githubusercontent.com/36912722/108809542-5f13fb80-75a9-11eb-9264-b93520fe2459.png">

Als we het hier over eens zijn kunnen we denk ik vragen om een custom small class met alle specs die eerder zijn beschreven.  

_sidenote_ Mogelijk moeten we hier een definitie voor omschrijven / globale stelregel wanneer deze actief wordt. In overleg met IP )

**Comment by bramhoosemans** [comment]
@MichielDHVD Waar komt de 425px vandaan?

Uiteindelijk komt het erop neer dat we meer breakpoints nodig hebben. Op dit moment wordt het grid systeem gebruikt van Bootstrap 3.3.7. Deze is sterk verouderd. In de nieuwere versies zie je dat er een ≤576px wordt geïntroduceerd.

Ik denk niet dat we het wiel opnieuw moeten uitvinden, maar eens moeten overleggen met IP of we het grid systeem kunnen "upgraden".

https://getbootstrap.com/docs/5.0/layout/breakpoints/

```
// X-Small devices (portrait phones, less than 576px)
// No media query for `xs` since this is the default in Bootstrap

// Small devices (landscape phones, 576px and up)
@media (min-width: 576px) { ... }

// Medium devices (tablets, 768px and up)
@media (min-width: 768px) { ... }

// Large devices (desktops, 992px and up)
@media (min-width: 992px) { ... }

// X-Large devices (large desktops, 1200px and up)
@media (min-width: 1200px) { ... }

// XX-Large devices (larger desktops, 1400px and up)
@media (min-width: 1400px) { ... }
```

**Comment by MichielDHVD** [comment]
Dat is een 425px tussenmaat van verschillende maten. Visueel gecontroleerd met bepaalde voorbeeld pagina.s wanneer extra switches handig zijn. 

Maar 576 is meer dan prima naar mijn mening. 

@PieterVerheij @gofix Hoe kijken jullie tegen het upgraden van de breakpoints layout aan? Ik ben ook voor.

**Comment by MichielDHVD** [comment]
Er zijn meerdere plekken waar het gebrek aan een tussenmaat bij kleinere schermen naar voren komt. 

Bij de header is de volgende situatie mogelijk als je net onder xs gaat zitten. Ontzettend breed uitklap menu. 

<img width="763" alt="Screenshot 2021-02-24 at 13 50 01" src="https://user-images.githubusercontent.com/36912722/109003218-720cf580-76a7-11eb-858e-1f6c3a69be21.png">

Waarschijnlijk moet dit een eigen issue worden om dit te beslissen. Maar het heeft gevolgen voor menig responsive ontwerp dat we willen toepassen. Deze beslissing moet eerst genomen worden voordat we uberhaupt verder kunnen.

**Comment by MichielDHVD** [comment]
Er zijn meerdere mogelijkheden besproken. Wat duidelijk wel was is dat de toolkit bootstrap ontstegen is en veel verder is door ontwikkeld. 

Dus een ander systeem (mapping) was besproken. 
Of een nieuwere bootstrap grid variant. 

Maar het meest praktische was om een extra grid optie toe te voegen met een breakpoint op 576px.

**Comment by gofix** [comment]
In grote lijnen hebben de media-queries effect op 2 aspecten: lay-out en vormfactor. 

Met **lay-out** bedoel ik de plaatsing van onderdelen op de pagina ten opzichte van elkaar: dus dat bv. in een large viewport in formulieren label en input naast elkaar staan, maar in kleinere viewports onder elkaar (zie bv. https://dso-toolkit.nl/21.1.0/components/preview/wizard-stap-1.html)

Met **vormfactor** bedoel ik dat binnen een component onderdelen van dat component anders worden in verschillende viewports, zoals bv. in het menu, https://dso-toolkit.nl/21.1.0/components/preview/navigations.html

Lay-out wordt over het algemeen bestuurd met de `.row` en `col-*-*` classes. Met name op complexere pagina's kan dit vrij gedetailleerd gebeuren, zie bv. de homepage waar we `col-lg-2 col-md-4 col-sm-6 col-xs-12` tegenkomen: https://dso-toolkit.nl/21.1.0/components/detail/homepage.html. NB: row en col worden zoals we weten ook soms oneigenlijk gebruikt, namelijk voor het aanbrengen van verticale ruimte tussen componenten, maar daar brengt release 21.0.0 verandering in.

De `lg`, `md`, `sm` en `xs` keywords bepalen in bootstrap het 'grid' en hoe dat varieert per breakpoint. In de gebruikte (3.x) bootstrap versie is het niet heel triviaal hier andere of extra keywords aan toe te voegen. NB: de breakpoints zoals nu effectief zijn:
```
// Extra small screen / phone
$screen-xs-min: 480px !default;
// Small screen / tablet
$screen-sm-min: 768px !default;
// Medium screen / desktop
$screen-md-min: 992px !default;
// Large screen / wide desktop
$screen-lg-min: 1200px !default;
```
(en daaruit volgen dan weer `$screen-xs-max`, `$screen-sm-max` en `$screen-md-max`)

Maar... als ik dit issue goed lees lijkt dat misschien ook helemaal niet nodig, want de gewenste detaillering voor Alert betreft niet zozeer lay-out, maar juist vormfactor! Momenteel komen we bv. de inzet van `$screen-xs-min` tegen in de navbar:
```
    @media (max-device-width: $screen-xs-min) and (orientation: landscape) {
      max-height: 200px;
    }
```

Eerlijk gezegd krijg ik dus het idee dat we hiermee de oplossing al in handen hebben. We kunnen de andere positionering van de onderdelen van Alert gewoon ophangen aan `$screen-xs-min`. Enige vraag is dan nog of we daarvan de waarde van de huidige `480px` zouden moeten wijzigen naar de genoemde `576px` of het eerder voorgestelde `425px`. Omdat `col-xs-*` classes al in gebruik zijn voor lay-out, is dat misschien niet raadzaam: daarmee verleg je echt het breakpoint voor dat gedrag.

**Comment by bramhoosemans** [comment]
Interessant :-) Als ik het goed begrijp hebben we zelf een `xs` breakpoint gedefineerd op 480px. 

Dit komt volgens mij niet overeen met Bootstrap 3.3.7 (https://getbootstrap.com/docs/3.3/css/#grid-media-queries) én documentatie van de layout (https://dso-toolkit.nl/21.1.0/docs/fundament/layout.html). Maar we hoeven in dat geval geen extra kenwords toe te voegen aan het grid systeem, en enkel de documentatie bij te werken!

Over de **layout** vs **vormfactor**. Misschien bedoelen we hetzelfde, maar ik zou het iets anders omschrijven: Er zijn breakpoints voor kleine optimalisaties en breakpoints die de weergave van schermen én componenten totaal veranderen.

**Grote breakpoints (xs, sm, md en lg)**
* Zorgen voor een totaal andere layout;
* Kunnen het aantal kolommen aanpassen;
* Kunnen de volgorde van elementen veranderen;
* Kunnen zorgen voor grote design aanpassingen, bijvoorbeeld dat de navigatiebalk veranderd in een hamburger menu.

**Kleine breakpoints (specifiek binnen een component)**
* Geen grote verschuivingen van elementen;
* Kleinere design aanpassingen zoals de grootte van het lettertype, de regelhoogte en de hoeveelheid witruimte.

**480 of toch 425 of 576px?**
Ik denk niet dat we de waarde van de huidige `480px` moeten wijzigen. Na een klein onderzoek, en dit mooie artikel https://ricostacruz.com/til/css-media-query-breakpoints, ben ik ervan overtuigd dat `480px` prima te gebruiken is voor het uiteindelijke optimalisatie doel (portrait weergave van mobiele telefoons).

**Comment by gofix** [comment]
Ik weet niet of wij dat breakpoint xs expliciet zelf hebben gedefinieerd. Ik zie dat we in https://github.com/dso-toolkit/dso-toolkit/pull/880/files, waar we de relevante files uit bootstrap opeten in de toolkit-codebase, dat daar het comment bij is gekomen 
```// Extra small screen / phone
$screen-xs-min: 480px !default; //** Deprecated `$screen-xs-min` as of v3.2.0, only used in _navbar.scss
```
@daverhelst kun jij je daar nog iets over herinneren?

**Comment by MichielDHVD** [comment]
Dit lijkt inderdaad precies wat we nodig hebben. Hoeven we ook geen speciale small class te introduceren. 

3.2.0 dat is wel flink geleden.

**Comment by bramhoosemans** [comment]
Documentatie van kleinste breakpoint meenemen in https://github.com/dso-toolkit/dso-toolkit/issues/977. Nieuw issue aanmaken voor responsive alerts.

**Comment by MichielDHVD** [comment]
Met oplevering #977 en issue alert is aangemaakt deze kan gesloten worden.
