### ISSUE TITLE
Banner; WCAG verbeteringen

### ISSUE THREAD

**Issue by daverhelst** [dso-toolkit/dso-toolkit#767]
Na het gesprek over verschillende WCAG punten die beschreven staan in https://docs.google.com/spreadsheets/d/19eZvX1o2ZAumc-D5uOixHvpS5jX8jijPpERO0qjD1k0/, is het volgende naar voren gekomen

- Status iconen hebben geen tekstalternatief

**Comment by PieterVerheij** [comment]
Volstaat het toevoegen van een `sr-only`, net als bij de status iconen in de accordion: https://www.dso-toolkit.nl/master/components/detail/accordion.html?

**Comment by bramhoosemans** [comment]
Zoals besproken in refinement van 05-11: toevoegen <span class="sr-only">Fout:</span> als tekstalternatief voor status iconen.

alert-danger > Fout:
alert-warning > Waarschuwing:
alert-success > Gelukt:
alert-info > Opmerking:

**Comment by gofix** [comment]
Dit lijkt me nog niet goed @daverhelst , het tekstje komt nu VOOR de sluit-knop:
![image](https://user-images.githubusercontent.com/2689559/98909261-dec9fe80-24c1-11eb-80db-887338ab5032.png)

Dat lijkt me niet ideaal voor een screenreader.

**Comment by daverhelst** [comment]
Ik had hem bewust op de plek gezet waar het icoon ook staat. Maar ik begrijp dat dit liever voor de rich-content (of er in?) staat?

**Comment by bramhoosemans** [comment]
Actie sluiten als laatst.

**Comment by gofix** [comment]
@timveld kun jij naar https://dso-toolkit.nl/_767.Banner-WCAG-verbeteringen/components/preview/banner.html kijken of je banner nu als voldoende toegankelijk en logisch beoordeelt?

**Comment by timveld** [comment]
Ik heb 2 opmerkingen:
* het tekstalternatief "fout:" staat volgens NVDA op een aparte regel. Ergens in de code wordt kennelijk een line break veroorzaakt en dat lijkt me niet helemaal logisch. 
* Dit ontwerp garandeert niet dat de banner als zodanig te onderscheiden is van de rest van de pagina. Als dit component in een pagina wordt ingevoegd is het voor iemand die de banner niet ziet niet zonder meer duidelijk dat het sluitknopje deze tekst verbergt, en het onderscheid tussen banner en pagina is puur visueel. Dit kun je afvangen met de juiste headings of misschien een landmark? Ik moet hier nog eens goed over nadenken, waarschijnlijk ligt hier een verantwoordelijkheid voor de implementator en moet ik dit documenteren. Donderdag graag agenderen.

**Comment by tfrijsewijk** [comment]
![image](https://user-images.githubusercontent.com/9696261/99644776-a17be880-2a4e-11eb-9c86-e3074c9284d0.png)

De `span.sr-only` staat naast een `p`, misschien dat NVDA het daarom als nieuwe regel ziet

**Comment by timveld** [comment]
Ja dat is vrijwel zeker het probleem

**Comment by timveld** [comment]
Als besproken is een heading boven de banner nodig, vooral omdat het sluitknopje anders geen context heeft. Het voorstel is nu om bovenaan de banner een h2 te zetten die goed beschrijft wat de banner bevat, zoals "systeemfout". Het sluitknopje krijgt in dat geval sr-only tekst "sluit systeemfout" om de relatie te onderstrepen.


De h2 maakt de sr-only tekst voor het icoontje in principe overbodig. De h2 hoeft niet op een eigen regel te staan maar kan bijvoorbeeld ook het eerste woord van de melding zijn. Zo lang zonder kleuren te zien de relatie tussen melding en sluitknopje duidelijk is, zou hij waarschijnlijk zelfs sr-only mogen zijn hoewel ik dat niet wenselijk vind gezien synchronisatie tussen wat wordt voorgelezen en zichtbaar is. H2 is het juiste niveau als de banner boven de h1 staat maar als hij op een andere manier gebruikt wordt moet de implementator wellicht een ander niveau kiezen, eventueel rekening mee houden bij de css styling (niet afhankelijk maken van heading niveau)?

Overigens is er nog discussie mogelijk over hoe deze banner zich verhoudt tot landmarks, je zou hem een banner landmark kunnen meegeven. Het doorslaggevende argument daartegen vind ik echter dat je dan met een sluitknopje de landmarkstructuur zou veranderen (kan change of context zijn) en bovendien zijn deze banners niet echt paginaoverstijgend, ze horen wel bij de applicatie in de main landmark.

**Comment by MichielDHVD** [comment]
![Banner redesign](https://user-images.githubusercontent.com/36912722/99942889-abfcf180-2d70-11eb-8a23-ec79afccc1b9.png)

![Banner redesign Alert](https://user-images.githubusercontent.com/36912722/99943323-64c33080-2d71-11eb-8edf-ae940c33a065.png)


Uiteindelijk is het aan de implementatoren om de juiste teksten toe te passen. 

Maar de banners die op de toolkit staan bevatten de volgende teksten in de h2's en de bijhorende sluitknoppen

Waarschuwingsmelding: 
<h2>Onderhoudsmelding: Op zondag 8 december 2019 van 10.00 uur tot 17.00 uur vindt er onderhoud plaats aan het Omgevingsloket. 
Meer informatie 

<Sluiten knop> Onderhoudsmelding sluiten

Storingsmelding: 
<h2>Storingsmelding: Op dit moment ervaren wij een storing in de Vergunningcheck. U kunt wel een aanvraag of melding indienen.
<sluiten knop> Storingsmelding sluiten

**Comment by gofix** [comment]
@daverhelst kun jij bovenstaande verwerken (dus: koppen!)
