### ISSUE TITLE
Banner; Responsive ontwerp

### ISSUE THREAD

**Issue by daverhelst** [dso-toolkit/dso-toolkit#768]
### Aanleiding
Na het gesprek over verschillende WCAG punten die beschreven staan. Is naar voren gekomen dat er een responsive ontwerp gemaakt moet worden voor het Banner component.

### Werkzaamheden
Banner moet op vormfactor >= 480px hetzelfde gedrag volgen als de Alert
Icoon en Kruisje komen boven de tekst te staan.
Marges 16px rondom (Zie afbeelding voor specificaties)

### Ontwerp
![image](https://user-images.githubusercontent.com/36912722/113303691-a0fb3480-9301-11eb-894d-4a093c3c98d2.png)

### Testen
Welke test stappen moeten uitgevoerd worden om te controleren of het component correct is gebouwd

Visuele controle -> Responsive, Zoom 400% 1280px
Interactie gedrag testen meerdere browsers
Voorbeeldpagina's nalopen kijken of er onwenselijke veranderingen zijn https://dso-toolkit.nl/21.3.0/components/detail/pagina-met-banner.html

**Comment by MichielDHVD** [comment]
Voor banner moet er een wijziging plaatsvinden op de XS-viewport (<768)

**Wijzigingen**

- Icoon wordt boven de tekst geplaatst
- Kruisje wordt boven de tekst geplaatst ( Dom-volgorde ongewijzigd: icoon -> tekst -> kruisje ) 
- Bij de sluiten knop ontbreekt nog de extra toevoeging storingsmelding of onderhoudsmelding. Zodat de sr-only span opleest sluiten storingsmelding of sluiten onderhoudsmelding. Afhankelijk van de banner. 

![Banner kruisje boven](https://user-images.githubusercontent.com/36912722/104456707-5cd18100-55a9-11eb-8e0e-f5cb78f076b9.png)

Omdat de viewport kleiner is dan 768 hier een afbeelding hoe dit wordt weergeven op bijv. Portrait tablets. 
![Banner kruisje breed](https://user-images.githubusercontent.com/36912722/104456720-61963500-55a9-11eb-9d2f-4cac2d641b4d.png)

**Comment by gofix** [comment]
Changes zien er goed uit, wat mij betreft. Wat jou betreft ook, @MichielDHVD ?
https://dso-toolkit.nl/_768.Banner-responsive/components/detail/alert.html

**Comment by daverhelst** [comment]
@MichielDHVD er viel me iets op omtrent de grootte van het icoon dat gebruikt wordt bij de banner. In het ontwerp lijkt hij namelijk de grotere variant van de alert te gebruiken. Moet het formaat van het icoon in de banner aangepast worden naar het formaat van de alert?

Zie: https://dso-toolkit.nl/21.3.0/components/preview/banner.html

**Comment by MichielDHVD** [comment]
@daverhelst  Nee niet dezelfde grootte gebruiken. We willen het component visueel niet te aggressief/intens maken. Huidige grootte vind ik persoonlijk beter werken. 

@gofix Ik zie nog iets wat volgens mij niet klopt. Op de kleinste scherm weergave is er ontzettend veel witruimte aan de rechterkant. 

<img width="274" alt="Screenshot 2021-04-07 at 10 51 27" src="https://user-images.githubusercontent.com/36912722/113839013-991f1280-978f-11eb-8ff6-9ee04ed11925.png">
<img width="276" alt="Screenshot 2021-04-07 at 10 51 21" src="https://user-images.githubusercontent.com/36912722/113839031-9d4b3000-978f-11eb-9fb3-c67ab9f145dc.png">

Waarom is dit? In de ontwerp afbeelding staat 16px aan de rechterkant.

**Comment by daverhelst** [comment]
@MichielDHVD goed punt, heb ik over het hoofd gezien. Ik ga ermee aan de slag

**Comment by daverhelst** [comment]
@MichielDHVD Inmiddels is het aangepast.

**Comment by MichielDHVD** [comment]
@daverhelst Prima ik zie het. Strik eromheen en doorzetten zou ik zeggen.
