### ISSUE TITLE
Buttons; Responsive gedrag

### ISSUE THREAD

**Issue by daverhelst** [dso-toolkit/dso-toolkit#771]
Na het gesprek over verschillende WCAG punten die beschreven staan in https://docs.google.com/spreadsheets/d/19eZvX1o2ZAumc-D5uOixHvpS5jX8jijPpERO0qjD1k0/, is naar voren gekomen dat er nagedacht moet worden over het responsive gedrag van buttons. Denk aan:

- tekst over 2 regels
- iconen naast tekst
- buttons breedte (btn-block)

**Comment by MichielDHVD** [comment]
Responsive gedrag omtrent buttons. Vraag is of alle problemen in dit issue kunnen worden opgelost. 

Volgende wijzigingen zijn noodzakelijk: 

**Algemene wijzigingen**
Wanneer een button een lange tekst dan wordt deze niet afgebroken. Zelfs als er spaties in zitten. 
_Foute situatie:_
<img width="338" alt="Screenshot 2021-01-13 at 14 31 45" src="https://user-images.githubusercontent.com/36912722/104458842-306b3400-55ac-11eb-8cc9-c8fc4b0dc983.png">
_Gewenste situatie (extreem voorbeeld):_
<img width="260" alt="Screenshot 2021-01-13 at 15 08 42" src="https://user-images.githubusercontent.com/36912722/104462797-4af3dc00-55b1-11eb-9343-770e73bc0dc3.png">


**Buttons in highlightbox/Alert/Info/Whitebox** 

- Buttons kunnen buiten het kader vallen van highlightbox. Wrs hetzelfde probleem als eerder vermeld. 
_Foute situatie_
<img width="290" alt="Screenshot 2021-01-13 at 14 34 14" src="https://user-images.githubusercontent.com/36912722/104459172-b12a3000-55ac-11eb-8e19-33808de374bd.png">
_Gewenste situatie_
<img width="773" alt="Screenshot 2021-01-13 at 15 11 50" src="https://user-images.githubusercontent.com/36912722/104463160-b3db5400-55b1-11eb-85a3-0c784dec7bac.png">

- Wanneer buttons onder elkaar komen te staan op een kleinere viewport. Is de uitlijning vreemd 
<img width="316" alt="Screenshot 2021-01-13 at 14 40 15" src="https://user-images.githubusercontent.com/36912722/104459966-c81d5200-55ad-11eb-984c-d59cbe8080a4.png">
Gewenste situatie.
![Highlightbox](https://user-images.githubusercontent.com/36912722/104460168-0581df80-55ae-11eb-8718-21f30e9359b8.png)

- **overlegpunt!** Introductie nieuwe class. Dat buttons de complete breedte van een highlightbox innemen. Het is een bekend patroon en is met een class implementatie afhankelijk. 
Afbeelding knoppen volle breedte: 
![Andere uitlijning](https://user-images.githubusercontent.com/36912722/104461662-eb490100-55af-11eb-940c-02e6a9c858ab.png)

**Comment by bramhoosemans** [comment]
> * Introductie nieuwe class. Dat buttons de complete breedte van een highlightbox innemen. Het is een bekend patroon en is met een class implementatie afhankelijk.  **Overlegpunt**

Persoonlijk ben ik geen fan van buttons over de volledige breedte. Als ze naast elkaar passen (afhankelijk van content) zou ik ze ook op kleine breakpunten naast elkaar willen laten staan.

![Schermafbeelding 2021-01-14 om 09 36 28](https://user-images.githubusercontent.com/598735/104565127-1aad4b80-564c-11eb-80b6-764230c4f303.png)

**Comment by MichielDHVD** [comment]
Aangezien er nog geen behoefte is vanuit teams en nog geen ontwerp is met buttons over de breedte. Is het prima om daar nu niets mee te doen. 

Link button vind ik wel een interessant voorbeeld want de dimensies van die buttons geven qua margins en padding een onrustig beeld in het systeem. 

Wat vind je ervan om link buttons dezelfde padding te geven als primaire en tertiare buttons. De tekst start dan telkens op de zelfde plek. Klikbare ruimte kan zo ook mogelijk vergroot worden. 

![Uploading Buttons+ghost-area.png…]()

**Comment by bramhoosemans** [comment]
> Wat vind je ervan om link buttons dezelfde padding te geven als primaire en tertiare buttons. De tekst start dan telkens op de zelfde plek. Klikbare ruimte kan zo ook mogelijk vergroot worden.

Dit hebben we in het verleden bewust niet gedaan. Er ontstaat namelijk extra ruimte die in veel gevallen ongewenst is. Denk aan een tertiaire button onder een paragraaf -of- naast een andere actie (zie voorbeeld hieronder).

![Schermafbeelding 2021-01-19 om 09 18 00](https://user-images.githubusercontent.com/598735/105006729-54f55f00-5a37-11eb-8619-70a48cc3cbad.png)

**Comment by MichielDHVD** [comment]
Prima laten we dat achterwege.

**Comment by hansgrimm** [comment]
Gesloten wegens inactief sinds lange tijd. Mocht de behoefte toch nog (weer) aanwezig zijn, maak een nieuwe issue op grond van het component zoals dat nu is.
