### ISSUE TITLE
Algemeen WCAG; whitespace no-wrap

### ISSUE THREAD

**Issue by daverhelst** [dso-toolkit/dso-toolkit#772]
In het voorbeeld van de Whitebox zijn we tegen een geval aangelopen waarin te zien was dat teksten in buttons een whitespace no-wrap hebben. Dit mag absoluut niet. De toolkit moet nagelopen worden op deze whitespace setting, en deze vervolgens verwijderen.

**Comment by daverhelst** [comment]
Na bezig te zijn met de opruiming kom ik ook een white-space: nowrap tegen in de responsive-table. Naar mijn idee moet die daar wel blijven staan.

**Comment by daverhelst** [comment]
Zoals net in de refinement besproken, bij deze het percy resultaat waarin de dropdown _geen_ `white-space: nowrap` meer heeft: https://percy.io/dso-toolkit/dso-toolkit/builds/7122854

**Comment by PieterVerheij** [comment]
Dat voorbeeld lijkt mij een onwenselijk scenario omdat het hier onnodig afbreekt. Wellicht moeten we alleen op de smalle viewport het eraf halen of op bredere viewports een breedte forceren op de dropdown.

**Comment by bramhoosemans** [comment]
Eens met @PieterVerheij. Het is zeker niet wenselijk dat 'Mijn Omgevingsloket' wordt afgebroken als er voldoende ruimte op het scherm is.

**Comment by gofix** [comment]
De modal (links de nieuwe situatie als titels lang worden, rechts de oude/huidige situatie, waarin je ook nog de ellipsis ziet die weggaat)
![image](https://user-images.githubusercontent.com/2689559/94910753-6bd26e80-04a5-11eb-8674-2afec111e5d4.png)

**Comment by bramhoosemans** [comment]
> De modal (links de nieuwe situatie als titels lang worden, rechts de oude/huidige situatie, waarin je ook nog de ellipsis ziet die weggaat): https://dso-toolkit.nl/_772.Algemeen-WCAG-whitespace-no-wrap/components/detail/modal.html

Als we kunnen fixen dat het kruisje in de rechter bovenhoek blijft staan ben ik helemaal blij ;-)

**Comment by daverhelst** [comment]
De uitlijning van het kruisje wordt in https://github.com/dso-toolkit/dso-toolkit/issues/774 gefixt

**Comment by daverhelst** [comment]
Om uit te zoeken of bepaalde, eventueel niet wenselijke, styling zoals `white-space: nowrap` voorkomt in packages vanuit node_modules ben ik op zoek gegaan.

Gezocht op "white-space: nowrap" in dso.css, met de volgende resultaten:

```
.text-nowrap {
  white-space: nowrap; }
```

De oorsprong bevindt zich in **\node_modules\bootstrap-sass\assets\stylesheets\bootstrap\_type.scss**

```
.text-nowrap         { white-space: nowrap; }
```

**Comment by daverhelst** [comment]
Aanvullen van sass linter om "white-space: nowrap" als error terug te laten komen, zodat er bewust een keuze gemaakt moet worden om deze error uit te zetten, of de regel te verwijderen.

**Comment by daverhelst** [comment]
Na onderzoek is gebleken dat er geen optie bestaat om een bepaalde css-property als error te bestempelen. Andere linters zoals https://stylelint.io/ kunnen dit wel

**Comment by daverhelst** [comment]
Het vervangen van sass-lint door Stylelint zal in issue #805 opgepakt worden

**Comment by gofix** [comment]
Percy zegt: no visual changes found. Die maakt z'n screenshots natuurlijk niet onder de meest extreme omstandigheden, maar het zegt genoeg dat dus normaliter deze change WEL goed is en GEEN kwaad kan.
