### ISSUE TITLE
Algemeen WCAG; Decoratieve plaatjes responsive

### ISSUE THREAD

**Issue by daverhelst** [dso-toolkit/dso-toolkit#773]
In het voorbeeld van de Whitebox zijn we tegen een geval aangelopen waarin te zien was dat afbeeldingen een vaste breedte hebben meegekregen, en deze daardoor buiten beeld kunnen lopen. Vanaf een bepaald punt moeten deze meeschalen met de container (width: 100%)

**Comment by hansgrimm** [comment]
Gesloten wegens inactief sinds lange tijd. Mocht de behoefte toch nog (weer) aanwezig zijn, maak een nieuwe issue op grond van het component zoals dat nu is.
