### ISSUE TITLE
Tertiaire button - icon only: onderzoek en documentatie

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#776]
Besproken in refinement 24-09: we willen onderzoeken wat het gewenste gebruik is van icon-only buttons.

Hoe zorgen we ervoor dat het voor alle gebruikers duidelijk is wat de actie is die wordt uitgevoerd (tooltip of niet)? En in welke context zouden we deze wel of niet kunnen gebruiken (verwijderen, acties op de rij)?

**Comment by bramhoosemans** [comment]
**Aandachtspunt:** Op dit moment passen we in Mijn Omgevingsloket in het overzicht projecten een 'react-tooltip' toe die ervoor zorgt dat het lijkt alsof er elementen dubbel worden voorgelezen. Sr-only span: "Verwijder project x" met een toolkit "Verwijderen".

Het lijkt me een beetje kort door de bocht om te zeggen dat we tooltips verbergen en de inhoud altijd in een sr-only span opnemen (dubbele content).

**Comment by gofix** [comment]
@bramhoosemans tooltips zijn vaak een enorme 'hassle' om 'zelf' te programmeren. 

Maar... nu webcomponents (officieel "custom elements") in zicht raken, kan dat natuurlijk verlichting brengen. Als we straks bv. kunnen doen `<dso-button tooltip="Verwijderen"/>` kan het component alle pijn op zich nemen...

Anyway: het lijkt me nuttig om in dit ticket een inventarisatie te doen van alle denkbare (en/of daadwerkelijk geimplementeerde) vormen van icon-only buttons, om zodoende de scope te bepalen.

**Comment by gofix** [comment]
@bramhoosemans is dit issue nog relevant, sinds we al in andere issues met tooltips etc. bezig zijn gegaan?

**Comment by bramhoosemans** [comment]
@gofix dat lijkt me wel. Er is niet verder gekeken naar het gebruik en documentatie van 'icon-only' buttons.

**Comment by hansgrimm** [comment]
Gesloten wegens inactief sinds lange tijd. Mocht de behoefte toch nog (weer) aanwezig zijn, maak een nieuwe issue op grond van het component zoals dat nu is.
