### ISSUE TITLE
Definition list moeten opgebroken kunnen worden in columns zonder dat de definition list zelf doorbroken wordt. 

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#779]
Tijdens een test kwam naar voren dat  de definition zoals voorbeeld onder, als twee losse lijsten wordt opgelezen terwijl het eigenlijk 1 lijst is. 

Paginastructuur is gebruikt voor opmaak wat niet de bedoeling is. 

<img width="929" alt="Screenshot 2020-09-28 at 11 59 41" src="https://user-images.githubusercontent.com/36912722/94418794-2995ee00-0182-11eb-8cc7-fbf3094269ac.png">

De vraag is dus kunnen definition list in columns opgebroken worden zonder dat de definition list zelf wordt onderbroken.

**Comment by daverhelst** [comment]
Naar mijn idee kan er eventueel gebruik gemaakt worden van de CSS Columns, waarbij we kunnen aangeven uit hoeveel kolommen het uiteindelijk zal bestaan. We hebben alleen geen invloed op de aantallen per kolom.

**Comment by MichielDHVD** [comment]
Ik heb ook zoiets gezien, maar lijkt beetje random dus wordt experimenteren wat de gevolgen zijn denk ik

**Comment by gofix** [comment]
Voor veel browsers werkt de gerealiseerde oplossing, helaas niet voor firefox:
![image](https://user-images.githubusercontent.com/2689559/95953077-9bfd0400-0df9-11eb-85ce-9c5e6e87a3db.png)

Zie https://developer.mozilla.org/en-US/docs/Web/CSS/break-inside, `avoid-column` wordt door firefox (als enige :( ) niet ondersteund.

**Comment by gofix** [comment]
Het probleem is ook te zien op de door Percy genomen screenshots: https://percy.io/dso-toolkit/dso-toolkit/builds/7255092?utm_campaign=dso-toolkit&utm_content=dso-toolkit&utm_source=github_status_public

**Comment by PieterVerheij** [comment]
My bad, ik ben er naar aan het kijken.

**Comment by gofix** [comment]
Het ziet er inmiddels best heel goed uit. 2 twijfels nog:
Als de viewport wat smaller wordt (maar nog niet zo smal dat we in smartphone-gebied komen) blijft de 2- en 3-koloms indeling toch van kracht. Met name bij 3-koloms vraag ik me af of we dat wel willen:
![image](https://user-images.githubusercontent.com/2689559/96011833-be1b7400-0e43-11eb-96cc-5c995f88347c.png)

Verder, netjes dat nu de vertikale variant van de benadrukte beschrijvingsvorm een titeltje heeft gekregen, maar... waarom ineens Engels? al die vormen hebben gewoon Nederlandse titels...?

**Comment by gofix** [comment]
Ik heb de titel van die verticale versie met nadruk nog gewijzigd. Voor het eventueel wijzigen van het responsive gedrag kan eventueel later een ander issue worden geopend.
