### ISSUE TITLE
Definition list component

### ISSUE THREAD

**Issue by DjangoBlok** [dso-toolkit/dso-toolkit#78]
I would like to ad a definition in the Toolkit for presenting an list of metadata (name value pairs).
I also like to have a slightly lighter background than the 10% black to put these labels on. My suggestion is 95% grey (5% black)
For the name value pairs I would like to have distinction between the values and the names, in such way that emphasize is on the values.   
![name_value_pairs__metadata_](https://user-images.githubusercontent.com/34900082/37458310-fbcc228c-2844-11e8-8b15-4c6484e82ca9.png)

**Comment by VolleMelk** [comment]
@MichielDHVD: Gaan we dit doen? Welke versie? Ik stel 1.3 voor, gezien de druk op 1.2

**Comment by MichielDHVD** [comment]
@VolleMelk Het lijkt me slimmer om dit mee te nemen voor 1.3. De druk op 1.2 is inderdaad al hoog genoeg. We waren al bezig om prioriteiten te stellen aan de hand van de mail die je had gestuurd. 
Om hier nog meer aan toe te voegen lijkt me niet slim. 

Betreffende kleur, dat hoeft niet perse moeilijk te zijn. Ik wil die aanpassing gerust zelf even doen en dan vraag ik een pull request. Dan haal ik de 100% zwart eruit en schuif ik alle kleuren een stapje naar links en voeg dan de 5% toe. We willen 100% zwart het liefst vermijden. 

ps. Als er meer componenten gaan komen voor de viewer dan kan er misschien ook een kopje viewer komen in de toolkit. Voor een duidelijke structuur

**Comment by VolleMelk** [comment]
Als ik het verzoek van @DjangoBlok goed begrijp wilt hij graag een definitie-component. Semantisch klinkt dit als een `<dl>`, en Bootstrap heeft hier al twee varianten voor: https://getbootstrap.com/docs/3.3/css/#description

Dit component kan ook in de Toolkit worden opgenomen. Ik denk dat zelfs dat de markup identiek zal zijn aan die van Bootstrap (Niet dat je nou zoveel ruimte hebt met dit element):

```html
<dl class="dl-horizontal">
  <dt>...</dt>
  <dd>...</dd>
</dl>
```

Bovenstaande markup zou je al een heel eind op weg helpen, ware het niet dat deze nog niet "officieel" door de Toolkit is erkend (vandaar dat deze nog nergens in de stijlgids is terug te vinden).

Nog wat openstaande punten:
* De achtergrondkleur wordt grijs, maar waarom? Is dat de verantwoordelijkheid van het definitie-component? Kan er een ontwerp komen waar het definitie-component in context is geplaatst? Ik vermoed dat de achtergrondkleur op een hoger niveau moet worden geregeld. Wat als een definitielijst op een uitgelichte `.row` (met steunkleur) komt? Dan heb je grijs op groen, terwijl het mij logischer lijkt de definitie-component transparant te houden zodat dit soort accenten/steunkleuren behouden blijven
* Bootstrap heeft twee varianten: Een verticale opsomming en een variant waar de definitie naast de toelichting staat (horizontal). Om de laatste variant te krijgen moet er expliciet een class `dl-horizontal` worden geplaatst. Gaat de verticale opsomming ooit gewenst worden? Want dan kunnen we de styling direct op het `<dl>` element zetten (1).
* Wat is de horizontale maatverdeling? Bootstrap geeft 160px voor de definitie, 20px voor de gutter en het resterende voor de definitie. Bootstrap heeft het element responsive gemaakt, op small wordt het een verticale opsomming.

1) Ik zou er zelfs voor pleitten het gedrag om te draaien: _altijd_ de horizontal variant (toelichting NAAST de definitie), in small viewport onder elkaar zetten. Een modifier aanbieden waarmee een implementator dit gedrag kan overrulen als hij weet dat dit component in een smalle kolom wordt geplaatst (zoals een menu):

```html
<dl class="dso-vertical"> <!-- .dso-vertical forceert een verticale opsomming, anders responsive met kantelpunt op small viewport -->
  <dt>...</dt>
  <dd>...</dd>
</dl>
```

**Comment by DjangoBlok** [comment]
Achtergrondkleur staat inderdaad los van het definitiecomponent. 
Helemaal prima als het element responsive is.
Wat gebeurt er als de definitie breder is dan 160px?

**Comment by VolleMelk** [comment]
Dat is een goede vraag. Ik heb even op de site van Bootstrap gekeken, en die hebben zelf ook een definitie die breder is dan 160px:

![image](https://user-images.githubusercontent.com/9696261/37662683-e2d2a8a2-2c57-11e8-8559-dcc9bee32550.png)

Bootstrap breekt dit af. Persoonlijk vind ik dat gek en zou ik het afbreken niet doen. Ik heb hier een voorbeeld gemaakt:

![image](https://user-images.githubusercontent.com/9696261/37662932-7224922c-2c58-11e8-9946-e8ea79bd233a.png)

En dit enkel door Bootstrap styling uit te zetten: 
![image](https://user-images.githubusercontent.com/9696261/37663006-949748d6-2c58-11e8-828d-19ff21973184.png)

Nog 'n beetje lucht onderling en wat regular/bolds uitdelen en we zijn er. Wat denk je hiervan?

**Comment by DjangoBlok** [comment]
Ok, ik vind het afbreken van de term ook niet heel erg met de ellipsis. 
Zou hem wel iets meer ruimte geven. (200px?) 
Kan de term nog volledig getoond worden bij een mouseover?
Graag nog wel de stijl aanpassen zodat de term light wordt en de waarde normaal. (maar het bootstrap voorbeeld was ter illustratie neem ik aan)

**Comment by VolleMelk** [comment]
Het Bootstrap voorbeeld was inderdaad ter illustratie.

Maar ik kan het pas maken als ik een ontwerp en specificaties heb.

* Horizontale maten: 200px voor de term, 20px gutter en de rest voor de uitleg
* De term breekt af
* Term in Zwart60% regular
* Toelichting Grijs95 regular
* Component is uit zichzelf responsive, een verticale opsomming moet geforceerd worden met een class modifier

Het tonen van de volledige term ligt bij de implementator. Een title/mouseover kan alleen worden gezet vanuit de markup. Dit zal bij de implementatie details onder het kopje "Notes" komen.

@MichielDHVD / @DjangoBlok Wat dachten jullie hiervan? Kan iemand dit visueel uitwerken?

**Comment by MichielDHVD** [comment]
Mij maakt het niet uit. Maar aangezien @DjangoBlok heeft het aangedragen en de context van het element het beste kent wil hij het misschien uitwerken?  

Anders doe ik het.

**Comment by MichielDHVD** [comment]
Qua context zou ik graag het eerder benoemde voorstel hanteren namelijk de viewer een eigen categorie geven binnen de DSO-toolkit. Uiteindelijk willen we dat alles natuurlijk een geheel wordt. 

Verder zal ik even een opzetje maken van het ontwerp. Schets misschien wat duidelijkheid.

**Comment by MichielDHVD** [comment]
@VolleMelk @DjangoBlok Hier is eerst het ontwerp met alle details. Daarna voeg ik een ontwerp toe waar dit in de context van ons systeem wordt weergeven en waar er mogelijk problemen ontstaan. 

![name-value-pair-specs](https://user-images.githubusercontent.com/36912722/37958720-81b3f38c-31b1-11e8-9992-a795831f1e7b.png)

Als we dit component zo in een ons huidig ontwerp stoppen zou dat er zo uitzien. 

![specs-viewer-incontext](https://user-images.githubusercontent.com/36912722/37958820-d38fba74-31b1-11e8-8954-e32c163aa25f.png)

Dit komt niet overeen met de typography regels zie wij voor ons hebben gesteld in het design system. Als we de typography regels zouden hanteren zou dit component er als volgt uitzien.

![specs-normaal-context](https://user-images.githubusercontent.com/36912722/37958873-fb159d70-31b1-11e8-9d9b-ecc8cb85ec9a.png)

Daarom lijkt het me slim om de viewer en componenten voor de viewer zijn eigen onderdeel te geven voor de toolkit. Want bepaalde wijzigingen in de breedte zullen voor conflict zorgen. 

Voor de zekerheid moet ik dit eerst met Michael bespreken, dus dit moet nog even in spec blijven staan. 


Wat voor werkvorm zou jij fijn vinden Django betreffende de viewer en de toolkit?

**Comment by DjangoBlok** [comment]
Met welke typografie regels conflicteert dit dan?
Waar staan die in de stijlgids? 
Met Michael had ik afgesproken dat ik al mijn punten in deze Github zou zetten. Heb je een ander idee @MichielDHVD ?
Wat mij betreft goed om de viewer een eigen context te geven. We moeten er wel voor waken dat het niet te veel uit elkaar gaat lopen.
In dit geval zou de rationale gelijk moeten zijn. Zijn de labels structuur elementen (en beeld je ze dus als dik gedrukte kopjes af?) of zijn het labels om de content te duiden maar hoeven ze niet prominent getoond te worden (grijs).

**Comment by MichielDHVD** [comment]
Sorry ik heb verkeerde indruk gewekt met conflicterende typografie. Het staat inderdaad niet zo in het dso toolkit.   Het is eerder onbenoemd. Tot nu toe was het systeem vaak Name (Bold) en Value (Regular) dit brengt daar verandering in.  

Want waar je specifiek omvraagt is een component waar de nadruk ligt op **values** en niet **names**

@VolleMelk draagt aan dat we het <dl> element kunnen gebruiken en omvormen naar het component met jouw aangeleverde specs. Waar de nadruk op de values ligt. 

  Mijn vraag is: Is er behoefte om ook de mogelijkheid te hebben om nadruk te leggen op Names ipv values in het <dl> element.
Of wordt het html element  <dl> exclusief gebruikt voor wanneer er nadruk moet liggen op values? 

Zo ja dan moet dat in de beschrijving van het component zitten.    Ik vind het er verder trouwens wel prima uitziet. Het heeft een rustige uitstraling iets waar ik altijd wel fan van ben. 

————-
 Het aandragen via Github is prima.
 Bij werkvorm bedoel ik vooral wanneer we misschien vragen hebben naar elkaar toe over onderdelen of algemene richting van ontwerpen etc. Om bijvoorbeeld het uit elkaar lopen van ontwerpen te voorkomen.  

Gaan we dat ook op GitHub doen tussen alles door of misschien via mail? Want Github lijkt me het handigste om dat zo efficient mogelijk te houden voor de ontwikkelaars.

**Comment by DjangoBlok** [comment]
Misschien moeten we de nadruk op names niet uitsluiten, dus dat betekent inderdaad twee varianten?

Het lijkt me inderdaad handiger als we procesvragen buiten de Github om doen (ligt uiteindelijk volgens mij bij Michael). 
Ik vind het zelf wel handig om de Github als centraal communicatiepunt te hebben zodat verschillende disciplines tot een gezamelijk gedragen oplossing komen.

**Comment by VolleMelk** [comment]
Semantisch vraagt dit component om het [HTML5 dl element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl).

Waar visueel de nadruk op wordt gelegd is styling. Mochten beide werkvormen gewenst zijn, kan met een modifier class dit visuele gedrag worden gemaakt (hoewel ik daar geen grote fan van ben, dit soort modifier classes zijn nou niet echt semantisch).

Voorstel:
* We kunnen het standaard `<dl>` element responsive maken met een nadruk op de term (het `<dt>` element).
* Een verticale opsomming kan geforceerd worden met `.dso-vertical`.
* Met `.dso-emphasize-description` kan de nadruk op de description (het `<dd>` element) worden gelegd.

Op deze manier is er nog steeds 1 component voor het tonen van name/value pairs, maar met class modifiers kan er een variant op gemaakt worden. In dit geval voorkomt dat losse componenten die bijna hetzelfde doen.

Bijvoorbeeld:
```html
<!-- responsive en nadruk op de term -->
<dl>
  <dt>DSO</dt>
  <dd>Digitaal Stelsel Omgevingswet</dd>
</dl>

<!-- niet responsive en nadruk op de term -->
<dl class="dso-vertical">
  <dt>DSO</dt>
  <dd>Digitaal Stelsel Omgevingswet</dd>
</dl>

<!-- responsive en nadruk op de description -->
<dl class="dso-emphasize-description">
  <dt>DSO</dt>
  <dd>Digitaal Stelsel Omgevingswet</dd>
</dl>

<!-- niet responsive en nadruk op de description -->
<dl class="dso-vertical dso-emphasize-description">
  <dt>DSO</dt>
  <dd>Digitaal Stelsel Omgevingswet</dd>
</dl>
```

En wat betreft mailen of GitHub issues: Mijn voorkeur gaat uit naar **_alles_** een GH issue. Door transparant in vragen en procesontwikkelingen te zijn betrekken we iedereen bij het grotere geheel: Een fijne toolkit waar met plezier mee wordt gewerkt en aan wordt bijgedragen. Een issue hoeft niet altijd "werk" te zijn, maar kan een kletsbak of checklist zijn.

**Comment by MichielDHVD** [comment]
Uiteindelijk gaan deze twee versies er dus als volgt uitzien.

Emphasis on description
![dso-emphasize-description](https://user-images.githubusercontent.com/36912722/38026023-d54edce4-328a-11e8-9e9e-f13c2d77e0ca.png)

Emphasis on value 
![specs-viewer-incontext](https://user-images.githubusercontent.com/36912722/38026048-ef8b34c2-328a-11e8-858a-506992559f2a.png)

Verder vind ik de oplossing van de modifier prima. En dan kunnen ze allebei onder het zelfde component kopje getoond worden. 

Deze kan dan gemaakt worden als @DjangoBlok het er ook mee eens is. 

---

Voor communicatie zoveel mogelijk op github vind ik helemaal prima. Vroeg me af of dat gewaardeerd zou worden, maar dat is dan bij deze beantwoord.

**Comment by DjangoBlok** [comment]
De tweede variant is prima e wat ik bedoel inderdaad. 
De eerste zou moeten weergeven wat jullie nu al hebben. 
Zou dat niet moeten zijn: De labels en de waardes beide dezelfde kleur, maar de labels vetgedrukt?

**Comment by VolleMelk** [comment]
Als de font kleuren nog uitgewerkt kunnen worden voor de verschillende varianten (waarom zit er een verschil eigenlijk?) en of de term afgebroken wordt dmv. ellipsis kunnen we aan de bak, lijkt mij.

**Comment by DjangoBlok** [comment]
Ik kan me geen situatie voorstellen waarin je de waarden (rechts) in het grijs wilt hebben.
Die blijven dus in beide gevallen zwart (#191919)
Voor jullie bestande situatie verandert er dus niks. De labels krijgen extra nadruk door ze dik te maken.

**Comment by VolleMelk** [comment]
Er is geen bestaande situatie, de DSO toolkit bied dit component nog niet aan (alleen zit het toevallig in de Bootstrap styling verstopt :-)).

**Comment by MichielDHVD** [comment]
Dan wordt dit de uiteindelijke situatie. 

Emphasis description
![name-value-emphasize-description](https://user-images.githubusercontent.com/36912722/38290960-e5962f82-37dd-11e8-9cc8-8e7b7e08f3a5.png)

Emphasis Values
![name-value-pair-specs](https://user-images.githubusercontent.com/36912722/38290961-e5aff598-37dd-11e8-960d-9ca176571a15.png)


Ik ben tegen het afbreken doormiddel van ellipsis. 

Volgens mij was dat alles wat nodig is. 

Enigste wat niet vergeten moet worden is de kleur #f2f2f2 toevoegen

**Comment by VolleMelk** [comment]
Top! We gaan 't uitwerken

**Comment by VolleMelk** [comment]
Opgeleverd in 2.0.0-alpha.0

**Comment by DjangoBlok** [comment]
Waar kan ik deze vinden in de toolkit?
