### ISSUE TITLE
List-button group styling

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#780]
Bij het implementeren van de list-button lopen we tegen de .btn + .btn marge aan (16px aan de linkerzijde). Dit is niet wenselijk; graag toevoegen en voorbeeld opnemen zoals ontwerp in het originele issue https://github.com/dso-toolkit/dso-toolkit/issues/426.

![Image Pasted at 2020-9-28 11-59](https://user-images.githubusercontent.com/598735/94431991-5d7b0e80-0196-11eb-8866-dcca37fcff34.png)

**Comment by PieterVerheij** [comment]
@bramhoosemans ik heb een preview pagina gemaakt, zie de percy check: https://percy.io/dso-toolkit/dso-toolkit/builds/7070755

**Comment by bramhoosemans** [comment]
@PieterVerheij Afbeelding ziet er goed uit. Ik zou wel de wel de 'default' list-button styling gebruiken ipv de 'selected' state. Toevallig in het screenshot waren alle activiteiten geselecteerd denk ik :)
