### ISSUE TITLE
Header van een accordion element sluit niet altijd netjes aan.

### ISSUE THREAD

**Issue by PieterVerheij** [dso-toolkit/dso-toolkit#785]
Soms zit er ruimte tussen de header van en de border van een accordion element.

![image](https://user-images.githubusercontent.com/25430835/94679873-1c633580-0321-11eb-85c6-7e6dbefaa520.png)

**Comment by PieterVerheij** [comment]
Het tochtgaten probleem beperkt zicht niet tot de componenten alleen...
![image](https://user-images.githubusercontent.com/25430835/95061205-99b0f080-06fb-11eb-8379-72ef89febec5.png)

**Comment by PieterVerheij** [comment]
https://www.sitepoint.com/community/t/how-to-prevent-a-gap-appearing-between-divs-when-zooming-in-out/311003/6
https://codepen.io/paulobrien/pen/rQNGJm

Conclusie: borders verhuizen van `dso-accordion-section` naar `dso-section-handle` en `dso-section-body`

**Comment by gofix** [comment]
Ik krijg, zelfs op mijn haarscherpe ultrahighresolutionscherm en met allerlei zoomlevels, het probleem nu niet meer voor elkaar: https://dso-toolkit.nl/_785.Header-van-een-accordion-element-sluit-niet-altijd-netjes-aan/components/detail/accordion.html

Dus: in orde, lijkt me.

**Comment by bramhoosemans** [comment]
Accordion header ziet er nu op alle zoomlevels en resoluties strak uit 👍  Component gefixt, dus issue geaccepteerd.

In de header van dso-example-wrapper lijken nog wel tochtgaten voor te komen (zoom 150% en 250%):
<img width="711" alt="Schermafbeelding 2020-10-08 om 13 15 28" src="https://user-images.githubusercontent.com/598735/95452089-054bc580-0969-11eb-9348-0394fc2e3a6d.png">

**Comment by PieterVerheij** [comment]
@bramhoosemans Alhoewel het een eigen bevinding was, dacht ik niet dat dat binnen de scope van het ticket viel. Wil je dat ook aangepast hebben?

**Comment by bramhoosemans** [comment]
@PieterVerheij heeft voor mij geen prioriteit. Aanname was dat die ook gelijk gefixt was..
