### ISSUE TITLE
Viewer - Voorbeeldpagina bouwen

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#786]
In de viewer worden de volgende componenten gebruikt die nog geen voorbeeld pagina hebben. 

- Label component
- Progress component
- Tooltip component

Viewer is ook onder vertegenwoordigd in de toolkit qua voorbeeld pagina's dit helpt daarbij. 

<img width="1440" alt="Screenshot 2020-10-05 at 12 49 31" src="https://user-images.githubusercontent.com/36912722/95070964-3b8b0a00-0709-11eb-9e31-5bdb529e59b9.png">

Sommige componenten in deze pagina zien niet beschikbaar in de toolkit, wat meteen ook laat zien dat er onderdelen ontbreken

**Comment by gofix** [comment]
Volgens mij is dit een mooi begin, maar ik ben onzeker over of we de huidige stand van zaken wel al in een release moeten onderbrengen. Misschien beter aan de hand van deze branch deploy (https://dso-toolkit.nl/_768-Viewer-voorbeeld-pagina/components/preview/viewer.html) bediscussiëren wat er nog nodig is, en het voorbeeld pas opnemen als ook alle onderdelen paraat zijn.

**Comment by MichielDHVD** [comment]
Is voor mij prima

**Comment by hansgrimm** [comment]
Is dit nog courant?
