### ISSUE TITLE
Refactoring voorbeeldtemplates : Wizard Stap 3 (Kies activiteiten)

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#787]
In Wizard stap 3 staat een outdated ontwerp en het list button component kan worden toegevoegd. 

**Aanpassingen**

- List button toevoegen
- Winkelmandje uitbreiden om opties winkelmandje te tonen.

**Comment by bramhoosemans** [comment]
@MichielDHVD niet helemaal, in de Vergunningcheck wordt de checkbox lijst nog wel toegepast. De list-button wordt pas dit PI geïmplementeerd.

**Comment by MichielDHVD** [comment]
Voorsorteren op de toekomst vind ik geen probleem. Als we een implementatie hadden gezien, was die linker button margin op list buttons ook opgevallen, voordat de implementatie begon. 

Maar deze kan pas ook op een latere release worden toegepast als het een probleem is.

**Comment by bramhoosemans** [comment]
Voorsorteren is zeker geen probleem, juist positief! Maar ik denk dat we dit voorbeeld ook moeten behouden, omdat het nog steeds voorkomt in de toepassing.

**Comment by MichielDHVD** [comment]
En deprecaten wanneer de listbutton compleet door alle omgevingen heen is en op pre staat.

**Comment by bramhoosemans** [comment]
Ja, wanneer een voorbeeld layout niet meer relevant is kunnen we deze zeker deprecaten.

**Comment by bramhoosemans** [comment]
@MichielDHVD Hierbij een screenshot van de huidige implementatie én ontwerp waar we uiteindelijk heen willen.

![screencapture-int-omgevingswet-overheid-nl-aanvragen-f2f92752-2ddd-4c6a-9b54-b9180bd4faf1-verzoek-956-stap-3-1-2020-12-10-15_13_23](https://user-images.githubusercontent.com/598735/101793493-287c2800-3b06-11eb-9608-d28f2424a856.png)
![activiteiten](https://user-images.githubusercontent.com/598735/101793511-2a45eb80-3b06-11eb-9a4f-367752467d57.png)
