### ISSUE TITLE
Voorbeeldpagina nieuw - RTR-pagina voor Treeview

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#788]
De RTR applicatie is de enige applicatie die een treeview gebruikt. 

Pagina zo goed mogelijk nabouwen ook al komt de treeview van de toolkit niet overeen met de tree view van de RTR

RTR heeft ook geen pagina in de Toolkit dit maakt de RTR zichtbaar in de toolkit. 

<img width="1255" alt="Screenshot 2020-10-05 at 13 19 54" src="https://user-images.githubusercontent.com/36912722/95073676-8870df80-070d-11eb-81f1-512770a6a1ac.png">

**Comment by hansgrimm** [comment]
is dit nog courant?
