### ISSUE TITLE
Voorbeeldpagina nieuw - Wizard Stap 4

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#789]
Het conclusion component heeft nog geen voorbeeldpagina. Deze wordt in de vergunningcheck getoond in stap 4. 

Deze pagina toont conclusion component in context van de vergunningcheck. Plus het toont ook dat de laatste pagina geen volgende knop meer heeft. 

<img width="583" alt="Screenshot 2020-10-22 at 13 52 43" src="https://user-images.githubusercontent.com/36912722/96868122-e4599900-146d-11eb-8296-f633165712f7.png">

**Comment by MichielDHVD** [comment]
Tekst om te copy pasten in de voorbeeld pagina:

Vergunningcheck

4. ResultaatStap 4 van 4

Bedrijf veranderen of uitbreiden? Dan hoeft u voor bestaande milieubelastende activiteiten die niet veranderen geen vergunning aan te vragen, melding te doen of informatie te geven.

Werkzaamheden

Gas opslaan in een opslagtank

Voor 'gas opslaan in een opslagtank' moet u het volgende doen:

U vraagt een vergunning aan voor milieubelastende activiteit gereguleerd in het omgevingsplan.

Let op: Kan er in één van de opslagtanks meer dan 13.000 liter propaan of propeen? Dan hoeft u geen aparte vergunning aan te vragen voor het opslaan in meer dan twee opslagtanks.
U vraagt een vergunning aan voor milieubelastende activiteit gereguleerd bij AMvB.

Tankstation

Voor 'tankstation' moet u het volgende doen:

U vraagt een vergunning aan voor milieubelastende activiteit gereguleerd bij AMvB.

Wasstraat of wasplaats voor auto's, bussen, treinen en trams

Voor 'wasstraat of wasplaats voor auto's, bussen, treinen en trams' moet u het volgende doen:

Voor milieubelastende activiteit gereguleerd bij AMvB is op dit moment geen vragenlijst van het rijk beschikbaar. Neem contact op met uw gemeente om te weten wat u moet doen.

Resultaat Vergunningcheck downloaden

U kunt de resultaten van deze Vergunningcheck downloaden als PDF bestand. U kunt geen rechten ontlenen aan de inhoud van het bestand.

Tip: Start een aanvraag

U kunt vanuit deze Vergunningcheck beginnen met het indienen van uw aanvraag. Ga daarvoor naar Aanvragen en vul een projectnaam in. Zodra u dat gedaan heeft, worden uw locatie en activiteiten opgeslagen. Die hoeft u dan niet meer in te vullen als u later verdergaat.

De Vergunningcheck is een serviceproduct van de Nederlandse overheid. Het geeft u een algemene indruk of er voor uw activiteit een vergunning of melding nodig is. De makers van de Vergunningcheck hebben met veel aandacht gewerkt aan de vragen en antwoorden. Toch geeft het resultaat van de Vergunningcheck u geen absolute zekerheid. Bijvoorbeeld doordat sommige activiteiten of combinaties van activiteiten (nog) niet in de Vergunningcheck staan. Of doordat er nog andere regels zijn waardoor u nog andere vergunningen moet aanvragen of andere meldingen moet doen. U kunt daarom geen rechten ontlenen aan deze Vergunningcheck. Wilt u zeker weten of en hoe u uw activiteit kunt uitvoeren? Dan raden wij u aan contact op te nemen met uw gemeente en/of waterschap.

**Comment by daverhelst** [comment]
@MichielDHVD Het resultaat: https://dso-toolkit.nl/_789.Voorbeeldpagina-nieuw-Wizard-Stap-4/components/detail/wizard-stap-4.html

Klopt het allemaal?

**Comment by bramhoosemans** [comment]
@daverhelst heb de voorbeeldpagina vergeleken met de live-versie en opmerkingen in het screenshot verwerkt. Grootste aandachtspunt zijn de headings, deze H3 'werkzaamheden' met daarin de afzonderlijke werkzaamheden in H4.

Wat me verder opviel is dat in de toepassing een `<span>` gebruikt wordt bij de conclusie, en in het voorbeeld een `<p>`. Zie 'Voor '...' moet u het volgende doen:'. Wellicht niet de moeite waard om gelijk te trekken.

![screencapture-dso-toolkit-nl-789-Voorbeeldpagina-nieuw-Wizard-Stap-4-components-preview-wizard-stap-4-html-2020-10-26-08_39_42](https://user-images.githubusercontent.com/598735/97146229-c8087580-1767-11eb-80a4-73e32be20347.png)

**Comment by daverhelst** [comment]
@bramhoosemans ik heb de wijzigingen doorgevoerd, ook de <p> vervangen in <span> bij de 'Voor... moet u het volgende doen" teksten

**Comment by MichielDHVD** [comment]
Ziet er goed uit. Ik heb geen op of aanmerkingen.

**Comment by bramhoosemans** [comment]
@daverhelst Top! Nog een tweetal (detail) opmerkingen: de stap is nog niet aangepast naar 'Stap 4 van 4' en de 'vorige stap' button mag aangepast worden naar een tertiaire button met icon 'chevron-left' ervoor.

**Comment by daverhelst** [comment]
@bramhoosemans top, die had ik inderdaad over het hoofd gezien. De aanpassingen zijn doorgezet

**Comment by bramhoosemans** [comment]
Lijkt me helemaal overeen te komen, prima zo!
