### ISSUE TITLE
Voorbeeld pagina nieuw - Actieverzoek pagina + tabbladen 

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#791]
Tabbladen worden nog niet getoond in de voorbeelden. 

Deze pagina bevat een praktijk voorbeeld uit samenwerken. 

<img width="1155" alt="Screenshot 2020-10-05 at 13 06 55" src="https://user-images.githubusercontent.com/36912722/95072569-b1907080-070b-11eb-9b0f-fa54b6b34b5e.png">

**Comment by MichielDHVD** [comment]
Testable: https://dso-toolkit.nl/_791-Actieverzoek-voorbeeld-pagina/components/preview/actieverzoeken.html 

Tekst aangepast om ervoor te zorgen dat het beter overkomt, niet teveel lorum ipsum.

**Comment by bramhoosemans** [comment]
@MichielDHVD een aantal opmerkingen:

- Tabindex=0 bij tabel nodig?
- Status, datum en verzonden aan geen description-list met columns?
- Dubbele fieldset met sr-only legend ‘Invoervelden’ lijkt me overbodig.
- Zou de submit button niet aan de linkerzijde moeten uitlijnen? Zie single page form op https://dso-toolkit.nl/11.4.1/components/detail/form.html

**Comment by MichielDHVD** [comment]
Goeie opmerkingen ik ga er mee aan de slag.  

Voor de snelheid heb ik onderdelen bij pr02 weggescooped vandaar de tab index en dubbele fieldset. 

Submit button zal ik links uitlijnen. 

Kan pr02 dit voorbeeld overnemen in de toekomst

**Comment by MichielDHVD** [comment]
De aanpassingen zijn doorgevoerd. Maar bij eentje heb ik iets ontdekt waar we mogelijk iets aan willen doen. 

Het lukte me niet om de submit button aan de linkerzijde te laten uitlijnen. 
Dit lukte alleen als ik er een tweede knop aan toevoegde. 

Dus ik heb de class dso-single-page toegevoegd. Maar een enkele knop lijnt niet links uit. Omdat effect te laten hebben moet je er twee neerzetten. 

Of ik doe iets fout @gofix?

**Comment by gofix** [comment]
Je constatering klopt @MichielDHVD, ook als je op pagina https://dso-toolkit.nl/11.4.1/components/detail/buttons.html in het voorbeeld "Uitzondering: single page (.dso-single-page)" de 2e knop weghaalt, gaat direct de ene knop die overblijft naar rechts. Dat zal ongetwijfeld by design zijn, maar ik moet even terugzoeken 'waarom'.

**Comment by gofix** [comment]
In de css staat `.dso-form-buttons .btn:not(.btn-link):not(:only-child):first-child`, oftewel: daar staat heel expliciet dat alleen als de knop NIET in z'n uppie staat, hij links zou moeten staan...

**Comment by gofix** [comment]
Dit is besloten in https://github.com/dso-toolkit/dso-toolkit/issues/401 
Daar stond:

- Buttons worden gesorteerd op belangrijkheid van rechts naar links, met de primaire actie aan de rechterkant. Wanneer knoppen gebruikt worden om door een reeks schermen te navigeren, wordt de primaire knop rechts uitgelijnd en de 'terug' actie helemaal links om de navigatie visueel te ondersteunen.
- Uitgezonderd zijn formulieren met één pagina en gerichte taken, buttons links uitlijnen en sorteren op belangrijkheid van links naar rechts.

Maar dat 2e aspect is dus niet helemaal correct geimplementeerd voor `.dso-single-page`

**Comment by gofix** [comment]
Maak jij er even een nieuw issue voor aan @MichielDHVD ?

**Comment by MichielDHVD** [comment]
Ga ik doen. Deze kan dan voor nu doorgezet worden.
