### ISSUE TITLE
Progressblock deprecaten. 

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#792]
## Deprecation notice "Progressblock"

Dit is geen breaking change, enkel een deprecation notice.

---
Er is geen enkele reden voor Progress block om nog te bestaan. 

Wat met dit component gerealiseerd zou kunnen worden kan ook met andere componenten gecreeerd worden. 

https://dso-toolkit.nl/11.2.1/components/detail/progress-block.html

**Comment by PieterVerheij** [comment]
Let op: issue pas sluiten in week 44

Release week 42 : label "Progress Block [deprecated]"
Release week 44 : component Progress Block verwijderen.

**Comment by gofix** [comment]
@PieterVerheij, @tfrijsewijk wat is de handigste manier om deze warnings te schedulen? Toch gewoon met 2 issues, 1 voor de deprecation, en 1 voor de obsoletion, lijkt me, ieder hangend aan de beoogde milestone?

**Comment by bramhoosemans** [comment]
Component styling aanpassen in rood. Volgende milestone issue aanmaken om component te verwijderen.
