### ISSUE TITLE
List-button; CHILDREN in BUTTON blokkeren klik

### ISSUE THREAD

**Issue by daverhelst** [dso-toolkit/dso-toolkit#793]
Vanuit de implementator is het volgende naar boven gekomen omtrent de list-buttons:

```
“heb een vervelend fixje moeten doen op die listbutton anders werk klikken op de tekst van de button niet
button > * {
  pointer-events: none;
}
dat werkt, maar hoort toch correcter in de dso-toolkit thuis”
```

Na wat onderzoek kom ik het volgende tegen: https://stackoverflow.com/questions/26402033/missing-click-event-for-span-inside-button-element-on-firefox

Daar wordt aangegeven dat elementen in <button>'s voor kliks "bad practice" zijn, maar is dat wel zo?

`As far as i known clicking the children elements won't work because it is nested inside a button. A button is not container for child elements - only for text.`

**Comment by tfrijsewijk** [comment]
Ik kan dit niet reproduceren op dso-toolkit.nl, als ik daar op de `button.dso-list-button` een `onclick = () => alert('test')` handler toevoeg en vervolgens op de button of expliciet op het `span` element klik, krijg ik beide keren een alert(). Ik heb dit getest in Chrome, Firefox en IE11.

Kan het zijn dat er custom CSS in de implementatie zit of wellicht andere event handler/preventers die in de weg zitten?

Die opmerking over spans niet in buttons heb ik nog nooit van gehoord of ooit eerder problemen mee gehad. Dit is iets wat ik al jaren doe, en wat al jaren goed gaat..

**Comment by gofix** [comment]
Op https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events hebben ze het wel over deze css mogelijkheid, maar die is default juist {{auto}}. Oftewel, ik onderschrijf de analyse van @tfrijsewijk dat dit welhaast iets in de implementatie moet zijn.

**Comment by daverhelst** [comment]
Ik had nog een klein vermoeden dat een intern absolute gepositioneerde <span> er misschien voor zorgde dat de click niet bereikbaar was, maar dat is ook niet waar. Zie deze pen: https://codepen.io/dverhelst/pen/Yzqowzy

Ik kan ook bijna niet anders concluderen dat de bevinding erg vreemd is, en dit hoogstwaarschijnlijk (zoals Thomas en Ad hierboven ook melden) voortkomt vanuit iets in de implementatie.

**Comment by jcstover** [comment]
Aangezien ik degene ben die het probleem heb/had. Het bleek dat klikken op het span element niks deed. Na toevoegen van aan onze css van 
button > * {
  pointer-events: none;
}
werkt het. Mochten jullie dit niet kunnen reproduceren dan laat ik die toevoeging gewoon aan onze kant staan. Vreemd genoeg zie ik het op andere soorten buttons wel gewoon werken, maar niet op de listButton.

**Comment by gofix** [comment]
@jcstover kun je (desnoods over de slack) aangeven waar we dit kunnen zien (NB wij hebben toegang tot het Standaard Platform, dus kunnen wellicht op die manier een blik werpen?)

**Comment by jcstover** [comment]
kan gesloten worden, lag aan event.target versus event.currentTarget

**Comment by tfrijsewijk** [comment]
https://stackoverflow.com/questions/5921413/difference-between-e-target-and-e-currenttarget

Was snel opgelost, goede sessie.
