### ISSUE TITLE
Iconen minus-square en plus-square updaten

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#796]
![Schermafbeelding 2020-10-01 om 16 16 29](https://user-images.githubusercontent.com/598735/94821116-86eba280-0401-11eb-8cd3-bcb5826f8533.png)

**Comment by Anto1nette** [comment]
Bij deze de aangepaste iconen
[iconen_plus_minus_square.zip](https://github.com/dso-toolkit/dso-toolkit/files/5402756/iconen_plus_minus_square.zip)

**Comment by PieterVerheij** [comment]
@Anto1nette @bramhoosemans Dit moet hem zijn: https://www.dso-toolkit.nl/_796.Iconen-minus-square-en-plus-square-updaten/components/detail/icon.html

**Comment by Anto1nette** [comment]
Dank je! :)

**Comment by gofix** [comment]
Done? Maar er is nog niks gemerged, @PieterVerheij, @bramhoosemans
