### ISSUE TITLE
Nieuw component: Input Number

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#797]
Nieuw formulier component Group/Input Stepper.

Specificaties:
[input-stepper.zip](https://github.com/dso-toolkit/dso-toolkit/files/5312650/input-stepper.zip)

![Schermafbeelding 2020-10-01 om 16 18 16](https://user-images.githubusercontent.com/598735/94821555-fa8daf80-0401-11eb-878d-159a700f8e7b.png)

Input Stepper in context; meerdere keren dezelfde activiteit selecteren.

![112_meerdere-dezelfde-activiteiten--gekozen](https://user-images.githubusercontent.com/598735/94899156-12614400-0493-11eb-8356-20b73cafef58.png)

**Comment by PieterVerheij** [comment]
Work in progress: https://www.dso-toolkit.nl/_797.Nieuw-component--Input-Stepper-/components/detail/input-stepper.html

**Comment by bramhoosemans** [comment]
@PieterVerheij Zou dit geen formulier element moeten zijn? Naar mijn idee is het ook een invoerelement...

- Variant met label
- Volledig inactief/disabled?

**Comment by PieterVerheij** [comment]
@bramhoosemans Kan hij niet ook los van een formulier gebruikt worden? En kan je stellen dat het binnen een formulier altijd een label heeft en daarnuiten niet, of is dat te kort door de bocht?

**Comment by bramhoosemans** [comment]
Tja, elk input element mag volgens mij los van een formulier gebruikt worden. Maar je zal toch op een of andere manier de context van de 'input stepper' mee moeten geven. Wellicht via een getoond of verborgen label? @timveld heb jij hier een mening over?

**Comment by PieterVerheij** [comment]
In de context van een formulier zou je er dan al bijna een `fieldset` met `legend` en twee `buttons` van maken.

**Comment by PieterVerheij** [comment]
Twee varianten gemaakt: buiten en binnen de context van het folmulier (.form-group). Variant daarbuiten ook met smaakje zonder label:
https://www.dso-toolkit.nl/_797.Nieuw-component--Input-Stepper-/components/detail/input-stepper.html
https://www.dso-toolkit.nl/_797.Nieuw-component--Input-Stepper-/components/detail/group-input-stepper.html

**Comment by gofix** [comment]
Al het harde werk ten spijt, ga ik deze toch nog niet in de release opnemen. Ik heb namelijk nog een paar opmerkingen, zie PR.

**Comment by MichielDHVD** [comment]
Naam veranderen naar Input-number class = dso-input-number

**Comment by MichielDHVD** [comment]
Is het handig als het nummer tussen de plus en de min in de input-number aangepast kan worden door de gebruiker. Zodat deze niet 80 keer op het plusje hoeft te drukken maar zelf 80 kan invoeren? 

@bramhoosemans

**Comment by bramhoosemans** [comment]
Dat zou ik niet doen. Dit element is niet bedoeld om grote afwijkende getallen in te voeren, maar juist om een kleine afwijking van de default snel in te voeren. Zoals aantal activiteiten of bijvoorbeeld aantal passagiers.

In andere gevallen zou ik een normaal invoerveld gebruiken.

**Comment by PieterVerheij** [comment]
Besproken door @gofix en @bramhoosemans : 
- component wordt hernoemd naar 'Input-numer' (class `dso-input-numer`)
- input krijgt `tabindex=0` zodat hij niet te focussen is

**Comment by timveld** [comment]
De link naar dit component werkt niet meer, met een screen reader is dit geen handige werkvorm maar kan m.i. wel mits er echt niet meer dan een paar keer op het knopje gedrukt hoeft te worden. Label knopje en alert bij indrukken moeten we dan goed documenteren. Graag donderdag nog even bespreken.

**Comment by gofix** [comment]
@timveld deze aandachtspunten waren al eerder besproken.
