### ISSUE TITLE
List-button multiple selection aanpassen en uitbreiden met extra inhoud

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#798]
1. Multiple selection aanpassen; gebruik maken input stepper https://github.com/dso-toolkit/dso-toolkit/issues/797 ipv meerdere keren klikken. Idee is dat het element wordt samengesteld uit verschillende componenten (input-group?), zodat er geen interactieve elementen over elkaar heen vallen.
2. Extra inhoud optioneel weergeven:
- Bestuurslaag (sub-label)
- Subactiviteiten of trefwoorden gescheiden door een puntkomma (sub-content?)

Specificaties: [list-button.zip](https://github.com/dso-toolkit/dso-toolkit/files/5695588/list-button.zip)

![toolkit-list-button](https://user-images.githubusercontent.com/598735/102204030-a1460000-3ec9-11eb-822c-9da432e78da5.png)

List-button in context; resultaten zoeken naar activiteiten (professionele aanvrager)

![106_activiteiten-zoekresultaten](https://user-images.githubusercontent.com/598735/94899428-961b3080-0493-11eb-8287-de6b3c46a759.png)

**Comment by PieterVerheij** [comment]
@timveld Wat is hier de beste manier om termen in zoekresultaten te highlighten (als in dat bv. "Tank" wordt gehighlight in "Tankstation" als je op "Tank" zoekt)? Wij gebruiken zelf vaak `<em>`, maar er heerst nu wat twijfel over of dit wel de juiste manier is.

**Comment by PieterVerheij** [comment]
Recap van de werkzaamheden:
De aanpassingen zijn nog gedaan in de oude opzet. D.w.z. dat het nog niet een web component is en op een later stadium moet owrden omgezet naar een web component. Het 'list-button'-component gebruikt o.a. het 'input-number' (nog geen web-component) en daarmee ook het 'button'-component (ombouw gaande).
Voor het groeperen van de 'list-button' met 'input-number' is de 'dso-btn-group' geintroduceerd. @tfrijsewijk gaan we hier ook losse voorbeelden van genereren?

**Comment by bramhoosemans** [comment]
@PieterVerheij Ziet er al goed uit!

- De 'button multiple selected' variant wordt niet meer gebruikt als we 'input number' introduceren. Zie ook ontwerp in dit issue. Volgens mij kunnen we deze deprecaten.
- Goed om een voorbeeld op te nemen van 'button met optionele tekst', dus zónder het extra label.

**Comment by PieterVerheij** [comment]
> @timveld Wat is hier de beste manier om termen in zoekresultaten te highlighten (als in dat bv. "Tank" wordt gehighlight in "Tankstation" als je op "Tank" zoekt)? Wij gebruiken zelf vaak `<em>`, maar er heerst nu wat twijfel over of dit wel de juiste manier is.
> 
> Is dit een goede optie: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/mark ?

@timveld Zou jij hier nog op kunnen reageren?

**Comment by timveld** [comment]
@PieterVerheij dit is inderdaad een probleem, de screen reader leest het in beide gevallen niet voor. em kun je met extra handelingen wel laten aankondigen maar mark nog niet zoals ze aangeven in de post waar je naar verwijst. 

Denk toch dat mark vanuit WCAG beter is, want dan is er een manier om programmatisch af te leiden dat de tekst gemarkeerd is en kunnen (toekomstige) user agents hier op hun eigen manier mee omgaan. Dat screen readers de mark nog niet ondersteunen is eigenlijk niet onze verantwoordelijkheid, we hebben bovendien geen beter toegankelijk alternatief. 

Zelf zou ik zowel de em als de mark goedkeuren. Deze markering is een visueel handigheidje maar de pagina is zonder deze markering volledig begrijpelijk en duidelijk. Als de markering een semantische functie had moest je hem misschien met sr-only aankondigen, maar in deze situatie is dit bij het voorlezen van de tekst overbodige informatie omdat gebruikers het gebruikte zoekwoord waarschijnlijk zonder extra hint herkennen als het wordt voorgelezen. En zoals bekend is overbodige informatie een van de belangrijkste irritaties van veel screen reader gebruikers.

**Comment by PieterVerheij** [comment]
Ok, duidelijk!

**Comment by gofix** [comment]
In dit issue is de `.dso-btn-group` geintroduceerd. Deze className pretendeert wat meer dan wat ie nu werkelijk biedt, maar voor nu is dat ook voldoende. Het groepeert nu een button met een `.dso-input-number`, en zorgt er voor dat de linker button dan de afronding krijgt, en de dso input number rand juist rechts, maar ook niet meer dan dat. Wanneer dit `.dso-btn-group` concept vaker nodig gaat zijn (bv. om 3 knoppen te combineren, of 2 knoppen en een dso-input-number), zal dit als zelfstandig component apart gedemonstreerd gaan worden.
