### ISSUE TITLE
LInks naar digitoegankelijk.nl vanaf pagina "Documentatie" bestaan niet meer

### ISSUE THREAD

**Issue by gofix** [dso-toolkit/dso-toolkit#799]
In het stuk over toegankelijkheid op de "Documentatie" (dus: start-) pagina van de Toolkit staan een aantal links naar digitoegankelijk.nl. Deze werken niet meer: digitoegankelijk.nl heeft sinds enige tijd zijn site flink uitgedund en verwijst voor meer en meer stukken naar bv. https://www.w3.org/TR/WCAG21/

**Comment by gofix** [comment]
Ook wordt beweerd: "In de toolkit is een sectie over digitale toegankelijkheid (onder ontwikkeling) ingericht waar uitleg en hulp wordt gegeven om te helpen bij het voldoen aan de eisen en richtlijnen van de digitale toegankelijkheid."

**Comment by MichielDHVD** [comment]
Goed gevonden. Ik ga dit meteen voor de release op lossen. Dat stukje over digitoegankelijkheid wordt nu telkens in losse documentatie verwerkt. Dus dat ga ik herschrijven of verwijderen. 


Hebben we een systeem in place voor het automatisch vinden van dode links?

**Comment by MichielDHVD** [comment]
Links zijn niet verwijderd maar verplaatst. Heb daarom de links aangepast naar de nieuwe locatie op de digitoegankelijkheid websites. Pagina's zijn exact hetzelfde alleen met andere url.
