### ISSUE TITLE
CSS regression testing + ontmantelen van de WCAG checker

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#8]
CSS regressie testing dmv. Percy (https://percy.io)

De ingebouwde WCAG checker heeft zichzelf niet bewezen. Voor nu ontmantelen we de wcag checker gaan we de toegankelijk via andere tools toetsen

**Comment by MichielDHVD** [comment]
Gezien, ter controle kan er gekeken worden naar de oudere versies. Daar is het tabje wcag nog zichtbaar. 

Verplaatst naar done.
