### ISSUE TITLE
Security headers van dso-toolkit.nl inregelen

### ISSUE THREAD

**Issue by gofix** [dso-toolkit/dso-toolkit#800]
![image](https://user-images.githubusercontent.com/2689559/95058097-55235600-06f7-11eb-8686-ba54f97989d0.png)

**Comment by tfrijsewijk** [comment]
Ik moest toch op die machine zijn

https://securityheaders.com/?q=www.dso-toolkit.nl&followRedirects=on

![image](https://user-images.githubusercontent.com/9696261/107114288-0fbd9380-6865-11eb-9873-9dd18b372938.png)

![image](https://user-images.githubusercontent.com/9696261/107114300-1f3cdc80-6865-11eb-8cb1-0ff4dd0120ee.png)

De volgende settings in de web.config toegepast:

```
<configuration>
  <system.webServer>
    <httpProtocol>
      <customHeaders>
        <remove name="Strict-Transport-Security" />
        <add name="Strict-Transport-Security" value="max-age=31536000; includeSubDomains" />
        <remove name="Content-Security-Policy" />
        <add name="Content-Security-Policy" value="default-src https: data: 'self' 'unsafe-inline'" />
        <remove name="Permissions-Policy" />
        <add name="Permissions-Policy" value="fullscreen=(*)" />
      </customHeaders>
    </httpProtocol>
  </system.webServer>
</configuration>
```

De warning is dismissable: De site is statisch gegenereerd, het is voor een bezoeker niet mogelijk dubieuze scripting te injecteren. En aangezien onze eigen tooling (Fractal) er wel gebruik van maakt moeten we het wel toestaan. Met de huidige opzet is het de investering niet waard om met hashes of nonces te gaan werken.

De geconfigureerde Permissions-Policy is natuurlijk de grootste onzin die er bestaat: Het is niet mogelijk om een Permissions-Policy te zetten waarmee je alles uitzet en aangeeft "Ik ken de header, doe maar niets".

Maar allemaal groene meldingen ziet er natuurlijk beter uit dan één rode en de rest groen.. Dus ik heb 'm maar op iets gezet.

**Comment by infoprojectsnl** [comment]
Ziet er goed uit. Akkoord.

**Comment by erikvdijk** [comment]
Ziet er goed uit. Akkoord.
