### ISSUE TITLE
Label herontwerp en Label Group

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#809]
Filter (buttons) afstanden optimaliseren als deze in rijen worden geplaatst. Is dat iets war generiek gemaakt kan worden of niet?

Het inspringen van de list-buttons is reeds gefixt in https://github.com/dso-toolkit/dso-toolkit/issues/780, onderdeel van 11.3.0.

![Schermafbeelding 2020-10-12 om 14 05 35](https://user-images.githubusercontent.com/598735/95759720-5c73d200-0caa-11eb-99b5-de89fb05397e.png)

**Comment by PieterVerheij** [comment]
Eigenlijk zien we hier twee issues:
- het ontbreken van verticale marges op de buttons
- een ongewenste linker marge op de laatste button

Je wilt niet altijd een verticale marge op een button, dus zal je daar een extra selector voor willen gebruiken, bv `dso-filter-buttons'.
Een button in een div met `.dso-form-buttons.dso-filter-buttons` heeft dan bv. `margin: 8px 16px 8px  0` en de laatste button geen margin-right.

**Comment by DjangoBlok** [comment]
Valt mij iets anders op. 
Hier hadden we toch een ander component voor gedefinieerd? (gebaseerd op de badge). 
Zo niet, dan lijkt mij dat wel nodig. Dit zou naar mijn idee geen button moeten zijn.

**Comment by gofix** [comment]
Badge? Daarop zit doorgaans geen interactie toch?
![image](https://user-images.githubusercontent.com/2689559/96842887-e875be80-144d-11eb-8510-876ca8c6acb9.png)

Of een nieuw component dat visueel lijkt op badge?

Hoe dan ook lijkt me de hierboven gesuggereerde `.dso-button-row` niet onaardig. Liever nog zou ik 'm niet nodig hebben, maar ik denk dat dat lastig is, dus dan maar liever expliciet...

**Comment by PieterVerheij** [comment]
Ik denk dat label een betere kandidaat is?
![image](https://user-images.githubusercontent.com/25430835/96843865-160f3780-144f-11eb-92c7-ada471118694.png)
https://www.dso-toolkit.nl/11.4.1/components/detail/label.html

**Comment by bramhoosemans** [comment]
> Ik denk dat label een betere kandidaat is?

Klopt. Er moet nog een besluit worden genomen of we labels of buttons gebruiken voor de actieve filters. Ivm afwezigheid hebben we deze beslissing een week moeten uitstellen.

Ik verwacht dat we hoe dan ook een expliciete row styling moeten toepassen, op de labels of buttons.. niet?

**Comment by bramhoosemans** [comment]
Inventarisatie gebruik labels in DSO applicaties voordat er een besluit kan worden genomen wat de oplossing is. Bestaande componenten in lijst of eigen component voor actieve facets/filters.

**Comment by daverhelst** [comment]
De laatste waarheid:

**Voor Wie***
PR12 gebruikerstoepassingen. In de toekomst de Viewer en mogelijk Stelselcatalogus.

**Waar***
Op de stap 'Kies activiteiten' in Aanvragen kunnen filters worden toegepast, zie voorbeeld layout https://dso-toolkit.nl/master/components/detail/activiteiten.html

**Precondities***
Aanleiding
_Als initiatiefnemer wil ik snel zien welke filters actief zijn, zodat ik mijn selectie kan verfijnen._

In de huidige implementatie van de gebruikerstoepassing zijn buttons gebruikt om actieve filters weer te geven, zie bijgevoegd screenshot. Bij het bespreken van een verbeterde uitlijning is de wens ontstaan hier een ander component voor te gebruiken.

**Werkzaamheden**
Gebruik component labels ipv buttons voor actieve filters.

**Herontwerp labels**

- Styling van het default label aangepast zodat deze meer in lijn is met de rest van de interface.
- Statisch label heeft twee formaten, namelijk 24px en 32px hoog.
- Het 'removable label' mag alleen 32px hoog zijn.
- Hover state van het 'removable label' herzien.
- Label group geïntroduceerd waarmee de afstanden en uitlijning van meerdere labels kan worden afgedwongen.
- Margin labels onderling 8px (afhankelijk van de oriëntatie).
- Margin-bottom label group 16px
- Uitbreiden voorbeeld met actieve filter

https://dso-toolkit.nl/master/components/detail/activiteiten.html

**Ontwerp**
Zie attachments. 

**Testen**
ntb

**Acceptatiecriteria**
ntb

**Comment by daverhelst** [comment]
![image](https://user-images.githubusercontent.com/5871330/117642186-4cac6580-b187-11eb-9ede-1f39e8572903.png)
