### ISSUE TITLE
Nav Bar Collapse to more button on overflow

### ISSUE THREAD

**Issue by DjangoBlok** [dso-toolkit/dso-toolkit#81]
The current navbar looks strange when there is not enough room to show all tabs.
I would like to collapse the not fitting tabs to a button "meer..." showing a menu with these tabs.
sample: https://www.bootply.com/8UzYhpyAPh

**Comment by VolleMelk** [comment]
Dit kan ik niet maken met CSS: Ik kan in de stijlgids alleen de implementatie voorschriften opnemen en de verschillende states van het menu stylen.

Hebben we het over de hoofdnavigatie? Wil je hier uberhaupt zoveel elementen in kunnen plaatsen dat er een "Meer.." knop nodig is?

**Comment by DjangoBlok** [comment]
Nee gaat niet over de hoofdnavigatie, maar over de navbar (tabbar)
De realiteit is dat daar momenteel te veel items in zitten (vanuit de beschikbare data), maar daar kan ik helaas even nog niks aan doen.

**Comment by tfrijsewijk** [comment]
We kunnen wel een werkvorm uitwerken, maar de implementator moet scriptend het mechanisme aansturen
