### ISSUE TITLE
"Toelichting" wordt dubbel voorgelezen door screenreader

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#813]
Er wordt op dit moment dubbel het woord "toelichting" voorgelezen als er een toelichting bij een vraag wordt gegeven (dso-info-button).

Getest met NVDA in Firefox.

Initieel hoor je “toelichting - groepering - toelichting - knop samengevouwen”, maar op het moment dat je de tab-focus terug verplaatst wordt er enkel "toelichting - knop samengevouwen” uitgesproken. Als je er met de cursortoetsen naar toe navigeert, wordt 'knop samengevouwen T' voorgelezen.

Mogelijk komt dit door de plaatsing van de elementen; het label en de button staan in één legend met `class="dso-label-container"`.

@timveld zie hierboven de gehele bevinding.

**Comment by MichielDHVD** [comment]
@bramhoosemans @timveld  Update?

**Comment by bramhoosemans** [comment]
Geen update. Dit is een bevinding en zou mogelijk verbeterd kunnen worden in de toolkit.

Zojuist ook de 'form' pagina in de toolkit getest met NVDA in Firefox en hetzelfde resultaat: “toelichting - groepering - toelichting - knop samengevouwen”

**Comment by PieterVerheij** [comment]
De labels en inhoud van de bijbehorende uitklappers waren vaak beiden gevuld met "Toelichting". Ik heb deze nu specifieker gemaakt: https://www.dso-toolkit.nl/_813.Toelichting-wordt-dubbel-voorgelezen-door-screenreader/

Wat volgens mij niet juist is, is de info-button die bij bv. een vraag met radio-buttons staat: de uitklapper staat daar niet direct naast de vraag(-label), maar onder de opties (waar ook weer een info-button met uitklapper bij kan horen). Zie onderaan deze pagina: https://www.dso-toolkit.nl/_813.Toelichting-wordt-dubbel-voorgelezen-door-screenreader/components/detail/group-radios.html. Deze zou je eigenlijk met `aira-controls` willen koppelen omdat ze niet direct naast elkaar staan, maar het gebruik en support daarvan is dubieus. In het kader van de tree view hebben we het hier ook al over gehad, maar deze case is weer net iets anders. Kan jij hier iets zinnigs over zeggen, @timveld ?

**Comment by PieterVerheij** [comment]
Labels aanpassen naar: 
"Toelichting bij vraag"
"Toelichting bij antwoord"

**Comment by PieterVerheij** [comment]
Soms was de term 'vraag' of 'antwoord' niet dekkend, dan heb ik naar eer en geweten 'zoekveld' of 'optie' ingevuld.

**Comment by bramhoosemans** [comment]
> Soms was de term 'vraag' of 'antwoord' niet dekkend, dan heb ik naar eer en geweten 'zoekveld' of 'optie' ingevuld.

Prima om 'Toelichting bij zoekveld' bij Group Search Bar te zetten. Uit nieuwsgierigheid: waar heb je 'optie' ingevuld?

**Comment by PieterVerheij** [comment]
Bij de Infobutton zelf: 'optie' als neutrale term gebruikt omdat je daar nog niet weet in welke context hij gebruikt gaat worden.
