### ISSUE TITLE
Viewport meta-tag toevoegen aan component pagina's in de toolkit

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#816]
Nu we steeds meer gaan kijken naar responsive design. Moeten we dan ook niet de meta-tag viewport toevoegen zodat als we bijv. de voorbeeld pagina's op mobile kijken een accurate representatie hebben?

**Comment by gofix** [comment]
@MichielDHVD kun jij testen?

**Comment by MichielDHVD** [comment]
Ziet er goed uit! Ik zie alweer verschillende onderdelen waar we nog eens goed naar moeten kijken.
