### ISSUE TITLE
Labels mogen niet bestaan zonder ingesloten invoerelement of for attribuut

### ISSUE THREAD

**Issue by gofix** [dso-toolkit/dso-toolkit#819]
Zoals gezien en bediscussieerd in #731 : In een aantal werkvormen komt een `<label />` voor zonder `for` en zonder veld IN het `<label />`. Dat is fout. 

Dit komt (voornamelijk?) voor in werkvormen met een `<legend />`, met een `.dso-label-container`-class.

**Comment by gofix** [comment]
De change hier is semi-breaking. Developers zullen eigenlijk markup moeten wijzigen. De change is niet explosief, de stijl zal niet stuk gaan als developers in bestaande code de `<label />`  laten staan, omdat de stijl wordt toegepast op `.control-label`.

Toch zou ik wel het **breaking** label willen hanteren, eens @bramhoosemans , @PieterVerheij

**Comment by PieterVerheij** [comment]
Ja, eens. Geforceerde best practice ;-)

**Comment by bramhoosemans** [comment]
prima!

**Comment by gofix** [comment]
Als zodanig genoteerd in het `changelog.md` en, zoals onlangs afgesproken, toegelicht bovenin de PR.
