### ISSUE TITLE
Single button op een single-page-form ook links laten uitlijnen. 

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#825]
Op dit moment worden de buttons in een single page-form links uitgelijnd wanneer er twee buttons aanwezig zijn. 

Wanneer er 1 button is moet deze ook links worden uitgelijnd. 

Oude situatie
<img width="558" alt="Screenshot 2020-10-28 at 11 22 37" src="https://user-images.githubusercontent.com/36912722/97423704-edd07e80-190f-11eb-9ef7-7a2e1de08ec3.png">

Nieuw situatie
<img width="570" alt="Screenshot 2020-10-28 at 11 23 50" src="https://user-images.githubusercontent.com/36912722/97423788-135d8800-1910-11eb-80df-43ae508d5de5.png">

**Comment by PieterVerheij** [comment]
@MichielDHVD 
Extra variant 'SINGLE PAGE FORM WITH SINGLE BUTTON'
https://www.dso-toolkit.nl/_825.Single-button-op-een-single-page-form-ook-links-laten-uitlijnen/components/detail/form.html

https://www.dso-toolkit.nl/_825.Single-button-op-een-single-page-form-ook-links-laten-uitlijnen/components/detail/actieverzoeken.html

**Comment by gofix** [comment]
Na flink wat nader overleg hebben we gezamenlijk besloten een wat explicieter model voor de buttons te gaan hanteren. Daarmee mag de branch met de changes tot nu toe verdwijnen, en we pakken dit issue tezamen op met https://github.com/dso-toolkit/dso-toolkit/issues/841

De regels worden:
- in een `.dso-form-buttons` staan alle knoppen rechts uitgelijnd;
- tenzij deze wordt gekenmerkt als `.dso-single-page` (dan staat alles links);
- als in een niet-`.dso-single-page` opstelling bepaalde buttons juist LINKS moeten komen (zoals bv. een 'vorige stap'-knop), dan zet je deze knop, of meerdere knoppen, in een `.dso-aside`. (`.dso-aside` krijgt vooralsnog alleen betekenis als deze IN een `.dso-form-buttons` staat, maar kan evt. later ook ooit in andere werkvormen iets gaan betekenen).
