### ISSUE TITLE
Refactoring voorbeeldtemplates : Aanvragen stap 7 (Verzoeken indienen)

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#826]
In stap 7 'Verzoeken indienen' wordt een dropdown gebruikt om een verzoek ergens anders in te dienen. Hier was nooit de juiste styling vanuit de toolkit toegepast.

Nu wel, en daarbij is een stukje custom css gebruikt om de dropdown een width 100% te geven. Terwijl het component zelf dit ook al heeft.

```
.form-horizontal .dso-select > .dso-field-container {
  width: 100%;
}
```
Vanuit de toolkit wordt met een media query een width 50% gezet... een snelle check van Dion wees uit dat dit 3 jaar geleden was toegevoegd.

![Schermafbeelding 2020-10-30 om 11 43 11](https://user-images.githubusercontent.com/598735/97702255-f9a67700-1aae-11eb-841b-fab851da6547.png)

**Comment by PieterVerheij** [comment]
De markup is niet correct: de form-elementen staan in een definition list. Het probleem hier is dat het label direct in een `<dt>` staat en de `.dso-field-container` in een `<dd>` geplaatst is. Daarin is nooit voorzien. Het label en de select worden gegroepeerd in een `.dso-form-group, de `.dso-label-container` (voor het label) en de `.dso-field-container` (voor de select) hebben daarin beiden een `float: left; width: 50%`.

Zie https://www.dso-toolkit.nl/master/components/detail/group-select.html

![image](https://user-images.githubusercontent.com/25430835/98215850-97cf8c80-1f48-11eb-85bc-7a58db2d8670.png)

**Comment by MichielDHVD** [comment]
Voorbeeld pagina's bouwen om verbeterde pagina als inspiratie voor team

**Comment by bramhoosemans** [comment]
Besproken in refinement 05-11: de toegepaste markup is niet correct. We gaan de stap 'Verzoeken indienen' opnemen in de toolkit als voorbeeld voor implementatie.

Aandachtspunt is het wijzigen van de verzoeknaam en dropdown 'indienen bij'. Het is mogelijk dat nieuwe inzichten leiden tot noodzakelijke aanpassingen in het ontwerp. In de specificaties hieronder zijn ook de vervolgschermen opgenomen, omdat de definition list daar ook op staat.

Specificaties:
[verzoeken-indienen.zip](https://github.com/dso-toolkit/dso-toolkit/files/5500328/verzoeken-indienen.zip)

![102_verzoek-wijzigen--bevoegd-gezag](https://user-images.githubusercontent.com/598735/98349684-9b334880-201a-11eb-912f-fa2ff0b36c92.png)

**Comment by PieterVerheij** [comment]
Algemeen:
De verticale marges behoeven aandacht:
- bij formgroups zijn deze te groot (https://www.dso-toolkit.nl/_826.Voorbeeld-schermen-Aanvragen-stap-7-Verzoeken-indienen-opnemen-in-toolkit/components/detail/verzoeken.html)
- tussen sommige componenten ontbreekt er juist weer ruimte (bv. indienen scherm: o.a. ruimte rond confirm en vaak boven de `dso-form-buttons`

De kolombreedtes van definition-list en form verschillen. (https://www.dso-toolkit.nl/_826.Voorbeeld-schermen-Aanvragen-stap-7-Verzoeken-indienen-opnemen-in-toolkit/components/detail/verzoeken-indienen.html)

In dit geval zijn de getoonde legends bij meerdere fiedlsets juist niet gewenst? https://www.dso-toolkit.nl/_826.Voorbeeld-schermen-Aanvragen-stap-7-Verzoeken-indienen-opnemen-in-toolkit/components/detail/verzoeken.html

Horizontaal uitgelijnde/inline radiobuttons bestaan nog niet (https://www.dso-toolkit.nl/_826.Voorbeeld-schermen-Aanvragen-stap-7-Verzoeken-indienen-opnemen-in-toolkit/components/detail/omgevingsoverleg.html)

**Comment by bramhoosemans** [comment]
> Algemeen:
> De verticale marges behoeven aandacht:
> 
> * bij formgroups zijn deze te groot (https://www.dso-toolkit.nl/_826.Voorbeeld-schermen-Aanvragen-stap-7-Verzoeken-indienen-opnemen-in-toolkit/components/detail/verzoeken.html)
> * tussen sommige componenten ontbreekt er juist weer ruimte (bv. indienen scherm: o.a. ruimte rond confirm en vaak boven de `dso-form-buttons`

Ik weet niet of de marge bij formgroups te groot is. Binnen formulieren is 32px marge tussen input elementen gewenst. De class dso-static heeft wel paddings en min height die eraf kunnen volgens mij...

> De kolombreedtes van definition-list en form verschillen. (https://www.dso-toolkit.nl/_826.Voorbeeld-schermen-Aanvragen-stap-7-Verzoeken-indienen-opnemen-in-toolkit/components/detail/verzoeken-indienen.html)

Juist. Definition-list heeft een vaste breedte van 200px en een form (dso-static) een breedte van 50%. Lastige dit, ik zou niet zo weten hoe/of we de twee vormen kunnen combineren.

> In dit geval zijn de getoonde legends bij meerdere fieldsets juist niet gewenst? https://www.dso-toolkit.nl/_826.Voorbeeld-schermen-Aanvragen-stap-7-Verzoeken-indienen-opnemen-in-toolkit/components/detail/verzoeken.html

Als je dit gaat zien als formulier misschien wel. Ik denk dat er nooit zo naar gekeken is, een definition-list in een fieldset met legend is niet logisch. Het is wellicht een optie om elk verzoek een H3 'Verzoek X' te geven.

Alleen is dit een wijziging die best wat impact heeft op verschillende stappen/schermen. Dus alleen noodzakelijk is.

> Horizontaal uitgelijnde/inline radiobuttons bestaan nog niet (https://www.dso-toolkit.nl/_826.Voorbeeld-schermen-Aanvragen-stap-7-Verzoeken-indienen-opnemen-in-toolkit/components/detail/omgevingsoverleg.html)

Jawel hoor, alleen is het een beetje weggestopt. Zie 'inline': https://www.dso-toolkit.nl/14.0.0/components/detail/group-radios.html

> Voor dit het realiseren van dit issue zijn de volgende issues aangemaakt:
> #881 Bewerkenknop in Group static toevoegen
> #882 Definition-list in accordion

**Comment by PieterVerheij** [comment]
- Ik bedoelde idd static form-groups: daar zou de marge/padding weg kunnen. Alleen: heeft dat geen negatief effect op bv. een bevestigingscherm (bv. de controle-stap in een formulier voordat je het verzendt)?

- we zouden een modifier kunnen maken voor de fomulieren, die de kolombreedtes gelijk trekt met de definition-list

- Het is wellicht een optie om elk verzoek een H3 'Verzoek X' te geven. 
En dan bv. het eerste label hernoemen van 'Verzoek X' naar 'Object' en dat uit de waarde weghalen?

- Nou ja, wel inline radios. Ik ga een brilletje halen...

**Comment by bramhoosemans** [comment]
> * Ik bedoelde idd static form-groups: daar zou de marge/padding weg kunnen. Alleen: heeft dat geen negatief effect op bv. een bevestigingscherm (bv. de controle-stap in een formulier voordat je het verzendt)?

Momenteel gebruiken we in de PR12 gebruikerstoepassingen nergens 'static form-groups'. Ik weet alleen niet of dat ook voor andere applicaties geldt.

> * we zouden een modifier kunnen maken voor de fomulieren, die de kolombreedtes gelijk trekt met de definition-list
> * Het is wellicht een optie om elk verzoek een H3 'Verzoek X' te geven.
>   En dan bv. het eerste label hernoemen van 'Verzoek X' naar 'Object' en dat uit de waarde weghalen?

Ik vraag me af of het nodig is de huidige implementatie helemaal overhoop te halen. Uiteraard kan het mooier/beter, maar zouden we ook met minimale wijzigingen een goed resultaat kunnen krijgen?

**Comment by PieterVerheij** [comment]
Een extra modifier op een form (voor andere kolombreedtes) is in mijn optiek geen grote wijziging. Over het omnoemen van de labels: ik weet niet hoeveel werk dat is. Een andere oplossing is om de legends in een accordion kleiner te maken?

**Comment by gofix** [comment]
Zoals zojuist uitgebreid overlegd (met @bramhoosemans  en @PieterVerheij) -> voor nu adviseren we het team de oplossing nog maar even met lokale CSS te fixen. We gaan wel door met de vastlegging in de Toolkit op de meest koninklijke manier, en daaruit zullen dan ook nog wensen volgen tot finetuning van CSS, al dan niet (maar liefst zonder) met modifierclasses. 

Nu we wederom flinke toevoegingen aan het doen zijn aan de "Voorbeelden", wordt het tijd om nog eens goed na te denken over de indeling van die sectie. Zoals ook gisteren in https://github.com/dso-toolkit/dso-toolkit/issues/897 al bleek, is er soms behoefte aan vastlegging van voorbeeld-snippets, naast compleet uitgewerkte pagina's. Maar: daarvoor is dan wel een herindeling wenselijk, want nu al is het soms bijzonder moeilijk de juiste voorbeelden te vinden.

**Comment by PieterVerheij** [comment]
Nog even een recap van zaken die op staan:
- De kwestie van de h3s/legends kan gezien worden als een redactionele actie. 
- De kolombreedtes van het formulier wordt nu met custom-css aangepast. Vraag is of er een modifier wenselijk is die de kolombreedtes gelijk trekt en hoe.
- De verticale marge/padding bij static form-groups, als deze gebruikt worden in bv. een overzichtsscherm, zodat deze niet zoveel van elkaar af staan (zie bv. https://www.dso-toolkit.nl/_826.Voorbeeld-schermen-Aanvragen-stap-7-Verzoeken-indienen-opnemen-in-toolkit/components/detail/verzoeken-wijzigen.html)
- De verticale ruimte om een enkele form-group verdiend wat liefde (zie de confirm op https://www.dso-toolkit.nl/_826.Voorbeeld-schermen-Aanvragen-stap-7-Verzoeken-indienen-opnemen-in-toolkit/components/detail/verzoeken-indienen.html)

**Comment by MichielDHVD** [comment]
@PieterVerheij  Is deze in review ? Of terug naar progress ?

**Comment by PieterVerheij** [comment]
- De kolombreedtes van het formulier wordt nu met custom-css aangepast. Vraag is of er een modifier wenselijk is die de kolombreedtes gelijk trekt en hoe.
Indien wenselijk: nieuw issue

- De verticale marge/padding bij static form-groups, als deze gebruikt worden in bv. een overzichtsscherm, zodat deze niet zoveel van elkaar af staan (zie bv. https://www.dso-toolkit.nl/_826.Voorbeeld-schermen-Aanvragen-stap-7-Verzoeken-indienen-opnemen-in-toolkit/components/detail/verzoeken-wijzigen.html)
Indien wenselijk: nieuw issue

- De verticale ruimte om een enkele form-group verdiend wat liefde (zie de confirm op https://www.dso-toolkit.nl/_826.Voorbeeld-schermen-Aanvragen-stap-7-Verzoeken-indienen-opnemen-in-toolkit/components/detail/verzoeken-indienen.html)
Dit is door consequent gebruik van `div.row` en `div.cols-xx-xx` te realiseren.
