### ISSUE TITLE
List-button volgorde is niet logisch

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#829]
Bij een geselecteerde activiteit wordt de tekst voorgelezen:
Bouw activiteit  - Melding - Geselecteerd - Gemeente

Hier wordt onderstaande verwacht:
Bouw activiteit  - Melding - Gemeente - Geselecteerd

Dit hebben we aangepast door de volgorde van voorgeschreven markup te wijzigen. Maar.. nu komt het vinkje onder de optionele tekst. Zie implementatie in screenshot:

![Schermafbeelding 2020-11-02 om 13 27 27](https://user-images.githubusercontent.com/598735/97867992-2f499b00-1d0f-11eb-8fb2-d9a6b12ee440.png)

**Comment by PieterVerheij** [comment]
@bramhoosemans 
Ik neem aan dat je ook wilt:
Bouw activiteit - Melding - Gemeente - 2x geselecteerd

**Comment by PieterVerheij** [comment]
https://www.dso-toolkit.nl/_829.List-button-volgorde-is-niet-logisch/components/detail/list-button.html
