### ISSUE TITLE
WCAG Navbalk verbeteren 

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#833]
- Aria-current toevoegen aan geselecteerde pagina
- Alle referenties naar tab verwijderen data-role=tab ? etc.

**Comment by daverhelst** [comment]
Na overleg met @MichielDHVD is duidelijk geworden dat dit over de Navbar van de Toolkit zelf gaat. Nu zie ik best wel wat scripting hangen op `data-role=tab`, dus ik denk dat het handig is als @tfrijsewijk hier naar kijkt.

Ik heb wel in het component de `aria-current` toevoeging gedaan op het actieve item.

**Comment by gofix** [comment]
Is het toepassen van een `aria-current` genoeg, voor de meeste gangbare screenreaders? 
Of is het ook nog wenselijk een `sr-only` tekstje "geselecteerd" op te nemen? Of... juist niet, omdat het dan dubbel voorgelezen wordt...?

**Comment by timveld** [comment]
Aria technieken zijn voor WCAG over het algemeen sufficient. Volgens mij ondersteunen alle moderne screen readers aria-current en in ieder geval hangt de oplossing niet op aria, als je niet meekrijgt welke pagina geselecteerd is kun je dat eenvoudig uit de h1 afleiden. Aria-current vs sr-only is een ontwerpkeuze, en voor DSO zou ik dan de voorkeur geven aan aria. We verwachten voor zo'n moderne applicatie een up to date screen reader en het voordeel van Aria is dat een screen reader op zijn eigen manier met de situatie kan omgaan, in JAWS kun je bijvoorbeeld tot op steeds grotere hoogte instellen welke attributen wel / niet worden vorgelezen en sommige mensen vinden dit soort meldingen bovenmatig storend. Overigens kleine aanvulling mbt "the first rule of aria is not to use it": daarmee wordt vooral bedoeld dat je aria niet moet gebruiken als met semantische html hetzelfde wordt bereikt. Met deze uitspraak wordt niet bedoeld dat een sr-only oplossing per se de voorkeur heeft.

**Comment by gofix** [comment]
Kijkend naar de input van @timveld kan ik dan niet anders concluderen dan dat de huidige changes uit het PR in orde zijn. @daverhelst voeg je ook nog even een regeltje aan het changelog toe, dan kunnen we de boel gaan mergen!

**Comment by daverhelst** [comment]
@gofix Absoluut, de regel is toegevoegd aan het changelog
