### ISSUE TITLE
Web Component: Alert

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#838]
# `.alert`

Het Alert component omzetten naar een StencilJS Component

**Comment by gofix** [comment]
@tfrijsewijk nu in #765 de markup van alert is gewijzigd, moet dat ook nog in het webcomponent worden doorgevoerd:
![image](https://user-images.githubusercontent.com/2689559/98912141-facf9f00-24c5-11eb-91e6-535f7c7120c5.png)
