### ISSUE TITLE
Button positionering wizard issues

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#841]
Bij implementatie van 'form met submit button in de wizard' lopen we tegen een aantal issues aan:

- Multipage form werkt niet met btn-link. In de wizard gebruiken we tertiaire buttons voor 'vorige stap'. Deze worden momenteel helemaal rechts uitgelijnd.
- Wat we ook gemist hebben is dat het ook mogelijk is dat er alléén een 'vorige stap' button staat. Op dit moment is dit niet mogelijk en wordt de button altijd rechts uitgelijnd.

![Schermafbeelding 2020-11-06 om 13 29 26](https://user-images.githubusercontent.com/598735/98366341-1a814600-2034-11eb-835e-9eaacb1da4a1.png)

![Schermafbeelding 2020-11-06 om 13 30 14](https://user-images.githubusercontent.com/598735/98366399-34bb2400-2034-11eb-8d8b-44dd1368071a.png)

**Comment by gofix** [comment]
Je 2e bevinding is volgens mij hetzelfde als https://github.com/dso-toolkit/dso-toolkit/issues/825, daar was @MichielDHVD ook al eerder tegenaan gelopen (en: daar komt dus al een oplossing voor). Maar we zullen het nog even extra checken.

**Comment by bramhoosemans** [comment]
> Je 2e bevinding is volgens mij hetzelfde als #825, daar was @MichielDHVD ook al eerder tegenaan gelopen (en: daar komt dus al een oplossing voor). Maar we zullen het nog even extra checken.

Nu je het zegt.. dat zou heel goed kunnen.

**Comment by PieterVerheij** [comment]
Gecheckt: tweede punt is idd afgevangen met #825 omdat de selector `only-child` gebruikt wordt.

**Comment by PieterVerheij** [comment]
@bramhoosemans 
![image](https://user-images.githubusercontent.com/25430835/98532914-9a045480-2282-11eb-8823-02e4f6aee656.png)

Wat betreft het eerste punt: willen jullie daar echt tertiaire buttons gebruiken ipv secundaire? Daar was idd niet in voorzien en om dit te faciliteren is er iig een **breaking** change nodig. De logica van de (linkse) uitlijning van de "vorige" hangt juist aan feit dat de eerste knop geen tertiaire (btn-link) knop is. Wanneer  je dat uit de logica verwijdert, gaan knoppen in andere scenarios ook aan de wandel. Dus ontkom je niet aan markup en css aanpassingen.

**Comment by bramhoosemans** [comment]
@PieterVerheij Ja, zo hebben we het destijds ook besproken in https://github.com/dso-toolkit/dso-toolkit/issues/401. Zie comment van 28 Nov 2019. Dat is dan toch gemist bij het testen... of heeft het eerder wel gewerkt?

**Comment by PieterVerheij** [comment]
Ik zie het idd. Maar gezien de opgetogen reactie van ons beiden, krijg je de indruk dat het wel ooit gewerkt heeft.

**Comment by bramhoosemans** [comment]
> Ik zie het idd. Maar gezien de opgetogen reactie van ons beiden, krijg je de indruk dat het wel ooit gewerkt heeft.

Ja, die indruk had ik ook!

> Gevonden, in het kader van #670 is de modifier aangepast van `link` naar `default`.

Ai, dan hebben we die gemist.. Zouden we niet beter een generieke modifier kunnen gebruiken ipv de logica aan de btn class te hangen? Bijvoorbeeld extra class 'previous' of 'back'

**Comment by PieterVerheij** [comment]
En dat die dan `btn-previous` altijd links uitgelijnd is? Dat is een optie. Wat vind jij, @tfrijsewijk ?
@tfrijsewijk had ook het idee om `.dso-form-buttons` op te splitsen in twee divs, waarin in de eerste div de buttons links en in de tweede div de buttons rechts uitgelijnd worden. Maar dan leg je wel veel verantwoordelijkheid voor de juiste implementatie bij de ontwikkelaar.

**Comment by bramhoosemans** [comment]
Beide opties zijn prima.

**Comment by gofix** [comment]
Na flink wat nader overleg hebben we gezamenlijk besloten een wat explicieter model voor de buttons te gaan hanteren. Daarmee mag de branch met de changes tot nu toe verdwijnen, en we pakken dit issue tezamen op met https://github.com/dso-toolkit/dso-toolkit/issues/825

De regels worden:
- in een `.dso-form-buttons` staan alle knoppen rechts uitgelijnd;
- tenzij deze wordt gekenmerkt als `.dso-single-page` (dan staat alles links);
- als in een niet-`.dso-single-page` opstelling bepaalde buttons juist LINKS moeten komen (zoals bv. een 'vorige stap'-knop), dan zet je deze knop, of meerdere knoppen, in een `.dso-aside`. (`.dso-aside` krijgt vooralsnog alleen betekenis als deze IN een `.dso-form-buttons` staat, maar kan evt. later ook ooit in andere werkvormen iets gaan betekenen).
