### ISSUE TITLE
Refactoring voorbeeldtemplates : Wizard stap 2 (Locatie)

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#845]
Wizard stap 2 'Locatie' uitbreiden met coördinaten. Op dit moment zit deze met kunst en vliegwerk in elkaar, zie https://pre.omgevingswet.overheid.nl/checken/stap/1. De wens is om een voorbeeld van de juiste markup en componenten in de toolkit op te nemen.

https://dso-toolkit.nl/12.0.0/components/detail/wizard-stap-2.html

![coordinaten](https://user-images.githubusercontent.com/598735/98545092-3afc0b00-2295-11eb-8744-c62def7f9aa5.png)
![coordinaten-gekozen-locatie](https://user-images.githubusercontent.com/598735/98545097-3df6fb80-2295-11eb-818a-d43b60f2cdfe.png)

**Comment by PieterVerheij** [comment]
ZIe https://www.dso-toolkit.nl/_845.Voorbeeld-Wizard-stap-2-uitbreiden/components/detail/wizard-stap-2.html.

Twee issues:
- de velden (of eigenlijk knop) zijn te breed. Een icon-only button zou dit oplossen.
- De verticale uitlijning is niet goed. Hier zou een extra modifier voor moeten komen die dit oplost. Dit zou een oploossingsrichting kunnen zijn: https://v4-alpha.getbootstrap.com/utilities/flexbox/#align-items

**Comment by PieterVerheij** [comment]
Markup cleanup, velden naast elkaar met `display: flex`.

**Comment by bramhoosemans** [comment]
Een paar vragen/opmerkingen:

- Zouden we de titel met de dropdown button kunnen uitlijnen? Of gaat dat niet ivm top margin van headings?
- Volgens mij moeten we iets met first/last form-group om de padding tussen de velden te verkleinen naar 16px.
- Er wordt veel gebruik gemaakt van `div class="clearfix"`, is dat onvermijdelijk?
- Er zit nu 2x een div met class `dso-form-buttons` in, maar geen van de twee hebben een `type=submit`. Volgens mij valideert de pagina dan niet.

**Comment by MichielDHVD** [comment]
@PieterVerheij

**Comment by PieterVerheij** [comment]
- Zouden we de titel met de dropdown button kunnen uitlijnen? Of gaat dat niet ivm top margin van headings?
Inderdaad, de margin-top van de heading is hier spelbreker.

- Volgens mij moeten we iets met first/last form-group om de padding tussen de velden te verkleinen naar 16px.
Aangepast

- Er wordt veel gebruik gemaakt van div class="clearfix", is dat onvermijdelijk?
Door consequent gebruik van `div.row` en `div.cols-xx-xx` is dit te realiseren zonder `.clearfix`. (moet nog doorgevoerd worden)

- Er zit nu 2x een div met class dso-form-buttons in, maar geen van de twee hebben een type=submit. Volgens mij valideert de pagina dan niet.
Goed gezien! Laatste knop is een submit geworden.

**Comment by bramhoosemans** [comment]
> * Zouden we de titel met de dropdown button kunnen uitlijnen? Of gaat dat niet ivm top margin van headings?
> Inderdaad, de margin-top van de heading is hier spelbreker.

Voor nu zo laten dan. Ik werk aan een verbetering van 'locatie kiezen' waarbij de dropdown button waarschijnlijk verdwijnt.

> * Volgens mij moeten we iets met first/last form-group om de padding tussen de velden te verkleinen naar 16px.
> Aangepast

Top! Als je deze nu op 8px zetten, dan is tie helemaal volgens ontwerp ;-)
