### ISSUE TITLE
Search Bar border kleur gelijk maken aan invoerveld

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#846]
Search Bar border kleur gelijk maken aan invoerveld: `border: 1px solid #275937;`

![Schermafbeelding 2020-11-09 om 15 38 03](https://user-images.githubusercontent.com/598735/98554917-9207dd00-22a1-11eb-8573-726569d44377.png)
![Schermafbeelding 2020-11-09 om 15 37 53](https://user-images.githubusercontent.com/598735/98554918-92a07380-22a1-11eb-9ff6-c2f90cc1c826.png)

**Comment by PieterVerheij** [comment]
Aanvullende wens: "kan de losse search bar ook ‘invalid’ styling krijgen"
"Dan nog een andere vraag: bij een ‘losse’ search bar zie ik geen ‘invalid’ styling: https://dso-toolkit.nl/14.0.0/components/detail/search-bar.html. Bij de ‘group search bar’ is deze er wel: https://dso-toolkit.nl/14.0.0/components/detail/group-search-bar.html. Ik had al geprobeerd de dso-invalid class aan de parent toe te voegen, maar dit heeft ook geen effect. Zie ik iets over het hoofd? Zo nee, kan de losse search bar ook ‘invalid’ styling krijgen?"
