### ISSUE TITLE
Rich content component

### ISSUE THREAD

**Issue by VolleMelk** [dso-toolkit/dso-toolkit#85]
Bootstrap geeft veel elementen, componenten en werkvormen verticale uitlijning waardoor het horizontaal uitijnen niet te voorspellen is.

Bijvoorbeeld: Een bootstrap list group (`ul.list-group`) krijgt `margin-bottom: 20px`. Als dit component in een uitgelichte rij wordt geplaatst (`.row.dso-featured` - rij die over de gehele breedte een groene steunkleur krijgt) krijg je visueel een ruimte van 68px aan de onderkant: `ul.list-group { margin-bottom: 20px }` + `.row.dso-featured { padding-bottom: 48px }` = 68px.

In dit specifieke geval moet de margin-bottom van de list-group gehaald worden. Een van de oplossingen kan zijn dat elementen geen _visuele ruimtes_ meer mag zetten.

De grote vraag is dan weer: Wat gebeurt er als ik _twee_ `ul.list-group`'s achter elkaar zet?
* De [Adjacent silbing selector](https://developer.mozilla.org/en-US/docs/Web/CSS/Adjacent_sibling_selectors): `.list-group + .listgroup + { margin-top: 20px }`
* Als het list-group component door een andere component wordt gebruikt, moet dit component daar op anticiperen.

Maar dit terzijde, dit was slechts onderbouwing voor het volgende probleem:

De typografische elementen krijgen vanuit Bootstrap ook deze verticale uitlijning mee. In vaste werkvormen zoals een Jumbotron is dat makkelijk weg te stijlen: `.jumbotron h1 { margin-top: 0 }`.

Maar er is nog geen oplossing voor redactionele-, user of andere (gegeneerde) rich-content. Denk aan een reactie op een artikel uit een WYSIWYG editor. Als hier een kop wordt gemaakt wat uitmondt op (bijvoorbeeld) een `h3`. Deze krijgt een margin-top van Bootstrap. Als deze content op een achtergrondkleur staat kan de ruimte boven de kop visueel te veel zijn.

Voor dit probleem wil ik component "Rich content" voorstellen. Teksten uit dit soort editors worden in een `.dso-rich-content` geplaatst. De elementen kunnen vervolgens hier op worden gescoped zonder dat de verticale uitlijning van de elementen die nu al worden gebruikt omvalt.

Een tastbaar voorbeeld kan bijvoorbeeld een landingspagina met een welkomstekst naast een jumbotron of een opsomming van reacties.

Geldige elementen die in een `.dso-richt-content` geplaatst mogen worden zijn:

* h2-h5
* p
* a
* table
* ol
* ul
* ul.listgroup
* b/strong
* i/em
* u/span.underline
* s/del/ins
* cite
* blockquote/q

**Comment by VolleMelk** [comment]
@MichielDHVD Kun jij hier een nachtje over slapen?

**Comment by MichielDHVD** [comment]
@VolleMelk  Dat klinkt als een uitstekend idee. 

Waar ik vooral naar kijk bij zon onderdeel is implementatie. Hoeveel vrijheden krijgen de devs? 
Langzaam aan moet er denk ik een best practices document worden ontwikkeld (Liefst doen we dat direct in de toolkit, zoals bij de buttons en de gebruiksregels) 

Zodat developers duidelijk weten waar en wanneer ze iets kunnen gebruiken. 

Je geeft 2 voorbeelden: Landingspagina + welkomstekst - een opsomming van reacties. 

Zijn er misschien meer voorbeelden die we kunnen gebruiken? Waar ik vooral naar opzoek ben is voorbeelden in context die we dan kunnen laten zien. Zodat het kader waar dit component wordt gebruikt duidelijk is.

**Comment by VolleMelk** [comment]
Ik vind het lastig om die voorbeelden te geven, ik ben in die zin niet op de hoogte van complete applicaties en hun vormgeving. Juist daarom vind ik het zo belangrijk dat er voorbeelden in context worden aangeleverd alvorens ik werkvormen ga uitwerken, zoals bijvoorbeeld bij #78.

De voorbeelden waar ik nu mee kwam, zijn verzonnen om de `.row.dso-featured` en jumbotron te demonstreren voor #61. Aangezien er 'van alles' kan staan heb ik een mock up pagina gemaakt:

![screencapture-localhost-3000-components-preview-full-width-2018-03-27-09_45_21](https://user-images.githubusercontent.com/9696261/37953611-af853f90-31a3-11e8-9f68-bb87a989545c.png)

Dit is een pagina met 6 rijen (`.row)`.
* In de eerste row staan twee componenten: Een inhoudsblok met een welkomsttekst in een `.dso-rich-content`. Daarnaast staat Bootstrap's variant van #61.
* De tweede row heeft twee componenten: Een list-group met titel. Daarnaast een tabel met titel en caption
* De derde row heeft een jumbotron
* De vierde row heeft een inhoudsblok met een uitgebreide rich text
* De 5e en 6e row zijn weer jumbotrons.

De `.dso-featured` modifier op een `.row` maakt de rij pagina breed met een steunkleur. Deze modifier zit op de 1e, 2e, en 5e row.

Om het gedrag van #47 goed te kunnen ontwikkelen (groene steunkleur = geen border, wat te doen bij meerdere featured enz enz) heb ik een typische landingspagina gemaakt zoals het IPROX CMS dit kan maken (en waarschijnlijk elk ander CMS).

En toen kwam ik op het `.dso-rich-content` component uit. Veel meer dan dit kan ik niet leveren. Maar alles wat met redactionele- en userinput uit een WYSIWYG kan komen zou in een `.dso-rich-content` moeten komen.

De vraag van de vrijheden van de developers begrijp ik niet helemaal. Welke componenten er in een `.dso-rich-content` kunnen? Kun je deze vraag verder toelichten, of heb ik 'm al beantwoord met bovenstaand betoog?

**Comment by VolleMelk** [comment]
Juist! Een werkvorm/component als jumbotron of accordion zal geen `.dso-rich-content` implementeren: De werkvorm staat vast. Maar bij een interactieve werkvorm zoals een reactiemodule of gebruiker gegenereerde content wil je die content kunnen sturen.

Een developer/editor kan in een `.dso-rich-content` alles plaatsen, maar dat betekent niet dat het goed is. Wat mag zal uitgewerkt moeten worden.

Ik heb naar een opmaakprofiel van een van onze sites gekeken, de volgende componenten kan door een gebruiker gemaakt worden:

* h1-h5 (misschien juist _niet_ de h1 ?)
* p
* a
* table
* ol
* ul
* ul.listgroup
* b/strong
* i/em

**Comment by MichielDHVD** [comment]
Kijk dan heb ik alvast een start om over na te denken over guidelines en waar het moet aan voldoen. 

Ik denk dat h1 verwijderd moet worden inderdaad. Die zal consistent blijven. 

Zijn er nog specs of dingen die je van mijn nodig hebt?

**Comment by VolleMelk** [comment]
Ik heb de initiele post bijgewerkt met onze suggesties. Ik heb `span.underline`, `s/del/ins` toegevoegd aan de specificatie, mee eens?

Ik stel voor dit component in de volgende versie (1.3.0) uit te brengen. Dit is een prima begin, finetuning kan altijd nog.

**Comment by Poofy83** [comment]
Even ter aanvulling; In principe kunnen alle elementen in het `.dso-rich-content` vlak elkaar opvolgen. Het voorbeeld wat @VolleMelk geeft in de eerste post dekt maar een klein deel van het probleem.

`.list-group + .listgroup` zou bijvoorbeeld net zo goed `.list-group + *` kunnen zijn, of eigenlijk `* + *` waarbij de `*` wel de elementen zijn die hierboven zijn aangegeven.

Kortom, naar mijn idee wil je alle basis styling intact laten, maar uit zien te vinden wat het eerste en het laatste kind is en hier vervolgens de verticale, respectievelijk top en bottom, ruimtes op 0 zetten zodra het een `.dso-rich-content` betreft.

**Comment by Poofy83** [comment]
Er is gekozen voor een oplossing waarbij `.dso-rich-content:first-child` een `margin-top: 0` heeft en `.dso-rich-content:last-child` een `margin-bottom: 0` heeft. Dit zodat we dan altijd controle hebben over de marges aan de boven- en onderkant.
