### ISSUE TITLE
Verschillende form-indelingen in afzonderlijke stappen van accordion

### ISSUE THREAD

**Issue by gofix** [dso-toolkit/dso-toolkit#851]
In https://github.com/dso-toolkit/dso-toolkit/pull/784 vroeg ik mij af of het in een accordion zou kunnen voorkomen of je in een stap (section) een verticale formulierindeling, en in een andere stap een horizontale formulierindeling zou kunnen hebben.

Het antwoord daarop was (https://github.com/dso-toolkit/dso-toolkit/pull/784#issuecomment-701948722):
> Ik kan me eerlijk gezegd geen situatie bedenken dat we binnen één formulier verschillen willen hebben in uitlijning van labels en velden. Vooralsnog prima om `form-horizontal` op het `<form>` te laten staan lijkt me.

Het lijkt er nu echter op dat dit toch zou moeten kunnen varieren. NB: We kijken naar feature branch `f/PR12-9135-wizard-button-styling` in `pr12/alexia`.

**Comment by bramhoosemans** [comment]
Juist, dit was een foutieve inschatting van mijn kant.

**Comment by gofix** [comment]
Allereerst: Wanneer we kijken naar https://dso-toolkit.nl/12.0.0/components/detail/aanvragen.html zien we dat wordt voorgeschreven dat de diverse onderdelen van de pagina (resp. headings, de accordion zelf, en de `.dso-form-buttons`) ieder in een eigen `.row > .col-md-12` staan, met name voor voorspelbare verticale tussenruimtes tussen deze pagina-onderdelen;

In de feature branch `f/PR12-9135-wizard-button-styling` echter zien we
```
<FormHorizontal>
  <!-- ... -->
  <div className="dso-form-buttons">
    <!-- ... -->
  </div>
</FormHorizontal>
```
En die `<FormHorizontal>` staat in een `.row > .col-xs-12`. Dus: `.dso-form-buttons` zal niet de juiste verticale ruimte hanteren t.o.v. `{renderedChildren}`: de accordion dus.

**Comment by gofix** [comment]
Uitgaande van:
- dat er in de accordion altijd maar 1 sectie tegelijk open is (en er dus geen behoefte bestaat aan een `<fieldset />` om op die manier onderscheid te maken tussen de secties);
- er _toch_ behoefte is aan verschillende formulierindelingen tussen secties;
is de eenvoudigste oplossing wellicht 
- het `<FormHorizontal>` in z'n geheel OM de `.row`s van deze pagina heen te zetten (zoals in het voorbeeld);
- maar, dit component niet zozeer `<FormHorizontal>` te laten zijn, maar juist `<Form>` met als optionele prop de className `form-horizontal`;
- zo kan dan per stap (maar wel van bovenaf...) bepaald worden of de sectie die open is, verticaal of horizontaal moet worden gegroepeerd;

**Comment by gofix** [comment]
Alternatieve oplossing is op het omliggende `<form>` toch maar GEEN className te specificeren, en dit juist per `.dso-section-body` te doen. Als ik daar `.form-horizontal` op zet lijkt het beoogde resultaat ook bereikt te worden.

**Comment by bramhoosemans** [comment]
> Alternatieve oplossing is op het omliggende `<form>` toch maar GEEN className te specificeren, en dit juist per `.dso-section-body` te doen. Als ik daar `.form-horizontal` op zet lijkt het beoogde resultaat ook bereikt te worden.

Deze oplossingsrichting heeft de voorkeur. Als het niet nodig is om logica in de wizard toe te voegen die bepaalt of het <form> vertical of horizontal moet worden, dan scheelt dat veel tijd/geld/etc.

**Comment by gofix** [comment]
Dus, als het omliggende `<form>` geen `class` krijgt, kan eenvoudig per sectie van een formulier bepaald worden of label en input verticaal moeten worden getoond (dat is de default), of toch naast elkaar (dus: met een `.form-horizontal`). De class `.form-horizontal`-class kan overal worden geplaatst, zolang dit maar buiten/boven de `.form-group` gebeurt. In geval van een accordion lijkt de meest logische plek de `.dso-section-body`.

Zie https://codepen.io/gofix/full/pobGXMR

Belangrijk: als voor een applicatie de oriëntatie per onderdeel moet kunnen verschillen, zoals dus hier gewenst is, moet NIET `.form-horizontal` op de buitenste `<form>` gezet worden (zie in mijn codepen het onderste voorbeeld), want je kunt dat dan vervolgens niet in de stap 'ongedaan maken'. Als dat wenselijk zou zijn, zou dit een change in de DSO Toolkit vergen (want: dan heb je iets als `.form-vertical` nodig).

**Comment by gofix** [comment]
NB: als een stap meerdere fieldsets zou hebben, kan ook per fieldset `.form-horizontal` worden toegepast:
https://codepen.io/gofix/full/bGezXgw
