### ISSUE TITLE
Web Component: Breadcrumbs

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#858]
# `ol.breadcrumb`

Dependencies:
* Clearfix #855

Was ooit een Bootstrap v3.4.1 component: https://getbootstrap.com/docs/3.4/components/#breadcrumbs maar is overgenomen en heeft DSO specifieke verbeteringen gekregen in #648.

* `packages\dso-toolkit\components\Componenten\breadcrumbs\breadcrumbs.njk`
* `packages\dso-toolkit\components\Componenten\breadcrumbs\breadcrumbs.config.yml`
* `packages\dso-toolkit\src\styles\components\_breadcrumbs.scss`

Voorstel:

```html
<dso-breadcrumbs>
  <dso-breadcrumb href="home">
    Home
  </dso-breadcrumb>
  <dso-breadcrumb href="contact">
    Contact
  </dso-breadcrumb>
</dso-breadcrumbs>
```

Maar dit wordt een ding. Aandachtspunten zijn framework integraties

Research:
* https://stackoverflow.com/questions/52421298/web-components-how-to-work-with-children

**Comment by hansgrimm** [comment]
is dit nog courant?
