### ISSUE TITLE
Documentatie Anchor, Cards Definition List.

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#872]
Componenten documentatie voor release week 48 - 16.6 

Aanpassingen aan voorbeeld pagina's zodat documentatie en pagina's overeenkomen:

-  Externe links bevatten in landingspagina's geen sr-only met  "opent in nieuw venster" en ook geen target blank
-  In de beheer-basis voorbeeldpagina staat een definition list maar deze is nog opgebroken in bootstrap kolommen en niet met de functionaliteit die de definition list zelf gebruikt.

**Comment by MichielDHVD** [comment]
@gofix Ik zie nu ik de documentatie van definition list aan het aanpassen bij dat er nog wip staat. Weghalen neem ik aan? Is niet meer work in progress.

**Comment by MichielDHVD** [comment]
Ik breid deze deze story een klein beetje uit. Er zijn namelijk wat voorbeeld pagina's die nog oude werkvormen bevatten. 

Anders zeggen we in de documentatie het een en tonen we in de voorbeeld pagina wat anders. Wat aangepast wordt aan de voorbeeldpagina's wordt omgeschreven in  het issue.

**Comment by gofix** [comment]
Inhoudelijk absoluut een fraaie bijdrage, maar ik heb nog wel wat muggezifterij over de codestyle (backticks, curly quotes, etc.

**Comment by MichielDHVD** [comment]
Ga je erbij zetten waar het anders moet? Ik kan me herinneren (deze is al weer een tijdje terug) dat ik veel heb moeten vechten met formatting omdat anders de layout er raar er uit ging zien.
