### ISSUE TITLE
Dropdown is niet met pijltjes te navigeren.

### ISSUE THREAD

**Issue by PieterVerheij** [dso-toolkit/dso-toolkit#875]
In tegenstelling tot het Bootstrap component 'Dropdown', is de uitklapper van het DSO component niet met de pijltjestoetsen te navigeren.
Uitzoeken waardoor dit komt en of component aanpassen of een duidelijkere instructie voor developers schrijven over hoe dit te activeren.

**Comment by timveld** [comment]
Je was me net voor want bij het documenteren viel me op dat we dit nog helemaal niet goed hebben. Zie voor hoe het wel moet https://www.w3.org/TR/wai-aria-practices/examples/menu-button/menu-button-links.html

**Comment by bramhoosemans** [comment]
Duidelijkere instructie voor developers schrijven bij gebruik CSS vorm.

**Comment by PieterVerheij** [comment]
https://getbootstrap.com/docs/3.3/components/#dropdowns
https://getbootstrap.com/docs/3.3/javascript/#dropdowns

**Comment by gofix** [comment]
@MichielDHVD zie https://dso-toolkit.nl/_875.Dropdown-is-niet-met-pijltjes-te-navigeren/components/detail/dropdown-button.html, wat denk je, goed genoeg?
