### ISSUE TITLE
Web Component: Date Picker

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#877]
Date Picker als webcomponent voor de verschillende DSO toepassingen gebaseerd op https://github.com/infoprojects/date-picker

Functionele wensen:
- Meegeven welk jaar/maand de kalender opent.
- Alleen datum in verleden of toekomst selecteren.

Specificaties: [Datepicker.zip](https://github.com/dso-toolkit/dso-toolkit/files/5643459/Datepicker.zip)

![datepicker](https://user-images.githubusercontent.com/598735/101178974-eb1d2380-3649-11eb-95f2-90d7e22c4665.png)
![Schermafbeelding 2020-12-04 om 15 58 24](https://user-images.githubusercontent.com/598735/101178983-ef494100-3649-11eb-84a8-4d42e429e17a.png)

**Comment by PieterVerheij** [comment]
Testresultaten @bramhoosemans :
- Default browser focus-state in de date picker gebruiken. Of moeten we dat hier juist wél zelf zetten? 
Apart issue https://github.com/dso-toolkit/dso-toolkit/issues/964

- Als je met tab navigeert wordt na de datum van vandaag de ‘sluiten’ button weergegeven. Is dat dezelfde als in de mobiele weergave?
Styling gelijkgetrokken (ronde border bij focus)
https://files.slack.com/files-pri/TB52M2Y23-F01JNKQHPJ5/schermafbeelding_2021-01-08_om_16.13.39.png

- Fontgrootte datum 16px (1 rem) ipv 14px
aangepast

- Datum buiten huidige maand tekstkleur #666
Aangepast

-  Datum disabled tekstkleur #666
Aangepast

- Labels 'Datumveld’ beschrijvend maken. Bijvoorbeeld ‘Minimum en maximum datum’.
Aangepast
