### ISSUE TITLE
Duplicate line in table header

### ISSUE THREAD

**Issue by DjangoBlok** [dso-toolkit/dso-toolkit#89]
The table header has a black line at the bottom 
The first row has a dotted line at the top
This looks strange, this first dotted line should be invisible

**Comment by VolleMelk** [comment]
Ik heb het ontwerp gevonden waar de table-component op is gebasseerd:

![image](https://user-images.githubusercontent.com/9696261/38131867-fa076e78-3408-11e8-9a0d-c493d9656a18.png)

We gaan die dotted border bij de eerste rij weghalen
