### ISSUE TITLE
Toevoeging aria-invalid attribuut op invalid inputs

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#893]
Bij inline validatie, zetten we de class .dso-invalid als de input ongeldig is, maar is dat voldoende om technisch aan WCAG te voldoen? Of zouden we standaard ook "aria-invalid" moeten toevoegen?

https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA21

**Comment by timveld** [comment]
Is er in deze situatie ook (altijd) een tekstuele foutmelding? Dan is het misschien voldoende dat deze als alert wordt gegeven en/of programmatisch aan het veld wordt gekoppeld, bijv. toeoegen aan label / aria-describedby. En dan is aria-invalid dubele informatie. Als er geen tekstuele melding is dan is een css class uiteraard niet voldoende, in combinatie met aria-invalid wel.

**Comment by bramhoosemans** [comment]
Voorbeeld maken en laten testen door Tim.

**Comment by daverhelst** [comment]
@timveld Ik heb een variant toegevoegd genaamd "Ongeldig - met aria-invalid", die je hier kunt testen: https://dso-toolkit.nl/_893.Inline-validatie-toegankelijk-genoeg/components/detail/group-input.html

**Comment by timveld** [comment]
Hij lijkt het wel corect voor te lezen maar je hebt alleen aria-invalid =ipv aria-invalid="true") gebruikt. Geeft ook een error in de w3c validator. Bovendien wordt het e-mail label op dit veld niet voorgelezen maar dat komt waarschijnlijk door een duplicate ID.

**Comment by daverhelst** [comment]
@timveld ik heb het aangepast, je kunt nog eens kijken of het zo goed gaat

**Comment by timveld** [comment]
Werkt behalve dat het e-mail label dubbel wordt voorgelezen (vermoedelijk duplicate ID's) Maar ongeldige invoer wordt dus goed vermeld.

**Comment by daverhelst** [comment]
@timveld Het is wel vreemd dat het e-mail label dubbel wordt voorgelezen, aangezien er geen duplicate ID's meer zijn. Wat wel zo is, is dat elke invalide invoer hetzelfde label gebruikt. Is dat misschien het geval?

**Comment by timveld** [comment]
Inderdaad vreemd want ik zie niets in de code wat dit kan veroorzaken en de code valideert nu wel. Op een andere computer leest NVDA de velden ook niet dubbel voor, vreende caching issue? In ieder geval zou het zo dus goed moeten zijn.

**Comment by MichielDHVD** [comment]
Labeling wordt meegenomen bij het aanpassen van deze story.

**Comment by daverhelst** [comment]
Even ter controle; @gofix @timveld, nu we hebben besloten om de aria-invalid op alle input vormen in te gaan zetten. Wordt dit een eigen variant, of is het niet logischer om dit gewoon in de "Ongeldige" variant te plaatsen? Het lijkt me namelijk niet dat er een ongeldige variant mag gaan bestaan waarbij er _geen_ aria-invalid op de input is gezet.

**Comment by timveld** [comment]
@daverhelst  we moeten aria-invalid inderdaad op alle ongeldige velden zetten, dus geen op zichzelf staande variant
