### ISSUE TITLE
Dropdown-button ook als tertiaire button kunnen inzetten

### ISSUE THREAD

**Issue by PieterVerheij** [dso-toolkit/dso-toolkit#894]
Voor het voorbeeldscherm van #845 is de volgende wijziging gewest:
- dropdown-button ook als tertiaire button kunnen inzetten
- icon kunnen gebruiken in tertiaire dropdown-button

**Comment by bramhoosemans** [comment]
@PieterVerheij dit is toch al mogelijk? Passen we dit niet al toe in de versie-selectie van de toolkit?

**Comment by PieterVerheij** [comment]
@bramhoosemans Ja, maar het was niet vastgelegd in de code.

**Comment by bramhoosemans** [comment]
@PieterVerheij momenteel heb ik een WCAG bevinding die hier mogelijk aan gerelateerd is. De knop 'meer zoekopties' ontvangt geen zichtbare toetsenbordfocus.

Het lijkt erop dat er nog iets in de DSO Toolkit staat:
![Schermafbeelding 2020-12-17 om 14 07 16](https://user-images.githubusercontent.com/598735/102491943-3afbe180-4071-11eb-838a-af607cf4ab17.png)

**Comment by PieterVerheij** [comment]
https://www.dso-toolkit.nl/_894.Dropdown-button-ook-als-tertiaire-button-kunnen-inzetten/components/detail/dropdown-button.html

**Comment by bramhoosemans** [comment]
Hi @PieterVerheij er vallen me een aantal dingen op:
- Het label staat niet in een `<span>`.
- Het icoon (svg) heeft geen 8px marge met het label.
- Het label krijgt geen underline op hover.
- Bij de default button wordt een niet ondersteund icoon gebruikt (volgens mij nog een oude implementatie svg iconen).
- De focus state van de default button bevat een ongewenste underline.

Ook het dropdown menu zelf wijkt af van het originele ontwerp:
- Er wordt een border geplaatst en een lichte dropshadow, terwijl in Sketch het volgende wordt gezet: `box-shadow: 0 8px 10px 1px rgba(0,0,0,0.40);`.
- Op hover en focus krijgt een list-item een ongewenste underline.

![Schermafbeelding 2021-01-04 om 15 52 57](https://user-images.githubusercontent.com/598735/103547621-f069ca00-4ea4-11eb-8279-937679e08b8f.png)

**Comment by PieterVerheij** [comment]
@bramhoosemans de meeste issues in de knop zelf waren te herleiden naar het ontbreken van de `<span>` in de button: scherp gezien!

Ik heb wel 1 vraag, welk icoon moet er dan tonen (ik had de chevron-down gebruikt)?
"Bij de default button wordt een niet ondersteund icoon gebruikt (volgens mij nog een oude implementatie svg iconen)."

**Comment by PieterVerheij** [comment]
Voor de issues met de default button is een apart issue aangemaakt: #957
Bij de default button wordt een niet ondersteund icoon gebruikt (volgens mij nog een oude implementatie svg iconen).
De focus state van de default button bevat een ongewenste underline.
