### ISSUE TITLE
Consequente styling van anchor links in lopende tekst

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#895]
Tekstlinks worden momenteel verschillend gestyled. 

1. Binnen `.dso-rich-content` krijgen links default een underline die soms verdwijnt op hover.
2. Daarbuiten krijgen link default geen underline en verschijnt die juist op hover.

Volgens mij is het wenselijk om de styling binnen `.dso-rich-content` overal door te voeren. Dus tekstlinks krijgen default een zichtbare underline. Zo zijn ze ook in lopende tekst niet alleen aan de kleur te herkennen.

![Schermafbeelding 2020-11-23 om 15 41 01](https://user-images.githubusercontent.com/598735/99975746-e97a7280-2da2-11eb-8b20-ccb2ed369a9f.png)
![Schermafbeelding 2020-11-23 om 15 40 55](https://user-images.githubusercontent.com/598735/99975764-eda69000-2da2-11eb-828a-c4f313f8fa55.png)

**Comment by daverhelst** [comment]
@bramhoosemans Ik heb de algemene anchor styling aangepast en percy heeft zijn rondje gedraaid in het pull-request. Nu kunnen we gericht de styling gaan aanpassen. Kun jij een overzicht/lijst maken van de anchor die _geen_ underline in de basis moeten hebben?

**Comment by bramhoosemans** [comment]
@daverhelst Componenten waar _geen underline_ wenselijk is:
* Accordion
* Anchor (als een link visueel als button getoond wordt dient deze de button styling te volgen.)
* Breadcrumbs
* Dropdown button
* Navigations
* Tabs
* Whitebox
* Footnotes
* Footer

Overige opmerkingen:
* In het voorbeeld ‘links’ staat een ‘example-big-font’. Is dit iets wat we impliciet ondersteunen vanuit Bootstrap?
* De footer is niet als component in de toolkit beschikbaar, terwijl deze wel specifieke styling krijgt. Nieuw issue aanmaken?
* In de Highlightbox met witte achtergrond kan de tertiaire button zijn originele styling behouden. Issue aangemaakt https://github.com/dso-toolkit/dso-toolkit/issues/925

**Comment by daverhelst** [comment]
Over de opmerkingen:

- Nee, 'example-big-font' is iets vanuit de toolkit zelf.
- Nieuw footer issue? Lijkt me een puik plan!

**Comment by daverhelst** [comment]
@bramhoosemans Inmiddels heb ik de aanpassingen doorgevoerd. Kun je controleren of het zo naar wens is?

**Comment by bramhoosemans** [comment]
Hi @daverhelst, volgens mij gaat het op een aantal plekken nog niet zoals gewenst:

- Als een link visueel als button wordt getoond dient deze de button styling te volgen (zonder underline).
- In de highlightbox staan bijvoorbeeld links die gestyled worden als buttons.
- Navigations > secondary navigation
- Accordion > compact

> Over de opmerkingen:
> 
> * Nee, 'example-big-font' is iets vanuit de toolkit zelf.

Dit is volgens mij de eerste keer dat ik hem zie.. hij staat ook niet vermeld bij de Typografie. Ben je hem ergens anders tegengekomen?

> * Nieuw footer issue? Lijkt me een puik plan!

Oké, dan zal ik die aanmaken.

**Comment by bramhoosemans** [comment]
'example-big-font' wordt gebruikt als voorbeeldstyling in de DSO Toolkit zelf. In de nieuwe opzet zal deze specifieke styling ook niet meer meegeleverd worden in de package naar de teams.

Footer issue is reeds aangemaakt > https://github.com/dso-toolkit/dso-toolkit/issues/936.

**Comment by daverhelst** [comment]
@bramhoosemans inmiddels heb ik de laatste wijzigingen gepushed, en heb het vermoeden dat we nu wel zijn waar we willen zijn

**Comment by bramhoosemans** [comment]
@daverhelst ziet er goed uit. Het vreemde is dat Percy aangeeft dat ook de 'Progress Indicator' gewijzigd is, maar die zie ik niet.

**Comment by gofix** [comment]
@daverhelst https://codepen.io/gofix/full/zYKjdvy -> daar heb ik een `a` gewoon scope-loos geplaatst, en deze heeft GEEN underline, maar krijgt m alleen bij hover. Als ik het ticket goed lees wat dat juist NIET de bedoeling toch? Ik dacht dat het idee was dat de default-der-defaults zou zijn dat links een underline hebben, en bij hover NIET.

Nu is deze formulering ook wel wat onduidelijk:
> Volgens mij is het wenselijk om de styling binnen `.dso-rich-content` overal door te voeren.
Want: de styling binnen `.dso-rich-content` is en was juist andersom.

@bramhoosemans kun jij uitsluitsel geven over wat de default-der-defaults zou moeten zijn? Dan kan @daverhelst daarna de 'andersom' uitzonderingen langslopen.

**Comment by bramhoosemans** [comment]
@gofix De default-der-defaults van een tekstlink moet juist een underline krijgen. Zo is deze beter te onderscheiden in lopende tekst.

De underline hoeft trouwens NIET te verdwijnen op hover. Ik zag dat dit ook niet consistent is in Rich Content; zie externe link én links in de tabel. https://dso-toolkit.nl/16.0.1/components/detail/rich-content.html

In het ontwerp heb ik het lang geleden zo uitgewerkt:
![Schermafbeelding 2021-01-05 om 11 18 44](https://user-images.githubusercontent.com/598735/103635214-7e4ac100-4f48-11eb-8617-b84a73214bbc.png)

**Comment by gofix** [comment]
Well, @daverhelst -> there you have it.

**Comment by daverhelst** [comment]
In de loop van het traject is er iets teruggedraaid, of niet goed overgezet. De changes van de allereerste push: https://github.com/dso-toolkit/dso-toolkit/commit/9a3eff0356b9c3dea6824659a18daca1d46627ef, zaten niet meer in het eindresultaat.

Ik heb deze changes opnieuw toegevoegd, waardoor anchors weer een underline krijgen (behalve waar niet wenselijk)

**Comment by gofix** [comment]
🎶That's what code reviews are for.🎵
Op de muziek van Dionne Warwick - That's What Friends Are For (https://www.youtube.com/watch?v=HyTpu6BmE88)

**Comment by daverhelst** [comment]
@bramhoosemans over het plaatje wat je in je laatste comment hebt gezet. Is dit _echt_ wat jullie willen? Geen visueel onderscheidt (behalve kleur) tussen default en hover state?

Als het antwoord ja is, bij sommige elementen (bijvoorbeeld accordion) werkt het juist andersom, klopt het dat je daar de active state dan _wel_ underlined wilt hebben, of geldt voor deze uitzonderingen juist dat er nooit een underline moet komen?

**Comment by bramhoosemans** [comment]
@daverhelst Ja, samen met de veranderende cursor is dit voldoende indicatie voor de gebruiker.

De scope is echter alléén de default tekstlink; het kan zijn dat tekstlinks binnen componenten anders worden gestyled. Denk bijvoorbeeld aan tekstlinks in Alerts of Highlightbox met grijze achtergrond. Hier is vanwege contrast eisen een alternatieve styling toegepast.

**Comment by tfrijsewijk** [comment]
> In het ontwerp heb ik het lang geleden zo uitgewerkt:
> ![Schermafbeelding 2021-01-05 om 11 18 44](https://user-images.githubusercontent.com/598735/103635214-7e4ac100-4f48-11eb-8617-b84a73214bbc.png)

Over die opmerking rechts: Op dit moment is daar geen voorziening voor. Zodra de browser een link als visited markeert krijgt deze de kleur. Wil je daar sturing op uitoefenen kunnen we een modifier class aanbieden die de visited styling voorkomt. Het is aan de implementator van de toolkit deze op de juiste momenten in te zetten.

**Comment by bramhoosemans** [comment]
@tfrijsewijk Klopt. Ik heb bij de componenten in Sketch korte instructies toegevoegd voor collega-ontwerpers. In dit geval misschien een beetje voorbarig, want het is nog niet als issue gesignaleerd.

**Comment by gofix** [comment]
@bramhoosemans de laatste vraag van @daverhelst gaat over de `:active` van links. Inderdaad: in tekstlinks wil je dat daar de underline verdwijnt. Dat hebben we ook zo gerealiseerd nu. In veel andere werkvormen is het underlinen 'tegengegaan', maar we vragen ons daar nu voor af wat je daarin met de `:active` wilt -> geldt daarvoor dan ook als stelregel dat het 'andersom' moet? Dus: dat als in een werkvorm de link NIET underlined is, dat ie dat met `:active` WEL moet krijgen?

**Comment by bramhoosemans** [comment]
@gofix Ik kan zo snel niet overzien welke werkvormen er allemaal links gebruiken. Dat maakt het lastig om een algemene stelregel te bepalen.

Dat gezegd hebbende lijkt me een dat de :active state altijd 'andersom' moet een mooi uitgangspunt.

**Comment by daverhelst** [comment]
Duidelijk, voor nu heb ik de basis van de anchors op underlined gezet, met alleen de :active state op niet underlined, zoals hierboven beschreven.

Voor de overige uitzonderingen heb ik ze ingesteld zoals ze waren. Als voorbeeld, een accordion met compacte links, krijgt dus op hover _wel_ een underline.

Wil je nog een keer een blik werpen op de uitzonderingen @bramhoosemans of kloppen de aanpassingen die we in het voorgaande jaar hebben gedaan nog steeds? (https://dso-toolkit.nl/_895.Anchor-tekst-links-styling/components/detail/accordion.html)

**Comment by gofix** [comment]
Bij de externe link verdwijnt de underline bij hover, in het rich content voorbeeld:
![Uploading image.png…]()

**Comment by gofix** [comment]
Ineens begin ik aan alles te twijfelen. Zou de knop van https://dso-toolkit.nl/_895.Anchor-tekst-links-styling/components/detail/dropdown-button.html op bij hover niet eigenlijk ook een underline moeten krijgen?

![image](https://user-images.githubusercontent.com/2689559/103873034-7ff2c100-50cf-11eb-90b3-6e3acbce3458.png)

**Comment by gofix** [comment]
Enne.. is eigenlijk in de footer dat scampi als visited wel gewenst?
![image](https://user-images.githubusercontent.com/2689559/103875171-643cea00-50d2-11eb-883c-df6c482120b2.png)

In highlight box is er expliciet aandacht aan besteed, maar eigenlijk zou dat op alle grijsjes (en geel...) moeten zijn toch?
