### ISSUE TITLE
Fieldset legends in wizard accordion worden niet gestyled.

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#896]
Het lijkt erop dat als er wél fieldsets in de accordion worden geplaatst deze niet de juiste legend styling meekrijgen.

Markup: [temp.html.zip](https://github.com/dso-toolkit/dso-toolkit/files/5584063/temp.html.zip)

<img width="1153" alt="Screenshot 2020-11-23 at 16 32 12" src="https://user-images.githubusercontent.com/598735/99982387-c5bb2a80-2daa-11eb-9bbd-8938fadbe798.png">

**Comment by PieterVerheij** [comment]
My gut feeling zegt dat er iets zit tussen de `.dso-section-body` en `fieldset` waardoor de styling omvalt.

![image](https://user-images.githubusercontent.com/25430835/100094920-08880b80-2e5a-11eb-9b09-176a765eaa82.png)

**Comment by bramhoosemans** [comment]
> My gut feeling zegt dat er iets zit tussen de `.dso-section-body` en `fieldset` waardoor de styling omvalt.

Check ook de 'temp.html.zip' in de eerste comment!

**Comment by PieterVerheij** [comment]
@bramhoosemans thanks!

En idd:

![image](https://user-images.githubusercontent.com/25430835/100098707-b7c6e180-2e5e-11eb-933f-2b479c166500.png)

**Comment by gofix** [comment]
Volgens mij zijn de changes in orde. Maak je nog even een changelog regel @PieterVerheij ?

**Comment by PieterVerheij** [comment]
Fixed
