### ISSUE TITLE
Uitlijning/marge formgroups bij indienen

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#897]
Zoals @PieterVerheij ook al constateerde in https://github.com/dso-toolkit/dso-toolkit/issues/826 hebben de marges in het formulier nog wat aandacht nodig.

Probleem: "de 2x div.form-group, dat is in onze markup niet gewijzigd en staat nu ineens te ver naar links. Als ik de form-group er af haal, staan ze op de goede plek (horizontaal dan), maar is de 32x marge tussen het vinkje en de downloadknop weg."

<img width="1208" alt="Screenshot 2020-11-23 at 16 54 43" src="https://user-images.githubusercontent.com/598735/100065345-f7c49f00-2e33-11eb-9b1d-754d84bba514.png">
<img width="1892" alt="Screenshot 2020-11-23 at 16 57 53" src="https://user-images.githubusercontent.com/598735/100065362-fabf8f80-2e33-11eb-9e97-8fef56e3541e.png">

**Comment by PieterVerheij** [comment]
Situatie nagebouwd:

https://codepen.io/pieterverheij/pen/WNGevve

**Comment by PieterVerheij** [comment]
@bramhoosemans @gofix 
Zie https://codepen.io/pieterverheij/pen/WNGevve

Conclusie;
Elk los staand "eiland" (in dit geval 3: 1. het accordion, 2. de checkbox en downloadbutton, 3. verzenden-knop) moet in een eigen `row` met `col`. Eigenlijk zoals het in https://www.dso-toolkit.nl/master/components/detail/aanvragen.html ook geimplementeerd is.

**Comment by gofix** [comment]
Ik denk inderdaad dat de laatste conclusie de meest juiste is: net als in 'aanvragen' moet bij het opbouwen van een pagina als deze echt gedacht worden in 'stroken', en iedere strook is dan een `row` met `col`. Over dso-confirm (https://dso-toolkit.nl/14.0.0/components/detail/group-confirm.html) -> strikt genomen lijkt dat de voor de hand liggende werkvorm, alleen is die eigenlijk echt bedoeld om samen met een 'echt' formulier gebruikt te worden (dus, bv. als laatste van een aantal andere velden). Als deze zo los opgenomen zou worden ziet het er echt niet uit.

**Comment by gofix** [comment]
Overigens, zoals onlangs uitgevogeld, kunnen in 1 formulier prima `.form-horizontal` en NIET-form-horizontal gecombineerd worden (zo lang je maar niet IN een `.form-horizontal` weer van dat horizontale af wilt, want dat gaat niet). Als we dus in genoemd voorbeeld de buitenste form NIET `.form-horizontal` geven, maar dit bv. alleen op de zichtbare accordion-stap toepassen, kan wel de checkbox met dso-confirm gemaakt worden. Misschien is dat toch wel het fraaiste.

**Comment by gofix** [comment]
@bramhoosemans kun je vooruit met bovenstaande? Het lijkt er namelijk op dat hiervoor geen toolkit changes nodig zijn. Eventueel kunnen we nog een uitwerking maken van hoe dso-confirm in dit voorbeeld gebruikt zou kunnen worden? Verder: is het wenselijk dat we een voorbeeld als dit ook nog opnemen in de Toolkit? Zeker nu er flink gefinetuned wordt aan stijlregels rondom bv. fieldsets etc. is het wel zo veilig om juist ook de minder triviale combinaties te borgen (zodat bij CSS wijzigingen Percy ons op eventueel onverwachte bij-effecten kan wijzen).

**Comment by bramhoosemans** [comment]
@gofix Ja, ik denk het wel.

Over de vraag of het wenselijk is om dit scherm ook als voorbeeld op te nemen in de toolkit; dat kan uiteraard. Al denk ik dat we beter eerst een plan kunnen maken welke layouts we moeten opnemen. De gehele applicatie(s) overnemen als voorbeeldschermen lijkt me niet wenselijk.

**Comment by gofix** [comment]
Inderdaad wordt het tijd om nog eens goed na te denken over de indeling van die sectie. Soms is er behoefte aan vastlegging van voorbeeld-snippets, naast compleet uitgewerkte pagina's. Maar: daarvoor is dan wel een herindeling wenselijk, want nu al is het soms bijzonder moeilijk de juiste voorbeelden te vinden.

**Comment by gofix** [comment]
Ik heb de pen van @PieterVerheij even geforked om de CSS verwijzing naar /master/ te leggen: https://codepen.io/gofix/pen/LYRYGQZ
