### ISSUE TITLE
Button Text wordt dubbel voorgelezen

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#903]
In https://github.com/dso-toolkit/dso-toolkit/issues/813 hebben we een fix uitgebracht, alleen is er niks gefixt... de toevoeging "toelichting bij vraag" wordt nu dubbel gelezen. Het team heeft besloten deze extra complexiteit nu niet toe te voegen.

![Schermafbeelding 2020-11-23 om 15 30 14](https://user-images.githubusercontent.com/598735/100231026-bcef6380-2f26-11eb-9c28-6c047a5ca5ae.png)

**Comment by MichielDHVD** [comment]
Best practice voorbeeld maken dat door Tim in't Veld wordt getest

**Comment by PieterVerheij** [comment]
@timveld 
Ik heb een POCje gemaakt. Onderaan deze pagina staat een formulier variant "FORM TOELICHTING": https://www.dso-toolkit.nl/_903.Vervolg-Toelichting-wordt-dubbel-voorgelezen/components/preview/form.html

Zou jij deze eens willen checken, en dan vooral letten op het dubbel voorlezen zoals hierboven gemeld?

**Comment by timveld** [comment]
* Toelichtingsknopjes  en de toelichting zelf  staan binnen de legend. Dat betekent dat ze worden voorgelezen samen met de legend. In de legend moet in principe alleen de vraag zelf staan.
* Het knopje "sluiten" bij de toelichtingen zou hier beter "toelichting sluiten"genoemd kunnen worden en in de flow na de tekst van de toelichting kunnen komen. 
* Ik heb wat andere problemen mar zie nog veel validatiefouten, kun je die oplossen? Dan weten we in ieder geval dat deze problemen daar niet door veroorzaakt worden.

**Comment by PieterVerheij** [comment]
![image](https://user-images.githubusercontent.com/25430835/105512440-648fd480-5cd1-11eb-97f0-dd6124e37b45.png)
De toelichting moet in de markup ONDER de legend komen.

**Comment by daverhelst** [comment]
Bovenstaande oplossing van @PieterVerheij gaat hem niet worden, althans het lijkt me wel een aardig uitgangspunt. @timveld wil zowel de toelichtings knop als de toelichting zelf uit de `legend` tillen. Op dit moment stylen we de `legend` op een 50% breedte, en zit er ook styling op `.control-label + button`.

Om dit visueel hetzelfde te krijgen zullen we een _container_ div om de `legend`, toelichtings knop en toelichting zelf moeten zetten, om daar dan de 50% width styling op te kunnen zetten. Maar _mag_ je een tussenlaag hebben tussen een `fieldset` en een `legend` of moet de `legend` _altijd direct_ onder een fieldset staan? @gofix @PieterVerheij ?

**Comment by PieterVerheij** [comment]
Ik zou eerst checken of het plaatsen de button in de legend echt een probleem is. Markup technisch mag het namelijk wel, dus het probleem zit hem evt. alleen in hoe een screen reader ermee omgaat.

**Comment by daverhelst** [comment]
@timveld @bramhoosemans Ik heb de markup aangepast zodat de button geen eigenlijke tekst meer bevat, maar die via een aria-label gezet wordt. Ik hoor daarin geen verschil met NVDA. Willen we nog iets anders proberen, of laten zoals het is?

**Comment by bramhoosemans** [comment]
@daverhelst Wat mij betreft laten we het zoals het is. Het is absoluut geen blokkerend probleem, en er is al veel tijd gestoken in mogelijke oplossingsrichtingen.

**Comment by daverhelst** [comment]
@bramhoosemans Dan kan dit issue op een soort 'won't do' lijkt me.

**Comment by timveld** [comment]
Ik ben de draad een beetje kwijt maar pagina https://www.dso-toolkit.nl/_903.Vervolg-Toelichting-wordt-dubbel-voorgelezen/components/preview/form.html  is met NVDA heel erg rommelig, er gaat van alles mis. Hij geeft veel validatiefouten in de w3c validator die waarschijnlijk veel van het niet / dubbel voorlezen verklaren, misschien is het goed om de pagina eerst min of meer valide te maken voordat we verder gaan want zoals het nu is kan ik er weinig zinvolle uitspraken over doen. Of is dit niet meer de meest actuele voorbeeldpagina?

**Comment by daverhelst** [comment]
@timveld dat is een lastige vraag waar op dit moment moeizaam op te antwoorden is. Bij de oplossing gemaakt in #996 valt het mij echter wel op dat het oorspronkelijke probleem van dit issue hiermee opgelost is. Ik stel voor om dit ticket even te parkeren tot #996 door is, en vervolgens kunnen we kijken of de form.html pagina nog wel toereikend genoeg is qua markup.

**Comment by gofix** [comment]
Inderdaad @daverhelst dit issue lijkt opgelost te zijn met #996. Als zodanig in de changelog.md verwerkt:
https://github.com/dso-toolkit/dso-toolkit/commit/377ed08a75529b5429b3e7b89e710f3610c5560b

**Comment by timveld** [comment]
net met @daverhelst  gecontroleerd en de fix lijkt goed te zijn.
