### ISSUE TITLE
Toelichting direct onder/na de vraag

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#906]
Op dit moment staat de toelichting op de vraag onder de antwoorden. Deze afstand levert zowel visueel als voor een screenreader problemen op. De wens is om de volgorde in markup en positionering aan te passen naar: vraag > toelichting bij vraag > antwoord > toelichting bij antwoord > antwoord > etc.

![104_vernieuwde-toelichtingen-wizard-met-toelichting](https://user-images.githubusercontent.com/598735/100359744-458a0480-2ff8-11eb-805d-985479f95ec2.png)

**Comment by daverhelst** [comment]
@bramhoosemans nog even ter opheldering, we gaan in dit issue de toelichting toevoegen _onder_ de vraag, maar laten de huidige foutieve ook nog staan, maar met deprecated styling?

**Comment by bramhoosemans** [comment]
> @bramhoosemans nog even ter opheldering, we gaan in dit issue de toelichting toevoegen _onder_ de vraag, maar laten de huidige foutieve ook nog staan, maar met deprecated styling?

In dit issue blijft de huidige (foutieve) nog bestaan, zonder deprecated styling. In https://github.com/dso-toolkit/dso-toolkit/issues/920 gaan we deze werkwijze deprecaten.

**Comment by daverhelst** [comment]
En dit geldt alleen voor vragen in `form-horizontal`?

**Comment by bramhoosemans** [comment]
Nee, de toelichting moet ook in verticale formulieren direct onder de vraag staan. Issue titel gelijk bijgewerkt. Hieronder een voorbeeld wat ik snel kon vinden met vaste toelichtingen (https://github.com/dso-toolkit/dso-toolkit/issues/907).

Excuses voor de onduidelijke story..

![Schermafbeelding 2020-12-08 om 08 44 19](https://user-images.githubusercontent.com/598735/101454643-991e1b80-3931-11eb-9be2-2cd69c1557fd.png)

**Comment by daverhelst** [comment]
@bramhoosemans Ik heb het een en ander gepushed; https://dso-toolkit.nl/_906.Toelichting-direct-onder-na-de-vraag/

Kun je controleren of dit naar wens is?

**Comment by bramhoosemans** [comment]
@daverhelst Het is even zoeken, maar volgens mij zitten beide vormen nu in https://dso-toolkit.nl/_906.Toelichting-direct-onder-na-de-vraag/components/detail/form.html

Voor wat ik kan zien ziet het er goed uit.

**Comment by gofix** [comment]
Dit voorbeeld bestaat alleen om duidelijk te maken dat je dit eigenlijk echt niet zou moeten willen?

![image](https://user-images.githubusercontent.com/2689559/103868124-c133a280-50c8-11eb-82d7-b97130ad5ec4.png)

Immers, het KAN natuurlijk wel, dat zowel de vraag als het antwoord een toelichting heeft...

**Comment by gofix** [comment]
Dit dan:
![image](https://user-images.githubusercontent.com/2689559/103868290-0061f380-50c9-11eb-9f69-fe952e3ee7af.png)
Zou je niet eigenlijk ook in deze voorbeelden niet al in de tekstjes willen zijn wat nu eigenlijk waar een toelichting bij is? Dus iets als "Toelichting bij vraag", "Toelichting bij antwoord 1", "Toelichting bij antwoord 2"? Of zit ik nu te zeiken...?

**Comment by gofix** [comment]
@bramhoosemans, @daverhelst ?

**Comment by bramhoosemans** [comment]
@gofix Goed dat je het aangeeft!

Ondanks dat de toelichting nog onder de antwoorden KAN verschijnen lijkt me het niet wenselijk deze als voorbeeld op te nemen in de DSO Toolkit. Daarnaast komen toelichtingen bij zowel vraag als antwoord geregeld voor in de 'echte' content. Deze 'voorbeeld toelichting' is sterk verouderd en zal gewijzigd moeten worden.

We zullen eens kritisch moeten kijken naar de inhoud van het `form` component, want eerlijk gezegd vind ik deze erg onoverzichtelijk met alle voorbeelden.

**Comment by bramhoosemans** [comment]
@daverhelst alleen teksten in toelichting beschrijvend maken, zoals "toelichting bij vraag"
