### ISSUE TITLE
Info-component zonder sluitmogelijkheid

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#907]
In de toepassing is het voor de redacteur mogelijk om een 'vaste' toelichting mee te geven aan een vraag en/of antwoord. Deze toelichtingen kunnen **niet** gesloten worden. Hier is destijds bewust voor gekozen.

Deze vorm kan ik niet terugvinden in de toolkit. In de praktijk wordt hier het 'info' component voor gebruikt zónder sluit button.

![Schermafbeelding 2020-11-26 om 15 10 14](https://user-images.githubusercontent.com/598735/100360670-81719980-2ff9-11eb-9386-1850114081b9.png)

![106_vernieuwde-toelichtingen-wizard-met-toelichting-vast](https://user-images.githubusercontent.com/598735/100360113-cea13b80-2ff8-11eb-88f9-cc0530b912d0.png)

**Comment by PieterVerheij** [comment]
@bramhoosemans Laat ik daar nou ook laatst naar hebben zoeken, is het dit niet? https://www.dso-toolkit.nl/master/components/detail/highlight-box.html

**Comment by bramhoosemans** [comment]
> @bramhoosemans Laat ik daar nou ook laatst naar hebben zoeken, is het dit niet? https://www.dso-toolkit.nl/master/components/detail/highlight-box.html

Lijkt er wel veel op. Zouden we dan het 'info' component moeten gebruiken als de toelichting veborgen kan worden. En de 'highlightbox' op het moment dat hij vast op de pagina staat?

Je zou bijna denken dat we de 'highlightbox' en 'info' component samen kunnen voegen..

**Comment by MichielDHVD** [comment]
Er moet een variatie komen van het info component zonder het sluiten kruisje
