### ISSUE TITLE
Pager deprecaten

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#910]
In de styling maken we een pager component, gebaseerd op Bootstrap: `.pager`. Maar we bieden nergens een implementatie aan.

Gebruikt iemand dit component? Of zullen we 'm deprecaten?

De laatste versie waar dit component nog wordt getoond is https://dso-toolkit.nl/10.3.1/components/detail/pager.html

De changelog van 10.4.0 rept niets over Pager, maar wel "Toolkit structuur platslaan (#604)", maar in dat issue wordt ook niets over de pager gezegd.

**Comment by gofix** [comment]
Ik heb nog:
- de changelog message gewijzigd;
- de kleur van de deprecation stijl gelijkgetrokken aan hoe we dat eerder deden;
- de PR van een depration notice voorzien;
