### ISSUE TITLE
Forms: voorbeelden kloppen niet

### ISSUE THREAD

**Issue by timveld** [dso-toolkit/dso-toolkit#912]
Ik probeer de WCAG checklist op te stellen voor de [concept documentatie forms](https://jira.team-dso.nl/confluence/display/DSOUX/Form?focusedTaskId=3)
Ik heb een paar vragen, donderdag bespreken? 
* Er wordt een en ander gezegd over het markeren van fouten maar volgens mij overlapt dat met het alert beleid (wat zetten we waar)
* Er wordt gesproken over het onderverdelen van formulieren in groepen, correct. Maar daarbij wordt nog niet benoemd dat je dat met een fieldset doet en we kunnen misschien iets duidelijkere richtlijnen / voorbeelden geven voor 
* Moeten we nog wat meer zeggen over visuele layout en responsive design in het kader van toegankelijkheid?
* Moeten we richtlijnen over welk component waar (bijv keuzelijst vs keuzerondjes)?

**Comment by timveld** [comment]
Met @Anto1nette en @MichielDHVD  besproken, volgende conclusies:   
* Ik schiet dit soort documentatiepunten niet meer in eerste instantie in via github maar via UX overleg / confluence
*We herhalen het verhaal over het aangeven van validatiefouten maar verwijzen met een voetnoot naar het alert beleid
* Over visuele layout kunnen we nog geen richtlijnen geven
* Ik schrijf een stukje over fieldsets en hulptechnologie (belang, hoe gaan ze er mee om)
* Ik voeg een kleine opmerking toe over de form tag / screen readers (werk ik zelf uit)

**Comment by timveld** [comment]
Bij het schrijven van de documentatie blijkt het niet nodig wat over de form tag te zeggen maar heb ik wel ontdekt dat de voorbeelden bij form het gebruik van de fieldset niet goed illustreren. ZO staat in het eerste voorbeeld o.m. het wachtwoord binnen een fieldset genaamd contact. Ter inspiratie de concept documentatie die ik @Anto1nette heb gestuurd:

Voor gebruikers van hulptechnologie is het in bepaalde situaties belangrijk om elementen te groeperen in fieldsets met een legend (omschrijving). Deze legend wordt voorgelezen zodra een veld in de fieldset focus krijgt. Daarom is het belangrijk de legend zo kort mogelijk te houden.

In sommige gevallen is een fieldset altijd nodig, zie bijvoorbeeld group radiso en group checkboxes. Andere voorbeelden waar velden met een fieldset gebroepeerd moeten worden:

* Een fieldset met legend "verzendadres" bevat tekstvelden "straat", "huisnummer", "postcode" en "plaats".

* Een fieldset met legend "gegevens aanvrager" bevat tekstvakken "naam" en "bsn", group radios voor geslacht met opties "man" en "vrouw" en een datumveld voor de geboortedatum.

* Een fieldset met legend "gegevens auto" bevat keuzelijsten voor merk en type, invoervelden voor kenteken en bouwjaar en een group radios brandstof met types benzine of disel.

**Comment by bramhoosemans** [comment]
Dit issue gesloten; we nemen de juiste opbouw van fieldsets mee in de nieuwe opzet van de pagina.
