### ISSUE TITLE
Web Component: Card

### ISSUE THREAD

**Issue by tfrijsewijk** [dso-toolkit/dso-toolkit#921]
## `.dso-card`

Component:
* `packages\dso-toolkit\components\Componenten\_card\card.njk`
* `packages\dso-toolkit\components\Componenten\_card\card.config.yml`
* `packages\dso-toolkit\src\styles\components\_card.scss`

Dit component wordt omgezet naar 4 Web Components:
* `dso-cards`
* `dso-card`
* `dso-card-interactions`
* `dso-card-interaction`

Nunjucks implementatie in `card.njk`:
```html
<dso-card>
  <a href="#">
    <div class="dso-rich-content">
      <h2>{{ label }}</h2>
      <p>{{ content | safe }}</p>
    </div>
  </a>
  {% if interactions %}
    <dso-card-interactions name="interactions">
      {% for interaction in interactions %}
        <dso-card-interaction>
          {% if interaction.toggle %}
            <label slot="label">
              <input type="checkbox" name="{{ interaction.toggle.id }}" />
              <span class="sr-only">{{ label }}</span>
            </label>
          {% endif %}
          {% if interaction.button %}
            <template slot="button">
              {% render '@button', interaction.button -%}
            </template>
          {% endif %}
        </dso-card-interaction>
      {% endfor %}
    </dso-card-interactions>
  {% endif %}
</dso-card>
```

* Checken of `<template slot="..">` werkt

Op de volgende plekken wordt het card component gebruikt:
* `packages\dso-toolkit\components\Componenten\cards\cards.njk`
* `\packages\dso-toolkit\components\Voorbeelden\Zoeken-in-lijst-cards.njk`

Daarnaast:
* We ontmantelen het verschil tussen het verborgen component `card` en `cards`: Er is straks nog maar één zichtbaar nunjucks component voor card. In dit component wordt `<dso-cards>` opgebouwd.
* `packages\dso-toolkit\components\Componenten\cards\_preview.njk` gaat weg

**Comment by PieterVerheij** [comment]
Scoping van de css is nogal een dingetje: gedrag van `.dso-card-interactions` kan bv. afhangen van een class op `.dso-cards`.

**Comment by hansgrimm** [comment]
Is dit nog courant?

**Comment by hansgrimm** [comment]
gerealiseerd in #1800
