### ISSUE TITLE
Tertiaire button grasgroen in Highlightbox met witte achtergrond

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#925]
In de Highlightbox `dso-border` en `dso-white dso-drop-shadow` moet de tertiaire button de originele styling behouden. Deze wordt op dit moment zwart gemaakt, maar dit is enkel nodig voor grijze en gele achtergrond.

**Comment by PieterVerheij** [comment]
@bramhoosemans moet het echt zwart, of grijs-90 (`#191919`) zijn?

**Comment by bramhoosemans** [comment]
> @bramhoosemans moet het echt zwart, of grijs-90 (`#191919`) zijn?

Zwart is in de huisstijl van het DSO inderdaad 90%, dus #191919.

**Comment by PieterVerheij** [comment]
`#191919` en `#39870c` it is! 
https://www.dso-toolkit.nl/_925.Tertiaire-button-grasgroen-in-Highlightbox-met-witte-achtergrond/components/detail/highlight-box.html

**Comment by bramhoosemans** [comment]
Ziet er goed uit 👍

**Comment by gofix** [comment]
@PieterVerheij ik heb nog even de changelog regel gewijzigd naar hoe we dat tegenwoordig doen (dus, inclusief indicatie voor welke package de change geldt, en het linkend maken van de issue referentie).
