### ISSUE TITLE
Group Input met icoon heeft een verwijzing naar niet bestaand icoon

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#927]
![Schermafbeelding 2020-12-04 om 16 17 12](https://user-images.githubusercontent.com/598735/101180690-2caece00-364c-11eb-9298-4e7a02833e0a.png)

**Comment by bramhoosemans** [comment]
Is reeds opgelost. Nagaan in welke release dit was.

**Comment by gofix** [comment]
Dit is opgelost met het verschijnen van release **17.1.0**, vergelijk:
- https://dso-toolkit.nl/17.1.0/components/detail/group-input.html
- https://dso-toolkit.nl/17.0.1/components/detail/group-input.html

Zoals overlegd gaan we niet after-the-fact dit in de changelog registreren.
