### ISSUE TITLE
"Grote" whitebox aanpassingen, en gelijktrekken box-shadow met highlight box

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#929]
Er zijn onderdelen van de "grote" whitebox die nog niet helemaal optimaal renderen. 

- De Titel tekst moet gecentreerd worden
- Er is geen bottom padding/margin waardoor op bepaalde breakpoints waardoor de tekst heel strak op de rand aansluit. Te zien op 1024px en 320px. Het liefst is er op zijn minst een adem ruimte van 16px.
De actieve whitebox implementatie op de pre omgeving heeft een padding van 24px aan de zijkanten en 16px boven onder.  Dat oogt fijn. 

<img width="931" alt="Screenshot 2020-12-07 at 14 42 58" src="https://user-images.githubusercontent.com/36912722/101357986-87d60000-389a-11eb-9402-6f1c57a0b0e6.png">

**Comment by PieterVerheij** [comment]
@MichielDHVD @bramhoosemans Is het een goed idee om bij de whitebox gelijk ook iets aan de dropshadow te doen, zodat er aan de bovenzijde ook een afkadering is?

![image](https://user-images.githubusercontent.com/25430835/102371700-c2d4e380-3fbe-11eb-8fa0-5365be4d2bd7.png)

**Comment by bramhoosemans** [comment]
> @MichielDHVD @bramhoosemans Is het een goed idee om bij de whitebox gelijk ook iets aan de dropshadow te doen, zodat er aan de bovenzijde ook een afkadering is op een witte achtergrond? Als je met je neus er dicht op zit, zie je nu nog net een lichtgrijs lijntje...

Ja, goed plan. Het voorbeeld wat je geeft is trouwens in de toepassing een Highlightbox met `dso-has-counter`. De dropshadow is bij beide componenten gelijk en kan gelijk getrokken worden met eerder ontwerp.

Huidige dropshadow:
`box-shadow: 0 6px 8px 0 rgba(0,0,0,.1), 0 6px 8px 0 rgba(0,0,0,.1);`

Gewenste dropshadow (zoals ontwerp):
`box-shadow: 0 4px 8px 0 rgba(0,0,0,.2)`

**Comment by PieterVerheij** [comment]
@MichielDHVD  Soms is er teveel witruimte aan de onderkant. Dit wordt veroorzaakt doordat er een `min-height` op de whiteboxes (small en regular) staat. Als we die `min-height` weghalen en we willen wel dat whiteboxes even hoog zijn, dan betekent dat automatisch dat een implementator verplicht is om equal -heights te gebruiken (https://www.dso-toolkit.nl/16.0.0/components/detail/row-equal-heights.html). Dat impliceert dan wel een breaking change.

**Comment by MichielDHVD** [comment]
Dat is voor mij prima, op dit moment is alleen pr 02 de enigste die whiteboxes gebruikt. En ik heb de stories ervoor al klaar staan.

**Comment by MichielDHVD** [comment]
Dropshadow voor highlightbox en whitebox.
