### ISSUE TITLE
Web Component: Logo

### ISSUE THREAD

**Issue by PieterVerheij** [dso-toolkit/dso-toolkit#931]
`<dso-logo>`

**Comment by tfrijsewijk** [comment]
@bramhoosemans We hebben wel eens gefilosofeerd over een Web Component wat logo's kan ""genereren"", hoe staan we hier nu in?

Ik vraag mij af in hoeverre het Logo een component is. Er bestaat een `logo` class, maar zonder de context van van `header` doet ie niets.

Als we voor nu geen slim Web Component gaan maken stel ik voor dat we alleen de documentatie (https://dso-toolkit.nl/24.2.2/docs/fundament/logo.html) en het logo alleen als onderdeel van het header component meenemen.

**Comment by bramhoosemans** [comment]
@tfrijsewijk Klopt. Zojuist ook even met @MichielDHVD afgestemd, want hij is met de header bezig.

Op dit moment zou ik geen tijd steken in een "slim" web component voor het logo. Het is prima dat er documentatie beschikbaar is en het logo alleen in het component header wordt opgenomen.

**Comment by tfrijsewijk** [comment]
Prima!
