### ISSUE TITLE
Footer redesign en finetuning styling linklijsten

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#936]
**Aanleiding**
Geconstateerd in #895; de footer is niet als component in de toolkit beschikbaar, terwijl deze wel specifieke styling krijgt.

**Werkzaamheden**
Component styling aanpassen zie afb. 
Externe links aan inhoud toevoegen. (kan het icoon wel zwart worden? ) 
Inhoud wijzigingen die totale range aan mogelijkheden weergeven
Verplaatsen naar patroon onder voorbeeldpagina's
 
 **Ontwerp**
![image](https://user-images.githubusercontent.com/36912722/120640106-61bca180-c472-11eb-8e9d-f461b66ec593.png)
![image](https://user-images.githubusercontent.com/36912722/120640121-65e8bf00-c472-11eb-9c39-255011ed9630.png)
 

**Testen**
Visuele controle -> Responsive, Zoom 400%
Interactie gedrag testen meerdere browsers
Voorbeeldpagina's nalopen kijken of er onwenselijke veranderingen zijn

**Acceptatiecriteria**
Controle/ Approval door Reporter/schrijver van Story
Technische keuze consistentie Toolkit bewaakt door Info Projects .

**Comment by MichielDHVD** [comment]
Alle toepassingen gebruiken dezelfde opzet alleen soms in verschillende volgorde gek genoeg. Geen probleem om dat de standaardiseren. 

Grootste verschillen zijn dat er soms kopjes en links zijn omgedraaid. Of dat er een een kopje met uitleg ontbreekt. 
Maar dit wordt allemaal bepaald in het cms. 

@gofix @PieterVerheij   Jullie hebben toegang tot het CMS toch? Het is immers jullie cms. Want dan kan dat meegenomen worden in het vast stellen van de footer als component. 

Wat afbeeldingen om de kleine verschillen aan te duiden: 

<img width="943" alt="Screenshot 2020-12-11 at 11 55 39" src="https://user-images.githubusercontent.com/36912722/101896601-84e45380-3ba9-11eb-9c42-99fe9deddf8d.png">
<img width="931" alt="Screenshot 2020-12-11 at 11 55 55" src="https://user-images.githubusercontent.com/36912722/101896605-86158080-3ba9-11eb-8249-a4b0da3ab40f.png">
<img width="1044" alt="Screenshot 2020-12-11 at 12 05 14" src="https://user-images.githubusercontent.com/36912722/101896609-8746ad80-3ba9-11eb-9407-cd233df2f0c7.png">

**Comment by MichielDHVD** [comment]
Deze gaat tijdelijk terug naar het backlog. Deze gaat een groter proces in om wat Footer standaarden vaststellen voordat we in de toolkit hier iets mee gaan doen.

**Comment by PieterVerheij** [comment]
@MichielDHVD Welke voorbeeldcontent zullen we in de footer plaatsen?

**Comment by MichielDHVD** [comment]
De tekst in de bovenste ontwerpen overnemen. Als Ux hebben we gekozen nep-content te kiezen om het algemeen te houden. Dus de footer komt er uit te zien als bijgevoegde bovenstaande ontwerpen

**Comment by PieterVerheij** [comment]
@bramhoosemans @MichielDHVD Wat zijn de verticale marges (van H2, tekst en linklist)?

**Comment by MichielDHVD** [comment]
@PieterVerheij 16px

**Comment by MichielDHVD** [comment]
@PieterVerheij heb toch nog iets gevonden. 

De lijn aan de bovenkant van de header is #bcbebd in de afbeelding in de Jira ticket is het #CCC

We hebben recentelijk een  story gemaakt waar we alle scheidingslijnen gelijk hebben getrokken. Zonde om het hier meteen weer los te laten.

**Comment by gofix** [comment]
@MichielDHVD klopt het dat link-lijsten ook in de highlight box die ruimere onderlinge verticale spatiering moeten krijgen?

Zie 
![image](https://user-images.githubusercontent.com/2689559/127894879-d57fe933-c719-45fd-8425-431ef91dc2a5.png)

NB: @PieterVerheij heeft ook gelijk opgelost dat de niet-werkende iconen op de gele en grijze versie van de web component ... well ... nu weer werken dus.

**Comment by PieterVerheij** [comment]
Als ik in het ontwerp kijk, moet er altijd een ruimte van 16px zijn: https://github.com/dso-toolkit/dso-toolkit/issues/1159#issue-910409972

![image](https://user-images.githubusercontent.com/25430835/127978312-2049acaf-3fd6-4226-a31d-d6d077c214d3.png)

**Comment by gofix** [comment]
@MichielDHVD resultaten van deze noeste arbeid te bewonderen op:

Footer, in fractal:
https://dso-toolkit.nl/_936.Footer-Redesign/components/preview/footer.html

Storybook (Css, linklijst op highlihtbox)
https://css.dso-toolkit.nl/_936.Footer-Redesign/iframe.html?id=link-list--in-highlight-box&args=&viewMode=story

Storybook (Css, linklijst op footer)
https://css.dso-toolkit.nl/_936.Footer-Redesign/iframe.html?id=link-list--in-footer&args=&viewMode=story

**Comment by bramhoosemans** [comment]
Check. Footer ziet erg goed uit.
