### ISSUE TITLE
Web component: Progress indicator

### ISSUE THREAD

**Issue by PieterVerheij** [dso-toolkit/dso-toolkit#939]
### `<dso-progress-indicator>` 

Component aanmaken in packages/core/src/components/progress-indicator

packages/core/src/components/progress-indicator/progress-indicator.tsx

packages/core/src/components/progress-indicator/progress-indicator.scss

Tag <dso-progress-indicator> toevoegen in packages/core/src/index.html

Tag <dso-progress-indicator> toevoegen in packages/dso-toolkit/compontent/progress-indicator/progress-indicator.njk

@import stylesheet verhuizen van packages/dso-toolkit/src/styles/dso.scss naar packages/styling/components.scss

styleheet verhuizen van packages/dso-toolkit/src/styles/components/_progress-indicator.scss naar packages/styling/components/progress-indicator.scss

**Comment by tfrijsewijk** [comment]
@bramhoosemans @MichielDHVD Kunnen jullie meekijken?
* https://dso-toolkit.nl/_939-v2-progress-indicator/components/detail/progress-indicator.html
* https://css.dso-toolkit.nl/_939-v2-progress-indicator/?path=/story/progress-indicator--spinner-small
* https://core.dso-toolkit.nl/_939-v2-progress-indicator/?path=/story/progress-indicator--spinner-small
* https://react.dso-toolkit.nl/_939-v2-progress-indicator/?path=/story/progress-indicator--spinner-small

De test is vooral.. Werkt het nog zoals het eerst werkte ;-)

**Comment by bramhoosemans** [comment]
Ziet er visueel goed uit.

Neem aan dat je de accessibility melding 'ARIA progressbar nodes must have an accessible name' zelf al had gespot?

**Comment by gofix** [comment]
Daar gaat al een ander issue over: https://github.com/dso-toolkit/dso-toolkit/issues/1211.

**Comment by MichielDHVD** [comment]
Ik had in slack gereageerd, ziet er prima uit. Zal in de toekomst ook op github reageren, de beste plek ervoor.
