### ISSUE TITLE
Web component: Tooltip

### ISSUE THREAD

**Issue by PieterVerheij** [dso-toolkit/dso-toolkit#940]
### `<dso-tooltip>`
Component aanmaken in packages/core/src/components/tooltip

packages/core/src/components/progress-indicator/tooltip.tsx

packages/core/src/components/progress-indicator/tooltip.scss

Tag toevoegen in packages/core/src/index.html

Tag toevoegen in packages/dso-toolkit/compontent/tooltip/tooltip.njk

@import stylesheet verhuizen van packages/dso-toolkit/src/styles/dso.scss naar packages/styling/components.scss

styleheet verhuizen van packages/dso-toolkit/src/styles/components/_tooltip.scss naar packages/styling/components/tooltip.scss

**Comment by tfrijsewijk** [comment]
Inspiratie:
* https://www.webcomponents.org/element/@polymer/paper-tooltip/demo/demo/index.html
* https://www.carbondesignsystem.com/components/tooltip/usage/#live-demo
