### ISSUE TITLE
Documentatie toolkit opsplitsen in losse pagina's (Productowner, Ontwerper & Developer)

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#945]

**Comment by gofix** [comment]
Zoals zojuist besproken op de refinement, is het wenselijk dat in het stukje 'voor de developer' wat korte tekst en uitleg gegeven wordt over wat de raketjes betekenen, en hoe dat resulteert in de andere tabbladindeling (dus: dat je dan 'Usage' en 'Markup' los krijgt),

**Comment by gofix** [comment]
Zo dan? https://dso-toolkit.nl/_945-Documentatie-opsplitsen/docs/voor-developers.html

**Comment by MichielDHVD** [comment]
Doorzetten zou ik zeggen

**Comment by tfrijsewijk** [comment]
Lokaal gemerged ivm merge conflicts
