### ISSUE TITLE
Dubbele previews bij componenten labelen met type

### ISSUE THREAD

**Issue by gofix** [dso-toolkit/dso-toolkit#947]
Op preview pagina's van webcomponents, of van componenten die webcomponents bevatten, wordt alles dubbel getoond (met een `<hr>` ertussen). Die dubbeling is op zich bewust aangebracht, om in het visueel regressietesten screenshots te kunnen maken van zowel de situatie bij traditionele markup, als bij markup zoals die tot leven zal komen als de browser de webcomponent in leven brengt. op www.dso-toolkit.nl is deze dubbele weergave echter niet gewenst.

**Comment by tfrijsewijk** [comment]
De bug is omgezet naar een feature en gelabelled. Het concept van Fractal met PJAX en statisch gegenereerde sites maakt het voor nu te tricky dit te voorkomen.

Een alternatief kan zijn om post-percy de dubbeling met Cheerio en een buildstap te verwijderen of clientside scripting. Dat laatste ben ik niet zo'n fan van omdat we in een iframe leven waar we de productieomgeving nabootsen.
