### ISSUE TITLE
Heading in Alert altijd dezelfde styling meegeven

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#952]
Styling van headings in Alerts overschrijven; Asap SemiBold 16px #191919, zonder marges (?).

![screencapture-int12-omgevingswet-overheid-nl-mijnomgevingsloket-open-5f32493e-959a-42a2-be6f-f4c9ce9ab0b9-0-details-2020-12-18-14_40_17](https://user-images.githubusercontent.com/598735/102624056-c5ad1100-4143-11eb-88ba-41702de6302d.png)

**Comment by PieterVerheij** [comment]
@bramhoosemans 
https://www.dso-toolkit.nl/_952.Heading-in-Alert-altijd-dezelfde-styling-meegeven/components/preview/alert.html

**Comment by bramhoosemans** [comment]
Ziet er goed uit.

**Comment by MichielDHVD** [comment]
Stiekem best blij mee, zorgt ervoor dat als mensen in het cms headings in een alert zetten ( Is namelijk wel eens gebeurd) dat het er nog steeds consistent uit ziet. 

Top!
