### ISSUE TITLE
Dropdown voorbeeld met `btn-default` button gebruikt verkeerde markup.

### ISSUE THREAD

**Issue by PieterVerheij** [dso-toolkit/dso-toolkit#957]
Geconstateerd i.k.v. #894 :
De markup van de knop is oud en niet conform de markup voorgeschreven zoals https://www.dso-
toolkit.nl/master/components/detail/buttons.html.

Extra aandachtspunt: 
De focus state van de default button bevat een ongewenste underline.

**Comment by gofix** [comment]
Klopt het wel dat de knop zelf helemaal geen hover styling meer heeft?

https://dso-toolkit.nl/_894.Dropdown-button-ook-als-tertiaire-button-kunnen-inzetten/components/detail/dropdown-button.html

NB: @daverhelst is in kader van #895 ook nog bezig met het finetunen van welke links nu eigenlijk wel en niet een underline krijgen bij hover. Ik twijfel over deze...

**Comment by bramhoosemans** [comment]
> Klopt het wel dat de knop zelf helemaal geen hover styling meer heeft (@PieterVerheij, @bramhoosemans) ?

Nee. In de dropdown button zijn nu twee button-vormen opgenomen (secundaire en tertiaire button). Het is de bedoeling dat de styling/state van de buttons niet veranderd ten opzichte van 'normale' buttons.

**Comment by PieterVerheij** [comment]
@bramhoosemans 
![image](https://user-images.githubusercontent.com/25430835/103873482-250d9980-50d0-11eb-8f3c-530208f62969.png)

In de `open` stand had hij een donkerdere hover kleur.
