### ISSUE TITLE
Inventarisatie link states

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#960]
Vervolg op https://github.com/dso-toolkit/dso-toolkit/issues/895; hierin hebben we de default styling van tekstlinks gelijkgetrokken (binnen en buiten `.dso-rich-content`). 

Er zijn echter ook een tal van uitzonderingen, zoals gebruik in accordion, footer, tabs, etc. In het kader van dit issue hier een inventarisatie van maken en gewenste implementatie van link states bespreken.

**Comment by MichielDHVD** [comment]
Bij deze de inventarisatie van de links:

https://docs.google.com/spreadsheets/d/1wQqn6V10empzz_LcOSfWdjqh8BM3Q-TZXaGT9MIUoek/edit?usp=sharing

Als er vragen zijn stel ze vooral.  @daverhelst  en @bramhoosemans jullie waren veel betrokken bij het vorige issue dus miss interessant als jullie ook even kijken .

**Comment by bramhoosemans** [comment]
Ik heb mijn opmerkingen toegevoegd in de spreadsheet.

**Comment by MichielDHVD** [comment]
Dit issue kan wordt gesloten de volgende issues zijn er uit voortgekomen. 

https://github.com/dso-toolkit/dso-toolkit/issues/1009
https://github.com/dso-toolkit/dso-toolkit/issues/1008
