### ISSUE TITLE
Dropdown menu met uitlijning links én rechts toevoegen

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#961]
Vervolg op https://github.com/dso-toolkit/dso-toolkit/issues/894. Hierin hebben we de tertiaire button toegevoegd als voorbeeld in de DSO Toolkit. Met de refinement 07-01-2021 hebben we de volgende toevoegingen besproken:

- [x] Open state verbeteren door pijltjes om te draaien;
- [x] Primaire button toevoegen als voorbeeld;
- [x] Dropdown menu met uitlijning links én rechts toevoegen als voorbeeld.

![Schermafbeelding 2021-02-17 om 13 27 37](https://user-images.githubusercontent.com/598735/108204313-ef72bc00-7123-11eb-973e-467ffb8b0d43.png)

**Comment by bramhoosemans** [comment]
Het lijkt erop dat de eerste twee toevoegingen reeds zijn doorgevoerd in https://dso-toolkit.nl/18.0.0/components/detail/dropdown-button.html.

Dan blijft over de positionering van het menu. Het is wenselijk om deze zowel links- als rechts uit te kunnen lijnen (zie afbeelding).

ps. zouden we dropdowns, tooltips, etc. niet automagisch kunnen uitlijnen met Popper.js? (https://popper.js.org/)

**Comment by bramhoosemans** [comment]
Extra class om uitlijning van het menu link of rechts te forceren.

**Comment by PieterVerheij** [comment]
Voorbeelden met rechter uitlijning dorpdown toegevoegd (onderaan pagina).
https://www.dso-toolkit.nl/_961.Dropdown-menu-met-uitlijning-links-en-rechts/components/detail/dropdown-button.html

**Comment by bramhoosemans** [comment]
Top. Ziet er goed uit.

Wat me (nu pas) opvalt is dat het icoon niet zichtbaar is bij de :focus styling van de default button. Deze blijft groen. Dit is niet het geval bij het button component.
![Schermafbeelding 2021-03-02 om 10 17 43](https://user-images.githubusercontent.com/598735/109626330-b33a5500-7b40-11eb-872d-4f5a13400ce3.png)

**Comment by PieterVerheij** [comment]
Woopsie: fixed
