### ISSUE TITLE
Inventarisatie gebruik dropshadow

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#963]
Waar gebruiken we welke dropshadows? Het vermoeden is dat er (te)veel verschillende dropshadow styling wordt toegepast. In het kader van dit issue inventariseren en gewenste implementatie bespreken.

**Comment by gofix** [comment]
In sommige andere tickets lopen we hier al tegenaan, zoals bv. #929. Daarin zijn nu aan elkaar gelijkgetrokken:
`$dso-whitebox-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);`
`$dso-highlight-box-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);`
we zouden natuurlijk een `$dso-default-box-shadow` kunnen introduceren...
