### ISSUE TITLE
Date Picker focus styling verbeteren

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#964]
In de Date Picker hebben we custom focus styling toegepast omdat het er anders heel vreemd uit gaat zien. Zie screenshot hieronder. Dit was echter niet meegenomen in het ontwerp van https://github.com/dso-toolkit/dso-toolkit/issues/877.

Om er zeker van te zijn dat we in alle gevallen voldoen aan het contrast ratio is hier een apart issue voor aangemaakt.

![image](https://user-images.githubusercontent.com/598735/104031430-017c4900-51cd-11eb-9428-cf67bcef3c05.png)

Eerste idee geschetst tijdens bespreken:
![Schermafbeelding 2021-01-08 om 16 18 39](https://user-images.githubusercontent.com/598735/104031584-2e306080-51cd-11eb-8801-89ba48087fa0.png)

**Comment by bramhoosemans** [comment]
@PieterVerheij zie hier de specificaties voor de focus styling: [Date picker.zip](https://github.com/dso-toolkit/dso-toolkit/files/5836152/Date.picker.zip)

![datepicker](https://user-images.githubusercontent.com/598735/105041313-1ecdd480-5a63-11eb-9dd2-ec1dfca08609.png)

**Comment by PieterVerheij** [comment]
https://www.dso-toolkit.nl/_964.Date-Picker-focus-styling-verbeteren/components/detail/date-picker.html

**Comment by PieterVerheij** [comment]
1 bevinding: disabled mag natuurlijk niet hoveren.
