### ISSUE TITLE
Refactoring voorbeeldtemplates : Wizard stap 4 (Resultaat)

### ISSUE THREAD

**Issue by PieterVerheij** [dso-toolkit/dso-toolkit#967]
De markup in https://www.dso-toolkit.nl/master/components/detail/wizard-stap-4.html is niet correct:
- tussen de `main` en paragrafen staat geen `.row`
- de tekst staat niet in een `dso-rich-content`
- tussen paragrafen staat een `<div class="clearfix"></div>`
- in de tekst staat wel een `.row` met daarin een `.col` met daarin weer een `.dso-form-buttons`

```
       <div class="row">
          <div class="col-md-12">
            <div class="dso-form-buttons">
              <div class="dso-aside">
                <button type="button" class="btn btn-link btn-align">
                  <dso-icon icon="chevron-left" class="hydrated"></dso-icon><span>Vorige stap</span>
                </button>
              </div>
              <button type="button" class="btn btn-primary pull-right"><span>Naar aanvragen</span></button>
            </div>
          </div>
        </div>

```

**Comment by daverhelst** [comment]
Ik zie dat geen enkele wizard pagina een `.row` na de `main` heeft staan. Zal ik ze bij allemaal maar toevoegen?

**Comment by MichielDHVD** [comment]
Is wel een "eerlijker" beeld van de margins wanneer rows en main gebruikt worden volgens de toolkit
