### ISSUE TITLE
Definition-list (in accordion) geen padding bij lange dt

### ISSUE THREAD

**Issue by bramhoosemans** [dso-toolkit/dso-toolkit#979]
Het lijkt erop dat als het label (dt) over meerdere regels valt de padding van de section body wordt genegeerd. Gespot op macOS Big Sur met Chrome Versie 88.0.4324.96 (actuele versie).

![Schermafbeelding 2021-01-21 om 16 07 12](https://user-images.githubusercontent.com/598735/105369583-fda3ea00-5c02-11eb-99f6-690f25e33d58.png)

**Comment by PieterVerheij** [comment]
Het is niet gerelateerd aan macOS en ook de gewone definition list te reproduceren:
![image](https://user-images.githubusercontent.com/25430835/105488673-4797d900-5cb2-11eb-9be9-e62263cd1cb2.png)
