### ISSUE TITLE
Buttons wrappen niet waardoor deze buiten elementen vallen

### ISSUE THREAD

**Issue by MichielDHVD** [dso-toolkit/dso-toolkit#990]
Buttons moeten over meerdere lijnen kunnen lopen anders vallen deze buiten container elementen of verdwijnen onder andere elementen.

**Fout situatie:**
![image](https://user-images.githubusercontent.com/36912722/106128667-dba8eb00-615f-11eb-8cb3-d2e4aff5c417.png)

**Gewenste situatie:**
![image](https://user-images.githubusercontent.com/36912722/106128854-0a26c600-6160-11eb-953c-e99dc7a92b1d.png)

**Nog een voorbeeld:**
![image](https://user-images.githubusercontent.com/36912722/106128972-2296e080-6160-11eb-9e6c-bb22bdecc8a8.png)
![image](https://user-images.githubusercontent.com/36912722/106128999-288cc180-6160-11eb-8ede-89861fa34162.png)

**Comment by gofix** [comment]
Ik denk dat het zinvol is als we op de buttons pagina dan ook wel wat voorbeelden met 'lange teksten' opnemen.
