### ISSUE TITLE
Refactoring voorbeeldtemplates : Bijstellingen styling en markup

### ISSUE THREAD

**Issue by PieterVerheij** [dso-toolkit/dso-toolkit#993]
In de voorbeeldpagina's is het gebruik van  `.container`, `.row` en `.cols-xx-xx` niet consequent doorgevoerd. Omdat het voorbeeldpagina's zijn voor de implementatoren, is het juist hier van belang dat de markup juist is.

**Comment by MichielDHVD** [comment]
Komt voor een deel overeen met dit issue https://github.com/dso-toolkit/dso-toolkit/issues/967 

Daarin heb ik nog een vraag gesteld over wat nu de juiste algemene markup is.

**Comment by PieterVerheij** [comment]
Er lopen nu een paar issues over dit onderwerp langs elkaar heen. Ik stel voor dit als verzamel-issue te gebruiken. Het betreft:
https://github.com/dso-toolkit/dso-toolkit/issues/826
https://github.com/dso-toolkit/dso-toolkit/issues/845
https://github.com/dso-toolkit/dso-toolkit/issues/967
https://github.com/dso-toolkit/dso-toolkit/issues/987

**Comment by gofix** [comment]
Als het over paginabrede stroken gaat, moet altijd `.col-xs-12` worden toegepast.

**Comment by PieterVerheij** [comment]
https://percy.io/dso-toolkit/dso-toolkit/builds/8991993/changed/509814770

alle content in 1 row, tenzij nodig voor responsive gedrag
content schuift soms tegen elkaar aan

verzoeken:
- group-static verticale marge (apart issue?)
- ruimte tussen knop 'Ergens anders indienen' en eerste 'hr' (moet knop trouwens niet anders vormgegeven?)
- ontbrekende sluit lijn
- kolombreedte (apart issue?)

verzoeken wijzigen:
- group-static verticale marge (apart issue?)
- kolombreedte (apart issue?)

verzoeken wijzigen bevoegd gezag:
- group-static verticale marge (apart issue?)
- kolombreedte (apart issue?)

omgevingsoverleg
- ruimte tussen highlight-box en definition-list te weinig

verzoek indienen:
- ruimte tussen accordion, confirm en dso-form-buttons (accodrion heeft nu een margin-bottom van 32px)

Wizard stap 2:
- drop down button (komt wat anders voor)
- dso-justify-form-groups geintroduceerd

Wizard stap 3:
- highlight-box is "misbruikt" voor grijze achtergrond searchbar
- geen ruimte tussen de searchbar en formulier (in een responsive row)
- markup correctie voor de legends

Er zitten margin correcties op dso-rich-content en accordion.

**Comment by PieterVerheij** [comment]
Percy build na aanpassingen:
- markup correcties verzoeken en wizard
- margins hr
- margins form static
- streepje dl + dl
- margin onder highlightbox
- margins heading in legend op 0

https://percy.io/dso-toolkit/dso-toolkit/builds/9038837/changed/512462647

**Comment by bramhoosemans** [comment]
Eerste reactie:
- Form static: waarom margin boven en onder, en niet gelijk aan definition list met margin bottom van 16px?
- Form static: paragrafen in dso-field-container staan slechts 8px van elkaar. Hier lijkt ook iets niet goed te gaan met uitlijning t.o.v. de tertiaire button. Wel of geen `<p>` gebruiken?
- Streepje dl + dl: volgens mij mag de padding en margin vergroot worden naar 32px. Zo ontstaat er een duidelijke scheiding tussen meerdere definition lists.
- Margin onder highlightbox: ik zie bijv. In de landingspagina of voorbeeld met banner dat er nog een `<br>` wordt toegepast na de highlightbox. Is dat wenselijk? Of margin-bottom verhogen naar 32px?
- Preview Omgevingsoverleg: graag rekening houden met vaste toelichting bij vraag. De huidige implementatie met highlightbox onder de vraag is niet gewenst.
- Preview Wizard stap 3: Headings aanpassen ‘Mijn activiteiten’ = H3, en filters + ‘aantal activiteiten’ = H4.
- Margin onder tabs toevoegen hadden we volgens mij ook benoemd (mag 32px). Of opnemen in een apart issue?

**Comment by PieterVerheij** [comment]
- Form static: waarom margin boven en onder, en niet gelijk aan definition list met margin bottom van 16px?
Group static gaat mee in de flow van de andere form-groups: die hebben een margin aan de bovenkant. Als je alleen een margin-bottom zou gebruiken, dan zou een group-satic te dicht op zijn voorganger staan.
![image](https://user-images.githubusercontent.com/25430835/109517706-d665f580-7aa9-11eb-8e85-fc46a9e2fb19.png)

- Form static: paragrafen in dso-field-container staan slechts 8px van elkaar. Hier lijkt ook iets niet goed te gaan met uitlijning t.o.v. de tertiaire button. Wel of geen <p> gebruiken?
Bij voorkeur niet, maar dat is afhankelijk van wat er in de field-container staat. Invoer in een textarea kan eventueel een <p> opleveren tenzij de implementator die escapet.

- Streepje dl + dl: volgens mij mag de padding en margin vergroot worden naar 32px. Zo ontstaat er een duidelijke scheiding tussen meerdere definition lists.
aangepast

- Margin onder highlightbox: ik zie bijv. In de landingspagina of voorbeeld met banner dat er nog een <br> wordt toegepast na de highlightbox. Is dat wenselijk? Of margin-bottom verhogen naar 32px?
Die <br>s waren door het net geglipt. Maar misschien dat inderdaad highlightbox en ook vaste toelichting een margin-bottom: 32px moeten krijgen.

- Preview Omgevingsoverleg: graag rekening houden met vaste toelichting bij vraag. De huidige implementatie met highlightbox onder de vraag is niet gewenst.
aangepast

- Preview Wizard stap 3: Headings aanpassen ‘Mijn activiteiten’ = H3, en filters + ‘aantal activiteiten’ = H4.
aangepast

- Margin onder tabs toevoegen hadden we volgens mij ook benoemd (mag 32px). Of opnemen in een apart issue?
ik maak wel een los issue aan, dit ticket barst al uit zijn voegen ;-)

**Comment by PieterVerheij** [comment]
@bramhoosemans hier kunnen we nog wel wat lucht gebruiken
![image](https://user-images.githubusercontent.com/25430835/109521930-1a5af980-7aae-11eb-93b3-6c1e1030a983.png)

**Comment by bramhoosemans** [comment]
@PieterVerheij De vaste toelichting mag in de `dso-label-container` worden geplaatst. Het is immers een toelichting op de vraag.

Dat neemt niet weg dat we op één of andere manier ruimte tussen de `fieldset` en de `dl` moeten creëren.. Wat daar de beste oplossing is weet ik niet.

**Comment by PieterVerheij** [comment]
Correctie markup rows: Pagina met banner (br's verwijderd)
packages/dso-toolkit/components/Voorbeelden/pagina-met-banner/pagina-met-banner.njk

Correctie markup rows: Samenwerken (br's verwijderd)
packages/dso-toolkit/components/Voorbeelden/samenwerken.njk

Nieuwe pagina Verzoeken indienen #826
packages/dso-toolkit/components/Voorbeelden/verzoek-indienen/omgevingsoverleg.config.yml
packages/dso-toolkit/components/Voorbeelden/verzoek-indienen/omgevingsoverleg.njk
packages/dso-toolkit/components/Voorbeelden/verzoek-indienen/verzoeken-indienen.config.yml
packages/dso-toolkit/components/Voorbeelden/verzoek-indienen/verzoeken-indienen.njk
packages/dso-toolkit/components/Voorbeelden/verzoek-indienen/verzoeken-wijzigen-bevoegd-gezag.config.yml
packages/dso-toolkit/components/Voorbeelden/verzoek-indienen/verzoeken-wijzigen-bevoegd-gezag.njk
packages/dso-toolkit/components/Voorbeelden/verzoek-indienen/verzoeken-wijzigen.config.yml
packages/dso-toolkit/components/Voorbeelden/verzoek-indienen/verzoeken-wijzigen.njk
packages/dso-toolkit/components/Voorbeelden/verzoek-indienen/verzoeken.config.yml
packages/dso-toolkit/components/Voorbeelden/verzoek-indienen/verzoeken.njk

Refactoring voorbeeldtemplates : Wizard stap 2 (Locatie) #845
packages/dso-toolkit/components/Voorbeelden/wizard/wizard-stap-2.config.yml
packages/dso-toolkit/components/Voorbeelden/wizard/wizard-stap-2.njk

Refactoring voorbeeldtemplates : Wizard Stap 3 (Kies activiteiten) #787
packages/dso-toolkit/components/Voorbeelden/wizard/wizard-stap-3.config.yml
packages/dso-toolkit/components/Voorbeelden/wizard/wizard-stap-3.njk

Refactoring voorbeeldtemplates : Wizard stap 4 (Resultaat) #967
packages/dso-toolkit/components/Voorbeelden/wizard/wizard-stap-4.njk

Correctie markup rows: Margin onder accordion
packages/dso-toolkit/src/styles/components/_accordion.scss

Correctie markup rows: Ruimte tussen dl's
packages/dso-toolkit/src/styles/components/_definition-list.scss

Verzameling aanpassingen nog uitzoeken
- .dso-justify-form-groups
- headings in legends
-- margins dso-form-button
-- margins form-group (ook static en edit)
-- margins elementen na form-group
packages/dso-toolkit/src/styles/components/_form.scss

Ruimte rond hr's
packages/dso-toolkit/src/styles/components/_rich-content.scss
packages/dso-toolkit/src/styles/mixins/_typography.scss
packages/styling/mixins/rich-content.scss

Onnodige clear fix steps weggehaald
packages/dso-toolkit/src/styles/components/_steps.scss

Correctie markup rows:
dso-rich-content standaard margin-bottom
dso-featured margin-bottom specifieker
packages/dso-toolkit/src/styles/mixins/_grid.scss

Margin onder highlightbox
packages/styling/components/highlight-box.scss

Units voor verticale marge
packages/styling/variables/units.scss

___________________________________________________________
snap ik niet: 
components/Componenten/dropdown-button/dropdown-button.config.js (#894 ?)
components/Voorbeelden/wizard/wizard-stap-2.njk (doubleure: staat ook in packages/dso-toolkit/components/Voorbeelden/wizard/wizard-stap-2.njk)
