### ISSUE TITLE
Verplichting bij een confirm zie je nergens aan af

### ISSUE THREAD

**Issue by gofix** [dso-toolkit/dso-toolkit#995]
![image](https://user-images.githubusercontent.com/2689559/107012633-90af5900-6799-11eb-87d6-bb00c9387b4e.png)

... vergelijk met werkvormen waar bij het label dan tenminste altijd een klein, schuin 'verplicht' als indicatie staat:

![image](https://user-images.githubusercontent.com/2689559/107012796-c9e7c900-6799-11eb-8c22-68653ba51f27.png)

(overigens, best opvallend dat van 'group input' niet een 'required' voorbeeldvariant gegeven wordt, maar dat dat alleen in sommige andere varianten naar voren komt)

**Comment by bramhoosemans** [comment]
@gofix Confirm is wel een uniek formulier element dat, volgens mij, altijd verplicht is. Een confirm selectievakje wordt namelijk altijd toegepast in combinatie met een submit button. Iets wat we in documentatie goed moeten vastleggen.

> (overigens, best opvallend dat van 'group input' niet een 'required' voorbeeldvariant gegeven wordt, maar dat dat alleen in sommige andere varianten naar voren komt)

Het lijkt me goed om die (group input required) ook specifiek 'los' te benoemen.

**Comment by bramhoosemans** [comment]
https://www.w3.org/WAI/WCAG21/Techniques/general/G155
